### ISSUE TITLE
controller manager pod crash loops if route table is nil 

### ISSUE THREAD

**Issue by BrandonWeng** [kubernetes/kubernetes#100271]
#### What happened:
Deploying a controller manager pod with `--cluster-cidr=.../16` and `--allocate-node-cidrs=true` in a cluster running Calico causes the controller manager pod to crash loop. This seems to only be a problem when running on Azure - the same configuration deployed to AWS didn't have any problems. 

```
I0313 03:05:34.558913       1 node_lifecycle_controller.go:1464] Initializing eviction metric for zone:
I0313 03:05:34.560444       1 node_lifecycle_controller.go:1280] Controller detected that zone  is now in state .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x210a9f0]

goroutine 399 [running]:
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*delayedRouteUpdater).updateRoutes(0xc000c479e0)
	/workspace/anago-v1.16.12-rc.1.1+29e53413f6c4f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_routes.go:148 +0x1d0
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*delayedRouteUpdater).run(0xc000c479e0)
	/workspace/anago-v1.16.12-rc.1.1+29e53413f6c4f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_routes.go:97 +0x2b
created by k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).InitializeCloudFromConfig
	/workspace/anago-v1.16.12-rc.1.1+29e53413f6c4f5/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure.go:515 +0x10c0
```

It seems like routeTable is nil here https://github.com/kubernetes/kubernetes/blob/v1.16.12/staging/src/k8s.io/legacy-cloud-providers/azure/azure_routes.go#L148

If the routeTableName is not set, the result will return a nil and cause a seg fault: https://github.com/kubernetes/kubernetes/blob/v1.16.12/staging/src/k8s.io/legacy-cloud-providers/azure/azure_wrap.go#L108

From AKS traffic manager:
`Proxy GET /subscriptions/.../resourceGroups/.../providers/Microsoft.Network/routeTables/?api-version=2019-06-01`

#### What you expected to happen:
pod controller manager should terminate gracefully with the error message instead of crash looping due to segfault. 

#### How to reproduce it (as minimally and precisely as possible):
 - In a cluster running Calico CNI, deploy controller manager pod with `--cluster-cidr=.../16` and `--allocate-node-cidrs=true` 
 - Do not set `routeTableName` in the cloud config 
 - Observe controller manager pod crashloop

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.12", GitCommit:"17c50ce2d686f4346924935063e3a431360e0db7", GitTreeState:"clean", BuildDate:"2020-06-26T03:41:29Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.12", GitCommit:"17c50ce2d686f4346924935063e3a431360e0db7", GitTreeState:"clean", BuildDate:"2020-06-26T03:33:27Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Azure 
- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug): 
- Others:

**Comment by dcbw** [comment]
/triage accepted
Looks legit; present in 1.21 and earlier, probably introduced by https://github.com/kubernetes/kubernetes/pull/88209

**Comment by benc-uk** [comment]
Hitting this now
