### ISSUE TITLE
Unit tests timing out

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#10149]
When I run `hack/test-go.sh`, it is failing with a timeout in  `github.com/GoogleCloudPlatform/kubernetes/pkg/controller`; I believe in TestSyncReplicationControllerDoesNothing.

Has anyone seen this?

```
panic: test timed out after 2m0s

goroutine 23 [running]:
testing.func·008()
        /usr/local/go/src/testing/testing.go:681 +0x12f
created by time.goFunc
        /usr/local/go/src/time/sleep.go:129 +0x4b

goroutine 1 [chan receive, 2 minutes]:
testing.RunTests(0xc82148, 0x1086280, 0x14, 0x14, 0x1)
        /usr/local/go/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc20803e7d0, 0x10aa2c0)
        /usr/local/go/src/testing/testing.go:485 +0x6c
main.main()
        github.com/GoogleCloudPlatform/kubernetes/pkg/controller/_test/_testmain.go:90 +0x1d5

goroutine 7 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x10a1ee0)
        /home/justinsb/github/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
        /home/justinsb/github/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 11 [select]:
net/http.(*persistConn).roundTrip(0xc20805a580, 0xc2080f02c0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1082 +0x7ad
net/http.(*Transport).RoundTrip(0xc208072120, 0xc208133790, 0xa, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:235 +0x558
github.com/GoogleCloudPlatform/kubernetes/pkg/client.(*userAgentRoundTripper).RoundTrip(0xc20800bac0, 0xc208133790, 0xc2080f67e0, 0x0, 0x0)
        /home/justinsb/github/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/transport.go:42 +0x134
net/http.send(0xc2081336c0, 0x7f805146b258, 0xc20800bac0, 0x4d, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:219 +0x4fc
net/http.(*Client).send(0xc2080c65a0, 0xc2081336c0, 0x4d, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:142 +0x15b
net/http.(*Client).doFollowingRedirects(0xc2080c65a0, 0xc2081336c0, 0xc822f0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:367 +0xb25
net/http.(*Client).Do(0xc2080c65a0, 0xc2081336c0, 0xc20803f360, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:177 +0x192
github.com/GoogleCloudPlatform/kubernetes/pkg/client.(*Request).request(0xc208130fc0, 0xc208123930, 0x0, 0x0)
        /home/justinsb/github/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/request.go:707 +0x3b5
github.com/GoogleCloudPlatform/kubernetes/pkg/client.(*Request).Do(0xc208130fc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/justinsb/github/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/request.go:748 +0xec
github.com/GoogleCloudPlatform/kubernetes/pkg/client.(*replicationControllers).Update(0xc20800bb80, 0xc2080c4460, 0xc2080c4540, 0x0, 0x0)
        /home/justinsb/github/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/replication_controllers.go:76 +0x145
github.com/GoogleCloudPlatform/kubernetes/pkg/controller.updateReplicaCount(0x7f805146b998, 0xc20800bb80, 0x0, 0x0, 0x7ffdf60ec1be, 0x7, 0xb15b50, 0x6, 0x0, 0x0, ...)
        /home/justinsb/github/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/controller/controller_utils.go:325 +0x405
github.com/GoogleCloudPlatform/kubernetes/pkg/controller.(*ReplicationManager).syncReplicationController(0xc208056100, 0xc2081345a0, 0xe, 0x0, 0x0)
        /home/justinsb/github/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/controller/replication_controller.go:388 +0x9bd
github.com/GoogleCloudPlatform/kubernetes/pkg/controller.TestSyncReplicationControllerDoesNothing(0xc2080726c0)
        /home/justinsb/github/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/controller/replication_controller_test.go:233 +0x294
testing.tRunner(0xc2080726c0, 0x1086280)
        /usr/local/go/src/testing/testing.go:447 +0xbf
created by testing.RunTests
        /usr/local/go/src/testing/testing.go:555 +0xa8b

goroutine 12 [runnable]:
github.com/GoogleCloudPlatform/kubernetes/pkg/util.(*tickRateLimiter).step(0xc20800baa0, 0x42a101)
        /home/justinsb/github/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:102 +0xfc
github.com/GoogleCloudPlatform/kubernetes/pkg/util.(*tickRateLimiter).run(0xc20800baa0)
        /home/justinsb/github/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:95 +0x28
created by github.com/GoogleCloudPlatform/kubernetes/pkg/util.NewTokenBucketRateLimiter
        /home/justinsb/github/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:50 +0x81

goroutine 13 [chan receive]:
github.com/GoogleCloudPlatform/kubernetes/pkg/watch.(*Broadcaster).loop(0xc2080c6810)
        /home/justinsb/github/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/watch/mux.go:159 +0x4e
created by github.com/GoogleCloudPlatform/kubernetes/pkg/watch.NewBroadcaster
        /home/justinsb/github/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/watch/mux.go:70 +0xf8

goroutine 14 [chan receive]:
github.com/GoogleCloudPlatform/kubernetes/pkg/client/record.func·003()
        /home/justinsb/github/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/record/event.go:214 +0x9e
created by github.com/GoogleCloudPlatform/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartEventWatcher
        /home/justinsb/github/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/record/event.go:226 +0x119

goroutine 15 [chan receive]:
github.com/GoogleCloudPlatform/kubernetes/pkg/client/record.func·003()
        /home/justinsb/github/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/record/event.go:214 +0x9e
created by github.com/GoogleCloudPlatform/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartEventWatcher
        /home/justinsb/github/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/record/event.go:226 +0x119

goroutine 22 [select]:
net/http.(*persistConn).writeLoop(0xc20805a580)
        /usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 21 [IO wait]:
net.(*pollDesc).Wait(0xc208095e20, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208095e20, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208095dc0, 0xc2080d5000, 0x1000, 0x1000, 0x0, 0x7f8051468df0, 0xc2080f03a0)
        /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20803a848, 0xc2080d5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7f805146ccd8, 0xc20803a848, 0xc20805a5d8, 0xc2080d5000, 0x1000, 0x1000, 0x7f8051457010, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2080ec4c0, 0xc2080d5000, 0x1000, 0x1000, 0xc207ffc57a, 0x0, 0x0)
        <autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc208035080)
        /usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc208035080, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20805a580)
        /usr/local/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xc9f
FAIL    github.com/GoogleCloudPlatform/kubernetes/pkg/controller        120.015s
```

**Comment by justinsb** [comment]
This doesn't happen for me when I run it in a Docker container on the same machine.  I'm guessing it is something like a port-conflict (?).  Reducing to P2 as it is something "on my machine".  We can close unless anyone thinks it could be a symptom of something important enough to try to track down.
