### ISSUE TITLE
[Failing Test] kubernetes.up e2e-up.sh

### ISSUE THREAD

**Issue by mkorbi** [kubernetes/kubernetes#102300]
#### Which jobs are failing:
- gce-os-master-alpha-features

#### Which test(s) are failing:
- kubernetes.Up

#### Since when has it been failing:
22.05.2021
- [first time test failed](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1395883924374163456)
- [in time of ticket creation latest test failing](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1397246201715232768)

#### Testgrid link:
[gce-os-master-alpha-features](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features&width=20)

#### Reason for failure:
```
 W0525 17:57:22.824] W0525 17:57:22.779180   11210 loader.go:221] Config not found: /workspace/.kube/config
W0525 17:57:22.825] 2021/05/25 17:57:22 process.go:155: Step './hack/e2e-internal/e2e-down.sh' finished in 5m58.313808136s
W0525 17:57:22.825] 2021/05/25 17:57:22 process.go:96: Saved XML output to /workspace/_artifacts/junit_runner.xml.
W0525 17:57:22.825] 2021/05/25 17:57:22 main.go:327: Something went wrong: starting e2e cluster: error during ./hack/e2e-internal/e2e-up.sh: exit status 2
W0525 17:57:22.825] Traceback (most recent call last):
W0525 17:57:22.826]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 723, in <module>
W0525 17:57:22.826]     main(parse_args())
W0525 17:57:22.826]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 569, in main
W0525 17:57:22.826]     mode.start(runner_args)
W0525 17:57:22.827]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 228, in start
W0525 17:57:22.827]     check_env(env, self.command, *args)
W0525 17:57:22.827]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 111, in check_env
W0525 17:57:22.827]     subprocess.check_call(cmd, env=env)
W0525 17:57:22.828]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W0525 17:57:22.828]     raise CalledProcessError(retcode, cmd)
W0525 17:57:22.829] subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--provider=gce', '--cluster=bootstrap-e2e', '--gcp-network=bootstrap-e2e', '--check-leaked-resources', '--extract=ci/latest-fast', '--extract-ci-bucket=k8s-release-dev', '--gcp-node-image=gci', '--gcp-zone=us-west1-b', '--runtime-config=api/all=true', '--test_args=--ginkgo.focus=\\[Feature:(ServiceAccountIssuerDiscovery|StorageVersionAPI|Audit|PodPreset|RunAsGroup|TTLAfterFinished|NodeLease|CSIServiceAccountToken|CSIStorageCapacity|GenericEphemeralVolume|DaemonSetUpdateSurge|CrossNamespacePodAffinity|SuspendJob)\\]|Networking --ginkgo.skip=\\[Feature:(SCTPConnectivity|Volumes|Networking-Performance)\\]|IPv6|csi-hostpath-v0 --minStartupPods=8', '--timeout=180m')' returned non-zero exit status 1
E0525 17:57:22.829] Command failed
I0525 17:57:22.829] process 283 exited with code 1 after 16.7m 
```

#### Anything else we need to know:

- log-dump.sh & bootstrap.py in this test are deprecated
- starting with this [PR](https://github.com/kubernetes/kubernetes/pull/100136/files) the tests are failing
  - therefore I'm also pinging @Danil-Grigorev @andrewsykim

**Comment by jzhoucliqr** [comment]
Kubelet log:  
`"Failed to run kubelet" err="failed to run Kubelet: failed to create kubelet: cloud provider \"gce\" was specified, but built-in cloud providers are disabled. Please set --cloud-provider=external and migrate to an external cloud provider"`

**Comment by pacoxu** [comment]
It seems to be related with #100136. 
/cc @Danil-Grigorev  @andrewsykim

**Comment by pacoxu** [comment]
I tried to fix it in Ihttps://github.com/kubernetes/test-infra/pull/22347.

**Comment by mkorbi** [comment]
the PR seems to solved it, thank you!
