### ISSUE TITLE
kubelet SyncLoop hangs at GetCgroupStats due to cadvisor encounter a possible deadlock

### ISSUE THREAD

**Issue by ydp** [kubernetes/kubernetes#102481]
#### What happened: 

We saw some pods stuck at ContainerCreating status after doing pods scale up test, the kubelet is unhealthy then:

```
# curl -k https://127.0.0.1:10250/healthz -H "Authorization: Bearer Gwrg_hEJtiXzjD2pnwHGlFja"
[+]ping ok
[+]log ok
[-]syncloop failed: reason withheld
healthz check failed
```
After checking the goroutine, found 2 goroutines stuck at semacquire: 
```
goroutine 473 [semacquire, 219 minutes]:
sync.runtime_SemacquireMutex(0xc000b18794, 0xc0009d1100, 0x0)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*RWMutex).RLock(...)
        /usr/local/go/src/sync/rwmutex.go:50
k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*manager).getContainersDiff(0xc000b18780, 0x48bf2a6, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager/manager.go:1066 +0xa8c
k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*manager).detectSubcontainers(0xc000b18780, 0x48bf2a6, 0x1, 0x0, 0x1)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager/manager.go:1114 +0x5d
k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*manager).globalHousekeeping(0xc000b18780, 0xc000bf8900)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager/manager.go:390 +0x1bb
created by k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*manager).Start
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager/manager.go:319 +0x585

goroutine 545 [semacquire, 219 minutes]:
sync.runtime_SemacquireMutex(0xc000b18794, 0x0, 0x0)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*RWMutex).RLock(...)
        /usr/local/go/src/sync/rwmutex.go:50
k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*manager).getContainer(0xc000b18780, 0x48bf2a6, 0x1, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager/manager.go:548 +0x1f6
k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*manager).getRequestedContainers(0xc000b18780, 0x48bf2a6, 0x1, 0x48c1422, 0x4, 0x2, 0x0, 0xc001e274a0, 0xc0002f1b00, 0xc0025e11b0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager/manager.go:707 +0x2f0
k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*manager).GetContainerInfoV2(0xc000b18780, 0x48bf2a6, 0x1, 0x48c1422, 0x4, 0x2, 0x0, 0xc001e274a0, 0x44c1c40, 0x1, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager/manager.go:492 +0x85
k8s.io/kubernetes/pkg/kubelet/cadvisor.(*cadvisorClient).ContainerInfoV2(0xc000ccc180, 0x48bf2a6, 0x1, 0x48c1422, 0x4, 0x2, 0x0, 0xc001e274a0, 0x48c146e, 0x4, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/cadvisor/cadvisor_linux.go:143 +0x73
k8s.io/kubernetes/pkg/kubelet/stats.getCgroupInfo(0x4ff20e0, 0xc000ccc180, 0x48bf2a6, 0x1, 0x1, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/stats/helper.go:306 +0xea
k8s.io/kubernetes/pkg/kubelet/stats.(*Provider).GetCgroupStats(0xc0005d1bd0, 0x48bf2a6, 0x1, 0xffffffffffffff01, 0x1, 0x5f5e100, 0x48c146e, 0x4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/stats/provider.go:111 +0x72
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).GetCgroupStats(0xc00018a000, 0x48bf2a6, 0x1, 0x1, 0x0, 0xc00185126f, 0x1b, 0x7ffe707acb02)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1195 +0x4f
k8s.io/kubernetes/pkg/kubelet/server/stats.(*summaryProviderImpl).Get(0xc000cfae40, 0xc00018a001, 0xc002ee4c00, 0x41, 0x80)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/summary.go:75 +0x178
k8s.io/kubernetes/pkg/kubelet/eviction.(*managerImpl).synchronize(0xc000dd58c0, 0x4f1d560, 0xc0005d1bd0, 0xc000344710, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go:258 +0x11e
k8s.io/kubernetes/pkg/kubelet/eviction.(*managerImpl).Start.func2(0xc000dd58c0, 0x4f1d560, 0xc0005d1bd0, 0xc000344710, 0xc000344780, 0x2540be400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go:203 +0x59
created by k8s.io/kubernetes/pkg/kubelet/eviction.(*managerImpl).Start
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go:201 +0x1fa

```
It looks like that kubelet stuck at https://github.com/kubernetes/kubernetes/blob/v1.20.6/pkg/kubelet/kubelet.go#L1195 ,  the reason might be cadvisor went into deadlock in those 2 places:

* https://github.com/kubernetes/kubernetes/blob/v1.20.6/vendor/github.com/google/cadvisor/manager/manager.go#L1066
* https://github.com/kubernetes/kubernetes/blob/v1.20.6/vendor/github.com/google/cadvisor/manager/manager.go#L548

#### What you expected to happen:

The main syncloop of kubelet shouldn't hang due to cadvisor.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.20.6

**Comment by n4j** [comment]
@ydp Could you give steps to reproduce this issue if the issue is consistent?

**Comment by ydp** [comment]
@n4j Thanks for the response, the issue occurs occasionally in our pipeline, will give more repro detail when it hit again.

**Comment by n4j** [comment]
@ydp just checking if this issue had cropped up lately

**Comment by ydp** [comment]
No.. @n4j  guess it's not easy to reproduce.
