### ISSUE TITLE
Winterm issue on Windows 8.1 in kubectl exec

### ISSUE THREAD

**Issue by jkabat** [kubernetes/kubernetes#102404]
#### What happened:

After latest update (Im not doing it regularly) Im facing following error when trying to connect to GCP pods:

```
$ kubectl exec --stdin --tty ingress-nginx-controller-pxhr2 -n ingress-nginx -- bash
panic: Invalid standard handle identifier: 4294967286

goroutine 1 [running]:
k8s.io/kubernetes/vendor/github.com/Azure/go-ansiterm/winterm.GetStdFile(0xfffffff6, 0x150, 0xf)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/Azure/go-ansiterm/winterm/ansi.go:173 +0x1f6
k8s.io/kubernetes/vendor/github.com/moby/term/windows.NewAnsiReader(0xfffffff6, 0xc00000000f, 0x219ac60)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/moby/term/windows/ansi_reader.go:34 +0x36
k8s.io/kubernetes/vendor/github.com/moby/term.StdStreams(0x2198f80, 0xc0000d8000, 0x2198fa0, 0xc0000d8008, 0x0, 0x0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/moby/term/term_windows.go:75 +0x1f8
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/exec.(*StreamOptions).SetupTTY(0xc0000a88c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/exec/exec.go:273 +0x13d
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/exec.(*ExecOptions).Run(0xc0000a88c0, 0x0, 0x200d550)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/exec/exec.go:331 +0x23f
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/exec.NewCmdExec.func1(0xc0001d4dc0, 0xc000303570, 0x2, 0x7)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/exec/exec.go:95 +0x11a
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0001d4dc0, 0xc000303500, 0x7, 0x7, 0xc0001d4dc0, 0xc000303500)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000392dc0, 0xc0000e8000, 0xc0000e6000, 0x9)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
main.main()
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x234
```

#### Anything else we need to know?:

I'm using GIT bash and have no issue with docker-compose EXEC, which might be bitten in similar way:
https://github.com/docker/for-win/issues/9770

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.6-gke.1000", GitCommit:"3ae0998c5052f420a17cb96bacf860ec5d6822a3", GitTreeState:"clean", BuildDate:"2021-04-29T09:17:16Z", GoVersion:"go1.15.10b5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GCP
- OS (e.g: `cat /etc/os-release`): Windows 8.1
- Kernel (e.g. `uname -a`): 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by n4j** [comment]
@neolit123  Is anyone working on this issue? If not then I would like to give it a stab.

**Comment by neolit123** [comment]
Sure, go ahead.

**Comment by n4j** [comment]
Quick update, I have setup my test bed on Windows 10 machine and I am able to reproduce this issue by turning on `Legacy Console Mode`.

After some debugging I applied a "monkey patch" in the package `github.com\moby\term` to test a hypothesis and the issue resolved :)

Though I am not sure if my patch would work on all versions of windows + would it be correct to do it in `moby\term` or not.

Let me dig deeper and get back on this

**Comment by n4j** [comment]
The issue seems to be with `Azure\go-ansiterm` project which uses flags from `syscall` package to map `stdin`, `stdout` and `stderr` while `mob\term` passes the flags from `golang.org/x/sys/windows` package.

This causes `go-ansiterm` to panic and throw the error mentioned above, this incompatibility between packages have impacted [docker CLI](https://github.com/docker/for-win/issues/9770) as well.

I have raised a [PR](https://github.com/Azure/go-ansiterm/pull/31) in `Azure\go-ansiterm` repo to permanently fix this couple of days back and I am waiting for @jstarks to review and merge the PR
