### ISSUE TITLE
kubelet panics on creation of inline ephemeral volume with FSType specified

### ISSUE THREAD

**Issue by okartau** [kubernetes/kubernetes#102651]
#### What happened:
kubelet panics on creation of inline ephemeral volume with FSType specified.

#### What you expected to happen:
creation of inline ephemeral volume succeeds with FSType specified.

#### How to reproduce it (as minimally and precisely as possible):
no existing isolated test case. Happens during e2e testing of pmem-csi.

#### Environment:
- Kubernetes version (use `kubectl version`): The pmem-csi CI system where this was detected, runs same tests on k8s systems with 1.19 and 1.20. The problem occurs in testing on 1.20 system, problem does not occur on 1.19 system.

- Cloud provider or hardware configuration: pmem-csi tests run on cluster formed by few qemu-based systems running Fedora-33 and emulated pmem storage.

The issue has been seen in e2e testing in [pmem-csi](https://github.com/intel/pmem-csi), where a new test was
recently introduced that creates a pod with an inline ephemeral volume.

If the related VolumeSource has filesystem type set to empty "", or FSType is omitted in spec,
then the pod creation works OK. In that case, pmem-csi chooses it's default fstype which is `ext4`.

Example of working definition of VolumeSource:
```
   fstype := ""
   vsource := v1.VolumeSource{
           CSI: &v1.CSIVolumeSource{
                   Driver: "pmem-csi.intel.com",
                   FSType: &fstype,
                   VolumeAttributes: map[string]string{
                           "size": "110Mi",
                   },
           },
   }
```

If the filesystem type in the VolumeSource is set to `ext4` or `xfs`
then kubelet fails to create the volume and pod. A panic trace is written in the node kubelet log and the creation will be retried few times,

```
pmem-csi-govm-worker2 kubelet[905]: E0526 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/a5c44727-b679-412d-a3ef-3f6bbc7af122-vol1 podName:a5c44727-b679-412d-a3ef-3f6bbc7af122 nodeName:}" failed. No retries permitted until 2021-05-26 16:53:09.613416932 +0000 UTC m=+14773.383054841 (durationBeforeRetry 500ms). Error: "recovered from panic \"runtime error: invalid memory address or nil pointer dereference\". (err=<nil>) Call stack:
goroutine 95902 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc0014c0d10)
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:158 +0xba
panic(0x40021e0, 0x6fd2280)
/usr/local/go/src/runtime/panic.go:975 +0x47a
k8s.io/kubernetes/pkg/volume/csi.(*csiMountMgr).supportsFSGroup(0xc0016b0ff0, 0xc0009e6724, 0x3, 0xc0013960f0, 0xc00144b260, 0x17, 0x0)
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_mounter.go:429 +0xb5
k8s.io/kubernetes/pkg/volume/csi.(*csiMountMgr).SetUpAt(0xc0016b0ff0, 0xc001077c80, 0x5f, 0xc001396470, 0xc0013960f0, 0x0, 0x0, 0x0, 0x0)
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_mounter.go:269 +0x105f
k8s.io/kubernetes/pkg/volume/csi.(*csiMountMgr).SetUp(0xc0016b0ff0, 0xc001396470, 0xc0013960f0, 0x0, 0x0, 0x0, 0xc0009e6720)
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_mounter.go:106 +0x65
k8s.io/kubernetes/pkg/volume/util/operationexecutor.(*operationGenerator).GenerateMountVolumeFunc.func1(0xc000bb7db0, 0xc0014c0d10, 0x0, 0x0)
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go:643 +0x504
k8s.io/kubernetes/pkg/volume/util/types.(*GeneratedOperations).Run(0xc001dcdb00, 0xc000bb7f18, 0x4b8530, 0xc000bb7f58, 0x409548)
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/util/types/types.go:54 +0xde
k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations.(*nestedPendingOperations).Run.func1(0xc000e1e5c0, 0xc00082fb00, 0x3b, 0xc001a24780, 0x24, 0x0, 0x0, 0xc001dcdb00, 0x0, 0x0, ...)
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:183 +0xfa
created by k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations.(*nestedPendingOperations).Run
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:178 +0x479"
```

On pmem-csi side: the 1st NodePublishVolume is received, namespace
and volume are created, formatted with mkfs, mounted and NodePublishVolume returns OK.
Same request is received few times with increasing time interval.

e2e testing code which tries to create the pod, will fail with:
```
FAIL: running pod
Unexpected error:
    <*errors.errorString | 0xc0002f9060>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
```

**Comment by pohly** [comment]
> What you expected to happen:
> creation of inline ephemeral volume succeeds with FSType specified

... and ownership changed for those volumes.
