### ISSUE TITLE
podresources API NPE if cpumanager featuregate is disabled

### ISSUE THREAD

**Issue by fromanirh** [kubernetes/kubernetes#102780]
#### What happened:
Iff the cpumanager feature gate (default: enabled) is explicitely disabled, calling podresources API causes a NPE in the kubelet.
The stacktrace looks like
```
Jun 10 15:46:30 xeon kubelet[181859]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 10 15:46:30 xeon kubelet[181859]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x5560856ab852]
Jun 10 15:46:30 xeon kubelet[181859]: goroutine 664 [running]:
Jun 10 15:46:30 xeon kubelet[181859]: k8s.io/kubernetes/pkg/kubelet/cm.(*containerManagerImpl).GetAllocatableCPUs(0xc00102ec80, 0x0, 0x0, 0x0)
Jun 10 15:46:30 xeon kubelet[181859]:         /work/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/container_manager_linux.go:1080 +0x32
Jun 10 15:46:30 xeon kubelet[181859]: k8s.io/kubernetes/pkg/kubelet/apis/podresources.(*v1PodResourcesServer).GetAllocatableResources(0xc000488240, 0x556088934418, 0xc000fa10b0, 0xc000ee6ea8, 0xc000488240, 0xc000fa10b0, 0xc000744b80)
Jun 10 15:46:30 xeon kubelet[181859]:         /work/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/apis/podresources/server_v1.go:92 +0x1ce
Jun 10 15:46:30 xeon kubelet[181859]: k8s.io/kubernetes/vendor/k8s.io/kubelet/pkg/apis/podresources/v1._PodResourcesLister_GetAllocatableResources_Handler(0x556087f11920, 0xc000488240, 0x556088934418, 0xc000fa10b0, 0xc000471b60, 0x0, 0x556088934418, 0xc000fa10b0, 0x0, 0x0)
Jun 10 15:46:30 xeon kubelet[181859]:         /work/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubelet/pkg/apis/podresources/v1/api.pb.go:636 +0x214
Jun 10 15:46:30 xeon kubelet[181859]: k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000754180, 0x556088980e78, 0xc000e0c600, 0xc0006ef000, 0xc0004882d0, 0x55608aadd6d8, 0x0, 0x0, 0x0)
Jun 10 15:46:30 xeon kubelet[181859]:         /work/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:1024 +0x522
Jun 10 15:46:30 xeon kubelet[181859]: k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000754180, 0x556088980e78, 0xc000e0c600, 0xc0006ef000, 0x0)
Jun 10 15:46:30 xeon kubelet[181859]:         /work/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:1313 +0xd4c
Jun 10 15:46:30 xeon kubelet[181859]: k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0013c6350, 0xc000754180, 0x556088980e78, 0xc000e0c600, 0xc0006ef000)
Jun 10 15:46:30 xeon kubelet[181859]:         /work/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:722 +0xad
Jun 10 15:46:30 xeon kubelet[181859]: created by k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
Jun 10 15:46:30 xeon kubelet[181859]:         /work/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:720 +0xa5
```
This applies to any podresources API (either `List` or `GetAllocatableResources`)

**Only triggers if the cpumanager feature gate is explicitely disabled (it is enabled by default in 1.20+) https://github.com/kubernetes/kubernetes/blob/v1.20.0/pkg/features/kube_features.go#L747**

#### What you expected to happen:
The podresources API should return either error or a valid value, not NPE.

#### How to reproduce it (as minimally and precisely as possible):
The simplest possible reproducer is probably to apply this patch
```
diff --git a/test/e2e_node/podresources_test.go b/test/e2e_node/podresources_test.go
index 2384cd9d68c..be6f6c35701 100644
--- a/test/e2e_node/podresources_test.go
+++ b/test/e2e_node/podresources_test.go
@@ -667,7 +667,7 @@ func configurePodResourcesInKubelet(f *framework.Framework, cleanStateFile bool,
        if newCfg.FeatureGates == nil {
                newCfg.FeatureGates = make(map[string]bool)
        }
-       newCfg.FeatureGates["CPUManager"] = true
+       newCfg.FeatureGates["CPUManager"] = false
        newCfg.FeatureGates["KubeletPodResourcesGetAllocatable"] = true
 
        // After graduation of the CPU Manager feature to Beta, the CPU Manager
@@ -725,6 +725,7 @@ func enablePodResourcesFeatureGateInKubelet(f *framework.Framework) (oldCfg *kub
        if newCfg.FeatureGates == nil {
                newCfg.FeatureGates = make(map[string]bool)
        }
+       newCfg.FeatureGates["CPUManager"] = false
        newCfg.FeatureGates["KubeletPodResourcesGetAllocatable"] = true
 
        // Update the Kubelet configuration.
```

And then run the podresources e2e tests
```
make test-e2e-node PARALLELISM=1 FOCUS="Feature:PodResources" SKIP="
```

#### Anything else we need to know?:
We should probably add another e2e test to explicitly check this dlow

#### Environment:
- Kubernetes version (use `kubectl version`): any since 1.20 (possibly introduced in commit https://github.com/kubernetes/kubernetes/commit/a8b8995ef241e93e9486d475126450f33f24ef4e#diff-c07d343a8d459721656cf7ddacda71506bde01a5cac288d15a4aba6bfc9a1caeR1031)
- Cloud provider or hardware configuration: any
- OS (e.g: `cat /etc/os-release`): any
- Kernel (e.g. `uname -a`): any
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by fromanirh** [comment]
possible workaround (not tested but everything suggests it should work)
- **enable the cpumanager feature gate**
- set the cpumanager policy to "none"
