### ISSUE TITLE
kubelet won't restart after reboot - Unable to register node with API server: connection refused

### ISSUE THREAD

**Issue by wangcheng34** [kubernetes/kubernetes#103687]
#### What happened:

After reboot, can't register node with API server: connection refused

as I issued in [kubeadm](https://github.com/kubernetes/kubeadm/issues/2527) 

#### What you expected to happen:

Kubernetes to respond

## Versions

ubeadm version: &version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:41:38Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**kubeadm version** (use `kubeadm version`):

**Environment**:
- **Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server office.snc-dev.com:6443 was refused - did you specify the right host or port?

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- **Kernel** (e.g. `uname -a`):
Linux master 4.15.0-147-generic  151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

## What happened?
Issue is exactly same as - #1026 and #1082 .  I have followed all the steps mentioned including kubeadm reset and kubeadm init , but issue still persists. The issue occured post reboot.

## What you expected to happen?
Kubernetes to respond

## How to reproduce it (as minimally and precisely as possible)?
reboot system.

## Anything else we need to know?
apiserver log:
```
Flag --insecure-port has been deprecated, This flag will be removed in a future version.
I0714 12:23:29.306407       1 server.go:596] external host was not specified, using 192.168.10.14
I0714 12:23:29.306551       1 server.go:150] Version: v1.17.5
I0714 12:23:29.530694       1 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,MutatingAdmissionWebhook,RuntimeClass.
I0714 12:23:29.530705       1 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,RuntimeClass,ResourceQuota.
I0714 12:23:29.531317       1 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,MutatingAdmissionWebhook,RuntimeClass.
I0714 12:23:29.531327       1 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,RuntimeClass,ResourceQuota.
I0714 12:23:29.532712       1 client.go:361] parsed scheme: "endpoint"
I0714 12:23:29.532747       1 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://127.0.0.1:2379 0  <nil>}]
I0714 12:23:30.531162       1 client.go:361] parsed scheme: "endpoint"
I0714 12:23:30.531219       1 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://127.0.0.1:2379 0  <nil>}]
panic: context deadline exceeded

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresourcedefinition.NewREST(0xc0007be1c0, 0x4f73a80, 0xc0000e2b40, 0xc0000e2e88)
	/workspace/anago-v1.17.5-beta.0.65+a04e7d7c202142/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresourcedefinition/etcd.go:56 +0x3c1
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver.completedConfig.New(0xc000821ac0, 0xc0000c2088, 0x50341e0, 0x756f2f0, 0x10, 0x0, 0x0)
	/workspace/anago-v1.17.5-beta.0.65+a04e7d7c202142/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go:147 +0x152b
k8s.io/kubernetes/cmd/kube-apiserver/app.createAPIExtensionsServer(0xc0000c2080, 0x50341e0, 0x756f2f0, 0x0, 0x4f73720, 0xc000263040)
	/workspace/anago-v1.17.5-beta.0.65+a04e7d7c202142/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/apiextensions.go:99 +0x59
k8s.io/kubernetes/cmd/kube-apiserver/app.CreateServerChain(0xc0007dd600, 0xc0002d8360, 0x449c00a, 0xc, 0xc0009cfc48)
	/workspace/anago-v1.17.5-beta.0.65+a04e7d7c202142/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:183 +0x292
k8s.io/kubernetes/cmd/kube-apiserver/app.Run(0xc0007dd600, 0xc0002d8360, 0x0, 0x0)
	/workspace/anago-v1.17.5-beta.0.65+a04e7d7c202142/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:152 +0x101
k8s.io/kubernetes/cmd/kube-apiserver/app.NewAPIServerCommand.func1(0xc0008bfb80, 0xc0004e1a00, 0x0, 0x1a, 0x0, 0x0)
	/workspace/anago-v1.17.5-beta.0.65+a04e7d7c202142/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:119 +0x104
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0008bfb80, 0xc00004c1d0, 0x1a, 0x1b, 0xc0008bfb80, 0xc00004c1d0)
	/workspace/anago-v1.17.5-beta.0.65+a04e7d7c202142/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:826 +0x460
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0008bfb80, 0x1691a7c6002a8feb, 0x7551340, 0xc000076750)
	/workspace/anago-v1.17.5-beta.0.65+a04e7d7c202142/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/anago-v1.17.5-beta.0.65+a04e7d7c202142/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
main.main()
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/apiserver.go:43 +0xcd
```

docker ps
```
root@master:/data1/easymock# docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                    NAMES
419e70afae9a        f640481f6db3                  "kube-apiserver --ad…"   7 seconds ago       Up 6 seconds                                 k8s_kube-apiserver_kube-apiserver-master_kube-system_039493a736397522556e2f0818d20350_484
112253b1e53d        303ce5db0e90                  "etcd --advertise-cl…"   9 minutes ago       Up 9 minutes                                 k8s_etcd_etcd-master_kube-system_3ef5300027185858dfff340b88b38bce_61
c05b0bcbe6a0        fe3d691efbf3                  "kube-controller-man…"   47 minutes ago      Up 47 minutes                                k8s_kube-controller-manager_kube-controller-manager-master_kube-system_b219a322e97fba705180b59be9be7e96_127
9da473163372        f648efaff966                  "kube-scheduler --au…"   47 minutes ago      Up 47 minutes                                k8s_kube-scheduler_kube-scheduler-master_kube-system_0f20e99c06ccc6f9f86e34e6dbe88537_121
17eadfb8a5a1        k8s.gcr.io/pause:3.1          "/pause"                 47 minutes ago      Up 47 minutes                                k8s_POD_kube-scheduler-master_kube-system_0f20e99c06ccc6f9f86e34e6dbe88537_23
afcf834a70fd        k8s.gcr.io/pause:3.1          "/pause"                 47 minutes ago      Up 47 minutes                                k8s_POD_kube-controller-manager-master_kube-system_b219a322e97fba705180b59be9be7e96_24
4223c4d8c1e5        k8s.gcr.io/pause:3.1          "/pause"                 47 minutes ago      Up 47 minutes                                k8s_POD_kube-apiserver-master_kube-system_039493a736397522556e2f0818d20350_23
24e178e31d91        k8s.gcr.io/pause:3.1          "/pause"                 47 minutes ago      Up 47 minutes                                k8s_POD_etcd-master_kube-system_3ef5300027185858dfff340b88b38bce_24
```

system log 

```
Jul 14 12:47:50 master kubelet[14758]: E0714 12:47:50.456928   14758 kubelet.go:2263] node "master" not found
Jul 14 12:47:50 master kubelet[14758]: E0714 12:47:50.557177   14758 kubelet.go:2263] node "master" not found
Jul 14 12:47:50 master kubelet[14758]: E0714 12:47:50.657456   14758 kubelet.go:2263] node "master" not found
Jul 14 12:47:50 master kubelet[14758]: E0714 12:47:50.757670   14758 kubelet.go:2263] node "master" not found
Jul 14 12:47:50 master kubelet[14758]: E0714 12:47:50.857907   14758 kubelet.go:2263] node "master" not found
Jul 14 12:47:50 master kubelet[14758]: E0714 12:47:50.902245   14758 kubelet_node_status.go:92] Unable to register node "master" with API server: Post **domain:6443/api/v1/nodes: read tcp 192.168.10.14:38666->192.168.10.
Jul 14 12:47:50 master kubelet[14758]: E0714 12:47:50.958083   14758 kubelet.go:2263] node "master" not found
Jul 14 12:47:51 master kubelet[14758]: E0714 12:47:51.058352   14758 kubelet.go:2263] node "master" not found
Jul 14 12:47:51 master kubelet[14758]: E0714 12:47:51.158644   14758 kubelet.go:2263] node "master" not found
Jul 14 12:47:51 master kubelet[14758]: E0714 12:47:51.258917   14758 kubelet.go:2263] node "master" not found
Jul 14 12:47:51 master kubelet[14758]: E0714 12:47:51.359112   14758 kubelet.go:2263] node "master" not found
Jul 14 12:47:51 master kubelet[14758]: E0714 12:47:51.459511   14758 kubelet.go:2263] node "master" not found
Jul 14 12:47:51 master kubelet[14758]: E0714 12:47:51.559950   14758 kubelet.go:2263] node "master" not found
Jul 14 12:47:51 master kubelet[14758]: E0714 12:47:51.660180   14758 kubelet.go:2263] node "master" not found
Jul 14 12:47:51 master kubelet[14758]: E0714 12:47:51.760462   14758 kubelet.go:2263] node "master" not found
Jul 14 12:47:51 master kubelet[14758]: E0714 12:47:51.860730   14758 kubelet.go:2263] node "master" not found
Jul 14 12:47:51 master kubelet[14758]: E0714 12:47:51.903557   14758 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:458: Failed to list *v1.Node: Get **domain:6443/api/v1/nodes?fieldSelector=metadata.name%3Dm
Jul 14 12:47:51 master kubelet[14758]: E0714 12:47:51.903564   14758 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.CSIDriver: Get ***domain:6443/apis/storage.k8s.io/v1beta1/csidriver
Jul 14 12:47:51 master kubelet[14758]: I0714 12:47:51.903816   14758 trace.go:116] Trace[1831172752]: "Reflector ListAndWatch" name:k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46 (started: 2021-07-14 12:47:41.60215041 +0000 UTC m=+6
Jul 14 12:47:51 master kubelet[14758]: Trace[1831172752]: [10.301601936s] [10.301601936s] END
Jul 14 12:47:51 master kubelet[14758]: E0714 12:47:51.903837   14758 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:449: Failed to list *v1.Service: Get ***domain:6443/api/v1/services?limit=500&resourceVersion
Jul 14 12:47:51 master kubelet[14758]: E0714 12:47:51.903853   14758 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get ***domain:6443/api/v1/pods?fieldSelector=spec.nodeNa
Jul 14 12:47:51 master kubelet[14758]: I0714 12:47:51.904247   14758 trace.go:116] Trace[1465092182]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (started: 2021-07-14 12:47:41.802422743 +0000 UTC m=+64.77191776
Jul 14 12:47:51 master kubelet[14758]: Trace[1465092182]: [10.101751002s] [10.101751002s] END
Jul 14 12:47:51 master kubelet[14758]: E0714 12:47:51.904282   14758 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.RuntimeClass: Get ***domain:6443/apis/node.k8s.io/v1beta1/runtimecl
Jul 14 12:47:51 master kubelet[14758]: I0714 12:47:51.931095   14758 kubelet_node_status.go:294] Setting node annotation to enable volume controller attach/detach
Jul 14 12:47:51 master kubelet[14758]: I0714 12:47:51.931207   14758 kubelet_node_status.go:294] Setting node annotation to enable volume controller attach/detach
Jul 14 12:47:51 master kubelet[14758]: E0714 12:47:51.960852   14758 kubelet.go:2263] node "master" not found
Jul 14 12:47:51 master kubelet[14758]: E0714 12:47:51.961676   14758 pod_workers.go:191] Error syncing pod 039493a736397522556e2f0818d20350 ("kube-apiserver-master_kube-system(039493a736397522556e2f0818d20350)"), skipping: failed to "Star
Jul 14 12:47:51 master kubelet[14758]: W0714 12:47:51.961769   14758 status_manager.go:530] Failed to get status for pod "kube-apiserver-master_kube-system(039493a736397522556e2f0818d20350)": Get ***domain:6443/api/v1/nam
Jul 14 12:47:52 master kubelet[14758]: E0714 12:47:52.061196   14758 kubelet.go:2263] node "master" not found
Jul 14 12:47:52 master kubelet[14758]: E0714 12:47:52.161618   14758 kubelet.go:2263] node "master" not found
Jul 14 12:47:52 master kubelet[14758]: E0714 12:47:52.240832   14758 csi_plugin.go:273] Failed to initialize CSINodeInfo: error updating CSINode annotation: timed out waiting for the condition; caused by: Get ***domain:64
Jul 14 12:47:52 master kubelet[14758]: F0714 12:47:52.240868   14758 csi_plugin.go:287] Failed to initialize CSINodeInfo after retrying
Jul 14 12:47:52 master systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jul 14 12:47:52 master systemd[1]: kubelet.service: Failed with result 'exit-code'.
```

kubelet status
```
root@master:/data1/easymock# systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Wed 2021-07-14 12:48:02 UTC; 47s ago
     Docs: https://kubernetes.io/docs/home/
 Main PID: 16170 (kubelet)
    Tasks: 26 (limit: 4915)
   CGroup: /system.slice/kubelet.service
           └─16170 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=cgroupfs --network-plugin=cni --pod-infra-co

Jul 14 12:48:48 master kubelet[16170]: E0714 12:48:48.942002   16170 kubelet.go:2263] node "master" not found
Jul 14 12:48:49 master kubelet[16170]: E0714 12:48:49.042250   16170 kubelet.go:2263] node "master" not found
Jul 14 12:48:49 master kubelet[16170]: E0714 12:48:49.142531   16170 kubelet.go:2263] node "master" not found
Jul 14 12:48:49 master kubelet[16170]: E0714 12:48:49.242803   16170 kubelet.go:2263] node "master" not found
Jul 14 12:48:49 master kubelet[16170]: E0714 12:48:49.303383   16170 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.RuntimeClass: Get ***domain:6443/apis/node.k8s.io/v1beta1/runtimecl
Jul 14 12:48:49 master kubelet[16170]: E0714 12:48:49.343004   16170 kubelet.go:2263] node "master" not found
Jul 14 12:48:49 master kubelet[16170]: E0714 12:48:49.443233   16170 kubelet.go:2263] node "master" not found
Jul 14 12:48:49 master kubelet[16170]: E0714 12:48:49.503900   16170 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get ***domain:6443/api/v1/pods?fieldSelector=spec.nodeNa
Jul 14 12:48:49 master kubelet[16170]: E0714 12:48:49.543462   16170 kubelet.go:2263] node "master" not found
Jul 14 12:48:49 master kubelet[16170]: E0714 12:48:49.643692   16170 kubelet.go:2263] node "master" not found
``` 
etcd log
```
raft2021/07/14 13:18:16 INFO: f60b205fb02fe23c is starting a new election at term 18560
raft2021/07/14 13:18:16 INFO: f60b205fb02fe23c became candidate at term 18561
raft2021/07/14 13:18:16 INFO: f60b205fb02fe23c received MsgVoteResp from f60b205fb02fe23c at term 18561
raft2021/07/14 13:18:16 INFO: f60b205fb02fe23c [logterm: 5641, index: 267337249] sent MsgVote request to 7e5337be3fa9b9b at term 18561
2021-07-14 13:18:16.652898 I | embed: rejected connection from "*.*.*.*:60894" (error "tls: failed to verify client's certificate: x509: certificate has expired or is not yet valid", ServerName "")
2021-07-14 13:18:16.658312 I | embed: rejected connection from "*.*.*.*:60896" (error "tls: failed to verify client's certificate: x509: certificate has expired or is not yet valid", ServerName "")
2021-07-14 13:18:16.751311 I | embed: rejected connection from "*.*.*.*:60898" (error "tls: failed to verify client's certificate: x509: certificate has expired or is not yet valid", ServerName "")
2021-07-14 13:18:16.755572 I | embed: rejected connection from "*.*.*.*:60900" (error "tls: failed to verify client's certificate: x509: certificate has expired or is not yet valid", ServerName "")
2021-07-14 13:18:16.852907 I | embed: rejected connection from "*.*.*.*:60926" (error "tls: failed to verify client's certificate: x509: certificate has expired or is not yet valid", ServerName "")
2021-07-14 13:18:16.858557 I | embed: rejected connection from "*.*.*.*:60928" (error "tls: failed to verify client's certificate: x509: certificate has expired or is not yet valid", ServerName "")
2021-07-14 13:18:16.951290 I | embed: rejected connection from "*.*.*.*:60930" (error "tls: failed to verify client's certificate: x509: certificate has expired or is not yet valid", ServerName "")
2021-07-14 13:18:16.955302 I | embed: rejected connection from "*.*.*.*:60932" (error "tls: failed to verify client's certificate: x509: certificate has expired or is not yet valid", ServerName "")
2021-07-14 13:18:17.053718 I | embed: rejected connection from "*.*.*.*:60934" (error "tls: failed to verify client's certificate: x509: certificate has expired or is not yet valid", ServerName "")
2021-07-14 13:18:17.059391 I | embed: rejected connection from "*.*.*.*:60936" (error "tls: failed to verify client's certificate: x509: certificate has expired or is not yet valid", ServerName "")
2021-07-14 13:18:17.080638 I | embed: rejected connection from "*.*.*.*:60938" (error "tls: failed to verify client's certificate: x509: certificate has expired or is not yet valid", ServerName "")
2021-07-14 13:18:17.152354 I | embed: rejected connection from "*.*.*.*:60940" (error "tls: failed to verify client's certificate: x509: certificate has expired or is not yet valid", ServerName "")
2021-07-14 13:18:17.158885 I | embed: rejected connection from "*.*.*.*:60942" (error "tls: failed to verify client's certificate: x509: certificate has expired or is not yet valid", ServerName "")
2021-07-14 13:18:17.246605 I | embed: rejected connection from "*.*.*.*:60944" (error "tls: failed to verify client's certificate: x509: certificate has expired or is not yet valid", ServerName "")
2021-07-14 13:18:17.250108 I | embed: rejected connection from "*.*.*.*:60946" (error "tls: failed to verify client's certificate: x509: certificate has expired or is not yet valid", ServerName "")
```
```
root@master:/home/user# kubeadm alpha certs check-expiration
[check-expiration] Reading configuration from the cluster...
[check-expiration] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[check-expiration] Error reading configuration from the Cluster. Falling back to default configuration

W0714 13:22:26.479881   18231 validation.go:28] Cannot validate kube-proxy config - no validator is available
W0714 13:22:26.479977   18231 validation.go:28] Cannot validate kubelet config - no validator is available
CERTIFICATE                EXPIRES                  RESIDUAL TIME   CERTIFICATE AUTHORITY   EXTERNALLY MANAGED
admin.conf                 Apr 26, 2022 08:39 UTC   285d                                    no
apiserver                  Apr 26, 2022 08:39 UTC   285d            ca                      no
apiserver-etcd-client      Apr 26, 2022 08:39 UTC   285d            etcd-ca                 no
apiserver-kubelet-client   Apr 26, 2022 08:39 UTC   285d            ca                      no
controller-manager.conf    Apr 26, 2022 08:39 UTC   285d                                    no
etcd-healthcheck-client    Apr 26, 2022 08:39 UTC   285d            etcd-ca                 no
etcd-peer                  Apr 26, 2022 08:39 UTC   285d            etcd-ca                 no
etcd-server                Apr 26, 2022 08:39 UTC   285d            etcd-ca                 no
front-proxy-client         Apr 26, 2022 08:39 UTC   285d            front-proxy-ca          no
scheduler.conf             Apr 26, 2022 08:39 UTC   285d                                    no

CERTIFICATE AUTHORITY   EXPIRES                  RESIDUAL TIME   EXTERNALLY MANAGED
ca                      Apr 19, 2030 10:03 UTC   8y              no
etcd-ca                 Apr 19, 2030 10:03 UTC   8y              no
front-proxy-ca          Apr 19, 2030 10:03 UTC   8y              no
```

**Comment by neolit123** [comment]
> 2021-07-14 13:18:16.652898 I | embed: rejected connection from "*.*.*.*:60894" (error "tls: failed to verify client's certificate: x509: certificate has expired or is not yet valid", ServerName "")

do you know what certificate is this about and who is making the connection?
i would assume it's the kube-apiserver.

what is the output of `openssl x509 -noout -dates -in /etc/kubernetes/pki/apiserver-etcd-client.crt`?

> After reboot, can't register node with API server: connection refused

are you sure the system time is correct after the restart?
what is the output of `date`?

/remove-kind bug
/kind support
/triage needs-information
/remove-sig node

**Comment by wangcheng34** [comment]
> openssl x509 -noout -dates -in /etc/kubernetes/pki/apiserver-etcd-client.crt

```
root@master:/data1/easymock# openssl x509 -noout -dates -in /etc/kubernetes/pki/apiserver-etcd-client.crt
notBefore=Apr 21 10:03:13 2020 GMT
notAfter=Apr 26 08:39:56 2022 GMT
root@master:/data1/easymock# date
Wed Jul 14 23:43:16 UTC 2021
root@master:/data1/easymock#
```
I think date is right

> do you know what certificate is this about and who is making the connection?
i would assume it's the kube-apiserver

yes, I think so. the kube-apiserver is rebooting again and again.

**Comment by wangcheng34** [comment]
> > 2021-07-14 13:18:16.652898 I | embed: rejected connection from "_._._._:60894" (error "tls: failed to verify client's certificate: x509: certificate has expired or is not yet valid", ServerName "")
> 
> do you know what certificate is this about and who is making the connection?
> i would assume it's the kube-apiserver.
> 
> what is the output of `openssl x509 -noout -dates -in /etc/kubernetes/pki/apiserver-etcd-client.crt`?
> 
> > After reboot, can't register node with API server: connection refused
> 
> are you sure the system time is correct after the restart?
> what is the output of `date`?
> 
> /remove-kind bug
> /kind support
> /triage needs-information
> /remove-sig node

kube-apiserver restart loop 
maybe the etcd server failed. but I can get etd process and its listenning port

**Comment by neolit123** [comment]
i have no explanation for this problem in that case. if the date is correct and all certificates are valid these error messages are strange.

**Comment by neolit123** [comment]
can you try to reproduce on 1.19 or newer?

**Comment by wangcheng34** [comment]
> can you try to reproduce on 1.19 or newer?

I update all cert, now is OK
