### ISSUE TITLE
DeviceManager panic on Allocate()

### ISSUE THREAD

**Issue by SidneyShen** [kubernetes/kubernetes#103838]
#### What happened:
Pod worker panic when trying to re-allocating the device plugin resource during the node restart. 

The issue is potentially caused by [m.devicesToReuse map deleting](https://github.com/kubernetes/kubernetes/blob/1a9ae3454993b2362503db3efe1d7e48307bf3ff/pkg/kubelet/cm/devicemanager/manager.go#L376) an un-matching pod id. The map will be later used in an [assignment](https://github.com/kubernetes/kubernetes/blob/1a9ae3454993b2362503db3efe1d7e48307bf3ff/pkg/kubelet/cm/devicemanager/pod_devices.go#L158), which caused panic. ([Allocate()](https://github.com/kubernetes/kubernetes/blob/1a9ae3454993b2362503db3efe1d7e48307bf3ff/pkg/kubelet/cm/devicemanager/manager.go#L369) func by itself is not thread-safe)

Stack trace:
```
runtime.go:78] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
goroutine 1419 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3cd4a80, 0x4c848b0)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3cd4a80, 0x4c848b0)
 /usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.podDevices.removeContainerAllocatedResources(0xc000960000, 0xc00140e240, 0x24, 0xc000c789f0, 0x9, 0x0)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/pod_devices.go:109 +0x1b2
k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).Allocate(0xc000995790, 0xc001475800, 0xc001302dc0, 0x42, 0xc001a21d88)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/manager.go:388 +0x373
k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).GetDeviceRunContainerOptions(0xc000995790, 0xc001475800, 0xc001302dc0, 0x0, 0x0, 0x0)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/manager.go:881 +0x5af
k8s.io/kubernetes/pkg/kubelet/cm.(*containerManagerImpl).GetResources(0xc000430fc0, 0xc001475800, 0xc001302dc0, 0x70, 0x70, 0x42f7840)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/cm/container_manager_linux.go:661 +0x83
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).GenerateRunContainerOptions(0xc000ec2a80, 0xc001475800, 0xc001302dc0, 0xc001d0a904, 0xb, 0xc00221d0c0, 0x1, 0x1, 0x3, 0x0, ...)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go:455 +0x6c
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).generateContainerConfig(0xc0000ff900, 0xc001302dc0, 0xc001475800, 0x1, 0xc001d0a904, 0xb, 0xc0014aeeb0, 0x47, 0xc00221d0c0, 0x1, ...)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go:247 +0xa7
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).startContainer(0xc0000ff900, 0xc00219c000, 0x40, 0xc0001985b0, 0xc00221d190, 0xc001475800, 0xc0009a1b00, 0xc000191180, 0x1, 0x1, ...)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go:166 +0x5bf
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).SyncPod.func1(0x458330a, 0x9, 0xc00221d190, 0xc000198500, 0x0)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager.go:816 +0x8e3
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).SyncPod(0xc0000ff900, 0xc001475800, 0xc0009a1b00, 0xc000191180, 0x1, 0x1, 0xc000d20dc0, 0xc0021afda0, 0x4, 0x4, ...)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager.go:855 +0xc24
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncPod(0xc000ec2a80, 0x0, 0xc001475800, 0x0, 0xc0009a1b00, 0x0, 0xc000db1440, 0xc000604660)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1719 +0x1018
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).managePodLoop.func1(0xc0021fdea0, 0xc00036a460, 0xc000f4fe88, 0x4d35e00, 0xc000a354c0)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:175 +0x25d
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).managePodLoop(0xc00036a460, 0xc001c947e0)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:184 +0x13f
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod.func1(0xc00036a460, 0xc001c947e0)
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:222 +0x6c
created by k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod
 /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:220 +0x3d3
```

#### What you expected to happen:
DeviceManager Allocate() should be able to handle such race safely. 

#### How to reproduce it (as minimally and precisely as possible):
Customer reported issue after upgrading to 1.18+. 

#### Anything else we need to know?:
This is the new behavior introduced since 1.18+ from [this commit](https://github.com/kubernetes/kubernetes/commit/cb9fdc49db8ed56aea6569e1a9ab69920ae8cc2e).

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by adisky** [comment]
/assign
looking into the issue

**Comment by chenyw1990** [comment]
https://github.com/kubernetes/kubernetes/pull/102525
@pacoxu I think your PR is related to this issue.

**Comment by adisky** [comment]
/unassign
seems pretty relatable to PR #102525 
cc @pacoxu

**Comment by ehashman** [comment]
/remove-priority critical-urgent

I don't think this is a release blocker at this point given the history reading through https://github.com/kubernetes/kubernetes/pull/102525; we can fix this in a cherry-pick.

**Comment by klueska** [comment]
I will take a closer look later this week.
