### ISSUE TITLE
Kube-proxy won't start, failed complete: too many open files

### ISSUE THREAD

**Issue by ClementGautier** [kubernetes/kubernetes#104303]
#### What happened:
Hi 👋 , I restarted kube-proxy after a change in the configmap (to expose the metrics) and the kube-proxy now won't start, telling that have too many open files. Here is the stack trace:

```
F0811 13:31:01.771818       1 server.go:488] failed complete: too many open files
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00000e001, 0xc00045c0b0, 0x52, 0xa4)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x2901ea0, 0xc000000003, 0x0, 0x0, 0xc000aeff10, 0x283bf19, 0x9, 0x1e8, 0x0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:945 +0x191
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printf(0x2901ea0, 0x3, 0x0, 0x0, 0x1ac6f6e, 0x13, 0xc000a4bd58, 0x1, 0x1)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:733 +0x17a
k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatalf(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1456
k8s.io/kubernetes/cmd/kube-proxy/app.NewProxyCommand.func1(0xc0001e6580, 0xc0002f6de0, 0x0, 0x2)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:488 +0xf4
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0001e6580, 0xc00003a1f0, 0x2, 0x2, 0xc0001e6580, 0xc00003a1f0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0001e6580, 0xc0000fe180, 0x2901a60, 0x4062c5)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:950 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:887
main.main()
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-proxy/proxy.go:48 +0x11d

goroutine 6 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2901ea0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1131 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:416 +0xd8

goroutine 130 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1b792f8, 0x1cbfac0, 0xc000478060, 0x1, 0xc00011a0c0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x149
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1b792f8, 0x12a05f200, 0x0, 0x1, 0xc00011a0c0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x1b792f8, 0x12a05f200)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81 +0x4f
created by k8s.io/kubernetes/vendor/k8s.io/component-base/logs.InitLogs
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/logs/logs.go:58 +0x8a
``` 

Here is my docker config
``` 
{"data-root": "/opt/storage/docker", "runtimes": {"nvidia": {"path": "/usr/bin/nvidia-container-runtime", "runtimeArgs": []}}, "default-runtime": "nvidia", "default-shm-size": "1G", "default-ulimits": {"memlock": {"name": "memlock", "hard": -1, "soft": -1}, "stack": {"name": "stack", "hard": 67108864, "soft": 67108864}}}
``` 

There is some open files but nothing near the limits
``` 
$ cat /proc/sys/fs/file-nr
49408   0       39177922
``` 

Thank you for any help you can provide 🙏 

#### What you expected to happen:
kube-proxy starting

#### How to reproduce it (as minimally and precisely as possible):
I reproduced using docker directly (so I could try various ulimit but it didn't fix the issue):
``` 
docker run --rm --ulimit nofile=65536:65536 -v /tmp/kube-proxy-config:/var/lib/kube-proxy -v /tmp/sa:/var/run/secrets/kubernetes.io/serviceaccount:ro -v /lib/module
s:/lib/modules:ro -v /run/xtables.lock:/run/xtables.lock k8s.gcr.io/kube-proxy:v1.19.10 /usr/local/bin/kube-proxy --config=/var/lib/kube-proxy/config.conf --hostname-override=my-hostname
``` 
You need to first get the configmap of kube-proxy and the secret containing the serviceaccount, here in /tmp

#### Anything else we need to know?:
The server is heavily loaded (we do deep learning on it 24/7) but I don't know what I can do to fix this issue.

#### Environment:
- Kubernetes version (use `kubectl version`): v1.19.10
- Cloud provider or hardware configuration: Bare metal setup (~350 Go RAM / ~40To hdd / with nvidia GPUs)
- OS (e.g: `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`): 3.10.0-1127.19.1.el7.x86_64
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): 
- Others: docker 19.03.15 using nvidia runtime

**Comment by BenTheElder** [comment]
The error message is a lie, try increasing inotify limits 🙃

Here's our entry about this for the KIND project https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files

**Comment by ClementGautier** [comment]
It worked, thank you so much !!!
