### ISSUE TITLE
UT failure: panic: duplicate metrics collector registration attempted

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#104940]
### Failure cluster [1b410c50dc9c60031af5](https://go.k8s.io/triage#1b410c50dc9c60031af5)
https://storage.googleapis.com/k8s-triage/index.html?text=prometheus

##### Error text:
**TestRecordOperation**
```
=== RUN   TestRecordOperation
--- FAIL: TestRecordOperation (0.00s)
panic: duplicate metrics collector registration attempted [recovered]
	panic: duplicate metrics collector registration attempted

goroutine 281 [running]:
testing.tRunner.func1.2({0x2b86420, 0xc000526a20})
	/usr/local/go/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1212 +0x3b6
panic({0x2b86420, 0xc000526a20})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc000164000, {0xc00081ac80, 0x1, 0x0})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus/registry.go:403 +0xa7
k8s.io/kubernetes/vendor/k8s.io/component-base/metrics.(*kubeRegistry).MustRegister(0xc000164000, {0xc00081ac70, 0x1, 0x10})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/registry.go:176 +0xcc
k8s.io/kubernetes/pkg/kubelet/kuberuntime.TestRecordOperation(0x0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/instrumented_services_test.go:33 +0xe4
testing.tRunner(0xc000602b60, 0x2e77168)
	/usr/local/go/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1306 +0x727

```

**TestRecordOperation**
```
=== RUN   TestRecordOperation
--- FAIL: TestRecordOperation (0.00s)
panic: duplicate metrics collector registration attempted [recovered]
	panic: duplicate metrics collector registration attempted

goroutine 281 [running]:
testing.tRunner.func1.2({0x2b86420, 0xc000526a20})
	/usr/local/go/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1212 +0x3b6
panic({0x2b86420, 0xc000526a20})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc000164000, {0xc00081ac80, 0x1, 0x0})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus/registry.go:403 +0xa7
k8s.io/kubernetes/vendor/k8s.io/component-base/metrics.(*kubeRegistry).MustRegister(0xc000164000, {0xc00081ac70, 0x1, 0x10})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/registry.go:176 +0xcc
k8s.io/kubernetes/pkg/kubelet/kuberuntime.TestRecordOperation(0x0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/instrumented_services_test.go:33 +0xe4
testing.tRunner(0xc000602b60, 0x2e77168)
	/usr/local/go/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1306 +0x727
```
**TestGetHistogramVecFromGatherer**

```
=== RUN   TestGetHistogramVecFromGatherer/filter_with_one_label
    --- FAIL: TestGetHistogramVecFromGatherer/filter_with_one_label (0.00s)
panic: duplicate metrics collector registration attempted [recovered]
	panic: duplicate metrics collector registration attempted

goroutine 131 [running]:
testing.tRunner.func1.2({0x9caea0, 0xc00008a7e0})
	/usr/local/go/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1212 +0x3b6
panic({0x9caea0, 0xc00008a7e0})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc000320000, {0xc000408b10, 0x1, 0x0})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus/registry.go:403 +0xa7
k8s.io/kubernetes/vendor/k8s.io/component-base/metrics.(*kubeRegistry).MustRegister(0xc000320000, {0xc000408b00, 0x1, 0x10})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/registry.go:176 +0xcc
k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/testutil.TestGetHistogramVecFromGatherer.func1.1()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/testutil/metrics_test.go:580 +0xa2
sync.(*Once).doSlow(0xc00041ab84, 0xc000078e38)
	/usr/local/go/src/sync/once.go:68 +0x128
sync.(*Once).Do(0xc00041ab84, 0xc00008a760)
	/usr/local/go/src/sync/once.go:59 +0x47
k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/testutil.TestGetHistogramVecFromGatherer.func1(0xc000419860)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/testutil/metrics_test.go:579 +0x35f
testing.tRunner(0xc000419860, 0xc0001415a8)
	/usr/local/go/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1306 +0x727
```

#### Recent failures:
[2021/9/4 上午2:00:19 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1433851876134096896)
[2021/9/3 下午8:00:05 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1433761222271963136)
[2021/9/3 下午2:00:15 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1433670624454119424)
[2021/9/3 上午7:59:43 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1433580026854379520)
[2021/9/3 上午1:59:22 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1433489204028903424)

/kind failing-test

/sig testing

This may be related with  https://github.com/prometheus/client_golang/issues/716 \  https://github.com/prometheus/client_golang/issues/733

**Comment by pacoxu** [comment]
/assign
I will do some initial research on this.

**Comment by ehashman** [comment]
/triage accepted
/assign @pacoxu
cc @catherinef-dev

**Comment by pacoxu** [comment]
To fix it gracefully, we may refactor the code in `vendor/k8s.io/component-base/metrics` like 
https://github.com/eh-am/pyroscope/commit/70733d11e3e09824b78879d17f518cabdb7a1dd7
https://github.com/pyroscope-io/pyroscope/pull/335/files

#105223 is another try to ignore the dup error in `MustRegister` but it is odd as `MustRegister` should panic as designed if one register failed.

**Comment by CatherineF-dev** [comment]
Three testings failed due to `panic: duplicate metrics collector registration attempted`.  Haven't found package promauto (https://github.com/prometheus/client_golang/issues/716#issuecomment-590282553) being used in these testings. It might be other issues.

These testings are:
1. TestGetHistogramVecFromGatherer/filter_with_one_label
2. TestRecordOperation
3. TestSampler

**Comment by pacoxu** [comment]
> What are you guys doing here? What test is this? You cannot change the component-base metrics code base it is doing what it is supposed to be doing. Does this test suite involve multiple sequential runs of the same test?

@logicalhan I think this is odd to change the component-base metrics code base.  But the refactor to use `promauto.With(reg).NewCounter` is another approach.

You can try to reproduce it with
```
 make test KUBE_RACE=-race KUBE_TIMEOUT=--timeout=600s GOFLAGS=-count=10 WHAT=./vendor/k8s.io/apiserver/pkg/util/flowcontrol/metrics/
```
`ci-kubernetes-generate-make-test-count10` is with `GOFLAGS=-count=10 `
