### ISSUE TITLE
queueSet.findDispatchQueueLocked() possibly panics

### ISSUE THREAD

**Issue by microyahoo** [kubernetes/kubernetes#105338]
https://github.com/kubernetes/kubernetes/blob/32fefd5580cc849dba50e25e92a093046e042c8b/staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go#L725

#### What happened:
```
E0929 15:10:50.948959   72105 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 2871 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x57a2e60, 0x8a813e0})
	/root/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x105
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0})
	/root/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0xce
panic({0x57a2e60, 0x8a813e0})
	/usr/local/go/src/runtime/panic.go:1047 +0x262
k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset.(*queueSet).findDispatchQueueLocked(0xc00c83def0)
	/root/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go:725 +0x607
k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset.(*queueSet).dispatchLocked(0xc00c83def0)
	/root/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go:633 +0x45
k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset.(*queueSet).dispatchAsMuchAsPossibleLocked(0xc00c83def0)
	/root/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go:594 +0x68
k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset.(*queueSet).setConfiguration(0xc00c83def0, {{0xc005cb89a8, 0x6}, 0x40, 0x32, 0x6, 0x37e11d600}, 0xc005704b90, {0x4a})
	/root/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go:242 +0x45b
k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset.(*queueSetCompleter).Complete(0xc0053e29a0, {0x4a})
	/root/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go:185 +0x31d
k8s.io/apiserver/pkg/util/flowcontrol.(*cfgMeal).finishQueueSetReconfigsLocked(0xc00decd3e0)
	/root/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go:683 +0x7cf
k8s.io/apiserver/pkg/util/flowcontrol.(*configController).lockAndDigestConfigObjects(0xc000923d40, {0xc006156440, 0x8, 0x8}, {0xc0102f3e80, 0xc, 0x10})
	/root/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go:523 +0x246
k8s.io/apiserver/pkg/util/flowcontrol.(*configController).digestConfigObjects(0xc000923d40, {0xc006156440, 0x8, 0x8}, {0xc0102f3e80, 0xc, 0x10})
	/root/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go:416 +0xb3
k8s.io/apiserver/pkg/util/flowcontrol.(*configController).syncOne(0xc000923d40)
	/root/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go:374 +0x61d
k8s.io/apiserver/pkg/util/flowcontrol.(*configController).processNextWorkItem.func1(0xc000923d40, {0x542b320, 0x650d210})
	/root/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go:344 +0x145
k8s.io/apiserver/pkg/util/flowcontrol.(*configController).processNextWorkItem(0xc000923d40)
	/root/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go:354 +0x98
k8s.io/apiserver/pkg/util/flowcontrol.(*configController).runWorker(0xc000923d40)
	/root/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go:330 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00874d0d0)
	/root/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0xbc
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00874d0d0, {0x653fca0, 0xc00aaf1890}, 0x1, 0xc00056e8a0)
	/root/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xc9
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00874d0d0, 0x3b9aca00, 0x0, 0x1, 0xc00056e8a0)
	/root/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x85
k8s.io/apimachinery/pkg/util/wait.Until(0xc00874d0d0, 0x3b9aca00, 0xc00056e8a0)
	/root/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x33
created by k8s.io/apiserver/pkg/util/flowcontrol.(*configController).Run
	/root/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go:319 +0x46e
> [unrecovered-panic] runtime.fatalpanic() /usr/local/go/src/runtime/panic.go:1271 (hits goroutine(2871):1 total:1) (PC: 0x43bf00)
Warning: debugging optimized function
	runtime.curg._panic.arg: interface {}(string) "runtime error: invalid memory address or nil pointer dereference"

```
#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux glusterfs-1.deeproute.ai 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
Something is violating locking or counting discipline.
Perhaps some cheap sanity checks on counts (like, never negative) would at least confirm that this is where the problem lies.
The needed discipline is very mechanical.  A careful read of all the code should find any violations.

**Comment by MikeSpreitzer** [comment]
Also, we could make queueSet::UpdateObservations check that the queueSet has the right sums over its queues (under the queueSet lock, of course).  I think it is called infrequently enough for that to be tolerable.  The point would be to reveal something to us developers.

We could even make it do repair if an error is found; this would not really solve the problem, of course, but might make a helpful reduction in the severity of the symptoms.

**Comment by MikeSpreitzer** [comment]
Also, the some comments on the fields in `queueSet` are outdated, they reference a now-non-existent field `config`.

**Comment by microyahoo** [comment]
@MikeSpreitzer Thanks for your investigation. I still have some confusions need your clarification.
1. Will the above issue occur under what conditions? As far as I know, `request.decision` will be set to `decisionCancel` just at the stage of `req.decision.Get()` for timeout, and this occurs at the `request.Finish`, but `dispatchAsMuchAsPossibleLocked` will set decision prior to this and decision can only be set once.
2. If two identical requests arrive at the same apiserver almost at the same time, what will happen and how to deal with it?

**Comment by MikeSpreitzer** [comment]
1. A given particular request X might not get dispatched during its `queueSet::StartRequest`; request X might have to wait a while if there are not enough seats available at the moment.  The goroutine that calls `queueSet::StartRequest` for X then proceeds to call `request::Finish`, which calls `request::wait` --- and that calls the `Get` method of X's `decision`.  If X's context times out or is cancelled before X is dispatched or rejected by APF logic then X's `decision` gets set to `decisionCancel`.
2. I hope my answer to 1. also answers this.
3. I am not sure I understand what potential problem you are thinking about here.  Each request is a distinct `*http.Request`, even if the client and request message are identical.  In turn, each request gets a distinct `*queueset.request`.

**Comment by microyahoo** [comment]
Thank you for your clarification. 
Aout question 2, I mean the `WriteOnce` has been set to `decisionExecute`, the setting of `decisionCancel` will no longer work. maybe nil is better.
