### ISSUE TITLE
etcd running but rejected connection from "192.168.7.175:53382" (error "remote error: tls: bad certificate", ServerName "")

### ISSUE THREAD

**Issue by jiangxiaobin96** [kubernetes/kubernetes#106407]
### What happened?

- etcd
etcd is running successfully.
```
[root@k8s-01 home]# systemctl status etcd
● etcd.service - Etcd Server
   Loaded: loaded (/etc/systemd/system/etcd.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2021-11-14 15:47:28 CST; 1h 22min ago
     Docs: https://github.com/coreos
 Main PID: 1817 (etcd)
    Tasks: 8
   Memory: 22.4M
   CGroup: /system.slice/etcd.service
           └─1817 /opt/k8s/bin/etcd --data-dir=/data/k8s/etcd/data --wal-dir=/data/k8s/etcd/wal --name=k8s-01 --cert-file=/etc/etcd/cert/etcd.pem --key-file=/etc/etcd/cert/etcd-key.pem --trus>

Nov 14 15:47:28 k8s-01 etcd[1817]: setting up the initial cluster version to 3.5
Nov 14 15:47:28 k8s-01 systemd[1]: Started Etcd Server.
Nov 14 15:47:28 k8s-01 etcd[1817]: serving client requests on 192.168.7.175:2379
Nov 14 15:47:28 k8s-01 etcd[1817]: set the initial cluster version to 3.5
Nov 14 15:47:28 k8s-01 etcd[1817]: enabled capabilities for version 3.5
Nov 14 16:47:27 k8s-01 etcd[1817]: Starting auto-compaction at revision 1 (retention: 1h0m0s)
Nov 14 16:47:27 k8s-01 etcd[1817]: store.index: compact 1
Nov 14 16:47:27 k8s-01 etcd[1817]: Finished auto-compaction at revision 1
Nov 14 16:47:27 k8s-01 etcd[1817]: finished scheduled compaction at 1 (took 12.669932ms)
Nov 14 16:51:39 k8s-01 etcd[1817]: read-only range request "key:\"/registry/serviceaccounts/\" range_end:\"/registry/serviceaccounts0\" limit:10000 " with result "range_response_count:0 size:>
```
- kube-apiserver
kube-apiserver can not start normally.
```
Nov 17 14:44:05 k8s-01 etcd[14827]: {"level":"warn","ts":"2021-11-17T14:44:05.786+0800","caller":"embed/config_logging.go:186","msg":"rejected connection","remote-addr":"192.168>
Nov 17 14:44:07 k8s-01 etcd[14827]: {"level":"warn","ts":"2021-11-17T14:44:07.926+0800","caller":"embed/config_logging.go:186","msg":"rejected connection","remote-addr":"192.168>
Nov 17 14:44:07 k8s-01 kube-apiserver[15035]: W1117 14:44:07.933170   15035 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://192.168.7.175:2379 0>
Nov 17 14:44:09 k8s-01 kube-apiserver[15035]: W1117 14:44:09.241405   15035 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://192.168.7.175:2379 0>
Nov 17 14:44:09 k8s-01 etcd[14827]: {"level":"warn","ts":"2021-11-17T14:44:09.246+0800","caller":"embed/config_logging.go:186","msg":"rejected connection","remote-addr":"192.168>
Nov 17 14:44:12 k8s-01 kube-apiserver[15035]: W1117 14:44:12.778592   15035 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://192.168.7.175:2379 0>
Nov 17 14:44:12 k8s-01 etcd[14827]: {"level":"warn","ts":"2021-11-17T14:44:12.785+0800","caller":"embed/config_logging.go:186","msg":"rejected connection","remote-addr":"192.168>
Nov 17 14:44:13 k8s-01 kube-apiserver[15035]: W1117 14:44:13.727224   15035 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://192.168.7.175:2379 0>
Nov 17 14:44:13 k8s-01 etcd[14827]: {"level":"warn","ts":"2021-11-17T14:44:13.728+0800","caller":"embed/config_logging.go:186","msg":"rejected connection","remote-addr":"192.168>
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]: panic: context deadline exceeded
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]: goroutine 1 [running]:
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]: k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresourcedefinition.NewREST(0x3fc81b6070, {0x3e2b4e0, 0x3>
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]:         /home/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresourcede>
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]: k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver.completedConfig.New({{0x3fc866d8d8}, 0x3fc81e72c8}, {0x3f2c30>
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]:         /home/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go:14>
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]: k8s.io/kubernetes/cmd/kube-apiserver/app.createAPIExtensionsServer(0x3fc81e72c0, {0x3f2c300, 0x61e52a8})
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]:         /home/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/apiextensions.go:102 +0x58
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]: k8s.io/kubernetes/cmd/kube-apiserver/app.CreateServerChain({0x3fc8336000}, 0x3fc808bc80)
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]:         /home/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:183 +0x1bc
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]: k8s.io/kubernetes/cmd/kube-apiserver/app.Run({0x3fc8336000}, 0x3fc808bc80)
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]:         /home/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:152 +0xc4
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]: k8s.io/kubernetes/cmd/kube-apiserver/app.NewAPIServerCommand.func1(0x3fc8471900, {0x3fc8700000, 0x0, 0x34})
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]:         /home/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:119 +0x104
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0x3fc8471900, {0x3fc804a390, 0x34, 0x37})
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]:         /home/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:826 +0x6cc
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x3fc8471900)
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]:         /home/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914 +0x398
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]:         /home/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]: main.main()
Nov 17 14:44:20 k8s-01 kube-apiserver[15035]:         _output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/apiserver.go:43 +0x11c
Nov 17 14:44:20 k8s-01 etcd[14827]: {"level":"warn","ts":"2021-11-17T14:44:20.510+0800","caller":"embed/config_logging.go:186","msg":"rejected connection","remote-addr":"192.168>
Nov 17 14:44:20 k8s-01 systemd[1]: kube-apiserver.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- An ExecStart= process belonging to unit kube-apiserver.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 2.
Nov 17 14:44:20 k8s-01 systemd[1]: kube-apiserver.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- The unit kube-apiserver.service has entered the 'failed' state with result 'exit-code'.
Nov 17 14:44:20 k8s-01 systemd[1]: Failed to start Kubernetes API Server.
-- Subject: A start job for unit kube-apiserver.service has failed
```

I'm following the course "Kubernetes The Hard Way" to deploy the k8s and met the above error when deploy kube-apiserver.
All my binary files build from source code.
I think there may be something lost when deployment. But I can not identify the error.

### What did you expect to happen?

succeed in deploying kube-apiserver

### How can we reproduce it (as minimally and precisely as possible)?

I deploy k8s on my RISCV development board.

### Kubernetes version

The kubernetes is v1.17.0 based on [riscv64](https://github.com/carlosedp/kubernetes/tree/riscv64_build)
The deployment refer to "Kubernetes The Hard Way" using binary file.

### Cloud provider

none

### OS version

```
[root@k8s-01 home]# uname -a
Linux k8s-01 5.4.61 #20 SMP Thu Aug 26 11:50:01 CST 2021 riscv64 riscv64 riscv64 GNU/Linux
```

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jiangxiaobin96** [comment]
I add more information.
Verification of etcd:
```
[root@k8s-01 cert]# ETCDCTL_API=3 etcdctl member list   --endpoints=https://127.0.0.1:2379   --cacert=/opt/k8s/work/ca.pem   --cert=/etc/etcd/cert/etcd.pem   --key=/etc/etcd/cert/etcd-key.pem
ac81b5d3343b8bcd, started, k8s-01, https://192.168.7.175:2380, https://192.168.7.175:2379, false
[root@k8s-01 cert]# for node_ip in ${NODE_IPS[@]}
>   do
>     echo ">>> ${node_ip}"
>     /opt/k8s/bin/etcdctl \
>     --endpoints=https://${node_ip}:2379 \
>     --cacert=/etc/kubernetes/cert/ca.pem \
>     --cert=/etc/etcd/cert/etcd.pem \
>     --key=/etc/etcd/cert/etcd-key.pem endpoint health
>   done
>>> 192.168.7.175
https://192.168.7.175:2379 is healthy: successfully committed proposal: took = 1.039731854s
[root@k8s-01 cert]# /opt/k8s/bin/etcdctl \
>   -w table --cacert=/etc/kubernetes/cert/ca.pem \
>   --cert=/etc/etcd/cert/etcd.pem \
>   --key=/etc/etcd/cert/etcd-key.pem \
>   --endpoints=${ETCD_ENDPOINTS} endpoint status
+----------------------------+------------------+-----------+---------+-----------+------------+-----------+------------+--------------------+--------+
|          ENDPOINT          |        ID        |  VERSION  | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+----------------------------+------------------+-----------+---------+-----------+------------+-----------+------------+--------------------+--------+
| https://192.168.7.175:2379 | ac81b5d3343b8bcd | 3.5.0-pre |   20 kB |      true |      false |         5 |         31 |                 31 |        |
+----------------------------+------------------+-----------+---------+-----------+------------+-----------+------------+--------------------+--------+
```
and the network port is 
```
[root@k8s-01 cert]# netstat -lnpt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 192.168.7.175:6443      0.0.0.0:*               LISTEN      8749/kube-apiserver
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1430/sshd
tcp        0      0 127.0.0.1:34679         0.0.0.0:*               LISTEN      7006/containerd
tcp6       0      0 :::2379                 :::*                    LISTEN      8373/etcd
tcp6       0      0 :::2380                 :::*                    LISTEN      8373/etcd
tcp6       0      0 :::22                   :::*                    LISTEN      1430/sshd
```

**Comment by jiangxiaobin96** [comment]
However `journalctl -u etcd`  seems have some problems.
```
Nov 15 12:53:23 k8s-01 etcd[1469]: rejected connection from "192.168.7.175:53382" (error "remote error: tls: bad certificate", ServerName "")
Nov 15 12:53:24 k8s-01 etcd[1469]: rejected connection from "192.168.7.175:53390" (error "remote error: tls: bad certificate", ServerName "")
Nov 15 12:53:26 k8s-01 etcd[1469]: rejected connection from "192.168.7.175:53396" (error "EOF", ServerName "")
Nov 15 12:56:22 k8s-01 etcd[1469]: rejected connection from "192.168.7.175:53560" (error "remote error: tls: bad certificate", ServerName "")
Nov 15 12:56:24 k8s-01 etcd[1469]: rejected connection from "192.168.7.175:53562" (error "remote error: tls: bad certificate", ServerName "")
Nov 15 12:56:26 k8s-01 etcd[1469]: rejected connection from "192.168.7.175:53564" (error "remote error: tls: bad certificate", ServerName "")
Nov 15 13:06:18 k8s-01 etcd[1469]: rejected connection from "192.168.7.175:54188" (error "remote error: tls: bad certificate", ServerName "")
Nov 15 13:06:19 k8s-01 etcd[1469]: rejected connection from "192.168.7.175:54194" (error "remote error: tls: bad certificate", ServerName "")
Nov 15 13:08:38 k8s-01 etcd[1469]: rejected connection from "192.168.7.175:54278" (error "remote error: tls: bad certificate", ServerName "")
Nov 15 13:08:39 k8s-01 etcd[1469]: rejected connection from "192.168.7.175:54280" (error "remote error: tls: bad certificate", ServerName "")
Nov 15 13:08:41 k8s-01 etcd[1469]: rejected connection from "192.168.7.175:54282" (error "remote error: tls: bad certificate", ServerName "")
Nov 15 13:17:52 k8s-01 etcd[1469]: rejected connection from "192.168.7.175:54810" (error "remote error: tls: bad certificate", ServerName "")
Nov 15 13:17:54 k8s-01 etcd[1469]: rejected connection from "192.168.7.175:54812" (error "remote error: tls: bad certificate", ServerName "")
Nov 15 13:19:56 k8s-01 systemd[1]: etcd.service: Current command vanished from the unit file, execution of the command list won't be resumed.
```

**Comment by jiangxiaobin96** [comment]
[#2669](https://github.com/rancher/rke/issues/2669) it seems the same question.

**Comment by jiangxiaobin96** [comment]
I searched other solution and shown that it may be caused by  certificate time conflict. But I just have one machine as a master node. The certificate time is similar to the server time.

**Comment by jiangxiaobin96** [comment]
the [#10608](https://github.com/etcd-io/etcd/issues/10608) is similar, so i changed my etcd.service as followed.
```
[Unit]
Description=Etcd Server
After=network.target
After=network-online.target
Wants=network-online.target
Documentation=https://github.com/coreos

[Service]
Type=notify
WorkingDirectory=/data/k8s/etcd/data
ExecStart=/opt/k8s/bin/etcd \
  --data-dir=/data/k8s/etcd/data \
  --wal-dir=/data/k8s/etcd/wal \
  --name=k8s-01 \
  --cert-file=/etc/etcd/cert/etcd.pem \
  --key-file=/etc/etcd/cert/etcd-key.pem \
  --trusted-ca-file=/etc/kubernetes/cert/ca.pem \
  --peer-cert-file=/etc/etcd/cert/etcd.pem \
  --peer-key-file=/etc/etcd/cert/etcd-key.pem \
  --peer-trusted-ca-file=/etc/kubernetes/cert/ca.pem \
  --peer-client-cert-auth \
  --client-cert-auth \
  --listen-peer-urls=https://0.0.0.0:2380 \
  --initial-advertise-peer-urls=https://k8s-01:2380 \
  --listen-client-urls=https://0.0.0.0:2379 \
  --advertise-client-urls=https://k8s-01:2379 \
  --initial-cluster-token=etcd-cluster-0 \
  --initial-cluster=k8s-01=https://192.168.7.175:2380 \
  --initial-cluster-state=new \
  --auto-compaction-mode=periodic \
  --auto-compaction-retention=1 \
  --max-request-bytes=33554432 \
  --quota-backend-bytes=6442450944 \
  --heartbeat-interval=250 \
  --election-timeout=2000 \
  --v=5
Restart=on-failure
RestartSec=5
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
```

**Comment by jiangxiaobin96** [comment]
the [#10608](https://github.com/etcd-io/etcd/issues/10608) is similar, so i changed my etcd.service as followed.
```
[Unit]
Description=Etcd Server
After=network.target
After=network-online.target
Wants=network-online.target
Documentation=https://github.com/coreos

[Service]
Type=notify
WorkingDirectory=/data/k8s/etcd/data
ExecStart=/opt/k8s/bin/etcd \
  --data-dir=/data/k8s/etcd/data \
  --wal-dir=/data/k8s/etcd/wal \
  --name=k8s-01 \
  --cert-file=/etc/etcd/cert/etcd.pem \
  --key-file=/etc/etcd/cert/etcd-key.pem \
  --trusted-ca-file=/etc/kubernetes/cert/ca.pem \
  --peer-cert-file=/etc/etcd/cert/etcd.pem \
  --peer-key-file=/etc/etcd/cert/etcd-key.pem \
  --peer-trusted-ca-file=/etc/kubernetes/cert/ca.pem \
  --peer-client-cert-auth \
  --client-cert-auth \
  --listen-peer-urls=https://0.0.0.0:2380 \
  --initial-advertise-peer-urls=https://k8s-01:2380 \
  --listen-client-urls=https://0.0.0.0:2379 \
  --advertise-client-urls=https://k8s-01:2379 \
  --initial-cluster-token=etcd-cluster-0 \
  --initial-cluster=k8s-01=https://192.168.7.175:2380 \
  --initial-cluster-state=new \
  --auto-compaction-mode=periodic \
  --auto-compaction-retention=1 \
  --max-request-bytes=33554432 \
  --quota-backend-bytes=6442450944 \
  --heartbeat-interval=250 \
  --election-timeout=2000 \
  --v=5
Restart=on-failure
RestartSec=5
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
```
