### ISSUE TITLE
kube-apiserver panics with "Header called after Handler finished" when health probes time out

### ISSUE THREAD

**Issue by tkashem** [kubernetes/kubernetes#106717]
### What happened?

`kube-apiserver` panics with `Header called after Handler finished` error when health probes time out. 

The following stack trace shows this error (from an apiserver that uses `1.21.0`:
```
E1012 19:59:23.879476       1 timeout.go:128] Header called after Handler finished
goroutine 509 [running]:
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc000e9f140)
	k8s.io/apiserver@v0.21.0/pkg/server/filters/timeout.go:102 +0x125
panic(0x220fa60, 0x2908620)
	runtime/panic.go:965 +0x1b9
golang.org/x/net/http2.(*responseWriter).Header(0xc0005fc658, 0x3941100)
	golang.org/x/net@v0.0.0-20210224082022-3d97a244fca7/http2/server.go:2601 +0x99
net/http.Error(0x2969fc0, 0xc0005fc658, 0xc00120a380, 0x1ad, 0x1f4)
	net/http/server.go:2059 +0x3b
k8s.io/apiserver/pkg/server/healthz.handleRootHealth.func1(0x29747f0, 0xc0005ab4e8, 0xc00024d100)
	k8s.io/apiserver@v0.21.0/pkg/server/healthz/healthz.go:245 +0x6c5
k8s.io/apiserver/pkg/endpoints/metrics.InstrumentHandlerFunc.func1(0x7ff4900e5018, 0xc0005fc660, 0xc00024d100)
	k8s.io/apiserver@v0.21.0/pkg/endpoints/metrics/metrics.go:453 +0x2be
net/http.HandlerFunc.ServeHTTP(0xc0006a21e0, 0x7ff4900e5018, 0xc0005fc660, 0xc00024d100)
	net/http/server.go:2049 +0x44
k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc0010b8940, 0x7ff4900e5018, 0xc0005fc660, 0xc00024d100)
	k8s.io/apiserver@v0.21.0/pkg/server/mux/pathrecorder.go:241 +0x77a
k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc00040aa80, 0x7ff4900e5018, 0xc0005fc660, 0xc00024d100)
	k8s.io/apiserver@v0.21.0/pkg/server/mux/pathrecorder.go:234 +0x8c
k8s.io/apiserver/pkg/server.director.ServeHTTP(0x261c5f1, 0xf, 0xc0013733b0, 0xc00040aa80, 0x7ff4900e5018, 0xc0005fc660, 0xc00024d100)
	k8s.io/apiserver@v0.21.0/pkg/server/handler.go:154 +0x914
k8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1(0x7ff4900e5018, 0xc0005fc660, 0xc00024d100)
	k8s.io/apiserver@v0.21.0/pkg/endpoints/filterlatency/filterlatency.go:95 +0x193
net/http.HandlerFunc.ServeHTTP(0xc0014456e0, 0x7ff4900e5018, 0xc0005fc660, 0xc00024d100)
	net/http/server.go:2049 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7ff4900e5018, 0xc0005fc660, 0xc00024d100)
	k8s.io/apiserver@v0.21.0/pkg/endpoints/filters/authorization.go:64 +0x603
net/http.HandlerFunc.ServeHTTP(0xc0014584c0, 0x7ff4900e5018, 0xc0005fc660, 0xc00024d100)
	net/http/server.go:2049 +0x44
k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1(0x7ff4900e5018, 0xc0005fc660, 0xc00024d100)
	k8s.io/apiserver@v0.21.0/pkg/endpoints/filterlatency/filterlatency.go:71 +0x186
net/http.HandlerFunc.ServeHTTP(0xc001458500, 0x7ff4900e5018, 0xc0005fc660, 0xc00024d100)
	net/http/server.go:2049 +0x44
k8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1(0x7ff4900e5018, 0xc0005fc660, 0xc00024d100)
	k8s.io/apiserver@v0.21.0/pkg/endpoints/filterlatency/filterlatency.go:95 +0x193
net/http.HandlerFunc.ServeHTTP(0xc001445710, 0x7ff4900e5018, 0xc0005fc660, 0xc00024d100)
	net/http/server.go:2049 +0x44
k8s.io/apiserver/pkg/server/filters.WithPriorityAndFairness.func1.4()
	k8s.io/apiserver@v0.21.0/pkg/server/filters/priority-and-fairness.go:127 +0x1ba
k8s.io/apiserver/pkg/util/flowcontrol.(*configController).Handle.func2()
	k8s.io/apiserver@v0.21.0/pkg/util/flowcontrol/apf_filter.go:176 +0x222
k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset.(*request).Finish.func1(0xc0015fc000, 0xc001a78b7f, 0xc00013aaf0)
	k8s.io/apiserver@v0.21.0/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go:329 +0x62
k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset.(*request).Finish(0xc0015fc000, 0xc00013aaf0, 0xc0015e04e0)
	k8s.io/apiserver@v0.21.0/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go:330 +0x5d
k8s.io/apiserver/pkg/util/flowcontrol.(*configController).Handle(0xc00024c600, 0x297a2f8, 0xc00135ec00, 0xc001c7a630, 0x297a8e0, 0xc001c5e680, 0xc001c5af90, 0xc001c5afa0, 0xc001383260)
	k8s.io/apiserver@v0.21.0/pkg/util/flowcontrol/apf_filter.go:166 +0x907
k8s.io/apiserver/pkg/server/filters.WithPriorityAndFairness.func1(0x7ff4900e5018, 0xc0005fc660, 0xc0003eb500)
	k8s.io/apiserver@v0.21.0/pkg/server/filters/priority-and-fairness.go:130 +0x606
net/http.HandlerFunc.ServeHTTP(0xc001445740, 0x7ff4900e5018, 0xc0005fc660, 0xc0003eb500)
	net/http/server.go:2049 +0x44
k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1(0x7ff4900e5018, 0xc0005fc660, 0xc0003eb500)
	k8s.io/apiserver@v0.21.0/pkg/endpoints/filterlatency/filterlatency.go:71 +0x186
net/http.HandlerFunc.ServeHTTP(0xc001458540, 0x7ff4900e5018, 0xc0005fc660, 0xc0003eb500)
	net/http/server.go:2049 +0x44
k8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1(0x7ff4900e5018, 0xc0005fc660, 0xc0003eb500)
	k8s.io/apiserver@v0.21.0/pkg/endpoints/filterlatency/filterlatency.go:95 +0x193
net/http.HandlerFunc.ServeHTTP(0xc001445770, 0x7ff4900e5018, 0xc0005fc660, 0xc0003eb500)
	net/http/server.go:2049 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7ff4900e5018, 0xc0005fc660, 0xc0003eb500)
	k8s.io/apiserver@v0.21.0/pkg/endpoints/filters/impersonation.go:50 +0x240d
net/http.HandlerFunc.ServeHTTP(0xc001458580, 0x7ff4900e5018, 0xc0005fc660, 0xc0003eb500)
	net/http/server.go:2049 +0x44
k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1(0x7ff4900e5018, 0xc0005fc660, 0xc0003eb500)
	k8s.io/apiserver@v0.21.0/pkg/endpoints/filterlatency/filterlatency.go:71 +0x186
net/http.HandlerFunc.ServeHTTP(0xc0014585c0, 0x7ff4900e5018, 0xc0005fc660, 0xc0003eb500)
	net/http/server.go:2049 +0x44
k8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1(0x7ff4900e5018, 0xc0005fc660, 0xc0003eb500)
	k8s.io/apiserver@v0.21.0/pkg/endpoints/filterlatency/filterlatency.go:95 +0x193
net/http.HandlerFunc.ServeHTTP(0xc0014457a0, 0x7ff4900e5018, 0xc0005fc660, 0xc0003eb500)
	net/http/server.go:2049 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithAudit.func1(0x7ff4900e5018, 0xc0005fc660, 0xc0003eb500)
	k8s.io/apiserver@v0.21.0/pkg/endpoints/filters/audit.go:55 +0x7d5
net/http.HandlerFunc.ServeHTTP(0xc001458600, 0x7ff4900e5018, 0xc0005fc660, 0xc0003eb500)
	net/http/server.go:2049 +0x44
k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1(0x7ff4900e5018, 0xc0005fc660, 0xc0003eb500)
	k8s.io/apiserver@v0.21.0/pkg/endpoints/filterlatency/filterlatency.go:71 +0x186
net/http.HandlerFunc.ServeHTTP(0xc001458640, 0x7ff4900e5018, 0xc0005fc660, 0xc0003eb500)
	net/http/server.go:2049 +0x44
k8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1(0x7ff4900e5018, 0xc0005fc660, 0xc0003eb500)
	k8s.io/apiserver@v0.21.0/pkg/endpoints/filterlatency/filterlatency.go:95 +0x193
net/http.HandlerFunc.ServeHTTP(0xc001445800, 0x7ff4900e5018, 0xc0005fc660, 0xc0003eb500)
	net/http/server.go:2049 +0x44
k8s.io/apiserver/pkg/endpoints/filters.withAuthentication.func1(0x7ff4900e5018, 0xc0005fc660, 0xc0003eb500)
	k8s.io/apiserver@v0.21.0/pkg/endpoints/filters/authentication.go:80 +0x75c
net/http.HandlerFunc.ServeHTTP(0xc001429d40, 0x7ff4900e5018, 0xc0005fc660, 0xc0003eb400)
	net/http/server.go:2049 +0x44
k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1(0x7ff4900e5018, 0xc0005fc660, 0xc0003eb300)
	k8s.io/apiserver@v0.21.0/pkg/endpoints/filterlatency/filterlatency.go:80 +0x38c
net/http.HandlerFunc.ServeHTTP(0xc0014586c0, 0x7ff4900e5018, 0xc0005fc660, 0xc0003eb300)
	net/http/server.go:2049 +0x44
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc000e9f140, 0xc0004d8480, 0x297a988, 0xc0005fc660, 0xc0003eb300)
	k8s.io/apiserver@v0.21.0/pkg/server/filters/timeout.go:107 +0xb8
created by k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	k8s.io/apiserver@v0.21.0/pkg/server/filters/timeout.go:93 +0x1f4
``` 

The `Header called after Handler finished` is thrown by net/http because `handleRootHealth` attempts to call `http.ResponseWriter.Header` after the request had timed out (handler had completed)

here is the code site that triggers the panic (on master):
https://github.com/kubernetes/kubernetes/blob/efa9029a0db2fa8e97dd6f54d92370f0a8c74187/staging/src/k8s.io/apiserver/pkg/server/healthz/healthz.go#L258

Is there any historical context why we use the original `ResponseWriter` by calling `responsewriter.GetOriginal(w)`. If we use the decorated `ResponseWriter` object then the panic will be prevented:
https://github.com/kubernetes/kubernetes/blob/efa9029a0db2fa8e97dd6f54d92370f0a8c74187/staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go#L177-L186

`baseTimeoutWriter` uses the underlying `ResponseWriter` object only when the request handler has not completed yet.

### What did you expect to happen?

No `Header called after Handler finished` panic

### How can we reproduce it (as minimally and precisely as possible)?
hard to reproduce, maybe we should add a unit test to reproduce the issue.

**Comment by tkashem** [comment]
/sig api-machinery
cc @p0lyn0mial
