### ISSUE TITLE
Windows capz [It] ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/kubernetes#107114]
### Which jobs are flaking?

pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts

### Which tests are flaking?

Kubernetes e2e suite: [sig-auth] ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance] 

### Since when has it been flaking?

failure seen today

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1932/pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts/1471937505442926592

### Reason for failure (if possible)

```
Dec 17 20:47:07.885: INFO: Pod "oidc-discovery-validator": Phase="Failed", Reason="", readiness=false. Elapsed: 14.83817536s
Dec 17 20:47:37.886: INFO: polling logs
Dec 17 20:47:38.013: INFO: Pod logs: 
2021/12/17 20:47:03 OK: Got token
2021/12/17 20:47:04 validating with in-cluster discovery
2021/12/17 20:47:04 OK: got issuer https://kubernetes.default.svc.cluster.local
2021/12/17 20:47:04 Full, not-validated claims: 
openidmetadata.claims{Claims:jwt.Claims{Issuer:"https://kubernetes.default.svc.cluster.local", Subject:"system:serviceaccount:svcaccounts-7205:default", Audience:jwt.Audience{"oidc-discovery-test"}, Expiry:1639774613, NotBefore:1639774013, IssuedAt:1639774013, ID:""}, Kubernetes:openidmetadata.kubeClaims{Namespace:"svcaccounts-7205", ServiceAccount:openidmetadata.kubeName{Name:"default", UID:"1ec407be-5355-4910-9c49-aec549581462"}}}
2021/12/17 20:47:04 Ensuring Windows DNS availability
2021/12/17 20:47:04 OK: Resolved host kubernetes.default.svc.cluster.local: [10.96.0.1]
2021/12/17 20:47:04 OK: Constructed OIDC provider for issuer https://kubernetes.default.svc.cluster.local
2021/12/17 20:47:04 failed to validate with in-cluster discovery: failed to verify signature: fetching keys oidc: get keys failed Get "https://10.0.0.4:6443/openid/v1/jwks": dial tcp 10.0.0.4:6443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.
2021/12/17 20:47:04 falling back to validating with external discovery
2021/12/17 20:47:04 OK: got issuer https://kubernetes.default.svc.cluster.local
2021/12/17 20:47:04 Full, not-validated claims: 
openidmetadata.claims{Claims:jwt.Claims{Issuer:"https://kubernetes.default.svc.cluster.local", Subject:"system:serviceaccount:svcaccounts-7205:default", Audience:jwt.Audience{"oidc-discovery-test"}, Expiry:1639774613, NotBefore:1639774013, IssuedAt:1639774013, ID:""}, Kubernetes:openidmetadata.kubeClaims{Namespace:"svcaccounts-7205", ServiceAccount:openidmetadata.kubeName{Name:"default", UID:"1ec407be-5355-4910-9c49-aec549581462"}}}
2021/12/17 20:47:04 Ensuring Windows DNS availability
2021/12/17 20:47:04 OK: Resolved host kubernetes.default.svc.cluster.local: [10.96.0.1]
2021/12/17 20:47:05 Get "https://kubernetes.default.svc.cluster.local/.well-known/openid-configuration": x509: certificate signed by unknown authority
```

```
Dec 17 20:47:38.222: INFO: At 2021-12-17 20:46:53 +0000 UTC - event for oidc-discovery-validator: {default-scheduler } Scheduled: Successfully assigned svcaccounts-7205/oidc-discovery-validator to capz-conf-d6ml5
Dec 17 20:47:38.222: INFO: At 2021-12-17 20:47:01 +0000 UTC - event for oidc-discovery-validator: {kubelet capz-conf-d6ml5} Pulled: Container image "k8s.gcr.io/e2e-test-images/agnhost:2.33" already present on machine
Dec 17 20:47:38.222: INFO: At 2021-12-17 20:47:01 +0000 UTC - event for oidc-discovery-validator: {kubelet capz-conf-d6ml5} Created: Created container oidc-discovery-validator
Dec 17 20:47:38.222: INFO: At 2021-12-17 20:47:03 +0000 UTC - event for oidc-discovery-validator: {kubelet capz-conf-d6ml5} Started: Started container oidc-discovery-validator
Dec 17 20:47:38.222: INFO: At 2021-12-17 20:47:07 +0000 UTC - event for oidc-discovery-validator: {kubelet capz-conf-d6ml5} FailedMount: MountVolume.SetUp failed for volume "kube-api-access-g5vmq" : object "svcaccounts-7205"/"kube-root-ca.crt" not registered
```

### Anything else we need to know?

volume attach started at:

```
I1217 20:46:53.331094    4752 reconciler.go:216] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-g5vmq\" (UniqueName: \"kubernetes.io/projected/23f009ea-a467-4bb5-8124-6ea48cb27fce-kube-api-access-g5vmq\") pod \"oidc-discovery-validator\" (UID: \"23f009ea-a467-4bb5-8124-6ea48cb27fce\") " pod="svcaccounts-7205/oidc-discovery-validator"
I1217 20:46:53.331094    4752 reconciler.go:216] "operationExecutor.VerifyControllerAttachedVolume started for volume \"sa-token\" (UniqueName: \"kubernetes.io/projected/23f009ea-a467-4bb5-8124-6ea48cb27fce-sa-token\") pod \"oidc-discovery-validator\" (UID: \"23f009ea-a467-4bb5-8124-6ea48cb27fce\") " pod="svcaccounts-7205/oidc-discovery-validator"
```

container started at:

```
[737] {"Timestamp":"2021-12-17T20:47:01.5430857+00:00","ProviderName":"ContainerD","Level":4,"Keywords":0,"Payload":{"ID":1,"EventName":"LogrusEntry","TraceEventProcessID":2568,"TraceEventProcessName":"","Message":"StartContainer for \"58ffd964cecf3d1b1185392ec9e0629ee58d158897d3ad585c874c8332aa79e1\"","Time":"2021-12-17T20:47:01.5958847+00:00"}}

[740] {"Timestamp":"2021-12-17T20:47:03.6582168+00:00","ProviderName":"ContainerD","Level":4,"Keywords":0,"Payload":{"ID":1,"EventName":"LogrusEntry","TraceEventProcessID":2568,"TraceEventProcessName":"","Message":"StartContainer for \"58ffd964cecf3d1b1185392ec9e0629ee58d158897d3ad585c874c8332aa79e1\" returns successfully","Time":"2021-12-17T20:47:03.7106336+00:00"}}
```

Shortly after it starts to turn off ( which aligns with timing of  `2021/12/17 20:47:05 Get "https://kubernetes.default.svc.cluster.local/.well-known/openid-configuration": x509: certificate signed by unknown authority`:

```
{"ID":26,"EventName":"LogrusEntry","TraceEventProcessID":16132,"TraceEventProcessName":"","Message":"Span","Time":"2021-12-17T20:47:05.3998312+00:00","cid":"58ffd964cecf3d1b1185392ec9e0629ee58d158897d3ad585c874c8332aa79e1","duration":"0s","endTime":"2021-12-17T20:47:05.3998312+00:00","name":"hcs::Process::CloseStderr","parentSpanID":"0000000000000000","pid":7420,"spanID":"4fe9f16c69b527d3","startTime":"2021-12-17T20:47:05.3998312+00:00","traceID":"6d39b88f1758813d9d6e339c60fcf063"}}
```

The failedmount is after the pod was removed

```
Dec 17 20:47:38.222: INFO: At 2021-12-17 20:47:07 +0000 UTC - event for oidc-discovery-validator: {kubelet capz-conf-d6ml5} FailedMount: MountVolume.SetUp failed for volume "kube-api-access-g5vmq" : object "svcaccounts-7205"/"kube-root-ca.crt" not registered
```

### Relevant SIG(s)

/sig windows

found during https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1932

successful run here: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/1932/pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts/1471879195658293248

**Comment by jsturtevant** [comment]
Saw this in CI https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1481222494881845248 with same failure message as above

**Comment by jsturtevant** [comment]
After de-flaking other tests this is still a flake: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1481964383998316544

**Comment by marosset** [comment]
/triage accepted
We saw this again recently in SIG-windows tests

**Comment by jsturtevant** [comment]
failed again this week https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-nightly-windows/1506689256301531136

In this case the failed volume mount error was not present

**Comment by jsturtevant** [comment]
When this is successfull the `in-cluster` provider is [successful](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-nightly-windows/1507051791278149632/build-log.txt):

```
Mar 24 18:28:42.719: INFO: polling logs
Mar 24 18:28:42.842: INFO: Pod logs: 
2022/03/24 18:28:04 OK: Got token
2022/03/24 18:28:04 validating with in-cluster discovery
2022/03/24 18:28:04 OK: got issuer https://kubernetes.default.svc.cluster.local
2022/03/24 18:28:04 Full, not-validated claims: 
openidmetadata.claims{Claims:jwt.Claims{Issuer:"https://kubernetes.default.svc.cluster.local", Subject:"system:serviceaccount:svcaccounts-5714:default", Audience:jwt.Audience{"oidc-discovery-test"}, Expiry:1648147080, NotBefore:1648146480, IssuedAt:1648146480, ID:""}, Kubernetes:openidmetadata.kubeClaims{Namespace:"svcaccounts-5714", ServiceAccount:openidmetadata.kubeName{Name:"default", UID:"dbb4fee1-751e-449b-a62a-75ebdbb3b641"}}}
2022/03/24 18:28:04 Ensuring Windows DNS availability
2022/03/24 18:28:04 OK: Resolved host kubernetes.default.svc.cluster.local: [10.96.0.1]
2022/03/24 18:28:04 OK: Constructed OIDC provider for issuer https://kubernetes.default.svc.cluster.local
2022/03/24 18:28:04 OK: Validated signature on JWT
2022/03/24 18:28:04 OK: Got valid claims from token!
2022/03/24 18:28:04 Full, validated claims: 
&openidmetadata.claims{Claims:jwt.Claims{Issuer:"https://kubernetes.default.svc.cluster.local", Subject:"system:serviceaccount:svcaccounts-5714:default", Audience:jwt.Audience{"oidc-discovery-test"}, Expiry:1648147080, NotBefore:1648146480, IssuedAt:1648146480, ID:""}, Kubernetes:openidmetadata.kubeClaims{Namespace:"svcaccounts-5714", ServiceAccount:openidmetadata.kubeName{Name:"default", UID:"dbb4fee1-751e-449b-a62a-75ebdbb3b641"}}}
```

In failure case the (see above too) the incluster validation fails and it falls back to external discovery:

```
2022/03/23 18:26:01 OK: Got token
2022/03/23 18:26:02 validating with in-cluster discovery
2022/03/23 18:26:02 OK: got issuer https://kubernetes.default.svc.cluster.local
2022/03/23 18:26:02 Full, not-validated claims: 
openidmetadata.claims{Claims:jwt.Claims{Issuer:"https://kubernetes.default.svc.cluster.local", Subject:"system:serviceaccount:svcaccounts-2377:default", Audience:jwt.Audience{"oidc-discovery-test"}, Expiry:1648060557, NotBefore:1648059957, IssuedAt:1648059957, ID:""}, Kubernetes:openidmetadata.kubeClaims{Namespace:"svcaccounts-2377", ServiceAccount:openidmetadata.kubeName{Name:"default", UID:"b40fd358-e9e7-4202-bdd1-eaeef76ab871"}}}
2022/03/23 18:26:02 Ensuring Windows DNS availability
2022/03/23 18:26:02 OK: Resolved host kubernetes.default.svc.cluster.local: [10.96.0.1]
2022/03/23 18:26:02 OK: Constructed OIDC provider for issuer https://kubernetes.default.svc.cluster.local
2022/03/23 18:26:02 failed to validate with in-cluster discovery: failed to verify signature: fetching keys oidc: get keys failed Get "https://10.0.0.4:6443/openid/v1/jwks": dial tcp 10.0.0.4:6443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.
2022/03/23 18:26:02 falling back to validating with external discovery
2022/03/23 18:26:02 OK: got issuer https://kubernetes.default.svc.cluster.local
2022/03/23 18:26:02 Full, not-validated claims: 
openidmetadata.claims{Claims:jwt.Claims{Issuer:"https://kubernetes.default.svc.cluster.local", Subject:"system:serviceaccount:svcaccounts-2377:default", Audience:jwt.Audience{"oidc-discovery-test"}, Expiry:1648060557, NotBefore:1648059957, IssuedAt:1648059957, ID:""}, Kubernetes:openidmetadata.kubeClaims{Namespace:"svcaccounts-2377", ServiceAccount:openidmetadata.kubeName{Name:"default", UID:"b40fd358-e9e7-4202-bdd1-eaeef76ab871"}}}
2022/03/23 18:26:02 Ensuring Windows DNS availability
2022/03/23 18:26:02 OK: Resolved host kubernetes.default.svc.cluster.local: [10.96.0.1]
2022/03/23 18:26:02 Get "https://kubernetes.default.svc.cluster.local/.well-known/openid-configuration": dial tcp 10.96.0.1:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.
```

**Comment by jsturtevant** [comment]
The following error seems to be the root:

```
2022/03/23 18:26:02 failed to validate with in-cluster discovery: failed to verify signature: 
fetching keys oidc: get keys failed Get "https://10.0.0.4:6443/openid/v1/jwks": dial tcp 
10.0.0.4:6443: connectex: An attempt was made to access a socket in a way forbidden by its
 access permissions.
```

Search briefly on `connectex: An attempt was made to access a socket in a way forbidden by its access permissions.` for windows this seems to happen when using a port that is already allocated or don't have enough permissions. Since we seem to have enough permissions I believe that we are trying to re-use an ephemeral port that is already in use.  

Just for reference the code that is opening the connection to the api server is from here: https://github.com/coreos/go-oidc/blob/e05c4c73b4b5f159727021bf2921c214f61b2688/jwks.go#L193-L201

**Comment by jsturtevant** [comment]
for what its worth I ran just this test with `GINKGO_UNTIL_IT_FAILS` and it hasn't failed yet:

```
All tests passed...                                                                          
Will keep running them until they fail.                                                      
This was attempt #92                                                                         
No, seriously... you can probably stop now
```

**Comment by jsturtevant** [comment]
I got a repo on this after 111th run. I created a pod with the same spec in the failed namespace as the one that failed in the test but it connected fine.  This does lead me to believe that the port is being opened in a reserved space.  

We had some port reservation issues in the past and this was suppose to help: https://github.com/kubernetes-sigs/image-builder/pull/750. I confirmed the node I got the repo on (and the ones used in the tests) have this patch.

Now that I can repo, going to run with the following etw provider to see if can get more info: `{2F07E2EE-15DB-40F1-90EF-9D7BA282188A} # Microsoft-Windows-TCPIP`

**Comment by jsturtevant** [comment]
The dynamic port range on the nodes is set to 33000-65535 in [capz ](https://github.com/kubernetes-sigs/image-builder/pull/750) and [aks-e](https://github.com/Azure/aks-engine/pull/4767), based on feedback we received for clusters with high number of services.  Should this be different set of ports?

**Comment by claudiubelu** [comment]
Ok, so... I have been looking into this a bit more.

Last time, i picked port number ``47001``, as it's one of the ports used by the System (PID 4) and tried to use it as a client port. Somehow, that was the worst port choice that could have made from the list of used ports above. Using that port, resulted in the error ``An attempt was made to access a socket in a way forbidden by its access permissions`` we've seen until now.

However, if we try a different port which is already open, we see this error instead:

```
>>> req = s.get("https://google.com")
Traceback (most recent call last):
  File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.bind(source_address)
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\urllib3\connection.py", line 308, in connect
    conn = self._new_conn()
  File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\urllib3\connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001D4ABF0E2E8>: Failed to establish a new connection: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\urllib3\connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4ABF0E2E8>: Failed to establish a new connection: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\Python\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
onnection object at 0x000001D4ABF0E2E8>: Failed to establish a new connection: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted',))
```

So, where does the ``An attempt was made to access a socket in a way forbidden by its access permissions`` error come from anyways? Well, it turns out there's another port range that we should consider:

```
netsh int ipv4 show excludedportrange tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
      5985        5985
      5986        5986
     33300       33363
     33364       33427
     33487       33550
     33551       33614
     33615       33678
     33679       33742
     47001       47001

* - Administered port exclusions.
```

As you can see, port ``47001`` is excluded, which is why we got that ``An attempt was made to access a socket in a way forbidden by its access permissions`` error. Same error occurs even with another port that's not currently in use from those excluded port ranges.

So, I'd say that these errors we've been seeing have been occuring because a client port number has been chosen from those excluded port ranges, resulting in this failure. Ideally, those port ranges would be respected when choosing a client port number. A quick fix would be to update the dynamic port range start from 33000-65535 to 34000-65535 or so. With this quick fix, the only case in which this error would occur would be if the port ``47001`` is chosen.

**Comment by claudiubelu** [comment]
PS: containers do not have any excluded port ranges:

```
kubectl exec -n new-ns pod/test-pod-default -- netsh int ipv4 show excludedportrange tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------

* - Administered port exclusions.
```

So, I think that we only have to update the dynamic port ranges on the hosts.

**Comment by marosset** [comment]
@daschott @mikezappa87 as FYI
@jsturtevant - WDYT about updating the port-ranges to `34000-65535` as mentioned about?
https://github.com/kubernetes-sigs/image-builder/blob/3a2e968864d7c297b5bc0979f9c3f1224ccdc08b/images/capi/ansible/windows/roles/systemprep/tasks/main.yml#L136-L137

**Comment by MikeZappa87** [comment]
@marosset 

Regarding port 65330 does the link below impact the listed suggestion above?

https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-faq#what-protocols-can-i-use-within-vnets

**Comment by marosset** [comment]
> @marosset
> 
> Regarding port 65330 does the link below impact the listed suggestion above?
> 
> https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-faq#what-protocols-can-i-use-within-vnets

Yes! I was looking for that port.
Perhaps we should update the dynamic to be `34000-65300`?

**Comment by MikeZappa87** [comment]
> > @marosset
> > Regarding port 65330 does the link below impact the listed suggestion above?
> > https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-faq#what-protocols-can-i-use-within-vnets
> 
> Yes! I was looking for that port. Perhaps we should update the dynamic to be `34000-65300`?

That would work, I wish we could do a comma separated list since we can't use ports above 65301 :-/

**Comment by marosset** [comment]
OK, let me open a PR into image-builder to update this.

**Comment by jsturtevant** [comment]
> @marosset
> 
> Regarding port 65330 does the link below impact the listed suggestion above?
> 
> https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-faq#what-protocols-can-i-use-within-vnets

from the link:
> DP source port 65330 which is reserved for the host. 

This is for UDP only. Currently we don't set ranges in image builder but maybe we should. but I think we can keep the extra few hundred ports for TCP

**Comment by marosset** [comment]
/reopen 
Let's see if updating the port ranges actually fixes the test flakes

**Comment by marosset** [comment]
We are still seeing this issue after updated the TCP port ranges with https://github.com/kubernetes-sigs/image-builder/pull/947.

The latest CAPZ images - which are used in the Windows e2e tests - all report

```cmd
PS C:\apps> netsh int ipv4 show dynamicportrange tcp

Protocol tcp Dynamic Port Range
---------------------------------
Start Port      : 34000
Number of Ports : 31536
```
 And we're still seeing occasional failures. Ex https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1609652332503502848 occurred on 01/01/2023
 
 @MikeZappa87 @daschott and other ideas??

**Comment by pacoxu** [comment]
Keep flaking in https://testgrid.k8s.io/sig-release-master-informing#capz-windows-master.

**Comment by pacoxu** [comment]
After adding capz-windows-1.30, it flake there as well.

https://testgrid.k8s.io/sig-release-1.30-informing#capz-windows-1.30

**Comment by neoaggelos** [comment]
Hi @marosset @jsturtevant, I'm here representing the Release Signal team for Kubernetes 1.30. This is still flaking https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-windows-1-30/1775417211389743104, last one was today.

Is this on your radar?

**Comment by marosset** [comment]
Yes this is still on our radar :(

**Comment by knabben** [comment]
Interesting running the agnhost in the pod that's the values for dynamic port range

```
C:/ $ netsh int ipv4 show dynamicportrange tcp

Protocol tcp Dynamic Port Range
---------------------------------
Start Port      : 49152
Number of Ports : 16384
```

**Comment by knabben** [comment]
Running for 4 hours, 300x on CAPV without any issue, same image-builder configuration, what makes me wonder: 1) is something in the infra hosting,  2) More tests runs in parallel and are causing this behavior somehow.



Interesting running the agnhost in the pod that's the values for dynamic port range

```
C:/ $ netsh int ipv4 show dynamicportrange tcp

Protocol tcp Dynamic Port Range
---------------------------------
Start Port      : 49152
Number of Ports : 16384
```

**Comment by jsturtevant** [comment]
Added a retry here https://github.com/kubernetes-sigs/windows-testing/pull/433

**Comment by jsturtevant** [comment]
unfortunately seems to have flaked here: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-windows/1797783176332972032

**Comment by wendy-ha18** [comment]
This test is continue failed today: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-windows/1798646879127343104

cc @jsturtevant 

```
{ failed [FAILED] Told to stop trying after 262.186s.
pod "oidc-discovery-validator" failed with status: {Phase:Failed Conditions:[{Type:PodReadyToStartContainers Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2024-06-06 10:17:24 +0000 UTC Reason: Message:} {Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2024-06-06 10:13:07 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2024-06-06 10:13:44 +0000 UTC Reason:PodFailed Message:} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2024-06-06 10:17:24 +0000 UTC Reason:PodFailed Message:} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2024-06-06 10:13:07 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:10.1.0.5 HostIPs:[{IP:10.1.0.5}] PodIP: PodIPs:[] StartTime:2024-06-06 10:13:07 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:oidc-discovery-validator State:{Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:255,Signal:0,Reason:Unknown,Message:,StartedAt:2024-06-06 10:13:12 +0000 UTC,FinishedAt:2024-06-06 10:17:16 +0000 UTC,ContainerID:containerd://f163451d0fa03be73d664cc39efb747c38c4170fb61a7dde252e79492fe90a4d,}} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:registry.k8s.io/e2e-test-images/agnhost:2.52 ImageID:registry.k8s.io/e2e-test-images/agnhost@sha256:b173c7d0ffe3d805d49f4dfe48375169b7b8d2e1feb81783efd61eb9d08042e6 ContainerID:containerd://f163451d0fa03be73d664cc39efb747c38c4170fb61a7dde252e79492fe90a4d Started:0xc00728808f AllocatedResources:map[] Resources:nil VolumeMounts:[] User:nil}] QOSClass:BestEffort EphemeralContainerStatuses:[] Resize: ResourceClaimStatuses:[]}
In [It] at: k8s.io/kubernetes/test/e2e/auth/service_accounts.go:637 @ 06/06/24 10:18:00.382
}
```

**Comment by drewhagen** [comment]
The release cycle for 1.32 starts today. Since this is still open, I will carry it over to the latest milestone.

I'm curious if we can reduce the amount of flakes we are tracking.
We still see this flaking, with a failure as recent as 9/5:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-windows/1831818458518523904

@jsturtevant @marosset @knabben I see this is tracked as "In Progress" on a SIG Windows board. Any updates or progress on resolving this?

**Comment by knabben** [comment]
The retries have decreased the number of flakes, but they are not solved completely. Still being investigated with suspicion of being an OS related issue

**Comment by knabben** [comment]
Changing the Windows for 2022 on this job, fixed the flake

/close
