### ISSUE TITLE
io.kubernetes.client.openapi.ApiException: java.net.ConnectException: Failed to connect to /192.168.200.142:8080

### ISSUE THREAD

**Issue by xiaobinggan-zmh** [kubernetes/kubernetes#107204]
### What happened?

In my development with SpringBoot,
**application.yml**  
`k8s-cluster-ip: http://192.168.200.142:8080  # Realize the connection with K8S`

Modify the K8S file   ->  **kube-apiserver.yaml**   
add
`- --insecure-bind-address=0.0.0.0  - --insecure-port=8080 `

The k8S version was 1.17.3 at the time, now updated to 1.22.3.There is no way to expose HTTP 8080 port, and an error occurs when running Java code:

2021-12-23 22:01:43.813 ERROR 128415 --- [models.V1Node-0] i.k.c.informer.cache.ReflectorRunnable   : class io.kubernetes.client.openapi.models.V1Node#Reflector loop failed unexpectedly

io.kubernetes.client.openapi.ApiException: java.net.ConnectException: Failed to connect to /192.168.200.142:8080
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:886) ~[client-java-api-9.0.2.jar!/:na]
	at io.kubernetes.client.informer.SharedInformerFactory$1.list(SharedInformerFactory.java:158) ~[client-java-9.0.2.jar!/:na]
	at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:74) ~[client-java-9.0.2.jar!/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_312]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_312]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_312]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_312]
Caused by: java.net.ConnectException: Failed to connect to /192.168.200.142:8080
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.RealCall.execute(RealCall.java:81) ~[okhttp-3.14.4.jar!/:na]
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:882) ~[client-java-api-9.0.2.jar!/:na]
	... 9 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_312]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_312]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_312]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_312]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_312]
	at java.net.Socket.connect(Socket.java:607) ~[na:1.8.0_312]
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263) ~[okhttp-3.14.4.jar!/:na]
	... 28 common frames omitted

### What did you expect to happen?

How do I enable HTTP port 8080 of K8s 1.22.3

### How can we reproduce it (as minimally and precisely as possible)?

io.kubernetes.client.openapi.ApiException: java.net.ConnectException: Failed to connect to /192.168.200.142:8080

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$ uname -a
Linux master 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mk46** [comment]
Hi @xiaobinggan-zmh, Would you mind to take a look on `--bind-address` and `--secure-port` in https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
For address binding, by default 0.0.0.0 is used. I think only need to add `--secure-port=8080` in kube-apiserver.yaml

**Comment by pacoxu** [comment]
Since #95856 1.20, the insecure port is not supported. 
> ACTION REQUIRED: The kube-apiserver ability to serve on an insecure port, deprecated since v1.10, has been removed. The insecure address flags `--address` and `--insecure-bind-address` have no effect in kube-apiserver and will be removed in v1.24. The insecure port flags `--port` and `--insecure-port` may only be set to 0 and will be removed in v1.24.

/kind support
/remove-kind  bug
/area apiserver
/sig api-machinery

**Comment by xiaobinggan-zmh** [comment]
When I change **Kube-apiserver.yaml** :
```
    - --insecure-port=0
    - --insecure-bind-address=0.0.0.0
```

There are still errors:

2021-12-25 22:22:44.518 ERROR 50218 --- [models.V1Node-0] i.k.c.informer.cache.ReflectorRunnable   : class io.kubernetes.client.openapi.models.V1Node#Reflector loop failed unexpectedly

java.lang.IllegalArgumentException: Invalid URL port: "0"
	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1394) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.HttpUrl.get(HttpUrl.java:917) ~[okhttp-3.14.4.jar!/:na]
	at okhttp3.Request$Builder.url(Request.java:165) ~[okhttp-3.14.4.jar!/:na]
	at io.kubernetes.client.openapi.ApiClient.buildRequest(ApiClient.java:1052) ~[client-java-api-9.0.2.jar!/:na]
	at io.kubernetes.client.openapi.ApiClient.buildCall(ApiClient.java:1005) ~[client-java-api-9.0.2.jar!/:na]
	at io.kubernetes.client.openapi.apis.CoreV1Api.listNodeCall(CoreV1Api.java:33440) ~[client-java-api-9.0.2.jar!/:na]
	at edu.xidian.cnmano.k8sclient.Informers.lambda$V1NodeInformer$2(Informers.java:81) ~[classes!/:na]
	at io.kubernetes.client.informer.SharedInformerFactory$1.list(SharedInformerFactory.java:157) ~[client-java-9.0.2.jar!/:na]
	at io.kubernetes.client.informer.cache.ReflectorRunnable.run(ReflectorRunnable.java:74) ~[client-java-9.0.2.jar!/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_312]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_312]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_312]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_312]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_312]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_312]

**Comment by kkkkun** [comment]
What's your used version of jar `https://github.com/fabric8io/kubernetes-client`?

You can upgrade version great than `4.4.2`?
