### ISSUE TITLE
[Flaky test] gci-gce-ingress, diffResource

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/kubernetes#107530]
### Which jobs are flaking?

* gci-gce-ingress

### Which tests are flaking?

* ci-kubernetes-e2e-gci-gce-ingress.Overall
* kubetest.diffResources

### Since when has it been flaking?

History goes back to 2021-12-30

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#gci-gce-ingress

### Reason for failure (if possible)

```bash


1/7062 Tests Failed. | expand_less
-- | --
e2e.go: diffResources expand_less0sError: 2 leaked resources +NAME                              REGION    SESSION_AFFINITY  BACKUP  HEALTH_CHECKS +a1ab9e2204ff44d809dc9bceaaf3c8a7  us-west1  NONE                      a1ab9e2204ff44d809dc9bceaaf3c8a7 | e2e.go: diffResources expand_less | 0s | Error: 2 leaked resources +NAME                              REGION    SESSION_AFFINITY  BACKUP  HEALTH_CHECKS +a1ab9e2204ff44d809dc9bceaaf3c8a7  us-west1  NONE                      a1ab9e2204ff44d809dc9bceaaf3c8a7
e2e.go: diffResources expand_less | 0s
Error: 2 leaked resources +NAME                              REGION    SESSION_AFFINITY  BACKUP  HEALTH_CHECKS +a1ab9e2204ff44d809dc9bceaaf3c8a7  us-west1  NONE                      a1ab9e2204ff44d809dc9bceaaf3c8a7


```

### Relevant SIG(s)

/sig testing

**Comment by aojea** [comment]
checking this occurence https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/1481536750466633728/build-log.txt

```
W0113 09:40:36.010] 2022/01/13 09:40:36 main.go:331: Something went wrong: encountered 1 errors: [Error: 2 leaked resources
W0113 09:40:36.011] +NAME                              REGION    SESSION_AFFINITY  BACKUP  HEALTH_CHECKS
W0113 09:40:36.011] +a1ab9e2204ff44d809dc9bceaaf3c8a7  us-west1  NONE                      a1ab9e2204ff44d809dc9bceaaf3c8a7]
W0113 09:40:36.012] Traceback (most recent call last):
W0113 09:40:36.012]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 723, in <module>
W0113 09:40:36.013]     main(parse_args())
W0113 09:40:36.013]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 569, in main
W0113 09:40:36.013]     mode.start(runner_args)
W0113 09:40:36.013]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 228, in start
W0113 09:40:36.014]     check_env(env, self.command, *args)
W0113 09:40:36.014]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 111, in check_env
W0113 09:40:36.014]     subprocess.check_call(cmd, env=env)
W0113 09:40:36.014]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W0113 09:40:36.014]     raise CalledProcessError(retcode, cmd)
W0113 09:40:36.015] subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--provider=gce', '--cluster=bootstrap-e2e', '--gcp-network=bootstrap-e2e', '--check-leaked-resources', '--extract=ci/latest-fast', '--extract-ci-bucket=k8s-release-dev', '--gcp-node-image=gci', '--gcp-zone=us-west1-b', '--test_args=--ginkgo.focus=\\[Feature:Ingress\\]|\\[Feature:NEG\\]|Loadbalancing|LoadBa
```

it seems that a load balancer didn't get cleaned after the test

```
I0113 09:14:18.044] [AfterEach] [sig-network] LoadBalancers ESIPP [Slow]
I0113 09:14:18.045]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/loadbalancer.go:996
I0113 09:14:18.045] Jan 13 09:14:18.044: INFO: cleaning load balancer resource for a1ab9e2204ff44d809dc9bceaaf3c8a7
I0113 09:14:29.232] I0113 09:14:29.231636    9862 gce_loadbalancer_external.go:384] DeleteExternalTargetPoolAndChecks(a1ab9e2204ff44d809dc9bceaaf3c8a7(/)): Target pool already deleted. Continuing to delete other resources.
I0113 09:14:29.232] I0113 09:14:29.231670    9862 gce_loadbalancer_external.go:401] DeleteExternalTargetPoolAndChecks(a1ab9e2204ff44d809dc9bceaaf3c8a7(/)): Deleting health check k8s-d1651d3665e125cb-node.
I0113 09:14:29.488] Jan 13 09:14:29.488: INFO: Still waiting for glbc to cleanup: <nil>
I0113 09:14:29.488] googleapi: Error 400: The resource 'projects/k8s-infra-e2e-boskos-011/global/httpHealthChecks/k8s-d1651d3665e125cb-node' is not ready, resourceNotReady
I0113 09:14:29.489] W0113 09:14:29.488187    9862 gce_loadbalancer_external.go:408] DeleteExternalTargetPoolAndChecks(a1ab9e2204ff44d809dc9bceaaf3c8a7(/)): Failed to delete health check k8s-d1651d3665e125cb-node: googleapi: Error 400: The resource 'projects/k8s-infra-e2e-boskos-011/global/httpHealthChecks/k8s-d1651d3665e125cb-node' is not ready, resourceNotReady.
I0113 09:14:33.813] I0113 09:14:33.813137    9862 gce_loadbalancer_external.go:384] DeleteExternalTargetPoolAndChecks(a1ab9e2204ff44d809dc9bceaaf3c8a7(/)): Target pool already deleted. Continuing to delete other resources.
I0113 09:14:33.814] I0113 09:14:33.813182    9862 gce_loadbalancer_external.go:401] DeleteExternalTargetPoolAndChecks(a1ab9e2204ff44d809dc9bceaaf3c8a7(/)): Deleting health check k8s-d1651d3665e125cb-node.
I0113 09:14:34.086] I0113 09:14:34.086285    9862 gce_loadbalancer_external.go:423] DeleteExternalTargetPoolAndChecks(a1ab9e2204ff44d809dc9bceaaf3c8a7(/)): Deleting health check firewall k8s-d1651d3665e125cb-node-http-hc.
I0113 09:14:34.334] Jan 13 09:14:34.334: INFO: Still waiting for glbc to cleanup: <nil>
I0113 09:14:34.335] googleapi: Error 400: The resource 'projects/k8s-infra-e2e-boskos-011/global/firewalls/k8s-d1651d3665e125cb-node-http-hc' is not ready, resourceNotReady
I0113 09:14:38.954] I0113 09:14:38.954299    9862 gce_loadbalancer_external.go:384] DeleteExternalTargetPoolAndChecks(a1ab9e2204ff44d809dc9bceaaf3c8a7(/)): Target pool already deleted. Continuing to delete other resources.
I0113 09:14:38.955] I0113 09:14:38.954327    9862 gce_loadbalancer_external.go:401] DeleteExternalTargetPoolAndChecks(a1ab9e2204ff44d809dc9bceaaf3c8a7(/)): Deleting health check k8s-d1651d3665e125cb-node.
I0113 09:14:39.205] I0113 09:14:39.205057    9862 gce_loadbalancer_external.go:423] DeleteExternalTargetPoolAndChecks(a1ab9e2204ff44d809dc9bceaaf3c8a7(/)): Deleting health check firewall k8s-d1651d3665e125cb-node-http-hc.
I0113 09:14:39.323] [32mâ€¢[0m{"msg":"PASSED [sig-network] LoadBalancers ESIPP [Slow] should handle updates to ExternalTrafficPolicy field","total":28,"completed":19,"skipped":5716,"failed":0}
I0113 09:14:39.324] 
```

@bowei @swetharepakula you may have more insights , can you PTAL?
cc @wojtek-t

**Comment by bowei** [comment]
Do we gate the deletion with finalizers? It might be the case that if we get a not ready signal, we need to just wait to see if it can recover the next time the deletion comes around.

**Comment by BenTheElder** [comment]
diffResources is highlighting a failure to cleanup, the underlying bug is not in the test infra or test framework etc.
/remove-sig testing

/sig network
(or cloud-provider?)

**Comment by leonardpahlke** [comment]
cc @swetharepakula

**Comment by leonardpahlke** [comment]
The job still fails, in 4 of the last 5 runs.

**Comment by lauralorenz** [comment]
CI Signal shadow here, still observing flaky behavior.

**Comment by Nivedita-coder** [comment]
CI Signal shadow here, still observing flaky behavior.

**Comment by leonardpahlke** [comment]
Hello @bowei did you investigated this further? Thanks

**Comment by lauralorenz** [comment]
Hi again from CI Signal shadow, x-posting from Slack: boosting this again as this Wednesday 3/30 we plan to cut the 1.24.0-beta.0 release and I would like input as to whether this flake should be considered release blocking since the next candidate is our first (and only) beta candidate.

**Comment by dims** [comment]
Looking at https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/1507923649141673984

```
[dims@dims-m1-7029 15:12] ~/Downloads ⟩ rg a20f037c649bd47158b926f5009186e8
gcp-resources-after.txt
80:a20f037c649bd47158b926f5009186e8  us-west1  NONE                      a20f037c649bd47158b926f5009186e8

junit_runner.xml
21:        <failure>Error: 2 leaked resources&#xA;+NAME                              REGION    SESSION_AFFINITY  BACKUP  HEALTH_CHECKS&#xA;+a20f037c649bd47158b926f5009186e8  us-west1  NONE                      a20f037c649bd47158b926f5009186e8</failure>

gcp-resources-diff.txt
6:+a20f037c649bd47158b926f5009186e8  us-west1  NONE                      a20f037c649bd47158b926f5009186e8

build-log.txt
2683:I0327 04:30:50.159] Mar 27 04:30:50.159: INFO: cleaning load balancer resource for a20f037c649bd47158b926f5009186e8
2684:I0327 04:31:03.805] I0327 04:31:03.805327   10033 gce_loadbalancer_external.go:384] DeleteExternalTargetPoolAndChecks(a20f037c649bd47158b926f5009186e8(/)): Target pool already deleted. Continuing to delete other resources.
2685:I0327 04:31:03.806] I0327 04:31:03.805356   10033 gce_loadbalancer_external.go:401] DeleteExternalTargetPoolAndChecks(a20f037c649bd47158b926f5009186e8(/)): Deleting health check k8s-da372d0ae1e25832-node.
2688:I0327 04:31:04.176] W0327 04:31:04.175779   10033 gce_loadbalancer_external.go:408] DeleteExternalTargetPoolAndChecks(a20f037c649bd47158b926f5009186e8(/)): Failed to delete health check k8s-da372d0ae1e25832-node: googleapi: Error 400: The resource 'projects/k8s-infra-e2e-boskos-059/global/httpHealthChecks/k8s-da372d0ae1e25832-node' is not ready, resourceNotReady.
2689:I0327 04:31:06.050] I0327 04:31:06.050133   10033 gce_loadbalancer_external.go:384] DeleteExternalTargetPoolAndChecks(a20f037c649bd47158b926f5009186e8(/)): Target pool already deleted. Continuing to delete other resources.
2690:I0327 04:31:06.050] I0327 04:31:06.050163   10033 gce_loadbalancer_external.go:401] DeleteExternalTargetPoolAndChecks(a20f037c649bd47158b926f5009186e8(/)): Deleting health check k8s-da372d0ae1e25832-node.
2691:I0327 04:31:06.363] I0327 04:31:06.363381   10033 gce_loadbalancer_external.go:423] DeleteExternalTargetPoolAndChecks(a20f037c649bd47158b926f5009186e8(/)): Deleting health check firewall k8s-da372d0ae1e25832-node-http-hc.
2694:I0327 04:31:11.007] I0327 04:31:11.007499   10033 gce_loadbalancer_external.go:384] DeleteExternalTargetPoolAndChecks(a20f037c649bd47158b926f5009186e8(/)): Target pool already deleted. Continuing to delete other resources.
2695:I0327 04:31:11.008] I0327 04:31:11.007544   10033 gce_loadbalancer_external.go:401] DeleteExternalTargetPoolAndChecks(a20f037c649bd47158b926f5009186e8(/)): Deleting health check k8s-da372d0ae1e25832-node.
2696:I0327 04:31:11.358] I0327 04:31:11.357911   10033 gce_loadbalancer_external.go:423] DeleteExternalTargetPoolAndChecks(a20f037c649bd47158b926f5009186e8(/)): Deleting health check firewall k8s-da372d0ae1e25832-node-http-hc.
4472:I0327 05:10:56.385] Deleting firewall rules remaining in network bootstrap-e2e: k8s-a20f037c649bd47158b926f5009186e8-http-hc
4473:W0327 05:11:05.197] Deleted [https://www.googleapis.com/compute/v1/projects/k8s-infra-e2e-boskos-059/global/firewalls/k8s-a20f037c649bd47158b926f5009186e8-http-hc].
4508:W0327 05:13:05.239] +a20f037c649bd47158b926f5009186e8  us-west1  NONE                      a20f037c649bd47158b926f5009186e8]

gcp-resources-cluster-down.txt
135:a20f037c649bd47158b926f5009186e8  us-west1  NONE                      a20f037c649bd47158b926f5009186e8
```

The problem is with the underlying cloud provider, not in our code. So i'd NOT consider this release-blocking.

**Comment by aojea** [comment]
is NOT a release blocker

**Comment by aojea** [comment]
> 

NOT a release blocker, the errors are unrelated to Kubernetes code
