### ISSUE TITLE
Containerd-hugepages job fails due to infrastructure issues

### ISSUE THREAD

**Issue by bart0sh** [kubernetes/kubernetes#108067]
### Which jobs are failing?

sig-node-containerd#node-kubelet-containerd-hugepages

### Which tests are failing?

none

### Since when has it been failing?

Feb 09 2022 18:30 EET

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#node-kubelet-containerd-hugepages

### Reason for failure (if possible)

It looks like some infrastructure setup issue with JWT token. This is a quote from the build log:
```
I0209 16:31:41.618] process 144 exited with code 1 after 0.0m
E0209 16:31:41.618] unexpected error
Traceback (most recent call last):
  File "./test-infra/jenkins/bootstrap.py", line 1103, in bootstrap
  File "./test-infra/jenkins/bootstrap.py", line 332, in start
  File "./test-infra/jenkins/bootstrap.py", line 372, in upload_json
  File "./test-infra/jenkins/bootstrap.py", line 1054, in <lambda>
  File "./test-infra/jenkins/bootstrap.py", line 149, in _call
CalledProcessError: Command '['gsutil', '-q', '-h', 'Content-Type:application/json', 'cp', '/tmp/gsutil_OBLDdj', 'gs://kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-containerd-hugepages/1491449360947351552/started.json']' returned non-zero exit status 1
I0209 16:31:41.620] Call:  gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json
W0209 16:31:42.269] ERROR: (gcloud.auth.activate-service-account) There was a problem refreshing your current auth tokens: ('invalid_grant: Invalid JWT Signature.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'})
W0209 16:31:42.269] Please run:
W0209 16:31:42.269] 
W0209 16:31:42.270]   $ gcloud auth login
W0209 16:31:42.270] 
W0209 16:31:42.270] to obtain new credentials.
W0209 16:31:42.270] 
W0209 16:31:42.270] If you have already logged in with a different account:
W0209 16:31:42.270] 
```
W0209 16:31:42.270]     $ gcloud config set account ACCOUNT
W0209 16:31:42.270] 
W0209 16:31:42.270] to select an already authenticated account to use.
E0209 16:31:42.426] Command failed

### Relevant SIG(s)

/sig node

**Comment by SergeyKanzhelev** [comment]
Looks like fixed now. All green

/close
