### ISSUE TITLE
Admission plugins don't exit gracefully

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#108388]
### What happened?

Found during the investigation of the goroutine leaks on the test integration framework that the resource quota controller doesn't exit

```
goroutine 2454 [sync.Cond.Wait]:
        sync.runtime_notifyListWait(0xc000205490, 0xc)
                /usr/local/go/src/runtime/sema.go:513 +0x13d
        sync.(*Cond).Wait(0xc008628380)
                /usr/local/go/src/sync/cond.go:56 +0x8c
        k8s.io/client-go/util/workqueue.(*Type).Get(0xc0007119e0)
                /home/aojea/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/queue.go:157 +0x9e
        k8s.io/apiserver/pkg/admission/plugin/resourcequota.(*quotaEvaluator).getWork(0xc0009e0d80)
                /home/aojea/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go:665 +0x6e
        k8s.io/apiserver/pkg/admission/plugin/resourcequota.(*quotaEvaluator).doWork.func1()
                /home/aojea/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go:150 +0x3c
        k8s.io/apiserver/pkg/admission/plugin/resourcequota.(*quotaEvaluator).doWork(0x0)
                /home/aojea/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go:162 +0x37
        k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f6db85c8930)
                /home/aojea/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
        k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x6765726f4627203b, {0x72ce380, 0xc00860b050}, 0x1, 0xc000152ae0)
                /home/aojea/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
        k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x746144222c222e64, 0x3b9aca00, 0x0, 0x22, 0x2c22223a2274616d)
                /home/aojea/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
        k8s.io/apimachinery/pkg/util/wait.Until(0x736c61663a226465, 0x776f6c6c41222c65, 0x756c6156656c6261)
                /home/aojea/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x25
        created by k8s.io/apiserver/pkg/admission/plugin/resourcequota.(*quotaEvaluator).run
                /home/aojea/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go:141 +0x8f
```

it seems that the registered plugins doesn't have a way to signal them to stop

https://github.com/kubernetes/kubernetes/blob/5b1e5387591dd3ad0b3ddacc9e44a6ac7260078e/staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/admission.go#L42-L59

this causes, that plugins that use informers are not able to stop gracefully

### What did you expect to happen?

Admissiong plugins to exit gracefully

### How can we reproduce it (as minimally and precisely as possible)?

with this fantastic reproducer @liggitt  pasted in one of the related issues

```go
func TestTestingAPIServerCleanTeardown(t *testing.T) {
	etcdConfig := framework.SharedEtcd()

	// Watch goroutines for 5 seconds before starting the server to get a high-water mark
	before := 0
	for i := 0; i < 500; i++ {
		if goroutines := runtime.NumGoroutine(); goroutines > before {
			before = goroutines
		}
		time.Sleep(10 * time.Millisecond)
	}
	beforeStack := make([]byte, 1024*1024)
	size := runtime.Stack(beforeStack, true)
	beforeStack = beforeStack[:size]

	s := apitesting.StartTestServerOrDie(t, nil, nil, etcdConfig)
	// time.Sleep(5 * time.Second)
	fmt.Println("DEBUG started teardown")
	s.TearDownFn()
	fmt.Println("DEBUG finished teardown")
	// time.Sleep(10 * time.Second)
	// Watch goroutines for 5 seconds after stopping the server to get a low-water mark
	after := math.MaxInt32
	for i := 0; i < 500; i++ {
		if goroutines := runtime.NumGoroutine(); goroutines < after {
			after = goroutines
		}
		time.Sleep(10 * time.Millisecond)
	}

	if after > before {
		afterStack := make([]byte, 1024*1024)
		size := runtime.Stack(afterStack, true)
		afterStack = afterStack[:size]

		//t.Logf("before:\n%s", string(beforeStack))
		t.Logf("after:\n%s", string(afterStack))
		t.Errorf("expected %d or fewer, got %d", before, after)
	} else {
		t.Logf("expected %d or fewer, got %d", before, after)
	}
}

```

### Anything else we need to know?

This impacts the integration framework, that sometimes have 30K goroutines leaked

https://github.com/kubernetes/kubernetes/pull/108060#issuecomment-1048629066

may explain why when we reduce tests the job doesn't timeout or is slow

https://github.com/kubernetes/kubernetes/issues/107857
https://github.com/kubernetes/kubernetes/issues/93609

### Kubernetes version

master

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
@wojtek-t you did fix this, right?
can we close it?

**Comment by wojtek-t** [comment]
Yes - this one was fixed by https://github.com/kubernetes/kubernetes/pull/110125 and https://github.com/kubernetes/kubernetes/pull/110246
