### ISSUE TITLE
kube-controller-manager able to acquire lease even when lock retrieval fails

### ISSUE THREAD

**Issue by yelhouti** [kubernetes/kubernetes#108380]
### What happened?

my etcd cluster got surcharged and become slow to answer, this in turn made the kube-controller-manager crash because it lost the election.

This shouldn't be a problem in theory as everything should be able to restart. 

But when the controller-manager tries to restart it fails to retrieve the lock but proceeds to acquire the lease:
```
I0227 22:49:25.006393       1 leaderelection.go:248] attempting to acquire leader lease kube-system/kube-controller-manager...
E0227 22:49:30.007315       1 leaderelection.go:330] error retrieving resource lock kube-system/kube-controller-manager: Get "https://127.0.0.1:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-controller-manager?timeout=5s": net/http: request can
celed (Client.Timeout exceeded while awaiting headers)
I0227 22:49:57.219037       1 leaderelection.go:258] successfully acquired lease kube-system/kube-controller-manager
```
Then starts working the cluster adding more strain on the etcd server

After few minutes, it tries to renew the lease but this time fails the crushes...
```
E0227 22:53:22.771806       1 leaderelection.go:330] error retrieving resource lock kube-system/kube-controller-manager: Get "https://127.0.0.1:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-controller-manager?timeout=5s": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E0227 22:53:27.771775       1 leaderelection.go:367] Failed to update lock: Put "https://127.0.0.1:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-controller-manager?timeout=5s": context deadline exceeded
I0227 22:53:27.771824       1 leaderelection.go:283] failed to renew lease kube-system/kube-controller-manager: timed out waiting for the condition
F0227 22:53:27.771925       1 controllermanager.go:287] leaderelection lost
goroutine 156 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00000e001, 0xc002a60f00, 0x4c, 0x12b)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x75186a0, 0xc000000003, 0x0, 0x0, 0xc005debf80, 0x0, 0x610b501, 0x14, 0x11f, 0x0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x1e5
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printf(0x75186a0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x4add216, 0x13, 0x0, 0x0, ...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:753 +0x19a
k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatalf(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1514
k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func4()
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:287 +0x8f
```

the cycle continues and the etcd cluster (and therefore the k8s cluster) is never able to fully recover

### What did you expect to happen?

If the controller is not able to retrieve the lease it should wait

### How can we reproduce it (as minimally and precisely as possible)?

1. start a k8s cluster
2. surcharge the etcd cluster
3. kill kube-controller-manager and ensure etcd is not able to answer it
4. check that kube-controller-manager behave as mentioned above:

### Kubernetes version

<details>

```console
$ kubectl version
paste output hereClient Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

Bare metal: kubespray

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="AlmaLinux"
VERSION="8.5 (Arctic Sphynx)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.5 (Arctic Sphynx)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.5"

$ uname -a
Linux node2 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Mon Nov 15 09:17:08 EST 2021 x86_64 x86_64 x86_64 GNU/Linux


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
Kubepray
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
containerd
</details>

**Comment by kkkkun** [comment]
When renew leader timeout,  kube-controller-manager and kube-scheduler  will crash.

**Comment by yelhouti** [comment]
@kkkkun but how is it able to to get the lease the first time if the request fails ?
>  it fails to retrieve the lock but proceeds to acquire the lease:

**Comment by yelhouti** [comment]
well thsi doesn't seem to be the case here, leader election fails the first time but etcd keeps starting up.
It is only after the second failure (almost 4 minutes later) that the node sees that his is not the leader in craches.
