### ISSUE TITLE
EventRecorder can accidentally send to a closed channel  and Panic

### ISSUE THREAD

**Issue by astoycos** [kubernetes/kubernetes#108518]
While Debugging https://github.com/kubernetes/kubernetes/issues/107372 Specifically with the unit test `TestMultipleServiceChanges` which is part of the endpoint controller's tests I ran into the following race after adding some code to shutdown the `EventBroadcaster` following conclusion of the unit tests 

```
I0211 14:29:20.042722 1767632 endpoints_controller.go:212] Shutting down endpoint controller
E0211 14:29:20.043166 1767632 runtime.go:79] Observed a panic: "send on closed channel" (send on closed channel)
goroutine 22 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x178aa60, 0x1ba8dc0})
        /home/astoycos/go/src/github.com/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x7d
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00031d040})
        /home/astoycos/go/src/github.com/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x178aa60, 0x1ba8dc0})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
k8s.io/apimachinery/pkg/watch.(*Broadcaster).ActionOrDrop(0x476c4f, {0x19b3916, 0x0}, {0x1bcc310, 0xc000242000})
        /home/astoycos/go/src/github.com/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/mux.go:225 +0x51
k8s.io/client-go/tools/record.(*recorderImpl).generateEvent(0xc0000c3d40, {0x1bcc2c0, 0xc0003fa780}, 0xad8ff6, {0x19b4bf4, 0x40ca87}, {0x19c40c7, 0x16}, {0xc000024000, 0x86})
        /home/astoycos/go/src/github.com/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record/event.go:349 +0x37b
k8s.io/client-go/tools/record.(*recorderImpl).Event(...)
        /home/astoycos/go/src/github.com/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record/event.go:355
k8s.io/client-go/tools/record.(*recorderImpl).Eventf(0x0, {0x1bcc2c0, 0xc0003fa780}, {0x19b4bf4, 0x7}, {0x19c40c7, 0x16}, {0x19e7b4b, 0xc00040e760}, {0xc0003822d0, ...})
        /home/astoycos/go/src/github.com/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record/event.go:359 +0xb4
k8s.io/kubernetes/pkg/controller/endpoint.(*Controller).syncService(0xc000148210, {0x1be21f8, 0xc0000c3e80}, {0xc000140780, 0xb})
        /home/astoycos/go/src/github.com/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go:578 +0x1ddd
k8s.io/kubernetes/pkg/controller/endpoint.(*Controller).processNextWorkItem(0xc000148210, {0x1be21f8, 0xc0000c3e80})
        /home/astoycos/go/src/github.com/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go:352 +0xfd
k8s.io/kubernetes/pkg/controller/endpoint.(*Controller).worker(...)
        /home/astoycos/go/src/github.com/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go:341
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
        /home/astoycos/go/src/github.com/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:188 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fafb2befad8)
        /home/astoycos/go/src/github.com/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x1bafea0, 0xc00040cf30}, 0x1, 0xc00010e0c0)
        /home/astoycos/go/src/github.com/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x0, 0x0)
        /home/astoycos/go/src/github.com/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext({0x1be21f8, 0xc0000c3e80}, 0xc00031c100, 0x0, 0x0, 0x0)
        /home/astoycos/go/src/github.com/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:188 +0x99
k8s.io/apimachinery/pkg/util/wait.UntilWithContext({0x1be21f8, 0xc0000c3e80}, 0x0, 0x0)
        /home/astoycos/go/src/github.com/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99 +0x2b
created by k8s.io/kubernetes/pkg/controller/endpoint.(*Controller).Run
        /home/astoycos/go/src/github.com/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go:203 +0x314
panic: send on closed channel [recovered]
        panic: send on closed channel
```

And after digging a little deeper I found the problem in the `ActionOrDrop` function, specifically a recorder may try to send an event to a broadcaster's incoming event channel even if the Broadcaster is shutdown 

```
func (m *Broadcaster) ActionOrDrop(action EventType, obj runtime.Object) bool {
	select {
	case m.incoming <- Event{action, obj}:
		return true
	default:
		return false
	}
}
```
Adding the following check to ensure we drop the event if the Broadcaster is already dropped seems to fix things. 

```
func (m *Broadcaster) ActionOrDrop(action EventType, obj runtime.Object) bool {
	select {
	case <-m.stopped:
		return false
	case m.incoming <- Event{action, obj}:
		return true
	default:
		return false
	}
}
```

I will push a PR to fix this soon.

**Comment by fedebongio** [comment]
/cc @aojea @wojtek-t @deads2k (since you are all commenting in the respective PR)

Thanks!
/triage accepted

**Comment by aojea** [comment]
/assign @astoycos 

he already has a PR https://github.com/kubernetes/kubernetes/pull/108080 and David's blessing
https://github.com/kubernetes/kubernetes/pull/108080#discussion_r821171649

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/110040 should address this once merged.
