### ISSUE TITLE
WebSocketNamespacedPodExecAsync get System.Net.Sockets.SocketException (10053) error

### ISSUE THREAD

**Issue by denli8** [kubernetes/kubernetes#108543]
### Which jobs are failing?

development environment：
development language：csharp & asp.net core 3.1
kuberentes version：1.20
KubernetesClient version: 4.0.26

I want to create a web terminal use kubernetes api,
but when I tried to create a websocket service, it reported an error;
so i need some help ,thank you !

### Which tests are failing?

```
public class WebSocketController : ControllerBase
{
        [HttpGet("/ws")]
        public async Task Get()
        {
            var config = 
            KubernetesClientConfiguration.BuildConfigFromConfigFile(Environment.GetEnvironmentVariable("KUBECONFIG"));
            var client = new Kubernetes(config);
            var list = client.ListNamespacedPod("default");
            var pod = list.Items.Where(x => x.Metadata.Name.Equals("system")).FirstOrDefault();
            using var webSocket = await client.WebSocketNamespacedPodExecAsync(pod.Metadata.Name,
                   "default", command, pod.Spec.Containers[0].Name).ConfigureAwait(true);
           await Echo(webSocket);
         }

        private static async Task Echo(WebSocket webSocket)
        {
            var buffer = new byte[1024 * 4];
            var receiveResult = await webSocket.ReceiveAsync(
            new ArraySegment<byte>(buffer), CancellationToken.None);

            while (!receiveResult.CloseStatus.HasValue)
            {
                  await webSocket.SendAsync(
                  new ArraySegment<byte>(buffer, 0, receiveResult.Count),
                  receiveResult.MessageType,
                  receiveResult.EndOfMessage,
                  CancellationToken.None);

                  receiveResult = await webSocket.ReceiveAsync(
                      new ArraySegment<byte>(buffer), CancellationToken.None);
             }

            await webSocket.CloseAsync(
                receiveResult.CloseStatus.Value,
                receiveResult.CloseStatusDescription,
                CancellationToken.None);
        }
}
```

**invoke code**
```
socket = new WebSocket(connectionUrl.value);
socket.onopen = function (event) {
    updateState();
    commsLog.innerHTML += '<tr>' +
        '<td colspan="3" class="commslog-data">Connection opened</td>' +
    '</tr>';
};
```

from ui, i get error :
Connection closed. Code: 1006.

### Since when has it been failing?

I got the following answers from the console：
An unhandled exception has occurred while executing the request.
```

Exception: 
System.IO.IOException: Unable to read data from the transport connection: The software in your host has aborted an established connection。.
 ---> System.Net.Sockets.SocketException (10053): The software in your host has aborted an established connection。
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.<WriteSingleChunk>g__CompleteAsync|210_1[TWriteAdapter](ValueTask writeTask, Byte[] bufferToReturn)
   at System.Net.Security.SslStream.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at websocketDemo.Controllers.WebSocketController.Echo(WebSocket webSocket) in C:\Users\source\repos\websocketDemo\websocketDemo\Controllers\WebSocketController.cs:line 50
   at websocketDemo.Controllers.WebSocketController.Get(String command) in C:\Users\source\repos\websocketDemo\websocketDemo\Controllers\WebSocketController.cs:line 34
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)


```

**Comment by pacoxu** [comment]
It sounds like a support ticket for https://github.com/kubernetes-client/csharp. 

/kind support

**Comment by neolit123** [comment]
does not seem like a core k8s issue. try contacting https://github.com/kubernetes-client/csharp
please reopen if there is more proof of a core k8s bug.

/close
