### ISSUE TITLE
[Failing test] gce-cos-master-scalability-100

### ISSUE THREAD

**Issue by lauralorenz** [kubernetes/kubernetes#108715]
### Which jobs are failing?
release-master-blocking

[gce-cos-master-scalability-100](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-scalability-100)

### Which tests are failing?

kubetest.ClusterLoaderV2
ci-kubernetes-e2e-gci-gce-scalability.Overall
ClusterLoaderV2.load: [step: 19] Collecting pod startup latency
ClusterLoaderV2.load overall (testing/load/config.yaml)
(intermittently) ClusterLoaderV2.load: [step: 25] Waiting for 'delete objects' to be completed

### Since when has it been failing?

3/15 6:47 PDT run; this run also happens to be the first at commit 1a5abe5d1

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-scalability-100

### Reason for failure (if possible)

```
[measurement call PodStartupLatency - PodStartupLatency error: pod startup: too high latency 99th percentile: got 10.515080076s expected: 5s]
```

### Relevant SIG(s)

/sig scalability

**Comment by lauralorenz** [comment]
Am I crazy or is this robot not working?

/sig scalability

**Comment by mborsz** [comment]
kube-scheduler:

```
0315 14:11:25.449772      11 scheduler.go:692] "Successfully bound pod to node" pod="test-1w3fvz-1/latency-deployment-67-5cb8c6bf86-psrtn" node="e2e-big-minion-group-wlt8" evaluatedNodes=101 feasibleNodes=99
```

kube-apiserver:

```
I0315 14:11:25.449403      11 httplog.go:131] "HTTP" verb="POST" URI="/api/v1/namespaces/test-1w3fvz-1/pods/latency-deployment-67-5cb8c6bf86-psrtn/binding" latency="2.029103ms" userAgent="kube-scheduler/v1.24.0 (linux/amd64) kubernetes/1a5abe5/scheduler" audit-ID="315f536a-7e25-4433-ae97-67d3f7efeb66" srcIP="[::1]:43282" apf_pl="workload-high" apf_fs="kube-scheduler" resp=201
I0315 14:11:25.453282      11 httplog.go:131] "HTTP" verb="GET" URI="/api/v1/namespaces/test-1w3fvz-1/pods/latency-deployment-67-5cb8c6bf86-psrtn" latency="1.34095ms" userAgent="Go-http-client/2.0" audit-ID="ee0a1380-509e-491a-9b52-22138ea11ae0" srcIP="10.40.3.224:35278" apf_pl="system" apf_fs="system-nodes" resp=200
I0315 14:11:25.458794      11 httplog.go:131] "HTTP" verb="PATCH" URI="/api/v1/namespaces/test-1w3fvz-1/pods/latency-deployment-67-5cb8c6bf86-psrtn/status" latency="4.305993ms" userAgent="Go-http-client/2.0" audit-ID="29334b89-0a15-4fcf-bea6-d3e0a4080230" srcIP="10.40.3.224:35278" apf_pl="system" apf_fs="system-nodes" resp=200
I0315 14:11:37.833079      11 httplog.go:131] "HTTP" verb="GET" URI="/api/v1/namespaces/test-1w3fvz-1/pods/latency-deployment-67-5cb8c6bf86-psrtn" latency="5.871236ms" userAgent="Go-http-client/2.0" audit-ID="16255076-ec3d-4497-8a86-3de3d93c2e7c" srcIP="10.40.3.224:35324" apf_pl="system" apf_fs="system-nodes" resp=200
I0315 14:11:37.861455      11 httplog.go:131] "HTTP" verb="PATCH" URI="/api/v1/namespaces/test-1w3fvz-1/pods/latency-deployment-67-5cb8c6bf86-psrtn/status" latency="27.021251ms" userAgent="Go-http-client/2.0" audit-ID="f6b3c0bd-b8ec-42b1-8a24-fb3b16356914" srcIP="10.40.3.224:35324" apf_pl="system" apf_fs="system-nodes" resp=200
I0315 14:11:39.136325      11 httplog.go:131] "HTTP" verb="GET" URI="/api/v1/namespaces/test-1w3fvz-1/pods/latency-deployment-67-5cb8c6bf86-psrtn" latency="2.207736ms" userAgent="Go-http-client/2.0" audit-ID="6d935024-2036-4381-be67-4b68790a8262" srcIP="10.40.3.224:35324" apf_pl="system" apf_fs="system-nodes" resp=200
I0315 14:11:39.142704      11 httplog.go:131] "HTTP" verb="PATCH" URI="/api/v1/namespaces/test-1w3fvz-1/pods/latency-deployment-67-5cb8c6bf86-psrtn/status" latency="4.806173ms" userAgent="Go-http-client/2.0" audit-ID="de38f195-aeb4-465b-a7d1-a9e57ffdc582" srcIP="10.40.3.224:35324" apf_pl="system" apf_fs="system-nodes" resp=200
I0315 14:13:07.827869      11 httplog.go:131] "HTTP" verb="GET" URI="/api/v1/namespaces/test-1w3fvz-1/pods/latency-deployment-67-5cb8c6bf86-psrtn" latency="1.547302ms" userAgent="Go-http-client/2.0" audit-ID="ba9572dc-ba66-44ac-ac1d-91617ed2ddf8" srcIP="10.40.3.224:35364" apf_pl="system" apf_fs="system-nodes" resp=200
I0315 14:13:14.632484      11 httplog.go:131] "HTTP" verb="GET" URI="/api/v1/namespaces/test-1w3fvz-1/pods/latency-deployment-67-5cb8c6bf86-psrtn" latency="1.285784ms" userAgent="kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/1a5abe5/system:serviceaccount:kube-system:generic-garbage-collector" audit-ID="a787cfab-105d-4794-a8a1-cacf983e93db" srcIP="[::1]:43518" apf_pl="workload-high" apf_fs="kube-system-service-accounts" resp=200
I0315 14:13:14.638045      11 httplog.go:131] "HTTP" verb="DELETE" URI="/api/v1/namespaces/test-1w3fvz-1/pods/latency-deployment-67-5cb8c6bf86-psrtn" latency="4.873993ms" userAgent="kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/1a5abe5/system:serviceaccount:kube-system:generic-garbage-collector" audit-ID="e416d0c1-a2b7-483c-b8cd-b1acd6107778" srcIP="[::1]:43518" apf_pl="workload-high" apf_fs="kube-system-service-accounts" resp=200
I0315 14:13:14.641316      11 httplog.go:131] "HTTP" verb="GET" URI="/api/v1/namespaces/test-1w3fvz-1/pods/latency-deployment-67-5cb8c6bf86-psrtn" latency="1.73244ms" userAgent="Go-http-client/2.0" audit-ID="5115ce4b-749f-440d-ab41-50c27a55bc46" srcIP="10.40.3.224:35364" apf_pl="system" apf_fs="system-nodes" resp=200
I0315 14:13:15.185544      11 httplog.go:131] "HTTP" verb="GET" URI="/api/v1/namespaces/test-1w3fvz-1/pods/latency-deployment-67-5cb8c6bf86-psrtn" latency="2.054178ms" userAgent="Go-http-client/2.0" audit-ID="857e05db-a4c7-4d89-8755-9d6a644b2ccd" srcIP="10.40.3.224:35364" apf_pl="system" apf_fs="system-nodes" resp=200
I0315 14:13:15.191930      11 httplog.go:131] "HTTP" verb="PATCH" URI="/api/v1/namespaces/test-1w3fvz-1/pods/latency-deployment-67-5cb8c6bf86-psrtn/status" latency="3.901442ms" userAgent="Go-http-client/2.0" audit-ID="79ae1ed7-08a0-4eef-8bf2-d6177de93e3c" srcIP="10.40.3.224:35364" apf_pl="system" apf_fs="system-nodes" resp=200
I0315 14:13:15.198270      11 httplog.go:131] "HTTP" verb="DELETE" URI="/api/v1/namespaces/test-1w3fvz-1/pods/latency-deployment-67-5cb8c6bf86-psrtn" latency="5.033096ms" userAgent="Go-http-client/2.0" audit-ID="447f2e58-4649-4fbd-9631-50a862f18d6f" srcIP="10.40.3.224:35364" apf_pl="system" apf_fs="system-nodes" resp=200
I0315 14:13:15.200311      11 httplog.go:131] "HTTP" verb="GET" URI="/api/v1/namespaces/test-1w3fvz-1/pods/latency-deployment-67-5cb8c6bf86-psrtn" latency="1.390126ms" userAgent="Go-http-client/2.0" audit-ID="f322a20e-7984-44a8-8793-c6745f60ee0e" srcIP="10.40.3.224:35364" apf_pl="system" apf_fs="system-nodes" resp=404
```

**Comment by mborsz** [comment]
Comparison of https://prow.k8s.io/prowjob?prowjob=bd9b46b8-a45e-11ec-b169-5a15552f8ec8 and https://prow.k8s.io/prowjob?prowjob=6c975cba-a466-11ec-b169-5a15552f8ec8 shows no diff (other than uuid/timestamp changes).

**Comment by mborsz** [comment]
https://storage.googleapis.com/sig-scalability-logs/ci-kubernetes-e2e-gci-gce-scalability/1503729543293177856/e2e-big-minion-group-wlt8/containerd.log

```
time="2022-03-15T14:11:25.758304621Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:latency-deployment-67-5cb8c6bf86-psrtn,Uid:fb1d35fb-d131-4564-a2ab-fff33f60a0c5,Namespace:test-1w3fvz-1,Attempt:0,}"
time="2022-03-15T14:11:25.839188091Z" level=info msg="starting signal loop" namespace=k8s.io path=/run/containerd/io.containerd.runtime.v2.task/k8s.io/c195613356d6e68b8dcfa6a200316d377917be2a15cfe2864e788ba4872dfe6e pid=11126
time="2022-03-15T14:11:26.219822385Z" level=info msg="RunPodSandbox for &PodSandboxMetadata{Name:latency-deployment-67-5cb8c6bf86-psrtn,Uid:fb1d35fb-d131-4564-a2ab-fff33f60a0c5,Namespace:test-1w3fvz-1,Attempt:0,} returns sandbox id \"c195613356d6e68b8dcfa6a2
00316d377917be2a15cfe2864e788ba4872dfe6e\""
time="2022-03-15T14:11:26.225394918Z" level=info msg="CreateContainer within sandbox \"c195613356d6e68b8dcfa6a200316d377917be2a15cfe2864e788ba4872dfe6e\" for container &ContainerMetadata{Name:latency-deployment-67,Attempt:0,}"
time="2022-03-15T14:11:26.273600741Z" level=info msg="CreateContainer within sandbox \"c195613356d6e68b8dcfa6a200316d377917be2a15cfe2864e788ba4872dfe6e\" for &ContainerMetadata{Name:latency-deployment-67,Attempt:0,} returns container id \"1be84c2ff671fc0707b
aa2f78ad8f9622c94fb119d97d54a65064a251bb9b1fb\""
time="2022-03-15T14:11:26.274987421Z" level=info msg="StartContainer for \"1be84c2ff671fc0707baa2f78ad8f9622c94fb119d97d54a65064a251bb9b1fb\""
time="2022-03-15T14:11:28.456375707Z" level=info msg="Finish piping stdout of container \"1be84c2ff671fc0707baa2f78ad8f9622c94fb119d97d54a65064a251bb9b1fb\""
time="2022-03-15T14:11:28.456375630Z" level=info msg="Finish piping stderr of container \"1be84c2ff671fc0707baa2f78ad8f9622c94fb119d97d54a65064a251bb9b1fb\""
time="2022-03-15T14:11:28.573977994Z" level=info msg="shim disconnected" id=1be84c2ff671fc0707baa2f78ad8f9622c94fb119d97d54a65064a251bb9b1fb
time="2022-03-15T14:11:28.574092507Z" level=error msg="copy shim log" error="read /proc/self/fd/469: file already closed"
time="2022-03-15T14:11:28.576348993Z" level=error msg="StartContainer for \"1be84c2ff671fc0707baa2f78ad8f9622c94fb119d97d54a65064a251bb9b1fb\" failed" error="failed to create containerd task: context canceled: unknown"
time="2022-03-15T14:11:36.868718529Z" level=info msg="Network plugin is ready, skip generating cni config from template \"/home/kubernetes/cni.template\""
time="2022-03-15T14:11:38.047112617Z" level=info msg="CreateContainer within sandbox \"c195613356d6e68b8dcfa6a200316d377917be2a15cfe2864e788ba4872dfe6e\" for container &ContainerMetadata{Name:latency-deployment-67,Attempt:1,}"
time="2022-03-15T14:11:38.096973704Z" level=info msg="CreateContainer within sandbox \"c195613356d6e68b8dcfa6a200316d377917be2a15cfe2864e788ba4872dfe6e\" for &ContainerMetadata{Name:latency-deployment-67,Attempt:1,} returns container id \"d4d21f3a53cf097abc4
fbd1e0b35611211018e201da5e6f98b37a2b7b671d69f\""
```

**Comment by mborsz** [comment]
Looks like the issue is on containerd level. It's interesting as we do not see any k8s change/prow job configuration change.

**Comment by Argh4k** [comment]
For both healthy/unhealthy run we use the same containerd
```
"starting containerd" revision=d71fcd7d8303cbf684402823e425e9dd2e99285d version=1.4.6
```

**Comment by Argh4k** [comment]
For healthy run:
```
Mar 15 11:06:36.017943 e2e-big-minion-group-0357 configure.sh[905]: ctr github.com/containerd/containerd 1.4.6
Mar 15 11:06:36.049774 e2e-big-minion-group-0357 configure.sh[905]: containerd github.com/containerd/containerd 1.4.6 d71fcd7d8303cbf684402823e425e9dd2e99285d
Mar 15 11:06:36.062778 e2e-big-minion-group-0357 configure.sh[905]: runc version 1.0.0-rc95
Mar 15 11:06:36.062778 e2e-big-minion-group-0357 configure.sh[905]: commit: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
Mar 15 11:06:36.062778 e2e-big-minion-group-0357 configure.sh[905]: spec: 1.0.2-dev
Mar 15 11:06:36.062778 e2e-big-minion-group-0357 configure.sh[905]: go: go1.13.5
Mar 15 11:06:36.062778 e2e-big-minion-group-0357 configure.sh[905]: libseccomp: 2.4.2
```

For unhealthy run:
```
Mar 15 13:54:19.437303 e2e-big-minion-group-01d1 configure.sh[898]: ctr github.com/containerd/containerd 1.4.6
Mar 15 13:54:19.469159 e2e-big-minion-group-01d1 configure.sh[898]: containerd github.com/containerd/containerd 1.4.6 d71fcd7d8303cbf684402823e425e9dd2e99285d
Mar 15 13:54:19.481082 e2e-big-minion-group-01d1 configure.sh[898]: runc version 1.0.0-rc95
Mar 15 13:54:19.481082 e2e-big-minion-group-01d1 configure.sh[898]: commit: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
Mar 15 13:54:19.481082 e2e-big-minion-group-01d1 configure.sh[898]: spec: 1.0.2-dev
Mar 15 13:54:19.481082 e2e-big-minion-group-01d1 configure.sh[898]: go: go1.13.5
Mar 15 13:54:19.481082 e2e-big-minion-group-01d1 configure.sh[898]: libseccomp: 2.4.2
```

**Comment by Argh4k** [comment]
Presubmit that uses the same configuration is passing:
![image](https://user-images.githubusercontent.com/22557451/158574468-ec3d7bfa-1d0e-44b3-bf89-d2b543227acb.png)

**Comment by mborsz** [comment]
https://storage.googleapis.com/sig-scalability-logs/ci-kubernetes-e2e-gci-gce-scalability/1503729543293177856/e2e-big-minion-group-wlt8/kubelet.log contains the answer:
```
I0315 14:11:26.259184   10683 kubelet.go:2077] "SyncLoop (PLEG): event for pod" pod="test-1w3fvz-1/latency-deployment-67-5cb8c6bf86-psrtn" event=&{ID:fb1d35fb-d131-4564-a2ab-fff33f60a0c5 Type:ContainerStarted Data:c195613356d6e68b8dcfa6a200316d377917be2a15cfe2864e788ba4872dfe6e}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d5d77b]
goroutine 2564 [running]:
k8s.io/kubernetes/pkg/kubelet/metrics/collectors.(*volumeStatsCollector).CollectWithStability(0x0?, 0xc0016df860)
        pkg/kubelet/metrics/collectors/volume_stats.go:129 +0x89b
k8s.io/kubernetes/vendor/k8s.io/component-base/metrics.(*BaseStableCollector).Collect.func1()
        vendor/k8s.io/component-base/metrics/collector.go:83 +0x2f
created by k8s.io/kubernetes/vendor/k8s.io/component-base/metrics.(*BaseStableCollector).Collect
        vendor/k8s.io/component-base/metrics/collector.go:82 +0x8d
kubelet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
kubelet.service: Failed with result 'exit-code'.
kubelet.service: Consumed 4.918s CPU time
kubelet.service: Service RestartSec=10s expired, scheduling restart.
kubelet.service: Scheduled restart job, restart counter is at 4.
Stopped Kubernetes kubelet.
kubelet.service: Consumed 4.918s CPU time
```

**Comment by mborsz** [comment]
OK, it looks like we found a root cause.

The question is why we haven't caught this as part of presubmit (which runs the same test as periodic)?

**Comment by Argh4k** [comment]
It looks like we have additional argument in periodic configuration compared to presubmit 
```
- --test-cmd-args=--prometheus-scrape-kubelets=true
```
which triggered the issue in periodics. We should align their configurations.

**Comment by Argh4k** [comment]
https://github.com/kubernetes/test-infra/issues/25647 was created for that.

**Comment by shuheiktgw** [comment]
The job has succeeded consecutively for the last ten runs, so I'm closing this issue 🙏 
/close
