### ISSUE TITLE
apiserver routines failing in integration tests

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#109026]
### What happened?

A lot of different routines failing just when setting up an apiserver.

Example:

<details>
```
goroutine 2535 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3dc2740?, 0xc005f64a50})
	/usr/local/google/home/acondor/go_k8s/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0xc002a7ae10, 0x1, 0x1737326?})
	/usr/local/google/home/acondor/go_k8s/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x3dc2740, 0xc005f64a50})
	/usr/local/google/home/acondor/.gvm/gos/go1.18/src/runtime/panic.go:838 +0x207
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc00089a660, {0x52ba780, 0xc005f61620}, 0xdf8475800?)
	/usr/local/google/home/acondor/go_k8s/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:120 +0x365
k8s.io/apiserver/pkg/endpoints/filters.withRequestDeadline.func1({0x52ba780, 0xc005f61620}, 0xc005f5f900)
	/usr/local/google/home/acondor/go_k8s/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/request_deadline.go:100 +0x494
net/http.HandlerFunc.ServeHTTP(0xc000a64c00?, {0x52ba780?, 0xc005f61620?}, 0x0?)
	/usr/local/google/home/acondor/.gvm/gos/go1.18/src/net/http/server.go:2084 +0x2f
k8s.io/apiserver/pkg/server/filters.withWaitGroup.func1({0x52ba780?, 0xc005f61620}, 0xc005f5f900)
	/usr/local/google/home/acondor/go_k8s/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:77 +0x766
net/http.HandlerFunc.ServeHTTP(0x52be1f8?, {0x52ba780?, 0xc005f61620?}, 0x5280bf0?)
	/usr/local/google/home/acondor/.gvm/gos/go1.18/src/net/http/server.go:2084 +0x2f
k8s.io/apiserver/pkg/endpoints/filters.WithWarningRecorder.func1({0x52ba780?, 0xc005f61620}, 0xc005f5f800)
	/usr/local/google/home/acondor/go_k8s/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/warning.go:35 +0x2bb
net/http.HandlerFunc.ServeHTTP(0x4567180?, {0x52ba780?, 0xc005f61620?}, 0xd?)
	/usr/local/google/home/acondor/.gvm/gos/go1.18/src/net/http/server.go:2084 +0x2f
k8s.io/apiserver/pkg/endpoints/filters.WithCacheControl.func1({0x52ba780, 0xc005f61620}, 0x5280b01?)
	/usr/local/google/home/acondor/go_k8s/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/cachecontrol.go:31 +0x126
net/http.HandlerFunc.ServeHTTP(0x52bf110?, {0x52ba780?, 0xc005f61620?}, 0x5280bf0?)
	/usr/local/google/home/acondor/.gvm/gos/go1.18/src/net/http/server.go:2084 +0x2f
k8s.io/apiserver/pkg/server/httplog.withLogging.func1({0x52bbec0, 0xc001765420}, 0xc005f5f700)
	/usr/local/google/home/acondor/go_k8s/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:130 +0x44d
net/http.HandlerFunc.ServeHTTP(0x52be1f8?, {0x52bbec0?, 0xc001765420?}, 0x5280bf0?)
	/usr/local/google/home/acondor/.gvm/gos/go1.18/src/net/http/server.go:2084 +0x2f
k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1({0x52bbec0, 0xc001765420}, 0xc005f5f600)
	/usr/local/google/home/acondor/go_k8s/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x316
net/http.HandlerFunc.ServeHTTP(0x52be1f8?, {0x52bbec0?, 0xc001765420?}, 0xc005f61560?)
	/usr/local/google/home/acondor/.gvm/gos/go1.18/src/net/http/server.go:2084 +0x2f
k8s.io/apiserver/pkg/endpoints/filters.withRequestReceivedTimestampWithClock.func1({0x52bbec0, 0xc001765420}, 0xc005f5f500)
	/usr/local/google/home/acondor/go_k8s/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/request_received_time.go:38 +0x27e
net/http.HandlerFunc.ServeHTTP(0x52be1f8?, {0x52bbec0?, 0xc001765420?}, 0x5280bf0?)
	/usr/local/google/home/acondor/.gvm/gos/go1.18/src/net/http/server.go:2084 +0x2f
k8s.io/apiserver/pkg/endpoints/filters.WithMuxAndDiscoveryComplete.func1({0x52bbec0, 0xc001765420}, 0xc005f5f400)
	/usr/local/google/home/acondor/go_k8s/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/mux_discovery_complete.go:52 +0x2c2
net/http.HandlerFunc.ServeHTTP(0x160?, {0x52bbec0?, 0xc001765420?}, 0x0?)
	/usr/local/google/home/acondor/.gvm/gos/go1.18/src/net/http/server.go:2084 +0x2f
k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1({0x52bbec0?, 0xc001765420?}, 0xc005f626e0?)
	/usr/local/google/home/acondor/go_k8s/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:73 +0xb1
net/http.HandlerFunc.ServeHTTP(0x4567180?, {0x52bbec0?, 0xc001765420?}, 0x8?)
	/usr/local/google/home/acondor/.gvm/gos/go1.18/src/net/http/server.go:2084 +0x2f
k8s.io/apiserver/pkg/endpoints/filters.withAuditID.func1({0x52bbec0, 0xc001765420}, 0xc005f5f300)
	/usr/local/google/home/acondor/go_k8s/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/with_auditid.go:66 +0x40d
net/http.HandlerFunc.ServeHTTP(0x479dc5?, {0x52bbec0?, 0xc001765420?}, 0xc004f05a70?)
	/usr/local/google/home/acondor/.gvm/gos/go1.18/src/net/http/server.go:2084 +0x2f
k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(...)
	/usr/local/google/home/acondor/go_k8s/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189
k8s.io/kubernetes/test/integration/framework.startAPIServerOrDie.func1({0x52bbec0?, 0xc001765420?}, 0x40ddec0?)
	/usr/local/google/home/acondor/go_k8s/src/k8s.io/kubernetes/test/integration/framework/controlplane_utils.go:160 +0x45
net/http.HandlerFunc.ServeHTTP(0xc0008fd2e5?, {0x52bbec0?, 0xc001765420?}, 0x40f905?)
	/usr/local/google/home/acondor/.gvm/gos/go1.18/src/net/http/server.go:2084 +0x2f
net/http.serverHandler.ServeHTTP({0x52a8958?}, {0x52bbec0, 0xc001765420}, 0xc005f5f300)
	/usr/local/google/home/acondor/.gvm/gos/go1.18/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc005f0d5e0, {0x52be1f8, 0xc000b07200})
	/usr/local/google/home/acondor/.gvm/gos/go1.18/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/google/home/acondor/.gvm/gos/go1.18/src/net/http/server.go:3071 +0x4db
```
</details>

### What did you expect to happen?

No errors

### How can we reproduce it (as minimally and precisely as possible)?

```golang
func TestMain(m *testing.M) {
	framework.EtcdMain(m.Run)
}

func TestDummy(t *testing.T) {
	controlPlaneConfig := framework.NewIntegrationTestControlPlaneConfig()
	_, _, apiServerCloseFn := framework.RunAnAPIServer(controlPlaneConfig)

	defer apiServerCloseFn()
}
```

https://github.com/alculquicondor/kubernetes/commit/cc5321fe372a0d923a7518cb417e917964cded20

### Anything else we need to know?

The test still passes, but those errors seem very worrisome

### Kubernetes version

<details>

master

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by alculquicondor** [comment]
/sig api-machinery
/sig testing
cc @aojea @liggitt

**Comment by liggitt** [comment]
all the panics I see are:

```
go test ./test/integration/job/ -run TestDummy -v | grep "Observed a panic"
E0325 14:15:52.092996   58909 runtime.go:77] Observed a panic: FieldManager must be installed to run apply
E0325 14:15:52.111588   58909 runtime.go:77] Observed a panic: FieldManager must be installed to run apply
E0325 14:15:52.115138   58909 runtime.go:77] Observed a panic: FieldManager must be installed to run apply
E0325 14:15:52.117694   58909 runtime.go:77] Observed a panic: FieldManager must be installed to run apply
E0325 14:15:52.120357   58909 runtime.go:77] Observed a panic: FieldManager must be installed to run apply
E0325 14:15:52.122678   58909 runtime.go:77] Observed a panic: FieldManager must be installed to run apply
E0325 14:15:52.125005   58909 runtime.go:77] Observed a panic: FieldManager must be installed to run apply
E0325 14:15:52.126972   58909 runtime.go:77] Observed a panic: FieldManager must be installed to run apply
E0325 14:15:52.129035   58909 runtime.go:77] Observed a panic: FieldManager must be installed to run apply
E0325 14:15:52.130971   58909 runtime.go:77] Observed a panic: FieldManager must be installed to run apply
E0325 14:15:52.133474   58909 runtime.go:77] Observed a panic: FieldManager must be installed to run apply
E0325 14:15:52.142742   58909 runtime.go:77] Observed a panic: FieldManager must be installed to run apply
E0325 14:15:52.214487   58909 runtime.go:77] Observed a panic: FieldManager must be installed to run apply
E0325 14:15:52.218160   58909 runtime.go:77] Observed a panic: FieldManager must be installed to run apply
E0325 14:15:52.223545   58909 runtime.go:77] Observed a panic: FieldManager must be installed to run apply
E0325 14:15:52.234307   58909 runtime.go:77] Observed a panic: FieldManager must be installed to run apply
```

**Comment by liggitt** [comment]
looks like https://github.com/kubernetes/kubernetes/issues/107727 again, due to https://github.com/kubernetes/kubernetes/pull/108383

**Comment by lavalamp** [comment]
https://github.com/kubernetes/kubernetes/blob/77eb1a03df5ed29db8b093bc1b89778388593c2f/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/patch.go#L476

Looks like some integration tests must not be enabling SSA.

**Comment by liggitt** [comment]
that's what https://github.com/kubernetes/kubernetes/issues/107727 is still open for
