### ISSUE TITLE
ci-cadvisor-e2e failed 

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#109186]
### Which jobs are failing?

ci-cadvisor-e2e

### Which tests are failing?

```
W0322 22:57:59.666] 2022/03/22 22:57:59 main.go:331: Something went wrong: encountered 1 errors: [error during go run /go/src/k8s.io/kubernetes/test/e2e_node/runner/remote/run_remote.go --cleanup --logtostderr --vmodule=*=4 --ssh-env=gce --results-dir=/workspace/_artifacts --project=ci-cadvisor-e2e --zone=us-central1-f --ssh-user=prow --ssh-key=/workspace/.ssh/google_compute_engine --ginkgo-flags=--nodes=1 --test_args= --test-timeout=10m0s --image-config-file=/workspace/test-infra/jobs/e2e_node/containerd/image-config.yaml --test-suite=cadvisor: exit status 1]
W0322 22:57:59.673] Traceback (most recent call last):
W0322 22:57:59.674]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 723, in <module>
W0322 22:57:59.674]     main(parse_args())
W0322 22:57:59.674]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 569, in main
W0322 22:57:59.674]     mode.start(runner_args)
W0322 22:57:59.674]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 228, in start
W0322 22:57:59.675]     check_env(env, self.command, *args)
W0322 22:57:59.675]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 111, in check_env
W0322 22:57:59.675]     subprocess.check_call(cmd, env=env)
W0322 22:57:59.675]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W0322 22:57:59.675]     raise CalledProcessError(retcode, cmd)
W0322 22:57:59.676] subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--deployment=node', '--provider=gce', '--cluster=bootstrap-e2e', '--gcp-network=bootstrap-e2e', '--gcp-project=ci-cadvisor-e2e', '--gcp-zone=us-central1-f', '--node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/containerd/image-config.yaml --test-suite=cadvisor', '--node-tests=true', '--test_args=--nodes=1', '--timeout=10m')' returned non-zero exit status 1
E0322 22:57:59.677] Command failed
I0322 22:57:59.678] process 339 exited with code 1 after 2.2m
E0322 22:57:59.678] FAIL: ci-cadvisor-e2e

```

### Since when has it been failing?
Since 03-22.

Changes list that may  

- https://github.com/kubernetes/kubernetes/compare/dd604a0f9a2e015a869d01957297e33f2c0c7025...95e30f66c?
- - Candidate1: https://github.com/kubernetes/kubernetes/pull/108704 （but for windows）
- https://github.com/kubernetes/test-infra/compare/ce1169a66...a6fe00c22 
- - Candidate1: https://github.com/kubernetes/test-infra/pull/25727 
- - Candidate2: https://github.com/kubernetes/test-infra/pull/25405

### Testgrid link

https://testgrid.k8s.io/sig-node-cadvisor#cadvisor-e2e

### Relevant SIG(s)

/sig node
/area cadvisor

**Comment by pacoxu** [comment]
/cc @bobbypage 
Would you give me some guide to look into the issue? Can this e2e run locally？

**Comment by bobbypage** [comment]
I think this is due to 1.18 golang bump in CI. cAdvisor does not currently build when using go1.18

```
porterdavid@porterdavid: ~/github/cadvisor on master [?$]
$ eval "$(gimme 1.17.8)"
go version go1.17.8 linux/amd64

porterdavid@porterdavid: ~/github/cadvisor on master [?$]
$ make build
>> building assets
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
>> building binaries
>> building cadvisor

porterdavid@porterdavid: ~/github/cadvisor on master [?$]
$ eval "$(gimme 1.18)"
go version go1.18 linux/amd64

porterdavid@porterdavid: ~/github/cadvisor on master [?$]
$ make build
>> building assets
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
make: *** [Makefile:72: assets] Error 1

```

**Comment by bobbypage** [comment]
xref: https://github.com/google/cadvisor/issues/3092

**Comment by bobbypage** [comment]
https://github.com/google/cadvisor/pull/3093 merged, let's see if it will make CI green.

**Comment by bobbypage** [comment]
Latest run is green

![image](https://user-images.githubusercontent.com/486583/162546344-15bca86a-ab2b-4695-a305-921412bdd4be.png)

**Comment by dims** [comment]
Sweet @bobbypage !
