### ISSUE TITLE
TestValidationExpressions timeout 10m

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#109225]
### Failure cluster [375262914f6b6fdcb255](https://go.k8s.io/triage#375262914f6b6fdcb255)
https://storage.googleapis.com/k8s-triage/index.html?text=TestValidationExpressions

##### Error text:
```
=== RUN   TestValidationExpressions/numeric_comparisons/double(self.val1)_<=_self.val4
=== PAUSE TestValidationExpressions/numeric_comparisons/double(self.val1)_<=_self.val4
    genericapiserver_graceful_termination_test.go:560: Sending request - timeout: 100ms, url: https://127.0.0.1:37295/echo?message=attempt-1
I0401 00:42:09.198209  104730 secure_serving.go:210] Serving securely on [::]:37295
I0401 00:42:09.198288  104730 tlsconfig.go:240] "Starting DynamicServingCertificateController"
    genericapiserver_graceful_termination_test.go:671: [server] seen new connection: &net.TCPConn{conn:net.conn{fd:(*net.netFD)(0xc000c7dc00)}}
    genericapiserver_graceful_termination_test.go:653: [server] received a request, proto: HTTP/2.0, url: /echo?message=attempt-1
    genericapiserver_graceful_termination_test.go:543: The API server has started
I0401 00:42:09.218278  104730 object_count_tracker.go:84] "StorageObjectCountTracker pruner is exiting"
    genericapiserver_graceful_termination_test.go:560: Sending request - timeout: 1s, url: https://127.0.0.1:37295/echo?message=attempt-0
    genericapiserver_graceful_termination_test.go:671: [server] seen new connection: &net.TCPConn{conn:net.conn{fd:(*net.netFD)(0xc0006cc280)}}
    genericapiserver_graceful_termination_test.go:560: Sending request - timeout: 1s, url: https://127.0.0.1:37295/echo?message=attempt-1
    genericapiserver_graceful_termination_test.go:671: [server] seen new connection: &net.TCPConn{conn:net.conn{fd:(*net.netFD)(0xc0004e6200)}}
    genericapiserver_graceful_termination_test.go:560: Sending request - timeout: 1s, url: https://127.0.0.1:37295/echo?message=attempt-2
    genericapiserver_graceful_termination_test.go:671: [server] seen new connection: &net.TCPConn{conn:net.conn{fd:(*net.netFD)(0xc0006cc000)}}
panic: test timed out after 10m0s

goroutine 6169 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:2029 +0xbb
created by time.goFunc
	/usr/local/go/src/time/sleep.go:176 +0x48

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000db04e0, {0x2cc0c1c, 0x14}, 0x2da58a0)
	/usr/local/go/src/testing/testing.go:1487 +0x750
testing.runTests.func1(0x0?)
	/usr/local/go/src/testing/testing.go:1839 +0x9a
testing.tRunner(0xc000db04e0, 0xc000879b28)
	/usr/local/go/src/testing/testing.go:1439 +0x214
testing.runTests(0xc0002d8aa0?, {0x42249c0, 0x17, 0x17}, {0x47d6d4?, 0x407e00?, 0x423ee20?})
	/usr/local/go/src/testing/testing.go:1837 +0x7e5
testing.(*M).Run(0xc0002d8aa0)
	/usr/local/go/src/testing/testing.go:1719 +0xa72
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.TestMain(0xc000100568?)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/genericapiserver_graceful_termination_test.go:47 +0x36
main.main()
	_testmain.go:93 +0x318

```
#### Recent failures:
[2022/4/1 07:51:37 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1509679315376148480)
[2022/3/31 13:50:25 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1509407218632495104)
[2022/3/30 01:47:11 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1508862835571036160)
[2022/3/29 07:47:17 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1508591042104922112)
[2022/3/28 13:46:10 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1508319007298555904)

/kind failing-test

**Comment by pacoxu** [comment]
The flake started after #108073 was merged.
/cc @benluddy @jpbetz
