### ISSUE TITLE
kubernetes/examples/cassandra  (v1.0.5) cluster setup not working

### ISSUE THREAD

**Issue by rroopreddy** [kubernetes/kubernetes#10931]
1. Followed the README.md for cluster setup with 4 nodes using

        $ kubectl scale rc cassandra --replicas=4

2. Following status command supposed to list all 4-nodes in cluster

        $ kubectl exec -ti cassandra -- nodetool status

Instead of 4-nodes, we **see just 1-node**. 

Seems like the "KubernetesSeedProvider" is not doing the needed cluster discovery?

**Comment by mwielgus** [comment]
Did you start cassandra service?
Could you please attach `kubectl logs` from all of the pods?

**Comment by rroopreddy** [comment]
I just tried with latest "Release 1.0.0 Candidate Two" to replicate original problem. kubectl command fails, let me wait for another release to see if I can get past this and duplicate Cassandra issue

>> ./cluster/kubectl.sh get nodes
error: couldn't read version from server: Get http://localhost:8080/api: dial tcp 127.0.0.1:8080: connection refused

**Comment by jamespshields** [comment]
Hello,

I am also seeing this problem, and for me it appears to be related to a missing file in the pod containers:

```
WARN  16:38:46 Request to kubernetes apiserver failed
java.nio.file.NoSuchFileException: /var/run/secrets/kubernetes.io/serviceaccount/token
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[na:1.7.0_79]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.7.0_79]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.7.0_79]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[na:1.7.0_79]
	at java.nio.file.Files.newByteChannel(Files.java:317) ~[na:1.7.0_79]
	at java.nio.file.Files.newByteChannel(Files.java:363) ~[na:1.7.0_79]
	at java.nio.file.Files.readAllBytes(Files.java:2981) ~[na:1.7.0_79]
	at io.k8s.cassandra.KubernetesSeedProvider.getServiceAccountToken(KubernetesSeedProvider.java:61) ~[kubernetes-cassandra.jar:na]
	at io.k8s.cassandra.KubernetesSeedProvider.getSeeds(KubernetesSeedProvider.java:108) ~[kubernetes-cassandra.jar:na]
	at org.apache.cassandra.config.DatabaseDescriptor.applyConfig(DatabaseDescriptor.java:654) [apache-cassandra-2.1.7.jar:2.1.7]
	at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:136) [apache-cassandra-2.1.7.jar:2.1.7]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:164) [apache-cassandra-2.1.7.jar:2.1.7]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:524) [apache-cassandra-2.1.7.jar:2.1.7]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:613) [apache-cassandra-2.1.7.jar:2.1.7]
```

I experience a similar issue (container fails to find service account token and dies) with the RethinkDB example. I have tried both Cassandra and RethinkDB examples locally via Docker, and also on Google Container Engine with same result. I am running the examples from kubernetes master branch c5bffaaf3166513da6259c44a5d1ba8e86bea5ce

**Comment by jamespshields** [comment]
Actually I take that back...both RethinkDB and Cassandra examples are working for me on a fresh GCE cluster with the latest example code. It's only when running locally via Docker that I have this issue, ala:
http://kubernetes.io/v1.0/docs/getting-started-guides/docker.html

**Comment by rroopreddy** [comment]
Finally I have Kubernetes cluster on Mac/Vagrant combination working with version 1.0.5. Running example/Cassandra as per instruction spins up pods/services/replicationcontrollers properly. However the original problem still remains, i.e: seed provider not working for a cluster discovery?

on a 4-node cluster the following command only returns one

kubectl exec -ti cassandra -- nodetool status

./cluster/kubectl.sh exec -ti cassandra -- nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address   Load       Tokens  Owns (effective)  Host ID                               Rack
UN  10.0.0.1  51.49 KB   256     100.0%            71f6f123-6cee-4bf5-b455-7d04a7dc0a2d  rack1

./cluster/kubectl.sh  logs cassandra

Returns the following error in logs of each of the pods

WARN  00:26:48 Request to kubernetes apiserver failed
java.net.UnknownHostException: kubernetes.default.cluster.local
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178) ~[na:1.7.0_79]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.7.0_79]
	at java.net.Socket.connect(Socket.java:579) ~[na:1.7.0_79]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:625) ~[na:1.7.0_79]
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:160) ~[na:1.7.0_79]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.7.0_79]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.7.0_79]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.7.0_79]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275) ~[na:1.7.0_79]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371) ~[na:1.7.0_79]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[na:1.7.0_79]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933) ~[na:1.7.0_79]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[na:1.7.0_79]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301) ~[na:1.7.0_79]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[na:1.7.0_79]
	at io.k8s.cassandra.KubernetesSeedProvider.getSeeds(KubernetesSeedProvider.java:124) ~[kubernetes-cassandra.jar:na]
	at org.apache.cassandra.config.DatabaseDescriptor.getSeeds(DatabaseDescriptor.java:1176) [apache-cassandra-2.1.7.jar:2.1.7]
	at org.apache.cassandra.gms.Gossiper.buildSeedsList(Gossiper.java:1318) [apache-cassandra-2.1.7.jar:2.1.7]
	at org.apache.cassandra.gms.Gossiper.start(Gossiper.java:1261) [apache-cassandra-2.1.7.jar:2.1.7]
	at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:792) [apache-cassandra-2.1.7.jar:2.1.7]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:714) [apache-cassandra-2.1.7.jar:2.1.7]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:605) [apache-cassandra-2.1.7.jar:2.1.7]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:378) [apache-cassandra-2.1.7.jar:2.1.7]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:524) [apache-cassandra-2.1.7.jar:2.1.7]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:613) [apache-cassandra-2.1.7.jar:2.1.7]
INFO  00:26:48 Starting Messaging Service on port 7000
INFO  00:26:48 Getting endpoints from https://kubernetes.default.cluster.local/api/v1/namespaces/default/endpoints/cassandra
WARN  00:26:48 Request to kubernetes apiserver failed
java.net.UnknownHostException: kubernetes.default.cluster.local

**Comment by bgrant0607** [comment]
@vishh @dlorenc: cassandra is an example we should test on the local dev cluster

**Comment by chrislovecnm** [comment]
@rroopreddy can you test this again?  It has been open for a long time and there have been multiple updates to the example.  Thanks

**Comment by chrislovecnm** [comment]
@brgrant0607 I recommend closing this.
