### ISSUE TITLE
Aggregator APIServer got panic when calling the `GetResourceKind`

### ISSUE THREAD

**Issue by astraw99** [kubernetes/kubernetes#109336]
### What happened?

We used the Aggregator APIServer in our cluster, but it got panic when calling the `GetResourceKind` at the startup.

Here is the stack:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x176d9c2]

goroutine 1 [running]:
github.com/xxx/CRD.(*REST).New(0x0)
        <autogenerated>:1 +0x22
k8s.io/apiserver/pkg/endpoints.GetResourceKind({{0x1cc4366, 0x16}, {0x1cacf33, 0x6}}, {0x1f26a20, 0x0}, {0x1f47ab8, 0xc00001a380})
        k8s.io/apiserver@v0.19.8/pkg/endpoints/installer.go:162 +0xc4
k8s.io/apiserver/pkg/endpoints.(*APIInstaller).registerResourceHandlers(0xc00199f718, {0x1cb9997, 0x1cb9997}, {0x1f26a20, 0x0}, 0xc00081ec40)
        k8s.io/apiserver@v0.19.8/pkg/endpoints/installer.go:200 +0x165
k8s.io/apiserver/pkg/endpoints.(*APIInstaller).Install(0xc00199f718)
        k8s.io/apiserver@v0.19.8/pkg/endpoints/installer.go:111 +0x279
k8s.io/apiserver/pkg/endpoints.(*APIGroupVersion).InstallREST(0xc0010b0b40, 0xc00070a0c0)
        k8s.io/apiserver@v0.19.8/pkg/endpoints/groupversion.go:105 +0x10c
k8s.io/apiserver/pkg/server.(*GenericAPIServer).installAPIResources(0xc00000a780, {0x1caa9af, 0x5}, 0xc00070a0c0, {0x0, 0x0})
        k8s.io/apiserver@v0.19.8/pkg/server/genericapiserver.go:423 +0x2d4
k8s.io/apiserver/pkg/server.(*GenericAPIServer).InstallAPIGroups(0xc00000a780, {0xc000326158, 0x1, 0xc000700570})
        k8s.io/apiserver@v0.19.8/pkg/server/genericapiserver.go:471 +0x24c
github.com/xxx/pkg/apiserver.CompletedConfig.New({{0xc00051bdb8}, 0xc00051bd30}, {0x1cb93ac, 0x1889e3c})
        github.com/xxx/pkg/apiserver/apiserver.go:84 +0x396
github.com/xxx/pkg/apiserver.RunAPIServer(0xc00051a1e0, 0x1)
        github.com/xxx/pkg/apiserver/run.go:30 +0x4b
github.com/xxx/pkg/apiserver.NewCommandStartServer.func1(0xc000246000, {0x1caa463, 0x4, 0x4})
        github.com/xxx/pkg/apiserver/cmd.go:46 +0x167
github.com/spf13/cobra.(*Command).execute(0xc000246000, {0xc00011a060, 0x4, 0x4})
        github.com/spf13/cobra@v1.1.1/command.go:850 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000246000)
        github.com/spf13/cobra@v1.1.1/command.go:958 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.1/command.go:895
main.main()
```
From the stack, we can see the `GetResourceKind` was called, but with nil panic in `storage.New()`.

### What did you expect to happen?

When registering REST storage at the APIServer startup, if the GVK scheme not found, just return the error, not panic.

### How can we reproduce it (as minimally and precisely as possible)?

Use the `Aggregator APIServer`, then add a CRD, but do not register the GVK sheme.
Start the APIServer, then it will panic.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.4-tke.23", GitCommit:"6581e1d61d266ea835f1f051122cccbc715c542f", GitTreeState:"clean", BuildDate:"2022-03-15T09:25:31Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```

</details>

**Comment by liggitt** [comment]
/close
per https://github.com/kubernetes/kubernetes/pull/109337#discussion_r847903735
