### ISSUE TITLE
ci-kubernetes-e2e-gce-iscsi and ci-kubernetes-e2e-gce-iscsi-serial are failing

### ISSUE THREAD

**Issue by Abirdcfly** [kubernetes/kubernetes#109645]
### Which jobs are failing?

ci-kubernetes-e2e-gce-iscsi-serial and ci-kubernetes-e2e-gce-iscsi

### Which tests are failing?

I guess it is create cluster step not tests
```
W0424 13:35:17.146] -----------------------------------------------------
W0424 13:35:17.147] * Expire in 0 ms for 6 (transfer 0x558db7d1b0f0)
W0424 13:35:17.147] * Expire in 5000 ms for 8 (transfer 0x558db7d1b0f0)
W0424 13:35:17.147] *   Trying 35.227.162.66...
W0424 13:35:17.147] * TCP_NODELAY set
W0424 13:35:17.147] * Expire in 200 ms for 4 (transfer 0x558db7d1b0f0)
W0424 13:35:17.147] * Connection timed out after 5001 milliseconds
W0424 13:35:17.147] * Closing connection 0
W0424 13:35:17.147] curl: (28) Connection timed out after 5001 milliseconds

...

W0424 13:42:40.840] 2022/04/24 13:42:40 main.go:331: Something went wrong: starting e2e cluster: error during ./hack/e2e-internal/e2e-up.sh: exit status 2
W0424 13:42:40.840] Traceback (most recent call last):
W0424 13:42:40.840]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 723, in <module>
W0424 13:42:40.840]     main(parse_args())
W0424 13:42:40.841]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 569, in main
W0424 13:42:40.841]     mode.start(runner_args)
W0424 13:42:40.841]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 228, in start
W0424 13:42:40.841]     check_env(env, self.command, *args)
W0424 13:42:40.842]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 111, in check_env
W0424 13:42:40.842]     subprocess.check_call(cmd, env=env)
W0424 13:42:40.842]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W0424 13:42:40.842]     raise CalledProcessError(retcode, cmd)
W0424 13:42:40.843] subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--provider=gce', '--cluster=bootstrap-e2e', '--gcp-network=bootstrap-e2e', '--check-leaked-resources', '--extract=ci/latest', '--gcp-node-image=ubuntu', '--image-family=ubuntu-2004-lts', '--image-project=ubuntu-os-cloud', '--gcp-zone=us-west1-b', '--test_args=--ginkgo.focus=\\[Driver:.iscsi\\].*(\\[Serial\\]|\\[Disruptive\\]) --ginkgo.skip=\\[Flaky\\] --minStartupPods=8', '--timeout=120m')' returned non-zero exit status 1
E0424 13:42:40.843] Command failed
I0424 13:42:40.843] process 272 exited with code 1 after 15.6m
E0424 13:42:40.843] FAIL: ci-kubernetes-e2e-gce-iscsi-serial
```

### Since when has it been failing?

Not clear

### Testgrid link

https://testgrid.k8s.io/sig-storage-kubernetes#gce-iscsi-serial

### Reason for failure (if possible)

I guess may be 
```bash
Apr 24 13:29:57.150050 bootstrap-e2e-master configure.sh[986]: Unable to automatically install containerd in non-ubuntu image. Bailing out...
```

From https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-iscsi-serial/1518219924101664768/artifacts/bootstrap-e2e-master/kube-master-installation.log

### Anything else we need to know?

I guess it is releated to https://github.com/kubernetes/kubernetes/issues/107377

### Relevant SIG(s)

/sig storage

**Comment by Abirdcfly** [comment]
From https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/109646/pull-kubernetes-e2e-gce-iscsi/1518505856285544448/artifacts/e2e-979482001b-decf4-master/kube-master-installation.log I get
```
Apr 25 08:48:13.114245 e2e-979482001b-decf4-master configure.sh[972]: + install-containerd-ubuntu
Apr 25 08:48:13.114611 e2e-979482001b-decf4-master configure.sh[972]: ++ command -v lsb_release
Apr 25 08:48:13.114876 e2e-979482001b-decf4-master configure.sh[972]: + [[ -z '' ]]
Apr 25 08:48:13.114957 e2e-979482001b-decf4-master configure.sh[972]: + echo 'Unable to automatically install containerd in non-ubuntu image. Bailing out...'
Apr 25 08:48:13.115001 e2e-979482001b-decf4-master configure.sh[972]: Unable to automatically install containerd in non-ubuntu image. Bailing out...
Apr 25 08:48:13.115052 e2e-979482001b-decf4-master configure.sh[972]: + exit 2
```
I think there's a problem here.
