### ISSUE TITLE
new invalid bearer token, square/go-jose: error in cryptographic primitive

### ISSUE THREAD

**Issue by 5279314** [kubernetes/kubernetes#109812]
### What happened?

I doubt whether the API configuration is wrong, because the created serviceaccount does not seem to be mounted in the pod container
```
[root@testwithsa /run/secrets/kubernetes.io/serviceaccount]$ curl --cacert ./ca.crt -H "Authorization: Bearer $(cat ./token)" https://10.1.1.100:6443/namespace/$(cat ./namespace)/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```
apiserver log
```
E0505 15:59:49.432822    7867 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, square/go-jose: error in cryptographic primitive]"
```

### What did you expect to happen?

All pods can operate normally. Please help analyze whether there are errors

### How can we reproduce it (as minimally and precisely as possible)?

try to apply the yaml file I supply blow.
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
  namespace: default
automountServiceAccountToken: true
---
apiVersion: v1
kind: Pod
metadata:
  name: testwithsa
  namespace: default
spec:
  containers:
  - name: amdinbox
    image: ikubernetes/admin-toolbox:v1.0
    imagePullPolicy: Always
  serviceAccountName: test
```

kube-apserver args
```
[root@k8s-master1 ~]# cat /opt/kubernetes/cfg/kube-apiserver.conf 
KUBE_APISERVER_OPTS="--logtostderr=false \
--v=2 \
--log-dir=/opt/kubernetes/logs \
--etcd-servers=https://10.1.1.100:2379,https://10.1.1.130:2379,https://10.1.1.120:2379 \
--bind-address=10.1.1.100 \
--secure-port=6443 \
--advertise-address=10.1.1.100 \
--allow-privileged=true \
--service-cluster-ip-range=192.168.0.0/16 \
--enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,NodeRestriction \
--authorization-mode=RBAC,Node \
--enable-bootstrap-token-auth=true \
--token-auth-file=/opt/kubernetes/cfg/token.csv \
--service-node-port-range=30000-32767 \
--kubelet-client-certificate=/opt/kubernetes/ssl/server.pem \
--kubelet-client-key=/opt/kubernetes/ssl/server-key.pem \
--client-ca-file=/opt/kubernetes/ssl/ca.pem \
--service-account-key-file=/opt/kubernetes/ssl/ca-key.pem \
--etcd-cafile=/opt/kubernetes/ssl/etcd/ca.pem \
--etcd-certfile=/opt/kubernetes/ssl/etcd/server.pem \
--etcd-keyfile=/opt/kubernetes/ssl/etcd/server-key.pem \
--service-account-issuer=api \
--service-account-signing-key-file=/opt/kubernetes/ssl/server-key.pem \
--tls-cert-file=/opt/kubernetes/ssl/server.pem  \
--tls-private-key-file=/opt/kubernetes/ssl/server-key.pem \
--proxy-client-cert-file=/opt/kubernetes/ssl/server.pem \
--proxy-client-key-file=/opt/kubernetes/ssl/server-key.pem \
--requestheader-allowed-names=kubernetes \
--requestheader-client-ca-file=/opt/kubernetes/ssl/ca.pem \
--requestheader-extra-headers-prefix=X-Remote-Extra- \
--requestheader-group-headers=X-Remote-Group \
--requestheader-username-headers=X-Remote-User \
--enable-aggregator-routing=true \
--audit-log-maxage=30 \
--audit-log-maxbackup=3 \
--audit-log-maxsize=100 \
--audit-log-path=/opt/kubernetes/logs/k8s-audit.log"
```
kube-controller-manager args
```
[root@k8s-master1 ~]# cat /opt/kubernetes/cfg/kube-controller-manager.conf 
KUBE_CONTROLLER_MANAGER_OPTS="--logtostderr=false \
--v=2 \
--log-dir=/opt/kubernetes/logs \
--leader-elect=true \
--kubeconfig=/opt/kubernetes/cfg/kube-controller-manager.kubeconfig \
--cluster-cidr=172.7.0.0/16 \
--service-cluster-ip-range=192.168.0.0/16 \
--cluster-signing-cert-file=/opt/kubernetes/ssl/ca.pem \
--cluster-signing-key-file=/opt/kubernetes/ssl/ca-key.pem  \
--root-ca-file=/opt/kubernetes/ssl/ca.pem \
--service-account-private-key-file=/opt/kubernetes/ssl/ca-key.pem \
--cluster-signing-duration=87600h0m0s"
```

 kube-scheduler.conf  args
```
KUBE_SCHEDULER_OPTS="--logtostderr=false \
--v=2 \
--log-dir=/opt/kubernetes/logs \
--leader-elect \
--kubeconfig=/opt/kubernetes/cfg/kube-scheduler.kubeconfig \
--bind-address=127.0.0.1"
```

### Anything else we need to know?

kube-co-m log
```
Log file created at: 2022/05/05 13:17:27
Running on machine: k8s-master1
Binary: Built with gc go1.17.9 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0505 13:17:27.963288    7994 controllermanager.go:298] leaderelection lost
goroutine 125 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0x1)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1038 +0x8a
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x779aa60, 0x3, 0x0, 0xc000641810, 0x0, {0x5f13e3a, 0x0}, 0xc000757b00, 0x0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:987 +0x5fd
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printf(0x0, 0x0, 0x0, {0x0, 0x0}, {0x471dbdf, 0x13}, {0x0, 0x0, 0x0})
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:753 +0x1c5
k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatalf(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1532
k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func4()
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:298 +0x55
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run.func1()
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:203 +0x1f
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc0000c98c0, {0x4e4a428, 0xc000140008})
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:213 +0x189
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection.RunOrDie({0x4e4a428, 0xc000140008}, {{0x4e911f0, 0xc000261040}, 0x37e11d600, 0x2540be400, 0x77359400, {0xc0007ab200, 0x48b9bb8, 0x0}, ...})
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:226 +0x94
k8s.io/kubernetes/cmd/kube-controller-manager/app.leaderElectAndRun(0xc000128538, {0xc0000b5ef0, 0x30}, 0xc00000d3e0, {0x46f5b3d, 0x6}, {0x4730b73, 0x17}, {0xc0007ab200, 0x48b9bb8, ...})
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:718 +0x2c5
created by k8s.io/kubernetes/cmd/kube-controller-manager/app.Run
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:283 +0x7c5
```
kube-api log
```
E0505 15:54:18.319100    7867 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, square/go-jose: error in cryptographic primitive]"
E0505 15:55:27.574617    7867 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, square/go-jose: error in cryptographic primitive]"
I0505 15:56:24.576807    7867 controller.go:611] quota admission added evaluator for: rolebindings.rbac.authorization.k8s.io
E0505 15:56:30.742378    7867 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, square/go-jose: error in cryptographic primitive]"
E0505 15:59:49.432822    7867 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, square/go-jose: error in cryptographic primitive]"
W0505 16:02:35.263506    7867 watcher.go:229] watch chan error: etcdserver: mvcc: required revision has been compacted
W0505 16:10:01.585297    7867 watcher.go:229] watch chan error: etcdserver: mvcc: required revision has been compacted
W0505 16:20:20.157816    7867 watcher.go:229] watch chan error: etcdserver: mvcc: required revision has been compacted
```

api-servceca.json
```
{
    "CN": "kubernetes",
    "hosts": [
      "192.168.0.1",
      "127.0.0.1",
      "kubernetes",
      "kubernetes.default",
      "kubernetes.default.svc",
      "kubernetes.default.svc.cluster",
      "kubernetes.default.svc.cluster.local",
                        "127.0.0.1",
                                "192.168.0.1",
                                "10.1.1.50",
                                "10.1.1.60",
                                "10.1.1.100",
                                "10.1.1.110",
                                "10.1.1.120",
                                "10.1.1.130",
                                "10.1.1.150"
                  ],
    "key": {
        "algo": "rsa",
        "size": 2048
    },
    "names": [
        {
            "C": "CN",
            "L": "BeiJing",
            "ST": "BeiJing",
            "O": "k8s",
            "OU": "System"
        }
    ]
}
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
CentOS Linux release 7.9.2009 (Core)
# paste output here
$ uname -a
Linux k8s-master1 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Shubham82** [comment]
Hi @5279314 

I have tried this issue but I got the following error:

```
$ curl --cacert ./ca.crt -H "Authorization:Bearer $(cat ./token)" https://xxx.xxx.xx.10:6443/namespace/$(cat ./namespace)/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:serviceaccount:default:test\" cannot get path \"/namespace/default/\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
```
and also there is no` "Unable to authenticate the request" err="[invalid bearer token, square/go-jose: error in cryptographic primitive]"`error  under kube-apiserver log. Did I miss something?
Are role and rolebinding help here? what do you think?

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by 5279314** [comment]
> testwithsa
Your serviceaccount does not have permission to manage the default namespace. Grant the serviceaccount permission to manage the default namespace
```shell
kubectl create rolebinding namespace-default-admin --clusterrole=admin --serviceaccount=default:test -n default
```

**Comment by 5279314** [comment]
> [<img alt="@5279314" width="20" height="20" src="https://avatars.githubusercontent.com/u/27267683?s=60&amp;v=4">](/5279314) [5279314](/5279314) 关闭此 [2分钟前](#event-6602501344)

**Comment by 5279314** [comment]
> 你好@5279314
> 
> 我已经尝试过这个问题，但出现以下错误：
> 
> ```
> $ curl --cacert ./ca.crt -H "Authorization:Bearer $(cat ./token)" https://xxx.xxx.xx.10:6443/namespace/$(cat ./namespace)/
> {
>   "kind": "Status",
>   "apiVersion": "v1",
>   "metadata": {},
>   "status": "Failure",
>   "message": "forbidden: User \"system:serviceaccount:default:test\" cannot get path \"/namespace/default/\"",
>   "reason": "Forbidden",
>   "details": {},
>   "code": 403
> }
> ```
> 
> ` "Unable to authenticate the request" err="[invalid bearer token, square/go-jose: error in cryptographic primitive]"`kube-api 下没有错误。我看服务器也 角色和角色绑定这里有帮助吗？
> 
> ```
> $ kubectl version
> Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
> ```

Your serviceaccount does not have permission to manage the default namespace. Grant the serviceaccount permission to manage the default namespace
```
kubectl create rolebinding namespace-default-admin --clusterrole=admin --serviceaccount=default:test -n default
```

**Comment by 5279314** [comment]
> 你好@5279314
> 
> 我已经尝试过这个问题，但出现以下错误：
> 
> ```
> $ curl --cacert ./ca.crt -H "Authorization:Bearer $(cat ./token)" https://xxx.xxx.xx.10:6443/namespace/$(cat ./namespace)/
> {
>   "kind": "Status",
>   "apiVersion": "v1",
>   "metadata": {},
>   "status": "Failure",
>   "message": "forbidden: User \"system:serviceaccount:default:test\" cannot get path \"/namespace/default/\"",
>   "reason": "Forbidden",
>   "details": {},
>   "code": 403
> }
> ```
> 
> ` "Unable to authenticate the request" err="[invalid bearer token, square/go-jose: error in cryptographic primitive]"`kube-api 下没有错误。我看服务器也 角色和角色绑定这里有帮助吗？
> 
> ```
> $ kubectl version
> Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
> ```

The authentication failed in my visit. I suspect there is an error in the args configuration of my api-server. Can I have a look at your Kube-apiserver args?

**Comment by Shubham82** [comment]
> 
> Your serviceaccount does not have permission to manage the default namespace. Grant the serviceaccount permission to manage the default namespace
> 
> ```
> kubectl create rolebinding namespace-default-admin --clusterrole=admin --serviceaccount=default:test -n default
> ```

Hi, @5279314 I tried this one, but still, get the same error.

```
$ kubectl get rolebinding namespace-default-admin -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2022-05-13T06:03:42Z"
  name: namespace-default-admin
  namespace: default
  resourceVersion: "54461436"
  uid: a30caaa8-27fa-497e-a20b-80550ae7fe9c
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: test
  namespace: default
```
After on run  this:
```
$ curl --cacert ./ca.crt -H "Authorization: Bearer $(cat ./token)" https://xxx.xxx.xx.10:6443/namespace/$(cat ./namespace)/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:serviceaccount:default:test\" cannot get path \"/namespace/default/\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
```

**Comment by Shubham82** [comment]
> The authentication failed in my visit. I suspect there is an error in the args configuration of my api-server. Can I have a look at your Kube-apiserver args?

Yeah, sure,  i searched but nothing related to this error, find the logs below:

```
I0513 04:59:58.560210       1 trace.go:205] Trace[1788797480]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/ubuntu-focal,user-agent:Go-http-client/2.0,audit-id:d5a590ba-f095-496f-b601-52f141a6553f,client:192.168.33.10,accept:application/vnd.kubernetes.protobuf,application/json,protocol:HTTP/2.0 (13-May-2022 04:59:57.994) (total time: 565ms):
Trace[1788797480]: ---"Object stored in database" 565ms (04:59:58.559)
Trace[1788797480]: [565.658724ms] [565.658724ms] END
I0513 05:30:53.782883       1 trace.go:205] Trace[1078522363]: "GuaranteedUpdate etcd3" type:*coordination.Lease (13-May-2022 05:30:53.072) (total time: 710ms):
Trace[1078522363]: ---"Transaction committed" 709ms (05:30:53.782)
Trace[1078522363]: [710.270186ms] [710.270186ms] END
I0513 05:30:53.783495       1 trace.go:205] Trace[755383581]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-scheduler,user-agent:kube-scheduler/v1.23.3 (linux/amd64) kubernetes/816c97a/leader-election,audit-id:00c799f9-145b-4417-a25e-4631a39f392a,client:192.168.33.10,accept:application/vnd.kubernetes.protobuf, */*,protocol:HTTP/2.0 (13-May-2022 05:30:53.072) (total time: 711ms):
Trace[755383581]: ---"Object stored in database" 710ms (05:30:53.782)
Trace[755383581]: [711.064733ms] [711.064733ms] END
I0513 05:30:53.788535       1 trace.go:205] Trace[1806163751]: "Get" url:/apis/coordination.k8s.io/v1/namespaces/tigera-operator/leases/operator-lock,user-agent:operator/v0.0.0 (linux/amd64) kubernetes/$Format/leader-election,audit-id:a1fd882f-1c57-4749-88ea-0dd209dab8f8,client:192.168.33.12,accept:application/json, */*,protocol:HTTP/2.0 (13-May-2022 05:30:53.069) (total time: 718ms):
Trace[1806163751]: ---"About to write a response" 718ms (05:30:53.788)
Trace[1806163751]: [718.497403ms] [718.497403ms] END
I0513 05:41:28.671359       1 trace.go:205] Trace[1891472725]: "Get" url:/api/v1/namespaces/tigera-operator/configmaps/operator-lock,user-agent:operator/v0.0.0 (linux/amd64) kubernetes/$Format/leader-election,audit-id:ffcfee99-46cb-4359-8def-e8bca5ac349d,client:192.168.33.12,accept:application/json, */*,protocol:HTTP/2.0 (13-May-2022 05:41:27.653) (total time: 1017ms):
Trace[1891472725]: ---"About to write a response" 1017ms (05:41:28.671)
Trace[1891472725]: [1.017689916s] [1.017689916s] END
I0513 06:05:24.754839       1 trace.go:205] Trace[2010102524]: "GuaranteedUpdate etcd3" type:*v1.Endpoints (13-May-2022 06:05:24.198) (total time: 556ms):
Trace[2010102524]: ---"Transaction committed" 553ms (06:05:24.754)
Trace[2010102524]: [556.751999ms] [556.751999ms] END
I0513 06:05:24.758168       1 trace.go:205] Trace[951546270]: "GuaranteedUpdate etcd3" type:*coordination.Lease (13-May-2022 06:05:24.203) (total time: 554ms):
Trace[951546270]: ---"Transaction committed" 552ms (06:05:24.758)
Trace[951546270]: [554.392451ms] [554.392451ms] END
I0513 06:05:24.758853       1 trace.go:205] Trace[879006556]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/workernode2,user-agent:Go-http-client/2.0,audit-id:93dce897-f357-4170-b914-665793262be0,client:192.168.33.12,accept:application/vnd.kubernetes.protobuf,application/json,protocol:HTTP/2.0 (13-May-2022 06:05:24.202) (total time: 556ms):
Trace[879006556]: ---"Object stored in database" 554ms (06:05:24.758)
Trace[879006556]: [556.169287ms] [556.169287ms] END
I0513 06:14:47.851732       1 trace.go:205] Trace[1703152084]: "GuaranteedUpdate etcd3" type:*coordination.Lease (13-May-2022 06:14:46.979) (total time: 872ms):
Trace[1703152084]: ---"Transaction committed" 870ms (06:14:47.851)
Trace[1703152084]: [872.412302ms] [872.412302ms] END
I0513 06:14:47.852484       1 trace.go:205] Trace[1133090392]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/workernode2,user-agent:Go-http-client/2.0,audit-id:90327a03-fd6a-45ce-b82a-15577643a5e2,client:192.168.33.12,accept:application/vnd.kubernetes.protobuf,application/json,protocol:HTTP/2.0 (13-May-2022 06:14:46.978) (total time: 873ms):
Trace[1133090392]: ---"Object stored in database" 872ms (06:14:47.851)
Trace[1133090392]: [873.569866ms] [873.569866ms] END
I0513 06:14:47.859790       1 trace.go:205] Trace[1526720283]: "Get" url:/apis/coordination.k8s.io/v1/namespaces/tigera-operator/leases/operator-lock,user-agent:operator/v0.0.0 (linux/amd64) kubernetes/$Format/leader-election,audit-id:3a1d2271-21e2-4597-aeed-68887314915a,client:192.168.33.12,accept:application/json, */*,protocol:HTTP/2.0 (13-May-2022 06:14:46.802) (total time: 1057ms):
Trace[1526720283]: ---"About to write a response" 1057ms (06:14:47.859)
Trace[1526720283]: [1.057418528s] [1.057418528s] END
I0513 06:14:47.862724       1 trace.go:205] Trace[1873209453]: "GuaranteedUpdate etcd3" type:*coordination.Lease (13-May-2022 06:14:46.798) (total time: 1064ms):
Trace[1873209453]: ---"Transaction committed" 1062ms (06:14:47.862)
Trace[1873209453]: [1.064155678s] [1.064155678s] END
I0513 06:14:47.863050       1 trace.go:205] Trace[1394624123]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-controller-manager,user-agent:kube-controller-manager/v1.23.3 (linux/amd64) kubernetes/816c97a/leader-election,audit-id:ac1588f9-aa44-4914-abac-5712136e21ca,client:192.168.33.10,accept:application/vnd.kubernetes.protobuf, */*,protocol:HTTP/2.0 (13-May-2022 06:14:46.798) (total time: 1064ms):
Trace[1394624123]: ---"Object stored in database" 1064ms (06:14:47.862)
Trace[1394624123]: [1.064637133s] [1.064637133s] END
I0513 06:24:24.814528       1 trace.go:205] Trace[856723605]: "GuaranteedUpdate etcd3" type:*coordination.Lease (13-May-2022 06:24:24.295) (total time: 519ms):
Trace[856723605]: ---"Transaction committed" 518ms (06:24:24.814)
Trace[856723605]: [519.16505ms] [519.16505ms] END
I0513 06:24:24.814906       1 trace.go:205] Trace[118813325]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-controller-manager,user-agent:kube-controller-manager/v1.23.3 (linux/amd64) kubernetes/816c97a/leader-election,audit-id:9db7821c-a986-4058-bf09-196c1cdd5d36,client:192.168.33.10,accept:application/vnd.kubernetes.protobuf, */*,protocol:HTTP/2.0 (13-May-2022 06:24:24.295) (total time: 519ms):
Trace[118813325]: ---"Object stored in database" 519ms (06:24:24.814)
Trace[118813325]: [519.649593ms] [519.649593ms] END
I0513 06:31:14.336585       1 trace.go:205] Trace[1054369249]: "GuaranteedUpdate etcd3" type:*coordination.Lease (13-May-2022 06:31:13.731) (total time: 605ms):
Trace[1054369249]: ---"Transaction committed" 604ms (06:31:14.336)
Trace[1054369249]: [605.39498ms] [605.39498ms] END
I0513 06:31:14.336901       1 trace.go:205] Trace[832323090]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-scheduler,user-agent:kube-scheduler/v1.23.3 (linux/amd64) kubernetes/816c97a/leader-election,audit-id:92ac42f9-a1d6-4913-849e-227e7e811df1,client:192.168.33.10,accept:application/vnd.kubernetes.protobuf, */*,protocol:HTTP/2.0 (13-May-2022 06:31:13.731) (total time: 605ms):
Trace[832323090]: ---"Object stored in database" 605ms (06:31:14.336)
Trace[832323090]: [605.83612ms] [605.83612ms] END

```

**Comment by 5279314** [comment]
> curl --cacert ./ca.crt -H "Authorization: Bearer $(cat ./token)" https://10.1.1.100:6443/namespace/$(cat ./namespace)/
> {
You try to access the following API, but my successful version is 1.20.x  Kubernetes，I'm still working on this issue after version 1.23.

```
[root@testwithsa /run/secrets/kubernetes.io/serviceaccount]# curl --cacert ./ca.crt -H "Authorization: Bearer $(cat ./token)" https://10.1.1.100:6443/api/v1/namesp
aces/$(cat ./namespace)/
{
  "kind": "Namespace",
  "apiVersion": "v1",
  "metadata": {
    "name": "default",
    "uid": "170e11bb-c2ea-43bd-8e34-277e72a6492f",
    "resourceVersion": "203",
    "creationTimestamp": "2022-05-14T05:15:51Z",
    "managedFields": [
      {
        "manager": "kube-apiserver",
        "operation": "Update",
        "apiVersion": "v1",
        "time": "2022-05-14T05:15:51Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {"f:status":{"f:phase":{}}}
      }
    ]
  },
  "spec": {
    "finalizers": [
      "kubernetes"
    ]
  },
  "status": {
    "phase": "Active"
  }
}
```

**Comment by 5279314** [comment]
@kubernetes
Can kubernetes officials help solve the following problem? Or do you have relevant technical documents for reference。

**Comment by Shubham82** [comment]
Hi @5279314 
I checked this on both k8s v1.20.0 and v1.23.3, With the following steps it's working for me in both, please follow the below steps:
1) Create ServiceAccount:

> apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
  namespace: default


2) Attach the role/clusterrole and rolebinding/clusterrolebinding:

> kubectl create rolebinding namespace-default-admin --clusterrole=admin --serviceaccount=default:test -n default

3) Deploy pod:

```
 apiVersion: v1
kind: Pod
metadata:
  name: testwithsa
  namespace: default
spec:
  containers:
  - name: amdinbox
    image: ikubernetes/admin-toolbox:v1.0
    imagePullPolicy: Always
  serviceAccountName: test

```
4) Now access the pod:

> kubectl exec -it testwithsa -- /bin/bash

5) Run the following command:

> curl --cacert ./ca.crt -H "Authorization: Bearer $(cat ./token)" https://xxx.xxx.xx.10:6443/api/v1/namespaces/$(cat ./namespace)/

We have to assign role and rolebinding to SA before deplying pod. This is working for me please see below output of k8sv1.23.3:
```
[root@testwithsa /run/secrets/kubernetes.io/serviceaccount]$ curl --cacert ./ca.crt -H "Authorization: Bearer $(cat ./token)" https://xxx.xxx.xx.10:6443/api/v1/namespaces/$(cat ./namespace)/
{
  "kind": "Namespace",
  "apiVersion": "v1",
  "metadata": {
    "name": "default",
    "uid": "741f85c0-3cb8-4be1-b361-e2814261820d",
    "resourceVersion": "204",
    "creationTimestamp": "2021-08-24T06:25:40Z",
    "labels": {
      "kubernetes.io/metadata.name": "default"
    },
    "managedFields": [
      {
        "manager": "kube-apiserver",
        "operation": "Update",
        "apiVersion": "v1",
        "time": "2021-08-24T06:25:40Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:metadata": {
            "f:labels": {
              ".": {},
              "f:kubernetes.io/metadata.name": {}
            }
          }
        }
      }
    ]
  },
  "spec": {
    "finalizers": [
      "kubernetes"
    ]
  },
  "status": {
    "phase": "Active"
  }
}
```

**Comment by ritazh** [comment]
/close

Looks like https://github.com/kubernetes/kubernetes/issues/109812#issuecomment-1128890327 has a suggested solution. Going to close this. Feel free to reopen if issue persists.
