### ISSUE TITLE
"kubectl alpha events -A -w" panics with "interface conversion: runtime.Object is *v1.Status, not *v1.Event"

### ISSUE THREAD

**Issue by invidian** [kubernetes/kubernetes#110622]
### What happened?

After 4 minutes or running `kubectl alpha events -A -w`, I got the following panic:
```console
panic: interface conversion: runtime.Object is *v1.Status, not *v1.Event

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/events.EventsOptions.runWatch.func1.1({{0x55de7e1f880d?, 0xc000a351f0?}, {0x55de7eb02840?, 0xc000c83c20?}})
        vendor/k8s.io/kubectl/pkg/cmd/events/events.go:247 +0x19f
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/watch.UntilWithoutRetry({0x55de7eb122c8, 0xc0000b25c0}, {0x55de7eb02bd8, 0xc0000b2580}, {0xc0001572d8, 0x1, 0x55de7cd3c651?})
        vendor/k8s.io/client-go/tools/watch/until.go:80 +0x38a
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/events.EventsOptions.runWatch.func1()
        vendor/k8s.io/kubectl/pkg/cmd/events/events.go:243 +0x85
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/interrupt.(*Handler).Run(0xc000596de0, 0xc000d9f490)
        vendor/k8s.io/kubectl/pkg/util/interrupt/interrupt.go:103 +0x12e
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/events.EventsOptions.runWatch({{0xc0007132b0, 0x9}, 0x1, 0x1, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, ...}, ...)
        vendor/k8s.io/kubectl/pkg/cmd/events/events.go:242 +0x2b9
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/events.EventsOptions.Run({{0xc0007132b0, 0x9}, 0x1, 0x1, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, ...})
        vendor/k8s.io/kubectl/pkg/cmd/events/events.go:191 +0x53e
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/events.NewCmdEvents.func1(0xc000c1c500?, {0xc00037a6a0?, 0x0?, 0x2?})
        vendor/k8s.io/kubectl/pkg/cmd/events/events.go:122 +0xc5
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000c1c500, {0xc00037a680, 0x2, 0x2})
        vendor/github.com/spf13/cobra/command.go:860 +0x663
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000950500)
        vendor/github.com/spf13/cobra/command.go:974 +0x3b4
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        vendor/github.com/spf13/cobra/command.go:902
k8s.io/kubernetes/vendor/k8s.io/component-base/cli.run(0xc000950500)
        vendor/k8s.io/component-base/cli/run.go:146 +0x305
k8s.io/kubernetes/vendor/k8s.io/component-base/cli.RunNoErrOutput(...)
        vendor/k8s.io/component-base/cli/run.go:84
main.main()
```

### What did you expect to happen?

I expected watching events to work continuously.

### How can we reproduce it (as minimally and precisely as possible)?

Not at the moment but will try to reproduce it.

### Kubernetes version

<details>

```console
$ kubectl version --output=yaml
clientVersion:
  buildDate: "2022-05-27T18:33:09Z"
  compiler: gc
  gitCommit: 3ddd0f45aa91e2f30c70734b175631bec5b5825a
  gitTreeState: archive
  gitVersion: v1.24.1
  goVersion: go1.18.2
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-05-24T12:18:48Z"
  compiler: gc
  gitCommit: 3ddd0f45aa91e2f30c70734b175631bec5b5825a
  gitTreeState: clean
  gitVersion: v1.24.1
  goVersion: go1.18.2
  major: "1"
  minor: "24"
  platform: linux/amd64
```

</details>

### Cloud provider

<details>
Hetzner Cloud
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ardaguclu** [comment]
Thanks for raising this issue @invidian 

This PR https://github.com/kubernetes/kubernetes/pull/110007 also fixes that issue

/triage accepted

**Comment by invidian** [comment]
/assign @ardaguclu

Awesome, thanks for taking care of it :)
