### ISSUE TITLE
[Falling test] skew-cluster-latest-kubectl-stable1-gce kubetest.Extract

### ISSUE THREAD

**Issue by shuheiktgw** [kubernetes/kubernetes#111161]
### Which jobs are failing?

- [skew-cluster-latest-kubectl-stable1-gce](https://testgrid.k8s.io/sig-release-master-blocking#skew-cluster-latest-kubectl-stable1-gce)

### Which tests are failing?

- kubetest.Extract

### Since when has it been failing?

7/13

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#skew-cluster-latest-kubectl-stable1-gce

### Reason for failure (if possible)

```
W0714 15:50:02.387] 2022/07/14 15:50:02 main.go:331: Something went wrong: failed to acquire k8s binaries: Failed to set release from https://storage.googleapis.com/k8s-release-dev/ci/k8s-stable1.txt (Unexpected HTTP status code: 404)
W0714 15:50:02.388] Traceback (most recent call last):
W0714 15:50:02.389]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 723, in <module>
W0714 15:50:02.389]     main(parse_args())
W0714 15:50:02.389]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 569, in main
W0714 15:50:02.389]     mode.start(runner_args)
W0714 15:50:02.389]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 228, in start
W0714 15:50:02.389]     check_env(env, self.command, *args)
W0714 15:50:02.390]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 111, in check_env
W0714 15:50:02.390]     subprocess.check_call(cmd, env=env)
W0714 15:50:02.390]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W0714 15:50:02.390]     raise CalledProcessError(retcode, cmd)
W0714 15:50:02.391] subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--provider=gce', '--cluster=bootstrap-e2e', '--gcp-network=bootstrap-e2e', '--check-leaked-resources', '--check-version-skew=false', '--extract=ci/k8s-stable1', '--extract=ci/latest', '--extract-ci-bucket=k8s-release-dev', '--gcp-node-image=gci', '--gcp-zone=us-west1-b', '--ginkgo-parallel=25', '--skew', '--test_args=--ginkgo.focus=Kubectl --ginkgo.skip=\\[Serial\\]|\\[Deprecated\\] --minStartupPods=8', '--timeout=120m')' returned non-zero exit status 1
E0714 15:50:02.397] Command failed
I0714 15:50:02.397] process 272 exited with code 1 after 0.0m
E0714 15:50:02.397] FAIL: ci-kubernetes-e2e-gce-master-new-gci-kubectl-skew
```

### Anything else we need to know?

[This](https://kubernetes.slack.com/archives/C2C40FMNF/p1645745536091569) may relate to the issue

### Relevant SIG(s)

/sig release

**Comment by saschagrunert** [comment]
I have a fix in mind in https://github.com/kubernetes/test-infra/pull/26824

**Comment by saschagrunert** [comment]
The new config is applied and the job run successfully: https://prow.k8s.io/log?job=ci-kubernetes-build-1-24&id=1547843272590757888

Unfortunately, it will only update the marker if the build is new. To avoid requiring a new merge into the release-1.24 branch, I manually restored the marker file for now: https://storage.googleapis.com/k8s-release-dev/ci/k8s-stable1.txt
