### ISSUE TITLE
logcheck plugin for golangci-lint fails under golang 1.19

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#111297]
See failure in https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/111254/pull-kubernetes-verify-go-canary/1549738608821276672/build-log.txt

```
regexp.(*Regexp).tryBacktrack(0x18a98c0, 0xc0274ae130, {0x0?, 0xc014d13008}, 0xd03a17?, 0x37?)
	/usr/local/go/src/regexp/backtrack.go:172 +0xcc5 fp=0xc014d12f60 sp=0xc014d12ea8 pc=0xa86e85
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
	/home/prow/go/pkg/mod/github.com/golangci/golangci-lint@v1.46.2/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x1eb
```	

it's quite possible that golangci-lint is tripping up on an “optimization” done in golang’s regexp package - https://github.com/golang/go/commit/0293c51bc5d8ca0728913c4b7f9f92339f8fd9a6

![image](https://user-images.githubusercontent.com/23304/180287095-56af2ebb-e6bd-4c78-98a9-ca2d5d3048e3.png)

cc @pohly

**Comment by dims** [comment]
So reverting the patch https://github.com/golang/go/commit/0293c51bc5d8ca0728913c4b7f9f92339f8fd9a6 and rebuilding go environment like so ... fixes the problem

```
$ GOROOT_BOOTSTRAP=/usr/lib/go-1.18.2/ make.bash
Building Go cmd/dist using /usr/lib/go-1.18.2/. (go1.18.2 linux/amd64)
Building Go toolchain1 using /usr/lib/go-1.18.2/.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for linux/amd64.
---
Installed Go for linux/amd64 in /usr/lib/go-1.19rc2
Installed commands in /usr/lib/go-1.19rc2/bin
```

**Comment by dims** [comment]
longer slack conversation with @liggitt and things we tried are here:
https://kubernetes.slack.com/archives/CHGFYJVAN/p1658400081793929

**Comment by dims** [comment]
Things we tried:
- commenting out logcheck entirely (works fine)
- commenting out all the regexp in the logcheck conf (works fine)
- running on darwin/arm64 (works fine)
- commenting out all linters expect for logcheck (works fine)
- have a duplicate logcheck2 in .golangci.yaml (works fine)
- run logcheck as a binary and not as a plugin (works fine)

So essentially this is a problem that happens on linux/amd64 for sure. The golang built-in Run-time plugin is involved here in the mix. golangci-lint essentially discovers the logcheck shared object and runs the linter in the shared object (golangci-lint essentially uses `go func` with sync.WaitGroup to call the methods in the shared object linter (see [here](https://github.com/golangci/golangci-lint/blob/0abb2981360f912786371b325f181871cf534f6a/pkg/golinters/goanalysis/runner_loadingpackage.go)) when the method in the shared object calls regexp stuff, it blows up the stack with the following trace

```
goroutine 53610 [running]:
runtime.systemstack_switch()
	/usr/lib/go-1.19rc2/src/runtime/asm_amd64.s:459 fp=0xc00daf88f8 sp=0xc00daf88f0 pc=0x8e4220
runtime.addOneOpenDeferFrame(0xc00daf8978?, 0x7f1b3423f8a5?, 0x23a3ee0?)
	/usr/lib/go-1.19rc2/src/runtime/panic.go:644 +0x69 fp=0xc00daf8938 sp=0xc00daf88f8 pc=0x8b0a29
panic({0x1479820, 0x189b1f0})
	/usr/lib/go-1.19rc2/src/runtime/panic.go:844 +0x112 fp=0xc00daf89f8 sp=0xc00daf8938 pc=0x8b1272
runtime: g 53610: unexpected return pc for regexp.(*Regexp).tryBacktrack called from 0xc00139eb00
stack: frame={sp:0xc00daf89f8, fp:0xc00daf8ab0} stack=[0xc00daf8000,0xc00dafa000)
0x000000c00daf88f8:  0x000000c00daf8900  0x00000000008b0a80 <runtime.addOneOpenDeferFrame.func1+0x0000000000000000> 
0x000000c00daf8908:  0x0000000000a86cc5 <regexp.(*Regexp).tryBacktrack+0x0000000000000cc5>  0x000000c00daf89f8 
0x000000c00daf8918:  0x000000c0010a7d40  0x0000000000000000 
0x000000c00daf8928:  0x000000c00daf89e8  0x00000000008b1272 <runtime.gopanic+0x0000000000000112> 
0x000000c00daf8938:  0x000000c00daf8978  0x00007f1b3423f8a5 <runtime.(*mcache).refill+0x00000000000001e5> 
0x000000c00daf8948:  0x00000000023a3ee0  0x00007f1b3424b067 <runtime.(*gcControllerState).heapGoalInternal+0x0000000000000027> 
0x000000c00daf8958:  0x0000000000000a80  0x000000000bbe1ae8 
0x000000c00daf8968:  0x000000c00daf89a8  0x00007f1b3424b1a5 <runtime.(*gcControllerState).trigger+0x0000000000000025> 
0x000000c00daf8978:  0x00000000023a56e0  0x00007f1b342352fe <runtime.(*mcache).nextFree+0x000000000000009e> 
0x000000c00daf8988:  0x00007f1b44283a18  0x0000000000203000 
0x000000c00daf8998:  0x0000000000203000  0x000000c0010a7d60 
0x000000c00daf89a8:  0x000000c0010a7d40  0x0000000000000000 
0x000000c00daf89b8:  0x0000000001479820  0x000000000189b1f0 
0x000000c00daf89c8:  0x0000000000000000  0x0000000000000000 
0x000000c00daf89d8:  0x0000000000000000  0x0000000000000000 
0x000000c00daf89e8:  0x000000c00daf8a90  0x0000000000a86cc5 <regexp.(*Regexp).tryBacktrack+0x0000000000000cc5> 
0x000000c00daf89f8: <0x0000000001479820  0x000000000189b1f0 
0x000000c00daf8a08:  0x00007f1b6c914fe8  0x0000000000000010 
0x000000c00daf8a18:  0x000000c000600400  0x000000c0162b1540 
0x000000c00daf8a28:  0x0000000000000000  0x00000000000000a0 
0x000000c00daf8a38:  0x000000c000008a60  0x00007f1b00000000 
0x000000c00daf8a48:  0x0000000000000010  0x00000000014788e0 
0x000000c00daf8a58:  0x0000000000000001  0x0000000000000000 
0x000000c00daf8a68:  0x00007f1b343598d1 <regexp.(*bitState).reset+0x0000000000000211>  0x000000000000000a 
0x000000c00daf8a78:  0x0000000000000000  0x000000c000325720 
0x000000c00daf8a88:  0x000000c000325720  0x000000c000325720 
0x000000c00daf8a98:  0x00007f1b3435ac0d <regexp.(*Regexp).backtrack+0x000000000000032d>  0x000000c0003257c0 
0x000000c00daf8aa8: !0x000000c00139eb00 >0x00000000018a95a0 
0x000000c00daf8ab8:  0x000000c00139eb80  0x000000c00daf8b70 
0x000000c00daf8ac8:  0x000000c010052540  0x0000000000000000 
0x000000c00daf8ad8:  0x000000000000002f  0x00000000018a95a0 
0x000000c00daf8ae8:  0x000000c00daf8bd8  0x0000000000000000 
0x000000c00daf8af8:  0x000000c00139eb80  0x000000c00139eb00 
0x000000c00daf8b08:  0x0000006e0daf8b40  0x000000c00daf8bc0 
0x000000c00daf8b18:  0x00007f1b3435d770 <regexp.(*Regexp).doExecute+0x0000000000000290>  0x00000000023a4200 
0x000000c00daf8b28:  0x0000000000000000  0x0000000000000000 
0x000000c00daf8b38:  0x000000c0003257c0  0x0000000000000000 
0x000000c00daf8b48:  0x0000000000000000  0x0000000000000000 
0x000000c00daf8b58:  0x000000c00117e390  0x000000000000002f 
0x000000c00daf8b68:  0x0000000000000000  0x000000c00daf8bc0 
0x000000c00daf8b78:  0x00007f1b34277657 <runtime.rawstring+0x0000000000000037>  0x000000c00daf8bb8 
0x000000c00daf8b88:  0x0000000000000000  0x0000000000000000 
0x000000c00daf8b98:  0x0000000000000000  0x000000000000002f 
0x000000c00daf8ba8:  0x000000c00117e390 
regexp.(*Regexp).tryBacktrack(0x18a95a0, 0xc00139eb80, {0xc00daf8b70?, 0xc010052540}, 0x0?, 0x2f?)
	/usr/lib/go-1.19rc2/src/regexp/backtrack.go:172 +0xcc5 fp=0xc00daf8ab0 sp=0xc00daf89f8 pc=0xa86cc5
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
	/home/dims/go/pkg/mod/github.com/golangci/golangci-lint@v1.46.2/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x1eb
```

**Comment by dims** [comment]
So reverting the patch https://github.com/golang/go/commit/0293c51bc5d8ca0728913c4b7f9f92339f8fd9a6 and rebuilding go environment like so ... fixes the problem

```
$ GOROOT_BOOTSTRAP=/usr/lib/go-1.18.2/ make.bash
Building Go cmd/dist using /usr/lib/go-1.18.2/. (go1.18.2 linux/amd64)
Building Go toolchain1 using /usr/lib/go-1.18.2/.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for linux/amd64.
---
Installed Go for linux/amd64 in /usr/lib/go-1.19rc2
Installed commands in /usr/lib/go-1.19rc2/bin
```

**Comment by dims** [comment]
cc @bboreham

**Comment by liggitt** [comment]
filed https://github.com/golang/go/issues/53989 with a minimal reproducer

**Comment by dims** [comment]
Looks like good progress in https://go-review.googlesource.com/c/go/+/418960/

**Comment by markyjackson-taulia** [comment]
Hello @dims, my name is Marky Jackson and I am one of the k8s 1.25 bug triage shadow assigned to track this body of work. Is this still on track for 1.25?

**Comment by dims** [comment]
@markyjackson-taulia yes it is. The fix is in golang as mentioned above. Once golang 1.19 GA is out, we will re-enable the logcheck plugin.

**Comment by markyjackson-taulia** [comment]
Thank you kindly @dims

**Comment by pacoxu** [comment]
https://github.com/golang/go/releases/tag/go1.19 is out.

**Comment by dims** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/111678
