### ISSUE TITLE
kube-controller-manager crashes when AWS EBS pvc is unable to resize

### ISSUE THREAD

**Issue by camaeel** [kubernetes/kubernetes#111891]
### What happened?

I migrated an existing EBS volume from in-tree plugin to external aws-ebs-csi-driver (https://github.com/kubernetes-sigs/aws-ebs-csi-driver). Resizing PVC twice in 6 hour window causes kube-controller-manager to crash. 

Exception message:
```
kube-controller-manager I0817 13:46:32.803739       9 event.go:291] "Event occurred" object="ebs-test/ebs-test6" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="ExternalExpanding" message="CSI migration enabled for kubernetes.io/aws-ebs; waiting for external resizer to expand the pvc"
kube-controller-manager E0817 13:46:32.815827       9 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
kube-controller-manager goroutine 2240 [running]:
kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x41de5a0, 0x74dfd60)
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
kube-controller-manager panic(0x41de5a0, 0x74dfd60)
kube-controller-manager 	/usr/local/go/src/runtime/panic.go:965 +0x1b9
kube-controller-manager k8s.io/kubernetes/pkg/volume/util.ClaimToClaimKey(...)
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/util/resize_util.go:57
kube-controller-manager k8s.io/kubernetes/pkg/controller/volume/expand.(*expandController).syncHandler(0xc001616360, 0xc002e62be8, 0x12, 0x0, 0x0)
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/expand/expand_controller.go:273 +0xf79
kube-controller-manager k8s.io/kubernetes/pkg/controller/volume/expand.(*expandController).processNextWorkItem(0xc001616360, 0x203000)
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/expand/expand_controller.go:198 +0xf5
kube-controller-manager k8s.io/kubernetes/pkg/controller/volume/expand.(*expandController).runWorker(...)
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/expand/expand_controller.go:342
kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0012df380)
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0012df380, 0x5182c40, 0xc00127ccf0, 0xc0016e4e01, 0xc0005c2ae0)
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0012df380, 0x3b9aca00, 0x0, 0x100000000000001, 0xc0005c2ae0)
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0012df380, 0x3b9aca00, 0xc0005c2ae0)
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
kube-controller-manager created by k8s.io/kubernetes/pkg/controller/volume/expand.(*expandController).Run
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/expand/expand_controller.go:335 +0x227
kube-controller-manager panic: runtime error: invalid memory address or nil pointer dereference [recovered]
kube-controller-manager 	panic: runtime error: invalid memory address or nil pointer dereference
kube-controller-manager [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x2cfac19]
kube-controller-manager
kube-controller-manager goroutine 2240 [running]:
kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x109
kube-controller-manager panic(0x41de5a0, 0x74dfd60)
kube-controller-manager 	/usr/local/go/src/runtime/panic.go:965 +0x1b9
kube-controller-manager k8s.io/kubernetes/pkg/volume/util.ClaimToClaimKey(...)
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/util/resize_util.go:57
kube-controller-manager k8s.io/kubernetes/pkg/controller/volume/expand.(*expandController).syncHandler(0xc001616360, 0xc002e62be8, 0x12, 0x0, 0x0)
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/expand/expand_controller.go:273 +0xf79
kube-controller-manager k8s.io/kubernetes/pkg/controller/volume/expand.(*expandController).processNextWorkItem(0xc001616360, 0x203000)
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/expand/expand_controller.go:198 +0xf5
kube-controller-manager k8s.io/kubernetes/pkg/controller/volume/expand.(*expandController).runWorker(...)
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/expand/expand_controller.go:342
kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0012df380)
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0012df380, 0x5182c40, 0xc00127ccf0, 0xc0016e4e01, 0xc0005c2ae0)
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0012df380, 0x3b9aca00, 0x0, 0x100000000000001, 0xc0005c2ae0)
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0012df380, 0x3b9aca00, 0xc0005c2ae0)
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
kube-controller-manager created by k8s.io/kubernetes/pkg/controller/volume/expand.(*expandController).Run
kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/expand/expand_controller.go:335 +0x227
```

### What did you expect to happen?

Kube-controller-manager shouldn't crash in such case. If external aws-ebs-csi-driver fails to provision the pvc it should just log an warning or error and continue operating as usual

### How can we reproduce it (as minimally and precisely as possible)?

1. Have running cluster version 1.22.9 using in-tree aws ebs driver. 
2. Create pvc:
    ```
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ebs-test6
      namespace: ebs-test
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: aws-ebs-ephemeral
      resources:
        requests:
          storage: 1Gi
    ```
4.  Install aws-ebs-csi-driver following https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md
5. Enable featureGate CSIMigrationAWS on all cluster components (with draining nodes before enabling featureGate on kubelets - according to warning https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md#migrating-from-in-tree-ebs-plugin)
6. Now we have ebs volume that has been migrated to aws-ebs-csi-driver. 
7. Resize pvc by increasing .spec.resources.request.storage to 2Gi. PVC, PV and EBS volume are correctly resized.
8. Resize once again not later than 6 hours after first resize. Increase .spec.resources.request.storage to 3Gi. Now kube-controller-manager throws an exception and crashes:
    ```
    kube-controller-manager I0817 13:46:32.803739       9 event.go:291] "Event occurred" object="ebs-test/ebs-test6" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="ExternalExpanding" message="CSI migration enabled for kubernetes.io/aws-ebs; waiting for external resizer to expand the pvc"
    kube-controller-manager E0817 13:46:32.815827       9 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
    kube-controller-manager goroutine 2240 [running]:
    kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x41de5a0, 0x74dfd60)
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
    kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
    kube-controller-manager panic(0x41de5a0, 0x74dfd60)
    kube-controller-manager 	/usr/local/go/src/runtime/panic.go:965 +0x1b9
    kube-controller-manager k8s.io/kubernetes/pkg/volume/util.ClaimToClaimKey(...)
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/util/resize_util.go:57
    kube-controller-manager k8s.io/kubernetes/pkg/controller/volume/expand.(*expandController).syncHandler(0xc001616360, 0xc002e62be8, 0x12, 0x0, 0x0)
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/expand/expand_controller.go:273 +0xf79
    kube-controller-manager k8s.io/kubernetes/pkg/controller/volume/expand.(*expandController).processNextWorkItem(0xc001616360, 0x203000)
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/expand/expand_controller.go:198 +0xf5
    kube-controller-manager k8s.io/kubernetes/pkg/controller/volume/expand.(*expandController).runWorker(...)
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/expand/expand_controller.go:342
    kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0012df380)
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
    kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0012df380, 0x5182c40, 0xc00127ccf0, 0xc0016e4e01, 0xc0005c2ae0)
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
    kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0012df380, 0x3b9aca00, 0x0, 0x100000000000001, 0xc0005c2ae0)
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
    kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0012df380, 0x3b9aca00, 0xc0005c2ae0)
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
    kube-controller-manager created by k8s.io/kubernetes/pkg/controller/volume/expand.(*expandController).Run
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/expand/expand_controller.go:335 +0x227
    kube-controller-manager panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    kube-controller-manager 	panic: runtime error: invalid memory address or nil pointer dereference
    kube-controller-manager [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x2cfac19]
    kube-controller-manager
    kube-controller-manager goroutine 2240 [running]:
    kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x109
    kube-controller-manager panic(0x41de5a0, 0x74dfd60)
    kube-controller-manager 	/usr/local/go/src/runtime/panic.go:965 +0x1b9
    kube-controller-manager k8s.io/kubernetes/pkg/volume/util.ClaimToClaimKey(...)
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/util/resize_util.go:57
    kube-controller-manager k8s.io/kubernetes/pkg/controller/volume/expand.(*expandController).syncHandler(0xc001616360, 0xc002e62be8, 0x12, 0x0, 0x0)
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/expand/expand_controller.go:273 +0xf79
    kube-controller-manager k8s.io/kubernetes/pkg/controller/volume/expand.(*expandController).processNextWorkItem(0xc001616360, 0x203000)
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/expand/expand_controller.go:198 +0xf5
    kube-controller-manager k8s.io/kubernetes/pkg/controller/volume/expand.(*expandController).runWorker(...)
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/expand/expand_controller.go:342
    kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0012df380)
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
    kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0012df380, 0x5182c40, 0xc00127ccf0, 0xc0016e4e01, 0xc0005c2ae0)
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
    kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0012df380, 0x3b9aca00, 0x0, 0x100000000000001, 0xc0005c2ae0)
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
    kube-controller-manager k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc0012df380, 0x3b9aca00, 0xc0005c2ae0)
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
    kube-controller-manager created by k8s.io/kubernetes/pkg/controller/volume/expand.(*expandController).Run
    kube-controller-manager 	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/volume/expand/expand_controller.go:335 +0x227
    ```
    EBS CSI Driver logs:
    ```
    ebs-csi-controller-6ccb584954-hhqxc csi-resizer I0817 14:00:32.597887       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"ebs-test", Name:"ebs-test6", UID:"3d0a720f-f3ba-4586-9ff3-90f25670f2f9", APIVersion:"v1", ResourceVersion:"63083", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-3d0a720f-f3ba-4586-9ff3-90f25670f2f9
    ebs-csi-controller-6ccb584954-hhqxc csi-resizer E0817 14:00:32.876941       1 controller.go:286] Error syncing PVC: resize volume "pvc-3d0a720f-f3ba-4586-9ff3-90f25670f2f9" by resizer "ebs.csi.aws.com" failed: rpc error: code = Internal desc = Could not resize volume "vol-0d47c36d05c03f8f8": could not modify AWS volume "vol-0d47c36d05c03f8f8": VolumeModificationRateExceeded: You've reached the maximum modification rate per volume limit. Wait at least 6 hours between modifications per EBS volume.
    ebs-csi-controller-6ccb584954-hhqxc csi-resizer 	status code: 400, request id: ba9efb31-0500-4119-bbdc-d16f25764025
    ebs-csi-controller-6ccb584954-hhqxc csi-resizer I0817 14:00:32.877031       1 event.go:285] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"ebs-test", Name:"ebs-test6", UID:"3d0a720f-f3ba-4586-9ff3-90f25670f2f9", APIVersion:"v1", ResourceVersion:"63083", FieldPath:""}): type: 'Warning' reason: 'VolumeResizeFailed' resize volume "pvc-3d0a720f-f3ba-4586-9ff3-90f25670f2f9" by resizer "ebs.csi.aws.com" failed: rpc error: code = Internal desc = Could not resize volume "vol-0d47c36d05c03f8f8": could not modify AWS volume "vol-0d47c36d05c03f8f8": VolumeModificationRateExceeded: You've reached the maximum modification rate per volume limit. Wait at least 6 hours between modifications per EBS volume.
    ebs-csi-controller-6ccb584954-hhqxc csi-resizer 	status code: 400, request id: ba9efb31-0500-4119-bbdc-d16f25764025
    ebs-csi-controller-6ccb584954-hhqxc ebs-plugin E0817 14:00:32.876672       1 driver.go:120] GRPC error: rpc error: code = Internal desc = Could not resize volume "vol-0d47c36d05c03f8f8": could not modify AWS volume "vol-0d47c36d05c03f8f8": VolumeModificationRateExceeded: You've reached the maximum modification rate per volume limit. Wait at least 6 hours between modifications per EBS volume.
    ebs-csi-controller-6ccb584954-hhqxc ebs-plugin 	status code: 400, request id: ba9efb31-0500-4119-bbdc-d16f25764025
    ```

### Anything else we need to know?

I tried also enabling alpha featureGate InTreePluginAWSUnregister but the issue still occurs. 

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-13T19:57:43Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-13T19:52:02Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
docker
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
aws-ebs-csi-driver version 1.10.0
</details>

**Comment by aojea** [comment]
/sig storage

some situation where the sync loop passes a nil `pvc` parameter to https://github.com/kubernetes/kubernetes/blob/d32be903b0b7606627ba8ea8dfbe37865b26dd5e/pkg/volume/util/resize_util.go#L57-L60

**Comment by wongma7** [comment]
https://github.com/kubernetes/kubernetes/blob/v1.26.0-alpha.0/pkg/controller/volume/expand/expand_controller.go#L272-L274

SetClaimResizer may return nil pvc and non-nil error, ClaimToClaimKey naively assumes non-nil as described above, will create PR

**Comment by gnufied** [comment]
But the posted bug is I think 1.22 specific and should never happen on master or 1.24 and hence this fix against master is kind of okay and should fix the issue but at the same time code in `PatchPVCStatus` is still kinda broken in 1.22 because it returns `nil` if patching fails.
