### ISSUE TITLE
DNS lookup issue Kubernetes API: io.kubernetes.client.openapi.ApiException: java.net.ConnectException: Failed to connect to /10.96.0.1:443

### ISSUE THREAD

**Issue by Sandeepisebauz** [kubernetes/kubernetes#112462]
### What happened?

We have been noticing the below issue where the application pod deployed on the Kubernetes cluster, fails to make a connection to external DB.
Kubernetes API: io.kubernetes.client.openapi.ApiException: java.net.ConnectException: Failed to connect to /10.96.0.1:443
io.kubernetes.client.openapi.ApiException: java.net.ConnectException: Failed to connect to /10.96.0.1:443
        at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:888)
        at io.kubernetes.client.openapi.apis.CoreV1Api.listNamespacedPodWithHttpInfo(CoreV1Api.java:30883)
        at io.kubernetes.client.openapi.apis.CoreV1Api.listNamespacedPod(CoreV1Api.java:30772)
        at com.distra.pm.mcas.platform.discovery.KubeDiscoverer.doGetAddresses(KubeDiscoverer.java:101)
        at com.distra.pm.mcas.platform.discovery.KubeDiscoverer.getAddresses(KubeDiscoverer.java:91)
        at com.distra.pm.mcas.platform.discovery.ProcessDiscoveryImpl$2.run(ProcessDiscoveryImpl.java:113)
Caused by: java.net.ConnectException: Failed to connect to /10.96.0.1:443
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at io.kubernetes.client.util.credentials.TokenFileAuthentication.intercept(TokenFileAuthentication.java:72)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:884)
        ... 5 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
        ... 23 more

### What did you expect to happen?

PODs to be running without any issue

### How can we reproduce it (as minimally and precisely as possible)?

Not sure

### Kubernetes version

<details>

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:52:18Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Cloud provider

<details>
On Prem 
</details>
On-Prem

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
Red Hat Enterprise Linux Server release 7.9 (Maipo)

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
k8s_cni_version=0.8.7-0
</details>

**Comment by pacoxu** [comment]
/kind support
If you can connect to 10.96.0.1:443 from the pod, it would be something wrong with the client code.
(If not, check kube-proxy on the node following https://kubernetes.io/docs/tasks/debug/debug-application/debug-service/.)
