### ISSUE TITLE
k8s v1.23.6 installed in binary kubelet "Unable to authenticate the request due to an error" err="[invalid bearer token, square/go-jose: error in cryptographic primitive]"

### ISSUE THREAD

**Issue by dwzkit** [kubernetes/kubernetes#112942]
### What happened?

1、A new work k8s-node03 is added
<img width="303" alt="image" src="https://user-images.githubusercontent.com/41875799/194770650-404c1f82-43e1-4226-827c-d26fc7b02b50.png">
2、Everything seems to be working well
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/41875799/194770696-5a921fe8-3b5e-4c6c-ba67-c1cb1c22460e.png">
3、The pod created on k8s-node03 can ping between other node's pod
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/41875799/194770889-6aa57803-0d06-4df6-8758-9d1a25286b50.png">

4、Bug when run ```journalctl -xefu kubelet``` in k8s-node03,A large number of errors are generated：`Unable to authenticate the request due to an error" err="[invalid bearer token, square/go-jose: error in cryptographic primitive]`
<img width="774" alt="image" src="https://user-images.githubusercontent.com/41875799/194770554-9f550d6e-025e-4776-83d1-a519925b37fd.png">

### What did you expect to happen?

Executing journalctl -xefu kubelet on k8s-node03 should not result in any errors

### How can we reproduce it (as minimally and precisely as possible)?

k8s v1.23.6 installed in binary,add a new work node

### Anything else we need to know?
```
Oct 10 10:11:38 k8s-node03 kubelet[286587]: I1010 10:11:38.655417  286587 round_trippers.go:466] curl -v -XPOST  -H "Content-Type: application/vnd.kubernetes.protobuf" -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "User-Agent: kubelet/v1.23.6 (linux/amd64) kubernetes/ad33385" 'https://172.17.59.249:8443/apis/authentication.k8s.io/v1/tokenreviews'
Oct 10 10:11:38 k8s-node03 kubelet[286587]: I1010 10:11:38.662069  286587 round_trippers.go:570] HTTP Statistics: GetConnection 0 ms ServerProcessing 6 ms Duration 6 ms
Oct 10 10:11:38 k8s-node03 kubelet[286587]: I1010 10:11:38.662104  286587 round_trippers.go:577] Response Headers:
Oct 10 10:11:38 k8s-node03 kubelet[286587]: I1010 10:11:38.662115  286587 round_trippers.go:580]     X-Kubernetes-Pf-Flowschema-Uid: be78849e-d5cc-41aa-84d9-2bef4a4e8e0e
Oct 10 10:11:38 k8s-node03 kubelet[286587]: I1010 10:11:38.662121  286587 round_trippers.go:580]     X-Kubernetes-Pf-Prioritylevel-Uid: a30424f7-8793-4a3e-9fc4-60d14e188075
Oct 10 10:11:38 k8s-node03 kubelet[286587]: I1010 10:11:38.662141  286587 round_trippers.go:580]     Content-Length: 1197
Oct 10 10:11:38 k8s-node03 kubelet[286587]: I1010 10:11:38.662149  286587 round_trippers.go:580]     Date: Mon, 10 Oct 2022 02:11:38 GMT
Oct 10 10:11:38 k8s-node03 kubelet[286587]: I1010 10:11:38.662158  286587 round_trippers.go:580]     Audit-Id: 49d20e61-dc93-41bc-9d59-7830d07edad4
Oct 10 10:11:38 k8s-node03 kubelet[286587]: I1010 10:11:38.662164  286587 round_trippers.go:580]     Cache-Control: no-cache, private
Oct 10 10:11:38 k8s-node03 kubelet[286587]: I1010 10:11:38.662171  286587 round_trippers.go:580]     Content-Type: application/vnd.kubernetes.protobuf
Oct 10 10:11:38 k8s-node03 kubelet[286587]: I1010 10:11:38.662289  286587 request.go:1179] Response Body:
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000000  6b 38 73 00 0a 27 0a 18  61 75 74 68 65 6e 74 69  |k8s..'..authenti|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000010  63 61 74 69 6f 6e 2e 6b  38 73 2e 69 6f 2f 76 31  |cation.k8s.io/v1|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000020  12 0b 54 6f 6b 65 6e 52  65 76 69 65 77 12 f9 08  |..TokenReview...|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000030  0a 73 0a 00 12 00 1a 00  22 00 2a 00 32 00 38 00  |.s......".*.2.8.|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000040  42 00 7a 00 8a 01 5e 0a  07 6b 75 62 65 6c 65 74  |B.z...^..kubelet|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000050  12 06 55 70 64 61 74 65  1a 18 61 75 74 68 65 6e  |..Update..authen|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000060  74 69 63 61 74 69 6f 6e  2e 6b 38 73 2e 69 6f 2f  |tication.k8s.io/|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000070  76 31 22 08 08 da fe 8d  9a 06 10 00 32 08 46 69  |v1".........2.Fi|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000080  65 6c 64 73 56 31 3a 1b  0a 19 7b 22 66 3a 73 70  |eldsV1:...{"f:sp|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000090  65 63 22 3a 7b 22 66 3a  74 6f 6b 65 6e 22 3a 7b  |ec":{"f:token":{|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000000a0  7d 7d 7d 42 00 12 ad 07  0a aa 07 65 79 4a 68 62  |}}}B.......eyJhb|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000000b0  47 63 69 4f 69 4a 53 55  7a 49 31 4e 69 49 73 49  |GciOiJSUzI1NiIsI|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000000c0  6d 74 70 5a 43 49 36 49  6e 64 31 54 46 56 66 64  |mtpZCI6Ind1TFVfd|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000000d0  32 31 36 5a 6d 6c 73 5a  56 68 4e 54 31 56 5a 64  |216ZmlsZVhNT1VZd|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000000e0  47 70 74 56 45 64 34 64  57 64 68 62 6c 6c 76 65  |GptVEd4dWdhbllve|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000000f0  45 70 56 54 6d 74 70 56  45 56 52 4c 56 42 48 4c  |EpVTmtpVEVRLVBHL|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000100  57 73 69 66 51 2e 65 79  4a 70 63 33 4d 69 4f 69  |WsifQ.eyJpc3MiOi|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000110  4a 72 64 57 4a 6c 63 6d  35 6c 64 47 56 7a 4c 33  |JrdWJlcm5ldGVzL3|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000120  4e 6c 63 6e 5a 70 59 32  56 68 59 32 4e 76 64 57  |NlcnZpY2VhY2NvdW|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000130  35 30 49 69 77 69 61 33  56 69 5a 58 4a 75 5a 58  |50Iiwia3ViZXJuZX|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000140  52 6c 63 79 35 70 62 79  39 7a 5a 58 4a 32 61 57  |Rlcy5pby9zZXJ2aW|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000150  4e 6c 59 57 4e 6a 62 33  56 75 64 43 39 75 59 57  |NlYWNjb3VudC9uYW|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000160  31 6c 63 33 42 68 59 32  55 69 4f 69 4a 72 64 57  |1lc3BhY2UiOiJrdW|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000170  4a 6c 4c 58 4e 35 63 33  52 6c 62 53 49 73 49 6d  |JlLXN5c3RlbSIsIm|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000180  74 31 59 6d 56 79 62 6d  56 30 5a 58 4d 75 61 57  |t1YmVybmV0ZXMuaW|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000190  38 76 63 32 56 79 64 6d  6c 6a 5a 57 46 6a 59 32  |8vc2VydmljZWFjY2|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000001a0  39 31 62 6e 51 76 63 32  56 6a 63 6d 56 30 4c 6d  |91bnQvc2VjcmV0Lm|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000001b0  35 68 62 57 55 69 4f 69  4a 74 5a 58 52 79 61 57  |5hbWUiOiJtZXRyaW|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000001c0  4e 7a 4c 58 4e 6c 63 6e  5a 6c 63 69 31 30 62 32  |NzLXNlcnZlci10b2|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000001d0  74 6c 62 69 31 33 4e 33  68 72 4e 53 49 73 49 6d  |tlbi13N3hrNSIsIm|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000001e0  74 31 59 6d 56 79 62 6d  56 30 5a 58 4d 75 61 57  |t1YmVybmV0ZXMuaW|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000001f0  38 76 63 32 56 79 64 6d  6c 6a 5a 57 46 6a 59 32  |8vc2VydmljZWFjY2|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000200  39 31 62 6e 51 76 63 32  56 79 64 6d 6c 6a 5a 53  |91bnQvc2VydmljZS|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000210  31 68 59 32 4e 76 64 57  35 30 4c 6d 35 68 62 57  |1hY2NvdW50Lm5hbW|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000220  55 69 4f 69 4a 74 5a 58  52 79 61 57 4e 7a 4c 58  |UiOiJtZXRyaWNzLX|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000230  4e 6c 63 6e 5a 6c 63 69  49 73 49 6d 74 31 59 6d  |NlcnZlciIsImt1Ym|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000240  56 79 62 6d 56 30 5a 58  4d 75 61 57 38 76 63 32  |VybmV0ZXMuaW8vc2|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000250  56 79 64 6d 6c 6a 5a 57  46 6a 59 32 39 31 62 6e  |VydmljZWFjY291bn|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000260  51 76 63 32 56 79 64 6d  6c 6a 5a 53 31 68 59 32  |Qvc2VydmljZS1hY2|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000270  4e 76 64 57 35 30 4c 6e  56 70 5a 43 49 36 49 6a  |NvdW50LnVpZCI6Ij|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000280  4d 78 4e 7a 42 6c 59 54  41 31 4c 54 6b 32 59 7a  |MxNzBlYTA1LTk2Yz|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000290  59 74 4e 44 56 6c 4f 43  30 35 59 57 55 33 4c 54  |YtNDVlOC05YWU3LT|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000002a0  46 6b 59 7a 46 68 5a 6a  4d 35 5a 54 45 32 4e 53  |FkYzFhZjM5ZTE2NS|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000002b0  49 73 49 6e 4e 31 59 69  49 36 49 6e 4e 35 63 33  |IsInN1YiI6InN5c3|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000002c0  52 6c 62 54 70 7a 5a 58  4a 32 61 57 4e 6c 59 57  |RlbTpzZXJ2aWNlYW|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000002d0  4e 6a 62 33 56 75 64 44  70 72 64 57 4a 6c 4c 58  |Njb3VudDprdWJlLX|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000002e0  4e 35 63 33 52 6c 62 54  70 74 5a 58 52 79 61 57  |N5c3RlbTptZXRyaW|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000002f0  4e 7a 4c 58 4e 6c 63 6e  5a 6c 63 69 4a 39 2e 50  |NzLXNlcnZlciJ9.P|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000300  43 4e 77 74 4d 33 6f 33  38 38 4f 42 34 4d 59 72  |CNwtM3o388OB4MYr|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000310  31 36 4a 72 37 42 35 68  4a 46 39 49 43 6e 41 6f  |16Jr7B5hJF9ICnAo|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000320  41 46 71 35 43 4e 2d 4b  4e 71 7a 73 38 73 38 38  |AFq5CN-KNqzs8s88|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000330  64 34 46 34 61 48 68 36  6e 77 64 38 4b 6e 58 35  |d4F4aHh6nwd8KnX5|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000340  7a 4b 37 53 43 55 51 66  63 44 74 74 50 77 50 55  |zK7SCUQfcDttPwPU|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000350  76 5a 33 65 36 62 42 2d  59 78 4d 50 6c 6a 4f 36  |vZ3e6bB-YxMPljO6|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000360  30 5a 76 70 44 33 39 77  38 43 6e 62 6a 68 35 67  |0ZvpD39w8Cnbjh5g|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000370  6f 30 72 62 39 72 50 5a  52 5f 45 71 6f 79 50 47  |o0rb9rPZR_EqoyPG|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000380  2d 32 63 52 7a 67 55 54  33 63 5f 47 69 73 5f 32  |-2cRzgUT3c_Gis_2|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000390  36 69 47 65 69 32 34 47  6c 5f 4b 68 69 75 4b 51  |6iGei24Gl_KhiuKQ|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000003a0  30 4f 71 64 58 78 69 43  5a 69 6b 31 63 63 48 6e  |0OqdXxiCZik1ccHn|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000003b0  41 38 41 6e 57 46 65 54  5f 5a 5f 57 76 55 64 4f  |A8AnWFeT_Z_WvUdO|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000003c0  71 71 44 67 78 6f 71 67  4c 65 6e 44 74 55 75 4f  |qqDgxoqgLenDtUuO|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000003d0  39 65 78 31 70 4b 65 31  6e 5f 79 6c 34 68 33 38  |9ex1pKe1n_yl4h38|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000003e0  78 66 4b 44 41 4f 65 74  73 4c 78 37 69 56 4a 68  |xfKDAOetsLx7iVJh|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000003f0  39 35 4d 43 72 66 70 70  33 38 37 59 71 63 48 5f  |95MCrfpp387YqcH_|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000400  48 46 4a 6e 78 31 76 7a  78 73 66 67 41 6f 34 70  |HFJnx1vzxsfgAo4p|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000410  6c 5f 6e 4b 34 77 6d 74  2d 34 49 68 45 77 5a 33  |l_nK4wmt-4IhEwZ3|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000420  4e 4e 48 58 75 35 58 6f  59 47 36 39 71 33 43 66  |NNHXu5XoYG69q3Cf|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000430  76 58 53 41 53 45 6c 5a  66 61 2d 55 4b 75 45 64  |vXSASElZfa-UKuEd|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000440  5f 76 46 4d 41 62 66 4c  76 42 73 46 38 59 64 37  |_vFMAbfLvBsF8Yd7|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000450  6c 46 45 43 67 1a 52 08  00 12 04 0a 00 12 00 1a  |lFECg.R.........|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000460  48 5b 69 6e 76 61 6c 69  64 20 62 65 61 72 65 72  |H[invalid bearer|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000470  20 74 6f 6b 65 6e 2c 20  73 71 75 61 72 65 2f 67  | token, square/g|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000480  6f 2d 6a 6f 73 65 3a 20  65 72 72 6f 72 20 69 6e  |o-jose: error in|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 00000490  20 63 72 79 70 74 6f 67  72 61 70 68 69 63 20 70  | cryptographic p|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: 000004a0  72 69 6d 69 74 69 76 65  5d 1a 00 22 00           |rimitive]..".|
Oct 10 10:11:38 k8s-node03 kubelet[286587]: E1010 10:11:38.662423  286587 server.go:274] "Unable to authenticate the request due to an error" err="[invalid bearer token, square/go-jose: error in cryptographic primitive]"
```
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/41875799/194792761-24e84bcf-4836-4f71-a479-db98c4650201.png">
<img width="581" alt="image" src="https://user-images.githubusercontent.com/41875799/194792767-646aa616-be83-4c7c-a5a6-503d614eb264.png">
<img width="595" alt="image" src="https://user-images.githubusercontent.com/41875799/194792771-97950608-1496-4526-ae3b-177125772767.png">
<img width="599" alt="image" src="https://user-images.githubusercontent.com/41875799/194792792-ce67dc1d-37f4-4917-947b-d103b7e69e76.png">

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
[root@k8s-master02 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
alicloud
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
[root@k8s-node03 bin]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
$ uname -a
uname -a
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

containerD

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<img width="508" alt="image" src="https://user-images.githubusercontent.com/41875799/194771165-1ba14f4a-e490-475d-984e-9db7e6ac8188.png">

**Comment by pacoxu** [comment]
/sig node auth
for triage

**Comment by dwzkit** [comment]
```
Oct 10 10:58:08 k8s-node03 kubelet[314765]: I1010 10:58:08.701900  314765 httplog.go:129] "HTTP" verb="GET" URI="/stats/summary?only_cpu_and_memory=true" latency="22.091886ms" userAgent="Go-http-client/2.0" audit-ID="" srcIP="172.17.125.215:30131" resp=401 statusStack="\ngoroutine 1047 [running]:\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc000cbc0b0, 0x500a2d)\n\t/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:314 +0x8f\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc000cbc0b0, 0x49e6f01)\n\t/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:296 +0x25\nk8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteHeader(...)\n\t/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/response.go:220\nk8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteErrorString(0xc0001c3d50, 0x191, {0x4912524, 0x40})\n\t/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/response.go:200 +0xae\nk8s.io/kubernetes/pkg/kubelet/server.(*Server).InstallAuthFilter.func1(0xc0004e21b0, 0x439a3c0, 0x1)\n\t/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:275 +0xa5c\nk8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0x3f8fd40, 0xc000cb0910, 0xc0015517e0)\n\t/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/filter.go:19 +0x47\nk8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc0005b0000, {0x508bc38, 0xc0015517e0}, 0xc00123ed00)\n\t/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:285 +0x9c6\nnet/http.HandlerFunc.ServeHTTP(0xc0015517e0, {0x508bc38, 0xc0015517e0}, 0xc00105fa88)\n\t/usr/local/go/src/net/http/server.go:2047 +0x2f\nnet/http.(*ServeMux).ServeHTTP(0x7f5ed45e5f40, {0x508bc38, 0xc0015517e0}, 0xc00123ed00)\n\t/usr/local/go/src/net/http/server.go:2425 +0x149\nk8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0x508fdf8, {0x508bc38, 0xc0015517e0}, 0xc00044d648)\n\t/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:303 +0x27\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.withLogging.func1({0x508a828, 0xc00044d648}, 0xc0000d4600)\n\t/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:128 +0x44d\nnet/http.HandlerFunc.ServeHTTP(0xc000224e00, {0x508a828, 0xc00044d648}, 0x4)\n\t/usr/local/go/src/net/http/server.go:2047 +0x2f\nk8s.io/kubernetes/pkg/kubelet/server.(*Server).ServeHTTP(0xc000634000, {0x508a828, 0xc00044d648}, 0xc0000d4600)\n\t/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:944 +0x657\nnet/http.serverHandler.ServeHTTP({0xc000052030}, {0x508a828, 0xc00044d648}, 0xc0000d4600)\n\t/usr/local/go/src/net/http/server.go:2879 +0x43b\nnet/http.initALPNRequest.ServeHTTP({{0x508dcb8, 0xc00062cf30}, 0xc000bda380, {0xc000fd2a80}}, {0x508a828, 0xc00044d648}, 0xc0000d4600)\n\t/usr/local/go/src/net/http/server.go:3480 +0x245\nnet/http.(*http2serverConn).runHandler(0x50757f8, 0xc0012f37d0, 0x7f9a66, 0xc001500f00)\n\t/usr/local/go/src/net/http/h2_bundle.go:5849 +0x78\ncreated by net/http.(*http2serverConn).processHeaders\n\t/usr/local/go/src/net/http/h2_bundle.go:5579 +0x510\n" addedInfo="\nlogging error output: \"Unauthorized\"\n"
```
srcIP="172.17.125.215:30131 " was from old K8S master.
I didn't do kubectl delete node03 to delete the node from old K8S,I just format node03. It happened that the master of the old K8S and the master of the new K8S were in the same network(Local Area Network), so the new node(k8s-node03) received the message from the old K8S master.I delete node from old K8S, then errors disappear.Not BUG. The problem has been solved.
 
(原来是新添加的node节点是以前旧K8S那边的node节点，而旧K8S当时我没有做kubectl delete node把节点删除，刚好旧K8S的master跟新K8S的master都在同一个局域网,导致新节点收到旧K8S master的消息，就一直报那个错误了。不是BUG。问题已解决。）
