### ISSUE TITLE
APIServer Tracing crashes with nil pointer exception when egress selector is configured

### ISSUE THREAD

**Issue by austinlparker** [kubernetes/kubernetes#112976]
### What happened?

While trying to enable API Server Tracing while using k3s, the API Server component crashes. The only way to avoid this crash is to disable egress selectors in k3s entirely. I originally opened an issue in the k3s repo (see https://github.com/k3s-io/k3s/issues/6254), and we determined that the issue seems to be an assumption that a dialer will always be returned if there's no error, but in this case there's no grpc egress configured so `Lookup` is returning `nil, nil` and causing a panic at https://github.com/kubernetes/kubernetes/blob/v1.25.2/staging/src/k8s.io/apiserver/pkg/server/options/tracing.go#L106

### What did you expect to happen?

API Server Tracing to function properly.

### How can we reproduce it (as minimally and precisely as possible)?

Please see the linked k3s issue for a repro case; However, I believe the minimal setup for this would be to configure cluster egress without defining a grpc egress selector and then attempting to enable API server tracing.

### Anything else we need to know?

panic stack trace --
```
Oct 11 02:44:12 minikube k3s[10429]: 2022/10/11 02:44:12 <nil>
Oct 11 02:44:12 minikube k3s[10429]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 11 02:44:12 minikube k3s[10429]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x26f98a7]
Oct 11 02:44:12 minikube k3s[10429]: goroutine 759 [running]:
Oct 11 02:44:12 minikube k3s[10429]: k8s.io/apiserver/pkg/server/options.(*TracingOptions).ApplyTo.func1({0x57a7f68?, 0xc00110db00?}, {0xc000ff88a0?, 0x810c440?})
Oct 11 02:44:12 minikube k3s[10429]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apiserver@v1.25.2-k3s1/pkg/server/options/tracing.go:106 +0x27
Oct 11 02:44:12 minikube k3s[10429]: google.golang.org/grpc/internal/transport.dial({0x57a7f68, 0xc00110db00}, 0xc000bec060, {{0xc000ff88a0, 0x14}, {0xc000ff88a0, 0x14}, 0x0, 0x0, {0x0, ...}}, ...)
Oct 11 02:44:12 minikube k3s[10429]:         /go/pkg/mod/google.golang.org/grpc@v1.40.0/internal/transport/http2_client.go:157 +0x1d9
Oct 11 02:44:12 minikube k3s[10429]: google.golang.org/grpc/internal/transport.newHTTP2Client({_, _}, {_, _}, {{0xc000ff88a0, 0x14}, {0xc000ff88a0, 0x14}, 0x0, 0x0, ...}, ...)
Oct 11 02:44:12 minikube k3s[10429]:         /go/pkg/mod/google.golang.org/grpc@v1.40.0/internal/transport/http2_client.go:196 +0x166
Oct 11 02:44:12 minikube k3s[10429]: google.golang.org/grpc/internal/transport.NewClientTransport(...)
Oct 11 02:44:12 minikube k3s[10429]:         /go/pkg/mod/google.golang.org/grpc@v1.40.0/internal/transport/transport.go:574
Oct 11 02:44:12 minikube k3s[10429]: google.golang.org/grpc.(*addrConn).createTransport(0xc000b8e580, {{0xc000ff88a0, 0x14}, {0xc000ff88a0, 0x14}, _, _, {_, _}}, {{0x4cdbaa9, ...}, ...}, ...)
Oct 11 02:44:12 minikube k3s[10429]:         /go/pkg/mod/google.golang.org/grpc@v1.40.0/clientconn.go:1328 +0x439
Oct 11 02:44:12 minikube k3s[10429]: google.golang.org/grpc.(*addrConn).tryAllAddrs(0xc000b8e580, {0xc0005e0b80?, 0x1, 0x0?}, {0x0?, 0x0?, 0x80cebe0?})
Oct 11 02:44:12 minikube k3s[10429]:         /go/pkg/mod/google.golang.org/grpc@v1.40.0/clientconn.go:1258 +0x4b9
Oct 11 02:44:12 minikube k3s[10429]: google.golang.org/grpc.(*addrConn).resetTransport(0xc000b8e580)
Oct 11 02:44:12 minikube k3s[10429]:         /go/pkg/mod/google.golang.org/grpc@v1.40.0/clientconn.go:1173 +0x265
Oct 11 02:44:12 minikube k3s[10429]: created by google.golang.org/grpc.(*addrConn).connect
Oct 11 02:44:12 minikube k3s[10429]:         /go/pkg/mod/google.golang.org/grpc@v1.40.0/clientconn.go:849 +0x136
```

contents of egress selector config file in direct mode-

```
{
  "kind": "EgressSelectorConfiguration",
  "apiVersion": "apiserver.k8s.io/v1beta1",
  "EgressSelections": [
    {
      "Name": "cluster",
      "Connection": {
        "ProxyProtocol": "Direct",
        "Transport": null
      }
    }
  ]
}
```

contents of egress selector config in 'agent' mode - 

```
{
	"kind": "EgressSelectorConfiguration",
	"apiVersion": "apiserver.k8s.io/v1beta1",
	"EgressSelections": [{
		"Name": "cluster",
		"Connection": {
			"ProxyProtocol": "HTTPConnect",
			"Transport": {
				"TCP": {
					"URL": "https://127.0.0.1:6443",
					"TLSConfig": {
						"CABundle": "/var/lib/rancher/k3s/server/tls/server-ca.crt",
						"ClientKey": "/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key",
						"ClientCert": "/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt"
					}
				},
				"UDS": null
			}
		}
	}]
}
```

contents of api server tracing config file --

```
apiVersion: apiserver.config.k8s.io/v1alpha1
kind: TracingConfiguration
endpoint: 0.0.0.0:4317
samplingRatePerMillion: 1000000
```

### Kubernetes version

<details>

1.25.2+k3s1

</details>

### Cloud provider

<details>
Digital Ocean Droplet
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dashpole** [comment]
/assign
/triage accepted
Thanks @austinlparker!
