### ISSUE TITLE
controller-manager crash when specifying --allocate-node-cidrs=true without a cloud provider

### ISSUE THREAD

**Issue by bhouse** [kubernetes/kubernetes#11307]
Running the `controller-manager` via the `hyperkube` container, I was getting a stack trace in the logs. Turns out I was calling `--allocate-node-cidrs=true` without a cloud provider. It gave an error message about requiring a cloud provider, but then dumps a full stack trace.

``` shell
root@9bc01ec35f04:/# /hyperkube --version
Kubernetes v0.21.2
root@9bc01ec35f04:/# /hyperkube controller-manager --master=127.0.0.1:8080 --cluster_name=bhouse --cluster-cidr=10.0.224.0/20 --allocate-node-cidrs=true --v=2
I0715 13:53:03.362346      85 plugins.go:69] No cloud provider specified.
I0715 13:53:03.363261      85 nodecontroller.go:114] Sending events to api server.
E0715 13:53:03.363933      85 controllermanager.go:198] Failed to start service controller: ServiceController should not be run without a cloudprovider.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0x498b1e]

goroutine 1 [running]:
github.com/GoogleCloudPlatform/kubernetes/cmd/kube-controller-manager/app.(*CMServer).Run(0xc2081dc640, 0xc20805b630, 0x0, 0x5, 0x0, 0x0)
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:202 +0x89e
main.func·002(0xc20805b5e0, 0xc20805b630, 0x0, 0x5, 0x0, 0x0)
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/hyperkube/kube-controller-manager.go:34 +0x5a
main.(*HyperKube).Run(0xc2080589c0, 0xc208058af0, 0x5, 0x5, 0x0, 0x0)
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/hyperkube/hyperkube.go:172 +0x5d1
main.(*HyperKube).RunToExit(0xc2080589c0, 0xc20800a000, 0x7, 0x7)
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/hyperkube/hyperkube.go:183 +0x6a
main.main()
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/hyperkube/main.go:40 +0x93b

[truncated]
```

**Comment by bhouse** [comment]
maybe related to #11172

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.
