### ISSUE TITLE
kubelet crashes when attempting to bring up a static pod that refers to a configmap

### ISSUE THREAD

**Issue by sdmodi** [kubernetes/kubernetes#113492]
### What happened?

We were attempting to bring up a static pod on the node. This pod was attempting to mount a configmap using a volume:

```
    apiVersion: v1
    kind: Pod
    metadata:
      name: network-controller-manager
      namespace: kube-system
    spec:
      containers:
      - args:
        - --config=controller_manager_config.yaml
        command:
        - /manager
        .....
        volumeMounts:
        - mountPath: /controller_manager_config.yaml
          name: manager-config
          subPath: controller_manager_config.yaml
      hostNetwork: true
      volumes:
      - configMap:
          name: network-controller-manager
        name: manager-config
```
The configmap was as follows:
```
apiVersion: v1
    data:
      controller_manager_config.yaml: |
.....
    kind: ConfigMap
    name: network-controller-manager
    namespace: kube-system
```
We later realized that static pods don't support configMaps. However, when we attempted to run this cluster, kubelet kept crashing with this stack trace. We should probably fix this as the problem here is not obvious.

```
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: E1031 20:00:48.166910 3019 runtime.go:79] Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: goroutine 549 [running]:\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3f89c00?, 0x71f2840})\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x2540be400?})\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: panic({0x3f89c00, 0x71f2840})\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: /usr/local/go/src/runtime/panic.go:884 +0x212\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: k8s.io/client-go/tools/cache.(*Reflector).list(0xc000cbb770, 0xc000f85920)\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: vendor/k8s.io/client-go/tools/cache/reflector.go:419 +0xb32\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc000cbb770, 0xc000f85920)\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: vendor/k8s.io/client-go/tools/cache/reflector.go:259 +0x152\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: k8s.io/client-go/tools/cache.(*Reflector).Run.func1()\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: vendor/k8s.io/client-go/tools/cache/reflector.go:223 +0x26\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0011af000?)\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x3e\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00092cc00?, {0x4fe2700, 0xc00075eaa0}, 0x1, 0xc000f85920)\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xb6\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: k8s.io/client-go/tools/cache.(*Reflector).Run(0xc000cbb770, 0xc000f85920)\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: vendor/k8s.io/client-go/tools/cache/reflector.go:222 +0x17d\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: k8s.io/kubernetes/pkg/kubelet/util/manager.(*objectCacheItem).startReflector(0xc000e03ce0)\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: pkg/kubelet/util/manager/watch_based_manager.go:123 +0x91\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: created by k8s.io/kubernetes/pkg/kubelet/util/manager.(*objectCache).newReflectorLocked\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: pkg/kubelet/util/manager/watch_based_manager.go:243 +0x84b\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: panic: runtime error: invalid memory address or nil pointer dereference [recovered]\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: panic: runtime error: invalid memory address or nil pointer dereference\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: goroutine 549 [running]:\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x2540be400?})\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xd7\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: panic({0x3f89c00, 0x71f2840})\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: /usr/local/go/src/runtime/panic.go:884 +0x212\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: k8s.io/client-go/tools/cache.(*Reflector).list(0xc000cbb770, 0xc000f85920)\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: vendor/k8s.io/client-go/tools/cache/reflector.go:419 +0xb32\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc000cbb770, 0xc000f85920)\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: vendor/k8s.io/client-go/tools/cache/reflector.go:259 +0x152\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: k8s.io/client-go/tools/cache.(*Reflector).Run.func1()\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: vendor/k8s.io/client-go/tools/cache/reflector.go:223 +0x26\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0011af000?)\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x3e\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00092cc00?, {0x4fe2700, 0xc00075eaa0}, 0x1, 0xc000f85920)\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xb6\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: k8s.io/client-go/tools/cache.(*Reflector).Run(0xc000cbb770, 0xc000f85920)\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: vendor/k8s.io/client-go/tools/cache/reflector.go:222 +0x17d\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: k8s.io/kubernetes/pkg/kubelet/util/manager.(*objectCacheItem).startReflector(0xc000e03ce0)\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: pkg/kubelet/util/manager/watch_based_manager.go:123 +0x91\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: created by k8s.io/kubernetes/pkg/kubelet/util/manager.(*objectCache).newReflectorLocked\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm kubelet[3019]: pkg/kubelet/util/manager/watch_based_manager.go:243 +0x84b\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm systemd[1]: \x1b[0;1;39m\x1b[0;1;31m\x1b[0;1;39mkubelet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT\x1b[0m\r\n
2022-10-31T20:00:48+0000 gke-b27bb59e05314f15b662-a7f3-3599-vm systemd[1]: \x1b[0;1;38;5;185m\x1b[0;1;39m\x1b[0;1;38;5;185mkubelet.service: Failed with result \'exit-code\'.\x1b[0m\r\n
```

### What did you expect to happen?

Instead of crashing Kubelet should have printed out a meaningful error message that would aid debugging.

### How can we reproduce it (as minimally and precisely as possible)?

Create a static pod that refers to a configMap and bring the pod up

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3-gke.900", GitCommit:"d7960fa8dcb507f46a99fb5f2ee0a1816cde8fea", GitTreeState:"clean", BuildDate:"2022-10-27T09:29:11Z", GoVersion:"go1.19.2 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
KERNEL_COMMIT_ID=6ffe18e56639e7815b07badca4d68fb0b54003cc
GOOGLE_METRICS_PRODUCT_ID=26
GOOGLE_CRASH_ID=Lakitu
VERSION=101
VERSION_ID=101
BUILD_ID=17162.40.13

$ uname -a
Linux gke-b5b62460724e4cfeae70-0376-801c-vm 5.15.65+ #1 SMP Sat Oct 15 09:12:54 UTC 2022 x86_64 Intel(R) Xeon(R) CPU @ 2.20GHz GenuineIntel GNU/Linux
```

</details>

### Install tools

<details>
None. Used GKE.
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
This is specifically when running a kubelet in standalone mode without an API connection
