### ISSUE TITLE
xgboost running with kubernetes issue 

### ISSUE THREAD

**Issue by Ayyan-droid** [kubernetes/kubernetes#113573]
### What happened?

i am using the following jars

xgboost4j-spark_2.12-1.6.1.jar
xgboost4j_2.12-1.6.1.jar

Here is the stack trace:

Traceback (most recent call last):
File "/u/bin/ai_fraudengine/AIModelTrain/aimodeltrain/bl/StandardModelTrainHandlerImpl.py", line 32, in train_model
trained_pipeline = train_pipeline.fit(df)
File "/opt/spark/python/pyspark/ml/base.py", line 161, in fit
return self._fit(dataset)
File "/opt/spark/python/pyspark/ml/pipeline.py", line 114, in _fit
model = stage.fit(dataset)
File "/opt/spark/python/pyspark/ml/base.py", line 161, in fit
return self._fit(dataset)
File "/opt/spark/python/pyspark/ml/wrapper.py", line 335, in _fit
java_model = self._fit_java(dataset)
File "/opt/spark/python/pyspark/ml/wrapper.py", line 331, in _fit_java
self._transfer_params_to_java()
File "/opt/spark/python/pyspark/ml/wrapper.py", line 143, in _transfer_params_to_java
pair = self._make_java_param_pair(param, self._paramMap[param])
File "/opt/spark/python/pyspark/ml/wrapper.py", line 134, in _make_java_param_pair
return java_param.w(java_value)
File "/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in call
answer, self.gateway_client, self.target_id, self.name)
File "/opt/spark/python/pyspark/sql/utils.py", line 111, in deco
return f(*a, **kw)
File "/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 328, in get_return_value
format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o18402.w.
: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:103)
at org.apache.spark.ml.param.IntParam.w(params.scala:382)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
at py4j.Gateway.invoke(Gateway.java:282)
at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
at py4j.commands.CallCommand.execute(CallCommand.java:79)
at py4j.GatewayConnection.run(GatewayConnection.java:238)
at java.lang.Thread.run(Thread.java:750)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/u/bin/ai_fraudengine/AIModelTrain/aimodeltrain/bl/ModelTrainHandlerImpl.py", line 101, in train_model
execution_context_info=execution_context_info, model_class_handler=model_class, model=model, validation_df = validation_df)
File "/u/bin/ai_fraudengine/AIModelTrain/aimodeltrain/bl/StandardModelTrainHandlerImpl.py", line 50, in train_model
raise CommonBaseException(exp)
commonexceps.CommonBaseException.CommonBaseException: An error occurred while calling o18402.w.
: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:103)
at org.apache.spark.ml.param.IntParam.w(params.scala:382)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
at py4j.Gateway.invoke(Gateway.java:282)
at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
at py4j.commands.CallCommand.execute(CallCommand.java:79)
at py4j.GatewayConnection.run(GatewayConnection.java:238)
at java.lang.Thread.run(Thread.java:750)

### What did you expect to happen?

distributed training of xgboost

### How can we reproduce it (as minimally and precisely as possible)?

run xgboost spark with kubernetes 

### Kubernetes version

<details>
1.2.5.3.4
```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
       own
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/remove-kind bug
/kind support 
It seems to be a problem in the jar/application. I would suggest you ask in the spark community.
This should not be a Kubernetes bug.

**Comment by pacoxu** [comment]
/close
 https://github.com/dmlc/xgboost/issues/8412
