### ISSUE TITLE
Latest k8s fails with kublet panic runtime error

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/kubernetes#113781]
### What happened?

While setting up k8s cluster using the ci/latest version, we notice the kublet failure with below error message in its log:

```
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]: I1109 07:20:47.984943   26715 topology_manager.go:134] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container"
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]: panic: runtime error: index out of range [1] with length 1
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]: goroutine 1 [running]:
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.newNUMAInfo({0xc0008ca540, 0x1, 0x0?}, 0xc000eda120)
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]:         pkg/kubelet/cm/topologymanager/numa_info.go:62 +0x2d4
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.NewNUMAInfo(...)
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]:         pkg/kubelet/cm/topologymanager/numa_info.go:45
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.NewManager({0xc0008ca540, 0x1, 0x1}, {0x143fa6eb, 0x4}, {0x14403c29, 0x9}, 0xc0007dd800?)
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]:         pkg/kubelet/cm/topologymanager/topology_manager.go:136 +0x1c8
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]: k8s.io/kubernetes/pkg/kubelet/cm.NewContainerManager({_, _}, {_, _}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]:         pkg/kubelet/cm/container_manager_linux.go:288 +0xba4
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]: k8s.io/kubernetes/cmd/kubelet/app.run({0x14c4b570, 0xc0004b03c0}, 0xc000ddc000, 0xc0008cea80, {0x7fff5c446958, 0xc0004b01c0})
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]:         cmd/kubelet/app/server.go:723 +0x1724
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]: k8s.io/kubernetes/cmd/kubelet/app.Run({0x14c4b570, 0xc0004b03c0}, 0xc000ddc000, 0x6?, {0x7fff5c446958, 0xc0004b01c0})
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]:         cmd/kubelet/app/server.go:419 +0x344
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]: k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0x101c2b8c?, {0xc000192080, 0x6, 0x6})
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]:         cmd/kubelet/app/server.go:265 +0x9c0
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]: github.com/spf13/cobra.(*Command).execute(0xc0005a6c00, {0xc000192080, 0x6, 0x6})
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]:         vendor/github.com/spf13/cobra/command.go:916 +0x674
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]: github.com/spf13/cobra.(*Command).ExecuteC(0xc0005a6c00)
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]:         vendor/github.com/spf13/cobra/command.go:1040 +0x36c
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]: github.com/spf13/cobra.(*Command).Execute(...)
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]:         vendor/github.com/spf13/cobra/command.go:968
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]: k8s.io/component-base/cli.run(0xc0005a6c00)
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]:         vendor/k8s.io/component-base/cli/run.go:146 +0x2dc
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]: k8s.io/component-base/cli.Run(0xc000180058?)
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]:         vendor/k8s.io/component-base/cli/run.go:46 +0x30
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]: main.main()
Nov 09 07:20:47 config1-1667977224-worker-0 kubelet[26715]:         cmd/kubelet/kubelet.go:36 +0x28
Nov 09 07:20:48 config1-1667977224-worker-0 systemd[1]: kubelet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 09 07:20:48 config1-1667977224-worker-0 systemd[1]: kubelet.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
```

### What did you expect to happen?

There should be no error while kubelet is coming up.

### How can we reproduce it (as minimally and precisely as possible)?

Install the prerequisites needed for the cluster setup.
Enable and try to start the kubelet.

### Kubernetes version
<details>

```console
$ kubectl version
"v1.26.0-alpha.3.456+20a9f7786aa4ee"
```
</details>

### Cloud provider

<details>
We noticed this in our IBM Cloud provider PowerVS
</details>

**Comment by mkumatag** [comment]
could be a side effect of https://github.com/kubernetes/kubernetes/pull/112914

/cc @PiotrProkop @klueska

**Comment by PiotrProkop** [comment]
@Rajalakshmi-Girish can you run `numactl -H` on the node where the kubelet fails to start? And can you provide the Operating System of the node?

**Comment by mkumatag** [comment]
> numactl -H

```shell
[root@config1-1667977224-master ~]# numactl -H
available: 1 nodes (0)
node 0 cpus: 0 1 2 3 4 5 6 7
node 0 size: 31625 MB
node 0 free: 24307 MB
node distances:
node   0
  0:  10

[root@config1-1667977224-master ~]# cat /etc/os-release
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
[root@config1-1667977224-master ~]#
```

**Comment by PiotrProkop** [comment]
@mkumatag can you also run:
```
ls /sys/devices/system/node/
```

**Comment by mkumatag** [comment]
both got similar config I believe, @Rajalakshmi-Girish can you please get the requested information from the other node?

**Comment by Rajalakshmi-Girish** [comment]
> and can you please rerun `numactl -H` on `config1-1667977224-worker-0`

```
[root@config1-1667977224-worker-0 ~]# numactl -H
available: 1 nodes (1)
node 1 cpus: 0 1 2 3 4 5 6 7
node 1 size: 31625 MB
node 1 free: 26403 MB
node distances:
node   1
  1:  10
[root@config1-1667977224-worker-0 ~]#
```

**Comment by PiotrProkop** [comment]
@Rajalakshmi-Girish and @mkumatag thanks for the info I know what is the issue, here is FIX PR https://github.com/kubernetes/kubernetes/pull/113788

**Comment by liggitt** [comment]
since this is a bug introduced in 1.26

/kind regression
/label release-blocker

**Comment by SergeyKanzhelev** [comment]
/assign @fromanirh 

to take a look
