### ISSUE TITLE
Panic on job controller

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#113852]
Since the last days there is an unusual rate of flakiness on kind jobs, but couldn't find a pattern

![image](https://user-images.githubusercontent.com/6450081/201342503-14bccf80-0550-4d6a-8065-1ffa1d56e0eb.png)

https://testgrid.k8s.io/sig-release-master-blocking#kind-master-parallel&width=20

https://storage.googleapis.com/k8s-triage/index.html?ci=0&pr=1

While looking at one test failure 
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1590913411464564736 

and checking at the controller manager logs, there is a panic on the controller manager that makes the controller manager to restart and impacts on all the test that are running at that time.

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1590913411464564736/artifacts/kind-control-plane/pods/kube-system_kube-controller-manager-kind-control-plane_3e273dfbea12b5e2f257cbecf138676d/kube-controller-manager/1.log

```
2022-11-11T04:14:03.708643025Z stderr F I1111 04:14:03.708431       1 controller_utils.go:938] Ignoring inactive pod job-4201/pod-disruption-failure-ignore-3-ghfx4 in state Succeeded, deletion time <nil>
2022-11-11T04:14:03.708665068Z stderr F I1111 04:14:03.708479       1 job_controller.go:669] Finished syncing job "job-4201/pod-disruption-failure-ignore" (395.972µs)
2022-11-11T04:14:03.708719804Z stderr F E1111 04:14:03.708598       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
2022-11-11T04:14:03.708771633Z stderr F goroutine 1971 [running]:
2022-11-11T04:14:03.708780922Z stderr F k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3ed03e0?, 0x755d570})
2022-11-11T04:14:03.708787473Z stderr F 	vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
2022-11-11T04:14:03.70879195Z stderr F k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0017ea430?})
2022-11-11T04:14:03.708796399Z stderr F 	vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
2022-11-11T04:14:03.70880099Z stderr F panic({0x3ed03e0, 0x755d570})
2022-11-11T04:14:03.708805824Z stderr F 	/usr/local/go/src/runtime/panic.go:884 +0x212
2022-11-11T04:14:03.708810477Z stderr F k8s.io/kubernetes/pkg/controller/job.getMatchingContainerFromList(...)
2022-11-11T04:14:03.70881498Z stderr F 	pkg/controller/job/pod_failure_policy.go:92
2022-11-11T04:14:03.708820503Z stderr F k8s.io/kubernetes/pkg/controller/job.matchOnExitCodes(0xc001342310, 0xc0011e2720)
2022-11-11T04:14:03.708825213Z stderr F 	pkg/controller/job/pod_failure_policy.go:72 +0x2e3
2022-11-11T04:14:03.70882944Z stderr F k8s.io/kubernetes/pkg/controller/job.matchPodFailurePolicy(0xc002267ae8, 0xc001342000)
2022-11-11T04:14:03.708833602Z stderr F 	pkg/controller/job/pod_failure_policy.go:41 +0x1d7
2022-11-11T04:14:03.708838331Z stderr F k8s.io/kubernetes/pkg/controller/job.getStatus.func2(0xc001342000)
2022-11-11T04:14:03.708843178Z stderr F 	pkg/controller/job/job_controller.go:1374 +0xd0
2022-11-11T04:14:03.70884815Z stderr F k8s.io/kubernetes/pkg/controller/job.countValidPodsWithFilter(0xc000933900, {0xc000a40760, 0x4, 0x8?}, 0xc0011e28d0, 0x0?, 0xc0018692e8)
2022-11-11T04:14:03.70885299Z stderr F 	pkg/controller/job/job_controller.go:1619 +0x18d
2022-11-11T04:14:03.708857836Z stderr F k8s.io/kubernetes/pkg/controller/job.getStatus(0xc000933900, {0xc000a40760, 0x4, 0x4}, 0xc0008f6ff0, 0x0?)
2022-11-11T04:14:03.708861735Z stderr F 	pkg/controller/job/job_controller.go:1369 +0xf9
2022-11-11T04:14:03.708866774Z stderr F k8s.io/kubernetes/pkg/controller/job.(*Controller).syncJob(0xc001096a90, {0x511ae50, 0xc0009d2280}, {0xc0017cc4b0, 0x26})
2022-11-11T04:14:03.708871081Z stderr F 	pkg/controller/job/job_controller.go:738 +0x9f8
2022-11-11T04:14:03.708875083Z stderr F k8s.io/kubernetes/pkg/controller/job.(*Controller).processNextWorkItem(0xc001096a90, {0x511ae50, 0xc0009d2280})
2022-11-11T04:14:03.708879414Z stderr F 	pkg/controller/job/job_controller.go:537 +0x123
2022-11-11T04:14:03.708883985Z stderr F k8s.io/kubernetes/pkg/controller/job.(*Controller).worker(0xc0011e2690?, {0x511ae50, 0xc0009d2280})
2022-11-11T04:14:03.708888449Z stderr F 	pkg/controller/job/job_controller.go:526 +0x39
2022-11-11T04:14:03.708892768Z stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
2022-11-11T04:14:03.708897013Z stderr F 	vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:190 +0x25
2022-11-11T04:14:03.70893803Z stderr F k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x203000?)
2022-11-11T04:14:03.708944858Z stderr F 	vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x3e
2022-11-11T04:14:03.708949425Z stderr F k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x50ee060, 0xc0011e2690}, 0x1, 0xc000a5b2c0)
2022-11-11T04:14:03.70895385Z stderr F 	vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xb6
2022-11-11T04:14:03.708957959Z stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x40dc27?, 0x3b9aca00, 0x0, 0x1?, 0xc0018db770?)
2022-11-11T04:14:03.708974504Z stderr F 	vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x89
2022-11-11T04:14:03.70897939Z stderr F k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext({0x511ae50, 0xc0009d2280}, 0xc0008f6b60, 0x3b9aca00?, 0x0?, 0x80?)
2022-11-11T04:14:03.708983365Z stderr F 	vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:190 +0x99
2022-11-11T04:14:03.70898773Z stderr F k8s.io/apimachinery/pkg/util/wait.UntilWithContext({0x511ae50?, 0xc0009d2280?}, 0xc0004ad208?, 0xc0018db7b8?)
2022-11-11T04:14:03.708991872Z stderr F 	vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:101 +0x2b
2022-11-11T04:14:03.709023054Z stderr F created by k8s.io/kubernetes/pkg/controller/job.(*Controller).Run
2022-11-11T04:14:03.709029377Z stderr F 	pkg/controller/job/job_controller.go:199 +0x3b4
2022-11-11T04:14:03.712299955Z stderr F panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2022-11-11T04:14:03.712318039Z stderr F 	panic: runtime error: invalid memory address or nil pointer dereference
2022-11-11T04:14:03.71232312Z stderr F [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1785d63]
2022-11-11T04:14:03.712327233Z stderr F 
2022-11-11T04:14:03.712340911Z stderr F goroutine 1971 [running]:
2022-11-11T04:14:03.712346136Z stderr F k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0017ea430?})
````

Lessons learned, we should not increase timeouts forever or these problems will go unnoticed, still, they are really hard to find and is not the first time that this happens, maybe Kubernetes is too good reconciling XD

It will be great to have a tool that detect panics on the components

/sig scheduling

**Comment by liggitt** [comment]
> It will be great to have a tool that detect panics on the components

big +1, a restart or panic detector on control plane components would be excellent

**Comment by alculquicondor** [comment]
cc @mimowo

**Comment by aojea** [comment]
> > It will be great to have a tool that detect panics on the components
> 
> big +1, a restart or panic detector on control plane components would be excellent

@MadhavJivrajani this sounds like a nice project ^^^ but is better to check first with @BenTheElder and @spiffxp , I see there are some scripts that parse and dump the logs here https://github.com/kubernetes/test-infra/blob/f89c3d9701ef9fb70caeadebab2865069651863e/logexporter/cluster/log-dump.sh#L871 

maybe we can add some `grep panic` thing to report them somehow?

**Comment by alculquicondor** [comment]
oops, it's holiday in Poland
/unassign @mimowo 
/assign

**Comment by alculquicondor** [comment]
I can add the fix proposed by @liggitt, but the underlying problem is #113855.

I'll prepare a PR for each and see if we are ok merging both or just the hotfix.

**Comment by liggitt** [comment]
commented on https://github.com/kubernetes/kubernetes/issues/113855

we'll merge the panic fix right away in either case

**Comment by alculquicondor** [comment]
Fix and unit test is up #113856
