### ISSUE TITLE
Some API parameter parsing error

### ISSUE THREAD

**Issue by painsAgains** [kubernetes/kubernetes#113939]
### /api/v1/componentstatuses/{name}
When I accessed a non-existent component,I recevied 500 status

### resourceVerison parameter parsiong error
When I set the value of the `resourceverion` parameter to an arbitrary string,I got 500 status 

### /api/v1/componentstatuses/{name}
I think when I access a non-existent component, I should recevie a 404 status response rather than a 500 status.I found this error in v1.18.3 but in v1.25.3 I still find it.

### resourceVerison parameter parsiong error
In the[ documentation](https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions) , when I  request list or get for a resource version that the API server does not recognize, then the API server may either:

- wait briefly for the resource version to become available, then timeout with a if the provided resource versions does not become available in a reasonable amount of time;**504 (Gateway Timeout)**

- respond with a response header indicating how many seconds a client should wait before retrying the request.**Retry-After**
- If you request a resource version that an API server does not recognize, the kube-apiserver additionally identifies its error responses with a "**Too large resource version**" message
So I think when I set up a wrong value for resourceVersion,I should recevie a 504 status rather than a 500 status

### /api/v1/componentstatuses{name}
curl -v -X GET 'https://1ip:port/api/v1/componentstatuses/galvanize' -H 'Authorization:CENSORED' -H 'Accept: */*'
### resourceVerion error
curl -v -X GET 'https://ip:port/apis/storage.k8s.io/v1/watch/namespaces/wallpaper/csistoragecapacities?pretty=one-armed&resourceVersion=cool&limit=58&allowWatchBookmarks=false' -H 'Authorization:CENSORED' -H 'Accept: */*

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal




</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by weilaaa** [comment]
Add logs for problem 1.

```log
➜  ~ kubectl get --raw='/api/v1/componentstatuses/xxx' -v=6
I1116 11:53:16.954490 3807325 loader.go:372] Config loaded from file:  /root/.kube/config
I1116 11:53:16.960436 3807325 round_trippers.go:553] GET https://10.219.192.164:6443/api/v1/componentstatuses/xxx 500 Internal Server Error in 5 milliseconds
Warning: v1 ComponentStatus is deprecated in v1.19+
I1116 11:53:16.960663 3807325 helpers.go:219] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "Component not found: xxx",
  "code": 500
}]
F1116 11:53:16.960684 3807325 helpers.go:118] Error from server: Component not found: xxx
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0x1)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1038 +0x8a
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x3080040, 0x3, 0x0, 0xc000770310, 0x2, {0x25f2be7, 0x10}, 0xc000068800, 0x0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:987 +0x5fd
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0xc0009be240, 0x2b, 0x0, {0x0, 0x0}, 0xc00068ac38, {0xc0003ff150, 0x1, 0x1})
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:735 +0x1ae
k8s.io/kubernetes/vendor/k8s.io/klog/v2.FatalDepth(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1518
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.fatal({0xc0009be240, 0x2b}, 0xc000715180)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:96 +0xc5
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.checkErr({0x1feb600, 0xc000715180}, 0x1e79770)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:191 +0x7d7
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:118
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get.NewCmdGet.func2(0xc0003b8780, {0xc00007fa20, 0x0, 0x2})
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get/get.go:181 +0xc8
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0003b8780, {0xc00007fa00, 0x2, 0x2})
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:860 +0x5f8
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0004a6280)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:902
k8s.io/kubernetes/vendor/k8s.io/component-base/cli.run(0xc0004a6280)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/cli/run.go:146 +0x325
k8s.io/kubernetes/vendor/k8s.io/component-base/cli.RunNoErrOutput(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/cli/run.go:84
main.main()
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:30 +0x1e

goroutine 6 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1181 +0x6a
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:420 +0xfb

goroutine 12 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x1feb900, 0xc0005a4000}, 0x1, 0xc000094360)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x13b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x12a05f200, 0x0, 0x0, 0x0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x0, 0x0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81 +0x28
created by k8s.io/kubernetes/vendor/k8s.io/component-base/logs.InitLogs
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/logs/logs.go:179 +0x85

goroutine 33 [IO wait]:
internal/poll.runtime_pollWait(0x7fdfcce74818, 0x72)
	/usr/local/go/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc00052eb80, 0xc0007a6000, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00052eb80, {0xc0007a6000, 0x8dd, 0x8dd})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc00052eb80, {0xc0007a6000, 0xc0007a6005, 0x8f})
	/usr/local/go/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc00011a028, {0xc0007a6000, 0x3fffd4003fffd3, 0xc0001337f0})
	/usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc0006980d8, {0xc0007a6000, 0x0, 0x409e2d})
	/usr/local/go/src/crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc0007765f8, {0x1fe9740, 0xc0006980d8})
	/usr/local/go/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000776380, {0x1fed120, 0xc00011a028}, 0x8dd)
	/usr/local/go/src/crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc000776380, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc000776380, {0xc00007c000, 0x1000, 0x8da880})
	/usr/local/go/src/crypto/tls/conn.go:1277 +0x16f
bufio.(*Reader).Read(0xc000114c00, {0xc0001aa900, 0x9, 0x8e8842})
	/usr/local/go/src/bufio/bufio.go:227 +0x1b4
io.ReadAtLeast({0x1fe9540, 0xc000114c00}, {0xc0001aa900, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:328 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:347
k8s.io/kubernetes/vendor/golang.org/x/net/http2.readFrameHeader({0xc0001aa900, 0x9, 0xc00179e300}, {0x1fe9540, 0xc000114c00})
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:237 +0x6e
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc0001aa8c0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:498 +0x95
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000133f98)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:2101 +0x130
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc00019cd80)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1997 +0x6f
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).newClientConn
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:725 +0xac5
```

**Comment by weilaaa** [comment]
Add logs for problem 2.

```log
➜  ~ kubectl get --raw='/api/v1/watch/namespaces/kube-system/pods?pretty=one-armed&resourceVersion=cool&limit=58&allowWatchBookmarks=false' -v=6
I1116 11:58:43.428486 3815795 loader.go:372] Config loaded from file:  /root/.kube/config
I1116 11:58:43.435157 3815795 round_trippers.go:553] GET https://10.219.192.164:6443/api/v1/watch/namespaces/kube-system/pods?allowWatchBookmarks=false&limit=58&pretty=one-armed&resourceVersion=cool 500 Internal Server Error in 6 milliseconds
I1116 11:58:43.435694 3815795 helpers.go:219] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "resourceVersion: Invalid value: \"cool\": strconv.ParseUint: parsing \"cool\": invalid syntax",
  "code": 500
}]
F1116 11:58:43.435914 3815795 helpers.go:118] Error from server: resourceVersion: Invalid value: "cool": strconv.ParseUint: parsing "cool": invalid syntax
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0x1)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1038 +0x8a
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x3080040, 0x3, 0x0, 0xc0004b27e0, 0x2, {0x25f2be7, 0x10}, 0xc000068400, 0x0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:987 +0x5fd
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0xc00072aaf0, 0x6c, 0x0, {0x0, 0x0}, 0xc000395828, {0xc00069f190, 0x1, 0x1})
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:735 +0x1ae
k8s.io/kubernetes/vendor/k8s.io/klog/v2.FatalDepth(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1518
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.fatal({0xc00072aaf0, 0x6c}, 0xc000533220)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:96 +0xc5
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.checkErr({0x1feb600, 0xc000533220}, 0x1e79770)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:191 +0x7d7
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:118
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get.NewCmdGet.func2(0xc0004a7b80, {0xc00051da00, 0x0, 0x2})
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/get/get.go:181 +0xc8
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0004a7b80, {0xc00051d9e0, 0x2, 0x2})
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:860 +0x5f8
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000699680)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:902
k8s.io/kubernetes/vendor/k8s.io/component-base/cli.run(0xc000699680)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/cli/run.go:146 +0x325
k8s.io/kubernetes/vendor/k8s.io/component-base/cli.RunNoErrOutput(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/cli/run.go:84
main.main()
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:30 +0x1e

goroutine 6 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1181 +0x6a
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:420 +0xfb

goroutine 8 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0, {0x1feb900, 0xc0005c2000}, 0x1, 0xc000094360)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x13b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x12a05f200, 0x0, 0x0, 0x0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x0, 0x0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81 +0x28
created by k8s.io/kubernetes/vendor/k8s.io/component-base/logs.InitLogs
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/logs/logs.go:179 +0x85

goroutine 12 [IO wait]:
internal/poll.runtime_pollWait(0x7fd189710818, 0x72)
	/usr/local/go/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc00047ec80, 0xc000175600, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00047ec80, {0xc000175600, 0x8dd, 0x8dd})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc00047ec80, {0xc000175600, 0xc000175605, 0xd4})
	/usr/local/go/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc00000e038, {0xc000175600, 0x3fffd4003fffd3, 0xc0005937f0})
	/usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc00054ad68, {0xc000175600, 0x0, 0x409e2d})
	/usr/local/go/src/crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc0005cc278, {0x1fe9740, 0xc00054ad68})
	/usr/local/go/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0005cc000, {0x1fed120, 0xc00000e038}, 0x8dd)
	/usr/local/go/src/crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0005cc000, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc0005cc000, {0xc000817000, 0x1000, 0x8da880})
	/usr/local/go/src/crypto/tls/conn.go:1277 +0x16f
bufio.(*Reader).Read(0xc000088d80, {0xc0001aa900, 0x9, 0x8e8842})
	/usr/local/go/src/bufio/bufio.go:227 +0x1b4
io.ReadAtLeast({0x1fe9540, 0xc000088d80}, {0xc0001aa900, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:328 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:347
k8s.io/kubernetes/vendor/golang.org/x/net/http2.readFrameHeader({0xc0001aa900, 0x9, 0xc00169bc20}, {0x1fe9540, 0xc000088d80})
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:237 +0x6e
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc0001aa8c0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:498 +0x95
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000593f98)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:2101 +0x130
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc00019cd80)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:1997 +0x6f
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).newClientConn
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:725 +0xac5
```

**Comment by weilaaa** [comment]
Some errors convert to `metav1.Status` failed defaulting to InternalError 500. 
Should we increase the judgment of some common storage errors, and then require the caller to use NewXxxError to construct common errors. @liggitt @lavalamp

https://github.com/kubernetes/kubernetes/blob/43b7a253539a777a4671c6ba761f38f605e87465/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/status.go#L60-L81

**Comment by BenTheElder** [comment]
This is still true on v1.32.1 (using [kind](https://sigs.k8s.io/kind)):

```console
$ kubectl version
Client Version: v1.32.1
Kustomize Version: v5.5.0
Server Version: v1.32.1

$ kubectl get --raw='/api/v1/componentstatuses/xxx' -v=6
I0128 21:30:43.391550   11839 loader.go:402] Config loaded from file:  /usr/local/google/home/bentheelder/.kube/config
I0128 21:30:43.391905   11839 envvar.go:172] "Feature gate default state" feature="InformerResourceVersion" enabled=false
I0128 21:30:43.391924   11839 envvar.go:172] "Feature gate default state" feature="WatchListClient" enabled=false
I0128 21:30:43.391930   11839 envvar.go:172] "Feature gate default state" feature="ClientsAllowCBOR" enabled=false
I0128 21:30:43.391935   11839 envvar.go:172] "Feature gate default state" feature="ClientsPreferCBOR" enabled=false
I0128 21:30:43.398606   11839 round_trippers.go:560] GET https://127.0.0.1:36699/api/v1/componentstatuses/xxx 500 Internal Server Error in 6 milliseconds
Warning: v1 ComponentStatus is deprecated in v1.19+
I0128 21:30:43.398813   11839 helpers.go:246] server response object: %s[{
  "metadata": {},
  "status": "Failure",
  "message": "Component not found: xxx",
  "code": 500
}]
Error from server: Component not found: xxx

$ kubectl get --raw='/api/v1/pod/xxx' -v=6
I0128 21:33:00.095782   13101 loader.go:402] Config loaded from file:  /usr/local/google/home/bentheelder/.kube/config
I0128 21:33:00.096201   13101 envvar.go:172] "Feature gate default state" feature="ClientsAllowCBOR" enabled=false
I0128 21:33:00.096221   13101 envvar.go:172] "Feature gate default state" feature="ClientsPreferCBOR" enabled=false
I0128 21:33:00.096227   13101 envvar.go:172] "Feature gate default state" feature="InformerResourceVersion" enabled=false
I0128 21:33:00.096232   13101 envvar.go:172] "Feature gate default state" feature="WatchListClient" enabled=false
I0128 21:33:00.102626   13101 round_trippers.go:560] GET https://127.0.0.1:36699/api/v1/pod/xxx 404 Not Found in 6 milliseconds
I0128 21:33:00.102894   13101 helpers.go:246] server response object: %s[{
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404
}]
Error from server (NotFound): the server could not find the requested resource
```

cc @kubernetes/sig-api-machinery-leads thoughts?

**Comment by yongruilin** [comment]
I have https://github.com/kubernetes/kubernetes/pull/129870 to make it return 404 for componentstatus not found

**Comment by liggitt** [comment]
Scoped this down to the resourceVersion parsing response report

**Comment by yongruilin** [comment]
Any LIST or GET request with parameter `resourceVersion=<invalid value>` would result in 500 response.
The cause is that [ParseResourceVersion](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/api_object_versioner.go#L90) returns an `InvalidError`and [ErrorToAPIStatus(err error)](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/status.go#L34) always parses it to http.StatusInternalServerError.

There are various ways to fix it, but I would like to check with @jpbetz on the documentation https://kubernetes.io/docs/reference/using-api/api-concepts/#unavailable-resource-versions to determine the proper response. Is the "unrecognized" the same as "invalid"? If it is "invalid", shouldn't the response status be "400 Bad Request"?

**Comment by jpbetz** [comment]
We should formalize the distinction between (a) "an unavailable resource version an apiserver can process" and (b) "a resource version an apiserver cannot process".

https://kubernetes.io/docs/reference/using-api/api-concepts/#unavailable-resource-versions covers (a) only.

Different apiservers are allowed to use different resource version schemes.  The kube-apiserver simply uses etcd's revision number, which is a int64 that monotonically increases for each etcd write transaction.  That is- at some point, the kube-apiserver MUST convert the resource version string to a int64 in order to construct an etcd request and do *something* if the resource version string is not an int64. With this resource version scheme, the kube-apiserver will *never* be able to a non-integer resource version, so telling the client to wait, or telling the client that the resource version is "too large" are both misleading.

But I agree 500 is not a good response.  400 seems appropriate here.

Note that other apiservers (custom apiservers or aggregated API servers) are allowed to use different schemes, so may accept non-integer resource versions. For this to be possible, we do require that when the kube-apiserver aggregates other apiservers, and that it treats resource versions as opaque strings during aggregation.

https://github.com/kubernetes/enhancements/pull/5505 is also relevant here and covers how clients should behave when resource version strings need to be compared.
