### ISSUE TITLE
ci-benchmark-scheduler-perf-master is failing

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#114890]
### Which jobs are failing?

ci-benchmark-scheduler-perf-master

### Which tests are failing?

scheduler_perf

### Since when has it been failing?

This Job was keep failing by another issue until https://github.com/kubernetes/kubernetes/pull/114796. So, we don't know when the current problem is started.

### Testgrid link

https://testgrid.k8s.io/sig-scalability-benchmarks#scheduler-perf

### Reason for failure (if possible)

We're observing several errors on scheduler_perf benchmark job now.
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-benchmark-scheduler-perf-master/1610954337838698496/build-log.txt

- `Error while deleting Node: client rate limiter Wait returned an error: context canceled`
  - will be fixed in https://github.com/kubernetes/kubernetes/pull/114843.
- `Process did not finish before 1h55m0s timeout`, `Could not interrupt process after timeout`
  - will be fixed in https://github.com/kubernetes/test-infra/pull/28368
  - But, if #114843 contributes to reducing the time, we may not need ^.
- `unexpected number of goroutines: before: 2 after 43`

### Relevant SIG(s)

/sig scheduling

/assign @sanposhiho
/assign @kerthcet

**Comment by sanposhiho** [comment]
The direct reason why the `ci-benchmark-scheduler-perf-master` is marked as fail is `unexpected number of goroutines: before: 2 after 43`.
https://github.com/kubernetes/kubernetes/blob/643353abfe180ded1fae1fe6fd48d3930d26a9e4/test/integration/framework/etcd.go#L217

I'm not sure if it can be fixed by https://github.com/kubernetes/kubernetes/pull/114843 or not. Let's see..

**Comment by pohly** [comment]
Here's a patch that makes the reporting of leaked goroutines more useful:

```patch
commit 469526fab53efb4cc26fb70b610239a232890a73
Author: Patrick Ohly <patrick.ohly@intel.com>
Date:   Wed Jan 25 17:59:10 2023 +0100

    test/integration: improve output when etcd detects leaked goroutines
    
    With the current output one was only told how many additional goroutines were
    running after a test and a dump of the current ones. But without knowing what
    was running initially, that information was not enough.
    
    Now a diff that shows changes in the stack traces before and after a test is
    shown.
    
    This currently gets triggered and leads to output like this:
    
    F0125 17:57:26.577440  462703 etcd.go:216] unexpected number of goroutines: before: 3, after: 9
      (
            """
            goroutine 1 [running]:
    -       k8s.io/kubernetes/test/integration/framework.stacks(0x10000)
    +       k8s.io/kubernetes/test/integration/framework.stacks(0x100000)
                    /nvme/gopath/src/k8s.io/kubernetes/test/integration/framework/etcd.go:224 +0x8a
            k8s.io/kubernetes/test/integration/framework.EtcdMain(0xc00139fe98)
    -               /nvme/gopath/src/k8s.io/kubernetes/test/integration/framework/etcd.go:189 +0x85
    +               /nvme/gopath/src/k8s.io/kubernetes/test/integration/framework/etcd.go:215 +0x1c5
            k8s.io/kubernetes/test/integration/scheduler_perf.TestMain(0xc0011680a0)
                    /nvme/gopath/src/k8s.io/kubernetes/test/integration/scheduler_perf/main_test.go:58 +0x1c8
            ... // 7 identical lines
                    /nvme/gopath/src/k8s.io/kubernetes/vendor/go.opencensus.io/stats/view/worker.go:34 +0x8d
      
    -       goroutine 203 [runnable]:
    +       goroutine 203 [select]:
            k8s.io/klog/v2.(*flushDaemon).run.func1()
    -               /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1131
    +               /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1135 +0x11e
            created by k8s.io/klog/v2.(*flushDaemon).run
                    /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1131 +0x17b
    + 
    +       goroutine 1514 [select]:
    +       k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x5906aa0, 0xc005ec4030}, 0x1, 0xc0000863c0)
    +               /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:169 +0x135
    +       k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0xdf8475800, 0x0, 0x0?, 0x0?)
    +               /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x89
    +       k8s.io/apimachinery/pkg/util/wait.Until(...)
    +               /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92
    +       k8s.io/apimachinery/pkg/util/wait.Forever(0x0?, 0x0?)
    +               /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:83 +0x28
    +       created by k8s.io/apiserver/pkg/server/healthz.(*log).Check.func1
    +               /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go:74 +0xe5
    + 
    +       goroutine 2473 [chan receive]:
    +       k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc0031c0d70)
    +               /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/mux.go:268 +0x65
    +       created by k8s.io/apimachinery/pkg/watch.NewBroadcaster
    +               /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/mux.go:77 +0x116
    + 
    +       goroutine 5540 [syscall]:
    +       os/signal.signal_recv()
    +               /nvme/gopath/go-1.19/src/runtime/sigqueue.go:152 +0x2f
    +       os/signal.loop()
    +               /nvme/gopath/go-1.19/src/os/signal/signal_unix.go:23 +0x19
    +       created by os/signal.Notify.func1.1
    +               /nvme/gopath/go-1.19/src/os/signal/signal.go:151 +0x2a
    + 
    +       goroutine 5956 [chan receive]:
    +       k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc004eb24b0)
    +               /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/mux.go:268 +0x65
    +       created by k8s.io/apimachinery/pkg/watch.NewLongQueueBroadcaster
    +               /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/mux.go:93 +0x116
    + 
    +       goroutine 5957 [chan receive]:
    +       k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
    +               /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record/event.go:307 +0x73
    +       created by k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher
    +               /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record/event.go:305 +0x13d
    + 
    +       goroutine 5958 [chan receive]:
    +       k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
    +               /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record/event.go:307 +0x73
    +       created by k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher
    +               /nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record/event.go:305 +0x13d
            ... // 1 identical line
            """
      )

diff --git a/test/integration/framework/etcd.go b/test/integration/framework/etcd.go
index 966f6538394..1eaf0f36b2e 100644
--- a/test/integration/framework/etcd.go
+++ b/test/integration/framework/etcd.go
@@ -29,6 +29,7 @@ import (
 	"syscall"
 	"time"
 
+	"github.com/google/go-cmp/cmp"
 	"google.golang.org/grpc/grpclog"
 	"k8s.io/klog/v2"
 
@@ -185,7 +186,7 @@ func EtcdMain(tests func() int) {
 	// Bail out early when -help was given as parameter.
 	flag.Parse()
 
-	before := runtime.NumGoroutine()
+	before, stacktracesBefore := stacks(1 << 16)
 	stop, err := startEtcd()
 	if err != nil {
 		klog.Fatalf("cannot run integration tests: unable to start etcd: %v", err)
@@ -211,14 +212,19 @@ func EtcdMain(tests func() int) {
 	// It generally takes visibly less than 1s to finish all goroutines.
 	// But we keep the limit higher to account for cpu-starved environments.
 	if err := wait.Poll(100*time.Millisecond, 5*time.Second, checkNumberOfGoroutines); err != nil {
-		after := runtime.NumGoroutine()
-		stacktraces := make([]byte, 1<<20)
-		runtime.Stack(stacktraces, true)
-		klog.Fatalf("unexpected number of goroutines: before: %d after %d\n%sd", before, after, string(stacktraces))
+		after, stacktracesAfter := stacks(1 << 20)
+		klog.Fatalf("unexpected number of goroutines: before: %d, after: %d\n%s", before, after, cmp.Diff(stacktracesBefore, stacktracesAfter))
 	}
 	os.Exit(result)
 }
 
+func stacks(bufferSize int) (int, string) {
+	num := runtime.NumGoroutine()
+	stacktraces := make([]byte, bufferSize)
+	len := runtime.Stack(stacktraces, true)
+	return num, string(stacktraces[:len])
+}
+
 // GetEtcdURL returns the URL of the etcd instance started by EtcdMain.
 func GetEtcdURL() string {
 	return etcdURL
```

I'll put that into a PR at some point, either stand-alone or in combination with some other cleanup commits.

**Comment by sanposhiho** [comment]
https://github.com/kubernetes/kubernetes/pull/114843 got merged

Two remaining issues and fixes:
- [ ] goroutine leak: #115423 @pohly 
- [ ] Process did not finish before 1h55m0s timeout, Could not interrupt process after timeout: https://github.com/kubernetes/test-infra/pull/28368

**Comment by kerthcet** [comment]
The goroutine leakage is solved, but I still saw perf-test occasionally failed for time out, instead of increasing the TTL directly, or maybe we can measure the durations for each test and find out the slowest one and maybe the reason, I think this can also help to find some potential performance issues u-turn.

**Comment by sanposhiho** [comment]
> The goroutine leakage is solved

🎉 

----

Seems sometimes timeout-ed and sometimes passes.
For me, it makes sense to increase the TTL given we've got additional performance tests in https://github.com/kubernetes/kubernetes/pull/113615. (Probably my current proposed `3h` in [the PR](https://github.com/kubernetes/test-infra/pull/28368) is too much though.)

**Comment by sanposhiho** [comment]
Another problem.
I believe the [perf-dash](https://perf-dash.k8s.io/#/?jobname=scheduler-perf-benchmark&metriccategoryname=Scheduler&metricname=BenchmarkResults&benchmark=BenchmarkPerfScheduling%2FSchedulingWithNodeInclusionPolicy%2F5000Nodes-8&metricName=time) should show the scheduler's metric result as BenchmarkPerfResults but currently not.

https://github.com/kubernetes/perf-tests/blob/master/perfdash/config.go#L486-L494

**Comment by kerthcet** [comment]
I think we can close this issue, metric is something out of this issue's scope.
