### ISSUE TITLE
Running opnfv/functest-kubernetes-cnf:v1.23 cnf_testsuite failed

### ISSUE THREAD

**Issue by sultetveny** [kubernetes/kubernetes#116295]
### What happened?

Running the below CNNT/OPNFV test failed:

```
podman run -it --env-file ~/opnfv/env \
-v ~/opnfv/ca.pem:/home/opnfv/functest/ca.pem:Z \
-v ~/opnfv/config:/root/.kube/config:Z \
-v ~/opnfv/results:/home/opnfv/functest/results:Z \
-v ~/opnfv/repositories.yml:/home/opnfv/functest/repositories.yml:Z \
-v ~/opnfv/cluster-admin.pem:/home/opnfv/functest/cluster-admin.pem:Z \
-v ~/opnfv/cluster-admin-key.pem:/home/opnfv/functest/cluster-admin-key.pem:Z \
opnfv/functest-kubernetes-cnf:v1.23 /bin/bash

run_tests -t cnf_testsuite
```

Log:
```
2023-03-06 08:51:46,782 - xtesting.ci.run_tests - INFO - Deployment description:

+-------------------------+----------------------------------------------------------+
|         ENV VAR         |                          VALUE                           |
+-------------------------+----------------------------------------------------------+
|         CI_LOOP         |                          daily                           |
|          DEBUG          |                           true                           |
|     DEPLOY_SCENARIO     |                 k8s-nosdn-nofeature-noha                 |
|      INSTALLER_TYPE     |                         unknown                          |
|        BUILD_TAG        |                                                          |
|        NODE_NAME        |                                                          |
|       TEST_DB_URL       |     http://testresults.opnfv.org/test/api/v1/results     |
|     TEST_DB_EXT_URL     |                                                          |
|     S3_ENDPOINT_URL     |                                                          |
|        S3_DST_URL       |                                                          |
|       HTTP_DST_URL      |                                                          |
+-------------------------+----------------------------------------------------------+

2023-03-06 08:51:46,785 - xtesting.ci.run_tests - DEBUG - No env file /var/lib/xtesting/conf/env_file found
2023-03-06 08:51:46,785 - xtesting.ci.run_tests - DEBUG - Test args: cnf_testsuite
2023-03-06 08:51:46,793 - xtesting.ci.run_tests - INFO - Loading test case 'cnf_testsuite'...
2023-03-06 08:51:46,809 - xtesting.ci.run_tests - INFO - Running test case 'cnf_testsuite'...
2023-03-06 08:51:47,143 - functest_kubernetes.cnf_conformance.conformance - INFO - cnf-testsuite setup
Successfully created directories for cnf-testsuite
Global helm found. Version: v3.3.1
Local helm found. Version: v3.3.1
Global kubectl found. Version: 1.23
No Local kubectl version found
Global git found. Version: 2.32.5
No Local git version found
All prerequisites found.
Setup complete

2023-03-06 08:59:10,193 - functest_kubernetes.cnf_conformance.conformance - INFO - cnf-testsuite cnf_setup cnf-config=cnf-testsuite.yml
Successfully created directories for cnf-testsuite
cnf setup online mode
Helm pull error
Successfully setup coredns
cnf setup online mode complete

2023-03-06 09:02:54,568 - functest_kubernetes.cnf_conformance.conformance - ERROR - Can not run CNT Conformance: 
cnf-testsuite workload
✔️  PASSED: hostPath volumes not found 🖥️  💾
State final score: 5 of 10

✔️  PASSED: No privileged containers 🔓🔑
✖️  SKIPPED: Skipping non_root_user: Falco failed to install. Check Kernel Headers are installed on the Host Systems(K8s).
/usr/share/crystal/src/indexable.cr:73:20 in '->'
/workspace/lib/sam/src/sam/task.cr:44:29 in 'call'
/workspace/lib/sam/src/sam/task.cr:44:29 in 'call'
/workspace/lib/sam/src/sam/execution.cr:20:7 in '__crystal_main'
/usr/share/crystal/src/crystal/main.cr:110:5 in 'main'
src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
Index out of bounds

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/xtesting/ci/run_tests.py", line 170, in run_test
    kwargs = run_dict['args']
KeyError: 'args'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/functest_kubernetes/cnf_conformance/conformance.py", line 111, in run
    self.run_conformance(**kwargs)
  File "/usr/lib/python3.9/site-packages/functest_kubernetes/cnf_conformance/conformance.py", line 74, in run_conformance
    output = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cnf-testsuite', 'workload']' returned non-zero exit status 1.
2023-03-06 09:02:54,574 - xtesting.ci.run_tests - INFO - Test result:

+-----------------------+------------------+------------------+----------------+
|       TEST CASE       |     PROJECT      |     DURATION     |     RESULT     |
+-----------------------+------------------+------------------+----------------+
|     cnf_testsuite     |     functest     |      11:07       |      FAIL      |
+-----------------------+------------------+------------------+----------------+

2023-03-06 09:02:54,633 - functest_kubernetes.cnf_conformance.conformance - INFO - cnf-testsuite uninstall_cri_tools cnf-config=cnf-testsuite.yml

2023-03-06 09:02:55,001 - functest_kubernetes.cnf_conformance.conformance - INFO - cnf-testsuite uninstall_falco cnf-config=cnf-testsuite.yml

2023-03-06 09:02:55,405 - functest_kubernetes.cnf_conformance.conformance - INFO - cnf-testsuite cnf_cleanup cnf-config=cnf-testsuite.yml
Successfully cleaned up coredns

2023-03-06 09:02:55,405 - xtesting.ci.run_tests - ERROR - The test case 'cnf_testsuite' failed.
2023-03-06 09:02:55,405 - xtesting.ci.run_tests - INFO - Execution exit value: Result.EX_ERROR
```

### What did you expect to happen?

The test case should executed successfully.

### How can we reproduce it (as minimally and precisely as possible)?

See above.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.15", GitCommit:"b84cb8ab29366daa1bba65bc67f54de2f6c34848", GitTreeState:"clean", BuildDate:"2022-12-08T10:49:13Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.15", GitCommit:"b84cb8ab29366daa1bba65bc67f54de2f6c34848", GitTreeState:"clean", BuildDate:"2022-12-08T10:42:57Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
Openstack
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.6 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.6 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

$ uname -a
Linux cbis-sut1-control-01 4.18.0-372.9.1.el8.x86_64 #1 SMP Tue May 10 14:48:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
should this issue be filed against https://github.com/opnfv/functest-kubernetes instead?

**Comment by BenTheElder** [comment]
Yeah, this is clearly not from Kubernetes / SIG Testing.
