### ISSUE TITLE
Failure cluster [466744fd...] TestCreateDiskFailDescribeVolume timeout on waiting until volume available

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#116206]
### Failure cluster [466744fd00eb9fa7e2a1](https://go.k8s.io/triage#466744fd00eb9fa7e2a1)
The test started to fail after Feb 17th. 

TestCreateDiskFailDescribeVolume  is in https://github.com/kubernetes/cloud-provider-aws/blob/d0551093673e8c355db17249b8f069767c014748/pkg/providers/v1/aws_test.go#L2538

##### Error text:
```
Failed
=== RUN   TestCreateDiskFailDescribeVolume
I0216 21:19:48.718102  113998 aws.go:1308] Building AWS cloudprovider
I0216 21:19:48.718130  113998 aws.go:1268] Zone not specified in configuration file; querying AWS metadata service
I0216 21:19:48.718290  113998 tags.go:80] AWS cloud filtering on ClusterID: clusterid.test
panic: test timed out after 10m0s
running tests:
	TestCreateDiskFailDescribeVolume (24s)

goroutine 1069 [running]:
testing.(*M).startAlarm.func1()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.1.linux.amd64/src/testing/testing.go:2241 +0x219
created by time.goFunc
	/home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.1.linux.amd64/src/time/sleep.go:176 +0x48

goroutine 1 [chan receive]:
testing.(*T).Run(0xc00002d380, {0x3266e73, 0x20}, 0x33462d0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.1.linux.amd64/src/testing/testing.go:1630 +0x82e
testing.runTests.func1(0x0?)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.1.linux.amd64/src/testing/testing.go:2036 +0x8e
testing.tRunner(0xc00002d380, 0xc000695b48)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.1.linux.amd64/src/testing/testing.go:1576 +0x217
testing.runTests(0xc0006800a0?, {0x57a7400, 0x45, 0x45}, {0xd0?, 0x301ca60?, 0x57b8de0?})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.1.linux.amd64/src/testing/testing.go:2034 +0x87d
testing.(*M).Run(0xc
```
#### Recent failures:
[2023/3/1 04:17:54 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1630663033158111232)
[2023/2/28 22:17:50 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1630572435256381440)
[2023/2/28 16:17:43 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1630481837178490880)
[2023/2/28 10:17:52 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1630391238869913600)
[2023/2/28 04:19:29 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1630300640649416704)

/kind failing-test

/sig storage
/area provider/aws

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/legacy-cloud-providers/aws has no update for a long time.

**Comment by pacoxu** [comment]
`ci-kubernetes-generate-make-test-count10` is commented on due to continuously failing in https://github.com/kubernetes/test-infra/pull/28869.

**Comment by torredil** [comment]
[TestCreateDiskFailDescribeVolume](https://github.com/kubernetes/kubernetes/pull/99664) is referencing the legacy cloud provider package, which was removed Feb 16: https://github.com/kubernetes/kubernetes/pull/115838.

```
TestCreateDiskFailDescribeVolume
ci-kubernetes-generate-make-test-count10 | k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/aws 
```

---

Taking a closer look at the aggregated failures dashboard, we can see that this test has been consistently failing long before Feb 17, right up until we stopped running it in https://github.com/kubernetes/test-infra/pull/28869.

The test runs through the scenario where a volume is created but remains in the "creating" state, meaning it doesn't become "available" within the expected time.

Let's do some code tracing:
[TestCreateDiskFailDescribeVolume](https://github.com/kubernetes/cloud-provider-aws/blob/d0551093673e8c355db17249b8f069767c014748/pkg/providers/v1/aws_test.go#L2538C6-L2538C38) -> [CreateDisk](CreateDisk) -> [waitUntilVolumeAvailable](https://github.com/kubernetes/cloud-provider-aws/blob/d0551093673e8c355db17249b8f069767c014748/pkg/providers/v1/aws.go#L2652) -> [wait.ExponentialBackoff](https://github.com/kubernetes/cloud-provider-aws/blob/d0551093673e8c355db17249b8f069767c014748/pkg/providers/v1/aws.go#L2694)

```
go test -run TestCreateDiskFailDescribeVolume
I0728 05:25:31.050240   31777 aws.go:1272] Building AWS cloudprovider
I0728 05:25:31.050297   31777 aws.go:1232] Zone not specified in configuration file; querying AWS metadata service
I0728 05:25:31.050340   31777 tags.go:79] AWS cloud filtering on ClusterID: clusterid.test
Starting exponential backoff...
[2023-07-28 05:25:36.051652565 +0000 UTC m=+5.013282506] Volume aws://us-east-1a/vol-volumeId0 state: creating
[2023-07-28 05:25:41.052784771 +0000 UTC m=+10.014414768] Volume aws://us-east-1a/vol-volumeId0 state: creating
[2023-07-28 05:25:47.053846229 +0000 UTC m=+16.015476420] Volume aws://us-east-1a/vol-volumeId0 state: creating
[2023-07-28 05:25:54.255208845 +0000 UTC m=+23.216838860] Volume aws://us-east-1a/vol-volumeId0 state: creating
[2023-07-28 05:26:02.895435408 +0000 UTC m=+31.857065415] Volume aws://us-east-1a/vol-volumeId0 state: creating
[2023-07-28 05:26:13.265753734 +0000 UTC m=+42.227383745] Volume aws://us-east-1a/vol-volumeId0 state: creating
[2023-07-28 05:26:25.711320597 +0000 UTC m=+54.672950538] Volume aws://us-east-1a/vol-volumeId0 state: creating
[2023-07-28 05:26:40.645325778 +0000 UTC m=+69.606955785] Volume aws://us-east-1a/vol-volumeId0 state: creating
[2023-07-28 05:26:58.563478475 +0000 UTC m=+87.525108599] Volume aws://us-east-1a/vol-volumeId0 state: creating
[2023-07-28 05:27:20.066411751 +0000 UTC m=+109.028041766] Volume aws://us-east-1a/vol-volumeId0 state: creating
Ended exponential backoff.
waitUntilVolumeAvailable took: 109.016 seconds
I0728 05:27:20.066570   31777 aws.go:2622] Failed to create the volume aws://us-east-1a/vol-volumeId0 due to timed out waiting for the condition. Will try to delete it.
PASS
ok      k8s.io/legacy-cloud-providers/aws       109.032s
```

When waiting for the volume state to transition, we sleep for 5 seconds and hit the exponential backoff loop for the full duration (10 steps). When we compute the total delay from the exponential backoff it sums up to 104 seconds. Adding the initial 5-second sleep, we get 109 seconds -- which is exactly how long it takes to run this test every time.

---
`make test` timeout for `ci-kubernetes-generate-make-test-count10` is set to 600s and runs 10 times, thus this test is basically guaranteed to always fail. From my understanding, in master we don't set a timeout and since the test eventually succeeds after 109 seconds it slipped under the radar.

cc: @dims @xing-yang

**Comment by xing-yang** [comment]
@pacoxu Can this issue be closed now?
cc @msau42 @jsafrane
