### ISSUE TITLE
Segmentation violation with k8s.io/client-go v0.26.1 and a 1.27.1 cluster (incompatibility)

### ISSUE THREAD

**Issue by scrayos** [kubernetes/kubernetes#117466]
### What happened?

After updating to Kubernetes 1.27.1 some containers using `k8s.io/api v0.26.1` are crashing because of SIGSEGV (Segmentation Violation) and they can no longer communicate with the cluster. Originally, this also occurred with my local kubectl installation of version 1.26.3, but now it seems to be working again.

Everything seemed to work fine until I updated the very last node in the cluster from 1.26.3 to 1.27.1. So the first 5 nodes had no problems, even with the containers that are now failing.

### What did you expect to happen?

I expect the containers to work just as they were before, as this version difference should be covered by the [Kubernetes version skew policy](https://kubernetes.io/releases/version-skew-policy/). So no segmentation violation should happen and the API access should be compatible.

### How can we reproduce it (as minimally and precisely as possible)?

1. Deploy a Kubernetes cluster in version 1.27.1
2. Install rook-ceph (v1.11.3) and rook-ceph-cluster (v1.11.3) with Helm
3. Check the logs for rook-ceph-operator and witness that it is failing with a segmentation violation. 

### Anything else we need to know?

<details>

rook-ceph-operator (rook-ceph-operator):
```console
2023-04-19 11:08:22.491914 I | rookcmd: starting Rook v1.11.3 with arguments '/usr/local/bin/rook ceph operator'
2023-04-19 11:08:22.491976 I | rookcmd: flag values: --enable-machine-disruption-budget=false, --help=false, --kubeconfig=, --log-level=INFO, --operator-image=, --service-account=
2023-04-19 11:08:22.491979 I | cephcmd: starting Rook-Ceph operator
2023-04-19 11:08:22.706361 I | cephcmd: base ceph version inside the rook operator image is "ceph version 17.2.5 (98318ae89f1a893a6ded3a640405cdbb33e08757) quincy (stable)"
2023-04-19 11:08:22.813675 I | op-k8sutil: ROOK_CURRENT_NAMESPACE_ONLY="false" (env var)
2023-04-19 11:08:22.813690 I | operator: watching all namespaces for Ceph CRs
2023-04-19 11:08:22.813755 I | operator: setting up schemes
2023-04-19 11:08:22.815942 I | operator: setting up the controller-runtime manager
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12edd10]

goroutine 81 [running]:
k8s.io/client-go/discovery.convertAPIResource(...)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/aggregated_discovery.go:88
k8s.io/client-go/discovery.convertAPIGroup({{{0x0, 0x0}, {0x0, 0x0}}, {{0xc000625068, 0x15}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/aggregated_discovery.go:69 +0x5f0
k8s.io/client-go/discovery.SplitGroupsAndResources({{{0xc000624018, 0x15}, {0xc00015e260, 0x1b}}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/aggregated_discovery.go:35 +0x2f8
k8s.io/client-go/discovery.(*DiscoveryClient).downloadAPIs(0x25fea6c?)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/discovery_client.go:310 +0x47c
k8s.io/client-go/discovery.(*DiscoveryClient).GroupsAndMaybeResources(0xc0001285a0?)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/discovery_client.go:198 +0x5c
k8s.io/client-go/discovery.ServerGroupsAndResources({0x26299d0, 0xc000904ff0})
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/discovery_client.go:392 +0x59
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources.func1()
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/discovery_client.go:356 +0x25
k8s.io/client-go/discovery.withRetries(0x2, 0xc0005a50d0)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/discovery_client.go:621 +0x72
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources(0x0?)
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.26.1/discovery/discovery_client.go:355 +0x3a
k8s.io/client-go/restmapper.GetAPIGroupResources({0x26299d0?, 0xc000904ff0?})
	/home/runner/go/pkg/mod/k8s.io/client-go@v0.26.1/restmapper/discovery.go:148 +0x42
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper.func1()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/client/apiutil/dynamicrestmapper.go:86 +0x25
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).setStaticMapper(...)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/client/apiutil/dynamicrestmapper.go:119
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper(0xc0008eecf0?, {0x0, 0x0, 0x9335f667369e3001?})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/client/apiutil/dynamicrestmapper.go:99 +0x176
sigs.k8s.io/controller-runtime/pkg/cluster.setOptionsDefaults.func1(0xc0004f9030?)
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/cluster/cluster.go:217 +0x25
sigs.k8s.io/controller-runtime/pkg/cluster.New(0xc000888d80, {0xc000999a58, 0x1, 0x0?})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/cluster/cluster.go:159 +0x18d
sigs.k8s.io/controller-runtime/pkg/manager.New(_, {0xc0004f9030, 0x0, 0x0, {{0x2623510, 0xc0001234c0}, 0x0}, 0x0, {0x0, 0x0}, ...})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/manager/manager.go:351 +0xf9
github.com/rook/rook/pkg/operator/ceph.(*Operator).startCRDManager(0xc000591260, {0x261fbc0?, 0xc000123f00}, 0xc0000c6c60?)
	/home/runner/work/rook/rook/pkg/operator/ceph/cr_manager.go:164 +0x275
created by github.com/rook/rook/pkg/operator/ceph.(*Operator).runCRDManager
	/home/runner/work/rook/rook/pkg/operator/ceph/operator.go:141 +0x185
```

csi-rbdplugin-provisioner (csi-omap-generator):
```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12c9170]

goroutine 1 [running]:
k8s.io/client-go/discovery.convertAPIResource(...)
	/go/src/github.com/ceph/ceph-csi/vendor/k8s.io/client-go/discovery/aggregated_discovery.go:88
k8s.io/client-go/discovery.convertAPIGroup({{{0x0, 0x0}, {0x0, 0x0}}, {{0xc0004a7128, 0x15}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
	/go/src/github.com/ceph/ceph-csi/vendor/k8s.io/client-go/discovery/aggregated_discovery.go:69 +0x5f0
k8s.io/client-go/discovery.SplitGroupsAndResources({{{0xc0004a64f8, 0x15}, {0xc000504080, 0x1b}}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
	/go/src/github.com/ceph/ceph-csi/vendor/k8s.io/client-go/discovery/aggregated_discovery.go:35 +0x2f8
k8s.io/client-go/discovery.(*DiscoveryClient).downloadAPIs(0x2036cf1?)
	/go/src/github.com/ceph/ceph-csi/vendor/k8s.io/client-go/discovery/discovery_client.go:310 +0x47c
k8s.io/client-go/discovery.(*DiscoveryClient).GroupsAndMaybeResources(0xc00031e280?)
	/go/src/github.com/ceph/ceph-csi/vendor/k8s.io/client-go/discovery/discovery_client.go:198 +0x5c
k8s.io/client-go/discovery.ServerGroupsAndResources({0x2527b98, 0xc000b83260})
	/go/src/github.com/ceph/ceph-csi/vendor/k8s.io/client-go/discovery/discovery_client.go:392 +0x59
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources.func1()
	/go/src/github.com/ceph/ceph-csi/vendor/k8s.io/client-go/discovery/discovery_client.go:356 +0x25
k8s.io/client-go/discovery.withRetries(0x2, 0xc0005a5040)
	/go/src/github.com/ceph/ceph-csi/vendor/k8s.io/client-go/discovery/discovery_client.go:621 +0x72
k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroupsAndResources(0x0?)
	/go/src/github.com/ceph/ceph-csi/vendor/k8s.io/client-go/discovery/discovery_client.go:355 +0x3a
k8s.io/client-go/restmapper.GetAPIGroupResources({0x2527b98?, 0xc000b83260?})
	/go/src/github.com/ceph/ceph-csi/vendor/k8s.io/client-go/restmapper/discovery.go:148 +0x42
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper.func1()
	/go/src/github.com/ceph/ceph-csi/vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go:94 +0x25
sigs.k8s.io/controller-runtime/pkg/client/apiutil.(*dynamicRESTMapper).setStaticMapper(...)
	/go/src/github.com/ceph/ceph-csi/vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go:130
sigs.k8s.io/controller-runtime/pkg/client/apiutil.NewDynamicRESTMapper(0xc000c2e510?, {0x0, 0x0, 0x9335f667369e3001?})
	/go/src/github.com/ceph/ceph-csi/vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go:110 +0x182
sigs.k8s.io/controller-runtime/pkg/cluster.setOptionsDefaults.func1(0x0?)
	/go/src/github.com/ceph/ceph-csi/vendor/sigs.k8s.io/controller-runtime/pkg/cluster/cluster.go:217 +0x25
sigs.k8s.io/controller-runtime/pkg/cluster.New(0xc0006ae6c0, {0xc000c9f9e8, 0x1, 0x0?})
	/go/src/github.com/ceph/ceph-csi/vendor/sigs.k8s.io/controller-runtime/pkg/cluster/cluster.go:159 +0x18d
sigs.k8s.io/controller-runtime/pkg/manager.New(_, {0x0, 0x0, 0x0, {{0x2522498, 0xc0004b6740}, 0x0}, 0x1, {0x203a454, 0x6}, ...})
	/go/src/github.com/ceph/ceph-csi/vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go:359 +0xf9
github.com/ceph/ceph-csi/internal/controller.Start({{0x7ffd3dbaa122, 0x1a}, {0x7ffd3dbaa105, 0x9}, {0x0, 0x0}, 0x0})
	/go/src/github.com/ceph/ceph-csi/internal/controller/controller.go:70 +0x139
main.main()
	/go/src/github.com/ceph/ceph-csi/cmd/cephcsi.go:276 +0x971
```

`kubectl get pods` (does not occur anymore):
```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55c08ab1d5b0]

goroutine 1 [running]:
k8s.io/client-go/discovery.convertAPIResource(...)
    vendor/k8s.io/client-go/discovery/aggregated_discovery.go:114
k8s.io/client-go/discovery.convertAPIGroup({{{0x0, 0x0}, {0x0, 0x0}}, {{0xc0002a7200, 0x15}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
    vendor/k8s.io/client-go/discovery/aggregated_discovery.go:95 +0x7d0
k8s.io/client-go/discovery.SplitGroupsAndResources({{{0xc0002a6000, 0x15}, {0xc00063a160, 0x1b}}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
    vendor/k8s.io/client-go/discovery/aggregated_discovery.go:49 +0x318
k8s.io/client-go/discovery.(*DiscoveryClient).downloadAPIs(0xd4998570fe3a39d8?)
    vendor/k8s.io/client-go/discovery/discovery_client.go:328 +0x3de
k8s.io/client-go/discovery.(*DiscoveryClient).GroupsAndMaybeResources(0xffffffffffffffff?)
    vendor/k8s.io/client-go/discovery/discovery_client.go:203 +0x65
k8s.io/client-go/discovery/cached/memory.(*memCacheClient).refreshLocked(0xc000128ae0)
    vendor/k8s.io/client-go/discovery/cached/memory/memcache.go:245 +0x57
k8s.io/client-go/discovery/cached/memory.(*memCacheClient).GroupsAndMaybeResources(0xc000128ae0)
    vendor/k8s.io/client-go/discovery/cached/memory/memcache.go:144 +0xcf
k8s.io/client-go/discovery/cached/memory.(*memCacheClient).ServerGroups(0xc0000d3720?)
    vendor/k8s.io/client-go/discovery/cached/memory/memcache.go:170 +0x19
k8s.io/client-go/discovery/cached/disk.(*CachedDiscoveryClient).ServerGroups(0xc0000d3720)
    vendor/k8s.io/client-go/discovery/cached/disk/cached_discovery.go:118 +0x172
k8s.io/client-go/discovery.ServerGroupsAndResources({0x55c08bb71b70, 0xc0000d3720})
    vendor/k8s.io/client-go/discovery/discovery_client.go:418 +0xca
k8s.io/client-go/discovery/cached/disk.(*CachedDiscoveryClient).ServerGroupsAndResources(0x0?)
    vendor/k8s.io/client-go/discovery/cached/disk/cached_discovery.go:101 +0x25
k8s.io/client-go/restmapper.discoveryCategoryExpander.Expand({{0x55c08bb71b70?, 0xc0000d3720?}}, {0x7ffc3473bff6, 0x4})
    vendor/k8s.io/client-go/restmapper/category_expansion.go:61 +0x52
k8s.io/cli-runtime/pkg/resource.(*Builder).ReplaceAliases(0xc0004dd4a0, {0x7ffc3473bff6?, 0xc000601000?})
    vendor/k8s.io/cli-runtime/pkg/resource/builder.go:645 +0x20a
k8s.io/cli-runtime/pkg/resource.(*Builder).ResourceTypeOrNameArgs(0xc0004dd4a0, 0x1, {0xc0001d7c30?, 0x55c08b1bc208?, 0xc000d97c30?})
    vendor/k8s.io/cli-runtime/pkg/resource/builder.go:609 +0x185
k8s.io/kubectl/pkg/cmd/get.(*GetOptions).Run(0xc000144480, {0x55c08bb74280?, 0xc0001650c0?}, 0xc00046c600?, {0xc0001d7c30, 0x1, 0x1})
    vendor/k8s.io/kubectl/pkg/cmd/get/get.go:485 +0x216
k8s.io/kubectl/pkg/cmd/get.NewCmdGet.func1(0xc00046c600?, {0xc0001d7c30, 0x1, 0x1})
    vendor/k8s.io/kubectl/pkg/cmd/get/get.go:173 +0xb2
github.com/spf13/cobra.(*Command).execute(0xc00046c600, {0xc0001d7b30, 0x1, 0x1})
    vendor/github.com/spf13/cobra/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc00046c000)
    vendor/github.com/spf13/cobra/command.go:1040 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
    vendor/github.com/spf13/cobra/command.go:968
k8s.io/component-base/cli.run(0xc00046c000)
    vendor/k8s.io/component-base/cli/run.go:146 +0x317
k8s.io/component-base/cli.RunNoErrOutput(...)
    vendor/k8s.io/component-base/cli/run.go:84
main.main()
    cmd/kubectl/kubectl.go:30 +0x1e
```

</details>

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"archive", BuildDate:"2023-03-19T19:47:22Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:14:42Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Hetzner Cloud (Controlplane) + Hetzner Dedicated/Bare Metal (Worker)
</details>

### OS version

<details>

```console
$ cat /etc/os-release
Talos (v1.4.0)
$ uname -a
6.1.24-talos
```

</details>

### Install tools

<details>
Installed and Bootstrapped according to the official Talos Linux instructions
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd: v1.6.20
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Cilium v1.11.8
Rook v1.11.3
Ceph v17.2.5
</details>

**Comment by neolit123** [comment]
> Check the logs for rook-ceph-operator and witness that it is failing with a segmentation violation.

that sounds like a rook / ceph problem.
please contact its maintainers for freeback first.

if they confirm it's a k8s bug please provide more details.

/triage needs-information

**Comment by dims** [comment]
@scrayos can you quickly try `kubectl` built with 1.26.4 kubernetes tag? that would be useful information to pass along to the rook/ceph team (if #116666 is indeed a patch that fixes it!)
