### ISSUE TITLE
Kube controller manager throws nil pointer dereference while tainting a node unreachable

### ISSUE THREAD

**Issue by ashvinsharma** [kubernetes/kubernetes#117555]
### What happened?

KCM tries to taint a newly provisioned node 

```
I0423 18:37:30.629784       1 node_lifecycle_controller.go:1082] Condition Ready of node ip-10-5-43-93.ap-south-1.compute.internal was never updated by kubelet
I0423 18:37:30.629819       1 node_lifecycle_controller.go:1082] Condition MemoryPressure of node ip-10-5-43-93.ap-south-1.compute.internal was never updated by kubelet
I0423 18:37:30.629825       1 node_lifecycle_controller.go:1082] Condition DiskPressure of node ip-10-5-43-93.ap-south-1.compute.internal was never updated by kubelet
I0423 18:37:30.629830       1 node_lifecycle_controller.go:1082] Condition PIDPressure of node ip-10-5-43-93.ap-south-1.compute.internal was never updated by kubelet
I0423 18:37:30.647620       1 node_lifecycle_controller.go:882] Node ip-10-5-43-93.ap-south-1.compute.internal is unresponsive as of 2023-04-23 18:37:30.647604493 +0000 UTC m=+271180.572213061. Adding it to the Taint queue.
E0423 18:37:30.649331       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 288383 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x40db4e0, 0x72e9910)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x40db4e0, 0x72e9910)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
k8s.io/kubernetes/pkg/controller/nodelifecycle.(*Controller).doNoExecuteTaintingPass.func1(0xc02a81d320, 0x29, 0x3dad060, 0xc030999230, 0xc1097c9aa699b3c1, 0xf6a325ad49f9, 0x7325a80, 0xc1097c9aa699b3c1, 0xf6a325ad49f9, 0x7325a80, ...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/nodelifecycle/node_lifecycle_controller.go:685 +0x2e3
k8s.io/kubernetes/pkg/controller/nodelifecycle/scheduler.(*RateLimitedTimedQueue).Try(0xc01e77ee40, 0xc00817cdd8)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/nodelifecycle/scheduler/rate_limited_queue.go:249 +0x255
k8s.io/kubernetes/pkg/controller/nodelifecycle.(*Controller).doNoExecuteTaintingPass(0xc002249080)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/nodelifecycle/node_lifecycle_controller.go:671 +0x13a
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc01e782900)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc01e782900, 0x5026f00, 0xc01e4b4c90, 0x6572206120657401, 0xc000a89320)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc01e782900, 0x5f5e100, 0x0, 0x666f206567617401, 0xc000a89320)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc01e782900, 0x5f5e100, 0xc000a89320)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/pkg/controller/nodelifecycle.(*Controller).Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/nodelifecycle/node_lifecycle_controller.go:570 +0x3f3
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x29a3983]

goroutine 288383 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x109
panic(0x40db4e0, 0x72e9910)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
k8s.io/kubernetes/pkg/controller/nodelifecycle.(*Controller).doNoExecuteTaintingPass.func1(0xc02a81d320, 0x29, 0x3dad060, 0xc030999230, 0xc1097c9aa699b3c1, 0xf6a325ad49f9, 0x7325a80, 0xc1097c9aa699b3c1, 0xf6a325ad49f9, 0x7325a80, ...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/nodelifecycle/node_lifecycle_controller.go:685 +0x2e3
k8s.io/kubernetes/pkg/controller/nodelifecycle/scheduler.(*RateLimitedTimedQueue).Try(0xc01e77ee40, 0xc032a83dd8)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/nodelifecycle/scheduler/rate_limited_queue.go:249 +0x255
k8s.io/kubernetes/pkg/controller/nodelifecycle.(*Controller).doNoExecuteTaintingPass(0xc002249080)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/nodelifecycle/node_lifecycle_controller.go:671 +0x13a
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc01e782900)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc01e782900, 0x5026f00, 0xc01e4b4c90, 0x6572206120657401, 0xc000a89320)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc01e782900, 0x5f5e100, 0x0, 0x666f206567617401, 0xc000a89320)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc01e782900, 0x5f5e100, 0xc000a89320)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/pkg/controller/nodelifecycle.(*Controller).Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/nodelifecycle/node_lifecycle_controller.go:570 +0x3f3
```

### What did you expect to happen?

KCM does not try to taint the node

### How can we reproduce it (as minimally and precisely as possible)?

- Create a new node with condition="Ready" and  status="unknown" (usually happens when provisioned using Karpenter). 
- Wait for KCM to process the node. 

### Anything else we need to know?

- The node is provisioned using Karpenter.
- kube-controller-manager version: v1.21.14

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.27.1
Kustomize Version: v5.0.1
Server Version: v1.21.14
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
Containerd version 1.5.13
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ashvinsharma** [comment]
I believe using the (currently ignored) integer return value can help mitigate this issue 
https://github.com/kubernetes/kubernetes/blob/0f77da5bd4809927e15d1658fb4aa8f13ad890a5/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L681

**Comment by iyear** [comment]
Could we just return false, TIME if condition==nil to retry to get nodes?

**Comment by ashvinsharma** [comment]
Is there an update on this?
