### ISSUE TITLE
Build on linux/arm64 using make

### ISSUE THREAD

**Issue by timofurrer** [kubernetes/kubernetes#117701]
### What happened?

I'm trying to build kubernetes on a `linux/arm64` machine that is virtualized using [UTM](https://mac.getutm.app/) on a M1 macOS.

The problem is that right after a `git clone` the build using `make` fails with:

```
make all
+++ [0501 12:11:19] Setting GOMAXPROCS: 8
+++ [0501 12:12:47] Building go targets for linux/arm64
    k8s.io/kubernetes/cmd/kube-proxy (static)
    k8s.io/kubernetes/cmd/kube-apiserver (static)
    k8s.io/kubernetes/cmd/kube-controller-manager (static)
    k8s.io/kubernetes/cmd/kubelet (non-static)
    k8s.io/kubernetes/cmd/kubeadm (static)
    k8s.io/kubernetes/cmd/kube-scheduler (static)
    k8s.io/component-base/logs/kube-log-runner (static)
    k8s.io/kube-aggregator (static)
    k8s.io/apiextensions-apiserver (static)
    k8s.io/kubernetes/cluster/gce/gci/mounter (non-static)
    k8s.io/kubernetes/cmd/kubectl (static)
    k8s.io/kubernetes/cmd/kubectl-convert (static)
    github.com/onsi/ginkgo/v2/ginkgo (non-static)
    k8s.io/kubernetes/test/e2e/e2e.test (test)
    k8s.io/kubernetes/test/conformance/image/go-runner (non-static)
    k8s.io/kubernetes/cmd/kubemark (static)
    github.com/onsi/ginkgo/v2/ginkgo (non-static)
    k8s.io/kubernetes/test/e2e_node/e2e_node.test (test)
# k8s.io/kubernetes/cmd/kube-controller-manager
google.golang.org/api/compute/v0%2ealpha.(*InstancesSetShieldedInstanceIntegrityPolicyCall).Do: phase error: addr=0x191d310 value+size=0x191d050
# k8s.io/kubernetes/cmd/kube-apiserver
panic: runtime error: slice bounds out of range [::5197319140] with capacity 48312998

goroutine 37 [running]:
cmd/internal/goobj.(*Reader).BytesAt(...)
	/usr/local/go/src/cmd/internal/goobj/objfile.go:618
cmd/internal/goobj.(*Reader).Data(0x0?, 0x0?)
	/usr/local/go/src/cmd/internal/goobj/objfile.go:849 +0xe0
cmd/link/internal/loader.(*Loader).Data(0x233700?, 0x4000616390?)
	/usr/local/go/src/cmd/link/internal/loader/loader.go:1228 +0xac
cmd/link/internal/ld.(*OutBuf).WriteSym(0x4001f18380, 0x400061a000, 0xc2151?)
	/usr/local/go/src/cmd/link/internal/ld/outbuf.go:311 +0x104
cmd/link/internal/ld.writeBlock(0x40000f0000, 0x0?, 0x400061a000, {0x40066d32d0, 0xf6c7, 0x0?}, 0x0?, 0x162a70?, {0x4725e0, 0x200, ...})
	/usr/local/go/src/cmd/link/internal/ld/data.go:1066 +0x2b4
cmd/link/internal/ld.writeBlocks.func1(0x0?, 0x40000f0000?, {0x40066d32d0?, 0x400d1df410?, 0x2?}, 0x2?, 0x27?, {0x4725e0?, 0x400d1df460?, 0x4001245400?})
	/usr/local/go/src/cmd/link/internal/ld/data.go:1023 +0x64
created by cmd/link/internal/ld.writeBlocks
	/usr/local/go/src/cmd/link/internal/ld/data.go:1022 +0x4dc
# k8s.io/kubernetes/cmd/kubemark
google.golang.org/api/compute/v0%2ealpha.(*LicensesListCall).Pages.func1: phase error: addr=0x1d1c750 value+size=0x1d1c6d0
!!! [0501 12:19:32] Call tree:
!!! [0501 12:19:32]  1: /home/timo/work/kubernetes-shared/kubernetes/hack/lib/golang.sh:771 kube::golang::build_some_binaries(...)
!!! [0501 12:19:32]  2: /home/timo/work/kubernetes-shared/kubernetes/hack/lib/golang.sh:941 kube::golang::build_binaries_for_platform(...)
!!! [0501 12:19:32]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0501 12:19:32] Call tree:
!!! [0501 12:19:32]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0501 12:19:32] Call tree:
!!! [0501 12:19:32]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make: *** [Makefile:92: all] Error 1
```

### What did you expect to happen?

It builds successfully

### How can we reproduce it (as minimally and precisely as possible)?

- Run Ubuntu 22.04 with UTM on an M1
- git clone kubernetes
- make

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux k8sdev 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:08 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
`go env` please

**Comment by timofurrer** [comment]
@dims here you go:

```
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/home/timo/.cache/go-build"
GOENV="/home/timo/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/timo/.asdf/installs/golang/1.20.3/packages/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/timo/.asdf/installs/golang/1.20.3/packages"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/timo/.asdf/installs/golang/1.20.3/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/timo/.asdf/installs/golang/1.20.3/go/pkg/tool/linux_arm64"
GOVCS=""
GOVERSION="go1.20.3"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/timo/work/kubernetes-shared/kubernetes/go.mod"
GOWORK=""
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2155705529=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by timofurrer** [comment]
Okay, I've changed the kubernetes clone directory to `$GOPATH/src/k8s.io` which seemed to have solved it.

Is that the only possible location for the k8s src?

**Comment by dims** [comment]
@timofurrer yes for now.

we've documented it here: https://github.com/kubernetes/community/blob/master/contributors/devel/development.md#a-quick-start-for-testing-kubernetes

/close
