### ISSUE TITLE
apiserver InstallAPIGroups slices out of range

### ISSUE THREAD

**Issue by Icarus9913** [kubernetes/kubernetes#118094]
### What happened?

I met a panic in apiserver package when I create an aggregated API.

```text
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
k8s.io/apiserver/pkg/server.(*GenericAPIServer).InstallAPIGroups(0xc000005200, {0xc000950a38, 0x1, 0x1})
	/src/vendor/k8s.io/apiserver/pkg/server/genericapiserver.go:764 +0x13c5
k8s.io/apiserver/pkg/server.(*GenericAPIServer).InstallAPIGroup(0xc000005200, 0xc0007adc20)
	/src/vendor/k8s.io/apiserver/pkg/server/genericapiserver.go:816 +0xeb
```

### What did you expect to happen?

not panic

### How can we reproduce it (as minimally and precisely as possible)?

Do not call `SetVersionPriority`

### Kubernetes version

<details>

```console
$ kubectl version
main branch
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Icarus9913** [comment]
Reference PR to fix: https://github.com/kubernetes/kubernetes/issues/118094
