### ISSUE TITLE
Aftere upgrade kuberentes version v1.20.15 to v1.21.15 not comming up the controller manager

### ISSUE THREAD

**Issue by vadlakiran** [kubernetes/kubernetes#118139]
### What happened?

we have  upgradede version  v1.20.15 to v1.21.14 when i am doing this pods are not coming up and contrroller is in crashloopbackup status, what might be the reason, why its went down ?

```
I0519 17:45:53.214908       1 controllermanager.go:574] Started "resourcequota"                                                                                                               
I0519 17:45:53.215260       1 resource_quota_controller.go:273] Starting resource quota controller                                                                                            
I0519 17:45:53.215278       1 shared_informer.go:240] Waiting for caches to sync for resource quota                                                                                           
I0519 17:45:53.215318       1 resource_quota_monitor.go:304] QuotaMonitor running                                                                                                             
I0519 17:45:53.249211       1 controllermanager.go:574] Started "serviceaccount"                                                                                                              
I0519 17:45:53.249313       1 serviceaccounts_controller.go:117] Starting service account controller                                                                                          
I0519 17:45:53.249321       1 shared_informer.go:240] Waiting for caches to sync for service account                                                                                          
I0519 17:45:53.297909       1 controllermanager.go:574] Started "statefulset"                                                                                                                 
I0519 17:45:53.297944       1 stateful_set.go:146] Starting stateful set controller                                                                                                           
I0519 17:45:53.297960       1 shared_informer.go:240] Waiting for caches to sync for stateful set                                                                                             
I0519 17:45:53.348233       1 controllermanager.go:574] Started "daemonset"                                                                                                                   
I0519 17:45:53.348290       1 daemon_controller.go:285] Starting daemon sets controller                                                                                                       
I0519 17:45:53.348298       1 shared_informer.go:240] Waiting for caches to sync for daemon sets                                                                                              
I0519 17:45:53.448085       1 controllermanager.go:574] Started "disruption"                                                                                                                  
I0519 17:45:53.448174       1 disruption.go:363] Starting disruption controller                                                                                                               
I0519 17:45:53.448183       1 shared_informer.go:240] Waiting for caches to sync for disruption                                                                                               
I0519 17:45:53.497302       1 node_ipam_controller.go:91] Sending events to api server.                                                                                                       
I0519 17:46:03.511279       1 range_allocator.go:82] Sending events to api server.                                                                                                            
I0519 17:46:03.511454       1 range_allocator.go:116] No Secondary Service CIDR provided. Skipping filtering out secondary service addresses.                                                 
E0519 17:46:03.511505       1 controllermanager.go:562] Error starting "nodeipam"                                                                                                             
F0519 17:46:03.511517       1 controllermanager.go:223] error starting controllers: failed to mark cidr[10.244.4.0/24] at idx [0] as occupied for node: vq9bcordv05-23: cidr 10.244.4.0/24 is 
out the range of cluster cidr 10.244.0.0/22                                                                                                                                                   
goroutine 167 [running]:                                                                                                                                                                      
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00000e001, 0xc0016e5200, 0xea, 0x1e8)                                                                                                       
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9                                                                 
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x7325f20, 0xc000000003, 0x0, 0x0, 0xc000af8700, 0x0, 0x5f4fb02, 0x14, 0xdf, 0x0)                                                  
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x1e5                                                                 
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printf(0x7325f20, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x49ef0f1, 0x1e, 0xc00015bfe0, 0x1, ...)                                              
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:753 +0x19a                                                                 
k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatalf(...)                                                                                                                                           
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1514`
```

### What did you expect to happen?

it should be running status for all the pods

### How can we reproduce it (as minimally and precisely as possible)?

we can re-run the upgrade

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
`
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.                           
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVers
ion:"go1.19.3", Compiler:"gc", Platform:"windows/amd64"}                                                                                                                                      
Kustomize Version: v4.5.7                                                                                                                                                                     
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:11:36Z", GoVer
sion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}                                                                                                                                      
WARNING: version difference between client (1.25) and server (1.21) exceeds the supported minor version skew of +/-1``

</details>


### Cloud provider

<details>
Azure vm's and we are using ansible tower to upgrade 
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
`
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"``

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>
containerd

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/kind support
BTW, 1.20 & 1.22 are End of Life in kubernetes community.

> error starting controllers: failed to mark cidr[10.244.4.0/24] at idx [0] as occupied for node: vq9bcordv05-23: cidr 10.244.4.0/24 is  out the range of cluster cidr 10.244.0.0/22                             

In general we don't support changing the cluster CIDR - you might be able to expand it into adjacent spaces, but it has to be contiguous and we don't have a way to change nodes assignments on the fly. See https://github.com/kubernetes/kubernetes/issues/75461.

**Comment by liggitt** [comment]
cc @aojea for visibility, even though this is an EOL version, would be good to know the root cause or whether it is relevant to upgraded clusters

**Comment by shubhindia** [comment]
> failed to mark cidr[10.244.4.0/24] at idx [0] as occupied for node: vq9bcordv05-23: cidr 10.244.4.0/24 is  out the range of cluster cidr 10.244.0.0/22


Is `vq9bcordv05-23` new VM or is it the existing one on which upgrade happened? The error is pretty self explanatory but can't understand why node CIDR became conflicting after upgrade.

**Comment by aojea** [comment]
The nodeipam controller crash the kube-controller-manager if the config is wrong

> F0519 17:46:03.511517       1 controllermanager.go:223] error starting controllers: failed to mark cidr[10.244.4.0/24] at idx [0] as occupied for node: vq9bcordv05-23: cidr 10.244.4.0/24 is 
out the range of cluster cidr 10.244.0.0/22  

The key message is here

```
10.244.4.0/24 is out the range of cluster cidr 10.244.0.0/22  
```

https://jodies.de/ipcalc?host=10.244.0.0&mask1=22&mask2=

have you changed your kube-controller-manager flags during the upgrade?

**Comment by khenidak** [comment]
> have you changed your kube-controller-manager flags during the upgrade?

I believe that this is the cause of this error. Can you confirm control manager CLI flags before and after upgrade? (the last IP in CIDR `10.244.0.0/22` is `10.244.3.255`)

**Comment by aojea** [comment]
/close

no answer in 2 months
