### ISSUE TITLE
[Flaky] CSIStorageCapacity e2e tests

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#118175]
##### Error text:
```
[TIMEDOUT] A spec timeout occurred
In [DeferCleanup (Each)] at: test/e2e/storage/drivers/csi.go:710 @ 05/13/23 11:40:32.756

This is the Progress Report generated when the spec timeout occurred:
  [sig-storage] CSI Mock volume storage capacity CSIStorageCapacity CSIStorageCapacity used, have capacity (Spec Runtime: 5m0.001s)
    test/e2e/storage/csi_mock/csi_storage_capacity.go:323
    In [DeferCleanup (Each)] (Node Runtime: 4m16.631s)
      test/e2e/storage/drivers/csi.go:710
      At [By Step] Waiting for namespaces [csi-mock-volumes-capacity-4788-7010] to vanish (Step Runtime: 2m47.369s)
        test/e2e/framework/util.go:241

      Spec Goroutine
      goroutine 498 [select]
        k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.waitForWithContext({0x7f3774252418, 0xc00484aae0}, 0xc001050138, 0x2bc95aa?)
          vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:205
        k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.poll({0x7f3774252418, 0xc00484aae0}, 0x46?, 0x0?, 0x0?)
          vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:260
        k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.PollWithContext({0x7f3774252418, 0xc00484aae0}, 0xc0046fc510?, 0x23?, 0x1?)
          vendor/k8s.io/apimachinery/pkg/util/wait/poll.go:85
      > k8s.io/kubernetes/test/e2e/framework.WaitForNamespacesDeleted({0x7f3774252418, 0xc00484aae0}, {0x72b89f0, 0xc005e39860}, {0xc00146c060, 0x1, 0x0?}, 0x0?)
          test/e2e/framework/util.go:247
      > k8s
```
#### Recent failures:
[21/05/2023, 05:01:14 ci-kubernetes-e2e-gci-gce-containerd](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-containerd/1660118502863802368)
[20/05/2023, 18:02:12 ci-kubernetes-e2e-gci-gce-flaky-repro](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-flaky-repro/1659952657780969472)
[19/05/2023, 10:14:16 ci-kubernetes-e2e-gci-gce-containerd](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-containerd/1659472507427622912)
[19/05/2023, 03:55:16 ci-kubernetes-e2e-gci-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1659377127247581184)
[17/05/2023, 08:40:10 ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1658724046159745024)

/kind flake 

/sig storage

It seems the timeout is too short or should not apply to the cleanup of the test, since the test is failing because the context is canceled during the timeout

https://github.com/kubernetes/kubernetes/pull/114580/files#r1059891282

https://github.com/kubernetes/kubernetes/blob/6d09ab86c24f8bb680e430feedb1f97200c93684/test/e2e/storage/csi_mock/csi_storage_capacity.go#L323

**Comment by pohly** [comment]
See https://github.com/kubernetes/kubernetes/pull/118200
