### ISSUE TITLE
Concurrent map writes on PVCRefCounts of NodeInfo

### ISSUE THREAD

**Issue by KunWuLuan** [kubernetes/kubernetes#118611]
### What happened?

Kube-scheduler crashed when many pods were scheduled simultaneously.

`184817 goroutine 431 [running]:
184818 runtime.throw(0x21afb8d, 0x15)
184819         /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc0019736b8 sp=0xc001973688 pc=0x438852
184820 runtime.mapassign_faststr(0x1e6df00, 0xc00da4ac00, 0xc01fd55d60, 0x20, 0x1)
184821         /usr/local/go/src/runtime/map_faststr.go:291 +0x3d8 fp=0xc001973720 sp=0xc0019736b8 pc=0x414a78
184822 k8s.io/kubernetes/pkg/scheduler/framework.(*NodeInfo).updatePVCRefCounts(0xc00d1f7050, 0xc016954c00, 0xc001973900)
184817 goroutine 431 [running]:`

`188323 goroutine 323722 [runnable]:
188324 k8s.io/kubernetes/pkg/scheduler/framework.(*NodeInfo).updatePVCRefCounts(0xc018308ea0, 0xc00d9d5000, 0xc022269c01)
188325         /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/scheduler/framework/types.go:771 +0x14f
188326 k8s.io/kubernetes/pkg/scheduler/framework.(*NodeInfo).AddPodInfo(0xc018308ea0, 0xc00dc7d700)
188327         /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/scheduler/framework/types.go:606 +0x31e
188328 k8s.io/kubernetes/pkg/scheduler/framework/runtime.addNominatedPods(0x2477e30, 0xc01a2004c0, 0x249c918, 0xc000732a80, 0xc012379800, 0xc01a4acf00, 0xc012894fc0, 0x34f5dc0, 0x34f5dd0, 0xc022269`

### What did you expect to happen?

Update on the copy of the map.

### How can we reproduce it (as minimally and precisely as possible)?

Kube-scheduler crashed when many pods were scheduled simultaneously.

### Anything else we need to know?

In 1.22 and 1.24 we still copy the map directly.

https://github.com/kubernetes/kubernetes/blob/0018fa8af8ffaff22f36d3bd86289753ca61da81/pkg/scheduler/framework/types.go#L544-L554

In 1.25 we copy the map in a safe way.

https://github.com/kubernetes/kubernetes/blob/e770bdbb87cccdc2daa790ecd69f40cf4df3cc9d/pkg/scheduler/framework/types.go#L535-L569

### Kubernetes version

<details>
kubernetes version 1.24.6
```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by KunWuLuan** [comment]
closed because no more release is for 1.24
