### ISSUE TITLE
Failure cluster [4f4faf64...]  TestGetListNonRecursiveCacheBypass flake

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#119028]
### Failure cluster [4f4faf643ed091bd9003](https://go.k8s.io/triage#4f4faf643ed091bd9003)

A recent failure can be found in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/118967/pull-kubernetes-unit/1675746725827973120. 

##### Error text:
```
Failed
=== RUN   Test_newReadyRacy
panic: test timed out after 3m0s

goroutine 32762 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:2036 +0xbb
created by time.goFunc
	/usr/local/go/src/time/sleep.go:176 +0x48

goroutine 1 [chan receive, 2 minutes]:
testing.(*T).Run(0xc000102b60, {0x226b4c5, 0x11}, 0x2340b20)
	/usr/local/go/src/testing/testing.go:1494 +0x789
testing.runTests.func1(0x0?)
	/usr/local/go/src/testing/testing.go:1846 +0x9a
testing.tRunner(0xc000102b60, 0xc0002dfba0)
	/usr/local/go/src/testing/testing.go:1446 +0x217
testing.runTests(0xc00032e280?, {0x32436a0, 0x31, 0x31}, {0x40?, 0x7f68c2f4df08?, 0x325a6c0?})
	/usr/local/go/src/testing/testing.go:1844 +0x7ed
testing.(*M).Run(0xc00032e280)
	/usr/local/go/src/testing/testing.go:1726 +0xa85
main.main()
	_testmain.go:145 +0x2ea

goroutine 23994 [chan receive, 2 minutes]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.Test_newReadyRacy(0xc002080000)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher/ready_test.go:97 +0x34c
testing.tRunner(0xc002080000, 0x2340b20)
	/usr/local/go/src/testing/testing.go:1446 +0x217
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1493 +0x75e

goroutine 35637 [select, 2 minutes]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.(*ready).wait(0xc001463a40, {0x25addb0, 0xc0001b0008})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kub
```
#### Recent failures:
[2023/7/2 09:16:29 ci-kubernetes-unit-1-24](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-1-24/1675311943788793856)
[2023/6/29 21:51:44 ci-kubernetes-unit-1-26](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-1-26/1674414728312524800)

/kind flake
/sig api-machinery

**Comment by aojea** [comment]
> panic: test timed out after 3m0s

this is a deadlock, we fixed one recently in this test, i wonder if we need to backport or something

**Comment by aojea** [comment]
@pacoxu I think we need to backport this https://github.com/kubernetes/kubernetes/pull/116251

**Comment by aojea** [comment]
/assign

I'll send them

**Comment by jiahuif** [comment]
Thank you.
/triage accepted

**Comment by ardaguclu** [comment]
I see that backports were merged and tests are passing. I think, we can close this issue.
/close
