### ISSUE TITLE
Windows unit test failure: [TestListPodStatsStrictlyFromCRI] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mansikulkarni96** [kubernetes/kubernetes#119565]
### Which jobs are failing?

windows-unit-master

### Which tests are failing?

k8s.io/kubernetes/cmd/kubeadm/app/cmd.TestNewResetData
k8s.io/kubernetes/cmd/kubeadm/app/cmd.TestNewResetData/Pass_with_config_from_file
k8s.io/kubernetes/cmd/kube-scheduler/app/options.TestLoadConfigFromFile
k8s.io/kubernetes/cmd/kube-scheduler/app/options.TestLoadConfigFromFile/case_0:_Empty_scheduler_config_file_path
k8s.io/kubernetes/pkg/scheduler/internal/queue.Test_InFlightPods
k8s.io/kubernetes/pkg/scheduler/internal/queue.Test_InFlightPods/Pod_registered_in_inFlightPods_with_previousEvent_with_inFlightPodsNum:non-zero_is_enqueued_back_to_activeQ
k8s.io/kubernetes/pkg/kubelet/stats.TestListPodStatsStrictlyFromCRI[Changes](https://github.com/kubernetes-sigs/windows-testing/compare/b98610b73...11fad6615?)

### Since when has it been failing?

07-18

### Testgrid link

https://testgrid.k8s.io/sig-windows-signal#windows-unit-master

### Reason for failure (if possible)

PANIC coming from code path:

https://github.com/kubernetes/kubernetes/blob/7e0a9a7f4e70e4cc6f5dd49917d18101a8e1a25c/pkg/kubelet/stats/cri_stats_provider_windows.go#L90

```
=== Failed
=== FAIL: pkg/kubelet/stats TestListPodStatsStrictlyFromCRI (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x23bad51]

goroutine 91 [running]:
testing.tRunner.func1.2({0x259c700, 0x3c19d30})
	C:/Program Files/Go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	C:/Program Files/Go/src/testing/testing.go:1529 +0x39f
panic({0x259c700, 0x3c19d30})
	C:/Program Files/Go/src/runtime/panic.go:884 +0x213
github.com/golang/mock/gomock.(*Controller).finish(0xc000a06ae0, 0x0, {0x259c700, 0x3c19d30})
	C:/kubernetes/vendor/github.com/golang/mock/gomock/controller.go:288 +0x505
github.com/golang/mock/gomock.(*Controller).Finish(0x2?)
	C:/kubernetes/vendor/github.com/golang/mock/gomock/controller.go:269 +0x38
panic({0x259c700, 0x3c19d30})
	C:/Program Files/Go/src/runtime/panic.go:884 +0x213
github.com/golang/mock/gomock.(*Controller).finish(0xc000a63bf0, 0x0, {0x259c700, 0x3c19d30})
	C:/kubernetes/vendor/github.com/golang/mock/gomock/controller.go:288 +0x505
github.com/golang/mock/gomock.(*Controller).Finish(0xc000a71d80?)
	C:/kubernetes/vendor/github.com/golang/mock/gomock/controller.go:269 +0x38
panic({0x259c700, 0x3c19d30})
	C:/Program Files/Go/src/runtime/panic.go:884 +0x213
k8s.io/kubernetes/pkg/kubelet/stats.(*criStatsProvider).addCRIPodContainerStats(0x2589360?, 0xc000a63d40?, 0xc000a33f98, 0x20?, 0xf?, 0xc000a92730, 0xd?, 0x55?)
	C:/kubernetes/pkg/kubelet/stats/cri_stats_provider_windows.go:90 +0x51
k8s.io/kubernetes/pkg/kubelet/stats.(*criStatsProvider).listPodStatsStrictlyFromCRI(0xc0002530e0, {0x2b9e180, 0xc00004e0d8}, 0xec?, 0xb?, 0xc000a63d40, 0x10?)
	C:/kubernetes/pkg/kubelet/stats/cri_stats_provider.go:251 +0x34a
k8s.io/kubernetes/pkg/kubelet/stats.(*criStatsProvider).listPodStats(0xc0002530e0, {0x2b9e180, 0xc00004e0d8}, 0x1?)
	C:/kubernetes/pkg/kubelet/stats/cri_stats_provider.go:140 +0x2d5
k8s.io/kubernetes/pkg/kubelet/stats.(*criStatsProvider).ListPodStats(0x2baa4d0?, {0x2b9e180?, 0xc00004e0d8?})
	C:/kubernetes/pkg/kubelet/stats/cri_stats_provider.go:108 +0x25
k8s.io/kubernetes/pkg/kubelet/stats.TestListPodStatsStrictlyFromCRI(0xc000a24000)
	C:/kubernetes/pkg/kubelet/stats/cri_stats_provider_test.go:473 +0x2154
testing.tRunner(0xc000a24000, 0x298ca78)
	C:/Program Files/Go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	C:/Program Files/Go/src/testing/testing.go:1629 +0x3ea
```

### Relevant SIG(s)

/sig windows

**Comment by mansikulkarni96** [comment]
cc: @jsturtevant @claudiubelu

**Comment by mansikulkarni96** [comment]
Couldn't reproduce the failure locally by running unit tests against the latest master.
```
k8s.io/kubernetes/hack/tools/ncpu
+++ [0725 13:25:33] Setting GOMAXPROCS: 8
+++ [0725 13:25:33] Running tests without code coverage and with -race
=== RUN   TestListPodStatsStrictlyFromCRI
--- PASS: TestListPodStatsStrictlyFromCRI (0.00s)
PASS
ok  	k8s.io/kubernetes/pkg/kubelet/stats
```

**Comment by neolit123** [comment]
there is one open PR by @claudiubelu 
https://github.com/kubernetes/kubernetes/pull/119436

**Comment by jsturtevant** [comment]
> there is one open PR by @claudiubelu #119436

that PR doesn't address  the failure being reported here: `FAIL: pkg/kubelet/stats TestListPodStatsStrictlyFromCRI (0.00s)`

/retitle Windows unit test failure: [TestListPodStatsStrictlyFromCRI] panic: runtime error: invalid memory address or nil pointer dereference

**Comment by mansikulkarni96** [comment]
/assign
working on it.
