### ISSUE TITLE
gce-master-scale-performance failed since 07-28

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#119664]
### Which jobs are failing?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1684609962237497344

### Which tests are failing?

e2e.go: Prepare 

### Since when has it been failing?

07-28

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-performance

### Reason for failure (if possible)

```
2023/07/27 17:09:01 main.go:328: Something went wrong: failed to prepare test environment: --provider=gce boskos failed to acquire project: resources not found
Traceback (most recent call last):
  File "/workspace/scenarios/kubernetes_e2e.py", line 723, in <module>
    main(parse_args())
  File "/workspace/scenarios/kubernetes_e2e.py", line 569, in main
    mode.start(runner_args)
  File "/workspace/scenarios/kubernetes_e2e.py", line 228, in start
    check_env(env, self.command, *args)
  File "/workspace/scenarios/kubernetes_e2e.py", line 111, in check_env
    subprocess.check_call(cmd, env=env)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)

```

### Relevant SIG(s)

/sig release

**Comment by pacoxu** [comment]
`v20230719-72ce785784-master` is changed in https://github.com/kubernetes/test-infra/pull/30179/.

**Comment by pacoxu** [comment]
/close
the problem was fixed early.
