### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by dzjiang91** [kubernetes/kubernetes#120094]
### What happened?

Command run:
```
ginkgo --focus="\[sig-storage\] In-tree Volumes \[Driver: vsphere\]" --skip="\[Disruptive\]|\[Slow\]|block.*multiVolume.*read-only|AllowedTopologies|should mount multiple PV pointing to the same storage on the same node" e2e.test -- --provider=vsphere --kubeconfig=kubeconfig
```

vSphere intree volume test suite occasionally failed with the following error:
```
fatal error: concurrent map writes

goroutine 1155 [running]:
k8s.io/kubernetes/test/e2e/storage/vsphere.(*NodeMapper).SetNodeInfo(...)
	test/e2e/storage/vsphere/nodemapper.go:290
k8s.io/kubernetes/test/e2e/storage/vsphere.(*NodeMapper).GenerateNodeMap.func1()
	test/e2e/storage/vsphere/nodemapper.go:129 +0x8e5
created by k8s.io/kubernetes/test/e2e/storage/vsphere.(*NodeMapper).GenerateNodeMap
	test/e2e/storage/vsphere/nodemapper.go:111 +0x2b4

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0002b04e0, {0x6c4cc09?, 0x2319985?}, 0x6f18600)
	/usr/local/go/src/testing/testing.go:1630 +0x405
testing.runTests.func1(0x9dcb980?)
	/usr/local/go/src/testing/testing.go:2036 +0x45
testing.tRunner(0xc0002b04e0, 0xc000b3f808)
	/usr/local/go/src/testing/testing.go:1576 +0x10b
testing.runTests(0xc0008f8500?, {0x9bc21a0, 0x1, 0x1}, {0x629c4a0?, 0xc000785cb0?, 0x0?})
	/usr/local/go/src/testing/testing.go:2034 +0x489
testing.(*M).Run(0xc0008f8500)
	/usr/local/go/src/testing/testing.go:1906 +0x63a
k8s.io/kubernetes/test/e2e.TestMain(0xffffffffffffffff?)
	test/e2e/e2e_test.go:137 +0x9c5
main.main()
	/tmp/go-build1839078858/b001/_testmain.go:49 +0x1d3

goroutine 104 [select]:
k8s.io/kubernetes/vendor/go.opencensus.io/stats/view.(*worker).start(0xc000420c80)
	vendor/go.opencensus.io/stats/view/worker.go:276 +0xad
created by k8s.io/kubernetes/vendor/go.opencensus.io/stats/view.init.0
	vendor/go.opencensus.io/stats/view/worker.go:34 +0x96

goroutine 123 [select]:
k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/v2/internal.(*Suite).runNode(_, {0x2136, 0x4, {0x6d13ed8, 0x28}, 0xc000e0b7a0, {{0x84d091b, 0x26}, 0xc2, {0x0, ...}, ...}, ...}, ...)
	vendor/github.com/onsi/ginkgo/v2/internal/suite.go:885 +0xff7
k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/v2/internal.(*group).attemptSpec(0xc003b187f0, 0x1, {{0xc000ee4a80?, 0xc002252790?, 0x3?}, 0x0?})
	vendor/github.com/onsi/ginkgo/v2/internal/group.go:199 +0xbc5
k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/v2/internal.(*group).run(0xc003b187f0, {0xc000c05da0?, 0xc000120e20?, 0x1?})
	vendor/github.com/onsi/ginkgo/v2/internal/group.go:346 +0x8e5
k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/v2/internal.(*Suite).runSpecs(0xc0001d2a80, {0x6c8621c, 0x14}, {0x9e00df8, 0x0, 0x0}, {0xc00007e144, 0x2d}, 0x0, {0xc00383c000, ...})
	vendor/github.com/onsi/ginkgo/v2/internal/suite.go:463 +0xabb
k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/v2/internal.(*Suite).Run(_, {_, _}, {_, _, _}, {_, _}, _, {0x7431430, ...}, ...)
	vendor/github.com/onsi/ginkgo/v2/internal/suite.go:116 +0x445
k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/v2.RunSpecs({0x73f8e20, 0xc0002b0680}, {0x6c8621c, 0x14}, {0xc000c037a0?, 0x2, 0x0?})
	vendor/github.com/onsi/ginkgo/v2/core_dsl.go:319 +0xfb7
k8s.io/kubernetes/test/e2e.RunE2ETests(0xc0002b0680?)
	test/e2e/e2e.go:118 +0x610
k8s.io/kubernetes/test/e2e.TestE2E(0x21d46f9?)
	test/e2e/e2e_test.go:141 +0x19
testing.tRunner(0xc0002b0680, 0x6f18600)
	/usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1629 +0x3ea

goroutine 124 [select]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*flushDaemon).run.func1()
	vendor/k8s.io/klog/v2/klog.go:1141 +0x11e
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*flushDaemon).run
	vendor/k8s.io/klog/v2/klog.go:1137 +0x17b

goroutine 81 [syscall]:
os/signal.signal_recv()
	/usr/local/go/src/runtime/sigqueue.go:152 +0x2f
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:151 +0x2a

goroutine 130 [select]:
k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/v2/internal/interrupt_handler.(*InterruptHandler).registerForInterrupts.func2(0x0?)
	vendor/github.com/onsi/ginkgo/v2/internal/interrupt_handler/interrupt_handler.go:123 +0x89
created by k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/v2/internal/interrupt_handler.(*InterruptHandler).registerForInterrupts
	vendor/github.com/onsi/ginkgo/v2/internal/interrupt_handler/interrupt_handler.go:120 +0x179

goroutine 107 [select]:
k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/v2/internal.RegisterForProgressSignal.func1()
	vendor/github.com/onsi/ginkgo/v2/internal/progress_report.go:32 +0x91
created by k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/v2/internal.RegisterForProgressSignal
	vendor/github.com/onsi/ginkgo/v2/internal/progress_report.go:30 +0xf8

goroutine 134 [IO wait]:
internal/poll.runtime_pollWait(0x7f65e58702d8, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc002d64280?, 0xc003900000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc002d64280, {0xc003900000, 0xa000, 0xa000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc002d64280, {0xc003900000?, 0xc003900005?, 0x1a?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000166338, {0xc003900000?, 0x257a663?, 0xc002467330?})
	/usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc000e76468, {0xc003900000?, 0xc000e76468?, 0x0?})
	/usr/local/go/src/crypto/tls/conn.go:788 +0x3d
bytes.(*Buffer).ReadFrom(0xc002467410, {0x73eed40, 0xc000e76468})
	/usr/local/go/src/bytes/buffer.go:202 +0x98
crypto/tls.(*Conn).readFromUntil(0xc002467180, {0x73f8780?, 0xc000166338}, 0xa000?)
	/usr/local/go/src/crypto/tls/conn.go:810 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc002467180, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:617 +0x116
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:583
crypto/tls.(*Conn).Read(0xc002467180, {0xc003197000, 0x1000, 0x0?})
	/usr/local/go/src/crypto/tls/conn.go:1316 +0x16f
bufio.(*Reader).Read(0xc00095bd40, {0xc0002aaac0, 0x9, 0xc001397888?})
	/usr/local/go/src/bufio/bufio.go:237 +0x1bb
io.ReadAtLeast({0x73eeb20, 0xc00095bd40}, {0xc0002aaac0, 0x9, 0x9}, 0x9)
	/usr/local/go/src/io/io.go:332 +0x9a
io.ReadFull(...)
	/usr/local/go/src/io/io.go:351
k8s.io/kubernetes/vendor/golang.org/x/net/http2.readFrameHeader({0xc0002aaac0?, 0x9?, 0xc001713710?}, {0x73eeb20?, 0xc00095bd40?})
	vendor/golang.org/x/net/http2/frame.go:237 +0x6e
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc0002aaa80)
	vendor/golang.org/x/net/http2/frame.go:498 +0x95
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc0000aaf98)
	vendor/golang.org/x/net/http2/transport.go:2224 +0x12e
k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc0008a0600)
	vendor/golang.org/x/net/http2/transport.go:2119 +0x6f
created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).newClientConn
	vendor/golang.org/x/net/http2/transport.go:817 +0xc1f

goroutine 1156 [select]:
net/http.(*persistConn).roundTrip(0xc000622fc0, 0xc002a4cdc0)
	/usr/local/go/src/net/http/transport.go:2638 +0x994
net/http.(*Transport).roundTrip(0xc0040f23c0, 0xc002a23200)
	/usr/local/go/src/net/http/transport.go:603 +0x7fa
net/http.(*Transport).RoundTrip(0xc003713d10?, 0x73f88a0?)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x19
net/http.send(0xc002a23200, {0x73f88a0, 0xc0040f23c0}, {0x8?, 0x6b787c0?, 0x0?})
	/usr/local/go/src/net/http/client.go:252 +0x5f7
net/http.(*Client).send(0xc00409c6e0, 0xc002a23200, {0xc003c2db00?, 0xc00356b1c8?, 0x0?})
	/usr/local/go/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc00409c6e0, 0xc002a23200)
	/usr/local/go/src/net/http/client.go:716 +0x8fb
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:582
k8s.io/kubernetes/vendor/github.com/vmware/govmomi/vim25/soap.(*Client).Do(0xc00409c6e0?, {0x7423f80?, 0xc003d80e10?}, 0xc002a23100?, 0xc00356b5d8)
	vendor/github.com/vmware/govmomi/vim25/soap/client.go:554 +0x38e
k8s.io/kubernetes/vendor/github.com/vmware/govmomi/vapi/rest.(*Client).Do(0xc003b62d80, {0x7423f80, 0xc003d80e10}, 0xc002a23100, {0x5df4e20, 0xc000f9cb10})
	vendor/github.com/vmware/govmomi/vapi/rest/client.go:191 +0x46b
k8s.io/kubernetes/vendor/github.com/vmware/govmomi/vapi/tags.(*Manager).ListAttachedTags(0xc00356b858, {0x7423f80, 0xc003d80e10}, {0x73f9da0, 0xc00245aa80})
	vendor/github.com/vmware/govmomi/vapi/tags/tag_association.go:200 +0x206
k8s.io/kubernetes/test/e2e/storage/vsphere.retrieveZoneInformationForNode.func1(0xc00356bc00?)
	test/e2e/storage/vsphere/nodemapper.go:183 +0x44e
k8s.io/kubernetes/test/e2e/storage/vsphere.withTagsClient({0x7423f80, 0xc003d80e10}, 0xc000572920, 0xc00356bcc0)
	test/e2e/storage/vsphere/nodemapper.go:153 +0x171
k8s.io/kubernetes/test/e2e/storage/vsphere.retrieveZoneInformationForNode({0xc0018c5880, 0x1e}, 0xc000572920, {{0xc003d0c390?, 0x24?}, {0xc003d0c3b0?, 0xc000d3b980?}})
	test/e2e/storage/vsphere/nodemapper.go:162 +0x1ad
k8s.io/kubernetes/test/e2e/storage/vsphere.(*NodeMapper).GenerateNodeMap.func1()
	test/e2e/storage/vsphere/nodemapper.go:125 +0x455
created by k8s.io/kubernetes/test/e2e/storage/vsphere.(*NodeMapper).GenerateNodeMap
	test/e2e/storage/vsphere/nodemapper.go:111 +0x2b4

goroutine 1133 [semacquire]:
sync.runtime_Semacquire(0xc003dd0480?)
	/usr/local/go/src/runtime/sema.go:62 +0x27
sync.(*WaitGroup).Wait(0xc003077ab8?)
	/usr/local/go/src/sync/waitgroup.go:116 +0x4b
k8s.io/kubernetes/test/e2e/storage/vsphere.(*NodeMapper).GenerateNodeMap(0x9e00df8, 0x0?, {{{0x0, 0x0}, {0x0, 0x0}}, {{0x0, 0x0}, {0xc00237f9f8, 0x6}, ...}, ...})
	test/e2e/storage/vsphere/nodemapper.go:137 +0x41d
k8s.io/kubernetes/test/e2e/storage/vsphere.bootstrapOnce(0xc000c95e00)
	test/e2e/storage/vsphere/bootstrap.go:56 +0x1dd
k8s.io/kubernetes/test/e2e/storage/vsphere.Bootstrap.func1.1()
	test/e2e/storage/vsphere/bootstrap.go:35 +0x1d
sync.(*Once).doSlow(0xc001618a80?, 0xc003e94fd0?)
	/usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:65
k8s.io/kubernetes/test/e2e/storage/vsphere.Bootstrap.func1()
	test/e2e/storage/vsphere/bootstrap.go:34 +0x55
created by k8s.io/kubernetes/test/e2e/storage/vsphere.Bootstrap
	test/e2e/storage/vsphere/bootstrap.go:33 +0x85

goroutine 737 [select]:
net/http.(*persistConn).writeLoop(0xc003c12fc0)
	/usr/local/go/src/net/http/transport.go:2410 +0xf2
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1766 +0x173d

goroutine 1172 [IO wait]:
internal/poll.runtime_pollWait(0x7f65e586ff18, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc001239080?, 0xc002997000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc001239080, {0xc002997000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc001239080, {0xc002997000?, 0xc00299700d?, 0xfe?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc00036d4c8, {0xc002997000?, 0xff3?, 0xc002997005?})
	/usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc000f9c1c8, {0xc002997000?, 0xc000f9c1c8?, 0x0?})
	/usr/local/go/src/crypto/tls/conn.go:788 +0x3d
bytes.(*Buffer).ReadFrom(0xc002668290, {0x73eed40, 0xc000f9c1c8})
	/usr/local/go/src/bytes/buffer.go:202 +0x98
crypto/tls.(*Conn).readFromUntil(0xc002668000, {0x73f8780?, 0xc00036d4c8}, 0x0?)
	/usr/local/go/src/crypto/tls/conn.go:810 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc002668000, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:617 +0x116
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:583
crypto/tls.(*Conn).Read(0xc002668000, {0xc0026fd000, 0x1000, 0x18?})
	/usr/local/go/src/crypto/tls/conn.go:1316 +0x16f
net/http.(*persistConn).Read(0xc003c2c240, {0xc0026fd000?, 0xc005571a40?, 0xc00387fd30?})
	/usr/local/go/src/net/http/transport.go:1943 +0x4e
bufio.(*Reader).fill(0xc00258d8c0)
	/usr/local/go/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).Peek(0xc00258d8c0, 0x1)
	/usr/local/go/src/bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc003c2c240)
	/usr/local/go/src/net/http/transport.go:2107 +0x1ac
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1765 +0x16ea

goroutine 1202 [runnable]:
crypto/internal/boring._Cfunc__goboringcrypto_EVP_AEAD_max_overhead(0x9dfaf30)
	/tmp/go-build1309417047/b077/_cgo_gotypes.go:761 +0x49
crypto/internal/boring.(*aesGCM).Overhead(0xc0030bbce0?)
	/usr/local/go/src/crypto/internal/boring/aes.go:286 +0x25
crypto/tls.(*prefixNonceAEAD).Overhead(0xc002668870?)
	/usr/local/go/src/crypto/tls/cipher_suites.go:463 +0x22
crypto/tls.(*halfConn).decrypt(0xc002668870, {0xc001436a00, 0xd9, 0x700})
	/usr/local/go/src/crypto/tls/conn.go:370 +0x526
crypto/tls.(*Conn).readRecordOrCCS(0xc002668700, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:671 +0xb34
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:583
crypto/tls.(*Conn).Read(0xc002668700, {0xc002909000, 0x1000, 0x18?})
	/usr/local/go/src/crypto/tls/conn.go:1316 +0x16f
net/http.(*persistConn).Read(0xc000622fc0, {0xc002909000?, 0xc00370ec60?, 0xc003f43d30?})
	/usr/local/go/src/net/http/transport.go:1943 +0x4e
bufio.(*Reader).fill(0xc00557b920)
	/usr/local/go/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).Peek(0xc00557b920, 0x1)
	/usr/local/go/src/bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc000622fc0)
	/usr/local/go/src/net/http/transport.go:2107 +0x1ac
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1765 +0x16ea

goroutine 1173 [select]:
net/http.(*persistConn).writeLoop(0xc003c2c240)
	/usr/local/go/src/net/http/transport.go:2410 +0xf2
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1766 +0x173d

goroutine 1140 [select]:
net/http.(*persistConn).writeLoop(0xc003c2d8c0)
	/usr/local/go/src/net/http/transport.go:2410 +0xf2
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1766 +0x173d

goroutine 1204 [IO wait]:
internal/poll.runtime_pollWait(0x7f65e5870008, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc002498080?, 0xc0022a9100?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc002498080, {0xc0022a9100, 0x700, 0x700})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc002498080, {0xc0022a9100?, 0xc0022a910d?, 0xcc?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000159368, {0xc0022a9100?, 0x6f3?, 0xc0022a9105?})
	/usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc000e76dc8, {0xc0022a9100?, 0xc000e76dc8?, 0x0?})
	/usr/local/go/src/crypto/tls/conn.go:788 +0x3d
bytes.(*Buffer).ReadFrom(0xc003770d10, {0x73eed40, 0xc000e76dc8})
	/usr/local/go/src/bytes/buffer.go:202 +0x98
crypto/tls.(*Conn).readFromUntil(0xc003770a80, {0x73f8780?, 0xc000159368}, 0x0?)
	/usr/local/go/src/crypto/tls/conn.go:810 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc003770a80, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:617 +0x116
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:583
crypto/tls.(*Conn).Read(0xc003770a80, {0xc002921000, 0x1000, 0x18?})
	/usr/local/go/src/crypto/tls/conn.go:1316 +0x16f
net/http.(*persistConn).Read(0xc003c3a240, {0xc002921000?, 0xc00370ee40?, 0xc003881d30?})
	/usr/local/go/src/net/http/transport.go:1943 +0x4e
bufio.(*Reader).fill(0xc002928ae0)
	/usr/local/go/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).Peek(0xc002928ae0, 0x1)
	/usr/local/go/src/bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc003c3a240)
	/usr/local/go/src/net/http/transport.go:2107 +0x1ac
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1765 +0x16ea

goroutine 1132 [chan receive]:
k8s.io/kubernetes/test/e2e/storage/vsphere.Bootstrap(0xc000c95e00)
	test/e2e/storage/vsphere/bootstrap.go:40 +0x91
k8s.io/kubernetes/test/e2e/storage/drivers.(*vSphereDriver).CreateVolume(0xc0?, {0x7f65e503a728, 0xc003e8aae0}, 0x0?, {0xc002cfb918?, 0x21dc147?})
	test/e2e/storage/drivers/in_tree.go:1303 +0x45
k8s.io/kubernetes/test/e2e/storage/framework.CreateVolume({0x7f65e503a728, 0xc003e8aae0}, {0x740c3a0, 0xc00046d860}, 0xc002cfb9b0?, {0x6c5e05f, 0xc})
	test/e2e/storage/framework/driver_operations.go:44 +0xf6
k8s.io/kubernetes/test/e2e/storage/framework.CreateVolumeResourceWithAccessModes({0x7f65e503a728, 0xc003e8aae0}, {0x740c3a0?, 0xc00046d860?}, 0xc002290a80, {{0x6cac93f, 0x1a}, {0x0, 0x0}, {0x6c5e05f, ...}, ...}, ...)
	test/e2e/storage/framework/volume_resource.go:70 +0x232
k8s.io/kubernetes/test/e2e/storage/framework.CreateVolumeResource({0x7f65e503a728, 0xc003e8aae0}, {0x740c3a0?, 0xc00046d860?}, 0x0?, {{0x6cac93f, 0x1a}, {0x0, 0x0}, {0x6c5e05f, ...}, ...}, ...)
	test/e2e/storage/framework/volume_resource.go:56 +0x145
k8s.io/kubernetes/test/e2e/storage/testsuites.(*volumesTestSuite).DefineTests.func1({0x7f65e503a728, 0xc003e8aae0})
	test/e2e/storage/testsuites/volumes.go:142 +0x2bb
k8s.io/kubernetes/test/e2e/storage/testsuites.(*volumesTestSuite).DefineTests.func4({0x7f65e503a728, 0xc003e8aae0})
	test/e2e/storage/testsuites/volumes.go:196 +0x82
k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/v2/internal.extractBodyFunction.func2({0x742c2c0?, 0xc003e8aae0})
	vendor/github.com/onsi/ginkgo/v2/internal/node.go:456 +0x48
k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3()
	vendor/github.com/onsi/ginkgo/v2/internal/suite.go:863 +0x98
created by k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/v2/internal.(*Suite).runNode
	vendor/github.com/onsi/ginkgo/v2/internal/suite.go:850 +0xd65

goroutine 1203 [select]:
net/http.(*persistConn).writeLoop(0xc000622fc0)
	/usr/local/go/src/net/http/transport.go:2410 +0xf2
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1766 +0x173d

goroutine 736 [IO wait]:
internal/poll.runtime_pollWait(0x7f65e58701e8, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc0017d0000?, 0xc002690000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0017d0000, {0xc002690000, 0x1800, 0x1800})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc0017d0000, {0xc002690000?, 0xc00269000d?, 0xfe?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc00036cca0, {0xc002690000?, 0x17f3?, 0xc002690005?})
	/usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc000abdcf8, {0xc002690000?, 0xc000abdcf8?, 0x0?})
	/usr/local/go/src/crypto/tls/conn.go:788 +0x3d
bytes.(*Buffer).ReadFrom(0xc002466d10, {0x73eed40, 0xc000abdcf8})
	/usr/local/go/src/bytes/buffer.go:202 +0x98
crypto/tls.(*Conn).readFromUntil(0xc002466a80, {0x73f8780?, 0xc00036cca0}, 0x0?)
	/usr/local/go/src/crypto/tls/conn.go:810 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc002466a80, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:617 +0x116
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:583
crypto/tls.(*Conn).Read(0xc002466a80, {0xc000fbd000, 0x1000, 0x18?})
	/usr/local/go/src/crypto/tls/conn.go:1316 +0x16f
net/http.(*persistConn).Read(0xc003c12fc0, {0xc000fbd000?, 0xc005571080?, 0xc003880d30?})
	/usr/local/go/src/net/http/transport.go:1943 +0x4e
bufio.(*Reader).fill(0xc0052b9080)
	/usr/local/go/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).Peek(0xc0052b9080, 0x1)
	/usr/local/go/src/bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc003c12fc0)
	/usr/local/go/src/net/http/transport.go:2107 +0x1ac
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1765 +0x16ea

goroutine 798 [chan send]:
k8s.io/kubernetes/vendor/github.com/moby/spdystream.(*Connection).shutdown(0xc00409c370, 0x0)
	vendor/github.com/moby/spdystream/connection.go:743 +0x27e
created by k8s.io/kubernetes/vendor/github.com/moby/spdystream.(*Connection).Close
	vendor/github.com/moby/spdystream/connection.go:769 +0x145

goroutine 1205 [select]:
net/http.(*persistConn).writeLoop(0xc003c3a240)
	/usr/local/go/src/net/http/transport.go:2410 +0xf2
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1766 +0x173d

goroutine 1139 [IO wait]:
internal/poll.runtime_pollWait(0x7f65e586fe28, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc002d65100?, 0xc0022a8a00?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc002d65100, {0xc0022a8a00, 0x700, 0x700})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc002d65100, {0xc0022a8a00?, 0xc0022a8a0d?, 0xcc?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000159378, {0xc0022a8a00?, 0x6f3?, 0xc0022a8a05?})
	/usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc000f9cba0, {0xc0022a8a00?, 0xc000f9cba0?, 0x0?})
	/usr/local/go/src/crypto/tls/conn.go:788 +0x3d
bytes.(*Buffer).ReadFrom(0xc003771090, {0x73eed40, 0xc000f9cba0})
	/usr/local/go/src/bytes/buffer.go:202 +0x98
crypto/tls.(*Conn).readFromUntil(0xc003770e00, {0x73f8780?, 0xc000159378}, 0x0?)
	/usr/local/go/src/crypto/tls/conn.go:810 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc003770e00, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:617 +0x116
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:583
crypto/tls.(*Conn).Read(0xc003770e00, {0xc0024e0000, 0x1000, 0x18?})
	/usr/local/go/src/crypto/tls/conn.go:1316 +0x16f
net/http.(*persistConn).Read(0xc003c2d8c0, {0xc0024e0000?, 0xc0022e9ce0?, 0xc003f31d30?})
	/usr/local/go/src/net/http/transport.go:1943 +0x4e
bufio.(*Reader).fill(0xc0022916e0)
	/usr/local/go/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).Peek(0xc0022916e0, 0x1)
	/usr/local/go/src/bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc003c2d8c0)
	/usr/local/go/src/net/http/transport.go:2107 +0x1ac
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1765 +0x16ea

Ginkgo ran 1 suite in 33.78465881s

Test Suite Failed
```

### What did you expect to happen?

The test suite should always pass.

### How can we reproduce it (as minimally and precisely as possible)?

We may have a chance to hit this by running
```
ginkgo --focus="\[sig-storage\] In-tree Volumes \[Driver: vsphere\]" --skip="\[Disruptive\]|\[Slow\]|block.*multiVolume.*read-only|AllowedTopologies|should mount multiple PV pointing to the same storage on the same node" e2e.test -- --provider=vsphere --kubeconfig=kubeconfig
````

### Kubernetes version

<details>

e2e.test binary version: 1.27.4

</details>

### Cloud provider

<details>
vsphere
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/sig testing storage
?
