### ISSUE TITLE
kube-apiserver error

### ISSUE THREAD

**Issue by GuoHui89757** [kubernetes/kubernetes#12006]
```
curl -L http://kube-master-ip:8080/ui/, kube-apiserver logs:
I0730 11:07:26.363276     547 handlers.go:137] GET /ui/: (56.743µs) 307 [[Mozilla/5.0 (Windows NT 6.1; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0] 192.168.5.125:59387]
I0730 11:07:26.389732     547 proxy.go:185] [2c92e31bcced2801] Beginning proxy /api/v1/proxy/namespaces/kube-system/services/kube-ui/...
I0730 11:07:56.390855     547 proxy.go:187] [2c92e31bcced2801] Proxy /api/v1/proxy/namespaces/kube-system/services/kube-ui/ finished 30.001118505s.
I0730 11:07:56.390998     547 handlers.go:137] GET /api/v1/proxy/namespaces/kube-system/services/kube-ui/: (30.002822352s) 503
goroutine 1353 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc20979e1e0, 0x1f7)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:188 +0x9a
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc2098c17a0, 0x7f480cfdd0e0, 0xc20979e1e0, 0xc20992c9c0)
        /usr/src/go/src/net/http/httputil/reverseproxy.go:159 +0x708
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.(*ProxyHandler).ServeHTTP(0xc208296190, 0x7f480cfdd0e0, 0xc20979e1e0, 0xc2093e6ea0)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/proxy.go:212 +0x2618
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·002(0xc20979c480, 0xc2093f2000)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:732 +0x60
github.com/emicklei/go-restful.func·005(0xc20979c480, 0xc2093f2000)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:215 +0x41
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20979c510, 0xc20979c480, 0xc2093f2000)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·003(0xc20979c480, 0xc2093f2000, 0xc20979c510)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:59 +0x88
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20979c510, 0xc20979c480, 0xc2093f2000)
        /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19 +0x84
github.com/emicklei/go-restful.(*Container).dispatch(0xc2082a0000, 0x7f480cfdd0e0, 0xc20979e1e0, 0xc2093e6ea0)
        /go/src/github.com/GoogleCloudPlatform/k [[Mozilla/5.0 (Windows NT 6.1; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0] 192.168.5.125:59387]
```

in my firefox, it looks like this
![image](https://cloud.githubusercontent.com/assets/12525252/8975064/f97e466e-36ab-11e5-8856-6105701a092a.png)
Is this a bug?

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
