### ISSUE TITLE
[Failing Test] (gce-master-scale-performance) Error while dumping cluster logs

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#121320]
### Which jobs are failing?

master-informing:
- gce-master-scale-performance

### Which tests are failing?

`kubetest.DumpClusterLogs`

### Since when has it been failing?

~https://github.com/kubernetes/kubernetes/pull/121242~

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-performance

### Reason for failure (if possible)

```
I1018 09:46:14.094967   21599 exec_service.go:123] Exec service: tearing down service
2023/10/18 09:46:29 process.go:155: Step '/home/prow/go/src/k8s.io/perf-tests/run-e2e.sh cluster-loader2 --experimental-gcp-snapshot-prometheus-disk=true --experimental-prometheus-disk-snapshot-name=ci-kubernetes-e2e-gce-scale-performance-1714540134923243520 --experimental-prometheus-snapshot-to-report-dir=true --nodes=5000 --prometheus-scrape-node-exporter --provider=gce --report-dir=/logs/artifacts --testconfig=testing/load/config.yaml --testconfig=testing/huge-service/config.yaml --testconfig=testing/access-tokens/config.yaml --testoverrides=./testing/experiments/enable_restart_count_check.yaml --testoverrides=./testing/experiments/ignore_known_gce_container_restarts.yaml --testoverrides=./testing/overrides/5000_nodes.yaml' finished in 1h57m49.081257202s
2023/10/18 09:46:29 e2e.go:569: Dumping logs from nodes to GCS directly at path: gs://k8s-infra-scalability-tests-logs/ci-kubernetes-e2e-gce-scale-performance/1714540134923243520
2023/10/18 09:46:29 process.go:153: Running: /workspace/log-dump.sh /logs/artifacts gs://k8s-infra-scalability-tests-logs/ci-kubernetes-e2e-gce-scale-performance/1714540134923243520
Checking for custom logdump instances, if any
Using gce provider, skipping check for LOG_DUMP_SSH_KEY and LOG_DUMP_SSH_USER
Project: k8s-infra-e2e-scale-5k-project
Network Project: k8s-infra-e2e-scale-5k-project
Zone: us-east1-b
Dumping logs temporarily to '/tmp/tmp.Lh8re5VkdY/logs'. Will upload to 'gs://k8s-infra-scalability-tests-logs/ci-kubernetes-e2e-gce-scale-performance/1714540134923243520' later.
Dumping logs from master locally to '/tmp/tmp.Lh8re5VkdY/logs'
Trying to find master named 'gce-scale-cluster-master'
Looking for address 'gce-scale-cluster-master-ip'
Looking for address 'gce-scale-cluster-master-internal-ip'
Using master: gce-scale-cluster-master (external IP: 104.196.48.60; internal IP: 10.40.0.2)
Changing logfiles to be world-readable for download
Copying 'kube-apiserver.log kube-apiserver-audit.log kube-scheduler.log cloud-controller-manager.log kube-controller-manager.log etcd.log etcd-events.log glbc.log cluster-autoscaler.log kube-addon-manager.log konnectivity-server.log fluentd.log kubelet.cov cl2-* startupscript.log' from gce-scale-cluster-master
Specify --start=117505 in the next get-serial-port-output invocation to get only the new output starting from here.
```
```
client_loop: send disconnect: Broken pipe
/usr/bin/scp: Connection closed
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [255].
ERROR: (gcloud.compute.scp) Could not fetch resource:
 - The resource 'projects/k8s-infra-e2e-scale-5k-project/zones/us-east1-b/instances/gce-scale-cluster-master' was not found
```

### Relevant SIG(s)

/sig testing
cc @kubernetes/ci-signal

**Comment by rjsadow** [comment]
It looks like `log-dump` is getting stuck here:

```
I1018 09:46:14.094967   21599 exec_service.go:123] Exec service: tearing down service
2023/10/18 09:46:29 process.go:155: Step '/home/prow/go/src/k8s.io/perf-tests/run-e2e.sh cluster-loader2 --experimental-gcp-snapshot-prometheus-disk=true --experimental-prometheus-disk-snapshot-name=ci-kubernetes-e2e-gce-scale-performance-1714540134923243520 --experimental-prometheus-snapshot-to-report-dir=true --nodes=5000 --prometheus-scrape-node-exporter --provider=gce --report-dir=/logs/artifacts --testconfig=testing/load/config.yaml --testconfig=testing/huge-service/config.yaml --testconfig=testing/access-tokens/config.yaml --testoverrides=./testing/experiments/enable_restart_count_check.yaml --testoverrides=./testing/experiments/ignore_known_gce_container_restarts.yaml --testoverrides=./testing/overrides/5000_nodes.yaml' finished in 1h57m49.081257202s
2023/10/18 09:46:29 e2e.go:569: Dumping logs from nodes to GCS directly at path: gs://k8s-infra-scalability-tests-logs/ci-kubernetes-e2e-gce-scale-performance/1714540134923243520
2023/10/18 09:46:29 process.go:153: Running: /workspace/log-dump.sh /logs/artifacts gs://k8s-infra-scalability-tests-logs/ci-kubernetes-e2e-gce-scale-performance/1714540134923243520
Checking for custom logdump instances, if any
Using gce provider, skipping check for LOG_DUMP_SSH_KEY and LOG_DUMP_SSH_USER
Project: k8s-infra-e2e-scale-5k-project
Network Project: k8s-infra-e2e-scale-5k-project
Zone: us-east1-b
Dumping logs temporarily to '/tmp/tmp.Lh8re5VkdY/logs'. Will upload to 'gs://k8s-infra-scalability-tests-logs/ci-kubernetes-e2e-gce-scale-performance/1714540134923243520' later.
Dumping logs from master locally to '/tmp/tmp.Lh8re5VkdY/logs'
Trying to find master named 'gce-scale-cluster-master'
Looking for address 'gce-scale-cluster-master-ip'
Looking for address 'gce-scale-cluster-master-internal-ip'
Using master: gce-scale-cluster-master (external IP: 104.196.48.60; internal IP: 10.40.0.2)
Changing logfiles to be world-readable for download
Copying 'kube-apiserver.log kube-apiserver-audit.log kube-scheduler.log cloud-controller-manager.log kube-controller-manager.log etcd.log etcd-events.log glbc.log cluster-autoscaler.log kube-addon-manager.log konnectivity-server.log fluentd.log kubelet.cov cl2-* startupscript.log' from gce-scale-cluster-master
Specify --start=117505 in the next get-serial-port-output invocation to get only the new output starting from here.
```

For ~4 hours then the test is timing out when it hits the 7 hour mark.

**Comment by Vyom-Yadav** [comment]
Thanks, added this to the reason for failure.

/retitle [Failing Test] (gce-master-scale-performance) Error while dumping cluster logs

**Comment by tosi3k** [comment]
This is weird - apparently, this was fixed in https://github.com/kubernetes/test-infra/pull/31037 but it still fails mysteriously.

For comparison, we do not have any problems with the same test but at 100 nodes scale despite using the same `kubekins-e2e` image version: https://testgrid.k8s.io/sig-scalability-gce#gce-cos-master-scalability-100.

**Comment by tosi3k** [comment]
I kicked off a manual one-off run with the following change in the `log-dump.sh` in our local Prow instance:

```
-        gcloud compute scp --recurse --project "${PROJECT}" --zone "${ZONE}" "${node}:${single_file}" "${dir}" > /dev/null || true
+        gcloud compute scp --recurse --project "${PROJECT}" --zone "${ZONE}" "${node}:${single_file}" "${dir}" --log-http
```

And log dumping magically started to work...

Maybe it's a matter of GCP projects used for these (`gce-master-scale-performance` as well as a couple of other scalability CI tests) tests?

**Comment by pacoxu** [comment]
@tosi3k would you submit a potential fix like that?

**Comment by tosi3k** [comment]
@pacoxu I kicked off another run using our internal infra and it also succeeded (i.e. `gcloud compute scp` commands didn't stall).

My belief is that it's somehow related to infra differences.

Let me open a PR today to add some logging to `log-dump.sh` so we can somehow progress with debugging here when new scalability test runs kick off during weekend.

**Comment by pacoxu** [comment]
With the debug log added in https://github.com/kubernetes/test-infra/pull/31087, the log shows

```
2023/10/22 00:18:46 main.go:324: Something went wrong: encountered 1 errors: [error during /workspace/log-dump.sh /logs/artifacts gs://k8s-infra-scalability-tests-logs/ci-kubernetes-e2e-gce-scale-performance/1715775341034737664 (interrupted): signal: interrupt]
Traceback (most recent call last):
  File "/workspace/scenarios/kubernetes_e2e.py", line 391, in <module>
    main(parse_args())
  File "/workspace/scenarios/kubernetes_e2e.py", line 307, in main
    mode.start(runner_args)
  File "/workspace/scenarios/kubernetes_e2e.py", line 136, in start
    check_env(env, self.command, *args)
  File "/workspace/scenarios/kubernetes_e2e.py", line 57, in check_env
    subprocess.check_call(cmd, env=env)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('kubetest', '--dump=/logs/artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--provider=gce', '--cluster=gce-scale-cluster', '--gcp-network=gce-scale-cluster', '--extract=ci/latest-fast', '--extract-ci-bucket=k8s-release-dev', '--gcp-nodes=5000', '--gcp-project-type=scalability-scale-project', '--gcp-zone=us-east1-b', '--metadata-sources=cl2-metadata.json', '--test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh', '--test-cmd-args=cluster-loader2', '--test-cmd-args=--experimental-gcp-snapshot-prometheus-disk=true', '--test-cmd-args=--experimental-prometheus-disk-snapshot-name=ci-kubernetes-e2e-gce-scale-performance-1715775341034737664', '--test-cmd-args=--experimental-prometheus-snapshot-to-report-dir=true', '--test-cmd-args=--nodes=5000', '--test-cmd-args=--prometheus-scrape-node-exporter', '--test-cmd-args=--provider=gce', '--test-cmd-args=--report-dir=/logs/artifacts', '--test-cmd-args=--testconfig=testing/load/config.yaml', '--test-cmd-args=--testconfig=testing/huge-service/config.yaml', '--test-cmd-args=--testconfig=testing/access-tokens/config.yaml', '--test-cmd-args=--testoverrides=./testing/experiments/enable_restart_count_check.yaml', '--test-cmd-args=--testoverrides=./testing/experiments/ignore_known_gce_container_restarts.yaml', '--test-cmd-args=--testoverrides=./testing/overrides/5000_nodes.yaml', '--test-cmd-name=ClusterLoaderV2', '--timeout=420m', '--logexporter-gcs-path=gs://k8s-infra-scalability-tests-logs/ci-kubernetes-e2e-gce-scale-performance/1715775341034737664')' returned non-zero exit status 1.
+ EXIT_VALUE=1
+ set +o xtrace
client_loop: send disconnect: Broken pipe
/usr/bin/scp: Connection closed
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [255].
ERROR: (gcloud.compute.scp) Could not fetch resource:
 - The resource 'projects/k8s-infra-e2e-scale-5k-project/zones/us-east1-b/instances/gce-scale-cluster-master' was not found

ERROR: (gcloud.compute.scp) Could not fetch resource:
 - The resource 'projects/k8s-infra-e2e-scale-5k-project/zones/us-east1-b/instances/gce-scale-cluster-master' was not found

ERROR: (gcloud.compute.scp) Could not fetch resource:
 - The resource 'projects/k8s-infra-e2e-scale-5k-project/zones/us-east1-b/instances/gce-scale-cluster-master' was not found

ERROR: (gcloud.compute.scp) Could not fetch resource:
 - The resource 'projects/k8s-infra-e2e-scale-5k-project/zones/us-east1-b/instances/gce-scale-cluster-master' was not found
```

**Comment by tosi3k** [comment]
@pacoxu the job still has old version of the `kubekins-e2e` image that holds the `log-dump.sh` file from test-infra: `gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231015-d38ebb23ab-master`.

We need to expedite the submission of https://github.com/kubernetes/test-infra/pull/31061 to get more debug logs.

**Comment by reetasingh** [comment]
looks like https://github.com/kubernetes/test-infra/pull/31061 is merged.
debug logs shows
```
ooglecloudsdk.command_lib.util.ssh.ssh.CommandError: [/usr/bin/scp] exited with return code [255].
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [255].
DEBUG: Running [gcloud.compute.scp] with arguments: [--project: "k8s-infra-e2e-scale-5k-project", --recurse: "True", --verbosity: "debug", --zone: "us-east1-b", [[USER@]INSTANCE:]DEST: "/tmp/tmp.PXjtIG24hA/logs/gce-scale-cluster-master", [[USER@]INSTANCE:]SRC:1: "['gce-scale-cluster-master:/var/log/kube-scheduler.log*']"]
DEBUG: Starting new HTTPS connection (1): compute.googleapis.com:443
DEBUG: [https://compute.googleapis.com:443](https://compute.googleapis.com/) "GET /compute/v1/projects/k8s-infra-e2e-scale-5k-project/zones/us-east1-b/instances/gce-scale-cluster-master?alt=json HTTP/1.1" 404 None
DEBUG: Chosen display Format:list[title="Could not fetch resource:",always-display-title]
DEBUG: (gcloud.compute.scp) Could not fetch resource:
16 skipped lines...
  File "/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 148, in RaiseException
    raise exception(
googlecloudsdk.calliope.exceptions.ToolException: Could not fetch resource:
 - The resource 'projects/k8s-infra-e2e-scale-5k-project/zones/us-east1-b/instances/gce-scale-cluster-master' was not found
ERROR: (gcloud.compute.scp) Could not fetch resource:
 - The resource 'projects/k8s-infra-e2e-scale-5k-project/zones/us-east1-b/instances/gce-scale-cluster-master' was not found
DEBUG: Running [gcloud.compute.scp] with arguments: [--project: "k8s-infra-e2e-scale-5k-project", --recurse: "True", --verbosity: "debug", --zone: "us-east1-b", [[USER@]INSTANCE:]DEST: "/tmp/tmp.PXjtIG24hA/logs/gce-scale-cluster-master", [[USER@]INSTANCE:]SRC:1: "['gce-scale-cluster-master:/var/log/cloud-controller-manager.log*']"]
DEBUG: Starting new HTTPS connection (1): compute.googleapis.com:443
DEBUG: [https://compute.googleapis.com:443](https://compute.googleapis.com/) "GET /compute/v1/projects/k8s-infra-e2e-scale-5k-project/zones/us-east1-b/instances/gce-scale-cluster-master?alt=json HTTP/1.1" 404 None
18 skipped lines...
  File "/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 148, in RaiseException
    raise exception(
googlecloudsdk.calliope.exceptions.ToolException: Could not fetch resource:
 - The resource 'projects/k8s-infra-e2e-scale-5k-project/zones/us-east1-b/instances/gce-scale-cluster-master' was not found
 - ```

**Comment by Vyom-Yadav** [comment]
Are we dumping the logs at the correct time? As far as I can see the logs, we are deleting the cluster before dumping the logs, hence 404
```
Updated [https://www.googleapis.com/compute/v1/projects/k8s-infra-e2e-scale-5k-project/zones/us-east1-b/instances/gce-scale-cluster-master].
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-infra-e2e-scale-5k-project/zones/us-east1-b/instances/gce-scale-cluster-master].
```
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1716500123258720256

**Comment by Argh4k** [comment]
I think this is not an issue, the logs that you posted are after:
```
DEBUG: Running command [/usr/bin/scp -r -i /workspace/.ssh/google_compute_engine -o CheckHostIP=no -o HashKnownHosts=no -o HostKeyAlias=compute.6267328027929810602 -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/workspace/.ssh/google_compute_known_hosts prow@34.75.126.154:/var/log/kube-apiserver.log* /tmp/tmp.PXjtIG24hA/logs/gce-scale-cluster-master].
DEBUG: Executing command: ['/usr/bin/scp', '-r', '-i', '/workspace/.ssh/google_compute_engine', '-o', 'CheckHostIP=no', '-o', 'HashKnownHosts=no', '-o', 'HostKeyAlias=compute.6267328027929810602', '-o', 'IdentitiesOnly=yes', '-o', 'StrictHostKeyChecking=yes', '-o', 'UserKnownHostsFile=/workspace/.ssh/google_compute_known_hosts', 'prow@34.75.126.154:/var/log/kube-apiserver.log*', '/tmp/tmp.PXjtIG24hA/logs/gce-scale-cluster-master']
2023/10/24 00:03:51 process.go:199: Interrupt after 7h0m0s timeout during /workspace/log-dump.sh /logs/artifacts gs://k8s-infra-scalability-tests-logs/ci-kubernetes-e2e-gce-scale-performance/1716500123258720256. Will terminate in another 15m
```

**Comment by reetasingh** [comment]
similar issue observed with another test https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1718311964112850944 but the logs look a bit different, this one is not failing with 404 error 
```
debug1: Sending subsystem: sftp
debug1: pledge: fork
/usr/bin/scp: debug1: Fetching /var/log/etcd.log to /tmp/tmp.gsbMp65qMj/logs/gce-scale-cluster-master

/usr/bin/scp: open local "/tmp/tmp.gsbMp65qMj/logs/gce-scale-cluster-master": No such file or directory
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 3700, received 6280 bytes, in 0.5 seconds
Bytes per second: sent 7749.7, received 13153.6
debug1: Exit status 0
DEBUG: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
Traceback (most recent call last):
  File "/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 807, in Run
    resources = command_instance.Run(args)
  File "/google-cloud-sdk/lib/surface/compute/scp.py", line 185, in Run
    return scp_helper.RunScp(
  File "/google-cloud-sdk/lib/googlecloudsdk/command_lib/compute/scp_utils.py", line 227, in RunScp
    cmd.Run(
  File "/google-cloud-sdk/lib/googlecloudsdk/command_lib/util/ssh/ssh.py", line 1995, in Run
    raise CommandError(args[0], return_code=status)
googlecloudsdk.command_lib.util.ssh.ssh.CommandError: [/usr/bin/scp] exited with return code [1].
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
Deleted [https://www.googleapis.com/compute/v1/projects/k8s-infra-e2e-scale-5k-project/global/firewalls/gce-scale-cluster-minion-http-alt].
DEBUG: Running [gcloud.compute.scp] with arguments: [--project: "k8s-infra-e2e-scale-5k-project", --recurse: "True", --scp-flag: "['-v']", --verbosity: "debug", --zone: "us-east1-b", [[USER@]INSTANCE:]DEST: "/tmp/tmp.gsbMp65qMj/logs/gce-scale-cluster-master", [[USER@]INSTANCE:]SRC:1: "['gce-scale-cluster-master:/var/log/etcd-events.log*']"]
DEBUG: Starting new HTTPS connection (1): compute.googleapis.com:443
DEBUG: [https://compute.googleapis.com:443](https://compute.googleapis.com/) "GET /compute/v1/projects/k8s-infra-e2e-scale-5k-project/zones/us-east1-b/instances/gce-scale-cluster-master?alt=json HTTP/1.1" 200 None
DEBUG: Starting new HTTPS connection (1): compute.googleapis.com:443
DEBUG: [https://compute.googleapis.com:443](https://compute.googleapis.com/) "GET /compute/v1/projects/k8s-infra-e2e-scale-5k-project?alt=json HTTP/1.1" 200 None
```

**Comment by Vyom-Yadav** [comment]
As the Alpha 3 release cut is approaching (2nd Nov)
/priority critical-urgent

**Comment by pacoxu** [comment]
/close
green now.

Fixed by https://github.com/kubernetes/test-infra/pull/31155

**Comment by pacoxu** [comment]
/reopen

> Honestly, that is a run where I broke master log dump. It doesn't contain https://github.com/kubernetes/test-infra/pull/31162 yet, so it works, but doesn't have the logs we want

> Tbh I believe it will fail again. We didn't fix anything yet, we just tried to understand what exactly was going wrong, and I believe we have a decent understanding that the scp can't keep up with apiserver logs, but we don't know why yet


This is still with problem uploading the log.

**Comment by pacoxu** [comment]
DumpClusterLogs now fails https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-scalability-100 as well.

This is a master-blocking issue now.

**Comment by pacoxu** [comment]
CI `gce-cos-master-scalability-100` is fixed by  https://github.com/kubernetes/test-infra/pull/31197. (recent 4 run: 3 passed.)

Thanks @aojea for the comment below.
> it seems 
[@wojtekt](https://kubernetes.slack.com/team/U09R30ANQ)
 has a clue, and is related to the bump on the images https://github.com/kubernetes/test-infra/commit/392423fd1037f1b17463e0148087655f48c0d810, since the logdump seems to not get the names of the nodes and is using the wrong url to try to get the node logs

**Comment by pacoxu** [comment]
I did a simple compare of 
- 11-01 success run: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1719742840218587136
- 10-16 success run:https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1713600917149847552

The log file number in artifacts and size are similar.  

After https://github.com/kubernetes/test-infra/pull/31121 was merged, there are also some debug logs in recent runs. Is that help?  I think we can already get the debug log in CI failure like https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1721211126902951936.


I would prefer to merge https://github.com/kubernetes/test-infra/pull/31200. @argh4k @dims

**Comment by pacoxu** [comment]
https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-performance 

It seems that https://github.com/kubernetes/test-infra/pull/31254 fix the problem

/close
