### ISSUE TITLE
Panic in statefulset controller

### ISSUE THREAD

**Issue by elias-dbx** [kubernetes/kubernetes#121336]
### What happened?

The statefulset controller started intermittently panicing with the follow stack trace:
```
fatal error: concurrent map writes

goroutine 15081 [running]:
k8s.io/kubernetes/pkg/controller/statefulset.getPersistentVolumeClaims(0xc0b3743900, 0xc0c3da8480?)
        pkg/controller/statefulset/stateful_set_utils.go:348 +0x2fd
k8s.io/kubernetes/pkg/controller/statefulset.(*StatefulPodControl).PodClaimIsStale(0xc001ec8160, 0x43ebb9f?, 0x18?)
        pkg/controller/statefulset/stateful_pod_control.go:268 +0x91
k8s.io/kubernetes/pkg/controller/statefulset.(*defaultStatefulSetControl).processReplica(0xc001e86f40, {0x4a183e0, 0xc00082eeb0}, 0xc0b3743900, 0xc0022c6e00, 0xc0022c6cc8, 0xc32354b440?, 0xc0b132f500?, 0x0, {0xc23d776f00, ...}, ...)
        pkg/controller/statefulset/stateful_set_control.go:399 +0x3f6
k8s.io/kubernetes/pkg/controller/statefulset.(*defaultStatefulSetControl).updateStatefulSet.func1(0xc00082eeb0?)
        pkg/controller/statefulset/stateful_set_control.go:626 +0x65
k8s.io/kubernetes/pkg/controller/statefulset.slowStartBatch.func1(0x5?)
        pkg/controller/statefulset/stateful_set_control.go:292 +0x68
created by k8s.io/kubernetes/pkg/controller/statefulset.slowStartBatch
        pkg/controller/statefulset/stateful_set_control.go:289 +0x16a
```

### What did you expect to happen?

the statefulset controller doesn't panic

### How can we reproduce it (as minimally and precisely as possible)?

Run a large amount of persistent volume claims (over 1000) which share the same statefulset

### Anything else we need to know?

This appears to be due to the PVC labels being shared between different objects? The frequency of panics appears to be correlated with a higher number of PVCs.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.5", GitCommit:"93e0d7146fb9c3e9f68aa41b2b4265b2fcdb0a4c", GitTreeState:"clean", BuildDate:"2001-09-09T01:46:40Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.5", GitCommit:"93e0d7146fb9c3e9f68aa41b2b4265b2fcdb0a4c", GitTreeState:"clean", BuildDate:"2001-09-09T01:46:40Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
on-prem
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
# paste output here
$ uname -a
Linux 5.15.0-39-generic #42-Ubuntu SMP Thu Jun 9 23:42:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
sounds a duplicate of https://github.com/kubernetes/kubernetes/issues/121053

**Comment by elias-dbx** [comment]
Yes, that is the same issue. I searched the issue tracker around the end of September when we initially had the panics which was before #121053 

I will close this since this appears to be the exact same issue.
