### ISSUE TITLE
failing-test: TestStoreDeleteCollectionWithContextCancellation

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#121627]
### Which jobs are failing?

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-unit

### Which tests are failing?

various

### Since when has it been failing?

Oct 30 2023 6pm pst

### Reason for failure (if possible)

Looks like different test are failing with connection timeout errors:
```
W1031 01:57:48.321545   61587 logging.go:59] [core] [Channel #244 SubChannel #246] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:43189", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:43189: connect: connection refused"
```

One of the tests triggered a core dump:
```
=== FAIL: pkg/kubelet/eviction TestManagerWithLocalStorageCapacityIsolationOpen (0.00s)
E1031 02:05:51.095814   44218 helpers.go:677] "Eviction manager: failed to construct signal" err="system container \"pods\" not found in metrics" signal="allocatableMemory.available"
I1031 02:05:51.095898   44218 helpers.go:750] "Eviction manager: no observation found for eviction signal" signal="allocatableMemory.available"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2bbae9b]
goroutine 140 [running]:
testing.tRunner.func1.2({0x2dfa500, 0x49e4720})
	/usr/local/go/src/testing/testing.go:1545 +0x366
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1548 +0x630
panic({0x2dfa500?, 0x49e4720?})
	/usr/local/go/src/runtime/panic.go:920 +0x270
k8s.io/kubernetes/pkg/kubelet/eviction.(*managerImpl).evictPod(0xc0007754a0, {0x35a4a78, 0x4a53e80}, 0xc000964000, 0x0, {0xc000061040, 0x43}, 0x8?, 0x0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go:591 +0xa7b
k8s.io/kubernetes/pkg/kubelet/eviction.(*managerImpl).emptyDirLimitEviction(0xc000964000?, {{{0x30ffd3d, 0x9}, {0x0, 0x0}, {0x30ffd3d, 0x9}}, {{0x0, 0x0, 0x0}}, ...}, ...)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go:514 +0x716
k8s.io/kubernetes/pkg/kubelet/eviction.(*managerImpl).localStorageEviction(0xc000775518?, {0xc0000840a0, 0x3, 0x0?}, 0xc0008f2400)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go:484 +0x1e8
k8s.io/kubernetes/pkg/kubelet/eviction.(*managerImpl).synchronize(0xc0007754a0, {0x3580c80, 0xc00039565f}, 0xc0007e1870)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go:336 +0x16f3
k8s.io/kubernetes/pkg/kubelet/eviction.TestManagerWithLocalStorageCapacityIsolationOpen(0xc000751520)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager_test.go:2028 +0x1051
testing.tRunner(0xc000751520, 0x3229210)
	/usr/local/go/src/testing/testing.go:1595 +0x239
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1648 +0x82b
```

### Relevant SIG(s)

/sig

**Comment by charles-chenzz** [comment]
#121321 #121628 are both suffers from pkg/registry 
```
W1031 01:57:48.321545   61587 logging.go:59] [core] [Channel #244 SubChannel #246] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:43189", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:43189: connect: connection refused"
```

and #121210 is from compoent-base, which likely same reason from ``connection refused``

**Comment by neolit123** [comment]
/retitle failing-test: pkg/kubelet/eviction TestManagerWithLocalStorageCapacityIsolationOpen

**Comment by msau42** [comment]
TestManagerWithLocalStorageCapacityIsolationOpen only failed in one of the PRs, so I don't think that specific test is the problem.

**Comment by neolit123** [comment]
ok, rename as see fit.
just put owning sigs please for triage.

**Comment by msau42** [comment]
TestStoreDeleteCollectionWithContextCancellation is the one that seems to be failing across all the failing PRs, so let's start there first.

/retitle failing-test: TestStoreDeleteCollectionWithContextCancellation
/sig api-machinery

**Comment by liggitt** [comment]
image used in the unit test job didn't change around the timeframe this was seen (https://github.com/kubernetes/test-infra/commits/master/config/jobs/kubernetes/sig-testing/make-test.yaml)

**Comment by liggitt** [comment]
looking for jumps in package unit test runtimes to see if something is taking longer or stressing the system:

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit&graph-metrics=test-duration-minutes&width=5

![image](https://github.com/kubernetes/kubernetes/assets/980082/9a1ccd25-2a75-4c91-9988-4897196d1b05)

#121310 - cc @enj @nilekhc

![image](https://github.com/kubernetes/kubernetes/assets/980082/9dd2031f-0dbc-4427-8911-10ed7f066fdb)

#119208 - cc @atosatto @soltysh 

![image](https://github.com/kubernetes/kubernetes/assets/980082/e9ca6140-8143-4022-81a2-5435b41b79a4)

#121609 - cc @neolit123 

Could any of those have introduced changes that could be stressing or exhausting listener connections in unit tests?

**Comment by neolit123** [comment]
> https://github.com/kubernetes/kubernetes/pull/121609 - cc @neolit123
> Could any of those have introduced changes that could be stressing or exhausting listener connections in unit tests?

the PR in question introduced a poll function around an API call that is unit tested with a fake client. the poll is unit tested, but the fake client has reactors that return error or success right away, so in theory the poll should not be stretched to >1 retries with >1 connections per fake client.

while testing locally i did not notice any significant time difference after https://github.com/kubernetes/kubernetes/pull/121609 or the prior https://github.com/kubernetes/kubernetes/pull/121305.

i can do some more checks to see what's going on.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/121614 merged right at the time the flakes were seen

DeleteCollection invokes List, which was modified in that PR to cancel more aggressively

cc @HirazawaUi @wojtek-t

**Comment by liggitt** [comment]
I can reproduce about a 10-20% flake rate at HEAD with:
```
go test -c -race k8s.io/apiserver/pkg/registry/generic/registry
GOMAXPROCS=4 stress ./registry.test
```

failures look like:
```
W1031 11:13:15.329997   39058 logging.go:59] [core] [Channel #4 SubChannel #6] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:59490", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:59490: connect: connection refused"
W1031 11:13:16.123446   39058 logging.go:59] [core] [Channel #24 SubChannel #26] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:59617", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:59617: connect: connection refused"
W1031 11:13:16.332973   39058 logging.go:59] [core] [Channel #4 SubChannel #6] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:59490", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:59490: connect: connection refused"
W1031 11:13:17.125098   39058 logging.go:59] [core] [Channel #24 SubChannel #26] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:59617", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:59617: connect: connection refused"
W1031 11:13:18.023311   39058 logging.go:59] [core] [Channel #4 SubChannel #6] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:59490", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:59490: connect: connection refused"
W1031 11:13:18.966532   39058 logging.go:59] [core] [Channel #24 SubChannel #26] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:59617", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:59617: connect: connection refused"
W1031 11:13:20.372743   39058 logging.go:59] [core] [Channel #4 SubChannel #6] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:59490", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:59490: connect: connection refused"
W1031 11:13:21.848063   39058 logging.go:59] [core] [Channel #24 SubChannel #26] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:59617", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:59617: connect: connection refused"
W1031 11:13:24.814228   39058 logging.go:59] [core] [Channel #4 SubChannel #6] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:59490", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:59490: connect: connection refused"
W1031 11:13:26.252181   39058 logging.go:59] [core] [Channel #24 SubChannel #26] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:59617", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:59617: connect: connection refused"
W1031 11:13:30.601846   39058 logging.go:59] [core] [Channel #4 SubChannel #6] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:59490", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:59490: connect: connection refused"
W1031 11:13:32.002287   39058 logging.go:59] [core] [Channel #24 SubChannel #26] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:59617", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:59617: connect: connection refused"
W1031 11:13:37.089957   39058 logging.go:59] [core] [Channel #53 SubChannel #54] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:59708", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:59708: operation was canceled"
W1031 11:13:37.091220   39058 logging.go:59] [core] [Channel #44 SubChannel #46] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:59708", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:59708: connect: connection refused"
--- FAIL: TestDryRunCreateExistingObjectFails (21.01s)
    dryrun_test.go:44: Error creating storage: context deadline exceeded
```
or
```
W1031 11:22:09.802401   41544 logging.go:59] [core] [Channel #944 SubChannel #946] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:49712", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:49712: connect: connection refused"
W1031 11:22:10.072708   41544 logging.go:59] [core] [Channel #864 SubChannel #866] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:65466", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:65466: connect: connection refused"
W1031 11:22:10.081830   41544 logging.go:59] [core] [Channel #1004 SubChannel #1007] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:50356", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:50356: connect: connection refused"
W1031 11:22:10.088927   41544 logging.go:59] [core] [Channel #1024 SubChannel #1026] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:50515", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:50515: connect: connection refused"
W1031 11:22:10.094246   41544 logging.go:59] [core] [Channel #384 SubChannel #386] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:60365", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:60365: connect: connection refused"
W1031 11:22:10.107777   41544 logging.go:59] [core] [Channel #624 SubChannel #626] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:62679", ServerName: "localhost", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:62679: connect: connection refused"
--- FAIL: TestStoreDeleteCollectionWithContextCancellation (1.02s)
    store_test.go:2218: Unexpected error: The list operation against pods.example.apiserver.k8s.io could not be completed at this time, please try again.
```

while testing that package with `stress`, I see ~1300-1500 open connections with this:
```
watch 'netstat -an | grep 127.0.0.1 | wc -l'
```

**Comment by wojtek-t** [comment]
> https://github.com/kubernetes/kubernetes/pull/121614 merged right at the time the flakes were seen

Let's revert it then. I looked into it and I don't know from a quick glance why it's failing and I don't have time to debug it now.
I opened https://github.com/kubernetes/kubernetes/pull/121646

**Comment by HirazawaUi** [comment]
> Let's revert it then.

Okay, it looks like we need more debugging to open this PR

**Comment by neolit123** [comment]
> > #121609 - cc @neolit123
> > Could any of those have introduced changes that could be stressing or exhausting listener connections in unit tests?
> 
> the PR in question introduced a poll function around an API call that is unit tested with a fake client i.e. the poll is unit tested, but the fake client has reactors that return error or success right away, so in theory the poll should not be stretched to >1 retries with >1 connection attempts per fake client.
> 
> while testing locally i did not notice any significant time difference after #121609 or the prior #121305.
> 
> i can do some more checks to see what's going on.

one optimization to strip some ~40 fake client connections and 2 seconds from a test:
https://github.com/kubernetes/kubernetes/pull/121648

**Comment by liggitt** [comment]
> > #121614 merged right at the time the flakes were seen
> 
> Let's revert it then. I looked into it and I don't know from a quick glance why it's failing and I don't have time to debug it now. I opened #121646

sounds good, `git bisect` pointed at that commit as well
