### ISSUE TITLE
[Failing Test] (ci-kubernetes-e2e-gce-cos-k8sbeta-alphafeatures) error during ./hack/e2e-internal/e2e-up.sh: exit status 2

### ISSUE THREAD

**Issue by reetasingh** [kubernetes/kubernetes#122012]
### Which jobs are failing?

https://testgrid.k8s.io/sig-release-1.29-blocking#gce-cos-k8sbeta-alphafeatures

### Which tests are failing?

kubetest.Up

### Since when has it been failing?

Nov 22 2023, last 7 runs failed

### Reason for failure (if possible)

```
2023/11/22 23:10:41 process.go:155: Step './hack/e2e-internal/e2e-down.sh' finished in 4m0.265724182s
2023/11/22 23:10:41 process.go:96: Saved XML output to /logs/artifacts/junit_runner.xml.
2023/11/22 23:10:41 main.go:324: Something went wrong: starting e2e cluster: error during ./hack/e2e-internal/e2e-up.sh: exit status 2
Traceback (most recent call last):
  File "/workspace/scenarios/kubernetes_e2e.py", line 391, in <module>
    main(parse_args())
  File "/workspace/scenarios/kubernetes_e2e.py", line 307, in main
    mode.start(runner_args)
  File "/workspace/scenarios/kubernetes_e2e.py", line 136, in start
    check_env(env, self.command, *args)
  File "/workspace/scenarios/kubernetes_e2e.py", line 57, in check_env
    subprocess.check_call(cmd, env=env)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('kubetest', '--dump=/logs/artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--provider=gce', '--cluster=test-eef92b583b', '--gcp-network=test-eef92b583b', '--check-leaked-resources', '--gcp-zone=us-west1-b', '--gcp-node-image=gci', '--extract=ci/latest-1.29', '--extract-ci-bucket=k8s-release-dev', '--timeout=180m', '--runtime-config=api/all=true', '--test_args=--ginkgo.focus=\\[Feature:(Audit|BlockVolume|PodPreset|ExpandCSIVolumes|ExpandInUseVolumes)\\]|Networking --ginkgo.skip=\\[Feature:(SCTPConnectivity|Volumes|Networking-Performance|Networking-IPv6)\\]|csi-hostpath-v0 --minStartupPods=8')' returned non-zero exit status 1.
+ EXIT_VALUE=1
+ set +o xtrace
```

### Relevant SIG(s)

/sig

**Comment by pacoxu** [comment]
APIServer failed for
> E1123 00:06:01.636838      10 run.go:74] "command failed" err="[when using --cloud-provider set to 'external', please set DisableCloudProviders feature to true, when using --cloud-provider set to 'external', please set DisableKubeletCloudCredentialProviders feature to true]"

**Comment by kumarankit999** [comment]
Yes it is failing for me too!

**Comment by neolit123** [comment]
> APIServer failed for #117503.
> 
> > E1123 00:06:01.636838      10 run.go:74] "command failed" err="[when using --cloud-provider set to 'external', please set DisableCloudProviders feature to true, when using --cloud-provider set to 'external', please set DisableKubeletCloudCredentialProviders feature to true]"

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sbeta-alphafeatures/1727567558883676160/artifacts/test-eef92b583b-master/kube-apiserver.log

https://github.com/kubernetes/test-infra/pull/31294
@jeremyrickard @xmudrii @dims 

the generator config source must include the env to handle the "external" provider deprecation:
https://github.com/kubernetes/test-infra/blob/36a7c91fffc75a3bc9dd8d18a6a6471e7b3a9527/config/jobs/kubernetes/sig-cloud-provider/gcp/gcp-gce.yaml#L578C1-L580C50

/sig cloud-provider
/area provider/gcp

**Comment by neolit123** [comment]
> https://testgrid.k8s.io/sig-release-1.29-blocking#gce-cos-k8sbeta-alphafeatures

all other jobs seem green in the 1.29 blocking/informing, post that change.

> the generator config source must include the env to handle the "external" provider deprecation:

i will try sending a PR for this, but you need to find a non-USA approver if you want it merged before Monday.
/assign

**Comment by neolit123** [comment]
never mind, the generator is giving me errors:

```bash
k8s.io/test-infra/releng$ make generate-tests
...
[notice] A new release of pip is available: 23.0.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
../hack/run-in-python-container.sh ./releng/generate_tests.py ""
Traceback (most recent call last):
  File "/home/lubo/go/src/k8s.io/test-infra/./releng/generate_tests.py", line 425, in <module>
    main(
  File "/home/lubo/go/src/k8s.io/test-infra/./releng/generate_tests.py", line 391, in main
    with open(yaml_config_path) as fp:
TypeError: expected str, bytes or os.PathLike object, not NoneType
make: *** [Makefile:26: generate-tests] Error 1
```

/unassign

**Comment by pacoxu** [comment]
/cc @kubernetes/ci-signal 
https://testgrid.k8s.io/sig-release-1.29-blocking#gce-cos-k8sbeta-alphafeatures
