### ISSUE TITLE
[Failing Test]  capz-windows-master ci-kubernetes-e2e-capz-master-windows.Overall 

### ISSUE THREAD

**Issue by zelenushechka** [kubernetes/kubernetes#122896]
### Which jobs are failing?

https://testgrid.k8s.io/sig-release-master-informing#capz-windows-master

### Which tests are failing?

ERROR: ✗ Failed to create Azure management cluster with AKS E0121 07:29:10.833272     816 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-windows/1748970609603252224
panic: Timed out after 180.001s. ERROR: Kubeconfig wasn't available after waiting 5 minutes. - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-windows/1748925058992050176
ERROR: Unable to get AAD authorization tokens with message: 2024-01-21 10:41:43.159217 An error occurred: CONNECTIVITY_TOOMANYREQUESTS_ERROR - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-windows/1749016160327700480
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-windows/1747745023220256768

### Since when has it been failing?

01-21

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#capz-windows-master

### Reason for failure (if possible)

{ failed [FAILED] failed to wait for definition "com.example.crd-publish-openapi-test-foo.v1.e2e-test-crd-publish-openapi-2548-crd" not to be served anymore: failed to wait for OpenAPI spec validating condition: Get "https://capz-conf-dfvfkt-dc763dd5.uksouth.cloudapp.azure.com:6443/openapi/v2": dial tcp 172.165.149.19:6443: i/o timeout; lastMsg: 
In [It] at: k8s.io/kubernetes/test/e2e/apimachinery/crd_publish_openapi.go:142 @ 01/18/24 04:41:07.392
}
{ failed [FAILED] error running /usr/local/bin/kubectl --kubeconfig=/home/prow/go/src/sigs.k8s.io/windows-testing/capz/capz-conf-dfvfkt.kubeconfig --namespace=kubectl-8837 get pods update-demo-nautilus-sm7q6 -o template --template={{if (exists . "spec" "containers")}}{{range .spec.containers}}{{if eq .name "update-demo"}}{{.image}}{{end}}{{end}}{{end}}:
Command stdout:

stderr:
Unable to connect to the server: dial tcp 172.165.149.19:6443: i/o timeout

### Relevant SIG(s)

/sig windows

**Comment by pacoxu** [comment]
/sig windows
/area provider/azure
for https://github.com/kubernetes-sigs/cluster-api-provider-azure?

The CI becomes green now. 

```
Failed to get logs for Machine capz-conf-ylv40c-md-win-vl27m-6zsjs, Cluster default/capz-conf-ylv40c: [dialing public load balancer at : dial tcp :22: connect: connection refused, Unable to collect VM Boot Diagnostic logs: AzureMachine provider ID is nil]
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
	>  goroutine 1 [running]:
	>  runtime/debug.Stack()
	>  	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
	>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	>  	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/log/log.go:60 +0xcd
	>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithName(0xc000332e80, {0x37a3a79, 0x14})
	>  	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/log/deleg.go:147 +0x45
	>  github.com/go-logr/logr.Logger.WithName({{0x3b8f240, 0xc000332e80}, 0x0}, {0x37a3a79?, 0x0?})
	>  	/home/prow/go/pkg/mod/github.com/go-logr/logr@v1.3.0/logr.go:349 +0x3d
	>  sigs.k8s.io/controller-runtime/pkg/client.newClient(0x12d2a1a?, {0x0, 0xc000633b20, {0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0})
	>  	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/client/client.go:122 +0xec
	>  sigs.k8s.io/controller-runtime/pkg/client.New(0x31e0140?, {0x0, 0xc000633b20, {0x0, 0x0}, 0x0, {0x0, 0x0}, 0x0})
	>  	/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/client/client.go:103 +0x7d
	>  sigs.k8s.io/cluster-api/test/framework.(*clusterProxy).GetClient.func1({0x136d0a0?, 0xc0002fa1d0?})
	>  	/home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.5.5/framework/cluster_proxy.go:200 +0x79
	>  k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func1(0x10?, {0x3b88fe0?, 0xc0002fa1c0?})
	>  	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/loop.go:49 +0x52
	>  k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext({0x3b88fe0, 0xc0002fa1c0}, {0x3b7d028?, 0xc00003da80}, 0x1, 0x0, 0x0?)
	>  	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/loop.go:50 +0xdf
	>  k8s.io/apimachinery/pkg/util/wait.PollUntilContextTimeout({0x3b88f00?, 0x52722c0?}, 0xb2d05e00, 0xc000370f00?, 0x20?, 0x13cf4ac?)
	>  	/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.28.3/pkg/util/wait/poll.go:48 +0x98
	>  sigs.k8s.io/cluster-api/test/framework.(*clusterProxy).GetClient(0xc000866ae0)
	>  	/home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.5.5/framework/cluster_proxy.go:199 +0xbe
	>  sigs.k8s.io/cluster-api/test/framework.(*clusterProxy).CollectWorkloadClusterLogs(0xc000866ae0, {0x3b88f00?, 0x52722c0}, {0x7ffc447e1e66, 0x7}, {0x7ffc447e1e49, 0x10}, {0xc0001f4990, 0x29})
	>  	/home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.5.5/framework/cluster_proxy.go:310 +0x367
	>  sigs.k8s.io/cluster-api-provider-azure/test/e2e.(*AzureClusterProxy).CollectWorkloadClusterLogs(0xc000619ec0, {0x3b88f00, 0x52722c0}, {0x7ffc447e1e66, 0x7}, {0x7ffc447e1e49, 0x10}, {0xc0001f4990, 0x29})
	>  	/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_clusterproxy.go:94 +0x14b
	>  main.main()
	>  	/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/logger.go:74 +0x612
  Jan 21 04:45:36.745: INFO: Unable to collect logs as node doesn't have addresses
  Jan 21 04:45:36.746: INFO: Collecting logs for Windows node capz-conf-ylv40c-md-win-f8wj6 in cluster capz-conf-ylv40c in namespace default
  Jan 21 04:49:36.751: INFO: Attempting to copy file /c:/crashdumps.tar on node capz-conf-ylv40c-md-win-f8wj6 to /logs/artifacts/clusters/capz-conf-ylv40c/machines/capz-conf-ylv40c-md-win-vl27m-7qn4f/crashdumps.tar
  Jan 21 04:49:36.752: INFO: Collecting boot logs for AzureMachine capz-conf-ylv40c-md-win-f8wj6
Failed to get logs for Machine capz-conf-ylv40c-md-win-vl27m-7qn4f, Cluster default/capz-conf-ylv40c: [dialing public load balancer at : dial tcp :22: connect: connection refused, Unable to collect VM Boot Diagnostic logs: AzureMachine provider ID is nil]
  Jan 21 04:49:36.906: INFO: Dumping workload cluster default/capz-conf-ylv40c nodes
panic: Timed out after 180.001s.
Failed to get default/capz-conf-ylv40c-kubeconfig
Expected success, but got an error:
    <*errors.StatusError | 0xc0009b0640>: 
    secrets "capz-conf-ylv40c-kubeconfig" not found
    {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "secrets \"capz-conf-ylv40c-kubeconfig\" not found",
            Reason: "NotFound",
            Details: {
                Name: "capz-conf-ylv40c-kubeconfig",
                Group: "",
                Kind: "secrets",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    }
goroutine 1 [running]:
main.Fail({0xc00031ae00?, 0x12?}, {0xc000705500?, 0x3?, 0x3?})
	/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/logger.go:36 +0x27
github.com/onsi/gomega/internal.(*AsyncAssertion).match.func3({0x378a4d9, 0x9})
	/home/prow/go/pkg/mod/github.com/onsi/gomega@v1.30.0/internal/async_assertion.go:478 +0x1cd
github.com/onsi/gomega/internal.(*AsyncAssertion).match(0xc00067a770, {0x3b769f8?, 0x52722c0}, 0x1, {0xc0005d7c80, 0x2, 0x2})
	/home/prow/go/pkg/mod/github.com/onsi/gomega@v1.30.0/internal/async_assertion.go:560 +0xdae
github.com/onsi/gomega/internal.(*AsyncAssertion).Should(0xc00067a770, {0x3b769f8, 0x52722c0}, {0xc0005d7c80, 0x2, 0x2})
	/home/prow/go/pkg/mod/github.com/onsi/gomega@v1.30.0/internal/async_assertion.go:145 +0x86
sigs.k8s.io/cluster-api/test/framework.(*clusterProxy).getKubeconfig(0xc00007bf40?, {0x3b88f00?, 0x52722c0}, {0x7ffc447e1e66, 0x7}, {0x7ffc447e1e49, 0x10})
	/home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.5.5/framework/cluster_proxy.go:389 +0x2c9
sigs.k8s.io/cluster-api/test/framework.(*clusterProxy).GetWorkloadCluster(0xc000866ae0, {0x3b88f00?, 0x52722c0}, {0x7ffc447e1e66, 0x7}, {0x7ffc447e1e49, 0x10})
	/home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.5.5/framework/cluster_proxy.go:[284](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-windows/1748925058992050176#1:build-log.txt%3A284) +0x1f7
sigs.k8s.io/cluster-api-provider-azure/test/e2e.(*AzureClusterProxy).collectNodes(0x378160d?, {0x3b88f00, 0x52722c0}, {0x7ffc447e1e66?, 0xc000953d28?}, {0x7ffc447e1e49?, 0x2?}, {0xc0001f4990, 0x29})
	/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_clusterproxy.go:198 +0x5a
sigs.k8s.io/cluster-api-provider-azure/test/e2e.(*AzureClusterProxy).CollectWorkloadClusterLogs(0xc000619ec0, {0x3b88f00, 0x52722c0}, {0x7ffc447e1e66, 0x7}, {0x7ffc447e1e49, 0x10}, {0xc0001f4990, 0x29})
	/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/azure_clusterproxy.go:100 +0x274
main.main()
	/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/logger.go:74 +0x612
exit status 2
/home/prow/go/src/sigs.k8s.io/windows-testing
```

/cc @jackfrancis

**Comment by jsturtevant** [comment]
Took a look at the report. There was an general issue with Azure deployments on Jan 21, which has been resolved.  I am going to close this issue.  Feel free to ping sig-windows in slack as well in case we miss the issue notification.

/close
