### ISSUE TITLE
runtime.ToUnstructured: panics for nil slice in map

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#123556]
### What happened?

I'm implementing a new API (see https://github.com/kubernetes/kubernetes/pull/123516). Part of that API is a one-of-many struct which contains as one option a slice. Empty or nil slice are different from "field not set", so I need to use a pointer. Because gogo/protobuf has a problem handling `*[]string`, I'm using a wrapper struct.

With those types, encoding as unstructured fails:
```
panic: reflect: reflect.Value.Set using unaddressable value [recovered]
	panic: reflect: reflect.Value.Set using unaddressable value

goroutine 89 [running]:
testing.tRunner.func1.2({0x9e5ba0, 0xc000037030})
	/nvme/gopath/go-1.21.0/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
	/nvme/gopath/go-1.21.0/src/testing/testing.go:1548 +0x397
panic({0x9e5ba0?, 0xc000037030?})
	/nvme/gopath/go-1.21.0/src/runtime/panic.go:914 +0x21f
reflect.flag.mustBeAssignableSlow(0x4?)
	/nvme/gopath/go-1.21.0/src/reflect/value.go:272 +0x74
reflect.flag.mustBeAssignable(...)
	/nvme/gopath/go-1.21.0/src/reflect/value.go:259
reflect.Value.Set({0xa0fde0?, 0xc0001e07b0?, 0xab5b5d?}, {0xa0fde0?, 0x0?, 0xc00011df80?})
	/nvme/gopath/go-1.21.0/src/reflect/value.go:2254 +0x65
k8s.io/apimachinery/pkg/runtime.sliceToUnstructured({0x9df900?, 0xc000012a08?, 0xa19e80?}, {0xa0fde0?, 0xc0001e07b0?, 0x4e7c65?})
	/nvme/gopath/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/converter.go:738 +0x67f
k8s.io/apimachinery/pkg/runtime.toUnstructured({0x9df900?, 0xc000012a08?, 0x0?}, {0xa0fde0?, 0xc0001e07b0?, 0xc000012a08?})
...
```

/sig api-machinery

### What did you expect to happen?

No panic, round-trip works.

### How can we reproduce it (as minimally and precisely as possible)?

Apply this patch:
```patch
diff --git a/staging/src/k8s.io/apimachinery/pkg/runtime/converter_test.go b/staging/src/k8s.io/apimachinery/pkg/runtime/converter_test.go
index eebbf03880e..9a588c33759 100644
--- a/staging/src/k8s.io/apimachinery/pkg/runtime/converter_test.go
+++ b/staging/src/k8s.io/apimachinery/pkg/runtime/converter_test.go
@@ -113,6 +113,17 @@ type I struct {
 	UL1 UnknownLevel1 `json:"ul1"`
 }
 
+// AttributeValue is a one-of-many struct, here with just one field for testing purposes.
+type AttributeValue struct {
+	StringSliceValue *StringSlice `json:"stringSliceValue,omitempty"`
+}
+
+// StringSlice as wrapper struct is necessary because gogo/protobuf generates invalid
+// code when given a *[]string above.
+type StringSlice struct {
+	Strings []string `json:",inline"`
+}
+
 type UnknownLevel1 struct {
 	A          int64 `json:"a"`
 	InlinedAA  `json:",inline"`
@@ -223,6 +234,18 @@ func TestRoundTrip(t *testing.T) {
 	testCases := []struct {
 		obj interface{}
 	}{
+		{
+			obj: &AttributeValue{
+				StringSliceValue: &StringSlice{
+					Strings: []string{"a"},
+				},
+			},
+		},
+		{
+			obj: &AttributeValue{
+				StringSliceValue: &StringSlice{},
+			},
+		},
 		{
 			obj: &unstructured.UnstructuredList{
 				Object: map[string]interface{}{
```

Then run `go test` in `staging/src/k8s.io/apimachinery/pkg/runtime`.

### Anything else we need to know?

The other test case with non-nil slice also fails:
```
--- FAIL: TestRoundTrip (0.00s)
    --- FAIL: TestRoundTrip/0 (0.00s)
        converter_test.go:216: ToUnstructured failed: cannot convert slice to: map
```

### Kubernetes version

Current master (47c92e2ab7ad9076e11772ee130b82dc2cfa1add).

### Cloud provider

n/a

**Comment by pohly** [comment]
/close

I found my mistake: one cannot inline a slice in a struct in JSON. The JSON encoder seems to tolerate that while the runtime converter crashes (garbage in, garbage out).
