### ISSUE TITLE
[Failing Test] ci-kubernetes-kubemark-gce-scale-scheduler | kubemark-5000-scheduler

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#123884]
### Which jobs are failing?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale-scheduler/1766766416834334720

### Which tests are failing?

- kubetest.Kubemark 
- kubetest.Kubemark Up

### Since when has it been failing?

3 failures in a row since 03-06
lastpass was @ 03-04
before that 3 failures.

### Testgrid link

https://testgrid.k8s.io/sig-scalability-kubemark#kubemark-5000-scheduler

### Reason for failure (if possible)

```
WARNING: Could not store access token in cache: database is locked
ERROR: gcloud crashed (OperationalError): database is locked

If you would like to report this issue, please run the following command:
  gcloud feedback

To check gcloud for common problems, please run the following command:
  gcloud info --run-diagnostics
Traceback (most recent call last):
  File "/google-cloud-sdk/lib/gcloud.py", line 189, in <module>
    main()
  File "/google-cloud-sdk/lib/gcloud.py", line 185, in main
    sys.exit(gcloud_main.main())
             ^^^^^^^^^^^^^^^^^^
  File "/google-cloud-sdk/lib/googlecloudsdk/command_lib/crash_handling.py", line 199, in Wrapper
    target_function(*args, **kwargs)
  File "/google-cloud-sdk/lib/googlecloudsdk/gcloud_main.py", line 186, in main
    gcloud_cli.Execute()
  File "/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 1024, in Execute
    self._HandleAllErrors(exc, command_path_string, specified_arg_names)
  File "/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 1061, in _HandleAllErrors
ERROR: gcloud crashed (OperationalError): database is locked
    exceptions.HandleError(exc, command_path_string, self.__known_error_handler)
  File "/google-cloud-sdk/lib/googlecloudsdk/calliope/exceptions.py", line 557, in HandleError
    core_exceptions.reraise(exc)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/exceptions.py", line 146, in reraise
    six.reraise(type(exc_value), exc_value, tb)
  File "/google-cloud-sdk/lib/third_party/six/__init__.py", line 719, in reraise
...
sqlite3.OperationalError: database is locked
WARNING: Could not store access token in cache: database is locked
WARNING: Could not store access token in cache: database is locked
```

### Relevant SIG(s)

/sig scalibility scheduling

**Comment by kerthcet** [comment]
Is this related to kube-scheduler, didn't see related logs.

**Comment by pacoxu** [comment]
/cc @wojtek-t 
Do you have any clue about this failure?

**Comment by BenTheElder** [comment]
nudge @wojtek-t [they've been OOO and maybe have a moment now or can reroute]

**Comment by wojtek-t** [comment]
@alculquicondor - can you please take a look or delagate?

/assign @alculquicondor

**Comment by BenTheElder** [comment]
This seems to be a constant failure for months now? https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale-scheduler

Should we turn down the job? cc @kubernetes/sig-scalability

**Comment by kerthcet** [comment]
I'll take a look today.

**Comment by kerthcet** [comment]
Well, I think the error is obvious, `sqlite3.OperationalError: database is locked`, I guess `gcloud` use sqlite to store some configurations and there's a concurrency problem or timeout waiting for the lock to release. 

Out of my reach then.
