### ISSUE TITLE
DRA: kubelet: crash when plugin returns nil UnprepareResourceResponse

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#124043]
### What happened?

protobuf doesn't require that objects get encoded when they are empty. This can lead to a nil pointer in https://github.com/kubernetes/kubernetes/issues/124042 (although that's probably an error because some information is needed) and in https://github.com/kubernetes/kubernetes/blob/20d0ab7ae808aaddb1556c3c38ca0607663c50ac/staging/src/k8s.io/kubelet/pkg/apis/dra/v1alpha3/api.pb.go#L255 (happened in practice).

The result is a crash of kubelet:
```
E0305 14:50:50.162844   10432 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 883 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3de2d20?, 0x6fc0d90})
	/go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
	/go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x6b
panic({0x3de2d20?, 0x6fc0d90?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
k8s.io/kubernetes/pkg/kubelet/cm/dra.(*ManagerImpl).UnprepareResources(0xc00097b998, 0xc000d48900)
	/go/src/kubernetes/pkg/kubelet/cm/dra/manager.go:375 +0x67c
k8s.io/kubernetes/pkg/kubelet/cm.(*containerManagerImpl).UnprepareDynamicResources(0xc00027f5c0?, 0x477a71c?)
	/go/src/kubernetes/pkg/kubelet/cm/container_manager_linux.go:1021 +0x22
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).UnprepareDynamicResources(...)
	/go/src/kubernetes/pkg/kubelet/kubelet.go:3055
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).SyncTerminatingPod(0xc0004e3000, {0xc0010b2510?, 0x24?}, 0xc000d48900, 0xed8569a108?, 0x0, 0x0)
	/go/src/kubernetes/pkg/kubelet/kubelet.go:2082 +0x1a0b
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).podWorkerLoop.func1({0x1, {0x0, {0x0, 0x0, 0x0}, 0xc000d48900, 0x0, 0x0, 0x0}}, 0xc0004c4dc0, ...)
	/go/src/kubernetes/pkg/kubelet/pod_workers.go:1279 +0x17d
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).podWorkerLoop(0xc0010b2510?, {0xc0010b2510, 0x24}, 0x0?)
	/go/src/kubernetes/pkg/kubelet/pod_workers.go:1288 +0x47b
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod.func1()
	/go/src/kubernetes/pkg/kubelet/pod_workers.go:950 +0x115
created by k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod in goroutine 230
	/go/src/kubernetes/pkg/kubelet/pod_workers.go:945 +0x221b
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x209f8bc]

goroutine 883 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
	/go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xcd
panic({0x3de2d20?, 0x6fc0d90?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
k8s.io/kubernetes/pkg/kubelet/cm/dra.(*ManagerImpl).UnprepareResources(0xc00097b998, 0xc000d48900)
	/go/src/kubernetes/pkg/kubelet/cm/dra/manager.go:375 +0x67c
k8s.io/kubernetes/pkg/kubelet/cm.(*containerManagerImpl).UnprepareDynamicResources(0xc00027f5c0?, 0x477a71c?)
	/go/src/kubernetes/pkg/kubelet/cm/container_manager_linux.go:1021 +0x22
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).UnprepareDynamicResources(...)
	/go/src/kubernetes/pkg/kubelet/kubelet.go:3055
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).SyncTerminatingPod(0xc0004e3000, {0xc0010b2510?, 0x24?}, 0xc000d48900, 0xed8569a108?, 0x0, 0x0)
	/go/src/kubernetes/pkg/kubelet/kubelet.go:2082 +0x1a0b
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).podWorkerLoop.func1({0x1, {0x0, {0x0, 0x0, 0x0}, 0xc000d48900, 0x0, 0x0, 0x0}}, 0xc0004c4dc0, ...)
	/go/src/kubernetes/pkg/kubelet/pod_workers.go:1279 +0x17d
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).podWorkerLoop(0xc0010b2510?, {0xc0010b2510, 0x24}, 0x0?)
	/go/src/kubernetes/pkg/kubelet/pod_workers.go:1288 +0x47b
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod.func1()
	/go/src/kubernetes/pkg/kubelet/pod_workers.go:950 +0x115
created by k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod in goroutine 230
	/go/src/kubernetes/pkg/kubelet/pod_workers.go:945 +0x221b
```

(from 1.29.1).

### What did you expect to happen?

No crash.

### How can we reproduce it (as minimally and precisely as possible)?

Run the DRA-enabled Akri plugin.

### Anything else we need to know?

Reported by @diconico07 in https://kubernetes.slack.com/archives/C0BP8PW9G/p1709647270084129

### Kubernetes version

Several, but we shouldn't (?) backport because it was alpha.

### Cloud provider

n/a

**Comment by bitoku** [comment]
Can I work on this?

**Comment by TommyStarK** [comment]
@pohly just to be sure to understand the issue, the problem comes from  the generated protobuf code and the fact that when unmarshaling or merging, a nil map is used to store an empty protobuf map isn't it ?

**Comment by pohly** [comment]
Check the backtrace, it shows which line lacks a nil check.

**Comment by TommyStarK** [comment]
Sorry for the dumb question, I should have paid more attention..

**Comment by cyclinder** [comment]
I also hit the issue, I had to return a fake response.

**Comment by TommyStarK** [comment]
I'm a bit puzzled here, I thought the panic occurs when we try to access the claims attributes on a nil UnprepareResourceResponse. I've definitely misunderstood everything, @bitoku's work looks much more complete. I can go ahead and close mine.

**Comment by pohly** [comment]
Cherry-pick into 1.30 is in https://github.com/kubernetes/kubernetes/pull/124410
