### ISSUE TITLE
apimachinery's unstructured converter panics if the destination struct contains private fields

### ISSUE THREAD

**Issue by hugoShaka** [kubernetes/kubernetes#124154]
### What happened?

Using the DefaultUnsatructuredConverter with a destination struct containing a non-exported field throws a panic.

```
panic: reflect: reflect.Value.Set using value obtained using unexported field

goroutine 1 [running]:
reflect.flag.mustBeAssignableSlow(0x140000337a8?)
        /usr/local/go/src/reflect/value.go:269 +0xb4
reflect.flag.mustBeAssignable(...)
        /usr/local/go/src/reflect/value.go:259
reflect.Value.Set({0x100f4c3e0?, 0x14000169800?, 0x14000011168?}, {0x100f4c3e0?, 0x101232e40?, 0x98?})
        /usr/local/go/src/reflect/value.go:2319 +0x58
k8s.io/apimachinery/pkg/runtime.structFromUnstructured({0x100f63c60?, 0x140001697d0?, 0x1012f0248?}, {0x100f7e000?, 0x14000169800?, 0x100c2d5f8?}, 0x14000033e60)
        /Users/shaka/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/runtime/converter.go:556 +0x490
k8s.io/apimachinery/pkg/runtime.fromUnstructured({0x100f63c60?, 0x140001697d0?, 0x1400001115c?}, {0x100f7e000?, 0x14000169800?, 0x98?}, 0x14000033e60)
        /Users/shaka/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/runtime/converter.go:359 +0x2c4
k8s.io/apimachinery/pkg/runtime.structFromUnstructured({0x100f63c60?, 0x140001697a0?, 0x14000033c48?}, {0x100f71840?, 0x14000169800?, 0x100cabbf4?}, 0x14000033e60)
        /Users/shaka/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/runtime/converter.go:550 +0x64c
k8s.io/apimachinery/pkg/runtime.fromUnstructured({0x100f63c60?, 0x140001697a0?, 0x10?}, {0x100f71840?, 0x14000169800?, 0x100c35cec?}, 0x14000033e60)
        /Users/shaka/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/runtime/converter.go:359 +0x2c4
k8s.io/apimachinery/pkg/runtime.(*unstructuredConverter).FromUnstructuredWithValidation(0x1011c8df0, 0x140001697a0, {0x100f44b20, 0x14000169800}, 0x1)
        /Users/shaka/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/runtime/converter.go:247 +0x20c
main.main()
        /Users/shaka/playground/repro-runtime-panic/main.go:30 +0x110
```

I might be in a specific edge case, but we use protobuf to generate gRPC structs. Those structs contain [private fields holding the grpc state](https://github.com/gravitational/teleport/blob/19b09e5a5c60e5e15f72324965a19d4762adbc97/api/gen/proto/go/teleport/machineid/v1/bot.pb.go#L195-L208) and cause the converter to panic, even if the unstructured object only contain the public user-facing fields.

### What did you expect to happen?

I would expect the converter to ignore private fields and not panic.

### How can we reproduce it (as minimally and precisely as possible)?

```go
package main

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"log"
)

type StructuredObject struct {
	Spec StructuredObjectSpec
}

type StructuredObjectSpec struct {
	bar []byte
	Foo string
}

func main() {
	u := &unstructured.Unstructured{
		Object: map[string]interface{}{
			"spec": map[string]interface{}{
				"foo": "value",
			},
		},
	}

	structured := StructuredObject{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructuredWithValidation(
		u.Object,
		&structured,
		true, /* returnUnknownFields */
	)
	if err != nil {
		log.Fatal(err)
	}
}
```

### Anything else we need to know?

I can send a PR if you confirm this should be fixed and that the fix is to skip the private fields.

### Kubernetes version

The go module looks like
```
go 1.22

require k8s.io/apimachinery v0.29.3
```

### Cloud provider

No cloud provider.

### Install tools

Go 1.22

**Comment by sttts** [comment]
If the reflection based, generic equality is not good enough (e.g. because of private values), just register into `reflect.Equalities` with your custom callback. Handling private fields by ignoring them feels wrong. They certainly can have meaning, and that meaning depends on context. Think about `metav1.Time`. It needs private field comparison to make any sense.

**Comment by tlwr** [comment]
As above, the controller-runtime is using this reflection fork in apimachinery inside the `CreateOrUpdate` function
https://github.com/kubernetes-sigs/controller-runtime/blob/e6c3d139d2b6c286b1dbba6b6a95919159cfe655/pkg/controller/controllerutil/controllerutil.go#L312

It is using this reflection fork because of historical false positives
https://github.com/kubernetes-sigs/controller-runtime/issues/464

`reflect.DeepEqual` considers unexported fields: https://go.dev/play/p/wSyJ6m6O5c9
but apimachinery does not, it just panics... https://github.com/kubernetes/apimachinery/blob/2465dc5239ab8827a637148a78b380c278b4a5f4/third_party/forked/golang/reflect/deep_equal.go#L257

ie the following
```
package main

import "k8s.io/apimachinery/pkg/api/equality"

func main() {
	type Foo struct {
		X int
		y int
	}

	equality.Semantic.DeepEqual(Foo{1, 2}, Foo{1, 2})

}
```
will return
```
go run ./...
panic: an unexported field was encountered, nested like this:  [recovered]
	panic: an unexported field was encountered, nested like this: int [recovered]
	panic: an unexported field was encountered, nested like this: main.Foo -> int

goroutine 1 [running]:
k8s.io/apimachinery/third_party/forked/golang/reflect.makeUsefulPanic({0x102be7fa0?, 0x14000144020?, 0x140000021c0?})
	/Users/toby/go/1.22.0/pkg/mod/k8s.io/apimachinery@v0.31.0/third_party/forked/golang/reflect/deep_equal.go:96 +0x134
panic({0x102bd3980?, 0x140000c28e8?})
...
```

This means, right now, as a controller author, you cannot use controller-runtime if you have a struct with unexported fields (which as above is common for grpc)

Given that the controller-runtime is doing the following:
* get struct from controller
* fetch entity from k8s API (which will only contain exported fields, because these are the only fields available to encoding libraries (eg `json:"foo" yaml:foo"` tags)
* comparing structs via reflection

It seems unreasonable (and an unintended consequence of https://github.com/kubernetes-sigs/controller-runtime/pull/704) to panic if there are unexported fields in the structs being compared (as these fields are not relevant for comparison, as they will have been lost between serialization/deserialization between the controller and the k8s API)

Regardless of how the fork of reflection is to be used, I think the current DeepEqual usage by controller-runtime which panics on unexported fields is a bug. I believe controller-runtime should use a method of checking equality which does not panic on unexported fields. I do not think such a function is uniquely useful to controller-runtime, but could benefit other clients of apimachinery.

I propose to

(1) raise a PR to add a new function to apimachinery's reflection fork for `PublicDeepEqual` which returns true instead of panicking if a field is unexported
(2) raise a PR to use this new function in controller-runtime, which will fix the issue in our controller using Istio structs, and the similar issue with Cilium structs

WDYT?

**Comment by sttts** [comment]
@tlwr I don't think the proposed steps are a good solution. The behaviour to fail on private fields is intensional because it is defensive. If there are private fields, the developer must define a matching equality. It is wrong to assume that they have no meaning.

Doing that is easy:
```golang
	type Foo struct {
		X int
		y int
	}

	equality.Semantic.AddFunc(func(a, b Foo) bool {
		return a.X == b.X
	})

	equality.Semantic.DeepEqual(Foo{1, 2}, Foo{1, 2})
```

**Comment by tlwr** [comment]
Your point is valid 👍 

I have raised https://github.com/kubernetes/kubernetes/pull/126998 which gives a method DeepEqualWithOptions with an option to ignore unexported fields.

If this gets merged I can then use this `DeepEqualWithOptions` in a new call to `equality.Semantic.AddFunc`, which gives the benefit of [a production tested deep equality that does not produce false positives](https://github.com/kubernetes-sigs/controller-runtime/issues/464) while also not panicking when unexported fields are added to structs like in the Istio and Cilium cases.

**Comment by Jay-Madden** [comment]
Bumping this, we have run into this and while the workaround of the gocmp comparator does work. Its not an ideal solution. 

This makes it impossible to use many of the (istio, cilium primarily) go api types in downstream codebases with controller-runtime.
