### ISSUE TITLE
bug: kubelet panic & crash if `--config-dir` is used

### ISSUE THREAD

**Issue by hegerdes** [kubernetes/kubernetes#124796]
### What happened?

I created a v1.30.0 k8s cluster with kubeadm and created a  drop-in directory for kubelet configuration under `/etc/kubernetes/kubelet.conf.d`. The normal conf file created by kubeadm is in ` /var/lib/kubelet/config.yaml`

According to the [docs](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/#kubelet-conf-d) the kubelet should merge all configs in specified order and start. But the kubelet crashes under two setups:

**Setup 1**:

The `/etc/kubernetes/kubelet.conf.d/20-kubelet.conf` is completely empty the kubelet crashes with:
```
>kubelet --config-dir /etc/kubernetes/kubelet.conf.d --config /var/lib/kubelet/config.yaml
E0510 13:47:28.749138    9050 run.go:74] "command failed" err="failed to merge kubelet configs: failed to walk through kubelet dropin directory \"/etc/kubernetes/kubelet.conf.d\": failed to load kubelet dropin file, path: /etc/kubernetes/kubelet.conf.d/20-kubelet.conf, error: kubelet config file \"/etc/kubernetes/kubelet.conf.d/20-kubelet.conf\" was empty"
```
If there is just one space or an newline in that file it crashes with:
```
>kubelet --config-dir /etc/kubernetes/kubelet.conf.d --config /var/lib/kubelet/config.yaml
E0510 13:49:26.243517    9062 run.go:74] "command failed" err=<
        failed to merge kubelet configs: failed to walk through kubelet dropin directory "/etc/kubernetes/kubelet.conf.d": failed to load kubelet dropin file, path: /etc/kubernetes/kubelet.conf.d/20-kubelet.conf, error: Object 'Kind' is missing in '
        '
```
Even when the docs say:

> These files may contain partial configurations and might not be valid config files by themselves. Validation is only performed on the final resulting configuration structure stored internally in the kubelet. 

If there is nothing or only whitspaces in  `/etc/kubernetes/kubelet.conf.d` the merged config should not be invalid and not every file in `/etc/kubernetes/kubelet.conf.d` must contain a `kind` property.

**Setup 2**:
The `/etc/kubernetes/kubelet.conf.d/20-kubelet.conf` is the same as the `/var/lib/kubelet/config.yaml` the kubelet panics and crashes with:
```
> kubelet --config-dir /etc/kubernetes/kubelet.conf.d --config /var/lib/kubelet/config.yaml
panic: non-positive interval for NewTicker

goroutine 1 [running]:
time.NewTicker(0xc00098f7a0?)
        time/tick.go:22 +0xe5
k8s.io/klog/v2/internal/clock.RealClock.NewTicker(...)
        k8s.io/klog/v2@v2.120.1/internal/clock/clock.go:111
k8s.io/klog/v2.(*flushDaemon).run(0xc000229650, 0x0)
        k8s.io/klog/v2@v2.120.1/klog.go:1169 +0x10f
k8s.io/klog/v2.StartFlushDaemon(0x0)
        k8s.io/klog/v2@v2.120.1/klog.go:1220 +0x36
k8s.io/component-base/logs/api/v1.apply(0xc0008c8a38, 0x0, {0x7f1ede53b2f0, 0xc000557130})
        k8s.io/component-base/logs/api/v1/options.go:285 +0x890
k8s.io/component-base/logs/api/v1.validateAndApply(0xc0008c8a38, 0x0, {0x7f1ede53b2f0, 0xc000557130}, 0x4?)
        k8s.io/component-base/logs/api/v1/options.go:132 +0x71
k8s.io/component-base/logs/api/v1.ValidateAndApplyAsField(...)
        k8s.io/component-base/logs/api/v1/options.go:124
k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0xc0000d8908, {0xc000100060, 0x4, 0x4})
        k8s.io/kubernetes/cmd/kubelet/app/server.go:238 +0x4bc
github.com/spf13/cobra.(*Command).execute(0xc0000d8908, {0xc000100060, 0x4, 0x4})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x882
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000d8908)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
k8s.io/component-base/cli.run(0xc0000d8908)
        k8s.io/component-base/cli/run.go:146 +0x290
k8s.io/component-base/cli.Run(0xc0000061c0?)
        k8s.io/component-base/cli/run.go:46 +0x17
main.main()
        k8s.io/kubernetes/cmd/kubelet/kubelet.go:36 +0x18
```
Using the same config only via `--config` works.

### What did you expect to happen?

The kubelet should start with empty files in `/etc/kubernetes/kubelet.conf.d` or if the files in `/var/lib/kubelet/config.yaml` and `/etc/kubernetes/kubelet.conf.d` are the same.

If this is not the expected usage, the docs have to be adjusted. 

### How can we reproduce it (as minimally and precisely as possible)?

Create a cluster with kubeadm v1.30 with kublet config in `/var/lib/kubelet/config.yaml` and `/etc/kubernetes/kubelet.conf.d` or setup kubelet by hand. 

```yaml
# kubeadm config
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration

nodeRegistration:
  kubeletExtraArgs:
    config: /var/lib/kubelet/config.yaml
    config-dir: /etc/kubernetes/kubelet.conf.d
``` 

### Anything else we need to know?

The kublet conf api version is `apiVersion: kubelet.config.k8s.io/v1beta1` and is was with and without setting `KUBELET_CONFIG_DROPIN_DIR_ALPHA`

Functionality was introduced in #119390

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"30", GitVersion:"v1.30.0", GitCommit:"7c48c2bd72b9bf5c44d21d7338cc7bea77d0ad2a", GitTreeState:"clean", BuildDate:"2024-04-17T17:34:08Z", GoVersion:"go1.22.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Hetzner/None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux controlplane-node-amd64-vcxkzu 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd github.com/containerd/containerd v1.7.16
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
not relevant
</details>

**Comment by carlory** [comment]
I think it is a doc issue for `step 1`.

From [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/3983-drop-in-configuration/README.md#proposal), it said,

```
If there are any issues with the drop-ins (e.g. formatting errors), the error will be reported in the same way as a misconfigured kubelet.conf file
```

**Comment by hegerdes** [comment]
> I think it is a doc issue for `step 1`.
> 
> From [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/3983-drop-in-configuration/README.md#proposal), it said,
> 
> ```
> If there are any issues with the drop-ins (e.g. formatting errors), the error will be reported in the same way as a misconfigured kubelet.conf file
> ```

Just to be sure I recreated the setup given in the KEP. It did not work. Every file in the drop-ins seems to be required to have a `kind` (which suggest the validation is not just done at the end) and empty files produce an error.

There seems to be something wrong while merging the files.

**Comment by saschagrunert** [comment]
cc @haircommander @yuqi-zhang @sohankunkerkar @harche

**Comment by haircommander** [comment]
yeah the documentation doesn't match the behavior. I think we need to keep the behavior this way, where the kubelet fails on any invalid configuration file, because an admin's intent may not be fulfilled in the resulting configuration if we skip the invalid configs and continue the config resolution without taking the funky one into account. @sohankunkerkar do you have bandwidth to update the docs?

**Comment by sohankunkerkar** [comment]
> yeah the documentation doesn't match the behavior. I think we need to keep the behavior this way, where the kubelet fails on any invalid configuration file, because an admin's intent may not be fulfilled in the resulting configuration if we skip the invalid configs and continue the config resolution without taking the funky one into account. @sohankunkerkar do you have bandwidth to update the docs?

+1 to what @haircommander said. Let me go ahead and update the docs.

**Comment by ffromani** [comment]
/triage accepted

per https://github.com/kubernetes/kubernetes/issues/124796#issuecomment-2107530974 and https://github.com/kubernetes/kubernetes/issues/124796#issuecomment-2107584048

**Comment by ffromani** [comment]
I think in the case/step 2 described above the kubelet should preferably abort like it does in the case/step1 rather than crash with a stacktrace. Perhaps a stretch goal?

**Comment by hegerdes** [comment]
Nice, thanks for the updating the docs so fast.

Just wanted to check in what's up with problem 2 described in _Setup 2_. Should this be reopened or is a new Issue needed?

**Comment by carlory** [comment]
/reopen

For problem 2 described in Setup 2

**Comment by liggitt** [comment]
The drop-in files must minimally identify themselves as kubelet config files (valid apiVersion / kind), and the docs should reflect that

**Comment by hegerdes** [comment]
> The drop-in files must minimally identify themselves as kubelet config files (valid apiVersion / kind), and the docs should reflect that

Yes, this section has been added to the docs and now the docs and implementation aligns.

The second issue I encountered was that I used the exact same config (with api version and kind) via `--config` and as an drop-in config file and the kubelet crashed with the above error. (See setup 2) Are `--config` and the `--config-dir` meant to be mutually exclusive? Which one takes precedence over the over? Both in terms of flags and config file.

I have not confirmed in recent time that specifying both with the same config still results in a crash but I can check again next week with k8s 1.31

**Comment by sohankunkerkar** [comment]
>The second issue I encountered was that I used the exact same config (with api version and kind) via --config and as an drop-in config file and the kubelet crashed with the above error. (See setup 2) Are --config and the --config-dir meant to be mutually exclusive? Which one takes precedence over the over? Both in terms of flags and config file.

These two options are not mutually exclusive; they are designed to work together. When both are used, the kubelet should first load the configuration from the `--config` file and then apply any settings from the files in the `--config-dir`, with the latter taking precedence. This means that if there are conflicting settings, those in the drop-in directory will override those specified in the primary configuration file. Regarding the issue, the kubelet should be able to handle such scenarios gracefully without resulting in a crash. I will work on it once the enhancement freeze is over.

**Comment by hegerdes** [comment]
I retested the bug with k8s 1.32.2 and I can confirm that it still occures.

Setting the content below in `/etc/kubernetes/kubelet.conf.d/99-kubelet-default.conf` and starting the kubelet with `--config-dir /etc/kubernetes/kubelet.conf.d` will crash the kubelet with this log:

```
Oct 25 15:05:13 worker-node-amd64-7ei6n5 systemd[1]: Started kubelet.service - kubelet: The Kubernetes Node Agent.
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]: Flag --container-runtime-endpoint has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]: Flag --pod-infra-container-image has been deprecated, will be removed in a future release. Image garbage collector will get sandbox image information from CRI.
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]: I1025 15:05:13.262673    3895 server.go:211] "--pod-infra-container-image will not be pruned by the image garbage collector in kubelet and should also be set in the remote runtime"
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]: panic: non-positive interval for NewTicker
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]: goroutine 1 [running]:
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]: time.NewTicker(0xc000477718?)
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]:         time/tick.go:22 +0xe5
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]: k8s.io/klog/v2/internal/clock.RealClock.NewTicker(...)
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]:         k8s.io/klog/v2@v2.130.1/internal/clock/clock.go:111
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]: k8s.io/klog/v2.(*flushDaemon).run(0xc0002611a0, 0x0)
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]:         k8s.io/klog/v2@v2.130.1/klog.go:1136 +0x10f
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]: k8s.io/klog/v2.StartFlushDaemon(0x0)
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]:         k8s.io/klog/v2@v2.130.1/klog.go:1187 +0x36
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]: k8s.io/component-base/logs/api/v1.apply(0xc000872438, 0x0, {0x7fbeacb02610, 0xc0004d7b90})
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]:         k8s.io/component-base/logs/api/v1/options.go:286 +0x896
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]: k8s.io/component-base/logs/api/v1.validateAndApply(0xc000872438, 0x0, {0x7fbeacb02610, 0xc0004d7b90}, 0x79?)
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]:         k8s.io/component-base/logs/api/v1/options.go:132 +0x71
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]: k8s.io/component-base/logs/api/v1.ValidateAndApplyAsField(...)
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]:         k8s.io/component-base/logs/api/v1/options.go:124
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]: k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0xc0003db208, {0xc0001340a0, 0x8, 0x8})
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]:         k8s.io/kubernetes/cmd/kubelet/app/server.go:244 +0x4bf
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]: github.com/spf13/cobra.(*Command).execute(0xc0003db208, {0xc0001340a0, 0x8, 0x8})
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]:         github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]: github.com/spf13/cobra.(*Command).ExecuteC(0xc0003db208)
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]:         github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]: github.com/spf13/cobra.(*Command).Execute(...)
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]:         github.com/spf13/cobra@v1.8.1/command.go:1041
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]: k8s.io/component-base/cli.run(0xc0003db208)
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]:         k8s.io/component-base/cli/run.go:143 +0x245
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]: k8s.io/component-base/cli.Run(0xc0000061c0?)
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]:         k8s.io/component-base/cli/run.go:44 +0x17
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]: main.main()
Oct 25 15:05:13 worker-node-amd64-7ei6n5 kubelet[3895]:         k8s.io/kubernetes/cmd/kubelet/kubelet.go:36 +0x18
Oct 25 15:05:13 worker-node-amd64-7ei6n5 systemd[1]: kubelet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 25 15:05:13 worker-node-amd64-7ei6n5 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Oct 25 15:05:23 worker-node-amd64-7ei6n5 systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 134.
```

The content of `99-kubelet-default.conf`:
```yaml
# kubelet config
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration

authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 0s
    enabled: true
  x509:
    clientCAFile: "/etc/kubernetes/pki/ca.crt"
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 0s
    cacheUnauthorizedTTL: 0s

# See https://kubernetes.io/docs/reference/access-authn-authz/kubelet-tls-bootstrapping/
rotateCertificates: true
serverTLSBootstrap: true

containerRuntimeEndpoint: unix:///run/containerd/containerd.sock
clusterDomain: cluster.local
clusterDNS: [10.96.0.10]

maxPods: 220
imageGCLowThresholdPercent: 70
protectKernelDefaults: true
nodeStatusMaxImages: 100
serializeImagePulls: false
staticPodPath: /etc/kubernetes/manifests
maxParallelImagePulls: 8
cgroupDriver: systemd
failSwapOn: true
streamingConnectionIdleTimeout: 0s
syncFrequency: 0s
volumeStatsAggPeriod: 0s
runtimeRequestTimeout: 0s
nodeStatusReportFrequency: 0s
nodeStatusUpdateFrequency: 0s
httpCheckFrequency: 0s
readOnlyPort: 0
imageMaximumGCAge: 0s
imageMinimumGCAge: 0s
fileCheckFrequency: 0s
cpuManagerReconcilePeriod: 0s
evictionPressureTransitionPeriod: 0s

logging:
  flushFrequency: 0
  options:
    json:
      infoBufferSize: "0"


```

**Comment by liggitt** [comment]
> I retested the bug with k8s 1.32.2 and I can confirm that it still occures.

1.32 is not released yet. Did you mean 1.31.2?

The fix to apply defaulting to config files loaded from the config dir is only in 1.32 dev builds (https://github.com/kubernetes/kubernetes/pull/127421)

**Comment by hegerdes** [comment]
> > I retested the bug with k8s 1.32.2 and I can confirm that it still occures.
> 
> 1.32 is not released yet. Did you mean 1.31.2?
> 
> The fix to apply defaulting to config files loaded from the config dir is only in 1.32 dev builds (#127421)

Sorry, was indeed a typo. Tested `Kubernetes v1.31.2`

**Comment by liggitt** [comment]
is this still an issue:

```
Setup 2:
The /etc/kubernetes/kubelet.conf.d/20-kubelet.conf is the same as the /var/lib/kubelet/config.yaml the kubelet panics and crashes with:

> kubelet --config-dir /etc/kubernetes/kubelet.conf.d --config /var/lib/kubelet/config.yaml
panic: non-positive interval for NewTicker

goroutine 1 [running]:
time.NewTicker(0xc00098f7a0?)
        time/tick.go:22 +0xe5
k8s.io/klog/v2/internal/clock.RealClock.NewTicker(...)
        k8s.io/klog/v2@v2.120.1/internal/clock/clock.go:111
k8s.io/klog/v2.(*flushDaemon).run(0xc000229650, 0x0)
        k8s.io/klog/v2@v2.120.1/klog.go:1169 +0x10f
k8s.io/klog/v2.StartFlushDaemon(0x0)
        k8s.io/klog/v2@v2.120.1/klog.go:1220 +0x36
k8s.io/component-base/logs/api/v1.apply(0xc0008c8a38, 0x0, {0x7f1ede53b2f0, 0xc000557130})
        k8s.io/component-base/logs/api/v1/options.go:285 +0x890
k8s.io/component-base/logs/api/v1.validateAndApply(0xc0008c8a38, 0x0, {0x7f1ede53b2f0, 0xc000557130}, 0x4?)
        k8s.io/component-base/logs/api/v1/options.go:132 +0x71
k8s.io/component-base/logs/api/v1.ValidateAndApplyAsField(...)
        k8s.io/component-base/logs/api/v1/options.go:124
k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0xc0000d8908, {0xc000100060, 0x4, 0x4})
        k8s.io/kubernetes/cmd/kubelet/app/server.go:238 +0x4bc
github.com/spf13/cobra.(*Command).execute(0xc0000d8908, {0xc000100060, 0x4, 0x4})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x882
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000d8908)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
k8s.io/component-base/cli.run(0xc0000d8908)
        k8s.io/component-base/cli/run.go:146 +0x290
k8s.io/component-base/cli.Run(0xc0000061c0?)
        k8s.io/component-base/cli/run.go:46 +0x17
main.main()
        k8s.io/kubernetes/cmd/kubelet/kubelet.go:36 +0x18
```

if so, that seems like a specific issue to route to the folks working on log config application

**Comment by SergeyKanzhelev** [comment]
KEP link: https://github.com/kubernetes/enhancements/issues/3983

@haircommander @sohankunkerkar can either of you take a look?

**Comment by hegerdes** [comment]
> is this still an issue

I can confirm that the crashing kubelet when supplying duplicate configs via `--config` and `--config-dir` is not a problem anymore in kubernetes `v1.33.1`. 

I can not say if there is any other issue regarding the logger, but for me this seems to be fixed and can be closed.

**Comment by sohankunkerkar** [comment]
We added some coverage here: https://github.com/kubernetes/kubernetes/pull/129460

**Comment by liggitt** [comment]
let's close and file a new specific issue if someone still has problems with merging specific fields
