### ISSUE TITLE
[Failing test] cgroupv1 EC2 serial jobs

### ISSUE THREAD

**Issue by AnishShah** [kubernetes/kubernetes#125173]
### Which jobs are failing?

* ci-cgroupv1-containerd-node-arm64-e2e-serial-ec2-eks
* ci-cgroupv1-containerd-node-e2e-serial-ec2-eks

### Which tests are failing?

Most of them are failing

### Since when has it been failing?

Since 5/21

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#ci-cgroupv1-containerd-node-arm64-e2e-serial-ec2-eks

### Reason for failure (if possible)

kubelet is failing because swap feature was enabled in cgroupv1 jobs, even though it is cgroupv2-only feature

```
May 28 10:57:45 ip-172-31-45-174.ec2.internal kubelet[9707]: E0528 10:57:45.002735    9707 run.go:72] "command failed" err="failed to run Kubelet: swap feature is enabled and LimitedSwap but it is only supported with cgroupv2"
```

panics in kube-apiserver as well

```
I0528 11:28:55.125850    4336 httplog.go:132] "HTTP" verb="CONNECT" URI="/api/v1/nodes/i-052068edaeac5560a/proxy/configz" latency="1.598163ms" userAgent="Go-http-client/1.1" audit-ID="4d31794e-f3a6-4505-94fa-dd50d1a44932" srcIP="127.0.0.1:35728" resp=503 statusStack=<
  	
  	goroutine 274441 [running]:
  	k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0x400a196c60, 0x1dba6ac?)
  		k8s.io/apiserver/pkg/server/httplog/httplog.go:319 +0x12c
  	k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0x400a196c60, 0x1f7)
  		k8s.io/apiserver/pkg/server/httplog/httplog.go:299 +0x24
  	k8s.io/apiserver/pkg/endpoints/metrics.(*ResponseWriterDelegator).WriteHeader(0x400a8c9801?, 0x40090cd8c0?)
  		k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:810 +0x38
  	k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.(*deferredResponseWriter).Write(0x4009ae5b00, {0x40085cc000, 0xd3, 0x68000})
  		k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:243 +0x52c
  	encoding/json.(*Encoder).Encode(0x4007899308, {0x39aa340, 0x4007d09ea0})
  		encoding/json/stream.go:230 +0x1a4
  	k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0x627c2f0?, {0x4220a28?, 0x4007d09ea0?}, {0x421a860, 0x4009ae5b00})
  		k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:246 +0x160
  	k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0x4000435c20, {0x4220a28?, 0x4007d09ea0}, {0x421a860, 0x4009ae5b00})
  		k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:220 +0xdc
  	k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode(0x400b638000, {0x4220a28, 0x4007d09ea0}, {0x421a860, 0x4009ae5b00}, {0x0?, 0x0?})
  		k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:268 +0x3d8
  	k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).encode(0x400b638000, {0x4220a28?, 0x4007d09ea0}, {0x421a860, 0x4009ae5b00}, {0x0, 0x0})
  		k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:214 +0xfc
  	k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0x4250f00?, {0x4220a28?, 0x4007d09ea0?}, {0x421a860?, 0x4009ae5b00?})
  		k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:207 +0x34
  	k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject({0x3a7c917, 0x10}, {0xffff5c99a880, 0x400b638000}, {0x4249fc0, 0x400aa779b0}, 0x400533a7e0, 0x1f7, {0x4220a28, 0x4007d09ea0})
  		k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:111 +0x7b4
  	k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated.func2()
  		k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:292 +0x190
  	k8s.io/apiserver/pkg/endpoints/request.(*durationTracker).Track(0x400aa771a0, 0x400abc44e0)
  		k8s.io/apiserver/pkg/endpoints/request/webhook_duration.go:75 +0x84
  	k8s.io/apiserver/pkg/endpoints/request.TrackSerializeResponseObjectLatency({0x4250f00?, 0x400aa77650?}, 0x400abc44e0)
  		k8s.io/apiserver/pkg/endpoints/request/webhook_duration.go:229 +0x68
  	k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated({0x42381e0, 0x40018d47c0}, {0x4248890, 0x6477060}, {{0x0, 0x0}, {0x3a5dcc0, 0x2}}, {0x4249fc0, 0x400aa779b0}, ...)
  		k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:288 +0x58c
  	k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.ErrorNegotiated({0x4210f20?, 0x4007d09e00?}, {0x42381e0, 0x40018d47c0}, {{0x0?, 0x400afc7350?}, {0x3a5dcc0?, 0x538f20?}}, {0x4249fc0, 0x400aa779b0}, ...)
  		k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:329 +0x1c8
  	k8s.io/apiserver/pkg/endpoints/handlers.(*RequestScope).err(...)
  		k8s.io/apiserver/pkg/endpoints/handlers/rest.go:113
  	k8s.io/apiserver/pkg/endpoints/handlers.(*responder).Error(0x120?, {0x4210f20?, 0x4007d09e00?})
  		k8s.io/apiserver/pkg/endpoints/handlers/rest.go:242 +0x78
  	k8s.io/apimachinery/pkg/util/proxy.simpleResponder.Error(...)
  		k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go:113
  	net/http/httputil.(*ReverseProxy).ServeHTTP(0x400789a9e0, {0x4249fc0, 0x400aa779b0}, 0x40053ef0e0)
  		net/http/httputil/reverseproxy.go:472 +0xc74
  	k8s.io/apimachinery/pkg/util/proxy.(*UpgradeAwareHandler).ServeHTTP(0x4002691570, {0x4249fc0, 0x400aa779b0}, 0x400533a7e0)
  		k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go:293 +0x70c
  	k8s.io/apiserver/pkg/endpoints/handlers.ConnectResource.func1.1()
  		k8s.io/apiserver/pkg/endpoints/handlers/rest.go:225 +0x190
  	k8s.io/apiserver/pkg/endpoints/metrics.RecordLongRunning(0x400533a7e0, 0x32ae7c0?, {0x3a68c26, 0x9}, 0x400789b0f8)
  		k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:528 +0x3b4
  	k8s.io/apiserver/pkg/endpoints/handlers.ConnectResource.func1({0x4249fc0, 0x400aa779b0}, 0x400533a7e0)
  		k8s.io/apiserver/pkg/endpoints/handlers/rest.go:219 +0x550
  	k8s.io/apiserver/pkg/endpoints.(*APIInstaller).registerResourceHandlers.restfulConnectResource.func31(0x4009f77600, 0x400277bf10)
  		k8s.io/apiserver/pkg/endpoints/installer.go:1324 +0x70
  	k8s.io/apiserver/pkg/endpoints.(*APIInstaller).registerResourceHandlers.InstrumentRouteFunc.func32(0x4009f77600, 0x400277bf10)
  		k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:600 +0x160
  	github.com/emicklei/go-restful/v3.(*Container).dispatch(0x4000f358c0, {0x4249fc0, 0x400aa77350}, 0x400533a7e0)
  		github.com/emicklei/go-restful/v3@v3.11.0/container.go:299 +0x80c
  	github.com/emicklei/go-restful/v3.(*Container).Dispatch(...)
  		github.com/emicklei/go-restful/v3@v3.11.0/container.go:204
  	k8s.io/apiserver/pkg/server.director.ServeHTTP({{0x3a778bf?, 0x0?}, 0x4000f358c0?, 0x400048f110?}, {0x4249fc0, 0x400aa77350}, 0x400533a7e0)
  		k8s.io/apiserver/pkg/server/handler.go:146 +0x4a8
  	k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0x400246fcf8?, {0x4249fc0?, 0x400aa77350?}, 0x2f?)
  		k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:118 +0x1e4
  	k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0x40057b4f00, {0x4249fc0, 0x400aa77350}, 0x400533a7e0)
  		k8s.io/apiserver/pkg/server/mux/pathrecorder.go:251 +0x358
  	k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0x40054d5cc4?, {0x4249fc0?, 0x400aa77350?}, 0x6e94d4?)
  		k8s.io/apiserver/pkg/server/mux/pathrecorder.go:237 +0x78
  	k8s.io/apiserver/pkg/server.director.ServeHTTP({{0x3a7b756?, 0x400aa77440?}, 0x4003e0fd40?, 0x40041b8d90?}, {0x4249fc0, 0x400aa77350}, 0x400533a7e0)
  		k8s.io/apiserver/pkg/server/handler.go:154 +0x5e8
  	k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.TrackCompleted.trackCompleted.func22({0x4249fc0, 0x400aa77350}, 0x400533a7e0)
  		k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:110 +0x130
  	net/http.HandlerFunc.ServeHTTP(0x4250f00?, {0x4249fc0?, 0x400aa77350?}, 0x4?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/endpoints/filters.withAuthorization.func1({0x4249fc0, 0x400aa77350}, 0x400533a7e0)
  		k8s.io/apiserver/pkg/endpoints/filters/authorization.go:78 +0x44c
  	net/http.HandlerFunc.ServeHTTP(0x4000d83ec8?, {0x4249fc0?, 0x400aa77350?}, 0xd?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1({0x4249fc0, 0x400aa77350}, 0x400533a7e0)
  		k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:84 +0x154
  	net/http.HandlerFunc.ServeHTTP(0x4000d83f48?, {0x4249fc0?, 0x400aa77350?}, 0x1fd6ce0?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.TrackCompleted.trackCompleted.func23({0x4249fc0, 0x400aa77350}, 0x400533a7e0)
  		k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:110 +0x130
  	net/http.HandlerFunc.ServeHTTP(0x39422a0?, {0x4249fc0?, 0x400aa77350?}, 0x3?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/server/filters.(*priorityAndFairnessHandler).Handle(0x40041985a0, {0x4249fc0, 0x400aa77350}, 0x400533a7e0)
  		k8s.io/apiserver/pkg/server/filters/priority-and-fairness.go:106 +0x284
  	net/http.HandlerFunc.ServeHTTP(0x4000d842e8?, {0x4249fc0?, 0x400aa77350?}, 0xd?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1({0x4249fc0, 0x400aa77350}, 0x400533a7e0)
  		k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:84 +0x154
  	net/http.HandlerFunc.ServeHTTP(0x4000d84368?, {0x4249fc0?, 0x400aa77350?}, 0x1fd6b00?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.TrackCompleted.trackCompleted.func24({0x4249fc0, 0x400aa77350}, 0x400533a7e0)
  		k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:110 +0x130
  	net/http.HandlerFunc.ServeHTTP(0x400aa76f30?, {0x4249fc0?, 0x400aa77350?}, 0x6?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithImpersonation.func4({0x4249fc0, 0x400aa77350}, 0x400533a7e0)
  		k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x144
  	net/http.HandlerFunc.ServeHTTP(0x4002ae6a88?, {0x4249fc0?, 0x400aa77350?}, 0xd?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1({0x4249fc0, 0x400aa77350}, 0x400533a7e0)
  		k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:84 +0x154
  	net/http.HandlerFunc.ServeHTTP(0x4002ae6b08?, {0x4249fc0?, 0x400aa77350?}, 0x1fd5470?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.TrackCompleted.trackCompleted.func25({0x4249fc0, 0x400aa77350}, 0x400533a7e0)
  		k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:110 +0x130
  	net/http.HandlerFunc.ServeHTTP(0x4002ae6cb8?, {0x4249fc0?, 0x400aa77350?}, 0xd?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1({0x4249fc0, 0x400aa77350}, 0x400533a7e0)
  		k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:84 +0x154
  	net/http.HandlerFunc.ServeHTTP(0x4002ae6d38?, {0x4249fc0?, 0x400aa77350?}, 0x1fd4640?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.TrackCompleted.trackCompleted.func27({0x4249fc0, 0x400aa77350}, 0x400533a7e0)
  		k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:110 +0x130
  	net/http.HandlerFunc.ServeHTTP(0x4250f00?, {0x4249fc0?, 0x400aa77350?}, 0x41f53c0?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/endpoints/filters.withAuthentication.func1({0x4249fc0, 0x400aa77350}, 0x400533a7e0)
  		k8s.io/apiserver/pkg/endpoints/filters/authentication.go:120 +0x5d4
  	net/http.HandlerFunc.ServeHTTP(0x4250f00?, {0x4249fc0?, 0x400aa77350?}, 0x41fcd00?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1({0x4249fc0, 0x400aa77350}, 0x400533a480)
  		k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:94 +0x2c4
  	net/http.HandlerFunc.ServeHTTP(0x400533a360?, {0x4249fc0?, 0x400aa77350?}, 0x40095d9450?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithWarningRecorder.func11({0x4249fc0, 0x400aa77350}, 0x400533a360)
  		k8s.io/apiserver/pkg/endpoints/filters/warning.go:35 +0xb8
  	net/http.HandlerFunc.ServeHTTP(0x400533a360?, {0x4249fc0?, 0x400aa77350?}, 0x66feb8?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0x4002bb6930, {0x4249fc0, 0x400aa77350}, 0x41a1b4?)
  		k8s.io/apiserver/pkg/server/filters/timeout.go:87 +0x2a0
  	k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithRequestDeadline.withRequestDeadline.func28({0x4249fc0, 0x400aa77350}, 0x400533a360)
  		k8s.io/apiserver/pkg/endpoints/filters/request_deadline.go:65 +0x300
  	net/http.HandlerFunc.ServeHTTP(0x4250f00?, {0x4249fc0?, 0x400aa77350?}, 0x8c00000000000000?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithWaitGroup.withWaitGroup.func29({0x4249fc0, 0x400aa77350}, 0x400533a360)
  		k8s.io/apiserver/pkg/server/filters/waitgroup.go:65 +0x180
  	net/http.HandlerFunc.ServeHTTP(0x400aa76f90?, {0x4249fc0?, 0x400aa77350?}, 0x3a82432?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithCacheControl.func14({0x4249fc0, 0x400aa77350}, 0x400533a360)
  		k8s.io/apiserver/pkg/endpoints/filters/cachecontrol.go:31 +0xa8
  	net/http.HandlerFunc.ServeHTTP(0x4251b58?, {0x4249fc0?, 0x400aa77350?}, 0x41fcd00?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithHTTPLogging.WithLogging.withLogging.func35({0x424aa40, 0x40095d9400}, 0x400533a240)
  		k8s.io/apiserver/pkg/server/httplog/httplog.go:131 +0x18c
  	net/http.HandlerFunc.ServeHTTP(0x400a8c9680?, {0x424aa40?, 0x40095d9400?}, 0x411d00?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/endpoints/filters.WithTracing.func2({0x424aa40?, 0x40095d9400?}, 0x400533a240?)
  		k8s.io/apiserver/pkg/endpoints/filters/traces.go:51 +0x1a0
  	net/http.HandlerFunc.ServeHTTP(0x4250f00?, {0x424aa40?, 0x40095d9400?}, 0x41fcd00?)
  		net/http/server.go:2166 +0x38
  	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP(0x4003eecd10, {0x4249fc0, 0x400aa77260}, 0x400533a120, {0x42118a0, 0x4002bb6a98})
  		go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.44.0/handler.go:217 +0xf28
  	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1({0x4249fc0?, 0x400aa77260?}, 0x425bb01?)
  		go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.44.0/handler.go:81 +0x40
  	net/http.HandlerFunc.ServeHTTP(0x4252108?, {0x4249fc0?, 0x400aa77260?}, 0x40a6c8?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithLatencyTrackers.func16({0x4238420, 0x400571a000}, 0x400548fe60)
  		k8s.io/apiserver/pkg/endpoints/filters/webhook_duration.go:56 +0x120
  	net/http.HandlerFunc.ServeHTTP(0x4004a08630?, {0x4238420?, 0x400571a000?}, 0x47bb48?)
  		net/http/server.go:2166 +0x38
  	k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithRoutine.func17.1()
  		k8s.io/apiserver/pkg/server/filters/routine.go:64 +0x64
  	created by k8s.io/apiserver/pkg/server.DefaultBuildHandlerChain.WithRoutine.func17 in goroutine 274439
  		k8s.io/apiserver/pkg/server/filters/routine.go:57 +0x15c
   > addedInfo=<
  	logging error output: "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"error trying to reach service: dial tcp 172.31.45.174:10250: connect: connection refused\",\"reason\":\"ServiceUnavailable\",\"code\":503}\n"
   >
  I0528 11:28:55.203041    4336 httplog.go:132] "HTTP" verb="GET" URI="/api/v1/namespaces/default/endpoints/kubernetes" latency="928.409µs" userAgent="e2e_node.test/v0.1.0 (linux/arm64) kubernetes/f03bf28" audit-ID="d1802888-0e80-4dac-97af-ed2b642c6c67" srcIP="127.0.0.1:53028" apf_pl="exempt" apf_fs="exempt" apf_iseats=1 apf_fseats=0 apf_additionalLatency="0s" apf_execution_time="737.707µs" resp=200
```

### Relevant SIG(s)

/sig node

**Comment by SergeyKanzhelev** [comment]
cc @dims

**Comment by mimowo** [comment]
It continues to be an issue. In particular it affects tests for the kubelet-initiated preemption for critical pods, as noticed here: https://github.com/kubernetes/enhancements/pull/4661#issuecomment-2149821788. I looked at some of the tests and found the line `run.go:72] "command failed" err="failed to run Kubelet: swap feature is enabled and LimitedSwap but it is only supported with cgroupv2"`. For example here: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-cgroupv1-containerd-node-e2e-serial-ec2-eks/1805833241165303808/artifacts/i-0eb10152e2ceef49e-system.log

**Comment by dims** [comment]
@mimowo looks like after https://github.com/kubernetes/test-infra/pull/32876 the 2 jobs are recovering

- https://testgrid.k8s.io/sig-node-containerd#ci-cgroupv1-containerd-node-e2e-serial-ec2-eks&width=20
- https://testgrid.k8s.io/sig-node-containerd#ci-cgroupv1-containerd-node-arm64-e2e-serial-ec2-eks&width=20

Do you mind adding a skip for the `NodeFeature:NodeSwap` for the same jobs since we switched off the feature in that PR above?

**Comment by mimowo** [comment]
> @mimowo looks like after https://github.com/kubernetes/test-infra/pull/32876 the 2 jobs are recovering

This is great news!

> Do you mind adding a skip for the NodeFeature:NodeSwap for the same jobs since we switched off the feature in that PR above?

+1 for that, IIUC it will make the board green, and the tests relevant for the recent investigation (with CriticalPod) don't have the marker.

**Comment by AnishShah** [comment]
The original issue for which this bug was filed was resolved. But OOMKiller test is failing consistently now. I filed a separate bug to track it - #126009 

Closing this one. 

/close
