### ISSUE TITLE
kubectl: panic when describe ingress with no Backend

### ISSUE THREAD

**Issue by able8** [kubernetes/kubernetes#126631]
### What happened?

k describe ing test-ing-without-backend

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1017fde94]

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe.(*IngressDescriber).describeBackendV1(0x140005d3070?, {0x140005c7057?, 0x1019d6ab8?}, 0x13?)
	vendor/k8s.io/kubectl/pkg/describe/describe.go:2593 +0x24
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe.(*IngressDescriber).describeIngressV1.func1({0x10226f920?, 0x140003a0000})
	vendor/k8s.io/kubectl/pkg/describe/describe.go:2667 +0x338
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe.tabbedString(0x140008c9a08)
	vendor/k8s.io/kubectl/pkg/describe/describe.go:5245 +0x80
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe.(*IngressDescriber).describeIngressV1(0x12b104420?, 0x14000d886b0?, 0x1022749e0?)
	vendor/k8s.io/kubectl/pkg/describe/describe.go:2627 +0x40
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/describe.(*IngressDescriber).Describe(0x14000d889a0, {0x14000c071b5, 0x5}, {0x16f6e346d, 0xd}, {0x0?, 0x14000ad3b28?})
	vendor/k8s.io/kubectl/pkg/describe/describe.go:2553 +0x150
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/describe.(*DescribeOptions).Run(0x1400060e320)
	vendor/k8s.io/kubectl/pkg/cmd/describe/describe.go:193 +0x40c
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/describe.NewCmdDescribe.func1(0x1400060c500?, {0x14000111760?, 0x2?, 0x2?})
	vendor/k8s.io/kubectl/pkg/cmd/describe/describe.go:113 +0x64
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0x1400060c500, {0x14000111700, 0x2, 0x2})
	vendor/github.com/spf13/cobra/command.go:860 +0x4ac
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x14000935900)
	vendor/github.com/spf13/cobra/command.go:974 +0x354
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	vendor/github.com/spf13/cobra/command.go:902
k8s.io/kubernetes/vendor/k8s.io/component-base/cli.run(0x14000935900)
	vendor/k8s.io/component-base/cli/run.go:146 +0x2a4
k8s.io/kubernetes/vendor/k8s.io/component-base/cli.RunNoErrOutput(...)
	vendor/k8s.io/component-base/cli/run.go:84
main.main()
	cmd/kubectl/kubectl.go:30 +0x20
```

### What did you expect to happen?

k describe ing test-ing-without-backend  work without error
 

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ing-without-backend
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      location = / {
        return 200 'OK';
      }
spec:
  rules:
  - host: a.com
```

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.12", GitCommit:"ef70d260f3d036fc22b30538576bbf6b36329995", GitTreeState:"clean", BuildDate:"2023-03-15T13:37:18Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"29", GitVersion:"v1.29.5-gke.1091002", GitCommit:"0126fa256b86df67042c3c08915a8f633f2ab5f5", GitTreeState:"clean", BuildDate:"2024-05-29T09:14:46Z", GoVersion:"go1.21.9 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.29) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by able8** [comment]
it works after upgrading kubectl to `Client Version: v1.30.3`
