### ISSUE TITLE
featuregates_linter fails to update the corresponding files

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#126741]
### Repro

```diff
diff --git a/pkg/features/kube_features.go b/pkg/features/kube_features.go
index 80a25132bca..fb598b95ddd 100644
--- a/pkg/features/kube_features.go
+++ b/pkg/features/kube_features.go
@@ -1125,7 +1125,7 @@ var defaultKubernetesFeatureGates = map[featuregate.Feature]featuregate.FeatureS
 
        MinDomainsInPodTopologySpread: {Default: true, PreRelease: featuregate.GA, LockToDefault: true}, // remove in 1.32
 
-       MultiCIDRServiceAllocator: {Default: false, PreRelease: featuregate.Beta},
+       MultiCIDRServiceAllocator: {Default: true, PreRelease: featuregate.Beta},
 
        NewVolumeManagerReconstruction: {Default: true, PreRelease: featuregate.GA, LockToDefault: true}, // remove in 1.32
```

```sh
hack/update-featuregates.sh 
found 158 features in FeatureSpecMap var defaultKubernetesFeatureGates in file: /usr/local/google/home/aojea/src/kubernetes/pkg/features/kube_features.go
found 2 features in FeatureSpecMap var defaultKubernetesFeatureGates in file: /usr/local/google/home/aojea/src/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/features/kube_features.go
found 37 features in FeatureSpecMap var defaultKubernetesFeatureGates in file: /usr/local/google/home/aojea/src/kubernetes/staging/src/k8s.io/apiserver/pkg/features/kube_features.go
found 3 features in FeatureSpecMap of func featureGates in file: /usr/local/google/home/aojea/src/kubernetes/staging/src/k8s.io/component-base/logs/api/v1/kube_features.go
found 1 features in FeatureSpecMap of func featureGates in file: /usr/local/google/home/aojea/src/kubernetes/staging/src/k8s.io/component-base/metrics/features/kube_features.go
found 3 features in FeatureSpecMap var cloudPublicFeatureGates in file: /usr/local/google/home/aojea/src/kubernetes/staging/src/k8s.io/controller-manager/pkg/features/kube_features.go
panic: feature MultiCIDRServiceAllocator changed with diff:   cmd.featureInfo{
                Name:     "MultiCIDRServiceAllocator",
                FullName: "",
                VersionedSpecs: []cmd.featureSpec{
                        {
        -                       Default:       false,
        +                       Default:       true,
                                LockToDefault: false,
                                PreRelease:    "Beta",
                                Version:       "",
                        },
                },
          }


goroutine 1 [running]:
k8s.io/kubernetes/test/featuregates_linter/cmd.updateFeatureListFunc(0xc0001f4d00?, {0x69953d?, 0x4?, 0x6994ed?})
        /usr/local/google/home/aojea/src/kubernetes/test/featuregates_linter/cmd/feature_gates.go:108 +0x91
github.com/spf13/cobra.(*Command).execute(0xc0001fc608, {0x8c8000, 0x0, 0x0})
        /usr/local/google/home/aojea/src/kubernetes/vendor/github.com/spf13/cobra/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x8a3dc0)
        /usr/local/google/home/aojea/src/kubernetes/vendor/github.com/spf13/cobra/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /usr/local/google/home/aojea/src/kubernetes/vendor/github.com/spf13/cobra/command.go:1041
k8s.io/kubernetes/test/featuregates_linter/cmd.Execute()
        /usr/local/google/home/aojea/src/kubernetes/test/featuregates_linter/cmd/root.go:32 +0x1a
main.main()
        /usr/local/google/home/aojea/src/kubernetes/test/featuregates_linter/main.go:22 +0xf
```

`verifyFeatureDeletionOnly` does not consider the command is being executed to update the files and fails, so it never updates the corresponding files

**Comment by aojea** [comment]
/assign @siyuanfoundation 
/cc @BenTheElder @logicalhan  

This was added in https://github.com/kubernetes/kubernetes/pull/125830

**Comment by BenTheElder** [comment]
cc @jpbetz @aaron-prindle @liggitt 

I feel like needing an update-features is the wrong approach and we should revisit having one source of truth and a linter.

**Comment by siyuanfoundation** [comment]
This is intended behavior. 
To encourage feature migration to the new version feature spec format, we require all new feature changes should be made through `map[Feature]VersionedSpecs` (https://github.com/kubernetes/kubernetes/issues/125031). 
The feature owner should migrate their feature to the format of `map[Feature]VersionedSpecs` first (for example in https://github.com/kubernetes/kubernetes/blob/master/pkg/features/versioned_kube_features.go) first, then make the stage/default changes. 

If you really do not want to migrate your feature, you can comment out the following lines locally and run `hack/update-featuregates.sh`
```
        if !versioned {
		if err := verifyFeatureDeletionOnly(featureList, baseFeatureList); err != nil {
			return err
		}
	}
```

**Comment by Jefftree** [comment]
Thanks for the comment @siyuanfoundation. Even though it is the expected behavior, seeing a panic line without any next steps is probably not a good user experience. I'll work on updating the check to be more clear.
