### ISSUE TITLE
[Flaking Test] master integration TestAPIServerTransportMetrics

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#127725]
### Which jobs are flaking?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1840177002766667776
and
pull-integration-master

### Which tests are flaking?

{Failed;  === RUN   TestAPIServerTransportMetrics

### Since when has it been flaking?

09-24?

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#integration-master

### Reason for failure (if possible)

```
I0929 00:18:37.984817  113612 controller.go:157] Shutting down quota evaluator
E0929 00:18:37.984844  113612 panic.go:262] "Observed a panic" panic="runtime error: invalid memory address or nil pointer dereference" panicGoValue="\"invalid memory address or nil pointer dereference\"" stacktrace=<
	goroutine 2426 [running]:
	k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3cd25a0, 0x5c6f900}, {0x3166080, 0x5ac91d0})
		/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:107 +0xbc
	k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x3cd25a0, 0x5c6f900}, {0x3166080, 0x5ac91d0}, {0x5c6f900, 0x0, 0x43d285?})
		/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:82 +0x5e
	k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc008a6a380?})
		/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:59 +0x108
	panic({0x3166080?, 0x5ac91d0?})
		/usr/local/go/src/runtime/panic.go:785 +0x132
	k8s.io/kubernetes/pkg/controlplane/controller/leaderelection.RunWithLeaderElection.func2()
		/home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/controller/leaderelection/run_with_leaderelection.go:53 +0x11
	k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc0036a0000, {0x3cd2850, 0xc00749a940})
		/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go:213 +0x13a
	k8s.io/kubernetes/pkg/controlplane/controller/leaderelection.RunWithLeaderElection({0x3cd2850, 0xc00749a940}, 0xc000598fc8, 0xc004b03e00)
		/home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/controller/leaderelection/run_with_leaderelection.go:90 +0x44e
	created by k8s.io/kubernetes/pkg/controlplane/apiserver.completedConfig.New.func2 in goroutine 2337
		/home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/apiserver/server.go:162 +0x165
 >
I0929 00:18:37.984851  113612 controller.go:176] quota evaluator worker shutdown
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2ca42b1]

goroutine 2426 [running]:
k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x3cd25a0, 0x5c6f900}, {0x3166080, 0x5ac91d0}, {0x5c6f900, 0x0, 0x43d285?})
	/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:89 +0xee
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc008a6a380?})
	/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:59 +0x108
panic({0x3166080?, 0x5ac91d0?})
	/usr/local/go/src/runtime/panic.go:785 +0x132
k8s.io/kubernetes/pkg/controlplane/controller/leaderelection.RunWithLeaderElection.func2()
	/home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/controller/leaderelection/run_with_leaderelection.go:53 +0x11
k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc0036a0000, {0x3cd2850, 0xc00749a940})
	/home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go:213 +0x13a
k8s.io/kubernetes/pkg/controlplane/controller/leaderelection.RunWithLeaderElection({0x3cd2850, 0xc00749a940}, 0xc000598fc8, 0xc004b03e00)
	/home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/controller/leaderelection/run_with_leaderelection.go:90 +0x44e
created by k8s.io/kubernetes/pkg/controlplane/apiserver.completedConfig.New.func2 in goroutine 2337
	/home/prow/go/src/k8s.io/kubernetes/pkg/controlplane/apiserver/server.go:162 +0x165
```

### Relevant SIG(s)

/sig instrumentation

**Comment by pacoxu** [comment]
/cc @sttts  
the recent update about the test https://github.com/kubernetes/kubernetes/pull/126149

**Comment by googs1025** [comment]
this is already fixed in https://github.com/kubernetes/kubernetes/pull/127675
FYI: https://github.com/kubernetes/kubernetes/pull/127675
```go
// RunWithLeaderElection only returns when the context is done, or initial
// leader election fails.
func RunWithLeaderElection(ctx context.Context, config *rest.Config, newRunnerFn NewRunner) {
	var cancel context.CancelFunc

	callbacks := leaderelection.LeaderCallbacks{
		OnStartedLeading: func(ctx context.Context) {
			ctx, cancel = context.WithCancel(ctx)
			var err error
			run, err := newRunnerFn()
			if err != nil {
				klog.Infof("Error creating runner: %v", err)
				return
			}
			run(ctx, 1)
		},
                // Here is the problem. When the OnStartedLeading method is not executed correctly, executing OnStoppedLeading will cause panic
		OnStoppedLeading: func() {
                         // here is 
			cancel()
		},
	}

	hostname, err := os.Hostname()
	if err != nil {
		klog.Infof("Error parsing hostname: %v", err)
		return
	}


```

**Comment by pacoxu** [comment]
Got it.

I may close this as dup to https://github.com/kubernetes/kubernetes/issues/127665.
