### ISSUE TITLE
Failure cluster [c81e0fc6...] `TestCreateBlobDisk` broken in `ci-kubernetes-unit-1-28` and `ci-kubernetes-unit-1-29`

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#129007]
### Failure cluster [c81e0fc6492b769bee97](https://go.k8s.io/triage#c81e0fc6492b769bee97)

![image](https://github.com/user-attachments/assets/5e0beef7-8b1a-4399-97ba-dd76df219ecc)

##### Error text:
```
Failed;
=== RUN   TestCreateBlobDisk
panic: test timed out after 3m0s
running tests:
	TestCreateBlobDisk (21s)

goroutine 214 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:2366 +0x265
created by time.goFunc
	/usr/local/go/src/time/sleep.go:177 +0x45

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0001d81a0, {0x2c01a2b, 0x12}, 0x2d0b010)
	/usr/local/go/src/testing/testing.go:1750 +0x851
testing.runTests.func1(0xc0001d81a0)
	/usr/local/go/src/testing/testing.go:2161 +0x86
testing.tRunner(0xc0001d81a0, 0xc0004c3aa8)
	/usr/local/go/src/testing/testing.go:1689 +0x21f
testing.runTests(0xc00049e168, {0x4144580, 0xf6, 0xf6}, {0xc00028d0c0?, 0x452dc5?, 0x4154300?})
	/usr/local/go/src/testing/testing.go:2159 +0x8bf
testing.(*M).Run(0xc0004f7720)
	/usr/local/go/src/testing/testing.go:2027 +0xf18
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.TestMain(0xc0004f7720)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/main_test.go:28 +0xd8
main.main()
	_testmain.go:539 +0x2d5

goroutine 129 [select]:
k8s.io/kubernetes/vendor/github.com/Azure/go-autorest/autorest.DelayForBackoffWithCap(0x12a05f200, 0x0, 0x2, 0x0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/Azure/go-autorest/autorest/sender.go:452 +0x206
k8s.io/kubernetes/vendor/github.com/Azure/go-autorest/autorest.DelayForBackoff(...)
	/home/prow/go/src/k8s.io/kubernetes/_out
```
#### Recent failures:
[11/27/2024, 8:18:59 AM ci-kubernetes-unit-1-28](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit-1-28/1861761427316936704)
[11/27/2024, 8:13:55 AM ci-kubernetes-unit-1-29](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit-1-29/1861760169118011392)
[11/27/2024, 7:18:59 AM ci-kubernetes-unit-1-28](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit-1-28/1861746327734456320)
[11/27/2024, 7:14:03 AM ci-kubernetes-unit-1-29](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit-1-29/1861745069342593024)
[11/27/2024, 6:18:54 AM ci-kubernetes-unit-1-28](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit-1-28/1861731228068089856)

/kind failing-test

**Comment by dims** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/128914

**Comment by dims** [comment]
cc @bridgetkromhout
