### ISSUE TITLE
getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by jiasir** [kubernetes/kubernetes#12904]
When execute `cluster/kube-up.sh` has the following errors:
```
TaiodeMacBook-Pro:kubernetes Taio$ cluster/kube-up.sh
Starting cluster using provider: azure
... calling verify-prereqs
==> AZ_STG: kubec635485
==> AZ_CS: kube-c635485
==> CONTAINER: kube-testing
... calling kube-up
==> SERVER_BINARY_TAR: cluster/../cluster/azure/../../cluster/../server/kubernetes-server-linux-amd64.tar.gz
==> SALT_TAR: cluster/../cluster/azure/../../cluster/../server/kubernetes-salt.tar.gz
+++ Staging server tars to Azure Storage: kubec635485
==> SERVER_BINARY_TAR_URL: https://kubec635485.blob.core.chinacloudapi.cn/kube-testing/kubernetes-server-linux-amd64.tar.gz
==> SALT_TAR_URL: https://kubec635485.blob.core.chinacloudapi.cn/kube-testing/kubernetes-salt.tar.gz
--> Checking storage exists...
--> Getting storage key...
--> Checking storage container exists...
--> Creating storage container...
info:    Executing command storage container create
+ Creating storage container kube-testing                                      
info:    Error information has been recorded to /Users/Taio/.azure/azure.err
info:    Executing command storage container create
+ Creating storage container kube-testing                                      
info:    Error information has been recorded to /Users/Taio/.azure/azure.err
info:    Executing command storage container create
+ Creating storage container kube-testing                                      
info:    Error information has been recorded to /Users/Taio/.azure/azure.err
info:    Executing command storage container create
+ Creating storage container kube-testing                                      
info:    Error information has been recorded to /Users/Taio/.azure/azure.err
info:    Executing command storage container create
+ Creating storage container kube-testing                                      
info:    Error information has been recorded to /Users/Taio/.azure/azure.err
info:    Executing command storage container create
+ Creating storage container kube-testing                                      
info:    Error information has been recorded to /Users/Taio/.azure/azure.err
info:    Executing command storage container create
+ Creating storage container kube-testing                                      
info:    Error information has been recorded to /Users/Taio/.azure/azure.err
info:    Executing command storage container create
+ Creating storage container kube-testing                                      
info:    Error information has been recorded to /Users/Taio/.azure/azure.err
info:    Executing command storage container create
+ Creating storage container kube-testing                                      
info:    Error information has been recorded to /Users/Taio/.azure/azure.err
info:    Executing command storage container create
+ Creating storage container kube-testing                                      
info:    Error information has been recorded to /Users/Taio/.azure/azure.err
error:   getaddrinfo ENOTFOUND
error:   storage container create command failed


Wed Aug 19 2015 17:46:41 GMT+0800 (CST):
{ [Error: getaddrinfo ENOTFOUND]
  stack: [Getter/Setter],
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  __frame: 
   { name: '__1',
     line: 322,
     file: '/usr/local/azure/lib/util/storage.util.js',
     prev: 
      { name: 'StorageUtil_performStorageOperation__1',
        line: 303,
        file: '/usr/local/azure/lib/util/storage.util.js',
        prev: [Object],
        calls: 1,
        active: false,
        offset: 19,
        col: 4 },
     calls: 0,
     active: false,
     offset: 2,
     col: 34 },
  rawStack: [Getter] }
Error: getaddrinfo ENOTFOUND
  <<< async stack >>>
  at __1 (/usr/local/azure/lib/util/storage.util.js:324:35)
  at StorageUtil_performStorageOperation__1 (/usr/local/azure/lib/util/storage.util.js:322:5)
  at showAzureContainer (/usr/local/azure/lib/commands/storage/storage.blob.js:413:20)
  <<< raw stack >>>
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

And how can I fix it? Thanks!

**Comment by jiasir** [comment]
I have fixed this issue, here is my solution:
microsoft gives its azure service to another cooperator partner for operating in some countries or areas, so that's a little tricky such as it has different domain name which access the azure storage service, in my country it's "http://storageaccount.table.core.chinacloudapi.cn/" , but "http://storageaccount.table.core.windows.net" in America, find azure-storage/lib/common/util/constants.jsfile and change
var storageDnsSuffix = process.env.AZURE_STORAGE_DNS_SUFFIX || 'core.windows.net';
to your suffix or redefine AZURE_STORAGE_DNS_SUFFIX environment variable, it's done.
