### ISSUE TITLE
runtime error when using OpenStack cloud provider

### ISSUE THREAD

**Issue by altvnk** [kubernetes/kubernetes#13034]
Hi,
I cannot configure OpenStack cloud provider in k8s. Apiserver fails immediately with following error:
```
Aug 21 15:58:00 k8s-master-01 kube-apiserver[29112]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 21 15:58:00 k8s-master-01 kube-apiserver[29112]: [signal 0xb code=0x1 addr=0x0 pc=0x7f43bd]
Aug 21 15:58:00 k8s-master-01 kube-apiserver[29112]: goroutine 1 [running]:
Aug 21 15:58:00 k8s-master-01 kube-apiserver[29112]: k8s.io/kubernetes/pkg/cloudprovider/providers/openstack.(*OpenStack).Instances(0x0, 0x0, 0x0, 0x6)
Aug 21 15:58:00 k8s-master-01 kube-apiserver[29112]: /builddir/build/BUILD/kubernetes-b5a4a548df0cffb99bdcc3b9b9e48d4025d0541c/_output/local/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/openstack/openstack.go:163 +0x8ed
Aug 21 15:58:00 k8s-master-01 kube-apiserver[29112]: k8s.io/kubernetes/cmd/kube-apiserver/app.(*APIServer).Run(0xc82029b500, 0xc8202b6400, 0x0, 0x10, 0x0, 0x0)
Aug 21 15:58:00 k8s-master-01 kube-apiserver[29112]: /builddir/build/BUILD/kubernetes-b5a4a548df0cffb99bdcc3b9b9e48d4025d0541c/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:384 +0x1439
Aug 21 15:58:00 k8s-master-01 kube-apiserver[29112]: main.main()
Aug 21 15:58:00 k8s-master-01 kube-apiserver[29112]: /builddir/build/BUILD/kubernetes-b5a4a548df0cffb99bdcc3b9b9e48d4025d0541c/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/apiserver.go:48 +0x171
Aug 21 15:58:00 k8s-master-01 kube-apiserver[29112]: goroutine 17 [chan receive]:
Aug 21 15:58:00 k8s-master-01 kube-apiserver[29112]: github.com/golang/glog.(*loggingT).flushDaemon(0x1d27440)
Aug 21 15:58:00 k8s-master-01 kube-apiserver[29112]: /builddir/build/BUILD/kubernetes-b5a4a548df0cffb99bdcc3b9b9e48d4025d0541c/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x67
Aug 21 15:58:00 k8s-master-01 kube-apiserver[29112]: created by github.com/golang/glog.init.1
Aug 21 15:58:00 k8s-master-01 kube-apiserver[29112]: /builddir/build/BUILD/kubernetes-b5a4a548df0cffb99bdcc3b9b9e48d4025d0541c/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297
Aug 21 15:58:00 k8s-master-01 kube-apiserver[29112]: goroutine 24 [syscall]:
Aug 21 15:58:00 k8s-master-01 kube-apiserver[29112]: os/signal.loop()
Aug 21 15:58:00 k8s-master-01 kube-apiserver[29112]: /usr/lib/golang/src/os/signal/signal_unix.go:22 +0x18
Aug 21 15:58:00 k8s-master-01 kube-apiserver[29112]: created by os/signal.init.1
Aug 21 15:58:00 k8s-master-01 kube-apiserver[29112]: /usr/lib/golang/src/os/signal/signal_unix.go:28 +0x37
Aug 21 15:58:00 k8s-master-01 kube-apiserver[29112]: goroutine 26 [runnable]:
```

`cloud.conf` contains all creds needed to operate OpenStack API, `kube-apiserver` is starting with options `--cloud-provider=openstack --cloud-config=/etc/cloud.conf`

I assume that i make a mistake in configuration, but there no information how to do it right.
If needed i can put full log pastebin.

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
