### ISSUE TITLE
Gcloud::Datastore::ApiError: API call to commit was not successful

### ISSUE THREAD

**Issue by enzomd** [kubernetes/kubernetes#13387]
```
[
    "/usr/local/bundle/bundler/gems/gcloud-ruby-b2860dc8b0e4/lib/gcloud/datastore/connection.rb:164:in `rpc'",
    "/usr/local/bundle/bundler/gems/gcloud-ruby-b2860dc8b0e4/lib/gcloud/datastore/connection.rb:100:in `commit'",
    "/usr/local/bundle/bundler/gems/gcloud-ruby-b2860dc8b0e4/lib/gcloud/datastore/dataset.rb:137:in `save'"
]
```
This happens quite often, I do not think I have hit my datastore quota limit.

What are some of the reasons that would cause a write to fail?

**Comment by sajjadmurtaza-ror** [comment]
Gcloud::Datastore::ApiError in

**Comment by sajjadmurtaza-ror** [comment]
Same issue
