### ISSUE TITLE
Docker on vagrant broken?

### ISSUE THREAD

**Issue by vsimon** [kubernetes/kubernetes#13484]
I'm trying to use docker on a vagrant kubernetes minion but I'm getting a weird error and a crash in the docker logs. Has anybody seen something like this before? I'm using busybox as a minimal example here. Tried this on Kubernetes version 1.0.1 release packages as well as 1.1.0-alpha.1. Same on both.

KUBERNETES_PROVIDER=vagrant cluster/kube-up.sh
vagrant ssh minion-1
Tried to do: sudo docker run -it --rm=true busybox

```
[vagrant@kubernetes-minion-1 ~]$ sudo docker run -it --rm=true busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from docker.io/busybox
cf2616975b4a: Pull complete 
6ce2e90b0bc7: Pull complete 
8c2e06607696: Already exists 
docker.io/busybox:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:38a203e1986cf79639cfb9b2e1d6e773de84002feea2d4eb006b52004ee8502d
Status: Downloaded newer image for docker.io/busybox:latest
/ # Error deleting container: Error response from daemon: Cannot destroy container 3f64a734488aa5fdada80ad06c8e1bf09136f20f1d5157c749395435bc7fac5b: Conflict, You cannot remove a running container. Stop the container before attempting removal or use -fPost http:///var/run/docker.sock/v1.19/containers/3f64a734488aa5fdada80ad06c8e1bf09136f20f1d5157c749395435bc7fac5b/start: EOF. Are you trying to connect to a TLS-enabled daemon without TLS?
[vagrant@kubernetes-minion-1 ~]$ 
```

```
[vagrant@kubernetes-minion-1 ~]$ sudo docker version
Client version: 1.7.1.fc21
Client API version: 1.19
Package Version (client): docker-io-1.7.1-3.git33de319.fc21.x86_64
Go version (client): go1.4.2
Git commit (client): 33de319/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1.fc21
Server API version: 1.19
Package Version (server): docker-io-1.7.1-3.git33de319.fc21.x86_64
Go version (server): go1.4.2
Git commit (server): 33de319/1.7.1
OS/Arch (server): linux/amd64
```

journalctl -f

```
ep 02 00:14:45 kubernetes-minion-1 sudo[5294]: vagrant : TTY=pts/0 ; PWD=/home/vagrant ; USER=root ; COMMAND=/bin/docker run -it --rm=true busybox
Sep 02 00:14:45 kubernetes-minion-1 docker[3145]: time="2015-09-02T00:14:45.434455611Z" level=info msg="POST /v1.19/containers/create"
Sep 02 00:14:45 kubernetes-minion-1 kernel: EXT4-fs (dm-12): mounted filesystem with ordered data mode. Opts: (null)
Sep 02 00:14:45 kubernetes-minion-1 kernel: SELinux: initialized (dev dm-12, type ext4), uses xattr
Sep 02 00:14:45 kubernetes-minion-1 kernel: EXT4-fs (dm-12): mounted filesystem with ordered data mode. Opts: (null)
Sep 02 00:14:45 kubernetes-minion-1 kernel: SELinux: initialized (dev dm-12, type ext4), uses xattr
Sep 02 00:14:45 kubernetes-minion-1 docker[3145]: time="2015-09-02T00:14:45.863065618Z" level=info msg="GET /version"
Sep 02 00:14:45 kubernetes-minion-1 docker[3145]: time="2015-09-02T00:14:45.956305377Z" level=info msg="POST /v1.19/containers/d79fb0f90cd47379084fea710309aa16001e09e7a6374283759d7b2209bf0f89/attach?stderr=1&stdin=1&stdout=1&stream=1"
Sep 02 00:14:45 kubernetes-minion-1 docker[3145]: time="2015-09-02T00:14:45.957585958Z" level=info msg="POST /v1.19/containers/d79fb0f90cd47379084fea710309aa16001e09e7a6374283759d7b2209bf0f89/start"
Sep 02 00:14:46 kubernetes-minion-1 kernel: EXT4-fs (dm-12): mounted filesystem with ordered data mode. Opts: (null)
Sep 02 00:14:46 kubernetes-minion-1 kernel: SELinux: initialized (dev dm-12, type ext4), uses xattr
Sep 02 00:14:46 kubernetes-minion-1 kernel: device veth7b91045 entered promiscuous mode
Sep 02 00:14:46 kubernetes-minion-1 kernel: IPv6: ADDRCONF(NETDEV_UP): veth0e7c056: link is not ready
Sep 02 00:14:46 kubernetes-minion-1 kernel: cbr0: port 5(veth7b91045) entered forwarding state
Sep 02 00:14:46 kubernetes-minion-1 kernel: cbr0: port 5(veth7b91045) entered forwarding state
Sep 02 00:14:46 kubernetes-minion-1 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth0e7c056: link becomes ready
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> (veth0e7c056): link connected
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> (veth0e7c056): carrier is ON
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> (veth0e7c056): new Veth device (driver: 'unknown' ifindex: 14)
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> (veth0e7c056): exported as /org/freedesktop/NetworkManager/Devices/13
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> (veth7b91045): link connected
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> (veth7b91045): carrier is ON
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> (veth7b91045): new Veth device (driver: 'unknown' ifindex: 15)
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> (veth7b91045): exported as /org/freedesktop/NetworkManager/Devices/14
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info>     read connection 'veth7b91045'
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> (veth7b91045): device state change: unmanaged -> unavailable (reason 'connection-assumed') [10 20 41]
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> (cbr0): bridge port veth7b91045 was attached
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> (veth7b91045): enslaved to cbr0
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> (veth7b91045): device state change: unavailable -> disconnected (reason 'connection-assumed') [20 30 41]
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> Activation (veth7b91045) starting connection 'veth7b91045'
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> Activation (veth7b91045) Stage 1 of 5 (Device Prepare) scheduled...
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> Activation (veth7b91045) Stage 1 of 5 (Device Prepare) started...
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> (veth7b91045): device state change: disconnected -> prepare (reason 'none') [30 40 0]
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> Activation (veth7b91045) Stage 2 of 5 (Device Configure) scheduled...
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> Activation (veth7b91045) Stage 1 of 5 (Device Prepare) complete.
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> Activation (veth7b91045) Stage 2 of 5 (Device Configure) starting...
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> (veth7b91045): device state change: prepare -> config (reason 'none') [40 50 0]
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> Activation (veth7b91045) Stage 2 of 5 (Device Configure) successful.
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> Activation (veth7b91045) Stage 3 of 5 (IP Configure Start) scheduled.
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> Activation (veth7b91045) Stage 2 of 5 (Device Configure) complete.
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> Activation (veth7b91045) Stage 3 of 5 (IP Configure Start) started...
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> (veth7b91045): device state change: config -> ip-config (reason 'none') [50 70 0]
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> Activation (veth7b91045) Stage 3 of 5 (IP Configure Start) complete.
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> (veth7b91045): device state change: ip-config -> secondaries (reason 'none') [70 90 0]
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> (veth7b91045): device state change: secondaries -> activated (reason 'none') [90 100 0]
Sep 02 00:14:46 kubernetes-minion-1 NetworkManager[477]: <info> Activation (veth7b91045) successful, device activated.
Sep 02 00:14:46 kubernetes-minion-1 dbus[484]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
Sep 02 00:14:46 kubernetes-minion-1 systemd[1]: Starting Network Manager Script Dispatcher Service...
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: time="2015-09-02T00:14:46.142781205Z" level=info msg="GET /containers/NetworkManager-dispatcher.service/json"
Sep 02 00:14:46 kubernetes-minion-1 kernel: eth0: renamed from veth0e7c056
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: time="2015-09-02T00:14:46.143110450Z" level=error msg="Handler for GET /containers/{name:.*}/json returned error: no such id: NetworkManager-dispatcher.service"
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: time="2015-09-02T00:14:46.143163266Z" level=error msg="HTTP Error" err="no such id: NetworkManager-dispatcher.service" statusCode=404
Sep 02 00:14:46 kubernetes-minion-1 dbus[484]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Sep 02 00:14:46 kubernetes-minion-1 nm-dispatcher[5337]: Dispatching action 'up' for veth7b91045
Sep 02 00:14:46 kubernetes-minion-1 kernel: SELinux: initialized (dev tmpfs, type tmpfs), uses transition SIDs
Sep 02 00:14:46 kubernetes-minion-1 kernel: SELinux: initialized (dev mqueue, type mqueue), uses transition SIDs
Sep 02 00:14:46 kubernetes-minion-1 kernel: SELinux: initialized (dev proc, type proc), uses genfs_contexts
Sep 02 00:14:46 kubernetes-minion-1 systemd[1]: Started Network Manager Script Dispatcher Service.
Sep 02 00:14:46 kubernetes-minion-1 systemd[1]: Starting docker container d79fb0f90cd47379084fea710309aa16001e09e7a6374283759d7b2209bf0f89.
Sep 02 00:14:46 kubernetes-minion-1 systemd[1]: Started docker container d79fb0f90cd47379084fea710309aa16001e09e7a6374283759d7b2209bf0f89.
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: time="2015-09-02T00:14:46.192793919Z" level=info msg="GET /containers/d79fb0f90cd47379084fea710309aa16001e09e7a6374283759d7b2209bf0f89/json"
Sep 02 00:14:46 kubernetes-minion-1 kernel: SELinux: initialized (dev tmpfs, type tmpfs), uses transition SIDs
Sep 02 00:14:46 kubernetes-minion-1 kernel: SELinux: initialized (dev devpts, type devpts), uses transition SIDs
Sep 02 00:14:46 kubernetes-minion-1 kernel: SELinux: initialized (dev tmpfs, type tmpfs), uses transition SIDs
Sep 02 00:14:46 kubernetes-minion-1 kernel: SELinux: initialized (dev sysfs, type sysfs), uses genfs_contexts
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: 2015/09/02 00:14:46 http: panic serving @: runtime error: slice bounds out of range
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: goroutine 1771 [running]:
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: net/http.func·011()
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: /usr/lib/golang/src/net/http/server.go:1130 +0xbb fp=0xc208c4d328 sp=0xc208c4d248
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: runtime.call16(0xc208c4def0, 0xc208413170, 0x0)
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: /usr/lib/golang/src/runtime/asm_amd64.s:401 +0x45 fp=0xc208c4d340 sp=0xc208c4d328
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: runtime.gopanic(0xb89f60, 0xc20802a010)
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: /usr/lib/golang/src/runtime/panic.go:387 +0x3a8 fp=0xc208c4d3a8 sp=0xc208c4d340
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: runtime.panicslice()
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: /usr/lib/golang/src/runtime/panic.go:18 +0x4e fp=0xc208c4d3d0 sp=0xc208c4d3a8
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: github.com/docker/docker/pkg/systemd.RegisterMachine(0xc2088c3db1, 0xe, 0xc208abff80, 0x40, 0x14de, 0xc65450, 0x1, 0x0, 0x0)
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: /builddir/build/BUILD/docker-33de3192f50bc95ecd3b9583ce5a1ad65000c470/_build/src/github.com/docker/docker/pkg/systemd/register.go:33 +0x624 fp=0xc208c4d510 sp=0xc208c4d3d0
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: github.com/docker/docker/daemon.(*Container).registerMachine(0xc20811de00)
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: /builddir/build/BUILD/docker-33de3192f50bc95ecd3b9583ce5a1ad65000c470/_build/src/github.com/docker/docker/daemon/container_linux.go:1044 +0xa4 fp=0xc208c4d5e8 sp=0xc208c4d510
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: github.com/docker/docker/daemon.(*Container).waitForStart(0xc20811de00, 0x0, 0x0)
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: /builddir/build/BUILD/docker-33de3192f50bc95ecd3b9583ce5a1ad65000c470/_build/src/github.com/docker/docker/daemon/container.go:761 +0x2e6 fp=0xc208c4d718 sp=0xc208c4d5e8
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: github.com/docker/docker/daemon.(*Container).Start(0xc20811de00, 0x0, 0x0)
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: /builddir/build/BUILD/docker-33de3192f50bc95ecd3b9583ce5a1ad65000c470/_build/src/github.com/docker/docker/daemon/container.go:295 +0x4cd fp=0xc208c4d828 sp=0xc208c4d718
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: github.com/docker/docker/daemon.(*Daemon).ContainerStart(0xc2080be2a0, 0xc20887d977, 0x40, 0x0, 0x0, 0x0)
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: /builddir/build/BUILD/docker-33de3192f50bc95ecd3b9583ce5a1ad65000c470/_build/src/github.com/docker/docker/daemon/start.go:35 +0x243 fp=0xc208c4d8f8 sp=0xc208c4d828
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: github.com/docker/docker/api/server.(*Server).postContainersStart(0xc2080d6440, 0xc20887d967, 0x4, 0x7f6b3f0f9e78, 0xc208679400, 0xc20857fd40, 0xc208c1f620, 0x0, 0x0)
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: /builddir/build/BUILD/docker-33de3192f50bc95ecd3b9583ce5a1ad65000c470/_build/src/github.com/docker/docker/api/server/server.go:1032 +0x162 fp=0xc208c4d990 sp=0xc208c4d8f8
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: github.com/docker/docker/api/server.*Server.(github.com/docker/docker/api/server.postContainersStart)·fm(0xc20887d967, 0x4, 0x7f6b3f0f9e78, 0xc208679400, 0xc20857fd40, 0xc208c1f620, 0x0, 0x0)
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: /builddir/build/BUILD/docker-33de3192f50bc95ecd3b9583ce5a1ad65000c470/_build/src/github.com/docker/docker/api/server/server.go:1616 +0x7b fp=0xc208c4d9e0 sp=0xc208c4d990
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: github.com/docker/docker/api/server.func·008(0x7f6b3f0f9e78, 0xc208679400, 0xc20857fd40)
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: /builddir/build/BUILD/docker-33de3192f50bc95ecd3b9583ce5a1ad65000c470/_build/src/github.com/docker/docker/api/server/server.go:1566 +0xacd fp=0xc208c4db88 sp=0xc208c4d9e0
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: net/http.HandlerFunc.ServeHTTP(0xc208037bc0, 0x7f6b3f0f9e78, 0xc208679400, 0xc20857fd40)
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: /usr/lib/golang/src/net/http/server.go:1265 +0x41 fp=0xc208c4dba8 sp=0xc208c4db88
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc2080dd2c0, 0x7f6b3f0f9e78, 0xc208679400, 0xc20857fd40)
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: /builddir/build/BUILD/docker-33de3192f50bc95ecd3b9583ce5a1ad65000c470/vendor/src/github.com/gorilla/mux/mux.go:98 +0x297 fp=0xc208c4dcb0 sp=0xc208c4dba8
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: net/http.serverHandler.ServeHTTP(0xc20819c0c0, 0x7f6b3f0f9e78, 0xc208679400, 0xc20857fd40)
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: /usr/lib/golang/src/net/http/server.go:1703 +0x19a fp=0xc208c4dd08 sp=0xc208c4dcb0
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: net/http.(*conn).serve(0xc208678f00)
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: /usr/lib/golang/src/net/http/server.go:1204 +0xb57 fp=0xc208c4dfd8 sp=0xc208c4dd08
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: runtime.goexit()
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: /usr/lib/golang/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208c4dfe0 sp=0xc208c4dfd8
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: created by net/http.(*Server).Serve
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: /usr/lib/golang/src/net/http/server.go:1751 +0x35e
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: time="2015-09-02T00:14:46.285925938Z" level=info msg="DELETE /v1.19/containers/d79fb0f90cd47379084fea710309aa16001e09e7a6374283759d7b2209bf0f89?v=1"
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: time="2015-09-02T00:14:46.286026768Z" level=error msg="Handler for DELETE /containers/{name:.*} returned error: Cannot destroy container d79fb0f90cd47379084fea710309aa16001e09e7a6374283759d7b2209bf0f89:
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: time="2015-09-02T00:14:46.286109436Z" level=error msg="HTTP Error" err="Cannot destroy container d79fb0f90cd47379084fea710309aa16001e09e7a6374283759d7b2209bf0f89: Conflict, You cannot remove a running c
Sep 02 00:14:46 kubernetes-minion-1 docker[3145]: time="2015-09-02T00:14:46.286567902Z" level=info msg="GET /containers/d79fb0f90cd47379084fea710309aa16001e09e7a6374283759d7b2209bf0f89/json"
```

**Comment by mwielgus** [comment]
cc: @fgrzadkowski

**Comment by vsimon** [comment]
Tried again today, still seeing this issue.

**Comment by vsimon** [comment]
Tried again today and its looking better.
