### ISSUE TITLE
https-nginx example fails to execute on Macintosh

### ISSUE THREAD

**Issue by nirving-versent** [kubernetes/kubernetes#14022]
Whilst investigating the cause of https://github.com/kubernetes/kubernetes/issues/14017 it has become apparent that the configuration used in the ```k8s.io/kubernetes/examples/https-nginx/Makefile``` causes 
```
fork/exec /var/folders/t1/sz_cq1tj337_dfk4ryjtm1_80000gn/T/go-build506171035/command-line-arguments/_obj/exe/make_secret: exec format error
```
if the line
```
CGO_ENABLED=0 GOOS=linux go run -a -installsuffix cgo -ldflags '-w' make_secret.go -crt $(CERT) -key $(KEY) > $(SECRET)
```
is changed to
```
CGO_ENABLED=0 GOOS=darwin go run -a -installsuffix cgo -ldflags '-w' make_secret.go -crt $(CERT) -key $(KEY) > $(SECRET)
```
I get a new error
```
panic: no version is registered for group 

goroutine 1 [running]:
k8s.io/kubernetes/pkg/api/latest.GroupMetaMap.GroupOrDie(0x820924870, 0x0, 0x0, 0x8208bcc40)
	/Users/nirving/go/src/k8s.io/kubernetes/pkg/api/latest/latest.go:69 +0x1b2
k8s.io/kubernetes/pkg/api/latest.(GroupMetaMap).GroupOrDie-fm(0x0, 0x0, 0x8208abed0)
	/Users/nirving/go/src/k8s.io/kubernetes/pkg/api/latest/latest.go:34 +0x37
main.main()
	/Users/nirving/go/src/k8s.io/kubernetes/examples/https-nginx/make_secret.go:65 +0x27e

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x775040)
	/Users/nirving/go/src/github.com/golang/glog/glog.go:879 +0x67
created by github.com/golang/glog.init.1
	/Users/nirving/go/src/github.com/golang/glog/glog.go:410 +0x297
exit status 2
make: *** [secret] Error 1
```

I managed to get this to work on tag v1.0.3 and V1.0.6 and @mikedanese suggested changing it to
```go run make_secret.go -crt /tmp/nginx.crt -key /tmp/nginx.key``` which also worked.

This is failing on the ```master``` branch.

**Comment by mikedanese** [comment]
cc @bprashanth since you might be fixing this example already.

**Comment by dims** [comment]
@mikedanese @bprashanth @nirving-versent : we can close this issue as this was fixed a while ago in
https://github.com/kubernetes/kubernetes/commit/3c2a7611bf9c2c9baed018a7198f03a7bd29ac5b
