### ISSUE TITLE
kubectl logs returns x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by gosharplite** [kubernetes/kubernetes#14097]
My v1.0.6 k8s cluster is working fine. My guestbook example is also working.
![screenshot from 2015-09-17 14 57 59](https://cloud.githubusercontent.com/assets/5064483/9926945/a9729914-5d4c-11e5-9598-9921c128b7bf.png)
<hr>
I can `kubectl get po`.
```
$ ./kubectl get pod
NAME                 READY     STATUS    RESTARTS   AGE
frontend-0d1d3       1/1       Running   0          2h
frontend-6npht       1/1       Running   0          2h
frontend-xnxh6       1/1       Running   0          2h
redis-master-wtc0v   1/1       Running   0          2h
redis-slave-0p33w    1/1       Running   0          2h
redis-slave-p3of6    1/1       Running   0          2h
```
But I can't `kubectl logs`. My worker node ip is `192.168.122.143`.
```
$ ./kubectl logs redis-master-wtc0v
Error from server: Get https://192.168.122.143:10250/containerLogs/tyd/redis-master-wtc0v/master: x509: certificate signed by unknown authority
```
I could use `curl -k` to get the logs though.
```
$ curl -k https://192.168.122.143:10250/containerLogs/tyd/redis-master-wtc0v/master
1:C 17 Sep 04:04:59.582 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 17 Sep 04:04:59.584 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
1:M 17 Sep 04:04:59.584 # Redis can't set maximum open files to 10032 because of OS error: Operation not permitted.
1:M 17 Sep 04:04:59.584 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 3.0.3 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

1:M 17 Sep 04:04:59.584 # Server started, Redis version 3.0.3
```
I read #3168 #3481 #6363 #11816 and not sure if `ssh tunnels from the master` is the solution.
Appreciate any direction to solve this 'kubectl logs' issue.

**Comment by gosharplite** [comment]
I set the kubelet tls file flags `--tls-cert-file` and `--tls-private-key-file` as shown below.
```
kubelet \
  --address=0.0.0.0 \
  --port=10250 \
  --hostname_override=${DEFAULT_IPV4} \
  --api_servers=https://192.168.122.189:443 \
  --kubeconfig=/srv/kubelet/kubeconfig \
  --pod_infra_container_image=192.168.122.74:5000/kubernetes/pause \
  --logtostderr=true \
  --cluster_dns=10.0.0.10 \
  --cluster_domain=cluster.local \
  --node-status-update-frequency=5s \
  --tls-cert-file=/srv/kubernetes/kubelet.crt \
  --tls-private-key-file=/srv/kubernetes/kubelet.key
```
It doesn't work, because it doesn't contain any IP SANs.
```
$ ./kubectl logs redis-master-g5vvg
Error from server: Get https://192.168.122.143:10250/containerLogs/tyd/redis-master-g5vvg/master: x509: cannot validate certificate for 192.168.122.143 because it doesn't contain any IP SANs
```

**Comment by gosharplite** [comment]
I have reverted my kubelet settings as shown below.
```
kubelet \
  --address=0.0.0.0 \
  --port=10250 \
  --hostname_override=${DEFAULT_IPV4} \
  --api_servers=https://192.168.122.189:443 \
  --kubeconfig=/srv/kubelet/kubeconfig \
  --pod_infra_container_image=192.168.122.74:5000/kubernetes/pause \
  --logtostderr=true \
  --cluster_dns=10.0.0.10 \
  --cluster_domain=cluster.local \
  --node-status-update-frequency=5s
```
As expected, `x509: certificate signed by unknown authority` still exists.
```
$ ./kubectl logs redis-master-9l9ss
Error from server: Get https://192.168.122.143:10250/containerLogs/tyd/redis-master-9l9ss/master: x509: certificate signed by unknown authority
```
Logs generated by the kube-apiserver are shown below.
```
Sep 17 08:56:35 master kube-apiserver[722]: I0917 08:56:35.743404     722 handlers.go:137] GET /api: (61.901µs) 200 [[kubectl/v1.0.6 (linux/amd64) kubernetes/388061f] 192.168.122.1:55617]
Sep 17 08:56:35 master kube-apiserver[722]: I0917 08:56:35.757231     722 handlers.go:137] GET /api/v1/namespaces/tyd/pods/redis-master-9l9ss: (1.158856ms) 200 [[kubectl/v1.0.6 (linux/amd64) kubernetes/388061f] 192.168.122.1:55618]
Sep 17 08:56:35 master kube-apiserver[722]: E0917 08:56:35.761010     722 apiserver.go:292] apiserver was unable to write a JSON response: Get https://192.168.122.143:10250/containerLogs/tyd/redis-master-9l9ss/master: x509: certificate signed by unknown authority
Sep 17 08:56:35 master kube-apiserver[722]: E0917 08:56:35.761023     722 errors.go:62] apiserver received an error that is not an api.Status: Get https://192.168.122.143:10250/containerLogs/tyd/redis-master-9l9ss/master: x509: certificate signed by unknown authority
Sep 17 08:56:35 master kube-apiserver[722]: I0917 08:56:35.761098     722 handlers.go:137] GET /api/v1/namespaces/tyd/pods/redis-master-9l9ss/log?container=master&follow=false&previous=false: (1.76518ms) 500
Sep 17 08:56:35 master kube-apiserver[722]: goroutine 93782 [running]:
Sep 17 08:56:35 master kube-apiserver[722]: k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc208fe19e0, 0x1f4)
Sep 17 08:56:35 master kube-apiserver[722]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:188 +0x9a
Sep 17 08:56:35 master kube-apiserver[722]: k8s.io/kubernetes/pkg/apiserver.errorJSONFatal(0x0, 0x0, 0x7f65764d70c0, 0xc2080d4640, 0x7f65764feea8, 0xc208fe19e0, 0x0)
Sep 17 08:56:35 master kube-apiserver[722]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:301 +0x42d
Sep 17 08:56:35 master kube-apiserver[722]: k8s.io/kubernetes/pkg/apiserver.write(0xc8, 0x1383990, 0x2, 0x7f65764d70c0, 0xc2080d4640, 0x7f6576303650, 0xc2092238c0, 0x7f65764feea8, 0xc208fe19e0, 0xc2087f00d0)
Sep 17 08:56:35 master kube-apiserver[722]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:222 +0x196
Sep 17 08:56:35 master kube-apiserver[722]: k8s.io/kubernetes/pkg/apiserver.func·018(0xc209222390, 0xc208b9fc20)
Sep 17 08:56:35 master kube-apiserver[722]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:105 +0x32c
Sep 17 08:56:35 master kube-apiserver[722]: github.com/emicklei/go-restful.func·005(0xc209222390, 0xc208b9fc20)
Sep 17 08:56:35 master kube-apiserver[722]: /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:215 +0x41
Sep 17 08:56:35 master kube-apiserver[722]: github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc209222480, 0xc209222390, 0xc208b9fc20)
Sep 17 08:56:35 master kube-apiserver[722]: /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
Sep 17 08:56:35 master kube-apiserver[722]: k8s.io/kubernetes/pkg/apiserver.func·003(0xc209222390, 0xc208b9fc20, 0xc209222480)
Sep 17 08:56:35 master kube-apiserver[722]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:59 +0x88
Sep 17 08:56:35 master kube-apiserver[722]: github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc209222480, 0xc209222390, 0xc208b9fc20)
Sep 17 08:56:35 master kube-apiserver[722]: /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19 +0x84
Sep 17 08:56:35 master kube-apiserver[722]: github.com/emicklei/go-restful.(*Container).dispatch(0xc2082e3570, 0x7f65764feea8, 0xc208fe19e0, 0xc2087f00d0)
Sep 17 08:56:35 master kube-apiserver[722]: /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:217 +0xecf
Sep 17 08:56:35 master kube-apiserver[722]: github.com/emicklei/go-restful.*Container.(github.com/emicklei/go-restful.dispatch)·fm(0x7f65764feea8, 0xc208fe19e0, 0xc2087f00d0)
Sep 17 08:56:35 master kube-apiserver[722]: /go/src/k8s.io/kubernetes/Godeps/_workspace/sr [[kubectl/v1.0.6 (linux/amd64) kubernetes/388061f] 192.168.122.1:55618]
```

**Comment by alex-mohr** [comment]
@gosharplite you didn't mention which environment you're running in or how you set up the cluster -- details please?  Also, did you manually generate those cert files, and if so, what commands?

@roberthbailey more cert stuff.  Is this worth an explicit section in one of the (many) troubleshooting guides, such as http://kubernetes.io/v1.0/docs/admin/cluster-troubleshooting.html ?

**Comment by gosharplite** [comment]
@alex-mohr My cluster is created from scratch base on [Getting started from Scratch](http://kubernetes.io/v1.0/docs/getting-started-guides/scratch.html). [Fleet](https://coreos.com/using-coreos/clustering/) is used to deploy K8s on top of a CoreOS cluster. Cert files are generated base on [Security Models](http://kubernetes.io/v1.0/docs/getting-started-guides/scratch.html#security-models). Commands are from the function `create-certs` in `cluster/gce/util.sh`.

The problem is my apiserver can't https to kubelet as shown in the logs above. The result is kubectl logs/exec fail to work.

This issue might link to  `Secure master -> node communication` #11816. My understanding is that there are three solutions.
- unified CA with server cert per node
- ssh tunnels from the master
- Add a bastion to apiserver #3481 (remove logs/exec function from apiserver)

Digging into salt scripts didn't help. I failed to find how secure master -> node communication is currently implemented in GKE/GCE.

**Comment by gosharplite** [comment]
It seems if I get rid of below parameters from kube-apiserver, `kubectl logs/exec` works.
```
  --kubelet-certificate-authority=/srv/kubernetes/ca.crt \
  --kubelet-client-certificate=/srv/kubernetes/kubelet.crt \
  --kubelet-client-key=/srv/kubernetes/kubelet.key \
```
I will create my k8s cluster from scratch and do more testing.

**Comment by gosharplite** [comment]
I have re-created my cluster and everything is working fine :100: 
FYR, below are the configurations.
```
kube-apiserver \
  --admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota \
  --authorization-mode=ABAC \
  --authorization-policy-file=/srv/kube-apiserver/auth_policy.csv \
  --basic_auth_file=/srv/kube-apiserver/basic_auth.csv \
  --client-ca-file=/srv/kubernetes/ca.crt \
  --etcd_servers="http://192.168.122.2:2379" \
  --logtostderr=true \
  --secure-port=443 \
  --service-cluster-ip-range=10.0.0.0/16 \
  --service-account-key-file=/srv/kubernetes/server.key \
  --tls-cert-file=/srv/kubernetes/server.crt \
  --tls-private-key-file=/srv/kubernetes/server.key \
  --token_auth_file=/srv/kube-apiserver/known_tokens.csv \
  --v=2
```
```
kube-controller-manager \
  --master=127.0.0.1:8080 \
  --logtostderr=true \
  --node-monitor-grace-period=7s \
  --pod-eviction-timeout=5s \
  --root-ca-file=/srv/kubernetes/ca.crt \
  --service-account-private-key-file=/srv/kubernetes/server.key
```
```
kube-scheduler --master=127.0.0.1:8080
```
```
kubelet \
  --address=0.0.0.0 \
  --port=10250 \
  --hostname_override=${DEFAULT_IPV4} \
  --api_servers=https://192.168.122.24:443 \
  --kubeconfig=/srv/kubelet/kubeconfig \
  --pod_infra_container_image=192.168.122.2:5000/kubernetes/pause \
  --logtostderr=true \
  --cluster_dns=10.0.0.10 \
  --cluster_domain=cluster.local \
  --node-status-update-frequency=5s
```
```
kube-proxy \
  --master=https://192.168.122.24:443 \
  --kubeconfig=/srv/kube-proxy/kubeconfig \
  --logtostderr=true
```

**Comment by roberthbailey** [comment]
@gosharplite - sorry for the delay in responding. For GCE we don't enable certificate checks between the master and the nodes because they are running within the same private network (which is assumed to be secured). For GKE we use the ssh tunnels to connect the master to the nodes across public IPs. RedHat uses certificate checks to secure this code (as mentioned in https://github.com/kubernetes/kubernetes/issues/11816) but most automated setup scripts don't yet do this, since it requires extra certificate plumbing.

**Comment by gosharplite** [comment]
@roberthbailey Thanks for the security hint! I see now it's better to protect kubelet api endpoints with certificate checks. Below are the extra certificate plumbing and configurations.

Base on `create-certs` in `cluster/gce/util.sh`, generate server keypair with correct `--subject-alt-name`  for each kubelet node. 
```
$ ./easyrsa --subject-alt-name="IP:192.168.122.221" build-server-full "kubelet-0" nopass
```
`kubelet-0.crt` and `kubelet-0.key` will be created for the kubelet server at 192.168.122.221 .

Add below parameters to the apiserver.
```
  --kubelet-certificate-authority=/srv/kubernetes/ca.crt \
  --kubelet-client-certificate=/srv/kubernetes/server.crt \
  --kubelet-client-key=/srv/kubernetes/server.key \
```
Add below parameters to the kubelet.
```
  --tls-cert-file=/srv/kubernetes/kubelet-0.crt \
  --tls-private-key-file=/srv/kubernetes/kubelet-0.key
``` 
Revised configurations are shown below.
```
kube-apiserver \
  --admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota \
  --authorization-mode=ABAC \
  --authorization-policy-file=/srv/kube-apiserver/auth_policy.csv \
  --basic_auth_file=/srv/kube-apiserver/basic_auth.csv \
  --client-ca-file=/srv/kubernetes/ca.crt \
  --etcd_servers="http://192.168.122.2:2379" \
  --kubelet-certificate-authority=/srv/kubernetes/ca.crt \
  --kubelet-client-certificate=/srv/kubernetes/server.crt \
  --kubelet-client-key=/srv/kubernetes/server.key \
  --logtostderr=true \
  --secure-port=443 \
  --service-cluster-ip-range=10.0.0.0/16 \
  --service-account-key-file=/srv/kubernetes/server.key \
  --tls-cert-file=/srv/kubernetes/server.crt \
  --tls-private-key-file=/srv/kubernetes/server.key \
  --token_auth_file=/srv/kube-apiserver/known_tokens.csv \
  --v=2
```
```
kubelet \
  --address=0.0.0.0 \
  --port=10250 \
  --hostname_override=${DEFAULT_IPV4} \
  --api_servers=https://192.168.122.24:443 \
  --kubeconfig=/srv/kubelet/kubeconfig \
  --pod_infra_container_image=192.168.122.2:5000/kubernetes/pause \
  --logtostderr=true \
  --cluster_dns=10.0.0.10 \
  --cluster_domain=cluster.local \
  --node-status-update-frequency=5s \
  --tls-cert-file=/srv/kubernetes/kubelet-0.crt \
  --tls-private-key-file=/srv/kubernetes/kubelet-0.key
```
The above certificate plumbing and configurations might be temporary.
See [#156 (comment)](https://github.com/kubernetes/kubernetes/issues/156#issuecomment-74364783) and [#3481 (comment)](https://github.com/kubernetes/kubernetes/issues/3481#issuecomment-74937184)

**Comment by diranged** [comment]
It seems like the real problem here is the strict-ness that `kube-apiserver` has with regards to the SSL validity. Requiring every single host in our environment that runs `kubelet` to have a properly generated SSL cert with the IP SAN and/or the fully qualified hostname in it is pretty arduous.

If `kube-apiserver` provided an `--tls-skip-host-verify` type option, that would make it easy enough for us to use SSL for authentication and encryption, while not necessarily using it to ensure actual server identity.

For the time being, I may have to disable SSL entirely here .. which is surely worse than the above option.

**Comment by diranged** [comment]
Ok -- my previous comment was a bit uninformed. I havn't disabled SSL _entirely_ (as thats not possible), but by removing the `--kubelet-tls...` settings from our `kube-apiserver`, we have effectively disabled SSL verification when the apiserver is reaching out to the kubelets. For the short term this is OK,  but ultimately it would be nice to be able to only disable *host name* verification, and nothing else.

**Comment by roberthbailey** [comment]
@diranged I agree it would be nice to just disable host name verification -- do you know of any easy way to do this with the Go SSL libraries? Using `InsecureSkipVerify` is a pretty big hammer (effective for getting things up and running, but not good for trying to run a production system) but I don't see anything more precise that is an easy knob to configure using the default libraries.

**Comment by Davei7** [comment]
Good night,
I got the same issue while doing a native installation of Kubernetes. As this is an old thread, please give feedback which I will explain later. I was using token bootstrapping at the same time (challenging myself).
