### ISSUE TITLE
e2e flaky tests: Multiple tests failing with "Kubelet stopped posting node status."

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#14211]
For example: 

/job/kubernetes-e2e-gce-parallel/7979

 Node e2e-test-parallel-minion-5mr3 condition 1/1: type: Ready, status: Unknown, reason: "NodeStatusUnknown", message: "Kubelet stopped posting node status.", last transition time: 2015-09-18 15:10:00 -0700 PDT

**Comment by quinton-hoole** [comment]
In the above case it was a single node that went AWOL after about 18 successful tests:

e2e-test-parallel-minion-5mr3

**Comment by quinton-hoole** [comment]
Looks like #13417 might be the culprit.

**Comment by quinton-hoole** [comment]
Before job/kubernetes-e2e-gce-parallel/7957 we didn't see this.  After that, the problem occurs frequently.  #13417 changes the way we do node status reporting, and merged precisely at  job/kubernetes-e2e-gce-parallel/7957

**Comment by thockin** [comment]
Still happening.  #14090 is the next suspect

**Comment by dchen1107** [comment]
Asked @yujuhong to prepare reverting #13417 if required. Meanwhile, I am debugging the issue.

**Comment by yujuhong** [comment]
I will get the revert PR up soon. 

In the meantime, I mapped the timestamps on the jenkins e2e log to a kubelet.log of a failed run. Here is a snippet around when kubelet stopped posting node status:
```
tartCount:0 AppArmorProfile:}
I0921 10:48:22.735340    3569 manager.go:223] Status for pod "fluentd-elasticsearch-e2e-gce-minion-yk1t_kube-system" updated successfully
I0921 10:48:22.739943    3569 reflector.go:297] pkg/kubelet/node_manager.go:187: Watch close - *api.Node total 11 items received
W0921 10:48:22.744393    3569 reflector.go:224] pkg/kubelet/kubelet.go:199: watch of *api.Service ended with: EOF
I0921 10:48:22.753700    3569 reflector.go:297] pkg/kubelet/config/apiserver.go:43: Watch close - *api.Pod total 72 items received
W0921 10:48:22.766563    3569 manager.go:108] Failed to updated pod status: error updating status for pod "kube-registry-proxy-e2e-gce-minion-yk1t_kube-system": 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/r
egistry/pods/kube-system/kube-registry-proxy-e2e-gce-minion-yk1t?quorum=false&recursive=false&sorted=false: dial tcp 127.0.0.1:4001: connection refused]) [0]
W0921 10:48:22.794220    3569 manager.go:108] Failed to updated pod status: error updating status for pod "baz-gvyki_e2e-tests-etcd-failure-q9ltf": 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/pods/
e2e-tests-etcd-failure-q9ltf/baz-gvyki?quorum=false&recursive=false&sorted=false: dial tcp 127.0.0.1:4001: connection refused]) [0]
W0921 10:48:22.821373    3569 manager.go:108] Failed to updated pod status: error updating status for pod "monitoring-heapster-v8-mj3fr_kube-system": 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/pod
s/kube-system/monitoring-heapster-v8-mj3fr?quorum=false&recursive=false&sorted=false: dial tcp 127.0.0.1:4001: connection refused]) [0]
W0921 10:48:22.848974    3569 manager.go:108] Failed to updated pod status: error updating status for pod "monitoring-influx-grafana-v1-f502x_kube-system": 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/regist
ry/pods/kube-system/monitoring-influx-grafana-v1-f502x?quorum=false&recursive=false&sorted=false: dial tcp 127.0.0.1:4001: connection refused]) [0]
I0921 10:48:23.380764    3569 file.go:135] Reading config file "/etc/kubernetes/manifests/fluentd-es.yaml"
I0921 10:48:23.381996    3569 file.go:135] Reading config file "/etc/kubernetes/manifests/kube-registry-proxy.yaml"
I0921 10:48:23.382977    3569 config.go:252] Setting pods for source file
I0921 10:48:25.121509    3569 server.go:679] GET /healthz: (706.09µs) 0 [[curl/7.26.0] 127.0.0.1:38933]
I0921 10:48:27.518895    3569 server.go:679] GET /stats/kube-system/kube-registry-proxy-e2e-gce-minion-yk1t/751b7793-6045-11e5-8b39-42010af00002/kube-registry-proxy: (12.813166ms) 0 [[Go 1.1 package http] 10.245.1.4:47023]
I0921 10:48:27.520338    3569 server.go:679] GET /stats/e2e-tests-etcd-failure-q9ltf/baz-gvyki/3b69263c-604e-11e5-8b39-42010af00002/baz: (12.540354ms) 0 [[Go 1.1 package http] 10.245.1.4:47099]
I0921 10:48:27.526433    3569 server.go:679] GET /stats/kube-system/monitoring-influx-grafana-v1-f502x/5d04155f-6045-11e5-8b39-42010af00002/influxdb: (18.392221ms) 0 [[Go 1.1 package http] 10.245.1.4:47098]
I0921 10:48:27.526935    3569 server.go:679] GET /stats/kube-system/monitoring-heapster-v8-mj3fr/5ca55458-6045-11e5-8b39-42010af00002/heapster: (18.698587ms) 0 [[Go 1.1 package http] 10.245.1.4:47097]
I0921 10:48:27.527374    3569 server.go:679] GET /stats/kube-system/fluentd-elasticsearch-e2e-gce-minion-yk1t/85c6c8c9-6045-11e5-8b39-42010af00002/fluentd-elasticsearch: (18.180893ms) 0 [[Go 1.1 package http] 10.245.1.4:47080]
I0921 10:48:27.534235    3569 server.go:679] POST /stats/container/: (28.671462ms) 0 [[Go 1.1 package http] 10.245.1.4:38933]
I0921 10:48:27.538816    3569 server.go:679] GET /stats/kube-system/monitoring-influx-grafana-v1-f502x/5d04155f-6045-11e5-8b39-42010af00002/grafana: (194.316µs) 0 [[Go 1.1 package http] 10.245.1.4:47023]
E0921 10:48:28.683372    3569 node_manager.go:478] Error updating node status, will retry: error getting node "e2e-gce-minion-yk1t": 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/minions/e2e-gce-mini
on-yk1t?quorum=false&recursive=false&sorted=false: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:28.710679    3569 node_manager.go:478] Error updating node status, will retry: error getting node "e2e-gce-minion-yk1t": 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/minions/e2e-gce-minion-yk1t?quorum=false&recursive=false&sorted=false: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:28.737696    3569 node_manager.go:478] Error updating node status, will retry: error getting node "e2e-gce-minion-yk1t": 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/minions/e2e-gce-minion-yk1t?quorum=false&recursive=false&sorted=false: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:28.766371    3569 node_manager.go:478] Error updating node status, will retry: error getting node "e2e-gce-minion-yk1t": 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/minions/e2e-gce-minion-yk1t?quorum=false&recursive=false&sorted=false: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:28.793667    3569 node_manager.go:478] Error updating node status, will retry: error getting node "e2e-gce-minion-yk1t": 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/minions/e2e-gce-minion-yk1t?quorum=false&recursive=false&sorted=false: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:28.793701    3569 node_manager.go:201] Unable to update node status: update node status exceeds retry count
```

Around the same time, apiserver.log was full of errros:

```
E0921 10:48:30.288639       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Pod: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/pods?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.289120       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Node: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/minions?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.311462       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Endpoints: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/services/endpoints?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.314298       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Pod: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/pods?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.314837       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Node: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/minions?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.337041       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Endpoints: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/services/endpoints?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.339865       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Pod: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/pods?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.340366       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Node: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/minions?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.362614       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Endpoints: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/services/endpoints?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.365458       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Pod: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/pods?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.365921       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Node: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/minions?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.388140       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Endpoints: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/services/endpoints?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.391091       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Pod: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/pods?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.391603       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Node: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/minions?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.413692       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Endpoints: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/services/endpoints?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.416639       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Pod: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/pods?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.417161       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Node: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/minions?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.439279       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Endpoints: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/services/endpoints?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.442215       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Pod: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/pods?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.442760       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Node: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/minions?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.464865       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Endpoints: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/services/endpoints?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.467764       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Pod: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/pods?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.468341       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Node: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/minions?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.490461       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Endpoints: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/services/endpoints?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.493353       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Pod: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/pods?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.493861       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Node: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/minions?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.516086       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Endpoints: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/services/endpoints?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.518893       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Pod: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/pods?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.519391       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Node: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/minions?quorum=false&recursive=true&sorted=true: dial tcp 127.0.0.1:4001: connection refused]) [0]
E0921 10:48:30.541676       5 cacher.go:147] unexpected ListAndWatch error: pkg/storage/cacher.go:114: Failed to list *api.Endpoints: 501: All the given peers are not reachable (failed to propose on members 
```

**Comment by dchen1107** [comment]
I saw the same issue as @yujuhong when looking at job/kubernetes-e2e-gce/8521/ which is the first e2e flaky reported by @thockin: 

From all Kubelets' logs, I noticed the error message to update node status through kube-apiserver:
```
E0918 02:06:21.000550    3706 node_manager.go:477] Error updating node status, will retry: error getting node "e2e-gce-minion-a7qh": 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/minions/e2e-gce-minion-a7qh?quorum=false&recursive=false&sorted=false: dial tcp 127.0.0.1:4001: i/o timeout]) [0]
W0918 02:06:22.824212    3706 reflector.go:224] pkg/kubelet/kubelet.go:198: watch of *api.Service ended with: 502:  (unhandled http status [OK] with body [nil]) [0]
I0918 02:06:22.940795    3706 reflector.go:297] pkg/kubelet/node_manager.go:186: Watch close - *api.Node total 13 items received
E0918 02:06:23.030864    3706 node_manager.go:477] Error updating node status, will retry: error getting node "e2e-gce-minion-a7qh": 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/minions/e2e-gce-minion-a7qh?quorum=false&recursive=false&sorted=false: dial tcp 127.0.0.1:4001: i/o timeout]) [0]
I0918 02:06:23.234189    3706 reflector.go:297] pkg/kubelet/config/apiserver.go:43: Watch close - *api.Pod total 24 items received
E0918 02:06:25.058499    3706 node_manager.go:477] Error updating node status, will retry: error getting node "e2e-gce-minion-a7qh": 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/minions/e2e-gce-minion-a7qh?quorum=false&recursive=false&sorted=false: dial tcp 127.0.0.1:4001: i/o timeout]) [0]
I0918 02:06:26.840203    3706 server.go:679] GET /stats/kube-system/monitoring-heapster-v8-zt5xw/7f9840ff-5da5-11e5-8e8a-42010af00002/heapster: (17.871834ms) 0 [[Go 1.1 package http] 10.245.1.4:38459]
I0918 02:06:26.841483    3706 server.go:679] GET /stats/e2e-tests-etcd-failure-x3kk3/baz-nxq5g/c46661d3-5da9-11e5-9f48-42010af00002/baz: (18.920232ms) 0 [[Go 1.1 package http] 10.245.1.4:38458]
I0918 02:06:26.842535    3706 server.go:679] GET /stats/kube-system/elasticsearch-logging-v1-la68z/7f9b5cfa-5da5-11e5-8e8a-42010af00002/elasticsearch-logging: (18.822354ms) 0 [[Go 1.1 package http] 10.245.1.4:38513]
I0918 02:06:26.843052    3706 server.go:679] GET /stats/kube-system/kube-registry-proxy-e2e-gce-minion-a7qh/a2713a05-5da5-11e5-8e8a-42010af00002/kube-registry-proxy: (19.077329ms) 0 [[Go 1.1 package http] 10.245.1.4:38509]
I0918 02:06:26.843508    3706 server.go:679] GET /stats/kube-system/fluentd-elasticsearch-e2e-gce-minion-a7qh/b7858d20-5da5-11e5-8e8a-42010af00002/fluentd-elasticsearch: (19.341168ms) 0 [[Go 1.1 package http] 10.245.1.4:38508]
I0918 02:06:26.856277    3706 server.go:679] POST /stats/container/: (34.414229ms) 0 [[Go 1.1 package http] 10.245.1.4:34414]
E0918 02:06:27.087332    3706 node_manager.go:477] Error updating node status, will retry: error getting node "e2e-gce-minion-a7qh": 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Get http://127.0.0.1:4001/v2/keys/registry/minions/e2e-gce-minion-a7qh?quorum=false&recursive=false&sorted=false: dial tcp 127.0.0.1:4001: i/o timeout]) [0]
E0918 02:06:27.087390    3706 node_manager.go:200] Unable to update node status: update node status exceeds retry count
```

At the same time, I observed kube-apiserver failure:
```
I0918 02:06:18.215061       6 trace.go:57] Trace "Create *api.Namespace" (started 2015-09-18 02:06:16.188815444 +0000 UTC):
[128.618µs] [128.618µs] About to create object
[2.026199197s] [2.026070579s] END
E0918 02:06:18.215122       6 errors.go:62] apiserver received an error that is not an unversioned.Status: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Put http://127.0.0.1:4001/v2/keys/registry/namespaces/kube-system?prevExist=false: dial tcp 127.0.0.1:4001: i/o timeout]) [0]
I0918 02:06:18.215301       6 handlers.go:143] POST /api/v1/namespaces: (2.026985822s) 500
goroutine 3643 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc20949daa0, 0x1f4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:188 +0x9a
k8s.io/kubernetes/pkg/apiserver.(*baseTimeoutWriter).WriteHeader(0xc20a26b180, 0x1f4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:249 +0xba
k8s.io/kubernetes/pkg/apiserver.writeJSON(0x1f4, 0x7fa7ce5da238, 0xc2080f5140, 0x7fa7ce5da9d0, 0xc208c3ca80, 0x7fa7ce423a88, 0xc209a9d188, 0xc20949df01)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:330 +0x2b7
k8s.io/kubernetes/pkg/apiserver.errorJSON(0x7fa7ce42e748, 0xc209f61b00, 0x7fa7ce5da238, 0xc2080f5140, 0x7fa7ce423a88, 0xc209a9d188, 0x1491910)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:337 +0xab
k8s.io/kubernetes/pkg/apiserver.func·026(0xc208fd8ed0, 0xc20949dc20)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:331 +0xbd8
github.com/emicklei/go-restful.func·009(0xc208fd8ed0, 0xc20949dc20)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:244 +0x41
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc208fd8f60, 0xc208fd8ed0, 0xc20949dc20)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
k8s.io/kubernetes/pkg/apiserver.func·003(0xc208fd8ed0, 0xc20949dc20, 0xc208fd8f60)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:61 +0x8b
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc208fd8f60, 0xc208fd8ed0, 0xc20949dc20)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19 +0x84
github.com/emicklei/go-restful.(*Container).dispatch(0xc2082542d0, 0x7fa7ce423a88, 0xc209a9d188, 0xc208a83d40)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/co [[kubectl/v1.1.0 (linux/amd64) kubernetes/0fb6048] 127.0.0.1:34748]
I0918 02:06:18.258553       6 handlers.go:143] GET /api: (177.432µs) 200 [[kubectl/v1.1.0 (linux/amd64) kubernetes/0fb6048] 127.0.0.1:34774]
I0918 02:06:18.259251       6 handlers.go:143] GET /version: (101.247µs) 200 [[kubectl/v1.1.0 (linux/amd64) kubernetes/0fb6048] 127.0.0.1:34774]
I0918 02:06:18.315755       6 trace.go:57] Trace "Get *api.Node" (started 2015-09-18 02:06:16.284902685 +0000 UTC):
[1.92µs] [1.92µs] About to read object
...
```

After a couple of minutes, kube-apiserver is back to normal, and most nodes are back to normal. Did we upgrade etcd-client library? Looks like etcd server is dead to me. But we don't have etcd related logs.

**Comment by dchen1107** [comment]
cc/ @davidopp @lavalamp

**Comment by yujuhong** [comment]
The etcd failure turned out to be a red herring. There was an "etcd failure" test running before kubelet stopped posting node status. Still digging...

**Comment by yujuhong** [comment]
I checked two failed builds. In both builds, the kubelet in question failed /healthz and was restarted. I only use one build for example below, but the observations apply to both.
```
I0920 16:10:04.771620    3659 kubelet.go:1772] SyncLoop (periodic sync)
I0920 16:10:04.771776    3659 kubelet.go:1739] SyncLoop (housekeeping)
I0920 16:10:04.833390    3659 kubelet.go:1761] SyncLoop (UPDATE): "my-hostname-private-01663448-5fb2-11e5-97fe-42010af01555-nhzp1_e2e-tests-replication-controller-d0mle"
I0920 16:10:04.836186    3659 kubelet.go:1764] SyncLoop (REMOVE): "my-hostname-private-01663448-5fb2-11e5-97fe-42010af01555-nhzp1_e2e-tests-replication-controller-d0mle"
I0920 16:10:14.836406    3659 kubelet.go:1772] SyncLoop (periodic sync)
I0920 16:10:14.836563    3659 kubelet.go:1739] SyncLoop (housekeeping)
I0920 16:10:24.885928    3659 kubelet.go:1772] SyncLoop (periodic sync)
I0920 16:10:24.886066    3659 kubelet.go:1739] SyncLoop (housekeeping)
I0920 16:10:34.906906    3659 kubelet.go:1772] SyncLoop (periodic sync)
I0920 16:10:34.907025    3659 kubelet.go:1739] SyncLoop (housekeeping)
I0920 16:10:44.926827    3659 kubelet.go:1772] SyncLoop (periodic sync)
I0920 16:10:44.926953    3659 kubelet.go:1739] SyncLoop (housekeeping)
I0920 16:16:20.782660   12119 kubelet.go:1758] SyncLoop (ADD): "fluentd-elasticsearch-e2e-gce-minion-qrtk_kube-system, kube-registry-proxy-e2e-gce-minion-qrtk_kube-system"
I0920 16:16:20.805591   12119 kubelet.go:1758] SyncLoop (ADD): "kube-registry-proxy-e2e-gce-minion-qrtk_kube-system"
I0920 16:16:20.812357   12119 kubelet.go:1758] SyncLoop (ADD): "fluentd-elasticsearch-e2e-gce-minion-qrtk_kube-system"
```
* The id changed after 16:10:44 because the kubelet was restarted for failing a health check (corroborated by supervisord.log).
* The SyncLoop was not active for more than 5 minutes, which was the potential cause of the failed health check.

SyncLoop is stuck somewhere when performing the housekeeping/cleanup task. This is unrelated to #13417, and the problem seemed to exist long before #13417 was merged.
I am still trying to trace back to where the problem started occurring, but for the long term, we should make sure that the calls in kubelet has probably timeout (#9896) and that housekeeping should be a separate goroutine (#13418).

**Comment by yujuhong** [comment]
@thockin, you were right. It is my PR, reverting soon. In summary, there might be a deadlock caused by lock grabbing in syncNodeStatus and syncNetworkStatus.

**Comment by thockin** [comment]
thanks for the update
