### ISSUE TITLE
apiserver: too old resource version error reported with wrong type

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#14384]
```
I0922 10:29:36.108012       5 handlers.go:143] GET /api/v1/watch/nodes?fieldSelector=metadata.name%3De2e-scalability-minion-v2ke&resourceVersion=285860: (1.675017213s) 500
goroutine 1159865 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc2ce615080, 0x1f4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:188 +0x9a
k8s.io/kubernetes/pkg/apiserver.writeJSON(0x1f4, 0x7f4c2d21b238, 0xc2080f7120, 0x7f4c2d21b9d0, 0xc23aef4900, 0x7f4c2d069698, 0xc2ce615080, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:399 +0x2b7
k8s.io/kubernetes/pkg/apiserver.errorJSON(0x7f4c2d215f40, 0xc21679c560, 0x7f4c2d21b238, 0xc2080f7120, 0x7f4c2d069698, 0xc2ce615080, 0xc2b161b680)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:406 +0xab
k8s.io/kubernetes/pkg/apiserver.func·027(0xc2c8d634a0, 0xc2ce615140)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:256 +0xc2a
github.com/emicklei/go-restful.func·009(0xc2c8d634a0, 0xc2ce615140)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:244 +0x41
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc2c8d63530, 0xc2c8d634a0, 0xc2ce615140)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
k8s.io/kubernetes/pkg/apiserver.func·003(0xc2c8d634a0, 0xc2ce615140, 0xc2c8d63530)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:61 +0x8b
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc2c8d63530, 0xc2c8d634a0, 0xc2ce615140)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19 +0x84
github.com/emicklei/go-restful.(*Container).dispatch(0xc2082a8090, 0x7f4c2d069698, 0xc2ce615080, 0xc284274f70)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:246 +0xee3
github.com/emicklei/go-restful.*Container.(github.com/emicklei/go-restful.dispatch)·fm(0x7f4c2d069698, 0xc2ce615080, 0xc284274f70)
	/go/src/k8s.io/kubernetes/Godeps/_workspa [[kubelet/v1.1.0 (linux/amd64) kubernetes/09cf38e] 10.240.139.247:41331]
E0922 10:29:36.108127       5 errors.go:62] apiserver received an error that is not an unversioned.Status: too old resource version: 287512 (289102)
```

**Comment by lavalamp** [comment]
We sorta fixed this-- now it's a real status error, but we left the status code 500, so it still produces stack traces and potentially confuses clients. @erictune @caesarxuchao we should figure out the correct status code.

**Comment by erictune** [comment]
I think there is a lot more going on related to this in #15389.  Clients are re-listing after the error but not rewatching.

**Comment by erictune** [comment]
It turned out this was not causing job e2e flakes.  Just sending 500s that were confusing.  So lowering priority.

**Comment by caesarxuchao** [comment]
@lavalamp How about a NewBadRequest error? https://github.com/kubernetes/kubernetes/blob/master/pkg/api/errors/errors.go#L187

**Comment by lavalamp** [comment]
@caesarxuchao that certainly sounds like an improvement.
