### ISSUE TITLE
Problems with accessing service with proxy

### ISSUE THREAD

**Issue by piosz** [kubernetes/kubernetes#14477]
In [autoscaling.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/autoscaling.go) e2e test service is created and then using API server proxy a request is sent to it. Quite often the request (>30% times) fails and in kube-apiserver logs I can find:
```
E0923 12:09:18.003491       6 apiserver.go:210] recover from panic situation: - invalid argument to Intn
    /usr/src/go/src/runtime/asm_amd64.s:401
    /usr/src/go/src/runtime/panic.go:387
    /usr/src/go/src/math/rand/rand.go:95
    /usr/src/go/src/math/rand/rand.go:195
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/service/rest.go:301
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/proxy.go:114
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/api_installer.go:757
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:244
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:61
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:246
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:95
    /usr/src/go/src/net/http/server.go:1265
    /usr/src/go/src/net/http/server.go:1541
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:399
    /usr/src/go/src/net/http/server.go:1265
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/auth/handlers/handlers.go:47
    /usr/src/go/src/net/http/server.go:1265
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101
    /usr/src/go/src/net/http/server.go:1265
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101
    /usr/src/go/src/net/http/server.go:1265
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:166
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:142
    /usr/src/go/src/net/http/server.go:1265
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:86
    /usr/src/go/src/net/http/server.go:1265
    /usr/src/go/src/net/http/server.go:1703
    /usr/src/go/src/net/http/server.go:1204
    /usr/src/go/src/runtime/asm_amd64.s:2232

I0923 12:09:18.003687       6 handlers.go:143] POST /api/v1/proxy/namespaces/e2e-tests-autoscaling-m33z0/services/rc/ConsumeCPU?durationSec=3600&millicores=600&timeout=30s: (33.781879ms) 500
```

Also in our standard gce-e2e suite I can find similar problem (in run 8188):
```
I0823 02:33:25.454805       9 handlers.go:142] GET /api/v1/proxy/namespaces/e2e-tests-kubectl-zt8kd/services/frontend/index.php?cmd=get&key=messages&value=: (1.424107ms) 503
goroutine 102593 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc20a982a80, 0x1f7)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:188 +0x9a
k8s.io/kubernetes/pkg/apiserver.writeJSON(0x1f7, 0x7f16821ec0e0, 0xc2080b0b20, 0x7f16821ec3a0, 0xc20bb8a200, 0x7f1682216680, 0xc20a982a80, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:278 +0x2b7
k8s.io/kubernetes/pkg/apiserver.(*ProxyHandler).ServeHTTP(0xc2083ea370, 0x7f1682216680, 0xc20a982a80, 0xc20cac41a0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/proxy.go:118 +0xcb9
k8s.io/kubernetes/pkg/apiserver.func·002(0xc20bfbbbc0, 0xc20a6c77c0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/api_installer.go:742 +0x60
github.com/emicklei/go-restful.func·005(0xc20bfbbbc0, 0xc20a6c77c0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:220 +0x41
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20bfbbc50, 0xc20bfbbbc0, 0xc20a6c77c0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
k8s.io/kubernetes/pkg/apiserver.func·003(0xc20bfbbbc0, 0xc20a6c77c0, 0xc20bfbbc50)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:59 +0x88
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20bfbbc50, 0xc20bfbbbc0, 0xc20a6c77c0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19 +0x84
github.com/emicklei/go-restful.(*Container).dispatch(0xc2083e8230, 0x7f1682216680, 0xc20a982a80, 0xc20cac41a0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:222 +0xec7
github.com/emicklei/go-restful.*Container.(github.com/emicklei/go-restful.dispatch)·fm(0x7f1682216680, 0xc20a982a80, 0xc20cac41a0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-res
Error getting ResourceLocation: no endpoints available for service "frontend" [[e2e.test/v1.1.0 (linux/amd64) kubernetes/5fe7029] 104.197.45.156:48696]
```

Both errors are silently ignored in e2e tests. EDIT: This is actually not right.

**Comment by piosz** [comment]
cc @lavalamp @kubernetes/goog-csi @jszczepkowski

**Comment by lavalamp** [comment]
This is a pretty easy one-- I sent a change that also rolls back the workaround.
