### ISSUE TITLE
e2e flaky: Job should run a job to completion when tasks sometimes fail and are locally restarted

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#15389]
Job should run a job to completion when tasks sometimes fail and are locally restarted

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/job.go:75
Expected error:
    <*errors.errorString | 0xc20807c990>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred

**Comment by dchen1107** [comment]
Couple of failures:

http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/8836/
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/12013/

**Comment by wojtek-t** [comment]
Another failure:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/

**Comment by dchen1107** [comment]
Another failure:

http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/12390/console

**Comment by quinton-hoole** [comment]
This test was introduced by @etune and @soltysh in #14566 and #14354.

It's currently failing at a rate of about 7%.

When it passes, it typically does so in 30-90 seconds.  

Occasionally it times out after 15 minutes.  I think that there's a real bug in the system here.

The timeout occurs while waiting for the Job to terminate, which it never does.

**Comment by quinton-hoole** [comment]
I'm going to label it as flaky until the bug has been fixed.

**Comment by wojtek-t** [comment]
Another portion of flakes:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/9462/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/8908/

**Comment by brendandburns** [comment]
@erictune @soltysh any progress on this?  Is it being actively worked on?

**Comment by erictune** [comment]
I've been working on this today.
Saw 1 e2e failure in 50 runs.
Logs suggest the problem is that half of kubelet's brain thinks it started a pod, and the other half of it thinks it didn't.  In fact it didn't.  So the test times out waiting for the not-started pod to complete.

**Comment by erictune** [comment]
Update: the kubelet did start all the pods, and they all terminated, and then the job controller somehow didn't notice that they were done until 40+ minutes later.

**Comment by erictune** [comment]
This is interesting.   There were 3 apiserver 500's around the time of the test failure, and no 500's any other time in the 8 hours the cluster was up, and many other test runs occurred.

500s:
```
I1022 03:56:10.452318       7 handlers.go:131] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3Dkubernetes-minion-ms7t&resourceVersion=11784: (531.223µs) 500
goroutine 1705 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc20d0ddd40, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:188 +0x9a
k8s.io/kubernetes/pkg/apiserver.writeJSON(0x1f4, 0x7f56d544f158, 0xc208066a40, 0x7f56d544f888, 0xc20b9e8d00, 0x7f56d5294c98, 0xc20d0ddd40, 0x1)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:400 +0x89
k8s.io/kubernetes/pkg/apiserver.errorJSON(0x7f56d5451a88, 0xc20b9e8c80, 0x7f56d544f158, 0xc208066a40, 0x7f56d5294c98, 0xc20d0ddd40, 0xc20dfc0e80)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:427 +0xab
k8s.io/kubernetes/pkg/apiserver.func·026(0xc20afe8c00, 0xc20d0dde00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:271 +0xc2a
github.com/emicklei/go-restful.func·009(0xc20afe8c00, 0xc20d0dde00)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:244 +0x41
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20afe8e40, 0xc20afe8c00, 0xc20d0dde00)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
k8s.io/kubernetes/pkg/apiserver.func·003(0xc20afe8c00, 0xc20d0dde00, 0xc20afe8e40)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:62 +0x8b
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20afe8e40, 0xc20afe8c00, 0xc20d0dde00)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19 +0x84
github.com/emicklei/go-restful.(*Container).dispatch(0xc2082621b0, 0x7f56d5294c98, 0xc20d0ddd40, 0xc20af7b860)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:246 +0xee3
github.com/emicklei/go-restful.*Container.(github.com/emicklei/go-restful.dispatch)·fm(0x7f56d5294c98, 0xc20d0ddd40, 0xc20af7b860)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/s [[kubelet/v1.2.0 (linux/amd64) kubernetes/a5a9176] 10.240.0.4:34668]
```
```
I1022 04:07:07.945868       7 handlers.go:131] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3Dkubernetes-master&resourceVersion=36: (670.064µs) 500
goroutine 109 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc20dd92cc0, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:188 +0x9a
k8s.io/kubernetes/pkg/apiserver.writeJSON(0x1f4, 0x7f56d544f158, 0xc208066a40, 0x7f56d544f888, 0xc20cc55280, 0x7f56d5294c98, 0xc20dd92cc0, 0x1)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:400 +0x89
k8s.io/kubernetes/pkg/apiserver.errorJSON(0x7f56d5451a88, 0xc20cc55200, 0x7f56d544f158, 0xc208066a40, 0x7f56d5294c98, 0xc20dd92cc0, 0xc20d77afc0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:427 +0xab
k8s.io/kubernetes/pkg/apiserver.func·026(0xc20e02f110, 0xc20dd92d80)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:271 +0xc2a
github.com/emicklei/go-restful.func·009(0xc20e02f110, 0xc20dd92d80)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:244 +0x41
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20e02f1a0, 0xc20e02f110, 0xc20dd92d80)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
k8s.io/kubernetes/pkg/apiserver.func·003(0xc20e02f110, 0xc20dd92d80, 0xc20e02f1a0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:62 +0x8b
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20e02f1a0, 0xc20e02f110, 0xc20dd92d80)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19 +0x84
github.com/emicklei/go-restful.(*Container).dispatch(0xc2082621b0, 0x7f56d5294c98, 0xc20dd92cc0, 0xc20cd14270)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:246 +0xee3
github.com/emicklei/go-restful.*Container.(github.com/emicklei/go-restful.dispatch)·fm(0x7f56d5294c98, 0xc20dd92cc0, 0xc20cd14270)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/sr [[kubelet/v1.2.0 (linux/amd64) kubernetes/a5a9176] 10.240.0.2:55047]
```
```
I1022 04:13:24.490047       7 handlers.go:131] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3Dkubernetes-minion-svng&resourceVersion=170: (502.663µs) 500
goroutine 1452 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc20dd102a0, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:188 +0x9a
k8s.io/kubernetes/pkg/apiserver.writeJSON(0x1f4, 0x7f56d544f158, 0xc208066a40, 0x7f56d544f888, 0xc20e561300, 0x7f56d5294c98, 0xc20dd102a0, 0x1)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:400 +0x89
k8s.io/kubernetes/pkg/apiserver.errorJSON(0x7f56d5451a88, 0xc20e561200, 0x7f56d544f158, 0xc208066a40, 0x7f56d5294c98, 0xc20dd102a0, 0xc20ea129a0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:427 +0xab
k8s.io/kubernetes/pkg/apiserver.func·026(0xc20dc64570, 0xc20dd10360)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:271 +0xc2a
github.com/emicklei/go-restful.func·009(0xc20dc64570, 0xc20dd10360)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:244 +0x41
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20dc64630, 0xc20dc64570, 0xc20dd10360)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
k8s.io/kubernetes/pkg/apiserver.func·003(0xc20dc64570, 0xc20dd10360, 0xc20dc64630)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:62 +0x8b
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20dc64630, 0xc20dc64570, 0xc20dd10360)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19 +0x84
github.com/emicklei/go-restful.(*Container).dispatch(0xc2082621b0, 0x7f56d5294c98, 0xc20dd102a0, 0xc20cf2f040)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:246 +0xee3
github.com/emicklei/go-restful.*Container.(github.com/emicklei/go-restful.dispatch)·fm(0x7f56d5294c98, 0xc20dd102a0, 0xc20cf2f040)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/s [[kubelet/v1.2.0 (linux/amd64) kubernetes/a5a9176] 10.240.0.3:56484]
```

**Comment by erictune** [comment]
The code that is failing is this in `pkg/apiserver/resthandler.go` at line 271
```
                if (opts.Watch || forceWatch) && rw != nil {
                        watcher, err := rw.Watch(ctx, opts.LabelSelector, opts.FieldSelector, opts.ResourceVersion)
                        if err != nil {
                                errorJSON(err, scope.Codec, w)
                                return
                        }
                        serveWatch(watcher, scope, w, req, minRequestTimeout)
                        return
                }
```
the `rw.Watch` gets an error, and then `errorJSON()` decides the error is a 500.

**Comment by erictune** [comment]
@lavalamp can you say anything about the above mentioned apiserver internal error which occurs immediately on receiving a watch request?

**Comment by lavalamp** [comment]
Look in the relevant kubelet logs to see how they interpreted the error.
It's a bit silly that we printed a stack trace but not the error text :(

**Comment by erictune** [comment]
`E1022 04:13:24.490216    3622 reflector.go:206] pkg/kubelet/config/apiserver.go:43: Failed to watch *api.Pod: Internal error occurred: too old resource version: 171 (13595)
`

**Comment by erictune** [comment]
This is happening at line 269 of pkg/storage/watch_cache.go.
Is this an unexpected condition?  If not, why is it a 500?

**Comment by lavalamp** [comment]
Oh, I thought that was fixed. It shouldn't be an internal error, you're out
of the watch window and need to re-list.

**Comment by lavalamp** [comment]
OK I reopened #14384.

@erictune did the kubelets involved re-list soon after getting these 500s?
If so, then this is coincidence and not your problem.

**Comment by erictune** [comment]
In all 3 cases, they relist immediately, but in 2 of 3 cases, they don't re-watch for about an hour.  That seems wrong, no?

Relist at 3:56 and rewatch at 4:53
```
I1022 03:56:10.450825       7 handlers.go:131] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3Dkubernetes-minion-ms7t&resourceVersion=2963: (56m57.077164863s) 0 [[kubelet/v1.2.0 (linux/amd64) kubernetes/a5a9176] 10.240.0.4:34668]
I1022 03:56:10.452318       7 handlers.go:131] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3Dkubernetes-minion-ms7t&resourceVersion=11784: (531.223µs) 500 <stacktrace omitted> [[kubelet/v1.2.0 (linux/amd64) kubernetes/a5a9176] 10.240.0.4:34668]
I1022 03:56:11.457315       7 handlers.go:131] GET /api/v1/pods?fieldSelector=spec.nodeName%3Dkubernetes-minion-ms7t: (3.87358ms) 200 [[kubelet/v1.2.0 (linux/amd64) kubernetes/a5a9176] 10.240.0.4:34668]
I1022 04:53:17.910532       7 handlers.go:131] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3Dkubernetes-minion-ms7t&resourceVersion=16321: (57m6.451233388s) 0 [[kubelet/v1.2.0 (linux/amd64) kubernetes/a5a9176] 10.240.0.4:34668]
```

Relist at 4:07 and rewatch at 5:00
```
I1022 04:07:07.944818       7 handlers.go:131] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3Dkubernetes-master&resourceVersion=36: (39m21.577389313s) 0 [[kubelet/v1.2.0 (linux/amd64) kubernetes/a5a9176] 10.240.0.2:55047]
I1022 04:07:07.945868       7 handlers.go:131] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3Dkubernetes-master&resourceVersion=36: (670.064µs) 500 <stacktrace-omitted> [[kubelet/v1.2.0 (linux/amd64) kubernetes/a5a9176] 10.240.0.2:55047]
I1022 04:07:08.951455       7 handlers.go:131] GET /api/v1/pods?fieldSelector=spec.nodeName%3Dkubernetes-master: (4.635415ms) 200 [[kubelet/v1.2.0 (linux/amd64) kubernetes/a5a9176] 10.240.0.2:55047]
I1022 05:00:42.371760       7 handlers.go:131] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3Dkubernetes-master&resourceVersion=17137: (53m33.417427356s) 0 [[kubelet/v1.2.0 (linux/amd64) kubernetes/a5a9176] 10.240.0.2:55047]
```

Working correctly.
```
I1022 16:08:28.277858       7 handlers.go:131] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3Dkubernetes-minion-svng&resourceVersion=17646: (46m58.192913613s) 0 [[kubelet/v1.2.0 (linux/amd64) kubernetes/a5a9176] 10.240.0.3:56484]
I1022 16:08:28.279551       7 handlers.go:131] GET /api/v1/watch/pods?fieldSelector=spec.nodeName%3Dkubernetes-minion-svng&resourceVersion=17646: (482.612µs) 500 <stacktrace-omitted> [[kubelet/v1.2.0 (linux/amd64) kubernetes/a5a9176] 10.240.0.3:56484]
I1022 16:08:29.277602       7 handlers.go:131] GET /api/v1/nodes/kubernetes-minion-svng: (1.381635ms) 200 [[kubelet/v1.2.0 (linux/amd64) kubernetes/a5a9176] 10.240.0.3:56484]
I1022 16:08:29.284818       7 handlers.go:131] GET /api/v1/pods?fieldSelector=spec.nodeName%3Dkubernetes-minion-svng: (4.054121ms) 200 [[kubelet/v1.2.0 (linux/amd64) kubernetes/a5a9176] 10.240.0.3:56484]
```

**Comment by lavalamp** [comment]
The time reported is the *end* of the watch, not the beginning. The last
one it seems you actually didn't get the log line for the watch, actually.

But the first two look WAI.

**Comment by erictune** [comment]
Oh, duh.

**Comment by erictune** [comment]
Working on #16134 which I suspect may fix this.

**Comment by erictune** [comment]
Okay, looking at a new test failure I see that there are expected failures, and the test just times out due to backoff by the kubelet.  The following things happen:

1. container runs and fails (1)
1. container runs and fails (2)
1. kubelet backs off for 10s
1. container runs and fails (3rd failure)
1. kubelet backoff 20s
1. container runs and fails (4th failure)
1. kubelet backoff 40s
1. container runs and fails (5th failure)
1. kubelet backoff 1m20s
1. container runs and fails (6th failure)
1. kubelet backoff 2m40s
1. container runs and fails (6th failure)
1.  kubelet backoff 5m
1. container runs and fails (6th failure)
1. kubelet backoff 5m
1. test timeout now that at least 15m10s has elapsed in backoffs.

Failures have a probability of 50%.
Chance of getting 8 fails in a row is 1 in 256.
Four pods per test run is 4 in 256 or 1 in 64.
I see failures about 1 in 50, so that seems about right.

So, I need to rewrite the test so that it writes to the emptydir after the first failure, and succeeds after that.

**Comment by erictune** [comment]
Ugh.  My fix for local breaks non-local restarts.

**Comment by lavalamp** [comment]
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-parallel/

Happened again.
