### ISSUE TITLE
kubectl edit for multiple resources broke by UpdateApplyAnnotation

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#15907]
When trying to edit multiple resources, for example:
```console
$ kubectl get pods 
NAME         READY     STATUS    RESTARTS   AGE
mock-9e7dn   1/1       Running   0          3m
mock-adkeu   1/1       Running   0          3m

$ kubectl edit pods 
# Do some edit, and then save...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x73edf2]

goroutine 1 [running]:
k8s.io/kubernetes/pkg/api/meta.(*genericAccessor).SetAnnotations(0xc208031cc0, 0xc20818f7d0)
	<autogenerated>:20 +0xd2
k8s.io/kubernetes/pkg/kubectl.GetModifiedConfiguration(0xc208221e80, 0xc208280200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/apply.go:102 +0x224
k8s.io/kubernetes/pkg/kubectl.UpdateApplyAnnotation(0xc208221e80, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/apply.go:169 +0x3f
k8s.io/kubernetes/pkg/kubectl/cmd.RunEdit(0xc2080b6f00, 0x7f05615e6fb0, 0xc20802e008, 0xc20813de00, 0xc208190010, 0x1, 0x1, 0x1bda6d0, 0x0, 0x0, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/edit.go:214 +0x1609
k8s.io/kubernetes/pkg/kubectl/cmd.func·018(0xc20813de00, 0xc208190010, 0x1, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/edit.go:83 +0x7e
```

`UpdateApplyAnnotation` will panic. Ref #14626 as the possible cause

cc @jackgr @bgrant0607

**Comment by liggitt** [comment]
if #14626 was the cause, any fix needs to happen in 1.1 as well, #14626 was already cherry picked there

**Comment by bgrant0607** [comment]
Also shows that we need a test for this case.

**Comment by JanetKuo** [comment]
#14626 is the cause. When we edit multiple resources (i.e., list-type objects), the list's Accessor.annotations (type `*map[string]string`) is nil and will panic when UpdateApplyAnnotation tries to SetAnnotations (`*accessor.annotations = annotations`).
