### ISSUE TITLE
k8s-bot seems to have wandered off

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#16161]
I see several PRs now where @k8s-merge-robot is trying to get the attention of @k8s-bot and failing. (See #15946, #12393, #16127, etc.) I've also tried to manually kick. (See #13109).

Whiter has @k8s-bot wandered, and can we get it back soon?

cc @ixdy @quinton-hoole

**Comment by zmerlynn** [comment]
@k8s-oncall probably cares, too.

**Comment by ixdy** [comment]
It last triggered around 2:30am PDT. I'm not sure why it stopped triggering after that.

One thought is that the new unit test/integration build that @jlowdermilk was working on used up our API quota, but I haven't verified if that's the case or not.

**Comment by jlowdermilk** [comment]
@ixdy, the new build isn't enabled yet, so that seems unlikely.

**Comment by ixdy** [comment]
Well, it was enabled when I just looked at Jenkins. And it tried to run two builds a few minutes ago.

**Comment by ixdy** [comment]
oh, I see, the GitHub pull request plugin is disabled there now. Still looking.

**Comment by ixdy** [comment]
I restarted Jenkins and it's started running everything now. I'm not really sure what happened - my best guess is that there's some bug in the latest version of the pull request plugin we pulled in. We'll have to watch to see if it happens again...

**Comment by ixdy** [comment]
Last bit of the log from when it last was working. Nothing particularly notable here:
```
Oct 23, 2015 2:24:37 AM org.jvnet.hudson.plugins.thinbackup.backup.HudsonBackup backupJobsDirectory
INFO: Found 2 jobs to back up.
Oct 23, 2015 2:25:07 AM org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
INFO: Pull request #16,154 was updated on kubernetes/kubernetes at 10/23/15 2:23 AM by User:zhengguoyong
Oct 23, 2015 2:25:08 AM org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
INFO: Pull request #16,153 was updated on kubernetes/kubernetes at 10/23/15 2:24 AM by User:gmarek
Oct 23, 2015 2:30:19 AM org.jvnet.hudson.plugins.thinbackup.backup.HudsonBackup backupJobsDirectory
INFO: Found 2 jobs to back up.
Oct 23, 2015 2:31:07 AM org.jenkinsci.plugins.ghprb.GhprbPullRequest updatePR
INFO: Pull request #16,152 was updated on kubernetes/kubernetes at 10/23/15 2:29 AM by User:feihujiang
Oct 23, 2015 2:46:18 AM org.jvnet.hudson.plugins.thinbackup.hudson.model.AsyncPeriodicWork doRun
WARNING: ThinBackup Worker Thread thread is still running. Execution aborted.
Oct 23, 2015 2:47:18 AM org.jvnet.hudson.plugins.thinbackup.hudson.model.AsyncPeriodicWork doRun
WARNING: ThinBackup Worker Thread thread is still running. Execution aborted.
Oct 23, 2015 2:48:18 AM org.jvnet.hudson.plugins.thinbackup.hudson.model.AsyncPeriodicWork doRun
WARNING: ThinBackup Worker Thread thread is still running. Execution aborted.
Oct 23, 2015 2:49:18 AM org.jvnet.hudson.plugins.thinbackup.hudson.model.AsyncPeriodicWork doRun
WARNING: ThinBackup Worker Thread thread is still running. Execution aborted.
Oct 23, 2015 2:50:18 AM org.jvnet.hudson.plugins.thinbackup.hudson.model.AsyncPeriodicWork doRun
WARNING: ThinBackup Worker Thread thread is still running. Execution aborted.
Oct 23, 2015 2:51:18 AM org.jvnet.hudson.plugins.thinbackup.hudson.model.AsyncPeriodicWork doRun
WARNING: ThinBackup Worker Thread thread is still running. Execution aborted.
Oct 23, 2015 2:52:18 AM org.jvnet.hudson.plugins.thinbackup.hudson.model.AsyncPeriodicWork doRun
WARNING: ThinBackup Worker Thread thread is still running. Execution aborted.
Oct 23, 2015 2:53:18 AM org.jvnet.hudson.plugins.thinbackup.hudson.model.AsyncPeriodicWork doRun
WARNING: ThinBackup Worker Thread thread is still running. Execution aborted.
Oct 23, 2015 2:54:18 AM org.jvnet.hudson.plugins.thinbackup.hudson.model.AsyncPeriodicWork doRun
WARNING: ThinBackup Worker Thread thread is still running. Execution aborted.
Oct 23, 2015 2:55:18 AM org.jvnet.hudson.plugins.thinbackup.hudson.model.AsyncPeriodicWork doRun
WARNING: ThinBackup Worker Thread thread is still running. Execution aborted.
Oct 23, 2015 2:56:18 AM org.jvnet.hudson.plugins.thinbackup.hudson.model.AsyncPeriodicWork doRun
WARNING: ThinBackup Worker Thread thread is still running. Execution aborted.
Oct 23, 2015 2:57:18 AM org.jvnet.hudson.plugins.thinbackup.hudson.model.AsyncPeriodicWork doRun
WARNING: ThinBackup Worker Thread thread is still running. Execution aborted.
Oct 23, 2015 2:58:18 AM org.jvnet.hudson.plugins.thinbackup.hudson.model.AsyncPeriodicWork doRun
WARNING: ThinBackup Worker Thread thread is still running. Execution aborted.
Oct 23, 2015 2:58:52 AM hudson.model.Run execute
INFO: kubernetes-pull-build-test-e2e-gce #13989 main build action completed: SUCCESS
Oct 23, 2015 2:59:17 AM hudson.model.listeners.RunListener report
WARNING: RunListener failed
java.lang.NumberFormatException: For input string: "^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@:
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@8853"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:430)
        at java.lang.Long.valueOf(Long.java:540)
        at jenkins.plugins.util.ReadUtil.getBuildMessageFrom(ReadUtil.java:56)
        at jenkins.plugins.mttr.MetricsAction$RunListenerImpl.onCompleted(MetricsAction.java:108)
        at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
        at hudson.model.Run.execute(Run.java:1786)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
        at hudson.model.ResourceController.execute(ResourceController.java:98)
        at hudson.model.Executor.run(Executor.java:410)

Oct 23, 2015 2:59:18 AM org.jvnet.hudson.plugins.thinbackup.hudson.model.AsyncPeriodicWork doRun
WARNING: ThinBackup Worker Thread thread is still running. Execution aborted.
Oct 23, 2015 2:59:18 AM org.jvnet.hudson.plugins.thinbackup.backup.HudsonBackup backupJobsDirectory
INFO: Found 2 jobs to back up.
Oct 23, 2015 3:00:19 AM org.jvnet.hudson.plugins.thinbackup.backup.HudsonBackup backupJobsDirectory
INFO: Found 2 jobs to back up.
Oct 23, 2015 3:15:19 AM org.jvnet.hudson.plugins.thinbackup.backup.HudsonBackup backupJobsDirectory
INFO: Found 2 jobs to back up.
Oct 23, 2015 3:30:19 AM org.jvnet.hudson.plugins.thinbackup.backup.HudsonBackup backupJobsDirectory
INFO: Found 2 jobs to back up.
Oct 23, 2015 3:45:19 AM org.jvnet.hudson.plugins.thinbackup.backup.HudsonBackup backupJobsDirectory
INFO: Found 2 jobs to back up.
Oct 23, 2015 4:00:19 AM org.jvnet.hudson.plugins.thinbackup.backup.HudsonBackup backupJobsDirectory
INFO: Found 2 jobs to back up.
Oct 23, 2015 4:15:19 AM org.jvnet.hudson.plugins.thinbackup.backup.HudsonBackup backupJobsDirectory
INFO: Found 2 jobs to back up.
Oct 23, 2015 4:30:19 AM org.jvnet.hudson.plugins.thinbackup.backup.HudsonBackup backupJobsDirectory
INFO: Found 2 jobs to back up.
Oct 23, 2015 4:45:19 AM org.jvnet.hudson.plugins.thinbackup.backup.HudsonBackup backupJobsDirectory
INFO: Found 2 jobs to back up.
...
Oct 23, 2015 9:30:19 AM org.jvnet.hudson.plugins.thinbackup.backup.HudsonBackup backupJobsDirectory
INFO: Found 2 jobs to back up.
Oct 23, 2015 9:45:19 AM org.jvnet.hudson.plugins.thinbackup.backup.HudsonBackup backupJobsDirectory
INFO: Found 2 jobs to back up.
Oct 23, 2015 10:00:19 AM org.jvnet.hudson.plugins.thinbackup.backup.HudsonBackup backupJobsDirectory
INFO: Found 2 jobs to back up.
Oct 23, 2015 10:07:59 AM org.jenkinsci.plugins.ghprb.GhprbTrigger stop
INFO: Stopping the ghprb trigger for project kubernetes-pull-build-test-unit-integration
Oct 23, 2015 10:07:59 AM org.eclipse.jetty.util.log.JavaUtilLog warn
WARNING: Error while serving http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-unit-integration/configSubmit
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[long stack trace]
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed to instantiate class com.google.jenkins.plugins.storage.GoogleCloudStorageUploader from {"uploads":[{"logName":"build-log.txt","bucket":"gs://kubernetes-jenkins/pr-logs/${ghprbActualCommit}/${JOB_NAME}/${BUILD_NUMBER}","sharedPublicly":false,"forFailedJobs":true,"stripPathPrefix":false,"pathPrefix":"","stapler-class":"com.google.jenkins.plugins.storage.StdoutUpload","$class":"com.google.jenkins.plugins.storage.StdoutUpload"},{"pattern":"_artifacts/**","bucket":"gs://kubernetes-jenkins/pr-logs/${ghprbActualCommit}/${JOB_NAME}/${BUILD_NUMBER}","sharedPublicly":false,"forFailedJobs":true,"stripPathPrefix":false,"pathPrefix":"","stapler-class":"com.google.jenkins.plugins.storage.ClassicUpload","$class":"com.google.jenkins.plugins.storage.ClassicUpload"}],"stapler-class":"com.google.jenkins.plugins.storage.GoogleCloudStorageUploader","$class":"com.google.jenkins.plugins.storage.GoogleCloudStorageUploader"}
        at hudson.model.Descriptor.newInstance(Descriptor.java:579)
        at hudson.model.Descriptor.newInstancesFromHeteroList(Descriptor.java:941)
        at hudson.model.Descriptor.newInstancesFromHeteroList(Descriptor.java:903)
        at hudson.util.DescribableList.rebuildHetero(DescribableList.java:208)
        at hudson.model.Project.submit(Project.java:236)
        at hudson.model.Job.doConfigSubmit(Job.java:1206)
        at hudson.model.AbstractProject.doConfigSubmit(AbstractProject.java:798)
        ... 75 more
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:187)
[long stacktrace]
        ... 81 more

Oct 23, 2015 10:08:47 AM org.jenkinsci.plugins.ghprb.GhprbTrigger stop
INFO: Stopping the ghprb trigger for project null
Oct 23, 2015 10:08:47 AM org.eclipse.jetty.util.log.JavaUtilLog warn
WARNING: Error while serving http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-unit-integration/configSubmit
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[long stacktrace]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
Oct 23, 2015 10:09:38 AM org.jenkinsci.plugins.ghprb.GhprbTrigger stop
INFO: Stopping the ghprb trigger for project null
Oct 23, 2015 10:16:08 AM org.jenkinsci.plugins.ghprb.GhprbTrigger stop
INFO: Stopping the ghprb trigger for project null
Oct 23, 2015 10:30:19 AM org.jvnet.hudson.plugins.thinbackup.backup.HudsonBackup backupJobsDirectory
INFO: Found 2 jobs to back up.
Oct 23, 2015 10:33:28 AM org.jenkinsci.plugins.ghprb.GhprbTrigger stop
INFO: Stopping the ghprb trigger for project null
Oct 23, 2015 10:35:50 AM org.jenkinsci.plugins.ghprb.GhprbTrigger stop
INFO: Stopping the ghprb trigger for project null
Oct 23, 2015 10:38:51 AM org.jenkinsci.plugins.ghprb.GhprbTrigger stop
INFO: Stopping the ghprb trigger for project null
```

I guess one weird thing (beside the NPEs which seem to happen regularly without causing issues?) is the "Stopping the ghprb trigger for project null" - maybe that was causing some sort of issues? Not sure how it happened, though. And I'm not sure what would've happened around 2:30 or 3am to break everything.

**Comment by ihmccreery** [comment]
Knocking this down to P2 until we see this again.

**Comment by jlowdermilk** [comment]
Let's just close. We can reopen if we see the issue again.
