### ISSUE TITLE
Panic in kubectl jsonpath templating 

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#16684]
```console
$ kubectl config view -o 'jsonpath={.contexts[?(@.name == \"\")].context.user}'
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0xbbf926]
goroutine 1 [running]:
k8s.io/kubernetes/pkg/util/jsonpath.parseAction(0x13284f0, 0x5, 0xc2080b0edf, 0x5, 0xc20800b450, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/jsonpath/parser.go:66 +0x266
k8s.io/kubernetes/pkg/util/jsonpath.(*Parser).parseFilter(0xc20800b3b0, 0xc208180ea0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/jsonpath/parser.go:349 +0x712
k8s.io/kubernetes/pkg/util/jsonpath.*Parser.(k8s.io/kubernetes/pkg/util/jsonpath.parseFilter)·fm(0xc208180ea0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/jsonpath/parser.go:140 +0x43
k8s.io/kubernetes/pkg/util/jsonpath.(*Parser).parseInsideAction(0xc20800b3b0, 0xc208180ea0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/jsonpath/parser.go:145 +0x3a0
k8s.io/kubernetes/pkg/util/jsonpath.(*Parser).parseField(0xc20800b3b0, 0xc208180ea0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/jsonpath/parser.go:391 +0x359
k8s.io/kubernetes/pkg/util/jsonpath.(*Parser).parseInsideAction(0xc20800b3b0, 0xc208180ea0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/jsonpath/parser.go:161 +0x55b
k8s.io/kubernetes/pkg/util/jsonpath.(*Parser).parseLeftDelim(0xc20800b3b0, 0xc208180ea0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/jsonpath/parser.go:134 +0x277
k8s.io/kubernetes/pkg/util/jsonpath.(*Parser).parseText(0xc20800b3b0, 0xc208180e80, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/jsonpath/parser.go:114 +0x3bc
k8s.io/kubernetes/pkg/util/jsonpath.(*Parser).Parse(0xc20800b3b0, 0xc2080b0ec9, 0x2b, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/jsonpath/parser.go:74 +0xc8
k8s.io/kubernetes/pkg/util/jsonpath.Parse(0x13258f0, 0x3, 0xc2080b0ec9, 0x2b, 0x1274660, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/jsonpath/parser.go:50 +0xbc
k8s.io/kubernetes/pkg/util/jsonpath.(*JSONPath).Parse(0xc208178600, 0xc2080b0ec9, 0x2b, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/jsonpath/jsonpath.go:50 +0x5e
k8s.io/kubernetes/pkg/kubectl.NewJSONPathPrinter(0xc2080b0ec9, 0x2b, 0x1c0e298, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource_printer.go:1672 +0xdf
k8s.io/kubernetes/pkg/kubectl.GetPrinter(0x135d450, 0x8, 0xc2080b0ec9, 0x2b, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource_printer.go:96 +0x11b6
k8s.io/kubernetes/pkg/kubectl/cmd/util.PrinterForCommand(0xc208175c20, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/printing.go:106 +0x305
k8s.io/kubernetes/pkg/kubectl/cmd/config.func·008(0xc208175c20, 0xc208180e60, 0x0, 0x2)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/config/view.go:64 +0x51
github.com/spf13/cobra.(*Command).execute(0xc208175c20, 0xc208180ca0, 0x2, 0x2, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:547 +0x82f
github.com/spf13/cobra.(*Command).Execute(0xc2080def00, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:630 +0x414
main.main()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:30 +0x104
goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1c02040)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/src/go/src/runtime/asm_amd64.s:2232 +0x1
goroutine 13 [syscall]:
os/signal.loop()
        /usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/src/go/src/os/signal/signal_unix.go:27 +0x35
```

@kubernetes/goog-ux

**Comment by janetkuo** [comment]
I think the right way to do this is either 
`$ kubectl config view -o jsonpath={.contexts[?(@.name == \"\")].context.user}`
or 
`$ kubectl config view -o 'jsonpath={.contexts[?(@.name == "")].context.user}'`

Can you try both commands and see if it still panics?

**Comment by mikedanese** [comment]
I agree that the input is malformed, but kubectl should return an error on malformed input and not panic. When I correct the input, it works as expected.

**Comment by janetkuo** [comment]
The fix would be improving error handling then.
