### ISSUE TITLE
Flaky: k8s.io/kubernetes/pkg/controller/framework_test.TestUpdate

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#17018]
```
E1109 11:31:44.493904    3385 util.go:82] Recovered from panic: "sync: negative WaitGroup counter" (sync: negative WaitGroup counter)
/home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:76
/home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:64
/usr/lib/golang/src/runtime/asm_amd64.s:437
/usr/lib/golang/src/runtime/panic.go:423
/usr/lib/golang/src/sync/waitgroup.go:70
/usr/lib/golang/src/sync/waitgroup.go:95
/home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller_test.go:368
/home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:182
<autogenerated>:23
/home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:252
/home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:126
/home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:96
/home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:126
/home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:127
/home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:96
/usr/lib/golang/src/runtime/asm_amd64.s:1696
--- FAIL: TestUpdate (1.00s)
panic: sync: WaitGroup is reused before previous Wait has returned [recovered]
        panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 7 [running]:
testing.tRunner.func1(0xc8201ae990)
        /usr/lib/golang/src/testing/testing.go:450 +0x171
sync.(*WaitGroup).Wait(0xc820230b80)
        /usr/lib/golang/src/sync/waitgroup.go:128 +0x114
k8s.io/kubernetes/pkg/controller/framework_test.TestUpdate(0xc8201ae990)
        /home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller_test.go:393 +0xb11
testing.tRunner(0xc8201ae990, 0x1887d90)
        /usr/lib/golang/src/testing/testing.go:456 +0x98
created by testing.RunTests
        /usr/lib/golang/src/testing/testing.go:561 +0x86d

goroutine 1 [chan receive]:
testing.RunTests(0x12fc4c8, 0x1887d60, 0x3, 0x3, 0xc820230a01)
        /usr/lib/golang/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc8200d3ee8, 0xc82006f938)
        /usr/lib/golang/src/testing/testing.go:494 +0x70
main.main()
        k8s.io/kubernetes/pkg/controller/framework/_test/_testmain.go:64 +0x116

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x18a6080)
        /home/vagrant/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x67
created by github.com/golang/glog.init.1
        /home/vagrant/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297

goroutine 8 [chan receive]:
k8s.io/kubernetes/pkg/watch.(*Broadcaster).loop(0xc8201a4800)
        /home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/watch/mux.go:198 +0x58
created by k8s.io/kubernetes/pkg/watch.NewBroadcaster
        /home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/watch/mux.go:74 +0x128

goroutine 9 [select]:
k8s.io/kubernetes/pkg/util.Until(0xc8200cff68, 0x3b9aca00, 0xc8202401e0)
        /home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:128 +0x125
k8s.io/kubernetes/pkg/controller/framework.(*Controller).Run(0xc82023cee0, 0xc8202401e0)
        /home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:96 +0x1c2
created by k8s.io/kubernetes/pkg/controller/framework_test.TestUpdate
        /home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller_test.go:377 +0x869

goroutine 55 [runnable]:
k8s.io/kubernetes/pkg/client/cache.(*Reflector).watchHandler(0xc8201aeab0, 0x7fa38f8852e8, 0xc820277cb0, 0xc82004dc88, 0xc820241ec0, 0xc8202401e0, 0x0, 0x0)
        /home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:312 +0x13df
k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch(0xc8201aeab0, 0xc8202401e0, 0x0, 0x0)
        /home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:279 +0x1215
k8s.io/kubernetes/pkg/client/cache.(*Reflector).RunUntil.func1()
        /home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:164 +0x29
k8s.io/kubernetes/pkg/util.Until.func1(0xc820216ea0)
        /home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:126 +0x4b
k8s.io/kubernetes/pkg/util.Until(0xc820216ea0, 0x3b9aca00, 0xc8202401e0)
        /home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:127 +0x68
created by k8s.io/kubernetes/pkg/client/cache.(*Reflector).RunUntil
        /home/vagrant/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:164 +0x9a
```

I got this by running the following against commit d65c61f:

```
export GOPATH=/home/vagrant/go/src/k8s.io/kubernetes/_output/local/go:/home/vagrant/go/src/k8s.io/kubernetes/Godeps/_workspace
go test -c k8s.io/kubernetes/pkg/controller/framework
while true; do GOMAXPROCS=4 ./framework.test -test.run TestUpdate; if [ $? != 0 ]; then break; fi; done
```

There have been previous attempts to fix this:

- #13058
- #14881

It appears it's still an issue :cry: 

We're also seeing it in OpenShift (https://github.com/openshift/origin/issues/5389), although our code hasn't pulled in the fix from #14881 quite yet.

**Comment by a-robinson** [comment]
cc @lavalamp

**Comment by lavalamp** [comment]
What go version are you using? Previously this test has been catching legit bugs, so I'm not sure about the "flaky" moniker.

**Comment by ncdc** [comment]
@lavalamp go 1.5.1. I noticed you had a comment in another issue or PR about this possibly being a bug in Go itself (or did I misread)?

**Comment by lavalamp** [comment]
I doubt it's a bug in go. (go1.5 had an unrelated bug, maybe that's what you're thinking of.) We haven't actually flipped 1.5 on so I may sit on this for a bit.

**Comment by krousey** [comment]
I instrumented this code, and this is being caused by duplicate deletions causing the wait group to decrement below 0. Are duplicate deletions a bug? Or should the wait group be guarded against that?

**Comment by krousey** [comment]
@lavalamp ping

If duplicate deletes are not a bug, I can put together a quick PR to guard against that. If they are a bug, I could try to track it down sometime this week (even thought I'm not that familiar with this code) if no one else is going to look into it.

**Comment by lavalamp** [comment]
Duplicate deletes are a bug. (assuming that the test harness isn't actually issuing multiple deletes for the same item.)

**Comment by lavalamp** [comment]
@krousey That would be great if you could take this, since I won't have time.

**Comment by krousey** [comment]
@lavalamp So it would be an error in the test if `source.Delete(n)` was called multiple times for the same pod? Or should the framework be de-duping that?

**Comment by lavalamp** [comment]
IMO, that's a test error.

...If the test is doing that because the framework dup'd an update or an
add, then it's a framework error. (adds and updates shouldn't be duped,
either)

**Comment by krousey** [comment]
@lavalamp from what I gather, this test is just trying to delete after each pod reaches it's final intended state. This code is deleting on every event, including intermediate ones. In particular, this test case is occasionally causing duplicate deletes to be issued:

```go
		func(name string) {
			name = "c-" + name
			source.AddDropWatch(pod(name, FROM))
			source.Modify(pod(name, ADD_MISSED))
			source.Modify(pod(name, TO))
		},
```

Sometimes it catches the transition from FROM to ADD_MISSED, and then gets ADD_MISSED to TO. I think the fix is to tell the test to only issue the delete when the final state is TO. I'll do that and some stress testing to see if it goes away.

**Comment by krousey** [comment]
3589 runs so far, 10 failures

and all 10 failures seem to confirm the above behavior.

**Comment by krousey** [comment]
Guarding against this:
10124 runs so far, 0 failures

I will clean this up and send out a fix shortly.

**Comment by lavalamp** [comment]
Awesome, thanks!

**Comment by krousey** [comment]
Accidentally left the test case running. Good news:
```console
> stress -p 50 ./framework.test -test.run TestUpdate
...
225515 runs so far, 0 failures
^C
```

**Comment by lavalamp** [comment]
It's probably safe to say that if there's remaining corner cases, your
setup is not going to exercise them! :)
