### ISSUE TITLE
TestMetrics fails on a mac

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#18605]
```
--- FAIL: TestMetrics (0.01s)
	empty_dir_test.go:304: Unexpected error when calling GetMetrics failed command 'du' on /var/folders/zw/j6656mbn1rv4fnqqdggss8h80000gn/T/empty_dir_test527299312/pods/poduid/volumes/kubernetes.io~empty-dir/vol1 with error exit status 64
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x26f188]

goroutine 36 [running]:
testing.tRunner.func1(0xc8202497a0)
	/usr/local/Cellar/go/1.5.1/libexec/src/testing/testing.go:450 +0x171
k8s.io/kubernetes/pkg/api/resource.(*Quantity).Value(0x0, 0xeb8480)
	/Users/clayton/projects/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/api/resource/quantity.go:382 +0x18
k8s.io/kubernetes/pkg/volume/empty_dir.TestMetrics(0xc8202497a0)
	/Users/clayton/projects/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/empty_dir/empty_dir_test.go:306 +0x616
testing.tRunner(0xc8202497a0, 0x1384b18)
```

**Comment by saad-ali** [comment]
CC @pmorie 
Related to #18580?

**Comment by ncdc** [comment]
I helped Paul out a bit on this one. The issue on osx is that `du` doesn't support `-B`.

**Comment by pmorie** [comment]
Looks like we can use `BLOCKSIZE` environment variable instead, but I wonder if shelling out to `du` is the right solution for this.  Seems fragile.

**Comment by smarterclayton** [comment]
Could just disable the test on macs.

**Comment by smarterclayton** [comment]
Fixed
