### ISSUE TITLE
e2e test failure: Build step 'Set build status on GitHub commit' marked build as failure

### ISSUE THREAD

**Issue by janetkuo** [kubernetes/kubernetes#18879]
Recent 5 e2e test (#21196~21199, 21201) failed even though tests are passed. 
```
19:32:38 [kubernetes-pull-build-test-e2e-gce] $ /bin/bash -xe /tmp/hudson3547670558140125091.sh
19:32:38 + make clean
19:32:38 build/make-clean.sh
19:32:38 +++ [1218 03:32:38] Verifying Prerequisites....
19:32:39 +++ [1218 03:32:39] Cleaning out _output/dockerized/bin/ via docker build image
19:32:39 +++ [1218 03:32:39] Running build command....
19:32:42 +++ [1218 03:32:42] Removing data container
19:32:44 +++ [1218 03:32:44] Cleaning out local _output directory
19:32:46 +++ [1218 03:32:46] Deleting docker image kube-build:build-8f5624d469
19:32:47 Untagged: kube-build:build-8f5624d469
19:32:47 Deleted: 999c492c0917dc3ccca89f170a26335c4c4b480d945bdaa9c2f86c165ab9264b
19:32:47 Deleted: b9aa3af9c3c8e53afe4e8a8baaaebe862b2d6fda4a363c8b96cbe0c81b2e9388
19:32:47 Deleted: d1dfe5ff392e9f060fc789610a2b8ce75076aadc5e76f776033d723ad2724599
19:32:47 Deleted: 0373ab5c20f02995692661625bc9bbe17aaa763e48e709f7e6147258905d8fac
19:32:47 +++ [1218 03:32:47] Cleaning all other untagged docker images
19:32:48 rm -rf _output
19:32:48 rm -rf Godeps/_workspace/pkg
19:32:48 Recording test results
19:32:51 [Google Cloud Storage Uploader] Uploading: build-log.txt
19:32:51 ERROR: Build step failed with exception
19:32:51 java.lang.NullPointerException
19:32:51 	at com.cloudbees.jenkins.GitHubCommitNotifier.updateCommitStatus(GitHubCommitNotifier.java:127)
19:32:51 	at com.cloudbees.jenkins.GitHubCommitNotifier.perform(GitHubCommitNotifier.java:105)
19:32:51 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
19:32:51 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
19:32:51 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
19:32:51 	at hudson.model.Build$BuildExecution.post2(Build.java:185)
19:32:51 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
19:32:51 	at hudson.model.Run.execute(Run.java:1763)
19:32:51 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
19:32:51 	at hudson.model.ResourceController.execute(ResourceController.java:98)
19:32:51 	at hudson.model.Executor.run(Executor.java:410)
19:32:51 Build step 'Set build status on GitHub commit' marked build as failure
19:32:51 Setting status of 7a4643f123c6aa1490d90099616a972cba1621a4 to FAILURE with url http://goto.google.com/prkubekins/job/kubernetes-pull-build-test-e2e-gce/21198/ and message: ' 208 tests run, 92 skipped, 0 failed.'
19:32:51 Using context: Jenkins GCE e2e
19:32:51 GCE e2e build/test **failed** for commit 7a4643f123c6aa1490d90099616a972cba1621a4.
```

cc @ixdy @quinton-hoole @k8s-oncall

**Comment by ixdy** [comment]
Apparently the latest version of the GitHub API Jenkins plugin (which I just upgraded tonight) is broken. Good to know!

Downgrading back to the previous version.

**Comment by ixdy** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-32132 is the relevant bug.

**Comment by ixdy** [comment]
Should be fixed on PR Jenkins.

**Comment by ixdy** [comment]
I apparently reverted the wrong plugin. Let's try again...

**Comment by ixdy** [comment]
Actually fixed: https://github.com/kubernetes/kubernetes/pull/17398#issuecomment-165689090

**Comment by janetkuo** [comment]
:+1: Thanks!
