### ISSUE TITLE
Openstack cloud provider invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dougbishop** [kubernetes/kubernetes#19264]
Kubernetes version: 1.1.0-0.4.git2bfa9a1.el7

OS:CentOS Linux release 7.1.1503 (Core)

The kubelet keeps failing with the following:

```
Dec 24 03:13:22 localhost kubelet: I1224 03:13:22.563665   20056 manager.go:158] Machine: {NumCores:1 CpuFrequency:2992788 MemoryCapacity:1929773056 MachineID:19d82c8902374e7caa655973bd7a6e6a SystemUUID:B75EF5E2-CCA7-4C77-9A75-98B1978DA33C BootID:7bf3d099-ab48-41ce-b91b-cacf7dfccf9d Filesystems:[{Device:/dev/vda1 Capacity:21456445440}] DiskMap:map[252:0:{Name:dm-0 Major:252 Minor:0 Size:107374182400 Scheduler:none} 253:0:{Name:vda Major:253 Minor:0 Size:21474836480 Scheduler:none}] NetworkDevices:[{Name:eth0 MacAddress:fa:16:3e:5d:3c:38 Speed:0 Mtu:1500} {Name:flannel0 MacAddress: Speed:10 Mtu:1472}] Topology:[{Id:0 Memory:2147074048 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:4194304 Type:Unified Level:2}]}] Caches:[]}] CloudProvider:Unknown InstanceType:Unknown}
Dec 24 03:13:22 localhost docker: time="2015-12-24T03:13:22.570268941Z" level=info msg="GET /version"
Dec 24 03:13:22 localhost kubelet: I1224 03:13:22.570915   20056 manager.go:165] Version: {KernelVersion:3.10.0-229.7.2.el7.x86_64 ContainerOsVersion:CentOS Linux 7 (Core) DockerVersion:1.8.2-el7.centos CadvisorVersion:0.16.0}
Dec 24 03:13:22 localhost kubelet: panic: runtime error: invalid memory address or nil pointer dereference
Dec 24 03:13:22 localhost kubelet: [signal 0xb code=0x1 addr=0x0 pc=0x57062d]
Dec 24 03:13:22 localhost kubelet: goroutine 1 [running]:
Dec 24 03:13:22 localhost kubelet: k8s.io/kubernetes/pkg/cloudprovider/openstack.(*OpenStack).Instances(0x0, 0x0, 0x0, 0xa)
Dec 24 03:13:22 localhost kubelet: /builddir/build/BUILD/kubernetes-2bfa9a1f98147cfdc2e9f4cf50e2c430518d91eb/_output/local/go/src/k8s.io/kubernetes/pkg/cloudprovider/openstack/openstack.go:163 +0x8ed
Dec 24 03:13:22 localhost kubelet: k8s.io/kubernetes/cmd/kubelet/app.RunKubelet(0xc8200cc000, 0x0, 0x0, 0x0)
Dec 24 03:13:22 localhost kubelet: /builddir/build/BUILD/kubernetes-2bfa9a1f98147cfdc2e9f4cf50e2c430518d91eb/_output/local/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:616 +0x13c
Dec 24 03:13:22 localhost kubelet: k8s.io/kubernetes/cmd/kubelet/app.(*KubeletServer).Run(0xc820238000, 0xc8200cc000, 0x0, 0x0)
Dec 24 03:13:22 localhost kubelet: /builddir/build/BUILD/kubernetes-2bfa9a1f98147cfdc2e9f4cf50e2c430518d91eb/_output/local/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:410 +0x84b
Dec 24 03:13:22 localhost kubelet: main.main()
Dec 24 03:13:22 localhost kubelet: /builddir/build/BUILD/kubernetes-2bfa9a1f98147cfdc2e9f4cf50e2c430518d91eb/_output/local/go/src/k8s.io/kubernetes/cmd/kubelet/kubelet.go:46 +0xab
Dec 24 03:13:22 localhost kubelet: goroutine 17 [syscall, locked to thread]:
Dec 24 03:13:22 localhost kubelet: runtime.goexit()
Dec 24 03:13:22 localhost kubelet: /usr/lib/golang/src/runtime/asm_amd64.s:1696 +0x1
Dec 24 03:13:22 localhost kubelet: goroutine 5 [chan receive]:
Dec 24 03:13:22 localhost kubelet: github.com/golang/glog.(*loggingT).flushDaemon(0x1c8b7a0)
Dec 24 03:13:22 localhost kubelet: /builddir/build/BUILD/kubernetes-2bfa9a1f98147cfdc2e9f4cf50e2c430518d91eb/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x67
Dec 24 03:13:22 localhost kubelet: created by github.com/golang/glog.init.1
Dec 24 03:13:22 localhost kubelet: /builddir/build/BUILD/kubernetes-2bfa9a1f98147cfdc2e9f4cf50e2c430518d91eb/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297
Dec 24 03:13:22 localhost kubelet: goroutine 13 [syscall]:
Dec 24 03:13:22 localhost kubelet: os/signal.loop()
Dec 24 03:13:22 localhost kubelet: /usr/lib/golang/src/os/signal/signal_unix.go:22 +0x18
Dec 24 03:13:22 localhost kubelet: created by os/signal.init.1
Dec 24 03:13:22 localhost kubelet: /usr/lib/golang/src/os/signal/signal_unix.go:28 +0x37
Dec 24 03:13:22 localhost kubelet: goroutine 16 [sleep]:
Dec 24 03:13:22 localhost kubelet: time.Sleep(0x12a05f200)
Dec 24 03:13:22 localhost kubelet: /usr/lib/golang/src/runtime/time.go:59 +0xf9
Dec 24 03:13:22 localhost kubelet: k8s.io/kubernetes/pkg/util.Until(0x15589a0, 0x12a05f200, 0x0)
Dec 24 03:13:22 localhost kubelet: /builddir/build/BUILD/kubernetes-2bfa9a1f98147cfdc2e9f4cf50e2c430518d91eb/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:113 +0x61
Dec 24 03:13:22 localhost kubelet: k8s.io/kubernetes/pkg/util.Forever(0x15589a0, 0x12a05f200)
Dec 24 03:13:22 localhost kubelet: /builddir/build/BUILD/kubernetes-2bfa9a1f98147cfdc2e9f4cf50e2c430518d91eb/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:93 +0x34
Dec 24 03:13:22 localhost kubelet: created by k8s.io/kubernetes/pkg/util.InitLogs
Dec 24 03:13:22 localhost kubelet: /builddir/build/BUILD/kubernetes-2bfa9a1f98147cfdc2e9f4cf50e2c430518d91eb/_output/local/go/src/k8s.io/kubernetes/pkg/util/logs.go:50 +0xae
Dec 24 03:13:22 localhost kubelet: goroutine 31 [IO wait]:
Dec 24 03:13:22 localhost kubelet: net.runtime_pollWait(0x7f19addac638, 0x72, 0xc820010120)
Dec 24 03:13:22 localhost kubelet: /usr/lib/golang/src/runtime/netpoll.go:157 +0x60
Dec 24 03:13:22 localhost kubelet: net.(*pollDesc).Wait(0xc82022f100, 0x72, 0x0, 0x0)
Dec 24 03:13:22 localhost kubelet: /usr/lib/golang/src/net/fd_poll_runtime.go:73 +0x3a
Dec 24 03:13:22 localhost kubelet: net.(*pollDesc).WaitRead(0xc82022f100, 0x0, 0x0)
Dec 24 03:13:22 localhost kubelet: /usr/lib/golang/src/net/fd_poll_runtime.go:78 +0x36
Dec 24 03:13:22 localhost kubelet: net.(*netFD).accept(0xc82022f0a0, 0x0, 0x7f19addad7b8, 0xc8204d1a80)
Dec 24 03:13:22 localhost kubelet: /usr/lib/golang/src/net/fd_unix.go:408 +0x27c
Dec 24 03:13:22 localhost kubelet: net.(*TCPListener).AcceptTCP(0xc8200264d8, 0xc820034d98, 0x0, 0x0)
Dec 24 03:13:22 localhost kubelet: /usr/lib/golang/src/net/tcpsock_posix.go:249 +0x4d
Dec 24 03:13:22 localhost kubelet: net/http.tcpKeepAliveListener.Accept(0xc8200264d8, 0x0, 0x0, 0x0, 0x0)
Dec 24 03:13:22 localhost kubelet: /usr/lib/golang/src/net/http/server.go:2092 +0x41
Dec 24 03:13:22 localhost kubelet: net/http.(*Server).Serve(0xc820016f00, 0x7f19addad780, 0xc8200264d8, 0x0, 0x0)
Dec 24 03:13:22 localhost kubelet: /usr/lib/golang/src/net/http/server.go:1841 +0xb3
Dec 24 03:13:22 localhost kubelet: net/http.(*Server).ListenAndServe(0xc820016f00, 0x0, 0x0)
Dec 24 03:13:22 localhost kubelet: /usr/lib/golang/src/net/http/server.go:1831 +0x136
Dec 24 03:13:22 localhost kubelet: k8s.io/kubernetes/pkg/kubelet/cadvisor.(*cadvisorClient).exportHTTP.func1(0xc820016f00, 0x1062)
Dec 24 03:13:22 localhost kubelet: /builddir/build/BUILD/kubernetes-2bfa9a1f98147cfdc2e9f4cf50e2c430518d91eb/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cadvisor/cadvisor_linux.go:99 +0x6a
Dec 24 03:13:22 localhost kubelet: created by k8s.io/kubernetes/pkg/kubelet/cadvisor.(*cadvisorClient).exportHTTP
Dec 24 03:13:22 localhost kubelet: /builddir/build/BUILD/kubernetes-2bfa9a1f98147cfdc2e9f4cf50e2c430518d91eb/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cadvisor/cadvisor_linux.go:105 +0x3ac
Dec 24 03:13:22 localhost systemd: kubelet.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 24 03:13:22 localhost systemd: Unit kubelet.service entered failed state.
Dec 24 03:13:22 localhost systemd: kubelet.service holdoff time over, scheduling restart.
Dec 24 03:13:22 localhost systemd: Stopping Kubernetes Kubelet Server...
Dec 24 03:13:22 localhost systemd: Starting Kubernetes Kubelet Server...
Dec 24 03:13:22 localhost systemd: kubelet.service start request repeated too quickly, refusing to start.
Dec 24 03:13:22 localhost systemd: Failed to start Kubernetes Kubelet Server.
Dec 24 03:13:22 localhost systemd: Unit kubelet.service entered failed state.
```

kublet config:

```
###
# kubernetes kubelet (minion) config

# The address for the info server to serve on (set to 0.0.0.0 or "" for all interfaces)
KUBELET_ADDRESS="--address=0.0.0.0"

# The port for the info server to serve on
# KUBELET_PORT="--port=10250"

# You may leave this blank to use the actual hostname
KUBELET_HOSTNAME="kube-node1"

# location of the api-server
KUBELET_API_SERVER="--api-servers=http://kube-master:8080"

# Add your own!
KUBELET_ARGS="--cloud-provider=openstack --cloud-config=/etc/kubernetes/cloud-config"
[root@kube-node1 kubernetes]#
```

config:

```
###
# kubernetes system config
#
# The following values are used to configure various aspects of all
# kubernetes services, including
#
#   kube-apiserver.service
#   kube-controller-manager.service
#   kube-scheduler.service
#   kubelet.service
#   kube-proxy.service
# logging to stderr means we get it in the systemd journal
KUBE_LOGTOSTDERR="--logtostderr=true"

# journal message level, 0 is debug
KUBE_LOG_LEVEL="--v=0"

# Should this cluster be allowed to run privileged docker containers
KUBE_ALLOW_PRIV="--allow-privileged=false"

# How the controller-manager, scheduler, and proxy find the apiserver
KUBE_MASTER="--master=http://kube-master:8080"
```

cloud-config:

```
[Global]
auth-url = http://172.200.1.5/v2.0
user-id = nova
api-key = password
region = RegionOne
tenant-id = service
tenant-name = service
```

Not sure what I am missing here. Been at it for hours, unfortunately the code for the openstack provider does not tell you when a param is missing, or malformed. Any help would be appreciated.

**Comment by AdoHe** [comment]
@freshfrmthehood would you mind check `Instances` function of the openstack cloud provider? from the stack trace I guess it is related with this method.

**Comment by freshfrmthehood** [comment]
From what i see the instances function looks pretty basic:

type Instances struct {
	compute            *gophercloud.ServiceClient
	flavor_to_resource map[string]*api.NodeResources // keyed by flavor id
}

My guess is that this is causing it:
	compute            *gophercloud.ServiceClient

However my knowledge of Go is limited, so not sure what else I can troubleshoot here, any more ideas?

Thanks!

**Comment by AdoHe** [comment]
@freshfrmthehood  I just checked the v1.1.0 source code, below is the `Instances` method:
```
func (os *OpenStack) Instances() (cloudprovider.Instances, bool) {
	glog.V(4).Info("openstack.Instances() called")

	compute, err := openstack.NewComputeV2(os.provider, gophercloud.EndpointOpts{
		Region: os.region,
	})
	if err != nil {
		glog.Warningf("Failed to find compute endpoint: %v", err)
		return nil, false
	}

	pager := flavors.ListDetail(compute, nil)

	flavor_to_resource := make(map[string]*api.NodeResources)
	err = pager.EachPage(func(page pagination.Page) (bool, error) {
		flavorList, err := flavors.ExtractFlavors(page)
		if err != nil {
			return false, err
		}
		for _, flavor := range flavorList {
			rsrc := api.NodeResources{
				Capacity: api.ResourceList{
					api.ResourceCPU:            *resource.NewQuantity(int64(flavor.VCPUs), resource.DecimalSI),
					api.ResourceMemory:         *resource.NewQuantity(int64(flavor.RAM)*MiB, resource.BinarySI),
					"openstack.org/disk":       *resource.NewQuantity(int64(flavor.Disk)*GB, resource.DecimalSI),
					"openstack.org/rxTxFactor": *resource.NewMilliQuantity(int64(flavor.RxTxFactor)*1000, resource.DecimalSI),
					"openstack.org/swap":       *resource.NewQuantity(int64(flavor.Swap)*MiB, resource.BinarySI),
				},
			}
			flavor_to_resource[flavor.ID] = &rsrc
		}
		return true, nil
	})
	if err != nil {
		glog.Warningf("Failed to find compute flavors: %v", err)
		return nil, false
	}

	glog.V(3).Infof("Found %v compute flavors", len(flavor_to_resource))
	glog.V(1).Info("Claiming to support Instances")

	return &Instances{compute, flavor_to_resource}, true
}
```
And I think the nil error is thrown by this sentence:
```
nodeName, err = instances.CurrentNodeName(kcfg.Hostname)
```
Hope this can help you figure out the root cause.

**Comment by dchen1107** [comment]
@AdoHe Thanks for helping us debugging the issue. @freshfrmthehood any more updates on this one?

**Comment by AdoHe** [comment]
@dchen1107 I think the openstack cloud provider has potential bugs. I will try to figure out.

**Comment by loshkovskyi** [comment]
@freshfrmthehood, I've been using the OpenStack cloud provider for some time. The minimum working configuration should look like this (based on your config):
```
[Global]
auth-url = http://172.200.1.5/v2.0
username = nova
password = password
tenant-id = service
```
Replace `username` with `user-id` or `password` with `api-key` and you will get the same nil pointer dereference error. You can use API keys as value for `password`.

**Comment by drngsl** [comment]
@loshkovskyi , I also meet the same problem.
And my kubelet config on the minion nodes like:
/etc/default/kubelet

KUBELET_OPTS="--address=0.0.0.0 \
--port=10250 \
--hostname_override=10.0.0.13 \
--api_servers=10.0.0.15:8080 \
--logtostderr=false \
--log_dir=/var/log/kubernetes
--cloud-provider=openstack\
--cloud-config=/etc/cloud.conf\
--v=5"

/etc/cloud.conf
[Global]
auth-url=https://162.3.132.50:443/identity/v2.0
username=username
password=password
region=RegionOne1
tenant-id=a1fa87b6b770496e929685fd5f1e0e18

When I restart kubelet service, kubelet can't be restarted.https://github.com/kubernetes/kubernetes/issues/20146

**Comment by loshkovskyi** [comment]
I responded in https://github.com/kubernetes/kubernetes/issues/20146. Let's communicate in separate issues to keep things clear.

**Comment by bgrant0607** [comment]
cc @doublerr
