### ISSUE TITLE
TestForwardPortsReturnsErrorWhenAllBindsFailed panics instead of returning error

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#19417]
With the following stack trace (http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/22564/testReport/junit/(root)/Kubernetes%20e2e%20suite/Deployment_deployment_should_support_rollover/):
```
--- PASS: TestForwardPorts (0.25s)
=== RUN   TestForwardPortsReturnsErrorWhenAllBindsFailed
I0106 18:11:12.600619    7226 portforward.go:213] Forwarding from 127.0.0.1:5555 -> 5555
I0106 18:11:12.601000    7226 portforward.go:213] Forwarding from [::1]:5555 -> 5555
E0106 18:11:12.611874    7226 portforward.go:202] Unable to create listener: Error listen tcp4 127.0.0.1:5555: bind: address already in use
E0106 18:11:12.612074    7226 portforward.go:202] Unable to create listener: Error listen tcp6 [::1]:5555: bind: address already in use
W0106 18:11:12.612177    7226 portforward.go:154] Unable to listen on port 5555: All listeners failed to create with the following errors: listen tcp4 127.0.0.1:5555: bind: address already in use, listen tcp6 [::1]:5555: bind: address already in use
panic: test timed out after 5m0s

goroutine 190 [running]:
testing.startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:703 +0x16b
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:129 +0x6e

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x17f40a0, 0x1e31bc0, 0x4, 0x4, 0xc820257901)
	/tmp/workdir/go/src/testing/testing.go:562 +0xafa
testing.(*M).Run(0xc820648f10, 0x4861bf)
	/tmp/workdir/go/src/testing/testing.go:494 +0xe5
main.main()
	k8s.io/kubernetes/pkg/client/unversioned/portforward/_test/_testmain.go:60 +0x210

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1e52d60)
	/workspace/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x8c
created by github.com/golang/glog.init.1
	/workspace/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2ba

goroutine 106 [chan send, 4 minutes]:
k8s.io/kubernetes/pkg/util/httpstream/spdy.(*connection).SetIdleTimeout(0xc82013c300, 0x0)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/httpstream/spdy/connection.go:138 +0x9b
k8s.io/kubernetes/pkg/kubelet/server.ServePortForward(0x7fa9a070d710, 0xc820208580, 0xc8202de000, 0x7fa9a070d748, 0xc8202ce220, 0x1598378, 0x3, 0x1599e40, 0x3, 0x0, ...)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:796 +0x4b6
k8s.io/kubernetes/pkg/client/unversioned/portforward.fakePortForwardServer.func1(0x7fa9a070d710, 0xc820208580, 0xc8202de000)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/unversioned/portforward/portforward_test.go:253 +0x265
net/http.HandlerFunc.ServeHTTP(0xc8202566f0, 0x7fa9a070d710, 0xc820208580, 0xc8202de000)
	/tmp/workdir/go/src/net/http/server.go:1422 +0x48
net/http/httptest.(*waitGroupHandler).ServeHTTP(0xc820134260, 0x7fa9a070d710, 0xc820208580, 0xc8202de000)
	/tmp/workdir/go/src/net/http/httptest/server.go:200 +0xff
net/http.serverHandler.ServeHTTP(0xc8200e41e0, 0x7fa9a070d710, 0xc820208580, 0xc8202de000)
	/tmp/workdir/go/src/net/http/server.go:1862 +0x207
net/http.(*conn).serve(0xc8202084d0)
	/tmp/workdir/go/src/net/http/server.go:1361 +0x117d
created by net/http.(*Server).Serve
	/tmp/workdir/go/src/net/http/server.go:1910 +0x465

goroutine 155 [semacquire, 4 minutes]:
sync.runtime_Semacquire(0xc8202ec13c)
	/tmp/workdir/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc8202ec130)
	/tmp/workdir/go/src/sync/waitgroup.go:126 +0x118
net/http/httptest.(*Server).Close(0xc8202ec100)
	/tmp/workdir/go/src/net/http/httptest/server.go:168 +0x81
k8s.io/kubernetes/pkg/client/unversioned/portforward.TestForwardPortsReturnsErrorWhenAllBindsFailed(0xc8201a0000)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/unversioned/portforward/portforward_test.go:393 +0x8dc
testing.tRunner(0xc8201a0000, 0x1e31c08)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 126 [chan send, 4 minutes]:
github.com/docker/spdystream.(*Connection).shutdown(0xc820208420, 0x0)
	/workspace/kubernetes/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:700 +0x335
created by github.com/docker/spdystream.(*Connection).handleGoAwayFrame
	/workspace/kubernetes/Godeps/_workspace/src/github.com/docker/spdystream/connection.go:600 +0x24f
FAIL	k8s.io/kubernetes/pkg/client/unversioned/portforward	300.212s
```

@ncdc

**Comment by ncdc** [comment]
This is the same root cause as #19230
