### ISSUE TITLE
Crash on addon_update.go:405

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#20006]
From http://goto.google.com/k8s-test/job/kubernetes-e2e-gce/10479/

```
goroutine 1752 [running]:
k8s.io/kubernetes/test/e2e.writeRemoteFile.func1(0xc821432000, 0x1a4, 0x142, 0x1d33550, 0x15, 0xc82155d760, 0x142)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/addon_update.go:405 +0x697
created by k8s.io/kubernetes/test/e2e.writeRemoteFile
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/addon_update.go:409 +0x552
```

**Comment by zmerlynn** [comment]
And http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/10481/consoleFull

**Comment by zmerlynn** [comment]
Looks like it's crashed the main `gce` test twice now, raising to P0.

**Comment by mikedanese** [comment]
I believe #20024  will fix this

**Comment by mikedanese** [comment]
#20024 is merged but we can leave open for a day or two to make sure.

**Comment by davidopp** [comment]
Please reopen if the problem returns.
