### ISSUE TITLE
Kubelet crashes with 500 response to health check during e2e

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#20173]
In this e2e log:

```
gsutil cp gs://kubernetes-jenkins/logs/kubernetes-e2e-gce-parallel/14712/artifacts/104.197.47.216:22-kubelet.log .
```

The kubelet crashes three times while handling a healthz check:
1)

```
I0120 22:15:32.616748    3461 server.go:1050] GET /healthz: (78.647µs) 500
goroutine 2587 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc2091c1960, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:214 +0xa6
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc2091c1960, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:193 +0x32
net/http.Error(0x7fd54a993178, 0xc2091c1960, 0xc208ec56e0, 0x58, 0x1f4)
        /usr/src/go/src/net/http/server.go:1274 +0x9a
k8s.io/kubernetes/pkg/healthz.func·002(0x7fd54a993178, 0xc2091c1960, 0xc2089651e0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/healthz/healthz.go:109 +0x46e
net/http.HandlerFunc.ServeHTTP(0xc2082f4580, 0x7fd54a993178, 0xc2091c1960, 0xc2089651e0)
        /usr/src/go/src/net/http/server.go:1265 +0x41
github.com/emicklei/go-restful.func·011(0x7fd54a993178, 0xc2091c1960, 0xc2089651e0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:278 +0xd3
net/http.HandlerFunc.ServeHTTP(0xc2082b9a60, 0x7fd54a993178, 0xc2091c1960, 0xc2089651e0)
        /usr/src/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc2082fc720, 0x7fd54a993178, 0xc2091c1960, 0xc2089651e0)
        /usr/src/go/src/net/http/server.go:1541 +0x17d
github.com/emicklei/go-restful.Container.ServeHTTP(0x0, 0x0, 0x0, 0xc20823da80, 0xb, 0x10, 0xc2082fc720, 0x0, 0x2bec1e0, 0x0, ...)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:264 +0x4f
k8s.io/kubernetes/pkg/kubelet/server.(*filteringContainer).ServeHTTP(0xc2082b99e0, 0x7fd54a993178, 0xc2091c1960, 0xc2089651e0)
        <autogenerated>:30 +0x8a
k8s.io/kubernetes/pkg/kubelet/server.(*Server).ServeHTTP(0xc2082fc690, 0x7fd54a993140, 0xc208343c20, 0xc2089651e0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:1049 +0x13d
net/http.serverHandler.ServeHTTP(0xc208271c20, 0x7fd54a993140, 0xc208343c20, 0xc2089651e0)
        /usr/src/go/src/net/http/server.go:1703 +0x19a
net/http. [[curl/7.26.0] 127.0.0.1:39312]
```

2)

```
I0120 22:21:14.230768   18047 server.go:1050] GET /healthz: (75.988µs) 500
goroutine 243 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc208810460, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:214 +0xa6
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc208810460, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:193 +0x32
net/http.Error(0x7f5a66b2b5d0, 0xc208810460, 0xc208812000, 0x58, 0x1f4)
        /usr/src/go/src/net/http/server.go:1274 +0x9a
k8s.io/kubernetes/pkg/healthz.func·002(0x7f5a66b2b5d0, 0xc208810460, 0xc208750750)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/healthz/healthz.go:109 +0x46e
net/http.HandlerFunc.ServeHTTP(0xc2084d2d70, 0x7f5a66b2b5d0, 0xc208810460, 0xc208750750)
        /usr/src/go/src/net/http/server.go:1265 +0x41
github.com/emicklei/go-restful.func·011(0x7f5a66b2b5d0, 0xc208810460, 0xc208750750)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:278 +0xd3
net/http.HandlerFunc.ServeHTTP(0xc2082e8ea0, 0x7f5a66b2b5d0, 0xc208810460, 0xc208750750)
        /usr/src/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc2082ed5f0, 0x7f5a66b2b5d0, 0xc208810460, 0xc208750750)
        /usr/src/go/src/net/http/server.go:1541 +0x17d
github.com/emicklei/go-restful.Container.ServeHTTP(0x0, 0x0, 0x0, 0xc2083ac380, 0xb, 0x10, 0xc2082ed5f0, 0x0, 0x2bec1e0, 0x0, ...)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:264 +0x4f
k8s.io/kubernetes/pkg/kubelet/server.(*filteringContainer).ServeHTTP(0xc2082e8e20, 0x7f5a66b2b5d0, 0xc208810460, 0xc208750750)
        <autogenerated>:30 +0x8a
k8s.io/kubernetes/pkg/kubelet/server.(*Server).ServeHTTP(0xc2082ed560, 0x7f5a66b2b598, 0xc2087b3ea0, 0xc208750750)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:1049 +0x13d
net/http.serverHandler.ServeHTTP(0xc20842e300, 0x7f5a66b2b598, 0xc2087b3ea0, 0xc208750750)
        /usr/src/go/src/net/http/server.go:1703 +0x19a
net/http.( [[curl/7.26.0] 127.0.0.1:39454]
```

3)

```
I0120 22:26:55.834103   18779 server.go:1050] GET /healthz: (74.144µs) 500
goroutine 244 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc2080ef500, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:214 +0xa6
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc2080ef500, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:193 +0x32
net/http.Error(0x7f211e4ddec8, 0xc2080ef500, 0xc2085c8660, 0x58, 0x1f4)
        /usr/src/go/src/net/http/server.go:1274 +0x9a
k8s.io/kubernetes/pkg/healthz.func·002(0x7f211e4ddec8, 0xc2080ef500, 0xc2086b1d40)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/healthz/healthz.go:109 +0x46e
net/http.HandlerFunc.ServeHTTP(0xc2084b6040, 0x7f211e4ddec8, 0xc2080ef500, 0xc2086b1d40)
        /usr/src/go/src/net/http/server.go:1265 +0x41
github.com/emicklei/go-restful.func·011(0x7f211e4ddec8, 0xc2080ef500, 0xc2086b1d40)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:278 +0xd3
net/http.HandlerFunc.ServeHTTP(0xc20849ad60, 0x7f211e4ddec8, 0xc2080ef500, 0xc2086b1d40)
        /usr/src/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc208250a20, 0x7f211e4ddec8, 0xc2080ef500, 0xc2086b1d40)
        /usr/src/go/src/net/http/server.go:1541 +0x17d
github.com/emicklei/go-restful.Container.ServeHTTP(0x0, 0x0, 0x0, 0xc208242580, 0xb, 0x10, 0xc208250a20, 0x0, 0x2bec1e0, 0x0, ...)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:264 +0x4f
k8s.io/kubernetes/pkg/kubelet/server.(*filteringContainer).ServeHTTP(0xc20849ace0, 0x7f211e4ddec8, 0xc2080ef500, 0xc2086b1d40)
        <autogenerated>:30 +0x8a
k8s.io/kubernetes/pkg/kubelet/server.(*Server).ServeHTTP(0xc208250990, 0x7f211e4dde90, 0xc2088214a0, 0xc2086b1d40)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:1049 +0x13d
net/http.serverHandler.ServeHTTP(0xc2082ab740, 0x7f211e4dde90, 0xc2088214a0, 0xc2086b1d40)
        /usr/src/go/src/net/http/server.go:1703 +0x19a
net/http.( [[curl/7.26.0] 127.0.0.1:39597]
```

**Comment by erictune** [comment]
This caused at least 1 test flake: #19898

**Comment by erictune** [comment]
All 3 stack traces are the same functions and files.

**Comment by erictune** [comment]
Another nodes from the same test build also shows this crash, so I think it is unlikely to be a single bad node.

**Comment by erictune** [comment]
I see that the code of handleRootHealthz in pkg/healthz/healthz.go is trying to return a verbose message about what check failed.  But I cannot see how to find this string in either the kubelet or supervisord logs.

I can't tell if (1) the http response does include the verbose error message but supervisord needs to be taught to log it, or (2) the http response never gets sent because the default behavior of a 500 is to panic,  and this panic needs to be recovered from.

**Comment by erictune** [comment]
I'm done with this issue.  Letting node team decide how to proceed.

**Comment by erictune** [comment]
So, 2 problems need to be fixed:

- kubelet failed healthz a bunch
- you can't tell which check failed from test logs.

**Comment by erictune** [comment]
@kubernetes/goog-node

**Comment by vishh** [comment]
FYI: Kubelet is configured to dump stack traces for all failing REST API calls. 

The fact that the root cause is not visible/evident is an issue. I can look into it.

**Comment by erictune** [comment]
@vishh it dumps stacks for all 500s.  For things like `/stats`, it appears to recover.  But it does not appear to recover from a 500 on the `/healthz` endpoint.  So I think that is a second issue.

**Comment by erictune** [comment]
Or maybe it does recover but then gets killed by `supervisord`.  Anyhow, thanks for offering to look at this.

**Comment by yujuhong** [comment]
> Or maybe it does recover but then gets killed by supervisord.

I think that's what happened.


```console
$ curl http://localhost:10255/healthz
[+]ping ok
[-]syncloop failed: Sync Loop took longer than expected.
healthz check failed
```
`pkg/healthz` will return 500 in this case, and as @vishh says, kubelet will dump stack trace in this case. 

The stack trace here is not helpful at all for identifying problems though. I think our handler should also log an error message for introspection.
