### ISSUE TITLE
crash with kubectl get -o=custom-columns 

### ISSUE THREAD

**Issue by therc** [kubernetes/kubernetes#20211]
I followed  the instructions and all I got was this lousy t-sh...  I mean, panic. Same happens with a configmap, etc.

```
$ kubectl get services -o=custom-columns=NAME:.metadata.name,RSRC:.metadata.resourceVersion
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x66bf95]

goroutine 1 [running]:
k8s.io/kubernetes/pkg/kubectl.(*CustomColumnsPrinter).printOneObject(0xc82022e6c0, 0x7f66d53ad4e0, 0xc820227680, 0xc82026dd20, 0x2, 0x2, 0x7f66d53ad430, 0xc8201dd400, 0x0, 0x0)
	/home/rudi/k8s/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/custom_column_printer.go:195 +0x185
k8s.io/kubernetes/pkg/kubectl.(*CustomColumnsPrinter).PrintObj(0xc82022e6c0, 0x7f66d53a5370, 0xc820288ae0, 0x7f66d53a34d8, 0xc820026010, 0x0, 0x0)
	/home/rudi/k8s/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/custom_column_printer.go:178 +0x792
k8s.io/kubernetes/pkg/kubectl/cmd.RunGet(0xc8200dc540, 0x7f66d53a34d8, 0xc820026010, 0xc820200200, 0xc820211140, 0x1, 0x2, 0xc8201eeb80, 0x0, 0x0)
	/home/rudi/k8s/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:232 +0xc39
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdGet.func1(0xc820200200, 0xc820211140, 0x1, 0x2)
	/home/rudi/k8s/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:93 +0x7d
github.com/spf13/cobra.(*Command).execute(0xc820200200, 0xc820211020, 0x2, 0x2, 0x0, 0x0)
	/home/rudi/k8s/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:572 +0x869
github.com/spf13/cobra.(*Command).ExecuteC(0xc8200f5e00, 0xc820200200, 0x0, 0x0)
	/home/rudi/k8s/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x54e
github.com/spf13/cobra.(*Command).Execute(0xc8200f5e00, 0x0, 0x0)
	/home/rudi/k8s/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x2d
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
	/home/rudi/k8s/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:28 +0xf0
main.main()
	/home/rudi/k8s/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:28 +0x28
```

**Comment by therc** [comment]
The [line where the crash happens](https://github.com/kubernetes/kubernetes/blame/master/pkg/kubectl/custom_column_printer.go#L195) is from a recent change by @smarterclayton:

https://github.com/kubernetes/kubernetes/commit/2fd38a7dc022c28f05403355061d521d8f124da3

**Comment by smarterclayton** [comment]
Decoder wasn't passed in, and tests don't validate custom columns path.

**Comment by smarterclayton** [comment]
Also, #17922 broke ExtractList for RawExtension objects.  Fixing that now
