### ISSUE TITLE
Frequent Apiserver 500 on DELETE pods associated with Key not found from etcd.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#20336]
Seen in a customer's apiserver log:

```
I0128 22:46:04.428165       6 handlers.go:131] DELETE /api/v1/namespaces/default/pods/XXX-6ew2h-kyh0b: (3.144843ms) 500
goroutine 1415 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc209793b00, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:188 +0x9a
k8s.io/kubernetes/pkg/apiserver.(*baseTimeoutWriter).WriteHeader(0xc2098bc1a0, 0x1f4)
      /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:237 +0xba
k8s.io/kubernetes/pkg/apiserver.writeJSON(0x1f4, 0x7f14f52c43a8, 0xc2080db6c0, 0x7f14f52c4ad0, 0xc209d49b80, 0x7f14f5112dd0, 0xc209813698, 0xc20804ea01)          
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:389 +0x89
k8s.io/kubernetes/pkg/apiserver.errorJSON(0x7f14f5112f98, 0xc20920daa0, 0x7f14f52c43a8, 0xc2080db6c0, 0x7f14f5112dd0, 0xc209813698, 0x0)
     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:416 +0xab
k8s.io/kubernetes/pkg/apiserver.func·034(0xc208b5acf0, 0xc209793d40)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:564 +0xacb
github.com/emicklei/go-restful.func·009(0xc208b5acf0, 0xc209793d40)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:244 +0x41
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc208b5aff0, 0xc208b5acf0, 0xc209793d40)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
k8s.io/kubernetes/pkg/apiserver.func·003(0xc208b5acf0, 0xc209793d40, 0xc208b5aff0)
       /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:62 +0x8b
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc208b5aff0, 0xc208b5acf0, 0xc209793d40)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19 +0x84
github.com/emicklei/go-restful.(*Container).dispatch(0xc20826e2d0, 0x7f14f5112dd0, 0xc209813698, 0xc208e05c70)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container [[kube-controller-manager/v1.1.4 (linux/amd64) kubernetes/a5949fe] 127.0.0.1:43835]
```

Version is 1.1.4

**Comment by erictune** [comment]
Error is coming from DeleteResource: https://github.com/kubernetes/kubernetes/blob/v1.1.4/pkg/apiserver/resthandler.go#L564

**Comment by erictune** [comment]
I suspect that debugging will be difficult without repro.  So, next step is to make changes so more information is visible next time.

**Comment by erictune** [comment]
This appears to happen about 2000 times per day for the last 4 days.

**Comment by erictune** [comment]
The stack trace appears to be always/usually preceded by:
```
 E0129 19:10:20.678055       5 errors.go:62] apiserver received an error that is not an unversioned.Status: 100: Key not found (/registry/pods/default/XXXXX) [219722]
```
where XXXX varies and is redacted for customer privacy.
 
It is followed by a line like this:
```
I0129 19:10:20.678218       5 handlers.go:131] DELETE /api/v1/namespaces/default/pods/XXXX: (6.767515ms) 500
```

However, it seems like occasionally, a `Key not found` is followed by a 200 instead, though I can't be sure if that is some other goroutine that is mixed into the logs.
