### ISSUE TITLE
v1.2 clients can't propagate errors from v1.1 API servers

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#20459]
Per https://github.com/kubernetes/kubernetes/issues/19715#issuecomment-178275745, it looks like a v1.1 cluster can't propagate certain error messages to a v1.2 client.

@kubernetes/goog-csi for triage.

**Comment by ihmccreery** [comment]
In the API server logs I see:

```
E0202 00:39:48.964503       5 errors.go:62] apiserver received an error that is not an unversioned.Status: no kind "DeleteOptions" is registered for version "extensions/v1beta1"
I0202 00:39:48.964762       5 handlers.go:131] DELETE /apis/extensions/v1beta1/namespaces/e2e-tests-kubectl-9nz04/jobs/run-test: (632.034µs) 500
goroutine 14540 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc20a989d40, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:188 +0x9a
k8s.io/kubernetes/pkg/apiserver.(*baseTimeoutWriter).WriteHeader(0xc2097c06c0, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:237 +0xba
k8s.io/kubernetes/pkg/apiserver.writeJSON(0x1f4, 0x7eff307b8488, 0xc20801e820, 0x7eff307b8bb0, 0xc209d09b80, 0x7eff306014a8, 0xc2081178d0, 0xc20947fa01)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:389 +0x89
k8s.io/kubernetes/pkg/apiserver.errorJSON(0x7eff30601550, 0xc20947fb00, 0x7eff307b8488, 0xc20801e820, 0x7eff306014a8, 0xc2081178d0, 0x7eff30601550)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:416 +0xab
k8s.io/kubernetes/pkg/apiserver.func·034(0xc20947f950, 0xc20a989ec0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:544 +0x4ff
github.com/emicklei/go-restful.func·009(0xc20947f950, 0xc20a989ec0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:244 +0x41
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20947fa10, 0xc20947f950, 0xc20a989ec0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
k8s.io/kubernetes/pkg/apiserver.func·003(0xc20947f950, 0xc20a989ec0, 0xc20947fa10)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:62 +0x8b
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20947fa10, 0xc20947f950, 0xc20a989ec0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19 +0x84
github.com/emicklei/go-restful.(*Container).dispatch(0xc208240bd0, 0x7eff306014a8, 0xc2081178d0, 0xc20935d1e0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restf [[e2e.test/v1.2.0 (linux/amd64) kubernetes/174521e] 74.125.59.6:55866]
```

**Comment by ihmccreery** [comment]
I'm digging into this; looks like `pkg/conversion/error.go` isn't raising `pkg/api/errors` properly?

**Comment by smarterclayton** [comment]
resthandler was probably passing the errors directly back, rather than wrapping an IsNotRegistered error with a valid api.Status error.

**Comment by ihmccreery** [comment]
After adding some logs, it looks like the client doesn't like that it's getting back an object that doesn't have an `apiVersion`:

```
I0202 16:28:05.873656   26323 request.go:840] Response Body: {
  "kind": "Status",
  "metadata": {},
  "status": "Failure",
  "message": "no kind \"DeleteOptions\" is registered for version \"extensions/v1beta1\"",
  "code": 500
}
I0202 16:28:05.873774   26323 request.go:846] Object 'apiVersion' is missing in '{
  "kind": "Status",
  "metadata": {},
  "status": "Failure",
  "message": "no kind \"DeleteOptions\" is registered for version \"extensions/v1beta1\"",
  "code": 500
}'
I0202 16:28:05.873810   26323 request.go:901] Response Body: {
  "kind": "Status",
  "metadata": {},
  "status": "Failure",
  "message": "no kind \"DeleteOptions\" is registered for version \"extensions/v1beta1\"",
  "code": 500
}
[AfterEach] Simple pod
[...]
```

cc @caesarxuchao

**Comment by ihmccreery** [comment]
@caesarxuchao Do we expect the apiserver (v1.1) to be providing an `apiVersion`, or is the client (v1.2) doing something wrong here?

**Comment by caesarxuchao** [comment]
v1.1 apiserver does not provide an apiVersion if it's responding to a request of extensions resource, so it probably is the v1.2 client's fault.

**Comment by ihmccreery** [comment]
Looks like `func (s unstructuredJSONScheme) Decode` expects there to be an `unstruct.APIVersion` (https://github.com/kubernetes/kubernetes/blob/master/pkg/runtime/unstructured.go#L53).  I'll pass it off to you to decide what should be done about this, but we definitely do want v1.2 clients to be able to take errors from v1.1 apiservers.

**Comment by caesarxuchao** [comment]
Thank you @ihmccreery for digging into this. @smarterclayton, I think before returning an error at L53, we should check if unstruct.Kind belongs to the unversioned group, if so, we should not return the `NewMissingVersionErr`, what do you think?

**Comment by smarterclayton** [comment]
Agree.  It's horrifying, but we have to roll with the punches on backcompat.

**Comment by ihmccreery** [comment]
cc @kubernetes/kube-api If that works for you all, I will send a PR.

**Comment by bgrant0607** [comment]
@ihmccreery SGTM. Please add an explanatory comment.

**Comment by ihmccreery** [comment]
@caesarxuchao I'm having quite a lot of difficulty actually doing what you said; I'm not familiar enough with this code to know where to get a scheme to check if it's unversioned.  Assigning to you to actually write the code.

**Comment by caesarxuchao** [comment]
I'll make a fix. cc @lavalamp

**Comment by caesarxuchao** [comment]
It's actually not the `unstructuredJSONScheme` to be blamed. Sent #20674 to fix.

**Comment by lavalamp** [comment]
Fix looks good to me.
