### ISSUE TITLE
unit test flake: pkg/proxy/config fails with panic: test timed out after 5m0s

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#20612]
Failed for https://github.com/kubernetes/kubernetes/pull/20532

Logs can be found at `kubernetes-jenkins/pr-logs/pull/20532/kubernetes-pull-test-unit-integration/12407`

Copying the relevant logs here:

```
=== RUN   TestNewServiceAddedAndNotified
panic: test timed out after 5m0s

goroutine 34 [running]:
testing.startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:703 +0x16b
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:129 +0x6e

goroutine 1 [chan receive]:
testing.RunTests(0x18aa9e0, 0x1f07d40, 0x8, 0x8, 0x20000028d3001)
	/tmp/workdir/go/src/testing/testing.go:562 +0xafa
testing.(*M).Run(0xc8200c5ef0, 0x18aedd0)
	/tmp/workdir/go/src/testing/testing.go:494 +0xe5
main.main()
	k8s.io/kubernetes/pkg/proxy/config/_test/_testmain.go:70 +0x210

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 19 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1f27be0)
	/workspace/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x8c
created by github.com/golang/glog.init.1
	/workspace/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2ba

goroutine 30 [chan send]:
k8s.io/kubernetes/pkg/proxy/config.newServicesSourceApiFromLW.func1(0x28d2f88, 0x0, 0x0)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/config/api.go:43 +0x304
k8s.io/kubernetes/pkg/client/cache.(*UndeltaStore).Replace(0xc82015d620, 0x28d2f88, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/undelta_store.go:73 +0x18a
k8s.io/kubernetes/pkg/client/cache.(*Reflector).syncWith(0xc82011d860, 0x28d2f88, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:306 +0x30a
k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch(0xc82011d860, 0xc82008b2c0, 0x0, 0x0)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:251 +0xa49
k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run.func1()
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:160 +0x54
k8s.io/kubernetes/pkg/util.Until.func1(0xc8202319b0)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:64 +0x59
k8s.io/kubernetes/pkg/util.Until(0xc8202319b0, 0x3b9aca00, 0xc82008b2c0)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:65 +0x7e
created by k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:160 +0xe5

goroutine 6 [chan receive]:
k8s.io/kubernetes/pkg/proxy/config_test.(*ServiceHandlerMock).ValidateServices(0xc820012b50, 0xc8202502d0, 0xc820254160, 0x1, 0x1)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/config/config_test.go:70 +0xbd
k8s.io/kubernetes/pkg/proxy/config_test.TestNewServiceAddedAndNotified(0xc8202502d0)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/config/config_test.go:155 +0x3d9
testing.tRunner(0xc8202502d0, 0x1f07d70)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4

goroutine 5 [chan send]:
k8s.io/kubernetes/pkg/proxy/config.newEndpointsSourceApiFromLW.func1(0x28d2f88, 0x0, 0x0)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/config/api.go:56 +0x304
k8s.io/kubernetes/pkg/client/cache.(*UndeltaStore).Replace(0xc82000e280, 0x28d2f88, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/undelta_store.go:73 +0x18a
k8s.io/kubernetes/pkg/client/cache.(*Reflector).syncWith(0xc8200160a0, 0x28d2f88, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:306 +0x30a
k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch(0xc8200160a0, 0xc82008b2c0, 0x0, 0x0)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:251 +0xa49
k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run.func1()
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:160 +0x54
k8s.io/kubernetes/pkg/util.Until.func1(0xc820012290)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:64 +0x59
k8s.io/kubernetes/pkg/util.Until(0xc820012290, 0x3b9aca00, 0xc82008b2c0)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:65 +0x7e
created by k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:160 +0xe5

goroutine 7 [chan receive]:
k8s.io/kubernetes/pkg/proxy/config.watchForUpdates(0xc82000a600, 0x7f7cbf0ce2a8, 0xc82000a570, 0xc8200106c0)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:288 +0x44
created by k8s.io/kubernetes/pkg/proxy/config.NewServiceConfig
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:194 +0x32c

goroutine 8 [chan receive]:
k8s.io/kubernetes/pkg/util/config.(*Mux).listen(0xc82000a5d0, 0x163fb08, 0x3, 0xc820010720)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/config/config.go:82 +0x62
k8s.io/kubernetes/pkg/util/config.(*Mux).Channel.func1()
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/config/config.go:77 +0x56
k8s.io/kubernetes/pkg/util.Until.func1(0xc82000a630)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:64 +0x59
k8s.io/kubernetes/pkg/util.Until(0xc82000a630, 0x0, 0xc82008b2c0)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:65 +0x7e
created by k8s.io/kubernetes/pkg/util/config.(*Mux).Channel
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/config/config.go:77 +0x349

goroutine 9 [chan receive]:
k8s.io/kubernetes/pkg/proxy/config.(*ServiceConfig).Channel.func1(0xc820010780, 0xc820010720)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:209 +0x77
created by k8s.io/kubernetes/pkg/proxy/config.(*ServiceConfig).Channel
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:213 +0xac
FAIL	k8s.io/kubernetes/pkg/proxy/config	300.200s
```

**Comment by nikhiljindal** [comment]
cc @bprashanth since https://github.com/kubernetes/kubernetes/pull/20471 seems to be the latest PR affecting that code.

**Comment by bprashanth** [comment]
Hmm, this is probably that pr. i ran stress unittest locally and didn't hit it. looking.

**Comment by freehan** [comment]
also failed for #20600
