### ISSUE TITLE
jenkins: job builder updater fails to create "kubernetes-upgrade-gce-1.1-master" job

### ISSUE THREAD

**Issue by colemickens** [kubernetes/kubernetes#21778]
I'm working on getting Jenkins running CI jobs for Azure. I want to reuse the existing built infrastructure (I like the declarative, auto-updating job builder stuff).

I'm trying to bootstrap the existing job (and document it a bit more as I go).

I created a Jenkins machine (just one for now). Pulled a Kubernetes branch down. Created a `jenkins_jobs.ini` in the `kubernetes/` root directory and executed `./hack/jenkins/update_jobs.sh`.

This is the bottom of the output:
```
INFO:jenkins_jobs.builder:Reconfiguring jenkins job kubernetes-test-linkchecker
INFO:jenkins_jobs.builder:Reconfiguring jenkins job kubernetes-update-jenkins-jobs
INFO:jenkins_jobs.builder:Creating jenkins job kubernetes-upgrade-gce-1.1-master
Traceback (most recent call last):
  File "/usr/local/bin/jenkins-jobs", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jenkins_jobs/cmd.py", line 172, in main
    execute(options, config)
  File "/usr/local/lib/python2.7/dist-packages/jenkins_jobs/cmd.py", line 331, in execute
    options.names)
  File "/usr/local/lib/python2.7/dist-packages/jenkins_jobs/builder.py", line 362, in update_job
    self.jenkins.update_job(job.name, job.output().decode('utf-8'))
  File "/usr/local/lib/python2.7/dist-packages/jenkins_jobs/builder.py", line 144, in update_job
    self.jenkins.create_job(job_name, xml)
  File "/usr/local/lib/python2.7/dist-packages/jenkins/__init__.py", line 852, in create_job
    config_xml.encode('utf-8'), DEFAULT_HEADERS))
  File "/usr/local/lib/python2.7/dist-packages/jenkins/__init__.py", line 358, in jenkins_open
    e.code, e.msg)
jenkins.JenkinsException: Error in request. Possibly authentication failed [500]: Server Error
INFO:jenkins_jobs.builder:Cache saved
```

I'm investigating this more, wanted to get this out there early in case someone has seen it.

**Comment by colemickens** [comment]
Looks like I need to install multijob project:

```
INFO:jenkins_jobs.builder:Creating jenkins job kubernetes-upgrade-gce-1.1-master
Traceback (most recent call last):
  File "/usr/local/bin/jenkins-jobs", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jenkins_jobs/cmd.py", line 172, in main
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Unable to read /var/lib/jenkins/jobs/kubernetes-upgrade-gce-1.1-master/config.xml
        at hudson.XmlFile.read(XmlFile.java:144)
        at hudson.model.Items.load(Items.java:326)
        at hudson.model.ItemGroupMixIn$4.call(ItemGroupMixIn.java:271)
        at hudson.model.ItemGroupMixIn$4.call(ItemGroupMixIn.java:269)
        at hudson.model.Items.whileUpdatingByXml(Items.java:96)
        at hudson.model.ItemGroupMixIn.createProjectFromXML(ItemGroupMixIn.java:269)
        at hudson.model.ItemGroupMixIn.createTopLevelItem(ItemGroupMixIn.java:191)
        at jenkins.model.Jenkins.doCreateItem(Jenkins.java:3098)
        at jenkins.model.Jenkins.doCreateItem(Jenkins.java:306)
        ... 53 more
Caused by: com.thoughtworks.xstream.mapper.CannotResolveClassException: com.tikal.jenkins.plugins.multijob.MultiJobProject
        at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:79)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
        at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:55)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
        at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(PackageAliasingMapper.java:88)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
        at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:79)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
        at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.java:74)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
        at com.thoughtworks.xstream.mapper.SecurityMapper.realClass(SecurityMapper.java:71)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
        at hudson.util.XStream2$CompatibilityMapper.realClass(XStream2.java:280)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
        at hudson.util.xstream.MapperDelegate.realClass(MapperDelegate.java:43)
        at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
        at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:48)
        at com.thoughtworks.xstream.core.util.HierarchicalStreams.readClassType(HierarchicalStreams.java:29)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:133)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1189)
        at hudson.util.XStream2.unmarshal(XStream2.java:113)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1173)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1053)
        at hudson.XmlFile.read(XmlFile.java:142)
        ... 61 more
```

**Comment by colemickens** [comment]
That did the trick. Will document in a PR.
