### ISSUE TITLE
Fluentd-gcp 1.16 panic

### ISSUE THREAD

**Issue by ernestoalejo** [kubernetes/kubernetes#21811]
I'm using fluentd-gcp, and I have updated it manually to the latest version the repo has (`gcr.io/google_containers/fluentd-gcp:1.16`). Today it started to throw panics and it's not logging anything to Cloud Console from that node.

```
2016-02-23 23:42:56 +0000 [warn]: pattern not match: " - exit status 1"
2016-02-23 23:43:26 +0000 [warn]: pattern not match: " - exit status 1"
2016-02-23 23:43:56 +0000 [warn]: pattern not match: " - exit status 1"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "goroutine 5893402 [running]:"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc20a6047e0, 0x1f4)"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:214 +0xa6"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc20a6047e0, 0x1f4)"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:193 +0x32"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "github.com/emicklei/go-restful.(*Response).WriteHeader(0xc20a89cae0, 0x1f4)"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "\t/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/response.go:191 +0x48"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "github.com/emicklei/go-restful.(*Response).WriteErrorString(0xc20a89cae0, 0x1f4, 0xc20a89d0e0, 0x56, 0x0, 0x0)"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "\t/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/response.go:180 +0x128"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "github.com/emicklei/go-restful.(*Response).WriteError(0xc20a89cae0, 0x1f4, 0x7f955d5810d8, 0xc20ab9fb30, 0x0, 0x0)"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "\t/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/response.go:165 +0xa8"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "k8s.io/kubernetes/pkg/kubelet/server.(*Server).getContainerLogs(0xc2084067e0, 0xc209e7f770, 0xc20a89cae0)"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:460 +0x14d5"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "k8s.io/kubernetes/pkg/kubelet/server.*Server.(k8s.io/kubernetes/pkg/kubelet/server.getContainerLogs)\xC2\xB7fm(0xc209e7f770, 0xc20a89cae0)"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:316 +0x3b"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "github.com/emicklei/go-restful.(*Container).dispatch(0xc2082be510, 0x7f955d3c8d68, 0xc20a6047e0, 0xc209ec3040)"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "\t/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:249 +0xf5e"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "github.com/emicklei/go-restful.*Container.(github.com/emicklei/go-restful.dispatch)\xC2\xB7fm(0x7f955d3c8d68, 0xc20a6047e0, 0xc209ec3040)"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "\t/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:95 +0x45"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "net/http.HandlerFunc.ServeHTTP(0xc208557b10, 0x7f955d3c8d68, 0xc20a6047e0, 0xc209ec3040)"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "\t/usr/src/go/src/net/http/server.go:1265 +0x41"
2016-02-23 23:44:02 +0000 [warn]: pattern not match: "net/http. [[Go 1.1 package http] 10.240.0.2:48888]"
2016-02-23 23:44:26 +0000 [warn]: pattern not match: " - exit status 1"
2016-02-23 23:44:56 +0000 [warn]: pattern not match: " - exit status 1"
2016-02-23 23:45:26 +0000 [warn]: pattern not match: " - exit status 1"
2016-02-23 23:45:44 +0000 [warn]: pattern not match: "/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/util.go:76"
2016-02-23 23:45:44 +0000 [warn]: pattern not match: "/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/util.go:64"
2016-02-23 23:45:44 +0000 [warn]: pattern not match: "/usr/src/go/src/runtime/asm_amd64.s:402"
2016-02-23 23:45:44 +0000 [warn]: pattern not match: "/usr/src/go/src/runtime/panic.go:387"
2016-02-23 23:45:44 +0000 [warn]: pattern not match: "/usr/src/go/src/runtime/panic.go:42"
2016-02-23 23:45:44 +0000 [warn]: pattern not match: "/usr/src/go/src/runtime/sigpanic_unix.go:26"
2016-02-23 23:45:44 +0000 [warn]: pattern not match: "/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/util/format/pod.go:33"
2016-02-23 23:45:44 +0000 [warn]: pattern not match: "/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/status/manager.go:414"
2016-02-23 23:45:44 +0000 [warn]: pattern not match: "/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/status/manager.go:330"
2016-02-23 23:45:44 +0000 [warn]: pattern not match: "/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/status/manager.go:339"
2016-02-23 23:45:44 +0000 [warn]: pattern not match: "/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/status/manager.go:132"
2016-02-23 23:45:44 +0000 [warn]: pattern not match: "/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/util.go:126"
2016-02-23 23:45:44 +0000 [warn]: pattern not match: "/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/util.go:127"
2016-02-23 23:45:44 +0000 [warn]: pattern not match: "/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/util.go:109"
2016-02-23 23:45:44 +0000 [warn]: pattern not match: "/usr/src/go/src/runtime/asm_amd64.s:2232"
2016-02-23 23:45:56 +0000 [warn]: pattern not match: " - exit status 1"
2016-02-23 23:46:26 +0000 [warn]: pattern not match: " - exit status 1"
2016-02-23 23:46:56 +0000 [warn]: pattern not match: " - exit status 1"
2016-02-23 23:47:26 +0000 [warn]: pattern not match: " - exit status 1"
2016-02-23 23:47:56 +0000 [warn]: pattern not match: " - exit status 1"
2016-02-23 23:48:26 +0000 [warn]: pattern not match: " - exit status 1"
```

**Comment by a-robinson** [comment]
Is there really nothing being logged from that node to the cloud console anymore?

I tracked down the warning messages to a problem in our fluentd config's attempt to parse the logs from the kubernetes components (#22091), but the stack trace there actually appears to be from either the kube-apiserver or kubelet logs.

**Comment by ernestoalejo** [comment]
Oops, sorry. There were two containers with similar names but one of them was not active any more and I took the wrong one as a reference (just a coincidence it was stopped almost at the same time). You are right, the only problem here is the warning.

**Comment by a-robinson** [comment]
Thanks for the confirmation! #22091 will fix this then.
