### ISSUE TITLE
e2e flake: not all pods starting in time

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#21940]
Coming up a bunch today:
https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce/12207/
```
Feb 24 14:44:46.585: INFO: At 2016-02-24 14:35:33 -0800 PST - event for monitoring-influxdb-grafana-v3-fyy2c: {kubelet jenkins-e2e-minion-bu2m} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): Cannot start container 0925337af9de6b234ac2edecdcd3e5536f8853b8467ec63ba4fcf53dd103c810: failed to create endpoint k8s_POD.444e2470_monitoring-influxdb-grafana-v3-fyy2c_kube-system_71d9a704-db46-11e5-95a6-42010af00002_46e1ec03 on network bridge: Bind for 0.0.0.0:8086 failed: port is already allocated\n"
```
https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce/12205/
```
Feb 24 14:04:40.690: INFO: At 2016-02-24 13:56:49 -0800 PST - event for kube-dns-v10-wjsgu: {kubelet jenkins-e2e-minion-sv8p} Killing: Killing container with docker id d15bb06ce583: pod "kube-dns-v10-wjsgu_kube-system(920f73a2-db40-11e5-affa-42010af00002)" container "skydns" is unhealthy, it will be killed and re-created.
Feb 24 14:04:40.690: INFO: At 2016-02-24 13:57:02 -0800 PST - event for kibana-logging-v1-qhv0i: {kubelet jenkins-e2e-minion-sv8p} FailedSync: Error syncing pod, skipping: failed to "StartContainer" for "kibana-logging" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=kibana-logging pod=kibana-logging-v1-qhv0i_kube-system(91f98f87-db40-11e5-affa-42010af00002)"
```
https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-e2e-gke/1662/
```
Running Suite: Kubernetes e2e suite
===================================
Random Seed: 1456350153 - Will randomize all specs
Will run 140 of 237 specs

Running in parallel across 30 nodes

Feb 24 13:42:36.010: INFO: >>> testContext.KubeConfig: /var/lib/jenkins/jobs/kubernetes-e2e-gke/workspace/.kube/config

Feb 24 13:42:36.231: INFO: Waiting up to 10m0s for all pods (need at least 0) in namespace 'kube-system' to be running and ready
Feb 24 13:42:36.308: INFO: The status of Pod heapster-v14-a1u2z is Pending, waiting for it to be either Running or Failed
Feb 24 13:42:36.308: INFO: The status of Pod kube-dns-v10-e16xm is Pending, waiting for it to be either Running or Failed
Feb 24 13:42:36.308: INFO: The status of Pod kubernetes-dashboard-v0.1.0-1632u is Pending, waiting for it to be either Running or Failed
Feb 24 13:42:36.308: INFO: The status of Pod l7-lb-controller-v0.5.2-by8kh is Pending, waiting for it to be either Running or Failed
Feb 24 13:42:36.308: INFO: 6 / 10 pods in namespace 'kube-system' are running and ready (0 seconds elapsed)
Feb 24 13:42:36.308: INFO: expected 4 pod replicas in namespace 'kube-system', 0 are Running and Ready.
Feb 24 13:42:36.308: INFO: POD                                NODE                                PHASE    GRACE  CONDITIONS
Feb 24 13:42:36.308: INFO: heapster-v14-a1u2z                 gke-jenkins-e2e-0cb7859f-node-soc9  Pending         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-24 13:38:28 -0800 PST ContainersNotReady containers with unready status: [heapster]}]
Feb 24 13:42:36.308: INFO: kube-dns-v10-e16xm                 gke-jenkins-e2e-0cb7859f-node-soc9  Pending         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-24 13:38:28 -0800 PST ContainersNotReady containers with unready status: [etcd kube2sky skydns healthz]}]
Feb 24 13:42:36.308: INFO: kubernetes-dashboard-v0.1.0-1632u  gke-jenkins-e2e-0cb7859f-node-soc9  Pending         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-24 13:38:28 -0800 PST ContainersNotReady containers with unready status: [kubernetes-dashboard]}]
Feb 24 13:42:36.308: INFO: l7-lb-controller-v0.5.2-by8kh      gke-jenkins-e2e-0cb7859f-node-soc9  Pending         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-24 13:38:28 -0800 PST ContainersNotReady containers with unready status: [default-http-backend l7-lb-controller]}]
Feb 24 13:42:36.308: INFO: 
Feb 24 13:42:38.326: INFO: The status of Pod heapster-v14-a1u2z is Pending, waiting for it to be either Running or Failed
Feb 24 13:42:38.326: INFO: The status of Pod kube-dns-v10-e16xm is Pending, waiting for it to be either Running or Failed
Feb 24 13:42:38.326: INFO: The status of Pod kubernetes-dashboard-v0.1.0-1632u is Pending, waiting for it to be either Running or Failed
Feb 24 13:42:38.326: INFO: The status of Pod l7-lb-controller-v0.5.2-by8kh is Pending, waiting for it to be either Running or Failed
Feb 24 13:42:38.326: INFO: 6 / 10 pods in namespace 'kube-system' are running and ready (2 seconds elapsed)
Feb 24 13:42:38.326: INFO: expected 4 pod replicas in namespace 'kube-system', 0 are Running and Ready.
Feb 24 13:42:38.326: INFO: POD                                NODE                                PHASE    GRACE  CONDITIONS
Feb 24 13:42:38.326: INFO: heapster-v14-a1u2z                 gke-jenkins-e2e-0cb7859f-node-soc9  Pending         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-24 13:38:28 -0800 PST ContainersNotReady containers with unready status: [heapster]}]
Feb 24 13:42:38.326: INFO: kube-dns-v10-e16xm                 gke-jenkins-e2e-0cb7859f-node-soc9  Pending         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-24 13:38:28 -0800 PST ContainersNotReady containers with unready status: [etcd kube2sky skydns healthz]}]
Feb 24 13:42:38.326: INFO: kubernetes-dashboard-v0.1.0-1632u  gke-jenkins-e2e-0cb7859f-node-soc9  Pending         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-24 13:38:28 -0800 PST ContainersNotReady containers with unready status: [kubernetes-dashboard]}]
Feb 24 13:42:38.326: INFO: l7-lb-controller-v0.5.2-by8kh      gke-jenkins-e2e-0cb7859f-node-soc9  Pending         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-24 13:38:28 -0800 PST ContainersNotReady containers with unready status: [default-http-backend l7-lb-controller]}]

(...)

Feb 24 13:49:14.325: INFO: 9 / 10 pods in namespace 'kube-system' are running and ready (398 seconds elapsed)
Feb 24 13:49:14.325: INFO: expected 4 pod replicas in namespace 'kube-system', 3 are Running and Ready.
Feb 24 13:49:14.325: INFO: POD                 NODE                                PHASE    GRACE  CONDITIONS
Feb 24 13:49:14.325: INFO: kube-dns-v10-e16xm  gke-jenkins-e2e-0cb7859f-node-soc9  Running         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-24 13:38:28 -0800 PST ContainersNotReady containers with unready status: [skydns]}]
Feb 24 13:49:14.325: INFO: 
Feb 24 13:49:16.328: INFO: The status of Pod kube-dns-v10-e16xm is Running, waiting for it to be either Running or Failed
Feb 24 13:49:16.329: INFO: 9 / 10 pods in namespace 'kube-system' are running and ready (400 seconds elapsed)
Feb 24 13:49:16.329: INFO: expected 4 pod replicas in namespace 'kube-system', 3 are Running and Ready.
Feb 24 13:49:16.329: INFO: POD                 NODE                                PHASE    GRACE  CONDITIONS
Feb 24 13:49:16.329: INFO: kube-dns-v10-e16xm  gke-jenkins-e2e-0cb7859f-node-soc9  Running         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-24 13:38:28 -0800 PST ContainersNotReady containers with unready status: [skydns]}]
Feb 24 13:49:16.329: INFO: 
Feb 24 13:49:18.324: INFO: The status of Pod kube-dns-v10-e16xm is Running, waiting for it to be either Running or Failed
Feb 24 13:49:18.324: INFO: 9 / 10 pods in namespace 'kube-system' are running and ready (402 seconds elapsed)
Feb 24 13:49:18.324: INFO: expected 4 pod replicas in namespace 'kube-system', 3 are Running and Ready.
Feb 24 13:49:18.324: INFO: POD                 NODE                                PHASE    GRACE  CONDITIONS
Feb 24 13:49:18.324: INFO: kube-dns-v10-e16xm  gke-jenkins-e2e-0cb7859f-node-soc9  Running         [{Ready False 0001-01-01 00:00:00 +0000 UTC 2016-02-24 13:38:28 -0800 PST ContainersNotReady containers with unready status: [skydns]}]
Feb 24 13:49:18.324: INFO: 
Feb 24 13:49:20.325: INFO: 10 / 10 pods in namespace 'kube-system' are running and ready (404 seconds elapsed)
Feb 24 13:49:20.325: INFO: expected 4 pod replicas in namespace 'kube-system', 4 are Running and Ready.
```

**Comment by a-robinson** [comment]
cc @spxtr

**Comment by spxtr** [comment]
On a normal run it takes <1 second for all pods in the kube-system namespace to report in. For all of these runs it looks like it's taking several minutes, and then something is still wrong because tests will fail.

**Comment by lavalamp** [comment]
Not convinced this is a test-infra problem, but maybe @spxtr can triage.

@dchen1107 fyi

**Comment by spxtr** [comment]
It doesn't seem like test infra, but I'll take a closer look.

**Comment by lavalamp** [comment]
This looks very similar to #21973

@thockin is it possible some recent change did something to break KubeDNS startup?

**Comment by spxtr** [comment]
http://ci-test.k8s.io/kubernetes-e2e-gce/12260

```
Feb 25 09:49:04.323: INFO: At 2016-02-25 09:38:38 -0800 PST - event for kube-dns-v10-ndopv: {kubelet jenkins-e2e-minion-wqel} Started: Started container with docker id b89197d0bd44
Feb 25 09:49:04.323: INFO: At 2016-02-25 09:38:40 -0800 PST - event for kube-dns-v10-ndopv: {kubelet jenkins-e2e-minion-wqel} Unhealthy: Readiness probe failed: HTTP probe failed with statuscode: 503
Feb 25 09:49:04.323: INFO: At 2016-02-25 09:39:00 -0800 PST - event for kube-dns-v10-ndopv: {kubelet jenkins-e2e-minion-wqel} Unhealthy: Liveness probe failed: HTTP probe failed with statuscode: 503
Feb 25 09:49:04.323: INFO: At 2016-02-25 09:39:19 -0800 PST - event for l7-lb-controller-v0.5.2-h8mbo: {kubelet jenkins-e2e-minion-wqel} Unhealthy: Liveness probe failed: Get http://10.245.0.3:8081/healthz: dial tcp 10.245.0.3:8081: connection refused
Feb 25 09:49:04.323: INFO: At 2016-02-25 09:39:20 -0800 PST - event for kube-dns-v10-ndopv: {kubelet jenkins-e2e-minion-wqel} Killing: Killing container with docker id 9c4020bac4dd: pod "kube-dns-v10-ndopv_kube-system(462bfcb6-dbe6-11e5-8d52-42010af00002)" container "skydns" is unhealthy, it will be killed and re-created.
Feb 25 09:49:04.323: INFO: At 2016-02-25 09:39:20 -0800 PST - event for kube-dns-v10-ndopv: {kubelet jenkins-e2e-minion-wqel} Pulled: Container image "gcr.io/google_containers/skydns:2015-10-13-8c72f8c" already present on machine
Feb 25 09:49:04.323: INFO: At 2016-02-25 09:39:20 -0800 PST - event for kube-dns-v10-ndopv: {kubelet jenkins-e2e-minion-wqel} Created: Created container with docker id 3d0e507bccec
Feb 25 09:49:04.323: INFO: At 2016-02-25 09:39:20 -0800 PST - event for kube-dns-v10-ndopv: {kubelet jenkins-e2e-minion-wqel} Started: Started container with docker id 3d0e507bccec
Feb 25 09:49:04.323: INFO: At 2016-02-25 09:39:50 -0800 PST - event for kube-dns-v10-ndopv: {kubelet jenkins-e2e-minion-wqel} Started: Started container with docker id 6cd4c5a6eed6
Feb 25 09:49:04.323: INFO: At 2016-02-25 09:39:50 -0800 PST - event for kube-dns-v10-ndopv: {kubelet jenkins-e2e-minion-wqel} Created: Created container with docker id 6cd4c5a6eed6
Feb 25 09:49:04.323: INFO: At 2016-02-25 09:39:50 -0800 PST - event for kube-dns-v10-ndopv: {kubelet jenkins-e2e-minion-wqel} Killing: Killing container with docker id 3d0e507bccec: pod "kube-dns-v10-ndopv_kube-system(462bfcb6-dbe6-11e5-8d52-42010af00002)" container "skydns" is unhealthy, it will be killed and re-created.
...
```

**Comment by bprashanth** [comment]
The dns pod not coming up is because of a liveness probe failure, which means it isn't able to resolve the kubernetes service. Any addon that requires dns (eg kibana needs to talk to ES) will fail because of dns. I'm adding some logging to clarify http liveness probe failures.

**Comment by bprashanth** [comment]
Grafana failing seems to be a different issue. It doesn't need DNS AFAICT. Looks like it couldn't get the 8086 hostPort from the first comment:

Feb 24 14:44:46.585: INFO: At 2016-02-24 14:35:33 -0800 PST - event for monitoring-influxdb-
grafana-v3-fyy2c: {kubelet jenkins-e2e-minion-bu2m} FailedSync: Error syncing pod, skipping: failed to 
"StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): Cannot start 
container 0925337af9de6b234ac2edecdcd3e5536f8853b8467ec63ba4fcf53dd103c810: failed to 
create endpoint k8s_POD.444e2470_monitoring-influxdb-grafana-v3-fyy2c_kube-system_71d9a704-
db46-11e5-95a6-42010af00002_46e1ec03 on network bridge: __Bind for 0.0.0.0:8086 failed: port is 
already allocated\n"__

**Comment by spxtr** [comment]
@bprashanth mind taking over this issue?

**Comment by yujuhong** [comment]
FYI, this happened in a per-PR build.

http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/30868/consoleFull
https://cloud.google.com/console/storage/kubernetes-jenkins/pr-logs/pull/21785/kubernetes-pull-build-test-e2e-gce/30868/

```
Feb 28 02:27:05.554: INFO: Ignoring Ready pod kube-system/elasticsearch-logging-v1-ieg9a
Feb 28 02:27:05.554: INFO: Ignoring Ready pod kube-system/elasticsearch-logging-v1-v3gwy
Feb 28 02:27:05.554: INFO: Ignoring Ready pod kube-system/fluentd-elasticsearch-e2e-gce-master-0-minion-2lq8
Feb 28 02:27:05.554: INFO: Ignoring Ready pod kube-system/fluentd-elasticsearch-e2e-gce-master-0-minion-fegx
Feb 28 02:27:05.554: INFO: Ignoring Ready pod kube-system/fluentd-elasticsearch-e2e-gce-master-0-minion-fres
Feb 28 02:27:05.554: INFO: Ignoring Ready pod kube-system/fluentd-elasticsearch-e2e-gce-master-0-minion-gofu
Feb 28 02:27:05.554: INFO: Ignoring Ready pod kube-system/fluentd-elasticsearch-e2e-gce-master-0-minion-iwt5
Feb 28 02:27:05.554: INFO: Ignoring Ready pod kube-system/fluentd-elasticsearch-e2e-gce-master-0-minion-tpy9
Feb 28 02:27:05.554: INFO: Ignoring Ready pod kube-system/heapster-v14-6qlfx
STEP: Previous logs of kube-system/kibana-logging-v1-5b16a:kibana-logging on node e2e-gce-master-0-minion-fegx
Feb 28 02:27:05.642: INFO: ELASTICSEARCH_URL=http://elasticsearch-logging:9200
{"@timestamp":"2016-02-28T10:24:37.218Z","level":"error","message":"Request Timeout after 1500ms","node_env":"production","error":{"message":"Request Timeout after 1500ms","name":"Error","stack":"Error: Request Timeout after 1500ms\n  at [object Object].<anonymous> (/kibana-4.0.2-linux-x64/src/node_modules/elasticsearch/src/lib/transport.js:282:15)\n  at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)\n"}}
{"@timestamp":"2016-02-28T10:24:37.219Z","level":"fatal","message":"Request Timeout after 1500ms","node_env":"production","error":{"message":"Request Timeout after 1500ms","name":"Error","stack":"Error: Request Timeout after 1500ms\n  at [object Object].<anonymous> (/kibana-4.0.2-linux-x64/src/node_modules/elasticsearch/src/lib/transport.js:282:15)\n  at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)\n"}}

Feb 28 02:27:05.747: INFO: Failed to get logs of pod kube-dns-v10-tb1ky, container etcd, err: previous terminated container "etcd" in pod "kube-dns-v10-tb1ky" not found
STEP: Previous logs of kube-system/kube-dns-v10-tb1ky:etcd on node e2e-gce-master-0-minion-2lq8
Feb 28 02:27:05.747: INFO: 
Feb 28 02:27:05.752: INFO: Failed to get logs of pod kube-dns-v10-tb1ky, container kube2sky, err: previous terminated container "kube2sky" in pod "kube-dns-v10-tb1ky" not found
STEP: Previous logs of kube-system/kube-dns-v10-tb1ky:kube2sky on node e2e-gce-master-0-minion-2lq8
Feb 28 02:27:05.752: INFO: 
STEP: Previous logs of kube-system/kube-dns-v10-tb1ky:skydns on node e2e-gce-master-0-minion-2lq8
Feb 28 02:27:05.758: INFO: 2016/02/28 10:26:20 skydns: falling back to default configuration, could not read from etcd: 100: Key not found (/skydns) [3]
2016/02/28 10:26:20 skydns: ready for queries on cluster.local. for tcp://0.0.0.0:53 [rcache 0]
2016/02/28 10:26:20 skydns: ready for queries on cluster.local. for udp://0.0.0.0:53 [rcache 0]

Feb 28 02:27:05.762: INFO: Failed to get logs of pod kube-dns-v10-tb1ky, container healthz, err: previous terminated container "healthz" in pod "kube-dns-v10-tb1ky" not found
STEP: Previous logs of kube-system/kube-dns-v10-tb1ky:healthz on node e2e-gce-master-0-minion-2lq8
Feb 28 02:27:05.762: INFO: 
Feb 28 02:27:05.762: INFO: Ignoring Ready pod kube-system/kube-proxy-e2e-gce-master-0-minion-2lq8
Feb 28 02:27:05.762: INFO: Ignoring Ready pod kube-system/kube-proxy-e2e-gce-master-0-minion-fegx
Feb 28 02:27:05.762: INFO: Ignoring Ready pod kube-system/kube-proxy-e2e-gce-master-0-minion-fres
Feb 28 02:27:05.762: INFO: Ignoring Ready pod kube-system/kube-proxy-e2e-gce-master-0-minion-gofu
Feb 28 02:27:05.762: INFO: Ignoring Ready pod kube-system/kube-proxy-e2e-gce-master-0-minion-iwt5
Feb 28 02:27:05.762: INFO: Ignoring Ready pod kube-system/kube-proxy-e2e-gce-master-0-minion-tpy9
Feb 28 02:27:05.762: INFO: Ignoring Ready pod kube-system/kubernetes-dashboard-v0.1.0-kaeb8
Feb 28 02:27:05.762: INFO: Ignoring Ready pod kube-system/l7-lb-controller-v0.5.2-cjsd4
Feb 28 02:27:05.762: INFO: Ignoring Ready pod kube-system/monitoring-influxdb-grafana-v3-wd9am
Feb 28 02:27:05.762: FAIL: Error waiting for all pods to be running and ready: Not all pods in namespace 'kube-system' running and ready within 10m0s
```

**Comment by bprashanth** [comment]
--previous only works on crashing containers, which in this case is skydns. But it's crashing because of an nslookup failure, which is most likely because of kube2sky, so I really should be logging the output of kube2sky (not --previous kube2sky, which doesn't exist because it never crashed). 

Hrm. 

I have https://github.com/kubernetes/kubernetes/pull/22253.

**Comment by jlowdermilk** [comment]
More recents hits from kubernetes-e2e-gce:
[kubernetes-e2e-gce/12642](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gce/12642)
[kubernetes-e2e-gce/12648](https://storage.cloud.google.com/kubernetes-jenkins/logs/kubernetes-e2e-gce/12648)

**Comment by bprashanth** [comment]
My pr is still pending unfortunately, it's a rats nest. Hopefully in by today.
