### ISSUE TITLE
Jenkins is regularly getting stuck never completing

### ISSUE THREAD

**Issue by eparis** [kubernetes/kubernetes#22435]
... so PRs hang 'pending' and will never get into the submit queue or will get kicked out after they wait and hour for jenkins to return.

**Comment by eparis** [comment]
This is a dupe of https://github.com/kubernetes/contrib/issues/536
@eparis @lavalamp @mwielgus @gmarek @fgrzadkowski @ixdy

**Comment by bgrant0607** [comment]
cc @fejta

**Comment by eparis** [comment]
I'm compiling a list of all PRs that look to be stuck on Jenkins....

**Comment by bgrant0607** [comment]
cc @wojtek-t

**Comment by eparis** [comment]
All PRs with LGTM that have been hanging in Jenkins for more than 1 hour.

https://github.com/kubernetes/kubernetes/pull/20578
https://github.com/kubernetes/kubernetes/pull/20851
https://github.com/kubernetes/kubernetes/pull/21335
https://github.com/kubernetes/kubernetes/pull/21645
https://github.com/kubernetes/kubernetes/pull/21851
https://github.com/kubernetes/kubernetes/pull/21904
https://github.com/kubernetes/kubernetes/pull/21982
https://github.com/kubernetes/kubernetes/pull/22038
https://github.com/kubernetes/kubernetes/pull/22043
https://github.com/kubernetes/kubernetes/pull/22264
https://github.com/kubernetes/kubernetes/pull/22320
https://github.com/kubernetes/kubernetes/pull/22332
https://github.com/kubernetes/kubernetes/pull/22394
https://github.com/kubernetes/kubernetes/pull/22406
https://github.com/kubernetes/kubernetes/pull/22426

**Comment by eparis** [comment]
PRs without LGTM but have 1.2 milestone:

https://github.com/kubernetes/kubernetes/pull/20044
https://github.com/kubernetes/kubernetes/pull/21400
https://github.com/kubernetes/kubernetes/pull/21910
https://github.com/kubernetes/kubernetes/pull/21966
https://github.com/kubernetes/kubernetes/pull/22345
https://github.com/kubernetes/kubernetes/pull/22432

**Comment by justinsb** [comment]
#21907 also.  That one needed a squash anyway, so I squashed, repushed and re-added LGTM.  Will be interesting to see what happens...

**Comment by eparis** [comment]
looking at the jenkins 'status' of #21907 it looks like it is going to be ok. The busted ones are linking something like:
```
http://pr-test.k8s.io/$%7BghprbPullId%7D/kubernetes-pull-build-test-e2e-gce/$%7BBUILD_NUMBER%7D/
```

And a working PR looks like:
```
http://pr-test.k8s.io/21907/kubernetes-pull-build-test-e2e-gce/31499/
```

So none of that `$%7BghprbPullId%7D` or `$%7BBUILD_NUMBER%7D` crap in the status link...

**Comment by gmarek** [comment]
7B and 7D are '{' and '}' - looks like a change from " " to ' ' in some bash script...

**Comment by eparis** [comment]
@gmarek but only 'sometimes'  :-(   which makes me think it might have to do with which builder ? maybe?

**Comment by gmarek** [comment]
If it happens only for some builds (I thought that we have problems with all of them), then it's certainly one of the builders. @ixdy is probably the best person to ask.

**Comment by eparis** [comment]
Its a LOT of them, but not all  :-(

**Comment by ixdy** [comment]
Looking. I'm not really sure what's happening. I upgraded the Github PR plugin last night, to see if it fixed any bugs that may have prevented those few PRs from scheduling, but it seems to have made things worse. I'm currently suspicious of jenkinsci/ghprb-plugin/pull/273, though still looking through recent commits.

**Comment by ixdy** [comment]
For added fun, PR Jenkins also just fell over. Shaping out to be a great Thursday so far.

**Comment by ixdy** [comment]
I think it might be jenkinsci/ghprb-plugin#273. It looked neat (it is supposed to cancel builds if a PR is updated, I think), but it looks like it's fundamentally broken:
```
WARNING: org.jenkinsci.plugins.ghprb.GhprbTrigger.run() failed for hudson.model.FreeStyleProject@7c2c4fa2[kubernetes
-pull-test-unit-integration]
java.lang.NullPointerException
        at org.jenkinsci.plugins.ghprb.extensions.build.GhprbCancelBuildsOnUpdate.cancelCurrentBuilds(GhprbCancelBui
ldsOnUpdate.java:44)
        at org.jenkinsci.plugins.ghprb.extensions.build.GhprbCancelBuildsOnUpdate.onScheduleBuild(GhprbCancelBuildsO
nUpdate.java:97)
        at org.jenkinsci.plugins.ghprb.GhprbTrigger.scheduleBuild(GhprbTrigger.java:296)
        at org.jenkinsci.plugins.ghprb.GhprbBuilds.build(GhprbBuilds.java:80)
        at org.jenkinsci.plugins.ghprb.GhprbPullRequest.build(GhprbPullRequest.java:325)
        at org.jenkinsci.plugins.ghprb.GhprbPullRequest.tryBuild(GhprbPullRequest.java:318)
        at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:161)
        at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:174)
        at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:154)
        at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:287)
        at hudson.triggers.Trigger.checkTriggers(Trigger.java:272)
        at hudson.triggers.Trigger$Cron.doRun(Trigger.java:221)
        at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecut
or.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java
:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by ixdy** [comment]
I disabled that feature ("Cancel build on update") and triggered #21907 successfully, so we might be OK. Probably need to explicitly trigger everything with a pending status, though (at least the LG'd ones).

**Comment by ixdy** [comment]
I re-queued all LGTM'd `priority/P1` pending-status PRs. There were no `priority/P0` PRs that I could find.

We probably need to re-queue the rest of the LGTM'd PRs at some point.

**Comment by ixdy** [comment]
fyi @kubernetes/goog-testing (should've CC'd earlier)

**Comment by eparis** [comment]
@k8s-bot test this, issue #22435

**Comment by eparis** [comment]
I just hit up any PR with the 1.2 milestone that was hanging.

**Comment by ixdy** [comment]
Jenkins seems to be working now, so closing.

**Comment by imkin** [comment]
https://github.com/kubernetes/kubernetes/pull/20851 is still not getting any love :-(

**Comment by eparis** [comment]
I will get it retriggered.
