### ISSUE TITLE
kubelet hangs for 20s while initializing cadvisor

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#22668]
The code blocks here for 20s:

https://github.com/kubernetes/kubernetes/blob/master/Godeps/_workspace/src/github.com/google/cadvisor/manager/machine.go#L96

I am not running with a cloud provider, just using `hack/local-up-cluster`

The code should not hang this long.

```
I0307 16:21:23.319211    4158 manager.go:172] cAdvisor running in container: "/"
I0307 16:21:23.463520    4158 manager.go:178] cadvisor new - docker info start time: (144.353548ms)
I0307 16:21:23.464067    4158 fs.go:109] Filesystem partitions: map[/dev/mapper/fedora-root:{mountpoint:/ major:253 minor:2 fsType: blockSize:0} /dev/sda1:{mountpoint:/boot major:8 minor:1 fsType: blockSize:0} /dev/mapper/fedora-home:{mountpoint:/home major:253 minor:3 fsType: blockSize:0}]
I0307 16:21:23.464091    4158 manager.go:185] cadvisor new - fs info start time: (144.929889ms)
I0307 16:21:23.464235    4158 machine.go:70] kubelet cadvisor - getMachineInfo  clockSpeed - time: (133.559µs)
I0307 16:21:23.464285    4158 machine.go:76] kubelet cadvisor - getMachineInfo  memoryCapacity - time: (183.781µs)
I0307 16:21:23.464408    4158 machine.go:82] kubelet cadvisor - getMachineInfo  filesystems - time: (306.144µs)
I0307 16:21:23.464712    4158 machine.go:88] kubelet cadvisor - getMachineInfo  diskMap - time: (610.47µs)
I0307 16:21:23.465242    4158 machine.go:94] kubelet cadvisor - getMachineInfo  netDevices - time: (1.139566ms)
I0307 16:21:23.465595    4158 machine.go:100] kubelet cadvisor - getMachineInfo  topology - time: (1.493255ms)
I0307 16:21:23.465624    4158 machine.go:106] kubelet cadvisor - getMachineInfo  systemUUID - time: (1.521393ms)
I0307 16:21:43.821091    4158 machine.go:109] kubelet cadvisor - getMachineInfo  realCloudInfo - time: (20.356975325s)
I0307 16:21:43.821145    4158 machine.go:111] kubelet cadvisor - getMachineInfo  cloudProvider - time: (20.357035925s)
I0307 16:21:43.821168    4158 machine.go:113] kubelet cadvisor - getMachineInfo  instanceType - time: (20.357059355s)
I0307 16:21:43.821190    4158 machine.go:115] kubelet cadvisor - getMachineInfo  instanceID - time: (20.357079922s)
```

I added some logging to work it backwards.

/cc @vishh @dchen1107 @ncdc @sjenning @smarterclayton

**Comment by sjenning** [comment]
Yes, this is caused by a retry timer on the AWS cloud detect code.

```
goroutine 1 [sleep]:
time.Sleep(0xb34a700)
	/usr/lib/golang/src/runtime/time.go:59 +0xf9
github.com/aws/aws-sdk-go/aws/corehandlers.glob.func4(0xc820117500)
	/home/sjennings/projects/cadvisor/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go:116 +0x123
github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc820117718, 0xc820117500)
	/home/sjennings/projects/cadvisor/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/request/handlers.go:136 +0xc3
github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc820117500, 0x0, 0x0)
	/home/sjennings/projects/cadvisor/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/request/request.go:248 +0x60a
github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).GetMetadata(0xc8200f0740, 0xccc920, 0xb, 0x0, 0x0, 0x0, 0x0)
	/home/sjennings/projects/cadvisor/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go:20 +0x1fb
github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).Available(0xc8200f0740, 0xc82012b1e0)
	/home/sjennings/projects/cadvisor/src/github.com/google/cadvisor/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go:38 +0x36
github.com/google/cadvisor/utils/cloudinfo.onAWS(0x0)
	/home/sjennings/projects/cadvisor/src/github.com/google/cadvisor/utils/cloudinfo/aws.go:27 +0xf2
github.com/google/cadvisor/utils/cloudinfo.detectCloudProvider(0x0, 0x0)
	/home/sjennings/projects/cadvisor/src/github.com/google/cadvisor/utils/cloudinfo/cloudinfo.go:62 +0x50
github.com/google/cadvisor/utils/cloudinfo.NewRealCloudInfo(0x0, 0x0)
	/home/sjennings/projects/cadvisor/src/github.com/google/cadvisor/utils/cloudinfo/cloudinfo.go:36 +0x28
github.com/google/cadvisor/manager.getMachineInfo(0x7f280c14cbd8, 0x1420170, 0x7f280c152148, 0xc8201d69e0, 0x1, 0x2, 0x0, 0x0)
	/home/sjennings/projects/cadvisor/src/github.com/google/cadvisor/manager/machine.go:96 +0x847
github.com/google/cadvisor/manager.New(0xc8201ad340, 0x7f280c14cbd8, 0x1420170, 0xdf8475800, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/sjennings/projects/cadvisor/src/github.com/google/cadvisor/manager/manager.go:200 +0x69f
main.main()
	/home/sjennings/projects/cadvisor/src/github.com/google/cadvisor/cadvisor.go:76 +0x597
```

**Comment by sjenning** [comment]
Basically, it can't resolve the hostname of the metadata server so the request doesn't get an HTTP error since the connection can't even be established.

This fixes it for me

```
diff --git a/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go b/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go
index 1d3e656..2bf0859 100644
--- a/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go
+++ b/Godeps/_workspace/src/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go
@@ -90,7 +90,7 @@ var SendHandler = request.NamedHandler{Name: "core.SendHandler", Fn: func(r *req
                }
                // Catch all other request errors.
                r.Error = awserr.New("RequestError", "send request failed", err)
-               r.Retryable = aws.Bool(true) // network errors are retryable
+               r.Retryable = aws.Bool(false) // network errors are retryable
        }
 }}
```

Not sure if that is generally acceptable though.

**Comment by dchen1107** [comment]
@sjenning Thanks for digging into this. This is what I suspected, but I have one puzzle left. Shouldn't this is one time thing? Once cAdvisor / Kubelet detects the cloud provider, the information should be cached, and following queries of cloudProvider, instanceType, and instanceID shouldn't be that long?

**Comment by derekwaynecarr** [comment]
@dchen1107 - I think its a one time thing, but it was the source of me needing to bump this time:
https://github.com/kubernetes/kubernetes/pull/22563

I think we should be able to provide a better experience than what I am getting when not running on a cloud provider.  What I wondered is if rather than detecting, I could just tell it I am not on a cloud provider.

**Comment by dchen1107** [comment]
Kubelet today already takes --cloud-provider, and empty string for local cluster. We can refactory cAdvisor library to carry this information too.

**Comment by derekwaynecarr** [comment]
I think we can avoid tweaking how cadvisor is started, and just update how we do client configuration for aws from cadvisor.  Some local testing showed a significant improvement.  Will update the issue with the cadvisor PR when pushed.

**Comment by derekwaynecarr** [comment]
Assuming this merges in cadvisor, https://github.com/google/cadvisor/pull/1152, we can bump kube and get our startup times from 20s to 5s (the default aws timeout) which should be good enough to let us use the default timeouts in e2e tests.

**Comment by vishh** [comment]
A note about the bump:  google/cadvisor#1152
<https://github.com/google/cadvisor/pull/1152> will have to be
cherry-picked into `release-0.22` branch and then we can create a tag based
on that branch. We can then use that tag to update cadvisor deps on the
kube side,
