### ISSUE TITLE
Heapster metric-export stack trace

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#22676]
Debugging a ooming apsierver I noticed the following suspicious stack trace:
```
I0307 22:34:07.704596       5 handlers.go:131] GET /api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/metric-export: (1.28314ms) 503
goroutine 909 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc27fbd48a0, 0x1f7)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:188 +0x9a
k8s.io/kubernetes/pkg/apiserver.writeJSON(0x1f7, 0x7f2762d754c8, 0xc2080db6c0, 0x7f2762d75bf0, 0xc212b12480, 0x7f2762b82790, 0xc27fbd48a0, 0x1)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:389 +0x89
k8s.io/kubernetes/pkg/apiserver.(*ProxyHandler).ServeHTTP(0xc208228b40, 0x7f2762b82790, 0xc27fbd48a0, 0xc208271e10)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/proxy.go:112 +0xcb9
k8s.io/kubernetes/pkg/apiserver.func·002(0xc20b048ea0, 0xc27fbd4960)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/api_installer.go:758 +0x60
github.com/emicklei/go-restful.func·009(0xc20b048ea0, 0xc27fbd4960)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:244 +0x41
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20b049020, 0xc20b048ea0, 0xc27fbd4960)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
k8s.io/kubernetes/pkg/apiserver.func·003(0xc20b048ea0, 0xc27fbd4960, 0xc20b049020)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:62 +0x8b
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc20b049020, 0xc20b048ea0, 0xc27fbd4960)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19 +0x84
github.com/emicklei/go-restful.(*Container).dispatch(0xc2081146c0, 0x7f2762b82790, 0xc27fbd48a0, 0xc208271e10)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:246 +0xee3
github.com/emicklei/go-restful.*Container.(github.com/emicklei/go-restful.dispatch)·fm(0x7f2762b82790, 0xc27fbd48a0, 0xc208271e10)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful
Error getting ResourceLocation: no endpoints available for service "heapster" ]
```

I can't tell if this was contributing to the oom, or because of it. Heapster was immediately disabled. We did a couple of things after that and the ooming stopped. Problem?

@piosz

**Comment by piosz** [comment]
Thanks for reporting. It looks like a problem with endpoint controller rather than with Heapster itself since the request failed due to missing endpoint, not because of internal Heapster problem. Could you please verify whether Heapster is working properly and heapster service is successfully created?

cc @lavalamp @mwielgus

**Comment by bprashanth** [comment]
Ah I missed that it was complaining about the missing endpoint. I think that's expected. Heapster was crashing anyway and the cluster was in a bad state (from a customer issue, not my cluster, so I don't have details).

what does that /metric-export endpoint do? There was actually a correlation with the (successfull) requests and memory spikes that caused OOM, but I can't say for sure. Does it pull massive amounts of stats through apiserver memory by any chance?

**Comment by piosz** [comment]
Any logs from Heapster? /metric-export is basically dumping all available metrics from last 2 minutes.
> Does it pull massive amounts of stats through apiserver memory by any chance?

exactly

cc @fgrzadkowski

**Comment by fgrzadkowski** [comment]
@piosz Can we estimate amount of data sent in this cluster? How many containers we had?

**Comment by bprashanth** [comment]
> Can we estimate amount of data sent in this cluster? How many containers we had?

~10,000 failed pods and a n1-standard-1 master. Nodes were out of disk. There was a period when we kept creating pods that went into failed, there were only a handful of running pods.

**Comment by fgrzadkowski** [comment]
@mwielgus @piosz Do we export metrics for failed pods? My understanding was that we don't since we export the newest samples through GKE API, and there are no new samples for terminated pods.

**Comment by mwielgus** [comment]
No, we only export mertrics for pods that are scrapeable by cAdvisor.

**Comment by fgrzadkowski** [comment]
So my understanding is that the size of heapster response should be rather small.

**Comment by piosz** [comment]
It should be easy to check:
```
curl <master>/api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/metric-export -so /dev/null -w '%{size_download}'
```
Could you please do it?

**Comment by piosz** [comment]
Closing as obsolete.

**Comment by tatroc** [comment]
I am having a similar issue. How/where do I set the end point for heapster ? I am unsure where to configure this. 

```
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"738b7603b042dcda7a5ba419ab0e7f40a617080c", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"738b7603b042dcda7a5ba419ab0e7f40a617080c", GitTreeState:"clean"}

```


```
May 23 13:53:34  kube-apiserver: I0523 13:53:34.934715    3851 <autogenerated>:1] Error getting ResourceLocation: no endpoints available for service "heapster"
May 23 13:53:42  kube-apiserver: I0523 13:53:42.207630    3851 <autogenerated>:1] Error getting ResourceLocation: no endpoints available for service "heapster"
May 23 13:53:57  kube-apiserver: I0523 13:53:57.394756    3851 <autogenerated>:1] Error getting ResourceLocation: no endpoints available for service "http:heapster:"
May 23 13:54:26  kube-apiserver: I0523 13:54:26.399335    3851 <autogenerated>:1] Error getting ResourceLocation: no endpoints available for service "http:heapster:"
May 23 13:54:55  kube-apiserver: I0523 13:54:55.402103    3851 <autogenerated>:1] Error getting ResourceLocation: no endpoints available for service "http:heapster:"

```

**Comment by piosz** [comment]
@tatroc could you please verify whether Heapster is working? Could you please take a look into Heapster logs and verify whether you can see anything suspicious?

**Comment by tatroc** [comment]
heapster logs look clean to me, except for a connection timeout when influxdb was starting

I also connected to the influxdb and verified that data is being inserted. 

```
E0523 15:50:20.953537       1 influxdb.go:209] issues while creating an InfluxDB sink: failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: dial tcp 10.254.173.254:8086: i/o timeout, will retry on use
I0523 15:50:20.953688       1 influxdb.go:223] created influxdb sink with options: host:monitoring-influxdb:8086 user:root db:k8s
I0523 15:50:20.953802       1 heapster.go:92] Starting with InfluxDB Sink
I0523 15:50:20.953824       1 heapster.go:92] Starting with Metric Sink
I0523 15:50:20.980567       1 heapster.go:171] Starting heapster on port 8082
I0523 15:51:05.000430       1 manager.go:79] Scraping metrics start: 2016-05-23 15:50:00 +0000 UTC, end: 2016-05-23 15:51:00 +0000 UTC
I0523 15:51:05.184665       1 manager.go:152] ScrapeMetrics: time: 183.865909ms size: 165
I0523 15:51:05.212981       1 influxdb.go:201] Created database "k8s" on influxDB server at "monitoring-influxdb:8086"
I0523 15:52:05.043874       1 manager.go:79] Scraping metrics start: 2016-05-23 15:51:00 +0000 UTC, end: 2016-05-23 15:52:00 +0000 UTC
I0523 15:52:05.280998       1 manager.go:152] ScrapeMetrics: time: 236.791029ms size: 165
I0523 15:53:05.000266       1 manager.go:79] Scraping metrics start: 2016-05-23 15:52:00 +0000 UTC, end: 2016-05-23 15:53:00 +0000 UTC
I0523 15:53:05.197091       1 manager.go:152] ScrapeMetrics: time: 196.604862ms size: 165
I0523 15:54:05.000301       1 manager.go:79] Scraping metrics start: 2016-05-23 15:53:00 +0000 UTC, end: 2016-05-23 15:54:00 +0000 UTC
I0523 15:54:05.165616       1 manager.go:152] ScrapeMetrics: time: 164.781416ms size: 165
I0523 15:55:05.000504       1 manager.go:79] Scraping metrics start: 2016-05-23 15:54:00 +0000 UTC, end: 2016-05-23 15:55:00 +0000 UTC
I0523 15:55:05.184315       1 manager.go:152] ScrapeMetrics: time: 183.555523ms size: 165
I0523 15:56:05.000328       1 manager.go:79] Scraping metrics start: 2016-05-23 15:55:00 +0000 UTC, end: 2016-05-23 15:56:00 +0000 UTC
I0523 15:56:05.177374       1 manager.go:152] ScrapeMetrics: time: 176.847106ms size: 165
I0523 15:57:05.000299       1 manager.go:79] Scraping metrics start: 2016-05-23 15:56:00 +0000 UTC, end: 2016-05-23 15:57:00 +0000 UTC
I0523 15:57:05.170819       1 manager.go:152] ScrapeMetrics: time: 170.3009ms size: 165
I0523 15:58:05.000295       1 manager.go:79] Scraping metrics start: 2016-05-23 15:57:00 +0000 UTC, end: 2016-05-23 15:58:00 +0000 UTC
I0523 15:58:05.162535       1 manager.go:152] ScrapeMetrics: time: 162.054069ms size: 165
I0523 15:59:05.000327       1 manager.go:79] Scraping metrics start: 2016-05-23 15:58:00 +0000 UTC, end: 2016-05-23 15:59:00 +0000 UTC
I0523 15:59:05.161500       1 manager.go:152] ScrapeMetrics: time: 160.687611ms size: 165
I0523 16:00:05.000408       1 manager.go:79] Scraping metrics start: 2016-05-23 15:59:00 +0000 UTC, end: 2016-05-23 16:00:00 +0000 UTC
I0523 16:00:05.246156       1 manager.go:152] ScrapeMetrics: time: 245.428689ms size: 165
I0523 16:01:05.000302       1 manager.go:79] Scraping metrics start: 2016-05-23 16:00:00 +0000 UTC, end: 2016-05-23 16:01:00 +0000 UTC
I0523 16:01:05.225515       1 manager.go:152] ScrapeMetrics: time: 224.621689ms size: 165

```

**Comment by tatroc** [comment]
The messages are coming in pairs kube-apiserver and kube-controller-manager. 


The whole reason I am trying to get heapster running is so I can do auto scaling. CURRENT is in a <waiting> status. 
```
NAME         REFERENCE                                TARGET    CURRENT     MINPODS   MAXPODS   AGE
nodetestv2   ReplicationController/nodetestv2/scale   10%       <waiting>   1         10        20h
```



```
May 23 15:14:12 kube-apiserver: I0523 15:14:12.047270    3851 <autogenerated>:1] Error getting ResourceLocation: no endpoints available for service "http:heapster:"
May 23 15:14:12 kube-controller-manager: W0523 15:14:12.052375    3878 horizontal.go:108] Failed to reconcile nodetestv2: failed to compute desired number of replicas based on CPU utilization for ReplicationController/default/nodetestv2: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 0/1 of pods
```

**Comment by piosz** [comment]
This looks like a problem with endpoint controller.

cc @bprashanth @thockin @kubernetes/goog-cluster

**Comment by bprashanth** [comment]
Is heapster "Ready"?

**Comment by tatroc** [comment]
Yes heapster is "Ready"

 ```
kubectl get pods --namespace=kube-system
NAME                     READY     STATUS    RESTARTS   AGE
heapster-spmtk           1/1       Running   0          15h
influxdb-grafana-gckid   2/2       Running   0          20h
kube-dns-v11-71x0c       4/4       Running   0          1d
```

 ```
kubectl cluster-info
Kubernetes master is running at http://localhost:8080
Heapster is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/heapster
KubeDNS is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kube-dns
monitoring-grafana is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana

```

**Comment by bprashanth** [comment]
and kubectl get ep doesn't show anything for heapster? did you modify the svc or pod labels/selectors? can you give me your kube-controller-manager logs?

**Comment by tatroc** [comment]
End points appear to be good. 
```
 kubectl get ep --namespace=kube-system
NAME                  ENDPOINTS                           AGE
heapster              172.17.91.2:8082                    1d
kube-dns              172.17.54.2:53,172.17.54.2:53       1d
monitoring-grafana    172.17.54.3:3000                    1d
monitoring-influxdb   172.17.54.3:8083,172.17.54.3:8086   1d
```

Here is the contents of: heapster-service.yaml
```
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Heapster
  name: heapster
  namespace: kube-system
spec:
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    k8s-app: heapste
```


In the kube-controller-manager log all I see are the following messages. 
``May 24 13:43:23 servername kube-controller-manager: W0524 13:43:23.205409    3878 horizontal.go:108] Failed to reconcile nodetestv2: failed to compute desired number of replicas based on CPU utilization for ReplicationController/default/nodetestv2: failed to get CPU utilization: failed to get CPU consumption and request: metrics obtained for 0/1 of pods`
`

**Comment by tatroc** [comment]
@bprashanth

I believe I have resolved the issue. Since making the changes below to heapster-service.yaml the above message: 
`failed to get CPU consumption and request: metrics obtained for 0/1 of pods` does not get logged anymore. I also generated some load on the application and the auto scaling is working beautifully now. Thanks for all the help!

Put double quotes around "true" and "Heapster"
```

kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Heapster"
```

removed these lines from heapster-service.yaml
```
 protocol: TCP
    name: http
```

**Comment by piosz** [comment]
Thanks @tatroc for the update. Closing the issue. Feel free to re-open in case of problems.

**Comment by sashgorokhov** [comment]
Having the same issue. 
kubernetes v1.3.0-beta.1

kubectl get ep
`heapster               10.0.2.15:8082`
heapster logs are healthy, i see full stats for my containers in influxdb and grafana.
added labels to heapster replication controller as bprashanth did. 

in api server logs i see lines like this:
`I0621 11:15:30.706061   13624 <autogenerated>:1] Error getting ResourceLocation: no endpoints available for service "http:heapster:"`

I wondering if there a way to manually define heapster endpoints in hpa, and why such a behaviour (need of heapster and heapster service discover by special label) of horizontal pod autoscaler is not documented?
