### ISSUE TITLE
kubectl panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by olafurnielsen** [kubernetes/kubernetes#23242]
Getting a panic error when trying to do a rolling-update. Any ideas?

```
➜  nodetest git:(master) ✗ kubectl rolling-update nodetest2 --image=814863397952.dkr.ecr.us-east-1.amazonaws.com/nodetest
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x336457]

goroutine 1 [running]:
k8s.io/kubernetes/pkg/runtime.Encode(0x0, 0x0, 0x1d145d8, 0xc82016de00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/runtime/codec.go:45 +0xf7
k8s.io/kubernetes/pkg/api.HashObject(0x1d145d8, 0xc82016de00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/helpers.go:156 +0xb2
k8s.io/kubernetes/pkg/kubectl.CreateNewControllerFromCurrentController(0x1d1a540, 0xc8203e8dc0, 0x0, 0x0, 0xc82026d050, 0x7, 0x7fff5fbff87f, 0x9, 0x0, 0x0, ...)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/rolling_updater.go:575 +0x754
k8s.io/kubernetes/pkg/kubectl/cmd.RunRollingUpdate(0xc8201e6820, 0x1d13198, 0xc820074008, 0xc820245e00, 0xc8202645e0, 0x1, 0x2, 0xc82023f3e0, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/rollingupdate.go:253 +0x4234
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdRollingUpdate.func1(0xc820245e00, 0xc8202645e0, 0x1, 0x2)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/rollingupdate.go:87 +0x7d
github.com/spf13/cobra.(*Command).execute(0xc820245e00, 0xc8202644a0, 0x2, 0x2, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:572 +0x869
github.com/spf13/cobra.(*Command).ExecuteC(0xc82013ba00, 0xc820245e00, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x54e
github.com/spf13/cobra.(*Command).Execute(0xc82013ba00, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x2d
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:28 +0xf0
main.main()
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:28 +0x28

goroutine 18 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x18f7840)
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x67
created by github.com/golang/glog.init.1
    /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297

goroutine 27 [syscall]:
os/signal.loop()
    /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
    /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 32 [IO wait]:
net.runtime_pollWait(0x1d4fe68, 0x72, 0xc82005c080)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8203320d0, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203320d0, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820332070, 0xc820411000, 0x800, 0x800, 0x0, 0x1d0f028, 0xc82005c080)
    /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820092010, 0xc820411000, 0x800, 0x800, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820330360, 0x1d50278, 0xc820092010, 0x5, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc82033e000, 0x13fb817, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc82033e000, 0xc8203f6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x1d1b420, 0xc82033e000, 0xc8202d0b58, 0xc8203f6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8202f8ae0, 0xc8203f6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8202f1620)
    /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8202f1620, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8202d0b00)
    /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 49 [select]:
net/http.(*persistConn).writeLoop(0xc8202d0b00)
    /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:686 +0xc9d
```

The resource controller was originally created with the following yml:

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: nodetest2
  labels:
    name: nodetest-new
spec:
  replicas: 1
  selector:
    name: nodetest-new
  template:
    metadata:
      labels:
        name: nodetest-new
    spec:
      imagePullSecrets:
        - name: nectar-registry-pull-secret
      containers:
        - name: nodetest-container
          image: 814863397952.dkr.ecr.us-east-1.amazonaws.com/nodetest:latest
          ports:
            - containerPort: 8080
              name: nodetest
```

**Comment by AdoHe** [comment]
@olafurnielsen could you provider your kubernetes version? `kubectl version` can give you that info. As I can see you are rolling-update a rc using the same image I tried on my local, it's ok.

**Comment by olafurnielsen** [comment]
Sure, see the version below. I've tried this with different images but always get the same error.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.7", GitCommit:"c0fd002fbb25d6a6cd8427d28b8ec78379c354a0", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.8_coreos.0", GitCommit:"197bd0e32d7f81ae3cac410a959a957f88e48419", GitTreeState:"clean"}
```

**Comment by AdoHe** [comment]
@olafurnielsen seems you are using mismatched client and server, could you update your server version to the latest v1.2.0? we just release this stable version.

**Comment by olafurnielsen** [comment]
Ok, I didn't realize that these versions are supposed to match. When I ran the same verisons on both sides I had no problems. Thank you.

kubectl should perhaps catch an error like this and give you feedback on the client/server incompatability.

**Comment by AdoHe** [comment]
I will take a deep look later, and find a more elegant solution.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.
