### ISSUE TITLE
pkg/registry/job/etcd: TestDelete: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#23682]
From: https://github.com/kubernetes/kubernetes/pull/23532#issuecomment-202242875

https://console.developers.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/23532/kubernetes-pull-build-test-e2e-gce/33943/artifacts/

```
=== RUN   TestDelete
E0330 09:36:09.761582    9905 utils.go:188] Error when getting etcd cluster members
--- FAIL: TestDelete (15.62s)
	utils.go:241: Unexpected error in waitUntilUp (timeout on waiting for etcd cluster)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x90bd28]

goroutine 89 [running]:
panic(0x1a30c80, 0xc8200140c0)
	/usr/local/go/src/runtime/panic.go:464 +0x3ff
testing.tRunner.func1(0xc82015e900)
	/usr/local/go/src/testing/testing.go:467 +0x22a
panic(0x1a30c80, 0xc8200140c0)
	/usr/local/go/src/runtime/panic.go:426 +0x521
k8s.io/kubernetes/pkg/registry/registrytest.NewEtcdStorage(0xc82015e900, 0x1c53320, 0xa, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/registrytest/etcd.go:40 +0x208
k8s.io/kubernetes/pkg/registry/job/etcd.newStorage(0xc82015e900, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/job/etcd/etcd_test.go:36 +0x48
k8s.io/kubernetes/pkg/registry/job/etcd.TestDelete(0xc82015e900)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/job/etcd/etcd_test.go:126 +0x41
testing.tRunner(0xc82015e900, 0x274b9d0)
	/usr/local/go/src/testing/testing.go:473 +0xdd
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0xae3
FAIL	k8s.io/kubernetes/pkg/registry/job/etcd	23.635s
```

**Comment by bprashanth** [comment]
This is happening in various etcd unittests: https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/23755/kubernetes-pull-test-unit-integration/19951/?pli=1

**Comment by fejta** [comment]
Made a best guess at assigning this flake with no owner for 2 weeks

**Comment by lavalamp** [comment]
@timothysc any chance you could look at this?

**Comment by timothysc** [comment]
@yujuhong is there a bisected root to this flake?

**Comment by yujuhong** [comment]
@timothysc I have no idea whether this is still happening or not. #21954 may also be related, but it's even older.

**Comment by timothysc** [comment]
@k8s-oncall - are we still seeing this?  There have were some quick-turn merges on Friday, but I have not seen traffic since then.

**Comment by timothysc** [comment]
Going to close, please re-open if issue persists.
