### ISSUE TITLE
when i set -metric_resolution=5s ,heapster will be closed with panic. 

### ISSUE THREAD

**Issue by fzu-huang** [kubernetes/kubernetes#24659]
Here is the log.

```
I0422 18:31:10.000361    7605 manager.go:79] Scraping metrics start: 2016-04-22 18:31:00 +0800 CST, end: 2016-04-22 18:31:05 +0800 CST
I0422 18:31:10.106464    7605 manager.go:152] ScrapeMetrics: time: 105.933682ms size: 73
W0422 18:31:10.106671    7605 node_aggregator.go:44] Failed to find node: node:10.126.72.33
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x5c8549]

goroutine 219 [running]:
panic(0x1398980, 0xc8200100f0)
    /usr/local/go1.6.1/src/runtime/panic.go:464 +0x3e6
k8s.io/heapster/metrics/processors.aggregate(0xc8204ebce0, 0x0, 0xc82000b400, 0x4, 0x4, 0x0, 0x0)
    /go/src/k8s.io/heapster/metrics/processors/helper.go:29 +0x179
k8s.io/heapster/metrics/processors.(*NodeAggregator).Process(0xc820418640, 0xc8203d3500, 0xc8208f5400, 0x0, 0x0)
    /go/src/k8s.io/heapster/metrics/processors/node_aggregator.go:46 +0x539
k8s.io/heapster/metrics/manager.process(0x7f86cb5c6f38, 0xc820418640, 0xc8203d3500, 0x0, 0x0, 0x0)
    /go/src/k8s.io/heapster/metrics/manager/manager.go:152 +0x1bd
k8s.io/heapster/metrics/manager.(*realManager).housekeep.func1(0xeceabf464, 0x0, 0x1d4e1e0, 0xeceabf469, 0x0, 0x1d4e1e0, 0xc820017740)
    /go/src/k8s.io/heapster/metrics/manager/manager.go:131 +0x165
created by k8s.io/heapster/metrics/manager.(*realManager).housekeep
    /go/src/k8s.io/heapster/metrics/manager/manager.go:143 +0x33e
```

I only ran 3 kube-slavers(Ver.1.2.2).  So I think it is not k8s' problem. Now I have  to ehance  `metric_resolution` from 5 seconds to 20 seconds to avoid this panic. And I am not sure  whether heapster can collection metrics in a short time.

**Comment by dchen1107** [comment]
cc/ @mwielgus
