### ISSUE TITLE
When output format is empty string, kubectl panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ye** [kubernetes/kubernetes#24931]
```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}

$ kubectl config view --output=""
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x2c1b36]

goroutine 1 [running]:
k8s.io/kubernetes/pkg/kubectl.(*VersionedPrinter).PrintObj(0xc2080fcc80, 0x1c93db0, 0xc208192fc0, 0x1c8fff0, 0xc20804e008, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource_printer.go:189 +0x426
k8s.io/kubernetes/pkg/kubectl/cmd/config.ViewOptions.Run(0x1c949d0, 0xc208050eb0, 0x100, 0x1c8fff0, 0xc20804e008, 0x1c94a88, 0xc2080fcc80, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/config/view.go:113 +0x19d
k8s.io/kubernetes/pkg/kubectl/cmd/config.func·009(0xc2081a6a00, 0xc208135490, 0x0, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/config/view.go:77 +0x3e2
github.com/spf13/cobra.(*Command).execute(0xc2081a6a00, 0xc208135400, 0x1, 0x1, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:572 +0x82f
github.com/spf13/cobra.(*Command).ExecuteC(0xc208073600, 0xc2081a6a00, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x4db
github.com/spf13/cobra.(*Command).Execute(0xc208073600, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x3a
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:28 +0x101
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:28 +0x2f

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1a3f640)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 13 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

$ kubectl config view -o ""
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x2c1b36]

goroutine 1 [running]:
k8s.io/kubernetes/pkg/kubectl.(*VersionedPrinter).PrintObj(0xc2080c8c40, 0x1c93dd8, 0xc20819cfc0, 0x1c8fff0, 0xc208048008, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource_printer.go:189 +0x426
k8s.io/kubernetes/pkg/kubectl/cmd/config.ViewOptions.Run(0x1c94ab8, 0xc20800af50, 0x100, 0x1c8fff0, 0xc208048008, 0x1c94b70, 0xc2080c8c40, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/config/view.go:113 +0x19d
k8s.io/kubernetes/pkg/kubectl/cmd/config.func·009(0xc2081aea00, 0xc2081a5300, 0x0, 0x2)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/config/view.go:77 +0x3e2
github.com/spf13/cobra.(*Command).execute(0xc2081aea00, 0xc2081a5140, 0x2, 0x2, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:572 +0x82f
github.com/spf13/cobra.(*Command).ExecuteC(0xc20807d600, 0xc2081aea00, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x4db
github.com/spf13/cobra.(*Command).Execute(0xc20807d600, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x3a
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:28 +0x101
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:28 +0x2f

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1a3f640)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 13 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35
```

**Comment by kargakis** [comment]
The panic is bad but I would expect the command to return to me valid outputs I could use and error out. @AdoHe we should also make sure the nil dereference in the resource printer gets handled. Your PR justs masks it.

**Comment by ye** [comment]
Btw, I didn't make up the empty string on purpose. It was documented in the `kubectl config view -h` output and it was seen as the default setting of `--output`. So perhaps someone should also fix the help text so newbies like me don't cause crashes as easily? Thanks.

```
$ kubectl config view -h
Displays merged kubeconfig settings or a specified kubeconfig file.

You can use --output jsonpath={...} to extract specific values using a jsonpath expression.

Usage:
  kubectl config view [flags]

Examples:
# Show Merged kubeconfig settings.
kubectl config view

# Get the password for the e2e user
kubectl config view -o jsonpath='{.users[?(@.name == "e2e")].user.password}'

Flags:
      --flatten[=false]: flatten the resulting kubeconfig file into self contained output (useful for creating portable kubeconfig files)
      --merge[=true]: merge together the full hierarchy of kubeconfig files
      --minify[=false]: remove all information not used by current-context from the output
      --no-headers[=false]: When using the default output, don't print headers.
  -o, --output="": Output format. One of: json|yaml|wide|name|go-template=...|go-template-file=...|jsonpath=...|jsonpath-file=... See golang template [http://golang.org/pkg/text/template/#pkg-overview] and jsonpath template [http://releases.k8s.io/release-1.2/docs/user-guide/jsonpath.md].
      --output-version="": Output the formatted object with the given group version (for ex: 'extensions/v1beta1').
      --raw[=false]: display raw byte data
  -a, --show-all[=false]: When printing, show all resources (default hide terminated pods.)
      --show-labels[=false]: When printing, show all labels as the last column (default hide labels column)
      --sort-by="": If non-empty, sort list types using this field specification.  The field specification is expressed as a JSONPath expression (e.g. '{.metadata.name}'). The field in the API resource specified by this JSONPath expression must be an integer or a string.
      --template="": Template string or path to template file to use when -o=go-template, -o=go-template-file. The template format is golang templates [http://golang.org/pkg/text/template/#pkg-overview].

Global Flags:
      --alsologtostderr[=false]: log to standard error as well as files
      --certificate-authority="": Path to a cert. file for the certificate authority.
      --client-certificate="": Path to a client certificate file for TLS.
      --client-key="": Path to a client key file for TLS.
      --cluster="": The name of the kubeconfig cluster to use
      --context="": The name of the kubeconfig context to use
      --insecure-skip-tls-verify[=false]: If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure.
      --kubeconfig="": use a particular kubeconfig file
      --log-backtrace-at=:0: when logging hits line file:N, emit a stack trace
      --log-dir="": If non-empty, write log files in this directory
      --log-flush-frequency=5s: Maximum number of seconds between log flushes
      --logtostderr[=true]: log to standard error instead of files
      --match-server-version[=false]: Require server version to match client version
      --namespace="": If present, the namespace scope for this CLI request.
      --password="": Password for basic authentication to the API server.
  -s, --server="": The address and port of the Kubernetes API server
      --stderrthreshold=2: logs at or above this threshold go to stderr
      --token="": Bearer token for authentication to the API server.
      --user="": The name of the kubeconfig user to use
      --username="": Username for basic authentication to the API server.
      --v=0: log level for V logs
      --vmodule=: comma-separated list of pattern=N settings for file-filtered logging
```

**Comment by fabianofranz** [comment]
I'd expect that we validate what's provided to `--output` and print the valid options if something unexpected was provided (including blank string). 

But the way we print flags that expect strings (and defaults to empty) in help can lead to this kind of confusion and other issues (on Windows, for example).

A few ideas:

```
--output=                        docker does this
--output=STRING
--output=FORMAT                  most shell commands
--output=JSON|YAML|wide|...      too large, but avoids the need to print accepted types on description
```

pflag could have a "select" type that takes a list of valid options (and validates/throws errors automatically).

**Comment by kargakis** [comment]
Agreed with @fabianofranz that the current way of showing flags in the help is not optimal.

cc: @kubernetes/kubectl

**Comment by AdoHe** [comment]
@kargakis I did agree that panic is bad, we should avoid this. The problem is if a user did use an empty output, how to handle this more properly. In PR #24955 you commented that we should not override user settings, it seems we should error out directly in this situation. Besides, nil dereference in the resource printer should be handled, will add this.
