### ISSUE TITLE
Builders failing with no space error

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#25017]
Since ~11:50 on april 29th (yesterday) some builders are failing with no space errors:
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-serial/1187/console
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke-ingress-release-1.2/
```
02:17:00 Caused by: java.io.IOException: remote file operation failed: /var/lib/jenkins/workspace/kubernetes-e2e-gke-ingress at hudson.remoting.Channel@7264b571:jenkins-builder-3: java.io.IOException: No space left on device
```

@kubernetes/goog-testing

**Comment by ixdy** [comment]
At least on `jenkins-builder-3`, there are a lot of `ws-cleanup` directories in `/var/lib/jenkins` dating back to April 15, all of which were eating up most of the disk. Jenkins is not supposed to schedule jobs on machines with no disk, but it was reporting free space of "n/a" on `jenkins-builder-3`, so I guess it figured ¯\\\_(ツ)\_/¯ and decided to schedule things there anyway.

That VM should be OK now. The others are reporting sufficient space, but I'll look for rogue `ws-cleanup` dirs on them, too.

**Comment by bprashanth** [comment]
They're passing now, thanks

**Comment by quinton-hoole** [comment]
I saw this again today:

http://goto.google.com/k8s-test/job/kubernetes-e2e-gce-ubernetes-lite/4106/

```
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
[PostBuildScript] - Execution post build scripts.
FATAL: Unable to produce a script file
java.io.IOException: Failed to create a temp file on /var/lib/jenkins/workspace/kubernetes-e2e-gce-ubernetes-lite
        at hudson.FilePath.createTextTempFile(FilePath.java:1410)
        at hudson.tasks.CommandInterpreter.createScriptFile(CommandInterpreter.java:142)
        at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:80)
        at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:64)
        at org.jenkinsci.plugins.postbuildscript.PostBuildScript.processBuildSteps(PostBuildScript.java:204)
        at org.jenkinsci.plugins.postbuildscript.PostBuildScript.processScripts(PostBuildScript.java:143)
        at org.jenkinsci.plugins.postbuildscript.PostBuildScript._perform(PostBuildScript.java:105)
        at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:85)
        at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
        at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
        at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
        at hudson.model.Build$BuildExecution.post2(Build.java:185)
        at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
        at hudson.model.Run.execute(Run.java:1766)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
        at hudson.model.ResourceController.execute(ResourceController.java:98)
        at hudson.model.Executor.run(Executor.java:410)
Caused by: java.io.IOException: remote file operation failed: /var/lib/jenkins/workspace/kubernetes-e2e-gce-ubernetes-lite at hudson.remoting.Channel@31818b64:agent-light-20160524-1: java.io.IOException: No space left on device
```

**Comment by ixdy** [comment]
@fejta can you rebuild the Jenkins agents that have disks that are too small?

**Comment by ixdy** [comment]
In particular, `agent-light-20160524-1` is the problem VM.

**Comment by fejta** [comment]
@ixdy please run https://github.com/kubernetes/test-infra/pull/63 (and I strongly recommend getting that committed)
