### ISSUE TITLE
Integration test failure: deployment/etcd

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#25047]
[test artifacts](https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/24804/kubernetes-pull-test-unit-integration/23757/)

>
FAIL	k8s.io/kubernetes/pkg/registry/deployment/etcd	15.668s

**Comment by fejta** [comment]
Assigning to @wojtek-t per https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/OWNERS

**Comment by pwittrock** [comment]
Janet probably has more state on this.  @wojtek-t if you have already started, feel free to take it back

**Comment by janetkuo** [comment]
```
=== RUN   TestCreate
E0502 12:43:47.954555   32628 utils.go:192] Error when getting etcd cluster members
--- FAIL: TestCreate (12.32s)
	utils.go:245: Unexpected error in waitUntilUp (timeout on waiting for etcd cluster)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x87b381]

goroutine 117 [running]:
panic(0x1d3afa0, 0xc8200120c0)
	/usr/local/go/src/runtime/panic.go:464 +0x3ff
testing.tRunner.func1(0xc8200daa20)
	/usr/local/go/src/testing/testing.go:467 +0x22a
panic(0x1d3afa0, 0xc8200120c0)
	/usr/local/go/src/runtime/panic.go:426 +0x521
k8s.io/kubernetes/pkg/registry/registrytest.NewEtcdStorage(0xc8200daa20, 0x1f8e450, 0xa, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/registrytest/etcd.go:41 +0x211
k8s.io/kubernetes/pkg/registry/deployment/etcd.newStorage(0xc8200daa20, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/deployment/etcd/etcd_test.go:41 +0x56
k8s.io/kubernetes/pkg/registry/deployment/etcd.TestCreate(0xc8200daa20)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/deployment/etcd/etcd_test.go:85 +0x44
testing.tRunner(0xc8200daa20, 0x2bc9cc0)
	/usr/local/go/src/testing/testing.go:473 +0xdd
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0xae3
FAIL	k8s.io/kubernetes/pkg/registry/deployment/etcd	15.668s
```

**Comment by janetkuo** [comment]
`EtcdTestServer` timed out and return `nil` server and then caused `nil pointer dereference`

**Comment by janetkuo** [comment]
timeout for `EtcdTestServer` to be up is 5s; should we wait longer?

**Comment by janetkuo** [comment]
2 issues here: 

1. 5s timeout is too short 
2. Shouldn't return nil server but fail now 

Fixing in #25047
