### ISSUE TITLE
Flake: unit test federation/cmd/federated-apiserver/app.TestRun

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#25138]
Slightly outdated failure, so it might be fixed. Doesn't look like https://github.com/kubernetes/kubernetes/issues/24952: 
```
=== RUN   TestValidateClusterStatusUpdate
--- PASS: TestValidateClusterStatusUpdate (0.00s)
PASS
ok  	k8s.io/kubernetes/federation/apis/federation/validation	1.045s
=== RUN   TestLongRunningRequestRegexp
--- PASS: TestLongRunningRequestRegexp (0.00s)
=== RUN   TestRun
I0430 14:52:03.646139   31121 server.go:93] Will report 172.17.0.3 as public IP address.
I0430 14:52:03.646468   31121 plugins.go:71] No cloud provider specified.
I0430 14:52:03.647147   31121 genericapiserver.go:287] Node port range unspecified. Defaulting to 30000-32767.
--- FAIL: TestRun (0.04s)
	<autogenerated>:31: 
                        
	Error Trace:	server_test.go:171
		
			server_test.go:97
		
	Error:		Expected value not to be nil.
		
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4b2ad2]

goroutine 45 [running]:
panic(0x2400980, 0xc8200120c0)
	/usr/local/go/src/runtime/panic.go:464 +0x3ff
testing.tRunner.func1(0xc8202d4000)
	/usr/local/go/src/testing/testing.go:467 +0x22a
panic(0x2400980, 0xc8200120c0)
	/usr/local/go/src/runtime/panic.go:426 +0x521
k8s.io/kubernetes/federation/cmd/federated-apiserver/app.testAPIGroupList(0xc8202d4000)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/cmd/federated-apiserver/app/server_test.go:172 +0xc72
k8s.io/kubernetes/federation/cmd/federated-apiserver/app.TestRun(0xc8202d4000)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/cmd/federated-apiserver/app/server_test.go:97 +0x359
testing.tRunner(0xc8202d4000, 0x37fce78)
	/usr/local/go/src/testing/testing.go:473 +0xdd
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0xae3
FAIL	k8s.io/kubernetes/federation/cmd/federated-apiserver/app	0.247s
=== RUN   TestGenerateStorageVersionMap
--- PASS: TestGenerateStorageVersionMap (0.00s)
```

**Comment by fejta** [comment]
Assigning to @nikhiljindal per https://github.com/kubernetes/kubernetes/blob/master/federation/cmd/federated-apiserver/OWNERS

**Comment by nikhiljindal** [comment]
Doesnt seem to have flaked in ~month.
Closing. (Bot will anyway file a separate issue if it flakes again)
