### ISSUE TITLE
Unable to cleanly stop controllers that use delta fifo in integration tests

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#25412]
I was debugging an integration test flake, and encountered a deadlock that prevents stopping controllers that use a delta fifo.  This prevents cleanly closing a server that a controller is operating against in an integration test.

The root cause is there is no way to tell a `DeltaFifo` to stop waiting:
https://github.com/kubernetes/kubernetes/blob/master/pkg/client/cache/delta_fifo.go#L370

This is invoked by the controller framework `processLoop` function, which never returns so the `wait.Until` that took a `stopCh` is irrelevant since the previous invocation blocks forever waiting for the `DeltaFifo`.

```
goroutine 139 [semacquire]:
sync.runtime_Syncsemacquire(0xc8200e0e98)
    /usr/local/go/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc8200e0e88)
    /usr/local/go/src/sync/cond.go:63 +0x9b
k8s.io/kubernetes/pkg/client/cache.(*DeltaFIFO).Pop(0xc8200e0e70, 0x0, 0x0)
    /home/decarr/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/delta_fifo.go:370 +0xb2
k8s.io/kubernetes/pkg/controller/framework.(*Controller).processLoop(0xc8204ca070)
    /home/decarr/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:127 +0x44
k8s.io/kubernetes/pkg/controller/framework.(*Controller).(k8s.io/kubernetes/pkg/controller/framework.processLoop)-fm()
    /home/decarr/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:103 +0x20
k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc820045e60)
    /home/decarr/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:66 +0x4b
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc820045e60, 0x3b9aca00, 0x0, 0xc82001fc20)
    /home/decarr/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:67 +0x68
k8s.io/kubernetes/pkg/util/wait.Until(0xc820045e60, 0x3b9aca00, 0xc82001fc20)
    /home/decarr/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x3e
k8s.io/kubernetes/pkg/controller/framework.(*Controller).Run(0xc8204ca070, 0xc82001fc20)
    /home/decarr/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:103 +0x1c2
k8s.io/kubernetes/pkg/controller/framework.(*sharedIndexInformer).Run(0xc82001fc80, 0xc82001fc20)
    /home/decarr/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/shared_informer.go:151 +0x483
created by k8s.io/kubernetes/pkg/controller/replication.(*ReplicationManager).Run
    /home/decarr/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/replication/replication_controller.go:247 +0x1ea
```

/cc @lavalamp @deads2k

**Comment by lavalamp** [comment]
OK, yeah, we should add a shutdown path. One idea: the controller can add a sentinel item and stop calling Pop() when it turns up.

**Comment by deads2k** [comment]
> OK, yeah, we should add a shutdown path. One idea: the controller can add a sentinel item and stop calling Pop() when it turns up.

How about setting a marker variable (close a channel?) and then `f.cond.broadcast`?  Then we get a choice of adding a `Stop` method to the fifo or spawning go funcs for them that wait on a stop channel like everything else.
