### ISSUE TITLE
exception on GET /api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/metric-export

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#25547]
Saw the following on 1.2.4 cluster:

```
I0512 19:59:49.688503       5 handlers.go:152] GET /api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/metric-export: (1.094504459s) 503
goroutine 798328 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc24b9e9f80, 0x1f7)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:214 +0xa6
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc24b9e9f80, 0x1f7)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:193 +0x32
k8s.io/kubernetes/pkg/apiserver/metrics.(*responseWriterDelegator).WriteHeader(0xc20dd7a2d0, 0x1f7)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:117 +0x53
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc227a1c450, 0x7f30041b2700, 0xc23b7fb578, 0xc2152fb110)
        /usr/src/go/src/net/http/httputil/reverseproxy.go:159 +0x708
k8s.io/kubernetes/pkg/apiserver.(*ProxyHandler).ServeHTTP(0xc208200d00, 0x7f30041b2700, 0xc23b7fb578, 0xc2275f1ee0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/proxy.go:205 +0x2574
k8s.io/kubernetes/pkg/apiserver.func·002(0xc20dd7a150, 0xc20d891e00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/api_installer.go:859 +0x60
k8s.io/kubernetes/pkg/apiserver/metrics.func·001(0xc20dd7a150, 0xc20d891e00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:101 +0x269
github.com/emicklei/go-restful.(*Container).dispatch(0xc20819c120, 0x7f30041b1fa8, 0xc24b9e9f80, 0xc2275f1ee0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:249 +0xf5e
github.com/emicklei/go-restful.*Container.(github.com/emicklei/go-restful.dispatch)·fm(0x7f30041b1fa8, 0xc24b9e9f80, 0xc2275f1ee0)
        /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:95 +0x45
net/http.HandlerFunc.ServeHTTP(0xc20845ae90, 0x7f30041b1fa8, 0xc24b9e9f80, 0xc2275f1ee0)
        /usr/src/go/src/net/http/server.go:1265 +0x41
net/http.(*ServeMux).ServeHTTP(0xc208214cc0, 0x7f30041b1fa8, 0xc24b9e9f80, 0xc2275f1ee0)
```

cc @vishh @piosz 
Not sure who is the right person for this.

**Comment by vishh** [comment]
cc @mwielgus

**Comment by piosz** [comment]
cc @a-robinson

**Comment by piosz** [comment]
@nikhiljindal could you please elaborate? IIUC this is log from apiserver. Did apiserver crash in this case? Did Heapster crash? Do you have logs from Heapster?

**Comment by a-robinson** [comment]
I believe that's just the response / stack trace the apiserver generates when it's asked to proxy a request to a service that doesn't have any endpoints up and running.

**Comment by a-robinson** [comment]
I assume that there wasn't a valid heapster pod in the running state at the time, right?
