### ISSUE TITLE
integration flake: panic in pkg/controller/framework/controller.go:108

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#25594]
See [kubernetes-pull-test-unit-integration/25720](https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25564/kubernetes-pull-test-unit-integration/25720/)

```
I0513 12:49:32.753078    8682 nodecontroller.go:144] Sending events to api server.
I0513 12:49:32.753558    8682 meta.go:46] Calling Accessor on non-internal object: *api.ServiceList
I0513 12:49:32.755728    8682 meta.go:46] Calling Accessor on non-internal object: *api.ServiceList
I0513 12:49:32.756555    8682 integration.go:216] Using /tmp/kubelet_integ_1.791540896 as root dir for kubelet #1
W0513 12:49:32.756685    8682 server.go:632] No api server defined - no events will be sent to API server.
I0513 12:49:32.756746    8682 server.go:694] Adding manifest file: /tmp/kubelet_integ_1.791540896/config945229695
I0513 12:49:32.756771    8682 file.go:47] Watching path "/tmp/kubelet_integ_1.791540896/config945229695"
I0513 12:49:32.756787    8682 server.go:700] Adding manifest url "http://127.0.0.1:58096/manifest" with HTTP header map[]
I0513 12:49:32.756810    8682 http.go:55] Watching URL http://127.0.0.1:58096/manifest
I0513 12:49:32.757239    8682 reflector.go:213] Starting reflector *api.Pod (0) from k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:342
I0513 12:49:32.757662    8682 meta.go:46] Calling Accessor on non-internal object: *api.ServiceList
I0513 12:49:32.758111    8682 meta.go:46] Calling Accessor on non-internal object: *api.ServiceList
I0513 12:49:32.758257    8682 meta.go:46] Calling Accessor on non-internal object: *api.PersistentVolumeClaimList
I0513 12:49:32.759232    8682 endpoints_controller.go:316] Finished syncing service "default/kubernetes" endpoints. (56.668Âµs)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x104e487]

goroutine 424 [running]:
panic(0x29e1bc0, 0xc8200120d0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
k8s.io/kubernetes/pkg/controller/framework.(*Controller).HasSynced(0x0, 0x4640f0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:108 +0x47
k8s.io/kubernetes/pkg/controller/framework.(*sharedIndexInformer).HasSynced(0xc820a00900, 0xa2f91b)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/shared_informer.go:161 +0x25
k8s.io/kubernetes/pkg/controller/framework.(SharedIndexInformer).HasSynced-fm(0xe00000028)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go:109 +0x32
k8s.io/kubernetes/pkg/controller/endpoint.(*EndpointController).syncService(0xc820a009c0, 0xc82112a3e0, 0x12)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go:319 +0xe5
k8s.io/kubernetes/pkg/controller/endpoint.(*EndpointController).worker.func1(0xc820a009c0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go:308 +0xe3
k8s.io/kubernetes/pkg/controller/endpoint.(*EndpointController).worker(0xc820a009c0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go:309 +0x21
k8s.io/kubernetes/pkg/controller/endpoint.(*EndpointController).(k8s.io/kubernetes/pkg/controller/endpoint.worker)-fm()
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go:160 +0x20
k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc820229340)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:66 +0x4b
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc820229340, 0x3b9aca00, 0x0, 0xc82000efc0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:67 +0x68
k8s.io/kubernetes/pkg/util/wait.Until(0xc820229340, 0x3b9aca00, 0xc82000efc0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x3e
created by k8s.io/kubernetes/pkg/controller/endpoint.(*EndpointController).Run
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go:160 +0x147
!!! Error in ./hack/test-integration.sh:58
  'KUBE_TEST_API_VERSIONS="$1" "${KUBE_OUTPUT_HOSTBIN}/integration" --v=${LOG_LEVEL} --max-concurrency="${KUBE_INTEGRATION_TEST_MAX_CONCURRENCY}" --watch-cache=true' exited with status 2
Call stack:
  1: ./hack/test-integration.sh:58 runTests(...)
  2: ./hack/test-integration.sh:83 main(...)
```

**Comment by fejta** [comment]
Assigning to @derekwaynecarr per https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/OWNERS

**Comment by derekwaynecarr** [comment]
Ouch will investigate this week!

**Comment by dims** [comment]
@derekwaynecarr @fejta Does not look like this has re-occured since it was filed. Should we close this out?

**Comment by derekwaynecarr** [comment]
I want to take one more look at code tomorrow and if nothing strikes me, I
will close.

**Comment by derekwaynecarr** [comment]
Sent a PR with a fix to prevent the flake from occurring.

**Comment by derekwaynecarr** [comment]
I am going to close this, we can re-open if it re-appears.

I suspect the fix was here: https://github.com/kubernetes/kubernetes/pull/25669
