### ISSUE TITLE
Cassandra Seed Provider - Code improvement

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#25616]
Low priority issue, but would be nice to have so this docker "could" run outside of k8s.  We are getting the following exception because it is trying to load a file that is not there, and the exception is not trapped.

```java
WARN  17:18:15 Request to kubernetes apiserver failed, using default seeds in cassandra.yaml
java.nio.file.NoSuchFileException: /var/run/secrets/kubernetes.io/serviceaccount/token
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[na:1.8.0_72-internal]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_72-internal]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_72-internal]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[na:1.8.0_72-internal]
	at java.nio.file.Files.newByteChannel(Files.java:361) ~[na:1.8.0_72-internal]
	at java.nio.file.Files.newByteChannel(Files.java:407) ~[na:1.8.0_72-internal]
	at java.nio.file.Files.readAllBytes(Files.java:3152) ~[na:1.8.0_72-internal]
	at io.k8s.cassandra.KubernetesSeedProvider.getServiceAccountToken(KubernetesSeedProvider.java:247) ~[kubernetes-cassandra.jar:na]
	at io.k8s.cassandra.KubernetesSeedProvider.getSeeds(KubernetesSeedProvider.java:116) ~[kubernetes-cassandra.jar:na]
	at org.apache.cassandra.config.DatabaseDescriptor.getSeeds(DatabaseDescriptor.java:1332) [apache-cassandra-3.4.jar:3.4]
	at org.apache.cassandra.service.StorageService.shouldBootstrap(StorageService.java:775) [apache-cassandra-3.4.jar:3.4]
	at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:808) [apache-cassandra-3.4.jar:3.4]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:727) [apache-cassandra-3.4.jar:3.4]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:613) [apache-cassandra-3.4.jar:3.4]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:349) [apache-cassandra-3.4.jar:3.4]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:551) [apache-cassandra-3.4.jar:3.4]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:680) [apache-cassandra-3.4.jar:3.4]
```

**Comment by chrislovecnm** [comment]
@bgrant0607 filing an issue on myself 😄

**Comment by chrislovecnm** [comment]
https://github.com/kubernetes/kubernetes/pull/26022 resolved this
