### ISSUE TITLE
rktnetes: Density tests fails when running 50 pods per node

### ISSUE THREAD

**Issue by yifan-gu** [kubernetes/kubernetes#25789]
Doing benchmark on rktnetes, the Density test works fine with 3 and 30 pods per node. But fails when running 50 pods per node. Because some pods failed to start at the first time. Here is the errors I got from `kubectl get events`

```
32m       32m       1         density150-0-ab0c044c-1cb3-11e6-875e-42010af00002-zmg6e   Pod       spec.containers{density150-0-ab0c044c-1cb3-11e6-875e-42010af00002}   Warning   Failed      {kubelet yifan-rkt-minion-55e4}   Failed to create rkt container with error: failed to run [prepare --quiet --pod-manifest /tmp/manifest-density150-0-ab0c044c-1cb3-11e6-875e-42010af00002-zmg6e-097668574 --stage1-path /opt/rkt/stage1-coreos.aci]: exit status 2
stdout: 
stderr: runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f055f5a469b m=0

goroutine 0 [idle]:

goroutine 1 [chan receive, locked to thread]:
runtime.gopark(0xfb20b0, 0xc8200181a8, 0xe2eb80, 0xc, 0x17, 0x3)
          /usr/lib/go/src/runtime/proc.go:262 +0x163 fp=0xc820057e38 sp=0xc820057e10
runtime.goparkunlock(0xc8200181a8, 0xe2eb80, 0xc, 0x47c317, 0x3)
          /usr/lib/go/src/runtime/proc.go:268 +0x54 fp=0xc820057e70 sp=0xc820057e38
runtime.chanrecv(0xb904e0, 0xc820018150, 0x0, 0xc820057f01, 0x450000)
          /usr/lib/go/src/runtime/chan.go:470 +0x49f fp=0xc820057ef8 sp=0xc820057e70
runtime.chanrecv1(0xb904e0, 0xc820018150, 0x0)
          /usr/lib/go/src/runtime/chan.go:355 +0x2b fp=0xc820057f28 sp=0xc820057ef8
runtime.gcenable()
          /usr/lib/go/src/runtime/mgc.go:192 +0x76 fp=0xc820057f50 sp=0xc820057f28
runtime.main()
          /usr/lib/go/src/runtime/proc.go:150 +0x138 fp=0xc820057fa0 sp=0xc820057f50
runtime.goexit()
          /usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820057fa8 sp=0xc820057fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
          /usr/lib/go/src/runtime/asm_amd64.s:1998 +0x1

rax    0x0
rbx    0x7f055f9157a0
rcx    0x7f055f5a469b
rdx    0x6
rdi    0x305c
rsi    0x305c
rbp    0x7ffe07f28ca0
rsp    0x7ffe07f28ca0
r8     0x7f055f9168e0
r9     0x7f055fd51740
r10    0x8
r11    0x206
r12    0x325e2f0
r13    0xfae384
r14    0x0
r15    0x8
rip    0x7f055f5a469b
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
```

And

```
 Error syncing pod, skipping: failed to SyncPod: failed to run [prepare --quiet --pod-manifest /tmp/manifest-density150-0-ab0c044c-1cb3-11e6-875e-42010af00002-wn3e7-687506860 --stage1-path /opt/rkt/stage1-coreos.aci]: fork/exec /opt/rkt/rkt: resource temporarily unavailable
stdout: 
stderr: 
```

However, after several restarts, all the pods seem to be in the RUNNING state:

```
NAMESPACE                 NAME                                                      READY     STATUS    RESTARTS   AGE
e2e-tests-density-l2rrn   density150-0-ab0c044c-1cb3-11e6-875e-42010af00002-053v5   1/1       Running   1          33m
e2e-tests-density-l2rrn   density150-0-ab0c044c-1cb3-11e6-875e-42010af00002-0ccby   1/1       Running   1          33m
e2e-tests-density-l2rrn   density150-0-ab0c044c-1cb3-11e6-875e-42010af00002-0f7tw   1/1       Running   1          33m
e2e-tests-density-l2rrn   density150-0-ab0c044c-1cb3-11e6-875e-42010af00002-0fezx   1/1       Running   1          33m
e2e-tests-density-l2rrn   density150-0-ab0c044c-1cb3-11e6-875e-42010af00002-0tb7k   1/1       Running   2          33m
e2e-tests-density-l2rrn   density150-0-ab0c044c-1cb3-11e6-875e-42010af00002-1z8e9   1/1       Running   1          33m
e2e-tests-density-l2rrn   density150-0-ab0c044c-1cb3-11e6-875e-42010af00002-265yz   1/1       Running   0          33m
e2e-tests-density-l2rrn   density150-0-ab0c044c-1cb3-11e6-875e-42010af00002-266a5   1/1       Running   3          33m
...
```

cc @kubernetes/sig-node @sjpotter @euank @jonboulle @iaguis @alban

**Comment by euank** [comment]
@yifan-gu any further information on this?

**Comment by yujuhong** [comment]
Closing this since relevant issues should be handled in CRI or moved to the rktlet repository.
