### ISSUE TITLE
Resource leak in gce-slow (gcloud crash during teardown)

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#25824]
https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce-slow/5733/

```
11:54:57 + echo '--- /workspace/_artifacts/gcp-resources-before.txt	2016-05-18 11:16:02.858354819 -0700
11:54:57 +++ /workspace/_artifacts/gcp-resources-after.txt	2016-05-18 11:54:57.280829905 -0700
11:54:57 @@ -10 +10,2 @@ [ instance-templates ]
11:54:57 -
11:54:57 +NAME                         MACHINE_TYPE   PREEMPTIBLE  CREATION_TIMESTAMP
11:54:57 +jenkins-e2e-minion-template  n1-standard-2               2016-05-18T11:17:01.936-07:00
11:54:57 @@ -14 +15,2 @@ [ instance-groups ]
11:54:57 -
11:54:57 +NAME                      ZONE           NETWORK      MANAGED  INSTANCES
11:54:57 +jenkins-e2e-minion-group  us-central1-f  jenkins-e2e  Yes      3
11:54:57 @@ -18 +20,4 @@ [ instances ]
11:54:57 -
11:54:57 +NAME                     ZONE           MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP      STATUS
11:54:57 +jenkins-e2e-minion-fr2w  us-central1-f  n1-standard-2               10.240.0.3   104.155.136.230  RUNNING
11:54:57 +jenkins-e2e-minion-ra0h  us-central1-f  n1-standard-2               10.240.0.2   104.154.247.241  RUNNING
11:54:57 +jenkins-e2e-minion-y1oy  us-central1-f  n1-standard-2               10.240.0.4   104.154.246.130  RUNNING
11:54:57 @@ -31,0 +37,3 @@ [ disks ]
11:54:57 +jenkins-e2e-minion-fr2w                           us-central1-f  100      pd-standard  READY
11:54:57 +jenkins-e2e-minion-ra0h                           us-central1-f  100      pd-standard  READY
11:54:57 +jenkins-e2e-minion-y1oy                           us-central1-f  100      pd-standard  READY'
11:54:57 + echo '!!! FAIL: Google Cloud Platform resources leaked while running tests!'
11:54:57 + exit 1
11:54:57 + chmod -R o+r /workspace/_artifacts
11:54:57 --- /workspace/_artifacts/gcp-resources-before.txt	2016-05-18 11:16:02.858354819 -0700
11:54:57 +++ /workspace/_artifacts/gcp-resources-after.txt	2016-05-18 11:54:57.280829905 -0700
11:54:57 @@ -10 +10,2 @@ [ instance-templates ]
11:54:57 -
11:54:57 +NAME                         MACHINE_TYPE   PREEMPTIBLE  CREATION_TIMESTAMP
11:54:57 +jenkins-e2e-minion-template  n1-standard-2               2016-05-18T11:17:01.936-07:00
11:54:57 @@ -14 +15,2 @@ [ instance-groups ]
11:54:57 -
11:54:57 +NAME                      ZONE           NETWORK      MANAGED  INSTANCES
11:54:57 +jenkins-e2e-minion-group  us-central1-f  jenkins-e2e  Yes      3
11:54:57 @@ -18 +20,4 @@ [ instances ]
11:54:57 -
11:54:57 +NAME                     ZONE           MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP      STATUS
11:54:57 +jenkins-e2e-minion-fr2w  us-central1-f  n1-standard-2               10.240.0.3   104.155.136.230  RUNNING
11:54:57 +jenkins-e2e-minion-ra0h  us-central1-f  n1-standard-2               10.240.0.2   104.154.247.241  RUNNING
11:54:57 +jenkins-e2e-minion-y1oy  us-central1-f  n1-standard-2               10.240.0.4   104.154.246.130  RUNNING
11:54:57 @@ -31,0 +37,3 @@ [ disks ]
11:54:57 +jenkins-e2e-minion-fr2w                           us-central1-f  100      pd-standard  READY
11:54:57 +jenkins-e2e-minion-ra0h                           us-central1-f  100      pd-standard  READY
11:54:57 +jenkins-e2e-minion-y1oy                           us-central1-f  100      pd-standard  READY
11:54:57 
!!! FAIL: Google Cloud Platform resources leaked while running tests!
```

**Comment by lavalamp** [comment]
Real problem is that gcloud crashed during teardown:

```

11:50:51 Zone: us-central1-f
11:50:55 ERROR: gcloud crashed (CannotConnectToMetadataServerException): <urlopen error timed out>
11:50:55 
11:50:55 If you would like to report this issue, please run the following command:
11:50:55   gcloud feedback
11:50:55 Traceback (most recent call last):
11:50:55   File "//google-cloud-sdk/lib/gcloud.py", line 53, in <module>
11:50:55     main()
11:50:55   File "//google-cloud-sdk/lib/gcloud.py", line 49, in main
11:50:55     sys.exit(googlecloudsdk.gcloud_main.main())
11:50:55   File "/google-cloud-sdk/lib/googlecloudsdk/gcloud_main.py", line 169, in main
11:50:55     gcloud_cli.Execute()
11:50:55   File "/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 632, in Execute
11:50:55     result = args.cmd_func(cli=self, args=args)
11:50:55   File "/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 1361, in Run
11:50:55     self._parent_group.RunGroupFilter(tool_context, args)
11:50:55   File "/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 1298, in RunGroupFilter
11:50:55     self._parent_group.RunGroupFilter(context, args)
11:50:55   File "/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 1298, in RunGroupFilter
11:50:55     self._parent_group.RunGroupFilter(context, args)
11:50:55   File "/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 1299, in RunGroupFilter
11:50:55     self._common_type().Filter(context, args)
11:50:55   File "/google-cloud-sdk/lib/surface/compute/__init__.py", line 48, in Filter
11:50:55     _DoFilter(context, 'v1')
11:50:55   File "/google-cloud-sdk/lib/surface/compute/__init__.py", line 35, in _DoFilter
11:50:55     utils.UpdateContextEndpointEntries(context, api_client_default)
11:50:55   File "/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 219, in UpdateContextEndpointEntries
11:50:55     compute = core_apis.GetClientInstance('compute', api_client)
11:50:55   File "/google-cloud-sdk/lib/googlecloudsdk/core/apis.py", line 240, in GetClientInstance
11:50:55     http_client = http.Http()
11:50:55   File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/http.py", line 60, in Http
11:50:55     creds = store.Load()
11:50:55   File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 271, in Load
11:50:55     account = properties.VALUES.core.account.Get()
11:50:55   File "/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 1068, in Get
11:50:55     required)
11:50:55   File "/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 1340, in _GetProperty
11:50:55     value = _GetPropertyWithoutDefault(prop, properties_file)
11:50:55   File "/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 1379, in _GetPropertyWithoutDefault
11:50:55     value = callback()
11:50:55   File "/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 609, in _GetGCEAccount
11:50:55     return c_gce.Metadata().DefaultAccount()
11:50:55   File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce.py", line 82, in DefaultAccount
11:50:55     http_errors_to_ignore=(404,))
11:50:55   File "/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 160, in TryFunc
11:50:55     return func(*args, **kwargs), None
11:50:55   File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce.py", line 47, in _ReadNoProxyWithCleanFailures
11:50:55     raise CannotConnectToMetadataServerException(e)
11:50:55 googlecloudsdk.core.credentials.gce.CannotConnectToMetadataServerException: <urlopen error timed out>
11:50:55 INSTANCE_GROUPS=
11:50:55 NODE_NAMES=
11:50:55 Bringing down cluster
11:50:59 ERROR: (gcloud.compute.instance-templates.delete) Some requests did not succeed:
11:50:59  - The instance_template resource 'jenkins-e2e-minion-template' is already being used by 'jenkins-e2e-minion-group'
11:50:59 
```

**Comment by bprashanth** [comment]
```
11:50:51 Zone: us-central1-f
11:50:55 ERROR: gcloud crashed (CannotConnectToMetadataServerException): <urlopen error timed out>
11:50:55 
11:50:55 If you would like to report this issue, please run the following command:
11:50:55   gcloud feedback
```
metadata server again? 

This is just complaining that the previous thing is using the current thing I guess
```
11:50:55     raise CannotConnectToMetadataServerException(e)
11:50:55 googlecloudsdk.core.credentials.gce.CannotConnectToMetadataServerException: <urlopen error timed out>
11:50:55 INSTANCE_GROUPS=
11:50:55 NODE_NAMES=
11:50:55 Bringing down cluster
11:50:59 ERROR: (gcloud.compute.instance-templates.delete) Some requests did not succeed:
11:50:59  - The instance_template resource 'jenkins-e2e-minion-template' is already being used by 'jenkins-e2e-minion-group'
11:50:59 
```

**Comment by bprashanth** [comment]
But it's not a connection refused like we saw before, I wonder if it's using the metadata server hostname and going through our http metadata cache proxy @kubernetes/goog-testing

**Comment by ixdy** [comment]
I turned off the metadata cache server on Sunday. Looks like we still need it after all. :(

**Comment by bprashanth** [comment]
Hmm, this happened again in gce-slow
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-slow/5776
```
Created [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-slow/regions/us-central1/addresses/jenkins-e2e-master-ip].
ERROR: gcloud crashed (CannotConnectToMetadataServerException): <urlopen error timed out>

If you would like to report this issue, please run the following command:
  gcloud feedback
Traceback (most recent call last):
```

**Comment by fejta** [comment]
New agents will have the metadata server, and it will now restart.
