### ISSUE TITLE
Flake: cluster startup: "Staging server tars to Google Storage"

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#25901]
https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce-slow/5770/

```
12:35:12 +++ Staging server tars to Google Storage: gs://kubernetes-staging-999f52ed59/jenkins-e2e-devel
12:35:20 +++ kubernetes-server-linux-amd64.tar.gz uploaded (sha1 = aa6598053206f3db43c28f477617cb45512d8b06)
12:35:26 Traceback (most recent call last):
12:35:26   File "//google-cloud-sdk/bin/bootstrapping/gsutil.py", line 71, in <module>
12:35:26     main()
12:35:26   File "//google-cloud-sdk/bin/bootstrapping/gsutil.py", line 55, in main
12:35:26     'platform/gsutil', 'gsutil', *args)
12:35:26   File "/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 45, in ExecutePythonTool
12:35:26     execution_utils.ArgsForPythonTool(_FullPath(tool_dir, exec_name), *args))
12:35:26   File "/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 87, in _ExecuteTool
12:35:26     execution_utils.Exec(args + sys.argv[1:], env=_GetToolEnv())
12:35:26   File "/google-cloud-sdk/lib/googlecloudsdk/core/execution_utils.py", line 232, in Exec
12:35:26     env = _GetToolEnv(env=env)
12:35:26   File "/google-cloud-sdk/lib/googlecloudsdk/core/execution_utils.py", line 120, in _GetToolEnv
12:35:26     env, p.EnvironmentName(), p.Get(required=False, validate=False))
12:35:26   File "/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 1068, in Get
12:35:26     required)
12:35:26   File "/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 1340, in _GetProperty
12:35:26     value = _GetPropertyWithoutDefault(prop, properties_file)
12:35:26   File "/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 1379, in _GetPropertyWithoutDefault
12:35:26     value = callback()
12:35:26   File "/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 609, in _GetGCEAccount
12:35:26     return c_gce.Metadata().DefaultAccount()
12:35:26   File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce.py", line 82, in DefaultAccount
12:35:26     http_errors_to_ignore=(404,))
12:35:26   File "/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 160, in TryFunc
12:35:26     return func(*args, **kwargs), None
12:35:26   File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce.py", line 47, in _ReadNoProxyWithCleanFailures
12:35:26     raise CannotConnectToMetadataServerException(e)
12:35:26 googlecloudsdk.core.credentials.gce.CannotConnectToMetadataServerException: <urlopen error timed out>
12:35:26 2016/05/19 12:35:26 e2e.go:200: Error running up: exit status 1
12:35:26 2016/05/19 12:35:26 e2e.go:196: Step 'up' finished in 16.459877586s
12:35:26 
2016/05/19 12:35:26 e2e.go:110: Error starting e2e cluster. Aborting.
```

**Comment by fejta** [comment]
Dup of https://github.com/kubernetes/kubernetes/issues/25926
