### ISSUE TITLE
Flake: start up: gcloud crashed (CannotConnectToMetadataServerException

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#25926]
https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce-slow/5776/

```
16:00:17 Starting master and configuring firewalls
16:00:24 Created [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-slow/zones/us-central1-f/disks/jenkins-e2e-master-pd].
16:00:24 NAME                   ZONE           SIZE_GB  TYPE    STATUS
16:00:24 jenkins-e2e-master-pd  us-central1-f  20       pd-ssd  READY
16:00:28 Created [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-slow/global/firewalls/jenkins-e2e-master-https].
16:00:28 NAME                      NETWORK      SRC_RANGES  RULES    SRC_TAGS  TARGET_TAGS
16:00:28 jenkins-e2e-master-https  jenkins-e2e  0.0.0.0/0   tcp:443            jenkins-e2e-master
16:00:31 Created [https://www.googleapis.com/compute/v1/projects/k8s-jkns-e2e-gce-slow/regions/us-central1/addresses/jenkins-e2e-master-ip].
16:00:36 ERROR: gcloud crashed (CannotConnectToMetadataServerException): <urlopen error timed out>
16:00:36 
16:00:36 If you would like to report this issue, please run the following command:
16:00:36   gcloud feedback
16:00:36 Traceback (most recent call last):
16:00:36   File "//google-cloud-sdk/lib/gcloud.py", line 53, in <module>
16:00:36     main()
16:00:36   File "//google-cloud-sdk/lib/gcloud.py", line 49, in main
16:00:36     sys.exit(googlecloudsdk.gcloud_main.main())
16:00:36   File "/google-cloud-sdk/lib/googlecloudsdk/gcloud_main.py", line 169, in main
16:00:36     gcloud_cli.Execute()
16:00:36   File "/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 632, in Execute
16:00:36     result = args.cmd_func(cli=self, args=args)
16:00:36   File "/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 1370, in Run
16:00:36     resources = display.Displayer(command_instance, args, resources).Display()
16:00:36   File "/google-cloud-sdk/lib/googlecloudsdk/calliope/display.py", line 330, in Display
16:00:36     self._printer.Print(self._resources)
16:00:36   File "/google-cloud-sdk/lib/googlecloudsdk/core/resource/resource_printer_base.py", line 282, in Print
16:00:36     for resource in resources:
16:00:36   File "/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/lister.py", line 50, in ProcessResults
16:00:36     cache = remote_completion.RemoteCompletion()
16:00:36   File "/google-cloud-sdk/lib/googlecloudsdk/core/remote_completion.py", line 248, in __init__
16:00:36     self.account = properties.VALUES.core.account.Get(required=False)
16:00:36   File "/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 1068, in Get
16:00:36     required)
16:00:36   File "/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 1340, in _GetProperty
16:00:36     value = _GetPropertyWithoutDefault(prop, properties_file)
16:00:36   File "/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 1379, in _GetPropertyWithoutDefault
16:00:36     value = callback()
16:00:36   File "/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 609, in _GetGCEAccount
16:00:36     return c_gce.Metadata().DefaultAccount()
16:00:36   File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce.py", line 82, in DefaultAccount
16:00:36     http_errors_to_ignore=(404,))
16:00:36   File "/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 160, in TryFunc
16:00:36     return func(*args, **kwargs), None
16:00:36   File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce.py", line 47, in _ReadNoProxyWithCleanFailures
16:00:36     raise CannotConnectToMetadataServerException(e)
16:00:36 googlecloudsdk.core.credentials.gce.CannotConnectToMetadataServerException: <urlopen error timed out>
16:00:36 Attempt 1 failed to create static ip jenkins-e2e-master-ip. Retrying.
16:00:41 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
16:00:41  - The resource 'projects/k8s-jkns-e2e-gce-slow/regions/us-central1/addresses/jenkins-e2e-master-ip' already exists
16:00:41 
16:00:41 Attempt 2 failed to create static ip jenkins-e2e-master-ip. Retrying.
16:00:52 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
16:00:52  - The resource 'projects/k8s-jkns-e2e-gce-slow/regions/us-central1/addresses/jenkins-e2e-master-ip' already exists
16:00:52 
16:00:52 Attempt 3 failed to create static ip jenkins-e2e-master-ip. Retrying.
16:01:07 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
16:01:07  - The resource 'projects/k8s-jkns-e2e-gce-slow/regions/us-central1/addresses/jenkins-e2e-master-ip' already exists
16:01:07 
16:01:07 Attempt 4 failed to create static ip jenkins-e2e-master-ip. Retrying.
16:01:28 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
16:01:28  - The resource 'projects/k8s-jkns-e2e-gce-slow/regions/us-central1/addresses/jenkins-e2e-master-ip' already exists
16:01:28 
16:01:28 Attempt 5 failed to create static ip jenkins-e2e-master-ip. Retrying.
16:01:54 ERROR: (gcloud.compute.addresses.create) Some requests did not succeed:
16:01:54  - The resource 'projects/k8s-jkns-e2e-gce-slow/regions/us-central1/addresses/jenkins-e2e-master-ip' already exists
16:01:54 
16:01:54 Failed to create static ip jenkins-e2e-master-ip 
16:01:54 2016/05/19 16:01:54 e2e.go:200: Error running up: exit status 2
16:01:54 2016/05/19 16:01:54 e2e.go:196: Step 'up' finished in 1m49.039844427s
16:01:54 
2016/05/19 16:01:54 e2e.go:110: Error starting e2e cluster. Aborting.
```

**Comment by Random-Liu** [comment]
Simillar issue: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/29181/kubernetes-pull-build-test-e2e-gce/50007/
