### ISSUE TITLE
kube-dns panic

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#26116]
crashlooping on my cluster:

```
I0523 22:11:45.809653       1 dns.go:352] Received DNS Request:galera.cluster.local., exact:false
I0523 22:11:45.809675       1 dns.go:385] records:[], retval:[], path:[local cluster galera]
I0523 22:11:46.064002       1 dns.go:352] Received DNS Request:kubernetes.default.svc.cluster.local., exact:false
I0523 22:11:46.064113       1 dns.go:385] records:[0xc82030e930], retval:[{10.0.0.1 0 10 10  false 30 0  }], path:[local cluster svc default kubernetes]
I0523 22:11:46.064450       1 dns.go:352] Received DNS Request:kubernetes.default.svc.cluster.local., exact:false
I0523 22:11:46.064476       1 dns.go:385] records:[0xc82030e930], retval:[{10.0.0.1 0 10 10  false 30 0  }], path:[local cluster svc default kubernetes]
I0523 22:11:46.064915       1 dns.go:393] Received ReverseRecord Request:1.0.0.10.in-addr.arpa.
I0523 22:11:46.816377       1 dns.go:352] Received DNS Request:galera.e2e-tests-petset-kqc7g.svc.cluster.local., exact:false
I0523 22:11:46.816435       1 dns.go:385] records:[0xc82030f810], retval:[{10.180.3.3 0 10 10  false 30 0  }], path:[local cluster svc e2e-tests-petset-kqc7g galera]
panic: runtime error: slice bounds out of range

goroutine 151 [running]:
panic(0x1677b20, 0xc820014020)
	/usr/local/google/home/abshah/.gvm/gos/go1.6/src/runtime/panic.go:464 +0x3e6
k8s.io/kubernetes/vendor/github.com/skynetservices/skydns/msg.Domain(0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/abshah/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/skynetservices/skydns/msg/service.go:132 +0x2b0
k8s.io/kubernetes/vendor/github.com/skynetservices/skydns/server.(*server).SRVRecords(0xc8204601c0, 0xc82011f830, 0x30, 0xe00010021, 0xc82011f830, 0x30, 0x7faaca000200, 0x0, 0x0, 0x0, ...)
	/usr/local/google/home/abshah/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/skynetservices/skydns/server/server.go:580 +0xfb7
k8s.io/kubernetes/vendor/github.com/skynetservices/skydns/server.(*server).ServeDNS(0xc8204601c0, 0x7faaca4e35f0, 0xc8204ead80, 0xc82011d7a0)
	/usr/local/google/home/abshah/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/skynetservices/skydns/server/server.go:392 +0x3558
k8s.io/kubernetes/vendor/github.com/miekg/dns.(*ServeMux).ServeDNS(0xc820464210, 0x7faaca4e35f0, 0xc8204ead80, 0xc82011d7a0)
	/usr/local/google/home/abshah/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/miekg/dns/server.go:209 +0xbb
k8s.io/kubernetes/vendor/github.com/miekg/dns.(*Server).serve(0xc820452410, 0x7faaca4e20e0, 0xc82011f7d0, 0x7faaca4e20b8, 0xc820464210, 0xc82012ae00, 0x41, 0x200, 0xc820022640, 0xc82012e5a0, ...)
	/usr/local/google/home/abshah/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/miekg/dns/server.go:576 +0x7ef
created by k8s.io/kubernetes/vendor/github.com/miekg/dns.(*Server).serveUDP
	/usr/local/google/home/abshah/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/miekg/dns/server.go:530 +0x3e1
```

@ArtfulCoder

**Comment by bprashanth** [comment]
Turns out this is because of an SRV lookup (and according to @thockin it's a malformed SRV lookup, but I got the idea from: https://github.com/skynetservices/skydns#srv-records; so file a bug on mikeg? :)

Anyway, first bring up a cluster without https://github.com/kubernetes/kubernetes/issues/26239: 
```console
19:35:11-beeps~/goproj/src/k8s.io/kubernetes] (test)$ k run -it ubuntu --image=bprashanth/ubuntu:15.10
Waiting for pod default/ubuntu-2915277147-ns12l to be running, status is Pending, pod ready: false
Waiting for pod default/ubuntu-2915277147-ns12l to be running, status is Pending, pod ready: false
Waiting for pod default/ubuntu-2915277147-ns12l to be running, status is Pending, pod ready: false
Waiting for pod default/ubuntu-2915277147-ns12l to be running, status is Pending, pod ready: false
Waiting for pod default/ubuntu-2915277147-ns12l to be running, status is Pending, pod ready: false
Waiting for pod default/ubuntu-2915277147-ns12l to be running, status is Pending, pod ready: false
Waiting for pod default/ubuntu-2915277147-ns12l to be running, status is Pending, pod ready: false

root@ubuntu-2915277147-ns12l:/# dig kubernetes.default.svc.cluster.local SRV

; <<>> DiG 9.9.5-11ubuntu1.3-Ubuntu <<>> kubernetes.default.svc.cluster.local SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13152
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;kubernetes.default.svc.cluster.local. IN SRV

;; Query time: 1 msec
;; SERVER: 10.0.0.10#53(10.0.0.10)
;; WHEN: Wed May 25 02:37:28 UTC 2016
;; MSG SIZE  rcvd: 54
root@ubuntu-2915277147-ns12l:/# exit
Session ended, resume using 'kubectl attach ubuntu-2915277147-ns12l -c ubuntu -i -t' command when the pod is running

19:39:28-beeps~/goproj/src/k8s.io/kubernetes] (test)$ kk logs kube-dns-v12-4y9ym -c kubedns --previous
I0525 02:37:28.067618       1 dns.go:385] records:[0xc8202d0e00], retval:[{10.0.0.1 0 10 10  false 30 0  }], path:[local cluster svc default kubernetes]
panic: runtime error: slice bounds out of range

goroutine 1969 [running]:
panic(0x1677b20, 0xc820014020)
	/usr/local/google/home/abshah/.gvm/gos/go1.6/src/runtime/panic.go:464 +0x3e6
k8s.io/kubernetes/vendor/github.com/skynetservices/skydns/msg.Domain(0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/abshah/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/skynetservices/skydns/msg/service.go:132 +0x2b0
k8s.io/kubernetes/vendor/github.com/skynetservices/skydns/server.(*server).SRVRecords(0xc8203279c0, 0xc8205684b0, 0x25, 0xe00010021, 0xc8205684b0, 0x25, 0x7fcc9d001000, 0x0, 0x0, 0x0, ...)
	/usr/local/google/home/abshah/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/skynetservices/skydns/server/server.go:580 +0xfb7
k8s.io/kubernetes/vendor/github.com/skynetservices/skydns/server.(*server).ServeDNS(0xc8203279c0, 0x7fcc9d528e78, 0xc820331800, 0xc82010bd40)
	/usr/local/google/home/abshah/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/skynetservices/skydns/server/server.go:392 +0x3558
k8s.io/kubernetes/vendor/github.com/miekg/dns.(*ServeMux).ServeDNS(0xc820170820, 0x7fcc9d528e78, 0xc820331800, 0xc82010bd40)
	/usr/local/google/home/abshah/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/miekg/dns/server.go:209 +0xbb
k8s.io/kubernetes/vendor/github.com/miekg/dns.(*Server).serve(0xc8200db930, 0x7fcc9d558e80, 0xc820568450, 0x7fcc9d558e58, 0xc820170820, 0xc8202c2800, 0x41, 0x200, 0xc820022158, 0xc820124cc0, ...)
	/usr/local/google/home/abshah/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/miekg/dns/server.go:576 +0x7ef
created by k8s.io/kubernetes/vendor/github.com/miekg/dns.(*Server).serveUDP
	/usr/local/google/home/abshah/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/miekg/dns/server.go:530 +0x3e1

```

This is happening because skydns tries to construct the target of SRV and NS lookups from the etcd key field in the skymsg.Service, but we don't actually set the field in our treecache node. I think this should be kind of easy to fix, every leaf must have a key, and we set it when we insert it: https://github.com/kubernetes/kubernetes/blob/master/pkg/dns/treecache.go#L69. I think we'll also have to append the full path in every entry in that subCache.
