### ISSUE TITLE
TestPersistentVolumeMultiPVs is flaky

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#26181]
```
goroutine 13886 [chan receive, 7 minutes]:
k8s.io/kubernetes/test/integration.waitForPersistentVolumePhase(0x7fd74c3ba278, 0xc82c328630, 0x23fe688, 0x5)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/persistent_volumes_test.go:281 +0x6b
k8s.io/kubernetes/test/integration.TestPersistentVolumeMultiPVs(0xc8290fd680)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/persistent_volumes_test.go:184 +0x89f
testing.tRunner(0xc8290fd680, 0x3568318)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892
```

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/24882/kubernetes-pull-test-unit-integration/27477/

**Comment by fejta** [comment]
Assigning to @saad-ali per PD

**Comment by jsafrane** [comment]
dup of #26256 - I can see in the log:

```
E0523 16:55:32.204766   22570 controller_base.go:259] PersistentVolumeController could not update claim "default/fake-pvc-16": Put http://127.0.0.1:35327/api/v1/namespaces/default/persistentvolumeclaims/fake-pvc-16: dial tcp 127.0.0.1:35327: getsockopt: connection refused
```
