### ISSUE TITLE
e2e flake - Many failures, mostly timed out waiting for condition

### ISSUE THREAD

**Issue by euank** [kubernetes/kubernetes#26302]
Apologies that I can't figure out a better title; I can't figure out what's in common between the flaking tests easily and I want something to point my `test this issue: #` at and maybe it will help. Feel free to re-title it.

I have two PRs with a similar set of failing tests:
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26096/kubernetes-pull-build-test-e2e-gce/42005/
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25902/kubernetes-pull-build-test-e2e-gce/41992/

There's lots of logs related to pre-pulling images ( #25784 ) but I'm not sure if that's relevant; I'm not familiar with expected output for that change.

The failing tests in common are the following 23 (many timeouts, but honestly I don't really know what's going on for most of them)
```
[Fail] [k8s.io] DNS [It] should provide DNS for services [Conformance] 
[Fail] [k8s.io] DNS [It] should provide DNS for the cluster [Conformance] 
[Fail] [k8s.io] Deployment [It] RecreateDeployment should delete old pods and create new ones 
[Fail] [k8s.io] Deployment [It] RollingUpdateDeployment should delete old pods and create new ones 
[Fail] [k8s.io] Deployment [It] deployment should label adopted RSs and pods 
[Fail] [k8s.io] Deployment [It] deployment should support rollover 
[Fail] [k8s.io] EmptyDir wrapper volumes [It] should becomes running 
[Fail] [k8s.io] Kubectl client [k8s.io] Guestbook application [It] should create and stop a working application [Conformance] 
[Fail] [k8s.io] Kubectl client [k8s.io] Update Demo [It] should create and stop a replication controller [Conformance] 
[Fail] [k8s.io] Kubectl client [k8s.io] Update Demo [It] should do a rolling update of a replication controller [Conformance] 
[Fail] [k8s.io] Kubectl client [k8s.io] Update Demo [It] should scale a replication controller [Conformance] 
[Fail] [k8s.io] Kubernetes Dashboard [It] should check that the kubernetes-dashboard instance is alive 
[Fail] [k8s.io] Monitoring [It] should verify monitoring pods and all cluster nodes are available on influxdb using heapster. 
[Fail] [k8s.io] Networking [It] should function for intra-pod communication [Conformance] 
[Fail] [k8s.io] Networking [It] should provide Internet connection for containers [Conformance] 
[Fail] [k8s.io] Networking [k8s.io] Granular Checks [It] should function for pod communication between nodes 
[Fail] [k8s.io] PrivilegedPod [It] should test privileged pod 
[Fail] [k8s.io] ReplicaSet [It] should serve a basic image on each replica with a private image 
[Fail] [k8s.io] ReplicaSet [It] should serve a basic image on each replica with a public image [Conformance] 
[Fail] [k8s.io] ReplicationController [It] should serve a basic image on each replica with a private image 
[Fail] [k8s.io] ReplicationController [It] should serve a basic image on each replica with a public image [Conformance] 
[Fail] [k8s.io] Services [It] should be able to create a functioning NodePort service 
[Fail] [k8s.io] Services [It] should be able to up and down services 
```

Those that only occur in the first are:
```
[Fail] [k8s.io] DNS [It] should provide DNS for pods for Hostname and Subdomain Annotation 
[Fail] [k8s.io] Deployment [It] RollingUpdateDeployment should scale up and down in the right order 
[Fail] [k8s.io] Kubectl client [k8s.io] Kubectl logs [It] should be able to retrieve and filter logs [Conformance] 
[Fail] [k8s.io] Services [It] should create endpoints for unready pods 
```

And only in the second are:
```
[Fail] [k8s.io] Deployment [It] deployment should delete old replica sets 
[Fail] [k8s.io] Horizontal pod autoscaling (scale resource: CPU) [k8s.io] ReplicationController light [It] Should scale from 1 pod to 2 pods 
[Fail] [k8s.io] Horizontal pod autoscaling (scale resource: CPU) [k8s.io] ReplicationController light [It] Should scale from 2 pods to 1 pod 
[Fail] [k8s.io] PreStop [It] should call prestop when killing a pod [Conformance] 
[Fail] [k8s.io] Proxy version v1 [It] should proxy through a service and a pod [Conformance] 
```

**Comment by yujuhong** [comment]
The apiserver log is full of 503 errors accessing pods through proxy. 

Some examples:
```
I0525 18:58:22.358245       9 handlers.go:165] GET /api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/?timeout=5m0s: (30.015133117s) 503
goroutine 69720 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc822a76c40, 0x1f7)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:214 +0xa3
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc822a76c40, 0x1f7)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:193 +0x2b
k8s.io/kubernetes/pkg/apiserver/metrics.(*responseWriterDelegator).WriteHeader(0xc824b24330, 0x1f7)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:117 +0x4c
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc823530840, 0x7faa52dc6f18, 0xc823433628, 0xc823a31dc0)
	/usr/local/go/src/net/http/httputil/reverseproxy.go:233 +0xcd1
k8s.io/kubernetes/pkg/registry/generic/rest.(*UpgradeAwareProxyHandler).ServeHTTP(0xc82188c0f0, 0x7faa52dc6f18, 0xc823433628, 0xc823a31ce0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/generic/rest/proxy.go:125 +0x8d9
k8s.io/kubernetes/pkg/apiserver.ConnectResource.func1(0xc824b240c0, 0xc8243e3560)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:215 +0xc1b
k8s.io/kubernetes/pkg/apiserver/metrics.InstrumentRouteFunc.func1(0xc824b240c0, 0xc8243e3560)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:101 +0x25f
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc8202501b0, 0x7faa52dc6be0, 0xc822a76c40, 0xc823a31ce0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:272 +0xf30
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x7faa52dc6be0, 0xc822a76c40, 0xc823a31ce0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x3e

I0525 18:58:34.308880       9 handlers.go:165] GET /api/v1/namespaces/e2e-tests-kubectl-thjyq/pods/update-demo-nautilus-dn4m2/proxy/data.json: (30.002440822s) 503
goroutine 23040 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc822a77c00, 0x1f7)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:214 +0xa3
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc822a77c00, 0x1f7)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:193 +0x2b
k8s.io/kubernetes/pkg/apiserver/metrics.(*responseWriterDelegator).WriteHeader(0xc82389b860, 0x1f7)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:117 +0x4c
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc822e09100, 0x7faa52dc6f18, 0xc822117268, 0xc8224b1ea0)
	/usr/local/go/src/net/http/httputil/reverseproxy.go:233 +0xcd1
k8s.io/kubernetes/pkg/registry/generic/rest.(*UpgradeAwareProxyHandler).ServeHTTP(0xc82279d860, 0x7faa52dc6f18, 0xc822117268, 0xc8224b1c00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/generic/rest/proxy.go:125 +0x8d9
k8s.io/kubernetes/pkg/apiserver.ConnectResource.func1(0xc82389b6e0, 0xc825d559e0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:215 +0xc1b
k8s.io/kubernetes/pkg/apiserver/metrics.InstrumentRouteFunc.func1(0xc82389b6e0, 0xc825d559e0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:101 +0x25f
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc8202501b0, 0x7faa52dc6be0, 0xc822a77c00, 0xc8224b1c00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:272 +0xf30
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x7faa52dc6be0, 0xc822a77c00, 0xc8224b1c00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x3e

I0525 18:58:36.100883       9 handlers.go:165] GET /api/v1/namespaces/e2e-tests-dns-f0eu6/pods/dns-test-781e5f7e-22aa-11e6-9f43-42010af00007/proxy/results/wheezy_udp@dns-test-service: (30.002437445s) 503
goroutine 73511 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc8259db1f0, 0x1f7)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:214 +0xa3
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc8259db1f0, 0x1f7)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:193 +0x2b
k8s.io/kubernetes/pkg/apiserver/metrics.(*responseWriterDelegator).WriteHeader(0xc825989c80, 0x1f7)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:117 +0x4c
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc821cb7d80, 0x7faa52dc6f18, 0xc82348f2e0, 0xc8246d2700)
	/usr/local/go/src/net/http/httputil/reverseproxy.go:233 +0xcd1
k8s.io/kubernetes/pkg/registry/generic/rest.(*UpgradeAwareProxyHandler).ServeHTTP(0xc825ee0320, 0x7faa52dc6f18, 0xc82348f2e0, 0xc8246d2380)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/generic/rest/proxy.go:125 +0x8d9
k8s.io/kubernetes/pkg/apiserver.ConnectResource.func1(0xc825989bf0, 0xc825bc85a0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:215 +0xc1b
k8s.io/kubernetes/pkg/apiserver/metrics.InstrumentRouteFunc.func1(0xc825989bf0, 0xc825bc85a0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:101 +0x25f
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc8202501b0, 0x7faa52dc6be0, 0xc8259db1f0, 0xc8246d2380)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:272 +0xf30
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x7faa52dc6be0, 0xc8259db1f0, 0xc8246d2380)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc820be67d0 [[e2e.test/v1.3.0 (linux/amd64) kubernetes/4eb9019] 104.197.46.215:52880]

I0525 18:59:33.731286       9 handlers.go:165] GET /api/v1/namespaces/e2e-tests-deployment-nm9mb/pods/test-recreate-controller-ogdtr/proxy/: (30.002302746s) 503
goroutine 54941 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc822c30850, 0x1f7)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:214 +0xa3
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc822c30850, 0x1f7)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:193 +0x2b
k8s.io/kubernetes/pkg/apiserver/metrics.(*responseWriterDelegator).WriteHeader(0xc82362a3c0, 0x1f7)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:117 +0x4c
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc823d97ec0, 0x7faa52dc6f18, 0xc82348f818, 0xc8225e1ce0)
	/usr/local/go/src/net/http/httputil/reverseproxy.go:233 +0xcd1
k8s.io/kubernetes/pkg/registry/generic/rest.(*UpgradeAwareProxyHandler).ServeHTTP(0xc82188db30, 0x7faa52dc6f18, 0xc82348f818, 0xc8225e1a40)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/generic/rest/proxy.go:125 +0x8d9
k8s.io/kubernetes/pkg/apiserver.ConnectResource.func1(0xc82362a300, 0xc826100060)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:215 +0xc1b
k8s.io/kubernetes/pkg/apiserver/metrics.InstrumentRouteFunc.func1(0xc82362a300, 0xc826100060)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:101 +0x25f
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc8202501b0, 0x7faa52dc6be0, 0xc822c30850, 0xc8225e1a40)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:272 +0xf30
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x7faa52dc6be0, 0xc822c30850, 0xc8225e1a40)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc820be67d0 [[e2e.test/v1.3.0 (linux/amd64) kubernetes/4eb9019] 104.197.46.215:52350]
```

**Comment by yujuhong** [comment]
Might be a dup of #26311

**Comment by euank** [comment]
I'm happy enough with that. Thank you very much for taking the time to dig into that, closing as a dupe (happy to reopen if there's suspicion it isn't).
