### ISSUE TITLE
plugin/pkg/client/auth/oidc: panic in TestNewOIDCAuthProvider

### ISSUE THREAD

**Issue by ericchiang** [kubernetes/kubernetes#27068]
Observed while running unit tests locally.

```
--- FAIL: TestNewOIDCAuthProvider (1.54s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5aac6a]

goroutine 20 [running]:
panic(0xec5e00, 0xc420012120)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420416180)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0xec5e00, 0xc420012120)
	/usr/local/go/src/runtime/panic.go:458 +0x243
k8s.io/kubernetes/plugin/pkg/auth/authenticator/token/oidc/testing.(*OIDCProvider).AddMinimalProviderConfig(0xc4201b2000, 0x0)
	/home/eric/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/auth/authenticator/token/oidc/testing/provider.go:85 +0x3a
k8s.io/kubernetes/plugin/pkg/client/auth/oidc.TestNewOIDCAuthProvider(0xc420416180)
	/home/eric/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/client/auth/oidc/oidc_test.go:51 +0x2dd
testing.tRunner(0xc420416180, 0x105a990)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec
FAIL	k8s.io/kubernetes/plugin/pkg/client/auth/oidc	1.567s
```

I think it's being caused by this bit of code[0]

```go
	srv, err := op.ServeTLSWithKeyPair(cert, key)
	op.AddMinimalProviderConfig(srv) // srv may be nil if previous action failed.
	if err != nil {
		t.Fatalf("Cannot start server %v", err)
	}
	defer srv.Close()
```

cc @bobbyrullo 

[0] https://github.com/kubernetes/kubernetes/blob/66149c50fd00550e55920d5e78f7dbc5e4283127/plugin/pkg/client/auth/oidc/oidc_test.go#L50-L52

**Comment by bobbyrullo** [comment]
Thanks Eric, I'll look into it.
