### ISSUE TITLE
e2e flake: no longer a configured node

### ISSUE THREAD

**Issue by euank** [kubernetes/kubernetes#27214]
The internal link is: http://goto.google.com/prkubekins/job/kubernetes-pull-build-test-e2e-gce//44196

The other "not found" link is https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26759/kubernetes-pull-build-test-e2e-gce/44196/

Hopefully the internal link has some information, I can't view it to check.

**Comment by euank** [comment]
Another occurrence: #27208, internal link http://goto.google.com/prkubekins/job/kubernetes-pull-build-test-e2e-gce//44198

**Comment by lavalamp** [comment]
actual error is:

```
FATAL: no longer a configured node for agent-pr-1
java.lang.IllegalStateException: no longer a configured node for agent-pr-1
	at hudson.model.AbstractBuild$AbstractBuildExecution.getCurrentNode(AbstractBuild.java:453)
	at hudson.model.AbstractBuild$AbstractBuildExecution.reportBrokenChannel(AbstractBuild.java:810)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
ERROR: Step ‘Publish JUnit test result report’ failed: no workspace for kubernetes-pull-build-test-e2e-gce #44196
[PostBuildScript] - Execution post build scripts.
ERROR: Build step failed with exception
java.lang.NullPointerException: no such build node: agent-pr-1
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:72)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:64)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.processBuildSteps(PostBuildScript.java:204)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.processScripts(PostBuildScript.java:143)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript._perform(PostBuildScript.java:105)
	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:85)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Build step 'Execute a set of scripts' marked build as failure
ERROR: Build step failed with exception
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:187)
	at com.google.jenkins.plugins.storage.AbstractUpload.perform(AbstractUpload.java:176)
	at com.google.jenkins.plugins.storage.GoogleCloudStorageUploader.perform(GoogleCloudStorageUploader.java:109)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Build step 'Google Cloud Storage Uploader' marked build as failure
ERROR: Step ‘Set build status on GitHub commit [deprecated]’ failed: no workspace for kubernetes-pull-build-test-e2e-gce #44196
Setting status of 098b9f0603f820ee04d11ba61146425219cb6e91 to FAILURE with url https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26759/kubernetes-pull-build-test-e2e-gce/44196/ and message: ' No test results found.'
Using context: Jenkins GCE e2e
```

**Comment by euank** [comment]
Closing as stale
/close
