### ISSUE TITLE
agent-pr-2 ran out of disk

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#27393]
This agent is failing jobs whenever they run @pwittrock  with lots of errors like:

11:10:00 java.io.IOException: Failed to create a temp file on /var/lib/jenkins/workspace/kubernetes-e2e-gce
11:10:00 	at hudson.FilePath.createTextTempFile(FilePath.java:1410)
11:10:00 	at hudson.tasks.CommandInterpreter.createScriptFile(CommandInterpreter.java:142)
11:10:00 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:80)
11:10:00 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:64)
11:10:00 	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.processBuildSteps(PostBuildScript.java:204)
11:10:00 	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.processScripts(PostBuildScript.java:143)
11:10:00 	at org.jenkinsci.plugins.postbuildscript.PostBuildScript._perform(PostBuildScript.java:105)
11:10:00 	at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:85)
11:10:00 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
11:10:00 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
11:10:00 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
11:10:00 	at hudson.model.Build$BuildExecution.post2(Build.java:185)
11:10:00 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
11:10:00 	at hudson.model.Run.execute(Run.java:1766)
11:10:00 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
11:10:00 	at hudson.model.ResourceController.execute(ResourceController.java:98)
11:10:00 	at hudson.model.Executor.run(Executor.java:410)

**Comment by fejta** [comment]
`sudo docker ps -a | wc` shows there are some 36 exited containers on the machine, which for some reason aren't getting removed.

**Comment by fejta** [comment]
```
$ sudo docker inspect $(sudo docker ps -f status=exited --format='{{.ID}}') | grep JOB_NAME | sort | uniq
            "JOB_NAME=kubernetes-e2e-gce-gci-ci-release-1.2",
            "JOB_NAME=kubernetes-e2e-gce-release-1.3",
            "JOB_NAME=kubernetes-e2e-gke-1.1-1.3-upgrade-master",
            "JOB_NAME=kubernetes-e2e-gke-1.2-1.3-kubectl-skew",
```

**Comment by fejta** [comment]
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-gci-ci-release-1.2/970/console -> timeout
969 -> timeout
948 timeout
944 timeout
928 timeout
923 timeout

**Comment by fejta** [comment]
Same: http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gke-1.2-1.3-kubectl-skew/471/consoleFull

**Comment by fejta** [comment]
I'm going to create an hourly maintenance job similar to https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/jenkins-daily-maintenance.yaml that for now does:
```
 sudo docker rm $(sudo docker ps -f status=exited --format='{{.ID}}')
```

**Comment by fejta** [comment]
https://github.com/kubernetes/test-infra/pull/167 should fix this
