### ISSUE TITLE
e2e flake: couldn't checkout branch

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#28021]
```
Checking out Revision 685e4cb2f3670311b4007e72596109e5f108e0af (origin/pr/28018/merge)
 > /usr/bin/git config core.sparsecheckout # timeout=10
 > /usr/bin/git checkout -f 685e4cb2f3670311b4007e72596109e5f108e0af # timeout=20
FATAL: Could not checkout 685e4cb2f3670311b4007e72596109e5f108e0af
hudson.plugins.git.GitException: Could not checkout 685e4cb2f3670311b4007e72596109e5f108e0af
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:1992)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:332)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to agent-pr-38(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
	at hudson.remoting.Channel.call(Channel.java:781)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:145)
	at sun.reflect.GeneratedMethodAccessor243.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:131)
	at com.sun.proxy.$Proxy64.execute(Unknown Source)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1135)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: hudson.plugins.git.GitException: Command "/usr/bin/git checkout -f 685e4cb2f3670311b4007e72596109e5f108e0af" returned status code 128:
```

https://github.com/kubernetes/kubernetes/pull/28015

**Comment by fejta** [comment]
@wojtek-t will you please try and link to gubernator or gcs or whatever with the actual logs? It is hard to track this down...

Are you sure you found this in PR 28015? The logs say 28018...

**Comment by fejta** [comment]
WOW, yes this seems to be part of the problem: https://test-dot-k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/28015/kubernetes-pull-build-test-e2e-gce/46566/

Why are we trying to pull origin/pr/28018/merge for PR 28015???

**Comment by fejta** [comment]
Making this a dup of #27462
