### ISSUE TITLE
Issue with kubelet's non-summary `/stats` endpoint

### ISSUE THREAD

**Issue by vishh** [kubernetes/kubernetes#28035]
I am hitting this problem with v1.2.4.

I have a pod named "lma-enp1h" running on a node, and that pod includes a container named "hindsight". The problem is that I cannot get stats for this container:

``` shell
$ # using the /stats/<pod name>/<container name> form
$ curl localhost:10255/stats/lma-enp1h/hindsight
Internal Error: unable to find Docker container "59c6609ee6a98a49b1db41c441e082603b40e0e7b880456dc6309dd7bf121475"
```

``` shell
$ # using the /stats/<namespace>/<pod name>/<uid>/<container name> form
$ curl localhost:10255/stats/default/lma-enp1h/ba48dff9-3942-11e6-9e92-64825ffb1682/hindsight
Internal Error: unable to find Docker container "59c6609ee6a98a49b1db41c441e082603b40e0e7b880456dc6309dd7bf121475"
```

kubelet does find the id of the "hindsight" container, but it reports that it is unable to find a container with that id.

The container does exist on the node, and it is running:

``` shell
$ docker ps --no-trunc | grep 59c6609ee6a98a49b1db41c441e082603b40e0e7b880456dc6309dd7bf121475
59c6609ee6a98a49b1db41c441e082603b40e0e7b880456dc6309dd7bf121475   mcp/hindsight:latest    "/usr/local/bin/hindsight /etc/hindsight/hindsight.cfg"    20 hours ago    Up 20 hours    k8s_hindsight.4ee35f9_lma-enp1h_default_ba48dff9-3942-11e6-9e92-64825ffb1682_aaaa5d6f
```

And cAdvisor does report statistics for that container:

``` shell
$ curl localhost:4194/api/v1.3/containers/docker/59c6609ee6a98a49b1db41c441e082603b40e0e7b880456dc6309dd7bf121475
{"name":"/docker/59c6609ee6a98a49b1db41c441e082603b40e0e7b880456dc6309dd7bf121475"…
```

This is the error I see in the kubelet logs:

```
Moved from https://github.com/kubernetes/kubernetes/issues/18868#issuecomment-228321537

Reported by @elemoine:

Jun 24 12:19:34 node1 kubelet[19095]: I0624 12:19:34.169643   19095 handler.go:239] HTTP InternalServerError: Internal Error: unable to find Docker container "59c6609ee6a98a49b1db41c441e082603b40e0e7b880456dc6309dd7bf121475"
Jun 24 12:19:34 node1 kubelet[19095]: I0624 12:19:34.169849   19095 server.go:1096] GET /stats/lma-enp1h/hindsight: (4.381405ms) 500
Jun 24 12:19:34 node1 kubelet[19095]: goroutine 450 [running]:
Jun 24 12:19:34 node1 kubelet[19095]: k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc2088dc2a0, 0x1f4)
Jun 24 12:19:34 node1 kubelet[19095]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:214 +0xa6
Jun 24 12:19:34 node1 kubelet[19095]: k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc2088dc2a0, 0x1f4)
Jun 24 12:19:34 node1 kubelet[19095]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:193 +0x32
Jun 24 12:19:34 node1 kubelet[19095]: github.com/emicklei/go-restful.(*Response).WriteHeader(0xc208922000, 0x1f4)
Jun 24 12:19:34 node1 kubelet[19095]: #011/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/response.go:191 +0x48
Jun 24 12:19:34 node1 kubelet[19095]: github.com/emicklei/go-restful.(*Response).WriteErrorString(0xc208922000, 0x1f4, 0xc20841eb80, 0x72, 0x0, 0x0)
Jun 24 12:19:34 node1 kubelet[19095]: #011/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/response.go:180 +0x128
Jun 24 12:19:34 node1 kubelet[19095]: k8s.io/kubernetes/pkg/kubelet/server/stats.handleError(0xc208922000, 0x7f0047090040, 0xc208dcd1f0)
Jun 24 12:19:34 node1 kubelet[19095]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/handler.go:240 +0x29a
Jun 24 12:19:34 node1 kubelet[19095]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*handler).handlePodContainer(0xc2085234a0, 0xc208dde3f0, 0xc208922000)
Jun 24 12:19:34 node1 kubelet[19095]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/handler.go:216 +0x8a6
Jun 24 12:19:34 node1 kubelet[19095]: k8s.io/kubernetes/pkg/kubelet/server/stats.*handler.(k8s.io/kubernetes/pkg/kubelet/server/stats.handlePodContainer)·fm(0xc208dde3f0, 0xc208922000)
Jun 24 12:19:34 node1 kubelet[19095]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/handler.go:72 +0x3b
Jun 24 12:19:34 node1 kubelet[19095]: github.com/emicklei/go-restful.(*Container).dispatch(0xc208516120, 0x7f0046ee8148, 0xc2088dc2a0, 0xc208790340)
Jun 24 12:19:34 node1 kubelet[19095]: #011/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:249 +0xf5e
Jun 24 12:19:34 node1 kubelet[19095]: github.com/emicklei/go-restful.*Container.(github.com/emicklei/go-restful.dispatch)·fm(0x7f0046ee8148, 0xc2088dc2a0, 0xc208790340)
Jun 24 12:19:34 node1 kubelet[19095]: #011/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:95 +0x45
Jun 24 12:19:34 node1 kubelet[19095]: net/http.HandlerFunc.ServeHTTP(0xc2084ffac0, 0x7f0046ee8148, 0xc2088dc2a0, 0xc208790340)
Jun 24 12:19:34 node1 kubelet[19095]: #011/usr/src/go/src/net/htt [[curl/7.47.0] 127.0.0.1:34274]
```

**Comment by vishh** [comment]
cc @timstclair @kubernetes/sig-node

**Comment by timstclair** [comment]
Strange, the cAdvisor API and kubelet API ultimately hit the same code path in cAdvisor where that error is generated (https://github.com/kubernetes/kubernetes/blob/eeda4c79155a2b90fdb45848c133428a19502ef7/vendor/github.com/google/cadvisor/manager/manager.go#L568). Are you able to reproduce this?

**Comment by elemoine** [comment]
@vishh there is a "reported by @elemoine" in the middle of the kubelet logs I provided. It is probably not where you intended to add that.

**Comment by elemoine** [comment]
@timstclair I don't know the cAdvisor and Kubernetes code bases, but I've been wondering if the problem could be related to the container namespace. The [`getDockerContainer` function](https://github.com/kubernetes/kubernetes/blob/eeda4c79155a2b90fdb45848c133428a19502ef7/vendor/github.com/google/cadvisor/manager/manager.go#L553-L566) would indeed not find the Docker container if it's namespace is not "docker". But I don't know really at this point.

**Comment by nhlfr** [comment]
I'm going to work on this.

**Comment by nhlfr** [comment]
I couldn't reproduce this on master. So it seems that's an issue occurring only on 1.2.x version.

**Comment by cmluciano** [comment]
Is this still an issue ?
