### ISSUE TITLE
Running `kubectl rollout history deployment` causing `panic: runtime error`

### ISSUE THREAD

**Issue by osterman** [kubernetes/kubernetes#28063]
## what

We have a k8s cluster that has been up for 9 days. We have CircleCI deploying this server as part of our CI/CD pipeline. Today, we're having trouble with a deployment. When I check the history, I get the following stacktrace.

## command
`kubectl rollout history deployment agent-desktop`

## output
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xb8 pc=0xe1b16a]

goroutine 1 [running]:
k8s.io/kubernetes/pkg/util/deployment.Revision(0x0, 0xc208323aa0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/deployment/deployment.go:328 +0x4a
k8s.io/kubernetes/pkg/kubectl.(*DeploymentHistoryViewer).History(0xc208150cf0, 0xc2081060f0, 0x5, 0x7fffca5b4c88, 0xd, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/history.go:80 +0x7ea
k8s.io/kubernetes/pkg/kubectl/cmd/rollout.RunHistory(0xc208152960, 0xc20819da00, 0x7fe249c1e030, 0xc208042008, 0xc20819b220, 0x2, 0x2, 0xc20819a2c0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/rollout/rollout_history.go:98 +0x8a8
k8s.io/kubernetes/pkg/kubectl/cmd/rollout.func·002(0xc20819da00, 0xc20819b220, 0x2, 0x2)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/rollout/rollout_history.go:55 +0x6f
github.com/spf13/cobra.(*Command).execute(0xc20819da00, 0xc20819b0a0, 0x2, 0x2, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:572 +0x82f
github.com/spf13/cobra.(*Command).ExecuteC(0xc208077600, 0xc20819da00, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:662 +0x4db
github.com/spf13/cobra.(*Command).Execute(0xc208077600, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:618 +0x3a
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:28 +0x101
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:28 +0x2f

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1e6b160)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 13 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 19 [IO wait]:
net.(*pollDesc).Wait(0xc2081de1b0, 0x72, 0x0, 0x0)
	/usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2081de1b0, 0x0, 0x0)
	/usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2081de150, 0xc208140000, 0x1000, 0x1000, 0x0, 0x7fe249c1e378, 0xc2081f0300)
	/usr/src/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208042028, 0xc208140000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/src/go/src/net/net.go:121 +0xdc
net/http.noteEOFReader.Read(0x7fe249c24c48, 0xc208042028, 0xc20808f4f8, 0xc208140000, 0x1000, 0x1000, 0x1309f20, 0x0, 0x0)
	/usr/src/go/src/net/http/transport.go:1270 +0x6e
net/http.(*noteEOFReader).Read(0xc2081dc920, 0xc208140000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
	<autogenerated>:125 +0xd4
bufio.(*Reader).fill(0xc2081911a0)
	/usr/src/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Peek(0xc2081911a0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/bufio/bufio.go:132 +0xf0
net/http.(*persistConn).readLoop(0xc20808f4a0)
	/usr/src/go/src/net/http/transport.go:842 +0xa4
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:660 +0xc9f

goroutine 20 [select]:
net/http.(*persistConn).writeLoop(0xc20808f4a0)
	/usr/src/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/src/go/src/net/http/transport.go:661 +0xcbc

goroutine 18 [sleep]:
net.func·019()
	/usr/src/go/src/net/dnsclient_unix.go:240 +0x5a
created by net.loadConfig
	/usr/src/go/src/net/dnsclient_unix.go:269 +0x20c
```

## version
```
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
```

On CoreOS 899.17.0

## remediation
Unfortunately, we can't leave the service in the current state so I had to take corrective action. 
```
kubectl get deployment agent-desktop -o yaml --export > /tmp/agent-desktop.yml
kubectl delete deployment agent-desktop
kubectl apply -f /tmp/agent-desktop.yml
```
After running these commands, it's healthy again.

**Comment by AdoHe** [comment]
@osterman seems you meet the same problem with this issue #24606, and the fix landed #25308. @kargakis since this fix is not included in 1.2, users may still meet this problem, should we consider cherry pick this one into 1.2?

**Comment by kargakis** [comment]
@bgrant0607 @janetkuo @pwittrock do you still cherry-pick for 1.2?

**Comment by bgrant0607** [comment]
@kargakis @AdoHe It can be cherrypicked into 1.2. If/when another release is cut from that branch, it could then be included.

**Comment by osterman** [comment]
Thanks! We'll be upgrading to 1.3 as soon as it's cut.

**Comment by ernestoalejo** [comment]
Note this also affects GKE and leaves the deployment in an unrecoverable status. If 1.3 will take much longer to reach GKE it will be highly appreciated to cherrypick the fix into a version that can be released quicker.

**Comment by osterman** [comment]
We haven't seen this happen again since upgrading to 1.3.

**Comment by AdoHe** [comment]
@kubernetes/kubectl I think we could close this now.
