### ISSUE TITLE
Printing v1 API objects causes protobuf warnings

### ISSUE THREAD

**Issue by ivan4th** [kubernetes/kubernetes#28218]
See examples e.g. in #26763, #26202 and #26840
The problem is that fields like `HTTPGetAction.Port` (of type `intstr.IntOrString`) in pkg/api/v1/types.go can't be handled by protobuf (there's several such fields), and String() methods of v1 API objects in generated.pb.go use `proto.CompactTextString()`. This causes confusing messages like

```
proto: no encoder for Type intstr.Type [GetProperties]
```

while priting error messages referencing v1 API objects.

**Comment by lavalamp** [comment]
@smarterclayton

**Comment by smarterclayton** [comment]
I'm pretty sure this is because it's actually printing internal objects, not v1.  We don't have proto defined on internal objects (unlike json).

**Comment by smarterclayton** [comment]
Nm, my brain interposed this with another issue I was investigating.

**Comment by smarterclayton** [comment]
What code is printing them?  I wouldn't expect String() to get invoked during apply (except maybe for glog?)

**Comment by ivan4th** [comment]
E.g. this line https://github.com/kubernetes/kubernetes/blob/ef0c9f0c5b8efbba948a0be2c98d9d2e32e0b68c/pkg/kubectl/cmd/apply.go#L178
Caught it by adding debug.PrintStack() to protobuf code

**Comment by ivan4th** [comment]
Here's [one of the important lines](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/generated.pb.go#L574)  appearing in protobuf error stack trace,

**Comment by ivan4th** [comment]
A part of output from failed `kubectl apply` with `debug.PrintStack()` in protobuf code:
```
proto: no encoder for TypeMeta unversioned.TypeMeta [GetProperties]
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/home/ivan4th/.gvm/gos/go1.6.2/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/home/ivan4th/.gvm/gos/go1.6.2/src/runtime/debug/stack.go:16 +0x18
k8s.io/kubernetes/vendor/github.com/gogo/protobuf/proto.getPropertiesLocked(0x7fa91a8aa0a8, 0x1ae6ea0, 0xc82030cda8)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/gogo/protobuf/proto/properties.go:781 +0xa66
k8s.io/kubernetes/vendor/github.com/gogo/protobuf/proto.GetProperties(0x7fa91a8aa0a8, 0x1ae6ea0, 0x199)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/gogo/protobuf/proto/properties.go:718 +0x13b
k8s.io/kubernetes/vendor/github.com/gogo/protobuf/proto.writeStruct(0xc82027df80, 0x1ae6ea0, 0xc820354000, 0x199, 0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/gogo/protobuf/proto/text.go:185 +0x87
k8s.io/kubernetes/vendor/github.com/gogo/protobuf/proto.marshalText(0x7fa91a8ad880, 0xc82031e070, 0x7fa91a873a78, 0xc820354000, 0x7fa91a8b0201, 0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/gogo/protobuf/proto/text.go:763 +0x43d
k8s.io/kubernetes/vendor/github.com/gogo/protobuf/proto.CompactTextString(0x7fa91a873a78, 0xc820354000, 0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/gogo/protobuf/proto/text.go:791 +0x99
k8s.io/kubernetes/pkg/api/v1.(*Pod).String(0xc820354000, 0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/api/v1/generated.pb.go:574 +0x58
fmt.(*pp).handleMethods(0xc8200d96c0, 0xc800000076, 0x2, 0x1c49101)
	/home/ivan4th/.gvm/gos/go1.6.2/src/fmt/print.go:730 +0x62a
fmt.(*pp).printValue(0xc8200d96c0, 0x1c49100, 0xc820354000, 0x16, 0x76, 0x2, 0x16)
	/home/ivan4th/.gvm/gos/go1.6.2/src/fmt/print.go:844 +0x3d6
fmt.(*pp).printReflectValue(0xc8200d96c0, 0x1b65a80, 0xc820170300, 0x199, 0xc800000076, 0x1, 0x7fa91a8f6000)
	/home/ivan4th/.gvm/gos/go1.6.2/src/fmt/print.go:932 +0x3b79
fmt.(*pp).printValue(0xc8200d96c0, 0x1b65a80, 0xc820170300, 0x199, 0xc800000076, 0x1, 0xc82030e1a8)
	/home/ivan4th/.gvm/gos/go1.6.2/src/fmt/print.go:848 +0x440
fmt.(*pp).printReflectValue(0xc8200d96c0, 0x1b4c920, 0xc820170300, 0x16, 0x76, 0x0, 0x0)
	/home/ivan4th/.gvm/gos/go1.6.2/src/fmt/print.go:1009 +0x351e
fmt.(*pp).printArg(0xc8200d96c0, 0x1b4c920, 0xc820170300, 0x76, 0x0, 0x0)
	/home/ivan4th/.gvm/gos/go1.6.2/src/fmt/print.go:810 +0x540
fmt.(*pp).doPrintf(0xc8200d96c0, 0x1ddf540, 0x1e, 0xc82030f0b8, 0x2, 0x2)
	/home/ivan4th/.gvm/gos/go1.6.2/src/fmt/print.go:1238 +0x1dcd
fmt.Sprintf(0x1ddf540, 0x1e, 0xc82030f0b8, 0x2, 0x2, 0x0, 0x0)
	/home/ivan4th/.gvm/gos/go1.6.2/src/fmt/print.go:203 +0x6f
k8s.io/kubernetes/pkg/kubectl/cmd.RunApply.func1(0xc820170300, 0x7fa91a8affc0, 0xc82018c980, 0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/apply.go:178 +0xb6f
k8s.io/kubernetes/pkg/kubectl/resource.ContinueOnErrorVisitor.Visit.func1(0xc820170300, 0x0, 0x0, 0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:340 +0x152
k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit.func1(0xc820170300, 0x0, 0x0, 0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:316 +0x137
k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit.func1(0xc820170300, 0x7fa91a8a6028, 0xc820858810, 0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:381 +0x142
k8s.io/kubernetes/pkg/kubectl/resource.EagerVisitorList.Visit.func1(0xc820170300, 0x0, 0x0, 0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:195 +0x152
k8s.io/kubernetes/pkg/kubectl/resource.(*StreamVisitor).Visit(0xc8200b4700, 0xc820109fe0, 0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:540 +0x5b3
k8s.io/kubernetes/pkg/kubectl/resource.(*FileVisitor).Visit(0xc820109ea0, 0xc820109fe0, 0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:489 +0x12d
k8s.io/kubernetes/pkg/kubectl/resource.EagerVisitorList.Visit(0xc8203b14e0, 0x1, 0x1, 0xc82016f020, 0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:190 +0x12c
k8s.io/kubernetes/pkg/kubectl/resource.(*EagerVisitorList).Visit(0xc820109ec0, 0xc82016f020, 0x0, 0x0)
	<autogenerated>:116 +0xb7
k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit(0x7fa91a688928, 0xc820109ec0, 0xc8200b46c0, 0xc8200b47c0, 0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:409 +0xaa
k8s.io/kubernetes/pkg/kubectl/resource.(*FlattenListVisitor).Visit(0xc820109ee0, 0xc8200b47c0, 0x0, 0x0)
	<autogenerated>:131 +0xb7
k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit(0x7fa91a688950, 0xc820109ee0, 0xc820109f20, 0x3, 0x4, 0xc820109f80, 0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:317 +0xf0
k8s.io/kubernetes/pkg/kubectl/resource.(*DecoratedVisitor).Visit(0xc82016efc0, 0xc820109f80, 0x0, 0x0)
	<autogenerated>:150 +0xae
k8s.io/kubernetes/pkg/kubectl/resource.ContinueOnErrorVisitor.Visit(0x7fa91a688978, 0xc82016efc0, 0xc82031ec40, 0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:335 +0x12f
k8s.io/kubernetes/pkg/kubectl/resource.(*ContinueOnErrorVisitor).Visit(0xc8203b1500, 0xc82031ec40, 0x0, 0x0)
	<autogenerated>:145 +0xae
k8s.io/kubernetes/pkg/kubectl/resource.(*Result).Visit(0xc82031ebd0, 0xc82031ec40, 0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/result.go:80 +0x6d
k8s.io/kubernetes/pkg/kubectl/cmd.RunApply(0xc820174900, 0xc820310000, 0x7fa91a8aa1c0, 0xc820036010, 0xc820089640, 0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/apply.go:195 +0x754
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdApply.func1(0xc820310000, 0xc820459860, 0x0, 0x2)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/apply.go:81 +0xf8
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc820310000, 0xc820459700, 0x2, 0x2, 0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:565 +0x85a
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc8204e9c00, 0xc820310000, 0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:651 +0x55c
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc8204e9c00, 0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:610 +0x2d
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:32 +0xf0
main.main()
	/home/ivan4th/work/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:28 +0x28
```

Obtained by changing protobuf code:
```
iff --git a/vendor/github.com/gogo/protobuf/proto/properties.go b/vendor/github.com/gogo/protobuf/proto/properties.go
index 4711057..dc4a4c4 100644
--- a/vendor/github.com/gogo/protobuf/proto/properties.go
+++ b/vendor/github.com/gogo/protobuf/proto/properties.go
@@ -45,6 +45,7 @@ import (
        "log"
        "os"
        "reflect"
+       dbg "runtime/debug"
        "sort"
        "strconv"
        "strings"
@@ -777,6 +778,7 @@ func getPropertiesLocked(t reflect.Type) *StructProperties {
                }
                if p.enc == nil && !strings.HasPrefix(f.Name, "XXX_") && !oneof {
                        fmt.Fprintln(os.Stderr, "proto: no encoder for", f.Name, f.Type.String(), "[GetProperties]")
+                       dbg.PrintStack()
                }
        }
```

**Comment by ivan4th** [comment]
Note `k8s.io/kubernetes/pkg/api/v1.(*Pod).String(0xc820354000, 0x0, 0x0)` line

**Comment by smarterclayton** [comment]
Passing the object as a string to Sprintf in pkg/kubectl/cmd/apply.go is
not correct.  We should be using the raw bytes or calling encode (raw bytes
are better).  This is really a bug in the output code (although we should
come up with a fix for IntOrStr separately).

On Jun 30, 2016, at 11:11 AM, Ivan Shvedunov <notifications@github.com>
wrote:

Note k8s.io/kubernetes/pkg/api/v1.(*Pod).String(0xc820354000, 0x0, 0x0) line

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/28218#issuecomment-229742354>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABG_pyLx9I6YCebOVFrOCXLMWFSrLU3Sks5qRAbCgaJpZM4JBFUR>
.

**Comment by smarterclayton** [comment]
This was fixed.
