### ISSUE TITLE
Builder has troubles with gettting src files from github.

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#28285]
```
Fetching upstream changes from https://github.com/kubernetes/kubernetes
 > /usr/bin/git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/pull/28279/merge:refs/remotes/origin/pr/28279/merge # timeout=20
ERROR: Error fetching remote repo 'remote1'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/kubernetes/kubernetes
    at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:810)
    at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1066)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1097)
    at hudson.scm.SCM.checkout(SCM.java:485)
... skipping 6 lines ...
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Caused by: hudson.plugins.git.GitException: Command "/usr/bin/git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/pull/28279/merge:refs/remotes/origin/pr/28279/merge" returned status code 128:
stdout: 
```

More available here:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/28279/kubernetes-pull-verify-all/2669/

**Comment by jlowdermilk** [comment]
This could be problems with the github jenkins plugin (which is flaky and overall pretty bad), but github was also [briefly down](https://status.github.com/) this morning.
