### ISSUE TITLE
scheduler and controller-manager stop after problems with etcd cluster

### ISSUE THREAD

**Issue by cristifalcas** [kubernetes/kubernetes#28350]
We are using kubernetes 1.2.5 and we noticed that if there are issues with the etcd cluster, the scheduler and controller-manager are dying.

We tested this by blocking access to 2 of our 3 node cluster. After a while (maximum 5 minutes) we found both the scheduler and controller-manager down.

Those are the logs from scheduler:

```
E0630 17:40:35.284183    8299 leaderelection.go:317] err: client: etcd cluster is unavailable or misconfigured
E0630 17:40:56.303598    8299 leaderelection.go:317] err: client: etcd cluster is unavailable or misconfigured
E0630 17:40:56.303700    8299 event.go:252] Could not construct reference to: '&api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"kube-scheduler", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Subsets:[]api.EndpointSubset(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' '%v stopped leading' 'v-is-st-kub.company.net'
I0630 17:40:56.304169    8299 leaderelection.go:233] failed to renew lease kube-system/kube-scheduler
F0630 17:40:56.304225    8299 server.go:153] lost master
```

And from controller-manager

```
E0630 17:40:35.282308    7803 leaderelection.go:317] err: client: etcd cluster is unavailable or misconfigured
E0630 17:40:56.299138    7803 leaderelection.go:317] err: client: etcd cluster is unavailable or misconfigured
E0630 17:40:56.299246    7803 event.go:252] Could not construct reference to: '&api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"kube-controller-manager", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Subsets:[]api.EndpointSubset(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' '%v stopped leading' 'v-is-st-kub.company.net'
I0630 17:40:56.299497    7803 leaderelection.go:233] failed to renew lease kube-system/kube-controller-manager
F0630 17:40:56.299555    7803 controllermanager.go:178] leaderelection lost
```

From my understanding on how kubernetes works, the message that there is a problem with etcd cluster came from the apiserver, as those 2 services don't know where the cluster is. So, since the apiserver is still up, they should not fail that miserably, but to keep waiting for better news from the api.

Is this failing intentional?

**Comment by cristifalcas** [comment]
We had now the kube-controller-manager service die because it lost the election?

        I0704 14:34:30.932466     933 leaderelection.go:295] lock is held by v-is-st-nod-01.company.net and has not yet expired
        I0704 14:34:32.934409     933 leaderelection.go:295] lock is held by v-is-st-nod-01.company.net and has not yet expired
        I0704 14:34:34.941212     933 leaderelection.go:295] lock is held by v-is-st-nod-01.company.net and has not yet expired
        I0704 14:34:36.936261     933 leaderelection.go:295] lock is held by v-is-st-nod-01.company.net and has not yet expired
        I0704 14:34:38.934482     933 leaderelection.go:295] lock is held by v-is-st-nod-01.company.net and has not yet expired
        I0704 14:34:38.942084     933 leaderelection.go:295] lock is held by v-is-st-nod-01.company.net and has not yet expired
        E0704 14:34:38.942124     933 event.go:252] Could not construct reference to: '&api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"kube-controller-manager", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Subsets:[]api.EndpointSubset(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' '%v stopped leading' 'v-is-st-nod-02.company.net'
        I0704 14:34:38.942249     933 leaderelection.go:233] failed to renew lease kube-system/kube-controller-manager
        F0704 14:34:38.942275     933 controllermanager.go:178] leaderelection lost

**Comment by cdpb** [comment]
also affects me with quay.io/coreos/hyperkube:v1.3.0_coreos.1

**Comment by hectorj2f** [comment]
We also experience these problems with hyperkube:v1.3.7_coreos.0

**Comment by xh3b4sd** [comment]
We saw a similar behaviour again. We are currently playing around with the setup of the API server, controller manager and scheduler to make it more resilient in our case. We recently saw the scheduler crashing with the following panic. Unfortunately it was not recoverable anymore.

```
Sep 29 13:41:11 xh3b4sd-k8svm-master systemd[1]: Started k8s-scheduler Service.
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: I0929 13:41:12.260144       1 factory.go:257] Creating scheduler from algorithm provider 'DefaultProvider'
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: I0929 13:41:12.260223       1 factory.go:303] creating scheduler with fit predicates 'map[NoDiskConflict:{} MaxEBSVolumeCount:{} GeneralPredicates:{} CheckNodeMemoryPressure:{} NoVolumeZoneConflict:{} MaxGCEPDVolumeCount:{} PodToleratesNodeTaints:{} CheckNodeDiskPressure:{} MatchInterPodAffinity:{}]' and priority functions 'map[TaintTolerationPriority:{} InterPodAffinityPriority:{} LeastRequestedPriority:{} BalancedResourceAllocation:{} SelectorSpreadPriority:{} NodePreferAvoidPodsPriority:{} NodeAffinityPriority:{}]
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: E0929 13:41:12.403411       1 event.go:258] Could not construct reference to: '&api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"kube-scheduler", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]api.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:""}, Subsets:[]api.EndpointSubset(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' '%v became leader' 'xh3b4sd-k8svm-master'
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: I0929 13:41:12.403542       1 leaderelection.go:214] sucessfully acquired lease kube-system/kube-scheduler
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: E0929 13:41:12.404128       1 runtime.go:64] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:70
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:63
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:49
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /usr/local/go/src/runtime/asm_amd64.s:472
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /usr/local/go/src/runtime/panic.go:443
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /usr/local/go/src/runtime/panic.go:62
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /usr/local/go/src/runtime/sigpanic_unix.go:24
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:971
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:1002
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:830
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:822
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/generic_scheduler.go:215
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/generic_scheduler.go:167
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/workqueue/parallelizer.go:43
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /usr/local/go/src/runtime/asm_amd64.s:1998
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: [signal 0xb code=0x1 addr=0x10 pc=0x1f37361]
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: goroutine 225 [running]:
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: panic(0x4475c00, 0xc820012070)
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /usr/local/go/src/runtime/panic.go:481 +0x3e6
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: k8s.io/kubernetes/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:56 +0x153
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: panic(0x4475c00, 0xc820012070)
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /usr/local/go/src/runtime/panic.go:443 +0x4e9
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.(*PodAffinityChecker).getMatchingAntiAffinityTerms(0xc8209f0880, 0xc82053ea00, 0xc820011c20, 0x3, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:971 +0x131
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.(*PodAffinityChecker).satisfiesExistingPodsAntiAffinity(0xc8209f0880, 0xc82053ea00, 0x0, 0x0, 0xc82048b400, 0xc820b0c810)
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:1002 +0x986
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.(*PodAffinityChecker).InterPodAffinityMatches(0xc8209f0880, 0xc82053ea00, 0x0, 0x0, 0xc8207740c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:830 +0x117
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates.(*PodAffinityChecker).InterPodAffinityMatches-fm(0xc82053ea00, 0x0, 0x0, 0xc8207740c0, 0x4c22a01, 0x0, 0x0, 0x0, 0x0, 0x0)
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates.go:822 +0x7c
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: k8s.io/kubernetes/plugin/pkg/scheduler.podFitsOnNode(0xc82053ea00, 0x0, 0x0, 0xc8207740c0, 0xc820a0ca80, 0xc820011a00, 0x0, 0x0, 0x0, 0x0, ...)
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/generic_scheduler.go:215 +0x10e
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: k8s.io/kubernetes/plugin/pkg/scheduler.findNodesThatFit.func1(0x0)
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/generic_scheduler.go:167 +0x169
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: k8s.io/kubernetes/pkg/util/workqueue.Parallelize.func1(0xc8203c2cd0, 0xc820ff6500, 0xc821002380)
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/workqueue/parallelizer.go:43 +0xbd
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: created by k8s.io/kubernetes/pkg/util/workqueue.Parallelize
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23944]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/workqueue/parallelizer.go:45 +0x10f
Sep 29 13:41:12 xh3b4sd-k8svm-master systemd[1]: k8s-scheduler.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23972]: Failed to stop container (k8s-scheduler.service): Error response from daemon: No such container: k8s-scheduler.service
Sep 29 13:41:12 xh3b4sd-k8svm-master docker[23982]: Failed to remove container (k8s-scheduler.service): Error response from daemon: No such container: k8s-scheduler.service
Sep 29 13:41:12 xh3b4sd-k8svm-master systemd[1]: k8s-scheduler.service: Unit entered failed state.
Sep 29 13:41:12 xh3b4sd-k8svm-master systemd[1]: k8s-scheduler.service: Failed with result 'exit-code'.
Sep 29 13:41:12 xh3b4sd-k8svm-master systemd[1]: k8s-scheduler.service: Service has no hold-off time, scheduling restart.
```

Dropping all data from etcd worked around this issue and the scheduler was able to properly register again.

**Comment by xiang90** [comment]
this panic is fixed by https://github.com/kubernetes/kubernetes/pull/33086.

**Comment by timothysc** [comment]
This should be closed.
