### ISSUE TITLE
problem with upgrading nodes

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#28361]
Reported by @fgrzadkowski when attempting a 1.2.5->1.3.0-beta.3 upgrade test.
Nodes cannot register as apiserver is returning 415 error code
```
I0701 11:53:12.877874       7 handlers.go:152] POST /api/v1/nodes: (435.314µs) 415
goroutine 70665 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc20bd507e0, 0x19f)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:214 +0xa6
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc20bd507e0, 0x19f)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:193 +0x32
k8s.io/kubernetes/pkg/apiserver.(*baseTimeoutWriter).WriteHeader(0xc20b73bd20, 0x19f)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:258 +0xba
k8s.io/kubernetes/pkg/apiserver/metrics.(*responseWriterDelegator).WriteHeader(0xc20ac442d0, 0x19f)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:117 +0x53
k8s.io/kubernetes/pkg/apiserver.writeNegotiated(0x7fd201b69fb8, 0xc20821a2a0, 0x0, 0x0, 0x1d4dd00, 0x2, 0x7fd2019c1788, 0xc20c605318, 0xc20b77aa90, 0x19f, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:429 +0x174
k8s.io/kubernetes/pkg/apiserver.errorNegotiated(0x7fd201893328, 0xc20b73bea0, 0x7fd201b69fb8, 0xc20821a2a0, 0x0, 0x0, 0x1d4dd00, 0x2, 0x7fd2019c1788, 0xc20c605318, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:441 +0xdd
k8s.io/kubernetes/pkg/apiserver.(*RequestScope).err(0xc208468ea0, 0x7fd201893328, 0xc20b73bea0, 0x7fd2019c1788, 0xc20c605318, 0xc20b77aa90)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:84 +0x11f
k8s.io/kubernetes/pkg/apiserver.func·029(0xc20ac441b0, 0xc20bc892c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:361 +0x54a
k8s.io/kubernetes/pkg/apiserver/metrics.func·001(0xc20ac441b0, 0xc20bc892c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:101 +0x269
github.com/emicklei/go-restful.(*Container).dispatch(0xc2082193b0, 0x7fd2019c15c8, 0xc20c [[kubelet/v1.3.0 (linux/amd64) kubernetes/a303f87] 10.128.0.3:57505]
```

**Comment by erictune** [comment]
@dchen1107

**Comment by erictune** [comment]
Never mind, filip later realized that this was due to upgrading nodes before master by accident, which is not expected to work under our current upgrade SLA.
