### ISSUE TITLE
ghprb plugin may fail to update github status

### ISSUE THREAD

**Issue by fejta** [kubernetes/kubernetes#28662]
Example: http://kubekins.dls.corp.google.com:8081/job/node-pull-build-e2e-test/13440/consoleFull

```
Using context: Jenkins GCE Node e2e
Could not update commit status of the Pull Request on GitHub.
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
	at sun.security.ssl.InputRecord.read(InputRecord.java:480)
	at sun.security.ssl.S
```

**Comment by spxtr** [comment]
Might have run out of API tokens.

**Comment by spxtr** [comment]
We were probably out of API tokens, since I think this might have been around the time Jeff was experimenting with the newer PRB plugin.

Please reopen if you see it again.
