### ISSUE TITLE
rolling-update with empty file panics

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#29398]
For example
```
> touch empty
> kubectl rolling-update rcname  -f empty

panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x19dca80, 0xc82000e0d0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
k8s.io/kubernetes/pkg/kubectl/cmd.RunRollingUpdate(0xc8204c6200, 0x7fda65fb6198, 0xc820090008, 0xc820324800, 0xc8200a4690, 0x1, 0x5, 0xc82029f380, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/rollingupdate.go:220 +0x46ee
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdRollingUpdate.func1(0xc820324800, 0xc8200a4690, 0x1, 0x5)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/rollingupdate.go:86 +0x7d
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc820324800, 0xc8200a4640, 0x5, 0x5, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:565 +0x85a
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc8200d2000, 0xc820324800, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:651 +0x55c
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc8200d2000, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:610 +0x2d
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:32 +0xf0
main.main()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:28 +0x28
```

**Comment by justinsb** [comment]
This is with recent kubectl:

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"283137936a498aed572ee22af6774b6fb6e9fd94", GitTreeState:"clean", BuildDate:"2016-07-01T19:26:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by pwittrock** [comment]
@AdoHe I think this is a duplicate, but just in case.

**Comment by AdoHe** [comment]
I will double check this.

**Comment by justinsb** [comment]
Thanks - it isn't a big deal, because I obviously didn't intend to rolling update to an empty manifest :-)  (I was experimenting with templating my manifests and made an error)   But let me know if you need any more info to reproduce!
