### ISSUE TITLE
Vagrant NFS folder syncing is hanging up on Fedora

### ISSUE THREAD

**Issue by nhlfr** [kubernetes/kubernetes#29916]
On Fedora (probably all the versions, but I'm using Fedora 24), using vagrant provider with the following exports:

```
export KUBERNETES_PROVIDER=vagrant
export VAGRANT_DEFAULT_PROVIDER=libvirt
export KUBERNETES_VAGRANT_USE_NFS=true
```

results in hanging up on the folder sync step:

```
... Starting cluster using provider: vagrant
... calling verify-prereqs
... calling kube-up
Bringing machine 'master' up with 'libvirt' provider...
Bringing machine 'node-1' up with 'libvirt' provider...
==> master: Creating image (snapshot of base box volume).
==> master: Creating domain with the following settings...
==> master:  -- Name:              kubernetes_master
==> master:  -- Domain type:       kvm
==> master:  -- Cpus:              4
==> master:  -- Memory:            1280M
==> master:  -- Management MAC:    
==> master:  -- Loader:            
==> master:  -- Base box:          kube-fedora23
==> master:  -- Storage pool:      default
==> master:  -- Image:             /var/lib/libvirt/images/kubernetes_master.img (41G)
==> master:  -- Volume Cache:      none
==> master:  -- Kernel:            
==> master:  -- Initrd:            
==> master:  -- Graphics Type:     vnc
==> master:  -- Graphics Port:     5900
==> master:  -- Graphics IP:       127.0.0.1
==> master:  -- Graphics Password: Not defined
==> master:  -- Video Type:        cirrus
==> master:  -- Video VRAM:        9216
==> master:  -- Keymap:            en-us
==> master:  -- INPUT:             type=mouse, bus=ps2
==> master:  -- Command line : 
==> master: Pruning invalid NFS exports. Administrator privileges will be required...
[sudo] password for nhlfr: 
==> master: Creating shared folders metadata...
==> master: Starting domain.
==> master: Waiting for domain to get an IP address...
==> master: Waiting for SSH to become available...
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
    master: 
    master: Vagrant insecure key detected. Vagrant will automatically replace
    master: this with a newly generated keypair for better security.
    master: 
    master: Inserting generated public key within guest...
    master: Removing insecure key from the guest if it's present...
    master: Key inserted! Disconnecting and reconnecting using new SSH key...
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
==> master: Configuring and enabling network interfaces...
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:80:in `ping': Object#timeout is deprecated, use Timeout.timeout instead.
==> master: Installing NFS client...
==> master: Exporting NFS shared folders...
==> master: Preparing to edit /etc/exports. Administrator privileges will be required...
Redirecting to /bin/systemctl status  nfs-server.service
● nfs-server.service - NFS server and services
   Loaded: loaded (/usr/lib/systemd/system/nfs-server.service; enabled; vendor preset: disabled)
   Active: active (exited) since Tue 2016-08-02 12:04:14 CEST; 3h 16min ago
  Process: 1204 ExecStart=/usr/sbin/rpc.nfsd $RPCNFSDARGS (code=exited, status=0/SUCCESS)
  Process: 1198 ExecStartPre=/usr/sbin/exportfs -r (code=exited, status=0/SUCCESS)
 Main PID: 1204 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 512)
   Memory: 0B
      CPU: 0
   CGroup: /system.slice/nfs-server.service

Aug 02 12:04:14 nhlfr-pc.localdomain systemd[1]: Starting NFS server and services...
Aug 02 12:04:14 nhlfr-pc.localdomain systemd[1]: Started NFS server and services.
==> master: Mounting NFS shared folders...
```

This is most probably because of lack of `vers=3` mount option. In theory, Vagrant should pick up the ver 3 by default, but in practice, Vagrant on Fedora is always failing without this option provided explicitly in Vagrantfile.

**Comment by spiffxp** [comment]
/sig cluster-lifecycle
because this is kube-up, but I'm not sure who owns the vagrant provider
