### ISSUE TITLE
Dockfile for examples/celery-rabbitmq does not match docker image in docker hub.

### ISSUE THREAD

**Issue by againer** [kubernetes/kubernetes#30936]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): celery-rabbitmq

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0+5cb86ee", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"not a git tree"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.3", GitCommit:"c6411395e09da356c608896d3d9725acab821418", GitTreeState:"dirty"}

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): OSX
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
If I build and host the image built from `celery-app-add/Dockerfile`, the example does not work as expected.

**What you expected to happen**:
If I build the docker image and host it on docker hub, the image should be the same as the one hosted on `endocode/celery-app-add` and work with the example.

**How to reproduce it** (as minimally and precisely as possible):

``` bash
# run all of the controllers and services in the example
# see the tasks being run successfully via the flower interface
# shutdown the rc's and the services
cd celery-app-add
docker build -t <mine>/celery-app-add .
docker push <mine>/celery-app-add
# in the celery replication controller config, replace endocode/celery-app-add with <mine>/celery-app-add.
# run all the controllers and services in the example
# look at the logs for the celery-controller after kubectl get pods shows an Error has occurred.
```

**Anything else do we need to know**:
Main errors from the controller logs:

```
Traceback (most recent call last):
2016-08-18T21:05:44.050245103Z   File "/usr/local/bin/celery", line 11, in <module>
2016-08-18T21:05:44.050249543Z     sys.exit(main())
2016-08-18T21:05:44.050251856Z   File "/usr/local/lib/python3.4/site-packages/celery/__main__.py", line 30, in main
2016-08-18T21:05:44.050255000Z     main()
2016-08-18T21:05:44.050257252Z   File "/usr/local/lib/python3.4/site-packages/celery/bin/celery.py", line 81, in main
2016-08-18T21:05:44.050259392Z     cmd.execute_from_commandline(argv)
2016-08-18T21:05:44.050261768Z   File "/usr/local/lib/python3.4/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline
2016-08-18T21:05:44.050264057Z     super(CeleryCommand, self).execute_from_commandline(argv)))
2016-08-18T21:05:44.050266462Z   File "/usr/local/lib/python3.4/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
2016-08-18T21:05:44.050268613Z     return self.handle_argv(self.prog_name, argv[1:])
2016-08-18T21:05:44.050270723Z   File "/usr/local/lib/python3.4/site-packages/celery/bin/celery.py", line 785, in handle_argv
2016-08-18T21:05:44.050273025Z     return self.execute(command, argv)
2016-08-18T21:05:44.050275154Z   File "/usr/local/lib/python3.4/site-packages/celery/bin/celery.py", line 717, in execute
2016-08-18T21:05:44.050277285Z     ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
2016-08-18T21:05:44.050279383Z   File "/usr/local/lib/python3.4/site-packages/celery/bin/worker.py", line 179, in run_from_argv
2016-08-18T21:05:44.050281510Z     return self(*args, **options)
2016-08-18T21:05:44.050283584Z   File "/usr/local/lib/python3.4/site-packages/celery/bin/base.py", line 274, in __call__
2016-08-18T21:05:44.050286059Z     ret = self.run(*args, **kwargs)
2016-08-18T21:05:44.050288113Z   File "/usr/local/lib/python3.4/site-packages/celery/bin/worker.py", line 212, in run
2016-08-18T21:05:44.050290266Z     state_db=self.node_format(state_db, hostname), **kwargs
2016-08-18T21:05:44.050292354Z   File "/usr/local/lib/python3.4/site-packages/celery/worker/__init__.py", line 100, in __init__
2016-08-18T21:05:44.050294484Z     self.setup_instance(**self.prepare_args(**kwargs))
2016-08-18T21:05:44.050296529Z   File "/usr/local/lib/python3.4/site-packages/celery/worker/__init__.py", line 136, in setup_instance
2016-08-18T21:05:44.050298729Z     self.on_init_blueprint()
2016-08-18T21:05:44.050300747Z   File "/usr/local/lib/python3.4/site-packages/celery/apps/worker.py", line 143, in on_init_blueprint
2016-08-18T21:05:44.050302904Z     self._custom_logging = self.setup_logging()
2016-08-18T21:05:44.050304982Z   File "/usr/local/lib/python3.4/site-packages/celery/apps/worker.py", line 184, in setup_logging
2016-08-18T21:05:44.050307151Z     redirect_stdouts=False, colorize=colorize, hostname=self.hostname,
2016-08-18T21:05:44.050309202Z   File "/usr/local/lib/python3.4/site-packages/celery/app/log.py", line 70, in setup
2016-08-18T21:05:44.050313694Z     loglevel, logfile, colorize=colorize, hostname=hostname,
2016-08-18T21:05:44.050315963Z   File "/usr/local/lib/python3.4/site-packages/celery/app/log.py", line 118, in setup_logging_subsystem
2016-08-18T21:05:44.050318135Z     root, logfile, loglevel, format, colorize, **kwargs
2016-08-18T21:05:44.050320218Z   File "/usr/local/lib/python3.4/site-packages/celery/app/log.py", line 156, in _configure_logger
2016-08-18T21:05:44.050322390Z     colorize, **kwargs)
2016-08-18T21:05:44.050328980Z   File "/usr/local/lib/python3.4/site-packages/celery/app/log.py", line 222, in setup_handlers
2016-08-18T21:05:44.050331228Z     handler = self._detect_handler(logfile)
2016-08-18T21:05:44.050333300Z   File "/usr/local/lib/python3.4/site-packages/celery/app/log.py", line 233, in _detect_handler
2016-08-18T21:05:44.050335504Z     return WatchedFileHandler(logfile)
2016-08-18T21:05:44.050337579Z   File "/usr/local/lib/python3.4/logging/handlers.py", line 434, in __init__
2016-08-18T21:05:44.050339701Z     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
2016-08-18T21:05:44.050341771Z   File "/usr/local/lib/python3.4/logging/__init__.py", line 1006, in __init__
2016-08-18T21:05:44.050343962Z     StreamHandler.__init__(self, self._open())
2016-08-18T21:05:44.050346003Z   File "/usr/local/lib/python3.4/logging/__init__.py", line 1035, in _open
2016-08-18T21:05:44.050348139Z     return open(self.baseFilename, self.mode, encoding=self.encoding)
2016-08-18T21:05:44.050350245Z PermissionError: [Errno 13] Permission denied: '/data/celery.log'
2016-08-18T21:05:44.846560901Z Traceback (most recent call last):
2016-08-18T21:05:44.846585632Z   File "/usr/local/lib/python3.4/site-packages/kombu/utils/__init__.py", line 423, in __call__
2016-08-18T21:05:44.846589080Z     return self.__value__
2016-08-18T21:05:44.846591547Z AttributeError: 'ChannelPromise' object has no attribute '__value__'
2016-08-18T21:05:44.846594397Z 
2016-08-18T21:05:44.846596670Z During handling of the above exception, another exception occurred:
2016-08-18T21:05:44.846599160Z 
2016-08-18T21:05:44.846602697Z Traceback (most recent call last):
2016-08-18T21:05:44.846605622Z   File "/usr/local/lib/python3.4/site-packages/kombu/connection.py", line 436, in _ensured
2016-08-18T21:05:44.846608180Z     return fun(*args, **kwargs)
2016-08-18T21:05:44.846610541Z   File "/usr/local/lib/python3.4/site-packages/kombu/messaging.py", line 177, in _publish
2016-08-18T21:05:44.846613045Z     channel = self.channel
2016-08-18T21:05:44.846615384Z   File "/usr/local/lib/python3.4/site-packages/kombu/messaging.py", line 194, in _get_channel
2016-08-18T21:05:44.846617891Z     channel = self._channel = channel()
2016-08-18T21:05:44.846620241Z   File "/usr/local/lib/python3.4/site-packages/kombu/utils/__init__.py", line 425, in __call__
2016-08-18T21:05:44.846629338Z     value = self.__value__ = self.__contract__()
2016-08-18T21:05:44.846632038Z   File "/usr/local/lib/python3.4/site-packages/kombu/messaging.py", line 209, in <lambda>
2016-08-18T21:05:44.846634927Z     channel = ChannelPromise(lambda: connection.default_channel)
2016-08-18T21:05:44.846637680Z   File "/usr/local/lib/python3.4/site-packages/kombu/connection.py", line 757, in default_channel
2016-08-18T21:05:44.846640157Z     self.connection
2016-08-18T21:05:44.846642449Z   File "/usr/local/lib/python3.4/site-packages/kombu/connection.py", line 742, in connection
2016-08-18T21:05:44.846647641Z     self._connection = self._establish_connection()
2016-08-18T21:05:44.846650088Z   File "/usr/local/lib/python3.4/site-packages/kombu/connection.py", line 697, in _establish_connection
2016-08-18T21:05:44.846652585Z     conn = self.transport.establish_connection()
2016-08-18T21:05:44.846654920Z   File "/usr/local/lib/python3.4/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
2016-08-18T21:05:44.846657470Z     conn = self.Connection(**opts)
2016-08-18T21:05:44.846659906Z   File "/usr/local/lib/python3.4/site-packages/amqp/connection.py", line 165, in __init__
2016-08-18T21:05:44.846662391Z     self.transport = self.Transport(host, connect_timeout, ssl)
2016-08-18T21:05:44.846664825Z   File "/usr/local/lib/python3.4/site-packages/amqp/connection.py", line 186, in Transport
2016-08-18T21:05:44.846667875Z     return create_transport(host, connect_timeout, ssl)
2016-08-18T21:05:44.846670268Z   File "/usr/local/lib/python3.4/site-packages/amqp/transport.py", line 299, in create_transport
2016-08-18T21:05:44.846672756Z     return TCPTransport(host, connect_timeout)
2016-08-18T21:05:44.846675143Z   File "/usr/local/lib/python3.4/site-packages/amqp/transport.py", line 75, in __init__
2016-08-18T21:05:44.846677673Z     socket.SOCK_STREAM, SOL_TCP):
2016-08-18T21:05:44.846679979Z   File "/usr/local/lib/python3.4/socket.py", line 537, in getaddrinfo
2016-08-18T21:05:44.846682362Z     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2016-08-18T21:05:44.846684732Z socket.gaierror: [Errno -2] Name or service not known
2016-08-18T21:05:44.846687050Z 
2016-08-18T21:05:44.846689219Z During handling of the above exception, another exception occurred:
2016-08-18T21:05:44.846691505Z 
2016-08-18T21:05:44.846693743Z Traceback (most recent call last):
2016-08-18T21:05:44.846695985Z   File "/data/run_tasks.py", line 26, in <module>
2016-08-18T21:05:44.846698517Z     res = add.delay(x, y)
2016-08-18T21:05:44.846700778Z   File "/usr/local/lib/python3.4/site-packages/celery/app/task.py", line 453, in delay
2016-08-18T21:05:44.846703182Z     return self.apply_async(args, kwargs)
2016-08-18T21:05:44.846705514Z   File "/usr/local/lib/python3.4/site-packages/celery/app/task.py", line 565, in apply_async
2016-08-18T21:05:44.846710322Z     **dict(self._get_exec_options(), **options)
2016-08-18T21:05:44.846712875Z   File "/usr/local/lib/python3.4/site-packages/celery/app/base.py", line 354, in send_task
2016-08-18T21:05:44.846715423Z     reply_to=reply_to or self.oid, **options
2016-08-18T21:05:44.846717803Z   File "/usr/local/lib/python3.4/site-packages/celery/app/amqp.py", line 310, in publish_task
2016-08-18T21:05:44.846720446Z     **kwargs
2016-08-18T21:05:44.846722739Z   File "/usr/local/lib/python3.4/site-packages/kombu/messaging.py", line 172, in publish
2016-08-18T21:05:44.846725169Z     routing_key, mandatory, immediate, exchange, declare)
2016-08-18T21:05:44.846727541Z   File "/usr/local/lib/python3.4/site-packages/kombu/connection.py", line 457, in _ensured
2016-08-18T21:05:44.846730008Z     interval_max)
2016-08-18T21:05:44.846732299Z   File "/usr/local/lib/python3.4/site-packages/kombu/connection.py", line 369, in ensure_connection
2016-08-18T21:05:44.846734843Z     interval_start, interval_step, interval_max, callback)
2016-08-18T21:05:44.846737195Z   File "/usr/local/lib/python3.4/site-packages/kombu/utils/__init__.py", line 246, in retry_over_time
2016-08-18T21:05:44.846739709Z     return fun(*args, **kwargs)
2016-08-18T21:05:44.846741974Z   File "/usr/local/lib/python3.4/site-packages/kombu/connection.py", line 237, in connect
2016-08-18T21:05:44.846744395Z     return self.connection
2016-08-18T21:05:44.846746626Z   File "/usr/local/lib/python3.4/site-packages/kombu/connection.py", line 742, in connection
2016-08-18T21:05:44.846749063Z     self._connection = self._establish_connection()
2016-08-18T21:05:44.846751414Z   File "/usr/local/lib/python3.4/site-packages/kombu/connection.py", line 697, in _establish_connection
2016-08-18T21:05:44.846753887Z     conn = self.transport.establish_connection()
2016-08-18T21:05:44.846757108Z   File "/usr/local/lib/python3.4/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
2016-08-18T21:05:44.846760036Z     conn = self.Connection(**opts)
2016-08-18T21:05:44.846762698Z   File "/usr/local/lib/python3.4/site-packages/amqp/connection.py", line 165, in __init__
2016-08-18T21:05:44.846765212Z     self.transport = self.Transport(host, connect_timeout, ssl)
2016-08-18T21:05:44.846767574Z   File "/usr/local/lib/python3.4/site-packages/amqp/connection.py", line 186, in Transport
2016-08-18T21:05:44.846769994Z     return create_transport(host, connect_timeout, ssl)
2016-08-18T21:05:44.846772397Z   File "/usr/local/lib/python3.4/site-packages/amqp/transport.py", line 299, in create_transport
2016-08-18T21:05:44.846774845Z     return TCPTransport(host, connect_timeout)
2016-08-18T21:05:44.846777109Z   File "/usr/local/lib/python3.4/site-packages/amqp/transport.py", line 75, in __init__
2016-08-18T21:05:44.846779524Z     socket.SOCK_STREAM, SOL_TCP):
2016-08-18T21:05:44.846783728Z   File "/usr/local/lib/python3.4/socket.py", line 537, in getaddrinfo
2016-08-18T21:05:44.846786248Z     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2016-08-18T21:05:44.846788640Z socket.gaierror: [Errno -2] Name or service not known
```

(sorry for the wall of text)

Docker history and undocker seem to show that the Dockerfile here produces a different image than what is hosted at endocode/celery-app-add. If I bash into endocode, I start in `/data` as `root` and if I bash into <mine> I start in `~` as `user`. Perhaps I am building the image incorrectly though.

**Comment by againer** [comment]
A little more info -- if I push celery logs to stdout, I get the following:
```
Cannot connect to amqp://guest:**@rabbit:5672//: [Errno -2] Name or service not known.
```

**Comment by jeffmendoza** [comment]
@againer thanks for the report. This example was submitted March 2015 and hasn't been updated since. Looks like `examples/celery-rabbitmq/celery-app-add/Dockerfile` originally imported `dockerfile/celery` which was changed to `library/celery`. I imagine a lot has changed in those base images. Are you interested in updating the image source to something that works now?

@kbeecher any chance you wish to update this example?

**Comment by againer** [comment]
Yeah, I can make the updates to the Dockerfile.  My solution is a somewhat of a hack.

**Comment by againer** [comment]
Sorry for the delay on the changes; been slammed.  I will make the changes soon.

**Comment by spiffxp** [comment]
/sig apps
because examples
/assign
closing due to inactivity, and the example isn't in the new home of https://github.com/kubernetes/examples; please reopen over there if you'd like to introduce back in as a maintained example
