### ISSUE TITLE
Rollback subresource returns a bad object type?

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#31738]
Seen many times in test logs. (e.g. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/31559/kubernetes-pull-build-test-e2e-gce/56433/)

```
I0829 20:27:32.582732       5 handlers.go:162] POST /apis/extensions/v1beta1/namespaces/e2e-tests-deployment-vk5cb/deployments/test-rollback-deployment/rollback: (5.162106ms) 500
goroutine 41717 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc826032770, 0x1f4)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:214 +0xa3
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc826032770, 0x1f4)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:193 +0x2b
k8s.io/kubernetes/pkg/apiserver/metrics.(*responseWriterDelegator).WriteHeader(0xc825844510, 0x1f4)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:117 +0x4c
k8s.io/kubernetes/pkg/apiserver.errorJSONFatal(0x0, 0x0, 0x7f2de1595ee8, 0xc825b6a880, 0x7f2de13aa4b0, 0xc822b571a0, 0xc824228f00)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:520 +0x47a
k8s.io/kubernetes/pkg/apiserver.writeNegotiated(0x7f2de1595e70, 0xc820191260, 0x3f1fd80, 0xa, 0x3eeb0f8, 0x7, 0x7f2de13aa4b0, 0xc822b571a0, 0xc82128b0a0, 0xc9, ...)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:490 +0x3d4
k8s.io/kubernetes/pkg/apiserver.write(0xc9, 0x3f1fd80, 0xa, 0x3eeb0f8, 0x7, 0x7f2de1595e70, 0xc820191260, 0x0, 0x0, 0x7f2de13aa4b0, ...)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:473 +0xbde
k8s.io/kubernetes/pkg/apiserver.createHandler.func1(0xc825844480, 0xc823d11500)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:421 +0x17b3
k8s.io/kubernetes/pkg/apiserver/metrics.InstrumentRouteFunc.func1(0xc825844480, 0xc823d11500)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:101 +0x25f
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc8206d9170, 0x7f2de13aa310, 0xc826032770, 0xc82128b0a0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:272 +0xf30
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x7f2de13aa310, 0xc826032770, 0xc82128b0a0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc821312d30, 0x7f2de13aa310, 0xc826032770, 0xc82128b0a0)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc8206cbef0, 0x7f2de13aa310, 0xc826032770, 0xc82128b0a0)
    /usr/local/go/src/net/http/server.go:1910 +0x17d
k8s.io/kubernetes/pkg/apiserver.WithAuthorizationCheck.func1(0x7f2de13aa310, 0xc826032770, 0xc82128b0a0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:476 +0x36c
net/http.HandlerFunc.ServeHTTP(0xc8202e18c0, 0x7f2de13aa310, 0xc826032770, 0xc82128b0a0)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/apiserver.WithImpersonation.func1(0x7f2de13aa310, 0xc826032770, 0xc82128b0a0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handler_impersonation.go:44 +0x2b4
net/http.HandlerFunc.ServeHTTP(0xc8202e1900, 0x7f2de13aa310, 0xc826032770, 0xc82128b0a0)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/auth/handlers.NewRequestAuthenticator.func1(0x7f2de13aa310, 0xc826032770, 0xc82128b0a0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/auth/handlers/handlers.go:66 +0x2c9
net/http.HandlerFunc.ServeHTTP(0xc820671810, 0x7f2de13aa310, 0xc826032770, 0xc82128b0a0)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/api.NewRequestContextFilter.func1(0x7f2de13aa310, 0xc826032770, 0xc82128b0a0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101 +0x157
net/http.HandlerFunc.ServeHTTP(0xc8202740a0, 0x7f2de13aa310, 0xc826032770, 0xc82128b0a0)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/api.NewRequestContextFilter.func1(0x7f2de13aa310, 0xc826032770, 0xc82128b0a0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101 +0x157
net/http.HandlerFunc.ServeHTTP(0xc820274100, 0x7f2de13aa310, 0xc826032770, 0xc82128b0a0)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/apiserver.RecoverPanics.func1(0x7f2de13aa310, 0xc826032770, 0xc82128b0a0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:161 +0x1f3
net/http.HandlerFunc.ServeHTTP(0xc821b95260, 0x7f2de13aa2d8, 0xc822b57190, 0xc82128b0a0)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/apiserver.(*timeoutHandler).ServeHTTP.func1(0xc821b95280, 0x7f2de13aa298, 0xc822b57190, 0xc82128b0a0, 0xc823d11380)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:194 +0x8d
created by k8s.io/kubernetes/pkg/apiserver.(*timeoutHandler).ServeHTTP
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:196 +0x15b
 [[e2e.test/v1.4.0 (linux/amd64) kubernetes/b6295c2] 104.197.121.19:44544]
```

**Comment by janetkuo** [comment]
Right before the 500 return code:
```
E0829 20:27:32.582492       5 apiserver.go:510] apiserver was unable to write a JSON response: expected pointer, but got invalid kind
E0829 20:27:32.582533       5 errors.go:63] apiserver received an error that is not an unversioned.Status: expected pointer, but got invalid kind
I0829 20:27:32.582732       5 handlers.go:162] POST /apis/extensions/v1beta1/namespaces/e2e-tests-deployment-vk5cb/deployments/test-rollback-deployment/rollback: (5.162106ms) 500
```

In pkg/apiserver/apiserver.go#writeNegotiated, the input object is nil, and caused this error

**Comment by kargakis** [comment]
There are cases in the rollback rest where we return plain errors instead of api errors
