### ISSUE TITLE
latest kubectl run can panic

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#32206]
```
root@ubuntu-8gb-lon1-04:~# kubectl run -i -t busybox --image=busybox --restart=Never
Waiting for pod default/busybox to be running, status is Pending, pod ready: false
Waiting for pod default/busybox to be running, status is Pending, pod ready: false
If you don't see a command prompt, try pressing enter.
                                                      panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x5650ec]

goroutine 1 [running]:
panic(0x2488aa0, 0xc82000e0c0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
fmt.Fprintf(0x0, 0x0, 0x29d7000, 0x2a, 0xc8204f7368, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:189 +0xac
k8s.io/kubernetes/pkg/kubectl/cmd.handleAttachPod(0xc82049f9e0, 0xc820479e60, 0xc82051a260, 0x7, 0xc82051a250, 0x7, 0xc82033a600, 0xc820181c00, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/run.go:482 +0x6c9
k8s.io/kubernetes/pkg/kubectl/cmd.Run(0xc82049f9e0, 0x7f81e4a0f2e8, 0xc82002a008, 0x7f81e4a0f210, 0xc82002a010, 0x7f81e4a0f210, 0xc82002a018, 0xc82041e480, 0xc8201c9630, 0x1, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/run.go:283 +0x18c6
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdRun.func1(0xc82041e480, 0xc8201c9630, 0x1, 0x5)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/run.go:93 +0x124
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc82041e480, 0xc8201c95e0, 0x5, 0x5, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:603 +0x896
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc8203c86c0, 0xc82041e480, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:689 +0x55c
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc8203c86c0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:648 +0x2d
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:38 +0x11e
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:26 +0x18
root@ubuntu-8gb-lon1-04:~# 
```

This was build from master earlier today.

**Comment by luxas** [comment]
cc @pwittrock @thockin @lavalamp @roberthbailey 
This should be fixed before v1.4

**Comment by pwittrock** [comment]
@foxish This is critical

**Comment by pwittrock** [comment]
This needs to be tracked as a 1.4 blocker

**Comment by pwittrock** [comment]
ETA for resolution: This afternoon

This is in the process of being cherrypicked
