### ISSUE TITLE
Error in JSON encoding in apiserver

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#32288]
We got an interesting failure: https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-kubemark-high-density-100-gce/1186

What happend is that encoding `runtime.Object` to JSON failed in pod list (apiserver/apiserver.go:495):

```
if err := encoder.Encode(object, w); err != nil {
    errorJSONFatal(err, encoder, w)
}
```

logs from the API server:

```
I0907 10:37:05.177940    2915 handlers.go:162] GET /api/v1/pods: (1.815800129s) 500
goroutine 474266 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc83fde0230, 0x1f4)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:219 +0xa3
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc83fde0230, 0x1f4)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:198 +0x2b
k8s.io/kubernetes/pkg/apiserver/metrics.(*responseWriterDelegator).WriteHeader(0xc83fba1b90, 0x1f4)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:117 +0x4c
k8s.io/kubernetes/pkg/apiserver.errorJSONFatal(0x0, 0x0, 0x7f3b5cff6118, 0xc83670a100, 0x7f3b5cfe8b38, 0xc83a0d87d0, 0xc846842eb0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:526 +0x47a
k8s.io/kubernetes/pkg/apiserver.writeNegotiated(0x7f3b5cff60a0, 0xc820253d50, 0x0, 0x0, 0x3f10a88, 0x2, 0x7f3b5cfe8b38, 0xc83a0d87d0, 0xc8252e8460, 0xc8, ...)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:496 +0x3d4
k8s.io/kubernetes/pkg/apiserver.write(0xc8, 0x0, 0x0, 0x3f10a88, 0x2, 0x7f3b5cff60a0, 0xc820253d50, 0x7f3b5cf809f0, 0xc842fe8fc0, 0x7f3b5cfe8b38, ...)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:479 +0xbde
k8s.io/kubernetes/pkg/apiserver.ListResource.func1(0xc83fba1b00, 0xc842fe8f00)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:328 +0xe5b
k8s.io/kubernetes/pkg/apiserver/metrics.InstrumentRouteFunc.func1(0xc83fba1b00, 0xc842fe8f00)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:101 +0x25f
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc82035acf0, 0x7f3b5d02e808, 0xc83fde0230, 0xc8252e8460)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:272 +0xf30
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x7f3b5d02e808, 0xc83fde0230, 0xc8252e8460)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc820f955b0, 0x7f3b5d02e808, 0xc83fde0230, 0xc8252e8460)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
```

and client side error:

```
couldn't get version/kind; json parse error: unexpected end of JSON input
```

It's very rare (it's the first time we saw it), but it probably indicates some real problem. Only explanations we were able to think of is either the bug in json encoding library (rather unlikely, as this should be a pretty straighforward) or a memory corruption (which we think is more likely). The latter would indicate a bug in a go compiler (unlikely) or a bug in our code, as we started to pass pointers instead of copies in a lot of places some time ago.

cc @wojtek-t @smarterclayton @lavalamp @kubernetes/sig-api-machinery

**Comment by smarterclayton** [comment]
No chance of running out of memory briefly during the encode?

**Comment by smarterclayton** [comment]
How many total pods would have been listed here?  1.8 seconds is a lot
even for a big list

**Comment by lavalamp** [comment]
@gmarek you left out the most important bit in your cut-n-paste:

```
logging error output:
"{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"write
tcp 10.240.0.6:443-\\u003e130.211.175.198:33550: write: connection reset by
peer\",\"code\":500}\n"
```

**Comment by lavalamp** [comment]
So this must have been a network drop or something like that.

Or maybe it was a client parse error, and the client then dropped the
connection without completely reading it.

Or maybe the server emitted some bunk JSON? Hard to say without the actual
body that was transmitted to the client. I don't think clients typically
write that on error :(

**Comment by wojtek-t** [comment]
@smarterclayton I'm pretty sure this wasn't out-of-memory issue in apiserver, because we had tens of GB of free space.
It was about 50.000 pods in this list.

@lavalamp yeah - this "write connection reset by peer" changes a lot - it basically explains the parsing error.
So the question is only why the connection was reset here...

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.
