### ISSUE TITLE
[Flake][e2e smoke gke] ERROR: Error fetching remote repo 'remote'

### ISSUE THREAD

**Issue by resouer** [kubernetes/kubernetes#32574]
It seems gke e2e smoke test is somehow down:

```
Error lines from build-log.txt
... skipping 5 lines ...
 > /usr/bin/git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from 2 remote Git repositories
 > /usr/bin/git config remote.remote.url https://github.com/kubernetes/kubernetes # timeout=10
Fetching upstream changes from https://github.com/kubernetes/kubernetes
 > /usr/bin/git --version # timeout=10
 > /usr/bin/git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/heads/*:refs/remotes/upstream/* # timeout=20
ERROR: Error fetching remote repo 'remote'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/kubernetes/kubernetes
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:810)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1066)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1097)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
... skipping 2 lines ...
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: hudson.plugins.git.GitException: Command "/usr/bin/git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/heads/*:refs/remotes/upstream/*" returned status code 128:
stdout: 
stderr: error: object file .git/objects/17/d4cf1af43a03a5997ea9142b19e5b1ac2d8747 is empty
fatal: loose object 17d4cf1af43a03a5997ea9142b19e5b1ac2d8747 (stored in .git/objects/17/d4cf1af43a03a5997ea9142b19e5b1ac2d8747) is corrupt
fatal: The remote end hung up unexpectedly
```

**Comment by rmmh** [comment]
Worker was rebooted and got a corrupted git tree. I'll add some automation to clean this up without manual intervention.

**Comment by rmmh** [comment]
This was fixed.
