### ISSUE TITLE
Adding --runtime-config="api/all=false" crashes apiserver

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#33293]
With

```
I0922 17:55:26.060656       5 master.go:297] Skipping disabled API group "rbac.authorization.k8s.io".
I0922 17:55:26.060710       5 master.go:297] Skipping disabled API group "storage.k8s.io".
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x10178c9]

goroutine 1 [running]:
panic(0x38b05e0, 0xc820016070)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
k8s.io/kubernetes/pkg/registry/service/ipallocator/controller.(*Repair).runOnce.func1(0x39a7aa0, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/service/ipallocator/controller/repair.go:95 +0x59
k8s.io/kubernetes/pkg/util/wait.pollImmediateInternal(0xc820888720, 0xc820888700, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:175 +0x2d
k8s.io/kubernetes/pkg/util/wait.PollImmediate(0x3b9aca00, 0x2540be400, 0xc820888700, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:171 +0x4f
k8s.io/kubernetes/pkg/registry/service/ipallocator/controller.(*Repair).runOnce(0xc820896720, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/service/ipallocator/controller/repair.go:97 +0x127
k8s.io/kubernetes/pkg/registry/service/ipallocator/controller.(*Repair).(k8s.io/kubernetes/pkg/registry/service/ipallocator/controller.runOnce)-fm(0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/service/ipallocator/controller/repair.go:78 +0x2e
k8s.io/kubernetes/pkg/client/unversioned.RetryOnConflict.func1(0x7f02d7f8a000, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/unversioned/util.go:64 +0x38
k8s.io/kubernetes/pkg/util/wait.ExponentialBackoff(0x989680, 0x4014000000000000, 0x3fb999999999999a, 0x4, 0xc8208886e0, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:146 +0x93
k8s.io/kubernetes/pkg/client/unversioned.RetryOnConflict(0x989680, 0x4014000000000000, 0x3fb999999999999a, 0x4, 0xc8203df220, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/unversioned/util.go:63 +0xd5
k8s.io/kubernetes/pkg/registry/service/ipallocator/controller.(*Repair).RunOnce(0xc820896720, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/service/ipallocator/controller/repair.go:78 +0x96
k8s.io/kubernetes/pkg/master.(*Controller).Start(0xc820451560)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/master/controller.go:86 +0x2a0
k8s.io/kubernetes/pkg/master.New(0xc820206e00, 0x0, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/master/master.go:227 +0xb4a
k8s.io/kubernetes/cmd/kube-apiserver/app.Run(0xc8204505a0, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:307 +0x4c67
main.main()
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/apiserver.go:50 +0x111

```

Because we invoke ip repair with a nil service registry (https://github.com/kubernetes/kubernetes/blob/master/pkg/master/controller.go#L82), which we don't initialize because it isn't enabled (https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master.go#L239). 

Applying p0 for triage because I don't know where else we might be making such assumptions, and I'm not familiar enough with the space to say this isn't 1.4.0

@jlowdermilk @kubernetes/sig-api-machinery

**Comment by lavalamp** [comment]
Running an apiserver with everything turned off doesn't seem that useful?

**Comment by lavalamp** [comment]
(not that we shouldn't fix this)

**Comment by bprashanth** [comment]
yeah, my point was I'm not sure if turning off something else more segmented causes an issue like this based on a fault assumption that an object was created elsewhere. 

I also tried this on a HEAD cluster, so unsure if it is in 1.4

**Comment by smarterclayton** [comment]
Service repair is definitely special (also not implying we shouldn't fix
this).

**Comment by bprashanth** [comment]
So I guess this doesn't block the release (since the release is going out today)? if so, please update the known issues doc with impact/mitigation. Assigning to Daniel for lack of an assignee.

**Comment by lavalamp** [comment]
This doesn't block the release and it's not clear to me that we even need a cherrypick.

**Comment by lavalamp** [comment]
@mbohlool I think this isn't urgent. It's probably not hard though, so might be good exposure to more of our codebase for you. :)

**Comment by mbohlool** [comment]
How can I reproduce this?

I've tried

```
export RUNTIME_CONFIG="api/all=false"
export LOG_LEVEL=7
hack/local-up-cluster.sh
```

but the log does not show a panic:

```
I1027 02:39:17.152000   96560 master.go:293] Skipping disabled API group "apps".
I1027 02:39:17.152014   96560 master.go:293] Skipping disabled API group "authentication.k8s.io".
I1027 02:39:17.152032   96560 master.go:293] Skipping disabled API group "authorization.k8s.io".
I1027 02:39:17.152038   96560 master.go:293] Skipping disabled API group "autoscaling".
I1027 02:39:17.152044   96560 master.go:293] Skipping disabled API group "batch".
I1027 02:39:17.152049   96560 master.go:293] Skipping disabled API group "certificates.k8s.io".
I1027 02:39:17.152055   96560 master.go:293] Skipping disabled API group "extensions".
I1027 02:39:17.152060   96560 master.go:293] Skipping disabled API group "policy".
I1027 02:39:17.152066   96560 master.go:293] Skipping disabled API group "rbac.authorization.k8s.io".
I1027 02:39:17.152072   96560 master.go:293] Skipping disabled API group "storage.k8s.io".
I1027 02:39:17.152532   96560 reflector.go:211] Starting reflector *api.Namespace (10m0s) from pkg/controller/informers/factory.go:87
I1027 02:39:17.152564   96560 reflector.go:249] Listing and watching *api.Namespace from pkg/controller/informers/factory.go:87
```

**Comment by mbohlool** [comment]
@bprashanth can you confirm if you still have this problem or it has been fixed?

**Comment by mbohlool** [comment]
I've checked out a commit around the time this issue is reported and confirm that it was happening at the time. It does not happen on head right now and I assume it has been fixed.
