### ISSUE TITLE
Crash in namespace controller when quickly adding/deleting namespaces

### ISSUE THREAD

**Issue by dcbw** [kubernetes/kubernetes#33676]
See https://bugzilla.redhat.com/show_bug.cgi?id=1379316 for full dumps.

```
Sep 26 18:44:41 master.bmeng.local openshift-master[18579]: I0926 18:44:41.059113   18579 namespace_controller.go:184] Namespace has been deleted bmengpp38
Sep 26 18:44:41 master.bmeng.local openshift-master[18579]: I0926 18:44:41.059118   18579 namespace_controller.go:184] Namespace has been deleted bmengpp31
Sep 26 18:44:41 master.bmeng.local openshift-master[18579]: I0926 18:44:41.059123   18579 namespace_controller.go:184] Namespace has been deleted bmengpp40
Sep 26 18:44:41 master.bmeng.local openshift-master[18579]: I0926 18:44:41.059128   18579 namespace_controller.go:184] Namespace has been deleted bmengpp35
Sep 26 18:44:41 master.bmeng.local openshift-master[18579]: I0926 18:44:41.059133   18579 namespace_controller.go:184] Namespace has been deleted bmengpp63
Sep 26 18:44:41 master.bmeng.local openshift-master[18579]: I0926 18:44:41.085140   18579 vnids_master.go:139] Released netid 11514995 for namespace "bmengpp64"
Sep 26 18:44:43 master.bmeng.local openshift-master[18579]: I0926 18:44:43.243116   18579 vnids_master.go:139] Released netid 15409101 for namespace "bmengp1"
Sep 26 18:44:54 master.bmeng.local openshift-master[18579]: I0926 18:44:54.883020   18579 logs.go:41] http: TLS handshake error from 127.0.0.1:49060: remote error: bad certificate
Sep 26 18:45:00 master.bmeng.local openshift-master[18579]: I0926 18:45:00.614629   18579 vnids_master.go:117] Allocated netid 6680021 for namespace "bmengppp"
Sep 26 18:45:05 master.bmeng.local openshift-master[18579]: I0926 18:45:05.546936   18579 vnids_master.go:139] Released netid 6680021 for namespace "bmengppp"
Sep 26 18:45:05 master.bmeng.local openshift-master[18579]: I0926 18:45:05.777454   18579 vnids_master.go:117] Allocated netid 3610012 for namespace "bmengppp"
Sep 26 18:45:09 master.bmeng.local openshift-master[18579]: I0926 18:45:09.202822   18579 vnids_master.go:139] Released netid 3610012 for namespace "bmengppp"
Sep 26 18:45:09 master.bmeng.local openshift-master[18579]: I0926 18:45:09.636770   18579 vnids_master.go:117] Allocated netid 6600708 for namespace "bmengppp"
Sep 26 18:45:11 master.bmeng.local openshift[18579]: start to snapshot (applied: 40012, lastsnap: 30010)
Sep 26 18:45:12 master.bmeng.local openshift[18579]: saved snapshot at index 40012
Sep 26 18:45:12 master.bmeng.local openshift[18579]: compacted raft log at 35012
Sep 26 18:45:13 master.bmeng.local openshift-master[18579]: I0926 18:45:13.223222   18579 namespace_controller.go:184] Namespace has been deleted bmengppp
Sep 26 18:45:13 master.bmeng.local openshift-master[18579]: I0926 18:45:13.245674   18579 vnids_master.go:139] Released netid 6600708 for namespace "bmengppp"
Sep 26 18:45:13 master.bmeng.local openshift-master[18579]: I0926 18:45:13.522417   18579 vnids_master.go:117] Allocated netid 1099046 for namespace "bmengppp"
Sep 26 18:45:17 master.bmeng.local openshift-master[18579]: I0926 18:45:17.139190   18579 vnids_master.go:139] Released netid 1099046 for namespace "bmengppp"
Sep 26 18:45:17 master.bmeng.local openshift-master[18579]: I0926 18:45:17.513861   18579 vnids_master.go:117] Allocated netid 1963187 for namespace "bmengppp"
Sep 26 18:45:21 master.bmeng.local openshift-master[18579]: I0926 18:45:21.016709   18579 vnids_master.go:139] Released netid 1963187 for namespace "bmengppp"
Sep 26 18:45:21 master.bmeng.local openshift-master[18579]: I0926 18:45:21.539964   18579 vnids_master.go:117] Allocated netid 14855766 for namespace "bmengppp"
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: I0926 18:45:24.575684   18579 vnids_master.go:139] Released netid 14855766 for namespace "bmengppp"
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: I0926 18:45:24.575883   18579 vnids_master.go:117] Allocated netid 7946673 for namespace "bmengppp"
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: E0926 18:45:24.594505   18579 runtime.go:64] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:70
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:63
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:49
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /usr/local/go/src/runtime/asm_amd64.s:472
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /usr/local/go/src/runtime/panic.go:443
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /usr/local/go/src/runtime/panic.go:62
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /usr/local/go/src/runtime/sigpanic_unix.go:24
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/namespace/namespace_controller_utils.go:383
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/namespace/namespace_controller.go:193
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/namespace/namespace_controller.go:149
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/namespace/namespace_controller.go:169
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/namespace/namespace_controller.go:201
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:88
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:89
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:49
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /usr/local/go/src/runtime/asm_amd64.s:1998
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: [signal 0xb code=0x1 addr=0x0 pc=0x1f8bb70]
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: goroutine 8305 [running]:
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: panic(0x53b0400, 0xc82000e070)
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /usr/local/go/src/runtime/panic.go:481 +0x3e6 fp=0xc82340f910 sp=0xc82340f890
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:56 +0x153 fp=0xc82340f970 sp=0xc82340f910
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: runtime.call32(0x0, 0x6ebed68, 0xc8297d4b70, 0x1800000018)
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /usr/local/go/src/runtime/asm_amd64.s:472 +0x3e fp=0xc82340f998 sp=0xc82340f970
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: panic(0x53b0400, 0xc82000e070)
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /usr/local/go/src/runtime/panic.go:443 +0x4e9 fp=0xc82340fa18 sp=0xc82340f998
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: runtime.panicmem()
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /usr/local/go/src/runtime/panic.go:62 +0x65 fp=0xc82340fa40 sp=0xc82340fa18
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: runtime.sigpanic()
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /usr/local/go/src/runtime/sigpanic_unix.go:24 +0x2ba fp=0xc82340fa90 sp=0xc82340fa40
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/namespace.syncNamespace(0x7f1731198238, 0xc828908e60, 0x7f172c21fdb8, 0xc8256bf0b0, 0xc82df31950, 0xc82d9ef800, 0x19, 0x20, 0xc825512500, 0x5eab050, ...)
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/namespace/namespace_controller_utils.go:383 +0x580 fp=0xc82340fbb8 sp=0xc82340fa90
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/namespace.(*NamespaceController).syncNamespaceFromKey(0xc82de5e380, 0xc83426ee60, 0x8, 0x0, 0x0)
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/namespace/namespace_controller.go:193 +0x725 fp=0xc82340fd30 sp=0xc82340fbb8
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/namespace.(*NamespaceController).worker.func1(0x455b00)
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/namespace/namespace_controller.go:149 +0x160 fp=0xc82340fe10 sp=0xc82340fd30
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/namespace.(*NamespaceController).worker(0xc82de5e380)
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/namespace/namespace_controller.go:169 +0x46 fp=0xc82340fe38 sp=0xc82340fe10
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/namespace.(*NamespaceController).(github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/namespace.worker)-fm()
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/namespace/namespace_controller.go:201 +0x20 fp=0xc82340fe48 sp=0xc82340fe38
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc826a877b0)
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:88 +0x4b fp=0xc82340fe78 sp=0xc82340fe48
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc826a877b0, 0x3b9aca00, 0x0, 0x6ebfa01, 0xc82000c1e0)
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:89 +0xb4 fp=0xc82340ff48 sp=0xc82340fe78
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc826a877b0, 0x3b9aca00, 0xc82000c1e0)
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:49 +0x43 fp=0xc82340ff78 sp=0xc82340ff48
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: runtime.goexit()
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82340ff80 sp=0xc82340ff78
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: created by github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/namespace.(*NamespaceController).Run
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/controller/namespace/namespace_controller.go:201 +0xf8
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: goroutine 1 [select (no cases), 119 minutes]:
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: runtime.gopark(0x0, 0x0, 0x6293e40, 0x11, 0xc82c715910, 0x1)
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /usr/local/go/src/runtime/proc.go:262 +0x163 fp=0xc82e0e9998 sp=0xc82e0e9970
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: runtime.block()
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /usr/local/go/src/runtime/select.go:208 +0x4c fp=0xc82e0e99d0 sp=0xc82e0e9998
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: github.com/openshift/origin/pkg/cmd/server/start.MasterOptions.StartMaster(0xc8200ce000, 0x1, 0x7ffc9cf66ec5, 0x3a, 0x7f173118b1c0, 0xc820022010, 0x0, 0x0, 0x0, 0x0, ...)
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_master.go:194 +0x110 fp=0xc82e0e9aa0 sp=0xc82e0e99d0
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: github.com/openshift/origin/pkg/cmd/server/start.NewCommandStartMaster.func1(0xc82039c240, 0xc8208c6640, 0x0, 0x2)
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/start/start_master.go:96 +0x188 fp=0xc82e0e9c98 sp=0xc82e0e9aa0
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc82039c240, 0xc8208c6460, 0x2, 0x2, 0x0, 0x0)
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x896 fp=0xc82e0e9db0 sp=0xc82e0e9c98
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc82071d200, 0xc82039c240, 0x0, 0x0)
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x55c fp=0xc82e0e9ec0 sp=0xc82e0e9db0
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc82071d200, 0x0, 0x0)
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2d fp=0xc82e0e9ee8 sp=0xc82e0e9ec0
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: main.main()
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /root/src/github.com/origin/_output/local/go/src/github.com/openshift/origin/cmd/openshift/openshift.go:33 +0x1a6 fp=0xc82e0e9f50 sp=0xc82e0e9ee8
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: runtime.main()
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc82e0e9fa0 sp=0xc82e0e9f50
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: runtime.goexit()
Sep 26 18:45:24 master.bmeng.local openshift-master[18579]: /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82e0e9fa8 sp=0xc82e0e9fa0
<etc>
```

The line number of namespace_controller_utils.go:383 corresponds to:

```
	// if the namespace is already finalized, delete it
	if finalized(namespace) {
		err = kubeClient.Core().Namespaces().Delete(namespace.Name, nil)
		if err != nil && !errors.IsNotFound(err) {
			return err
		}
		return nil
	}

	// there may still be content for us to remove
--->	estimate, err := deleteAllContent(kubeClient, clientPool, opCache, groupVersionResources, namespace.Name, *namespace.DeletionTimestamp)
	if err != nil {
		return err
	}
	if estimate > 0 {
		return &contentRemainingError{estimate}
	}
```

**Comment by dcbw** [comment]
From a quick look, perhaps the namespace object returned from retryOnConflictError() just above no longer has a DeletionTimestamp and thus "*namespace.DeletionTimestamp" triggers the panic?

**Comment by derekwaynecarr** [comment]
Thanks for the report, I will investigate.
