### ISSUE TITLE
panics on kubectl exec

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#33823]
I've seen a few different panics using `kubectl exec` and other commands, here is one that seems quite reproducible.

```
> kubectl exec --namespace=test-5 --stdin --tty master-00 kubeadm init
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x5b743f80 pc=0x686e5]

runtime stack:
runtime/internal/atomic.Load64(0x5b743f80, 0x5b743f837cb8)
	/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:26 +0x5

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc8205016a8 sp=0xc8205016a0
runtime.gcAssistAlloc(0xc820000180)
	/usr/local/go/src/runtime/mgcmark.go:425 +0x180 fp=0xc820501728 sp=0xc8205016a8
runtime.mallocgc(0x26, 0x0, 0x3, 0x11caae0)
	/usr/local/go/src/runtime/malloc.go:537 +0x184 fp=0xc820501800 sp=0xc820501728
runtime.rawstring(0x26, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/string.go:284 +0x70 fp=0xc820501848 sp=0xc820501800
runtime.rawstringtmp(0x0, 0x26, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/string.go:111 +0xb7 fp=0xc820501880 sp=0xc820501848
runtime.slicebytetostring(0x0, 0xc82011fb12, 0x26, 0x2b9, 0x0, 0x0)
	/usr/local/go/src/runtime/string.go:93 +0x6f fp=0xc820501918 sp=0xc820501880
encoding/json.(*decodeState).literalStore(0xc820524000, 0xc82011fb11, 0x28, 0x2ba, 0x1210200, 0xc82032ab70, 0x198, 0xc820501e00)
	/usr/local/go/src/encoding/json/decode.go:833 +0x14e8 fp=0xc820501df0 sp=0xc820501918
encoding/json.(*decodeState).literal(0xc820524000, 0x1210200, 0xc82032ab70, 0x198)
	/usr/local/go/src/encoding/json/decode.go:717 +0xe9 fp=0xc820501e58 sp=0xc820501df0
encoding/json.(*decodeState).value(0xc820524000, 0x1210200, 0xc82032ab70, 0x198)
	/usr/local/go/src/encoding/json/decode.go:370 +0x37b fp=0xc820501f30 sp=0xc820501e58
encoding/json.(*decodeState).object(0xc820524000, 0x169d2c0, 0xc82032ab60, 0x199)
	/usr/local/go/src/encoding/json/decode.go:684 +0x116a fp=0xc8205022d8 sp=0xc820501f30
encoding/json.(*decodeState).value(0xc820524000, 0x11d0900, 0xc82032ab60, 0x16)
	/usr/local/go/src/encoding/json/decode.go:367 +0x3a1 fp=0xc8205023b0 sp=0xc8205022d8
encoding/json.(*decodeState).unmarshal(0xc820524000, 0x11d0900, 0xc82032ab60, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:168 +0x196 fp=0xc820502488 sp=0xc8205023b0
encoding/json.Unmarshal(0xc82011fb00, 0xcb, 0x2cb, 0x11d0900, 0xc82032ab60, 0x0, 0x0)
	/usr/local/go/src/encoding/json/decode.go:96 +0x12b fp=0xc8205024f8 sp=0xc820502488
k8s.io/kubernetes/vendor/golang.org/x/oauth2/google.tokenSourceFromFile(0x28c7360, 0xc820014890, 0xc8200b4140, 0x3f, 0xc820502948, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/oauth2/google/default.go:128 +0x13e fp=0xc820502710 sp=0xc8205024f8
k8s.io/kubernetes/vendor/golang.org/x/oauth2/google.DefaultTokenSource(0x28c7360, 0xc820014890, 0xc820502948, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/oauth2/google/default.go:74 +0x3b1 fp=0xc8205028b8 sp=0xc820502710
k8s.io/kubernetes/plugin/pkg/client/auth/gcp.newCachedTokenSource(0xc8203bec30, 0x48, 0xc820321050, 0x22, 0x28c8a60, 0xc8202b0ce0, 0xc820502b18, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/client/auth/gcp/gcp.go:71 +0x178 fp=0xc8205029b8 sp=0xc8205028b8
k8s.io/kubernetes/plugin/pkg/client/auth/gcp.newGCPAuthProvider(0xc8200868e0, 0x16, 0xc820321380, 0x28c8a60, 0xc8202b0ce0, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/client/auth/gcp/gcp.go:43 +0x158 fp=0xc820502a78 sp=0xc8205029b8
k8s.io/kubernetes/pkg/client/restclient.GetAuthProvider(0xc8200868e0, 0x16, 0xc8200871e0, 0x28c8a60, 0xc8202b0ce0, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/restclient/plugin.go:72 +0x25f fp=0xc820502b20 sp=0xc820502a78
k8s.io/kubernetes/pkg/client/restclient.(*Config).transportConfig(0xc820522340, 0xc8200868e0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/restclient/transport.go:63 +0x92 fp=0xc820502bb8 sp=0xc820502b20
k8s.io/kubernetes/pkg/client/restclient.TransportFor(0xc820522340, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/restclient/transport.go:40 +0x3d fp=0xc820502bf8 sp=0xc820502bb8
k8s.io/kubernetes/pkg/client/restclient.RESTClientFor(0xc820522340, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/restclient/config.go:167 +0x183 fp=0xc820502cd8 sp=0xc820502bf8
k8s.io/kubernetes/pkg/client/unversioned.NewRbac(0xc820502e48, 0xc8203ea0c0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/unversioned/rbac.go:60 +0xb4 fp=0xc820502d38 sp=0xc820502cd8
k8s.io/kubernetes/pkg/client/unversioned.New(0xc8202d4340, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/unversioned/helper.go:111 +0x702 fp=0xc820503908 sp=0xc820502d38
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*ClientCache).ClientForVersion(0xc82000f680, 0x0, 0xc82043bd40, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/clientcache.go:111 +0x118 fp=0xc820503af8 sp=0xc820503908
k8s.io/kubernetes/pkg/kubectl/cmd/util.NewFactory.func2(0xc82043bd40, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/factory.go:336 +0x35 fp=0xc820503b28 sp=0xc820503af8
k8s.io/kubernetes/pkg/kubectl/cmd.(*ExecOptions).Complete(0xc82042a460, 0xc82017e500, 0xc8202b5800, 0xc820085860, 0x3, 0x6, 0xffffffffffffffff, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/exec.go:144 +0x227 fp=0xc820503ba8 sp=0xc820503b28
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdExec.func1(0xc8202b5800, 0xc820085860, 0x3, 0x6)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/exec.go:65 +0x87 fp=0xc820503c18 sp=0xc820503ba8
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc8202b5800, 0xc8200857a0, 0x6, 0x6, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:565 +0x85a fp=0xc820503d30 sp=0xc820503c18
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc8200a0400, 0xc8202b5800, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:651 +0x55c fp=0xc820503e40 sp=0xc820503d30
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc8200a0400, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:610 +0x2d fp=0xc820503e68 sp=0xc820503e40
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:32 +0xf0 fp=0xc820503ee8 sp=0xc820503e68
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:28 +0x28 fp=0xc820503f10 sp=0xc820503ee8
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc820503f60 sp=0xc820503f10
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820503f68 sp=0xc820503f60

goroutine 5 [chan receive]:
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x23421e0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:879 +0x67
created by k8s.io/kubernetes/vendor/github.com/golang/glog.init.1
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:410 +0x297

goroutine 27 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 30 [IO wait]:
net.runtime_pollWait(0x28c9f40, 0x72, 0xc820498c00)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82033c680, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82033c680, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82033c620, 0xc820498c00, 0x400, 0x400, 0x0, 0x26e2050, 0xc8200141d0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82017a2f8, 0xc820498c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc82029b110, 0x28ca050, 0xc82017a2f8, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc82014cc00, 0x1bd8817, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc82014cc00, 0xc820304000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0x28ca660, 0xc82014cc00, 0xc8201e7318, 0xc820304000, 0x1000, 0x1000, 0x4cd3, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1687 +0x67
net/http.(*noteEOFReader).Read(0xc8202a92c0, 0xc820304000, 0x1000, 0x1000, 0xc82016bd0d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc820302360)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820302360, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8201e72b0)
	/usr/local/go/src/net/http/transport.go:1073 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:857 +0x10a6

goroutine 31 [select]:
net/http.(*persistConn).writeLoop(0xc8201e72b0)
	/usr/local/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:858 +0x10cb
[signal 0xb code=0x1 addr=0x5b743f80 pc=0x686e5]

goroutine 23 [running]:
runtime.throw(0x1a4b1e0, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc82002c628 sp=0xc82002c610
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc82002c678 sp=0xc82002c628
runtime/internal/atomic.Load64(0x5b743f80, 0x5b743f837cb8)
	/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:26 +0x5 fp=0xc82002c680 sp=0xc82002c678
runtime.lfstackpop(0x2342500, 0x0)
	/usr/local/go/src/runtime/lfstack.go:38 +0x6d fp=0xc82002c6b8 sp=0xc82002c680
runtime.trygetfull(0xa7, 0xc81fffb9c4)
	/usr/local/go/src/runtime/mgcwork.go:382 +0x23 fp=0xc82002c6d8 sp=0xc82002c6b8
runtime.(*gcWork).tryGet(0xc820024720, 0xc820024720)
	/usr/local/go/src/runtime/mgcwork.go:150 +0x7c fp=0xc82002c708 sp=0xc82002c6d8
runtime.gcDrain(0xc820024720, 0x5)
	/usr/local/go/src/runtime/mgcmark.go:833 +0x22a fp=0xc82002c740 sp=0xc82002c708
runtime.gcBgMarkWorker(0xc820023500)
	/usr/local/go/src/runtime/mgc.go:1435 +0x583 fp=0xc82002c7b8 sp=0xc82002c740
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82002c7c0 sp=0xc82002c7b8
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1330 +0x92
[signal 0xb code=0x1 addr=0x5b743f80 pc=0x686e5]

goroutine 19 [running]:
runtime.throw(0x1a4b1e0, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc820030628 sp=0xc820030610
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc820030678 sp=0xc820030628
runtime/internal/atomic.Load64(0x5b743f80, 0x5b743f837cb8)
	/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:26 +0x5 fp=0xc820030680 sp=0xc820030678
runtime.lfstackpop(0x2342500, 0xc81ffe31c0)
	/usr/local/go/src/runtime/lfstack.go:38 +0x6d fp=0xc8200306b8 sp=0xc820030680
runtime.trygetfull(0xa7, 0xc81ffe31b8)
	/usr/local/go/src/runtime/mgcwork.go:382 +0x23 fp=0xc8200306d8 sp=0xc8200306b8
runtime.(*gcWork).tryGet(0xc82001f220, 0xc82001f220)
	/usr/local/go/src/runtime/mgcwork.go:150 +0x7c fp=0xc820030708 sp=0xc8200306d8
runtime.gcDrain(0xc82001f220, 0x6)
	/usr/local/go/src/runtime/mgcmark.go:833 +0x22a fp=0xc820030740 sp=0xc820030708
runtime.gcBgMarkWorker(0xc82001e000)
	/usr/local/go/src/runtime/mgc.go:1433 +0x25f fp=0xc8200307b8 sp=0xc820030740
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200307c0 sp=0xc8200307b8
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1330 +0x92

> kubectl exec --namespace=test-5 --stdin --tty master-00 kubeadm init
<master/tokens> generated token: "d9e800.955fc7f8f87970e6"
<master/pki> created keys and certificates in "/etc/kubernetes/pki"
<util/kubeconfig> created "/etc/kubernetes/kubelet.conf"
<util/kubeconfig> created "/etc/kubernetes/admin.conf"
<master/apiclient> created API client configuration
<master/apiclient> created API client, waiting for the control plane to become ready
<master/apiclient> all control plane components are healthy after 45.291538 seconds
<master/apiclient> waiting for at least one node to register and become ready
<master/apiclient> first node is ready after 6.002781 seconds
<master/discovery> created essential addon: kube-discovery, waiting for it to become ready
<master/discovery> kube-discovery is ready after 21.003347 seconds
<master/addons> created essential addon: kube-proxy
<master/addons> created essential addon: kube-dns

Kubernetes master initialised successfully!

You can now join any number of machines by running the following on each node:

kubeadm join --token d9e800.955fc7f8f87970e6 10.0.0.13
```

I'm using GKE and `kubectl` is part of the official CLI package:
```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.6", GitCommit:"ae4550cc9c89a593bcda6678df201db1b208133b", GitTreeState:"clean", BuildDate:"2016-08-26T18:13:23Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.7", GitCommit:"a2cba278cba1f6881bb0a7704d9cac6fca6ed435", GitTreeState:"clean", BuildDate:"2016-09-12T23:08:43Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

I've upgraded to macOS Sierra yesterday, could it be to do with that?

You might see me using `kubeadm`, but that's nothing to do with it. If you are curious what I'm doing, [take a look here](https://gist.github.com/errordeveloper/589431595b9aa5c70533045fb575ef2a).

**Comment by errordeveloper** [comment]
I am fairly certain the issue is to do with Sierra. I've ran `gcloud components update`, will see if this comes up with latests version (v1.3.7).

**Comment by errordeveloper** [comment]
I keep seeing panics with v1.3.7, e.g.:
```
> kubectl exec --namespace=test-6 --stdin --tty node-01 systemctl -- start kubelet docker
panic: sync: inconsistent mutex state

goroutine 55 [running]:
panic(0x1210200, 0xc8202fb770)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
sync.(*Mutex).Lock(0xc82000e1a0)
	/usr/local/go/src/sync/mutex.go:75 +0x16d
math/rand.(*lockedSource).Int63(0xc82000e1a0, 0x0)
	/usr/local/go/src/math/rand/rand.go:258 +0x28
math/rand.(*Rand).Int63(0xc820010510, 0x5db85)
	/usr/local/go/src/math/rand/rand.go:46 +0x39
math/rand.(*Rand).Int(0xc820010510, 0x0)
	/usr/local/go/src/math/rand/rand.go:56 +0x21
math/rand.Int(0xc82008a0e8)
	/usr/local/go/src/math/rand/rand.go:198 +0x23
net.exchange(0xc8202fb730, 0xd, 0xc8201afda0, 0x14, 0xc8202f0001, 0x12a05f200, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dnsclient_unix.go:151 +0x405
net.tryOneName(0xc82034fb00, 0xc8201afda0, 0x14, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dnsclient_unix.go:181 +0x2f3
net.goLookupIPOrder.func1(0xc82034fb00, 0xc82033fb80, 0xc820013ec0, 0x1)
	/usr/local/go/src/net/dnsclient_unix.go:462 +0x59
created by net.goLookupIPOrder
	/usr/local/go/src/net/dnsclient_unix.go:464 +0x3d0
```
And all is good on the second attempt:
```
>  kubectl exec --namespace=test-6 --stdin --tty node-01 systemctl -- start kubelet docker
```

**Comment by dims** [comment]
work is being done here - #28742

**Comment by errordeveloper** [comment]
@dims thanks, I'll close this.
