### ISSUE TITLE
hyperkube-arm crashes on Hypriot 1.0.0

### ISSUE THREAD

**Issue by rhuss** [kubernetes/kubernetes#34702]
**Kubernetes version** 1.4.1

**Environment**:
- **Cloud provider or hardware configuration**: Raspberry Pi v3
- **OS** (e.g. from /etc/os-release): Hypriot OS 1.0.0, based on Raspbian 8
- **Kernel** (e.g. `uname -a`): Linux 4.4.24-hypriotos-v7+ #1 SMP PREEMPT Tue Oct 11 17:15:58 UTC 2016 armv7l GNU/Linux
- **Install tools**:
- **Others**:

**What happened**: When running a `docker run -it gcr.io/google_containers/hyperkube-arm:v1.4.1 /hyperkube` a SIGSEV occurs. Also with any other compile in this image (e.g. `kubectl`):

<details>
  <summary>

Stack-Trace</summary>

```
root@n0:/home/pi# docker run -it gcr.io/google_containers/hyperkube-arm:v1.4.1 /hyperkube
unexpected fault address 0xdd083390
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xdd083390 pc=0x7d108]

goroutine 1 [running, locked to thread]:
runtime.throw(0x33f0423, 0x5)
    /usr/local/go_k8s_patched/src/runtime/panic.go:566 +0x78 fp=0x14e47950 sp=0x14e47944
runtime.sigpanic()
    /usr/local/go_k8s_patched/src/runtime/sigpanic_unix.go:27 +0x280 fp=0x14e4797c sp=0x14e47950
runtime.memmove(0x14ece000, 0xdd083393, 0x1ff64)
    /usr/local/go_k8s_patched/src/runtime/memmove_arm.s:236 +0x1d0 fp=0x14e47988 sp=0x14e47980
runtime.concatstrings(0x4, 0x14e47a54, 0x3, 0x3, 0x0, 0x0)
    /usr/local/go_k8s_patched/src/runtime/string.go:52 +0x2f8 fp=0x14e47a24 sp=0x14e47988
runtime.concatstring3(0x4, 0xdd083393, 0x1ff64, 0x14e9eaf8, 0x44, 0x14e9eb34, 0x0, 0x0, 0x0)
    /usr/local/go_k8s_patched/src/runtime/string.go:63 +0x58 fp=0x14e47a4c sp=0x14e47a24
encoding/gob.newTypeObject(0x2d04a90, 0x8, 0x14eb13c0, 0x49a5808, 0x327cd18, 0x327cd18, 0x49a5808, 0x327cd18, 0x253cc84)
    /usr/local/go_k8s_patched/src/encoding/gob/type.go:448 +0x24 fp=0x14e47be0 sp=0x14e47a4c
encoding/gob.getType(0x2d04a90, 0x8, 0x14eb13c0, 0x49a5808, 0x327cd18, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go_k8s_patched/src/encoding/gob/type.go:608 +0xc0 fp=0x14e47c28 sp=0x14e47be0
encoding/gob.getBaseType(0x2d04a90, 0x8, 0x49a5808, 0x327cd18, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go_k8s_patched/src/encoding/gob/type.go:595 +0x78 fp=0x14e47c50 sp=0x14e47c28
encoding/gob.buildTypeInfo(0x14eb13c0, 0x49a5808, 0x327cd18, 0x0, 0x0, 0x0)
    /usr/local/go_k8s_patched/src/encoding/gob/type.go:725 +0xf0 fp=0x14e47d28 sp=0x14e47c50
encoding/gob.getTypeInfo(0x14eb13c0, 0x327cd18, 0x0, 0x0)
    /usr/local/go_k8s_patched/src/encoding/gob/type.go:712 +0xa4 fp=0x14e47d4c sp=0x14e47d28
encoding/gob.mustGetTypeInfo(0x49a5808, 0x327cd18, 0x49a5808)
    /usr/local/go_k8s_patched/src/encoding/gob/type.go:776 +0x34 fp=0x14e47d84 sp=0x14e47d4c
encoding/gob.init()
    /usr/local/go_k8s_patched/src/encoding/gob/type.go:269 +0x1be0 fp=0x14e47de8 sp=0x14e47d84
net/rpc.init()
    /usr/local/go_k8s_patched/src/net/rpc/server.go:713 +0x5c fp=0x14e47e1c sp=0x14e47de8
k8s.io/kubernetes/vendor/github.com/ugorji/go/codec.init()
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/ugorji/go/codec/time.go:223 +0xe4 fp=0x14e47eb8 sp=0x14e47e1c
k8s.io/kubernetes/pkg/runtime/serializer/json.init()
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/runtime/serializer/json/meta.go:62 +0x6c fp=0x14e47ebc sp=0x14e47eb8
k8s.io/kubernetes/pkg/runtime/serializer.init()
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/runtime/serializer/protobuf_extension.go:53 +0x64 fp=0x14e47ec0 sp=0x14e47ebc
k8s.io/kubernetes/pkg/api.init()
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/zz_generated.deepcopy.go:3750 +0x11c fp=0x14e47f84 sp=0x14e47ec0
k8s.io/kubernetes/pkg/api/install.init()
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/install/install.go:160 +0x64 fp=0x14e47f94 sp=0x14e47f84
k8s.io/kubernetes/federation/cmd/federation-apiserver/app.init()
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/federation/cmd/federation-apiserver/app/server.go:224 +0x5c fp=0x14e47f98 sp=0x14e47f94
main.init()
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/hyperkube/server.go:78 +0x54 fp=0x14e47f9c sp=0x14e47f98
runtime.main()
    /usr/local/go_k8s_patched/src/runtime/proc.go:172 +0x228 fp=0x14e47fc4 sp=0x14e47f9c
runtime.goexit()
    /usr/local/go_k8s_patched/src/runtime/asm_arm.s:998 +0x4 fp=0x14e47fc4 sp=0x14e47fc4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go_k8s_patched/src/runtime/asm_arm.s:998 +0x4

goroutine 19 [chan receive]:
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x4b651e8)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:879 +0x68
created by k8s.io/kubernetes/vendor/github.com/golang/glog.init.1
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:410 +0x20c
```

</details>

**What you expected to happen**: That it start

**How to reproduce it** (as minimally and precisely as possible): Call

```
docker run -it gcr.io/google_containers/hyperkube-arm:v1.4.1 /hyperkube
```

on the latest [Hypriot OS 1.0.0](http://blog.hypriot.com/downloads/) on a Raspberry Pi

**Anything else do we need to know**: Using `hyperkube-arm:v1.3.2` works flawless.

**Comment by malaskim** [comment]
Hi everyone, 

I have exactly the same issue with Raspbian Jessie on a Raspberry Pi 3. (same stacktrace)
hyperkube-arm:v1.3.2 and hyperkube-arm:v1.3.6 also work flawless.

Malaskim

**Comment by taylorsmcclure** [comment]
+1 Same issue and stack trace it appears

Tested on hyperkube 1.4.3, 1.4.4-beta.0, 1.5.0-alpha.1

```
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
HYPRIOT_OS="HypriotOS/armhf"
HYPRIOT_OS_VERSION="v1.0.0"
HYPRIOT_DEVICE="Raspberry Pi"
```

**Comment by rhuss** [comment]
Same for 1.4.4

**Comment by rhuss** [comment]
`SIGSEGV` happens also on the plain binary when downloaded from https://storage.googleapis.com/kubernetes-release/release/v1.4.4/bin/linux/arm/hyperkube

**Comment by rhuss** [comment]
For v1.5.0-beta.1 I get the following stacktrace when running hyperkube on arm:

```
HypriotOS/armv7: pi@n1 in /tmp
$ ./hyperkube
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x5 pc=0x1d6d8]

goroutine 1 [running]:
panic(0x2d33460, 0x1590c010)
	/usr/local/go_k8s_patched/src/runtime/panic.go:500 +0x33c
compress/flate.generateFixedLiteralEncoding(0x5684b08)
	/usr/local/go_k8s_patched/src/compress/flate/huffman_code.go:64 +0x88
compress/flate.init()
	/usr/local/go_k8s_patched/src/compress/flate/huffman_code.go:105 +0x64
compress/gzip.init()
	/usr/local/go_k8s_patched/src/compress/gzip/gzip.go:249 +0x50
k8s.io/kubernetes/vendor/github.com/go-openapi/spec.init()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/go-openapi/spec/xml_object.go:69 +0x5c
k8s.io/kubernetes/pkg/api/resource.init()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/resource/suffix.go:199 +0xa4
k8s.io/kubernetes/pkg/api.init()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/zz_generated.deepcopy.go:3805 +0x7c
k8s.io/kubernetes/pkg/api/install.init()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/install/install.go:154 +0x64
k8s.io/kubernetes/federation/cmd/federation-apiserver/app.init()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/federation/cmd/federation-apiserver/app/server.go:254 +0x5c
main.init()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/hyperkube/server.go:76 +0x54
```

**Comment by rhuss** [comment]
the kubelet works btw.

**Comment by MathiasRenner** [comment]
I just talked with @luxas about it. The underlying issues are limitations in the core of golang (e.g. https://github.com/golang/go/issues/17028 or https://github.com/kubernetes/kubernetes/pull/32517 ). They are fixed in golang now, but available not before K8s is built with golang version 1.8. ETA: Jan-Mar 2017.

**Comment by smarterclayton** [comment]
Kube is now built with 1.8.
