### ISSUE TITLE
nameless dead containers break ListPodSandbox

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#35924]
I have a bunch of dead containers on my docker1.9 local machine
```
$ docker ps -a
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                         PORTS               NAMES
616c50a881fe        radial/busyboxplus:curl                    "sleep 3600"             10 minutes ago      Up 10 minutes                                      k8s_busybox_busybox-uid_default_14f23694-9fa2-11e6-86c2-ac162d075328_0
5db6218487c5        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 10 minutes ago      Up 10 minutes                                      k8s_POD_busybox-uid_default_14f23694-9fa2-11e6-86c2-ac162d075328_0
7bd05528b3c2        busybox                                    "/bin/sh"                About an hour ago   Exited (0) About an hour ago                       angry_cori
11eae11b12fc        kube-build:build-3b42428009-4-v1.7.1-2     "chown -R 170621.5000"   2 hours ago         Exited (0) 2 hours ago                             kube-build-data-3b42428009-4-v1.7.1-2
1cefb7aab14d        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 5 days ago          Dead                                               
d1a9eba1e3bc        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 5 days ago          Dead                                               
9e4e7a32cb84        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 5 days ago          Dead                                               
2f6688c2b5bb        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 5 days ago          Dead                                               
16be008c5482        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 5 days ago          Dead                                               
94ca679bbda8        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 5 days ago          Dead                                               
8fbaa6909bd3        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 5 days ago          Dead                                               
07458c6d6315        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 5 days ago          Dead                                               
6984e527a8a2        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 5 days ago          Dead              
```

Gave me a stacktrace
```
efault_14f23694-9fa2-11e6-86c2-ac162d075328_0 616c50a881fe514212d5284edc68814ef21b768fc5724601af0c2134bf3de61f], namespace: "docker")
I1031 12:41:58.578021   28152 container.go:407] Start housekeeping for container "/docker/616c50a881fe514212d5284edc68814ef21b768fc5724601af0c2134bf3de61f"
panic: runtime error: index out of range

goroutine 1586 [running]:
panic(0x2f79740, 0xc4200121f0)
	/usr/lib/google-golang/src/runtime/panic.go:507 +0x1b3
k8s.io/kubernetes/pkg/kubelet/dockershim.toRuntimeAPISandbox(0xc4221801c0, 0xc4221801c0, 0x0, 0x0)
	/usr/local/google/home/beeps/goproj/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/dockershim/convert.go:144 +0x2de
k8s.io/kubernetes/pkg/kubelet/dockershim.(*dockerService).ListPodSandbox(0xc420280850, 0x0, 0xc42129fa70, 0x413fb7, 0x33093a0, 0x3462860, 0xc420f8bb00)
	/usr/local/google/home/beeps/goproj/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_sandbox.go:275 +0x37a
k8s.io/kubernetes/pkg/kubelet/dockershim/remote.(*dockerService).ListPodSandbox(0xc420fcb0c0, 0x7f138660e2b0, 0xc420bead50, 0xc420f8bb20, 0x0, 0xc42129fac8, 0x27016f8)
	/usr/local/google/home/beeps/goproj/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/dockershim/remote/docker_service.go:85 +0x50
k8s.io/kubernetes/pkg/kubelet/api/v1alpha1/runtime._RuntimeService_ListPodSandbox_Handler(0x3462860, 0xc420fcb0c0, 0x7f138660e2b0, 0xc420bead50, 0xc420976550, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/beeps/goproj/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/api/v1alpha1/runtime/api.pb.go:3043 +0x27d
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc420f017c0, 0x5c80620, 0xc42094ad80, 0xc421700780, 0xc420fb09c0, 0x5c410b8, 0xc420bead20, 0x0, 0x0)
	/usr/local/google/home/beeps/goproj/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:608 +0xc50
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).handleStream(0xc420f017c0, 0x5c80620, 0xc42094ad80, 0xc421700780, 0xc420bead20)
	/usr/local/google/home/beeps/goproj/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:766 +0x6b0
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420229db0, 0xc420f017c0, 0x5c80620, 0xc42094ad80, 0xc421700780)
	/usr/local/google/home/beeps/goproj/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:419 +0xab
created by k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/usr/local/google/home/beeps/goproj/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:420 +0xa3

```

presumably because of https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/convert.go#L144. 
@kubernetes/sig-node unsure if this is 1.9 bug, but seems like we should probably guard against it anyway. 

Fwiw I run into this more often than not with `hostNetwork: true`

**Comment by bprashanth** [comment]
Oh, even better, they get their names back after docker restart
```
$ docker ps -a
CONTAINER ID        IMAGE                                      COMMAND             CREATED             STATUS              PORTS               NAMES
1cefb7aab14d        gcr.io/google_containers/pause-amd64:3.0   "/pause"            5 days ago          Dead                                    
d1a9eba1e3bc        gcr.io/google_containers/pause-amd64:3.0   "/pause"            5 days ago          Dead                                    
9e4e7a32cb84        gcr.io/google_containers/pause-amd64:3.0   "/pause"            5 days ago          Dead                                    
2f6688c2b5bb        gcr.io/google_containers/pause-amd64:3.0   "/pause"            5 days ago          Dead                                    
16be008c5482        gcr.io/google_containers/pause-amd64:3.0   "/pause"            5 days ago          Dead                                    
94ca679bbda8        gcr.io/google_containers/pause-amd64:3.0   "/pause"            5 days ago          Dead                                    
8fbaa6909bd3        gcr.io/google_containers/pause-amd64:3.0   "/pause"            5 days ago          Dead                                    
..

$ docker rm 1cefb7aab14d
Error response from daemon: Driver aufs failed to remove root filesystem 1cefb7aab14d8450481af0defc57663e3af2bc62f8ddb74790599a2ea7b7da7c: rename /usr/local/google/docker/aufs/mnt/1cefb7aab14d8450481af0defc57663e3af2bc62f8ddb74790599a2ea7b7da7c /usr/local/google/docker/aufs/mnt/1cefb7aab14d8450481af0defc57663e3af2bc62f8ddb74790599a2ea7b7da7c-removing: device or resource busy
Error: failed to remove containers: [1cefb7aab14d]

$ sudo service docker restart
docker stop/waiting
docker start/running, process 13457

$ docker ps -a
CONTAINER ID        IMAGE                                      COMMAND             CREATED             STATUS              PORTS               NAMES
1cefb7aab14d        gcr.io/google_containers/pause-amd64:3.0   "/pause"            5 days ago          Dead                                    fervent_engelbart
d1a9eba1e3bc        gcr.io/google_containers/pause-amd64:3.0   "/pause"            5 days ago          Dead                                    trusting_jennings
9e4e7a32cb84        gcr.io/google_containers/pause-amd64:3.0   "/pause"            5 days ago          Dead                                    evil_joliot
2f6688c2b5bb        gcr.io/google_containers/pause-amd64:3.0   "/pause"            5 days ago          Dead                                    kickass_einstein
16be008c5482        gcr.io/google_containers/pause-amd64:3.0   "/pause"            5 days ago          Dead                                    compassionate_ptolemy
94ca679bbda8        gcr.io/google_containers/pause-amd64:3.0   "/pause"            5 days ago          Dead                                    distracted_liskov
8fbaa6909bd3        gcr.io/google_containers/pause-amd64:3.0   "/pause"            5 days ago          Dead                                    angry_goldberg
```

**Comment by Random-Liu** [comment]
> it's usually the result of a container failing to be stopped/removed, and therefore given a "dead" state, so that it can be cleaned up in a later stage. This is also the reason "dead" containers may have no name.

https://github.com/docker/docker/issues/18628#issuecomment-164391489

I'll send a PR to fix this.

**Comment by yujuhong** [comment]
> Oh, even better, they get their names back after docker restart

They just got random names docker assigned to them after the restart. The name itself is pretty useless.
