### ISSUE TITLE
Panic in the deployment controller

### ISSUE THREAD

**Issue by kargakis** [kubernetes/kubernetes#36488]
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x79724d]

goroutine 960 [running]:
panic(0x2222440, 0xc420010030)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
k8s.io/kubernetes/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:56 +0x126
panic(0x2222440, 0xc420010030)
	/usr/local/go/src/runtime/panic.go:458 +0x243
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).syncRolloutStatus(0xc420ce8700, 0xc421c5c600, 0x2, 0x2, 0x0, 0xc422c41180, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/progress.go:123 +0x84d
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).rolloutRecreate(0xc420ce8700, 0xc422c41180, 0x26802d3, 0x8)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/recreate.go:45 +0x19a
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).syncDeployment(0xc420ce8700, 0xc421ec1300, 0x20, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:389 +0x5e6
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).(k8s.io/kubernetes/pkg/controller/deployment.syncDeployment)-fm(0xc421ec1300, 0x20, 0xc421edecc0, 0xc4227f5de0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:117 +0x3e
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).worker.func1(0x453e00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:278 +0xfe
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).worker(0xc420ce8700)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:285 +0x48
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).(k8s.io/kubernetes/pkg/controller/deployment.worker)-fm()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:139 +0x2a
k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc42086a950)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:87 +0x5e
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc42086a950, 0x3b9aca00, 0x0, 0x1, 0xc420046ae0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:88 +0xad
k8s.io/kubernetes/pkg/util/wait.Until(0xc42086a950, 0x3b9aca00, 0xc420046ae0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:49 +0x4d
created by k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).Run
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:139 +0x1b7
I1109 04:04:59.078270       5 leaderelection.go:188] sucessfully acquired lease kube-system/kube-controller-manager
```

cc: @kubernetes/deployment 

Found in https://github.com/kubernetes/kubernetes/issues/36286#issuecomment-259332072

**Comment by kargakis** [comment]
Increasing the priority to P0 because it seems this is the issue behind most of the latest deployment flakes.
