### ISSUE TITLE
etcd 2.3.7 panics with rolled back data

### ISSUE THREAD

**Issue by mml** [kubernetes/kubernetes#37035]
Wasn't sure whether to file here or etcd, but the problem probably occurs due to the rollback tool that's in this repo.

This is with my test cluster.  I have upgraded the data from 2.21 to 2.3.7 to 3.0.14.

```
 Backup and remove all existing v2 data
 Performing etcd3 -> etcd2 rollback
 2016-11-17 21:58:12.410302 I | membership: added member b71f75320dc06a6c [http://127.0.0.1:2380] to cluster 0
 2016-11-17 21:58:12.410419 N | membership: set the initial cluster version to 2.2
 2016-11-17 21:58:12.410443 I | api: enabled capabilities for version 2.2
 2016-11-17 21:58:12.410659 N | membership: updated the cluster version from 2.2 to 2.3
 2016-11-17 21:58:12.410680 I | api: enabled capabilities for version 2.3
 2016-11-17 21:58:12.410716 N | membership: updated the cluster version from 2.3 to 3.0
 2016-11-17 21:58:12.410738 I | api: enabled capabilities for version 3.0
 Finished successfully
```

Then we try to start etcd 2.3.7...

```
 2016-11-17 21:58:12.851626 I | etcdmain: etcd Version: 2.3.7
 2016-11-17 21:58:12.851692 I | etcdmain: Git SHA: fd17c91
 2016-11-17 21:58:12.851700 I | etcdmain: Go Version: go1.6.2
 2016-11-17 21:58:12.851706 I | etcdmain: Go OS/Arch: linux/amd64
 2016-11-17 21:58:12.851718 I | etcdmain: setting maximum number of CPUs to 12, total number of available CPUs is 12
 2016-11-17 21:58:12.851759 W | etcdmain: found invalid file/dir version.txt under data dir /var/etcd/data (Ignore this if you are upgrading etcd)
 2016-11-17 21:58:12.851770 N | etcdmain: the server is already initialized as member before, starting as etcd member...
 2016-11-17 21:58:12.851845 I | etcdmain: listening for peers on http://127.0.0.1:2380
 2016-11-17 21:58:12.851884 I | etcdmain: listening for client requests on http://127.0.0.1:2379
 2016-11-17 21:58:12.853423 I | etcdserver: recovered store from snapshot at index 46
 2016-11-17 21:58:12.853440 I | etcdserver: name = etcd-master
 2016-11-17 21:58:12.853450 I | etcdserver: data dir = /var/etcd/data
 2016-11-17 21:58:12.853460 I | etcdserver: member dir = /var/etcd/data/member
 2016-11-17 21:58:12.853469 I | etcdserver: heartbeat = 100ms
 2016-11-17 21:58:12.853478 I | etcdserver: election = 1000ms
 2016-11-17 21:58:12.853487 I | etcdserver: snapshot count = 10000
 2016-11-17 21:58:12.853509 I | etcdserver: advertise client URLs = http://127.0.0.1:2379
 panic: runtime error: makeslice: len out of range
 
 goroutine 1 [running]:
 panic(0xdc26c0, 0xc820262c50)
         /usr/local/go/src/runtime/panic.go:481 +0x3e6
 github.com/coreos/etcd/wal.(*decoder).decode(0xc820255320, 0xc8201fdf90, 0x0, 0x0)
         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/wal/decoder.go:55 +0x142
 github.com/coreos/etcd/wal.(*WAL).ReadAll(0xc82021f930, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/wal/wal.go:237 +0x214
 github.com/coreos/etcd/etcdserver.readWAL(0xc820258da0, 0x19, 0x2e, 0x6, 0x0, 0x0, 0x0, 0xc82021f930, 0x1, 0xc820262a90, ...)
         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/storage.go:87 +0x228
 github.com/coreos/etcd/etcdserver.restartNode(0xc82008f2c0, 0xc820081290, 0x29, 0xc8201fe950, 0x0, 0x0, 0x0, 0x0)
         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/raft.go:334 +0xff
 github.com/coreos/etcd/etcdserver.NewServer(0xc82008f2c0, 0xc82008f378, 0x0, 0x0)
         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:333 +0x3be5
 github.com/coreos/etcd/etcdmain.startEtcd(0xc820091180, 0x0, 0x0, 0x0)
         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:302 +0x1b40
 github.com/coreos/etcd/etcdmain.Main()
         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:118 +0x2142
 main.main()
         /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/main.go:29 +0x14
```

@wojtek-t @hongchaodeng

**Comment by lavalamp** [comment]
@xiang90

**Comment by xiang90** [comment]
@mml Do you still have the data before you preformed the rollback?

**Comment by hongchaodeng** [comment]
How to repro?

**Comment by mml** [comment]
Whoops.  To reproduce expand this tarfile and run `rollback --data-dir $(pwd)/etcd/data`

[etcd-data.tar.gz](https://github.com/kubernetes/kubernetes/files/600791/etcd-data.tar.gz)

**Comment by xiang90** [comment]
This is a dup with https://github.com/kubernetes/kubernetes/issues/37035. I am going to comment there.

**Comment by mml** [comment]
@xiang90 *this* is #37035

**Comment by xiang90** [comment]
sorry i wanted to close #37131. but i think that one actually has more context. so how about closing this one and keep #37131?

**Comment by xiang90** [comment]
@mml Can you verify this is also fixed if we do https://github.com/kubernetes/kubernetes/issues/38253?

**Comment by mml** [comment]
Yes, that's correct.
