### ISSUE TITLE
kubelet: concurrent map read & write

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#37560]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-cri/644

bootstrap-e2e-minion-group-22bp/kubelet.log

```
fatal error: concurrent map read and map write
goroutine 79 [running]:
runtime.throw(0x29b56bd, 0x21)
/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc420b41660 sp=0xc420b41640
runtime.mapaccess1_faststr(0x2491400, 0xc4215c0780, 0x29c7833, 0x27, 0x3efc2e0)
/usr/local/go/src/runtime/hashmap_fast.go:201 +0x4f3 fp=0xc420b416c0 sp=0xc420b41660
k8s.io/kubernetes/pkg/api/v1/pod.SetInitContainersAndStatuses(0xc421227340, 0x0, 0x0)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/v1/pod/util.go:67 +0x57 fp=0xc420b41738 sp=0xc420b416c0
k8s.io/kubernetes/pkg/kubelet/config.newSourceApiserverFromLW.func1(0xc4204dd7a0, 0x11, 0x11)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:44 +0xa4 fp=0xc420b41818 sp=0xc420b41738
k8s.io/kubernetes/pkg/client/cache.(*UndeltaStore).Update(0xc4209d6a40, 0x2903dc0, 0xc4200d3340, 0xc4200d3340, 0x1)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/cache/undelta_store.go:57 +0x9b fp=0xc420b41850 sp=0xc420b41818
k8s.io/kubernetes/pkg/client/cache.(*Reflector).watchHandler(0xc420287c00, 0x3e15700, 0xc4208b0570, 0xc420b41c40, 0xc420bce4e0, 0xc42005e900, 0x0, 0x0)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:368 +0x8a3 fp=0xc420b41b18 sp=0xc420b41850
k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch(0xc420287c00, 0xc42005e900, 0x0, 0x0)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:313 +0xa6f fp=0xc420b41e20 sp=0xc420b41b18
k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run.func1()
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:187 +0x36 fp=0xc420b41e50 sp=0xc420b41e20
k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc420335140)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:96 +0x5e fp=0xc420b41e88 sp=0xc420b41e50
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc420335140, 0x3b9aca00, 0x0, 0x1, 0xc42005e900)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:97 +0xad fp=0xc420b41f50 sp=0xc420b41e88
k8s.io/kubernetes/pkg/util/wait.Until(0xc420335140, 0x3b9aca00, 0xc42005e900)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:52 +0x4d fp=0xc420b41f88 sp=0xc420b41f50
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420b41f90 sp=0xc420b41f88
created by k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:190 +0x1ad
```

The offending line was added by #36673

/cc @dchen1107

**Comment by yujuhong** [comment]
Found another one in a non-cri (i.e., regular) build: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/379

**Comment by yujuhong** [comment]
Spoke to @caesarxuchao offline. He will send a fix soon. 

/cc @saad-ali

**Comment by liggitt** [comment]
shouldn't be a release blocker, that PR merged post branch

**Comment by yujuhong** [comment]
> shouldn't be a release blocker, that PR merged post branch

Ah..good to know. Thanks!
