### ISSUE TITLE
failed to start apiserver if use --authorization-mode=RBAC

### ISSUE THREAD

**Issue by xilabao** [kubernetes/kubernetes#37615]
Happen to the newest version.

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

**Kubernetes version** (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.949+e6c57c6569ea38", GitCommit:"e6c57c6569ea38a007c1c75916718cb078cce40d", GitTreeState:"clean", BuildDate:"2016-11-29T06:35:08Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:local
- **OS** (e.g. from /etc/os-release):Ubuntu 15.10
- **Kernel** (e.g. `uname -a`):4.2.0-42-generic

**What happened**:
kube-apiserver start failed:
```
Nov 29 03:54:17 master kube-apiserver[15094]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:198
Nov 29 03:54:17 master kube-apiserver[15094]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:96
Nov 29 03:54:17 master kube-apiserver[15094]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:97
Nov 29 03:54:17 master kube-apiserver[15094]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:52
Nov 29 03:54:17 master kube-apiserver[15094]: /usr/local/go/src/runtime/asm_amd64.s:2086
Nov 29 03:54:17 master kube-apiserver[15094]: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
Nov 29 03:54:17 master kube-apiserver[15094]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 29 03:54:17 master kube-apiserver[15094]: [signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x827979]
Nov 29 03:54:17 master kube-apiserver[15094]: goroutine 533 [running]:
Nov 29 03:54:17 master kube-apiserver[15094]: panic(0x251af00, 0xc42000e060)
Nov 29 03:54:17 master kube-apiserver[15094]: /usr/local/go/src/runtime/panic.go:500 +0x1a1
Nov 29 03:54:17 master kube-apiserver[15094]: k8s.io/kubernetes/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Nov 29 03:54:17 master kube-apiserver[15094]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:56 +0x126
Nov 29 03:54:17 master kube-apiserver[15094]: panic(0x251af00, 0xc42000e060)
Nov 29 03:54:17 master kube-apiserver[15094]: /usr/local/go/src/runtime/panic.go:458 +0x243
Nov 29 03:54:17 master kube-apiserver[15094]: k8s.io/kubernetes/pkg/controller/informers.(*roleBindingInformer).Informer.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0
Nov 29 03:54:17 master kube-apiserver[15094]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/informers/rbac.go:170 +0x39
Nov 29 03:54:17 master kube-apiserver[15094]: k8s.io/kubernetes/pkg/client/cache.(*ListWatch).List(0xc4202c4bf0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 
Nov 29 03:54:17 master kube-apiserver[15094]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/cache/listwatch.go:91 +0x5d
Nov 29 03:54:17 master kube-apiserver[15094]: k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch(0xc420298000, 0xc42012aea0, 0x0, 0x0)
Nov 29 03:54:17 master kube-apiserver[15094]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:243 +0x2ba
Nov 29 03:54:17 master kube-apiserver[15094]: k8s.io/kubernetes/pkg/client/cache.(*Reflector).RunUntil.func1()
Nov 29 03:54:17 master kube-apiserver[15094]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:198 +0x33
Nov 29 03:54:17 master kube-apiserver[15094]: k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc420db4080)
Nov 29 03:54:17 master kube-apiserver[15094]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:96 +0x5e
Nov 29 03:54:17 master kube-apiserver[15094]: k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc420db4080, 0x3b9aca00, 0x0, 0xc4202af801, 0xc42012aea0)
Nov 29 03:54:17 master kube-apiserver[15094]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:97 +0xad
Nov 29 03:54:17 master kube-apiserver[15094]: k8s.io/kubernetes/pkg/util/wait.Until(0xc420db4080, 0x3b9aca00, 0xc42012aea0)
Nov 29 03:54:17 master kube-apiserver[15094]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:52 +0x4d
Nov 29 03:54:17 master kube-apiserver[15094]: created by k8s.io/kubernetes/pkg/client/cache.(*Reflector).RunUntil
Nov 29 03:54:17 master kube-apiserver[15094]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:201 +0x1c4
Nov 29 03:54:17 master systemd[1]: kube-apiserver.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 29 03:54:17 master systemd[1]: Failed to start Kubernetes API Server.
Nov 29 03:54:17 master systemd[1]: kube-apiserver.service: Unit entered failed state.
Nov 29 03:54:17 master systemd[1]: kube-apiserver.service: Failed with result 'exit-code'.
Nov 29 03:54:17 master systemd[1]: kube-apiserver.service: Service hold-off time over, scheduling restart.
Nov 29 03:54:17 master systemd[1]: Stopped Kubernetes API Server.
Nov 29 03:54:17 master systemd[1]: kube-apiserver.service: Start request repeated too quickly.
Nov 29 03:54:17 master systemd[1]: Failed to start Kubernetes API Server.
Nov 29 03:54:17 master systemd[1]: kube-apiserver.service: Unit entered failed state.
Nov 29 03:54:17 master systemd[1]: kube-apiserver.service: Failed with result 'start-limit'.
```

**Comment by deads2k** [comment]
Looks like the change to external clients in the informers broke this

**Comment by deads2k** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/37714.  Thanks for the bug report.
