### ISSUE TITLE
apiserver error: first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by Pensu** [kubernetes/kubernetes#38380]
Hi,

I have been trying to run api-server as an standalone service along with etcd. I am passing etcd-servers and cluster-ip-range as arguments, here is the error I am getting:

 ```
./_output/bin/kube-apiserver --etcd-servers=http://127.0.0.1:2379 --service-cluster-ip-range=10.0.0.0/16
I1207 01:29:41.175437   16008 config.go:514] Will report 192.168.122.69 as public IP address.
W1207 01:29:41.179097   16008 config_selfclient.go:39] Failed to create secure local client, falling back to insecure local connection: <nil>
E1207 01:29:41.179125   16008 server.go:245] Failed to create clientset: parse 127.0.0.1:8080: first path segment in URL cannot contain colon
panic: parse 127.0.0.1:8080: first path segment in URL cannot contain colon

goroutine 1 [running]:
k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/core/internalversion.NewForConfigOrDie(0xc420756700, 0xc42072adf0)
    /root/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/core/internalversion/core_client.go:132 +0x68
k8s.io/kubernetes/pkg/master.(*Config).Complete(0xc42072bce8, 0x0)
    /root/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/master/master.go:181 +0x330
k8s.io/kubernetes/cmd/kube-apiserver/app.Run(0xc420580140, 0x24ca4f0, 0x5115440)
    /root/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:311 +0x16ac
main.main()
    /root/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/apiserver.go:50 +0xc0
```

etcd servers are up and running on that address. Any leads as to how to resolve this? TIA.

**Comment by mkumatag** [comment]
This is only happening on go1.8 version, not really sure what is causing issue while parsing the URI.

**Comment by dims** [comment]
Caused by this change i believe - https://github.com/golang/go/commit/c5ccbdd22bdbdc43d541b7e7d4ed66ceb559030e 

CC @jessfraz as 1.8beta1 is being worked on here - https://github.com/kubernetes/kubernetes/issues/38228

**Comment by mkumatag** [comment]
@dims Thanks

**Comment by timstoop** [comment]
I'm getting this exact issue using Kubernetes 1.5.7 and Go 1.8.3. Reverting to Go 1.7 seems to resolve it. This happened after updating a Go 1.7-compiled 1.4.8 Kubernetes cluster to 1.5.7, not sure if that's a corner case.

For reference, my stack trace:

```
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]: I0619 06:01:46.997174       1 config.go:527] Will report 10.101.6.237 as public IP address.
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]: I0619 06:01:46.997284       1 aws.go:749] Building AWS cloudprovider
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]: I0619 06:01:46.997311       1 aws.go:703] Zone not specified in configuration file; querying AWS metadata service
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]: E0619 06:01:47.806067       1 aws.go:831] Tag "KubernetesCluster" not found; Kubernetes may behave unexpectedly.
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]: I0619 06:01:47.806086       1 aws.go:838] AWS cloud - no tag filtering
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]: E0619 06:01:47.808917       1 server.go:254] Failed to create clientset: parse 127.0.0.1:8080: first path segment in URL cannot contain colon
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]: panic: parse 127.0.0.1:8080: first path segment in URL cannot contain colon
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]: goroutine 1 [running]:
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]: k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/core/internalversion.NewForConfigOrDie(0xc420bf5860, 0xc420df8918)
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]:         /opt/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/core/internalversion/core_cli
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]: k8s.io/kubernetes/pkg/master.(*Config).Complete(0xc420df98a0, 0x0)
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]:         /opt/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/master/master.go:180 +0x40a
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]: k8s.io/kubernetes/cmd/kube-apiserver/app.Run(0xc4201cd040, 0xc4209c7aa8, 0xc4200d8b70)
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]:         /opt/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:347 +0x1e8d
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]: main.NewKubeAPIServer.func1(0xc420bb97c0, 0xc420230200, 0x0, 0x10, 0x0, 0x0)
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]:         /opt/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/hyperkube/kube-apiserver.go:33 +0x2a
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]: main.(*HyperKube).Run(0xc4205525a0, 0xc420010130, 0x10, 0x11, 0x0, 0x0)
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]:         /opt/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/hyperkube/hyperkube.go:179 +0x416
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]: main.(*HyperKube).RunToExit(0xc4205525a0, 0xc420010120, 0x11, 0x12)
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]:         /opt/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/hyperkube/hyperkube.go:189 +0x53
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]: main.main()
Jun 19 06:01:47 ip-10-101-6-237.eu-west-1.compute.internal docker[1365]:         /opt/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/hyperkube/main.go:46 +0x779
```

**Comment by Shreyamitti** [comment]
2024/12/19 18:32:00 Error creating request: parse "172.20.212.240:80/api/v1/operators/add": first path segment in URL cannot contain colon
