### ISSUE TITLE
kubectl randomly fails with `fatal error: MSpanList_Insert`

### ISSUE THREAD

**Issue by sandcastle** [kubernetes/kubernetes#39316]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**Kubernetes version**:

```
Client Version: version.Info{Major:"0", Minor:"20.1", GitVersion:"v0.20.1", GitCommit:"", GitTreeState:"not a git tree"}

Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Macbook Pro
- **OS** (e.g. from /etc/os-release): macOS Sierra 10.12.2 (16C67)
- **Kernel**:  `Darwin 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64`
- **Install tools**: brew (kubernetes-cli) or curl (http://kubernetes.io/docs/user-guide/prereqs/) - both give same result
- **go version**: go1.7.4 darwin/amd64

**What happened**:

When running any `kubectl` command roughly 2 out of 3 times it results in the following error:

```
$ kubectl version
failed MSpanList_Insert 0xd8c8e0 0xdb2fe440763f 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.MSpanList_Insert(0xc58880, 0xd8c8e0)
	/usr/src/go/src/runtime/mheap.c:692 +0x8f
runtime.MHeap_Alloc(0xc57d80, 0x1, 0x1000000000a, 0xcf39)
	/usr/src/go/src/runtime/mheap.c:240 +0x66
runtime.MCentral_CacheSpan(0xc5f1f8, 0xd8c9b0)
	/usr/src/go/src/runtime/mcentral.c:85 +0x167
runtime.MCache_Refill(0xd85000, 0xc20000000a, 0xd8c9b0)
	/usr/src/go/src/runtime/mcache.c:90 +0xa0

goroutine 1 [running]:
runtime.switchtoM()
	/usr/src/go/src/runtime/asm_amd64.s:198 fp=0xc208232698 sp=0xc208232690
runtime.mallocgc(0x90, 0x5f21a0, 0xc200000001, 0xc2081c1ef0)
	/usr/src/go/src/runtime/malloc.go:178 +0x849 fp=0xc208232748 sp=0xc208232698
runtime.newarray(0x5f21a0, 0x11, 0xc2081c1ef0)
	/usr/src/go/src/runtime/malloc.go:365 +0xc1 fp=0xc208232780 sp=0xc208232748
runtime.makeslice(0x812560, 0x11, 0x11, 0x0, 0x0, 0x0)
	/usr/src/go/src/runtime/slice.go:32 +0x15c fp=0xc2082327c8 sp=0xc208232780
math/big.nat.divLarge(0xc2081ffd40, 0x10, 0x24, 0xc208076640, 0x20, 0x25, 0xc2081fed80, 0x20, 0x24, 0xc208036420, ...)
	/usr/src/go/src/math/big/nat.go:541 +0x2d0 fp=0xc208232960 sp=0xc2082327c8
math/big.nat.div(0xc2081ffd40, 0x10, 0x24, 0xc208076640, 0x20, 0x25, 0xc2081fed80, 0x20, 0x24, 0xc208036420, ...)
	/usr/src/go/src/math/big/nat.go:519 +0x35a fp=0xc208232a08 sp=0xc208232960
math/big.nat.expNNWindowed(0xc2081fed80, 0x20, 0x24, 0xc208172c80, 0x10, 0x14, 0xc208172b40, 0x10, 0x14, 0xc208036420, ...)
	/usr/src/go/src/math/big/nat.go:1361 +0xdd7 fp=0xc208232c98 sp=0xc208232a08
math/big.nat.expNN(0xc2081fed80, 0x10, 0x24, 0xc208172c80, 0x10, 0x14, 0xc208172b40, 0x10, 0x14, 0xc208036420, ...)
	/usr/src/go/src/math/big/nat.go:1260 +0x4b0 fp=0xc208232e30 sp=0xc208232c98
math/big.nat.probablyPrime(0xc208036420, 0x10, 0x15, 0x14, 0x0)
	/usr/src/go/src/math/big/nat.go:1445 +0x887 fp=0xc208232fa8 sp=0xc208232e30
math/big.(*Int).ProbablyPrime(0xc2080d0220, 0x14, 0xc207ff2b1f)
	/usr/src/go/src/math/big/int.go:741 +0x4a fp=0xc208232fd8 sp=0xc208232fa8
crypto/rsa.(*PrivateKey).Validate(0xc20819c240, 0x0, 0x0)
	/usr/src/go/src/crypto/rsa/rsa.go:110 +0x108 fp=0xc2082330d8 sp=0xc208232fd8
crypto/x509.ParsePKCS1PrivateKey(0xc2080ccf00, 0x4a7, 0x4a7, 0xc20819c240, 0x0, 0x0)
	/usr/src/go/src/crypto/x509/pkcs1.go:77 +0x702 fp=0xc208233260 sp=0xc2082330d8
crypto/tls.parsePrivateKey(0xc2080ccf00, 0x4a7, 0x4a7, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/crypto/tls/tls.go:259 +0x7d fp=0xc208233350 sp=0xc208233260
crypto/tls.X509KeyPair(0xc20808f615, 0x0, 0x0, 0xc2080d7e76, 0x0, 0x0, 0xc2080d0180, 0x1, 0x1, 0x0, ...)
	/usr/src/go/src/crypto/tls/tls.go:213 +0x394 fp=0xc208233548 sp=0xc208233350
github.com/GoogleCloudPlatform/kubernetes/pkg/client.NewClientCertTLSConfig(0xc20808f200, 0x426, 0x426, 0xc2080d7800, 0x68b, 0x68b, 0xc20808ed80, 0x416, 0x416, 0x1f90819b74f, ...)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/transport.go:149 +0x8f fp=0xc2082336b8 sp=0xc208233548
github.com/GoogleCloudPlatform/kubernetes/pkg/client.TLSConfigFor(0xc208077040, 0xc208174f50, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/transport.go:91 +0x1a7 fp=0xc208233738 sp=0xc2082336b8
github.com/GoogleCloudPlatform/kubernetes/pkg/client.TransportFor(0xc208077040, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/helper.go:341 +0xd7 fp=0xc208233850 sp=0xc208233738
github.com/GoogleCloudPlatform/kubernetes/pkg/client.RESTClientFor(0xc208077040, 0x0, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/helper.go:318 +0x1d8 fp=0xc2082338d8 sp=0xc208233850
github.com/GoogleCloudPlatform/kubernetes/pkg/client.New(0xc208076f00, 0x0, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/helper.go:138 +0xbf fp=0xc208233938 sp=0xc2082338d8
github.com/GoogleCloudPlatform/kubernetes/pkg/client.NegotiateVersion(0xc208076f00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/helper.go:176 +0x66 fp=0xc208233af0 sp=0xc208233938
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/util.(*clientCache).ClientConfigForVersion(0xc20803dbf0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/util/clientcache.go:61 +0x23c fp=0xc208233bb8 sp=0xc208233af0
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/util.(*clientCache).ClientForVersion(0xc20803dbf0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/util/clientcache.go:78 +0xcd fp=0xc208233c28 sp=0xc208233bb8
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/util.func·002(0xc208163ba0, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/util/factory.go:120 +0x50 fp=0xc208233c60 sp=0xc208233c28
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd.RunVersion(0xc208082090, 0xd96c30, 0xc208046008, 0xc208163ba0, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/version.go:47 +0x94 fp=0xc208233cb0 sp=0xc208233c60
github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd.func·030(0xc208163ba0, 0xc4f338, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/cmd/version.go:33 +0x41 fp=0xc208233cf8 sp=0xc208233cb0
github.com/spf13/cobra.(*Command).execute(0xc208163ba0, 0xc4f338, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:495 +0x65c fp=0xc208233e08 sp=0xc208233cf8
github.com/spf13/cobra.(*Command).Execute(0xc20803ed00, 0x0, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/spf13/cobra/command.go:560 +0x18d fp=0xc208233f08 sp=0xc208233e08
main.main()
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/kubectl/kubectl.go:30 +0x104 fp=0xc208233f98 sp=0xc208233f08
runtime.main()
	/usr/src/go/src/runtime/proc.go:63 +0xf3 fp=0xc208233fe0 sp=0xc208233f98
runtime.goexit()
	/usr/src/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208233fe8 sp=0xc208233fe0

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xc455c0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 11 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 12 [select]:
github.com/GoogleCloudPlatform/kubernetes/pkg/util.(*tickRateLimiter).step(0xc2080d0160, 0x0)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:102 +0xfc
github.com/GoogleCloudPlatform/kubernetes/pkg/util.(*tickRateLimiter).run(0xc2080d0160)
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:95 +0x28
created by github.com/GoogleCloudPlatform/kubernetes/pkg/util.NewTokenBucketRateLimiter
	/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/throttle.go:50 +0x81
```

From `brew` I uninstalled go and kuberenetes-cli and reinstalled and that didn't seem to have an impact. I also tried installing following the  user guide links (http://kubernetes.io/docs/user-guide/prereqs/) and again the same result remains.

**What you expected to happen**:

The kubectl command should execute

**How to reproduce it**:

Roughly 2 out of 3 calls to `kubectl` will result in the error being thrown.

**Anything else do we need to know**:

I have also tried with `v1.5.2-beta.0` compiled locally via `brew` and same issue still.

There are mentions of a similar issue that was resolved here:
https://github.com/kubernetes/kubernetes/issues/33801#issuecomment-250890436

**Comment by riturajtiwari** [comment]
I have the same problem with Kubectl version:
```
Client Version: version.Info{Major:"0", Minor:"18", GitVersion:"v0.18.2", GitCommit:"1f12b893876ad6c41396222693e37061f6e80fe1", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean"}
```

and minikube version:
`minikube version: v0.14.0`

**Comment by riturajtiwari** [comment]
Reverting to kubectl 1.4.4 removes this issue for me:
```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sandcastle** [comment]
Ok, so something super weird was going on - after running `brew prune`, `brew cleanup`, uninstalling `google-cloud-sdk` and rebooting - everything is now working and when running `kubectl get` I now have all options (some were missing like `deployments` previously). I'm also not seeing the crashes that were previously happening.

@riturajtiwari - do these steps help you?
