### ISSUE TITLE
ci-kubernetes-build failing

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#39380]
The submit queue is stuck on https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build/525 .

```
I0103 10:59:36.763] OK
I0103 10:59:39.173] * Validating uploaded version file at https://storage.googleapis.com/kubernetes-release-dev/ci/latest.txt: FAILED (file contents: v1.6.0-alpha.0.2710+1cee8c45d6c703)
I0103 10:59:39.176] 
I0103 10:59:39.178] 
I0103 10:59:39.181] Signal ERR caught!
I0103 10:59:39.184] 
I0103 10:59:39.186] Traceback (line function script):
I0103 10:59:39.187] 166 main /var/lib/jenkins/workspace/ci-kubernetes-build/go/src/k8s.io/kubernetes/_tmp/release.git/push-build.sh
I0103 10:59:39.189] 
I0103 10:59:39.192] Exiting...
I0103 10:59:39.194] 
I0103 10:59:39.197] 
I0103 10:59:39.199] push-build.sh: DONE main on agent-heavy-7 Tue Jan  3 10:59:39 PST 2017 in 46s
W0103 10:59:39.204] Traceback (most recent call last):
W0103 10:59:39.204]   File "/var/lib/jenkins/workspace/ci-kubernetes-build/./test-infra/jenkins/../jobs/../scenarios/kubernetes_build.py", line 85, in <module>
W0103 10:59:39.204]     main(ARGS)
W0103 10:59:39.204]   File "/var/lib/jenkins/workspace/ci-kubernetes-build/./test-infra/jenkins/../jobs/../scenarios/kubernetes_build.py", line 60, in main
W0103 10:59:39.204]     check(args.script)
W0103 10:59:39.204]   File "/var/lib/jenkins/workspace/ci-kubernetes-build/./test-infra/jenkins/../jobs/../scenarios/kubernetes_build.py", line 31, in check
W0103 10:59:39.205]     subprocess.check_call(cmd)
W0103 10:59:39.205]   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
W0103 10:59:39.205]     raise CalledProcessError(retcode, cmd)
W0103 10:59:39.205] subprocess.CalledProcessError: Command '('./hack/jenkins/build.sh',)' returned non-zero exit status 2
W0103 10:59:39.207] + rc=1
W0103 10:59:39.207] + [[ 1 -eq 124 ]]
I0103 10:59:39.208] Exiting with code: 1
W0103 10:59:39.208] + [[ 1 -eq 137 ]]
W0103 10:59:39.208] + [[ 1 -ne 0 ]]
W0103 10:59:39.208] + echo 'Build failed'
```

**Comment by deads2k** [comment]
@kubernetes/test-infra-maintainers

**Comment by fejta** [comment]
Thanks, looking into this

**Comment by fejta** [comment]
Running the job a second time. This just looks like a flake. A single flake should not block the SQ. @rmmh @lavalamp

**Comment by fejta** [comment]
Jeff I'll let you look into whether there is anything interesting to do with our build infra for:

```
I0103 10:59:39.173] * Validating uploaded version file at https://storage.googleapis.com/kubernetes-release-dev/ci/latest.txt: FAILED (file contents: v1.6.0-alpha.0.2710+1cee8c45d6c703)
I0103 10:59:39.181] Signal ERR caught!
```

**Comment by ixdy** [comment]
This one is really weird; it seems like GCS was caching the latest.txt file:

```
I0103 10:59:30.254] Publish official pointer text files to ...
I0103 10:59:32.304] Test v1.6.0-alpha.0.2720+8623fdf0b106e1 > ci/latest.txt (published): OK
I0103 10:59:32.308] * v1.6.0-alpha.0.2720+8623fdf0b106e1 > v1.6.0-alpha.0.2710+1cee8c45d6c703
I0103 10:59:32.308] (published), updating
I0103 10:59:32.309] 
I0103 10:59:32.309] push-build.sh::release::gcs::publish(): mkdir -p /var/lib/jenkins/workspace/ci-kubernetes-build/go/src/k8s.io/kubernetes/_output/release-stage/upload
I0103 10:59:32.311] 
I0103 10:59:32.311] push-build.sh::release::gcs::publish(): /usr/bin/gsutil -m -h Content-Type:text/plain cp /var/lib/jenkins/workspace/ci-kubernetes-build/go/src/k8s.io/kubernetes/_output/release-stage/upload/latest gs://kubernetes-release-dev/ci/latest.txt
I0103 10:59:34.287] Copying file:///var/lib/jenkins/workspace/ci-kubernetes-build/go/src/k8s.io/kubernetes/_output/release-stage/upload/latest [Content-Type=text/plain]...
I0103 10:59:34.438] / [0/1 files][    0.0 B/   35.0 B]   0% Done                                    
/ [1/1 files][   35.0 B/   35.0 B] 100% Done                                    
I0103 10:59:34.438] Operation completed over 1 objects/35.0 B.                                       
I0103 10:59:34.588] Making uploaded version file public and non-cacheable: 
I0103 10:59:34.589] push-build.sh::release::gcs::publish(): /usr/bin/gsutil acl ch -R -g all:R gs://kubernetes-release-dev/ci/latest.txt
I0103 10:59:36.606] No changes to gs://kubernetes-release-dev/ci/latest.txt
I0103 10:59:36.763] OK
I0103 10:59:39.173] * Validating uploaded version file at https://storage.googleapis.com/kubernetes-release-dev/ci/latest.txt: FAILED (file contents: v1.6.0-alpha.0.2710+1cee8c45d6c703)
```

We mark this file [non-cacheable](https://github.com/kubernetes/release/blob/master/lib/releaselib.sh#L708), but maybe setting that header after uploading isn't working?

I created https://github.com/kubernetes/release/pull/240 to make the file non-cacheable as we upload it. I'm not sure whether we'll run into this issue again, though.

**Comment by zmerlynn** [comment]
Re-running this job broke `kop-aws` because the `sha1` files look like they're inappropriately cached as well: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws/1826/artifacts/ec2-35-162-125-195.us-west-2.compute.amazonaws.com/cloud-init-output.log (cc @justinsb)

**Comment by ixdy** [comment]
@zmerlynn that one is tricker to fix, since we upload all release artifacts (tarballs, binaries, and md5/sha1 sums) at once: https://github.com/kubernetes/release/blob/master/lib/releaselib.sh#L493-L503, and we definitely want binaries to be cacheable.

**Comment by zmerlynn** [comment]
Yeah, I'm not sure it's worth fixing, I'm just noting it's not fully safe to re-run the job.

**Comment by ixdy** [comment]
yeah, it's good to know. it also confirms my suspicion that having multiple build jobs pushing builds to the same path (which is a thing we've done before) is unsafe.
