### ISSUE TITLE
Error running make test-integration discoverysummarizer

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/kubernetes#39573]
I am encountering the following exception while running `make test-integration` on master.

```
F0107 15:18:31.741148    5835 apiserver.go:91] Error creating self-signed certificates: mkdir /var/run/kubernetes: permission denied
goroutine 101 [running]:
k8s.io/kubernetes/vendor/github.com/golang/glog.stacks(0x25b9c00, 0xc400000000, 0x85, 0xd5)
	/u01/clove/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:766 +0xa5
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).output(0x2599900, 0xc400000003, 0xc420032480, 0x240a13f, 0xc, 0x5b, 0x0)
	/u01/clove/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:717 +0x337
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).printf(0x2599900, 0x3, 0x19ea3e0, 0x2b, 0xc4204e1c18, 0x1, 0x1)
	/u01/clove/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:655 +0x14c
k8s.io/kubernetes/vendor/github.com/golang/glog.Fatalf(0x19ea3e0, 0x2b, 0xc4204e1c18, 0x1, 0x1)
	/u01/clove/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:1145 +0x67
k8s.io/kubernetes/examples/apiserver.(*ServerRunOptions).Run(0xc42037bda0, 0xc42019d500, 0x0, 0x0)
	/u01/clove/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/examples/apiserver/apiserver.go:91 +0x1200
k8s.io/kubernetes/test/integration/discoverysummarizer.runAPIServer.func1(0xc42037bda0, 0xc42019d500, 0xc420620480)
	/u01/clove/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/discoverysummarizer/discoverysummarizer_test.go:74 +0x39
created by k8s.io/kubernetes/test/integration/discoverysummarizer.runAPIServer
	/u01/clove/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/discoverysummarizer/discoverysummarizer_test.go:77 +0x7e
FAIL	k8s.io/kubernetes/test/integration/discoverysummarizer	1.013s
```

On centos: Linux build-01-pi 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Go: go version go1.7.3 linux/amd64

**Comment by chrislovecnm** [comment]
Closing
