### ISSUE TITLE
kube-apiserver restarts due to failing SSHKey sync check

### ISSUE THREAD

**Issue by normanrz** [kubernetes/kubernetes#39585]
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Bunch of bare metal servers x64
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 8 (jessie)
- **Kernel** (e.g. `uname -a`): Linux kube.scm.io 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
- **Install tools**: kubeadm

**What happened**:
I observed a high number of restarts for `kube-apiserver`. I checked the logs and the `/healthz` request repeatedly fails.

```
E0108 22:36:22.766430       1 tunneler.go:165] Won't attempt to install ssh key: InstallSSHKey function is nil
[...]
I0108 22:36:52.434109       1 panics.go:76] GET /healthz: (1.14401ms) 500
goroutine 26438 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc4256b73b0, 0x1f4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:219 +0xbb
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc4256b73b0, 0x1f4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:198 +0x35
net/http.Error(0x4945220, 0xc4256b73b0, 0xc4222d6000, 0xda, 0x1f4)
	/usr/local/go/src/net/http/server.go:1738 +0xda
k8s.io/kubernetes/pkg/healthz.handleRootHealthz.func1(0x4945220, 0xc4256b73b0, 0xc423896690)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/healthz/healthz.go:109 +0x490
net/http.HandlerFunc.ServeHTTP(0xc4224cffe0, 0x4945220, 0xc4256b73b0, 0xc423896690)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc42018b1d0, 0x4945220, 0xc4256b73b0, 0xc423896690)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
k8s.io/kubernetes/pkg/genericapiserver/filters.WithPanicRecovery.func1(0x4945220, 0xc4256b73b0, 0xc423896690)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/panics.go:75 +0x24a
net/http.HandlerFunc.ServeHTTP(0xc42015ee40, 0x7f3acf95a2a8, 0xc424cce590, 0xc423896690)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/apiserver/filters.WithRequestInfo.func1(0x7f3acf95a2a8, 0xc424cce590, 0xc423896690)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/filters/requestinfo.go:45 +0x212
net/http.HandlerFunc.ServeHTTP(0xc42015ef30, 0x7f3acf95a2a8, 0xc424cce590, 0xc423896690)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/api.WithRequestContext.func1(0x7f3acf95a2a8, 0xc424cce590, 0xc423896690)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:107 +0xef
net/http.HandlerFunc.ServeHTTP(0xc4205bd940, 0x7f3acf95a2a8, 0xc424cce590, 0xc423896690)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/genericapiserver/filters.(*timeoutHandler).ServeHTTP.func1(0xc4205bd960, 0x494a7e0, 0xc424cce590, 0xc423896690, 0xc425d8b6e0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/timeout.go:78 +0x8d
created by k8s.io/kubernetes/pkg/genericapiserver/filters.(*timeoutHandler).ServeHTTP
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/timeout.go:80 +0x1db

logging error output: "[+]poststarthook/bootstrap-controller ok\n[+]poststarthook/extensions/third-party-resources ok\n[+]poststarthook/rbac/bootstrap-roles ok\n[-]SSH Tunnel Check failed: SSHKey sync is taking to long: 630\nhealthz check failed\n"
 [[Go-http-client/1.1] 127.0.0.1:34231]
```

I am using ssh tunnels for master -> node communication but have not set up a cloud provider for the apiserver because my servers are self-hosted. I traced through the source code and found out that tunneler won't set the `lastSSHKeySync` variable if the `InstallSSHKey` is `nil` ([reference](https://github.com/kubernetes/kubernetes/blob/v1.5.1/pkg/genericapiserver/tunneler.go#L164)). Now, because I haven't set up a cloud provider `InstallSSHKey` always is `nil` ([reference](https://github.com/kubernetes/kubernetes/blob/v1.5.1/cmd/kube-apiserver/app/server.go#L113)), therefore the SSHKey sync check fails.

**What you expected to happen**:
The SSHKey sync check shouldn't fail the tunneler health check if ssh keys won't be installed.

**How to reproduce it** (as minimally and precisely as possible):
Set up kube-apiserver with SSH key and SSH user but w/o a cloud provider. Connect nodes to the apiserver. Observe high failure rates.

**Anything else do we need to know**:
This is my command for the kube-apiserver:
```
"command": [
  "/usr/local/bin/kube-apiserver",
  "--v=4",
  "--insecure-bind-address=127.0.0.1",
  "--etcd-servers=http://127.0.0.1:2379",
  "--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota",
  "--service-cluster-ip-range=100.64.0.0/12",
  "--service-account-key-file=/etc/kubernetes/pki/apiserver-key.pem",
  "--ssh-keyfile=/etc/kubernetes/kube.id_rsa",
  "--ssh-user=kube",
  "--client-ca-file=/etc/kubernetes/pki/ca.pem",
  "--tls-cert-file=/etc/kubernetes/pki/apiserver.pem",
  "--tls-private-key-file=/etc/kubernetes/pki/apiserver-key.pem",
  "--token-auth-file=/etc/kubernetes/pki/tokens.csv",
  "--secure-port=6443",
  "--allow-privileged",
  "--etcd-servers=http://127.0.0.1:2379"
]
```

**Comment by gabarmas** [comment]
Hi. I am getting the exact same issue, using v1.5.3
Were you able to make it work?

**Comment by normanrz** [comment]
I solved my issue by not using ssh tunnels anymore. Now, I use `kubelet` authentication/authorization for secure comms between apiserver and nodes. https://kubernetes.io/docs/admin/kubelet-authentication-authorization/

**Comment by dove-young** [comment]
I've got the same issue at v1.5.5. 

I workaround this issue by replace kube-apiserver generated private key with my own ssh private key.  And deploy my own ssh public key by myself.

**Comment by roberthbailey** [comment]
It sounds like both @normanrz and @dove-young were able to resolve their respective issues, so I'm going to close this issue.
