### ISSUE TITLE
kube-proxy panic on restarting.

### ISSUE THREAD

**Issue by octete** [kubernetes/kubernetes#40590]
Hi,

I am running a k8s cluster in GKE (among others) that has gotten into a broken state where kube-proxy panics and keeps restarting. I have asked on slack and also searched here for 'kube-proxy panic' but have not found anything similar to this problem. I have even raised a ticket with google but have not got anywhere. I feels to me like a bug in kubernetes-proxy that might be related to invalid input or something. Please feel free to close this ticket if you think there's a duplicate I haven't seen or if this shouldn't be raised here.

I don't know how to further debug this issue, so any pointers to extract more information would be appreciated.

I'll start with the version:
```
» kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.8", GitCommit:"c5fcb1951afb8150e4574bc234aed957cb586eb0", GitTreeState:"clean", BuildDate:"2017-01-12T02:14:29Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

The pods in kube-system are:
```
» kubectl get pods  --namespace=kube-system
NAME                                                           READY     STATUS             RESTARTS   AGE
fluentd-cloud-logging-gke-go-misc-default-pool-84e90b98-0jps   1/1       Running            0          21h
fluentd-cloud-logging-gke-go-misc-default-pool-84e90b98-4jna   1/1       Running            0          21h
fluentd-cloud-logging-gke-go-misc-default-pool-84e90b98-xh7g   1/1       Running            0          21h
heapster-v1.2.0-4114705363-zg35b                               2/2       Running            0          21h
kube-dns-v20-szu6w                                             1/3       CrashLoopBackOff   607        21h
kube-dns-v20-xtcmm                                             1/3       CrashLoopBackOff   622        21h
kube-proxy-gke-go-misc-default-pool-84e90b98-0jps              0/1       Error              253        15m
kube-proxy-gke-go-misc-default-pool-84e90b98-4jna              0/1       CrashLoopBackOff   252        21h
kube-proxy-gke-go-misc-default-pool-84e90b98-xh7g              0/1       CrashLoopBackOff   252        21h
kubernetes-dashboard-v1.4.0-hqki7                              0/1       CrashLoopBackOff   253        21h
l7-default-backend-v1.0-bybpx                                  1/1       Running            0          21h
```

As you can see, `kube-dns` is also failing.

The logs from `kube-proxy` are extracted from `/var/log/kube-proxy.log` and consist of:
```
I0127 11:31:00.585035       5 proxier.go:434] Adding new service "kube-system/kubernetes-dashboard:" at 10.55.245.136:80/TCP
I0127 11:31:00.585102       5 proxier.go:434] Adding new service "default/mona:" at 10.55.243.217:80/TCP
I0127 11:31:00.585266       5 proxier.go:434] Adding new service "kube-system/default-http-backend:http" at 10.55.247.194:80/TCP
I0127 11:31:00.585328       5 proxier.go:434] Adding new service "kube-system/heapster:" at 10.55.242.100:80/TCP
I0127 11:31:00.585416       5 proxier.go:434] Adding new service "kube-system/kube-dns:dns" at 10.55.240.10:53/UDP
I0127 11:31:00.585536       5 proxier.go:434] Adding new service "kube-system/kube-dns:dns-tcp" at 10.55.240.10:53/TCP
I0127 11:31:00.585618       5 proxier.go:434] Adding new service "default/deployer-reporter:" at 10.55.254.70:80/TCP
I0127 11:31:00.585789       5 proxier.go:758] Not syncing iptables until Services and Endpoints have been received from master
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x526dc2]

goroutine 36 [running]:
panic(0x2090940, 0xc820012060)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
net.networkNumberAndMask(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/ip.go:433 +0x42
net.(*IPNet).Contains(0x0, 0xc820181d00, 0x10, 0x10, 0x0)
        /usr/local/go/src/net/ip.go:457 +0x25
k8s.io/kubernetes/pkg/proxy/iptables.(*Proxier).syncProxyRules(0xc8204905a0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go:1028 +0xa95c
k8s.io/kubernetes/pkg/proxy/iptables.(*Proxier).OnEndpointsUpdate(0xc8204905a0, 0xc82031f600, 0xa, 0x10)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go:597 +0x153b
k8s.io/kubernetes/pkg/proxy/config.(*EndpointsConfig).RegisterHandler.func1(0x1bc7b00, 0xc8204cc100)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:100 +0xdc
k8s.io/kubernetes/pkg/util/config.ListenerFunc.OnUpdate(0xc8202237e0, 0x1bc7b00, 0xc8204cc100)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/config/config.go:110 +0x30
k8s.io/kubernetes/pkg/util/config.(*Broadcaster).Notify(0xc820382fc0, 0x1bc7b00, 0xc8204cc100)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/config/config.go:138 +0xf8
k8s.io/kubernetes/pkg/proxy/config.watchForUpdates(0xc820382fc0, 0x7f12b24ee070, 0xc820382f30, 0xc8203bb680)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:297 +0x76
created by k8s.io/kubernetes/pkg/proxy/config.NewEndpointsConfig
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:93 +0x248
Flag --resource-container has been deprecated, This feature will be removed in a later release.
I0127 11:36:11.549654       5 iptables.go:176] Could not connect to D-Bus system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
I0127 11:36:11.549711       5 server.go:156] setting OOM scores is unsupported in this build
I0127 11:36:11.580385       5 server.go:203] Using iptables Proxier.
I0127 11:36:11.585768       5 server.go:215] Tearing down userspace rules.
I0127 11:36:11.592542       5 healthcheck.go:119] Initializing kube-proxy health checker
I0127 11:36:11.611125       5 conntrack.go:81] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
I0127 11:36:11.611507       5 conntrack.go:66] Setting conntrack hashsize to 32768
I0127 11:36:11.611768       5 conntrack.go:81] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
I0127 11:36:11.611788       5 conntrack.go:81] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
I0127 11:36:11.614262       5 proxier.go:434] Adding new service "kube-system/kube-dns:dns" at 10.55.240.10:53/UDP
I0127 11:36:11.614381       5 proxier.go:434] Adding new service "kube-system/kube-dns:dns-tcp" at 10.55.240.10:53/TCP
I0127 11:36:11.614442       5 proxier.go:434] Adding new service "kube-system/kubernetes-dashboard:" at 10.55.245.136:80/TCP
I0127 11:36:11.614477       5 proxier.go:434] Adding new service "default/mona:" at 10.55.243.217:80/TCP
I0127 11:36:11.614560       5 proxier.go:434] Adding new service "default/kubernetes:https" at 10.55.240.1:443/TCP
I0127 11:36:11.614590       5 proxier.go:434] Adding new service "default/deployer-reporter:" at 10.55.254.70:80/TCP
I0127 11:36:11.614653       5 proxier.go:434] Adding new service "kube-system/default-http-backend:http" at 10.55.247.194:80/TCP
I0127 11:36:11.614682       5 proxier.go:434] Adding new service "kube-system/heapster:" at 10.55.242.100:80/TCP
I0127 11:36:11.614725       5 proxier.go:758] Not syncing iptables until Services and Endpoints have been received from master
I0127 11:36:11.625561       5 proxier.go:1321] Opened local port "nodePort for default/mona:" (:31375/tcp)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x526dc2]

goroutine 36 [running]:
panic(0x2090940, 0xc820012060)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
net.networkNumberAndMask(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/ip.go:433 +0x42
net.(*IPNet).Contains(0x0, 0xc82017fd40, 0x10, 0x10, 0x0)
        /usr/local/go/src/net/ip.go:457 +0x25
k8s.io/kubernetes/pkg/proxy/iptables.(*Proxier).syncProxyRules(0xc820494820)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go:1028 +0xa95c
k8s.io/kubernetes/pkg/proxy/iptables.(*Proxier).OnEndpointsUpdate(0xc820494820, 0xc82031d600, 0xa, 0x10)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go:597 +0x153b
k8s.io/kubernetes/pkg/proxy/config.(*EndpointsConfig).RegisterHandler.func1(0x1bc7b00, 0xc8204d6300)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:100 +0xdc
k8s.io/kubernetes/pkg/util/config.ListenerFunc.OnUpdate(0xc820225820, 0x1bc7b00, 0xc8204d6300)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/config/config.go:110 +0x30
k8s.io/kubernetes/pkg/util/config.(*Broadcaster).Notify(0xc8203c4fc0, 0x1bc7b00, 0xc8204d6300)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/config/config.go:138 +0xf8
k8s.io/kubernetes/pkg/proxy/config.watchForUpdates(0xc8203c4fc0, 0x7fdc594a2070, 0xc8203c4f30, 0xc8203bb620)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:297 +0x76
created by k8s.io/kubernetes/pkg/proxy/config.NewEndpointsConfig
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:93 +0x248
```

**Environment**:
- **Cloud provider**: Google Container Engine. Runs version 1.4.8, which I think it's the latest.
- **OS** (e.g. from /etc/os-release):
```
cat /etc/os-release
BUILD_ID=8872.47.0
NAME="Container-VM Image"
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=55
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Google Container-VM Image"
VERSION=55
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=gci
```
- **Kernel** (e.g. `uname -a`): `Linux gke-go-misc-default-pool-84e90b98-0jps 4.4.21+ #1 SMP Thu Nov 10 21:43:53 PST 2016 x86_64 Intel(R) Xeon(R) CPU @ 2.60GHz GenuineIntel GNU/Linux`
- **Install tools**: Client version runs on Mac OS Sierra.

**What happened**:
Not entirely sure what happened. I was adding a new service when I started noticing that it was not working. I noticed that there were no iptables rules to route to this new service.

**How to reproduce it**:
Unsure. I would like to know any tips on how to extract more information.

Let me know if you need anything else I Can help with.

Thank you.

**Comment by dcbw** [comment]
```
					for _, src := range svcInfo.loadBalancerSourceRanges {
						writeLine(natRules, append(args, "-s", src, "-j", string(chosenChain))...)
						// ignore error because it has been validated
						_, cidr, _ := net.ParseCIDR(src)
---->						if cidr.Contains(proxier.nodeIP) {
							allowFromNode = true
						}
					}

```

which seems to be due to `cidr` being nil, which means that something is writing invalid IP addresses to the loadBalancerSourceRanges.

**Comment by dcbw** [comment]
Which is odd, because loadBalancerSourceRanges should be validated by the apiserver... if you get this issue again, could you 'kubectl describe' the service and paste in the results?

**Comment by thockin** [comment]
I'm going to close for now - please reopen if you can repro!!

**Comment by blemagicleap** [comment]
What's the solution?

**Comment by octete** [comment]
@blemagicleap I don't know. Google updated their version, and it probably got fixed in the migration.
