### ISSUE TITLE
Default service account tokens deleted in all namespaces after apiserver crash

### ISSUE THREAD

**Issue by GnawNom** [kubernetes/kubernetes#40754]
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.9-ee10669", GitCommit:"ee10669e21109f86c21e8f7ceb1187d7910fe120", GitTreeState:"clean", BuildDate:"2016-10-26T17:13:55Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.9", GitCommit:"ee10669e21109f86c21e8f7ceb1187d7910fe120", GitTreeState:"clean", BuildDate:"2016-10-20T20:37:18Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Baremetal @ Box
- **OS** (e.g. from /etc/os-release): ScientificLinux 6
- **Kernel** (e.g. `uname -a`): `Linux compute-master1001.ve.box.net 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 05:09:55 CDT 2015 x86_64 x86_64 x86_64 GNU/Linux
`
- **Install tools**:
- **Others**:

**What happened**:
Following a series of apiserver crashes, controller-manager deleted all default service account tokens. A subset of pods were deleted too, but they came back up in a wedged state because the pods still referenced old, deleted service account tokens.

Apiserver crash:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x1a7727a]
 
goroutine 1844215 [running]:
panic(0x3275920, 0xc820014070)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
container/list.(*List).MoveToFront(0xc820867980, 0xc86fc18c60)
        /usr/local/go/src/container/list/list.go:169 +0x22a
k8s.io/kubernetes/vendor/github.com/golang/groupcache/lru.(*Cache).Get(0xc82087f380, 0x294b100, 0xc84ee366f0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/groupcache/lru/lru.go:79 +0xa4
k8s.io/kubernetes/pkg/util/cache.(*LRUExpireCache).Get(0xc82087f3a0, 0x294b100, 0xc84ee366f0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/cache/lruexpirecache.go:51 +0xb7
k8s.io/kubernetes/plugin/pkg/auth/authorizer/webhook.(*WebhookAuthorizer).Authorize(0xc82087f3c0, 0x7f4e78f47218, 0xc8508283c0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/auth/authorizer/webhook/webhook.go:156 +0x543
k8s.io/kubernetes/pkg/auth/authorizer/union.unionAuthzHandler.Authorize(0xc82086cf20, 0x2, 0x2, 0x7f4e78f47218, 0xc8508283c0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/auth/authorizer/union/union.go:36 +0xf2
k8s.io/kubernetes/pkg/auth/authorizer/union.(*unionAuthzHandler).Authorize(0xc82086cf40, 0x7f4e78f47218, 0xc8508283c0, 0x0, 0x0)
        <autogenerated>:1 +0xc1
k8s.io/kubernetes/pkg/apiserver.WithAuthorizationCheck.func1(0x7f4e78f47130, 0xc8336a3040, 0xc85f57f960)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:484 +0x9f
net/http.HandlerFunc.ServeHTTP(0xc82086ac40, 0x7f4e78f47130, 0xc8336a3040, 0xc85f57f960)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/apiserver.WithImpersonation.func1(0x7f4e78f47130, 0xc8336a3040, 0xc85f57f960)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:421 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc82086acc0, 0x7f4e78f47130, 0xc8336a3040, 0xc85f57f960)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/auth/handlers.NewRequestAuthenticator.func1(0x7f4e78f47130, 0xc8336a3040, 0xc85f57f960)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/auth/handlers/handlers.go:70 +0x2f3
net/http.HandlerFunc.ServeHTTP(0xc8202ad860, 0x7f4e78f47130, 0xc8336a3040, 0xc85f57f960)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/api.NewRequestContextFilter.func1(0x7f4e78f47130, 0xc8336a3040, 0xc85f57f960)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101 +0x157
net/http.HandlerFunc.ServeHTTP(0xc82086df80, 0x7f4e78f47130, 0xc8336a3040, 0xc85f57f960)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/api.NewRequestContextFilter.func1(0x7f4e78f47130, 0xc8336a3040, 0xc85f57f960)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101 +0x157
net/http.HandlerFunc.ServeHTTP(0xc82086dfa0, 0x7f4e78f47130, 0xc8336a3040, 0xc85f57f960)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/apiserver.(*timeoutHandler).ServeHTTP.func1(0xc821e91ac0, 0x7f4e78f470f0, 0xc8336a3040, 0xc85f57f960, 0xc85056df20)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:195 +0x91
created by k8s.io/kubernetes/pkg/apiserver.(*timeoutHandler).ServeHTTP
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:197 +0x15b

```
Token deletion:
```
...
I0108 16:03:29.371250      21 handlers.go:165] DELETE /api/v1/namespaces/workflow-worker-staging/secrets/default-token-797ic: (24.258346ms) 200 [[hyperkube/v1.3.9 (linux/amd64) kubernetes/ee10669/tokens-controller] 127.0.0.1:49818]
I0108 16:03:29.389383      21 handlers.go:165] DELETE /api/v1/namespaces/webhooks-worker-staging/secrets/default-token-quowk: (11.635732ms) 200 [[hyperkube/v1.3.9 (linux/amd64) kubernetes/ee10669/tokens-controller] 127.0.0.1:49818]
I0108 16:03:29.417469      21 handlers.go:165] DELETE /api/v1/namespaces/sops-dev/secrets/default-token-4f047: (23.941188ms) 200 [[hyperkube/v1.3.9 (linux/amd64) kubernetes/ee10669/tokens-controller] 127.0.0.1:49818]
I0108 16:03:29.500691      21 handlers.go:165] DELETE /api/v1/namespaces/user-preferences-dev/secrets/default-token-iwine: (17.127462ms) 200 [[hyperkube/v1.3.9 (linux/amd64) kubernetes/ee10669/tokens-controller] 127.0.0.1:49818]
I0108 16:03:29.527143      21 handlers.go:165] DELETE /api/v1/namespaces/recents-worker-staging/secrets/default-token-4xa3d: (12.412173ms) 200 [[hyperkube/v1.3.9 (linux/amd64) kubernetes/ee10669/tokens-controller] 127.0.0.1:49818]
I0108 16:03:29.541986      21 handlers.go:165] DELETE /api/v1/namespaces/shovel-to-mqs-staging/secrets/default-token-vn0ua: (10.434432ms) 200 [[hyperkube/v1.3.9 (linux/amd64) kubernetes/ee10669/tokens-controller] 127.0.0.1:49818]
I0108 16:03:29.561008      21 handlers.go:165] DELETE /api/v1/namespaces/alf-chunk-dispatch-dev/secrets/default-token-f9iz8: (11.456524ms) 200 [[hyperkube/v1.3.9 (linux/amd64) kubernetes/ee10669/tokens-controller] 127.0.0.1:49818]
...
```
Filtering for requests against a specific namespace (alf-firehose-dispatch-staging), we see a 404 on a GET to the default service account, followed by a DELETE on the token:
```
I0108 19:45:47.294634      24 handlers.go:165] GET /api/v1/namespaces/alf-firehose-dispatch-staging/secrets/default-token-i1r7t: (3.100726ms) 200 [[kubelet/v1.3.9 (linux/amd64) kubernetes/ee10669] 10.3.89.181:48011]
I0108 19:45:47.651141      24 handlers.go:165] GET /api/v1/namespaces/alf-firehose-dispatch-staging/serviceaccounts/default: (30.523032ms) 404 [[hyperkube/v1.3.9 (linux/amd64) kubernetes/ee10669/tokens-controller] 127.0.0.1:42530]
I0108 19:45:47.654145      24 handlers.go:165] GET /api/v1/namespaces/alf-firehose-dispatch-staging: (2.03876ms) 200 [[hyperkube/v1.3.9 (linux/amd64) kubernetes/ee10669] 127.0.0.1:42607]
I0108 19:45:47.673030      24 handlers.go:165] DELETE /api/v1/namespaces/alf-firehose-dispatch-staging/secrets/default-token-i1r7t: (21.277306ms) 200 [[hyperkube/v1.3.9 (linux/amd64) kubernetes/ee10669/tokens-controller] 127.0.0.1:42530]
I0108 19:45:48.120852      24 handlers.go:165] POST /api/v1/namespaces/alf-firehose-dispatch-staging/events: (14.628513ms) 201 [[kubelet/v1.3.9 (linux/amd64) kubernetes/ee10669] 10.3.89.182:57087]
I0108 19:45:48.608443      24 handlers.go:165] POST /api/v1/namespaces/alf-firehose-dispatch-staging/events: (19.827168ms) 201 [[kubelet/v1.3.9 (linux/amd64) kubernetes/ee10669] 10.3.89.190:54170]
I0108 19:45:48.812999      24 handlers.go:165] POST /api/v1/namespaces/alf-firehose-dispatch-staging/events: (24.551706ms) 201 [[kubelet/v1.3.9 (linux/amd64) kubernetes/ee10669] 10.3.89.190:54170]
I0108 19:45:49.294552      24 handlers.go:165] GET /api/v1/namespaces/alf-firehose-dispatch-staging/configmaps/hekad-config-map-db2677748d7378117b6ba5dec6021981: (3.056265ms) 200 [[kubelet/v1.3.9 (linux/amd64) kubernetes/ee10669] 10.3.89.181:48109]
I0108 19:45:49.454880      24 handlers.go:165] DELETE /api/v1/namespaces/alf-firehose-dispatch-staging/endpoints/app: (9.45938ms) 200 [[hyperkube/v1.3.9 (linux/amd64) kubernetes/ee10669/endpoint-controller] 127.0.0.1:42922]
```

**What you expected to happen**:
We expected our tokens to persist after apiserver restarts and crashes.

**How to reproduce it** (as minimally and precisely as possible):
We were unable to reproduce it by forcing apiserver restarts, but the problem has not resurfaced after disabling the webhooks authorizer plugin which was triggering the periodic apiserver crashes.

**Anything else do we need to know**:
Our apiserver had been crashing for several weeks due to the webhooks authorizer plugin without triggering this issue, so there is likely something else triggering this delete spree apart from the apiserver panics.

@huggsboson @ahakanbaba @ghodss @jbeda

**Comment by GnawNom** [comment]
```
I0108 16:42:47.640623      21 tokens_controller.go:232] Deleting updated secret alf-checker-staging/default-token-qve6r because service account default (uid=9aec9159-bc06-11e6-8619-c81f66ba8f07) was not found
I0108 16:42:47.656064      21 tokens_controller.go:232] Deleting updated secret alf-fanout-stream-dev/default-token-7khcw because service account default (uid=fa5575d4-9cb4-11e6-902b-0242ca764737) was not found
I0108 16:42:47.669823      21 tokens_controller.go:232] Deleting updated secret job-manager-staging/default-token-wp6jl because service account default (uid=ed228d28-081b-11e6-9d0e-c81f66ba89b3) was not found
I0108 16:42:47.811191      21 tokens_controller.go:232] Deleting updated secret shovel-to-mqs-dev/default-token-bw8fl because service account default (uid=433066af-bcc9-11e6-8697-c81f66ba89b3) was not found
I0108 16:42:47.877815      21 tokens_controller.go:232] Deleting updated secret metadata-reindex-worker-staging/default-token-fx9ac because service account default (uid=e4940146-84d2-11e6-902b-0242ca764737) was not found
I0108 16:42:48.016649      21 tokens_controller.go:232] Deleting updated secret mqs-staging/default-token-sv1ee because service account default (uid=bac78178-08fb-11e6-a499-c81f66ba86f7) was not found
I0108 16:42:48.109037      21 tokens_controller.go:232] Deleting updated secret webhooks-worker-staging/default-token-h2v97 because service account default (uid=3530682f-bcc0-11e6-8697-c81f66ba89b3) was not found
```

**Comment by liggitt** [comment]
does that service account with that uid still exist?

**Comment by GnawNom** [comment]
Yep, same uid.
```
[joewang@compute-master02.dev ~]$ kubectl get serviceaccount default --namespace=kube-system default  -o json
{
    "kind": "List",
    "apiVersion": "v1",
    "metadata": {},
    "items": [
        {
            "kind": "ServiceAccount",
            "apiVersion": "v1",
            "metadata": {
                "name": "default",
                "namespace": "kube-system",
                "selfLink": "/api/v1/namespaces/kube-system/serviceaccounts/default",
                "uid": "735dfc3e-f84d-11e5-abb4-c81f66ba8f07",
                "resourceVersion": "177503484",
                "creationTimestamp": "2016-04-01T21:05:23Z"
            },
            "secrets": [
                {
                    "name": "default-token-zavhz"
                },
                {
                    "name": "default-token-dz1s5"
                },
                {
                    "name": "default-token-meuoe"
                },
                {
                    "name": "default-token-soh4y"
                },
                {
                    "name": "default-token-oevt8"
                }
            ]
        },
        {
            "kind": "ServiceAccount",
            "apiVersion": "v1",
            "metadata": {
                "name": "default",
                "namespace": "kube-system",
                "selfLink": "/api/v1/namespaces/kube-system/serviceaccounts/default",
                "uid": "735dfc3e-f84d-11e5-abb4-c81f66ba8f07",
                "resourceVersion": "177503484",
                "creationTimestamp": "2016-04-01T21:05:23Z"
            },
            "secrets": [
                {
                    "name": "default-token-zavhz"
                },
                {
                    "name": "default-token-dz1s5"
                },
                {
                    "name": "default-token-meuoe"
                },
                {
                    "name": "default-token-soh4y"
                },
                {
                    "name": "default-token-oevt8"
                }
            ]
        }
    ]
}
```

**Comment by liggitt** [comment]
> we see a 404 on a GET to the default service account, followed by a DELETE on the token

are you running HA etcd?

**Comment by huggsboson** [comment]
yes.  We have 3 etcd servers and 2 masters (behind a keepalived'd vip).

**Comment by huggsboson** [comment]
The apiservers were crashing due to a known bug in the cache.

**Comment by liggitt** [comment]
is this still an issue? are you running your apiserver with `--etcd-quorum-read` on?
