### ISSUE TITLE
Cassandra example rc failure 

### ISSUE THREAD

**Issue by liggetm** [kubernetes/kubernetes#40872]
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"87d9d8d7bc5aa35041a8ddfe3d4b367381112f89", GitTreeState:"clean", BuildDate:"2017-01-23T14:15:25Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"87d9d8d7bc5aa35041a8ddfe3d4b367381112f89", GitTreeState:"clean", BuildDate:"2017-01-23T14:15:25Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
Bare metal install on various HP and Dell hardware
- **OS** (e.g. from /etc/os-release):
Latest CentOS 7 (identical error on CentOS Atomic Host 7 20161006)
- **Kernel** (e.g. `uname -a`):
Linux 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:
via RPM:
kubernetes-master-1.4.0-0.1.git87d9d8d.el7.x86_64
kubernetes-node-1.4.0-0.1.git87d9d8d.el7.x86_64
kubernetes-client-1.4.0-0.1.git87d9d8d.el7.x86_64

- **Others**:
Cassandra example taken from current master branch

**What happened**:
Cassandra pods bootstrap before eventually shutting down after a RuntimeException (pasted below).

**What you expected to happen**:
The Cassandra example to happily run in the cluster.

**How to reproduce it** (as minimally and precisely as possible):
Install Kubernetes and configure in-cluster DNS and service account tokens.
Create the headless Cassandra services in the example (step 1)
Create the Cassandra replication controller in the example (step 5)

**Anything else we need to know**:
Relevant log snippet...
```
WARN  18:12:43 Seeds are not available using default seeds in cassandra.yaml
INFO  18:13:14 Getting endpoints from https://10.254.0.1:443/api/v1/namespaces/default/endpoints/cassandra
INFO  18:13:14 Available num endpoints: 0
WARN  18:13:14 Seeds are not available using default seeds in cassandra.yaml
Exception (java.lang.RuntimeException) encountered during startup: Unable to gossip with any seeds
java.lang.RuntimeException: Unable to gossip with any seeds
	at org.apache.cassandra.gms.Gossiper.doShadowRound(Gossiper.java:1386)
	at org.apache.cassandra.service.StorageService.checkForEndpointCollision(StorageService.java:484)
	at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:778)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:648)
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:548)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:385)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:601)
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:730)
ERROR 18:13:14 Exception encountered during startup
java.lang.RuntimeException: Unable to gossip with any seeds
	at org.apache.cassandra.gms.Gossiper.doShadowRound(Gossiper.java:1386) ~[apache-cassandra-3.9.jar:3.9]
	at org.apache.cassandra.service.StorageService.checkForEndpointCollision(StorageService.java:484) ~[apache-cassandra-3.9.jar:3.9]
	at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:778) ~[apache-cassandra-3.9.jar:3.9]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:648) ~[apache-cassandra-3.9.jar:3.9]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:548) ~[apache-cassandra-3.9.jar:3.9]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:385) [apache-cassandra-3.9.jar:3.9]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:601) [apache-cassandra-3.9.jar:3.9]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:730) [apache-cassandra-3.9.jar:3.9]
WARN  18:13:14 No local state or state is in silent shutdown, not announcing shutdown
INFO  18:13:14 Waiting for messaging service to quiesce
INFO  18:13:14 MessagingService has terminated the accept() thread
INFO  18:13:14 Paused hints dispatch
INFO  18:13:14 Paused hints dispatch
```

Env settings:
```
Starting Cassandra on 172.17.0.2
CASSANDRA_CONF_DIR /etc/cassandra
CASSANDRA_CFG /etc/cassandra/cassandra.yaml
CASSANDRA_AUTO_BOOTSTRAP true
CASSANDRA_BROADCAST_ADDRESS 172.17.0.2
CASSANDRA_BROADCAST_RPC_ADDRESS 172.17.0.2
CASSANDRA_CLUSTER_NAME 'Test Cluster'
CASSANDRA_COMPACTION_THROUGHPUT_MB_PER_SEC
CASSANDRA_CONCURRENT_COMPACTORS
CASSANDRA_CONCURRENT_READS
CASSANDRA_CONCURRENT_WRITES
CASSANDRA_COUNTER_CACHE_SIZE_IN_MB
CASSANDRA_DC
CASSANDRA_DISK_OPTIMIZATION_STRATEGY ssd
CASSANDRA_ENDPOINT_SNITCH SimpleSnitch
CASSANDRA_GC_WARN_THRESHOLD_IN_MS
CASSANDRA_INTERNODE_COMPRESSION
CASSANDRA_KEY_CACHE_SIZE_IN_MB
CASSANDRA_LISTEN_ADDRESS 172.17.0.2
CASSANDRA_LISTEN_INTERFACE
CASSANDRA_MEMTABLE_ALLOCATION_TYPE
CASSANDRA_MEMTABLE_CLEANUP_THRESHOLD
CASSANDRA_MEMTABLE_FLUSH_WRITERS
CASSANDRA_MIGRATION_WAIT 1
CASSANDRA_NUM_TOKENS 32
CASSANDRA_RACK
CASSANDRA_RING_DELAY 30000
CASSANDRA_RPC_ADDRESS 0.0.0.0
CASSANDRA_RPC_INTERFACE
CASSANDRA_SEEDS
CASSANDRA_SEED_PROVIDER io.k8s.cassandra.KubernetesSeedProvider
```

**Comment by chrislovecnm** [comment]
I would encourage you to use Pet Set example.  Otherwise, we have a bug in the start script.

**Comment by liggetm** [comment]
Thanks @chrislovecnm.  I was running version 1.2 so I didn't have Pet Sets.  I appreciate that this is not causing any issue in the real-world and the example docs have since been updated.  Feel free to close if you agree it's not worth spending time on.

**Comment by chrislovecnm** [comment]
@liggetm don't have perms to close the issue.  Please self-close

**Comment by liggetm** [comment]
@chrislovecnm No problem, thanks again for your help on this.

**Comment by kumarganesh2814** [comment]
@liggetm @chrislovecnm 

Hi 
I am folowinf same example from 
https://kubernetes.io/docs/tutorials/stateful-application/cassandra/

Getting exact same error here 

```

INFO  17:50:21 Starting Messaging Service on /10.244.1.37:7000 (eth0)
WARN  17:50:21 No host ID found, created 7ffe85b4-eef6-4274-9461-821d538c1181 (Note: This should happen exactly once per node).
Exception (java.lang.RuntimeException) encountered during startup: Unable to gossip with any seeds
java.lang.RuntimeException: Unable to gossip with any seeds
        at org.apache.cassandra.gms.Gossiper.doShadowRound(Gossiper.java:1386)
        at org.apache.cassandra.service.StorageService.checkForEndpointCollision(StorageService.java:484)
        at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:778)
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:648)
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:548)
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:385)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:601)
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:730)
ERROR 17:50:53 Exception encountered during startup
java.lang.RuntimeException: Unable to gossip with any seeds
        at org.apache.cassandra.gms.Gossiper.doShadowRound(Gossiper.java:1386) ~[apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.StorageService.checkForEndpointCollision(StorageService.java:484) ~[apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:778) ~[apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:648) ~[apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.StorageService.initServer(StorageService.java:548) ~[apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:385) [apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:601) [apache-cassandra-3.9.jar:3.9]
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:730) [apache-cassandra-3.9.jar:3.9]
WARN  17:50:53 No local state or state is in silent shutdown, not announcing shutdown
```

Can you please help what I need to chage in yaml from provided on Example 

Even my platform is too centos 7
Using Flannel as network add on
1 Master 2 Mnion cluster on latest kubeadm 1.8.5 

Best Regards'
Ganesh
