### ISSUE TITLE
client: etcd cluster is unavailable or misconfigured

### ISSUE THREAD

**Issue by Phanindra48** [kubernetes/kubernetes#40997]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Hi,

I have been getting this error when trying to reach the kubernetes dashboard and this is happening few days after starting the cluster and slowly the frequency of crashes and unavailability of k8s dashboard time is also increasing.

Error message:
```
{
	"kind": "Status",
	"apiVersion": "v1",
	"metadata": {},
	"status": "Failure",
	"message": "client: etcd cluster is unavailable or misconfigured",
	"code": 500
}
```

Here is the log (snippet) that I got from etcd container k8s_etcd-container.fc80f341_etcd-server-events-ip-172-20-61-117.eu-central-1.compute.internal_kube-system_59da3ff0d3d20fb78afe7b5f9a9333bc_38757300 in this path `/var/log/etcd.log`

```
2017-02-01 05:50:25.076007 I | etcdserver: starting server... [version: 2.2.1, cluster version: 2.2]
2017-02-01 05:50:25.476159 I | raft: 64ee7ee04873811a is starting a new election at term 2769
2017-02-01 05:50:25.476244 I | raft: 64ee7ee04873811a became candidate at term 2770
2017-02-01 05:50:25.476253 I | raft: 64ee7ee04873811a received vote from 64ee7ee04873811a at term 2770
2017-02-01 05:50:25.476271 I | raft: 64ee7ee04873811a became leader at term 2770
2017-02-01 05:50:25.476297 I | raft: raft.node: 64ee7ee04873811a elected leader 64ee7ee04873811a at term 2770
2017-02-01 05:50:25.482216 I | etcdserver: published {Name:etcd-events-eu-central-1a ClientURLs:[http://etcd-events-eu-central-1a.internal.dev.logos.social:4002]} to cluster 853871caecae4c74
2017-02-01 06:02:38.987224 I | flags: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://etcd-events-master-eu-central-1a.internal.dev.logos.social:4002
2017-02-01 06:02:38.987273 I | flags: recognized and used environment variable ETCD_DATA_DIR=/var/etcd/data-events
2017-02-01 06:02:38.987309 I | flags: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-events-master-eu-central-1a.internal.dev.logos.social:2381
2017-02-01 06:02:38.987325 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER=etcd-events-master-eu-central-1a=http://etcd-events-master-eu-central-1a.internal.dev.logos.social:2381
2017-02-01 06:02:38.987332 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=new
2017-02-01 06:02:38.987337 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-token-etcd-events
2017-02-01 06:02:38.987345 I | flags: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:4002
2017-02-01 06:02:38.987352 I | flags: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2381
2017-02-01 06:02:38.987365 I | flags: recognized and used environment variable ETCD_NAME=etcd-events-master-eu-central-1a
2017-02-01 06:02:38.987469 I | etcdmain: etcd Version: 2.2.1
2017-02-01 06:02:38.987476 I | etcdmain: Git SHA: 75f8282
2017-02-01 06:02:38.987480 I | etcdmain: Go Version: go1.5.1
2017-02-01 06:02:38.987484 I | etcdmain: Go OS/Arch: linux/amd64
2017-02-01 06:02:38.987492 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
2017-02-01 06:02:38.987532 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2017-02-01 06:02:38.987591 I | etcdmain: listening for peers on http://0.0.0.0:2381
2017-02-01 06:02:38.987631 I | etcdmain: listening for client requests on http://0.0.0.0:4002
2017-02-01 06:02:39.071569 I | etcdserver: recovered store from snapshot at index 1510151
2017-02-01 06:02:39.071601 I | etcdserver: name = etcd-events-master-eu-central-1a
2017-02-01 06:02:39.071606 I | etcdserver: data dir = /var/etcd/data-events
2017-02-01 06:02:39.071612 I | etcdserver: member dir = /var/etcd/data-events/member
2017-02-01 06:02:39.071616 I | etcdserver: heartbeat = 100ms
2017-02-01 06:02:39.071620 I | etcdserver: election = 1000ms
2017-02-01 06:02:39.071624 I | etcdserver: snapshot count = 10000
2017-02-01 06:02:39.071638 I | etcdserver: advertise client URLs = http://etcd-events-master-eu-central-1a.internal.dev.logos.social:4002
2017-02-01 06:02:39.071660 I | etcdserver: loaded cluster information from store: <nil>
2017-02-01 06:02:39.381693 I | etcdserver: restarting member 64ee7ee04873811a in cluster 853871caecae4c74 at commit index 1515419
2017-02-01 06:02:39.381994 I | raft: 64ee7ee04873811a became follower at term 2770
2017-02-01 06:02:39.382010 I | raft: newRaft 64ee7ee04873811a [peers: [64ee7ee04873811a], term: 2770, commit: 1515419, applied: 1510151, lastindex: 1515419, lastterm: 2770]
2017-02-01 06:02:39.384152 I | etcdserver: starting server... [version: 2.2.1, cluster version: 2.2]
2017-02-01 06:02:39.784296 I | raft: 64ee7ee04873811a is starting a new election at term 2770
2017-02-01 06:02:39.784394 I | raft: 64ee7ee04873811a became candidate at term 2771
2017-02-01 06:02:39.784402 I | raft: 64ee7ee04873811a received vote from 64ee7ee04873811a at term 2771
2017-02-01 06:02:39.784434 I | raft: 64ee7ee04873811a became leader at term 2771
2017-02-01 06:02:39.784444 I | raft: raft.node: 64ee7ee04873811a elected leader 64ee7ee04873811a at term 2771
2017-02-01 06:02:39.786300 I | etcdserver: published {Name:etcd-events-master-eu-central-1a ClientURLs:[http://etcd-events-master-eu-central-1a.internal.dev.logos.social:4002]} to cluster 853871caecae4c74
2017-02-01 06:03:38.947298 I | flags: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://etcd-events-eu-central-1a.internal.dev.logos.social:4002
2017-02-01 06:03:38.947368 I | flags: recognized and used environment variable ETCD_DATA_DIR=/var/etcd/data-events
2017-02-01 06:03:38.947389 I | flags: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-events-eu-central-1a.internal.dev.logos.social:2381
2017-02-01 06:03:38.947396 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER=etcd-events-eu-central-1a=http://etcd-events-eu-central-1a.internal.dev.logos.social:2381
2017-02-01 06:03:38.947407 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=new
```
**Kubernetes version** (use `kubectl version`):
```
{
  "major": "1",
  "minor": "4",
  "gitVersion": "v1.4.7",
  "gitCommit": "92b4f971662de9d8770f8dcd2ee01ec226a6f6c0",
  "gitTreeState": "clean",
  "buildDate": "2016-12-10T04:43:42Z",
  "goVersion": "go1.6.3",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

**Environment**:
- **Cloud provider or hardware configuration**: `AWS`
- **OS** (e.g. from /etc/os-release): `Debian GNU/Linux 8 (jessie)`
- **Kernel** (e.g. `uname -a`): `Linux ip-172-20-61-117 4.4.26-k8s #1 SMP Fri Oct 21 05:21:13 UTC 2016 x86_64 GNU/Linux`
- **Install tools**: `kops`
- **Others**:

**What happened**:
Kubernetes api is not reachable.

**What you expected to happen**:
High availability of kubernetes api and dashboard

**How to reproduce it** (as minimally and precisely as possible):
Create a cluster using kops (https://github.com/kubernetes/kops/blob/master/docs/aws.md) 

**Anything else we need to know**:
Have 1 master(t2.small) and 2 nodes(t2.medium)

Please help in resolving the issue and also let me know if you need more info. 

Thanks,
Phanindra

**Comment by Phanindra48** [comment]
Logs from `/var/log/kube-apiserver.log`
```
logging error output: "k8s\x00\n\f\n\x02v1\x12\x06Status\x12J\n\x04\n\x00\x12\x00\x12\aFailure\x1a4client: etcd cluster is unavailable or misconfigured\"\x000\xf4\x03\x1a\x00\"\x00"
 [[kubelet/v1.4.8 (linux/amd64) kubernetes/c5fcb19] 172.20.60.32:34598]
E0214 11:49:52.259197       5 errors.go:63] apiserver received an error that is not an unversioned.Status: client: etcd cluster is unavailable or misconfigured
I0214 11:49:52.259304       5 handlers.go:162] PATCH /api/v1/namespaces/nginx-ingress/events/nginx-ingress-3555141209-mih9t.14a1fd5e7c528548: (544.484µs) 500
goroutine 26454094 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc825529570, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:219 +0xa3
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc825529570, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:198 +0x2b
k8s.io/kubernetes/pkg/apiserver/metrics.(*responseWriterDelegator).WriteHeader(0xc826b9d5c0, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:117 +0x4c
k8s.io/kubernetes/pkg/apiserver.writeNegotiated(0x7fc80379d7c0, 0xc8204dcd20, 0x0, 0x0, 0x3f04220, 0x2, 0x7fc8035bda40, 0xc830385050, 0xc821c8ea80, 0x1f4, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:492 +0x189
k8s.io/kubernetes/pkg/apiserver.errorNegotiated(0x7fc8035d1bb0, 0xc826796f20, 0x7fc80379d7c0, 0xc8204dcd20, 0x0, 0x0, 0x3f04220, 0x2, 0x7fc8035bda40, 0xc830385050, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:509 +0x1a9
k8s.io/kubernetes/pkg/apiserver.(*RequestScope).err(0xc820996540, 0x7fc8035d1bb0, 0xc826796f20, 0x7fc8035bda40, 0xc830385050, 0xc821c8ea80)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:87 +0x191
k8s.io/kubernetes/pkg/apiserver.PatchResource.func1(0xc826b9d530, 0xc82a91cc00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:505 +0xf2e
k8s.io/kubernetes/pkg/apiserver/metrics.InstrumentRouteFunc.func1(0xc826b9d530, 0xc82a91cc00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:101 +0x25f
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc820037170, 0x7fc8035bd958, 0xc825529570, 0xc821c8ea80)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:272 +0xf30
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x7fc8035bd958, 0xc825529570, 0xc821c8ea80)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc821054410, 0x7fc8035bd958, 0xc825529570, 0xc821c8ea80)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc82036e480, 0x7fc8035bd958, 0xc825529570, 0xc821c8ea80)
        /usr/local/go/src/net/http/server.go:1910 +0x17d
                                                                                                                                                                                          311633,1-8    99%
net/http.(*ServeMux).ServeHTTP(0xc82036e480, 0x7fc8035bd958, 0xc825529570, 0xc821c8ea80)
        /usr/local/go/src/net/http/server.go:1910 +0x17d
k8s.io/kubernetes/pkg/apiserver.WithAuthorizationCheck.func1(0x7fc8035bd958, 0xc825529570, 0xc821c8ea80)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:476 +0x36c
net/http.HandlerFunc.ServeHTTP(0xc8202cf340, 0x7fc8035bd958, 0xc825529570, 0xc821c8ea80)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/apiserver.WithImpersonation.func1(0x7fc8035bd958, 0xc825529570, 0xc821c8ea80)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handler_impersonation.go:44 +0x2b4
net/http.HandlerFunc.ServeHTTP(0xc8202cf380, 0x7fc8035bd958, 0xc825529570, 0xc821c8ea80)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/auth/handlers.NewRequestAuthenticator.func1(0x7fc8035bd958, 0xc825529570, 0xc821c8ea80)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/auth/handlers/handlers.go:70 +0x2f3
net/http.HandlerFunc.ServeHTTP(0xc8205d6780, 0x7fc8035bd958, 0xc825529570, 0xc821c8ea80)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/api.NewRequestContextFilter.func1(0x7fc8035bd958, 0xc825529570, 0xc821c8ea80)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101 +0x157
net/http.HandlerFunc.ServeHTTP(0xc8202bee20, 0x7fc8035bd958, 0xc825529570, 0xc821c8ea80)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/api.NewRequestContextFilter.func1(0x7fc8035bd958, 0xc825529570, 0xc821c8ea80)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101 +0x157
net/http.HandlerFunc.ServeHTTP(0xc8202bee40, 0x7fc8035bd958, 0xc825529570, 0xc821c8ea80)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/apiserver.RecoverPanics.func1(0x7fc8035bd958, 0xc825529570, 0xc821c8ea80)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:161 +0x1f3
net/http.HandlerFunc.ServeHTTP(0xc821972440, 0x7fc8035bd920, 0xc830385040, 0xc821c8ea80)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/apiserver.(*timeoutHandler).ServeHTTP.func1(0xc821972460, 0x7fc8035bd8e0, 0xc830385040, 0xc821c8ea80, 0xc82a91c9c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:194 +0x8d
created by k8s.io/kubernetes/pkg/apiserver.(*timeoutHandler).ServeHTTP
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:196 +0x15b```

**Comment by spiffxp** [comment]
/sig aws
since this references kops

**Comment by vladkras** [comment]
Same problem on fresh install of Kubernetes on Ubuntu 16 using snap and juju https://jujucharms.com/kubernetes-core/

Dashboard worked fine a couple of days, but when I returned a week later I've got
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 10.212.16.210:2379: getsockopt: connection refused\n",
  "code": 500
}
```
on /api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
