### ISSUE TITLE
scheduler_perf cant match nodes.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#41171]
**What keywords did you search in Kubernetes issues before filing this one?** 
scheduler_perf.
**Is this a BUG REPORT or FEATURE REQUEST?**
Bug
**Kubernetes version** (use `kubectl version`): 
Master

Looks like perf test is broke. I'll dig into the details.  

```
test/integration/scheduler_perf/test-performance.sh
```

Leads to 

```
goroutine 23494242 [sleep]:
time.Sleep(0x1dcd65000)
        /root/.gimme/versions/go1.7.4.linux.amd64/src/runtime/time.go:59 +0xe1
k8s.io/kubernetes/plugin/pkg/scheduler/util.(*backoffEntry).wait(0xc4297df770, 0xdf8475800)
        /root/Dropbox/jayunit100.apache/Development/golang/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/util/backoff_utils.go:82 +0x43
k8s.io/kubernetes/plugin/pkg/scheduler/util.(*backoffEntry).TryWait(0xc4297df770, 0xdf8475800, 0x0)
        /root/Dropbox/jayunit100.apache/Development/golang/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/util/backoff_utils.go:66 +0x7b
k8s.io/kubernetes/plugin/pkg/scheduler/factory.(*ConfigFactory).MakeDefaultErrorFunc.func1.1(0xc42b3dcb00, 0xc4276b32c0, 0xc42527cd80, 0xc426064f30)
        /root/Dropbox/jayunit100.apache/Development/golang/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:613 +0xf3
created by k8s.io/kubernetes/plugin/pkg/scheduler/factory.(*ConfigFactory).MakeDefaultErrorFunc.func1
        /root/Dropbox/jayunit100.apache/Development/golang/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:637 +0x1df
exit status 2
FAIL    k8s.io/kubernetes/test/integration/scheduler_perf       3601.424s
!!! Error in test/integration/scheduler_perf/test-performance.sh:51
  Error in test/integration/scheduler_perf/test-performance.sh:51. 'go test -test.run=. -test.timeout=60m -test.short=false' exited with status 1
Call stack:
```

Will add more details later or issue a PR if its something trivial.

**Comment by jayunit100** [comment]
@timothysc i think 

```
		podCreatorConfig.AddStrategy("sched-perf-node-affinity", config.numPods/numGroups,
```

is supposed to be 

```
sched-perf-node-affinity-pod-
```

?  Not sure but i think the source of this bug is https://github.com/kubernetes/kubernetes/pull/40176/files#diff-3126019cd381f25186f4fa8c8da06ec6R85

Possibly just a typo might have been introduced in that patch?  If not maybe its just an issue with the way we need to update the labelling json or something.  I can take another look in the morning.

**Comment by jayunit100** [comment]
ok, i think i see...  it wants to match the label `kubernetes.io/sched-perf-...`... from this node:

```
&Node{
        ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:scheduler-perf-jz53v,GenerateName:scheduler-perf-,Namespace:,SelfLink:/api/v1/nodesscheduler-perf-jz53v,UID:258bbfa7-efa3-11e6-8c77-ecf4bbc73dec,ResourceVersion:9236,Generation:0,CreationTimestamp:2017-02-10 10:11:07 -0500 EST,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{kubernetes.io/sched-perf-node-affinity: 5,},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,},Spec:NodeSpec{PodCIDR:,ExternalID:foo,ProviderID:,Unschedulable:false,},Status:NodeStatus{Capacity:ResourceList{cpu: {{4 0} {<nil>} 4 DecimalSI},memory: {{34359738368 0} {<nil>}  BinarySI},pods: {{110 0} {<nil>} 110 DecimalSI},},Allocatable:ResourceList{cpu: {{4 0} {<nil>} 4 DecimalSI},memory: {{34359738368 0} {<nil>}  BinarySI},pods: {{110 0} {<nil>} 110 DecimalSI},},Phase:Running,Conditions:[{Ready True 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC  }],Addresses:[],DaemonEndpoints:NodeDaemonEndpoints{KubeletEndpoint:DaemonEndpoint{Port:0,},},NodeInfo:NodeSystemInfo{MachineID:,SystemUUID:,BootID:,KernelVersion:,OSImage:,ContainerRuntimeVersion:,KubeletVersion:,KubeProxyVersion:,OperatingSystem:,Architecture:,},Images:[],VolumesInUse:[],VolumesAttached:[],},}
```
into this set
```
[{[{kubernetes.io/sched-perf-node-affinity In []}]}]
```

so the set is empty.  I guess it could be a bug in the way the match selector is being produced, but the code looks clean to me.  will double check.

**Comment by jayunit100** [comment]
fixed
