### ISSUE TITLE
`release-1.5` build flaking

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#41374]
`release-1.5` branch release builds have started to randomly fail; see https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-build-1.5/

All the failed builds:
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build-1.5/122/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build-1.5/127/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build-1.5/129/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build-1.5/134/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build-1.5/138/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build-1.5/141/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build-1.5/143/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build-1.5/144/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build-1.5/146/

Have the same error:
<details>

```
I0213 07:57:19.269] +++ [0213 07:57:19] Building tarball: src
I0213 07:57:19.270] +++ [0213 07:57:19] Building tarball: salt
I0213 07:57:19.270] +++ [0213 07:57:19] Building tarball: manifests
I0213 07:57:19.272] +++ [0213 07:57:19] Starting tarball: client darwin-386
I0213 07:57:19.274] +++ [0213 07:57:19] Starting tarball: client darwin-amd64
I0213 07:57:19.277] +++ [0213 07:57:19] Starting tarball: client linux-386
I0213 07:57:19.279] +++ [0213 07:57:19] Starting tarball: client linux-amd64
I0213 07:57:19.281] +++ [0213 07:57:19] Starting tarball: client linux-arm
I0213 07:57:19.284] +++ [0213 07:57:19] Starting tarball: client linux-arm64
I0213 07:57:19.286] +++ [0213 07:57:19] Starting tarball: client windows-386
I0213 07:57:19.286] +++ [0213 07:57:19] Building tarball: node linux-amd64
I0213 07:57:19.286] +++ [0213 07:57:19] Building tarball: server linux-amd64
I0213 07:57:19.288] +++ [0213 07:57:19] Starting tarball: client windows-amd64
I0213 07:57:19.290] +++ [0213 07:57:19] Waiting on tarballs
W0213 07:57:20.385] cp: cannot stat ‘/var/lib/jenkins/workspace/ci-kubernetes-build-1.5/go/src/k8s.io/kubernetes/_output/release-tars/kubernetes-src.tar.gz’: No such file or directory
I0213 07:57:21.286] +++ [0213 07:57:21] Starting Docker build for image: kube-apiserver
I0213 07:57:21.304] +++ [0213 07:57:21] Starting Docker build for image: kube-controller-manager
I0213 07:57:21.312] +++ [0213 07:57:21] Starting Docker build for image: kube-scheduler
I0213 07:57:21.319] +++ [0213 07:57:21] Starting Docker build for image: kube-proxy
I0213 07:57:40.716] +++ [0213 07:57:40] Deleting docker image gcr.io/google_containers/kube-scheduler:75c4894c6dc9f6cb3da34de60aa879f7
I0213 07:57:41.022] Untagged: gcr.io/google_containers/kube-scheduler:75c4894c6dc9f6cb3da34de60aa879f7
I0213 07:57:41.023] Deleted: ee7c37c67c25a90214e61ca2e4fe8a8043a1b8b101b29ba3ea8e89e03e6a8ac8
I0213 07:57:45.578] +++ [0213 07:57:45] Deleting docker image gcr.io/google_containers/kube-controller-manager:79fe3bdf01d40587b915763c5cab13d8
I0213 07:57:45.704] Untagged: gcr.io/google_containers/kube-controller-manager:79fe3bdf01d40587b915763c5cab13d8
I0213 07:57:45.704] Deleted: aaa487dd22eec0167d13be7034876fe0cc32766ff5f3fccae94c61801abe05b2
I0213 07:57:45.834] +++ [0213 07:57:45] Deleting docker image gcr.io/google_containers/kube-apiserver:575f7edfcd27e264c513a1829d987557
I0213 07:57:46.097] Untagged: gcr.io/google_containers/kube-apiserver:575f7edfcd27e264c513a1829d987557
I0213 07:57:46.098] Deleted: 3b954e6f3a854a0b961ffd16eab3267a5382dc37bbade901c6b43332b1c3e78c
I0213 07:58:09.460] +++ [0213 07:58:09] Deleting docker image gcr.io/google_containers/kube-proxy:1f66d28391edc3b36d67d6f961cb5090
I0213 07:58:09.506] Untagged: gcr.io/google_containers/kube-proxy:1f66d28391edc3b36d67d6f961cb5090
I0213 07:58:09.506] Deleted: ea2a4ab1b70faa60331436e54a549f44f673254d0c2d6fb9d1bb4078f8c309f7
I0213 07:58:09.510] +++ [0213 07:58:09] Docker builds done
I0213 07:59:07.185] +++ [0213 07:59:07] Building tarball: server linux-arm
I0213 07:59:08.974] +++ [0213 07:59:08] Starting Docker build for image: kube-apiserver
I0213 07:59:08.976] +++ [0213 07:59:08] Starting Docker build for image: kube-controller-manager
I0213 07:59:08.978] +++ [0213 07:59:08] Starting Docker build for image: kube-scheduler
I0213 07:59:08.980] +++ [0213 07:59:08] Starting Docker build for image: kube-proxy
I0213 07:59:21.916] +++ [0213 07:59:21] Deleting docker image gcr.io/google_containers/kube-scheduler-arm:7c27f72fe54436f0d83ef78b72c106fc
I0213 07:59:21.975] Untagged: gcr.io/google_containers/kube-scheduler-arm:7c27f72fe54436f0d83ef78b72c106fc
I0213 07:59:21.975] Deleted: a771e9a4f7f42185c9e6011a1094c70f140644a51f96b2bdfc90cce125e73b67
I0213 07:59:24.236] +++ [0213 07:59:24] Deleting docker image gcr.io/google_containers/kube-controller-manager-arm:81ecaf695009b3ba110081af2e50d444
I0213 07:59:24.337] Untagged: gcr.io/google_containers/kube-controller-manager-arm:81ecaf695009b3ba110081af2e50d444
I0213 07:59:24.338] Deleted: 5e3e09ddab89ce86af1299d41d1dd53d045eb925cea74f3a62ef9ac76cb7e4ed
I0213 07:59:25.651] +++ [0213 07:59:25] Deleting docker image gcr.io/google_containers/kube-apiserver-arm:4fe6ebc2f328c23a6fc1f5975d0241ae
I0213 07:59:25.785] Untagged: gcr.io/google_containers/kube-apiserver-arm:4fe6ebc2f328c23a6fc1f5975d0241ae
I0213 07:59:25.785] Deleted: 415e5dbbc800eaafdbc451f709c5be1136bfc7e125b5ad5875cb1d9bee68acb6
I0213 07:59:29.179] +++ [0213 07:59:29] Deleting docker image gcr.io/google_containers/kube-proxy-arm:a3d6338c72b8e2f147f0708b7ce72f1c
I0213 07:59:29.229] Untagged: gcr.io/google_containers/kube-proxy-arm:a3d6338c72b8e2f147f0708b7ce72f1c
I0213 07:59:29.229] Deleted: 77f6c3bc8aede52da03a9bd6ab73ac197d64342cb54e0f0cb47534ac927b792e
I0213 07:59:29.232] +++ [0213 07:59:29] Docker builds done
I0213 08:00:18.680] +++ [0213 08:00:18] Building tarball: server linux-arm64
I0213 08:00:20.045] +++ [0213 08:00:20] Starting Docker build for image: kube-apiserver
I0213 08:00:20.046] +++ [0213 08:00:20] Starting Docker build for image: kube-controller-manager
I0213 08:00:20.052] +++ [0213 08:00:20] Starting Docker build for image: kube-scheduler
I0213 08:00:20.053] +++ [0213 08:00:20] Starting Docker build for image: kube-proxy
I0213 08:00:26.652] +++ [0213 08:00:26] Deleting docker image gcr.io/google_containers/kube-scheduler-arm64:026fe8fe64fbc403870f72d19e77c45b
I0213 08:00:26.701] Untagged: gcr.io/google_containers/kube-scheduler-arm64:026fe8fe64fbc403870f72d19e77c45b
I0213 08:00:26.701] Deleted: ac2173ee36534c1bc8e847247c0156bd213cb74c4411de37feb85bb62c830bc9
I0213 08:00:29.509] +++ [0213 08:00:29] Deleting docker image gcr.io/google_containers/kube-controller-manager-arm64:c3ffa0b115f9f664e279d87c34cd9037
I0213 08:00:29.576] Untagged: gcr.io/google_containers/kube-controller-manager-arm64:c3ffa0b115f9f664e279d87c34cd9037
I0213 08:00:29.576] Deleted: a0d9ca8fef6dd0c97624a6d4950b3778dc6d49d7faf3540e14cadbf993c25987
I0213 08:00:35.643] +++ [0213 08:00:35] Deleting docker image gcr.io/google_containers/kube-apiserver-arm64:68b6732eaeb1a57413b618c7716255d9
I0213 08:00:35.766] Untagged: gcr.io/google_containers/kube-apiserver-arm64:68b6732eaeb1a57413b618c7716255d9
I0213 08:00:35.766] Deleted: a48c40f88702466390f19b1f0bc2eb3090b6f97131ea78474dd0a9421847087d
I0213 08:00:38.173] +++ [0213 08:00:38] Deleting docker image gcr.io/google_containers/kube-proxy-arm64:4ed850bb4c6e7ec99aaee7c2ae654067
I0213 08:00:38.224] Untagged: gcr.io/google_containers/kube-proxy-arm64:4ed850bb4c6e7ec99aaee7c2ae654067
I0213 08:00:38.224] Deleted: f1a4bff6a2c4e40119110382d9fdec474cf04a5230ace65a4a01fdf8cbad03f2
I0213 08:00:38.227] +++ [0213 08:00:38] Docker builds done
W0213 08:01:36.762] !!! [0213 08:01:36] previous tarball phase failed
W0213 08:01:36.764] make: *** [release] Error 1
W0213 08:01:36.766] Traceback (most recent call last):
W0213 08:01:36.766]   File "/var/lib/jenkins/workspace/ci-kubernetes-build-1.5/./test-infra/jenkins/../scenarios/kubernetes_build.py", line 85, in <module>
W0213 08:01:36.766]     main(ARGS)
W0213 08:01:36.766]   File "/var/lib/jenkins/workspace/ci-kubernetes-build-1.5/./test-infra/jenkins/../scenarios/kubernetes_build.py", line 60, in main
W0213 08:01:36.766]     check(args.script)
W0213 08:01:36.766]   File "/var/lib/jenkins/workspace/ci-kubernetes-build-1.5/./test-infra/jenkins/../scenarios/kubernetes_build.py", line 31, in check
W0213 08:01:36.767]     subprocess.check_call(cmd)
W0213 08:01:36.767]   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
W0213 08:01:36.788]     raise CalledProcessError(retcode, cmd)
W0213 08:01:36.789] subprocess.CalledProcessError: Command '('./hack/jenkins/build.sh',)' returned non-zero exit status 2
I0213 08:01:36.857] Makefile:248: recipe for target 'release' failed
E0213 08:01:36.857] Build failed
I0213 08:01:36.858] process 26345 exited with code 1 after 32.9m
E0213 08:01:36.858] FAIL: ci-kubernetes-build-1.5
```

</details>

The flakes correlate with PR https://github.com/kubernetes/kubernetes/pull/40507 merging.

@brendandburns @luxas @pires could you please take a look.

CC @ixdy @kubernetes/test-infra-admins

**Comment by ixdy** [comment]
oh, I bet we need to cherry-pick https://github.com/kubernetes/kubernetes/pull/39773.

**Comment by saad-ali** [comment]
Ah nice, I'll get that cherry picked. Thanks.

**Comment by saad-ali** [comment]
The builds look stable since https://github.com/kubernetes/kubernetes/pull/41376 merged
Closing this issue
