### ISSUE TITLE
Jenkins Bazel Build failing with python errors

### ISSUE THREAD

**Issue by vladimirvivien** [kubernetes/kubernetes#41591]
Jenken Bazel Build keeps failing after three tries while building https://github.com/kubernetes/kubernetes/pull/38924 - See following link: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/38924/pull-kubernetes-bazel/5627/

```
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/s~k8s-gubernator/1.398728629607611537/view_base.py", line 81, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~k8s-gubernator/1.398728629607611537/view_build.py", line 132, in get
    details = build_details(build_dir)
  File "/base/data/home/apps/s~k8s-gubernator/1.398728629607611537/view_base.py", line 128, in wrapped
    data = func(*args)
  File "/base/data/home/apps/s~k8s-gubernator/1.398728629607611537/view_build.py", line 109, in build_details
    failures.extend(parse_junit(junit, junit_futures[future]))
  File "/base/data/home/apps/s~k8s-gubernator/1.398728629607611537/view_build.py", line 33, in parse_junit
    tree = ET.fromstring(xml)
  File "/base/data/home/apps/s~k8s-gubernator/1.398728629607611537/third_party/defusedxml/common.py", line 159, in fromstring
    parser.feed(text)
  File "/base/data/home/runtimes/python27_experiment/python27_dist/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/base/data/home/runtimes/python27_experiment/python27_dist/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 57, column 125
```

**Comment by calebamiles** [comment]
Could someone from @kubernetes/test-infra-maintainers please take a look? Thanks!
