### ISSUE TITLE
1.6 -> 1.5 Downgrade jobs failing

### ISSUE THREAD

**Issue by ethernetdan** [kubernetes/kubernetes#43470]
Currently the 1.6 -> 1.5 downgrade jobs are failing:
[gce-1.6-1.5-downgrade-cluster](https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gce-1.6-1.5-downgrade-cluster)
```
Expected error:
    <*errors.errorString | 0xc4208102d0>: {
        s: "error running /workspace/kubernetes_skew/cluster/gce/upgrade.sh [-M v1.5.5-beta.0.14+0fb9a2d414403e]; got error signal: interrupt, stdout \"== Pre-Upgrade Node OS and Kubelet Versions ==\\nname: \\\"bootstrap-e2e-master\\\", osImage: \\\"Container-Optimized OS from Google\\\", kubeletVersion: \\\"v1.6.0-beta.4.81+2c160759f37fb8\\\"\\nname: \\\"bootstrap-e2e-minion-group-4v5v\\\", osImage: \\\"Debian GNU/Linux 7 (wheezy)\\\", kubeletVersion: \\\"v1.5.5-beta.0.14+0fb9a2d414403e\\\"\\nname: \\\"bootstrap-e2e-minion-group-dmcl\\\", osImage: \\\"Debian GNU/Linux 7 (wheezy)\\\", kubeletVersion: \\\"v1.5.5-beta.0.14+0fb9a2d414403e\\\"\\nname: \\\"bootstrap-e2e-minion-group-lsrw\\\", osImage: \\\"Debian GNU/Linux 7 (wheezy)\\\", kubeletVersion: \\\"v1.5.5-beta.0.14+0fb9a2d414403e\\\"\\n== Upgrading master to 'https://storage.googleapis.com/kubernetes-release-dev/ci/v1.5.5-beta.0.14+0fb9a2d414403e/kubernetes-server-linux-amd64.tar.gz'. Do not interrupt, deleting master instance. ==\\nNAME                  ZONE           MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP     STATUS\\nbootstrap-e2e-master  us-central1-f  n1-standard-1               10.240.0.2   35.184.192.247  RUNNING\\n== Waiting for new master to respond to API requests ==\\n\", stderr \"Project: k8s-gce-dg-1-6-1-5-dwngr-clu\\nZone: us-central1-f\\nINSTANCE_GROUPS=bootstrap-e2e-minion-group\\nNODE_NAMES=bootstrap-e2e-minion-group-4v5v bootstrap-e2e-minion-group-dmcl bootstrap-e2e-minion-group-lsrw\\nTrying to find master named 'bootstrap-e2e-master'\\nLooking for address 'bootstrap-e2e-master-ip'\\nUsing master: bootstrap-e2e-master (external IP: 35.184.192.247)\\nDeleted [https://www.googleapis.com/compute/v1/projects/k8s-gce-dg-1-6-1-5-dwngr-clu/zones/us-central1-f/instances/bootstrap-e2e-master].\\nWARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#pdperformance.\\nCreated [https://www.googleapis.com/compute/v1/projects/k8s-gce-dg-1-6-1-5-dwngr-clu/zones/us-central1-f/instances/bootstrap-e2e-master].\\n\"",
    }
    error running /workspace/kubernetes_skew/cluster/gce/upgrade.sh [-M v1.5.5-beta.0.14+0fb9a2d414403e]; got error signal: interrupt, stdout "== Pre-Upgrade Node OS and Kubelet Versions ==\nname: \"bootstrap-e2e-master\", osImage: \"Container-Optimized OS from Google\", kubeletVersion: \"v1.6.0-beta.4.81+2c160759f37fb8\"\nname: \"bootstrap-e2e-minion-group-4v5v\", osImage: \"Debian GNU/Linux 7 (wheezy)\", kubeletVersion: \"v1.5.5-beta.0.14+0fb9a2d414403e\"\nname: \"bootstrap-e2e-minion-group-dmcl\", osImage: \"Debian GNU/Linux 7 (wheezy)\", kubeletVersion: \"v1.5.5-beta.0.14+0fb9a2d414403e\"\nname: \"bootstrap-e2e-minion-group-lsrw\", osImage: \"Debian GNU/Linux 7 (wheezy)\", kubeletVersion: \"v1.5.5-beta.0.14+0fb9a2d414403e\"\n== Upgrading master to 'https://storage.googleapis.com/kubernetes-release-dev/ci/v1.5.5-beta.0.14+0fb9a2d414403e/kubernetes-server-linux-amd64.tar.gz'. Do not interrupt, deleting master instance. ==\nNAME                  ZONE           MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP     STATUS\nbootstrap-e2e-master  us-central1-f  n1-standard-1               10.240.0.2   35.184.192.247  RUNNING\n== Waiting for new master to respond to API requests ==\n", stderr "Project: k8s-gce-dg-1-6-1-5-dwngr-clu\nZone: us-central1-f\nINSTANCE_GROUPS=bootstrap-e2e-minion-group\nNODE_NAMES=bootstrap-e2e-minion-group-4v5v bootstrap-e2e-minion-group-dmcl bootstrap-e2e-minion-group-lsrw\nTrying to find master named 'bootstrap-e2e-master'\nLooking for address 'bootstrap-e2e-master-ip'\nUsing master: bootstrap-e2e-master (external IP: 35.184.192.247)\nDeleted [https://www.googleapis.com/compute/v1/projects/k8s-gce-dg-1-6-1-5-dwngr-clu/zones/us-central1-f/instances/bootstrap-e2e-master].\nWARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#pdperformance.\nCreated [https://www.googleapis.com/compute/v1/projects/k8s-gce-dg-1-6-1-5-dwngr-clu/zones/us-central1-f/instances/bootstrap-e2e-master].\n"
not to have occurred
```

[gke-gci-1.6-gci-1.5-downgrade-cluster](https://k8s-testgrid.appspot.com/release-1.6-upgrade-skew#gke-gci-1.6-gci-1.5-downgrade-cluster)
```
Mar 21 03:12:01.772: Failed to allocated static ip e2e-tests-ingress-upgrade-zszrb-static-ip: googleapi: Error 403: Quota 'STATIC_ADDRESSES' exceeded. Limit: 7.0, quotaExceeded****
```

Looks like this could be for different reasons.

**Comment by ixdy** [comment]
I'll fix quota for the GKE test. It was failing for unrelated reasons yesterday and leaked IPs.

**Comment by krousey** [comment]
From etcd log:

```
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/coreos/etcd/wal.(*decoder).decode(0xc82019b200, 0xc820186178, 0x0, 0x0)
	/home/vagrant/gopath/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/wal/decoder.go:55 +0x142
github.com/coreos/etcd/wal.(*WAL).ReadAll(0xc820147520, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/vagrant/gopath/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/wal/wal.go:238 +0x214
github.com/coreos/etcd/etcdserver.readWAL(0xc820195520, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc820147520, 0xc8201b40e0, 0x5, ...)
	/home/vagrant/gopath/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/storage.go:84 +0x227
github.com/coreos/etcd/etcdserver.restartNode(0xc8201380e0, 0x0, 0x7f026dbe3028, 0xc8200a7410, 0x0, 0x0, 0x0, 0x0)
	/home/vagrant/gopath/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/raft.go:286 +0xff
github.com/coreos/etcd/etcdserver.NewServer(0xc8201380e0, 0xc820138100, 0x0, 0x0)
	/home/vagrant/gopath/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:288 +0x322d
github.com/coreos/etcd/etcdmain.startEtcd(0xc8200f26c0, 0x0, 0x0, 0x0)
	/home/vagrant/gopath/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:287 +0x1a92
github.com/coreos/etcd/etcdmain.Main()
	/home/vagrant/gopath/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:117 +0x1e26
main.main()
	/home/vagrant/gopath/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/main.go:29 +0x14
```

From what I understand, we cannot rollback etcdv3 + proto data store encoding. We can rollback etcdv3 + json data store encoding if we use the updated etcd image that has the rollback tool in it. Details look to be in https://github.com/kubernetes/kubernetes.github.io/pull/2767/files

I'll start playing around with this to see if I can get it working.

cc @mml

**Comment by ethernetdan** [comment]
#43481 just merged - will review results in morning before closing

**Comment by krousey** [comment]
@ethernetdan I'm afraid this only uncovers another issue. Last I spoke with @mikedanese, he said he was working on something for that.

**Comment by ethernetdan** [comment]
@mikedanese, any luck?

**Comment by mikedanese** [comment]
https://github.com/kubernetes/kubernetes/pull/43532 https://github.com/kubernetes/kubernetes/pull/43529

**Comment by krousey** [comment]
Also https://github.com/kubernetes/kubernetes/pull/43533 is probably needed. Thanks @mml for helping investigate that.

**Comment by ethernetdan** [comment]
@mikedanese @krousey looks like still failing but with different errors this time. I'm seeing:
```
Expected
    <bool>: false
to be true
```
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.6-1.5-downgrade-cluster/110

and

```
Mar 22 21:19:34.872: timeout waiting 15m0s for pods size to be 3
```
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1.6-gci-1.5-downgrade-cluster/111

**Comment by ethernetdan** [comment]
@mikedanese @krousey @skriss thoughts? This is a release blocker

**Comment by mikedanese** [comment]
@ethernetdan your comment was before https://github.com/kubernetes/kubernetes/pull/43532 merged. Most recent failure is significantly different but I'm finding the output hard to read. I'm talking to @krousey to decipher:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.6-1.5-downgrade-cluster/113

**Comment by janetkuo** [comment]
I tried to create a 1.6 cluster and then downgrade the master to 1.5, but the downgraded master never responded (waited ~hours). 

The steps I run:
```console
➜ kubernetes(master)$ git checkout release-1.6 
➜ kubernetes(release-1.6)$ make clean && make quick-release && cluster/kube-up.sh 
➜ kubernetes(release-1.6)$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-beta.4.169+1e24124c2c4868-dirty", GitCommit:"1e24124c2c486801b1b9b6be118b9dab80173ad5", GitTreeState:"dirty", BuildDate:"2017-03-23T18:15:20Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-beta.4.169+1e24124c2c4868-dirty", GitCommit:"1e24124c2c486801b1b9b6be118b9dab80173ad5", GitTreeState:"dirty", BuildDate:"2017-03-23T18:12:32Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
➜ kubernetes(release-1.6)$ git checkout v1.5.3
➜ kubernetes((HEAD detached at v1.5.3))$ cluster/gce/upgrade.sh -M v1.5.3
== Pre-Upgrade Node OS and Kubelet Versions ==
name: "kubernetes-master", osImage: "Container-Optimized OS from Google", kubeletVersion: "v1.6.0-beta.4.169+1e24124c2c4868-dirty"
name: "kubernetes-minion-group-13tb", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.6.0-beta.4.169+1e24124c2c4868-dirty"
name: "kubernetes-minion-group-hfxr", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.6.0-beta.4.169+1e24124c2c4868-dirty"
name: "kubernetes-minion-group-n28d", osImage: "Debian GNU/Linux 7 (wheezy)", kubeletVersion: "v1.6.0-beta.4.169+1e24124c2c4868-dirty"
Your active configuration is: [default]

Project: janet-kube
Zone: us-central1-b
INSTANCE_GROUPS=kubernetes-minion-group
NODE_NAMES=kubernetes-minion-group-13tb kubernetes-minion-group-hfxr kubernetes-minion-group-n28d
== Upgrading master to 'https://storage.googleapis.com/kubernetes-release/release/v1.5.3/kubernetes-server-linux-amd64.tar.gz'. Do not interrupt, deleting master instance. ==
Trying to find master named 'kubernetes-master'
Looking for address 'kubernetes-master-ip'
Using master: kubernetes-master (external IP: 104.154.166.25)
Deleted [https://www.googleapis.com/compute/v1/projects/janet-kube/zones/us-central1-b/instances/kubernetes-master].
WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#pdperformance.
Created [https://www.googleapis.com/compute/v1/projects/janet-kube/zones/us-central1-b/instances/kubernetes-master].
NAME               ZONE           MACHINE_TYPE   PREEMPTIBLE  INTERNAL_IP  EXTERNAL_IP     STATUS
kubernetes-master  us-central1-b  n1-standard-1               10.128.0.2   104.154.166.25  RUNNING
== Waiting for new master to respond to API requests ==
..................................................... 
(stuck for hours)
```

**Comment by mikedanese** [comment]
Your hitting the downgrade issue https://github.com/kubernetes/kubernetes/issues/43470#issuecomment-288203309, there is no way to downgrade etcd from v3 storage version to v2. @krousey has some env variables that allow you to deploy etcd with v2 for the 1.6 cluster.

**Comment by mml** [comment]
We still aren't passing the right variables into the kube-env.  In particular, there's no value for `ETCD_IMAGE`, so we end up running the 2.2.1 image which doesn't contain the migration script nor the rollback tool.

```console
% gcloud --project=k8s-gce-dg-1-6-1-5-dwngr-clu compute instances describe bootstrap-e2e-master --zone=us-central1-f | grep -E 'ETCD|STORAGE|VERSION'
      E2E_STORAGE_TEST_ENVIRONMENT: 'false'
      STORAGE_BACKEND: 'etcd2'
      ETCD_CA_KEY: ''
      ETCD_CA_CERT: ''
      ETCD_PEER_KEY: ''
      ETCD_PEER_CERT: ''
      INITIAL_ETCD_CLUSTER: 'bootstrap-e2e-master'
      ETCD_QUORUM_READ: 'false'
```

I can try to reproduce this myself.

cc @wojtek-t in case we are doing something dumb WRT the environment.

**Comment by ethernetdan** [comment]
@mml were you able to reproduce?

**Comment by ethernetdan** [comment]
Looks like `gke-gci-1.6-gci-1.5-downgrade-cluster` is now failing with the same error as #43612, progress!
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-1.6-gci-1.5-downgrade-cluster/136

Now it looks like `ci-kubernetes-e2e-gce-1.6-1.5-downgrade-cluster` has the static IP allocation issue:
```
Mar 24 07:42:47.248: Failed to allocated static ip e2e-tests-ingress-upgrade-19xh3-static-ip: googleapi: Error 403: Quota 'STATIC_ADDRESSES' exceeded. Limit: 7.0, quotaExceeded
```
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.6-1.5-downgrade-cluster/126
@ixdy could you look into the quota on this one too? It looks like whatever you did fixed the other suite.

**Comment by mikedanese** [comment]
I'm not looking at this anymore, ping me if you need me.

**Comment by krousey** [comment]
I'm willing to count https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-1.6-1.5-downgrade-cluster/130 as a pass...

**Comment by ethernetdan** [comment]
Was decided at burndown that these are test failures and don't need to block 1.6

**Comment by ixdy** [comment]
Doesn't look like we're having quota issues anymore.

/unassign

**Comment by nicksardo** [comment]
The ingress upgrade test continues to leak static addresses when the disruption fails.  The test's `Teardown()` func is never called.
Please see #45842

**Comment by cmluciano** [comment]
This seems to be affecting many PRs at the moment. Is there a clear owner here?
