### ISSUE TITLE
Deployment of 1.5.4 fails on Openstack Mitaka. Error on second node.

### ISSUE THREAD

**Issue by carlosedp** [kubernetes/kubernetes#43476]
**Kubernetes version** (use `kubectl version`): 1.5.4 from releases (.tar.gz)

**Environment**:
- **Cloud provider or hardware configuration**: Mirantis Openstack 9.2 (Mitaka) over VMware
- **OS** (e.g. from /etc/os-release): CentOS 7.3 (1611)
- **Kernel** (e.g. `uname -a`): 3.10.0-514.el7.x86_64
- **Install tools**: `KUBERNETES_PROVIDER=openstack-heat ./cluster/kube-up.sh`
- **Others**: Deployment from both .tar.gz downloaded from releases and downloaded thru `export KUBERNETES_PROVIDER=openstack-heat; curl -sS https://get.k8s.io | bash`

**What happened**: Tried to deploy on Openstack infrastructure. The deploy fails and investigating the nodes, the master is deployed, the first minion is deployed as well **but on the second minion (node) I get the error below**:

```
Mar 21 19:50:56 kube-stack-node-6vgkt9wr cloud-init[4643]: +++ Install binaries from tar: kubernetes-server.tar.gz
Mar 21 19:52:33 kube-stack-node-6vgkt9wr chronyd[517]: Selected source 200.160.7.186

Mar 21 20:01:02 kube-stack-node-6vgkt9wr systemd[1]: Created slice user-0.slice.
Mar 21 20:01:02 kube-stack-node-6vgkt9wr systemd[1]: Starting user-0.slice.
Mar 21 20:01:02 kube-stack-node-6vgkt9wr systemd[1]: Started Session 2 of user root.
Mar 21 20:01:02 kube-stack-node-6vgkt9wr systemd[1]: Starting Session 2 of user root.
Mar 21 20:01:02 kube-stack-node-6vgkt9wr CROND[9309]: (root) CMD (run-parts /etc/cron.hourly)
Mar 21 20:01:02 kube-stack-node-6vgkt9wr run-parts(/etc/cron.hourly)[9312]: starting 0anacron
Mar 21 20:01:02 kube-stack-node-6vgkt9wr anacron[9318]: Anacron started on 2017-03-21
Mar 21 20:01:02 kube-stack-node-6vgkt9wr run-parts(/etc/cron.hourly)[9320]: finished 0anacron
Mar 21 20:01:02 kube-stack-node-6vgkt9wr anacron[9318]: Will run job `cron.daily' in 21 min.
Mar 21 20:01:02 kube-stack-node-6vgkt9wr anacron[9318]: Will run job `cron.weekly' in 41 min.
Mar 21 20:01:02 kube-stack-node-6vgkt9wr anacron[9318]: Will run job `cron.monthly' in 61 min.
Mar 21 20:01:02 kube-stack-node-6vgkt9wr anacron[9318]: Jobs will be executed sequentially
Mar 21 20:02:40 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/server/bin/hyperkube’ -> ‘/srv/salt-new/salt/kube-bins/hyperkube’
Mar 21 20:02:40 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/server/bin/kubeadm’ -> ‘/srv/salt-new/salt/kube-bins/kubeadm’
Mar 21 20:02:40 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/server/bin/kube-apiserver’ -> ‘/srv/salt-new/salt/kube-bins/kube-apiserver’
Mar 21 20:02:40 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/server/bin/kube-apiserver.docker_tag’ -> ‘/srv/salt-new/salt/kube-bins/kube-apiserver.docker_tag’
Mar 21 20:02:40 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/server/bin/kube-apiserver.tar’ -> ‘/srv/salt-new/salt/kube-bins/kube-apiserver.tar’
Mar 21 20:02:40 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/server/bin/kube-controller-manager’ -> ‘/srv/salt-new/salt/kube-bins/kube-controller-manager’
Mar 21 20:02:40 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/server/bin/kube-controller-manager.docker_tag’ -> ‘/srv/salt-new/salt/kube-bins/kube-controller-manager.docker_tag’
Mar 21 20:02:40 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/server/bin/kube-controller-manager.tar’ -> ‘/srv/salt-new/salt/kube-bins/kube-controller-manager.tar’
Mar 21 20:02:40 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/server/bin/kubectl’ -> ‘/srv/salt-new/salt/kube-bins/kubectl’
Mar 21 20:02:40 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/server/bin/kube-discovery’ -> ‘/srv/salt-new/salt/kube-bins/kube-discovery’
Mar 21 20:02:40 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/server/bin/kube-dns’ -> ‘/srv/salt-new/salt/kube-bins/kube-dns’
Mar 21 20:02:40 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/server/bin/kubefed’ -> ‘/srv/salt-new/salt/kube-bins/kubefed’
Mar 21 20:02:40 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/server/bin/kubelet’ -> ‘/srv/salt-new/salt/kube-bins/kubelet’
Mar 21 20:02:40 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/server/bin/kube-proxy’ -> ‘/srv/salt-new/salt/kube-bins/kube-proxy’
Mar 21 20:02:40 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/server/bin/kube-proxy.docker_tag’ -> ‘/srv/salt-new/salt/kube-bins/kube-proxy.docker_tag’
Mar 21 20:02:40 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/server/bin/kube-proxy.tar’ -> ‘/srv/salt-new/salt/kube-bins/kube-proxy.tar’
Mar 21 20:02:40 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/server/bin/kube-scheduler’ -> ‘/srv/salt-new/salt/kube-bins/kube-scheduler’
Mar 21 20:02:40 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/server/bin/kube-scheduler.docker_tag’ -> ‘/srv/salt-new/salt/kube-bins/kube-scheduler.docker_tag’
Mar 21 20:02:40 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/server/bin/kube-scheduler.tar’ -> ‘/srv/salt-new/salt/kube-bins/kube-scheduler.tar’
Mar 21 20:02:42 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/LICENSES’ -> ‘/srv/salt-new/salt/kube-docs/LICENSES’
Mar 21 20:02:49 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/kubernetes.T8mLIv/kubernetes/kubernetes-src.tar.gz’ -> ‘/srv/salt-new/salt/kube-docs/kubernetes-src.tar.gz’
Mar 21 20:02:49 kube-stack-node-6vgkt9wr cloud-init[4643]: +++ Swapping in new configs
Mar 21 20:02:49 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/salt-new/salt’ -> ‘/srv/salt’
Mar 21 20:02:49 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/salt-new/pillar’ -> ‘/srv/pillar’
Mar 21 20:02:49 kube-stack-node-6vgkt9wr cloud-init[4643]: ‘/srv/salt-new/reactor’ -> ‘/srv/reactor’
Mar 21 20:03:40 kube-stack-node-6vgkt9wr systemd[1]: Starting Cleanup of Temporary Directories...
Mar 21 20:03:40 kube-stack-node-6vgkt9wr systemd[1]: Started Cleanup of Temporary Directories.
Mar 21 20:03:44 kube-stack-node-6vgkt9wr flanneld-start[9240]: E0321 20:03:44.370202    9240 watch.go:272] Subnet watch failed: client: etcd cluster is unavailable or misconfigured
Mar 21 20:03:45 kube-stack-node-6vgkt9wr flanneld-start[9240]: E0321 20:03:45.371060    9240 watch.go:272] Subnet watch failed: client: etcd cluster is unavailable or misconfigured
Mar 21 20:03:46 kube-stack-node-6vgkt9wr flanneld-start[9240]: E0321 20:03:46.371481    9240 watch.go:272] Subnet watch failed: client: etcd cluster is unavailable or misconfigured
Mar 21 20:03:47 kube-stack-node-6vgkt9wr flanneld-start[9240]: E0321 20:03:47.058055    9240 watch.go:43] Watch subnets: client: etcd cluster is unavailable or misconfigured
Mar 21 20:03:47 kube-stack-node-6vgkt9wr flanneld-start[9240]: E0321 20:03:47.371898    9240 watch.go:272] Subnet watch failed: client: etcd cluster is unavailable or misconfigured
Mar 21 20:03:48 kube-stack-node-6vgkt9wr flanneld-start[9240]: E0321 20:03:48.058487    9240 watch.go:43] Watch subnets: client: etcd cluster is unavailable or misconfigured
Mar 21 20:03:48 kube-stack-node-6vgkt9wr flanneld-start[9240]: E0321 20:03:48.372367    9240 watch.go:272] Subnet watch failed: client: etcd cluster is unavailable or misconfigured
Mar 21 20:03:49 kube-stack-node-6vgkt9wr flanneld-start[9240]: E0321 20:03:49.058958    9240 watch.go:43] Watch subnets: client: etcd cluster is unavailable or misconfigured
Mar 21 20:03:49 kube-stack-node-6vgkt9wr flanneld-start[9240]: E0321 20:03:49.372808    9240 watch.go:272] Subnet watch failed: client: etcd cluster is unavailable or misconfigured
Mar 21 20:03:50 kube-stack-node-6vgkt9wr flanneld-start[9240]: E0321 20:03:50.059457    9240 watch.go:43] Watch subnets: client: etcd cluster is unavailable or misconfigured
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: curl: (6) Could not resolve host: bootstrap.saltstack.com; Unknown error
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: 2017-03-21 20:03:50,187 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-009 [6]
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-009 [6]
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Failed running /var/lib/cloud/instance/scripts/part-009 [6]
                                                           Traceback (most recent call last):
                                                             File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 619, in runparts
                                                               subp(prefix + [exe_path], capture=False)
                                                             File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 1539, in subp
                                                               cmd=args)
                                                           ProcessExecutionError: Unexpected error while running command.
                                                           Command: ['/var/lib/cloud/instance/scripts/part-009']
                                                           Exit code: 6
                                                           Reason: -
                                                           Stdout: ''
                                                           Stderr: ''
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: 2017-03-21 20:03:50,191 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: 2017-03-21 20:03:50,191 - util.py[WARNING]: Running scripts-user (<module 'cloudinit.config.cc_scripts_user'
from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[WARNING]: Running scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Running scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
                                                           Traceback (most recent call last):
                                                             File "/usr/lib/python2.7/site-packages/cloudinit/stages.py", line 658, in _run_modules
                                                               cc.run(run_name, mod.handle, func_args, freq=freq)
                                                             File "/usr/lib/python2.7/site-packages/cloudinit/cloud.py", line 63, in run
                                                               return self._runners.run(name, functor, args, freq, clear_on_fail)
                                                             File "/usr/lib/python2.7/site-packages/cloudinit/helpers.py", line 197, in run
                                                               results = functor(*args)
                                                             File "/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.py", line 38, in handle
                                                               util.runparts(runparts_path)
                                                             File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 626, in runparts
                                                               % (len(failed), len(attempted)))
                                                           RuntimeError: Runparts: 1 failures in 4 attempted commands
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Writing to /var/lib/cloud/instances/8fa5c106-d869-4c42-bf68-acb185c83f45/sem/config_ssh_authkey_fingerprints - wb: [420] 20 bytes
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/8fa5c106-d869-4c42-bf68-acb185c83f45/sem/config_ssh_authkey_fingerprints (recursive=False)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/8fa5c106-d869-4c42-bf68-acb185c83f45/sem/config_ssh_authkey_fingerprints (recursive=False)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] helpers.py[DEBUG]: Running config-ssh-authkey-fingerprints using lock (<FileLock using file '/var/lib/cloud/instances/8fa5c106-d869-4c42-bf68-acb185c83f45/sem/config_ssh_authkey_fingerprints'>)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] importer.py[DEBUG]: Looking for modules ['cloudinit.mergers.m_list'] that have attributes ['Merger']
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] importer.py[DEBUG]: Found m_list with attributes ['Merger'] in ['cloudinit.mergers.m_list']
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] importer.py[DEBUG]: Looking for modules ['cloudinit.mergers.m_dict'] that have attributes ['Merger']
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] importer.py[DEBUG]: Found m_dict with attributes ['Merger'] in ['cloudinit.mergers.m_dict']
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] importer.py[DEBUG]: Looking for modules ['cloudinit.mergers.m_str'] that have attributes ['Merger']
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] importer.py[DEBUG]: Found m_str with attributes ['Merger'] in ['cloudinit.mergers.m_str']
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] __init__.py[DEBUG]: Merging 'dict' into 'dict' using method '_handle_unknown' of 'LookupMerger: (3)'
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] __init__.py[DEBUG]: Merging using located merger 'DictMerger: (method=no_replace,recurse_str=False,recurse_dict=True,recurse_array=False,allow_delete=False)' since it had method '_on_dict'
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] importer.py[DEBUG]: Looking for modules ['cloudinit.mergers.m_list'] that have attributes ['Merger']
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] importer.py[DEBUG]: Found m_list with attributes ['Merger'] in ['cloudinit.mergers.m_list']
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] importer.py[DEBUG]: Looking for modules ['cloudinit.mergers.m_dict'] that have attributes ['Merger']
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] importer.py[DEBUG]: Found m_dict with attributes ['Merger'] in ['cloudinit.mergers.m_dict']
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] importer.py[DEBUG]: Looking for modules ['cloudinit.mergers.m_str'] that have attributes ['Merger']
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] importer.py[DEBUG]: Found m_str with attributes ['Merger'] in ['cloudinit.mergers.m_str']
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] __init__.py[DEBUG]: Merging 'dict' into 'dict' using method '_handle_unknown' of 'LookupMerger: (3)'
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] __init__.py[DEBUG]: Merging using located merger 'DictMerger: (method=no_replace,recurse_str=False,recurse_dict=True,recurse_array=False,allow_delete=False)' since it had method '_on_dict'
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] importer.py[DEBUG]: Looking for modules ['cloudinit.mergers.m_list'] that have attributes ['Merger']
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] importer.py[DEBUG]: Found m_list with attributes ['Merger'] in ['cloudinit.mergers.m_list']
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] importer.py[DEBUG]: Looking for modules ['cloudinit.mergers.m_dict'] that have attributes ['Merger']
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] importer.py[DEBUG]: Found m_dict with attributes ['Merger'] in ['cloudinit.mergers.m_dict']
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] importer.py[DEBUG]: Looking for modules ['cloudinit.mergers.m_str'] that have attributes ['Merger']
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] importer.py[DEBUG]: Found m_str with attributes ['Merger'] in ['cloudinit.mergers.m_str']
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] __init__.py[DEBUG]: Merging 'dict' into 'dict' using method '_handle_unknown' of 'LookupMerger: (3)'
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] __init__.py[DEBUG]: Merging using located merger 'DictMerger: (method=no_replace,recurse_str=False,recurse_dict=True,recurse_array=False,allow_delete=False)' since it had method '_on_dict'
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Read 4359 bytes from /etc/ssh/sshd_config
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Reading from /home/minion/.ssh/authorized_keys (quiet=False)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Read 395 bytes from /home/minion/.ssh/authorized_keys
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Writing to /var/lib/cloud/instances/8fa5c106-d869-4c42-bf68-acb185c83f45/sem/config_keys_to_console - wb: [420] 20 bytes
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/8fa5c106-d869-4c42-bf68-acb185c83f45/sem/config_keys_to_console (recursive=False)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/8fa5c106-d869-4c42-bf68-acb185c83f45/sem/config_keys_to_console (recursive=False)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] helpers.py[DEBUG]: Running config-keys-to-console using lock (<FileLock using file '/var/lib/cloud/instances/8fa5c106-d869-4c42-bf68-acb185c83f45/sem/config_keys_to_console'>)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Running command ['/usr/libexec/cloud-init/write-ssh-key-fingerprints', '', 'ssh-dss'] with allowed return codes [0] (shell=False, capture=True)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr flanneld-start[9240]: E0321 20:03:50.373305    9240 watch.go:272] Subnet watch failed: client: etcd cluster is unavailable or misconfigured
Mar 21 20:03:50 kube-stack-node-6vgkt9wr ec2[9352]:
Mar 21 20:03:50 kube-stack-node-6vgkt9wr ec2[9352]: #############################################################
Mar 21 20:03:50 kube-stack-node-6vgkt9wr ec2[9352]: -----BEGIN SSH HOST KEY FINGERPRINTS-----
Mar 21 20:03:50 kube-stack-node-6vgkt9wr ec2[9352]: 256 c8:2d:56:d5:03:ed:2e:27:b7:d7:49:64:2a:3c:ef:c4   (ECDSA)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr ec2[9352]: 256 30:65:95:39:44:85:e3:ca:0d:f2:d1:20:c7:a9:b4:5e   (ED25519)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr ec2[9352]: 2048 e6:7d:8b:52:c9:24:05:81:2a:9f:60:ef:f4:9a:eb:05   (RSA)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr ec2[9352]: -----END SSH HOST KEY FINGERPRINTS-----
Mar 21 20:03:50 kube-stack-node-6vgkt9wr ec2[9352]: #############################################################
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Writing to /var/lib/cloud/instances/8fa5c106-d869-4c42-bf68-acb185c83f45/sem/config_phone_home - wb: [420] 20 bytes
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/8fa5c106-d869-4c42-bf68-acb185c83f45/sem/config_phone_home (recursive=False)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/8fa5c106-d869-4c42-bf68-acb185c83f45/sem/config_phone_home (recursive=False)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] helpers.py[DEBUG]: Running config-phone-home using lock (<FileLock using file '/var/lib/cloud/instances/8fa5c106-d869-4c42-bf68-acb185c83f45/sem/config_phone_home'>)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] cc_phone_home.py[DEBUG]: Skipping module named phone-home, no 'phone_home' configuration found
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] helpers.py[DEBUG]: Running config-final-message using lock (<cloudinit.helpers.DummyLock object at 0x1f15bd0>)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Read 14 bytes from /proc/uptime
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Cloud-init v. 0.7.5 finished at Tue, 21 Mar 2017 20:03:50 +0000. Datasource DataSourceOpenStack [net,ver=2].  Up 909.87 seconds
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [420] 52 bytes
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: Cloud-init v. 0.7.5 finished at Tue, 21 Mar 2017 20:03:50 +0000. Datasource DataSourceOpenStack [net,ver=2].
 Up 909.87 seconds
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/8fa5c106-d869-4c42-bf68-acb185c83f45/boot-finished (recursive=False)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/8fa5c106-d869-4c42-bf68-acb185c83f45/boot-finished (recursive=False)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] cloud-init[DEBUG]: Ran 9 modules with 1 failures
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: Read 14 bytes from /proc/uptime
Mar 21 20:03:50 kube-stack-node-6vgkt9wr cloud-init[4643]: [CLOUDINIT] util.py[DEBUG]: cloud-init mode 'modules' took 73.307 seconds (878.79)
Mar 21 20:03:50 kube-stack-node-6vgkt9wr systemd[1]: cloud-final.service: main process exited, code=exited, status=1/FAILURE
Mar 21 20:03:50 kube-stack-node-6vgkt9wr systemd[1]: Failed to start Execute cloud user/final scripts.
Mar 21 20:03:50 kube-stack-node-6vgkt9wr systemd[1]: Unit cloud-final.service entered failed state.
Mar 21 20:03:50 kube-stack-node-6vgkt9wr systemd[1]: cloud-final.service failed.
Mar 21 20:03:50 kube-stack-node-6vgkt9wr systemd[1]: Reached target Multi-User System.
Mar 21 20:03:50 kube-stack-node-6vgkt9wr systemd[1]: Starting Multi-User System.
Mar 21 20:03:50 kube-stack-node-6vgkt9wr systemd[1]: Starting Update UTMP about System Runlevel Changes...
Mar 21 20:03:50 kube-stack-node-6vgkt9wr systemd[1]: Started Update UTMP about System Runlevel Changes.
Mar 21 20:03:50 kube-stack-node-6vgkt9wr systemd[1]: Startup finished in 1.414s (kernel) + 1.123s (initrd) + 15min 7.364s (userspace) = 15min 9.902s. 
```

Tried with two and three nodes but the error always appears on the second node.

Also I had to add some missing parameters in the documentation from https://kubernetes.io/docs/getting-started-guides/openstack-heat/

* The versions of Openstack clients described in the page do not work with Mitaka (never tested on earlier releases). Had to remove the version enforcement and it works.
* Had to add FIXED_NETWORK_CIDR otherwise delpoyment misses a Heat parameter

**What you expected to happen**: Successful deployment

**How to reproduce it** (as minimally and precisely as possible): Download 1.5.4 version and deploy on Openstack Mitaka using CentOS 7.3 image.

**Anything else we need to know**:
One of the nodes always installs correctly.

**Comment by dims** [comment]
Heat support is now deprecated - https://github.com/kubernetes/website/pull/5670

/close
