### ISSUE TITLE
nrpe hook failures in kubernetes-worker charm

### ISSUE THREAD

**Issue by jacekn** [kubernetes/kubernetes#44322]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): "nrpe"

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): N/A

**Environment**:
- **Cloud provider or hardware configuration**: OpenStack
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.2 LTS
- **Kernel** (e.g. `uname -a`): 4.4.0-71-generic
- **Install tools**: juju
- **Others**:

**What happened**:

I deployed kubernetes-worker using https://jujucharms.com/u/containers/kubernetes-worker/21 charm and related it to nrpe subordinate for monitoring. This resulted in hook failures:
hook failed: "nrpe-external-master-relation-joined" for nrpe:nrpe-external-master

And the following traceback in the logs:
````
Traceback (most recent call last):
  File "./hooks/nrpe-external-master-relation-joined", line 19, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/__init__.py", line 78, in main
    bus.dispatch()
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 434, in dispatch
    _invoke(other_handlers)
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 417, in _invoke
    handler.invoke()
  File "/usr/local/lib/python3.5/dist-packages/charms/reactive/bus.py", line 291, in invoke
    self._action(*args)
  File "/var/lib/juju/agents/unit-kubernetes-worker-0/charm/reactive/kubernetes_worker.py", line 601, in initial_nrpe_config
    update_nrpe_config(nagios)
  File "/var/lib/juju/agents/unit-kubernetes-worker-0/charm/reactive/kubernetes_worker.py", line 614, in update_nrpe_config
    nrpe.add_init_service_checks(nrpe_setup, services, current_unit)
  File "/usr/local/lib/python3.5/dist-packages/charmhelpers/contrib/charmsupport/nrpe.py", line 361, in add_init_service_checks
    check_cmd='check_systemd.py %s' % svc
  File "/usr/local/lib/python3.5/dist-packages/charmhelpers/contrib/charmsupport/nrpe.py", line 258, in add_check
    self.checks.append(Check(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/charmhelpers/contrib/charmsupport/nrpe.py", line 148, in __init__
    Check.shortname_re))
charmhelpers.contrib.charmsupport.nrpe.CheckException: shortname must match [A-Za-z0-9-_]+$
````

**What you expected to happen**:

I expected monitoring to be set up

**How to reproduce it** (as minimally and precisely as possible):

juju deploy cs:~containers/kubernetes-worker-21
juju deploy cs:nrpe
juju add-relation nrpe:nrpe-external-master kubernetes-worker:nrpe-external-master

**Anything else we need to know**:

**Comment by tvansteenburgh** [comment]
I think the problem is this line in kubernetes_worker.py:608:

```python
services = ('snap.kubelet.daemon', 'snap.kube-proxy.daemon')
```

I don't think these service names are allowed to have '.' characters.

**Comment by jacekn** [comment]
kubernetes-master has similar problem

**Comment by jacekn** [comment]
I can confirm that this problem is no longer affecting latest released charms.
