### ISSUE TITLE
pull-kubernetes-e2e-gce-etcd3 failed test run

### ISSUE THREAD

**Issue by verb** [kubernetes/kubernetes#45135]
CalledProcessError with no output:

```
W0428 10:59:04.757] ERROR: (gcloud.compute.copy-files) [/usr/bin/scp] exited with return code [1].
W0428 10:59:04.758] See https://cloud.google.com/compute/docs/troubleshooting#ssherrors for troubleshooting hints.
I0428 10:59:04.858] Dumping node logs to /workspace/_artifacts
I0428 10:59:08.351] Changing logfiles to be world-readable for download
I0428 10:59:08.428] Changing logfiles to be world-readable for download
I0428 10:59:08.551] Changing logfiles to be world-readable for download
I0428 10:59:08.724] Changing logfiles to be world-readable for download
... skipping 13 lines ...
W0428 10:59:12.271] scp: /var/log/fluentd.log*: No such file or directory
W0428 10:59:12.271] scp: /var/log/node-problem-detector.log*: No such file or directory
W0428 10:59:12.276] scp: /var/log/supervisor/kubelet-stdout.log*: No such file or directory
W0428 10:59:12.276] scp: /var/log/supervisor/kubelet-stderr.log*: No such file or directory
W0428 10:59:12.276] scp: /var/log/supervisor/docker-stdout.log*: No such file or directory
W0428 10:59:12.276] scp: /var/log/supervisor/docker-stderr.log*: No such file or directory
W0428 10:59:12.279] ERROR: (gcloud.compute.copy-files) [/usr/bin/scp] exited with return code [1].
W0428 10:59:12.279] See https://cloud.google.com/compute/docs/troubleshooting#ssherrors for troubleshooting hints.
W0428 10:59:12.328] 2017/04/28 10:59:12 util.go:131: Step './cluster/log-dump.sh /workspace/_artifacts' finished in 23.155910025s
W0428 10:59:12.329] 2017/04/28 10:59:12 util.go:129: Running: ./hack/e2e-internal/e2e-down.sh
W0428 10:59:12.364] Project: k8s-jkns-pr-gce-etcd3
W0428 10:59:12.364] Zone: us-central1-f
I0428 10:59:12.465] Shutting down test cluster in background.
... skipping 25 lines ...
I0428 11:04:29.125] Property "users.k8s-jkns-pr-gce-etcd3_e2e-gce-agent-pr-72-0-basic-auth" unset.
I0428 11:04:29.290] Property "contexts.k8s-jkns-pr-gce-etcd3_e2e-gce-agent-pr-72-0" unset.
I0428 11:04:29.292] Cleared config for k8s-jkns-pr-gce-etcd3_e2e-gce-agent-pr-72-0 from /workspace/.kube/config
I0428 11:04:29.292] Done
W0428 11:04:29.393] 2017/04/28 11:04:29 util.go:131: Step './hack/e2e-internal/e2e-down.sh' finished in 5m16.965614636s
W0428 11:04:29.393] 2017/04/28 11:04:29 main.go:159: Saved XML output to /workspace/_artifacts/junit_runner.xml.
W0428 11:04:29.393] 2017/04/28 11:04:29 main.go:193: Something went wrong: starting e2e cluster: error during ./hack/e2e-internal/e2e-up.sh: exit status 1
W0428 11:04:29.393] +(/workspace/e2e-runner.sh:1): main(): chmod -R o+r /workspace/_artifacts
I0428 11:04:30.242] Starting pull-kubernetes-e2e-gce-etcd3-27780...
W0428 11:04:30.321] Traceback (most recent call last):
W0428 11:04:30.321]   File "/var/lib/jenkins/workspace/pull-kubernetes-e2e-gce-etcd3/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 453, in <module>
W0428 11:04:30.322]     main(create_parser().parse_args())
W0428 11:04:30.322]   File "/var/lib/jenkins/workspace/pull-kubernetes-e2e-gce-etcd3/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 383, in main
... skipping 2 lines ...
W0428 11:04:30.322]     check(*cmd)
W0428 11:04:30.322]   File "/var/lib/jenkins/workspace/pull-kubernetes-e2e-gce-etcd3/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 40, in check
W0428 11:04:30.322]     subprocess.check_call(cmd)
W0428 11:04:30.322]   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
W0428 11:04:30.322]     raise CalledProcessError(retcode, cmd)
W0428 11:04:30.323] subprocess.CalledProcessError: Command '('docker', 'run', '--rm', '--name=pull-kubernetes-e2e-gce-etcd3-27780', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-e2e-gce-etcd3/go/src/k8s.io/kubernetes/_artifacts:/workspace/_artifacts', '-v', '/etc/localtime:/etc/localtime:ro', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-e', 'HOME=/workspace', '-e', 'WORKSPACE=/workspace', '--env-file', '/var/lib/jenkins/workspace/pull-kubernetes-e2e-gce-etcd3/./test-infra/jenkins/../scenarios/../platforms/gce.env', '--env-file', '/var/lib/jenkins/workspace/pull-kubernetes-e2e-gce-etcd3/./test-infra/jenkins/../scenarios/../jobs/pull-kubernetes-e2e.env', '--env-file', '/var/lib/jenkins/workspace/pull-kubernetes-e2e-gce-etcd3/./test-infra/jenkins/../scenarios/../jobs/pull-kubernetes-e2e-gce-etcd3.env', '-v', '/home/jenkins/.ssh/google_compute_engine:/workspace/.ssh/google_compute_engine:ro', '-v', '/home/jenkins/.ssh/google_compute_engine.pub:/workspace/.ssh/google_compute_engine.pub:ro', '-e', 'JENKINS_GCE_SSH_PRIVATE_KEY_FILE=/workspace/.ssh/google_compute_engine', '-e', 'JENKINS_GCE_SSH_PUBLIC_KEY_FILE=/workspace/.ssh/google_compute_engine.pub', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-e2e-gce-etcd3@tmp/secretFiles/bf94a5da-9a72-4d69-a490-db7a50257cdc/kubernetes-jenkins-pull-c67f9519f993.json:/service-account.json:ro', '-e', 'GOOGLE_APPLICATION_CREDENTIALS=/service-account.json', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-e2e-gce-etcd3/go/src/k8s.io/kubernetes:/go/src/k8s.io/kubernetes', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-e2e-gce-etcd3/go/src/k8s.io/release:/go/src/k8s.io/release', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-e2e-gce-etcd3/go/src/k8s.io/release:/go/src/k8s.io/release', '-e', 'JENKINS_HOME=/var/lib/jenkins', '-e', 'BUILD_CAUSE=MANUALTRIGGER', '-e', 'PULL_BASE_REF=master', '-e', 'HUDSON_URL=http://goto.google.com/prkubekins/', '-e', 'BUILD_URL=http://goto.google.com/prkubekins/job/pull-kubernetes-e2e-gce-etcd3/27780/', '-e', 'BOOTSTRAP_MIGRATION=yes', '-e', 'CLOUDSDK_CONFIG=/var/lib/jenkins/workspace/pull-kubernetes-e2e-gce-etcd3/go/src/k8s.io/kubernetes/.config/gcloud', '-e', 'BUILD_TAG=jenkins-pull-kubernetes-e2e-gce-etcd3-27780', '-e', 'HUDSON_SERVER_COOKIE=32617aabcc4952a0', '-e', 'JENKINS_URL=http://goto.google.com/prkubekins/', '-e', 'LOGNAME=jenkins', '-e', 'USER=jenkins', '-e', 'JOB_NAME=pull-kubernetes-e2e-gce-etcd3', '-e', 'LANG=en_US.UTF-8', '-e', 'SHELL=/bin/bash', '-e', 'buildId=423faecb-2c36-11e7-95a3-0a580a6c00c3', '-e', 'HUDSON_HOME=/var/lib/jenkins', '-e', 'NODE_LABELS=agent-pr-72 pull', '-e', 'JOB_URL=http://goto.google.com/prkubekins/job/pull-kubernetes-e2e-gce-etcd3/', '-e', 'ROOT_BUILD_CAUSE_MANUALTRIGGER=true', '-e', 'BUILD_CAUSE_MANUALTRIGGER=true', '-e', 'JENKINS_AWS_CREDENTIALS_FILE=/var/lib/jenkins/workspace/pull-kubernetes-e2e-gce-etcd3@tmp/secretFiles/936b62f1-4bfc-480c-b800-674be1a87e67/KubernetesPresubmitTests.txt', '-e', 'ROOT_BUILD_CAUSE=MANUALTRIGGER', '-e', 'SSH_CLIENT=10.240.0.2 44178 22', '-e', 'BUILD_ID=27780', '-e', 'BUILD_NUMBER=27780', '-e', 'HUDSON_COOKIE=75e6a1a2-8842-475e-aed0-abfaf53f5e6c', '-e', 'JENKINS_AWS_SSH_PRIVATE_KEY_FILE=/var/lib/jenkins/workspace/pull-kubernetes-e2e-gce-etcd3@tmp/secretFiles/3afea9ab-6d75-48d3-9d8c-9b41a5fc8b58/id_rsa.jenkins', '-e', 'JENKINS_GCE_SSH_PRIVATE_KEY_FILE=/home/jenkins/.ssh/google_compute_engine', '-e', 'JOB_BASE_NAME=pull-kubernetes-e2e-gce-etcd3', '-e', 'NLSPATH=/usr/dt/lib/nls/msg/%L/%N.cat', '-e', 'JENKINS_GCE_SSH_PUBLIC_KEY_FILE=/home/jenkins/.ssh/google_compute_engine.pub', '-e', '_=./test-infra/jenkins/bootstrap.py', '-e', 'JENKINS_AWS_SSH_PUBLIC_KEY_FILE=/var/lib/jenkins/workspace/pull-kubernetes-e2e-gce-etcd3@tmp/secretFiles/f7ec79f2-5fba-4d56-a34b-31f69b94cf58/id_rsa.jenkins.pub', '-e', 'EXECUTOR_NUMBER=0', '-e', 'NODE_NAME=agent-pr-72', '-e', 'PULL_NUMBER=41583', '-e', 'SHLVL=2', '-e', 'JENKINS_SERVER_COOKIE=32617aabcc4952a0', '-e', 'BUILD_DISPLAY_NAME=#27780', '-e', 'PULL_REFS=master:dbce213ea6ced9b93123a6d82833aca9197b59a5,41583:d22dd0fa357fabe8fc0b97a5216ee18190676fef', '-e', 'XFILESEARCHPATH=/usr/dt/app-defaults/%L/Dt', '-e', 'MAIL=/var/mail/jenkins', '-e', 'SSH_CONNECTION=10.240.0.2 44178 10.240.0.82 22', '-e', 'CLOUDSDK_COMPONENT_MANAGER_DISABLE_UPDATE_CHECK=true', '-e', 'CLOUDSDK_EXPERIMENTAL_FAST_COMPONENT_UPDATE=false', '-e', 'E2E_UP=true', '-e', 'E2E_TEST=true', '-e', 'E2E_DOWN=true', '-e', 'E2E_NAME=e2e-gce-agent-pr-72-0', '-e', 'KUBE_AWS_INSTANCE_PREFIX=e2e-gce-agent-pr-72-0', '-e', 'INSTANCE_PREFIX=e2e-gce-agent-pr-72-0', '-e', 'KUBE_GCE_NETWORK=e2e-gce-agent-pr-72-0', '-e', 'KUBE_GCE_INSTANCE_PREFIX=e2e-gce-agent-pr-72-0', '-e', 'CLUSTER_NAME=e2e-gce-agent-pr-72-0', '-e', 'KUBE_GKE_NETWORK=e2e-gce-agent-pr-72-0', 'gcr.io/k8s-testimages/kubekins-e2e:v20170421-c719a74d', '--build', '--stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce-etcd3')' returned non-zero exit status 1
E0428 11:04:30.324] Build failed
I0428 11:04:30.324] process 12992 exited with code 1 after 46.8m
E0428 11:04:30.324] FAIL: pull-kubernetes-e2e-gce-etcd3
```

full log: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41583/pull-kubernetes-e2e-gce-etcd3/27780/?log#log
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41583/pull-kubernetes-e2e-gce-etcd3/27780/

**Comment by mml** [comment]
Despite the name of the suite, this flake is due to the cluster not getting 5 healthy nodes in time.  Has nothing to do with etcd.

```
I0428 10:58:48.942] [0;33mDetected 4 ready nodes, found 4 nodes out of expected 5. Your cluster may not be fully functional.[0m
```

I'll file a test-infra bug to have this reported more clearly.

**Comment by mml** [comment]
@verb Thanks for the report.  In this case just re-run the test.  This kind of flake is inherent in the nature of the e2e test.

**Comment by verb** [comment]
@mml We have to do better. This cannot be inherent in the nature of the e2e test. I literally have to run tests 2-3 times every time I upload a change. It makes me not want to contribute.
