### ISSUE TITLE
The cross-build is broken

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#45554]
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-cross-build/

I wonder why there is no auto-filed issue for this @ixdy 

#44895 broke the crossbuild: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-cross-build/1683/
```
I0509 09:36:49.941] +++ [0509 09:36:49] Building go targets for {linux/amd64 linux/arm linux/arm64 linux/s390x linux/ppc64le windows/amd64} in parallel (output will appear in a burst when complete):
I0509 09:36:49.941]     cmd/kube-proxy
I0509 09:36:49.941]     cmd/kubelet
I0509 09:37:49.342] +++ [0509 09:36:50] linux/amd64: go build started
I0509 09:37:49.343] +++ [0509 09:37:10] linux/amd64: go build finished
I0509 09:37:49.352] +++ [0509 09:36:50] linux/arm: go build started
I0509 09:37:49.352] +++ [0509 09:37:10] linux/arm: go build finished
I0509 09:37:49.352] +++ [0509 09:36:50] linux/arm64: go build started
I0509 09:37:49.352] +++ [0509 09:37:11] linux/arm64: go build finished
I0509 09:37:49.352] +++ [0509 09:36:50] linux/s390x: go build started
I0509 09:37:49.353] +++ [0509 09:37:11] linux/s390x: go build finished
I0509 09:37:49.353] +++ [0509 09:36:50] linux/ppc64le: go build started
I0509 09:37:49.353] +++ [0509 09:37:11] linux/ppc64le: go build finished
I0509 09:37:49.353] +++ [0509 09:36:50] windows/amd64: go build started
I0509 09:37:49.354] # k8s.io/kubernetes/pkg/util/iptables
I0509 09:37:49.354] pkg/util/iptables/iptables.go:391: undefined: syscall.Flock
I0509 09:37:49.354] pkg/util/iptables/iptables.go:391: undefined: syscall.LOCK_EX
I0509 09:37:49.354] pkg/util/iptables/iptables.go:391: undefined: syscall.LOCK_NB
I0509 09:37:49.354] !!! [0509 09:37:49] Call tree:
I0509 09:37:49.355] !!! [0509 09:37:49]  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:691 kube::golang::build_binaries_for_platform(...)
I0509 09:37:49.355] !!! [0509 09:37:49]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
I0509 09:37:49.355] Makefile:89: recipe for target 'all' failed
I0509 09:37:49.355] Makefile:395: recipe for target 'cross' failed
W0509 09:37:49.456] !!! [0509 09:37:49] Call tree:
W0509 09:37:49.456] !!! [0509 09:37:49]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
W0509 09:37:49.456] make[1]: *** [all] Error 1
W0509 09:37:49.456] make: *** [cross] Error 1
W0509 09:37:49.890] !!! [0509 09:37:49] Call tree:
W0509 09:37:49.892] !!! [0509 09:37:49]  1: build/../build/common.sh:513 kube::build::run_build_command_ex(...)
W0509 09:37:49.893] !!! [0509 09:37:49]  2: build/release.sh:36 kube::build::run_build_command(...)
W0509 09:37:49.894] make: *** [release] Error 1
W0509 09:37:49.895] Traceback (most recent call last):
W0509 09:37:49.895]   File "/var/lib/jenkins/workspace/ci-kubernetes-cross-build/./test-infra/jenkins/../scenarios/kubernetes_build.py", line 85, in <module>
W0509 09:37:49.895]     main(ARGS)
W0509 09:37:49.895]   File "/var/lib/jenkins/workspace/ci-kubernetes-cross-build/./test-infra/jenkins/../scenarios/kubernetes_build.py", line 60, in main
W0509 09:37:49.896]     check(args.script)
W0509 09:37:49.896]   File "/var/lib/jenkins/workspace/ci-kubernetes-cross-build/./test-infra/jenkins/../scenarios/kubernetes_build.py", line 31, in check
W0509 09:37:49.896]     subprocess.check_call(cmd)
W0509 09:37:49.896]   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
W0509 09:37:49.896]     raise CalledProcessError(retcode, cmd)
W0509 09:37:49.896] subprocess.CalledProcessError: Command '('./hack/jenkins/build.sh',)' returned non-zero exit status 2
I0509 09:37:49.902] Makefile:358: recipe for target 'release' failed
E0509 09:37:49.902] Build failed
I0509 09:37:49.902] process 15245 exited with code 1 after 20.7m
E0509 09:37:49.902] FAIL: ci-kubernetes-cross-build
I0509 09:37:49.902] Upload result and artifacts...
```

@kubernetes/sig-testing-bugs FYI

@dcbw @thockin @smarterclayton @lavalamp @vishh

**Comment by ixdy** [comment]
it seems like the triage tool is behind by a day.

**Comment by k82cn** [comment]
I think it's because the following error, the `syscall.Flock` are not available in windows.

```
I0509 09:37:49.353] +++ [0509 09:36:50] windows/amd64: go build started
I0509 09:37:49.354] # k8s.io/kubernetes/pkg/util/iptables
I0509 09:37:49.354] pkg/util/iptables/iptables.go:391: undefined: syscall.Flock
I0509 09:37:49.354] pkg/util/iptables/iptables.go:391: undefined: syscall.LOCK_EX
I0509 09:37:49.354] pkg/util/iptables/iptables.go:391: undefined: syscall.LOCK_NB
```

**Comment by luxas** [comment]
@ixdy strange thing is that the regression happened 5/5 and still yesterday no issue was filed

**Comment by ixdy** [comment]
ah, apparently the triage tool doesn't look at the cross-build job? https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=.*cross.*

not sure if this is expected behavior - cc @cjwagner @rmmh

**Comment by rmmh** [comment]
The cross build doesn't create any JUnit output, so our tooling doesn't catch it at all. I can improve that to inject a dummy test failure for jobs that fail with no test results.

**Comment by luxas** [comment]
@rmmh Thanks, that'd be helpful.

I know we've had auto-filed issues for this kind of job before, but it seems to have gone away when renaming the job or something...

**Comment by fejta** [comment]
@kubernetes/sig-network-test-failures 
/assign @bowei 

Not 100% sure who owns the proxy package, but it (along with the iptables issue) smells like networking to me. Can we get someone from sig-network to review https://github.com/kubernetes/kubernetes/pull/45642?

Thanks for highlighting Jago, removing the testing label because the test results appear to be correct here (we really can't build the windows version)
/remove-sig testing

**Comment by bowei** [comment]
@dcbw -- is there a way to stub out the code using build constraints? (https://golang.org/pkg/go/build/#hdr-Build_Constraints)

**Comment by ixdy** [comment]
@bowei yeah we do things like this in a variety of places, see e.g. `pkg/util/resourcecontainer/resource_container_linux.go` and `pkg/util/resourcecontainer/resource_container_unsupported.go`, or the `pkg/kubelet/cadvisor` package, or a variety of other places.

**Comment by ixdy** [comment]
For this particular example, maybe just use `pkg/util/flock`?

**Comment by bowei** [comment]
oh nice -- sending PR

**Comment by bowei** [comment]
n/m -- looks like there is one already on its way

**Comment by rmmh** [comment]
I think both #45601 and #45642 are required.
