### ISSUE TITLE
client-go unit test failure

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#45693]
https://github.com/kubernetes/test-infra/pull/2735 is sent as a fix.

```
--- FAIL: TestRoundTrip (0.00s)
panic: fuzzFunc's second parameter must be type fuzz.Continue [recovered]
	panic: fuzzFunc's second parameter must be type fuzz.Continue

goroutine 6 [running]:
panic(0xa65dc0, 0xc4203fdc70)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc4200963c0)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0xa65dc0, 0xc4203fdc70)
	/usr/local/go/src/runtime/panic.go:458 +0x243
k8s.io/apimachinery/vendor/github.com/google/gofuzz.(*Fuzzer).Funcs(0xc42032b0b0, 0xc42006db00, 0xa, 0x10, 0xc420458000)
	/go-workspace/src/k8s.io/apimachinery/vendor/github.com/google/gofuzz/fuzz.go:90 +0x36c
k8s.io/apimachinery/pkg/api/testing.FuzzerFor(0xc42006db00, 0xa, 0x10, 0xe8b3a0, 0xc420458000, 0xc42006db00)
	/go-workspace/src/k8s.io/apimachinery/pkg/api/testing/fuzzer.go:137 +0x9c
k8s.io/client-go/examples/third-party-resources/apis/tpr/v1.TestRoundTrip(0xc4200963c0)
	/go-workspace/src/k8s.io/client-go/examples/third-party-resources/apis/tpr/v1/types_test.go:59 +0x269
testing.tRunner(0xc4200963c0, 0xbc3a60)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec
FAIL	k8s.io/client-go/examples/third-party-resources/apis/tpr/v1
```

cc @sttts 

It's a test failure reported by the publishing robot.

**Comment by caesarxuchao** [comment]
The line it fails at: https://github.com/google/gofuzz/blob/master/fuzz.go#L90

**Comment by caesarxuchao** [comment]
It looks like a vendor copy vs gopath copy issue.

**Comment by caesarxuchao** [comment]
One possible fix is removing github.com/google/gofuzz from the vendor/ directory.

**Comment by caesarxuchao** [comment]
Confirmed removing github.com/google/gofuzz from the vendor/ directory fixed the test in robot.

**Comment by caesarxuchao** [comment]
We need to add the "issue filer" feature to the publishing robot, we can't rely on @MikeSpreitzer to report robot issues everytime :P

I'm just not sure how long the publishing robot will be needed (i.e., when we will get rid of the staging/ directory) so not sure whether we should invest more time on the robot.
