### ISSUE TITLE
ResourceUsageGatherer panics in scalability tests

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#46198]
Example:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scalability/2405

```
I0521 22:50:08.062] May 21 22:50:08.061: INFO: Closing worker for e2e-scalability-minion-group-hjmj
I0521 22:50:08.062] E0521 22:50:08.061857    6620 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
I0521 22:50:08.062] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
I0521 22:50:08.062] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
I0521 22:50:08.062] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
I0521 22:50:08.062] /usr/local/go_k8s_patched/src/runtime/asm_amd64.s:514
I0521 22:50:08.062] /usr/local/go_k8s_patched/src/runtime/panic.go:489
I0521 22:50:08.063] /usr/local/go_k8s_patched/src/runtime/panic.go:63
I0521 22:50:08.063] /usr/local/go_k8s_patched/src/runtime/signal_unix.go:290
I0521 22:50:08.063] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/kubelet_stats.go:373
I0521 22:50:08.063] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/kubelet_stats.go:397
I0521 22:50:08.063] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/resource_usage_gatherer.go:159
I0521 22:50:08.063] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/resource_usage_gatherer.go:182
I0521 22:50:08.063] /usr/local/go_k8s_patched/src/runtime/asm_amd64.s:2197
I0521 22:50:08.064] panic: runtime error: invalid memory address or nil pointer dereference [recovered]
I0521 22:50:08.064] 	panic: runtime error: invalid memory address or nil pointer dereference
I0521 22:50:08.064] [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x230c29a]
I0521 22:50:08.065] 
I0521 22:50:08.065] goroutine 180 [running]:
I0521 22:50:08.065] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
I0521 22:50:08.065] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
I0521 22:50:08.065] panic(0x2f40340, 0x4f7c940)
I0521 22:50:08.066] 	/usr/local/go_k8s_patched/src/runtime/panic.go:489 +0x2cf
I0521 22:50:08.066] k8s.io/kubernetes/test/e2e/framework.getOneTimeResourceUsageOnNode.func1(0xc4248d4960, 0x2e, 0xc424711620, 0x348b8ce)
I0521 22:50:08.066] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/kubelet_stats.go:373 +0x2a
I0521 22:50:08.066] k8s.io/kubernetes/test/e2e/framework.getOneTimeResourceUsageOnNode(0x4fde720, 0xc4211e7680, 0xc4207a0e70, 0x21, 0x37e11d600, 0xc424753d58, 0xc420e97ed8, 0xc420a1f5c0, 0xc4226f8480)
I0521 22:50:08.066] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/kubelet_stats.go:397 +0x4d0
I0521 22:50:08.066] k8s.io/kubernetes/test/e2e/framework.(*resourceGatherWorker).singleProbe(0xc4211e93e8)
I0521 22:50:08.066] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/resource_usage_gatherer.go:159 +0x38c
I0521 22:50:08.066] k8s.io/kubernetes/test/e2e/framework.(*resourceGatherWorker).gather(0xc4211e93e8, 0x6c706bafd)
I0521 22:50:08.066] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/resource_usage_gatherer.go:182 +0x2b4
I0521 22:50:08.067] created by k8s.io/kubernetes/test/e2e/framework.(*containerResourceGatherer).getKubeSystemContainersResourceUsage
I0521 22:50:08.067] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/resource_usage_gatherer.go:199 +0xa2
I0521 22:50:08.080] 
```

@kubernetes/sig-scalability-bugs

**Comment by gmarek** [comment]
It seems that there's some bug in processing Stats from SummaryAPI that I wrote recently. Segfault is in the logic that tries to get CPU infro from `ContainerStats`, which is unset. @piosz - is this expected behavior?

For the time being I'll add more logging to make sure that this is indeed the problem, and try to understand circumstances when it happens. I'll send the proper fix only after understanding the problem more.

**Comment by piosz** [comment]
AFAIK there is a possibility that CPU hasn't been yet collected.

@dashpole @timstclair who knows it better.

**Comment by timstclair** [comment]
Yes, the CPU stats are always collected with the container stats, but it's possible to request the stats in a window where kubelet knows about the container, but cAdvisor hasn't yet gathered any info on it.

**Comment by wojtek-t** [comment]
@timstclair - thanks!
@gmarek - can you please fix that so that our takes will not panic?
