### ISSUE TITLE
Flake: pull-kubernetes-federation-e2e-gce: error during ./federation/cluster/federation-up.sh: exit status 124

### ISSUE THREAD

**Issue by tnozicka** [kubernetes/kubernetes#46690]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46500/pull-kubernetes-federation-e2e-gce/7569/

```
W0531 00:40:45.381] 2017/05/31 00:40:45 util.go:129: Running: ./federation/cluster/federation-up.sh
W0531 00:40:45.443] Project: k8s-jkns-pr-bldr-e2e-gce-fdrtn
W0531 00:40:45.443] Zone: us-central1-f
I0531 00:40:45.544] +++ [0531 00:40:45] Deploying federation control plane for e2e-f8n-agent-pr-63-0 in cluster federation-e2e-gce-us-central1-f
I0531 00:40:45.544] +++ [0531 00:40:45] DNS_ZONE_NAME: "pr-bldr.test-f8n.k8s.io.", DNS_PROVIDER: "google-clouddns"
I0531 00:40:45.544] +++ [0531 00:40:45] Image: "gcr.io/k8s-jkns-pr-bldr-e2e-gce-fdrtn/hyperkube-amd64:v1.7.0-alpha.4.837_4c654571549f99"
I0531 00:40:45.630] Creating a namespace f8n-system-agent-pr-63-0 for federation system components... done
I0531 01:00:45.530] Creating federation control plane service..................................................................................................................Dumping Federation and DNS pod logs to /workspace/_artifacts
W0531 01:00:45.632] I0531 00:40:45.608190    3500 init.go:287] Creating a namespace f8n-system-agent-pr-63-0 for federation system components
W0531 01:00:45.632] I0531 00:40:45.630002    3500 init.go:296] Creating federation control plane service
W0531 01:00:45.632] 2017/05/31 01:00:45 util.go:131: Step './federation/cluster/federation-up.sh' finished in 20m0.094954274s
W0531 01:00:45.632] 2017/05/31 01:00:45 e2e.go:410: Dumping Federation logs to: /workspace/_artifacts
W0531 01:00:45.632] 2017/05/31 01:00:45 util.go:129: Running: ./federation/cluster/log-dump.sh /workspace/_artifacts
W0531 01:00:45.632] Project: k8s-jkns-pr-bldr-e2e-gce-fdrtn
W0531 01:00:45.632] Zone: us-central1-f
W0531 01:00:46.979] Unable to connect to the server: x509: certificate signed by unknown authority
W0531 01:00:47.097] Unable to connect to the server: x509: certificate signed by unknown authority
W0531 01:00:47.100] 2017/05/31 01:00:47 util.go:131: Step './federation/cluster/log-dump.sh /workspace/_artifacts' finished in 1.631920175s
W0531 01:00:47.100] 2017/05/31 01:00:47 util.go:129: Running: ./federation/cluster/federation-down.sh
W0531 01:00:47.146] Project: k8s-jkns-pr-bldr-e2e-gce-fdrtn
W0531 01:00:47.147] Zone: us-central1-f
W0531 01:00:47.332] error: context "e2e-f8n-agent-pr-63-0" does not exist
I0531 01:00:47.433] Cleaning Federation control plane objects
W0531 01:00:47.534] Unable to connect to the server: x509: certificate signed by unknown authority
W0531 01:00:47.707] Unable to connect to the server: x509: certificate signed by unknown authority
W0531 01:00:47.889] Unable to connect to the server: x509: certificate signed by unknown authority
I0531 01:00:48.068] +++ [0531 01:00:48] Waiting for 2 minutes to allow controllers to clean up federation components...
W0531 01:02:48.072] 2017/05/31 01:02:48 util.go:131: Step './federation/cluster/federation-down.sh' finished in 2m0.971565169s
W0531 01:02:48.073] 2017/05/31 01:02:48 none.go:41: Noop Down()
W0531 01:02:48.073] 2017/05/31 01:02:48 main.go:161: Saved XML output to /workspace/_artifacts/junit_runner.xml.
W0531 01:02:48.073] 2017/05/31 01:02:48 main.go:195: Something went wrong: error starting federation: error during ./federation/cluster/federation-up.sh: exit status 124
W0531 01:02:48.074] +(/workspace/e2e-runner.sh:1): main(): chmod -R o+r /workspace/_artifacts
I0531 01:02:48.987] Starting pull-kubernetes-federation-e2e-gce-7569...
W0531 01:02:49.026] Traceback (most recent call last):
W0531 01:02:49.026]   File "/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 506, in <module>
W0531 01:02:49.026]     main(create_parser().parse_args())
W0531 01:02:49.027]   File "/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 429, in main
... skipping 2 lines ...
W0531 01:02:49.027]     check(*cmd)
W0531 01:02:49.027]   File "/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 40, in check
W0531 01:02:49.027]     subprocess.check_call(cmd)
W0531 01:02:49.027]   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
W0531 01:02:49.027]     raise CalledProcessError(retcode, cmd)
W0531 01:02:49.028] subprocess.CalledProcessError: Command '('docker', 'run', '--rm', '--name=pull-kubernetes-federation-e2e-gce-7569', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/go/src/k8s.io/kubernetes/_artifacts:/workspace/_artifacts', '-v', '/etc/localtime:/etc/localtime:ro', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-e', 'HOME=/workspace', '-e', 'WORKSPACE=/workspace', '--env-file', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/./test-infra/jenkins/../scenarios/../platforms/gce.env', '--env-file', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/./test-infra/jenkins/../scenarios/../jobs/pull-kubernetes-e2e.env', '--env-file', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/./test-infra/jenkins/../scenarios/../jobs/pull-kubernetes-federation-e2e-gce.env', '-v', '/home/jenkins/.ssh/google_compute_engine:/workspace/.ssh/google_compute_engine:ro', '-v', '/home/jenkins/.ssh/google_compute_engine.pub:/workspace/.ssh/google_compute_engine.pub:ro', '-e', 'JENKINS_GCE_SSH_PRIVATE_KEY_FILE=/workspace/.ssh/google_compute_engine', '-e', 'JENKINS_GCE_SSH_PUBLIC_KEY_FILE=/workspace/.ssh/google_compute_engine.pub', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce@tmp/secretFiles/6af0c076-71c2-44f0-a0d4-1487b0f70372/kubernetes-jenkins-pull-c67f9519f993.json:/service-account.json:ro', '-e', 'GOOGLE_APPLICATION_CREDENTIALS=/service-account.json', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/go/src/k8s.io/kubernetes:/go/src/k8s.io/kubernetes', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/go/src/k8s.io/release:/go/src/k8s.io/release', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/go/src/k8s.io/release:/go/src/k8s.io/release', '-e', 'JENKINS_HOME=/var/lib/jenkins', '-e', 'BUILD_CAUSE=MANUALTRIGGER', '-e', 'PULL_BASE_REF=master', '-e', 'HUDSON_URL=http://goto.google.com/prkubekins/', '-e', 'BUILD_URL=http://goto.google.com/prkubekins/job/pull-kubernetes-federation-e2e-gce/7569/', '-e', 'BOOTSTRAP_MIGRATION=yes', '-e', 'CLOUDSDK_CONFIG=/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/go/src/k8s.io/kubernetes/.config/gcloud', '-e', 'BUILD_TAG=jenkins-pull-kubernetes-federation-e2e-gce-7569', '-e', 'HUDSON_SERVER_COOKIE=32617aabcc4952a0', '-e', 'JENKINS_URL=http://goto.google.com/prkubekins/', '-e', 'LOGNAME=jenkins', '-e', 'USER=jenkins', '-e', 'JOB_NAME=pull-kubernetes-federation-e2e-gce', '-e', 'LANG=en_US.UTF-8', '-e', 'SHELL=/bin/bash', '-e', 'buildId=ef028d57-45d1-11e7-8980-0a580a6c1411', '-e', 'HUDSON_HOME=/var/lib/jenkins', '-e', 'NODE_LABELS=agent-pr-63 pull', '-e', 'JOB_URL=http://goto.google.com/prkubekins/job/pull-kubernetes-federation-e2e-gce/', '-e', 'ROOT_BUILD_CAUSE_MANUALTRIGGER=true', '-e', 'BUILD_CAUSE_MANUALTRIGGER=true', '-e', 'JENKINS_AWS_CREDENTIALS_FILE=/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce@tmp/secretFiles/76410d48-2a34-497e-bada-6637a711ba54/KubernetesPresubmitTests.txt', '-e', 'ROOT_BUILD_CAUSE=MANUALTRIGGER', '-e', 'SSH_CLIENT=10.240.0.2 55506 22', '-e', 'BUILD_ID=7569', '-e', 'BUILD_NUMBER=7569', '-e', 'HUDSON_COOKIE=387ab928-930f-418e-a112-2f7925bb6d90', '-e', 'JENKINS_AWS_SSH_PRIVATE_KEY_FILE=/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce@tmp/secretFiles/37ca6fdf-9266-47fb-9dd9-f27da28cabae/id_rsa.jenkins', '-e', 'JENKINS_GCE_SSH_PRIVATE_KEY_FILE=/home/jenkins/.ssh/google_compute_engine', '-e', 'JOB_BASE_NAME=pull-kubernetes-federation-e2e-gce', '-e', 'NLSPATH=/usr/dt/lib/nls/msg/%L/%N.cat', '-e', 'JENKINS_GCE_SSH_PUBLIC_KEY_FILE=/home/jenkins/.ssh/google_compute_engine.pub', '-e', '_=./test-infra/jenkins/bootstrap.py', '-e', 'JENKINS_AWS_SSH_PUBLIC_KEY_FILE=/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce@tmp/secretFiles/8b60977e-f8ed-4878-8865-75f05af9e2ce/id_rsa.jenkins.pub', '-e', 'EXECUTOR_NUMBER=0', '-e', 'NODE_NAME=agent-pr-63', '-e', 'PULL_NUMBER=46500', '-e', 'SHLVL=2', '-e', 'JENKINS_SERVER_COOKIE=32617aabcc4952a0', '-e', 'BUILD_DISPLAY_NAME=#7569', '-e', 'PULL_REFS=master:77a8c258391f30bb1d99c8eef0aba79218eaa445,46500:9ed01e44a14e52ec8460b0282930b44964940972', '-e', 'XFILESEARCHPATH=/usr/dt/app-defaults/%L/Dt', '-e', 'MAIL=/var/mail/jenkins', '-e', 'SSH_CONNECTION=10.240.0.2 55506 10.240.0.43 22', '-e', 'CLOUDSDK_COMPONENT_MANAGER_DISABLE_UPDATE_CHECK=true', '-e', 'CLOUDSDK_EXPERIMENTAL_FAST_COMPONENT_UPDATE=false', '-e', 'E2E_UP=true', '-e', 'E2E_TEST=true', '-e', 'E2E_DOWN=true', '-e', 'E2E_NAME=e2e-gce-agent-pr-63-0', '-e', 'KUBE_AWS_INSTANCE_PREFIX=e2e-gce-agent-pr-63-0', '-e', 'INSTANCE_PREFIX=e2e-gce-agent-pr-63-0', '-e', 'KUBE_GCE_NETWORK=e2e-gce-agent-pr-63-0', '-e', 'KUBE_GCE_INSTANCE_PREFIX=e2e-gce-agent-pr-63-0', '-e', 'CLUSTER_NAME=e2e-gce-agent-pr-63-0', '-e', 'KUBE_GKE_NETWORK=e2e-gce-agent-pr-63-0', 'gcr.io/k8s-testimages/kubekins-e2e:v20170525-59b0e879', '--build', '--stage=gs://kubernetes-release-pull/ci/pull-kubernetes-federation-e2e-gce', '--multiple-federations')' returned non-zero exit status 1
E0531 01:02:49.029] Build failed
```

**Comment by dchen1107** [comment]
pull-kubernetes-federation-e2e-gce is one of the builds blocks our submit-queue. I raised the priority the issue. If we cannot address the issue, we are going to remove this from pre-submit. 

cc/ @kubernetes/kubernetes-release-managers @sig-federation-misc @csbell

**Comment by madhusudancs** [comment]
This issue is due to https://github.com/kubernetes/kubernetes/issues/46380.

**Comment by madhusudancs** [comment]
@dchen1107 this happens once in 200 times or something. It is due to the issue linked above. I don't think it is that critical or urgent to remove the suite from the submit queue.

**Comment by janetkuo** [comment]
@madhusudancs All (~15) recent builds failed https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-federation-e2e-gce

**Comment by madhusudancs** [comment]
@janetkuo recent test-infra issue. Fixed in https://github.com/kubernetes/test-infra/pull/2932

**Comment by madhusudancs** [comment]
Oops. Fix is in https://github.com/kubernetes/test-infra/pull/2931.

**Comment by sttts** [comment]
This might be the same error we see constantly today (e.g. in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46138/pull-kubernetes-federation-e2e-gce/13815/):

```
W0710 12:17:01.047] 2017/07/10 12:17:01 util.go:129: Running: ./federation/cluster/federation-up.sh
W0710 12:17:01.117] Project: k8s-jkns-pr-bldr-e2e-gce-fdrtn
W0710 12:17:01.118] Zone: us-central1-f
I0710 12:17:01.218] +++ [0710 12:17:01] Deploying federation control plane for e2e-f8n-agent-pr-50-0 in cluster federation-e2e-gce-us-central1-f
I0710 12:17:01.218] +++ [0710 12:17:01] DNS_ZONE_NAME: "pr-bldr.test-f8n.k8s.io.", DNS_PROVIDER: "google-clouddns"
I0710 12:17:01.218] +++ [0710 12:17:01] Image: "gcr.io/k8s-jkns-pr-bldr-e2e-gce-fdrtn/hyperkube-amd64:v1.8.0-alpha.1.914_d3a58bb32b5c5e"
W0710 12:17:01.334] No resources found.
I0710 12:17:01.649] Creating a namespace f8n-system-agent-pr-50-0 for federation system components... done
I0710 12:17:56.699] Creating federation control plane service............... done
I0710 12:17:58.125] Creating federation control plane objects (credentials, persistent volume claim)... done
I0710 12:17:58.226] Creating federation component deployments... done
I0710 12:17:58.342] Updating kubeconfig... done
I0710 12:18:26.373] Waiting for federation control plane to come up................. done
I0710 12:18:26.374] Federation API server is running at: 35.188.92.115
W0710 12:18:26.474] I0710 12:17:01.625278    3958 init.go:289] Creating a namespace f8n-system-agent-pr-50-0 for federation system components
W0710 12:18:26.475] I0710 12:17:01.649329    3958 init.go:298] Creating federation control plane service
W0710 12:18:26.475] I0710 12:17:56.698763    3958 init.go:304] Created service named e2e-f8n-agent-pr-50-0-apiserver with IP addresses [35.188.92.115], hostnames []
W0710 12:18:26.475] I0710 12:17:56.698835    3958 init.go:307] Generating TLS certificates and credentials for communicating with the federation API server
W0710 12:18:26.475] I0710 12:17:58.099392    3958 init.go:318] Certificates and credentials generated
W0710 12:18:26.475] I0710 12:17:58.099437    3958 init.go:320] Creating an entry in the kubeconfig file with the certificate and credential data
W0710 12:18:26.475] I0710 12:17:58.113429    3958 init.go:325] Credentials secret successfully created
W0710 12:18:26.476] I0710 12:17:58.113468    3958 init.go:327] Creating a persistent volume and a claim to store the federation API server's state, including etcd data
W0710 12:18:26.476] I0710 12:17:58.124794    3958 init.go:335] Persistent volume and claim created
W0710 12:18:26.476] I0710 12:17:58.124850    3958 init.go:347] Creating federation control plane components
W0710 12:18:26.476] I0710 12:17:58.144001    3958 init.go:352] Successfully created federation API server
W0710 12:18:26.476] I0710 12:17:58.144047    3958 init.go:359] Creating service account for federation controller manager in the host cluster
W0710 12:18:26.476] I0710 12:17:58.152480    3958 init.go:364] Successfully created federation controller manager service account
W0710 12:18:26.476] I0710 12:17:58.152509    3958 init.go:366] Creating RBAC role and role bindings for the federation controller manager's service account
W0710 12:18:26.477] I0710 12:17:58.191636    3958 init.go:371] Successfully created RBAC role and role bindings
W0710 12:18:26.477] I0710 12:17:58.191679    3958 init.go:374] Creating a DNS provider config secret
W0710 12:18:26.477] I0710 12:17:58.191687    3958 init.go:379] Successfully created DNS provider config secret
W0710 12:18:26.477] I0710 12:17:58.191694    3958 init.go:381] Creating federation controller manager deployment
W0710 12:18:26.477] I0710 12:17:58.226210    3958 init.go:387] Successfully created federation controller manager deployment
W0710 12:18:26.477] I0710 12:17:58.226297    3958 init.go:391] Updating kubeconfig
W0710 12:18:26.477] I0710 12:17:58.341693    3958 init.go:411] Successfully updated kubeconfig
W0710 12:18:26.477] I0710 12:17:58.341726    3958 init.go:415] Waiting for federation control plane to come up
W0710 12:18:26.478] I0710 12:18:26.373156    3958 init.go:425] Federation control plane running
I0710 12:18:26.578] +++ [0710 12:18:26] Joining cluster with name 'federation-e2e-gce-us-central1-a' to federation with name 'e2e-f8n-agent-pr-50-0'
W0710 12:18:26.679] I0710 12:18:26.632924    4022 join.go:131] Args and flags: name federation-e2e-gce-us-central1-a, host: federation-e2e-gce-us-central1-f, host-system-namespace: f8n-system-agent-pr-50-0, kubeconfig: , cluster-context: federation-e2e-gce-us-central1-a, secret-name: , dry-run: %!s(bool=false)
W0710 12:18:26.679] I0710 12:18:26.632976    4022 join.go:133] Performing preflight checks.
W0710 12:18:26.679] I0710 12:18:26.648990    4022 cached_discovery.go:126] skipped caching discovery info due to Get https://35.188.92.115/api: x509: certificate signed by unknown authority
W0710 12:18:26.679] F0710 12:18:26.649050    4022 helpers.go:119] error: Couldn't get clientset to create RBAC roles in the host cluster: Get https://35.188.92.115/api: x509: certificate signed by unknown authority
W0710 12:18:26.679] 2017/07/10 12:18:26 util.go:131: Step './federation/cluster/federation-up.sh' finished in 1m25.606364544s
```

**Comment by nikhiljindal** [comment]
cc @csbell (the current federation on call)

**Comment by mattmoyer** [comment]
Is this a duplicate of https://github.com/kubernetes/kubernetes/issues/45978?

**Comment by nikhiljindal** [comment]
federation e2e tests are passing now
