### ISSUE TITLE
Statefulset first pod is orphaned and doesnt scale past it

### ISSUE THREAD

**Issue by bruj0** [kubernetes/kubernetes#46901]
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2+477efc3", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"not a git tree", BuildDate:"2017-05-02T22:42:26Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2+coreos.0", GitCommit:"79fee581ce4a35b7791fdd92e0fc97e02ef1d5c0", GitTreeState:"clean", BuildDate:"2017-04-19T23:13:34Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```
**Environment**:
- **Cloud provider or hardware configuration**:
AWS

- **OS** (e.g. from /etc/os-release):
v1.6.2+coreos.0
- **Kernel** (e.g. `uname -a`):
Linu 4.9.24-coreos  SMP Tue May 30 23:12:01 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux

- **Install tools**:
https://github.com/kz8s/tack
- **Others**:

**What happened**:
Hi, im trying to create a stateful set to host postgresql.
The pods are created but the first pod, ie pgset-0 doesnt show up as created:
```
Replicas:		2 desired | 0 total
Pods Status:		0 Running / 0 Waiting / 0 Succeeded / 0 Failed
```
 With error:
```
 FirstSeen	LastSeen	Count	From		SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----		-------------	--------	------			-------
  4m		4m		1	statefulset			Normal		SuccessfulCreate	create Pod pgset-0 in StatefulSet pgset successful
  1m		26s		17	statefulset			Warning		FailedCreate		create Pod pgset-0 in StatefulSet pgset failed error: The POST operation against Pod could not be completed at this time, please try again.
```

However pgset-0 is running:

```
NAME      READY     STATUS    RESTARTS   AGE
pgset-0   1/1       Running   0          6m

Name:		pgset-0
Namespace:	siteadmin-deployment
Node:		ip-10-0-10-98.ec2.internal/10.0.10.98
Start Time:	Fri, 02 Jun 2017 23:32:44 -0300
Labels:		app=pgset
		name=pgset-master
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"StatefulSet","namespace":"siteadmin-deployment","name":"pgset","uid":"ec0b045a-4804-11e7-b856-0a17c7a5d990...
		pod.beta.kubernetes.io/hostname=pgset-0
		pod.beta.kubernetes.io/subdomain=pgset
Status:		Running
IP:		10.2.75.3
Controllers:	StatefulSet/pgset
```

Any idea what could be the problem?

**What you expected to happen**:

All pods showing up in the statefulset.

**How to reproduce it** (as minimally and precisely as possible):

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: pgset
  namespace: siteadmin-deployment
spec:
  serviceName: pgset
  replicas: 2
  template:
    metadata:
      labels:
        app: pgset
        name: pgset-replica
    spec:
      securityContext:
        fsGroup: 26
        supplementalGroups: [26]
      containers:
      - name: pgset
        image: crunchydata/crunchy-postgres:centos7-9.5-1.4.1
        ports:
        - containerPort: 5432
          name: pgset
        env:
        - name: PG_MASTER_USER
          value: master
        - name: PGHOST
          value: "/tmp"
        - name: PG_MODE
          value: set
          value: set
        - name: PG_MASTER_HOST
          value: pgset-master
        - name: PG_MASTER_PORT
          value: '5432'
        - name: PG_MASTER_PASSWORD
          value: password
        - name: PG_USER
          value: testuser
        - name: PG_PASSWORD
          value: password
        - name: PG_DATABASE
          value: userdb
        - name: PG_ROOT_PASSWORD
          value: password
        volumeMounts:
        - name: pgdata
          mountPath: "/pgdata"
          readOnly: false
      volumes:
      - name: pgdata
        emptydir: {}
```

**Anything else we need to know**:

I think this is an error generated because of it:
```
I0603 01:32:02.355573       1 wrap.go:75] POST /api/v1/namespaces/siteadmin-deployment/pods: (5.287932ms) 500
goroutine 4263962 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc42531b490, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/log.go:219 +0xbb
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc42531b490, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/log.go:198 +0x35
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.(*responseWriterDelegator).WriteHeader(0xc42342e8d0, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:134 +0x45
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x6cb1fa0, 0xc420d0b1a0, 0x0, 0x0, 0x40e913e, 0x2, 0x6ca9920, 0xc42357d0c8, 0xc425d82780, 0x1
f4, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:89 +0x162
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.ErrorNegotiated(0x6c7fe20, 0xc428db5d00, 0x6cb1fa0, 0xc420d0b1a0, 0x0, 0x0, 0x40e913e, 0x2, 0x6ca9920, 0xc42357d0c8
, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:106 +0x103
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.(*RequestScope).err(0xc420ed5b80, 0x6c7fe20, 0xc428db5d00, 0x6ca9920, 0xc42357d0c8, 0xc425d82780)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:100 +0xd7
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.createHandler.func1(0xc42342e840, 0xc424399620)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:435 +0xee2
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc42342e840, 0xc424399620)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:104 +0x1ec
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc4206753b0, 0x6ca99a0, 0xc42531b490, 0xc425d82780)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:272 +0xba0
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x6ca99a0, 0xc42531b490, 0xc425d82780)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4213f4810, 0x6ca99a0, 0xc42531b490, 0xc425d82780)
        /usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc420f90f30, 0x6ca99a0, 0xc42531b490, 0xc425d82780)
        /usr/local/go/src/net/http/server.go:2022 +0x7f
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0x6ca99a0, 0xc42531b490, 0xc425d82780)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:74 +0x24a
net/http.HandlerFunc.ServeHTTP(0xc420f70180, 0x7fbd4f37d100, 0xc42357d0b8, 0xc425d82780)
        /usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc420d06420, 0x6cb4ea0, 0xc42357d0b8, 0xc425d82780, 0xc4243995c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:91 +0x8d
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:93 +0x1d1

logging error output: "k8s\x00\n\f\n\x02v1\x12\x06Status\x12\x89\x01\n\x04\n\x00\x12\x00\x12\aFailure\x1aUThe POST operation against Pod could not be completed at this time, please try again.\"\rS
erverTimeout*\x0f\n\x04POST\x12\x00\x1a\x03Pod(\x000\xf4\x03\x1a\x00\"\x00"
 [[hyperkube/v1.6.2+coreos.0 (linux/amd64) kubernetes/79fee58/statefulset-controller] 127.0.0.1:38284]
```

**Comment by kargakis** [comment]
@kubernetes/sig-apps-bugs

**Comment by foxish** [comment]
@bruj0 can you give us more detail? `kubectl get statefulset pgset -o yaml` and `kubectl get pod pgset-0 -o yaml`?
Is this reproducible consistently?

**Comment by bruj0** [comment]
@foxish it is reproducible consistently on my cluster with any type of statefulset configuration, including the one i posted as an example.
Any pointers appreciated!


This is the output you requested:

kubectl get statefulset pgset -o yaml

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta1","kind":"StatefulSet","metadata":{"annotations":{},"name":"pgset","namespace":"siteadmin-deployment"},"spec":{"replicas":2,"serviceName":"pgset","template":{"metadata":{"labels":{"app":"pgset","name":"pgset-replica"}},"spec":{"containers":[{"env":[{"name":"PG_MASTER_USER","value":"master"},{"name":"PGHOST","value":"/tmp"},{"name":"PG_MODE","value":"set"},{"name":"PG_MASTER_HOST","value":"pgset-master"},{"name":"PG_MASTER_PORT","value":"5432"},{"name":"PG_MASTER_PASSWORD","value":"password"},{"name":"PG_USER","value":"testuser"},{"name":"PG_PASSWORD","value":"password"},{"name":"PG_DATABASE","value":"userdb"},{"name":"PG_ROOT_PASSWORD","value":"password"}],"image":"crunchydata/crunchy-postgres:centos7-9.5-1.4.1","name":"pgset","ports":[{"containerPort":5432,"name":"postgres"}],"volumeMounts":[{"mountPath":"/pgdata","name":"pgdata","readOnly":false}]}],"securityContext":{"fsGroup":26},"serviceAccount":"pgset-sa","volumes":[{"emptyDir":{},"name":"pgdata"}]}}}}
  creationTimestamp: 2017-06-03T07:22:29Z
  generation: 1
  labels:
    app: pgset
    name: pgset-replica
  name: pgset
  namespace: siteadmin-deployment
  resourceVersion: "4802044"
  selfLink: /apis/apps/v1beta1/namespaces/siteadmin-deployment/statefulsets/pgset
  uid: 670d4cd7-482d-11e7-b856-0a17c7a5d990
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgset
      name: pgset-replica
  serviceName: pgset
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pgset
        name: pgset-replica
    spec:
      containers:
      - env:
        - name: PG_MASTER_USER
          value: master
        - name: PGHOST
          value: /tmp
        - name: PG_MODE
          value: set
        - name: PG_MASTER_HOST
          value: pgset-master
        - name: PG_MASTER_PORT
          value: "5432"
        - name: PG_MASTER_PASSWORD
          value: password
        - name: PG_USER
          value: testuser
        - name: PG_PASSWORD
          value: password
        - name: PG_DATABASE
          value: userdb
        - name: PG_ROOT_PASSWORD
          value: password
        image: crunchydata/crunchy-postgres:centos7-9.5-1.4.1
        imagePullPolicy: IfNotPresent
        name: pgset
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /pgdata
          name: pgdata
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 26
      serviceAccount: pgset-sa
      serviceAccountName: pgset-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: pgdata
status:
  observedGeneration: 1
  replicas: 0
```

kubectl get pod pgset-0 -o yaml

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"StatefulSet","namespace":"siteadmin-deployment","name":"pgset","uid":"670d4cd7-482d-11e7-b856-0a17c7a5d990","apiVersion":"apps","resourceVersion":"4802043"}}
    pod.beta.kubernetes.io/hostname: pgset-0
    pod.beta.kubernetes.io/subdomain: pgset
  creationTimestamp: 2017-06-03T07:22:29Z
  generateName: pgset-
  labels:
    app: pgset
    name: pgset-master
  name: pgset-0
  namespace: siteadmin-deployment
  resourceVersion: "4802356"
  selfLink: /api/v1/namespaces/siteadmin-deployment/pods/pgset-0
  uid: 6715089d-482d-11e7-b856-0a17c7a5d990
spec:
  containers:
  - env:
    - name: PG_MASTER_USER
      value: master
    - name: PGHOST
      value: /tmp
    - name: PG_MODE
      value: set
    - name: PG_MASTER_HOST
      value: pgset-master
    - name: PG_MASTER_PORT
      value: "5432"
    - name: PG_MASTER_PASSWORD
      value: password
    - name: PG_USER
      value: testuser
    - name: PG_PASSWORD
      value: password
    - name: PG_DATABASE
      value: userdb
    - name: PG_ROOT_PASSWORD
      value: password
    image: crunchydata/crunchy-postgres:centos7-9.5-1.4.1
    imagePullPolicy: IfNotPresent
    name: pgset
    ports:
    - containerPort: 5432
      name: postgres
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /pgdata
      name: pgdata
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: pgset-sa-token-6319z
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: ip-10-0-10-98.ec2.internal
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 26
  serviceAccount: pgset-sa
  serviceAccountName: pgset-sa
  terminationGracePeriodSeconds: 30
  volumes:
  - emptyDir: {}
    name: pgdata
  - name: pgset-sa-token-6319z
    secret:
      defaultMode: 420
      secretName: pgset-sa-token-6319z
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2017-06-03T07:22:30Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2017-06-03T07:22:31Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2017-06-03T07:22:30Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://e2e51f2283a9c97de06557c8efbf8342adcbac729f0526028586ca0b3cd6e245
    image: crunchydata/crunchy-postgres:centos7-9.5-1.4.1
    imageID: docker-pullable://crunchydata/crunchy-postgres@sha256:c87d9ce392769ce0605205010e50f392c4a6246274230f2c0af7410cd773e34a
    lastState: {}
    name: pgset
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2017-06-03T07:22:30Z
  hostIP: 10.0.10.98
  phase: Running
  podIP: 10.2.75.3
  qosClass: BestEffort
  startTime: 2017-06-03T07:22:30Z
```

**Comment by bruj0** [comment]
More info:
```
$ kubectl -n siteadmin-deployment describe statefulset pgset
Name:			pgset
Namespace:		siteadmin-deployment
CreationTimestamp:	Sat, 03 Jun 2017 04:22:29 -0300
Selector:		app=pgset,name=pgset-replica
Labels:			app=pgset
			name=pgset-replica
Annotations:		kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"apps/v1beta1","kind":"StatefulSet","metadata":{"annotations":{},"name":"pgset","namespace":"siteadmin-deployment"},"spec":{"replicas":2,...
Replicas:		2 desired | 0 total
Pods Status:		0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:		app=pgset
			name=pgset-replica
  Service Account:	pgset-sa
  Containers:
   pgset:
    Image:	crunchydata/crunchy-postgres:centos7-9.5-1.4.1
    Port:	5432/TCP
    Environment:
      PG_MASTER_USER:		master
      PGHOST:			/tmp
      PG_MODE:			set
      PG_MASTER_HOST:		pgset-master
      PG_MASTER_PORT:		5432
      PG_MASTER_PASSWORD:	password
      PG_USER:			testuser
      PG_PASSWORD:		password
      PG_DATABASE:		userdb
      PG_ROOT_PASSWORD:		password
    Mounts:
      /pgdata from pgdata (rw)
  Volumes:
   pgdata:
    Type:	EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:	
Volume Claims:	<none>
Events:
  FirstSeen	LastSeen	Count	From		SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----		-------------	--------	------		-------
  1d		14m		2	statefulset			Warning		FailedCreate	create Pod pgset-0 in StatefulSet pgset failed error: etcdserver: request timed out
  13d		30s		40662	statefulset			Warning		FailedCreate	create Pod pgset-0 in StatefulSet pgset failed error: The POST operation against Pod could not be completed at this time, please try again.
```

**Comment by foxish** [comment]
>   1d		14m		2	statefulset			Warning		FailedCreate	create Pod pgset-0 in StatefulSet pgset failed error: etcdserver: request timed out

This is interesting. Can you confirm that this only occurs with StatefulSet and not other mechanisms of creating pods?

**Comment by bruj0** [comment]
@foxish i can confirm that, i just created a simple busybox pod in the namespace and its running:

```
$ kubectl -n siteadmin-deployment describe pod busybox
Name:		busybox
Namespace:	siteadmin-deployment
Node:		ip-10-0-10-229.ec2.internal/10.0.10.229
Start Time:	Fri, 16 Jun 2017 21:21:01 -0300
Labels:		<none>
Annotations:	kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"busybox","namespace":"siteadmin-deployment"},"spec":{"containers":[{"command":["sl...
Status:		Running
IP:		10.2.70.7
Controllers:	<none>
Containers:
  busybox:
    Container ID:	docker://d04f086388d24a2fc5a1fad24daa4765299449369b407d047edecd0e8782750a
    Image:		busybox
    Image ID:		docker-pullable://busybox@sha256:c79345819a6882c31b41bc771d9a94fc52872fa651b36771fbe0c8461d7ee558
    Port:		
    Command:
      sleep
      3600
    State:		Running
      Started:		Fri, 16 Jun 2017 21:21:03 -0300
    Ready:		True
    Restart Count:	0
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-9sv7h (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	True 
  PodScheduled 	True 
Volumes:
  default-token-9sv7h:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-9sv7h
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From					SubObjectPath			Type		ReasonMessage
  ---------	--------	-----	----					-------------			--------	-------------
  34s		34s		1	default-scheduler							Normal		Scheduled	Successfully assigned busybox to ip-10-0-10-229.ec2.internal
  32s		32s		1	kubelet, ip-10-0-10-229.ec2.internal	spec.containers{busybox}	Normal		PulledContainer image "busybox" already present on machine
  32s		32s		1	kubelet, ip-10-0-10-229.ec2.internal	spec.containers{busybox}	Normal		CreatedCreated container with id d04f086388d24a2fc5a1fad24daa4765299449369b407d047edecd0e8782750a
  32s		32s		1	kubelet, ip-10-0-10-229.ec2.internal	spec.containers{busybox}	Normal		StartedStarted container with id d04f086388d24a2fc5a1fad24daa4765299449369b407d047edecd0e8782750a
```

**Comment by foxish** [comment]
Thanks @bruj0. Will try to reproduce said issue. I can see that there was a fix in 1.6.3.
StatefulSet: Fix to fully preserve restart and termination order when StatefulSet is rapidly scaled up and down. (#45113)

@kow3ns Does this look related?

**Comment by AkashKrDutta** [comment]
Is this solved? I am facing the same issue.

**Comment by ianmaddox** [comment]
I can confirm the same issue.

**Comment by kow3ns** [comment]
@bruj0 

Here is your selector.

```yaml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgset
      name: pgset-replica
```
You've mutated the labels on the Pod (to intentionally orphan it?). They are as below. The StatefulSet controller didn't create a Pod with these labels from the specified template,  and the template is not mutable, so this Pod was relabeled (either manually or via a script).

```yaml
labels:
    app: pgset
    name: pgset-master
```

You can see they don't match.

It is okay to relabel a Pod so that it is intentionally orphaned, but because of the unique naming of Pods in a StatefulSet, the StatefulSet controller will not be able to create a new Pod until you delete the orphan. You will block the StatefulSet from scaling by purposefully orphaning a Pod. This is by design, and we don't delete the Pod under these circumstances. This is not a bug.

For your use case the correct way to use selectors is to specify 

```yaml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgset
```

This will match your master labels 

```yaml
labels:
    app: pgset
    name: pgset-master
```

and your replica labels 

```yaml
labels:
    app: pgset
    name: pgset-replica
```

**Comment by bruj0** [comment]
@kow3ns 
I have not manually changed the label in the pods, however, I did recreate the StatefulSet a couple of times and at some point, the label was "pgset-master".
Should I retest this bug in the last version of Kubernetes?

**Comment by harryge00** [comment]
I have just encountered the same issue:
```
{
    "apiVersion":"apps/v1beta1",
    "kind":"StatefulSet",
    "metadata":{
        "name":"web",
        "namespace": "haoyuan-40",
        "labels":{
                    "name":"web",
                    "room":"abcd-room"
                }
    },
    "spec":{
        "replicas": 2,
        "serviceName":"web",
        "template":{
            "metadata":{
                "labels":{
                    "name":"web",
                    "room":"abcd-room"
                }
            },
            "spec":{
                "containers":[
                    {
                        "image":"reg.dhdc.com/library/nginx:1.9",
                        "name":"nginx",
                        "ports":[
                             {
                                "containerPort":80,
                                "name":"web"
                            }
                        ]
                    }
                ]
            }
        }
    }
}

```

**Comment by kow3ns** [comment]
@bruj0 If the labels on the Pod are mutated such that they no longer match the selector than this is the behavior you will get in any version.
