### ISSUE TITLE
kubelet Error adding network: the server does not allow access to the requested resource

### ISSUE THREAD

**Issue by txg1550759** [kubernetes/kubernetes#47398]
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
[root@master3 ~]# kubectl get nodes
NAME            STATUS    AGE       VERSION
jenkins-2       Ready     2d        v1.6.4
node1.txg.com   Ready     3d        v1.6.4
node2.txg.com   Ready     2d        v1.6.4
node3.txg.com   Ready     3d        v1.6.4
node4.txg.com   Ready     2d        v1.6.4
[root@master3 ~]# 

**Environment**:
centos7 vm
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
centos7
- **Kernel** (e.g. `uname -a`):
[root@node1 ~]# uname -a
Linux node1.txg.com 4.4.71-1.el7.elrepo.x86_64 #1 SMP Wed Jun 7 12:08:54 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**:

- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
# Calico Version v2.1.5
# http://docs.projectcalico.org/v2.1/releases#v2.1.5
# This manifest includes the following component versions:
#   calico/node:v1.1.3
#   calico/cni:v1.8.0
#   calico/kube-policy-controller:v0.5.4

**Anything else we need to know**:

kubernetes version v1.6.4
calico cni network cannot create
Some nodes cannot be created calico networks kubelet error

Kubelet 1.5 has no problem at all, the same configuration!
this kubelet bug!

```
 kubectl create -f /root/nginx.yaml
[root@master3 ~]# kubectl get pod -o wide

NAME                                     READY     STATUS              RESTARTS   AGE       IP              NODE
nfs-client-provisioner-278618947-z32dw   1/1       Running             5          1d        172.1.160.224   node4.txg.com
nginx-3950648766-6b3d2                   0/1       ContainerCreating   0          37s       <none>          node1.txg.com
nginx-3950648766-c0scf                   0/1       ContainerCreating   0          37s       <none>          node3.txg.com
nginx-3950648766-nss09                   1/1       Running             0          37s       172.1.24.214    jenkins-2
nginx-3950648766-tcw1s                   1/1       Running             0          37s       172.1.160.229   node4.txg.com
nginx-3950648766-vq7mk                   1/1       Running             0          37s       172.1.27.146    node2.txg.com

 
nginx-3950648766-6b3d2                   0/1       ContainerCreating   0          37s       <none>          node1.txg.com
nginx-3950648766-c0scf                   0/1       ContainerCreating   0          37s       <none>          node3.txg.com

Jun 13 13:06:27 node1 kubelet: time="2017-06-13T13:06:27+08:00" level=info msg="Configured environment: [LANG=en_US.UTF-8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin CNI_COMMAND=DEL CNI_CONTAINERID=96bb81b2e6aa45510954d8b3386c3f66e6b9727024ae591f8519facc8f319765 CNI_NETNS= CNI_ARGS=IgnoreUnknown=1;IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=nginx-3950648766-6b3d2;K8S_POD_INFRA_CONTAINER_ID=96bb81b2e6aa45510954d8b3386c3f66e6b9727024ae591f8519facc8f319765 CNI_IFNAME=eth0 CNI_PATH=/opt/cni/bin:/opt/calico/bin ETCD_ENDPOINTS=https://192.168.1.65:2379,https://192.168.1.66:2379,https://192.168.1.67:2379 ETCD_KEY_FILE=/etc/cni/net.d/calico-tls/etcd-key ETCD_CERT_FILE=/etc/cni/net.d/calico-tls/etcd-cert ETCD_CA_CERT_FILE=/etc/cni/net.d/calico-tls/etcd-ca KUBECONFIG=/etc/cni/net.d/calico-kubeconfig K8S_API_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLWxnbTJ4Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIxMDUzMDZlMC00Y2QwLTExZTctYWI4ZC01MjU0MDA4MWMwNmEiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.O9LzJ4sITudjFxq9XtXXa6UZLPm1ojSH0GMZ24OFa5kVRlEQCDnUUOt19uyPrL2OEkC48l-OLJ-PGXMmnG4vc5TRIpOQmvPTr7v573gYeB4FhkWX01l1yMecFSZ6LgIqYNZczudycpCEeIl5o8vrY9tlrlx5mcJxl7vmIhpkrZBAH1PiXEbzMe1TYFF3wDQAsQp8cIXn8tbC3RlM0TwK8BQt1Pe4OVdItj05nW7eDQktC_r1nZTAOsk7C9d2rw1MojL-HKrDD4gy13PZInhCzr6PpYFf0w5LLOM7odDa6Ge5ZKADtxCBL8PJobxyrnzrfu3CmF-Ecpfmd9PMavXksw]"
Jun 13 13:06:27 node1 kubelet: time="2017-06-13T13:06:27+08:00" level=info msg="Loading config from environment"
Jun 13 13:06:27 node1 kubelet: 2017-06-13 13:06:27.879550 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
Jun 13 13:06:27 node1 kubelet: time="2017-06-13T13:06:27+08:00" level=info msg="Releasing address using workloadID" Workload=default.nginx-3950648766-6b3d2
Jun 13 13:06:27 node1 kubelet: time="2017-06-13T13:06:27+08:00" level=info msg="Releasing all IPs with handle 'default.nginx-3950648766-6b3d2'"
Jun 13 13:06:27 node1 kubelet: time="2017-06-13T13:06:27+08:00" level=warning msg="Asked to release address but it doesn't exist. Ignoring" Workload=default.nginx-3950648766-6b3d2 workloadId=default.nginx-3950648766-6b3d2
Jun 13 13:06:30 node1 kubelet: time="2017-06-13T13:06:30+08:00" level=info msg="Extracted identifiers" Node=node1.txg.com Orchestrator=k8s Workload=default.nginx-3950648766-6b3d2
Jun 13 13:06:30 node1 kubelet: time="2017-06-13T13:06:30+08:00" level=info msg="Loaded CNI NetConf" NetConfg={ k8s-pod-network calico { calico-ipam  <nil> <nil> [] []} 0     https://192.168.1.65:2379,https://192.168.1.66:2379,https://192.168.1.67:2379 info {k8s https://172.1.0.1:443 eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLWxnbTJ4Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIxMDUzMDZlMC00Y2QwLTExZTctYWI4ZC01MjU0MDA4MWMwNmEiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.O9LzJ4sITudjFxq9XtXXa6UZLPm1ojSH0GMZ24OFa5kVRlEQCDnUUOt19uyPrL2OEkC48l-OLJ-PGXMmnG4vc5TRIpOQmvPTr7v573gYeB4FhkWX01l1yMecFSZ6LgIqYNZczudycpCEeIl5o8vrY9tlrlx5mcJxl7vmIhpkrZBAH1PiXEbzMe1TYFF3wDQAsQp8cIXn8tbC3RlM0TwK8BQt1Pe4OVdItj05nW7eDQktC_r1nZTAOsk7C9d2rw1MojL-HKrDD4gy13PZInhCzr6PpYFf0w5LLOM7odDa6Ge5ZKADtxCBL8PJobxyrnzrfu3CmF-Ecpfmd9PMavXksw   } { /etc/cni/net.d/calico-kubeconfig } {{{ {[]}}}}  /etc/cni/net.d/calico-tls/etcd-key /etc/cni/net.d/calico-tls/etcd-cert /etc/cni/net.d/calico-tls/etcd-ca} Workload=default.nginx-3950648766-6b3d2
Jun 13 13:06:30 node1 kubelet: time="2017-06-13T13:06:30+08:00" level=info msg="Configured environment: [LANG=en_US.UTF-8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin CNI_COMMAND=ADD CNI_CONTAINERID=09d7f77434e6bd57abc2418d3bae865be238a1b5964e131548a96757c8be9a44 CNI_NETNS=/proc/15016/ns/net CNI_ARGS=IgnoreUnknown=1;IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=nginx-3950648766-6b3d2;K8S_POD_INFRA_CONTAINER_ID=09d7f77434e6bd57abc2418d3bae865be238a1b5964e131548a96757c8be9a44 CNI_IFNAME=eth0 CNI_PATH=/opt/cni/bin:/opt/calico/bin ETCD_ENDPOINTS=https://192.168.1.65:2379,https://192.168.1.66:2379,https://192.168.1.67:2379 ETCD_KEY_FILE=/etc/cni/net.d/calico-tls/etcd-key ETCD_CERT_FILE=/etc/cni/net.d/calico-tls/etcd-cert ETCD_CA_CERT_FILE=/etc/cni/net.d/calico-tls/etcd-ca KUBECONFIG=/etc/cni/net.d/calico-kubeconfig K8S_API_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLWxnbTJ4Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIxMDUzMDZlMC00Y2QwLTExZTctYWI4ZC01MjU0MDA4MWMwNmEiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.O9LzJ4sITudjFxq9XtXXa6UZLPm1ojSH0GMZ24OFa5kVRlEQCDnUUOt19uyPrL2OEkC48l-OLJ-PGXMmnG4vc5TRIpOQmvPTr7v573gYeB4FhkWX01l1yMecFSZ6LgIqYNZczudycpCEeIl5o8vrY9tlrlx5mcJxl7vmIhpkrZBAH1PiXEbzMe1TYFF3wDQAsQp8cIXn8tbC3RlM0TwK8BQt1Pe4OVdItj05nW7eDQktC_r1nZTAOsk7C9d2rw1MojL-HKrDD4gy13PZInhCzr6PpYFf0w5LLOM7odDa6Ge5ZKADtxCBL8PJobxyrnzrfu3CmF-Ecpfmd9PMavXksw]"
Jun 13 13:06:30 node1 kubelet: time="2017-06-13T13:06:30+08:00" level=info msg="Loading config from environment"
Jun 13 13:06:30 node1 kubelet: 2017-06-13 13:06:30.538481 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
Jun 13 13:06:30 node1 kubelet: I0613 13:06:30.552847    1349 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/3ae79124-4e6f-11e7-85cd-52540081c06a-default-token-lgm2x" (spec.Name: "default-token-lgm2x") pod "3ae79124-4e6f-11e7-85cd-52540081c06a" (UID: "3ae79124-4e6f-11e7-85cd-52540081c06a").
Jun 13 13:06:30 node1 kubelet: Calico CNI checking for existing endpoint: <nil>
Jun 13 13:06:30 node1 kubelet: time="2017-06-13T13:06:30+08:00" level=info msg="Extracted identifiers for CmdAddK8s" Node=node1.txg.com Orchestrator=k8s Workload=default.nginx-3950648766-6b3d2
Jun 13 13:06:30 node1 kubelet: E0613 13:06:30.870062    1349 cni.go:257] Error adding network: the server does not allow access to the requested resource (get pods nginx-3950648766-6b3d2)
Jun 13 13:06:30 node1 kubelet: E0613 13:06:30.870718    1349 cni.go:211] Error while adding to cni network: the server does not allow access to the requested resource (get pods nginx-3950648766-6b3d2)
Jun 13 13:06:30 node1 kubelet: W0613 13:06:30.877113    1349 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "nginx-3950648766-6b3d2_default": Unexpected command output nsenter: cannot open /proc/15016/ns/net: No such file or directory
Jun 13 13:06:30 node1 kubelet: with error: exit status 1
Jun 13 13:06:30 node1 kubelet: W0613 13:06:30.886304    1349 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "nginx-3950648766-6b3d2_default": Unexpected command output nsenter: cannot open : No such file or directory
Jun 13 13:06:30 node1 kubelet: with error: exit status 1
Jun 13 13:06:30 node1 kubelet: W0613 13:06:30.902117    1349 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "nginx-3950648766-6b3d2_default": Unexpected command output nsenter: cannot open : No such file or directory
Jun 13 13:06:30 node1 kubelet: with error: exit status 1
Jun 13 13:06:30 node1 kubelet: W0613 13:06:30.917711    1349 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "nginx-3950648766-6b3d2_default": Unexpected command output nsenter: cannot open : No such file or directory
Jun 13 13:06:30 node1 kubelet: with error: exit status 1
Jun 13 13:06:30 node1 kubelet: W0613 13:06:30.925323    1349 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "nginx-3950648766-6b3d2_default": Unexpected command output nsenter: cannot open : No such file or directory
Jun 13 13:06:30 node1 kubelet: with error: exit status 1
Jun 13 13:06:30 node1 kubelet: W0613 13:06:30.935989    1349 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "nginx-3950648766-6b3d2_default": Unexpected command output nsenter: cannot open : No such file or directory
Jun 13 13:06:30 node1 kubelet: with error: exit status 1
Jun 13 13:06:30 node1 kubelet: W0613 13:06:30.947595    1349 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "nginx-3950648766-6b3d2_default": Unexpected command output nsenter: cannot open : No such file or directory
Jun 13 13:06:30 node1 kubelet: with error: exit status 1
Jun 13 13:06:30 node1 kubelet: W0613 13:06:30.954916    1349 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "nginx-3950648766-6b3d2_default": Unexpected command output nsenter: cannot open : No such file or directory
Jun 13 13:06:30 node1 kubelet: with error: exit status 1
Jun 13 13:06:30 node1 kubelet: W0613 13:06:30.968116    1349 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "nginx-3950648766-6b3d2_default": Unexpected command output nsenter: cannot open : No such file or directory
Jun 13 13:06:30 node1 kubelet: with error: exit status 1
Jun 13 13:06:30 node1 kubelet: W0613 13:06:30.975409    1349 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "nginx-3950648766-6b3d2_default": Unexpected command output nsenter: cannot open : No such file or directory
Jun 13 13:06:30 node1 kubelet: with error: exit status 1
Jun 13 13:06:30 node1 kubelet: W0613 13:06:30.990380    1349 docker_sandbox.go:263] NetworkPlugin cni failed on the status hook for pod "nginx-3950648766-6b3d2_default": Unexpected command output nsenter: cannot open : No such file or directory
Jun 13 13:06:30 node1 kubelet: with error: exit status 1
Jun 13 13:06:32 node1 kubelet: E0613 13:06:32.027764    1349 remote_runtime.go:86] RunPodSandbox from runtime service failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod "nginx-3950648766-6b3d2_default" network: the server does not allow access to the requested resource (get pods nginx-3950648766-6b3d2)
Jun 13 13:06:32 node1 kubelet: E0613 13:06:32.027854    1349 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "nginx-3950648766-6b3d2_default(a7bb9223-4ff4-11e7-85cd-52540081c06a)" failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod "nginx-3950648766-6b3d2_default" network: the server does not allow access to the requested resource (get pods nginx-3950648766-6b3d2)
@                                                                                                                                                                                 
```

**Comment by kargakis** [comment]
Seems like an RBAC error with the CNI plugin. 

Did you try 
```
kubectl apply -f http://docs.projectcalico.org/master/getting-started/kubernetes/installation/rbac.yaml
```
http://docs.projectcalico.org/master/getting-started/kubernetes/installation/hosted/

**Comment by txg1550759** [comment]
Thank you very much. It's really a RBAC authorization problem
So I created rbac.yaml and restarted kube-apiserver.service, kubelet.service, and other services.
Pod container is still unable to allocate IP
Until I close the RBAC option in kube-apiserver.service
The calico CNI plug-in can assign IP to pod
Creating rbac.yaml authorization is invalid. Please help resolve
The rbac.yaml file is as follows

# Calico Version master
# http://docs.projectcalico.org/master/releases#master

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: calico-policy-controller
  namespace: kube-system
rules:
  - apiGroups:
    - ""
    - extensions
    resources:
      - pods
      - namespaces
      - networkpolicies
    verbs:
      - watch
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: calico-policy-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-policy-controller
subjects:
- kind: ServiceAccount
  name: calico-policy-controller
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: calico-node
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: calico-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-node
subjects:
- kind: ServiceAccount
  name: calico-node
  namespace: kube-system

 [root@master3 calico]# kubectl get pod --all-namespaces|grep calico
kube-system   calico-node-5r37q                           2/2       Running   3          20h
kube-system   calico-node-hldk2                           2/2       Running   2          20h
kube-system   calico-node-pjdj8                           2/2       Running   2          20h
kube-system   calico-node-rqkm9                           2/2       Running   2          20h
kube-system   calico-node-zqkxd                           2/2       Running   0          20h
kube-system   calico-policy-controller-2361802377-bgbwz   1/1       Running   2          20h
[root@master3 calico]# 
calico-policy-controller-2361802377-bgbwz  error logs

2017-06-14 07:24:13,384 7 INFO Restarting watch on resource: NetworkPolicy
2017-06-14 07:24:14,136 7 INFO Syncing 'Namespace' objects
2017-06-14 07:24:14,145 7 ERROR Unhandled exception killed Namespace manager
Traceback (most recent call last):
  File "<string>", line 311, in _manage_resource
  File "<string>", line 424, in _sync_resources
  File "site-packages/requests/models.py", line 808, in json
  File "site-packages/simplejson/__init__.py", line 516, in loads
  File "site-packages/simplejson/decoder.py", line 374, in decode
  File "site-packages/simplejson/decoder.py", line 404, in raw_decode
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by liggitt** [comment]
your log indicates you are running your calico pods with the `default` service account in the `kube-system` namespace. the RBAC example from calico grants permissions to the `calico-node` and `calico-policy-controller` service accounts, and is intended to be used with manifests that set up pods to run as those service accounts. I would recommend getting both the RBAC and calico manifests from the same version of the calico documentation (for example, https://docs.projectcalico.org/v2.5/getting-started/kubernetes/installation/hosted/hosted) so they work well together
