### ISSUE TITLE
Unexpected code path in protobuf decoding of the internal event recorder in 1.6

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#47714]
Use of the client-go event recorder is calling into NewNotRegisteredErrForType() on every response from the server, which I would not expect.  Not a huge number of allocations, but at least on first inspection I would not expect to get this on a decode into.

Kube 1.6, but may still happen in 1.7.

```
goroutine 529 [running]:
runtime/debug.Stack(0x8aad100, 0xc428f31600, 0x16)
	/usr/local/Cellar/go/1.7.5/libexec/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.7.5/libexec/src/runtime/debug/stack.go:16 +0x22
github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime.NewNotRegisteredErrForType(0xdbc7060, 0x89ab1e0, 0xc42d415730, 0xf866dc0)
	/Volumes/development/projects/origin/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/error.go:39 +0x26
github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime.(*Scheme).ObjectKinds(0xc42020e9c0, 0xdb59d00, 0xc428f31600, 0xc428f40310, 0x2, 0xc428f40312, 0x5, 0x0, 0x0)
	/Volumes/development/projects/origin/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:246 +0x1c1
github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/serializer/protobuf.(*Serializer).Decode(0xc420222a50, 0xc428f3e600, 0x22b, 0x600, 0x0, 0xdb59d00, 0xc428f31600, 0xc42c848c30, 0x0, 0x0, ...)
	/Volumes/development/projects/origin/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/serializer/protobuf/protobuf.go:136 +0xd53
github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.DirectDecoder.Decode(0xfb252e8, 0xc420222a50, 0xc428f3e600, 0x22b, 0x600, 0x0, 0xdb59d00, 0xc428f31600, 0xc42d415ac0, 0x0, ...)
	/Volumes/development/projects/origin/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:266 +0x97
github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*DirectDecoder).Decode(0xc422185130, 0xc428f3e600, 0x22b, 0x600, 0x0, 0xdb59d00, 0xc428f31600, 0xdb6da00, 0xc422185130, 0x0, ...)
	<autogenerated>:1 +0xad
github.com/openshift/origin/vendor/k8s.io/client-go/rest.Result.Into(0xc428f3e600, 0x22b, 0x600, 0xc421b084b0, 0x23, 0x0, 0x0, 0xc8, 0xdb6da00, 0xc422185130, ...)
	/Volumes/development/projects/origin/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/rest/request.go:1152 +0xad
github.com/openshift/origin/vendor/k8s.io/client-go/kubernetes/typed/core/v1.(*events).PatchWithEventNamespace(0xc4213c3c80, 0xc428f30e00, 0xc42bd5cf44, 0x33, 0x40, 0xb6dbf12, 0xc41fb86a15, 0x0)
	/Volumes/development/projects/origin/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/kubernetes/typed/core/v1/event_expansion.go:94 +0x386
github.com/openshift/origin/vendor/k8s.io/client-go/kubernetes/typed/core/v1.(*EventSinkImpl).Patch(0xc422185810, 0xc428f30e00, 0xc42bd5cf44, 0x33, 0x40, 0x86a29e0, 0x5, 0x0)
	/Volumes/development/projects/origin/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/kubernetes/typed/core/v1/event_expansion.go:162 +0x5b
github.com/openshift/origin/vendor/k8s.io/client-go/tools/record.recordEvent(0xdb8dcc0, 0xc422185810, 0xc428f30e00, 0xc42bd5cf44, 0x33, 0x40, 0x1, 0xc4213c3d00, 0xc420b59801)
	/Volumes/development/projects/origin/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/record/event.go:174 +0x591
github.com/openshift/origin/vendor/k8s.io/client-go/tools/record.recordToSink(0xdb8dcc0, 0xc422185810, 0xc428f30400, 0xc4213c3d00, 0xc4213c3ca0, 0x2540be400)
	/Volumes/development/projects/origin/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/record/event.go:138 +0x11f
github.com/openshift/origin/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartRecordingToSink.func1(0xc428f30400)
	/Volumes/development/projects/origin/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/record/event.go:120 +0x5c
github.com/openshift/origin/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1(0xdb76240, 0xc423c0c840, 0xc423c0c810)
	/Volumes/development/projects/origin/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/record/event.go:238 +0xf5
created by github.com/openshift/origin/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher
	/Volumes/development/projects/origin/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/client-go/tools/record/event.go:240 +0x6e
```

**Comment by smarterclayton** [comment]
It's possible that this is a case where a client-go is being initialized with a RESTClient that was created via kapi.Scheme, which is not technically valid.  The client-go version has a different Scheme.

**Comment by smarterclayton** [comment]
```
	eventBroadcaster := record.NewBroadcaster()
	eventBroadcaster.StartRecordingToSink(&v1core.EventSinkImpl{Interface: v1core.New(kubeExternalClient.Core().RESTClient()).Events("")})
```

this code is only correct if kubeExternalClient (`pkg/client/clientset_generated`) and v1core (`client-go/...`) have the same scheme, which they don't.

**Comment by smarterclayton** [comment]
Scheduler and attach/detach controller are both doing this

**Comment by mml** [comment]
cc @caesarxuchao 
@smarterclayton can you verify this is still happening?  (Re-open if so.)  Thanks.
