### ISSUE TITLE
SSH tunnel to worker nodes doesnt' work anymore for k8s 1.7

### ISSUE THREAD

**Issue by kayrus** [kubernetes/kubernetes#48419]
**What happened**:

ssh tunnel to kubelet nodes doesn't work anymore. Here are the apiserver logs:

```
Jul 03 08:57:04 master kube-apiserver[2288]: I0703 08:57:04.044968    2288 wrap.go:42] GET /api/v1/namespaces/monitoring/pods/grafana-2599252727-4cp3s/log?container=grafana&follow=true: (4.666795ms) 500
Jul 03 08:57:04 master kube-apiserver[2288]: goroutine 58028 [running]:
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc42222dc00, 0x1f4)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/log.go:219 +0xdd
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc42222dc00, 0x1f4)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/log.go:198 +0x35
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.(*legacyAuditResponseWriter).WriteHeader(0xc422dfa6c0, 0x1f4)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/legacy_audit.go:55 +0x55
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.(*responseWriterDelegator).WriteHeader(0xc422dfac90, 0x1f4)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:135 +0x45
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x3be77bd, 0x10, 0x7fbb240cdee0, 0xc424d2b680, 0x774ef00, 0xc427df1b20, 0xc42e570600, 0x1f4, 0x772b340, 0xc420430000)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:91 +0x8d
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x7fbb240d9d70, 0xc422dfaed0, 0x7756cc0, 0xc420687620, 0x0, 0x0, 0x3bcad5f, 0x2, 0x774ef00, 0xc427df1b20, ...)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:116 +0x29e
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.ErrorNegotiated(0x7fbb240d9d70, 0xc422dfaed0, 0x7731a80, 0xc4221d4b40, 0x7756cc0, 0xc420687620, 0x0, 0x0, 0x3bcad5f, 0x2, ...)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:135 +0x165
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.StreamObject(0x7fbb240d9d70, 0xc422dfaed0, 0xc8, 0x0, 0x0, 0x3bcad5f, 0x2, 0x7756cc0, 0xc420687620, 0x7fbb23b77ad0, ...)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:57 +0x77f
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObject(0x7fbb240d9d70, 0xc422dfaed0, 0xc8, 0x0, 0x0, 0x3bcad5f, 0x2, 0x7756cc0, 0xc420687620, 0x772c280, ...)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:45 +0x10c
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.transformResponseObject(0x7fbb240d9d70, 0xc422dfaed0, 0x775ca60, 0xc42114e300, 0xc421144a20, 0x7756cc0, 0xc420687620, 0x773bf00, 0xc420422d20, 0x772b700, ...)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/response.go:172 +0x2793
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.getResourceHandler.func1(0x774ef00, 0xc427df1b20, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:145 +0x3cd
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints.restfulGetResourceWithOptions.func1(0xc422dfa720, 0xc423aa0540)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1062 +0xb0
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc422dfa720, 0xc423aa0540)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:104 +0x1cf
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc42098b050, 0x774ee00, 0xc427df1b10, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:277 +0xb8d
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(0xc42098b050, 0x774ee00, 0xc427df1b10, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:199 +0x57
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x3be0ba2, 0xe, 0xc42098b050, 0xc4201455e0, 0x774ee00, 0xc427df1b10, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:153 +0x6e7
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc4209bad80, 0x774ee00, 0xc427df1b10, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         <autogenerated>:64 +0x86
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc4217db780, 0x774ee00, 0xc427df1b10, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:91 +0x122
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc426368f80, 0x774ee00, 0xc427df1b10, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x3dd
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc421be60e0, 0x774ee00, 0xc427df1b10, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x72
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x3be41f8, 0xf, 0xc4235195f0, 0xc421be60e0, 0x774ee00, 0xc427df1b10, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:161 +0x301
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc4245d1660, 0x774ee00, 0xc427df1b10, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         <autogenerated>:64 +0x86
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x774ee00, 0xc427df1b10, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:50 +0x30c
Jul 03 08:57:04 master kube-apiserver[2288]: net/http.HandlerFunc.ServeHTTP(0xc420de25c0, 0x774ee00, 0xc427df1b10, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /usr/local/go/src/net/http/server.go:1942 +0x44
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x774ee00, 0xc427df1b10, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:47 +0x226a
Jul 03 08:57:04 master kube-apiserver[2288]: net/http.HandlerFunc.ServeHTTP(0xc420de2880, 0x774ee00, 0xc427df1b10, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /usr/local/go/src/net/http/server.go:1942 +0x44
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithLegacyAudit.func1(0x774ef80, 0xc42222dc00, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/legacy_audit.go:144 +0x92f
Jul 03 08:57:04 master kube-apiserver[2288]: net/http.HandlerFunc.ServeHTTP(0xc420fae840, 0x774ef80, 0xc42222dc00, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /usr/local/go/src/net/http/server.go:1942 +0x44
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x774ef80, 0xc42222dc00, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:73 +0x2b0
Jul 03 08:57:04 master kube-apiserver[2288]: net/http.HandlerFunc.ServeHTTP(0xc422afe0a0, 0x774ef80, 0xc42222dc00, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /usr/local/go/src/net/http/server.go:1942 +0x44
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x774ef80, 0xc42222dc00, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xef
Jul 03 08:57:04 master kube-apiserver[2288]: net/http.HandlerFunc.ServeHTTP(0xc4245d1680, 0x774ef80, 0xc42222dc00, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /usr/local/go/src/net/http/server.go:1942 +0x44
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0x774ef80, 0xc42222dc00, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41 +0x11b
Jul 03 08:57:04 master kube-apiserver[2288]: net/http.HandlerFunc.ServeHTTP(0xc4245d1760, 0x7755800, 0xc427df1b08, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /usr/local/go/src/net/http/server.go:1942 +0x44
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc4245d1800, 0x7755800, 0xc427df1b08, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:84 +0x42f
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7755800, 0xc427df1b08, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:78 +0x292
Jul 03 08:57:04 master kube-apiserver[2288]: net/http.HandlerFunc.ServeHTTP(0xc420faf400, 0x7755800, 0xc427df1b08, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /usr/local/go/src/net/http/server.go:1942 +0x44
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x7755800, 0xc427df1b08, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:45 +0x200
Jul 03 08:57:04 master kube-apiserver[2288]: net/http.HandlerFunc.ServeHTTP(0xc423bd84e0, 0x7755800, 0xc427df1b08, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /usr/local/go/src/net/http/server.go:1942 +0x44
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x7755800, 0xc427df1b08, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xef
Jul 03 08:57:04 master kube-apiserver[2288]: net/http.HandlerFunc.ServeHTTP(0xc4245d1980, 0x7755800, 0xc427df1b08, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /usr/local/go/src/net/http/server.go:1942 +0x44
Jul 03 08:57:04 master kube-apiserver[2288]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc423bd8510, 0x7755800, 0xc427df1b08, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:198 +0x51
Jul 03 08:57:04 master kube-apiserver[2288]: net/http.serverHandler.ServeHTTP(0xc422a33600, 0x7755800, 0xc427df1b08, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /usr/local/go/src/net/http/server.go:2568 +0x92
Jul 03 08:57:04 master kube-apiserver[2288]: net/http.initNPNRequest.ServeHTTP(0xc423dfe380, 0xc422a33600, 0x7755800, 0xc427df1b08, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /usr/local/go/src/net/http/server.go:3088 +0x93
Jul 03 08:57:04 master kube-apiserver[2288]: net/http.(*initNPNRequest).ServeHTTP(0xc42cc1d940, 0x7755800, 0xc427df1b08, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         <autogenerated>:312 +0x74
Jul 03 08:57:04 master kube-apiserver[2288]: net/http.(Handler).ServeHTTP-fm(0x7755800, 0xc427df1b08, 0xc42e570600)
Jul 03 08:57:04 master kube-apiserver[2288]:         /usr/local/go/src/net/http/h2_bundle.go:4331 +0x4d
Jul 03 08:57:04 master kube-apiserver[2288]: net/http.(*http2serverConn).runHandler(0xc42bc9c1c0, 0xc427df1b08, 0xc42e570600, 0xc4242fa6e0)
Jul 03 08:57:04 master kube-apiserver[2288]:         /usr/local/go/src/net/http/h2_bundle.go:4611 +0x89
Jul 03 08:57:04 master kube-apiserver[2288]: created by net/http.(*http2serverConn).processHeaders
Jul 03 08:57:04 master kube-apiserver[2288]:         /usr/local/go/src/net/http/h2_bundle.go:4343 +0x4ac
Jul 03 08:57:04 master kube-apiserver[2288]: logging error output: "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Get https://node-1:10250/containerLogs/monitoring/grafana-2599252727-4cp3s/grafana?follow=true: No SSH tunnels currently open. Were the targets able to accept an ssh-key for user \\\"kube\\\"?\",\"code\":500}\n"
```

Here is the `authorized_keys` file on kubelet node:

```
no-pty,no-user-rc,no-X11-forwarding,command="/bin/false" %key-is-here%
```

Here is the manual tunnel command which works fine:

```
ssh -L 1234:127.0.0.1:10250 -i /etc/kubernetes/certs/id_rsa kube@192.168.140.155 -N
```

Same ssh tunnel with the same configuration works fine on k8s 1.6.x

P.S. I use tls cert auth + ssh tunneling:

```
/usr/bin/kube-apiserver ... \
  --ssh-keyfile=/etc/kubernetes/certs/id_rsa \
  --ssh-user=kube \
  --kubelet-client-certificate=/etc/kubernetes/certs/kubectl.pem \
  --kubelet-client-key=/etc/kubernetes/certs/kubectl-key.pem
```

This issue was found by our automatic tests.

**Comment by liggitt** [comment]
@kubernetes/sig-api-machinery-bugs
