### ISSUE TITLE
k8s.io/apiserver: Too many requests handler double-calls NewLogged

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#48782]
Example call stack from #48700:

```
I0708 04:52:19.376927       8 logs.go:41] http2: panic serving 35.184.222.31:52308: multiple NewLogged calls!
79860470 goroutine 1237316710 [running]:
79860471 net/http.(*http2serverConn).runHandler.func1(0xc6c13e0a28, 0xc4794b1faf, 0xc4455908c0)
79860472         /usr/local/go/src/net/http/h2_bundle.go:4604 +0x190
79860473 panic(0x2ccc6c0, 0xc6a7a91f90)
79860474         /usr/local/go/src/runtime/panic.go:489 +0x2cf
79860475 k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc4794b1cd8, 0x1, 0x1)
79860476         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
79860477 panic(0x2ccc6c0, 0xc6a7a91f90)
79860478         /usr/local/go/src/runtime/panic.go:489 +0x2cf
79860479 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.NewLogged(0xc72d583c00, 0xc42a5d2ac8, 0x6de9d00)
79860480         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/log.go:99 +0x85
79860481 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.tooManyRequests(0xc72d583c00, 0x6c2e4c0, 0xc66fabc150)
79860482         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:106 +0x39
79860483 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x6c2e4c0, 0xc66fabc150, 0xc72d583c00)
79860484         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:97 +0x1e2
79860485 net/http.HandlerFunc.ServeHTTP(0xc421d0ef00, 0x6c2e4c0, 0xc66fabc150, 0xc72d583c00)
79860486         /usr/local/go/src/net/http/server.go:1942 +0x44
79860487 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x6c2e4c0, 0xc66fabc150, 0xc72d583c00)
79860488         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:45 +0x200
79860489 net/http.HandlerFunc.ServeHTTP(0xc422b9af30, 0x6c2e4c0, 0xc66fabc150, 0xc72d583c00)
79860490         /usr/local/go/src/net/http/server.go:1942 +0x44
79860491 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x6c2e4c0, 0xc66fabc150, 0xc72d583c00)
79860492         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xef
79860493 net/http.HandlerFunc.ServeHTTP(0xc422ec2dc0, 0x6c2e4c0, 0xc66fabc150, 0xc72d583c00)
79860494         /usr/local/go/src/net/http/server.go:1942 +0x44
79860495 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0x6c2e4c0, 0xc66fabc150, 0xc72d583c00)
79860496         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41 +0x11b
79860497 net/http.HandlerFunc.ServeHTTP(0xc422ec2de0, 0x6c2ee80, 0xc6c13e0a28, 0xc72d583c00)
79860498         /usr/local/go/src/net/http/server.go:1942 +0x44
79860499 k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc422b9aff0, 0x6c2ee80, 0xc6c13e0a28, 0xc72d583c00)
79860500         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:198 +0x51
79860501 net/http.serverHandler.ServeHTTP(0xc422150a50, 0x6c2ee80, 0xc6c13e0a28, 0xc72d583c00)
79860502         /usr/local/go/src/net/http/server.go:2568 +0x92
79860503 net/http.initNPNRequest.ServeHTTP(0xc447aa0a80, 0xc422150a50, 0x6c2ee80, 0xc6c13e0a28, 0xc72d583c00)
79860504         /usr/local/go/src/net/http/server.go:3088 +0x93
79860505 net/http.(*initNPNRequest).ServeHTTP(0xc4409f7920, 0x6c2ee80, 0xc6c13e0a28, 0xc72d583c00)
79860506         <autogenerated>:312 +0x74
79860507 net/http.(Handler).ServeHTTP-fm(0x6c2ee80, 0xc6c13e0a28, 0xc72d583c00)
79860508         /usr/local/go/src/net/http/h2_bundle.go:4331 +0x4d
79860509 net/http.(*http2serverConn).runHandler(0xc4455908c0, 0xc6c13e0a28, 0xc72d583c00, 0xc650c25d20)
79860510         /usr/local/go/src/net/http/h2_bundle.go:4611 +0x89
79860511 created by net/http.(*http2serverConn).processHeaders
79860512         /usr/local/go/src/net/http/h2_bundle.go:4343 +0x4ac
```

We should fix this and **add an integration test that sets the limit low and exercises apiserver when it is getting too many requests**.

**Comment by shyamjvs** [comment]
Should be fixed by the above PR. Closing it.
