### ISSUE TITLE
pkg/proxy unit tests fail when you don't have an internet connection

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#4884]
It failed the "does it work while I'm on a plane" test.  :)  Assigning this to you since I think you were the last one in here.

```
$ hack/test-go.sh pkg/proxy
--- FAIL: TestTCPProxy (0.00s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 9 [running]:
testing.func·006()
	/usr/local/Cellar/go/1.4.1/libexec/src/testing/testing.go:441 +0x181
github.com/GoogleCloudPlatform/kubernetes/pkg/proxy.chooseHostInterface(0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/clayton/projects/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/proxier.go:791 +0x738
github.com/GoogleCloudPlatform/kubernetes/pkg/proxy.NewProxier(0x1013a08, 0xc20800a5c0, 0xc2080b2450, 0x10, 0x10, 0x1013a40, 0x62bac8, 0x0)
	/Users/clayton/projects/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/proxier.go:322 +0xe1
github.com/GoogleCloudPlatform/kubernetes/pkg/proxy.TestTCPProxy(0xc2080421b0)
	/Users/clayton/projects/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/proxier_test.go:204 +0x2da
testing.tRunner(0xc2080421b0, 0x61f680)
	/usr/local/Cellar/go/1.4.1/libexec/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/usr/local/Cellar/go/1.4.1/libexec/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
testing.RunTests(0x4e7f30, 0x61f680, 0x17, 0x17, 0x1013801)
	/usr/local/Cellar/go/1.4.1/libexec/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc20802e320, 0x62af20)
	/usr/local/Cellar/go/1.4.1/libexec/src/testing/testing.go:485 +0x6c
main.main()
	github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/_test/_testmain.go:96 +0x1d5

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x622b40)
	/Users/clayton/projects/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x78
created by github.com/golang/glog.init·1
	/Users/clayton/projects/go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x2a7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4.1/libexec/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [IO wait]:
net.(*pollDesc).Wait(0xc208010140, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010140, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080100e0, 0x0, 0x1011e20, 0xc2080b2368)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20802c018, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20802c018, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/tcpsock_posix.go:244 +0x4c
net/http/httptest.(*historyListener).Accept(0xc2080ae120, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/httptest/server.go:48 +0x7a
net/http.(*Server).Serve(0xc208030540, 0x1013828, 0xc2080ae120, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/server.go:1728 +0x92
created by net/http/httptest.(*Server).Start
	/usr/local/Cellar/go/1.4.1/libexec/src/net/http/httptest/server.go:109 +0x35e

goroutine 8 [IO wait]:
net.(*pollDesc).Wait(0xc208010220, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010220, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).readFrom(0xc2080101c0, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x0, 0x0, 0x1011e20, 0xc2080b23d8)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/fd_unix.go:269 +0x4a1
net.(*UDPConn).ReadFromUDP(0xc20802c028, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/udpsock_posix.go:67 +0x124
net.(*UDPConn).ReadFrom(0xc20802c028, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.4.1/libexec/src/net/udpsock_posix.go:82 +0x12e
github.com/GoogleCloudPlatform/kubernetes/pkg/proxy.(*udpEchoServer).Loop(0xc2080b2330)
	/Users/clayton/projects/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/udp_server.go:32 +0xad
created by github.com/GoogleCloudPlatform/kubernetes/pkg/proxy.init·1
	/Users/clayton/projects/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/proxier_test.go:144 +0xa42
FAIL	github.com/GoogleCloudPlatform/kubernetes/pkg/proxy	0.009s
```

**Comment by sub-mod** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/4865 would fix this

**Comment by sub-mod** [comment]
@smarterclayton When there is no internet connection , should the kube-proxy use 127.0.0.1 right ?

**Comment by smarterclayton** [comment]
Good question - or the test should log an error message but not actually fail.  I don't know if Kube-proxy listening on 127.0.0.1 is something we would want happening by accident in a prod env.

**Comment by thockin** [comment]
kube-proxy listening on 127 is probably not going to actually WORK either.
