### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by xiajohnnyxia** [kubernetes/kubernetes#49648]
When i was debugging the source codes , run to 
`/home/johnny/workspace/go/GoWorks/src/kubernetes-1.7.0/vendor/k8s.io/apiserver/pkg/server/openapi/openapi.go`，it throws an error and exits.

```
func (o *openAPI) init(webServices []*restful.WebService) error {
	if o.config.GetOperationIDAndTags == nil {
		o.config.GetOperationIDAndTags = func(r *restful.Route) (string, []string, error) {
			return r.Operation, nil, nil
		}
	}
	if o.config.GetDefinitionName == nil {
		o.config.GetDefinitionName = func(name string) (string, spec.Extensions) {
			return name[strings.LastIndex(name, "/")+1:], nil
		}
	}




	

       o.definitions = o.config.GetDefinitions(func(name string) spec.Ref {
 		defName, _ := o.config.GetDefinitionName(name)
 		return spec.MustCreateRef(DEFINITION_PREFIX + openapi.EscapeJsonPointer(defName))
 	})




	if o.config.CommonResponses == nil {
		o.config.CommonResponses = map[int]spec.Response{}
	}
	err := o.buildPaths(webServices)
	if err != nil {
		return err
	}
	if o.config.SecurityDefinitions != nil {
		o.swagger.SecurityDefinitions = *o.config.SecurityDefinitions
		o.swagger.Security = o.config.DefaultSecurity
	}
	if o.config.PostProcessSpec != nil {
		o.swagger, err = o.config.PostProcessSpec(o.swagger)
		if err != nil {
			return err
		}
	}

	return nil
}
```

What's wrong with it?

```
[restful] 2017/07/27 00:51:06 log.go:33: [restful/swagger] https://10.0.2.15:6443/swaggerui/ is mapped to folder /swagger-ui/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x199f006]

goroutine 1 [running]:
kubernetes-1.7.0/vendor/k8s.io/apiserver/pkg/server/openapi.(*openAPI).init(0xc421ab7950, 0xc421b0c120, 0x22, 0x22, 0x0, 0x0)
	xxx/src/kubernetes-1.7.0/vendor/k8s.io/apiserver/pkg/server/openapi/openapi.go:97 +0xe6
kubernetes-1.7.0/vendor/k8s.io/apiserver/pkg/server/openapi.BuildSwaggerSpec(0xc421b0c120, 0x22, 0x22, 0xc420157200, 0x0, 0x0, 0x0)
	xxx/src/kubernetes-1.7.0/vendor/k8s.io/apiserver/pkg/server/openapi/openapi.go:70 +0x2bc
kubernetes-1.7.0/vendor/k8s.io/apiserver/pkg/server/routes.OpenAPI.Install(0xc420157200, 0xc420b40000, 0xc420abb810, 0x0)
	xxx/src/kubernetes-1.7.0/vendor/k8s.io/apiserver/pkg/server/routes/openapi.go:36 +0x96
kubernetes-1.7.0/vendor/k8s.io/apiserver/pkg/server.(*GenericAPIServer).PrepareOpenAPIService(0xc420a9d0e0)
	xxx/src/kubernetes-1.7.0/vendor/k8s.io/apiserver/pkg/server/genericapiserver.go:262 +0xc2
kubernetes-1.7.0/vendor/k8s.io/apiserver/pkg/server.(*GenericAPIServer).PrepareRun(0xc420a9d0e0, 0x0)
	xxx/src/kubernetes-1.7.0/vendor/k8s.io/apiserver/pkg/server/genericapiserver.go:250 +0x95
kubernetes-1.7.0/vendor/k8s.io/kubernetes/cmd/kube-apiserver/app.Run(0xc420432200, 0xc42006e0c0, 0x0, 0x0)
	xxx/src/kubernetes-1.7.0/vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:155 +0x6a3
main.main()
	xxx/src/kubernetes-1.7.0/io/kubernetes/cmd/kube-apiserver/apiserver.go:51 +0xe4
```

**Comment by xiajohnnyxia** [comment]
remove sig/federation
