### ISSUE TITLE
e2e/unit/integration flake: pull-kubernetes-verify

### ISSUE THREAD

**Issue by sbezverk** [kubernetes/kubernetes#49641]
Consistently failure on pull-kubernetes-verify..
```log
I0726 14:17:15.960] SUCCESS  hack/make-rules/../../hack/verify-symbols.sh	126s
I0726 14:17:15.960] Verifying hack/make-rules/../../hack/verify-test-images.sh
I0726 14:17:15.971] SUCCESS  hack/make-rules/../../hack/verify-test-images.sh	0s
I0726 14:17:15.972] Skipping hack/make-rules/../../hack/verify-test-owners.sh
I0726 14:17:15.973] Verifying hack/make-rules/../../hack/verify-flags-underscore.py
I0726 14:17:45.533] SUCCESS  hack/make-rules/../../hack/verify-flags-underscore.py	30s
I0726 14:17:45.534] Makefile:126: recipe for target 'verify' failed
W0726 14:17:45.634] make: *** [verify] Error 1
W0726 14:17:48.581] Traceback (most recent call last):
W0726 14:17:48.581]   File "/var/lib/jenkins/workspace/pull-kubernetes-verify/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 110, in <module>
W0726 14:17:48.581]     main(ARGS.branch, ARGS.script, ARGS.force)
W0726 14:17:48.581]   File "/var/lib/jenkins/workspace/pull-kubernetes-verify/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 94, in main
W0726 14:17:48.581]     'bash', '-c', 'cd kubernetes && %s' % script,
W0726 14:17:48.582]   File "/var/lib/jenkins/workspace/pull-kubernetes-verify/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 52, in check
W0726 14:17:48.582]     subprocess.check_call(cmd)
W0726 14:17:48.582]   File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
W0726 14:17:48.582]     raise CalledProcessError(retcode, cmd)
W0726 14:17:48.582] subprocess.CalledProcessError: Command '('docker', 'run', '--rm=true', '--privileged=true', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-v', '/etc/localtime:/etc/localtime:ro', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-verify/go/src/k8s.io/kubernetes:/go/src/k8s.io/kubernetes', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-verify/go/src/k8s.io/kubernetes/_artifacts:/workspace/artifacts', '-e', 'KUBE_FORCE_VERIFY_CHECKS=n', '-e', 'KUBE_VERIFY_GIT_BRANCH=master', '-e', 'REPO_DIR=/var/lib/jenkins/workspace/pull-kubernetes-verify/go/src/k8s.io/kubernetes', 'gcr.io/k8s-testimages/kubekins-test:1.7-v20170713-c28e0556', 'bash', '-c', 'cd kubernetes && ./hack/jenkins/verify-dockerized.sh')' returned non-zero exit status 2
E0726 14:17:48.593] Build failed
I0726 14:17:48.593] process 12085 exited with code 1 after 39.9m
E0726 14:17:48.594] FAIL: pull-kubernetes-verify
I0726 14:17:48.594] Upload result and artifacts...
I0726 14:17:48.594] Gubernator results at https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49598/pull-kubernetes-verify/41706
I0726 14:17:48.595] Call:  gsutil -m -q -o GSUtil:use_magicfile=True cp -r -c -z log,txt,xml _artifacts gs://kubernetes-jenkins/pr-logs/pull/49598/pull-kubernetes-verify/41706/artifacts
I0726 14:17:50.157] process 5514 exited with code 0 after 0.0m
I0726 14:17:50.158] Call:  git rev-parse HEAD
I0726 14:17:50.161] process 6022 exited with code 0 after 0.0m
```

**Comment by cblecker** [comment]
/assign
Can you please link the PR? The log provided is incomplete.

**Comment by sbezverk** [comment]
https://github.com/kubernetes/kubernetes/pull/49598

**Comment by cblecker** [comment]
It's not a flake. There is a legitimate error on your PR (I've commented with details in that PR).
Closing..
/close

**Comment by sbezverk** [comment]
I can assure you that I have read the log and saw that failed message, but when I run the same command locally on my branch, gofmt returns rc 0. 
```
gofmt -d -s pkg/volume/local/local.go 
diff pkg/volume/local/local.go gofmt/pkg/volume/local/local.go
--- /tmp/gofmt973539598 2017-07-26 11:51:26.106026591 -0400
+++ /tmp/gofmt650953493 2017-07-26 11:51:26.106026591 -0400
@@ -102,12 +102,12 @@
 
        return &localVolumeMounter{
                localVolume: &localVolume{
-                       podUID:     pod.UID,
-                       volName:    spec.Name(),
-                       mounter:    plugin.host.GetMounter(),
-                       plugin:     plugin,
-                       globalPath: volumeSource.Path,
-                        MetricsProvider: volume.NewMetricsStatFS(volumeSource.Path),
+                       podUID:          pod.UID,
+                       volName:         spec.Name(),
+                       mounter:         plugin.host.GetMounter(),
+                       plugin:          plugin,
+                       globalPath:      volumeSource.Path,
+                       MetricsProvider: volume.NewMetricsStatFS(volumeSource.Path),
                },
                readOnly: readOnly,
        }, nil
@@ -152,7 +152,7 @@
        // Mounter interface that provides system calls to mount the global path to the pod local path.
        mounter mount.Interface
        plugin  *localVolumePlugin
-        volume.MetricsProvider
+       volume.MetricsProvider
 }
 
 func (l *localVolume) GetPath() string {
[root@kube-2 kubernetes]# echo $?
0
```
