### ISSUE TITLE
kubectl edit panics when you have an empty list

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kubernetes#50147]
Try running `kubectl edit ingress` and adding an ingress object, or an empty list, then exit the editor – it will panic like this:

```
panic: runtime error: index out of range

goroutine 1 [running]:
k8s.io/kubernetes/pkg/kubectl/cmd/util/editor.(*EditOptions).Run.func1(0x3b7f0f8, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/editor/editoptions.go:237 +0xed2
k8s.io/kubernetes/pkg/kubectl/cmd/util/editor.(*EditOptions).Run(0xc420158400, 0x3a6c900, 0xc420239710)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/editor/editoptions.go:334 +0x731
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdEdit.func1(0xc420376480, 0xc420273ac0, 0x1, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/edit.go:99 +0x15b
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc420376480, 0xc420273a50, 0x1, 0x1, 0xc420376480, 0xc420273a50)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:603 +0x22b
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420453b00, 0x8000101, 0x0, 0xffffffffffffffff)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:689 +0x339
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420453b00, 0xc420239710, 0x3a46140)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:648 +0x2b
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:39 +0xd5
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:26 +0x22

```

I've also tried `kubectl edit ds`, and for the sake of experiment tried adding a Pod, then it failed rather gracefully with this message:
```
A copy of your changes has been stored to "/var/folders/zr/qjxvg8xn10nd06j2vflwtj880000gn/T/kubectl-edit-0133o.yaml"
error: no original object found for &unstructured.Unstructured{Object:map[string]interface {}{"apiVersion":"v1", "kind":"Pod", "metadata":map[string]interface {}{"namespace":"default"}}}
```
But when I tried to add a DaemonSet, it paniced.

I am not sure how we should fix, perhaps editing of lists isn't something a normal user is expected to do... Let's discuss.

**Comment by errordeveloper** [comment]
So I wanted to test how it would behave if I take an item out of my list, so I've create and ingress object and tried `kubectl edit ingress`. To my surprise I've found only one ingress object without a list. When I added a second object, `kubectl edit ingress` gave me a list to edit. So I must say that flattening of the list in case there is only one object was a bit surprising.
Now that I have a list of two items, I've decided to try deleting one by removing it from the list, and it turns that's not possible.

**Comment by errordeveloper** [comment]
It feels like the problem is complicated, and I'd rather see `kubectl edit <kind>` disallowed unless users passed a name of a specific resource.
If we belive some folks rely on `kubectl edit <kind>` to work when there is only one resource to edit, maybe we can keep that...
If we cannot disallow this, I'd rather see it fixed in a way where removing items results in deletion and editing a single item list is actually about editing a list.
At the very least, of course, we should fix the panic, but I still want to hear what people think about this before I open a PR (presumably at least fixing the panic should be trivial).

**Comment by dixudx** [comment]
@errordeveloper  I'm working on this. Already submitted a PR in #50205. PTAL.

**Comment by shiywang** [comment]
>  To my surprise I've found only one ingress object without a list. When I added a second object, kubectl edit ingress gave me a list to edit. 

I think at the very beginning, at least v1.5.0 the logic is already like this, I'm not sure why this bothering you

> If we belive some folks rely on kubectl edit <kind> to work when there is only one resource to edit, maybe we can keep that...

I use this lot of time, I'd prefer keep it.

also cc @kubernetes/sig-cli-misc

**Comment by liggitt** [comment]
I don't think edit should open with an empty list.

`edit myresource` should open a list if there are multiple items, a single item if there is only one, and error if there are none of that type.

`edit myresource/name` should open a single item if it is found, and error if it is not found

**Comment by errordeveloper** [comment]
@liggitt that sounds good to me.

@shiywang I was just a bit surprised, that's all.
