### ISSUE TITLE
TestUpdateClusterRace flake

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#50262]
seen in https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/50258/pull-kubernetes-unit/45229/artifacts/junit_42602c56127c09f7378bbc50f2d72cb7f5b883c6_20170807-183126.stdout

```
=== RUN   TestUpdateClusterRace
E0807 18:35:35.756756   23178 cluster_client.go:145] Failed to list nodes while getting zone names: couldn't get version/kind; json parse error: invalid character 'o' looking for beginning of value
E0807 18:35:35.765719   23178 cluster_client.go:145] Failed to list nodes while getting zone names: couldn't get version/kind; json parse error: invalid character 'o' looking for beginning of value
==================
WARNING: DATA RACE
Write at 0x00c4202c1fb0 by goroutine 34:
  runtime.mapdelete()
      /usr/local/go/src/runtime/hashmap.go:598 +0x0
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets.String.Delete()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets/string.go:58 +0x8f
  k8s.io/kubernetes/federation/pkg/federation-controller/cluster.(*ClusterController).delFromClusterSetByName()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller.go:109 +0x194
  k8s.io/kubernetes/federation/pkg/federation-controller/cluster.(*ClusterController).delFromClusterSet()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller.go:101 +0xbc
  k8s.io/kubernetes/federation/pkg/federation-controller/cluster.TestUpdateClusterRace()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller_test.go:193 +0x667
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:657 +0x107

Previous read at 0x00c4202c1fb0 by goroutine 37:
  k8s.io/kubernetes/federation/pkg/federation-controller/cluster.(*ClusterController).UpdateClusterStatus()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller.go:190 +0x2ba
  k8s.io/kubernetes/federation/pkg/federation-controller/cluster.TestUpdateClusterRace.func2()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller_test.go:185 +0x38

Goroutine 34 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:697 +0x543
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:882 +0xaa
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:657 +0x107
  testing.runTests()
      /usr/local/go/src/testing/testing.go:888 +0x4e0
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:822 +0x1c3
  main.main()
      k8s.io/kubernetes/federation/pkg/federation-controller/cluster/_test/_testmain.go:44 +0x20f

Goroutine 37 (running) created at:
  k8s.io/kubernetes/federation/pkg/federation-controller/cluster.TestUpdateClusterRace()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller_test.go:187 +0x5e4
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:657 +0x107
==================
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1c7760b]

goroutine 85 [running]:
k8s.io/kubernetes/federation/pkg/federation-controller/cluster.(*ClusterClient).GetClusterHealthStatus(0xc420365f00, 0xc42065f500)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/cluster_client.go:100 +0x24b
k8s.io/kubernetes/federation/pkg/federation-controller/cluster.(*ClusterController).GetClusterStatus(0xc4200ea770, 0xc42065f500, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller.go:172 +0x9a
k8s.io/kubernetes/federation/pkg/federation-controller/cluster.(*ClusterController).UpdateClusterStatus(0xc4200ea770, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller.go:204 +0x427
k8s.io/kubernetes/federation/pkg/federation-controller/cluster.TestUpdateClusterRace.func2(0xc4200ea770)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller_test.go:185 +0x39
created by k8s.io/kubernetes/federation/pkg/federation-controller/cluster.TestUpdateClusterRace
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller_test.go:187 +0x5e5
FAIL	k8s.io/kubernetes/federation/pkg/federation-controller/cluster	1.205s
=== RUN   TestIngressController
E0807 18:35:42.628738   23320 event.go:260] Could not construct reference to: '&v1beta1.Ingress{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"test-ingress", GenerateName:"", Namespace:"mynamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"ingress.federation.kubernetes.io/first-cluster":"cluster1"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v1beta1.IngressSpec{Backend:(*v1beta1.IngressBackend)(nil), TLS:[]v1beta1.IngressTLS(nil), Rules:[]v1beta1.IngressRule(nil)}, Status:v1beta1.IngressStatus{LoadBalancer:v1.LoadBalancerStatus{Ingress:[]v1.LoadBalancerIngress(nil)}}}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'CreateInCluster' 'Creating ingress "mynamespace/test-ingress" in cluster cluster1'
E0807 18:35:42.633482   23320 event.go:260] Could not construct reference to: '&v1beta1.Ingress{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"test-ingress", GenerateName:"", Namespace:"mynamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"ingress.federation.kubernetes.io/first-cluster":"cluster1"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v1beta1.IngressSpec{Backend:(*v1beta1.IngressBackend)(nil), TLS:[]v1beta1.IngressTLS(nil), Rules:[]v1beta1.IngressRule(nil)}, Status:v1beta1.IngressStatus{LoadBalancer:v1.LoadBalancerStatus{Ingress:[]v1.LoadBalancerIngress(nil)}}}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'CreateInCluster' 'Creating ingress "mynamespace/test-ingress" in cluster cluster1'
E0807 18:35:43.840482   23320 event.go:260] Could not construct reference to: '&v1beta1.Ingress{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"test-ingress", GenerateName:"", Namespace:"mynamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{}, Annotations:map[string]string{"ingress.federation.kubernetes.io/first-cluster":"cluster1", "federation.alpha.kubernetes.io/cluster-selector":"[{\"key\": \"cluster\", \"operator\": \"in\", \"values\": [\"cluster1\",\"cluster2\"]}]", "A":"B"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v1beta1.IngressSpec{Backend:(*v1beta1.IngressBackend)(nil), TLS:[]v1beta1.IngressTLS(nil), Rules:[]v1beta1.IngressRule(nil)}, Status:v1beta1.IngressStatus{LoadBalancer:v1.LoadBalancerStatus{Ingress:[]v1.LoadBalancerIngress(nil)}}}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'UpdateInCluster' 'Updating ingress "mynamespace/test-ingress" in cluster cluster1'
E0807 18:35:43.844918   23320 event.go:260] Could not construct reference to: '&v1beta1.Ingress{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"test-ingress", GenerateName:"", Namespace:"mynamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{}, Annotations:map[string]string{"ingress.federation.kubernetes.io/first-cluster":"cluster1", "federation.alpha.kubernetes.io/cluster-selector":"[{\"key\": \"cluster\", \"operator\": \"in\", \"values\": [\"cluster1\",\"cluster2\"]}]", "A":"B", "kubernetes.io/ingress.global-static-ip-name":"foo"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v1beta1.IngressSpec{Backend:(*v1beta1.IngressBackend)(nil), TLS:[]v1beta1.IngressTLS(nil), Rules:[]v1beta1.IngressRule(nil)}, Status:v1beta1.IngressStatus{LoadBalancer:v1.LoadBalancerStatus{Ingress:[]v1.LoadBalancerIngress(nil)}}}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'UpdateInCluster' 'Updating ingress "mynamespace/test-ingress" in cluster cluster1'
E0807 18:35:43.846056   23320 event.go:260] Could not construct reference to: '&v1beta1.Ingress{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"test-ingress", GenerateName:"", Namespace:"mynamespace", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"ingress.federation.kubernetes.io/first-cluster":"cluster1", "A":"B", "federation.alpha.kubernetes.io/cluster-selector":"[{\"key\": \"cluster\", \"operator\": \"in\", \"values\": [\"cluster1\",\"cluster2\"]}]", "kubernetes.io/ingress.global-static-ip-name":"foo"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:v1beta1.IngressSpec{Backend:(*v1beta1.IngressBackend)(nil), TLS:[]v1beta1.IngressTLS(nil), Rules:[]v1beta1.IngressRule(nil)}, Status:v1beta1.IngressStatus{LoadBalancer:v1.LoadBalancerStatus{Ingress:[]v1.LoadBalancerIngress(nil)}}}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'CreateInCluster' 'Creating ingress "mynamespace/test-ingress" in cluster cluster2'
```

**Comment by shashidharatd** [comment]
Another flake in here. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46090/pull-kubernetes-unit/45339/

**Comment by liggitt** [comment]
cc @dqminh

**Comment by yastij** [comment]
@liggitt - any update on this one ?

**Comment by liggitt** [comment]
> @liggitt - any update on this one ?

I just opened the issue because I encountered it. @kubernetes/sig-federation-test-failures is assigned to resolve it.

**Comment by dqminh** [comment]
@liggitt strange, i can take a look at this.

**Comment by shashidharatd** [comment]
I had just raised a fix. @dqminh, Can you PTAL. Thanks!

**Comment by MikeSpreitzer** [comment]
I have also been getting intermittent failures from this test case.  The reported symptom is a little different fro the one originally reported here, but since it also involves a mysterious data validation complaint I am going to guess it might have the same root cause.  You can see an example in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/47262/pull-kubernetes-unit/45970/ .
