### ISSUE TITLE
The cross-build is broken

### ISSUE THREAD

**Issue by luxas** [kubernetes/kubernetes#50675]
```
I0815 09:30:09.341] +++ [0815 09:28:58] windows/amd64: go build started
I0815 09:30:09.341] # k8s.io/kubernetes/pkg/kubelet/dockershim
I0815 09:30:09.341] pkg/kubelet/dockershim/docker_container.go:153: not enough arguments in call to ds.getSecurityOpts
I0815 09:30:09.341] 	have (string, rune)
I0815 09:30:09.342] 	want (string, *"k8s.io/kubernetes/pkg/kubelet/apis/cri/v1alpha1/runtime".PodSandboxConfig, rune)
I0815 09:30:09.342] pkg/kubelet/dockershim/docker_sandbox.go:591: not enough arguments in call to ds.getSecurityOpts
I0815 09:30:09.342] 	have (string, rune)
I0815 09:30:09.342] 	want (string, *"k8s.io/kubernetes/pkg/kubelet/apis/cri/v1alpha1/runtime".PodSandboxConfig, rune)
I0815 09:30:09.342] !!! [0815 09:30:09] Call tree:
I0815 09:30:09.343] !!! [0815 09:30:09]  1: /go/src/k8s.io/kubernetes/hack/lib/golang.sh:697 kube::golang::build_binaries_for_platform(...)
I0815 09:30:09.343] !!! [0815 09:30:09]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
I0815 09:30:09.348] Makefile:92: recipe for target 'all' failed
I0815 09:30:09.351] Makefile:419: recipe for target 'cross' failed
W0815 09:30:09.452] !!! [0815 09:30:09] Call tree:
W0815 09:30:09.452] !!! [0815 09:30:09]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
W0815 09:30:09.452] make[1]: *** [all] Error 1
W0815 09:30:09.453] make: *** [cross] Error 1
W0815 09:30:09.743] !!! [0815 09:30:09] Call tree:
W0815 09:30:09.745] !!! [0815 09:30:09]  1: build/../build/common.sh:521 kube::build::run_build_command_ex(...)
W0815 09:30:09.747] !!! [0815 09:30:09]  2: build/release.sh:36 kube::build::run_build_command(...)
W0815 09:30:09.760] make: *** [release] Error 1
W0815 09:30:09.761] Traceback (most recent call last):
W0815 09:30:09.761]   File "/var/lib/jenkins/workspace/pull-kubernetes-cross/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>
W0815 09:30:09.784]     main(ARGS.env, ARGS.cmd + ARGS.args)
W0815 09:30:09.784]   File "/var/lib/jenkins/workspace/pull-kubernetes-cross/./test-infra/jenkins/../scenarios/execute.py", line 41, in main
W0815 09:30:09.785]     check(*cmd)
W0815 09:30:09.785]   File "/var/lib/jenkins/workspace/pull-kubernetes-cross/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W0815 09:30:09.785]     subprocess.check_call(cmd)
W0815 09:30:09.785]   File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
W0815 09:30:09.802]     raise CalledProcessError(retcode, cmd)
W0815 09:30:09.802] subprocess.CalledProcessError: Command '('make', 'release')' returned non-zero exit status 2
I0815 09:30:09.809] Makefile:382: recipe for target 'release' failed
E0815 09:30:09.809] Command failed
```

seems to belong to sig node @kubernetes/sig-node-bugs PTAL and fix ASAP

**Comment by xiangpengzhao** [comment]
/assign @feiskyer
as it seems like having something to do with https://github.com/kubernetes/kubernetes/pull/49178
