### ISSUE TITLE
Controller manager NPE because some controllers aren't ready to receive shared informer events immediately after adding handlers

### ISSUE THREAD

**Issue by hchenxa** [kubernetes/kubernetes#51013]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

When I trying on kubernetes master HA, when the master node failured, the null point exceptions throws on candidate hosts and lead the controller manager crashed.
 
```
I0821 10:23:53.900036       5 controllermanager.go:460] Started "endpoint"
I0821 10:23:53.900047       5 controllermanager.go:450] Starting "serviceaccount"
I0821 10:23:53.900167       5 endpoints_controller.go:154] Starting endpoint controller
I0821 10:23:53.900184       5 controller_utils.go:1021] Waiting for caches to sync for endpoint controller
W0821 10:23:53.916153       5 client_builder.go:226] Token for service-account-controller/kube-system did not authenticate correctly
W0821 10:23:53.916172       5 client_builder.go:169] secret service-account-controller-token-c6rqp contained an invalid API token for service-account-controller/kube-system
I0821 10:23:53.929196       5 client_builder.go:233] Verified credential for service-account-controller/kube-system
I0821 10:23:53.929559       5 controllermanager.go:460] Started "serviceaccount"
I0821 10:23:53.929571       5 controllermanager.go:450] Starting "daemonset"
I0821 10:23:53.929683       5 serviceaccounts_controller.go:113] Starting service account controller
I0821 10:23:53.929706       5 controller_utils.go:1021] Waiting for caches to sync for service account controller
I0821 10:23:53.948499       5 client_builder.go:233] Verified credential for daemon-set-controller/kube-system
I0821 10:23:53.953902       5 daemon_controller.go:160] Adding daemon set calico-node-s390x
I0821 10:23:53.953996       5 controllermanager.go:460] Started "daemonset"
E0821 10:23:53.954001       5 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/root/hchen/GOPATH/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/root/hchen/GOPATH/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/root/hchen/GOPATH/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:514
/usr/local/go/src/runtime/panic.go:489
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:290
/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go:161
/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:195
<autogenerated>:57
/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:545
/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:381
/root/hchen/GOPATH/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/usr/local/go/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x31c705a]

goroutine 1244 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/root/hchen/GOPATH/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x4050880, 0x934c510)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
k8s.io/kubernetes/pkg/controller/daemon.NewDaemonSetsController.func1(0x4809980, 0xc422100000)
	/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller.go:161 +0xea
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(0xc422c963a0, 0xc422c963b0, 0xc422c963c0, 0x4809980, 0xc422100000)
	/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:195 +0x49
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd(0xc422c98a40, 0x4809980, 0xc422100000)
	<autogenerated>:57 +0x73
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc422cde230)
	/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:545 +0x287
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).(k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.run)-fm()
	/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:381 +0x2a
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc420415788, 0xc422c963f0)
	/root/hchen/GOPATH/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/root/hchen/GOPATH/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:72 +0x62
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by janetkuo** [comment]
I saw this as well. I've seen this panic in ds, deploy, and disruption controller. Logs also pointed me to `k8s.io/client-go/tools/cache/controller.go` and `k8s.io/client-go/tools/cache/shared_informer.go`

/sig api-machinery

**Comment by deads2k** [comment]
Is this on head or on a prior level?

**Comment by ncdc** [comment]
Looks like head. I'm going to take a stab at guessing what happened:

1. controller-manager was starting all the individual controllers
1. each controller's init function starts it in a goroutine
1. after all the controller goroutines have started, we start the shared informer factory
1. the shared informer event handler delivered a DaemonSet event [here](https://github.com/kubernetes/kubernetes/blob/73a6ee1dcc20ece22b1bbcdd00d3147984ba70bb/pkg/controller/daemon/daemon_controller.go#L161) ... BUT
1. because of goroutine scheduling, `NewDaemonSetsController` hadn't actually finished executing, resulting in `dsc.enqueueDaemonSet` still being nil when the event was delivered
1. `dsc.enqueueDaemonSet` is actually set [here](https://github.com/kubernetes/kubernetes/blob/73a6ee1dcc20ece22b1bbcdd00d3147984ba70bb/pkg/controller/daemon/daemon_controller.go#L201)

Maybe the solution is to move setting the function pointers up, prior to adding the event handlers?

**Comment by ncdc** [comment]
Also if it wasn't clear in my comment above, I don't think this has anything to do with failover/leader election. It may be possible that failover makes this more likely to happen, but I believe that's correlation, not causation.

**Comment by ncdc** [comment]
@janetkuo do you have stack traces from the other controllers you mentioned? I looked e.g. at disrutpion and it doesn't appear to have this exact same code structure/order. I don't know that we can lump all of them together as the same underlying root cause at this point.

**Comment by timothysc** [comment]
Does failover exacerbate this behavior or do we see this 1/(X) times on KCM startup?

**Comment by ncdc** [comment]
I don't believe my theory above is correct, given that it's the _last_ part of the function chain that is run in a separate goroutine; i.e., `NewDaemonSetsController()` runs in the calling goroutine, and its `Run()` method is in a different one.

Looking at the stack trace above more carefully, the event was delivered via a goroutine created at
```
	/root/hchen/GOPATH/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:381 +0x2a
```
which is from `func (p *sharedProcessor) addAndStartListener(listener *processorListener)`, and that is only ever called when adding an event handler to an **already running** shared informer. The receiver of the new event handler is immediately delivered everything in the shared informer's cache, which explains why the DaemonSetController starts getting events before the `enqueueDaemonSet` function pointer is set.

What I haven't yet figured out is why the DS shared informer has already been started. The only other controller that appears to use it is the node controller, but I thought that started at the same time as all the other "normal" controllers; i.e., all the controllers are started, then the shared informers. I will note that we start the shared informers twice: once for the service account controller (just for service accounts and secrets), and again for the remainder, after all the controllers have been initialized and are running. Still digging...

**Comment by ncdc** [comment]
Oh it's also started by the GC controller

**Comment by ncdc** [comment]
My current theory is this is from the GarbageCollector controller, as it is coded to start a shared informer for resource X as soon as it sees X from discovery. If the GC controller starts up first, and thus starts up the DaemonSet shared informer, by the time the DS controller is constructed, there may be DSes in that shared informer's cache, which get delivered "immediately" as soon as the DS controller adds its event handler.

**Comment by ironcladlou** [comment]
Spoke with @ncdc about this on slack, and my current proposal is to make the SharedInformerFactory auto-start newly requested informers if Start has already been called. This gives the factory owner more control over the lifecycle of the informers shared by controllers, removing the need for the GC (or other) controllers to try and manage the factory lifecycle.

**Comment by ncdc** [comment]
@ironcladlou that does still mean that if you add an event handler to an unstarted shared informer when the factory has already been started, you must be ready to handle add/update/delete events as soon as the AddEventHandler call finishes, just to be clear.

**Comment by ironcladlou** [comment]
@ncdc 
>that does still mean that if you add an event handler to an unstarted shared informer when the factory has already been started, you must be ready to handle add/update/delete events as soon as the AddEventHandler call finishes, just to be clear.

Given SharedInformer doesn't expose any way to safely determine whether the informer is "started",  and ResourceEventHandler doesn't expose any way to mark a handler "ready", I'm not sure consumers have any choice but to assume their event handlers could be called at any point after adding. Does that seem true?

**Comment by ncdc** [comment]
Yes. I am going to update the godoc to make sure that's clear.

**Comment by janetkuo** [comment]
I just hit this again on HEAD (https://github.com/kubernetes/kubernetes/commit/05e7f6d0737be8161469c9f78660e25122ed838b). I also included https://github.com/kubernetes/kubernetes/pull/51054 so that local cluster works, but I don't think that PR is related to this issue. 

It's not always reproducible. What I did was:

1. Start a local cluster (hack/local-up-cluster.sh)
1. Create a controller immediately after the cluster is up and running, e.g. `kubectl run nginx --image nginx`
1. If the controller manager crashed you'll see this:
  ```console
  $ kubectl get cs 
  NAME                 STATUS      MESSAGE                                                                                        ERROR
  controller-manager   Unhealthy   Get http://127.0.0.1:10252/healthz: dial tcp 127.0.0.1:10252: getsockopt: connection refused   
  ```

Here's the log I saw this time:

```
I0824 13:52:07.698825  116520 node_controller.go:214] Sending events to api server.
I0824 13:52:07.698990  116520 taint_controller.go:158] Sending events to api server.
I0824 13:52:07.699073  116520 controllermanager.go:460] Started "node"
I0824 13:52:07.699089  116520 controllermanager.go:450] Starting "route"
W0824 13:52:07.699097  116520 core.go:126] Unsuccessful parsing of cluster CIDR : invalid CIDR address: 
I0824 13:52:07.699110  116520 core.go:129] Will not configure cloud provider routes for allocate-node-cidrs: false, configure-cloud-routes: true.
W0824 13:52:07.699120  116520 controllermanager.go:457] Skipping "route"
I0824 13:52:07.699132  116520 controllermanager.go:450] Starting "persistentvolume-binder"
I0824 13:52:07.699178  116520 node_controller.go:471] Starting node controller
E0824 13:52:07.699190  116520 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/usr/local/google/home/xxx/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/usr/local/google/home/xxx/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/usr/local/google/home/xxx/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:514
/usr/local/go/src/runtime/panic.go:489
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:290
/usr/local/google/home/xxx/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/node/scheduler/taint_controller.go:287
/usr/local/google/home/xxx/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/node/node_controller.go:375
/usr/local/google/home/xxx/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/node/util/controller_utils.go:297
/usr/local/google/home/xxx/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:195
<autogenerated>:57
/usr/local/google/home/xxx/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:545
/usr/local/google/home/xxx/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:381
/usr/local/google/home/xxx/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/usr/local/go/src/runtime/asm_amd64.s:2197
I0824 13:52:07.699225  116520 controller_utils.go:1021] Waiting for caches to sync for node controller
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x315965d]

goroutine 1333 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/usr/local/google/home/xxx/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x407e660, 0x93bd510)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
k8s.io/kubernetes/pkg/controller/node/scheduler.(*NoExecuteTaintManager).NodeUpdated(0x0, 0x0, 0xc4228ac000)
	/usr/local/google/home/xxx/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/node/scheduler/taint_controller.go:287 +0x1ad
k8s.io/kubernetes/pkg/controller/node.NewNodeController.func8(0xc4228ac000, 0x483a840, 0xc420dec000)
	/usr/local/google/home/xxx/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/node/node_controller.go:375 +0x44
k8s.io/kubernetes/pkg/controller/node/util.CreateAddNodeHandler.func1(0x483a840, 0xc420dec000)
	/usr/local/google/home/xxx/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/node/util/controller_utils.go:297 +0x89
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(0xc4227ffd10, 0xc4227ffd30, 0xc4227ffd50, 0x483a840, 0xc420dec000)
	/usr/local/google/home/xxx/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:195 +0x49
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd(0xc422886580, 0x483a840, 0xc420dec000)
	<autogenerated>:57 +0x73
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc422870960)
	/usr/local/google/home/xxx/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:545 +0x287
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).(k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.run)-fm()
	/usr/local/google/home/xxx/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:381 +0x2a
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc420243868, 0xc4227ffd60)
	/usr/local/google/home/xxx/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/usr/local/google/home/xxx/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:72 +0x62
```

**Comment by ncdc** [comment]
That looks like the same underlying root cause - the node controller is adding event handlers that operate on `nc.taintManager` **before** setting `nc.taintManager`. I will try to get a fix out for this tomorrow.

**Comment by janetkuo** [comment]
Another example: #51286

**Comment by yastij** [comment]
Do we know if it's a regression or an undetected NPE ?

**Comment by ironcladlou** [comment]
Probably introduced with https://github.com/kubernetes/kubernetes/pull/47665

**Comment by derekwaynecarr** [comment]
@ncdc @ironcladlou -- this is happening all the time for me in normal development process.

**Comment by ncdc** [comment]
Will try to submit a fix tonight.

**Comment by ncdc** [comment]
I opened https://github.com/kubernetes/kubernetes/pull/51492 to try to fix this

**Comment by ncdc** [comment]
Going to use #51633 instead, since it's a smaller change.

**Comment by jeremyd** [comment]
I hit this same issue in v1.7.6  Trace below.  Is there any way to recover from this?  Currently the cluster is unable to startup a controller-manager although the api is still responding.

```
I0920 01:10:37.699697       1 controller_utils.go:1001] Caches are synced for GC controller
I0920 01:10:37.700511       1 controller_utils.go:1001] Caches are synced for RC controller
I0920 01:10:37.700690       1 controller_utils.go:1001] Caches are synced for endpoint controller
I0920 01:10:37.701144       1 controller_utils.go:1001] Caches are synced for certificate controller
I0920 01:10:37.716689       1 controller_utils.go:1001] Caches are synced for resource quota controller
I0920 01:10:37.743727       1 controller_utils.go:1001] Caches are synced for attach detach controller
I0920 01:10:38.026325       1 controller_utils.go:1001] Caches are synced for deployment controller
I0920 01:10:38.131808       1 controller_utils.go:1001] Caches are synced for garbage collector controller
I0920 01:10:38.131901       1 garbagecollector.go:132] Garbage collector: all resource monitors have synced. Proceeding to collect garbage
I0920 01:10:38.132769       1 controller_utils.go:1001] Caches are synced for replica set controller
I0920 01:10:38.141202       1 controller_utils.go:1001] Caches are synced for disruption controller
I0920 01:10:38.141249       1 disruption.go:305] Sending events to api server.
I0920 01:10:38.560887       1 event.go:218] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"heapster-1152096127", UID:"079405ef-9da0-11e7-be81-12ee649370f8", APIVersion:"extensions", ResourceVersion:"2341744", FieldPath:""}): type: 'Normal' reason: 'SuccessfulDelete' Deleted pod: heapster-1152096127-61wrv
E0920 01:10:39.782309       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:514
/usr/local/go/src/runtime/panic.go:489
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:290
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/progress.go:100
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/recreate.go:49
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:686
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:135
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:471
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:460
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:160
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/usr/local/go/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x355229c]

goroutine 1075 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x4304920, 0x8f474a0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).syncRolloutStatus(0xc420add180, 0xc429164380, 0x2, 0x2, 0x0, 0xc42196d800, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/progress.go:100 +0x9cc
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).rolloutRecreate(0xc420add180, 0xc42196d800, 0xc42806e0a0, 0x1, 0x1, 0xc4291ca060, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/recreate.go:49 +0x485
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).syncDeployment(0xc420add180, 0xc422090680, 0x32, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:686 +0x990
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).(k8s.io/kubernetes/pkg/controller/deployment.syncDeployment)-fm(0xc422090680, 0x32, 0xc42119f060, 0x4081260)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:135 +0x3e
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).processNextWorkItem(0xc420add180, 0x50d800)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:471 +0xd9
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).worker(0xc420add180)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:460 +0x2b
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).(k8s.io/kubernetes/pkg/controller/deployment.worker)-fm()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:160 +0x2a
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4267c2420)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97 +0x5e
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4267c2420, 0x3b9aca00, 0x0, 0x2110ff01, 0xc4200837a0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98 +0xbd
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4267c2420, 0x3b9aca00, 0xc4200837a0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52 +0x4d
created by k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).Run
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:160 +0x22d
```

**Comment by ncdc** [comment]
@jeremyd I would recommend opening a new issue. Your root cause appears to be different (different stack trace).

**Comment by jeremyd** [comment]
@ncdc, ok thanks, yes it does look slightly different than https://github.com/kubernetes/kubernetes/issues/51286 which was linked here but originally it looked similar enough that I didn't want to dupe.  Anyhow, here's the new bug report I created: https://github.com/kubernetes/kubernetes/issues/53613  Thanks!
