### ISSUE TITLE
Deployment controller panic

### ISSUE THREAD

**Issue by nicksardo** [kubernetes/kubernetes#51286]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Deployment controller hit a panic near kube-controller-manager start.

```log
I0824 18:41:27.586494       5 disruption.go:336] addPod called on pod "heapster-v1.4.1-167081345-zt4cb"
I0824 18:41:27.586506       5 disruption.go:411] No PodDisruptionBudgets found for pod heapster-v1.4.1-167081345-zt4cb, PodDisruptionBudget controller will avoid syncing.
I0824 18:41:27.586539       5 disruption.go:339] No matching pdb for pod "heapster-v1.4.1-167081345-zt4cb"
I0824 18:41:27.586740       5 client_builder.go:233] Verified credential for deployment-controller/kube-system
I0824 18:41:27.589173       5 deployment_controller.go:167] Adding deployment kubernetes-dashboard
E0824 18:41:27.589263       5 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/nicksardo/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/nicksardo/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/nicksardo/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/nicksardo/.gvm/gos/go1.8.3/src/runtime/asm_amd64.s:514
/home/nicksardo/.gvm/gos/go1.8.3/src/runtime/panic.go:489
/home/nicksardo/.gvm/gos/go1.8.3/src/runtime/panic.go:63
/home/nicksardo/.gvm/gos/go1.8.3/src/runtime/signal_unix.go:290
/home/nicksardo/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:168
/home/nicksardo/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:120
/home/nicksardo/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:195
<autogenerated>:57
/home/nicksardo/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:545
/home/nicksardo/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:381
/home/nicksardo/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/home/nicksardo/.gvm/gos/go1.8.3/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1cae661]

goroutine 1018 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/nicksardo/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x2e7d4a0, 0x4df6490)
	/home/nicksardo/.gvm/gos/go1.8.3/src/runtime/panic.go:489 +0x2cf
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).addDeployment(0xc421adf360, 0x344f7e0, 0xc421a1aba0)
	/home/nicksardo/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:168 +0xe1
k8s.io/kubernetes/pkg/controller/deployment.(*DeploymentController).(k8s.io/kubernetes/pkg/controller/deployment.addDeployment)-fm(0x344f7e0, 0xc421a1aba0)
	/home/nicksardo/go/src/k8s.io/kubernetes/pkg/controller/deployment/deployment_controller.go:120 +0x3e
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(0xc421c18710, 0xc421c18720, 0xc421c18730, 0x344f7e0, 0xc421a1aba0)
	/home/nicksardo/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:195 +0x49
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd(0xc421c17da0, 0x344f7e0, 0xc421a1aba0)
	<autogenerated>:57 +0x73
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc421c09270)
	/home/nicksardo/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:545 +0x287
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).(k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.run)-fm()
	/home/nicksardo/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:381 +0x2a
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc4203f3fd8, 0xc421c18760)
	/home/nicksardo/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/nicksardo/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:72 +0x62

```

**Environment**:
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.3.100+c86686f6df9aa9", GitCommit:"c86686f6df9aa982a1f2c05b91cb35a2ea016fe4", GitTreeState:"clean", BuildDate:"2017-08-24T16:59:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
This was on a local branch based on `1957e4a2ced19d0beb85da9c232b8eb7ce2e771b`

**Comment by yastij** [comment]
Related to #51013 I think

**Comment by janetkuo** [comment]
Yes, this is #51013
