### ISSUE TITLE
pull-kubernetes-federation-e2e-gce is failing

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/kubernetes#51478]
Ref: https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-federation-e2e-gce?

PR job seems started failing since 11:39 AM today.

Sample error message from https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/50099/pull-kubernetes-federation-e2e-gce/23847/:
```
W0828 22:39:08.049] 2017/08/28 22:39:08 main.go:233: Something went wrong: error starting federation: error during ./federation/cluster/federation-up.sh: exit status 124
W0828 22:39:08.886] Run: ('sudo', 'chmod', '-R', 'o+r', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/go/src/k8s.io/kubernetes/_artifacts')
W0828 22:39:08.896] Traceback (most recent call last):
W0828 22:39:08.897]   File "/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 682, in <module>
W0828 22:39:08.897]     main(parse_args())
W0828 22:39:08.897]   File "/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 545, in main
W0828 22:39:08.897]     mode.start(runner_args)
W0828 22:39:08.897]   File "/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 346, in start
W0828 22:39:08.897]     check(*cmd)
W0828 22:39:08.897]   File "/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 47, in check
W0828 22:39:08.898]     subprocess.check_call(cmd)
W0828 22:39:08.898]   File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
W0828 22:39:08.898]     raise CalledProcessError(retcode, cmd)
W0828 22:39:08.899] subprocess.CalledProcessError: Command '('docker', 'run', '--rm', '--name=pull-kubernetes-federation-e2e-gce-23847', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/go/src/k8s.io/kubernetes/_artifacts:/workspace/_artifacts', '-v', '/etc/localtime:/etc/localtime:ro', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-e', 'HOME=/workspace', '-e', 'WORKSPACE=/workspace', '--env-file', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/./test-infra/jenkins/../scenarios/../jobs/platform/gce.env', '--env-file', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/./test-infra/jenkins/../scenarios/../jobs/env/pull-kubernetes-e2e.env', '--env-file', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/./test-infra/jenkins/../scenarios/../jobs/env/pull-kubernetes-federation-e2e-gce.env', '-e', 'KUBETEST_MANUAL_DUMP=y', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce@tmp/secretFiles/708748ad-ebba-4850-90a1-26303be2ad02/kubernetes-jenkins-pull-c67f9519f993.json:/service-account.json:ro', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/go/src/k8s.io/kubernetes:/go/src/k8s.io/kubernetes', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/go/src/k8s.io/release:/go/src/k8s.io/release', '-v', '/home/jenkins/.ssh/google_compute_engine:/workspace/.ssh/google_compute_engine:ro', '-v', '/home/jenkins/.ssh/google_compute_engine.pub:/workspace/.ssh/google_compute_engine.pub:ro', '-e', 'JENKINS_GCE_SSH_PRIVATE_KEY_FILE=/workspace/.ssh/google_compute_engine', '-e', 'JENKINS_GCE_SSH_PUBLIC_KEY_FILE=/workspace/.ssh/google_compute_engine.pub', '-e', 'JENKINS_HOME=/var/lib/jenkins', '-e', 'PULL_BASE_REF=master', '-e', 'BUILD_CAUSE=MANUALTRIGGER', '-e', 'HUDSON_URL=http://goto.google.com/prkubekins/', '-e', 'BUILD_URL=http://goto.google.com/prkubekins/job/pull-kubernetes-federation-e2e-gce/23847/', '-e', 'BOOTSTRAP_MIGRATION=yes', '-e', 'CLOUDSDK_CONFIG=/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce/go/src/k8s.io/kubernetes/.config/gcloud', '-e', 'BUILD_TAG=jenkins-pull-kubernetes-federation-e2e-gce-23847', '-e', 'HUDSON_SERVER_COOKIE=32617aabcc4952a0', '-e', 'JENKINS_URL=http://goto.google.com/prkubekins/', '-e', 'LOGNAME=jenkins', '-e', 'USER=jenkins', '-e', 'NODE_LABELS=agent-pr-06 pull', '-e', 'JOB_NAME=pull-kubernetes-federation-e2e-gce', '-e', 'LANG=en_US.UTF-8', '-e', 'RUN_DISPLAY_URL=http://goto.google.com/prkubekins/job/pull-kubernetes-federation-e2e-gce/23847/display/redirect', '-e', 'SHELL=/bin/bash', '-e', 'buildId=4dca5e06-8c39-11e7-9428-0a580a6c115c', '-e', 'HUDSON_HOME=/var/lib/jenkins', '-e', 'JOB_URL=http://goto.google.com/prkubekins/job/pull-kubernetes-federation-e2e-gce/', '-e', 'ROOT_BUILD_CAUSE_MANUALTRIGGER=true', '-e', 'BUILD_CAUSE_MANUALTRIGGER=true', '-e', 'GCS_ARTIFACTS_DIR=gs://kubernetes-jenkins/pr-logs/pull/50099/pull-kubernetes-federation-e2e-gce/23847/artifacts', '-e', 'JENKINS_AWS_CREDENTIALS_FILE=/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce@tmp/secretFiles/ac33e675-5609-4f8c-a20c-3837c8dfe4a6/KubernetesPresubmitTests.txt', '-e', 'ROOT_BUILD_CAUSE=MANUALTRIGGER', '-e', 'SSH_CLIENT=10.240.0.2 40997 22', '-e', 'BUILD_ID=23847', '-e', 'BUILD_NUMBER=23847', '-e', 'XDG_RUNTIME_DIR=/run/user/1000', '-e', 'HUDSON_COOKIE=96079c52-e391-4cf3-b735-e891e8d48b4a', '-e', 'JENKINS_AWS_SSH_PRIVATE_KEY_FILE=/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce@tmp/secretFiles/c25dc1d7-4fb4-4673-9925-6aa56e422a19/id_rsa.jenkins', '-e', 'JOB_BASE_NAME=pull-kubernetes-federation-e2e-gce', '-e', 'RUN_CHANGES_DISPLAY_URL=http://goto.google.com/prkubekins/job/pull-kubernetes-federation-e2e-gce/23847/display/redirect?page=changes', '-e', 'XDG_SESSION_ID=484', '-e', 'JENKINS_GCE_SSH_PUBLIC_KEY_FILE=/home/jenkins/.ssh/google_compute_engine.pub', '-e', '_=./test-infra/jenkins/bootstrap.py', '-e', 'OLDPWD=/home/jenkins', '-e', 'JOB_DISPLAY_URL=http://goto.google.com/prkubekins/job/pull-kubernetes-federation-e2e-gce/display/redirect', '-e', 'JENKINS_AWS_SSH_PUBLIC_KEY_FILE=/var/lib/jenkins/workspace/pull-kubernetes-federation-e2e-gce@tmp/secretFiles/27c18c25-c90d-43bf-8447-d0de3f2083fc/id_rsa.jenkins.pub', '-e', 'EXECUTOR_NUMBER=0', '-e', 'NODE_NAME=agent-pr-06', '-e', 'PULL_NUMBER=50099', '-e', 'SHLVL=2', '-e', 'JENKINS_SERVER_COOKIE=32617aabcc4952a0', '-e', 'BUILD_DISPLAY_NAME=#23847', '-e', 'PULL_REFS=master:a64eeb47f6ed4aa2587113793a76878b876809f9,50099:55339f30acd9fbad60d651e419ba50b08fa7245a', '-e', 'JENKINS_GCE_SSH_PRIVATE_KEY_FILE=/home/jenkins/.ssh/google_compute_engine', '-e', 'MAIL=/var/mail/jenkins', '-e', 'SSH_CONNECTION=10.240.0.2 40997 10.240.0.61 22', '-e', 'CLOUDSDK_COMPONENT_MANAGER_DISABLE_UPDATE_CHECK=true', '-e', 'CLOUDSDK_EXPERIMENTAL_FAST_COMPONENT_UPDATE=false', '-e', 'KUBE_AWS_INSTANCE_PREFIX=e2e-23847', '-e', 'INSTANCE_PREFIX=e2e-23847', '-e', 'KUBE_GCE_INSTANCE_PREFIX=e2e-23847', 'gcr.io/k8s-testimages/kubekins-e2e:v20170728-faff708c', '-v', '--dump=/workspace/_artifacts', '--gcp-service-account=/service-account.json', '--build', '--up', '--down', '--test', '--cluster=e2e-23847', '--gcp-network=e2e-23847', '--deployment=none', '--extract=local', '--federation', '--gcp-project=k8s-jkns-pr-bldr-e2e-gce-fdrtn', '--gcp-zone=us-central1-f', '--multiple-federations', '--provider=gce', '--save=gs://kubernetes-jenkins/federation/ci-kubernetes-pull-gce-federation-deploy', '--stage=gs://kubernetes-release-pull/ci/pull-kubernetes-federation-e2e-gce', '--test_args=--ginkgo.focus=\\[Feature:Federation\\] --ginkgo.skip=\\[Slow\\]|\\[Serial\\]|\\[Disruptive\\]|\\[Flaky\\]|\\[NoCluster\\] --minStartupPods=8', '--timeout=90m')' returned non-zero exit status 1
I0828 22:39:08.905] Starting pull-kubernetes-federation-e2e-gce-23847...
E0828 22:39:08.906] Command failed
I0828 22:39:08.906] process 26112 exited with code 1 after 41.3m
E0828 22:39:08.906] FAIL: pull-kubernetes-federation-e2e-gce
```

/sig federation
/priority failing-test
@kubernetes/kubernetes-build-cops

**Comment by MrHohn** [comment]
cc @kubernetes/sig-federation-bugs

**Comment by nikhiljindal** [comment]
cc @madhusudancs the oncall this week.

Cant get any idea why its failing from the logs.

**Comment by nikhiljindal** [comment]
cc @kubernetes/test-infra-maintainers in case something in test infra changed that could be causing this.

**Comment by krzyzacy** [comment]
https://k8s-testgrid.appspot.com/kubernetes-presubmits#pull-kubernetes-federation-e2e-gce

there's no infra change between the last successful and first failed run - I'll check from main repo

**Comment by krzyzacy** [comment]
It looks like the federation control plane up is timed out?

**Comment by MrHohn** [comment]
> It looks like the federation control plane up is timed out?

And federation control plane's logs is empty...

Ref: http://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/50099/pull-kubernetes-federation-e2e-gce/23847/artifacts/federation/

**Comment by madhusudancs** [comment]
Sorry, looking at it now. I am technically away today :P

**Comment by madhusudancs** [comment]
Tests should be working now. We ran out of PD quota.

**Comment by yujuhong** [comment]
> Tests should be working now. We ran out of PD quota.

Do you know why garbage collection didn't kick in?

**Comment by MrHohn** [comment]
Checked the federation CI project, found plenty of not-in-use PDs (each has 10 GB). Is this PR jobs consistently leaking PR resources? Might be good to root cause it, or we will hit quota limit and block the queue again...

**Comment by krzyzacy** [comment]
federation job is opt-out of the janitor process - maybe it need to somehow have it's own clean up process?

**Comment by yujuhong** [comment]
> federation job is opt-out of the janitor process - maybe it need to somehow have it's own clean up process?

+1 
I don't think we can ever be sure that the tests won't leak any resources. Since this is a required presubmit job, having a cleanup process sounds reasonable.

**Comment by madhusudancs** [comment]
> Checked the federation CI project, found plenty of not-in-use PDs (each has 10 GB). Is this PR jobs consistently leaking PD resources? Might be good to root cause it, or we will hit quota limit and block the queue again...

@MrHohn it's a known issue. It's being tracked here - https://github.com/kubernetes/kubernetes/issues/50543.

> federation job is opt-out of the janitor process - maybe it need to somehow have it's own clean up process?

@krzyzacy yes. It needs to be federation specific, that's why we opted out of the janitor. Janitor is too big a hammer for federation tests.

**Comment by MrHohn** [comment]
@madhusudancs Thanks for the link. Closing this issue as pull-kubernetes-federation-e2e-gce is no longer failing.

**Comment by madhusudancs** [comment]
@MrHohn makes sense, thanks!
