### ISSUE TITLE
[SQ-blocking] Kubemark presubmit failing to create pod in kubemark cluster

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#51799]
`pull-kubernetes-kubemark-e2e-gce` is failing almost continuously - https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-kubemark-e2e-gce
with the following error:

```
Expected error:
    <*errors.errorString | 0xc420cc4300>: {
        s: "Only 0 pods started out of 1",
    }
    Only 0 pods started out of 1
not to have occurred
```

cc @kubernetes/sig-scalability-misc @kubernetes/test-infra-maintainers @jdumars @luxas

**Comment by shyamjvs** [comment]
Even the CI tests are failing continuously - https://k8s-testgrid.appspot.com/sig-scalability#kubemark-small
I'm looking at the [diff](https://github.com/kubernetes/kubernetes/compare/61bc3aa56...c65ab61b3)

**Comment by shyamjvs** [comment]
There are 5 commits in the diff and 3 of them seem unrelated. One of these two PRs (touching kubelet) likely introduced the regression:
https://github.com/kubernetes/kubernetes/pull/51357 (cc @ConnorDoyle)
https://github.com/kubernetes/kubernetes/pull/51372 (cc @mtaufen)

**Comment by shyamjvs** [comment]
I suspect the latter is the reason as it touches a bunch of kubelet configs, which could potentially break hollow-kubelet in kubemark.
I'll create a revert PR and check if the presubmit passes on it - though it's surprising how it passed the original one (iirc this happened once in the past already).

**Comment by shyamjvs** [comment]
cc @k8s-oncall

**Comment by shyamjvs** [comment]
Ok.. So I just checked from a live node on our currently running kubemark-500 CI test. Seems like it definitely is a problem with kubelet.
I'm attaching the logs for one of the hollow-kubelet I managed to get.

[kubelet-hollow-node-rq565.txt](https://github.com/kubernetes/kubernetes/files/1270843/kubelet-hollow-node-rq565.txt)

**Comment by shyamjvs** [comment]
cc @kubernetes/sig-node-bugs

**Comment by yujuhong** [comment]
> I'm attaching the logs for one of the hollow-kubelet I managed to get.

Based on the log, #51357 seems to be the culprit. 
/cc @ConnorDoyle @derekwaynecarr

**Comment by mtaufen** [comment]
```
grep "Observed a panic" kubelet-hollow-node-rq565.txt                                                                                                                                     9:20  mtaufen@mtaufen0
E0901 15:52:00.130344      27 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
E0901 15:53:45.726544      92 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
E0901 15:55:06.751086     152 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
E0901 15:56:55.543805     226 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
E0901 15:58:08.688172     290 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
E0901 16:01:17.503001     362 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
E0901 16:04:50.052179     423 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
```
```
0 goroutine 221 [running]:                                                        
341 k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
342 » /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
343 panic(0x2f07f00, 0x50efd90)                                                     
344 » /usr/local/go/src/runtime/panic.go:489 +0x2cf                                 
345 k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).startContainer(0xc420c2a4b0, 0xc420144840, 0x10, 0xc4201d29c0, 0xc420f6b040, 0xc420d9fc00, 0xc4209c8930, 0x5234b58, 0x0, 0x0, ...)
346 » /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go:119 +0x36b
347 k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).SyncPod(0xc420c2a4b0, 0xc420d9fc00, 0x359fdc0, 0x7, 0xc420b0e380, 0x3, 0x4, 0x0, 0x0, 0x0, ...)
348 » /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_manager.go:689 +0xc09
349 k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncPod(0xc42014b500, 0x0, 0xc420d9fc00, 0x2, 0xc4209c8930, 0x0, 0xc420dc2720, 0xc420a744e0)
350 » /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1606 +0xdeb
351 k8s.io/kubernetes/pkg/kubelet.(*Kubelet).(k8s.io/kubernetes/pkg/kubelet.syncPod)-fm(0x0, 0xc420d9fc00, 0x2, 0xc4209c8930, 0x0, 0x0, 0xc4209c8930)
352 » /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:786 +0x51
353 k8s.io/kubernetes/pkg/kubelet.(*podWorkers).managePodLoop.func1(0xc42066ff08, 0xc420071490, 0xc420dc1ef0, 0x1, 0xc42066fec0)
354 » /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:173 +0x146
355 k8s.io/kubernetes/pkg/kubelet.(*podWorkers).managePodLoop(0xc420071490, 0xc42029fc20)
```

Agree with @yujuhong

**Comment by dchen1107** [comment]
I agreed with @yujuhong's assessment, but why pr was merged at the first place?

**Comment by shyamjvs** [comment]
> but why pr was merged at the first place?

I had the same question too https://github.com/kubernetes/kubernetes/issues/51799#issuecomment-326610751. Let me look into it :)

**Comment by derekwaynecarr** [comment]
I have no idea how that was not caught in the PR checks.
