### ISSUE TITLE
Duplicate Kubernetes watch caches, also some caches should be considered disabled by default

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#51825]
More discussion here https://github.com/openshift/origin/issues/16112

We've observed in most normal clusters the watch cache is only effective on some resources, and on dense clusters it is unnecessary on most resources.  For our density SLO we may actually prefer to waste less memory on the masters on the watch cache except for certain high `N x C x W` resources ([N]umber of resources, number of [C]lients, [W]rite rate) like pods, nodes, and endpoints.

Issue repurposed as well to cover duplicate watch caches found.

**Comment by smarterclayton** [comment]
@kubernetes/sig-scalability-bugs

**Comment by wojtek-t** [comment]
Yes, disabling it for many resources shouldn't have visibly impact on performance and can decrease memory usage.

But there are some resources, where disabling it will be a disaster. Those are resources, which are being watched by node components.
Clayton already mentioned: pods, node and endpoints.
I think services are also in this group.

But it definitely shouldn't affect things like RCs, RSs, Deployments, Jobs, ...

**Comment by smarterclayton** [comment]
I was trying to get a prometheus query that would show it.  We could do it per watch cache as well, but basically it's

1. N = number of total resources (i don't think we have a prometheus metric for today, but we could report watch cache stats if necessary)
2. C = concurrent watchers - should be able to calculate from apiserver_request_latency
3. W = write rate - can calculate from apiserver_request_count

I'm pretty sure we could do a heuristic that someone could test whether they need the watch cache on.  Oootb we should always turn on pods / endpoints / nodes.  We try to come up with some way to communicate to users when they should start watch caching (alert, log, or prometheus monitoring) or just simple rule of thumb.

In general, most of our controller loops can accurately calculate what their own tuning parameters should be (i.e. pod gc has access to total pods, so it should be able to calculate how much overhead is being kept on nodes and trade off retention vs overhead, so the tuning parameter could be percentageRetainedPods and minimumRetention).  For watch cache an enabled watch cache could probably report a fairly accurate count of whether it should be on or off.

**Comment by wojtek-t** [comment]
> I'm pretty sure we could do a heuristic that someone could test whether they need the watch cache on. Oootb we should always turn on pods / endpoints / nodes. We try to come up with some way to communicate to users when they should start watch caching (alert, log, or prometheus monitoring) or just simple rule of thumb

I'm not sure I agree. The fact whether it matters for you or not depends on what machines you're using. For large clusters we have big enough machines so we have quite a bit free space there. So we've never cared that much about memory.

> For watch cache an enabled watch cache could probably report a fairly accurate count of whether it should be on or off.

There is one information bit that watch cache is missing, which is how much memory it can actually use.
Even if there are two watchers of a given resource, in theory watch cache is helping, because instead of two decodes from etcd data there is exactly one.
The question is how frequently it actually happens and how much gain it does.

But in the world where you have as much memory as you can, it actually make sense to enable watch cache for everything. So there isn't a universal recommendation - it is based on the amount of memory that is available.

**Comment by smarterclayton** [comment]
> So we've never cared that much about memory.

Given that for large clusters it may be a 2x swing, and for small clusters there is very little value, i'm based towards opt in.  But I was saying heuristic on the lines of "you don't need to turn on unless you need to know"

**Comment by smarterclayton** [comment]
Hrm - disabling the watch cache globally does not have the same behavior as setting capacity zero for a given resource.  That concerns me.  Also, it looks like we found a bug when watch cache is totally disabled - requests pile up on the api server and then time out an hour later.  Debugging more.

**Comment by smarterclayton** [comment]
So re: disabling the watch cache, I'd like to propose adding `default-watch-cache-size` as an arg, let it be set to zero, which should have the behavior of taking the storage cacher completely out of the code path (so that we are calling storage directly).  That would preserve the watch cache flag behavior (turning off turns off watch cache completely)

**Comment by smarterclayton** [comment]
Hrm - looks like store is looking up watch cache size by using a global variable that is injected by a flag?  I think we may want to take this time to reorganize this and have kube-apiserver perform that calculation and pass defaults in via the storage getter.

**Comment by smarterclayton** [comment]
Looks like watch-cache-sizes doesn't work for apiservices, which means you can't selectively control that value.

**Comment by wojtek-t** [comment]
> Hrm - disabling the watch cache globally does not have the same behavior as setting capacity zero for a given resource. That concerns me. 

Yeah - that is unfortunate. We should fix that.

> So re: disabling the watch cache, I'd like to propose adding default-watch-cache-size as an arg, let it be set to zero,

So you're saying that it would be the same size for all resources? I'm not sure that's the best thing, because for some of resources we seem to need more than for others...

> Hrm - looks like store is looking up watch cache size by using a global variable that is injected by a flag? I think we may want to take this time to reorganize this and have kube-apiserver perform that calculation and pass defaults in via the storage getter.

+1

> Looks like watch-cache-sizes doesn't work for apiservices, which means you can't selectively control that value.

I don't undestand this - can you please clarify?

**Comment by smarterclayton** [comment]
> So you're saying that it would be the same size for all resources?

We already have a default represented on the etcd struct, it's just not a flag.  Would propose making it a flag.  I do think it's likely that in etcd3 we are more likely to be able to continue watches from etcd3 that are out of the cache window window.

> Looks like watch-cache-sizes doesn't work for apiservices

Someone added a setting (based on RAM) but then didn't wire it up to where it is used, so it's a no-op.  I think the previous comment around "we can reorganize this so it's done in the same place" will make it less likely someone accidentally does that in the future.

**Comment by smarterclayton** [comment]
Cleaning this up, will open a PR

**Comment by xiang90** [comment]
> I do think it's likely that in etcd3 we are more likely to be able to continue watches from etcd3 that are out of the cache window window.

If we start supporting failing back to etcd watch, we also need to support jumping back to api server watch cache.

etcd team has implemented all coalescing/caching logic in an etcd3 proxy library. we probably should try it out first if we decide to be smarter about watch.

**Comment by smarterclayton** [comment]
Hrm, I'm seeing multiple calls to storage cache wrappers:

```
Storage caching is enabled for *api.ConfigMap with capacity 100
Storage caching is enabled for *api.Endpoints with capacity 1000
Storage caching is enabled for *api.LimitRange with capacity 100
Storage caching is enabled for *api.Namespace with capacity 100
Storage caching is enabled for *api.Node with capacity 1000
Storage caching is enabled for *api.PersistentVolume with capacity 100
Storage caching is enabled for *api.PersistentVolumeClaim with capacity 100
Storage caching is enabled for *api.Pod with capacity 1700
Storage caching is enabled for *api.PodTemplate with capacity 100
Storage caching is enabled for *api.ReplicationController with capacity 170
Storage caching is enabled for *api.ReplicationController with capacity 170
Storage caching is enabled for *api.ResourceQuota with capacity 100
Storage caching is enabled for *api.Secret with capacity 100
Storage caching is enabled for *api.Service with capacity 1000
Storage caching is enabled for *api.ServiceAccount with capacity 100
Storage caching is enabled for *apiextensions.CustomResourceDefinition with capacity 100
Storage caching is enabled for *apiregistration.APIService with capacity 1000
Storage caching is enabled for *apps.ControllerRevision with capacity 100
Storage caching is enabled for *apps.ControllerRevision with capacity 100
Storage caching is enabled for *apps.StatefulSet with capacity 100
Storage caching is enabled for *apps.StatefulSet with capacity 100
Storage caching is enabled for *autoscaling.HorizontalPodAutoscaler with capacity 100
Storage caching is enabled for *batch.CronJob with capacity 100
Storage caching is enabled for *batch.Job with capacity 100
Storage caching is enabled for *certificates.CertificateSigningRequest with capacity 100
Storage caching is enabled for *extensions.DaemonSet with capacity 100
Storage caching is enabled for *extensions.DaemonSet with capacity 100
Storage caching is enabled for *extensions.Deployment with capacity 100
Storage caching is enabled for *extensions.Deployment with capacity 100
Storage caching is enabled for *extensions.Deployment with capacity 100
Storage caching is enabled for *extensions.Ingress with capacity 100
Storage caching is enabled for *extensions.PodSecurityPolicy with capacity 100
Storage caching is enabled for *extensions.ReplicaSet with capacity 100
Storage caching is enabled for *extensions.ReplicaSet with capacity 100
Storage caching is enabled for *networking.NetworkPolicy with capacity 100
Storage caching is enabled for *networking.NetworkPolicy with capacity 100
Storage caching is enabled for *policy.PodDisruptionBudget with capacity 100
Storage caching is enabled for *rbac.ClusterRole with capacity 100
Storage caching is enabled for *rbac.ClusterRole with capacity 100
Storage caching is enabled for *rbac.ClusterRoleBinding with capacity 100
Storage caching is enabled for *rbac.ClusterRoleBinding with capacity 100
Storage caching is enabled for *rbac.Role with capacity 100
Storage caching is enabled for *rbac.Role with capacity 100
Storage caching is enabled for *rbac.RoleBinding with capacity 100
Storage caching is enabled for *rbac.RoleBinding with capacity 100
Storage caching is enabled for *storage.StorageClass with capacity 100
Storage caching is enabled for *storage.StorageClass with capacity 100
```

Investigating

**Comment by smarterclayton** [comment]
Ok, we're definitely starting multiple watch caches.

**Comment by smarterclayton** [comment]
```
I0907 17:56:09.719809   82989 storage_factory.go:47] Storage caching is enabled for *extensions.Deployment with capacity 100
I0907 17:56:09.719824   82989 reflector.go:240] Listing and watching *extensions.DaemonSet from storage/cacher.go:/daemonsets
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x195, 0x7d)
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/debug/stack.go:16 +0x22
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage.NewCacherFromConfig(0x64, 0x8d88d20, 0xc42183b3b0, 0x8d7e160, 0x8f3f208, 0x8d513e0, 0xc42047d380, 0x4420d60, 0xc421a8e800, 0xc4217cdeb0, ...)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.go:200 +0x37
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry.StorageWithCacher.func1(0x8d513e0, 0xc42047d380, 0xc4216f8b00, 0x8d5bda0, 0xc421a8e800, 0xc4217cdeb0, 0xc, 0xc4219e30a0, 0x45b6d10, 0x45bc350, ...)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry/storage_factory.go:64 +0x3ea
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry.(*Store).CompleteWithOptions(0xc421a8c5a0, 0xc4211609f8, 0x8d689e0, 0xc4219e2e80)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:1342 +0x726
k8s.io/kubernetes/pkg/registry/extensions/deployment/storage.NewREST(0x8d51fe0, 0xc4207ea7e0, 0x4496dec, 0x7, 0x449c56e)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/extensions/deployment/storage/storage.go:76 +0x34a
k8s.io/kubernetes/pkg/registry/extensions/deployment/storage.NewStorage(0x8d51fe0, 0xc4207ea7e0, 0xa, 0x4496dec, 0x7, 0x449e751)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/extensions/deployment/storage/storage.go:48 +0x39
k8s.io/kubernetes/pkg/registry/extensions/rest.RESTStorageProvider.v1beta1Storage(0x8d7fa60, 0xc42000c148, 0x8d51fe0, 0xc4207ea7e0, 0x7)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/extensions/rest/storage_extensions.go:69 +0xd7e
k8s.io/kubernetes/pkg/registry/extensions/rest.RESTStorageProvider.NewRESTStorage(0x8d7fa60, 0xc42000c148, 0x8d51fe0, 0xc4207ea7e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/extensions/rest/storage_extensions.go:45 +0x1b1
k8s.io/kubernetes/pkg/registry/extensions/rest.(*RESTStorageProvider).NewRESTStorage(0x8f3f208, 0x8d7fa60, 0xc42000c148, 0x8d51fe0, 0xc4207ea7e0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        <autogenerated>:1 +0xb6
k8s.io/kubernetes/pkg/master.(*Master).InstallAPIs(0xc420c9fea0, 0x8d7fa60, 0xc42000c148, 0x8d51fe0, 0xc4207ea7e0, 0xc4211617d0, 0xe, 0xe)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/master/master.go:326 +0x15a
k8s.io/kubernetes/pkg/master.completedConfig.New(0xc4208c6b00, 0x8d81ec0, 0xc4207ebe60, 0x8d82580, 0xc420bc68b0, 0xc420c1e980)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/master/master.go:273 +0x69e
k8s.io/kubernetes/cmd/kube-apiserver/app.CreateKubeAPIServer(0xc4208c6b00, 0x8d81ec0, 0xc4207ebe60, 0x8d8c1e0, 0xc420b463f0, 0x0, 0x8d58120, 0xc420b4dac0)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:196 +0x51
k8s.io/kubernetes/cmd/kube-apiserver/app.CreateServerChain(0xc4207ec000, 0xc42035b8c0, 0xc420b37e48, 0x1, 0x1)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:146 +0x210
k8s.io/kubernetes/cmd/kube-apiserver/app.Run(0xc4207ec000, 0xc42035b8c0, 0x8f1dc20, 0x44f9a1e)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:116 +0xfa
main.main()
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/apiserver.go:52 +0xe6

I0907 17:56:09.733523   82989 storage_factory.go:47] Storage caching is enabled for *extensions.Deployment with capacity 100
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x24e, 0x7d)
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/debug/stack.go:16 +0x22
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage.NewCacherFromConfig(0x64, 0x8d88d20, 0xc42030c070, 0x8d7e160, 0x8f3f208, 0x8d513e0, 0xc42047d380, 0x4420d60, 0xc421501c00, 0xc420331210, ...)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.go:200 +0x37
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry.StorageWithCacher.func1(0x8d513e0, 0xc42047d380, 0xc420ba93f0, 0x8d5bda0, 0xc421501c00, 0xc420331210, 0xc, 0xc4218fae60, 0x45b6d10, 0x45bc350, ...)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry/storage_factory.go:64 +0x3ea
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry.(*Store).CompleteWithOptions(0xc42223e7e0, 0xc421b58c18, 0x8d689e0, 0xc4218fac40)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:1342 +0x726
k8s.io/kubernetes/pkg/registry/extensions/deployment/storage.NewREST(0x8d51fe0, 0xc4207ea7e0, 0x4496dec, 0x7, 0x44918fe)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/extensions/deployment/storage/storage.go:76 +0x34a
k8s.io/kubernetes/pkg/registry/extensions/deployment/storage.NewStorage(0x8d51fe0, 0xc4207ea7e0, 0x4, 0x4496dec, 0x7, 0x449e751)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/extensions/deployment/storage/storage.go:48 +0x39
k8s.io/kubernetes/pkg/registry/apps/rest.RESTStorageProvider.v1beta1Storage(0x8d7fa60, 0xc42000c148, 0x8d51fe0, 0xc4207ea7e0, 0x7)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/apps/rest/storage_apps.go:59 +0x654
k8s.io/kubernetes/pkg/registry/apps/rest.RESTStorageProvider.NewRESTStorage(0x8d7fa60, 0xc42000c148, 0x8d51fe0, 0xc4207ea7e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/apps/rest/storage_apps.go:43 +0x2eb
k8s.io/kubernetes/pkg/registry/apps/rest.(*RESTStorageProvider).NewRESTStorage(0x8f3f208, 0x8d7fa60, 0xc42000c148, 0x8d51fe0, 0xc4207ea7e0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        <autogenerated>:1 +0xb6
k8s.io/kubernetes/pkg/master.(*Master).InstallAPIs(0xc420c9fea0, 0x8d7fa60, 0xc42000c148, 0x8d51fe0, 0xc4207ea7e0, 0xc421b597d0, 0xe, 0xe)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/master/master.go:326 +0x15a
k8s.io/kubernetes/pkg/master.completedConfig.New(0xc4208c6b00, 0x8d81ec0, 0xc4207ebe60, 0x8d82580, 0xc420bc68b0, 0xc420c1e980)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/master/master.go:273 +0x69e
k8s.io/kubernetes/cmd/kube-apiserver/app.CreateKubeAPIServer(0xc4208c6b00, 0x8d81ec0, 0xc4207ebe60, 0x8d8c1e0, 0xc420b463f0, 0x0, 0x8d58120, 0xc420b4dac0)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:196 +0x51
k8s.io/kubernetes/cmd/kube-apiserver/app.CreateServerChain(0xc4207ec000, 0xc42035b8c0, 0xc420b37e48, 0x1, 0x1)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:146 +0x210
k8s.io/kubernetes/cmd/kube-apiserver/app.Run(0xc4207ec000, 0xc42035b8c0, 0x8f1dc20, 0x44f9a1e)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:116 +0xfa
main.main()
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/apiserver.go:52 +0xe6

I0907 17:56:09.735968   82989 storage_factory.go:47] Storage caching is enabled for *extensions.Deployment with capacit
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x244, 0x7d)
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/debug/stack.go:16 +0x22
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage.NewCacherFromConfig(0x64, 0x8d88d20, 0xc42030d880, 0x8d7e160, 0x8
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry.StorageWithCacher.func1(0x8d513e0, 0xc42047d380
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry.(*Store).CompleteWithOptions(0xc4224d0000, 0xc4
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io
k8s.io/kubernetes/pkg/registry/extensions/deployment/storage.NewREST(0x8d51fe0, 0xc4207ea7e0, 0x4496df3, 0x7, 0x44918fe
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/
k8s.io/kubernetes/pkg/registry/extensions/deployment/storage.NewStorage(0x8d51fe0, 0xc4207ea7e0, 0x4, 0x4496df3, 0x7, 0
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/
k8s.io/kubernetes/pkg/registry/apps/rest.RESTStorageProvider.v1beta2Storage(0x8d7fa60, 0xc42000c148, 0x8d51fe0, 0xc4207
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/
k8s.io/kubernetes/pkg/registry/apps/rest.RESTStorageProvider.NewRESTStorage(0x8d7fa60, 0xc42000c148, 0x8d51fe0, 0xc4207
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/
k8s.io/kubernetes/pkg/registry/apps/rest.(*RESTStorageProvider).NewRESTStorage(0x8f3f208, 0x8d7fa60, 0xc42000c148, 0x8d
        <autogenerated>:1 +0xb6
k8s.io/kubernetes/pkg/master.(*Master).InstallAPIs(0xc420c9fea0, 0x8d7fa60, 0xc42000c148, 0x8d51fe0, 0xc4207ea7e0, 0xc4
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/master/ma
k8s.io/kubernetes/pkg/master.completedConfig.New(0xc4208c6b00, 0x8d81ec0, 0xc4207ebe60, 0x8d82580, 0xc420bc68b0, 0xc420
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/master/ma
k8s.io/kubernetes/cmd/kube-apiserver/app.CreateKubeAPIServer(0xc4208c6b00, 0x8d81ec0, 0xc4207ebe60, 0x8d8c1e0, 0xc420b4
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apis
k8s.io/kubernetes/cmd/kube-apiserver/app.CreateServerChain(0xc4207ec000, 0xc42035b8c0, 0xc420b37e48, 0x1, 0x1)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apis
k8s.io/kubernetes/cmd/kube-apiserver/app.Run(0xc4207ec000, 0xc42035b8c0, 0x8f1dc20, 0x44f9a1e)
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apis
main.main()
        /Volumes/development/projects/origin/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apis
```

**Comment by smarterclayton** [comment]
@kubernetes/sig-api-machinery-bugs looks like we start the same storage from multiple places, which starts multiple watch caches.  I would have expected watch caches to be shared across resources.

We have 34 unique resources and 47 watch caches started.

**Comment by smarterclayton** [comment]
In 1.7 it looks like this was less bad - I only see 3 duplicate in openshift (deployments, replication controllers)

**Comment by wojtek-t** [comment]
> We have 34 unique resources and 47 watch caches started.

Hmm - that seems pretty bad. I'm pretty sure it wasn't the case few releases back.

**Comment by smarterclayton** [comment]
It's one per api group resource - deployments are now in three (extensions,
apps/v1beta1, and apps/v2beta2).  Some attributes of those storage are
different between storage (the resource info reported on errors).  The
watch cache should be shared.

On Fri, Sep 8, 2017 at 3:20 AM, Wojciech Tyczynski <notifications@github.com

**Comment by wojtek-t** [comment]
OK - got it. So that's probably not a regression then - I think we were never sharing watch case between api groups.

**Comment by smarterclayton** [comment]
No, although as a side effect of promoting APIs some memory hungry ones got
worse.  And I'm not convinced we didn't refactor something since 1.6 that
made it start happening.  I think it's important to fix (some clusters will
have lots of these) but not critical.

On Fri, Sep 8, 2017 at 2:55 PM, Wojciech Tyczynski <notifications@github.com

**Comment by wojtek-t** [comment]
Sure - I'm not saying we should fix that. I just think it's not a regression.

**Comment by spiffxp** [comment]
friendly v1.8 release ping, does this issue need to be in the v1.8 milestone? is this issue actively being worked?

**Comment by mbohlool** [comment]
@smarterclayton this is a daily ping from release team. Does this issue need to be in v1.8 milestone?

**Comment by lavalamp** [comment]
I am kicking this out of the milestone as it doesn't sound like a trivial fix and it also doesn't sound like a cluster-breaking problem.
