### ISSUE TITLE
All endpoint controller workers stuck at http call because of missing timeout setting

### ISSUE THREAD

**Issue by xinxiaogang** [kubernetes/kubernetes#53191]
**What happened**:
We use OpenStack as our cloud provider. We meet an issue that some controllers stuck because all workers routine stuck at http call to OpenStack services because of rabbitmq issues.

Stuck routine call stack:
```
goroutine 65108 [select, 145 minutes]:
net/http.(*persistConn).roundTrip(0xc42f6fb700, 0xc422c5acc0, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1840 +0x93b
net/http.(*Transport).RoundTrip(0xc4200f0000, 0xc42547f950, 0xc4200f0000, 0x0, 0xc400000000)
    /usr/local/go/src/net/http/transport.go:380 +0x4fa
net/http.send(0xc42547f950, 0x48e4b80, 0xc4200f0000, 0x0, 0x0, 0x0, 0x8, 0xc42b3cea20, 0x40fb78)
    /usr/local/go/src/net/http/client.go:256 +0x15f
net/http.(*Client).send(0xc4211c8428, 0xc42547f950, 0x0, 0x0, 0x0, 0xc42b3cea20, 0x0, 0x1)
    /usr/local/go/src/net/http/client.go:146 +0x102
net/http.(*Client).doFollowingRedirects(0xc4211c8428, 0xc42547f950, 0x33407f0, 0x4, 0x1, 0xc42ae6a3c8)
    /usr/local/go/src/net/http/client.go:528 +0x5e5
net/http.(*Client).Do(0xc4211c8428, 0xc42547f950, 0x1c, 0x3177153, 0x11)
    /usr/local/go/src/net/http/client.go:187 +0x11d
k8s.io/kubernetes/vendor/github.com/gophercloud/gophercloud.(*ProviderClient).Request(0xc4211c83f0, 0x3159d93, 0x4, 0xc428126c00, 0x37, 0xc430a750a8, 0x0, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/gophercloud/gophercloud/provider_client.go:169 +0x3b5
k8s.io/kubernetes/vendor/github.com/gophercloud/gophercloud.(*ServiceClient).Post(0xc426444e40, 0xc428126c00, 0x37, 0x2bff4a0, 0xc4289f1500, 0x298cde0, 0xc4289f1470, 0xc430a750a8, 0x40c99f, 0x2f21380, ...)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/gophercloud/gophercloud/service_client.go:78 +0x1b1
k8s.io/kubernetes/vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas/members.Create(0xc426444e40, 0x48e76c0, 0xc428126b80, 0x0, 0x0, 0x0, 0x0, 0x0)
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas/members/requests.go:74 +0x19a
```

Checked the openstack cloud provider that there is no HttpClient.Timeout set which means no timeout during http call. I think we should set at least the default http timeout value.
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L264-L291

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.6.3
- Cloud provider or hardware configuration**:
OpenStack

**Comment by dixudx** [comment]
/sig openstack
/kind feature

@xinxiaogang PTAL PR #53195.
