### ISSUE TITLE
kubelet status updates wedging after failed CRI call

### ISSUE THREAD

**Issue by jsravn** [kubernetes/kubernetes#53207]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Occasionally our nodes stop reporting their status to apiserver, and get marked as NotReady. However, they remain connected to the apiserver and receive the update to delete all their pods - which they do.

```
  OutOfDisk 		Unknown 	Thu, 28 Sep 2017 07:55:44 +0000 	Thu, 28 Sep 2017 07:57:04 +0000 	NodeStatusUnknown 	Kubelet stopped posting node status.
  MemoryPressure 	Unknown 	Thu, 28 Sep 2017 07:55:44 +0000 	Thu, 28 Sep 2017 07:57:04 +0000 	NodeStatusUnknown 	Kubelet stopped posting node status.
  DiskPressure 		Unknown 	Thu, 28 Sep 2017 07:55:44 +0000 	Thu, 28 Sep 2017 07:57:04 +0000 	NodeStatusUnknown 	Kubelet stopped posting node status.
  Ready 		Unknown 	Thu, 28 Sep 2017 07:55:44 +0000 	Thu, 28 Sep 2017 07:57:04 +0000 	NodeStatusUnknown 	Kubelet stopped posting node status.
  KernelDeadlock 	False 		Thu, 28 Sep 2017 07:58:38 +0000 	Wed, 27 Sep 2017 08:44:28 +0000 	KernelHasNoDeadlock 	kernel has no deadlock
```

In this example, the node last reported at 7:55:44.

This always seems to happen after I see these sort of log messages:
```
Sep 28 07:57:54 ip-10-50-97-190 start-kubelet.sh[1748]: E0928 07:57:54.064121    1748 remote_runtime.go:163] ListPodSandbox with filter "nil" from runtime service failed: rpc error: code = 4 desc = context deadline exceeded
Sep 28 07:57:54 ip-10-50-97-190 start-kubelet.sh[1748]: E0928 07:57:54.064194    1748 kuberuntime_sandbox.go:185] ListPodSandbox failed: rpc error: code = 4 desc = context deadline exceeded
Sep 28 07:57:54 ip-10-50-97-190 start-kubelet.sh[1748]: E0928 07:57:54.064209    1748 generic.go:198] GenericPLEG: Unable to retrieve pods: rpc error: code = 4 desc = context deadline exceeded
Sep 28 07:57:54 ip-10-50-97-190 start-kubelet.sh[1748]: E0928 07:57:54.081115    1748 remote_runtime.go:163] ListPodSandbox with filter "&PodSandboxFilter{Id:,State:&PodSandboxStateValue{State:SANDBOX_READY,},LabelSelector:map[string]string{},}" from runtime service failed: rpc error: code = 4 desc = context deadline exceeded
Sep 28 07:57:54 ip-10-50-97-190 start-kubelet.sh[1748]: E0928 07:57:54.081169    1748 kuberuntime_sandbox.go:185] ListPodSandbox failed: rpc error: code = 4 desc = context deadline exceeded
Sep 28 07:57:54 ip-10-50-97-190 start-kubelet.sh[1748]: E0928 07:57:54.081187    1748 kubelet_pods.go:842] Error listing containers: &grpc.rpcError{code:0x4, desc:"context deadline exceeded"}
Sep 28 07:57:54 ip-10-50-97-190 start-kubelet.sh[1748]: E0928 07:57:54.081210    1748 kubelet.go:1886] Failed cleaning pods: rpc error: code = 4 desc = context deadline exceeded
```

Which looks like the dockershim is timing out, maybe blocked on something.

Oddly, I never see these errors again in the kubelet logs - which indicates to me the PLEG loop continues to run successfully.

However after this time, all heartbeats to the apiserver stop. This even happened on an apiserver node, where kubelet connects to the localhost. So it doesn't seem like a network issue to me.

Next time this happens I'll try to capture a goroutine dump.

**What you expected to happen**:

Even if there is a temporary blip in the PLEG loop, kubelet should continue to send heartbeats, and then eventually go ready again.

**How to reproduce it (as minimally and precisely as possible)**:
I've been unable to reproduce it yet - it happens quite infrequently.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.9 / 1.7.10
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dchen1107** [comment]
@jsravn Thanks for reporting this. Yes, having goroutine dump might help to understand this infrequent failure.

**Comment by jsravn** [comment]
I've now had pods that continue to report "context deadline exceeded" to docker shim but still report the node as Ready. They are stuck in this mode until I restart kubelet. Something seems seriously wrong w/ dockershim/docker communication.

**Comment by jsravn** [comment]
Here's a goroutine dump of kubelet: looks like dockershim gets stuck while sending a request to docker. It looks like there is no timeout and dockershim wedges after this (despite docker itself still seeming to work for new connections).

[goroutines-10-50-201-163.txt](https://github.com/kubernetes/kubernetes/files/1368189/goroutines-10-50-201-163.txt)

**Comment by jsravn** [comment]
Deleted my comments - it was an unrelated issue (kernel hang on that node).

**Comment by jsravn** [comment]
This started happening to us more frequently recently. On 1.7.10.

I've attached a goroutine dump of when it happens:

[goroutinedump.txt](https://github.com/kubernetes/kubernetes/files/1517528/goroutinedump.txt)

**Comment by jsravn** [comment]
@dchen1107

**Comment by jsravn** [comment]
Today it happened to 3 of our prod nodes
```
  DiskPressure     Unknown   Thu, 30 Nov 2017 10:53:56 +0000   Thu, 30 Nov 2017 10:55:21 +0000   NodeStatusUnknown     Kubelet stopped posting node status.
  MemoryPressure   Unknown   Thu, 30 Nov 2017 10:53:56 +0000   Thu, 30 Nov 2017 10:55:21 +0000   NodeStatusUnknown     Kubelet stopped posting node status.
  OutOfDisk        Unknown   Thu, 30 Nov 2017 10:53:56 +0000   Thu, 30 Nov 2017 10:55:21 +0000   NodeStatusUnknown     Kubelet stopped posting node status.
  Ready            Unknown   Thu, 30 Nov 2017 10:53:56 +0000   Thu, 30 Nov 2017 10:55:21 +0000   NodeStatusUnknown     Kubelet stopped posting node status.
  KernelDeadlock   False     Thu, 30 Nov 2017 11:14:37 +0000   Tue, 28 Nov 2017 10:59:16 +0000   KernelHasNoDeadlock   kernel has no deadlock
```

**Comment by jsravn** [comment]
Looks like syncNodeStatus is hanging indefinitely waiting for docker to respond, when gathering version info.

```
goroutine 341 [select, 20 minutes]:
k8s.io/kubernetes/vendor/github.com/docker/engine-api/client/transport/cancellable.Do(0x7f8656a5cd98, 0xc420014368, 0x7f8656a0efa8, 0xc420ae4a40, 0xc423541200, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:56 +0x36b
k8s.io/kubernetes/vendor/github.com/docker/engine-api/client.(*Client).sendClientRequest(0xc42043d020, 0x7f8656a5cd98, 0xc420014368, 0x3a327c0, 0x3, 0x3a391da, 0x8, 0x0, 0x0, 0x0, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/docker/engine-api/client/request.go:100 +0x2e7
k8s.io/kubernetes/vendor/github.com/docker/engine-api/client.(*Client).sendRequest(0xc42043d020, 0x7f8656a5cd98, 0xc420014368, 0x3a327c0, 0x3, 0x3a391da, 0x8, 0x0, 0x0, 0x0, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/docker/engine-api/client/request.go:73 +0xe9
k8s.io/kubernetes/vendor/github.com/docker/engine-api/client.(*Client).get(0xc42043d020, 0x7f8656a5cd98, 0xc420014368, 0x3a391da, 0x8, 0x0, 0x0, 0x470636, 0xc4225f3778, 0x4434bb)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/docker/engine-api/client/request.go:31 +0xa7
k8s.io/kubernetes/vendor/github.com/docker/engine-api/client.(*Client).ServerVersion(0xc42043d020, 0x7f8656a5cd98, 0xc420014368, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/docker/engine-api/client/version.go:12 +0xab
k8s.io/kubernetes/vendor/github.com/google/cadvisor/container/docker.VersionString(0xc4234a1459, 0x12)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/container/docker/docker.go:148 +0xc8
k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.getVersionInfo(0x31, 0x31caf40, 0xc4218cac20)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager/manager.go:1272 +0x56
k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*manager).GetVersionInfo(0xc420085520, 0xc421ff4080, 0xc4218ced00, 0x40)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager/manager.go:755 +0x22
k8s.io/kubernetes/pkg/kubelet/cadvisor.(*cadvisorClient).VersionInfo(0xc4206f1bc0, 0x0, 0x0, 0x3a3931a)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/cadvisor/cadvisor_linux.go:176 +0x37
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).setNodeStatusVersionInfo(0xc420fa4000, 0xc420a3a000)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:605 +0x52
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).setNodeStatusInfo(0xc420fa4000, 0xc420a3a000)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:667 +0x51
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).(k8s.io/kubernetes/pkg/kubelet.setNodeStatusInfo)-fm(0xc420a3a000)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:970 +0x34
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).defaultNodeStatusFuncs.func1.1(0xc420a3a000, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:964 +0x2f
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).setNodeStatus(0xc420fa4000, 0xc420a3a000)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:952 +0x5e
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).tryUpdateNodeStatus(0xc420fa4000, 0x0, 0xd, 0x6)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:395 +0x4e6
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).updateNodeStatus(0xc420fa4000, 0xc42195de78, 0x42bdae)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:356 +0x45
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncNodeStatus(0xc420fa4000)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_node_status.go:348 +0x5a
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).(k8s.io/kubernetes/pkg/kubelet.syncNodeStatus)-fm()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1332 +0x2a
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc42038aba0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97 +0x5e
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc42038aba0, 0x2540be400, 0x0, 0x1, 0xc420060120)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98 +0xbd
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc42038aba0, 0x2540be400, 0xc420060120)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52 +0x4d
created by k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1332 +0x581
```

**Comment by jsravn** [comment]
So is that a cadvisor bug? It appears there is no timeout around querying docker.

**Comment by jsravn** [comment]
Indeed: https://github.com/google/cadvisor/blob/master/container/docker/docker.go#L139. These calls all should have a deadline on the context.

**Comment by jsravn** [comment]
Made a hopefully cherry pickable fix in #56630.

**Comment by dashpole** [comment]
cadvisor version 0.28.3 has been cut with the fix to this: https://github.com/google/cadvisor/pull/1830

**Comment by jsravn** [comment]
ACK. PR opened #56967
