### ISSUE TITLE
kube-apiserver 1.8 returns 500 with experimental-encryption-provider-config & changed key

### ISSUE THREAD

**Issue by RRAlex** [kubernetes/kubernetes#53301]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Upgrading to 1.8.0, I get weird errors from the API when using secrets after swapping the encryption key. I basically seem to be having ghost records. 
Doing a `kubectl get` gives the error bellow, and a `create` of the same secret name will say it `already exists`. Those secrets don't show up in a global `get`.

Maybe there should be an option to overwrite "ghost" records?

```
kubectl get secret --namespace=staging registry
Error from server (InternalError): Internal error occurred: output array was not large enough for encryption
```
The kube-apiserver reports:
```
Sep 30 17:48:49 localhost docker/kube-apiserver[982]: I0930 21:48:49.437238       1 wrap.go:42] PUT /api/v1/namespaces/kube-system/endpoints/kube-controller-manager: (6.770873ms) 200 [[kube-controller-manager/v1.8.0 (linux/amd64) kubernetes/6e93783/leader-election] 172.27.19.228:39882]
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: I0930 21:48:50.522597       1 wrap.go:42] GET /api/v1/namespaces/staging/secrets/registry: (2.403246ms) 500
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: goroutine 385517 [running]:
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc42b54c0e0, 0x1f4)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc42b54c0e0, 0x1f4)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc429449ea0, 0x1f4)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:201 +0xb5
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.(*ResponseWriterDelegator).WriteHeader(0xc428b56ea0, 0x1f4)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:173 +0x45
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x391bd5b, 0x23, 0x7fdf5dd624b8, 0xc427913ef0, 0x8127dc0, 0xc4278b89f8, 0xc429277700, 0x1f4, 0x8111080, 0xc427913e60)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:91 +0x8d
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x7fdf5db33fc0, 0xc4269e70b0, 0x812a300, 0xc420c0ac60, 0x0, 0x0, 0x38adfd1, 0x2, 0x8127dc0, 0xc4278b89f8, ...)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:113 +0x220
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.ErrorNegotiated(0x7fdf5db33fc0, 0xc4269e70b0, 0x80ff480, 0xc427913c20, 0x812a300, 0xc420c0ac60, 0x0, 0x0, 0x38adfd1, 0x2, ...)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:132 +0x16b
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.(*RequestScope).err(0xc428fc1e00, 0x80ff480, 0xc427913c20, 0x8127dc0, 0xc4278b89f8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:80 +0x10e
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.getResourceHandler.func1(0x8127dc0, 0xc4278b89f8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:131 +0x4bb
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints.restfulGetResource.func1(0xc428b56240, 0xc42b882780)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1099 +0xb7
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc428b56240, 0xc42b882780)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:145 +0x207
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc420897dd0, 0x7fdf5d734d90, 0xc4278b89e8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:277 +0xb8d
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(0xc420897dd0, 0x7fdf5d734d90, 0xc4278b89e8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:199 +0x57
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x38c4713, 0xe, 0xc420897dd0, 0xc4202eb500, 0x7fdf5d734d90, 0xc4278b89e8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:153 +0x6e7
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc4209917e0, 0x7fdf5d734d90, 0xc4278b89e8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011<autogenerated>:69 +0x86
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc42ad96f00, 0x7fdf5d734d90, 0xc4278b89e8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:91 +0x122
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc42b953c40, 0x7fdf5d734d90, 0xc4278b89e8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x3dd
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc421544930, 0x7fdf5d734d90, 0xc4278b89e8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x72
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x38c7dc4, 0xf, 0xc4249ff320, 0xc421544930, 0x7fdf5d734d90, 0xc4278b89e8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:161 +0x301
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc426bb1fc0, 0x7fdf5d734d90, 0xc4278b89e8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011<autogenerated>:69 +0x86
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7fdf5d734d90, 0xc4278b89e8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:51 +0x37a
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: net/http.HandlerFunc.ServeHTTP(0xc4226df400, 0x7fdf5d734d90, 0xc4278b89e8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/usr/local/go/src/net/http/server.go:1942 +0x44
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7fdf5d734d90, 0xc4278b89e8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:98 +0x5a0
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: net/http.HandlerFunc.ServeHTTP(0xc4263ae3c0, 0x7fdf5d734d90, 0xc4278b89e8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/usr/local/go/src/net/http/server.go:1942 +0x44
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7fdf5d734d90, 0xc4278b89e8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:49 +0x21b2
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: net/http.HandlerFunc.ServeHTTP(0xc4226df590, 0x7fdf5d734d90, 0xc4278b89e8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/usr/local/go/src/net/http/server.go:1942 +0x44
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7fdf5d734d90, 0xc4278b89e8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:79 +0x2b0
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: net/http.HandlerFunc.ServeHTTP(0xc4226df6d0, 0x7fdf5d734d90, 0xc4278b89e8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/usr/local/go/src/net/http/server.go:1942 +0x44
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x7fdf5d734d90, 0xc4278b89e8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xef
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: net/http.HandlerFunc.ServeHTTP(0xc426bb1fe0, 0x7fdf5d734d90, 0xc4278b89e8, 0xc429277700)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/usr/local/go/src/net/http/server.go:1942 +0x44
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc425e92060, 0x812bb80, 0xc4278b89e8, 0xc429277700, 0xc42b882660)
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:106 +0x8d
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: #011/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0x1ca
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: 
Sep 30 17:48:50 localhost docker/kube-apiserver[982]: logging error output: "k8s\x00\n\f\n\x02v1\x12\x06Status\x12\xb2\x01\n\x06\n\x00\x12\x00\x1a\x00\x12\aFailure\x1aIInternal error occurred: output array was not large enough for encryption\"\rInternalError*B\n\x00\x12\x00\x1a\x00\"6\n\x00\x120output array was not large enough for encryption\x1a\x00(\x002\x000\xf4\x03\x1a\x00\"\x00"
Sep 30 17:48:50 localhost docker/kube-apiserver[982]:  [[kubelet/v1.8.0 (linux/amd64) kubernetes/6e93783] 172.27.19.238:59768]
```
encryption-config.yml :
```
kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
    - secrets
    providers:
    - secretbox:
        keys:
        - name: key1
          # The secret that was changed...
          secret: MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE=
    - identity: {}
```
The launch command in the systemd service:
```
ExecStart=/usr/bin/docker run --rm \
  -v /var/lib/kubernetes:/var/lib/kubernetes \
  -p 6443:6443 \
  -p 8080:8080 \
  --net=host \
  --name kube-apiserver \
  gcr.io/google-containers/kube-apiserver-amd64:v1.8.0 \
   /usr/local/bin/kube-apiserver \
    --admission-control=NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds \
    --advertise-address=172.27.19.228 \
    --allow-privileged=true \
    --apiserver-count=3 \
    --audit-log-maxage=30 \
    --audit-log-maxbackup=3 \
    --audit-log-maxsize=100 \
    --audit-log-path=/var/log/audit.log \
    --authorization-mode=Node,RBAC \
    --bind-address=0.0.0.0 \
    --client-ca-file=/var/lib/kubernetes/ca.pem \
    --enable-swagger-ui=true \
    --etcd-cafile=/var/lib/kubernetes/ca.pem \
    --etcd-certfile=/var/lib/kubernetes/kubernetes.pem \
    --etcd-keyfile=/var/lib/kubernetes/kubernetes-key.pem \
    --etcd-servers=https://172.27.19.228:2379,https://172.27.19.232:2379,https://172.27.19.234:2379 \
    --event-ttl=1h \
    --experimental-encryption-provider-config=/var/lib/kubernetes/encryption-config.yml \
    --insecure-bind-address=127.0.0.1 \
    --kubelet-certificate-authority=/var/lib/kubernetes/ca.pem \
    --kubelet-client-certificate=/var/lib/kubernetes/kubernetes.pem \
    --kubelet-client-key=/var/lib/kubernetes/kubernetes-key.pem \
    --kubelet-https=true \
    --runtime-config=rbac.authorization.k8s.io/v1alpha1 \
    --service-account-key-file=/var/lib/kubernetes/ca-key.pem \
    --service-cluster-ip-range=240.0.0.0/24 \
    --service-node-port-range=30000-32767 \
    --tls-ca-file=/var/lib/kubernetes/ca.pem \
    --tls-cert-file=/var/lib/kubernetes/kubernetes.pem \
    --tls-private-key-file=/var/lib/kubernetes/kubernetes-key.pem \
    --v=2
```

**What you expected to happen**:

It seems that changing the secret for the experimental encrypted secret store breaks things by keeping impossible to list "ghost" secrets.

**How to reproduce it (as minimally and precisely as possible)**:
Change the secret and restart the apiserver.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:46:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration**:
OpenStack 3 controllers and 4 seperate worker nodes.
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux staging-controller-001 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by RRAlex** [comment]
@kubernetes/sig-api-machinery
/sig area/secret-api

**Comment by liggitt** [comment]
Changing encryption keys and removing the old decrypting keys without rotating storage orphans records in etcd. follow the instructions to rotate encrypted secrets before removing the old key. 

https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/

> IMPORTANT: If any resource is not readable via the encryption config (because keys were changed), the only recourse is to delete that key from the underlying etcd directly. Calls that attempt to read that resource will fail until it is deleted or a valid decryption key is provided.
