### ISSUE TITLE
pull-kubernetes-e2e-kubeadm-gce and ci-kubernetes-e2e-kubeadm-gce are broken

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#53570]
Please see recent runs:
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kubeadm-gce

```
W1008 13:54:33.559] 2017/10/08 13:54:33 util.go:154: Running: make -C /workspace/kubernetes-anywhere kubeconfig-path
I1008 13:54:33.659] make: Entering directory '/workspace/kubernetes-anywhere'
I1008 13:54:33.759] util/config_to_json /workspace/kubernetes-anywhere/.config > /workspace/kubernetes-anywhere/.config.json
I1008 13:54:33.771] Makefile:43: recipe for target '/workspace/kubernetes-anywhere/.config.json' failed
I1008 13:54:33.771] make: Leaving directory '/workspace/kubernetes-anywhere'
I1008 13:54:33.816] make: Entering directory '/workspace/kubernetes-anywhere'
I1008 13:54:33.822] make do WHAT=deploy-cluster
I1008 13:54:33.826] make[1]: Entering directory '/workspace/kubernetes-anywhere'
I1008 13:54:33.833] ( cd "phase1/"; ./do deploy-cluster )
I1008 13:54:33.839] Makefile:77: recipe for target 'do' failed
I1008 13:54:33.839] make[1]: Leaving directory '/workspace/kubernetes-anywhere'
I1008 13:54:33.839] Makefile:49: recipe for target 'deploy-cluster' failed
I1008 13:54:33.839] make: Leaving directory '/workspace/kubernetes-anywhere'
I1008 13:54:33.867] make: Entering directory '/workspace/kubernetes-anywhere'
I1008 13:54:33.882] Makefile:57: recipe for target 'kubeconfig-path' failed
I1008 13:54:33.882] make: Leaving directory '/workspace/kubernetes-anywhere'
W1008 13:54:33.983] util/config_to_json: line 35: jq: command not found
W1008 13:54:33.983] make: *** [/workspace/kubernetes-anywhere/.config.json] Error 127
W1008 13:54:33.983] 2017/10/08 13:54:33 util.go:156: Step 'make -C /workspace/kubernetes-anywhere kubeconfig-path' finished in 256.10281ms
W1008 13:54:33.983] 2017/10/08 13:54:33 util.go:154: Running: make -C /workspace/kubernetes-anywhere WAIT_FOR_KUBECONFIG=y deploy
W1008 13:54:33.983] + cd .
W1008 13:54:33.984] + CONFIG_FILE=/workspace/kubernetes-anywhere/.config.json
W1008 13:54:33.984] ++ jq -r .phase1.cloud_provider /workspace/kubernetes-anywhere/.config.json
W1008 13:54:33.984] ./do: line 11: jq: command not found
```

**Comment by dims** [comment]
looks like `jq` is missing from the image?

https://github.com/kubernetes/kubernetes-anywhere/blob/master/util/config_to_json#L35

**Comment by dims** [comment]
Looks like `jq` as installed in a bunch of places here : https://github.com/kubernetes/test-infra/pull/3276/commits/23a93a63ed6c8631992d7caa2a780ea1e869a980

**Comment by dims** [comment]
@ixdy @fejta @david-mcmahon - Can you please help?

**Comment by dims** [comment]
cc @luxas

**Comment by ixdy** [comment]
This was probably #4915 - @krzyzacy 

I'll revert https://github.com/kubernetes/test-infra/commit/17c8eb57bd042d347f93e966135acb59dd775a91.

**Comment by ixdy** [comment]
Reverted the offending commit, so hopefully the kubeadm builds will start passing again.

Also working on a PR to bring `jq` back into our `kubekins-e2e` images.

**Comment by dims** [comment]
Thanks @ixdy

**Comment by dims** [comment]
@krzyzacy @ixdy @fejta - The `jq` problem has been fixed, but another problem cropped up

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/53546/pull-kubernetes-e2e-kubeadm-gce/8179/build-log.txt

```
I1009 17:01:23.390] Call:  /workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py --cluster= --deployment=kubernetes-anywhere --env-file=jobs/platform/gce.env --gcp-zone=us-central1-f --ginkgo-parallel=30 --kubeadm=pull --kubernetes-anywhere-kubernetes-version=ci/latest --provider=kubernetes-anywhere '--test_args=--ginkgo.focus=\[Conformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\] --minStartupPods=8' --timeout=55m --use-shared-build=bazel
W1009 17:01:23.432] Getting shared build location from: gs://kubernetes-jenkins/shared-results/master:92210a7d76ddac84fdf0d9439b08e4d54b61be72,53546:b31c5382f4721c6fab721b0740a6cb3744b9672c/bazel-build-location.txt
W1009 17:01:23.470] Failed to get shared build location: HTTP Error 404: Not Found
W1009 17:01:23.471] Waiting 5 seconds and retrying...
W1009 17:01:28.539] Failed to get shared build location: HTTP Error 404: Not Found
W1009 17:01:28.540] Waiting 5 seconds and retrying...
W1009 17:01:33.582] Failed to get shared build location: HTTP Error 404: Not Found
W1009 17:01:33.582] Waiting 5 seconds and retrying...
W1009 17:01:38.621] Failed to get shared build location: HTTP Error 404: Not Found
W1009 17:01:38.621] Waiting 5 seconds and retrying...
W1009 17:01:43.664] Failed to get shared build location: HTTP Error 404: Not Found
W1009 17:01:43.665] Waiting 5 seconds and retrying...
W1009 17:01:48.706] Failed to get shared build location: HTTP Error 404: Not Found
W1009 17:01:48.706] Waiting 5 seconds and retrying...
W1009 17:01:53.751] Failed to get shared build location: HTTP Error 404: Not Found
W1009 17:01:53.751] Waiting 5 seconds and retrying...
W1009 17:01:58.795] Failed to get shared build location: HTTP Error 404: Not Found
W1009 17:01:58.795] Waiting 5 seconds and retrying...
W1009 17:02:03.850] Failed to get shared build location: HTTP Error 404: Not Found
W1009 17:02:03.851] Waiting 5 seconds and retrying...
W1009 17:02:08.898] Failed to get shared build location: HTTP Error 404: Not Found
W1009 17:02:08.898] Waiting 5 seconds and retrying...
W1009 17:02:13.932] Failed to get shared build location: HTTP Error 404: Not Found
W1009 17:02:13.932] Waiting 5 seconds and retrying...
W1009 17:02:18.980] Failed to get shared build location: HTTP Error 404: Not Found
W1009 17:02:18.980] Traceback (most recent call last):
W1009 17:02:18.980]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 766, in <module>
W1009 17:02:18.981]     main(parse_args())
W1009 17:02:18.981]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 532, in main
W1009 17:02:18.981]     raise RuntimeError('Failed to get shared build location too many times!')
W1009 17:02:18.981] RuntimeError: Failed to get shared build location too many times!
```

**Comment by ixdy** [comment]
Retesting "run-after" jobs doesn't seem to work properly; I think that's a known issue. @BenTheElder

**Comment by krzyzacy** [comment]
@dims probably try to re-trigger the bazel-build job instead

**Comment by dims** [comment]
@ixdy @krzyzacy - ok, let me try rebasing under master and do a totally fresh run

**Comment by BenTheElder** [comment]
Yeah, run-after-success is screwy, the correct way right now is to re-trigger the parent job. The kubeadm job is the only PR job using that feature currently because it is awkward. We should probably have another issue about that if I don't have one already..

**Comment by luxas** [comment]
@BenTheElder This worked a week or so ago... Any known recent breakage?

**Comment by BenTheElder** [comment]
The only breakage I know of is the missing jq problem, I haven't touched run_after_success or the shared builds logic in a long time and I don't know that anyone else has either.

**Comment by luxas** [comment]
Hmm, that's strange. @idxy @kargakis any clues?

**Comment by dims** [comment]
Next problem : https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/53546/pull-kubernetes-e2e-kubeadm-gce/8181/build-log.txt

```
I1009 19:09:39.647] Oct  9 18:19:01.976: INFO: Condition Ready of node e2e-8181-master is false instead of true. Reason: KubeletNotReady, message: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
I1009 19:09:39.647] Oct  9 18:19:01.977: INFO: Condition Ready of node e2e-8181-node-qqw6 is false instead of true. Reason: KubeletNotReady, message: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

**Comment by dims** [comment]
Could this recent change be the source of issue? https://github.com/kubernetes/test-infra/pull/2771

**Comment by krzyzacy** [comment]
I don't think we've updated the image with that change yet

**Comment by dims** [comment]
@krzyzacy - that got past the `jq` issue. thanks!

Both `pull-kubernetes-e2e-kubeadm-gce` and `ci-kubernetes-e2e-kubeadm-gce` are broken:

https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kubeadm-gce
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/

Symptom seens to be a problem with CNI initialization

```
I1010 09:18:45.802] Oct 10 09:18:45.802: INFO: Condition Ready of node e2e-6968-master is false instead of true. Reason: KubeletNotReady, message: runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
```

**Comment by dims** [comment]
@krzyzacy @fejta - can one of you please get me the kubelet logs for one of the latest runs?

**Comment by roberthbailey** [comment]
@kubernetes/sig-cluster-lifecycle-bugs

**Comment by dims** [comment]
Thanks for the kubelet logs @krzyzacy Looks like the containers are crash looping

```
Oct 10 18:39:52 e2e-6970-node-brs0 kubelet[4943]: I1010 18:39:52.403556    4943 kuberuntime_manager.go:739] checking backoff for container "kube-proxy" in pod "kube-proxy-gl7xt_kube-system(1f5cf49b-adcf-11e7-b866-42010a800002)"
Oct 10 18:39:52 e2e-6970-node-brs0 kubelet[4943]: I1010 18:39:52.403842    4943 kuberuntime_manager.go:749] Back-off 5m0s restarting failed container=kube-proxy pod=kube-proxy-gl7xt_kube-system(1f5cf49b-adcf-11e7-b866-42010a800002)
Oct 10 18:39:56 e2e-6970-node-brs0 kubelet[4943]: I1010 18:39:56.402319    4943 kuberuntime_manager.go:500] Container {Name:weave Image:weaveworks/weave-kube:1.9.4 Command:[/home/weave/launch.sh] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[cpu:{i:{value:10 scale:-3} d:{Dec:<nil>} s:10m Format:DecimalSI}]} VolumeMounts:[{Name:weavedb ReadOnly:false MountPath:/weavedb SubPath: MountPropagation:<nil>} {Name:cni-bin ReadOnly:false MountPath:/host/opt SubPath: MountPropagation:<nil>} {Name:cni-bin2 ReadOnly:false MountPath:/host/home SubPath: MountPropagation:<nil>} {Name:cni-conf ReadOnly:false MountPath:/host/etc SubPath: MountPropagation:<nil>} {Name:dbus ReadOnly:false MountPath:/host/var/lib/dbus SubPath: MountPropagation:<nil>} {Name:lib-modules ReadOnly:false MountPath:/lib/modules SubPath: MountPropagation:<nil>} {Name:weave-net-token-2l8tm ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil>}] LivenessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/status,Port:6784,Host:127.0.0.1,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:30,TimeoutSeconds:1,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,} ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*true,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Oct 10 18:39:56 e2e-6970-node-brs0 kubelet[4943]: I1010 18:39:56.403664    4943 kuberuntime_manager.go:739] checking backoff for container "weave" in pod "weave-net-m7rgd_kube-system(249f5abb-adcf-11e7-b866-42010a800002)"
Oct 10 18:39:56 e2e-6970-node-brs0 kubelet[4943]: I1010 18:39:56.404004    4943 kuberuntime_manager.go:749] Back-off 5m0s restarting failed container=weave pod=weave-net-m7rgd_kube-system(249f5abb-adcf-11e7-b866-42010a800002)
Oct 10 18:40:07 e2e-6970-node-brs0 kubelet[4943]: I1010 18:40:07.405689    4943 kuberuntime_manager.go:500] Container {Name:kube-proxy Image:gcr.io/kubernetes-ci-images/kube-proxy-amd64:v1.9.0-alpha.1.896_46c2bfe47df080 Command:[/usr/local/bin/kube-proxy --kubeconfig=/var/lib/kube-proxy/kubeconfig.conf] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:kube-proxy ReadOnly:false MountPath:/var/lib/kube-proxy SubPath: MountPropagation:<nil>} {Name:xtables-lock ReadOnly:false MountPath:/run/xtables.lock SubPath: MountPropagation:<nil>} {Name:kube-proxy-token-sz5m8 ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil>}] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*true,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
```

**Comment by dims** [comment]
kube-proxy seems to be failing with:
```
{"log":"W1011 15:09:32.772916       1 server.go:193] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.\n","stream":"stderr","time":"2017-10-11T15:09:32.773134794Z"}
{"log":"error: KubeProxyConfiguration.ClusterCIDR: Invalid value: \"\": must be a valid CIDR block (e.g. 10.100.0.0/16)\n","stream":"stderr","time":"2017-10-11T15:09:32.77330047Z"}
```

weave-net is failing with:
```
{"log":"2017/10/11 15:11:09 error contacting APIServer: Get https://10.96.0.1:443/api/v1/nodes: dial tcp 10.96.0.1:443: i/o timeout; trying with fallback: http://localhost:8080\n","stream":"stderr","time":"2017-10-11T15:11:09.184802842Z"}
{"log":"2017/10/11 15:11:09 Could not get peers: Get http://localhost:8080/api/v1/nodes: dial tcp 127.0.0.1:8080: getsockopt: connection refused\n","stream":"stderr","time":"2017-10-11T15:11:09.196577602Z"}
{"log":"Failed to get peers\n","stream":"stderr","time":"2017-10-11T15:11:09.196609087Z"}
```

**Comment by dims** [comment]
Looks like https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-gce/ is back on its feet after  #53749 got merged !

**Comment by dims** [comment]
Looks like we are done here!

**Comment by cblecker** [comment]
Awesome! Thanks for your work on this @dims!

**Comment by luxas** [comment]
Thank you for haunting down that proxy regression @dims, awesome!
