### ISSUE TITLE
pull-kubernetes-bazel-build broken

### ISSUE THREAD

**Issue by david-mcmahon** [kubernetes/kubernetes#53923]
See [recent runs](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-bazel-build):

```
source hack/lib/version.sh
kube::version::get_version_vars
echo $KUBE_GIT_VERSION
'
I1013 23:17:06.312] process 56 exited with code 0 after 0.0m
I1013 23:17:06.313] Call:  gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json
W1013 23:17:09.073] Activated service account credentials for: [pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com]
I1013 23:17:09.772] process 89 exited with code 0 after 0.1m
I1013 23:17:09.772] Call:  gcloud config get-value account
I1013 23:17:11.177] process 102 exited with code 0 after 0.0m
I1013 23:17:11.179] Will upload results to gs://kubernetes-jenkins/pr-logs using pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com
I1013 23:17:11.180] Start 9442 at v1.9.0-alpha.1.1133+053c73e9b7c612...
I1013 23:17:11.182] Call:  gsutil -q -h Content-Type:application/json cp - gs://kubernetes-jenkins/pr-logs/pull/52883/pull-kubernetes-bazel-build/9442/started.json
I1013 23:17:14.935] process 115 exited with code 0 after 0.1m
I1013 23:17:14.936] Call:  gsutil -q -h Content-Type:text/plain -h 'x-goog-meta-link: gs://kubernetes-jenkins/pr-logs/pull/52883/pull-kubernetes-bazel-build/9442' cp - gs://kubernetes-jenkins/pr-logs/directory/pull-kubernetes-bazel-build/9442.txt
I1013 23:17:18.184] process 287 exited with code 0 after 0.1m
I1013 23:17:18.214] Call:  /workspace/./test-infra/jenkins/../scenarios/kubernetes_bazel.py '--build=//cmd/... //pkg/... //federation/... //plugin/... //third_party/... //examples/... //test/... //vendor/k8s.io/...' --release=//build/release-tars
W1013 23:17:18.345] Run: ('bazel', 'clean', '--expunge')
W1013 23:17:18.563] INFO: $TEST_TMPDIR defined: output root default is '/root/.cache/bazel'.
W1013 23:17:20.816] Java version not detected while at least 1.8 is needed.
W1013 23:17:20.819] Please set JAVA_HOME.
W1013 23:17:20.820] Traceback (most recent call last):
W1013 23:17:20.820]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_bazel.py", line 219, in <module>
W1013 23:17:20.821]     main(parse_args())
W1013 23:17:20.823]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_bazel.py", line 117, in main
W1013 23:17:20.823]     check('bazel', 'clean', '--expunge')
W1013 23:17:20.824]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_bazel.py", line 33, in check
W1013 23:17:20.824]     subprocess.check_call(cmd)
W1013 23:17:20.824]   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
W1013 23:17:20.865]     raise CalledProcessError(retcode, cmd)
W1013 23:17:20.866] subprocess.CalledProcessError: Command '('bazel', 'clean', '--expunge')' returned non-zero exit status 36
E1013 23:17:20.869] Command failed
I1013 23:17:20.870] process 459 exited with code 1 after 0.0m
E1013 23:17:20.871] FAIL: pull-kubernetes-bazel-build
I1013 23:17:20.871] Upload result and artifacts...
I1013 23:17:20.873] Gubernator results at https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/52883/pull-kubernetes-bazel-build/9442
```

cc @kubernetes/test-infra-maintainers @javier-b-perez

**Comment by BenTheElder** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-bazel-build/9447/
`Unrecognized option: --incompatible_comprehension_variables_do_not_leak=false`

seeing that and the message about JAVA_HOME above, but also a lot of green builds

**Comment by dims** [comment]
Is this in some way related to https://github.com/kubernetes/kubernetes/issues/52677 ?

**Comment by BenTheElder** [comment]
This only seems to affect your PR and the batch it was tested in. Other recent reds look to be failures to build broken go code.

**Comment by david-mcmahon** [comment]
And my PR went through.  So yeah, I dunno.

**Comment by ixdy** [comment]
It seems like batch jobs are using the release-1.6 branch configurations, rather than the master branch configurations. 
cc @rmmh
