### ISSUE TITLE
kubelet crashes on handling /summary when failing to retrieve imagestats from docker

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#54097]
I noticed on several GKE prod nodes, kubelet crashes with the following stacktrace. 

```
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: I1014 11:41:05.552990    1650 server.go:794] GET /stats/summary/: (192.043619ms) 500
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: goroutine 27377206 [running]:
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc4250322a0, 0x1f4)
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/log.go:219 +0xdd
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc4250322a0, 0x1f4)
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/log.go:198 +0x35
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteHeader(0xc42961e840, 0x1f4)
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/response.go:201 +0x41
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteErrorString(0xc42961e840, 0x1f4, 0xc421b39e60, 0x8d, 0x2, 0xc421b39e60)
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/response.go:181 +0x46
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: k8s.io/kubernetes/pkg/kubelet/server/stats.handleError(0xc42961e840, 0x3a4ccb4, 0xe, 0x57a0360, 0xc428cf21e0)
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/handler.go:248 +0x1da
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*handler).handleSummary(0xc4207cc320, 0xc42764f230, 0xc42961e840)
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/handler.go:159 +0x79
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*handler).(k8s.io/kubernetes/pkg/kubelet/server/stats.handleSummary)-fm(0xc42764f230, 0xc42961e840)
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/handler.go:71 +0x3e
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc4203d2240, 0x57c8820, 0xc4250322a0, 0xc42048dc00)
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:277 +0xb8d
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x57c8820, 0xc4250322a0, 0xc42048dc00)
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x48
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: net/http.HandlerFunc.ServeHTTP(0xc420252e60, 0x57c8820, 0xc4250322a0, 0xc42048dc00)
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: 	/usr/local/go/src/net/http/server.go:1942 +0x44
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: net/http.(*ServeMux).ServeHTTP(0xc4202d4570, 0x57c8820, 0xc4250322a0, 0xc42048dc00)
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: 	/usr/local/go/src/net/http/server.go:2238 +0x130
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc4203d2240, 0x57c8820, 0xc4250322a0, 0xc42048dc00)
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:292 +0x4d
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: k8s.io/kubernetes/pkg/kubelet/server.(*Server).ServeHTTP(0xc4206da9b0, 0x57c8820, 0xc4250322a0, 0xc42048dc00)
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:793 +0x110
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: net/http.serverHandler.ServeHTTP(0xc4202344d0, 0x57ceda0, 0xc4286f35e0, 0xc42048dc00)
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: 	/usr/local/go/src/net/http/server.go:2568 +0x92
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: net/http.(*conn).serve(0xc423e8e000, 0x57d0fa0, 0xc425392140)
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: 	/usr/local/go/src/net/http/server.go:1825 +0x612
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: created by net/http.(*Server).Serve
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: 	/usr/local/go/src/net/http/server.go:2668 +0x2ce
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]: logging error output: "Internal Error: failed ImageStats: rpc error: code = 2 desc = Cannot connect to the Docker daemon. Is the docker daemon running on this host?"
Oct 14 11:41:05 gke-XXX-XXX-pool-11-f98a46ec-65t6 kubelet[1650]:  [[Go-http-client/1.1] 10.163.0.43:35630]
```

cc/ @kubernetes/sig-node-bugs @dashpole

**Comment by dashpole** [comment]
cc @yguo0905

**Comment by yujuhong** [comment]
@dchen1107 what's the version of the kubelet?
