### ISSUE TITLE
Frequent "end of JSON input", from kubectl >= 1.7 with old/empty cache

### ISSUE THREAD

**Issue by tcolgate** [kubernetes/kubernetes#54859]
/kind bug

**What happened**:

Running newer kubectl version beyond 1.6 gives errors for simple get commands if the command has not been run for "some time" (annecdotally about 15m). Versions < 1.8.2 fail with `unexpected end of JSON input", 1.8.2 fails with a net.OpError (see below).

Deleteing ~/.kube/cache and ~/.kube/http-cache can more reliably reproduce the problem on the newer versions.

The failing runs do not hang for any notable period of time but return with the error after approximately 1s.

**What you expected to happen**:

kubectl get pods should reliably return results.

**How to reproduce it (as minimally and precisely as possible)**:

```
rm -rf ~/.kube/cache ~/.kube/http-cache

time kubectl18 --logtostderr=true --log-backtrace-at=request.go:766  --v 5 get pods
E1031 11:40:35.656870    4802 request.go:766] Unexpected error when reading response body: &net.OpError{Op:"read", Net:"tcp", Source:(*net.TCPAddr)(0xc420948540), Addr:(*net.TCPAddr)(0xc420948570), Err:(*os.SyscallError)(0xc42084a020)}
goroutine 1 [running]:
k8s.io/kubernetes/vendor/github.com/golang/glog.stacks(0x22fbf00, 0x216bc1d, 0xa, 0x2fe)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:766 +0xa7
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).output(0x22fbf40, 0xc400000002, 0xc42096cc60, 0x216bc1d, 0xa, 0x2fe, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:675 +0x637
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).printf(0x22fbf40, 0x2, 0x17ac46d, 0x30, 0xc42077aaa0, 0x1, 0x1)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:655 +0x14f
k8s.io/kubernetes/vendor/github.com/golang/glog.Errorf(0x17ac46d, 0x30, 0xc42077aaa0, 0x1, 0x1)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:1118 +0x67
k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Request).transformResponse(0xc4206c0780, 0xc4208cb950, 0xc42096ad00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:766 +0x8b9
k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Request).Do.func1(0xc42096ad00, 0xc4208cb950)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:718 +0x5f
k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Request).request.func2(0xc4208cb950, 0xc42077aee0, 0xa, 0xc4206c0780, 0xc42077afb0, 0xc42096ad00, 0xc4208d0e10, 0x44, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:696 +0xd7
k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Request).request(0xc4206c0780, 0xc42077afb0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:698 +0x3ea
k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Request).Do(0xc4206c0780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:719 +0xc0
k8s.io/kubernetes/pkg/kubectl/resource.(*Helper).List(0xc4208aca40, 0x1772f18, 0x7, 0xc420356860, 0x2, 0x21a0320, 0xc420433540, 0x0, 0xc42040e2a0, 0xc420366870, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/helper.go:82 +0x1b5
k8s.io/kubernetes/pkg/kubectl/resource.(*Selector).Visit(0xc4205de800, 0xc420899ce0, 0x1771fdd, 0x6)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/selector.go:52 +0x119
k8s.io/kubernetes/pkg/kubectl/resource.EagerVisitorList.Visit(0xc4202edfa0, 0x1, 0x1, 0xc420976420, 0x1, 0xc420976420)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:211 +0x100
k8s.io/kubernetes/pkg/kubectl/resource.(*EagerVisitorList).Visit(0xc4209b5000, 0xc420976420, 0x7f8877b5d000, 0x0)
        <autogenerated>:115 +0x69
k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit(0x2183d00, 0xc4209b5000, 0xc420012800, 0xc4208aca00, 0xc420899c01, 0xc4208aca00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:417 +0xa3
k8s.io/kubernetes/pkg/kubectl/resource.(*FlattenListVisitor).Visit(0xc4209b5020, 0xc4208aca00, 0x18, 0x18)
        <autogenerated>:130 +0x69
k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit(0x2183d80, 0xc4209b5020, 0xc4209b5060, 0x3, 0x4, 0xc420899ca0, 0x40eb01, 0xc420899ca0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:325 +0xd8
k8s.io/kubernetes/pkg/kubectl/resource.(*DecoratedVisitor).Visit(0xc4209b6ed0, 0xc420899ca0, 0xc420030800, 0x10)
        <autogenerated>:153 +0x73
k8s.io/kubernetes/pkg/kubectl/resource.ContinueOnErrorVisitor.Visit(0x2183c80, 0xc4209b6ed0, 0xc4201fb440, 0x1603dc0, 0x1311101)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:352 +0xf1
k8s.io/kubernetes/pkg/kubectl/resource.(*ContinueOnErrorVisitor).Visit(0xc4202ce010, 0xc4201fb440, 0x0, 0xc42077b668)
        <autogenerated>:144 +0x60
k8s.io/kubernetes/pkg/kubectl/resource.(*Result).Infos(0xc4206c5340, 0x0, 0x0, 0xc4209763f0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource/result.go:124 +0xfd
k8s.io/kubernetes/pkg/kubectl/cmd.RunGet(0x21acd60, 0xc4202e2810, 0x2182e40, 0xc42000c018, 0x2182e40, 0xc42000c020, 0xc4203726c0, 0xc420829590, 0x1, 0x5, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:418 +0x27aa
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdGet.func1(0xc4203726c0, 0xc420829590, 0x1, 0x5)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:122 +0x95
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203726c0, 0xc420287280, 0x5, 0x8, 0xc4203726c0, 0xc420287280)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:603 +0x22b
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4201fe6c0, 0x8000102, 0x0, 0xffffffffffffffff)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:689 +0x339
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4201fe6c0, 0xc4202e2810, 0x2182e00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:648 +0x2b
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:39 +0xd5
main.main()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:26 +0x22
F1031 11:40:35.657060    4802 helpers.go:120] Unexpected error &net.OpError{Op:"read", Net:"tcp", Source:(*net.TCPAddr)(0xc420948540), Addr:(*net.TCPAddr)(0xc420948570), Err:(*os.SyscallError)(0xc42084a020)} when reading response body. Please retry.
kubectl18 --logtostderr=true --log-backtrace-at=request.go:766 --v 5 get pods  0.09s user 0.01s system 8% cpu 1.217 total
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
  - all tests against server 1.7.5 (though we see this again other v1.7 servers, others are untested)
  - clients:
    - 1.6: works reliably
    - 1.7.5: fails with "end of JSON input" 70% of the time.
    - 1.8.2: fails as shown above about 70% of the time.
- Cloud provider or hardware configuration:
  - Test on kops aws and GKE , same behaviour on both.
- OS (e.g. from /etc/os-release):
  client ```PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
server: various , ubuntu and container OS
- Kernel (e.g. `uname -a`): client `4.7.0-0.bpo.1-amd64`, server: various

- Install tools:
- Others:

**Comment by apelisse** [comment]
@liggitt Not something I know about. This can't be related to http-caching as I added it, since it only applies to discovery request.

**Comment by tcolgate** [comment]
We're pretty sure this has now been resolved. I can't clearly state when, but as of 1.8.4 this appears to be resolved (I've asked a few colleagues, we can't be sure when it stopped).
