### ISSUE TITLE
[job failure] pull-kubernetes-e2e-kops-aws failed

### ISSUE THREAD

**Issue by dixudx** [kubernetes/kubernetes#55303]
/priority critical-urgent
/priority failing-test
/kind bug
@kubernetes/sig-testing-test-failures 

```
W1108 07:13:35.698]       --test-cmd-name string                              name to log the test command as in xml results
W1108 07:13:35.698]       --test_args string                                  Space-separated list of arguments to pass to Ginkgo test runner. (default "")
W1108 07:13:35.698]       --timeout duration                                  Terminate testing after the timeout duration (s/m/h) (default 0s)
W1108 07:13:35.698]       --up                                                If true, start the the e2e cluster. If cluster is already up, recreate it. (default false)
W1108 07:13:35.698]       --upgrade_args string                               If set, run upgrade tests before other tests
W1108 07:13:35.698]   -v, --v                                                 If true, print all command output. (default false)
W1108 07:13:35.699] 2017/11/08 07:13:35 main.go:295: Flag parse failed: unknown flag: --kops-ssh-user
W1108 07:13:36.153] Run: ('sudo', 'chmod', '-R', 'o+r', '/var/lib/jenkins/workspace/pull-kubernetes-e2e-kops-aws/_artifacts')
W1108 07:13:36.162] Traceback (most recent call last):
W1108 07:13:36.162]   File "/var/lib/jenkins/workspace/pull-kubernetes-e2e-kops-aws/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 871, in <module>
W1108 07:13:36.162]     main(parse_args())
W1108 07:13:36.162]   File "/var/lib/jenkins/workspace/pull-kubernetes-e2e-kops-aws/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 711, in main
W1108 07:13:36.162]     mode.start(runner_args)
W1108 07:13:36.163]   File "/var/lib/jenkins/workspace/pull-kubernetes-e2e-kops-aws/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 369, in start
W1108 07:13:36.163]     check(*cmd)
W1108 07:13:36.163]   File "/var/lib/jenkins/workspace/pull-kubernetes-e2e-kops-aws/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 49, in check
W1108 07:13:36.163]     subprocess.check_call(cmd)
W1108 07:13:36.163]   File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
W1108 07:13:36.163]     raise CalledProcessError(retcode, cmd)
```

https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kops-aws

**Comment by xiangpengzhao** [comment]
I guess CI should update kubetest. ref: https://github.com/kubernetes/test-infra/pull/5398

/cc @justinsb @krzyzacy

**Comment by krzyzacy** [comment]
whoooops did not realize this touches the pr job, I'll bump the image

**Comment by krzyzacy** [comment]
should be fixed by https://github.com/kubernetes/test-infra/pull/5402

**Comment by dixudx** [comment]
@krzyzacy Thanks
