### ISSUE TITLE
Race in metrics/util.go tests

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#55488]
Fix to follow

```
> bazel test //pkg/util/metrics/... --runs_per_test 200
INFO: Analysed 4 targets (0 packages loaded).
INFO: Found 3 targets and 1 test target...
FAIL: //pkg/util/metrics:go_default_test (run 36 of 200) (see /home/justinsb/.cache/bazel/_bazel_justinsb/53419f5d51785321b16f924d43766350/execroot/__main__/bazel-out/local-fastbuild/testlogs/pkg/util/metrics/go_default_test/run_36_of_200/test.log)
INFO: From Testing //pkg/util/metrics:go_default_test (run 36 of 200):
==================== Test output for //pkg/util/metrics:go_default_test (run 36 of 200):
PASS
E1110 16:26:01.682104   16494 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/justinsb/.cache/bazel/_bazel_justinsb/53419f5d51785321b16f924d43766350/external/go_sdk/src/runtime/asm_amd64.s:509
/home/justinsb/.cache/bazel/_bazel_justinsb/53419f5d51785321b16f924d43766350/external/go_sdk/src/runtime/panic.go:491
/home/justinsb/.cache/bazel/_bazel_justinsb/53419f5d51785321b16f924d43766350/external/go_sdk/src/runtime/panic.go:63
/home/justinsb/.cache/bazel/_bazel_justinsb/53419f5d51785321b16f924d43766350/external/go_sdk/src/runtime/signal_unix.go:367
pkg/util/metrics/util.go:77
vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/home/justinsb/.cache/bazel/_bazel_justinsb/53419f5d51785321b16f924d43766350/external/go_sdk/src/runtime/asm_amd64.s:2337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x7d11c7]

goroutine 19 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x16f
panic(0x824e60, 0xa7e7f0)
	/home/justinsb/.cache/bazel/_bazel_justinsb/53419f5d51785321b16f924d43766350/external/go_sdk/src/runtime/panic.go:491 +0x2a2
k8s.io/kubernetes/pkg/util/metrics.RegisterMetricAndTrackRateLimiterUsage.func1()
	pkg/util/metrics/util.go:77 +0x127
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc42015e000)
	vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x70
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc42015e000, 0x12a05f200, 0x0, 0x45d101, 0xc42015a000)
	vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xce
k8s.io/apimachinery/pkg/util/wait.Until(0xc42015e000, 0x12a05f200, 0xc42015a000)
	vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x5b
created by k8s.io/kubernetes/pkg/util/metrics.RegisterMetricAndTrackRateLimiterUsage
	pkg/util/metrics/util.go:74 +0x1a1
================================================================================
...
```

**Comment by clairew** [comment]
@justinsb Interested in checking this out - mind telling me how I can replicate this? Thanks

**Comment by b1zzu** [comment]
Hi @justinsb, I have tried to reproduce this bug on the latest version ( v1.9.9-beta.0 ):
```
$ bazel test //pkg/util/metrics/... --runs_per_test 200
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
......................
INFO: Analysed 4 targets (29 packages loaded).
INFO: Found 3 targets and 1 test target...
INFO: Elapsed time: 99.404s, Critical Path: 18.64s
INFO: 233 processes: 231 linux-sandbox, 2 local.
INFO: Build completed successfully, 237 total actions
//pkg/util/metrics:go_default_test                                       PASSED in 0.2s
  Stats over 200 runs: max = 0.2s, min = 0.1s, avg = 0.1s, dev = 0.0s

Executed 1 out of 1 test: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
```
but as you can see it works fine for me, do I have to do something else?

**Comment by nikhita** [comment]
Removing help wanted since directions are not clear on how to reproduce.

/remove-help
