### ISSUE TITLE
Memory leak in controller manager

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#55617]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

/kind bug

> /kind feature

**What happened**:

The controller manager consuming 4.6G memory in my environment.

```
top - 10:29:30 up 4 days, 21:13,  4 users,  load average: 6.77, 7.39, 7.48
Tasks:   1 total,   0 running,   1 sleeping,   0 stopped,   0 zombie
%Cpu(s): 85.5 us, 10.6 sy,  0.2 ni,  0.7 id,  2.0 wa,  0.0 hi,  1.0 si,  0.0 st
KiB Mem : 16170444 total,   275776 free, 11637004 used,  4257664 buff/cache
KiB Swap:  8388604 total,  5899216 free,  2489388 used.  3993476 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 7096 root      20   0 7265460 4.607g  15960 S  44.9 29.9 279:38.79 hyperkube
```

After gdb to controller manager, I found that it has 8 threads, but normally, I can see the controller manager often have 1 thread. Can someone help check in which case the controller manager can have many threads?

```
(gdb) info thread
  Id   Target Id         Frame
* 1    Thread 0x7f515fdf1700 (LWP 7096) "hyperkube" runtime.futex () at /usr/local/go/src/runtime/sys_linux_amd64.s:426
  2    Thread 0x7f515f3ea700 (LWP 7128) "hyperkube" runtime.futex () at /usr/local/go/src/runtime/sys_linux_amd64.s:426
  3    Thread 0x7f515ebe9700 (LWP 7129) "hyperkube" 0x00000000004127f0 in runtime.mallocgc (size=32, typ=0x0, needzero=false, ~r3=0xc494180128)
    at /usr/local/go/src/runtime/malloc.go:712
  4    Thread 0x7f515e3e8700 (LWP 7130) "hyperkube" runtime.futex () at /usr/local/go/src/runtime/sys_linux_amd64.s:426
  5    Thread 0x7f515d3a7700 (LWP 7133) "hyperkube" runtime.futex () at /usr/local/go/src/runtime/sys_linux_amd64.s:426
  6    Thread 0x7f515ca46700 (LWP 7140) "hyperkube" runtime.epollwait () at /usr/local/go/src/runtime/sys_linux_amd64.s:563
  7    Thread 0x7f5157fff700 (LWP 10180) "hyperkube" runtime.futex () at /usr/local/go/src/runtime/sys_linux_amd64.s:426
  8    Thread 0x7f51576be700 (LWP 18696) "hyperkube" runtime.futex () at /usr/local/go/src/runtime/sys_linux_amd64.s:426
  9    Thread 0x7f515658c700 (LWP 10293) "hyperkube" runtime.futex () at /usr/local/go/src/runtime/sys_linux_amd64.s:426
(gdb) t 1
[Switching to thread 1 (Thread 0x7f515fdf1700 (LWP 7096))]
#0  runtime.futex () at /usr/local/go/src/runtime/sys_linux_amd64.s:426
426	in /usr/local/go/src/runtime/sys_linux_amd64.s
(gdb) bt
#0  runtime.futex () at /usr/local/go/src/runtime/sys_linux_amd64.s:426
#1  0x000000000042b8e2 in runtime.futexsleep (addr=0x9335150 <runtime.m0+272>, val=0, ns=-1) at /usr/local/go/src/runtime/os_linux.go:45
#2  0x000000000041148b in runtime.notesleep (n=0x9335150 <runtime.m0+272>) at /usr/local/go/src/runtime/lock_futex.go:145
#3  0x000000000043372d in runtime.stopm () at /usr/local/go/src/runtime/proc.go:1650
#4  0x0000000000434544 in runtime.findrunnable (gp#10=0xc42001f300, inheritTime=false) at /usr/local/go/src/runtime/proc.go:2102
#5  0x00000000004350dc in runtime.schedule () at /usr/local/go/src/runtime/proc.go:2222
#6  0x00000000004353db in runtime.park_m (gp=0xc420753860) at /usr/local/go/src/runtime/proc.go:2285
#7  0x000000000045a5ab in runtime.mcall () at /usr/local/go/src/runtime/asm_amd64.s:269
#8  0x0000000009334900 in runtime.g0 ()
#9  0x00007ffcbd4d4eb0 in ?? ()
#10 0x00000000093348c0 in runtime.work ()
#11 0x00007ffcbd4d4ea0 in ?? ()
#12 0x00000000004326d4 in runtime.mstart () at /usr/local/go/src/runtime/proc.go:1149
#13 0x000000000045a419 in runtime.rt0_go () at /usr/local/go/src/runtime/asm_amd64.s:169
#14 0x000000000000000c in ?? ()
#15 0x00007ffcbd4d4fb8 in ?? ()
#16 0x000000000000000c in ?? ()
#17 0x00007ffcbd4d4fb8 in ?? ()
#18 0x0000000000000000 in ?? ()
(gdb) t2
Undefined command: "t2".  Try "help".
(gdb) bt
#0  runtime.futex () at /usr/local/go/src/runtime/sys_linux_amd64.s:426
#1  0x000000000042b8e2 in runtime.futexsleep (addr=0x9335150 <runtime.m0+272>, val=0, ns=-1) at /usr/local/go/src/runtime/os_linux.go:45
#2  0x000000000041148b in runtime.notesleep (n=0x9335150 <runtime.m0+272>) at /usr/local/go/src/runtime/lock_futex.go:145
#3  0x000000000043372d in runtime.stopm () at /usr/local/go/src/runtime/proc.go:1650
#4  0x0000000000434544 in runtime.findrunnable (gp#10=0xc42001f300, inheritTime=false) at /usr/local/go/src/runtime/proc.go:2102
#5  0x00000000004350dc in runtime.schedule () at /usr/local/go/src/runtime/proc.go:2222
#6  0x00000000004353db in runtime.park_m (gp=0xc420753860) at /usr/local/go/src/runtime/proc.go:2285
#7  0x000000000045a5ab in runtime.mcall () at /usr/local/go/src/runtime/asm_amd64.s:269
#8  0x0000000009334900 in runtime.g0 ()
#9  0x00007ffcbd4d4eb0 in ?? ()
#10 0x00000000093348c0 in runtime.work ()
#11 0x00007ffcbd4d4ea0 in ?? ()
#12 0x00000000004326d4 in runtime.mstart () at /usr/local/go/src/runtime/proc.go:1149
#13 0x000000000045a419 in runtime.rt0_go () at /usr/local/go/src/runtime/asm_amd64.s:169
#14 0x000000000000000c in ?? ()
#15 0x00007ffcbd4d4fb8 in ?? ()
#16 0x000000000000000c in ?? ()
#17 0x00007ffcbd4d4fb8 in ?? ()
#18 0x0000000000000000 in ?? ()
(gdb) t 3
[Switching to thread 3 (Thread 0x7f515ebe9700 (LWP 7129))]
#0  0x00000000004127f0 in runtime.mallocgc (size=32, typ=0x0, needzero=false, ~r3=0xc494180128) at /usr/local/go/src/runtime/malloc.go:712
712	/usr/local/go/src/runtime/malloc.go: No such file or directory.
(gdb) bt
#0  0x00000000004127f0 in runtime.mallocgc (size=32, typ=0x0, needzero=false, ~r3=0xc494180128) at /usr/local/go/src/runtime/malloc.go:712
#1  0x0000000000448835 in runtime.rawstring (size=17, s=..., b=...) at /usr/local/go/src/runtime/string.go:237
#2  0x0000000000448208 in runtime.rawstringtmp (buf=0x0, l=17, s=..., b=...) at /usr/local/go/src/runtime/string.go:107
#3  0x0000000000447d19 in runtime.concatstrings (buf=0x0, a=..., ~r2=...) at /usr/local/go/src/runtime/string.go:46
#4  0x0000000000447f97 in runtime.concatstring3 (buf=0x0, a=..., ~r2=...) at /usr/local/go/src/runtime/string.go:59
#5  0x00000000005cba7b in net.JoinHostPort (host=..., port=..., ~r2=...) at /usr/local/go/src/net/ipsock.go:191
#6  0x00000000008a775d in k8s.io/kubernetes/vendor/golang.org/x/net/http2.authorityAddr (scheme=..., authority=..., addr=...)
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:322
#7  0x00000000008a79b1 in k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).RoundTripOpt (t=0xc420ea77c0, req=0xc5762c4300, opt=..., ~r2=0xffffffffffffffff,
    ~r3=...) at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:331
#8  0x00000000008a75a0 in k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*Transport).RoundTrip (t=0xc420ea77c0, req=0xc5762c4300,
    ~r1=0x81d5f34 <runtime.pclntab+19757044>, ~r2=...) at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:301
#9  0x000000000088bfe9 in k8s.io/kubernetes/vendor/golang.org/x/net/http2.noDialH2RoundTripper.RoundTrip (rt=..., req=0xc5762c4300, ~r1=0xc534d81080, ~r2=...)
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/configure_transport.go:75
#10 0x0000000000751679 in net/http.(*Transport).RoundTrip (t=0xc42022f680, req=0xc5762c4300, ~r1=0xa, ~r2=...) at /usr/local/go/src/net/http/transport.go:349
#11 0x0000000000eb588c in k8s.io/kubernetes/vendor/k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip (rt=0xc420ef5ee0, req=0xc5762c4300, ~r1=0xc420ef5ee0,
    ~r2=...) at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/transport/round_trippers.go:162
#12 0x00000000006fb8c2 in net/http.send (ireq=0xc5762c4200, rt=..., deadline=..., resp=0x0, didTimeout={void (bool *)} 0xc420e1cc88, err=...)
    at /usr/local/go/src/net/http/client.go:249
#13 0x00000000006fb548 in net/http.(*Client).send (c=0xc420ef7650, req=0xc5762c4200, deadline=..., resp=0xc4325632f8, didTimeout={void (bool *)} 0xc420e1cd00, err=...)
    at /usr/local/go/src/net/http/client.go:173
#14 0x00000000006fcbe4 in net/http.(*Client).Do (c=0xc420ef7650, req=0xc5762c4200, ~r1=0x0, ~r2=...) at /usr/local/go/src/net/http/client.go:595
#15 0x0000000000ec1ded in k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Request).request (r=0xc50320db00, fn=
    {void (struct net/http.Request *, struct net/http.Response *)} 0xc420e1cf48, ~r1=...)
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:821
#16 0x0000000000ec26d0 in k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Request).Do (r=0xc50320db00, ~r0=...)
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:895
#17 0x0000000001e4e721 in k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/core/v1.(*endpoints).Get (c=0xc58070d3c0, name=..., options=...,
    result=0x19ca0a9b, err=...)
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/clientset_generated/clientset/typed/core/v1/endpoints.go:116
#18 0x0000000001e8fa93 in k8s.io/kubernetes/pkg/client/leaderelection/resourcelock.(*EndpointsLock).Get (el=0xc420f4fd40, ~r0=0xc4203b1180, ~r1=...)
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/leaderelection/resourcelock/endpointslock.go:42
#19 0x0000000002fbf716 in k8s.io/kubernetes/pkg/client/leaderelection.(*LeaderElector).tryAcquireOrRenew (le=0xc420103d40, ~r0=true)
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go:226
#20 0x0000000002fc058a in k8s.io/kubernetes/pkg/client/leaderelection.(*LeaderElector).renew.func1.1 (~r0=160, ~r1=...)
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go:199
#21 0x000000000050e3f0 in k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.WaitFor (wait={void (<-chan struct {}, <-chan struct {} *)} 0xc420e1d410, fn=
    {void (bool *, error *)} 0xc420e1d418, done=0xc534d803c0, ~r3=...)
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:275
#22 0x000000000050e099 in k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.pollInternal (wait={void (<-chan struct {}, <-chan struct {} *)} 0xc420e1d450,
    condition={void (bool *, error *)} 0xc420e1d458, ~r2=...)
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:191
#23 0x000000000050dfcd in k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Poll (interval=2000000000, timeout=10000000000, condition=
    {void (bool *, error *)} 0xc420e1d490, ~r3=...)
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185
---Type <return> to continue, or q <return> to quit---
#24 0x0000000002fc063b in k8s.io/kubernetes/pkg/client/leaderelection.(*LeaderElector).renew.func1 ()
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go:200
#25 0x000000000050e61e in k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1 (f={void (void)} 0xc420e1d578)
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
#26 0x000000000050dc0d in k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil (f={void (void)} 0xc420e1d648, period=0, jitterFactor=0, sliding=true,
    stopCh=0xc420015f20) at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98
#27 0x000000000050dadd in k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until (f={void (void)} 0xc420e1d680, period=0, stopCh=0xc420015f20)
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
#28 0x0000000002fbf5db in k8s.io/kubernetes/pkg/client/leaderelection.(*LeaderElector).renew (le=0xc420103d40)
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go:210
#29 0x0000000002fbf2f5 in k8s.io/kubernetes/pkg/client/leaderelection.(*LeaderElector).Run (le=0xc420103d40)
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go:151
#30 0x0000000002fbf38a in k8s.io/kubernetes/pkg/client/leaderelection.RunOrDie (lec=...)
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go:162
#31 0x0000000003675c39 in k8s.io/kubernetes/cmd/kube-controller-manager/app.Run (s=0xc420091500, ~r1=...)
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:222
#32 0x0000000003d0ee5a in main.NewKubeControllerManager.func1 (args=..., ~r2=...)
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/hyperkube/kube-controller-manager.go:35
#33 0x0000000003d0c09c in main.(*HyperKube).Run (hk=0xc420604780, args=..., ~r1=...)
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/hyperkube/hyperkube.go:177
#34 0x0000000003d0c649 in main.(*HyperKube).RunToExit (hk=0xc420604780, args=...)
    at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/hyperkube/hyperkube.go:187
#35 0x0000000003d0e177 in main.main () at /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/hyperkube/main.go:47
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Not sure, but I can 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mml** [comment]
Might be a dup of #52657.  cc @cheftako @jennybuckley

**Comment by gyliu513** [comment]
But in my env, there are not too many pods and also no cron job. Can you please show more detail to me for what actions will trigger the controller manager have multiple threads? @mm0 @cheftako
