### ISSUE TITLE
fluentd-gcp crashing because of `JournalError: Bad message`

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#55725]
This happened in a 1.6 test: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-serial-release-1-6/929

fluentd crashed/restarted ~40 times during the test because it could not handle the bad message in journal.
```
2017-11-14 15:40:52 +0000 [error]: unexpected error error_class=Systemd::JournalError error=#<Systemd::JournalError: Bad message>
  2017-11-14 15:40:52 +0000 [error]: /var/lib/gems/2.1.0/gems/systemd-journal-1.2.3/lib/systemd/journal.rb:284:in `enumerate_helper'
  2017-11-14 15:40:52 +0000 [error]: /var/lib/gems/2.1.0/gems/systemd-journal-1.2.3/lib/systemd/journal.rb:106:in `current_entry'
  2017-11-14 15:40:52 +0000 [error]: /var/lib/gems/2.1.0/gems/fluent-plugin-systemd-0.0.8/lib/fluent/plugin/in_systemd.rb:88:in `watch'
  2017-11-14 15:40:52 +0000 [error]: /var/lib/gems/2.1.0/gems/fluent-plugin-systemd-0.0.8/lib/fluent/plugin/in_systemd.rb:70:in `run'
2017-11-14 15:40:52 +0000 [info]: shutting down fluentd
```

This issue fixed in fluentd-0.14.x according to https://github.com/reevoo/fluent-plugin-systemd/issues/16
Not sure if the latest fluentd-gcp image contains the fix or not.

/cc @crassirostris

**Comment by yujuhong** [comment]
I'm seeing crashing fluentd-gcp pods in other branches too, but since fluentd became DaemonSet, the logs are no longer archived with the logs.
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-serial-stable1/930

**Comment by QSonx** [comment]
Had this problem today on 3 of my 6 nodes.

Node version 1.8.4-gke.0
fluentd: gcr.io/google-containers/fluentd-gcp:2.0.9

```
2017-12-12 18:43:50 +0000 [warn]: 'block' action stops input process until the buffer full is resolved. Check your pipeline this action is fit or not
2017-12-12 18:43:50 +0000 [warn]: 'block' action stops input process until the buffer full is resolved. Check your pipeline this action is fit or not
2017-12-12 18:43:51 +0000 [error]: unexpected error error_class=Systemd::JournalError error=#<Systemd::JournalError: Bad message>
  2017-12-12 18:43:51 +0000 [error]: /var/lib/gems/2.1.0/gems/systemd-journal-1.3.0/lib/systemd/journal.rb:300:in `enumerate_helper'
  2017-12-12 18:43:51 +0000 [error]: /var/lib/gems/2.1.0/gems/systemd-journal-1.3.0/lib/systemd/journal.rb:106:in `current_entry'
  2017-12-12 18:43:51 +0000 [error]: /var/lib/gems/2.1.0/gems/fluent-plugin-systemd-0.0.8/lib/fluent/plugin/in_systemd.rb:88:in `watch'
  2017-12-12 18:43:51 +0000 [error]: /var/lib/gems/2.1.0/gems/fluent-plugin-systemd-0.0.8/lib/fluent/plugin/in_systemd.rb:70:in `run'
2017-12-12 18:43:51 +0000 [warn]: unexpected error while shutting down input plugin plugin=Fluent::SystemdInput plugin_id="object:3f9d8556d5e4" error_class=Systemd::JournalError error=#<Systemd::JournalError: Bad message>
  2017-12-12 18:43:51 +0000 [warn]: /var/lib/gems/2.1.0/gems/systemd-journal-1.3.0/lib/systemd/journal.rb:300:in `enumerate_helper'
  2017-12-12 18:43:51 +0000 [warn]: /var/lib/gems/2.1.0/gems/systemd-journal-1.3.0/lib/systemd/journal.rb:106:in `current_entry'
  2017-12-12 18:43:51 +0000 [warn]: /var/lib/gems/2.1.0/gems/fluent-plugin-systemd-0.0.8/lib/fluent/plugin/in_systemd.rb:88:in `watch'
  2017-12-12 18:43:51 +0000 [warn]: /var/lib/gems/2.1.0/gems/fluent-plugin-systemd-0.0.8/lib/fluent/plugin/in_systemd.rb:70:in `run'
```

**Comment by michaelmitchell** [comment]
Seeing the same thing

Node version 1.8.6-gke.0
fluentd image: gcr.io/google-containers/fluentd-gcp:2.0.9

**Comment by yujuhong** [comment]
@kubernetes/sig-instrumentation-bugs @piosz is this fixed already?

**Comment by piosz** [comment]
@bmoyles0117 PTAL

**Comment by yujuhong** [comment]
@piosz could you confirm whether this is fixed or not? Thanks

**Comment by loburm** [comment]
I believe this issue was fixed long time ago.

/assign @bmoyles0117 could you confirm it?

**Comment by bmoyles0117** [comment]
This issue should be fixed in the latest version of the container images. I believe we're at 3.*.* at this point.

**Comment by rexagod** [comment]
/close

Feel free to reopen if this is still exhibited.
