### ISSUE TITLE
pkg/registry/storage/storageclass/storage unit test failed

### ISSUE THREAD

**Issue by jingax10** [kubernetes/kubernetes#56134]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

pkg/registry/storage/storageclass/storage test failed

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

make test WHAT=./pkg/registry/storage/storageclass/storage

Running tests for APIVersion: v1,admissionregistration.k8s.io/v1alpha1,admission.k8s.io/v1alpha1,apps/v1beta1,apps/v1beta2,apps/v1,authentication.k8s.io/v1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1,authorization.k8s.io/v1beta1,autoscaling/v1,autoscaling/v2beta1,batch/v1,batch/v1beta1,batch/v2alpha1,certificates.k8s.io/v1beta1,extensions/v1beta1,imagepolicy.k8s.io/v1alpha1,networking.k8s.io/v1,policy/v1beta1,rbac.authorization.k8s.io/v1,rbac.authorization.k8s.io/v1beta1,rbac.authorization.k8s.io/v1alpha1,scheduling.k8s.io/v1alpha1,settings.k8s.io/v1alpha1,storage.k8s.io/v1alpha1,storage.k8s.io/v1beta1,storage.k8s.io/v1,
+++ [1120 22:11:29] Running tests without code coverage
2017-11-20 22:11:32.694382 I | integration: launching 350357350691360349 (unix://localhost:3503573506913603490)
2017-11-20 22:11:32.697180 I | etcdserver: name = 350357350691360349
2017-11-20 22:11:32.697191 I | etcdserver: data dir = /tmp/etcd150364170
2017-11-20 22:11:32.697195 I | etcdserver: member dir = /tmp/etcd150364170/member
2017-11-20 22:11:32.697197 I | etcdserver: heartbeat = 10ms
2017-11-20 22:11:32.697200 I | etcdserver: election = 100ms
2017-11-20 22:11:32.697202 I | etcdserver: snapshot count = 0
2017-11-20 22:11:32.697208 I | etcdserver: advertise client URLs = unix://127.0.0.1:21002144510
2017-11-20 22:11:32.697211 I | etcdserver: initial advertise peer URLs = unix://127.0.0.1:21001144510
2017-11-20 22:11:32.697218 I | etcdserver: initial cluster = 350357350691360349=unix://127.0.0.1:21001144510
2017-11-20 22:11:32.714064 I | etcdserver: starting member 51e9ef4a860d9569 in cluster 798d22d3d1aa1aa9
2017-11-20 22:11:32.714096 I | raft: 51e9ef4a860d9569 became follower at term 0
2017-11-20 22:11:32.714107 I | raft: newRaft 51e9ef4a860d9569 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2017-11-20 22:11:32.714112 I | raft: 51e9ef4a860d9569 became follower at term 1
2017-11-20 22:11:32.728842 I | etcdserver: set snapshot count to default 10000
2017-11-20 22:11:32.728865 I | etcdserver: starting server... [version: 3.1.10, cluster version: to_be_decided]
2017-11-20 22:11:32.729177 I | etcdserver/membership: added member 51e9ef4a860d9569 [unix://127.0.0.1:21001144510] to cluster 798d22d3d1aa1aa9
2017-11-20 22:11:32.729192 I | integration: launched 350357350691360349 (unix://localhost:3503573506913603490)
2017-11-20 22:11:32.804415 I | raft: 51e9ef4a860d9569 is starting a new election at term 1
2017-11-20 22:11:32.804525 I | raft: 51e9ef4a860d9569 became candidate at term 2
2017-11-20 22:11:32.804545 I | raft: 51e9ef4a860d9569 received MsgVoteResp from 51e9ef4a860d9569 at term 2
2017-11-20 22:11:32.804564 I | raft: 51e9ef4a860d9569 became leader at term 2
2017-11-20 22:11:32.804579 I | raft: raft.node: 51e9ef4a860d9569 elected leader 51e9ef4a860d9569 at term 2
2017-11-20 22:11:32.804846 I | etcdserver: published {Name:350357350691360349 ClientURLs:[unix://127.0.0.1:21002144510]} to cluster 798d22d3d1aa1aa9
2017-11-20 22:11:32.804873 I | etcdserver: setting up the initial cluster version to 3.1
2017-11-20 22:11:32.805945 N | etcdserver/membership: set the initial cluster version to 3.1
2017-11-20 22:11:32.805977 I | etcdserver/api: enabled capabilities for version 3.1
2017-11-20 22:11:32.814300 I | integration: terminating 350357350691360349 (unix://localhost:3503573506913603490)
2017-11-20 22:11:32.818001 I | integration: terminated 350357350691360349 (unix://localhost:3503573506913603490)
--- FAIL: TestCreate (0.12s)
	resttest.go:318: Unexpected error: no kind "StorageClass" is registered for version "storage.k8s.io/v1alpha1"
2017-11-20 22:11:32.818476 I | integration: launching 6568308720082957755 (unix://localhost:65683087200829577550)
2017-11-20 22:11:32.821789 I | etcdserver: name = 6568308720082957755
2017-11-20 22:11:32.821813 I | etcdserver: data dir = /tmp/etcd844266977
2017-11-20 22:11:32.821822 I | etcdserver: member dir = /tmp/etcd844266977/member
2017-11-20 22:11:32.821828 I | etcdserver: heartbeat = 10ms
2017-11-20 22:11:32.821834 I | etcdserver: election = 100ms
2017-11-20 22:11:32.821839 I | etcdserver: snapshot count = 0
2017-11-20 22:11:32.821849 I | etcdserver: advertise client URLs = unix://127.0.0.1:21004144510
2017-11-20 22:11:32.821856 I | etcdserver: initial advertise peer URLs = unix://127.0.0.1:21003144510
2017-11-20 22:11:32.821876 I | etcdserver: initial cluster = 6568308720082957755=unix://127.0.0.1:21003144510
2017-11-20 22:11:32.827313 I | etcdserver: starting member ed1d41d3ffb24ed3 in cluster 1bb8c328abbbfd78
2017-11-20 22:11:32.827346 I | raft: ed1d41d3ffb24ed3 became follower at term 0
2017-11-20 22:11:32.827360 I | raft: newRaft ed1d41d3ffb24ed3 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2017-11-20 22:11:32.827368 I | raft: ed1d41d3ffb24ed3 became follower at term 1
2017-11-20 22:11:32.843212 I | etcdserver: set snapshot count to default 10000
2017-11-20 22:11:32.843270 I | etcdserver: starting server... [version: 3.1.10, cluster version: to_be_decided]
2017-11-20 22:11:32.843652 I | etcdserver/membership: added member ed1d41d3ffb24ed3 [unix://127.0.0.1:21003144510] to cluster 1bb8c328abbbfd78
2017-11-20 22:11:32.843707 I | integration: launched 6568308720082957755 (unix://localhost:65683087200829577550)
2017-11-20 22:11:32.877742 I | raft: ed1d41d3ffb24ed3 is starting a new election at term 1
2017-11-20 22:11:32.877776 I | raft: ed1d41d3ffb24ed3 became candidate at term 2
2017-11-20 22:11:32.877805 I | raft: ed1d41d3ffb24ed3 received MsgVoteResp from ed1d41d3ffb24ed3 at term 2
2017-11-20 22:11:32.877826 I | raft: ed1d41d3ffb24ed3 became leader at term 2
2017-11-20 22:11:32.877845 I | raft: raft.node: ed1d41d3ffb24ed3 elected leader ed1d41d3ffb24ed3 at term 2
2017-11-20 22:11:32.878039 I | etcdserver: setting up the initial cluster version to 3.1
2017-11-20 22:11:32.879399 N | etcdserver/membership: set the initial cluster version to 3.1
2017-11-20 22:11:32.879463 I | etcdserver: published {Name:6568308720082957755 ClientURLs:[unix://127.0.0.1:21004144510]} to cluster 1bb8c328abbbfd78
2017-11-20 22:11:32.887794 I | integration: terminating 6568308720082957755 (unix://localhost:65683087200829577550)
2017-11-20 22:11:32.891519 I | integration: terminated 6568308720082957755 (unix://localhost:65683087200829577550)
--- FAIL: TestUpdate (0.07s)
	resttest.go:456: unexpected error: no kind "StorageClass" is registered for version "storage.k8s.io/v1alpha1"
	resttest.go:461: unexpected error: storageclasses.storage.k8s.io "foo2" not found
panic: interface conversion: runtime.Object is nil, not *storage.StorageClass [recovered]
	panic: interface conversion: runtime.Object is nil, not *storage.StorageClass

goroutine 213 [running]:
testing.tRunner.func1(0xc420ca0000)
	/usr/lib/google-golang/src/testing/testing.go:711 +0x2d2
panic(0x1661b00, 0xc4200ccf00)
	/usr/lib/google-golang/src/runtime/panic.go:491 +0x283
k8s.io/kubernetes/pkg/registry/storage/storageclass/storage.TestUpdate.func1(0x0, 0x0, 0x14, 0xc420bafdb8)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/storage/storageclass/storage/storage_test.go:93 +0x147
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/rest/resttest.(*Tester).testUpdateEquals(0xc42028a7e0, 0x22e6aa0, 0xc420288580, 0xc42062fee8, 0xc4202803e0, 0x18daca0)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/rest/resttest/resttest.go:463 +0x2bd
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/rest/resttest.(*Tester).TestUpdate(0xc42028a7e0, 0x22e6aa0, 0xc420288420, 0xc420bafee8, 0xc4202803e0, 0x18daca0, 0xc42000e208, 0x1, 0x1)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/rest/resttest/resttest.go:162 +0x61
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/testing.(*Tester).TestUpdate(0xc4202803c0, 0x22e6aa0, 0xc420288420, 0x18daca0, 0xc42062ff88, 0x1, 0x1)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/testing/tester.go:92 +0x209
k8s.io/kubernetes/pkg/registry/storage/storageclass/storage.TestUpdate(0xc420ca0000)
	/usr/local/google/home/jinga/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/storage/storageclass/storage/storage_test.go:88 +0x33a
testing.tRunner(0xc420ca0000, 0x18dacb0)
	/usr/lib/google-golang/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/lib/google-golang/src/testing/testing.go:789 +0x2de
FAIL	k8s.io/kubernetes/pkg/registry/storage/storageclass/storage	0.410s
make: *** [test] Error 1

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): head
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
go version go1.9.2 linux/amd64

**Comment by jingax10** [comment]
@kubernetes/sig-storage

**Comment by jingax10** [comment]
Thanks edisonxiang@! It is a dup of #56136. I will close it.

/close

**Comment by CaoShuFeng** [comment]
#56136 is a pull request.
This is an issue.
So this is not a dup.

/assign

**Comment by CaoShuFeng** [comment]
#56136 is merged.
So we can close this officially now.
@jingax10 Thanks.

**Comment by jingax10** [comment]
Thanks @CaoShuFeng!

/close
