### ISSUE TITLE
apiserver panic when call endpoints API.

### ISSUE THREAD

**Issue by hchenxa** [kubernetes/kubernetes#56278]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
> 
/kind bug
> /kind feature

**What happened**:
apiserver panic'd on GET /api/v1/endpoints
```
I1123 07:12:56.702335       1 wrap.go:42] GET /api/v1/services?resourceVersion=0: (37.619665188s) 200 [[hyperkube/v1.8.2 (linux/amd64) kubernetes/ad4d771] 10.29.97.1:58748]
E1123 07:12:56.702458       1 runtime.go:66] Observed a panic: &errors.errorString{s:"kill connection/stream"} (kill connection/stream)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:514
/usr/local/go/src/runtime/panic.go:489
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:230
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:114
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:45
/usr/local/go/src/net/http/server.go:1942
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110
/usr/local/go/src/net/http/server.go:1942
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41
/usr/local/go/src/net/http/server.go:1942
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:198
/usr/local/go/src/net/http/server.go:2568
/usr/local/go/src/net/http/server.go:3088
<autogenerated>:312
/usr/local/go/src/net/http/h2_bundle.go:4331
/usr/local/go/src/net/http/h2_bundle.go:4611
/usr/local/go/src/runtime/asm_amd64.s:2197
E1123 07:12:56.702846       1 wrap.go:34] APIServer panic'd on GET /api/v1/endpoints?resourceVersion=0: kill connection/stream
goroutine 17455 [running]:
runtime/debug.Stack(0x9afdec0, 0xc4296f72d0, 0x49e85e1)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1.1(0x3f93140, 0xc420367fe0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:34 +0x74
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc5912dfcd8, 0x1, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:54 +0xe5
panic(0x3f93140, 0xc420367fe0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc4251608a0, 0xc433f9eab0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:230 +0x182
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc42c138fe0, 0x9afdec0, 0xc4296f72d0, 0xc433863400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:114 +0x28c
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x9afdec0, 0xc4296f72d0, 0xc433863400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:45 +0x219
net/http.HandlerFunc.ServeHTTP(0xc428707540, 0x9afdec0, 0xc4296f72d0, 0xc433863400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x9afdec0, 0xc4296f72d0, 0xc433863400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xef
net/http.HandlerFunc.ServeHTTP(0xc42c139000, 0x9afdec0, 0xc4296f72d0, 0xc433863400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0x9afdec0, 0xc4296f72d0, 0xc433863400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41 +0x11b
net/http.HandlerFunc.ServeHTTP(0xc42c139020, 0x9aff0c0, 0xc4362a0170, 0xc433863400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc42f4435f0, 0x9aff0c0, 0xc4362a0170, 0xc433863400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:198 +0x51
net/http.serverHandler.ServeHTTP(0xc435f9a370, 0x9aff0c0, 0xc4362a0170, 0xc433863400)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.initNPNRequest.ServeHTTP(0xc4348b1500, 0xc435f9a370, 0x9aff0c0, 0xc4362a0170, 0xc433863400)
	/usr/local/go/src/net/http/server.go:3088 +0x93
net/http.(*initNPNRequest).ServeHTTP(0xc42bf45530, 0x9aff0c0, 0xc4362a0170, 0xc433863400)
	<autogenerated>:312 +0x74
net/http.(Handler).ServeHTTP-fm(0x9aff0c0, 0xc4362a0170, 0xc433863400)
	/usr/local/go/src/net/http/h2_bundle.go:4331 +0x4d
net/http.(*http2serverConn).runHandler(0xc4257a1c00, 0xc4362a0170, 0xc433863400, 0xc429ab1120)
	/usr/local/go/src/net/http/h2_bundle.go:4611 +0x89
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:4343 +0x4ac

I1123 07:12:56.703041       1 logs.go:41] http2: panic serving 10.29.97.1:58748: kill connection/stream
goroutine 17455 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc4362a0170, 0xc5912dffaf, 0xc4257a1c00)
	/usr/local/go/src/net/http/h2_bundle.go:4604 +0x190
panic(0x3f93140, 0xc420367fe0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc5912dfcd8, 0x1, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x3f93140, 0xc420367fe0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc4251608a0, 0xc433f9eab0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:230 +0x182
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc42c138fe0, 0x9afdec0, 0xc4296f72d0, 0xc433863400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:114 +0x28c
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x9afdec0, 0xc4296f72d0, 0xc433863400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:45 +0x219
net/http.HandlerFunc.ServeHTTP(0xc428707540, 0x9afdec0, 0xc4296f72d0, 0xc433863400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x9afdec0, 0xc4296f72d0, 0xc433863400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xef
net/http.HandlerFunc.ServeHTTP(0xc42c139000, 0x9afdec0, 0xc4296f72d0, 0xc433863400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0x9afdec0, 0xc4296f72d0, 0xc433863400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41 +0x11b
net/http.HandlerFunc.ServeHTTP(0xc42c139020, 0x9aff0c0, 0xc4362a0170, 0xc433863400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc42f4435f0, 0x9aff0c0, 0xc4362a0170, 0xc433863400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:198 +0x51
net/http.serverHandler.ServeHTTP(0xc435f9a370, 0x9aff0c0, 0xc4362a0170, 0xc433863400)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.initNPNRequest.ServeHTTP(0xc4348b1500, 0xc435f9a370, 0x9aff0c0, 0xc4362a0170, 0xc433863400)
	/usr/local/go/src/net/http/server.go:3088 +0x93
net/http.(*initNPNRequest).ServeHTTP(0xc42bf45530, 0x9aff0c0, 0xc4362a0170, 0xc433863400)
	<autogenerated>:312 +0x74
net/http.(Handler).ServeHTTP-fm(0x9aff0c0, 0xc4362a0170, 0xc433863400)
	/usr/local/go/src/net/http/h2_bundle.go:4331 +0x4d
net/http.(*http2serverConn).runHandler(0xc4257a1c00, 0xc4362a0170, 0xc433863400, 0xc429ab1120)
	/usr/local/go/src/net/http/h2_bundle.go:4611 +0x89
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:4343 +0x4ac
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
here is my apiserver startup parameters:
```
/hyperkube apiserver --secure-port=8001 --bind-address=0.0.0.0 --advertise-address=10.29.67.72 --insecure-port=8888 --insecure-bind-address=127.0.0.1 --etcd-servers=https://10.29.67.72:4001 --etcd-cafile=/etc/cfc/conf/etcd/ca.pem --etcd-certfile=/etc/cfc/conf/etcd/client.pem --etcd-keyfile=/etc/cfc/conf/etcd/client-key.pem --runtime-config=batch/v2alpha1,extensions/v1beta1=true,extensions/v1beta1/podsecuritypolicy=true,admissionregistration.k8s.io/v1alpha1 --admission-control=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,PodSecurityPolicy,DefaultTolerationSeconds,ResourceQuota --oidc-issuer-url=https://mycluster.icp:9443/oidc/endpoint/OP --oidc-client-id=50c8d17edeb4949f3caefc1404c146d6 --oidc-ca-file=/etc/cfc/conf/platformauth-ca.crt --max-requests-inflight=1000 --max-mutating-requests-inflight=1000 --deserialization-cache-size=1000 --target-ram-mb=10000 --feature-gates=PersistentLocalVolumes=true --oidc-groups-claim=sub --tls-cert-file=/etc/cfc/conf/server.cert --tls-private-key-file=/etc/cfc/conf/server.key --kubelet-client-certificate=/etc/cfc/conf/kubelet-client.crt --kubelet-client-key=/etc/cfc/conf/kubelet-client.key --client-ca-file=/etc/cfc/conf/ca.crt --service-account-key-file=/etc/cfc/conf/server.key --authorization-mode=RBAC --min-request-timeout=300 --allow-privileged --requestheader-client-ca-file=/etc/cfc/conf/front/front-proxy-ca.pem --requestheader-username-headers=X-Remote-User --requestheader-group-headers=X-Remote-Group --requestheader-allowed-names=mycluster.icp --requestheader-extra-headers-prefix=X-Remote-Extra- --proxy-client-cert-file=/etc/cfc/conf/front/front-proxy-client.pem --proxy-client-key-file=/etc/cfc/conf/front/front-proxy-client-key.pem --v=2 --service-cluster-ip-range=10.0.0.1/24
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
ubuntu
- Kernel (e.g. `uname -a`):
4.4.0-93-generic
- Install tools:
- Others:

**Comment by liggitt** [comment]
that panic is how request timeouts are handled internally. are other APIs working properly?

**Comment by hzxuzhonghu** [comment]
Yes, the default timeout is 60s.

**Comment by liggitt** [comment]
Possible the fix in https://github.com/kubernetes/kubernetes/pull/49688 resolved this. What apiserver version are you running?

**Comment by xialonglee** [comment]
Meet the similar situation too.
```
I0214 21:08:58.040763   89632 logs.go:41] http2: panic serving 172.168.200.32:43508: kill connection/stream
goroutine 91118316 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc422217cb0, 0xc4226e7f7f, 0xc423ff7d40)
	/usr/local/go/src/net/http/h2_bundle.go:4304 +0xd1
panic(0x2c942e0, 0xc420265c10)
	/usr/local/go/src/runtime/panic.go:458 +0x243
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc4221c78c0, 0xc426419c00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:214 +0x187
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc420adccc0, 0x5531700, 0xc422217cb0, 0xc42314a960)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:98 +0x28c
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x5531700, 0xc422217cb0, 0xc42314a960)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:95 +0x197
net/http.HandlerFunc.ServeHTTP(0xc42009afc0, 0x5531700, 0xc422217cb0, 0xc42314a960)
	/usr/local/go/src/net/http/server.go:1726 +0x44
```
The cluster is not in a large scale, which means the resources date stored in etcd should not be very large for client retrieve from and should not result in a very long time to retrieve.
Seems like is the IO problem that would cause this situation, which means that the response data from etcd are transferred very slowly?

**Comment by hzxuzhonghu** [comment]
@xialonglee  can you paste some normal apiserver log? want to see how long it takes for one request in your cluster.

**Comment by xialonglee** [comment]
@hzxuzhonghu 
the whole log are too long to paste here..
and from the log of `apiserver` side, i can't see the point when the request start

and when the panic occur the `kubelet` was requesting something from `apiserver` 
we can see when the panic occur from `apiserver` side, the `kubelet` side receive error and mount volume failed: 

```
E0217 04:33:53.329869   27689 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/secret/7169775f-0cca-11e8-9319-fa163e9a0184-default-token-q54rp\" (\"7169775f-0cca-11e8-9319-fa163e9a0184\")" failed. No retries permitted until 2018-02-17 04:33:53.829836988 +0800 CST (durationBeforeRetry 500ms). Error: MountVolume.SetUp failed for volume "kubernetes.io/secret/7169775f-0cca-11e8-9319-fa163e9a0184-default-token-q54rp" (spec.Name: "default-token-q54rp") pod "7169775f-0cca-11e8-9319-fa163e9a0184" (UID: "7169775f-0cca-11e8-9319-fa163e9a0184") with: the server cannot complete the requested operation at this time, try again later (get secrets default-token-q54rp)
```
but I didn't keep the whole complete log of `kubelet`, so i can't get the time when `kubelet` start requsting now ...

and this situation continues several days and recovered now, so i doubt that the reason is the IO problem or something related to cpu/memory performance which cause etcd react slowly.

**Comment by xialonglee** [comment]
I check the relate codes too.
If i am not missing something, this panic only occurs when `apiserver` establish connection with etcd.
`apiserver` send a request to etcd and etcd response to apiserver, the header of response was filled up, but because of the data are too large to filled complete in time or the network transferred are too slowly or the data transfer improper ending will cause this panic

**Comment by hzxuzhonghu** [comment]
I mean something like this `I0301 11:45:53.307853   56515 wrap.go:42] GET /api/v1/namespaces/default/services/kubernetes: (3.034548ms) 404 [[hyperkube/v1.10.0 (linux/amd64) kubernetes/3ca89a3] 127.0.0.1:42557]`

**Comment by xialonglee** [comment]
@hzxuzhonghu 
you mean log like this?
```
[761.898µs] [3.88µs] About to store object in database
"Update /api/v1/namespaces/kube-system/endpoints/kube-controller-manager" [30.001069869s] [30.000307971s] END
I0214 21:08:58.040763   89632 logs.go:41] http2: panic serving 172.168.200.32:43508: kill connection/stream
goroutine 91118316 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc422217cb0, 0xc4226e7f7f, 0xc423ff7d40)
	/usr/local/go/src/net/http/h2_bundle.go:4304 +0xd1
```

```
I0214 21:09:01.749811   89632 trace.go:61] Trace "Get /api/v1/namespaces/kube-system/endpoints/kube-controller-manager" (started 2018-02-14 21:08:58.04192275 +0800 CST):
"Get /api/v1/namespaces/kube-system/endpoints/kube-controller-manager" [3.707836016s] [3.707836016s] END
I0214 21:09:17.874674   89632 logs.go:41] http2: panic serving 172.168.200.21:59990: kill connection/stream
goroutine 91118412 [running]:
```

```
[24.73805491s] [9.198µs] Self-link added
"Update /api/v1/namespaces/iot/pods/965cb0c1-0e16-40af-9300-d83bf3e7022f-1-zhnpt/status" [24.738177416s] [122.506µs] END
I0214 21:21:57.690791   89632 logs.go:41] http2: panic serving 172.168.200.21:59990: kill connection/stream
goroutine 91139565 [running]:
```

**Comment by hzxuzhonghu** [comment]
check with this https://github.com/kubernetes/kubernetes/issues/56278#issuecomment-360991788
