### ISSUE TITLE
17-minute node LIST operation in gci-gce-scalability

### ISSUE THREAD

**Issue by porridge** [kubernetes/kubernetes#56291]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

load test in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8224 failed with:
```
I1122 20:50:41.974] Nov 22 20:50:41.974: INFO: WARNING Top latency metric: {Resource:nodes Subresource: Verb:LIST Scope:cluster Latency:{Perc50:10.291ms Perc90:20.575ms Perc99:17m24.122128s Perc100:0s} Count:131}
[...]
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scalability/load.go:96
There should be no high-latency requests
Expected
    <int>: 1
not to be >
    <int>: 0
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scalability/load.go:105
```

**Comment by porridge** [comment]
/priority failing-test
@kubernetes/sig-scalability-bugs
Umbrella issue: #56062

**Comment by porridge** [comment]
Also happened in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/8852: a single request took 15 minutes `I1211 08:35:54.658] Dec 11 08:35:54.657: INFO: WARNING Top latency metric: {Resource:nodes Subresource: Verb:LIST Scope:cluster Latency:{Perc50:8.35ms Perc90:11.927ms Perc99:15m28.296985s Perc100:0s} Count:83}`

**Comment by porridge** [comment]
Looking at `kube-apiserver.log` for this run, there are a few more such long requests at that time, as well as some panics. I don't know whether the 15 minute latency is the cause or effect of the panics, but I don't think they are expected, @kubernetes/sig-api-machinery-bugs ?

```
E1211 08:27:16.748805       6 writers.go:149] apiserver was unable to write a JSON response: client disconnected
E1211 08:27:16.748830       6 writers.go:149] apiserver was unable to write a JSON response: write tcp 10.128.0.2:443->104.197.79.4:50010: write: no route to host
E1211 08:27:16.748848       6 status.go:64] apiserver received an error that is not an metav1.Status: client disconnected
I1211 08:27:16.748877       6 asm_amd64.s:509] GET /api/v1/events: (15m28.375243659s) 200 [[eventer/v0.0.0 (linux/amd64) kubernetes/$Format] 104.197.79.4:50006]
E1211 08:27:16.748891       6 writers.go:149] apiserver was unable to write a JSON response: write tcp 10.128.0.2:443->104.197.79.4:50010: write: no route to host
I1211 08:27:16.748909       6 asm_amd64.s:509] GET /api/v1/nodes?resourceVersion=0: (15m28.299482586s) 200 [[heapster/v0.0.0 (linux/amd64) kubernetes/$Format] 104.197.79.4:50010]
E1211 08:27:16.749038       6 runtime.go:66] Observed a panic: &errors.errorString{s:"kill connection/stream"} (kill connection/stream)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:509
/usr/local/go/src/runtime/panic.go:491
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:217
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:101
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:51
/usr/local/go/src/net/http/server.go:1918
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:45
/usr/local/go/src/net/http/server.go:1918
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110
/usr/local/go/src/net/http/server.go:1918
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41
/usr/local/go/src/net/http/server.go:1918
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:198
/usr/local/go/src/net/http/server.go:2619
/usr/local/go/src/net/http/server.go:3164
<autogenerated>:1
/usr/local/go/src/net/http/h2_bundle.go:5462
/usr/local/go/src/net/http/h2_bundle.go:5747
/usr/local/go/src/runtime/asm_amd64.s:2337
E1211 08:27:16.749067       6 runtime.go:66] Observed a panic: &errors.errorString{s:"kill connection/stream"} (kill connection/stream)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:509
/usr/local/go/src/runtime/panic.go:491
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:217
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:101
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:51
/usr/local/go/src/net/http/server.go:1918
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:45
/usr/local/go/src/net/http/server.go:1918
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110
/usr/local/go/src/net/http/server.go:1918
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41
/usr/local/go/src/net/http/server.go:1918
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:198
/usr/local/go/src/net/http/server.go:2619
/usr/local/go/src/net/http/server.go:3164
<autogenerated>:1
/usr/local/go/src/net/http/h2_bundle.go:5462
/usr/local/go/src/net/http/h2_bundle.go:5747
/usr/local/go/src/runtime/asm_amd64.s:2337
I1211 08:27:16.749277       6 asm_amd64.s:509] GET /api/v1/nodes?resourceVersion=0: (15m28.295364064s) 200 [[heapster/v0.0.0 (linux/amd64) kubernetes/$Format] 104.197.79.4:50010]
E1211 08:27:16.749367       6 wrap.go:34] APIServer panic'd on GET /api/v1/nodes?resourceVersion=0: kill connection/stream
goroutine 124494 [running]:
runtime/debug.Stack(0x8d97a20, 0xc436aebb90, 0x3af937b)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1.1(0x3265c20, 0xc42036e380)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:34 +0x74
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc42b173cf0, 0x1, 0x1)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:54 +0xc8
panic(0x3265c20, 0xc42036e380)
        /usr/local/go/src/runtime/panic.go:491 +0x283
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc435646c20, 0xc42ff3f170)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:217 +0x190
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc42816d600, 0x8d97a20, 0xc436aebb90, 0xc43d4e3e00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:101 +0x292
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x8d97a20, 0xc436aebb90, 0xc43d4e3e00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:51 +0xeb
net/http.HandlerFunc.ServeHTTP(0xc42828a280, 0x8d97a20, 0xc436aebb90, 0xc43d4e3e00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x8d97a20, 0xc436aebb90, 0xc43d4e3e00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:45 +0x20f
net/http.HandlerFunc.ServeHTTP(0xc42828a2c0, 0x8d97a20, 0xc436aebb90, 0xc43d4e3e00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x8d97a20, 0xc436aebb90, 0xc43d4e3e00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc42816d620, 0x8d97a20, 0xc436aebb90, 0xc43d4e3e00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0x8d97a20, 0xc436aebb90, 0xc43d4e3e00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41 +0x108
net/http.HandlerFunc.ServeHTTP(0xc42816d640, 0x8d98860, 0xc42a3f8cd8, 0xc43d4e3e00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc42827c720, 0x8d98860, 0xc42a3f8cd8, 0xc43d4e3e00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:198 +0x51
net/http.serverHandler.ServeHTTP(0xc422bf0dd0, 0x8d98860, 0xc42a3f8cd8, 0xc43d4e3e00)
        /usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.initNPNRequest.ServeHTTP(0xc42cdf8e00, 0xc422bf0dd0, 0x8d98860, 0xc42a3f8cd8, 0xc43d4e3e00)
        /usr/local/go/src/net/http/server.go:3164 +0x9a
net/http.(*initNPNRequest).ServeHTTP(0xc4276238e0, 0x8d98860, 0xc42a3f8cd8, 0xc43d4e3e00)
        <autogenerated>:1 +0x63
net/http.(Handler).ServeHTTP-fm(0x8d98860, 0xc42a3f8cd8, 0xc43d4e3e00)
        /usr/local/go/src/net/http/h2_bundle.go:5462 +0x4d
net/http.(*http2serverConn).runHandler(0xc42e83f180, 0xc42a3f8cd8, 0xc43d4e3e00, 0xc435646ba0)
        /usr/local/go/src/net/http/h2_bundle.go:5747 +0x89
created by net/http.(*http2serverConn).processHeaders
        /usr/local/go/src/net/http/h2_bundle.go:5481 +0x495

```
