### ISSUE TITLE
pull-kubernetes-unit job fails on ubuntu 16.04

### ISSUE THREAD

**Issue by duane-ibm** [kubernetes/kubernetes#56780]
**Is this a BUG REPORT or FEATURE REQUEST?**: bug

**What happened**: pull-kubernetes-unit job fails, while looking through the error log, it is unclear what the exact cause of failure is.
```I1128 11:26:20.972] message:error: requesting groups or user-extra for  without impersonating a user
I1128 11:26:20.972] has:without impersonating a user
I1128 11:26:21.216] certificatesigningrequest "foo" created
I1128 11:26:21.371] test-cmd-util.sh:4453: Successful get csr/foo {{.spec.username}}: user1
I1128 11:26:21.503] test-cmd-util.sh:4454: Successful get csr/foo {{range .spec.groups}}{{.}}{{end}}: system:authenticated
I1128 11:26:21.680] certificatesigningrequest "foo" deleted
I1128 11:26:21.932] certificatesigningrequest "foo" created
I1128 11:26:22.112] test-cmd-util.sh:4459: Successful get csr/foo {{len .spec.groups}}: 3
I1128 11:26:22.282] test-cmd-util.sh:4460: Successful get csr/foo {{range .spec.groups}}{{.}} {{end}}: group2 group1 ,,,chameleon
I1128 11:26:22.440] certificatesigningrequest "foo" deleted
I1128 11:26:22.456] +++ exit code: 0
W1128 11:26:22.636] warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
I1128 11:26:22.737] No resources found
I1128 11:26:22.784] No resources found
I1128 11:26:22.786] TEST FAILED
I1128 11:26:22.854] junit report dir: /workspace/artifacts
I1128 11:26:22.858] +++ [1128 11:26:22] Clean up complete
I1128 11:26:22.860] Makefile:292: recipe for target 'test-cmd' failed
W1128 11:26:22.960] warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
W1128 11:26:22.961] I1128 11:26:22.808774   28324 naming_controller.go:285] Shutting down NamingConditionController
W1128 11:26:22.961] I1128 11:26:22.812591   28324 controller.go:90] Shutting down OpenAPI AggregationController
W1128 11:26:22.961] I1128 11:26:22.812894   28324 serve.go:129] Stopped listening on 127.0.0.1:6443
W1128 11:26:22.961] I1128 11:26:22.812961   28324 serve.go:129] Stopped listening on 127.0.0.1:8080
W1128 11:26:22.962] I1128 11:26:22.814484   28324 autoregister_controller.go:160] Shutting down autoregister controller
W1128 11:26:22.962] make:  ***[test-cmd] Error 1
W1128 11:26:23.986] Traceback (most recent call last):
W1128 11:26:23.987]   File "/root/Kubernetes-CI/test-infra/./jenkins/../scenarios/kubernetes_verify.py", line 112, in <module>
W1128 11:26:24.455]     main(ARGS.branch, ARGS.script, ARGS.force)
W1128 11:26:24.456]   File "/root/Kubernetes-CI/test-infra/./jenkins/../scenarios/kubernetes_verify.py", line 96, in main
W1128 11:26:24.456]     'bash', '-c', 'cd kubernetes && %s' % script,
W1128 11:26:24.456]   File "/root/Kubernetes-CI/test-infra/./jenkins/../scenarios/kubernetes_verify.py", line 54, in check
W1128 11:26:24.456]     subprocess.check_call(cmd)
W1128 11:26:24.456]   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
W1128 11:26:24.504]     raise CalledProcessError(retcode, cmd)
W1128 11:26:24.504] subprocess.CalledProcessError: Command '('docker', 'run', '--rm=true', '--privileged=true', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-v', '/etc/localtime:/etc/localtime:ro', '-v', '/root/Kubernetes-CI/test-infra/github.com/kubernetes/kubernetes:/go/src/k8s.io/kubernetes', '-v', '/root/Kubernetes-CI/test-infra/github.com/kubernetes/kubernetes/_artifacts:/workspace/artifacts', '-e', 'KUBE_FORCE_VERIFY_CHECKS=n', '-e', 'KUBE_VERIFY_GIT_BRANCH=master', '-e', 'REPO_DIR=/root/Kubernetes-CI/test-infra/github.com/kubernetes/kubernetes', 'gcr.io/k8s-testimages/kubekins-test:1.9-v20171018-6ddbad97', 'bash', '-c', 'cd kubernetes && ./hack/jenkins/test-dockerized.sh')' returned non-zero exit status 2
E1128 11:26:24.505] Command failed
I1128 11:26:24.505] process 11080 exited with code 1 after 28.8m
E1128 11:26:24.508] FAIL: pull-kubernetes-unit
```

PFA complete build log [build-log.txt](https://github.com/kubernetes/kubernetes/files/1526612/build-log.txt)

**What you expected to happen**: The build to move ahead after Running command: run_impersonation_tests

**How to reproduce it (as minimally and precisely as possible)**: Executed the following command, `root@xyz:~/Kubernetes-CI/test-infra# ./jenkins/bootstrap.py --job=pull-kubernetes-unit --repo=github.com/kubernetes/kubernetes`
(https://github.com/kubernetes/test-infra)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9
- Cloud provider or hardware configuration: x86 64-bit VM. 8gb RAM, 2 cores CPU.
- OS (e.g. from /etc/os-release): Ubuntu 16.04 LTS
- Kernel (e.g. `uname -a`): 4.4.0-21-generic

/area test-infra
/sig testing

**Comment by duane-ibm** [comment]
The logs seem to have a lot of junk in it.
The job fails with the error "Error when running run_kubectl_get_tests"
With the following logs seen, looks like the **FAIL!** is the actual point of failure

```I1128 11:20:28.277] message:No resources found.
I1128 11:20:28.277] has:No resources found
I1128 11:20:28.417] [32mtest-cmd-util.sh:1382: Successful get pods {{range.items}}{{.metadata.name}}:{{end}}: 
I1128 11:20:28.561] (B[mSuccessful
I1128 11:20:28.561] message:Error from server (NotFound): pods "abc" not found
I1128 11:20:28.561] has:pods "abc" not found
I1128 11:20:28.563] FAIL!
I1128 11:20:28.563] message:Error from server (NotFound): pods "abc" not found
I1128 11:20:28.563] has not:List
I1128 11:20:28.563] 1388 /go/src/k8s.io/kubernetes/hack/make-rules/test-cmd-util.sh
I1128 11:20:28.859] Successful
I1128 11:20:28.859] message:I1128 11:20:28.689550    5640 loader.go:357] Config loaded from file /tmp/tmp.qM40BZRi1W/.kube/config```

**Comment by duane-ibm** [comment]
Closing issue. Will open a new one.
