### ISSUE TITLE
Encounter some http stack error in apiserver log

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/kubernetes#57024]
**Version**:
v1.10.0-alpha.0.821+a505d1bc7854c0-dirty

**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
When start k8s on `hack/local-up-cluster.sh`, there is some error in `/tmp/kube-apiserver.log`
```

I1211 02:49:53.635542   29967 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/system:controller:route-controller: (907.851µs) 404 [[hyperkube/v1.10.0 (linux/amd64) kubernetes/bb72237] 127.0.0.1:58754]
I1211 02:49:53.636242   29967 wrap.go:42] GET /healthz: (340.401µs) 500
goroutine 3961 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc422fd4700, 0x1f4)
	/data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc422fd4700, 0x1f4)
	/data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc42acf1ea0, 0x1f4)
	/data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:188 +0xac
net/http.Error(0x7f8756662640, 0xc427ad7ce0, 0xc4299ae840, 0x2ae, 0x1f4)
	/usr/local/go/src/net/http/server.go:1930 +0xda
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/healthz.handleRootHealthz.func1(0x7f8756662640, 0xc427ad7ce0, 0xc426b12200)
	/data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go:121 +0x508
net/http.HandlerFunc.ServeHTTP(0xc4245f40c0, 0x7f8756662640, 0xc427ad7ce0, 0xc426b12200)
	/usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc42afc9340, 0x7f8756662640, 0xc427ad7ce0, 0xc426b12200)
	/data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:241 +0x55a
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc422ee2fc0, 0x7f8756662640, 0xc427ad7ce0, 0xc426b12200)
	/data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0xa1
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x4978c63, 0xf, 0xc42397bc20, 0xc422ee2fc0, 0x7f8756662640, 0xc427ad7ce0, 0xc426b12200)
	/data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:161 +0x6ad
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc426705060, 0x7f8756662640, 0xc427ad7ce0, 0xc426b12200)
	<autogenerated>:1 +0x75
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7f8756662640, 0xc427ad7ce0, 0xc426b12200)
	/data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:51 +0x37d
net/http.HandlerFunc.ServeHTTP(0xc42302c640, 0x7f8756662640, 0xc427ad7ce0, 0xc426b12200)
	/usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7f8756662640, 0xc427ad7ce0, 0xc426b12200)
	/data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:95 +0x318
net/http.HandlerFunc.ServeHTTP(0xc4265c0ec0, 0x7f8756662640, 0xc427ad7ce0, 0xc426b12200)
	/usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7f8756662640, 0xc427ad7ce0, 0xc426b12200)
	/data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:49 +0x203a
net/http.HandlerFunc.ServeHTTP(0xc42302c690, 0x7f8756662640, 0xc427ad7ce0, 0xc426b12200)
	/usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7f8756662640, 0xc427ad7ce0, 0xc426b12200)
	/data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:79 +0x2b1
net/http.HandlerFunc.ServeHTTP(0xc42302c780, 0x7f8756662640, 0xc427ad7ce0, 0xc426b12200)
	/usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x7f8756662640, 0xc427ad7ce0, 0xc426b12200)
	/data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc426705080, 0x7f8756662640, 0xc427ad7ce0, 0xc426b12200)
	/usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithCORS.func1(0x7f8756662640, 0xc427ad7ce0, 0xc426b12200)
	/data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/cors.go:75 +0x17b
net/http.HandlerFunc.ServeHTTP(0xc426d228a0, 0x7f8756662640, 0xc427ad7ce0, 0xc426b12200)
	/usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc426705220, 0xa665e80, 0xc427ad7ce0, 0xc426b12200, 0xc42624a600)
	/data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:93 +0x8d
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:92 +0x1ab

logging error output: "[+]ping ok\n[+]etcd ok\n[+]poststarthook/generic-apiserver-start-informers ok\n[+]poststarthook/start-apiextensions-informers ok\n[+]poststarthook/start-apiextensions-controllers ok\n[+]poststarthook/bootstrap-controller ok\n[-]poststarthook/rbac/bootstrap-roles failed: reason withheld\n[+]poststarthook/ca-registration ok\n[+]poststarthook/start-kube-apiserver-informers ok\n[+]poststarthook/start-kube-aggregator-informers ok\n[+]poststarthook/apiservice-registration-controller ok\n[+]poststarthook/apiservice-status-available-controller ok\n[+]poststarthook/apiservice-openapi-controller ok\n[+]poststarthook/kube-apiserver-autoregistration ok\n[+]autoregister-completion ok\nhealthz check failed\n"
 [[curl/7.29.0] 127.0.0.1:58782]

```

**What you expected to happen**:
No those error in apiserver

**Detail log link**:
https://paste.fedoraproject.org/paste/Jab1IAnQGblS2m2TdorSZg

**Comment by roycaihw** [comment]
cc @jpbetz

**Comment by liggitt** [comment]
Those logs occur when /healthz is hit when one of the health checks is failing. Those can fail for various reasons, like etcd not being available or writeable, or startup having not completed. Check the particular health checks that are failing for more info

/close
