### ISSUE TITLE
cpumanager should graceful exit other than panic when met error

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/kubernetes#57239]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When enable cpumanager by `--cpu-manager-policy=static`,  but not set `--kube-reserved` and `--system-reserved`, kubelet will get panic error in log
```
I1214 03:22:51.865756   23951 cpu_manager.go:120] [cpumanager] detected CPU topology: &{2 2 1 map[0:{0 0} 1:{0 1}]}
panic: [cpumanager] unable to determine reserved CPU resources for static policy

goroutine 88 [running]:
k8s.io/kubernetes/pkg/kubelet/cm/cpumanager.NewManager(0x7fff04c660c7, 0x6, 0x2540be400, 0xc420b96738, 0xc421442360, 0x497d024, 0x10, 0xffffffffffffffff, 0x0, 0x80, ...)
        /data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/cpumanager/cpu_manager.go:124 +0x65b
k8s.io/kubernetes/pkg/kubelet/cm.NewContainerManager(0xa682480, 0xc420c17160, 0xa680780, 0xc4214109c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/container_manager_linux.go:278 +0xb0e
k8s.io/kubernetes/cmd/kubelet/app.run(0xc420496600, 0xc420ef1e40, 0xc42003be98, 0x1)
        /data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:454 +0xc22
k8s.io/kubernetes/cmd/kubelet/app.Run(0xc420496600, 0x0, 0x10, 0x43dd620)
        /data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:183 +0xfa
main.NewKubelet.func1(0xc4208697a0, 0xc420c28000, 0x0, 0x1b, 0xc420124600, 0x1, 0x10000a9f0280)
        /data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/hyperkube/kubelet.go:45 +0x75
main.(*HyperKube).Run.func1(0xc4201245a0, 0xc4208697a0)
        /data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/hyperkube/hyperkube.go:216 +0x6d
created by main.(*HyperKube).Run
        /data/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/hyperkube/hyperkube.go:215 +0x733

```
**What you expected to happen**:
Should graceful exit with error not panic.

**How to reproduce it (as minimally and precisely as possible)**:
set `--cpu-manager-policy=static` and but not set `--kube-reserved` and `--system-reserved`

**Anything else we need to know?**:

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/cpumanager/cpu_manager.go#L122-L135

**Comment by discordianfish** [comment]
Great that it's not panicing anymore, but I'd also love to get the "requires systemreserved.cpu + kubereserved.cpu to be greater than zero" hint in this particular case. It looks like even with #57247 this doesn't seem to be the case (since it errors out with the non-actionable "unable to determine reserved CPU resources for static policy".
Should I open another issue for this?
