### ISSUE TITLE
Panic in kubeadm init

### ISSUE THREAD

**Issue by ateleshev** [kubernetes/kubernetes#57560]
/kind bug

Received panic when execute kubeadm init:
```
[certificates] Generated apiserver-kubelet-client certificate and key.
[certificates] Generated sa key and public key.
[certificates] Generated front-proxy-ca certificate and key.
[certificates] Generated front-proxy-client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x2b2466b]

goroutine 1 [running]:
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.createKubeConfigFileIfNotExists(0x38b4c58, 0xf, 0x38aa445, 0xa, 0xc42028e360, 0xc42000c001, 0x39505c7)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:247 +0x50b
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.createKubeConfigFiles(0x38b4c58, 0xf, 0xc42039d680, 0xc42130f888, 0x4, 0x4, 0x5, 0xc42130f8c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:121 +0x134
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.CreateInitKubeConfigFiles(0x38b4c58, 0xf, 0xc42039d680, 0xc4203004d0, 0x1a)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:63 +0x95
k8s.io/kubernetes/cmd/kubeadm/app/cmd.(*Init).Run(0xc420300350, 0x55f61a0, 0xc42000c018, 0x0, 0xc420a80000)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:309 +0x1fd0
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdInit.func1(0xc4201d9440, 0xc420b59650, 0x0, 0x7)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:137 +0x2b5
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc4201d9440, 0xc420b595e0, 0x7, 0x7, 0xc4201d9440, 0xc420b595e0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:603 +0x234
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4201ead80, 0xc4201c9680, 0xc4201c86c0, 0xc4201d9440)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:689 +0x2fe
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4201ead80, 0xc42000c010, 0x55f61a0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:648 +0x2b
k8s.io/kubernetes/cmd/kubeadm/app.Run(0xc420a53f70, 0x4046f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:36 +0xe3
main.main()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:27 +0x26
```

**Reproduce**:
```
> sudo kubeadm init --token-ttl 0 --node-name s1 --service-dns-domain=cloud.local --pod-network-cidr=10.244.0.0/16
```

- Kubernetes version
```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

- OS: Debian GNU/Linux 9 (stretch)
- Kernel: Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3 x86_64 GNU/Linux
- Packages:
```
ii  kubeadm                          1.9.0-00                       amd64        Kubernetes Cluster Bootstrapping Tool
ii  kubectl                          1.9.0-00                       amd64        Kubernetes Command Line Tool
ii  kubelet                          1.9.0-00                       amd64        Kubernetes Node Agent
ii  kubernetes-cni                   0.6.0-00                       amd64        Kubernetes CNI
```

**Comment by ateleshev** [comment]
sudo kubeadm reset - doesn't delete all sub-folders, 
sudo rm -rf /etc/kubernetes/* - helped me
