### ISSUE TITLE
Kubectl cp fails when attempting to copy files from secrets mounted as directories

### ISSUE THREAD

**Issue by athornton** [kubernetes/kubernetes#58011]
/kind bug

**What happened**:

I get a Go stack trace when I try to copy a secrets-mounted directory.

**What you expected to happen**:

I expected to copy the files out to the environment where I'm running `kubectl`.

In this example, `/etc/tls` is a secret:

```
    Mounts:
      /etc/tls from tls (ro)
```

...

```
Volumes:
  tls:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  tls
    Optional:    false
```

I initially expected to be able to just `kubectl cp <pod>:/etc/tls .` and have the files show up, by analogy with, say `/etc/init.d`.

That gave me a set of zero-length files.  But that's also what happens if I copy symlinks (e.g. `/etc/rc0.d`), so, fine, it's a little irritating but it's at least consistent, since if I `kubectl` exec into the pod, I see that the actual files are symlinked into `/etc/tls/..data`.

Then if I do 

```
adam@ixitxachitl:/tmp/kubectl-cp$ kubectl cp $POD:/etc/tls/..data .
tar: Removing leading `/' from member names
error: open .: is a directory
```

So it gets angry about overwriting `.` which seems a little suspicious since it should be dumping files into `.`.  

Copying `..data` to a named file gives me...a zero-length file.

```
adam@ixitxachitl:/tmp/kubectl-cp$ kubectl cp $POD:/etc/tls/..data foo
tar: Removing leading `/' from member names
adam@ixitxachitl:/tmp/kubectl-cp$ ls -l foo
-rw-r--r--  1 adam  wheel  0 Jan  9 11:03 foo
```
OK, so what if I add a traling slash to `..data` ?  It works fine for `/etc/init.d/` after all:

```
adam@ixitxachitl:/tmp/kubectl-cp$ kubectl cp $POD:/etc/tls/..data/ foo
tar: Removing leading `/' from member names
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
k8s.io/kubernetes/pkg/kubectl/cmd.untarAll(0x2d8c6e0, 0xc4205280c8, 0x7ffeefbff94f, 0x3, 0x7ffeefbff93f, 0xf, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go:247 +0x2f3
k8s.io/kubernetes/pkg/kubectl/cmd.copyFromPod(0x2dbc080, 0xc4201e34a0, 0xc4202326c0, 0x2d91e60, 0xc420084010, 0x0, 0x0, 0x7ffeefbff923, 0x1a, 0x7ffeefbff93e, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go:191 +0x371
k8s.io/kubernetes/pkg/kubectl/cmd.runCopy(0x2dbc080, 0xc4201e34a0, 0xc4202326c0, 0x2d91e60, 0xc420084008, 0x2d91e60, 0xc420084010, 0xc4203db0c0, 0x2, 0x2, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go:128 +0x2d1
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdCp.func1(0xc4202326c0, 0xc4203db0c0, 0x2, 0x2)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go:69 +0x89
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202326c0, 0xc4203daf00, 0x2, 0x2, 0xc4202326c0, 0xc4203daf00)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:603 +0x22b
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4203366c0, 0x5000107, 0x0, 0xffffffffffffffff)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:689 +0x339
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4203366c0, 0xc4201e34a0, 0x2d91e20)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:648 +0x2b
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:39 +0xd5
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:26 +0x22
```

That feels like it should not have happened.

I *can* copy a file out by specifying a single filename:

```
adam@ixitxachitl:/tmp/kubectl-cp$ kubectl cp $POD:/etc/tls/..data/dhparam.pem dhparam.pem
tar: Removing leading `/' from member names
adam@ixitxachitl:/tmp/kubectl-cp$ ls -l dhparam.pem
-rw-r--r--  1 adam  wheel  424 Jan  9 11:08 dhparam.pem
```

**How to reproduce it (as minimally and precisely as possible)**:

Mount a secret at some directory `/d` .

`kubectl pod:/d/..data/ d`

**Anything else we need to know?**:

Nothing leaps to mind

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.4", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"clean", BuildDate:"2017-11-20T05:28:34Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5-gke.0", GitCommit:"2c2a807131fa8708abc92f3513fe167126c8cce5", GitTreeState:"clean", BuildDate:"2017-12-19T20:05:45Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
GKE
- OS (e.g. from /etc/os-release):
Client: MacOS High Sierra 10.13.2S
Container: Debian 9
- Kernel (e.g. `uname -a`):
Client: 
```
Darwin ixitxachitl 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
```
Container: 
```
Linux jld-nginx-6ffb87f8c7-qwnns 4.4.86+ #1 SMP Thu Dec 7 20:11:11 PST 2017 x86_64 GNU/Linux
```
- Install tools:
Locally-installed-as-user google-cloud-sdk; custom Dockerfile in container.
- Others:
Nothing to speak of.
  
/sig cli

**Comment by yue9944882** [comment]
This BUG will occur if we try to `kubectl cp <ns>/<pod>:<src> <dst>` where the suffix of `<src>` is a symbolic link to a dir and <src> is tailed with a slash. 

```
kubectl exec <pod> mkdir /root/foo
kubectl exec <pod> ln -s /root/foo /root/bar
# kubectl crush
kubectl cp <pod>:/root/bar/ .
```
