### ISSUE TITLE
GET /healthz panics during startup

### ISSUE THREAD

**Issue by php-coder** [kubernetes/kubernetes#58348]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
When I run local cluster by `hack/local-up-cluster.sh` command, in the api-server log I see that `GET /healthz` request was panicked.

**What you expected to happen**:
It shouldn't panic.

**How to reproduce it (as minimally and precisely as possible)**:
```console
$ PSP_ADMISSION=true ALLOW_PRIVILEGED=true ALLOW_SECURITY_CONTEXT=true hack/local-up-cluster.sh
```

**Anything else we need to know?**:
Excerpt from `/tmp/kube-apiserver.log`:
```
I0116 17:40:00.486564    5723 storage_rbac.go:236] created clusterrolebinding.rbac.authorization.k8s.io/system:discovery
I0116 17:40:00.490604    5723 wrap.go:42] GET /healthz: (304.101µs) 500
goroutine 3528 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc423265e30, 0x1f4)
		/home/coder/git/src/home/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc423265e30, 0x1f4)
		/home/coder/git/src/home/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc420c6bac0, 0x1f4)
		/home/coder/git/src/home/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:188 +0xac
net/http.Error(0x7f3ca7ffdfd0, 0xc425ec0c10, 0xc429e342c0, 0x2ae, 0x1f4)
		/opt/go1.9.2/src/net/http/server.go:1930 +0xda
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/healthz.handleRootHealthz.func1(0x7f3ca7ffdfd0, 0xc425ec0c10, 0xc427e5bc00)
		/home/coder/git/src/home/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go:121 +0x508
net/http.HandlerFunc.ServeHTTP(0xc425dec6e0, 0x7f3ca7ffdfd0, 0xc425ec0c10, 0xc427e5bc00)
		/opt/go1.9.2/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc427d68940, 0x7f3ca7ffdfd0, 0xc425ec0c10, 0xc427e5bc00)
		/home/coder/git/src/home/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:241 +0x55a
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc4204b3880, 0x7f3ca7ffdfd0, 0xc425ec0c10, 0xc427e5bc00)
		/home/coder/git/src/home/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0xa1
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x4ac02c9, 0xf, 0xc4212203f0, 0xc4204b3880, 0x7f3ca7ffdfd0, 0xc425ec0c10, 0xc427e5bc00)
		/home/coder/git/src/home/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:161 +0x6ad
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc427175f20, 0x7f3ca7ffdfd0, 0xc425ec0c10, 0xc427e5bc00)
		<autogenerated>:1 +0x75
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7f3ca7ffdfd0, 0xc425ec0c10, 0xc427e5bc00)
		/home/coder/git/src/home/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:51 +0x37d
net/http.HandlerFunc.ServeHTTP(0xc423a3a050, 0x7f3ca7ffdfd0, 0xc425ec0c10, 0xc427e5bc00)
		/opt/go1.9.2/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7f3ca7ffdfd0, 0xc425ec0c10, 0xc427e5bc00)
		/home/coder/git/src/home/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:95 +0x318
net/http.HandlerFunc.ServeHTTP(0xc4270b5bc0, 0x7f3ca7ffdfd0, 0xc425ec0c10, 0xc427e5bc00)
		/opt/go1.9.2/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7f3ca7ffdfd0, 0xc425ec0c10, 0xc427e5bc00)
		/home/coder/git/src/home/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:49 +0x203a
net/http.HandlerFunc.ServeHTTP(0xc423a3a0f0, 0x7f3ca7ffdfd0, 0xc425ec0c10, 0xc427e5bc00)
		/opt/go1.9.2/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7f3ca7ffdfd0, 0xc425ec0c10, 0xc427e5bc00)
		/home/coder/git/src/home/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:79 +0x2b1
net/http.HandlerFunc.ServeHTTP(0xc423a3a140, 0x7f3ca7ffdfd0, 0xc425ec0c10, 0xc427e5bc00)
		/opt/go1.9.2/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x7f3ca7ffdfd0, 0xc425ec0c10, 0xc427e5bc00)
		/home/coder/git/src/home/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc427175f40, 0x7f3ca7ffdfd0, 0xc425ec0c10, 0xc427e5bc00)
		/opt/go1.9.2/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithCORS.func1(0x7f3ca7ffdfd0, 0xc425ec0c10, 0xc427e5bc00)
		/home/coder/git/src/home/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/cors.go:75 +0x17b
net/http.HandlerFunc.ServeHTTP(0xc426add2c0, 0x7f3ca7ffdfd0, 0xc425ec0c10, 0xc427e5bc00)
		/opt/go1.9.2/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc4271780e0, 0xa9aec60, 0xc425ec0c10, 0xc427e5bc00, 0xc427dc3680)
		/home/coder/git/src/home/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:93 +0x8d
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
		/home/coder/git/src/home/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:92 +0x1ab

logging error output: "[+]ping ok\n[+]etcd ok\n[+]poststarthook/generic-apiserver-start-informers ok\n[+]poststarthook/start-apiextensions-informers ok\n[+]poststarthook/start-apiextensions-controllers ok\n[+]poststarthook/bootstrap-controller ok\n[-]poststarthook/rbac/bootstrap-roles failed: reason withheld\n[+]poststarthook/ca-registration ok\n[+]poststarthook/start-kube-apiserver-informers ok\n[+]poststarthook/start-kube-aggregator-informers ok\n[+]poststarthook/apiservice-registration-controller ok\n[+]poststarthook/apiservice-status-available-controller ok\n[+]poststarthook/apiservice-openapi-controller ok\n[+]poststarthook/kube-apiserver-autoregistration ok\n[+]autoregister-completion ok\nhealthz check failed\n"
 [[curl/7.51.0] 127.0.0.1:44634]
I0116 17:40:00.495691    5723 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/system:basic-user: (595.392µs) 404 [[hyperkube/v1.10.0 (linux/amd64) kubernetes/a1e3b3f] 127.0.0.1:44596]
```

**Environment**:
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0-beta1", GitCommit:"3258431", GitTreeState:"clean", BuildDate:"2018-01-08T18:34:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-alpha.1.878+a1e3b3f0533d5d-dirty", GitCommit:"a1e3b3f0533d5d211d0d8fad15005ee3cb7d67f0", GitTreeState:"dirty", BuildDate:"2018-01-16T16:22:09Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by php-coder** [comment]
`[-]poststarthook/rbac/bootstrap-roles failed: reason withheld` <-- could it be related to RBAC?

**Comment by liggitt** [comment]
it's not a panic, it's an intentional stack trace log that is done for any server error http status (which /healthz returns while startup is happening and the server isn't healthy yet):

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go#L207

I think it's silly, but it's intentional

/close
