### ISSUE TITLE
kubectl apply on a service yaml crashes apiserver

### ISSUE THREAD

**Issue by nicklan** [kubernetes/kubernetes#58892]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Applying the following yaml causes our apiserver to crash:
```yaml
apiVersion: v1
kind: Service
metadata:
 labels:
   ttl: never
 name: svc-web
spec:
 ports:
 - name: web
   port: 443
   protocol: TCP
   targetPort: 443
 - name: web-rpc
   port: 34562
   protocol: TCP
   targetPort: 34562
 selector:
   app: webapp
 type: LoadBalancer
```

The error output by kubectl is:
```
error: error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{},\"labels\":{\"ttl\":\"never\"},\"name\":\"svc-web\",\"namespace\":\"development\"},\"spec\":{\"ports\":[{\"name\":\"web\",\"port\":443,\"protocol\":\"TCP\",\"targetPort\":443},{\"name\":\"web-rpc\",\"port\":34562,\"protocol\":\"TCP\",\"targetPort\":34562}],\"selector\":{\"app\":\"webapp\"},\"type\":\"LoadBalancer\"}}\n"}},"spec":{"type":"LoadBalancer"}}
to:
&{0xc421756000 0xc42041cb60 development webapp /tmp/foo.yaml.hoxD1x 0xc4209fdc70 0xc42007e018 286849333 false}
for: "/tmp/foo.yaml.hoxD1x": Patch https://[server]:443/api/v1/namespaces/development/services/svc-web: unexpected EOF; some request body already written
```
The apiserver logs show:
```
GET /api/v1/namespaces/development/resourcequotas: (877.892µs) 200 [[hyperkube/v1.8.1 (linux/amd64) kubernetes/9164d76] 127.0.0.1:55468]
I0125 00:42:33.099086       1 admission.go:58] Service development/svc-web missing source ranges. Defaulting to [SNIP].
E0125 00:42:33.105661       1 runtime.go:66] Observed a panic: "duplicate node port" (duplicate node port)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:514
/usr/local/go/src/runtime/panic.go:489
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/core/service/rest.go:598
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/core/service/rest.go:341
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:836
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:1187
/usr/local/go/src/runtime/asm_amd64.s:2197
panic: duplicate node port [recovered]
	panic: duplicate node port

goroutine 236770 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc43410bf78, 0x1, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x3d77400, 0xc453fe3280)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
k8s.io/kubernetes/pkg/registry/core/service.(*REST).updateNodePorts(0xc420d39590, 0xc470149a40, 0xc46c2ec780, 0xc43410be18, 0xc420d39501, 0x9a7a260)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/core/service/rest.go:598 +0x262
k8s.io/kubernetes/pkg/registry/core/service.(*REST).Update(0xc420d39590, 0x7ff91caff138, 0xc47b6b51d0, 0xc479fad0a8, 0x16, 0x9a84ba0, 0xc479f2dbc0, 0x0, 0x0, 0xc43ae54e00, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/core/service/rest.go:341 +0xb12
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.patchResource.func3(0x18, 0x4a49bc8, 0xc43b998778, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:836 +0xbb
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.finishRequest.func1(0xc47eef6c00, 0xc47082ea50, 0xc47eef6b40, 0xc47eef6ae0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:1187 +0x99
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.finishRequest
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:1192 +0xd9
panic: duplicate node port [recovered]
	panic: duplicate node port

goroutine 236720 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAudit.func1.1(0xc4797c4200, 0x7ff91cbe6838, 0xc4210dd9c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/audit.go:83 +0x23f
panic(0x3d77400, 0xc453fe3280)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.finishRequest(0x6fc23ac00, 0xc47082ea50, 0x9a6dd20, 0xc4203f4fc0, 0xc453f88900, 0x2)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:1205 +0x454
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.patchResource(0x7ff91caff138, 0xc47b6b51d0, 0xc47082ea00, 0x6fc23ac00, 0x9a82960, 0xc470149680, 0x7ff91caa9510, 0xc420d39590, 0xc479fad0a8, 0x16, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:842 +0x714
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.PatchResource.func1(0x9aa0760, 0xc44d082390, 0xc457a66400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:590 +0xaf3
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints.restfulPatchResource.func1(0xc47b6b5050, 0xc47eef6840)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1093 +0xd5
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc47b6b5050, 0xc47eef6840)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:145 +0x207
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc4210c37a0, 0x9aa0660, 0xc44d082378, 0xc457a66400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:277 +0xb8d
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(0xc4210c37a0, 0x9aa0660, 0xc44d082378, 0xc457a66400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:199 +0x57
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x48a7fc6, 0xe, 0xc4210c37a0, 0xc42054a3f0, 0x9aa0660, 0xc44d082378, 0xc457a66400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:153 +0x6e7
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc420fc4e40, 0x9aa0660, 0xc44d082378, 0xc457a66400)
	<autogenerated>:69 +0x86
k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc45d018200, 0x9aa0660, 0xc44d082378, 0xc457a66400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:91 +0x122
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc45d1e1980, 0x9aa0660, 0xc44d082378, 0xc457a66400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x3dd
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc429086000, 0x9aa0660, 0xc44d082378, 0xc457a66400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x72
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x48ac804, 0xf, 0xc428976870, 0xc429086000, 0x9aa0660, 0xc44d082378, 0xc457a66400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:161 +0x301
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc42a546ea0, 0x9aa0660, 0xc44d082378, 0xc457a66400)
	<autogenerated>:69 +0x86
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x9aa0660, 0xc44d082378, 0xc457a66400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:51 +0x37a
net/http.HandlerFunc.ServeHTTP(0xc427369f40, 0x9aa0660, 0xc44d082378, 0xc457a66400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x9aa0660, 0xc44d082378, 0xc457a66400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:98 +0x5a0
net/http.HandlerFunc.ServeHTTP(0xc4265fe140, 0x9aa0660, 0xc44d082378, 0xc457a66400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x9aa0660, 0xc44d082378, 0xc457a66400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:49 +0x21b2
net/http.HandlerFunc.ServeHTTP(0xc427369f90, 0x9aa0660, 0xc44d082378, 0xc457a66400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAudit.func1(0x7ff9088c8db8, 0xc44d082350, 0xc457a66400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/audit.go:105 +0x52a
net/http.HandlerFunc.ServeHTTP(0xc427fe2000, 0x7ff9088c8db8, 0xc44d082350, 0xc457a66400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7ff9088c8db8, 0xc44d082350, 0xc457a66400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:79 +0x2b0
net/http.HandlerFunc.ServeHTTP(0xc427fe20f0, 0x7ff9088c8db8, 0xc44d082350, 0xc457a66400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x7ff9088c8db8, 0xc44d082350, 0xc457a66400)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xef
net/http.HandlerFunc.ServeHTTP(0xc42a546ec0, 0x7ff9088c8db8, 0xc44d082350, 0xc457a66400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc42a546f40, 0x9aa7760, 0xc44d082350, 0xc457a66400, 0xc47eef6600)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:106 +0x8d
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0x1ca
```
The only actual change was that the existing service was ClusterIP and not LoadBalancer (despite the last applied annotation).  Removing the last applied annotation did not resolve the issue. Deleting the service and recreating it did.

**What you expected to happen**:
Service should have been applied

**How to reproduce it (as minimally and precisely as possible)**:
Not sure at this point

**Anything else we need to know?**:

This seems related to issue #48579

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8.1
- Cloud provider or hardware configuration: aws
- OS (e.g. from /etc/os-release): CoreOS
- Kernel (e.g. `uname -a`): Linux 4.13.9-coreos #1 SMP
- Install tools:
- Others:

**Comment by liggitt** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/49258 in 1.9

Picked to 1.8.x in https://github.com/kubernetes/kubernetes/issues/55580 so upgrading to the latest 1.8.x release will include this fix

/close
