### ISSUE TITLE
TestGetMultipleTypeObjectsAsList: times out when .kube/config specifies server

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#59425]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

After setting up minikube once, I proceeded to compiling and testing kubernetes directly. The minikube VM is inactive, but I have that cluster as default in .kube/config.

With commit 68da45623f5b14f61d9ce51b4946c11e034eb25c (current master), I noticed that "make test" failed with TestGetMultipleTypeObjectsAsList timing out. The stack backtraces show that it is trying to connect, and strace highlighted that this is for an IP address that is used by the API server for the inactive minikube cluster.

```
=== RUN   TestGetMultipleTypeObjectsAsList
[pid 29988] openat(AT_FDCWD, "/home/pohly/.kube/config", O_RDONLY|O_CLOEXEC) = 3
[pid 29988] openat(AT_FDCWD, "/home/pohly/.minikube/client.crt", O_RDONLY|O_CLOEXEC) = 3
[pid 29988] openat(AT_FDCWD, "/home/pohly/.minikube/client.key", O_RDONLY|O_CLOEXEC) = 5
[pid 29988] openat(AT_FDCWD, "/home/pohly/.minikube/ca.crt", O_RDONLY|O_CLOEXEC) = 3
[pid 29988] openat(AT_FDCWD, "/home/pohly/.minikube/ca.crt", O_RDONLY|O_CLOEXEC) = 3
[pid 29988] openat(AT_FDCWD, "/home/pohly/.minikube/client.crt", O_RDONLY|O_CLOEXEC) = 3
[pid 29988] openat(AT_FDCWD, "/home/pohly/.minikube/client.key", O_RDONLY|O_CLOEXEC) = 3
[pid 29988] openat(AT_FDCWD, "/home/pohly/.kube/cache/discovery/192.168.39.186_8443/servergroups.json", O_RDONLY|O_CLOEXEC) = 3
[pid 29988] connect(3, {sa_family=AF_INET, sin_port=htons(8443), sin_addr=inet_addr("192.168.39.186")}, 16) = -1 EINPROGRESS (Operation now in progress)
[pid 30009] openat(AT_FDCWD, "/home/pohly/.kube/cache/discovery/192.168.39.186_8443/servergroups.json", O_RDONLY|O_CLOEXEC) = 3
[pid 30009] connect(3, {sa_family=AF_INET, sin_port=htons(8443), sin_addr=inet_addr("192.168.39.186")}, 16) = -1 EINPROGRESS (Operation now in progress)
panic: test timed out after 2m0s

goroutine 74 [running]:
testing.startAlarm.func1()
	/usr/lib/go-1.9/src/testing/testing.go:1145 +0xf9
created by time.goFunc
	/usr/lib/go-1.9/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc4200e40f0, 0x1c535b9, 0x20, 0x1cc83c8, 0x482001)
	/usr/lib/go-1.9/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc4200e40f0)
	/usr/lib/go-1.9/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc4200e40f0, 0xc420861dd8)
	/usr/lib/go-1.9/src/testing/testing.go:746 +0xd0
testing.runTests(0xc4206c1760, 0x2856680, 0x18, 0x18, 0xe0000000001)
	/usr/lib/go-1.9/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc420093c20, 0x2881e18)
	/usr/lib/go-1.9/src/testing/testing.go:921 +0x111
main.main()
	k8s.io/kubernetes/pkg/kubectl/cmd/resource/_test/_testmain.go:90 +0xc1

goroutine 5 [chan receive]:
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x2861840)
	/fast/work/gopath/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:879 +0x7d
created by k8s.io/kubernetes/vendor/github.com/golang/glog.init.0
	/fast/work/gopath/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:410 +0x231

goroutine 130 [syscall, 2 minutes]:
os/signal.signal_recv(0x0)
	/usr/lib/go-1.9/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/lib/go-1.9/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/lib/go-1.9/src/os/signal/signal_unix.go:28 +0x41

goroutine 219 [select]:
net/http.(*Transport).getConn(0xc4200e45a0, 0xc421504330, 0x0, 0xc420e54040, 0x5, 0xc420e54080, 0x13, 0x0, 0x0, 0x412b90)
	/usr/lib/go-1.9/src/net/http/transport.go:948 +0x5bf
net/http.(*Transport).RoundTrip(0xc4200e45a0, 0xc421098200, 0xa, 0xc420016500, 0x35)
	/usr/lib/go-1.9/src/net/http/transport.go:400 +0x6a6
k8s.io/kubernetes/vendor/k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc4207defc0, 0xc421098200, 0x0, 0x0, 0x0)
	/fast/work/gopath/src/k8s.io/kubernetes/vendor/k8s.io/client-go/transport/round_trippers.go:162 +0x20f
net/http.send(0xc421098100, 0x269a4c0, 0xc4207defc0, 0x0, 0x0, 0x0, 0xc4200d80d0, 0x100, 0xc421701c60, 0x1)
	/usr/lib/go-1.9/src/net/http/client.go:249 +0x1a9
net/http.(*Client).send(0xc420ba49c0, 0xc421098100, 0x0, 0x0, 0x0, 0xc4200d80d0, 0x0, 0x1, 0xc421701ce8)
	/usr/lib/go-1.9/src/net/http/client.go:173 +0xfd
net/http.(*Client).Do(0xc420ba49c0, 0xc421098100, 0x0, 0x1f, 0x0)
	/usr/lib/go-1.9/src/net/http/client.go:602 +0x28d
k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Request).request(0xc420504180, 0xc4217020a8, 0x0, 0x0)
	/fast/work/gopath/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:663 +0x845
k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Request).Do(0xc420504180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/fast/work/gopath/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:735 +0x11e
k8s.io/kubernetes/vendor/k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroups(0xc4207df040, 0x0, 0x0, 0x0)
	/fast/work/gopath/src/k8s.io/kubernetes/vendor/k8s.io/client-go/discovery/discovery_client.go:128 +0x1b9
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*CachedDiscoveryClient).ServerGroups(0xc4200d7ec0, 0x0, 0x0, 0x0)
	/fast/work/gopath/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/cached_discovery.go:122 +0x263
k8s.io/kubernetes/pkg/kubectl/cmd/util.(*CachedDiscoveryClient).ServerResources(0xc4200d7ec0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/fast/work/gopath/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/cached_discovery.go:94 +0xa0
k8s.io/kubernetes/pkg/kubectl/categories.discoveryFilteredExpander.Expand(0x269b9c0, 0xc420256ab0, 0x7f1774ab4588, 0xc4200d7ec0, 0x1c3ed41, 0x4, 0x0, 0x0, 0x0, 0xc421702b00)
	/fast/work/gopath/src/k8s.io/kubernetes/pkg/kubectl/categories/categories.go:108 +0x175
k8s.io/kubernetes/pkg/kubectl/categories.(*discoveryFilteredExpander).Expand(0xc4207df060, 0x1c3ed41, 0x4, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:1 +0xe0
k8s.io/kubernetes/pkg/kubectl/categories.discoveryCategoryExpander.Expand(0x269ba40, 0xc4207df060, 0x7f1774ab4588, 0xc4200d7ec0, 0x1c3ed41, 0x4, 0x0, 0x0, 0x0, 0x0)
	/fast/work/gopath/src/k8s.io/kubernetes/pkg/kubectl/categories/categories.go:55 +0x14d
k8s.io/kubernetes/pkg/kubectl/categories.(*discoveryCategoryExpander).Expand(0xc4207df080, 0x1c3ed41, 0x4, 0x0, 0x0, 0x0, 0x0)
	<autogenerated>:1 +0xe0
k8s.io/kubernetes/pkg/kubectl/resource.(*Builder).ReplaceAliases(0xc42095eb40, 0x1c3ed41, 0xd, 0x0, 0x0)
	/fast/work/gopath/src/k8s.io/kubernetes/pkg/kubectl/resource/builder.go:490 +0x1b3
k8s.io/kubernetes/pkg/kubectl/resource.(*Builder).ResourceTypeOrNameArgs(0xc42095eb40, 0x101, 0xc4219b3ea0, 0x1, 0x1, 0x0)
	/fast/work/gopath/src/k8s.io/kubernetes/pkg/kubectl/resource/builder.go:463 +0x7b9
k8s.io/kubernetes/pkg/kubectl/cmd/resource.(*GetOptions).Run(0xc4200e23c0, 0x26c57c0, 0xc42170f880, 0xc420752000, 0xc4219b3ea0, 0x1, 0x1, 0x0, 0x0)
	/fast/work/gopath/src/k8s.io/kubernetes/pkg/kubectl/cmd/resource/get.go:249 +0x3f1
k8s.io/kubernetes/pkg/kubectl/cmd/resource.NewCmdGet.func1(0xc420752000, 0xc4219b3ea0, 0x1, 0x1)
	/fast/work/gopath/src/k8s.io/kubernetes/pkg/kubectl/cmd/resource/get.go:142 +0x15b
k8s.io/kubernetes/pkg/kubectl/cmd/resource.TestGetMultipleTypeObjectsAsList(0xc4200e44b0)
	/fast/work/gopath/src/k8s.io/kubernetes/pkg/kubectl/cmd/resource/get_test.go:822 +0x6b0
testing.tRunner(0xc4200e44b0, 0x1cc83c8)
	/usr/lib/go-1.9/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/lib/go-1.9/src/testing/testing.go:789 +0x2de

goroutine 72 [IO wait]:
internal/poll.runtime_pollWait(0x7f1774a97f00, 0x77, 0xc420025900)
	/usr/lib/go-1.9/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc421d58318, 0x77, 0xc420f83100, 0x436b5b, 0xc420f83120)
	/usr/lib/go-1.9/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitWrite(0xc421d58318, 0xc420f83100, 0xc420f83158, 0x58e033)
	/usr/lib/go-1.9/src/internal/poll/fd_poll_runtime.go:94 +0x3d
internal/poll.(*FD).WaitWrite(0xc421d58300, 0x1cc9fa8, 0x26b5d00)
	/usr/lib/go-1.9/src/internal/poll/fd_unix.go:403 +0x37
net.(*netFD).connect(0xc421d58300, 0x26b5d00, 0xc42178e1e0, 0x0, 0x0, 0x269b040, 0xc420e540a0, 0x0, 0x0, 0x0, ...)
	/usr/lib/go-1.9/src/net/fd_unix.go:152 +0x2b6
net.(*netFD).dial(0xc421d58300, 0x26b5d00, 0xc42178e1e0, 0x26b87c0, 0x0, 0x26b87c0, 0xc421504420, 0xc420f83378, 0x5a96ee)
	/usr/lib/go-1.9/src/net/sock_posix.go:142 +0xe9
net.socket(0x26b5d00, 0xc42178e1e0, 0x1c37414, 0x3, 0x2, 0x1, 0x0, 0x0, 0x26b87c0, 0x0, ...)
	/usr/lib/go-1.9/src/net/sock_posix.go:93 +0x1a5
net.internetSocket(0x26b5d00, 0xc42178e1e0, 0x1c37414, 0x3, 0x26b87c0, 0x0, 0x26b87c0, 0xc421504420, 0x1, 0x0, ...)
	/usr/lib/go-1.9/src/net/ipsock_posix.go:141 +0x129
net.doDialTCP(0x26b5d00, 0xc42178e1e0, 0x1c37414, 0x3, 0x0, 0xc421504420, 0x2881e18, 0x0, 0x0)
	/usr/lib/go-1.9/src/net/tcpsock_posix.go:62 +0xb9
net.dialTCP(0x26b5d00, 0xc42178e1e0, 0x1c37414, 0x3, 0x0, 0xc421504420, 0xbe969231ef536603, 0x22e81c9b3a, 0x2861520)
	/usr/lib/go-1.9/src/net/tcpsock_posix.go:58 +0xe4
net.dialSingle(0x26b5d00, 0xc42178e1e0, 0xc421d58280, 0x26a5fc0, 0xc421504420, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.9/src/net/dial.go:547 +0x3e2
net.dialSerial(0x26b5d00, 0xc42178e1e0, 0xc421d58280, 0xc42195a100, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.9/src/net/dial.go:515 +0x247
net.(*Dialer).DialContext(0xc42072cfc0, 0x26b5cc0, 0xc42001a0e0, 0x1c37414, 0x3, 0xc420e54080, 0x13, 0x0, 0x0, 0x0, ...)
	/usr/lib/go-1.9/src/net/dial.go:397 +0x6ee
net.(*Dialer).Dial(0xc42072cfc0, 0x1c37414, 0x3, 0xc420e54080, 0x13, 0xc420756000, 0x120, 0x110, 0x1c12220)
	/usr/lib/go-1.9/src/net/dial.go:320 +0x75
net.(*Dialer).Dial-fm(0x1c37414, 0x3, 0xc420e54080, 0x13, 0x0, 0x0, 0x0, 0x0)
	/fast/work/gopath/src/k8s.io/kubernetes/vendor/k8s.io/client-go/transport/cache.go:87 +0xc0
net/http.(*Transport).dial(0xc4200e45a0, 0x26b5cc0, 0xc42001a0e0, 0x1c37414, 0x3, 0xc420e54080, 0x13, 0xc420112d80, 0xc420112da0, 0xc420112dc0, ...)
	/usr/lib/go-1.9/src/net/http/transport.go:887 +0x7b
net/http.(*Transport).dialConn(0xc4200e45a0, 0x26b5cc0, 0xc42001a0e0, 0x0, 0xc420e54040, 0x5, 0xc420e54080, 0x13, 0x4820b6, 0x5a79d0b9, ...)
	/usr/lib/go-1.9/src/net/http/transport.go:1060 +0x1d62
net/http.(*Transport).getConn.func4(0xc4200e45a0, 0x26b5cc0, 0xc42001a0e0, 0xc421504390, 0xc421f9c000)
	/usr/lib/go-1.9/src/net/http/transport.go:943 +0x78
created by net/http.(*Transport).getConn
	/usr/lib/go-1.9/src/net/http/transport.go:942 +0x393

goroutine 73 [select]:
net.(*netFD).connect.func2(0x26b5d00, 0xc42178e1e0, 0xc421d58300, 0xc421f9c1e0, 0xc421f9c180)
	/usr/lib/go-1.9/src/net/fd_unix.go:129 +0xf2
created by net.(*netFD).connect
	/usr/lib/go-1.9/src/net/fd_unix.go:128 +0x2a3
```

**What you expected to happen**:

The test should ignore ~/.kube entirely and pass regardless of what's in the config there.

**How to reproduce it (as minimally and precisely as possible)**:

This is the relevant subset of my `.kube/config` that triggers the issue:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/pohly/.minikube/ca.crt
    server: https://192.168.39.186:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    as-user-extra: {}
    client-certificate: /home/pohly/.minikube/client.crt
    client-key: /home/pohly/.minikube/client.key
```

A minimal command which fails is:
```
go test -v -exec "strace -f -e trace=openat,connect" -timeout 120s k8s.io/kubernetes/pkg/kubectl/cmd/resource
```

**Anything else we need to know?**:

Limiting the test run to just TestGetMultipleTypeObjectsAsList with `-run TestGetMultipleTypeObjectsAsList` does *not* fail. There are also failed connection attempts in tests that succeed.

**Environment**:
- Kubernetes version (use `kubectl version`): commit 68da45623f5b14f61d9ce51b4946c11e034eb25c
- OS (e.g. from /etc/os-release): Debian Stretch (9.0)
- Kernel (e.g. `uname -a`): 4.9.0-5-amd64

**Comment by pohly** [comment]
Let me add that `KUBECONFIG=/dev/null` as env variable can be used to work around the failure. Then strace shows no attempts to read ~/.kube and there is no connect system call. Tests also run much faster.

This could be done via the Makefile, but this doesn't look like the right solution to me because a plain "go test" command would still fail.

I started looking at the code in order to figure out where it reads .kube/config, but did not get very far. There is a ``defaultClientConfig()`` function in cmd_test.go,  so it looks like someone already tried to make the test independent from the actual configuration. Or I'm misunderstanding the code ;-} I'm pretty new to k8s...

**Comment by pohly** [comment]
> Let me add that KUBECONFIG=/dev/null as env variable can be used to work around the failure.

Hmm, not quite. I'm pretty sure that worked for `go test`, but a full `KUBECONFIG=/dev/null make test` just failed with:
```
...
ok  	k8s.io/kubernetes/pkg/kubectl/cmd/auth	0.146s
error: open /dev/null.lock: permission denied
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd/config	0.224s
....
```

**Comment by liggitt** [comment]
> a full KUBECONFIG=/dev/null make test just failed with:
> 
> ...
> error: open /dev/null.lock: permission denied

cc @cjcullen @krousey 
for problems with kubeconfig lock files

**Comment by pohly** [comment]
On Tue, 2018-02-06 at 19:04 +0000, Jordan Liggitt wrote:
> a full KUBECONFIG=/dev/null make test just failed with:
> ...
> error: open /dev/null.lock: permission denied
> cc @cjcullen @krousey
> for problems with kubeconfig lock files

To be fair, pointing KUBECONFIG to a special file like /dev/null is
probably not something that is worth supporting. I was just looking for
 a workaround other than "remove my ~/.kube directory".

**Comment by liggitt** [comment]
> I was just looking for a workaround other than "remove my ~/.kube directory".

isolating $HOME would probably work as well (e.g. `HOME=/tmp/foo make test`)

**Comment by cjcullen** [comment]
I'm fine w/ `KUBECONFIG=/dev/null` failing if you try to actually use a kubeconfig file, but we can probably make that test more hermetic.

**Comment by pohly** [comment]
Setting HOME works before invoking a test works. I am a bit concerned that doing it before invoking make and go - what if any of the commands used during building the tests need access to the original HOME? Is that a valid concern or do I just worry too much?

I experimented with os.Setenv() in a TestMain function, but that doesn't help because various global variables were already initialized with the original HOME value before TestMain even starts. In particular, RecommendedConfigDir in loader.go continues to use the original HOME.

So it seems to me that invoking test binaries with HOME set to an empty temporary directory is the safest approach for truly isolating unit tests from the local user's environment. While at it, we probably also should unset variables that could taint the testing (like KUBECONFIG).

Do you agree that this is the right approach?

Does the handling of KUBECONFIG described in https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#the-kubeconfig-environment-variable have unit tests? For those tests to be realistic, they would have to be invoked within KUBECONFIG set in various ways.

**Comment by pohly** [comment]
I've implemented the "temporary HOME and unset KUBECONFIG" proposal in PR #59648.

**Comment by pohly** [comment]
@cjcullen: "but we can probably make that test more hermetic" - how?

I tried a generic approach in PR #59648, but @liggitt prefers to have the test itself to behave the same independent of the environment.

**Comment by pohly** [comment]
> Setting HOME works before invoking a test works. I am a bit concerned that doing it before invoking make and go - what if any of the commands used during building the tests need access to the original HOME? Is that a valid concern or do I just worry too much?

I just want to add that the `HOME=/tmp/foo make test` workaround indeed fails for me when `make test` involves rebuilding more than just the tests. I've not investigated further why, but for example building `deepcopy-gen` fails.

So right now I either rebuild manually or use `make && HOME=/tmp/foo make test` when bisecting. I suspect the latter rebuilds more than what is strictly needed for testing and thus is slower.
