### ISSUE TITLE
local-up-cluster.sh broken by enhance kubeproxy init flag commit

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#60378]
```
/home/dims/go/src/k8s.io/kubernetes/_output/local/bin/linux/amd64/hyperkube flag redefined: config
panic: /home/dims/go/src/k8s.io/kubernetes/_output/local/bin/linux/amd64/hyperkube flag redefined: config

goroutine 1 [running]:
k8s.io/kubernetes/vendor/github.com/spf13/pflag.(*FlagSet).AddFlag(0xc4200b6000, 0xc420bc8dc0)
	/home/dims/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/pflag/flag.go:817 +0x9d2
k8s.io/kubernetes/vendor/github.com/spf13/pflag.(*FlagSet).VarPF(0xc4200b6000, 0xaf96b60, 0xc420c4ebb0, 0x4bf8e67, 0x6, 0x0, 0x0, 0x4c7f9b5, 0x23, 0x74a62f)
	/home/dims/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/pflag/flag.go:800 +0x120
k8s.io/kubernetes/vendor/github.com/spf13/pflag.(*FlagSet).VarP(0xc4200b6000, 0xaf96b60, 0xc420c4ebb0, 0x4bf8e67, 0x6, 0x0, 0x0, 0x4c7f9b5, 0x23)
	/home/dims/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/pflag/flag.go:806 +0x8e
k8s.io/kubernetes/vendor/github.com/spf13/pflag.(*FlagSet).StringVar(0xc4200b6000, 0xc420c4ebb0, 0x4bf8e67, 0x6, 0x0, 0x0, 0x4c7f9b5, 0x23)
	/home/dims/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/pflag/string.go:37 +0xa3
k8s.io/kubernetes/cmd/kube-proxy/app.(*Options).AddFlags(0xc420c4ebb0, 0xc4200b6000)
	/home/dims/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:122 +0x74
k8s.io/kubernetes/cmd/kube-proxy/app.NewProxyCommand(0x1)
	/home/dims/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:357 +0x250
main.NewHyperKubeCommand.func3(0xc4201a9440)
	/home/dims/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/hyperkube/main.go:102 +0x26
main.commandFor(0x7ffc9f1b3dec, 0x9, 0xc42052d680, 0xc4202f4380, 0x7, 0x7, 0x8ba6520)
	/home/dims/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/hyperkube/main.go:71 +0xdf
main.main()
	/home/dims/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/hyperkube/main.go:63 +0x230
```

**Comment by dims** [comment]
Caused by https://github.com/kubernetes/kubernetes/pull/57672

**Comment by dims** [comment]
Could be a clash between these two?

https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server.go#L122
https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-scheduler/app/server.go#L108

**Comment by dims** [comment]
cc @stewart-yu

**Comment by sbezverk** [comment]
@dims I still see the issue with local-cluster on the latest master:
F0225 17:06:49.216100   25765 helpers.go:119] error: v1alpha1.KubeProxyConfiguration: FeatureGates: ReadMapCB: expect { or n, but found ", error found in #10 byte of ...|reGates":"AllAlpha=f|..., bigger context ...|ubernetes/kube-proxy.kubeconfig"},"featureGates":"AllAlpha=false","hostnameOverride":"kube-4","kind"|...

**Comment by dims** [comment]
@sbezverk looks like that's another issue, can you please file a new bug? with more logs? this one was about none of the hyperkube based processes starting up.

**Comment by sbezverk** [comment]
@dims will do as it is also broke container kube-proxy as well. Same type of error.
