### ISSUE TITLE
kubelet API GET /stats/:pod/:container handler panics

### ISSUE THREAD

**Issue by SpComb** [kubernetes/kubernetes#61168]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

`GET /stats/:pod/whatever` requests to the kubelet API seem to panic the [`handler.handlePodContainer`](https://github.com/kubernetes/kubernetes/blob/v1.9.3/pkg/kubelet/server/stats/handler.go#L249) => [`StatsProvider.GetContainerInfo`](https://github.com/kubernetes/kubernetes/blob/v1.9.3/pkg/kubelet/stats/stats_provider.go#L139), presumably the `runtimeCache` is `nil`?

```
I0314 09:37:32.292894    1838 logs.go:41] http: panic serving [::1]:59092: runtime error: invalid memory address or nil pointer dereference
goroutine 572105 [running]:
net/http.(*conn).serve.func1(0xc4222ea6e0)
	/usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x3179200, 0x5721c20)
	/usr/local/go/src/runtime/panic.go:491 +0x283
k8s.io/kubernetes/pkg/kubelet/stats.(*StatsProvider).GetContainerInfo(0xc420cbe580, 0xc422396e60, 0x1f, 0x0, 0x0, 0xc4221600e3, 0x8, 0xc421150200, 0x0, 0x0, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/stats/stats_provider.go:139 +0x93
k8s.io/kubernetes/pkg/kubelet/server/stats.(*handler).handlePodContainer(0xc420d922a0, 0xc421c12c90, 0xc4210fba40)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/handler.go:249 +0x6b9
k8s.io/kubernetes/pkg/kubelet/server/stats.(*handler).(k8s.io/kubernetes/pkg/kubelet/server/stats.handlePodContainer)-fm(0xc421c12c90, 0xc4210fba40)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/handler.go:102 +0x3e
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc4209c8240, 0x576a940, 0xc42042c690, 0xc420b7c600)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:277 +0xb18
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x576a940, 0xc42042c690, 0xc420b7c600)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4204e0e70, 0x576a940, 0xc42042c690, 0xc420b7c600)
	/usr/local/go/src/net/http/server.go:1918 +0x44
net/http.(*ServeMux).ServeHTTP(0xc420b44330, 0x576a940, 0xc42042c690, 0xc420b7c600)
	/usr/local/go/src/net/http/server.go:2254 +0x130
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc4209c8240, 0x576a940, 0xc42042c690, 0xc420b7c600)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:292 +0x4d
k8s.io/kubernetes/pkg/kubelet/server.(*Server).ServeHTTP(0xc420276a00, 0x576a940, 0xc42042c690, 0xc420b7c600)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:795 +0x106
net/http.serverHandler.ServeHTTP(0xc420bd0000, 0x576b580, 0xc4202741c0, 0xc420b7c600)
	/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc4222ea6e0, 0x576da00, 0xc421150000)
	/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288
```

**What you expected to happen**:

Get some JSON response or a 404 error for an unknown container.

**How to reproduce it (as minimally and precisely as possible)**:

The `:pod` must exist, but the `:container` can be whatever. Oneliner repro case, assuming the node has some pod running in the default namespace:

```
$ curl -v http://localhost:10255/stats/$(curl -s http://localhost:10255/pods | jq -r 'first(.items[] | select(.metadata.namespace == "default")).metadata.name')/whatever
*   Trying ::1...
* Connected to localhost (::1) port 10255 (#0)
> GET /stats/whoami-66ffd9d657-gvz95/whatever HTTP/1.1
> Host: localhost:10255
> User-Agent: curl/7.47.0
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

The panic trace is visible in `journalctl -u kubelet`.

**Anything else we need to know?**:

This panic can be triggered as an unauthenticated request via the readonly kubelet API.

**Environment**:
- Kubernetes version (`kubelet --version`): `Kubernetes v1.9.3` 
- Cloud provider or hardware configuration: packet.net
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3
- Kernel (e.g. `uname -a`): `4.4.0-112-generic`
- Install tools: `kubeadm`
- Others:

**Comment by hzxuzhonghu** [comment]
can not reproduce on master.

**Comment by SpComb** [comment]
Upgraded to 1.9.4 and this is still panicing. I also noticed that kubeadm is configuring the kubelet with `--cadvisor-port=0`, but this still happens after reverting that to the default.

---

Oneliner repro case, assuming the node has some pod running in the default namespace:

```
curl -v http://localhost:10255/stats/$(curl -s http://localhost:10255/pods | jq -r 'first(.items[] | select(.metadata.namespace == "default")).metadata.name')/whatever
```

This results in an `curl: (52) Empty reply from server` error, and the panic trace is visible in `journalctl -u kubelet`.

**Comment by yokomotod** [comment]
I am facing the same issue on GKE with v1.9.6-gke.1

**Comment by astefanutti** [comment]
I looks like a duplicate of #56297 that has PR #62544 pending validation.

**Comment by astefanutti** [comment]
#62544 has been merged and should fix this issue.
