### ISSUE TITLE
azure unit test failing in my environment

### ISSUE THREAD

**Issue by CaoShuFeng** [kubernetes/kubernetes#61526]
When I run `make test` in community master branch:
I get such error:
```
E0322 14:38:04.340377   25735 azure_backoff.go:368] backoff: failure, will retry, HTTP response=400, err=<nil>
E0322 14:38:04.340656   25735 azure_backoff.go:368] backoff: failure, will retry, HTTP response=500, err=<nil>
E0322 14:38:04.340663   25735 azure_backoff.go:368] backoff: failure, will retry, HTTP response=303, err=some error
E0322 14:38:06.347457   25735 azure_loadbalancer.go:288] selectLoadBalancer: cluster(testCluster) service(default/service-2) isInternal(true) -  all available load balancers have exceeded maximum rule limit 1, vmSetNames ([as])
E0322 14:38:06.358666   25735 azure_loadbalancer.go:288] selectLoadBalancer: cluster(testCluster) service(default/service-2) isInternal(false) -  all available load balancers have exceeded maximum rule limit 1, vmSetNames ([as])
panic: test timed out after 6m0s

goroutine 521 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1145 +0xf9
created by time.goFunc
	/usr/local/go/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive, 5 minutes]:
testing.(*T).Run(0xc4200ea0f0, 0x13e0353, 0x14, 0x145db18, 0x1c98101)
	/usr/local/go/src/testing/testing.go:790 +0x2fc
testing.runTests.func1(0xc4200ea0f0)
	/usr/local/go/src/testing/testing.go:1004 +0x64
testing.tRunner(0xc4200ea0f0, 0xc420307de0)
	/usr/local/go/src/testing/testing.go:746 +0xd0
testing.runTests(0xc4203dbc60, 0x1c90a40, 0x4d, 0x4d, 0xc420307e80)
	/usr/local/go/src/testing/testing.go:1002 +0x2d8
testing.(*M).Run(0xc42027df18, 0x41340d)
	/usr/local/go/src/testing/testing.go:921 +0x111
main.main()
	k8s.io/kubernetes/pkg/cloudprovider/providers/azure/_test/_testmain.go:196 +0xdb

goroutine 19 [chan receive]:
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x1c983a0)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:879 +0x9f
created by k8s.io/kubernetes/vendor/github.com/golang/glog.init.0
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 503 [select, 3 minutes]:
k8s.io/kubernetes/vendor/github.com/Azure/go-autorest/autorest.DelayForBackoff(0x6fc23ac00, 0x3, 0x0, 0x1c2d140)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/Azure/go-autorest/autorest/sender.go:311 +0x16b
k8s.io/kubernetes/vendor/github.com/Azure/go-autorest/autorest.DoRetryForStatusCodes.func1.1(0xc420204500, 0xc4200b0d40, 0x0, 0xc42068aff8)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/Azure/go-autorest/autorest/sender.go:231 +0x1f8
k8s.io/kubernetes/vendor/github.com/Azure/go-autorest/autorest.SenderFunc.Do(0xc4200b0d40, 0xc420204500, 0xc42068aff8, 0x1, 0x1)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/Azure/go-autorest/autorest/sender.go:38 +0x30
k8s.io/kubernetes/vendor/github.com/Azure/go-autorest/autorest.SendWithSender(0x1c2cfc0, 0xc4200e8960, 0xc420204500, 0xc42068aff8, 0x1, 0x1, 0xc4200d98e0, 0x16, 0xc)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/Azure/go-autorest/autorest/sender.go:80 +0x75
k8s.io/kubernetes/vendor/github.com/Azure/go-autorest/autorest/azure.DoRetryWithRegistration.func1.1(0xc420204500, 0xc42010a120, 0x0, 0xc42068b260)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/Azure/go-autorest/autorest/azure/rp.go:40 +0x1d4
k8s.io/kubernetes/vendor/github.com/Azure/go-autorest/autorest.SenderFunc.Do(0xc42010a120, 0xc420204500, 0xc42068b260, 0x1, 0x1)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/Azure/go-autorest/autorest/sender.go:38 +0x30
k8s.io/kubernetes/vendor/github.com/Azure/go-autorest/autorest.SendWithSender(0x1c2cfc0, 0xc4200e8960, 0xc420204500, 0xc42068b260, 0x1, 0x1, 0x12a05f200, 0xd18c2e2800, 0x3)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/Azure/go-autorest/autorest/sender.go:80 +0x75
k8s.io/kubernetes/vendor/github.com/Azure/azure-sdk-for-go/arm/storage.AccountsClient.ListByResourceGroupSender(0x1c29780, 0xc4202509f0, 0x1c2ba00, 0xc4201fb920, 0x0, 0x0, 0x12a05f200, 0xd18c2e2800, 0x3, 0x6fc23ac00, ...)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/Azure/azure-sdk-for-go/arm/storage/accounts.go:596 +0x110
k8s.io/kubernetes/vendor/github.com/Azure/azure-sdk-for-go/arm/storage.AccountsClient.ListByResourceGroup(0x1c29780, 0xc4202509f0, 0x1c2ba00, 0xc4201fb920, 0x0, 0x0, 0x12a05f200, 0xd18c2e2800, 0x3, 0x6fc23ac00, ...)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/Azure/azure-sdk-for-go/arm/storage/accounts.go:558 +0x33b
k8s.io/kubernetes/pkg/cloudprovider/providers/azure.(*azStorageAccountClient).ListByResourceGroup(0xc42010c600, 0xc4200d8fe0, 0x12, 0x0, 0x0, 0x0, 0x0)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_client.go:1213 +0x256
k8s.io/kubernetes/pkg/cloudprovider/providers/azure.(*BlobDiskController).getAllStorageAccounts(0xc420250bb0, 0xc420250bb0, 0x1, 0xc42068b840)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_blobDiskController.go:435 +0x6b
k8s.io/kubernetes/pkg/cloudprovider/providers/azure.newBlobDiskController(0xc420562140, 0xc420562140, 0xc420215a70, 0xc4202158c0)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_blobDiskController.go:68 +0x6b
k8s.io/kubernetes/pkg/cloudprovider/providers/azure.initDiskControllers(0xc4200f8400, 0xc42000c540, 0x0)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure.go:390 +0xf4
k8s.io/kubernetes/pkg/cloudprovider/providers/azure.NewCloud(0x1c2c340, 0xc42000c040, 0x7ffc27f96c2a, 0xc420051f30, 0x101643e30, 0xf)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure.go:303 +0xe9e
k8s.io/kubernetes/pkg/cloudprovider/providers/azure.getCloudFromConfig(0xc4205761e0, 0x1455354, 0x2c6, 0x12a96362897337)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_test.go:1630 +0x80
k8s.io/kubernetes/pkg/cloudprovider/providers/azure.validateConfig(0xc4205761e0, 0x1455354, 0x2c6)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_test.go:1561 +0x43
k8s.io/kubernetes/pkg/cloudprovider/providers/azure.TestNewCloudFromJSON(0xc4205761e0)
	/home/fujitsu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_test.go:1510 +0x40
testing.tRunner(0xc4205761e0, 0x145db18)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de
FAIL	k8s.io/kubernetes/pkg/cloudprovider/providers/azure	360.046s

```

**Comment by andyzhangx** [comment]
@CaoShuFeng there are some error logs(could be regarded as warning) in azure cloud provider unit tests, while they all PASS, see below:

```
root@andy-dev:/code2/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/azure# go test -v
=== RUN   TestShouldRetry
--- PASS: TestShouldRetry (0.00s)
=== RUN   TestIsSuccessResponse
--- PASS: TestIsSuccessResponse (0.00s)
=== RUN   TestProcessRetryResponse
E0326 02:32:07.168333    8844 azure_backoff.go:368] backoff: failure, will retry, HTTP response=400, err=<nil>
E0326 02:32:07.170357    8844 azure_backoff.go:368] backoff: failure, will retry, HTTP response=500, err=<nil>
E0326 02:32:07.170377    8844 azure_backoff.go:368] backoff: failure, will retry, HTTP response=303, err=some error
--- PASS: TestProcessRetryResponse (0.00s)
=== RUN   TestCacheGet
--- PASS: TestCacheGet (0.00s)
=== RUN   TestCacheGetError
--- PASS: TestCacheGetError (0.00s)
=== RUN   TestCacheDelete
--- PASS: TestCacheDelete (0.00s)
=== RUN   TestCacheExpired
--- PASS: TestCacheExpired (2.00s)
=== RUN   TestFindProbe
--- PASS: TestFindProbe (0.00s)
=== RUN   TestAzureMetricLabelCardinality
--- PASS: TestAzureMetricLabelCardinality (0.00s)
=== RUN   TestAzureMetricLabelPrefix
--- PASS: TestAzureMetricLabelPrefix (0.00s)
=== RUN   TestDeleteRoute
--- PASS: TestDeleteRoute (0.00s)
=== RUN   TestCreateRoute
--- PASS: TestCreateRoute (0.00s)
=== RUN   TestCreateRouteTableIfNotExists_Exists
--- PASS: TestCreateRouteTableIfNotExists_Exists (0.00s)
=== RUN   TestCreateRouteTableIfNotExists_NotExists
--- PASS: TestCreateRouteTableIfNotExists_NotExists (0.00s)
=== RUN   TestCreateRouteTable
--- PASS: TestCreateRouteTable (0.00s)
=== RUN   TestProcessRoutes
--- PASS: TestProcessRoutes (0.00s)
=== RUN   TestIsMasterNode
--- PASS: TestIsMasterNode (0.00s)
=== RUN   TestGetLastSegment
--- PASS: TestGetLastSegment (0.00s)
=== RUN   TestGenerateStorageAccountName
--- PASS: TestGenerateStorageAccountName (0.00s)
=== RUN   TestMapLoadBalancerNameToVMSet
--- PASS: TestMapLoadBalancerNameToVMSet (0.00s)
=== RUN   TestCreateFileShare
--- PASS: TestCreateFileShare (0.00s)
=== RUN   TestGetStorageAccessKeys
--- PASS: TestGetStorageAccessKeys (0.00s)
=== RUN   TestParseConfig
--- PASS: TestParseConfig (0.00s)
=== RUN   TestFlipServiceInternalAnnotation
--- PASS: TestFlipServiceInternalAnnotation (0.00s)
=== RUN   TestAddPort
--- PASS: TestAddPort (0.00s)
=== RUN   TestLoadBalancerInternalServiceModeSelection
E0326 02:32:09.181112    8844 azure_loadbalancer.go:288] selectLoadBalancer: cluster(testCluster) service(default/service-2) isInternal(true) -  all available load balancers have exceeded maximum rule limit 1, vmSetNames ([as])
--- PASS: TestLoadBalancerInternalServiceModeSelection (0.01s)
=== RUN   TestLoadBalancerExternalServiceModeSelection
E0326 02:32:09.191017    8844 azure_loadbalancer.go:288] selectLoadBalancer: cluster(testCluster) service(default/service-2) isInternal(false) -  all available load balancers have exceeded maximum rule limit 1, vmSetNames ([as])
--- PASS: TestLoadBalancerExternalServiceModeSelection (0.01s)
=== RUN   TestReconcileLoadBalancerAddServiceOnInternalSubnet
--- PASS: TestReconcileLoadBalancerAddServiceOnInternalSubnet (0.00s)
=== RUN   TestReconcileSecurityGroupFromAnyDestinationAddressPrefixToLoadBalancerIP
--- PASS: TestReconcileSecurityGroupFromAnyDestinationAddressPrefixToLoadBalancerIP (0.00s)
=== RUN   TestReconcileSecurityGroupDynamicLoadBalancerIP
--- PASS: TestReconcileSecurityGroupDynamicLoadBalancerIP (0.00s)
=== RUN   TestReconcileLoadBalancerAddServicesOnMultipleSubnets
--- PASS: TestReconcileLoadBalancerAddServicesOnMultipleSubnets (0.00s)
=== RUN   TestReconcileLoadBalancerEditServiceSubnet
--- PASS: TestReconcileLoadBalancerEditServiceSubnet (0.00s)
=== RUN   TestReconcileLoadBalancerNodeHealth
--- PASS: TestReconcileLoadBalancerNodeHealth (0.00s)
=== RUN   TestReconcileLoadBalancerRemoveService
--- PASS: TestReconcileLoadBalancerRemoveService (0.00s)
=== RUN   TestReconcileLoadBalancerRemoveAllPortsRemovesFrontendConfig
--- PASS: TestReconcileLoadBalancerRemoveAllPortsRemovesFrontendConfig (0.00s)
=== RUN   TestReconcileLoadBalancerRemovesPort
--- PASS: TestReconcileLoadBalancerRemovesPort (0.00s)
=== RUN   TestReconcileLoadBalancerMultipleServices
--- PASS: TestReconcileLoadBalancerMultipleServices (0.00s)
=== RUN   TestServiceDefaultsToNoSessionPersistence
--- PASS: TestServiceDefaultsToNoSessionPersistence (0.00s)
=== RUN   TestServiceRespectsNoSessionAffinity
--- PASS: TestServiceRespectsNoSessionAffinity (0.00s)
=== RUN   TestServiceRespectsClientIPSessionAffinity
--- PASS: TestServiceRespectsClientIPSessionAffinity (0.00s)
=== RUN   TestReconcileSecurityGroupNewServiceAddsPort
--- PASS: TestReconcileSecurityGroupNewServiceAddsPort (0.00s)
=== RUN   TestReconcileSecurityGroupNewInternalServiceAddsPort
--- PASS: TestReconcileSecurityGroupNewInternalServiceAddsPort (0.00s)
=== RUN   TestReconcileSecurityGroupRemoveService
--- PASS: TestReconcileSecurityGroupRemoveService (0.00s)
=== RUN   TestReconcileSecurityGroupRemoveServiceRemovesPort
--- PASS: TestReconcileSecurityGroupRemoveServiceRemovesPort (0.00s)
=== RUN   TestReconcileSecurityWithSourceRanges
--- PASS: TestReconcileSecurityWithSourceRanges (0.00s)
=== RUN   TestReconcilePublicIPWithNewService
--- PASS: TestReconcilePublicIPWithNewService (0.00s)
=== RUN   TestReconcilePublicIPRemoveService
--- PASS: TestReconcilePublicIPRemoveService (0.00s)
=== RUN   TestReconcilePublicIPWithInternalService
--- PASS: TestReconcilePublicIPWithInternalService (0.00s)
=== RUN   TestReconcilePublicIPWithExternalAndInternalSwitch
--- PASS: TestReconcilePublicIPWithExternalAndInternalSwitch (0.00s)
=== RUN   TestSecurityRulePriorityPicksNextAvailablePriority
--- PASS: TestSecurityRulePriorityPicksNextAvailablePriority (0.00s)
=== RUN   TestSecurityRulePriorityFailsIfExhausted
--- PASS: TestSecurityRulePriorityFailsIfExhausted (0.06s)
=== RUN   TestProtocolTranslationTCP
--- PASS: TestProtocolTranslationTCP (0.00s)
=== RUN   TestProtocolTranslationUDP
--- PASS: TestProtocolTranslationUDP (0.00s)
=== RUN   TestNewCloudFromJSON
E0326 02:32:09.371817    8844 azure_blobDiskController.go:70] azureDisk - getAllStorageAccounts error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/--subscription-id--/resourceGroups/--resource-group--/providers/Microsoft.Storage/storageAccounts?api-version=2017-06-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"AADSTS90002: Requested tenant identifier '--tenant-id--' is not valid.\r\nTrace ID: c73fa040-1e0c-4598-b5fb-fad9e76a2100\r\nCorrelation ID: 8b09d70e-20ee-4707-92f4-5c2f401cc7a2\r\nTimestamp: 2018-03-26 02:32:09Z","error_codes":[90002],"timestamp":"2018-03-26 02:32:09Z","trace_id":"c73fa040-1e0c-4598-b5fb-fad9e76a2100","correlation_id":"8b09d70e-20ee-4707-92f4-5c2f401cc7a2"}
--- PASS: TestNewCloudFromJSON (0.12s)
=== RUN   TestCloudDefaultConfigFromJSON
E0326 02:32:09.372035    8844 azure_blobDiskController.go:70] azureDisk - getAllStorageAccounts error: storage.AccountsClient#ListByResourceGroup: Invalid input: autorest/validation: validation failed: parameter=resourceGroupName constraint=MinLength value="" details: value length must be greater than or equal to 1
--- PASS: TestCloudDefaultConfigFromJSON (0.00s)
=== RUN   TestCloudDefaultConfigFromYAML
E0326 02:32:09.372168    8844 azure_blobDiskController.go:70] azureDisk - getAllStorageAccounts error: storage.AccountsClient#ListByResourceGroup: Invalid input: autorest/validation: validation failed: parameter=resourceGroupName constraint=MinLength value="" details: value length must be greater than or equal to 1
--- PASS: TestCloudDefaultConfigFromYAML (0.00s)
=== RUN   TestNewCloudFromYAML
E0326 02:32:09.383905    8844 azure_blobDiskController.go:70] azureDisk - getAllStorageAccounts error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/--subscription-id--/resourceGroups/--resource-group--/providers/Microsoft.Storage/storageAccounts?api-version=2017-06-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"AADSTS90002: Requested tenant identifier '--tenant-id--' is not valid.\r\nTrace ID: 3c880ae2-757b-4a1a-84a7-88edb2c82000\r\nCorrelation ID: 68eb3e3b-6961-4230-9ea1-fd8c75b62ecf\r\nTimestamp: 2018-03-26 02:32:09Z","error_codes":[90002],"timestamp":"2018-03-26 02:32:09Z","trace_id":"3c880ae2-757b-4a1a-84a7-88edb2c82000","correlation_id":"68eb3e3b-6961-4230-9ea1-fd8c75b62ecf"}
--- PASS: TestNewCloudFromYAML (0.01s)
=== RUN   TestGetZone
--- PASS: TestGetZone (0.00s)
=== RUN   TestFetchFaultDomain
--- PASS: TestFetchFaultDomain (0.00s)
=== RUN   TestDecodeInstanceInfo
--- PASS: TestDecodeInstanceInfo (0.00s)
=== RUN   TestGetNodeNameByProviderID
--- PASS: TestGetNodeNameByProviderID (0.00s)
=== RUN   TestMetadataURLGeneration
--- PASS: TestMetadataURLGeneration (0.00s)
=== RUN   TestMetadataParsing
--- PASS: TestMetadataParsing (0.00s)
=== RUN   TestIfServiceSpecifiesSharedRuleAndRuleDoesNotExistItIsCreated
--- PASS: TestIfServiceSpecifiesSharedRuleAndRuleDoesNotExistItIsCreated (0.00s)
=== RUN   TestIfServiceSpecifiesSharedRuleAndRuleExistsThenTheServicesPortAndAddressAreAdded
--- PASS: TestIfServiceSpecifiesSharedRuleAndRuleExistsThenTheServicesPortAndAddressAreAdded (0.00s)
=== RUN   TestIfServicesSpecifySharedRuleButDifferentPortsThenSeparateRulesAreCreated
--- PASS: TestIfServicesSpecifySharedRuleButDifferentPortsThenSeparateRulesAreCreated (0.00s)
=== RUN   TestIfServicesSpecifySharedRuleButDifferentProtocolsThenSeparateRulesAreCreated
--- PASS: TestIfServicesSpecifySharedRuleButDifferentProtocolsThenSeparateRulesAreCreated (0.00s)
=== RUN   TestIfServicesSpecifySharedRuleButDifferentSourceAddressesThenSeparateRulesAreCreated
--- PASS: TestIfServicesSpecifySharedRuleButDifferentSourceAddressesThenSeparateRulesAreCreated (0.00s)
=== RUN   TestIfServicesSpecifySharedRuleButSomeAreOnDifferentPortsThenRulesAreSeparatedOrConsoliatedByPort
--- PASS: TestIfServicesSpecifySharedRuleButSomeAreOnDifferentPortsThenRulesAreSeparatedOrConsoliatedByPort (0.00s)
=== RUN   TestIfServiceSpecifiesSharedRuleAndServiceIsDeletedThenTheServicesPortAndAddressAreRemoved
--- PASS: TestIfServiceSpecifiesSharedRuleAndServiceIsDeletedThenTheServicesPortAndAddressAreRemoved (0.00s)
=== RUN   TestIfSomeServicesShareARuleAndOneIsDeletedItIsRemovedFromTheRightRule
--- PASS: TestIfSomeServicesShareARuleAndOneIsDeletedItIsRemovedFromTheRightRule (0.00s)
=== RUN   TestIfServiceSpecifiesSharedRuleAndLastServiceIsDeletedThenRuleIsDeleted
--- PASS: TestIfServiceSpecifiesSharedRuleAndLastServiceIsDeletedThenRuleIsDeleted (0.00s)
=== RUN   TestCanCombineSharedAndPrivateRulesInSameGroup
--- PASS: TestCanCombineSharedAndPrivateRulesInSameGroup (0.00s)
=== RUN   TestExtractVmssVMName
E0326 02:32:09.387692    8844 azure_vmss_cache.go:52] Failed to extract vmssVMName "vm1234"
E0326 02:32:09.387709    8844 azure_vmss_cache.go:52] Failed to extract vmssVMName "vm-1234"
--- PASS: TestExtractVmssVMName (0.00s)
=== RUN   TestGetScaleSetVMInstanceID
--- PASS: TestGetScaleSetVMInstanceID (0.00s)
=== RUN   TestGetInstanceIDByNodeName
--- PASS: TestGetInstanceIDByNodeName (0.00s)
=== RUN   TestExtractNotFound
--- PASS: TestExtractNotFound (0.00s)
PASS
ok      k8s.io/kubernetes/pkg/cloudprovider/providers/azure     2.236s
```

**Comment by CaoShuFeng** [comment]
Some azure unit tests need access to the Internet, so they fail in my environment.
