### ISSUE TITLE
cant resolve localhost address

### ISSUE THREAD

**Issue by w5750584** [kubernetes/kubernetes#62008]
我在deploy里面跑了一个java应用，在启动的时候提示一下错误信息:
我google搜索了这个错误信息，别人说需要将hostname绑定到127.0.0.1
但是，pod的名字不是固定的，如何绑定pod的名称。

Apr 02, 2018 10:29:17 AM redis.clients.jedis.HostAndPort getLocalHostQuietly
SEVERE: cant resolve localhost address
java.net.UnknownHostException: xxxr-7bc6dff48d-mm8hl: xxxr-7bc6dff48d-mm8hl: Name or service not kn
own
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
	at redis.clients.jedis.HostAndPort.getLocalHostQuietly(HostAndPort.java:105)
	at redis.clients.jedis.HostAndPort.<clinit>(HostAndPort.java:12)

**Comment by dims** [comment]
Please use stackoverflow for support questions
/close
