### ISSUE TITLE
Local traffic policy not working on Windows

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubernetes#62046]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

Also onlyNodeLocalEndpoints is handled when processing service updates in `pkg/proxy/winkernel`, it is not used in syncProxyRules.

We should fix this and cherry-pick to old releases.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by PatrickLang** [comment]
@daschott - can you see if this is possible in Windows Server 2019? Or are more changes needed.

**Comment by daschott** [comment]
@PatrickLang @feiskyer I don't understand the description -- what do you want me to test?

**Comment by feiskyer** [comment]
@daschott Local traffic policy requires DSR mode. Will it be possible in Windows Server 2019?

**Comment by daschott** [comment]
Sadly DSR mode is still not fully supported :( We still need to hold discussion about best course of action.

**Comment by PatrickLang** [comment]
/remove-lifecycle stale
This might be possible in v1.15 with Windows Server version 1903. Will check in April

**Comment by daschott** [comment]
DSR Mode should be possible on Windows Server, version 1903 and v1.14 with `WinDSR` feature gate passed in

**Comment by daschott** [comment]
Is non-DSR mode blocking any features or scenarios? Is there something we need to document as not being supported? Load-balancing should still work today, it is just that pod IPs will be SNAT'ed and it will be less performant. This means that network policy enforcement doesn't work for services. But network policies isn't documented yet and that will be included there.

 Can you describe @feiskyer what else is blocked?

**Comment by feiskyer** [comment]
@daschott AFAIK, only Local traffic policy is blocked for now.

**Comment by soggiest** [comment]
Hello! Code Freeze is just about on us. We'll be entering into Freeze tomorrow, May 31st. Is this still planned to land in 1.15?

**Comment by benmoss** [comment]
This has an additional implication: on services that are configured to `externalTrafficPolicy: "local"`, Windows nodes will still happily forward traffic to other nodes, whereas Linux nodes will drop packets instead of forwarding.

https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport

**Comment by feiskyer** [comment]
still pending on https://github.com/kubernetes/kubernetes/pull/62093#issuecomment-495326334.

**Comment by xmudrii** [comment]
@feiskyer Hello! I'm bug triage lead for the 1.16 release cycle and considering this issue is tagged for 1.16, but not updated for a long time, I'd like to check its status. The code freeze is starting on August 29th (about 1.5 weeks from now), which means that there should be a PR ready (and merged) until then.

Do we still target this issue to be fixed for 1.16?

**Comment by feiskyer** [comment]
> Do we still target this issue to be fixed for 1.16?

@ksubrmnn  @daschott Do we have updates on the DSR mode in Windows Server?

**Comment by daschott** [comment]
@feiskyer looking internally, it looks as though the minimum version with end-to-end DSR support is Build 18873 or above. So this should be included in 
 [Insider release 18945](https://blogs.windows.com/windowsexperience/2019/07/30/announcing-windows-server-vnext-insider-preview-build-18945/)

**Comment by feiskyer** [comment]
@daschott Thanks for the information. Do you think we're ok to report an error if Windows Server version is <18945?

**Comment by PatrickLang** [comment]
/milestone v1.17
We won't be testing Windows versions >18945 in 1.16. Maybe 1.17

**Comment by josiahbjorgaard** [comment]
Bug triage for 1.17 here. This issue has been open for a significant amount of time and since it is tagged for milestone 1.17, we want to let you know that the 1.17 code freeze is coming in less than one month on Nov. 18th. Will this issue be resolved before then?

**Comment by ksubrmnn** [comment]
@josiahbjorgaard I will be discussing this in the Sig-Windows meeting tomorrow so we can give an update then.

**Comment by josiahbjorgaard** [comment]
@ksubrmnn Were you able to get an update on the plans for this issue?

**Comment by josiahbjorgaard** [comment]
@PatrickLang Code freeze for v1.17 is upcoming this Thursday, should this issue be moved to v1.18?

**Comment by jtslear** [comment]
Hello @feiskyer, @ksubrmnn 
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March. Is this issue still intended for milestone 1.18?

**Comment by daschott** [comment]
I think this should be moved to milestone 1.19 or (more likely) 1.20. 
FYI DSR is also pending approval at Microsoft to be backported all the way to RS5 later this year, will keep this thread updated.

**Comment by jtslear** [comment]
@daschott thank you for following up.  I'll bump this to 1.19 for the time being, we can follow up again then.
/milestone v1.19

**Comment by bai** [comment]
👋 Hello from Bug Triage team! Wanted to follow up on this issue with a friendly reminder that the code freeze for 1.19 is starting June 25th (about 4 weeks from now).

As this issue is tagged for 1.19, is it still planned for this release?

**Comment by daschott** [comment]
This should be addressed here: https://github.com/kubernetes/kubernetes/pull/93166

**Comment by mkostersitz** [comment]
DSR mode back port to Server 2019 was completed and shipped in this year's 8C release of Windows Server 2019. It should be available in AKS by the mid of September. There is some work to be done to start the kubelet with the required flags to enable DSR mode. AKS will also have to have K8s 1.19 at least in preview at that point to enable it end 2 end.

**Comment by elweb9858** [comment]
The kube-proxy work to enable DSR mode via local traffic policy did not make it into k8s 1.19, it will likely be in 1.20. Like David mentioned, the changes are in progress here #93166

**Comment by immuzz** [comment]
SIG Windows Backlog Meeting 

@daschott Can we discuss this in the next SIG Windows Meeting. We thought this became part of K8s 1.19

**Comment by daschott** [comment]
@immuzz Just to be clear here, DSR support for Windows Server 2019 has landed in v1.19 (requires https://support.microsoft.com/en-us/help/4571748/windows-10-update-kb4571748). Local traffic policy will be coming in 1.20. We discussed this in SIG-Windows meeting on 07/21/2020 and reached this agreement, but definitely happy to discuss if there are any outstanding confusions!

**Comment by jeremyje** [comment]
@elweb9858 This change isn't complete. It does not provide healthchecks to the load balancer to indicate that the service is healthy and can direct traffic to it. I have a draft PR but I'm struggling to test it locally. https://github.com/kubernetes/kubernetes/compare/master...jeremyje:clientip

**Comment by elweb9858** [comment]
@jeremyje Hi Jeremy, I was not aware that my changes should address load balancer health checks. Were load balancer health checks something that existed before and my changes broke them? Or was this a feature you were expecting to be added along with the local traffic policy?

fyi @daschott

**Comment by jeremyje** [comment]
Test File

```bash
# Follow steps from https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/windows/README-GCE-Windows-kube-up.md. To setup the cluster, I increased the machine time size from 2 to 8 cores).
KUBE_BUILD_PLATFORMS="linux/amd64 windows/amd64" make quick-release
NODE_SIZE=e2-standard-8 NUM_NODES=2 NUM_WINDOWS_NODES=2 KUBE_GCE_ENABLE_IP_ALIASES=true KUBERNETES_NODE_PLATFORM=windows LOGGING_STACKDRIVER_RESOURCE_TYPES=new PROJECT=${CLOUDSDK_CORE_PROJECT} WINDOWS_NODE_OS_DISTRIBUTION=win1909 KUBE_UP_AUTOMATIC_CLEANUP=true ./cluster/kube-up.sh
```

Push a pod that will run on the service port.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: agnhost-fixed
  labels:
    app: agnhost-fixed
spec:
  containers:
  - args:
    - netexec
    image: k8s.gcr.io/e2e-test-images/agnhost:2.20
    name: agnhost-fixed
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
  nodeSelector:
    kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: agnhost-fixed
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: agnhost-fixed
```

Traversing the Services

```yaml
#kubectl get svc -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"agnhost-fixed","namespace":"default"},"spec":{"externalTrafficPolicy":"Local","ports":[{"name":"http","port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"agnhost-fixed"},"type":"LoadBalancer"}}
    creationTimestamp: "2020-11-13T22:23:55Z"
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          f:externalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector:
            .: {}
            f:app: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2020-11-13T22:23:55Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"service.kubernetes.io/load-balancer-cleanup": {}
        f:status:
          f:loadBalancer:
            f:ingress: {}
      manager: kube-controller-manager
      operation: Update
      time: "2020-11-13T22:25:29Z"
    name: agnhost-fixed
    namespace: default
    resourceVersion: "1632"
    uid: 4089dc73-60dc-4e55-97ec-ea386b6e9ae2
  spec:
    clusterIP: 10.0.14.65
    clusterIPs:
    - 10.0.14.65
    externalTrafficPolicy: Local
    healthCheckNodePort: 31062
    ports:
    - name: http
      nodePort: 30703
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: agnhost-fixed
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 34.70.5.133
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"hostinfo-dev-1809","namespace":"default"},"spec":{"ports":[{"port":8080,"targetPort":8080}],"selector":{"app":"hostinfo-dev-1809"},"type":"LoadBalancer"}}
    creationTimestamp: "2020-11-13T22:23:55Z"
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          f:externalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector:
            .: {}
            f:app: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: "2020-11-13T22:23:55Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"service.kubernetes.io/load-balancer-cleanup": {}
        f:status:
          f:loadBalancer:
            f:ingress: {}
      manager: kube-controller-manager
      operation: Update
      time: "2020-11-13T22:24:41Z"
    name: hostinfo-dev-1809
    namespace: default
    resourceVersion: "1530"
    uid: 74b7484e-7802-449c-8bae-8473defac5b2
  spec:
    clusterIP: 10.0.138.213
    clusterIPs:
    - 10.0.138.213
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 31389
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: hostinfo-dev-1809
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 35.226.99.189
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2020-11-13T22:18:39Z"
    labels:
      component: apiserver
      provider: kubernetes
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:component: {}
            f:provider: {}
        f:spec:
          f:clusterIP: {}
          f:ipFamilyPolicy: {}
          f:ports:
            .: {}
            k:{"port":443,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kube-apiserver
      operation: Update
      time: "2020-11-13T22:18:39Z"
    name: kubernetes
    namespace: default
    resourceVersion: "161"
    uid: 555404af-0e2d-48a9-a4d6-531016a1c507
  spec:
    clusterIP: 10.0.0.1
    clusterIPs:
    - 10.0.0.1
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

Pivot from the IP address I can find the forwarding rule of the [Google Compute Load Balancer](https://cloud.google.com/load-balancing/docs/using-forwarding-rules).

```yaml
gcloud compute forwarding-rules describe a4089dc7360dc4e5597ecea386b6e9ae --region us-central1 --format yaml
IPAddress: 34.70.5.133
IPProtocol: TCP
creationTimestamp: '2020-11-13T14:25:07.715-08:00'
description: '{"kubernetes.io/service-name":"default/agnhost-fixed"}'
fingerprint: xoZpMl7TTiY=
id: '2450600932719900972'
kind: compute#forwardingRule
loadBalancingScheme: EXTERNAL
name: a4089dc7360dc4e5597ecea386b6e9ae
networkTier: PREMIUM
portRange: 8080-8080
```

```yaml
gcloud compute target-pools describe a4089dc7360dc4e5597ecea386b6e9ae --region us-central1
creationTimestamp: '2020-11-13T14:25:02.989-08:00'
description: '{"kubernetes.io/service-name":"default/agnhost-fixed"}'
healthChecks:
- https://www.googleapis.com/compute/v1/projects/some-gce-project/global/httpHealthChecks/a4089dc7360dc4e5597ecea386b6e9ae
id: '3011763045874710865'
instances:
- https://www.googleapis.com/compute/v1/projects/some-gce-project/zones/us-central1-b/instances/kubernetes-minion-group-nvf8
- https://www.googleapis.com/compute/v1/projects/some-gce-project/zones/us-central1-b/instances/kubernetes-minion-group-ktjv
- https://www.googleapis.com/compute/v1/projects/some-gce-project/zones/us-central1-b/instances/kubernetes-windows-node-group-bg8m
- https://www.googleapis.com/compute/v1/projects/some-gce-project/zones/us-central1-b/instances/kubernetes-windows-node-group-8327
- https://www.googleapis.com/compute/v1/projects/some-gce-project/zones/us-central1-b/instances/kubernetes-master
kind: compute#targetPool
name: a4089dc7360dc4e5597ecea386b6e9ae
region: https://www.googleapis.com/compute/v1/projects/some-gce-project/regions/us-central1
selfLink: https://www.googleapis.com/compute/v1/projects/some-gce-project/regions/us-central1/targetPools/a4089dc7360dc4e5597ecea386b6e9ae
sessionAffinity: NONE
```

```yaml
gcloud compute http-health-checks describe a4089dc7360dc4e5597ecea386b6e9ae --format yaml
checkIntervalSec: 8
creationTimestamp: '2020-11-13T14:25:00.762-08:00'
description: '{"kubernetes.io/service-name":"a4089dc7360dc4e5597ecea386b6e9ae"}'
healthyThreshold: 1
host: ''
id: '3397215731962788179'
kind: compute#httpHealthCheck
name: a4089dc7360dc4e5597ecea386b6e9ae
port: 31062
requestPath: /healthz
selfLink: https://www.googleapis.com/compute/v1/projects/some-gce-project/global/httpHealthChecks/a4089dc7360dc4e5597ecea386b6e9ae
timeoutSec: 1
unhealthyThreshold: 3
```

I cannot figure out how to query the health status of each node but I have a screen shot of how this plays out.

![image](https://user-images.githubusercontent.com/1312331/99133770-3060af00-25d0-11eb-89d7-5f6a4e96f3ba.png)

**Comment by jeremyje** [comment]
The way GCE Load Balancer works in this context is if all nodes report unhealthy the load balancer will direct traffic to any random node. So in the example above you'd have a 1/5 chance of hitting the right node. https://cloud.google.com/load-balancing/docs/health-check-concepts#importance_of_firewall_rules

The UX is the request sometimes works but it's very slow to respond.

**Comment by daschott** [comment]
@jeremyje Does this issue also occur if you create a load balancer without the local traffic policy flag?

**Comment by jeremyje** [comment]
This only happens with local traffic policy mode. There's a proposed fix but I don't know how to run Windows centric unittests in winkernel.

See https://github.com/kubernetes/kubernetes/issues/62046#issuecomment-727073543

**Comment by jeremyje** [comment]
@elweb9858 @daschott I still having issues running the unit tests in pkg/proxy/winkernel/... The instructions at are not helpful.

Building on Windows gives this,

```powershell
go test k8s.io/kubernetes/pkg/proxy/winkernel/...
pkg\proxy\winkernel\proxier.go:36:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\api\core\v1
pkg\proxy\winkernel\proxier.go:33:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\api\discovery\v1beta1
pkg\apis\core\v1\helper\helpers.go:25:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\apimachinery\pkg\api\resource
pkg\apis\core\types.go:21:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\apimachinery\pkg\apis\meta\internalversion
pkg\apis\core\helper\helpers.go:25:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\apimachinery\pkg\apis\meta\v1
pkg\apis\core\helper\helpers.go:26:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\apimachinery\pkg\conversion
pkg\apis\core\helper\helpers.go:27:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\apimachinery\pkg\fields
pkg\apis\core\v1\helper\helpers.go:26:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\apimachinery\pkg\labels
pkg\apis\core\register.go:21:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\apimachinery\pkg\runtime
pkg\apis\core\objectreference.go:23:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\apimachinery\pkg\runtime\schema
pkg\apis\core\v1\helper\helpers.go:27:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\apimachinery\pkg\selection
pkg\proxy\winkernel\proxier.go:37:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\apimachinery\pkg\types
pkg\proxy\healthcheck\proxier_health.go:26:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\apimachinery\pkg\util\clock
pkg\proxy\winkernel\proxier.go:38:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\apimachinery\pkg\util\intstr
pkg\proxy\util\utils.go:29:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\apimachinery\pkg\util\rand
pkg\features\kube_features.go:20:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\apimachinery\pkg\util\runtime
pkg\apis\core\helper\helpers.go:30:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\apimachinery\pkg\util\sets
pkg\apis\core\v1\helper\helpers.go:28:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\apimachinery\pkg\util\validation
pkg\proxy\winkernel\proxier.go:39:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\apimachinery\pkg\util\wait
pkg\features\kube_features.go:21:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\apiserver\pkg\features
pkg\proxy\winkernel\proxier.go:40:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\apiserver\pkg\util\feature
pkg\proxy\config\config.go:26:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\client-go\informers\core\v1
pkg\proxy\config\config.go:27:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\client-go\informers\discovery\v1beta1
pkg\proxy\config\config.go:28:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\client-go\tools\cache
pkg\proxy\winkernel\proxier.go:41:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\client-go\tools\record
pkg\util\async\bounded_frequency_runner.go:24:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\client-go\util\flowcontrol
pkg\proxy\apis\config\types.go:25:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\component-base\config
pkg\features\kube_features.go:23:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\component-base\featuregate
pkg\proxy\winkernel\metrics.go:22:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\component-base\metrics
pkg\proxy\winkernel\metrics.go:23:2: cannot find package "." in:
        C:\Users\jeremyedwards\kubernetes\vendor\k8s.io\component-base\metrics\legacyregistry
```

Building on linux and running the test binary on Windows returns.

```powershell
.\winkernel.test.exe
--- FAIL: TestGetNetworkByName (0.15s)
    hns_test.go:115: hcnCreateNetwork failed in Win32: An adapter was not found. (0x803b0006) {"Success":false,"Error":"An adapter was not found. ","ErrorCode":2151350278}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x12a715d]

goroutine 8 [running]:
testing.tRunner.func1.1(0x13b3da0, 0x1f76ca0)
        /usr/lib/google-golang/src/testing/testing.go:1072 +0x310
testing.tRunner.func1(0xc0000c0900)
        /usr/lib/google-golang/src/testing/testing.go:1075 +0x43a
panic(0x13b3da0, 0x1f76ca0)
        /usr/lib/google-golang/src/runtime/panic.go:969 +0x1c7
k8s.io/kubernetes/pkg/proxy/winkernel.testGetNetworkByName(0xc0000c0900, 0x16f3840, 0x1fcb900)
        /usr/local/google/home/jeremyedwards/github/fasterboot/kubernetes/pkg/proxy/winkernel/hns_test.go:118 +0x9d
k8s.io/kubernetes/pkg/proxy/winkernel.TestGetNetworkByName(0xc0000c0900)
        /usr/local/google/home/jeremyedwards/github/fasterboot/kubernetes/pkg/proxy/winkernel/hns_test.go:46 +0x4a
testing.tRunner(0xc0000c0900, 0x15e2048)
        /usr/lib/google-golang/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
        /usr/lib/google-golang/src/testing/testing.go:1168 +0x2b3
```
