### ISSUE TITLE
api-server can not start up ,the cluster is installed by kubespray

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#62260]
@kubernetes/master
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened**:
api-server can not start up.
**What you expected to happen**:
api-server started up and running
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
```
logging error output: "k8s\x00\n\f\n\x02v1\x12\x06Status\x12\x99\x03\n\x06\n\x00\x12\x00\x1a\x00\x12\aFailure\x1a\xb1\x01Unable to refresh the initializer configuration: Get https://127.0.0.1:6443/apis/admissionregistration.k8s.io/v1alpha1/initializerconfigurations: net/http: TLS handshake timeout\"\x14LoadingConfiguration*\xb8\x01\n\x06create\x12\x00\x1a\x05nodes\"\xa0\x01\n\x1fInitializerConfigurationFailure\x12{An error has occurred while refreshing the initializer configuration, no resources can be created until a refresh succeeds.\x1a\x00(\x012\x000\xf4\x03\x1a\x00\"\x00"
 [[kubelet/v1.9.2+coreos.0 (linux/amd64) kubernetes/b427929] 192.168.1.44:48044]
I0409 01:31:57.049663       1 rbac.go:116] RBAC DENY: user "system:kube-scheduler" groups ["system:authenticated"] cannot "list" resource "nodes" cluster-wide
I0409 01:31:57.049881       1 wrap.go:42] GET /api/v1/nodes?limit=500&resourceVersion=0: (793.689µs) 403 [[hyperkube/v1.9.2+coreos.0 (linux/amd64) kubernetes/b427929/scheduler] 127.0.0.1:43000]
I0409 01:31:57.063457       1 node_authorizer.go:147] NODE DENY: unknown node "node5" cannot get pvc default/pvc-mariadb
I0409 01:31:57.063555       1 rbac.go:116] RBAC DENY: user "system:node:node5" groups ["system:nodes" "system:authenticated"] cannot "get" resource "persistentvolumeclaims" named "pvc-mariadb" in namespace "default"
I0409 01:31:57.063740       1 wrap.go:42] GET /api/v1/namespaces/default/persistentvolumeclaims/pvc-mariadb: (828.544µs) 403 [[kubelet/v1.9.2+coreos.0 (linux/amd64) kubernetes/b427929] 192.168.1.225:56894]
I0409 01:31:57.100645       1 rbac.go:116] RBAC DENY: user "system:kube-proxy" groups ["system:node-proxier" "system:authenticated"] cannot "list" resource "endpoints" cluster-wide
I0409 01:31:57.100889       1 wrap.go:42] GET /api/v1/endpoints?limit=500&resourceVersion=0: (782.055µs) 403 [[hyperkube/v1.9.2+coreos.0 (linux/amd64) kubernetes/b427929] 192.168.1.43:54444]
I0409 01:31:57.123852       1 rbac.go:116] RBAC DENY: user "system:kube-proxy" groups ["system:node-proxier" "system:authenticated"] cannot "list" resource "services" cluster-wide
I0409 01:31:57.124152       1 wrap.go:42] GET /api/v1/services?limit=500&resourceVersion=0: (823.973µs) 403 [[hyperkube/v1.9.2+coreos.0 (linux/amd64) kubernetes/b427929] 192.168.1.43:54444]
I0409 01:31:57.235261       1 rbac.go:116] RBAC DENY: user "system:kube-scheduler" groups ["system:authenticated"] cannot "list" resource "services" cluster-wide
I0409 01:31:57.235527       1 wrap.go:42] GET /api/v1/services?limit=500&resourceVersion=0: (836.163µs) 403 [[hyperkube/v1.9.2+coreos.0 (linux/amd64) kubernetes/b427929/scheduler] 127.0.0.1:43000]
I0409 01:31:57.263532       1 node_authorizer.go:147] NODE DENY: unknown node "node5" cannot get pvc default/gogs-data-v2
I0409 01:31:57.263600       1 rbac.go:116] RBAC DENY: user "system:node:node5" groups ["system:nodes" "system:authenticated"] cannot "get" resource "persistentvolumeclaims" named "gogs-data-v2" in namespace "default"
I0409 01:31:57.263917       1 wrap.go:42] GET /api/v1/namespaces/default/persistentvolumeclaims/gogs-data-v2: (984.722µs) 403 [[kubelet/v1.9.2+coreos.0 (linux/amd64) kubernetes/b427929] 192.168.1.225:56894]
I0409 01:31:57.326720       1 wrap.go:42] POST /api/v1/namespaces: (1.074328ms) 500
goroutine 8385 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc423139650, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc423139650, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc42624d040, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:188 +0xac
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.(*ResponseWriterDelegator).WriteHeader(0xc4267f3e60, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:227 +0x45
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x49ea065, 0x23, 0x7f7143e2db10, 0xc429fbb180, 0xa669a00, 0xc42604ac20, 0xc42c93a400, 0x1f4, 0xa64a6c0, 0xc42c93e3f0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:95 +0x8d
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x7f713fa0ecb0, 0xc425712060, 0xa66d640, 0xc420e5ab40, 0x0, 0x0, 0x4961418, 0x2, 0xa669a00, 0xc42604ac20, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:123 +0x32b
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.ErrorNegotiated(0x7f713fa0ecb0, 0xc425712060, 0xa634400, 0xc42c93e360, 0xa66d640, 0xc420e5ab40, 0x0, 0x0, 0x4961418, 0x2, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:142 +0x163
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.(*RequestScope).err(0xc423565680, 0xa634400, 0xc42c93e360, 0xa669a00, 0xc42604ac20, 0xc42c93a400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:67 +0x10c
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.createHandler.func1(0xa669a00, 0xc42604ac20, 0xc42c93a400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go:101 +0x1645
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints.restfulCreateResource.func1(0xc4267f3dd0, 0xc42c9293e0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1080 +0xd5
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc4267f3dd0, 0xc42c9293e0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:168 +0x208
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc420bc83f0, 0x7f713f81ae78, 0xc42604ac10, 0xc42c93a400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:277 +0xb18
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(0xc420bc83f0, 0x7f713f81ae78, 0xc42604ac10, 0xc42c93a400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:199 +0x57
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x497acd5, 0xe, 0xc420bc83f0, 0xc4206887e0, 0x7f713f81ae78, 0xc42604ac10, 0xc42c93a400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:153 +0x4e0
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc420bf9c60, 0x7f713f81ae78, 0xc42604ac10, 0xc42c93a400)
        <autogenerated>:1 +0x75
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc42afbf380, 0x7f713f81ae78, 0xc42604ac10, 0xc42c93a400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:254 +0x407
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc42333cc40, 0x7f713f81ae78, 0xc42604ac10, 0xc42c93a400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0xa1
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x497e839, 0xf, 0xc42425fa70, 0xc42333cc40, 0x7f713f81ae78, 0xc42604ac10, 0xc42c93a400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:161 +0x6ad
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc4272a6700, 0x7f713f81ae78, 0xc42604ac10, 0xc42c93a400)
        <autogenerated>:1 +0x75
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7f713f81ae78, 0xc42604ac10, 0xc42c93a400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:51 +0x37d
net/http.HandlerFunc.ServeHTTP(0xc422cf14f0, 0x7f713f81ae78, 0xc42604ac10, 0xc42c93a400)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7f713f81ae78, 0xc42604ac10, 0xc42c93a400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:95 +0x318
net/http.HandlerFunc.ServeHTTP(0xc422e1c700, 0x7f713f81ae78, 0xc42604ac10, 0xc42c93a400)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7f713f81ae78, 0xc42604ac10, 0xc42c93a400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:49 +0x203a
net/http.HandlerFunc.ServeHTTP(0xc422cf1540, 0x7f713f81ae78, 0xc42604ac10, 0xc42c93a400)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7f713f81ae78, 0xc42604ac10, 0xc42c93a400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:79 +0x2b1
net/http.HandlerFunc.ServeHTTP(0xc422cf1590, 0x7f713f81ae78, 0xc42604ac10, 0xc42c93a400)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x7f713f81ae78, 0xc42604ac10, 0xc42c93a400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc4272a6740, 0x7f713f81ae78, 0xc42604ac10, 0xc42c93a400)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc4272a67e0, 0xa670e80, 0xc42604ac10, 0xc42c93a400, 0xc42c8d98c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:93 +0x8d
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:92 +0x1ab

logging error output: "k8s\x00\n\f\n\x02v1\x12\x06Status\x12\x9e\x03\n\x06\n\x00\x12\x00\x1a\x00\x12\aFailure\x1a\xb1\x01Unable to refresh the initializer configuration: Get https://127.0.0.1:6443/apis/admissionregistration.k8s.io/v1alpha1/initializerconfigurations: net/http: TLS handshake timeout\"\x14LoadingConfiguration*\xbd\x01\n\x06create\x12\x00\x1a\nnamespaces\"\xa0\x01\n\x1fInitializerConfigurationFailure\x12{An error has occurred while refreshing the initializer configuration, no resources can be created until a refresh succeeds.\x1a\x00(\x012\x000\xf4\x03\x1a\x00\"\x00"
 [[hyperkube/v1.9.2+coreos.0 (linux/amd64) kubernetes/b427929] 127.0.0.1:42764]
E0409 01:31:57.327487       1 client_ca_hook.go:78] Unable to refresh the initializer configuration: Get https://127.0.0.1:6443/apis/admissionregistration.k8s.io/v1alpha1/initializerconfigurations: net/http: TLS handshake timeout
F0409 01:31:57.327537       1 hooks.go:188] PostStartHook "ca-registration" failed: unable to initialize client CA configmap: timed out waiting for the condition
```
**Environment**:
```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2+coreos.0", GitCommit:"b427929b2982726eeb64e985bc1ebb41aaa5e095", GitTreeState:"clean", BuildDate:"2018-01-18T22:56:14Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server 192.168.1.41:6443 was refused - did you specify the right host or port?
```

/sig scheduling
/kind bug

**Comment by 13567436138** [comment]
@kubernetes/Apps

**Comment by dims** [comment]
Can you please open a bug with kubespray? https://github.com/kubernetes-incubator/kubespray/issues

/close
