### ISSUE TITLE
Kubectl run returning error

### ISSUE THREAD

**Issue by GabrielSVinha** [kubernetes/kubernetes#62473]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

When I run `kubectl run -i --tty temp --image redis --command "/bin/bash"`, the following error shows up:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x140c46e]

goroutine 1 [running]:
k8s.io/kubernetes/pkg/kubectl/cmd.RunRun(0x2344c80, 0xc4207fa600, 0x231a080, 0xc42000c010, 0x231a0c0, 0xc42000c018, 0x231a0c0, 0xc42000c020, 0xc42055d400, 0xc42009fa40, ...)
	/workspace/anago-v1.10.0-rc.1.9+fc32d2f3698e36/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/run.go:328 +0x10ae
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdRun.func1(0xc42055d400, 0xc42009fa40, 0x2, 0x7)
	/workspace/anago-v1.10.0-rc.1.9+fc32d2f3698e36/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/run.go:105 +0x144
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc42055d400, 0xc42009f960, 0x7, 0x7, 0xc42055d400, 0xc42009f960)
	/workspace/anago-v1.10.0-rc.1.9+fc32d2f3698e36/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:757 +0x2c1
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42012fb80, 0xc420751ed8, 0xc420751ee0, 0x12a05f200)
	/workspace/anago-v1.10.0-rc.1.9+fc32d2f3698e36/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:843 +0x334
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42012fb80, 0x18c9378, 0x24e48e0)
	/workspace/anago-v1.10.0-rc.1.9+fc32d2f3698e36/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:791 +0x2b
main.main()
	/workspace/anago-v1.10.0-rc.1.9+fc32d2f3698e36/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:50 +0x196
```
**What you expected to happen**:
A new deployment is created and a connection to it is open.
**How to reproduce it (as minimally and precisely as possible)**:
Run the above command in a kubeadm cluster

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):Ubuntu 16.04
- Kernel (e.g. `uname -a`):4.13.0-38-generic
- Install tools:
- Others:

**Comment by janetkuo** [comment]
/sig cli 

This is fixed by #61713. The fix is cherrypicked to 1.10.
