### ISSUE TITLE
scheduler crash looping

### ISSUE THREAD

**Issue by stevvooe** [kubernetes/kubernetes#62501]
/kind bug

**What happened**:

When upgrading to 1.10.1 scheduler, it crashes continuously with the following trace:

```
$  kubectl logs -n kube-system kube-scheduler-sjd-bigdell
SIGILL: illegal instruction
PC=0x619d87 m=0 sigcode=2

goroutine 1 [running, locked to thread]:
k8s.io/kubernetes/vendor/github.com/golang/glog.Verbose.Infof(0x13e5e00, 0x16516fb, 0x21, 0xc42063be08, 0x1, 0x1)
	/workspace/anago-v1.10.1-beta.0.68+d4ab47518836c7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:1043 +0x7 fp=0xc42063bdc0 sp=0xc42063bdb8 pc=0x619d87
k8s.io/kubernetes/pkg/credentialprovider.RegisterCredentialProvider(0x1637aae, 0xa, 0x2035fa0, 0xc42038eb80)
	/workspace/anago-v1.10.1-beta.0.68+d4ab47518836c7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/credentialprovider/plugins.go:41 +0x150 fp=0xc42063be48 sp=0xc42063bdc0 pc=0x1298940
k8s.io/kubernetes/pkg/credentialprovider.init.0()
	/workspace/anago-v1.10.1-beta.0.68+d4ab47518836c7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/credentialprovider/provider.go:58 +0xa9 fp=0xc42063be88 sp=0xc42063be48 pc=0x1298b29
k8s.io/kubernetes/pkg/credentialprovider.init()
	<autogenerated>:1 +0x272 fp=0xc42063bed0 sp=0xc42063be88 pc=0x1299272
k8s.io/kubernetes/pkg/kubectl.init()
	<autogenerated>:1 +0x1d1 fp=0xc42063bf18 sp=0xc42063bed0 pc=0x1299a51
k8s.io/kubernetes/pkg/kubectl/cmd/util.init()
	<autogenerated>:1 +0xe1 fp=0xc42063bf60 sp=0xc42063bf18 pc=0x12a4d81
k8s.io/kubernetes/cmd/kube-scheduler/app.init()
	<autogenerated>:1 +0x101 fp=0xc42063bf70 sp=0xc42063bf60 pc=0x12def81
main.init()
	<autogenerated>:1 +0x6c fp=0xc42063bf80 sp=0xc42063bf70 pc=0x12e01bc
runtime.main()
	/usr/local/go/src/runtime/proc.go:183 +0x1de fp=0xc42063bfe0 sp=0xc42063bf80 pc=0x42d6ce
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42063bfe8 sp=0xc42063bfe0 pc=0x45d0a1

goroutine 5 [chan receive]:
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x21d5560)
	/workspace/anago-v1.10.1-beta.0.68+d4ab47518836c7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:879 +0x9f
created by k8s.io/kubernetes/vendor/github.com/golang/glog.init.0
	/workspace/anago-v1.10.1-beta.0.68+d4ab47518836c7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 36 [syscall]:
os/signal.signal_recv(0xc420016b40)
	/usr/local/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

rax    0xc42063be08
rbx    0x0
rcx    0xc4204acc10
rdx    0x0
rdi    0x1198
rsi    0x10
rbp    0xc42063be38
rsp    0xc42063bdb8
r8     0xc41ffda9a0
r9     0x4
r10    0x204a400
r11    0x8
r12    0x0
r13    0xf4
r14    0x74
r15    0x8
rip    0x619d87
rflags 0x10202
cs     0x33
fs     0x0
gs     0x0
```

Pods shows that it is in crash loop:

```
$ kubectl get --all-namespaces pods
NAMESPACE     NAME                                  READY     STATUS             RESTARTS   AGE
kube-system   etcd-sjd-bigdell                      1/1       Running            0          15m
kube-system   kube-apiserver-sjd-bigdell            1/1       Running            0          15m
kube-system   kube-controller-manager-sjd-bigdell   1/1       Running            0          15m
kube-system   kube-dns-86f4d74b45-bj9kh             3/3       Running            0          16m
kube-system   kube-proxy-4gsxj                      1/1       Running            0          16m
kube-system   kube-scheduler-sjd-bigdell            0/1       CrashLoopBackOff   4          3m
kube-system   weave-net-w7dxm                       2/2       Running            0          9m
```

**What you expected to happen**:

Should not crash.

**How to reproduce it (as minimally and precisely as possible)**:

Use kubeadm to upgrade scheduler kubelet to 1.10.1.

You can also edit /etc/kubernetes/manifests/kube-scheduler.yaml to point at k8s.gcr.io/kube-scheduler-amd64:v1.10.1.

**Anything else we need to know?**:

I am using the containerd runtime. Possibly an issue there.

Downgrading to 1.10.0 image works fine.

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: laptop
- OS (e.g. from /etc/os-release):

```
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.10"
VERSION_ID="17.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
```

- Kernel (e.g. `uname -a`):

```
$ uname -a 
Linux sjd-bigdell 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools: 
```
$  kubeadm version 
kubeadm version: &version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Others:

**Comment by stevvooe** [comment]
After some investigation, I've found that this might a problem with corruption, via the disk or at pull time. The actual image used here was `k8s.gcr.io/kube-scheduler-amd64:v1.10.1@sha256:34e37ff17af97c27afe12ed2e82fa3c9656d3bed12692e88b605f43b98145d14`. I've pulled this image with docker and in another containerd namespace, isolated from the CRI driven containers and it works fine, so the image is not the problem.

Below we can see the difference in the hash of the binary between the corrupt image, the first one and the working image, the second one:

```
$ sudo ctr -n k8s.io run -t k8s.gcr.io/kube-scheduler-amd64:v1.10.1 crashing6 sh
/ # sha256sum `which kube-scheduler`
17e2d56686ee257a8ad096bc87e5e2b07d466c92e7e5ad304cc7357bd8bf6afa  /usr/local/bin/kube-scheduler
/ # %
$ sudo ctr run -t k8s.gcr.io/kube-scheduler-amd64:v1.10.1 crashing7 sh
/ # sha256sum `which kube-scheduler`
ad44f1c248ce0b6c35b7c7c66567d6e8085f785a130a6a26fd238411088fab5b  /usr/local/bin/kube-scheduler
```

At this point, its pretty clear this is not a kubernetes bug.

**Comment by stevvooe** [comment]
Closing in favor of https://github.com/containerd/cri/issues/733.
