### ISSUE TITLE
kube-router start failed

### ISSUE THREAD

**Issue by ckeyer** [kubernetes/kubernetes#62527]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
```
kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml
```
```
I0413 08:55:24.415474       1 server.go:182] Running /usr/local/bin/kube-router version v0.2.0-beta.1, built on 2018-04-12, go1.8.7
I0413 08:55:24.417965       1 health_controller.go:127] Starting health controller
E0413 08:55:29.418108       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:29.418143       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:29.918119       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:29.918149       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:30.418134       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:30.418165       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:30.918136       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:30.918165       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:31.418152       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:31.418182       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:31.918090       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:31.918115       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:32.418109       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:32.418137       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:32.918057       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:32.918089       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:33.418090       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:33.418118       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:33.918145       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:33.918176       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:34.418150       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:34.418179       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:34.918032       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:34.918057       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:35.418050       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:35.418079       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:35.918140       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:35.918174       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:36.418153       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:36.418179       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:36.918112       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:36.918140       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:37.418095       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:37.418122       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:37.918121       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:37.918151       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:38.418077       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:38.418106       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:38.918184       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:38.918215       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:39.418053       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:39.418077       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:39.918038       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:39.918063       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:40.418065       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:40.418099       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:40.918037       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:40.918075       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:41.418043       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:41.418069       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:41.918033       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:41.918060       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:42.418090       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:42.418120       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:42.918092       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:42.918124       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:43.418116       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:43.418146       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:43.918120       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:43.918148       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:44.418147       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:44.418177       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:44.918048       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:44.918072       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:45.418058       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:45.418085       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:45.918149       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:45.918178       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:46.418129       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:46.418165       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:46.918121       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:46.918150       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:47.418074       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:47.418102       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:47.918156       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:47.918190       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:48.418055       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:48.418090       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:48.918215       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:48.918261       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:49.418046       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:49.418078       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:49.918156       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:49.918184       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:50.418050       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:50.418085       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:50.918195       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:50.918248       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:51.418057       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:51.418091       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:51.918105       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:51.918139       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:52.418198       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:52.418238       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:52.918179       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:52.918210       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:53.418071       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:53.418098       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:53.918175       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:53.918200       1 health_controller.go:100] Network Routing Controller heartbeat missed
E0413 08:55:54.418043       1 health_controller.go:93] Network Policy Controller heartbeat missed
E0413 08:55:54.418071       1 health_controller.go:100] Network Routing Controller heartbeat missed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x14b8f12]

goroutine 1 [running]:
github.com/cloudnativelabs/kube-router/app/controllers.NewNetworkPolicyController(0x2630500, 0xc420444d00, 0xc42029c7e0, 0x262a1c0, 0xc420172cf0, 0x262a1c0, 0xc420172ea0, 0x262a1c0, 0xc420172e10, 0x15, ...)
        /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/app/controllers/network_policy_controller.go:1474 +0xf2
github.com/cloudnativelabs/kube-router/app.(*KubeRouter).Run(0xc4202ecd80, 0x0, 0x0)
        /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/app/server.go:123 +0xcfa
main.Main(0x2601640, 0x0)
        /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/kube-router.go:66 +0x20d
main.main()
        /home/travis/gopath/src/github.com/cloudnativelabs/kube-router/kube-router.go:17 +0x26

```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.1-beta.0.15+027058c19b8fde-dirty", GitCommit:"027058c19b8fde1a8df247fb658b0a05bde9bd8b", GitTreeState:"dirty", BuildDate:"2018-01-05T06:23:07Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T20:55:30Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux gaea188 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools: `kubeadm`
- Others:

**Comment by dims** [comment]
please open the issue at https://github.com/cloudnativelabs/kube-router/issues

thanks!

/close
