### ISSUE TITLE
1.10.x upgrade causes api-server to consume a lot of resources and eventually oom

### ISSUE THREAD

**Issue by george-angel** [kubernetes/kubernetes#62538]
/kind bug
/sig api-machinery

**What happened**:

Upgrade from 1.9 (either 1.9.3 or 1.9.6) to 1.10 (either 1.10.0 or 1.10.1) - after a few hours of running, api server, starts throttling cpu at 100% and consuming more and more memory. Only error logs:

```
E0413 12:45:48.549420       1 authentication.go:63] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, Token has been invalidated]]
E0413 12:45:48.549680       1 errors.go:90] no context found for request
```

Other symptoms are: 
 - slow api server responses
 - nodes becoming `NotReady`

**What you expected to happen**:

Things to work.

**How to reproduce it (as minimally and precisely as possible)**:

Update version of hyperkube 1.9 > 1.10

**Anything else we need to know?**:

**Environment**:

etcd: v3.3.2

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1+coreos.0", GitCommit:"baafb306bb191971a84cb1796420d093de7e6014", GitTreeState:"clean", BuildDate:"2018-04-12T21:14:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

AWS
3 etcd instances
3 masters in ASG
3 workers in ASG

```
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=1688.5.3
VERSION_ID=1688.5.3
BUILD_ID=2018-04-03-0547
PRETTY_NAME="Container Linux by CoreOS 1688.5.3 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

```
Linux ip-10-66-23-26 4.14.32-coreos #1 SMP Tue Apr 3 05:21:26 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz GenuineIntel GNU/Linux
```
![2018-04-13-134312_2450x269_scrot](https://user-images.githubusercontent.com/1801067/38735914-3352c744-3f22-11e8-9594-16caed9dfc69.png)

Our api-server pod definition: https://github.com/utilitywarehouse/tf_kube_ignition/blob/master/resources/kube-apiserver.yaml

**Comment by jennybuckley** [comment]
cc @yliaog

**Comment by george-angel** [comment]
We have not lost track of this, just waiting for the failure to occur when we're awake to get that information, last one was ~03:00. Will update as soon possible.

**Comment by george-angel** [comment]
@jennybuckley We have two auto scaling groups for masters and workers. Both are managed via terraform. Kubelet is a rkt service, and is defined via userdata for the launch configurations. There we specify the hyperkube version.

On `terraform apply` we update both group's launch configurations. We also have a bash script: https://github.com/utilitywarehouse/kube-aws-updater

That will double the auto scaling groups size, wait for 2x capacity, then drain and terminate old nodes, and scale the group down to the original size. Same again for workers.

**Comment by yliaog** [comment]
i think there are two options to further diagnose the problem.

1. run pprof to see where the memory/cpu is used, following something like http://jeffmendoza.github.io/kubernetes/v1.0/docs/devel/profiling.html

2. turn on more verbose logging by adding --v=4 (or higher) to see if there is any useful logs emitted

**Comment by george-angel** [comment]
Some updates, the logs are extremely verbose and hard to navigate, we did however get pprof of cpu and memory (attached) of an increasingly broken master.

[pprof.cpu.pb.gz](https://github.com/kubernetes/kubernetes/files/1938470/pprof.cpu.pb.gz)
[pprof.heap.pb.gz](https://github.com/kubernetes/kubernetes/files/1938471/pprof.heap.pb.gz)

It looks like the problem is around grpc client, talking to etcd. Ours are TLS.

There is a fair number of ESTAB connections on masters and etcd nodes (~1000 - 500)

Looking through the code it looks like vendored version of grpc was updated ~2017-12 would that coincide with release of Kubernetes 1.10?

**Comment by george-angel** [comment]
Update, managed to consistently reproduce this issue now. The original time frame comes from us restarting etcd-member services and kubelets (masters and workers) every 6 hours.

As an `ExecStartPre` step, we create *new* certificates via a csr request to a cfssl server.

To produce the issue, we simply restart all our etcd-member services, they come up with new certificates. And immediately start logging a lot of:

```

May 02 16:34:21 ip-10-66-23-68 etcd-wrapper[9117]: 2018-05-02 16:34:21.357102 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 43.093623ms)
May 02 16:34:21 ip-10-66-23-68 etcd-wrapper[9117]: 2018-05-02 16:34:21.357109 W | etcdserver: server is likely overloaded
May 02 16:34:21 ip-10-66-23-68 etcd-wrapper[9117]: 2018-05-02 16:34:21.357115 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 43.146694ms)
May 02 16:34:21 ip-10-66-23-68 etcd-wrapper[9117]: 2018-05-02 16:34:21.357120 W | etcdserver: server is likely overloaded
May 02 16:34:21 ip-10-66-23-68 etcd-wrapper[9117]: 2018-05-02 16:34:21.363322 I | embed: rejected connection from "10.66.23.105:44524" (error "EOF", ServerName "")
May 02 16:34:21 ip-10-66-23-68 etcd-wrapper[9117]: 2018-05-02 16:34:21.639103 I | embed: rejected connection from "10.66.23.105:44656" (error "EOF", ServerName "")
May 02 16:34:21 ip-10-66-23-68 etcd-wrapper[9117]: 2018-05-02 16:34:21.646432 I | embed: rejected connection from "10.66.23.105:44654" (error "EOF", ServerName "")
May 02 16:34:21 ip-10-66-23-68 etcd-wrapper[9117]: 2018-05-02 16:34:21.672182 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 104.897002ms)
May 02 16:34:21 ip-10-66-23-68 etcd-wrapper[9117]: 2018-05-02 16:34:21.672381 W | etcdserver: server is likely overloaded
May 02 16:34:21 ip-10-66-23-68 etcd-wrapper[9117]: 2018-05-02 16:34:21.672494 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 105.210962ms)
May 02 16:34:21 ip-10-66-23-68 etcd-wrapper[9117]: 2018-05-02 16:34:21.672585 W | etcdserver: server is likely overloaded
```

api-servers start leaking memory and cpu is at 100%

![2018-05-02-173637_1814x265_scrot](https://user-images.githubusercontent.com/1801067/39537032-3cbb430c-4e30-11e8-9a08-79d9020aedf3.png)
 
Recreating masters fixes this (I suspect simply restarting api-server will actually be enough, I'll confirm and edit this in a few hours.)

**Comment by yliaog** [comment]
what are you running in the k8s cluster? don't understand why etcd would be 'immediately' overloaded

**Comment by george-angel** [comment]
Its basically an empty cluster apart from a few monitoring/logging agents. But that is a moot point, I suspect api-server is hanging on to connections in http2/grpc and tries to re-auth with the endpoint, which now has a different cert.

**Comment by yliaog** [comment]
i guess it could be a bug in the grpc client library, just to confirm, you don't see any problem if you don't restart etcd or change its certs in any way.

**Comment by george-angel** [comment]
Thats correct

**Comment by george-angel** [comment]
In a goroutine dump, there a lot of these `.../vendor/google.golang.org/grpc/credentials/credentials.go:150`:

```
goroutine 60201 [semacquire]:
sync.runtime_SemacquireMutex(0xc420a5a8ac, 0x0)
        /usr/local/go/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc420a5a8a8)
        /usr/local/go/src/sync/mutex.go:134 +0xee
sync.(*Pool).Get(0xb52b600, 0x4c089a0, 0xc442471aa0)
        /usr/local/go/src/sync/pool.go:133 +0xcd
math/big.getNat(0x9, 0xa)
        /usr/local/go/src/math/big/nat.go:540 +0x31
math/big.nat.divLarge(0x0, 0x0, 0x0, 0xc428613880, 0x9, 0xd, 0xc4286138f0, 0x9, 0xd, 0xc428613960, ...)
        /usr/local/go/src/math/big/nat.go:587 +0x78e
math/big.nat.div(0x0, 0x0, 0x0, 0xc428613880, 0x9, 0xd, 0xc4286138f0, 0x9, 0xd, 0xc428613960, ...)
        /usr/local/go/src/math/big/nat.go:532 +0x3c9
math/big.(*Int).QuoRem(0xc4426c2f28, 0xc4426c2fc8, 0xc4426c2ee8, 0xc4426c2fe8, 0x1, 0x5)
        /usr/local/go/src/math/big/int.go:227 +0xbf
math/big.(*Int).GCD(0xc4426c3068, 0xc4426c3168, 0x0, 0xc42701c1a0, 0xc4204eed20, 0xc4426c3088)
        /usr/local/go/src/math/big/int.go:481 +0x41a
math/big.(*Int).ModInverse(0xc4426c3168, 0xc42701c1a0, 0xc4204eed20, 0x0)
        /usr/local/go/src/math/big/int.go:590 +0x97
crypto/ecdsa.Verify(0xc4234585a0, 0xc440188240, 0x40, 0x40, 0xc42701c160, 0xc42701c1a0, 0x0)
        /usr/local/go/src/crypto/ecdsa/ecdsa.go:244 +0x597
crypto/x509.checkSignature(0xc, 0xc4314ccdce, 0x1dd, 0x2b2, 0xc4314ccfbb, 0x8a, 0xc5, 0x4686e80, 0xc4234585a0, 0x37, ...)
        /usr/local/go/src/crypto/x509/x509.go:885 +0x7aa
crypto/x509.(*Certificate).CheckSignature(0xc4213c0500, 0xc, 0xc4314ccdce, 0x1dd, 0x2b2, 0xc4314ccfbb, 0x8a, 0xc5, 0xc422043080, 0x9)
        /usr/local/go/src/crypto/x509/x509.go:823 +0x97
crypto/x509.(*Certificate).CheckSignatureFrom(0xc44551f900, 0xc4213c0500, 0xc431eb5940, 0x14)
        /usr/local/go/src/crypto/x509/x509.go:817 +0xf6
crypto/x509.(*CertPool).findVerifiedParents(0xc4230df7d0, 0xc44551f900, 0x406efc0, 0x1, 0xc437659ce0, 0xc4426c3468, 0x5241a7, 0xc437659ce0)
        /usr/local/go/src/crypto/x509/cert_pool.go:59 +0x11c
crypto/x509.(*Certificate).buildChains(0xc44551f900, 0xc4426c36c0, 0xc4426c3698, 0x1, 0x1, 0xc4426c3818, 0x0, 0x0, 0x3c67d1c, 0xe, ...)
        /usr/local/go/src/crypto/x509/verify.go:354 +0x54
crypto/x509.(*Certificate).Verify(0xc44551f900, 0xc420f6582f, 0xb, 0xc43766be00, 0xc4230df7d0, 0xbeb68137fa918db4, 0xa7ed1f69a9, 0xb52d8c0, 0x0, 0x0, ...)
        /usr/local/go/src/crypto/x509/verify.go:315 +0x6d6
crypto/tls.(*clientHandshakeState).doFullHandshake(0xc4426c3e88, 0xc427b81800, 0x3a)
        /usr/local/go/src/crypto/tls/handshake_client.go:300 +0x5b5
crypto/tls.(*Conn).clientHandshake(0xc444fd2a80, 0x4e75f58, 0xc444fd2ba0)
        /usr/local/go/src/crypto/tls/handshake_client.go:228 +0xf9b
crypto/tls.(*Conn).Handshake(0xc444fd2a80, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1307 +0x18f
k8s.io/kubernetes/vendor/google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake.func1(0xc436f77c20, 0xc444fd2a80)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/credentials/credentials.go:151 +0x2b
created by k8s.io/kubernetes/vendor/google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/credentials/credentials.go:150 +0x118
```

and `.../vendor/google.golang.org/grpc/clientconn.go:694`:

```
goroutine 59926 [select]:
k8s.io/kubernetes/vendor/google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake(0xc4213673f8, 0xb1a3ca0, 0xc43c8da180, 0xc420f6582f, 0x10, 0xb1b68e0, 0xc43d739180, 0x0, 0x0, 0x42dea8, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/credentials/credentials.go:153 +0x20c
k8s.io/kubernetes/vendor/google.golang.org/grpc/transport.newHTTP2Client(0xb1a3c20, 0xc42d3400c0, 0xc420f6582f, 0x10, 0x0, 0x0, 0x4ca1abb, 0xd, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/transport/http2_client.go:176 +0x1b14
k8s.io/kubernetes/vendor/google.golang.org/grpc/transport.NewClientTransport(0xb1a3c20, 0xc422121600, 0xc420f6582f, 0x10, 0x0, 0x0, 0x4ca1abb, 0xd, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/transport/transport.go:524 +0xbe
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*addrConn).resetTransport(0xc42cb1a400, 0xc4218e6ea0, 0xc4218e6ed8)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/clientconn.go:929 +0x2e5
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*addrConn).connect.func1(0xc42cb1a400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/clientconn.go:695 +0x2f
created by k8s.io/kubernetes/vendor/google.golang.org/grpc.(*addrConn).connect
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/clientconn.go:694 +0x40d
```

**Comment by george-angel** [comment]
With v=6 logging a lot of these messages:

```
logging error output: "{\"metadata\":{},\"status\":\"Failure\",\"message\":\"Timeout: request did not complete within 1m0s\",\"reason\":\"Timeout\",\"details\":{},\"code\":504}\n"
 [[hyperkube/v1.10.2+coreos.0 (linux/amd64) kubernetes/211703c] 127.0.0.1:49244]
goroutine 96807 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc42e28cd90, 0x1f8)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc42e28cd90, 0x1f8)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc43967e8a0, 0xc42024ddd0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:201 +0xb3
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc4256a6900, 0xb19ea20, 0xc42e28cd90, 0xc42e27dc00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:101 +0x292
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0xb19ea20, 0xc42e28cd90, 0xc42e27dc00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:51 +0xeb
net/http.HandlerFunc.ServeHTTP(0xc4260c4780, 0xb19ea20, 0xc42e28cd90, 0xc42e27dc00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0xb19ea20, 0xc42e28cd90, 0xc42e27dc00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:45 +0x20f
net/http.HandlerFunc.ServeHTTP(0xc4260c4880, 0xb19ea20, 0xc42e28cd90, 0xc42e27dc00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0xb19ea20, 0xc42e28cd90, 0xc42e27dc00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc4256a6920, 0xb19ea20, 0xc42e28cd90, 0xc42e27dc00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0xb19ea20, 0xc42e28cd90, 0xc42e27dc00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41 +0x108
net/http.HandlerFunc.ServeHTTP(0xc4256a6960, 0xb1a0360, 0xc4452cde78, 0xc42e27dc00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc42884ab10, 0xb1a0360, 0xc4452cde78, 0xc42e27dc00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:197 +0x51
net/http.serverHandler.ServeHTTP(0xc4215fe410, 0xb1a0360, 0xc4452cde78, 0xc42e27dc00)
        /usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.initNPNRequest.ServeHTTP(0xc427cdf180, 0xc4215fe410, 0xb1a0360, 0xc4452cde78, 0xc42e27dc00)
        /usr/local/go/src/net/http/server.go:3164 +0x9a
net/http.(*initNPNRequest).ServeHTTP(0xc42caca2f0, 0xb1a0360, 0xc4452cde78, 0xc42e27dc00)
        <autogenerated>:1 +0x63
net/http.(Handler).ServeHTTP-fm(0xb1a0360, 0xc4452cde78, 0xc42e27dc00)
        /usr/local/go/src/net/http/h2_bundle.go:5462 +0x4d
net/http.(*http2serverConn).runHandler(0xc420c361c0, 0xc4452cde78, 0xc42e27dc00, 0xc427552020)
        /usr/local/go/src/net/http/h2_bundle.go:5747 +0x89
created by net/http.(*http2serverConn).processHeaders
        /usr/local/go/src/net/http/h2_bundle.go:5481 +0x495
```

**Comment by george-angel** [comment]
Update: Running the latest Kubernetes master apiserver fixes this issue, going to try to find the commit that fixes it.

**Comment by george-angel** [comment]
This fixes the issue: https://github.com/kubernetes/kubernetes/commit/814401fc902a7083bfd9933e245a2be62abfed60

Any chance to include it in the next PATCH release of v1.10 branch? Otherwise we will have to go 1.9.6 > 1.11.X which isn't ideal. Thanks.

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/64153

**Comment by liggitt** [comment]
#64153 is merged, will be in 1.10.4, planned for 6/6

**Comment by warmchang** [comment]
@liggitt @george-angel 
I am wondering why this dialTimeout parameter of etcd only affects version 1.10.
As @george-angel 's description, the 1.9 (either 1.9.3 or 1.9.6) is not affected.

**Comment by whites11** [comment]
Not sure if it's the same problem or not, but I'm having the same symptoms with version 1.9.0 and 1.9.6. Ram usage goes up to 2Gb before OOM in about 2-3 minutes. Have no idea how to fix it. It all started when I added a new node to the cluster.

**Comment by whites11** [comment]
Upgraded to 1.10.6 and looks like problem isn't occouring anymore.
