### ISSUE TITLE
CSI: data race in csi_attacher_test.go

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#62630]
/kind bug
/sig storage

**What happened**:
CSI unit tests occasionally end up with data race:

```
I0416 10:15:48.860139   12592 csi_plugin.go:61] kubernetes.io/csi: plugin initializing...
I0416 10:15:48.860996   12592 plugins.go:463] Loaded volume plugin "kubernetes.io/csi"
I0416 10:15:48.861457   12592 csi_attacher.go:102] kubernetes.io/csi: attachment [csi-4d8f42c5f953488d695504cfaf9658961d83f72b5ac9bba3e32c2ddb7708e84f] for volume [testvol-01] created successfully
I0416 10:15:48.861528   12592 csi_attacher.go:131] kubernetes.io/csi: probing for updates from CSI driver for [attachment.ID=csi-4d8f42c5f953488d695504cfaf9658961d83f72b5ac9bba3e32c2ddb7708e84f]
I0416 10:15:48.861608   12592 csi_attacher.go:140] kubernetes.io/csi: probing VolumeAttachment [id=csi-4d8f42c5f953488d695504cfaf9658961d83f72b5ac9bba3e32c2ddb7708e84f]
I0416 10:15:48.871527   12592 watch.go:109] Stopping fake watcher.
I0416 10:15:48.871614   12592 csi_attacher.go:115] kubernetes.io/csi: attacher.Attach finished OK with VolumeAttachment verified=true: attachment object [csi-4d8f42c5f953488d695504cfaf9658961d83f72b5ac9bba3e32c2ddb7708e84f]
I0416 10:15:48.871657   12592 csi_plugin.go:61] kubernetes.io/csi: plugin initializing...
I0416 10:15:48.871693   12592 plugins.go:463] Loaded volume plugin "kubernetes.io/csi"
I0416 10:15:48.872070   12592 csi_attacher.go:102] kubernetes.io/csi: attachment [csi-70fa8b122628ff5436f098759b79c93487b3894e2bff5637c618405a059b0b47] for volume [vol02] created successfully
I0416 10:15:48.872106   12592 csi_attacher.go:131] kubernetes.io/csi: probing for updates from CSI driver for [attachment.ID=csi-70fa8b122628ff5436f098759b79c93487b3894e2bff5637c618405a059b0b47]
I0416 10:15:48.872138   12592 csi_attacher.go:140] kubernetes.io/csi: probing VolumeAttachment [id=csi-70fa8b122628ff5436f098759b79c93487b3894e2bff5637c618405a059b0b47]
I0416 10:15:48.882107   12592 watch.go:109] Stopping fake watcher.
I0416 10:15:48.882168   12592 csi_attacher.go:115] kubernetes.io/csi: attacher.Attach finished OK with VolumeAttachment verified=true: attachment object [csi-70fa8b122628ff5436f098759b79c93487b3894e2bff5637c618405a059b0b47]
I0416 10:15:48.882225   12592 csi_plugin.go:61] kubernetes.io/csi: plugin initializing...
I0416 10:15:48.882258   12592 plugins.go:463] Loaded volume plugin "kubernetes.io/csi"
I0416 10:15:48.882545   12592 csi_attacher.go:102] kubernetes.io/csi: attachment [csi-75f1d3164ac9ae6f73784b2ed6b77839daf5b01a8dd52e787c8769b6fdb1b8ec] for volume [vol01] created successfully
I0416 10:15:48.882587   12592 csi_attacher.go:131] kubernetes.io/csi: probing for updates from CSI driver for [attachment.ID=csi-75f1d3164ac9ae6f73784b2ed6b77839daf5b01a8dd52e787c8769b6fdb1b8ec]
I0416 10:15:48.882619   12592 csi_attacher.go:140] kubernetes.io/csi: probing VolumeAttachment [id=csi-75f1d3164ac9ae6f73784b2ed6b77839daf5b01a8dd52e787c8769b6fdb1b8ec]
I0416 10:15:49.883446   12592 csi_plugin.go:61] kubernetes.io/csi: plugin initializing...
I0416 10:15:49.883588   12592 plugins.go:463] Loaded volume plugin "kubernetes.io/csi"
I0416 10:15:49.884863   12592 csi_attacher.go:102] kubernetes.io/csi: attachment [csi-8d666355799344c2b14819eb973950d28cf52f4d3a58e3fbeb8b92e29851fa17] for volume [vol02] created successfully
I0416 10:15:49.885055   12592 csi_attacher.go:131] kubernetes.io/csi: probing for updates from CSI driver for [attachment.ID=csi-8d666355799344c2b14819eb973950d28cf52f4d3a58e3fbeb8b92e29851fa17]
I0416 10:15:49.885232   12592 csi_attacher.go:140] kubernetes.io/csi: probing VolumeAttachment [id=csi-8d666355799344c2b14819eb973950d28cf52f4d3a58e3fbeb8b92e29851fa17]
I0416 10:15:50.884496   12592 csi_plugin.go:61] kubernetes.io/csi: plugin initializing...
I0416 10:15:50.884541   12592 plugins.go:463] Loaded volume plugin "kubernetes.io/csi"
I0416 10:15:50.885009   12592 csi_attacher.go:102] kubernetes.io/csi: attachment [csi-fd8097578f4563d9a74d4e7ba8397c32e42b2cea4ae677f8ccb4ba12bbd0008f] for volume [vol02] created successfully
I0416 10:15:50.885058   12592 csi_attacher.go:131] kubernetes.io/csi: probing for updates from CSI driver for [attachment.ID=csi-fd8097578f4563d9a74d4e7ba8397c32e42b2cea4ae677f8ccb4ba12bbd0008f]
I0416 10:15:50.885108   12592 csi_attacher.go:140] kubernetes.io/csi: probing VolumeAttachment [id=csi-fd8097578f4563d9a74d4e7ba8397c32e42b2cea4ae677f8ccb4ba12bbd0008f]
I0416 10:15:51.888911   12592 csi_plugin.go:61] kubernetes.io/csi: plugin initializing...
I0416 10:15:51.889066   12592 plugins.go:463] Loaded volume plugin "kubernetes.io/csi"
I0416 10:15:51.889932   12592 csi_attacher.go:131] kubernetes.io/csi: probing for updates from CSI driver for [attachment.ID=csi-8a782d3ec493cb8e5a83684820c9164ad40c550244be34ba2efe59a416235cce]
I0416 10:15:51.890190   12592 csi_attacher.go:140] kubernetes.io/csi: probing VolumeAttachment [id=csi-8a782d3ec493cb8e5a83684820c9164ad40c550244be34ba2efe59a416235cce]
I0416 10:15:51.891346   12592 csi_attacher.go:131] kubernetes.io/csi: probing for updates from CSI driver for [attachment.ID=csi-bce2a64c54e9d68b8c3f705c118ee2142fa71812c655090f4b42bfb1a5bafec8]
I0416 10:15:51.891446   12592 csi_attacher.go:140] kubernetes.io/csi: probing VolumeAttachment [id=csi-bce2a64c54e9d68b8c3f705c118ee2142fa71812c655090f4b42bfb1a5bafec8]
E0416 10:15:51.891634   12592 csi_attacher.go:158] kubernetes.io/csi: attachment for test-vol-1 failed: missing volume
I0416 10:15:51.895332   12592 csi_attacher.go:131] kubernetes.io/csi: probing for updates from CSI driver for [attachment.ID=csi-7abd6e0ec9124637db4e952a24f9ff404b1185f5ead8852977a1d67741508e9f]
I0416 10:15:51.895635   12592 csi_attacher.go:140] kubernetes.io/csi: probing VolumeAttachment [id=csi-7abd6e0ec9124637db4e952a24f9ff404b1185f5ead8852977a1d67741508e9f]
I0416 10:15:51.902762   12592 watch.go:109] Stopping fake watcher.
I0416 10:15:51.903200   12592 csi_attacher.go:131] kubernetes.io/csi: probing for updates from CSI driver for [attachment.ID=csi-27939ef3d2b20326fbd5c067388c94dcf976a8aeb5bd93b5219b4027d07ae753]
I0416 10:15:51.903269   12592 csi_attacher.go:140] kubernetes.io/csi: probing VolumeAttachment [id=csi-27939ef3d2b20326fbd5c067388c94dcf976a8aeb5bd93b5219b4027d07ae753]
E0416 10:15:51.939593   12592 csi_attacher.go:207] kubernetes.io/csi: attacher.WaitForAttach timeout after 30ms [volume=test-vol-3; attachment.ID=csi-27939ef3d2b20326fbd5c067388c94dcf976a8aeb5bd93b5219b4027d07ae753]
I0416 10:15:51.939758   12592 watch.go:109] Stopping fake watcher.
==================
WARNING: DATA RACE
Write at 0x00c4200209c0 by goroutine 26:
  runtime.closechan()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/runtime/chan.go:313 +0x0
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch.(*FakeWatcher).Stop()
      /home/jsafrane/project/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/watch.go:110 +0x118
  k8s.io/kubernetes/pkg/volume/csi.(*csiAttacher).waitForVolumeAttachmentInternal()
      /home/jsafrane/project/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_attacher.go:208 +0x1e29
  k8s.io/kubernetes/pkg/volume/csi.(*csiAttacher).waitForVolumeAttachment()
      /home/jsafrane/project/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_attacher.go:136 +0x29a
  k8s.io/kubernetes/pkg/volume/csi.TestAttacherWaitForVolumeAttachment()
      /home/jsafrane/project/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go:259 +0xcf1
  testing.tRunner()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:746 +0x16c

Previous read at 0x00c4200209c0 by goroutine 28:
  runtime.chansend()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/runtime/chan.go:128 +0x0
  k8s.io/kubernetes/pkg/volume/csi.TestAttacherWaitForVolumeAttachment.func1()
      /home/jsafrane/project/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/watch.go:140 +0x13a

Goroutine 26 (running) created at:
  testing.(*T).Run()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:789 +0x568
  testing.runTests.func1()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:1004 +0xa7
  testing.tRunner()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:746 +0x16c
  testing.runTests()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:1002 +0x521
  testing.(*M).Run()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:921 +0x206
  main.main()
      k8s.io/kubernetes/pkg/volume/csi/_test/_testmain.go:88 +0x1d3

Goroutine 28 (running) created at:
  k8s.io/kubernetes/pkg/volume/csi.TestAttacherWaitForVolumeAttachment()
      /home/jsafrane/project/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go:251 +0x1185
  testing.tRunner()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:746 +0x16c
==================
==================
WARNING: DATA RACE
Write at 0x00c42050d000 by goroutine 26:
  k8s.io/kubernetes/pkg/volume/csi.TestAttacherWaitForVolumeAttachment()
      /home/jsafrane/project/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go:234 +0x4b6
  testing.tRunner()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:746 +0x16c

Previous read at 0x00c42050d001 by goroutine 28:
  k8s.io/kubernetes/pkg/volume/csi.TestAttacherWaitForVolumeAttachment.func1()
      /home/jsafrane/project/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go:253 +0x79

Goroutine 26 (running) created at:
  testing.(*T).Run()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:789 +0x568
  testing.runTests.func1()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:1004 +0xa7
  testing.tRunner()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:746 +0x16c
  testing.runTests()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:1002 +0x521
  testing.(*M).Run()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:921 +0x206
  main.main()
      k8s.io/kubernetes/pkg/volume/csi/_test/_testmain.go:88 +0x1d3

Goroutine 28 (running) created at:
  k8s.io/kubernetes/pkg/volume/csi.TestAttacherWaitForVolumeAttachment()
      /home/jsafrane/project/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go:251 +0x1185
  testing.tRunner()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:746 +0x16c
==================
==================
WARNING: DATA RACE
Write at 0x00c42050d008 by goroutine 26:
  k8s.io/kubernetes/pkg/volume/csi.TestAttacherWaitForVolumeAttachment()
      /home/jsafrane/project/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go:234 +0x4b6
  testing.tRunner()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:746 +0x16c

Previous read at 0x00c42050d008 by goroutine 28:
  k8s.io/kubernetes/pkg/volume/csi.TestAttacherWaitForVolumeAttachment.func1()
      /home/jsafrane/project/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go:252 +0x40

Goroutine 26 (running) created at:
  testing.(*T).Run()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:789 +0x568
  testing.runTests.func1()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:1004 +0xa7
  testing.tRunner()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:746 +0x16c
  testing.runTests()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:1002 +0x521
  testing.(*M).Run()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:921 +0x206
  main.main()
      k8s.io/kubernetes/pkg/volume/csi/_test/_testmain.go:88 +0x1d3

Goroutine 28 (running) created at:
  k8s.io/kubernetes/pkg/volume/csi.TestAttacherWaitForVolumeAttachment()
      /home/jsafrane/project/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go:251 +0x1185
  testing.tRunner()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:746 +0x16c
==================
==================
WARNING: DATA RACE
Write at 0x00c42050d018 by goroutine 26:
  k8s.io/kubernetes/pkg/volume/csi.TestAttacherWaitForVolumeAttachment()
      /home/jsafrane/project/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go:234 +0x4b6
  testing.tRunner()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:746 +0x16c

Previous read at 0x00c42050d018 by goroutine 28:
  k8s.io/kubernetes/pkg/volume/csi.TestAttacherWaitForVolumeAttachment.func1()
      /home/jsafrane/project/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go:254 +0xb7

Goroutine 26 (running) created at:
  testing.(*T).Run()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:789 +0x568
  testing.runTests.func1()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:1004 +0xa7
  testing.tRunner()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:746 +0x16c
  testing.runTests()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:1002 +0x521
  testing.(*M).Run()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:921 +0x206
  main.main()
      k8s.io/kubernetes/pkg/volume/csi/_test/_testmain.go:88 +0x1d3

Goroutine 28 (running) created at:
  k8s.io/kubernetes/pkg/volume/csi.TestAttacherWaitForVolumeAttachment()
      /home/jsafrane/project/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go:251 +0x1185
  testing.tRunner()
      /home/jsafrane/.gimme/versions/go1.9.2.linux.amd64/src/testing/testing.go:746 +0x16c
==================
panic: send on closed channel

goroutine 40 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch.(*FakeWatcher).Modify(...)
	/home/jsafrane/project/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/watch.go:140
k8s.io/kubernetes/pkg/volume/csi.TestAttacherWaitForVolumeAttachment.func1(0xc42050cff0, 0xc42037ab00, 0xc420504740)
	/home/jsafrane/project/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go:255 +0x13b
created by k8s.io/kubernetes/pkg/volume/csi.TestAttacherWaitForVolumeAttachment
	/home/jsafrane/project/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go:251 +0x1186


ERROR: exit status 2
```

**How to reproduce it (as minimally and precisely as possible)**:

1. Follow https://github.com/kubernetes/community/blob/master/contributors/devel/flaky-tests.md#reproducing-unit-test-flakes to get `$GOPATH/bin/stress`

2. Compile CSI unit tests into a binary: `cd pkg/volume/csi; go test -c -race`

3. Run the binary 500 times in parallel until it breaks: `stress -p 500 ./csi.test -v 5 -alsologtostderr`. Use different `-p` argument to really load your machine, it should not be idle!

4. Wait. On my Linux, I got 3 failures in ~1000 runs.

`stress` puts stderr of failed runs into `/tmp/go-stressXXXXXXXXX`.

**Comment by linyouchong** [comment]
@jsafrane @vladimirvivien 
I make a Fix: https://github.com/kubernetes/kubernetes/pull/62827
PTAL
