### ISSUE TITLE
kubectl diff does not work with list

### ISSUE THREAD

**Issue by wangzhen127** [kubernetes/kubernetes#63117]
Using ```dummy-list.yaml``` as an example:
```
kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: dummy-pod
  spec:
    containers:
      - name: dummy-pod
        image: ubuntu
        command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
    restartPolicy: Always
```

Create pod by ```kubectl apply -f dummy-list.yaml```.
Check the pod is running by ```kubectl get pods```.
Then run diff by ```kubectl alpha diff -f dummy-list.yaml```.

It outputs errors:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x10fb11f]

goroutine 1 [running]:
k8s.io/kubernetes/pkg/kubectl/resource.(*Helper).Get(0xc420a40640, 0x18349cd, 0x7, 0xc4217c8400, 0x9, 0x16a2c00, 0x2, 0x20000000000, 0x8, 0x0)
	/media/myssd/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/helper.go:55 +0x3f
k8s.io/kubernetes/pkg/kubectl/resource.(*Info).Get(0xc4203b32d0, 0x2353fa0, 0xc4200abde0)
	/media/myssd/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:110 +0x9c
k8s.io/kubernetes/pkg/kubectl/cmd.RunDiff.func1(0xc4203b32d0, 0x0, 0x0, 0x0, 0x0)
	/media/myssd/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/diff.go:435 +0x91
k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit.func1(0xc4203b32d0, 0x0, 0x0, 0xc420f76540, 0x1)
	/media/myssd/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:383 +0xe7
k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit.func1(0xc4203b3110, 0x0, 0x0, 0x120, 0xc420997b30)
	/media/myssd/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:468 +0x28f
k8s.io/kubernetes/pkg/kubectl/resource.(*StreamVisitor).Visit(0xc4219bbd40, 0xc421799a40, 0x2350f20, 0xc4217c7a40)
	/media/myssd/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:609 +0x2a7
k8s.io/kubernetes/pkg/kubectl/resource.(*FileVisitor).Visit(0xc4217c7960, 0xc421799a40, 0x0, 0x0)
	/media/myssd/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:558 +0x138
k8s.io/kubernetes/pkg/kubectl/resource.VisitorList.Visit(0xc42191b900, 0x1, 0x1, 0xc421799a40, 0x1, 0xc421799a40)
	/media/myssd/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:245 +0x63
k8s.io/kubernetes/pkg/kubectl/resource.(*VisitorList).Visit(0xc4217c7980, 0xc421799a40, 0x7f9dc0f9c000, 0x0)
	<autogenerated>:1 +0x58
k8s.io/kubernetes/pkg/kubectl/resource.FlattenListVisitor.Visit(0x234b120, 0xc4217c7980, 0xc4219bbd80, 0xc4219bbe00, 0x1, 0xc4219bbe00)
	/media/myssd/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:439 +0x9e
k8s.io/kubernetes/pkg/kubectl/resource.(*FlattenListVisitor).Visit(0xc4217c79a0, 0xc4219bbe00, 0x20, 0x171f100)
	<autogenerated>:1 +0x58
k8s.io/kubernetes/pkg/kubectl/resource.DecoratedVisitor.Visit(0x234b0a0, 0xc4217c79a0, 0xc4217c79e0, 0x3, 0x4, 0xc4217c7a00, 0x0, 0x234ada0)
	/media/myssd/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/visitor.go:374 +0x9b
k8s.io/kubernetes/pkg/kubectl/resource.(*DecoratedVisitor).Visit(0xc421799a10, 0xc4217c7a00, 0x411148, 0x20)
	<autogenerated>:1 +0x62
k8s.io/kubernetes/pkg/kubectl/resource.(*Result).Visit(0xc4209bfa00, 0xc4217c7a00, 0x234afe0, 0xc42191b910)
	/media/myssd/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/resource/result.go:98 +0x62
k8s.io/kubernetes/pkg/kubectl/cmd.RunDiff(0x2374b40, 0xc4200b5860, 0xc420469260, 0xc420737e60, 0x1831d5c, 0x5, 0x183121a, 0x4, 0x0, 0x0)
	/media/myssd/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/diff.go:429 +0x389
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdDiff.func1(0xc42085c500, 0xc4206ee880, 0x0, 0x2)
	/media/myssd/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/diff.go:120 +0x11e
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc42085c500, 0xc4206ee820, 0x2, 0x2, 0xc42085c500, 0xc4206ee820)
	/media/myssd/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760 +0x2c1
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42017f900, 0xc42090fed8, 0xc42090fee0, 0x12a05f200)
	/media/myssd/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x334
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42017f900, 0x18ea490, 0x25145a0)
	/media/myssd/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
	/media/myssd/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:50 +0x196
```

**Comment by xiaoxubeii** [comment]
Please follow the template below to issue:



**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature


**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:


**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

As i have tested it with Kubernetes 1.9.2 and CentOS7.1, no problem exists.

**Comment by apelisse** [comment]
Yeah I think @wangzhen127 is using kubernetes 1.9.x with a patch on top of it. Thank you for reporting that bug, that's pretty useful. We're in the process of changing the way the merge is computed (on the server rather than the client), so we won't fix this for now.

**Comment by wangzhen127** [comment]
Right. I am using a locally built version: v1.10.0-alpha.1.5119 (almost HEAD) with #61227

**Comment by wangzhen127** [comment]
And is this only related to MERGED? I got the same error when running:
```kubectl alpha diff -f dummy-list.yaml LAST LOCAL```

**Comment by apelisse** [comment]
Oh that's good to know, thank you!

**Comment by JessieAMorris** [comment]
I'm still running into this issue. 

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-28T20:13:43Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

```
Jessie-Morris-MacBook-Pro:dev jessiemorris$ kubectl alpha diff -f dashboard.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1507bc2]

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).UnstructuredContent(0x0, 0x103ceb9)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go:104 +0x22
k8s.io/kubernetes/pkg/kubectl/cmd.InfoObject.Live(0x24c1160, 0x0, 0xc4203b27e0, 0x249d3c0, 0xc4223ceaf0, 0xc42225e000, 0x0, 0x0, 0xc422273370)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/diff.go:297 +0x36
k8s.io/kubernetes/pkg/kubectl/cmd.(*DiffVersion).getObject(0xc42224d440, 0x24bcda0, 0xc4223c3e60, 0xc4223d2180, 0x0, 0x0)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/diff.go:201 +0x10d
k8s.io/kubernetes/pkg/kubectl/cmd.(*DiffVersion).Print(0xc42224d440, 0x24bcda0, 0xc4223c3e60, 0x0, 0x0)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/diff.go:214 +0x4b
k8s.io/kubernetes/pkg/kubectl/cmd.(*Differ).Diff(0xc42225e010, 0x24bcda0, 0xc4223c3e60, 0xc4223c3e60, 0xc4223c81b0)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/diff.go:375 +0x7b
k8s.io/kubernetes/pkg/kubectl/cmd.RunDiff.func1(0xc4203b27e0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/diff.go:488 +0x14a
k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.DecoratedVisitor.Visit.func1(0xc4203b27e0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/visitor.go:315 +0xd3
k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.FlattenListVisitor.Visit.func1(0xc4203b27e0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/visitor.go:381 +0x485
k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.FlattenListVisitor.Visit.func1(0xc4203b27e0, 0x0, 0x0, 0xd0, 0xc420458da0)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/visitor.go:381 +0x485
k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.(*StreamVisitor).Visit(0xc422275740, 0xc4222b79c0, 0x24a2de0, 0xc4222f3300)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/visitor.go:542 +0x2a2
k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.(*FileVisitor).Visit(0xc4222a6380, 0xc4222b79c0, 0x0, 0x0)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/visitor.go:491 +0x12e
k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.VisitorList.Visit(0xc422294710, 0x1, 0x1, 0xc4222b79c0, 0x1, 0xc4222b79c0)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/visitor.go:177 +0x63
k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.FlattenListVisitor.Visit(0x249cb80, 0xc4222a63a0, 0x24a8ea0, 0x302b548, 0xc422297560, 0xc4222b7980, 0x1, 0xc4222b7980)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/visitor.go:372 +0x99
k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.FlattenListVisitor.Visit(0x249cb40, 0xc422297590, 0x24a8ea0, 0x302b548, 0xc422297560, 0xc4222b7940, 0xc4222b9e01, 0xc4222b7940)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/visitor.go:372 +0x99
k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.DecoratedVisitor.Visit(0x249cb40, 0xc4222975f0, 0xc4222a63e0, 0x3, 0x4, 0xc4222f0480, 0x0, 0xc4222b9e50)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/visitor.go:306 +0x99
k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.(*Result).Visit(0xc420acfc00, 0xc4222f0480, 0xc422297650, 0x0)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/result.go:99 +0x62
k8s.io/kubernetes/pkg/kubectl/cmd.RunDiff(0x24cfa80, 0xc4204d8f60, 0xc4204c2780, 0xc4206a39c0, 0x23393a6, 0x5, 0x233883b, 0x4, 0x0, 0x0)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/diff.go:475 +0x2e7
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdDiff.func1(0xc420669b80, 0xc4200e2460, 0x0, 0x2)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/diff.go:122 +0x11e
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc420669b80, 0xc4200e23e0, 0x2, 0x2, 0xc420669b80, 0xc4200e23e0)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760 +0x2c1
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200daa00, 0xc42051a1e0, 0x12a05f200, 0xc4208e7ee8)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x30a
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200daa00, 0x23f2d30, 0x300ccc0)
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
	/private/tmp/kubernetes-cli-20180808-18633-96wn9g/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:50 +0x196
Jessie-Morris-MacBook-Pro:dev jessiemorris$ 
```

**Comment by zeeZ** [comment]
I've encountered the same as above with different kubectl versions:
```
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.1", GitCommit:"94c2c6c8423d722f436305cd67ef515a8800d723", GitTreeState:"clean", BuildDate:"2018-08-01T23:32:58Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"windows/amd64"}
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.10", GitCommit:"098570796b32895c38a9a1c9286425fb1ececa18", GitTreeState:"clean", BuildDate:"2018-08-02T17:11:51Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
`test.yaml` (only local, does not exist in cluster):
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: test
  namespace: default
data:
  foo: bar
```

```
>kubectl alpha diff -f test.yaml -v 6
I0821 11:58:52.075453    5660 loader.go:359] Config loaded from file REDACTED
I0821 11:58:52.195720    5660 round_trippers.go:405] GET https://REDACTED/openapi/v2?timeout=32s 404 Not Found in 24 milliseconds
I0821 11:58:52.201939    5660 round_trippers.go:405] GET https://REDACTED/swagger-2.0.0.pb-v1?timeout=32s 200 OK in 3 milliseconds
I0821 11:58:52.322356    5660 loader.go:359] Config loaded from file REDACTED
I0821 11:58:52.326315    5660 loader.go:359] Config loaded from file REDACTED
I0821 11:58:52.328319    5660 loader.go:359] Config loaded from file REDACTED
I0821 11:58:52.330318    5660 loader.go:359] Config loaded from file REDACTED
I0821 11:58:52.330318    5660 decoder.go:224] decoding stream as YAML
I0821 11:58:52.342535    5660 round_trippers.go:405] GET https://REDACTED/api/v1/namespaces/default/configmaps/test 404 Not Found in 3 milliseconds
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x938e09]

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).UnstructuredContent(0x0, 0x43bbb0)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go:104 +0x29
k8s.io/kubernetes/pkg/kubectl/cmd.InfoObject.Live(0x19644e0, 0x0, 0xc0420b5880, 0x1940440, 0xc042fd45b0, 0xc042d983f0, 0x0, 0x0, 0xc042def2c0)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/diff.go:297 +0x3d
k8s.io/kubernetes/pkg/kubectl/cmd.(*DiffVersion).getObject(0xc042da3c40, 0x195fea0, 0xc042fd19b0, 0xc042b63700, 0x0, 0x0)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/diff.go:201 +0x114
k8s.io/kubernetes/pkg/kubectl/cmd.(*DiffVersion).Print(0xc042da3c40, 0x195fea0, 0xc042fd19b0, 0x0, 0x0)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/diff.go:214 +0x52
k8s.io/kubernetes/pkg/kubectl/cmd.(*Differ).Diff(0xc042d98400, 0x195fea0, 0xc042fd19b0, 0xc042fd19b0, 0xc042f665a0)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/diff.go:375 +0x82
k8s.io/kubernetes/pkg/kubectl/cmd.RunDiff.func1(0xc0420b5880, 0x0, 0x0, 0x0, 0x0)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/diff.go:488 +0x151
k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.DecoratedVisitor.Visit.func1(0xc0420b5880, 0x0, 0x0, 0x0, 0x0)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/visitor.go:315 +0xda
k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.FlattenListVisitor.Visit.func1(0xc0420b5880, 0x0, 0x0, 0x0, 0x0)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/visitor.go:380 +0x7bd
k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.FlattenListVisitor.Visit.func1(0xc0420b5880, 0x0, 0x0, 0x80, 0xc04245d720)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/visitor.go:380 +0x7bd
k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.(*StreamVisitor).Visit(0xc042df0840, 0xc042eaba80, 0x1945ee0, 0xc042ef79a0)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/visitor.go:558 +0x2a9
k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.(*FileVisitor).Visit(0xc042df8100, 0xc042eaba80, 0x0, 0x0)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/visitor.go:507 +0x135
k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.VisitorList.Visit(0xc042d99890, 0x1, 0x1, 0xc042eaba80, 0x1, 0xc042eaba80)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/visitor.go:177 +0x6a
k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.FlattenListVisitor.Visit(0x193fc00, 0xc042df8120, 0x194c0a0, 0x251a288, 0xc042dd5020, 0xc042eaba40, 0x1, 0xc042eaba40)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/visitor.go:372 +0xa0
k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.FlattenListVisitor.Visit(0x193fbc0, 0xc042dd5050, 0x194c0a0, 0x251a288, 0xc042dd5020, 0xc042eaba00, 0xc042eb2701, 0xc042eaba00)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/visitor.go:372 +0xa0
k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.DecoratedVisitor.Visit(0x193fbc0, 0xc042dd50b0, 0xc042df8160, 0x3, 0x4, 0xc042efc5a0, 0x0, 0xc042eb2730)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/visitor.go:306 +0xa0
k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.(*Result).Visit(0xc042013300, 0xc042efc5a0, 0xc042dd5110, 0x0)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/result.go:99 +0x69
k8s.io/kubernetes/pkg/kubectl/cmd.RunDiff(0x1973100, 0xc0425b3e60, 0xc0425a8640, 0xc0425b5160, 0x17ce60b, 0x5, 0x17cda51, 0x4, 0x0, 0x0)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/diff.go:475 +0x2ee
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdDiff.func1(0xc04242a780, 0xc0425a8d40, 0x0, 0x4)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/diff.go:122 +0x125
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc04242a780, 0xc0425a8c80, 0x4, 0x4, 0xc04242a780, 0xc0425a8c80)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760 +0x2c8
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc04218d900, 0xc04277c000, 0x12a05f200, 0xc042a57ee8)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x311
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc04218d900, 0x188bab8, 0x24fd920)
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794 +0x32
main.main()
        /workspace/anago-v1.12.0-alpha.0.2637+94c2c6c8423d72/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:50 +0x19d
```
My guess is it doesn't like the 404.

New bug or still "we won't fix this for now" @apelisse ?

**Comment by apelisse** [comment]
I'll submit a fix, thanks for the detailed report @zeeZ
