### ISSUE TITLE
API server -> TLS bootstrapped node: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by seanknox** [kubernetes/kubernetes#63164]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Brought up a v1.10.1 control plane and nodes via TLS bootstrap tokens. The nodes are online and can run pods, but connections to the nodes from kube-apiserver fail with "x509: certificate signed by unknown authority".

```
$ kubectl -n kube-system logs -f kube-dns-7567cf4b86-np4sx kubedns
Error from server: Get https://node2.seano2.acs:10250/containerLogs/kube-system/kube-dns-7567cf4b86-np4sx/kubedns?follow=true: x509: certificate signed by unknown authority
```
I know when using the `--tls-cert-file` flag that the CA cert is supposed to be concatenated after the certificate itself: 

> --tls-cert-file File containing x509 Certificate for HTTPS. (CA cert, if any, concatenated after server cert). [[kubelet documentation](http://kubernetes.io/docs/admin/kubelet/)]

Could that be the issue here?

Logs from the API server:
```
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]: E0425 20:07:32.682945  127611 status.go:64] apiserver received an error that is not an metav1.Status: Get https://node2.seano2.acs:10250/containerLogs/kube-system/kube-dns-7567cf4b86-np4sx/kubedns?follow=true: x509: certificate signed by unknown authority
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]: I0425 20:07:32.683220  127611 wrap.go:42] GET /api/v1/namespaces/kube-system/pods/kube-dns-7567cf4b86-np4sx/log?container=kubedns&follow=true: (35.842868ms) 500
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]: goroutine 15002 [running]:
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc4237263f0, 0x1f4)
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]:         /workspace/anago-v1.10.1-beta.0.68+d4ab47518836c7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc4237263f0, 0x1f4)
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]:         /workspace/anago-v1.10.1-beta.0.68+d4ab47518836c7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.(*ResponseWriterDelegator).WriteHeader(0xc42f8590b0, 0x1f4)
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]:         /workspace/anago-v1.10.1-beta.0.68+d4ab47518836c7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:281 +0x45
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x3d346fa, 0x10, 0x7f3f56420fc8, 0xc42ed4f400, 0x987fe00, 0xc428a3e1f8, 0xc4285d2d00, 0x1f4, 0x9866bc0, 0xc42a231170)
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]:         /workspace/anago-v1.10.1-beta.0.68+d4ab47518836c7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:95 +0x8d
--
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]: net/http.initNPNRequest.ServeHTTP(0xc42b978000, 0xc42b2f9380, 0x9881000, 0xc428a3e1e8, 0xc4285d2d00)
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]:         /usr/local/go/src/net/http/server.go:3164 +0x9a
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]: net/http.(*initNPNRequest).ServeHTTP(0xc4258c3ab0, 0x9881000, 0xc428a3e1e8, 0xc4285d2d00)
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]:         <autogenerated>:1 +0x63
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]: net/http.(Handler).ServeHTTP-fm(0x9881000, 0xc428a3e1e8, 0xc4285d2d00)
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]:         /usr/local/go/src/net/http/h2_bundle.go:5462 +0x4d
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]: net/http.(*http2serverConn).runHandler(0xc4306f4e00, 0xc428a3e1e8, 0xc4285d2d00, 0xc4257eede0)
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]:         /usr/local/go/src/net/http/h2_bundle.go:5747 +0x89
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]: created by net/http.(*http2serverConn).processHeaders
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]:         /usr/local/go/src/net/http/h2_bundle.go:5481 +0x495
Apr 25 20:07:32 k8scontroller1 kube-apiserver[127611]: logging error output: "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Get https://node2.seano2.acs:10250/containerLogs/kube-system/kube-dns-7567cf4b86-np4sx/kubedns?follow=true: x509: certificate signed by unknown authority\",\"code\":500}\n"
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
- bring up nodes using [TLS bootstrap tokens](https://kubernetes.io/docs/admin/bootstrap-tokens/)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.1
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): Ubuntu 17.10
- Kernel (e.g. `uname -a`): `Linux k8scontroller2 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: Manual (with Terraform)
- Others:

**Comment by seanknox** [comment]
@kubernetes/sig-auth-bugs

**Comment by seanknox** [comment]
Yep. Here's the API config:

```
[Service]
ExecStart=/usr/local/bin/kube-apiserver \
  --admission-control=Initializers,NamespaceLifecycle,NodeRestriction,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota \
  --advertise-address=10.0.10.247 \
  --allow-privileged=true \
  --apiserver-count=3 \
  --audit-log-maxage=30 \
  --audit-log-maxbackup=3 \
  --audit-log-maxsize=100 \
  --audit-log-path=/var/log/audit.log \
  --authorization-mode=Node,RBAC \
  --bind-address=0.0.0.0 \
  --client-ca-file=/etc/kubernetes/ssl/ca.pem \
  --cloud-config=/etc/kubernetes/azure.json \
  --cloud-provider=azure \
  --enable-swagger-ui=true \
  --enable-bootstrap-token-auth=true \
  --etcd-cafile=/etc/kubernetes/ssl/ca.pem \
  --etcd-certfile=/etc/kubernetes/ssl/kube-apiserver.pem \
  --etcd-keyfile=/etc/kubernetes/ssl/kube-apiserver-key.pem \
  --etcd-servers=https://etcd1.seano2.acs:2379,https://etcd2.seano2.acs:2379,https://etcd3.seano2.acs:2379 \
  --event-ttl=1h \
  --insecure-bind-address=127.0.0.1 \
  --kubelet-certificate-authority=/etc/kubernetes/ssl/ca.pem \
  --kubelet-client-certificate=/etc/kubernetes/ssl/kube-apiserver.pem \
  --kubelet-client-key=/etc/kubernetes/ssl/kube-apiserver-key.pem \
  --kubelet-https=true \
  --profiling=false \
  --repair-malformed-updates=false \
  --runtime-config=api/all \
  --service-account-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem \
  --service-cluster-ip-range=10.3.0.0/24 \
  --service-node-port-range=30000-32767 \
  --storage-backend=etcd3 \
  --tls-ca-file=/etc/kubernetes/ssl/ca.pem \
  --tls-cert-file=/etc/kubernetes/ssl/kube-apiserver.pem \
  --tls-private-key-file=/etc/kubernetes/ssl/kube-apiserver-key.pem \
  --v=2
```

**Comment by liggitt** [comment]
and this (run from the apiserver) doesn't complain about TLS errors:

```sh
curl -v \
  --cert /etc/kubernetes/ssl/kube-apiserver.pem \
  --key /etc/kubernetes/ssl/kube-apiserver-key.pem \
  --cacert /etc/kubernetes/ssl/ca.pem \
  /etc/kubernetes/ssl/kube-apiserver.pem \
  https://node2.seano2.acs:10250
```

**Comment by seanknox** [comment]
Ah, indeed it does complain:

```
* Rebuilt URL to: https://node2.seano2.acs:10250/
*   Trying 10.1.0.4...
* TCP_NODELAY set
* Connected to node2.seano2.acs (10.1.0.4) port 10250 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/kubernetes/ssl/ca.pem
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: self signed certificate in certificate chain
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate in certificate chain
```

Does the issue seem to be in the apiserver certs, then?

**Comment by seanknox** [comment]
looking at the TLS certs generated on the node:

```
ubuntu@node3:/var/lib/kubelet/pki$ openssl verify -CAfile /etc/kubernetes/ssl/ca.pem kubelet.crt
kubelet.crt: CN = node3.seano3.acs@1524874169
error 20 at 0 depth lookup:unable to get local issuer certificate

ubuntu@node3:/var/lib/kubelet/pki$ openssl verify -CAfile /etc/kubernetes/ssl/ca.pem kubelet-client.crt
kubelet-client.crt: OK
```

**Comment by liggitt** [comment]
TLS bootstrapping only sets up api client certificates for the kubelet currently. If you want a serving cert for the kubelet that is signed by the apiserver's `--kubelet-certificate-authority` you must provide it. Otherwise the kubelet generates a self-signed serving cert.

**Comment by seanknox** [comment]
Couple questions:
- Are there any known issues with TLS bootstrapping in v1.10.x?
- Do you think the configuration issue is with the kubelet or the apiserver? I'm grasping at straws at why the kubelet cert is invalid (as shown in the curl or the `x509: certificate signed by unknown authority` message on the API server)

**Comment by liggitt** [comment]
> Are there any known issues with TLS bootstrapping in v1.10.x?

TLS bootstrapping where the cluster CA is used to sign certificates is only implemented for client certificates (kubelet -> apiserver) in 1.10. The issues you are encountering are with the serving certificate used by the kubelet.

> Do you think the configuration issue is with the kubelet or the apiserver?

It is with the kubelet. Did you provide the kubelet with a serving certificate via the `--tls-cert-file` flag which is signed by the CA given to the apiserver with the `--kubelet-certificate-authority` flag?
