### ISSUE TITLE
golang1.10.1 build kube-scheduler has some trouble

### ISSUE THREAD

**Issue by ShualLiu** [kubernetes/kubernetes#63360]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
When I use golang1.10.1 to build kube-scheduler(using make kube-scheduler in kubernetes), a scheduler will be crashloopbackoff in cluster. But It's ok using golang 1.9.6.[configure-multiple-schedulers](https://v1-8.docs.kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/)
**I'm confused  it  was a golang bug or a kubernetes bug...**
**What you expected to happen**:
run ok in cluster.
**How to reproduce it (as minimally and precisely as possible)**:
* Using golang 1.10.1 version to build kube-scheduler (make kube-scheduler)
* Packing a docker image with  above website instructions.
* Using above website deployment to deploy a custom scheduler.
* The Pod is Error...
**Anything else we need to know?**:
Everything will be OK with golang1.9.6
```
E0502 09:44:05.284741       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/home/maurice/Environment/golang-1.10.1/src/runtime/asm_amd64.s:573
/home/maurice/Environment/golang-1.10.1/src/runtime/panic.go:502
/home/maurice/Environment/golang-1.10.1/src/runtime/panic.go:63
/home/maurice/Environment/golang-1.10.1/src/runtime/signal_unix.go:388
/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/schedulercache/util.go:110
/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/schedulercache/node_info.go:469
/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/schedulercache/cache.go:330
/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:558
/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:216
/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:195
/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:542
/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:383
/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:383
/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/home/maurice/Environment/golang-1.10.1/src/runtime/asm_amd64.s:2361
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xf00ee2]

goroutine 13 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x145cea0, 0x21e14a0)
	/home/maurice/Environment/golang-1.10.1/src/runtime/panic.go:502 +0x229
k8s.io/kubernetes/plugin/pkg/scheduler/schedulercache.GetNodeReceiveBytesRate(0xc42042439a, 0x6, 0xc400000000)
	/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/schedulercache/util.go:110 +0x3c2
k8s.io/kubernetes/plugin/pkg/scheduler/schedulercache.(*NodeInfo).SetNode(0xc4202a8a50, 0xc4204e8d20, 0x2, 0xc4207d8580)
	/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/schedulercache/node_info.go:469 +0x1f7
k8s.io/kubernetes/plugin/pkg/scheduler/schedulercache.(*schedulerCache).AddNode(0xc420039a00, 0xc4204e8d20, 0x0, 0x0)
	/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/schedulercache/cache.go:330 +0x1ca
k8s.io/kubernetes/plugin/pkg/scheduler/factory.(*ConfigFactory).addNodeToCache(0xc4202a80f0, 0x164f580, 0xc4204e8d20)
	/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:558 +0x18d
k8s.io/kubernetes/plugin/pkg/scheduler/factory.(*ConfigFactory).(k8s.io/kubernetes/plugin/pkg/scheduler/factory.addNodeToCache)-fm(0x164f580, 0xc4204e8d20)
	/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/factory/factory.go:216 +0x3e
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(0xc420332990, 0xc4203329a0, 0xc4203329b0, 0x164f580, 0xc4204e8d20)
	/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:195 +0x49
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc420450870)
	/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:542 +0x247
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).(k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.run)-fm()
	/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:383 +0x2a
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc4203c2ca0, 0xc4202c02e0)
	/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
created by k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/maurice/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62

```
**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.8
- Cloud provider or hardware configuration: 4CPU 8G 11Nodes 3Masters
- OS (e.g. from /etc/os-release):  CentOS7.4
- Kernel (e.g. `uname -a`):Linux master2 4.4.98-1.el7.elrepo.x86_64 #1 SMP Wed Nov 15 12:29:46 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by wgliang** [comment]
Which one is the version of the scheduler? After checking the versions, it should be a very old version, it is recommended to upgrade kubernetes. If you still get this error, please reply here.

**Comment by ShualLiu** [comment]
The scheduler target version is v1.8.8,,, I think it's not old-fashioned.... @wgliang

**Comment by ravisantoshgudimetla** [comment]
@ShualLiu - Thanks for reporting this. 
- I believe kube 1.8 master has been tested with golang 1.8.3. (https://github.com/kubernetes/community/blob/master/contributors/devel/development.md).
- You can try finding that from https://github.com/kubernetes/kubernetes/blob/release-1.8/hack/lib/golang.sh#L341. 
- I also think that with the error you faced now, it would be better to lock the maximum version of golang in the script. 

Tagging in few people who can handle this. Please feel free to re-assign.

/cc @cblecker @luxas @ixdy

**Comment by ixdy** [comment]
Yep, as @ravisantoshgudimetla noted, the 1.8 branch of kubernetes was qualified with go1.8, and we don't upgrade go minor versions on a release branch, since incompatibilities as you've experienced occasionally appear.

When using the crossbuild image or bazel, we have the go version explicitly specified, so this issue really only comes up when you're doing a nonhermetic build through make.

We can probably enforce a maximum go version as suggested, though [this conditional](https://github.com/kubernetes/kubernetes/blob/a3d79c39f49ea13f83f13ca0a47ccb970283828a/hack/lib/golang.sh#L325) already terrifies me a bit.

**Comment by ravisantoshgudimetla** [comment]
Thanks @ixdy for confirming. @ShualLiu Can you please close the issue unless there are other concerns?
