### ISSUE TITLE
kubectl panic with wrong arguments to 'kubectl run'

### ISSUE THREAD

**Issue by rmorrise** [kubernetes/kubernetes#64054]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1468b05]

goroutine 1 [running]:
k8s.io/kubernetes/pkg/kubectl/cmd.RunRun(0x23bffc0, 0xc04273a2a0, 0x2395160, 0xc042004010, 0x23951a0, 0xc042004018, 0x23951a0, 0xc042004020, 0xc0426d6280, 0xc042235100, ...)
        /workspace/anago-v1.10.0-rc.1.9+fc32d2f3698e36/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/run.go:328 +0x10b5
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdRun.func1(0xc0426d6280, 0xc042235100, 0x2, 0x4)
        /workspace/anago-v1.10.0-rc.1.9+fc32d2f3698e36/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/run.go:105 +0x14b
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0426d6280, 0xc042235080, 0x4, 0x4, 0xc0426d6280, 0xc042235080)
        /workspace/anago-v1.10.0-rc.1.9+fc32d2f3698e36/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:757 +0x2c8
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc04242f180, 0xc042821ed8, 0xc042821ee0, 0x12a05f200)
        /workspace/anago-v1.10.0-rc.1.9+fc32d2f3698e36/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:843 +0x33b
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc04242f180, 0x192dfb8, 0x255ff20)
        /workspace/anago-v1.10.0-rc.1.9+fc32d2f3698e36/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:791 +0x32
main.main()
        /workspace/anago-v1.10.0-rc.1.9+fc32d2f3698e36/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:50 +0x19d
```

**What you expected to happen**:
If the syntax of my command is invalid, it should tell me what I did wrong. In this case, I think the command has too many arguments?

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl run -it bar --image=busybox env`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"g
o1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"g
o1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
```
$ minikube version
minikube version: v0.27.0
```

- OS (e.g. from /etc/os-release): Windows 7 (x64)

**Comment by ibrasho** [comment]
Looks like this was a bug in v1.10.0. It should have been solved in v1.10.1+.

Can you test with kubectl v1.10.1 or v1.10.2?

**Comment by rmorrise** [comment]
Verified with 1.10.2. Can the Windows download link on this page be updated to point to the latest fixed version?
https://kubernetes.io/docs/tasks/tools/install-kubectl/

Thanks.

**Comment by ibrasho** [comment]
I've submitted a PR to fix this (https://github.com/kubernetes/website/pull/8662)

**Comment by ibrasho** [comment]
You should be able to close this issue. 😁
