### ISSUE TITLE
[kube-apiserver] when server timeout, client didn't return and tcp connection didn't close

### ISSUE THREAD

**Issue by shenlanse** [kubernetes/kubernetes#64496]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I use `curl ` to send POST Request to kube-apiserver. I set wrong Content-Length header, which is bigger than real value. 

```
curl -XPOST -d @namespace.json -H "Content-Type: application/json" -H "Content-Length: 10000" 'localhost:8080/api/v1/namespaces'
```

RESULT:

- client: `curl` didn't return util I `ctrl+c` to cancel it
- server: 

```
I0530 15:26:23.815938      11 wrap.go:42] POST /api/v1/namespaces: (1m0.000346704s) 504
goroutine 19688782 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc44cdf5b20, 0x1f8)
        /data/workspace/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc44cdf5b20, 0x1f8)
        /data/workspace/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc45cdde840, 0xc45b7366c0)
        /data/workspace/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:201 +0xb3
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc42bfeaae0, 0x8ddac40, 0xc44cdf5b20, 0xc45d5ac100)
        /data/workspace/kubernetes/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:101 +0x292

```

- tcp connection: still established

**What you expected to happen**:

kube-apiserver timeout is 1min. 

- client: shoud return after 1min
- server: it is expected, 504 and print stack info
- tcp connection: closed

**How to reproduce it (as minimally and precisely as possible)**:

like above. Set Content-Length higher than real value

**Anything else we need to know?**:

Because we want to expose our k8s cluster to customer, public cloud, not private cloud. So we have to be careful to avoid 'bad user'.

**Environment**:

k8s v1.9.2

**Comment by hzxuzhonghu** [comment]
cc @liggitt @sttts

**Comment by lavalamp** [comment]
hm, yes that is a reasonable expectation but the timeout isn't enforced until after the body has been read, I think.

**Comment by lavalamp** [comment]
(looks at call stack) Oh, sorry, right. The timeout did trigger. But I think the connection is locked up inside the go http stack on a read, and that's why it was unable to close/send stuff.

I bet if you tell it you'll send 2 bytes, send 1, then after 60+ seconds have gone by send the 2nd one, then you'll get a timeout error message.

The fix is likely to not be easy :/

**Comment by hzxuzhonghu** [comment]
Yes, not easy. A way is to auto close the connection(hijack) from server side. But i am not sure whether there are other issues.

**Comment by hzxuzhonghu** [comment]
We can set http.Server.ReadTimeout to tackle with this issue. And I have verified it did effect.

**Comment by lavalamp** [comment]
Oh, I didn't dare hope that go's HTTP library would help us here. Happy to
look at a PR setting that!
