### ISSUE TITLE
kubeadm token test is flaky

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#64625]
Just got this while running the tests:

```
goroutine 65 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7f7826878c90, 0x72, 0x0)
        /data/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420739398, 0x72, 0xc420100600, 0x0, 0x0)
        /data/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420739398, 0xffffffffffffff00, 0x0, 0x0)
        /data/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc420739380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /data/go/src/internal/poll/fd_unix.go:372 +0x1a8
net.(*netFD).accept(0xc420739380, 0x7f78268b46c8, 0x0, 0x17c4240)
        /data/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc4200fd210, 0xc4200a7e18, 0x412878, 0x30)
        /data/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc4200fd210, 0x16083a0, 0xc420737470, 0x14e4d00)
        /data/go/src/net/tcpsock.go:246 +0x49
net/http.tcpKeepAliveListener.Accept(0xc4200fd210, 0xc4200f8050, 0x14e4d00, 0x2351b80, 0x16d9060)
        /data/go/src/net/http/server.go:3216 +0x2f
net/http.(*Server).Serve(0xc4206e4ea0, 0x1877940, 0xc4200fd210, 0x0, 0x0)
        /data/go/src/net/http/server.go:2770 +0x1a5
net/http.(*Server).ListenAndServe(0xc4206e4ea0, 0x0, 0x0)
        /data/go/src/net/http/server.go:2711 +0xa9
k8s.io/kubernetes/cmd/kubeadm/app/cmd.TestRunListTokens.func1(0xc4206e4ea0, 0xc4202d54a0, 0x171e65d, 0x4)
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/token_test.go:408 +0x2f
created by k8s.io/kubernetes/cmd/kubeadm/app/cmd.TestRunListTokens
        /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/token_test.go:407 +0x6a6
```

**Comment by dims** [comment]
@gnufied let's please move this to https://github.com/kubernetes/kubeadm/issues/

/close

/sig cluster-lifecycle
