### ISSUE TITLE
v1.10.3 kube-controller-manager crashes after Azure provisioning load balancer

### ISSUE THREAD

**Issue by seanknox** [kubernetes/kubernetes#64716]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

/kind bug

**What happened**:
- Created a service of type `LoadBalancer` on Azure.
- The service is created successful and a LoadBalancer with public IP is created on Azure.
- kube-controller-manager goes into a crashloop

```
Jun 04 20:08:00 controller1 kube-controller-manager[6143]: I0604 20:08:00.553408    6143 azure_backoff.go:230] PublicIPAddressesClient.List(pixel104) - backoff: success
Jun 04 20:08:00 controller1 kube-controller-manager[6143]: I0604 20:08:00.611308    6143 azure_loadbalancer.go:444] reconcileLoadBalancer(default/nginx) - wantLb(true): started
Jun 04 20:08:00 controller1 kube-controller-manager[6143]: I0604 20:08:00.641296    6143 azure_backoff.go:181] LoadBalancerClient.List(pixel104) - backoff: success
Jun 04 20:08:00 controller1 kube-controller-manager[6143]: I0604 20:08:00.667537    6143 azure_loadbalancer.go:450] reconcileLoadBalancer(default/nginx): lb(pixel104) wantLb(true) resolved load balancer name
Jun 04 20:08:00 controller1 kube-controller-manager[6143]: I0604 20:08:00.784228    6143 azure_backoff.go:62] backoff: success
Jun 04 20:08:00 controller1 kube-controller-manager[6143]: I0604 20:08:00.856423    6143 azure_backoff.go:62] backoff: success
Jun 04 20:08:00 controller1 kube-controller-manager[6143]: I0604 20:08:00.869422    6143 azure_backoff.go:62] backoff: success
Jun 04 20:08:00 controller1 kube-controller-manager[6143]: I0604 20:08:00.882323    6143 azure_backoff.go:62] backoff: success
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: I0604 20:08:01.073606    6143 azure_loadbalancer.go:803] ensure(default/nginx): lb(pixel104) finished
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: E0604 20:08:01.206862    6143 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: /usr/local/go/src/runtime/asm_amd64.s:509
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: /usr/local/go/src/runtime/panic.go:491
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: /usr/local/go/src/runtime/panic.go:63
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: /usr/local/go/src/runtime/signal_unix.go:367
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_loadbalancer.go:888
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_loadbalancer.go:127
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:374
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:305
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:252
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:732
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:213
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:202
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:191
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: /usr/local/go/src/runtime/asm_amd64.s:2337
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
Jun 04 20:08:01 controller1 kube-controller-manager[6143]:         panic: runtime error: invalid memory address or nil pointer dereference
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x21dfb3d]
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: goroutine 1294 [running]:
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Jun 04 20:08:01 controller1 kube-controller-manager[6143]:         /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x111
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: panic(0x30c5960, 0x5646750)
Jun 04 20:08:01 controller1 kube-controller-manager[6143]:         /usr/local/go/src/runtime/panic.go:491 +0x283
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: k8s.io/kubernetes/pkg/cloudprovider/providers/azure.(*Cloud).reconcileSecurityGroup(0xc420479000, 0x7ffe3c3b2d3b, 0x8, 0xc4225465a0, 0xc422d99640, 0x1, 0x4, 0x1, 0xc422bdc500)
Jun 04 20:08:01 controller1 kube-controller-manager[6143]:         /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_loadbalancer.go:888 +0x66d
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: k8s.io/kubernetes/pkg/cloudprovider/providers/azure.(*Cloud).EnsureLoadBalancer(0xc420479000, 0x547a140, 0xc420010030, 0x7ffe3c3b2d3b, 0x8, 0xc4225465a0, 0xc4208aaa00, 0x4, 0x4, 0x5665580, ...)
Jun 04 20:08:01 controller1 kube-controller-manager[6143]:         /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/azure/azure_loadbalancer.go:127 +0x48b
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: k8s.io/kubernetes/pkg/controller/service.(*ServiceController).ensureLoadBalancer(0xc420962620, 0xc4225465a0, 0xc4225465a0, 0x37bd966, 0x6)
Jun 04 20:08:01 controller1 kube-controller-manager[6143]:         /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:374 +0xe8
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: k8s.io/kubernetes/pkg/controller/service.(*ServiceController).createLoadBalancerIfNeeded(0xc420962620, 0xc4209074a0, 0xd, 0xc4225465a0, 0xc422681b28, 0xc4226c9cc0)
Jun 04 20:08:01 controller1 kube-controller-manager[6143]:         /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:305 +0x20e
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: k8s.io/kubernetes/pkg/controller/service.(*ServiceController).processServiceUpdate(0xc420962620, 0xc422759448, 0xc4225465a0, 0xc4209074a0, 0xd, 0x0, 0x0)
Jun 04 20:08:01 controller1 kube-controller-manager[6143]:         /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:252 +0xe9
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: k8s.io/kubernetes/pkg/controller/service.(*ServiceController).syncService(0xc420962620, 0xc4209074a0, 0xd, 0x0, 0x0)
Jun 04 20:08:01 controller1 kube-controller-manager[6143]:         /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:732 +0x30d
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: k8s.io/kubernetes/pkg/controller/service.(*ServiceController).processNextWorkItem(0xc420962620, 0x634000)
Jun 04 20:08:01 controller1 kube-controller-manager[6143]:         /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:213 +0xe1
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: k8s.io/kubernetes/pkg/controller/service.(*ServiceController).worker(0xc420962620)
Jun 04 20:08:01 controller1 kube-controller-manager[6143]:         /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:202 +0x2b
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: k8s.io/kubernetes/pkg/controller/service.(*ServiceController).(k8s.io/kubernetes/pkg/controller/service.worker)-fm()
Jun 04 20:08:01 controller1 kube-controller-manager[6143]:         /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:191 +0x2a
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4226aa650)
Jun 04 20:08:01 controller1 kube-controller-manager[6143]:         /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4226aa650, 0x3b9aca00, 0x0, 0x1, 0xc42004d740)
Jun 04 20:08:01 controller1 kube-controller-manager[6143]:         /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
Jun 04 20:08:01 controller1 systemd[1]: kube-controller-manager.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4226aa650, 0x3b9aca00, 0xc42004d740)
Jun 04 20:08:01 controller1 kube-controller-manager[6143]:         /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
Jun 04 20:08:01 controller1 kube-controller-manager[6143]: created by k8s.io/kubernetes/pkg/controller/service.(*ServiceController).Run
Jun 04 20:08:01 controller1 kube-controller-manager[6143]:         /workspace/anago-v1.10.3-beta.0.74+2bba0127d85d5a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/service/service_controller.go:191 +0x20c
Jun 04 20:08:01 controller1 systemd[1]: kube-controller-manager.service: Unit entered failed state.
Jun 04 20:08:01 controller1 systemd[1]: kube-controller-manager.service: Failed with result 'exit-code'.
```

**What you expected to happen**: LoadBalancer service receives public IP and is available for traffic

**How to reproduce it (as minimally and precisely as possible)**: 
- provision a loadbalancer service on Azure with v1.10.3.

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux controller1 4.13.0-1018-azure #21-Ubuntu SMP Thu May 17 13:58:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:

**Comment by seanknox** [comment]
Logs of the initial request to create the load balancer service:

```
Jun 04 20:22:04 controller1 kube-controller-manager[7763]: I0604 20:22:04.143772    7763 service_controller.go:300] Ensuring LB for service default/nginx
Jun 04 20:22:04 controller1 kube-controller-manager[7763]: I0604 20:22:04.143835    7763 azure_loadbalancer.go:444] reconcileLoadBalancer(default/nginx) - wantLb(false): started
Jun 04 20:22:04 controller1 kube-controller-manager[7763]: I0604 20:22:04.144171    7763 event.go:218] Event(v1.ObjectReference{Kind:"Service", Namespace:"default", Name:"nginx", UID:"f1ee322c-6834-11e8-9daa-000d3a068552", APIVersion:"v1", ResourceVersion:"81093", FieldPath:""}): type: 'Normal' reason: 'EnsuringLoadBalancer' Ensuring load balancer
Jun 04 20:22:04 controller1 kube-controller-manager[7763]: I0604 20:22:04.364296    7763 azure_backoff.go:181] LoadBalancerClient.List(pixel104) - backoff: success
Jun 04 20:22:04 controller1 kube-controller-manager[7763]: I0604 20:22:04.364710    7763 azure_loadbalancer.go:450] reconcileLoadBalancer(default/nginx): lb(pixel104-internal) wantLb(false) resolved load balancer name
Jun 04 20:22:04 controller1 kube-controller-manager[7763]: I0604 20:22:04.364973    7763 azure_loadbalancer.go:803] ensure(default/nginx): lb(pixel104-internal) finished
Jun 04 20:22:04 controller1 kube-controller-manager[7763]: I0604 20:22:04.426269    7763 azure_backoff.go:230] PublicIPAddressesClient.List(pixel104) - backoff: success
Jun 04 20:22:08 controller1 kube-controller-manager[7763]: I0604 20:22:08.145428    7763 azure_backoff.go:368] backoff: success, HTTP response=200
Jun 04 20:22:08 controller1 kube-controller-manager[7763]: I0604 20:22:08.171041    7763 azure_loadbalancer.go:444] reconcileLoadBalancer(default/nginx) - wantLb(true): started
Jun 04 20:22:08 controller1 kube-controller-manager[7763]: I0604 20:22:08.210708    7763 azure_backoff.go:181] LoadBalancerClient.List(pixel104) - backoff: success
Jun 04 20:22:08 controller1 kube-controller-manager[7763]: I0604 20:22:08.211563    7763 azure_loadbalancer.go:248] selectLoadBalancer: cluster(pixel104) service(default/nginx) isInternal(false) - vmSetNames [controlleravset]
Jun 04 20:22:08 controller1 kube-controller-manager[7763]: I0604 20:22:08.211888    7763 azure_loadbalancer.go:450] reconcileLoadBalancer(default/nginx): lb(pixel104) wantLb(true) resolved load balancer name
Jun 04 20:22:08 controller1 kube-controller-manager[7763]: I0604 20:22:08.731816    7763 azure_backoff.go:368] backoff: success, HTTP response=201
Jun 04 20:22:08 controller1 kube-controller-manager[7763]: I0604 20:22:08.870137    7763 azure_backoff.go:62] backoff: success
Jun 04 20:22:08 controller1 kube-controller-manager[7763]: I0604 20:22:08.990981    7763 azure_backoff.go:62] backoff: success
Jun 04 20:22:08 controller1 kube-controller-manager[7763]: I0604 20:22:08.992582    7763 azure_backoff.go:62] backoff: success
Jun 04 20:22:09 controller1 kube-controller-manager[7763]: I0604 20:22:09.130082    7763 azure_backoff.go:62] backoff: success
```

**Comment by seanknox** [comment]
fyi @jessfraz @khenidak

**Comment by khenidak** [comment]
@feiskyer FYI

**Comment by seanknox** [comment]
BTW, this is with an Availability Set.

**Comment by seanknox** [comment]
Update: my azure.json was missing:

`"securityGroupName": "${NETWORK_SECURITY_GROUP}",`

Once I added it LoadBalancer services work. Still, we shouldn't panic in the main loop on this.

**Comment by khenidak** [comment]
Thanks @seanknox. I think we can close this issue. Create another for handling errors in both the cloud provider and the controller.

**Comment by feiskyer** [comment]
Filed #64739 to fix this
