### ISSUE TITLE
[Failing Tests] All GKE related jobs are failing in release-master-blocking, upgrade, 1.11 release-blocking jobs

### ISSUE THREAD

**Issue by AishSundar** [kubernetes/kubernetes#64789]
## Failing Jobs
* [gci-gke](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke)
* [gci-gke-slow](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke-slow)
* [gci-gke-reboot](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gke-reboot)
* [gke-gci-master-gci-1.10-downgrade-cluster-parallel](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-master-gci-1.10-downgrade-cluster-parallel)
* [gke-gci-1.10-gci-master-upgrade-cluster-new](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gke-gci-1.10-gci-master-upgrade-cluster-new)
* [gke-1.11](https://k8s-testgrid.appspot.com/sig-release-1.11-blocking#gke-1.11)
* [gke-slow-1.11](https://k8s-testgrid.appspot.com/sig-release-1.11-blocking#gke-slow-1.11)

## Error Logs
* [Master blocking job ](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/27368)
* [Upgrade test failure](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-master-gci-new-downgrade-cluster-parallel/3171)
* [1.11 iob](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cos-k8sbeta-default/3207)

/kind bug
/priority failing-test
/priority important-critical
/milestone v1.11
/assign @saad-ali 
cc @jberkus @tpepper

All GKE jobs are failing in various release dashboards. Code freeze for 1.11 is a couple of hours away.

**Comment by saad-ali** [comment]
Common error appears to be:

```
W0605 21:07:10.385]  zone: u'us-central1-f'>] finished with error: All cluster resources were brought up, but the cluster API is reporting that component "kube-apiserver" from endpoint "gke-b6b9aee342f4d6833488-b4d9" is unhealthy.
```

**Comment by saad-ali** [comment]
Failures seem to align with when https://github.com/kubernetes/kubernetes/pull/62005 was merged. But nothing in that PR seems suspicious. Having @mikedanese verify. Bringing up my own cluster on head to try and get a live cluster.

**Comment by jingax10** [comment]
I have a quick try to reproduce one of the failure test cases by

gcloud container clusters create --addons=HttpLoadBalancing,HorizontalPodAutoscaling,KubernetesDashboard --machine-type=n1-standard-2 --image-type=gci --num-nodes=3 --cluster-version=1.11.0-beta.1.222+f16c15909adccc test-ff924dde89

The cluster isn't up.

What I observed is the following:

1) kubelet on master is in crash-loop due to a panic

```
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]: I0605 22:45:26.511825    1123 kubenet_linux.go:254] CNI network config set to {
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:   "cniVersion": "0.1.0",
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:   "name": "kubenet",
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:   "type": "bridge",
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:   "bridge": "cbr0",
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:   "mtu": 1460,
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:   "addIf": "eth0",
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:   "isGateway": true,
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:   "ipMasq": false,
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:   "hairpinMode": false,
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:   "ipam": {
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:     "type": "host-local",
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:     "subnet": "172.17.42.1/16",
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:     "gateway": "172.17.0.1",
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:     "routes": [
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:       { "dst": "0.0.0.0/0" }
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:     ]
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:   }
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]: }
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]: I0605 22:45:26.513993    1123 kubelet_network.go:73] Setting Pod CIDR:  -> 172.17.42.1/16
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]: [signal SIGSEGV: segmentation violation code=0x1 addr=0xd0 pc=0x2b89096]
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]: goroutine 1 [running]:
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]: k8s.io/kubernetes/pkg/kubelet.NewMainKubelet(0xc42098bac8, 0xc42099c3c0, 0xc42098b860, 0x39afd02, 0x6, 0x0, 0x0, 0x
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:783 +0x2ae6
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]: k8s.io/kubernetes/cmd/kubelet/app.CreateAndInitKubelet(0xc42098bac8, 0xc42099c3c0, 0xc42098b860, 0x39afd02, 0x6, 0x
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:1055 +0x32a
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]: k8s.io/kubernetes/cmd/kubelet/app.RunKubelet(0xc42098b800, 0xc42098bac8, 0xc42099c3c0, 0x0, 0xc4200a3aa0, 0x0, 0x0)
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:934 +0x880
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]: k8s.io/kubernetes/cmd/kubelet/app.run(0xc42098b800, 0xc42099c3c0, 0xc4200a3aa0, 0x1, 0x1)
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:724 +0x635
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]: k8s.io/kubernetes/cmd/kubelet/app.Run(0xc42098b800, 0xc42099c3c0, 0xc4200a3aa0, 0xc420db9b80, 0x1)
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:412 +0xfc
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]: k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0xc4205da500, 0xc42004c0c0, 0xa, 0xa)
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:261 +0x521
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc4205da500, 0xc42004c0c0, 0xa, 0xa, 0xc4205da5
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4205da500, 0xc4205dc840, 0x3b055b8, 0xc420db
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4205da500, 0x3b15140, 0x5c3b3c0)
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]: main.main()
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm kubelet[1123]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/kubelet.go:43 +0x164
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm systemd[1]: kubelet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm systemd[1]: kubelet.service: Unit entered failed state.
Jun 05 22:45:26 gke-be6755264fce8f1fc221-75a5-08c1-vm systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jun 05 22:45:36 gke-be6755264fce8f1fc221-75a5-08c1-vm systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Jun 05 22:45:36 gke-be6755264fce8f1fc221-75a5-08c1-vm systemd[1]: Stopped Kubernetes kubelet.
```

No other master components could be up.

2) kubelet is in crashloop in node as well.

```
un 05 22:45:06 gke-test-ff924dde89-default-pool-4ab8167b-ns26 kubelet[1034]: I0605 22:45:06.985513    1034 bootstrap.go:53] Using bootstrap kubeconfig to generate TLS client cert, key
Jun 05 22:45:06 gke-test-ff924dde89-default-pool-4ab8167b-ns26 kubelet[1034]: I0605 22:45:06.987797    1034 bootstrap.go:79] No valid private key found for bootstrapping, creating a ne
Jun 05 22:45:22 gke-test-ff924dde89-default-pool-4ab8167b-ns26 kubelet[1034]: F0605 22:45:22.555599    1034 server.go:262] failed to run Kubelet: cannot create certificate signing requ
Jun 05 22:45:22 gke-test-ff924dde89-default-pool-4ab8167b-ns26 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jun 05 22:45:22 gke-test-ff924dde89-default-pool-4ab8167b-ns26 systemd[1]: kubelet.service: Unit entered failed state.
Jun 05 22:45:22 gke-test-ff924dde89-default-pool-4ab8167b-ns26 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jun 05 22:45:32 gke-test-ff924dde89-default-pool-4ab8167b-ns26 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Jun 05 22:45:32 gke-test-ff924dde89-default-pool-4ab8167b-ns26 systemd[1]: Stopped Kubernetes kubelet.
```

**Comment by dims** [comment]
/sig node

Looks like @mikedanese has a patch up at https://github.com/kubernetes/kubernetes/pull/64795

**Comment by AishSundar** [comment]
Waiting for new runs to verify the fix. Will reopen this issue if needed

**Comment by AishSundar** [comment]
/reopen 

Reopening this one until its actually verified to ensure it shows up in our tracking queries.

**Comment by AishSundar** [comment]
I see the GKE tests cleaning up in the [master-blocking suite](https://k8s-testgrid.appspot.com/sig-release-master-blocking). [1.11 branch](https://k8s-testgrid.appspot.com/sig-release-1.11-blocking) still doesn't seem to have the change (will have to wait for cutover?). The fix looks promising. Will wait for a couple more runs before I close

**Comment by dims** [comment]
all the GKE ones still look good

/close
