### ISSUE TITLE
kube-controller-manager - panic: runtime error: index out of range

### ISSUE THREAD

**Issue by jaredledvina** [kubernetes/kubernetes#65674]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Brand new install of Hypriot OS v1.9.0 on a Raspberry Pi Model B. Installed the latest v1.11 of `kubelet`, `kubectl`, and `kubeadm`. Performed the following commands:
```
kubeadm init --pod-network-cidr 10.244.0.0/16
curl -sSL https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml | sed "s/amd64/arm/g" | kubectl apply -f -
```

Everything reported successful and not errors were logged during the installation. However, `kube-controller-manager` errors and gets caught in a crash loop forever. 

`kube-controller-manager` logs:
```
❯ kubectl --namespace kube-system logs -f kube-controller-manager-node01
I0701 22:00:56.833121       1 controllermanager.go:122] Version: v1.11.0
W0701 22:00:56.837185       1 authentication.go:55] Authentication is disabled
I0701 22:00:56.837267       1 insecure_serving.go:49] Serving insecurely on 127.0.0.1:10252
I0701 22:00:56.838719       1 leaderelection.go:185] attempting to acquire leader lease  kube-system/kube-controller-manager...
I0701 22:01:12.918334       1 leaderelection.go:194] successfully acquired lease kube-system/kube-controller-manager
I0701 22:01:12.918943       1 event.go:221] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"kube-controller-manager", UID:"ad092a07-7d62-11e8-baa8-b827eb4f8d3a", APIVersion:"v1", ResourceVersion:"9838", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' node01_3b40d226-7d7a-11e8-86bc-b827eb4f8d3a became leader
I0701 22:01:13.073861       1 plugins.go:97] No cloud provider specified.
I0701 22:01:13.082943       1 controller_utils.go:1025] Waiting for caches to sync for tokens controller
I0701 22:01:13.185646       1 controller_utils.go:1032] Caches are synced for tokens controller
I0701 22:01:13.366035       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for {apps deployments}
I0701 22:01:13.366651       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for {autoscaling horizontalpodautoscalers}
I0701 22:01:13.366838       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for {networking.k8s.io networkpolicies}
I0701 22:01:13.367118       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for {rbac.authorization.k8s.io rolebindings}
I0701 22:01:13.367416       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for { endpoints}
I0701 22:01:13.367671       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for {apps daemonsets}
I0701 22:01:13.367847       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for {events.k8s.io events}
W0701 22:01:13.368052       1 shared_informer.go:311] resyncPeriod 47110443001297 is smaller than resyncCheckPeriod 64972060632246 and the informer has already started. Changing it to 64972060632246
I0701 22:01:13.368613       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for { podtemplates}
I0701 22:01:13.368886       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for {policy poddisruptionbudgets}
I0701 22:01:13.369064       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for { limitranges}
I0701 22:01:13.369350       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for {apps replicasets}
I0701 22:01:13.369528       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for {apps controllerrevisions}
I0701 22:01:13.369840       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for {extensions daemonsets}
I0701 22:01:13.370015       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for {extensions ingresses}
I0701 22:01:13.370192       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for {batch cronjobs}
I0701 22:01:13.370374       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for {rbac.authorization.k8s.io roles}
I0701 22:01:13.370608       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for {extensions replicasets}
I0701 22:01:13.370811       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for {apps statefulsets}
I0701 22:01:13.371049       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for {batch jobs}
W0701 22:01:13.371162       1 shared_informer.go:311] resyncPeriod 53843626648998 is smaller than resyncCheckPeriod 64972060632246 and the informer has already started. Changing it to 64972060632246
I0701 22:01:13.371684       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for { serviceaccounts}
I0701 22:01:13.372063       1 resource_quota_monitor.go:228] QuotaMonitor created object count evaluator for {extensions deployments}
I0701 22:01:13.372256       1 controllermanager.go:468] Started "resourcequota"
I0701 22:01:13.372375       1 resource_quota_controller.go:275] Starting resource quota controller
I0701 22:01:13.372485       1 controller_utils.go:1025] Waiting for caches to sync for resource quota controller
I0701 22:01:13.372798       1 resource_quota_monitor.go:301] QuotaMonitor running
I0701 22:01:13.437776       1 controllermanager.go:468] Started "deployment"
I0701 22:01:13.437874       1 deployment_controller.go:152] Starting deployment controller
I0701 22:01:13.438527       1 controller_utils.go:1025] Waiting for caches to sync for deployment controller
I0701 22:01:13.510727       1 controllermanager.go:468] Started "cronjob"
I0701 22:01:13.511107       1 cronjob_controller.go:94] Starting CronJob Manager
I0701 22:01:13.584227       1 controllermanager.go:468] Started "csrsigning"
I0701 22:01:13.584303       1 certificate_controller.go:113] Starting certificate controller
I0701 22:01:13.584570       1 controller_utils.go:1025] Waiting for caches to sync for certificate controller
I0701 22:01:13.792567       1 controllermanager.go:468] Started "horizontalpodautoscaling"
I0701 22:01:13.793177       1 horizontal.go:127] Starting HPA controller
I0701 22:01:13.793240       1 controller_utils.go:1025] Waiting for caches to sync for HPA controller
I0701 22:01:13.857905       1 controllermanager.go:468] Started "persistentvolume-expander"
I0701 22:01:13.858160       1 expand_controller.go:150] Starting expand controller
I0701 22:01:13.858316       1 controller_utils.go:1025] Waiting for caches to sync for expand controller
I0701 22:01:13.933249       1 controllermanager.go:468] Started "endpoint"
I0701 22:01:13.933291       1 endpoints_controller.go:153] Starting endpoint controller
I0701 22:01:13.933469       1 controller_utils.go:1025] Waiting for caches to sync for endpoint controller
I0701 22:01:14.001686       1 stateful_set.go:151] Starting stateful set controller
I0701 22:01:14.001747       1 controller_utils.go:1025] Waiting for caches to sync for stateful set controller
I0701 22:01:14.001638       1 controllermanager.go:468] Started "statefulset"
I0701 22:01:14.085618       1 controllermanager.go:468] Started "persistentvolume-binder"
I0701 22:01:14.086139       1 pv_controller_base.go:271] Starting persistent volume controller
I0701 22:01:14.086189       1 controller_utils.go:1025] Waiting for caches to sync for persistent volume controller
I0701 22:01:14.148571       1 controllermanager.go:468] Started "csrapproving"
I0701 22:01:14.148694       1 certificate_controller.go:113] Starting certificate controller
I0701 22:01:14.148747       1 controller_utils.go:1025] Waiting for caches to sync for certificate controller
I0701 22:01:14.193017       1 controllermanager.go:468] Started "csrcleaner"
I0701 22:01:14.193090       1 cleaner.go:81] Starting CSR cleaner controller
E0701 22:01:14.270970       1 core.go:72] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail
W0701 22:01:14.271417       1 controllermanager.go:465] Skipping "service"
I0701 22:01:14.342750       1 taint_manager.go:184] Sending events to api server.
I0701 22:01:14.343262       1 controllermanager.go:468] Started "nodelifecycle"
I0701 22:01:14.343346       1 node_lifecycle_controller.go:361] Starting node controller
I0701 22:01:14.343658       1 controller_utils.go:1025] Waiting for caches to sync for taint controller
I0701 22:01:14.405777       1 controllermanager.go:468] Started "pvc-protection"
I0701 22:01:14.405833       1 pvc_protection_controller.go:99] Starting PVC protection controller
I0701 22:01:14.406272       1 controller_utils.go:1025] Waiting for caches to sync for PVC protection controller
I0701 22:01:14.468100       1 controllermanager.go:468] Started "pv-protection"
I0701 22:01:14.468310       1 pv_protection_controller.go:81] Starting PV protection controller
I0701 22:01:14.468579       1 controller_utils.go:1025] Waiting for caches to sync for PV protection controller
I0701 22:01:14.625476       1 namespace_controller.go:186] Starting namespace controller
I0701 22:01:14.625788       1 controller_utils.go:1025] Waiting for caches to sync for namespace controller
I0701 22:01:14.625435       1 controllermanager.go:468] Started "namespace"
I0701 22:01:14.747909       1 job_controller.go:143] Starting job controller
I0701 22:01:14.747976       1 controller_utils.go:1025] Waiting for caches to sync for job controller
I0701 22:01:14.747866       1 controllermanager.go:468] Started "job"
I0701 22:01:14.898406       1 controllermanager.go:468] Started "disruption"
I0701 22:01:14.898474       1 disruption.go:288] Starting disruption controller
I0701 22:01:14.898929       1 controller_utils.go:1025] Waiting for caches to sync for disruption controller
I0701 22:01:15.048531       1 csi_plugin.go:111] kubernetes.io/csi: plugin initializing...
I0701 22:01:15.049351       1 controllermanager.go:468] Started "attachdetach"
I0701 22:01:15.049420       1 attach_detach_controller.go:259] Starting attach detach controller
I0701 22:01:15.049873       1 controller_utils.go:1025] Waiting for caches to sync for attach detach controller
I0701 22:01:15.239538       1 controllermanager.go:468] Started "clusterrole-aggregation"
I0701 22:01:15.240772       1 clusterroleaggregation_controller.go:148] Starting ClusterRoleAggregator
I0701 22:01:15.240870       1 controller_utils.go:1025] Waiting for caches to sync for ClusterRoleAggregator controller
I0701 22:01:15.347689       1 controllermanager.go:468] Started "replicationcontroller"
I0701 22:01:15.347745       1 replica_set.go:182] Starting replicationcontroller controller
I0701 22:01:15.347785       1 controller_utils.go:1025] Waiting for caches to sync for ReplicationController controller
I0701 22:01:15.495490       1 controllermanager.go:468] Started "podgc"
I0701 22:01:15.495672       1 gc_controller.go:76] Starting GC controller
I0701 22:01:15.495708       1 controller_utils.go:1025] Waiting for caches to sync for GC controller
W0701 22:01:15.779839       1 garbagecollector.go:649] failed to discover preferred resources: the cache has not been filled yet
I0701 22:01:15.781185       1 controllermanager.go:468] Started "garbagecollector"
I0701 22:01:15.781242       1 garbagecollector.go:133] Starting garbage collector controller
I0701 22:01:15.781289       1 controller_utils.go:1025] Waiting for caches to sync for garbage collector controller
I0701 22:01:15.781347       1 graph_builder.go:308] GraphBuilder running
I0701 22:01:15.949713       1 controllermanager.go:468] Started "daemonset"
I0701 22:01:15.949796       1 daemon_controller.go:253] Starting daemon sets controller
I0701 22:01:15.950378       1 controller_utils.go:1025] Waiting for caches to sync for daemon sets controller
I0701 22:01:16.098664       1 controllermanager.go:468] Started "ttl"
I0701 22:01:16.098731       1 ttl_controller.go:116] Starting TTL controller
I0701 22:01:16.098778       1 controller_utils.go:1025] Waiting for caches to sync for TTL controller
I0701 22:01:16.233528       1 node_ipam_controller.go:99] Sending events to api server.
I0701 22:01:26.300398       1 range_allocator.go:78] Sending events to api server.
I0701 22:01:26.300944       1 range_allocator.go:99] No Service CIDR provided. Skipping filtering out service addresses.
I0701 22:01:26.301022       1 range_allocator.go:108] Node node01 has CIDR 10.244.0.0/24, occupying it in CIDR map
I0701 22:01:26.301213       1 controllermanager.go:468] Started "nodeipam"
I0701 22:01:26.302164       1 node_ipam_controller.go:165] Starting ipam controller
I0701 22:01:26.302258       1 controller_utils.go:1025] Waiting for caches to sync for node controller
I0701 22:01:26.378640       1 controllermanager.go:468] Started "serviceaccount"
I0701 22:01:26.379737       1 serviceaccounts_controller.go:115] Starting service account controller
I0701 22:01:26.380025       1 controller_utils.go:1025] Waiting for caches to sync for service account controller
I0701 22:01:26.454869       1 controllermanager.go:468] Started "bootstrapsigner"
I0701 22:01:26.454943       1 controller_utils.go:1025] Waiting for caches to sync for bootstrap_signer controller
I0701 22:01:26.526308       1 controllermanager.go:468] Started "tokencleaner"
I0701 22:01:26.526364       1 tokencleaner.go:116] Starting token cleaner controller
W0701 22:01:26.526398       1 core.go:150] configure-cloud-routes is set, but no cloud provider specified. Will not configure cloud provider routes.
I0701 22:01:26.526401       1 controller_utils.go:1025] Waiting for caches to sync for token_cleaner controller
W0701 22:01:26.526432       1 controllermanager.go:465] Skipping "route"
I0701 22:01:26.592953       1 controllermanager.go:468] Started "replicaset"
I0701 22:01:26.593011       1 replica_set.go:182] Starting replicaset controller
I0701 22:01:26.594574       1 controller_utils.go:1025] Waiting for caches to sync for ReplicaSet controller
I0701 22:01:26.594855       1 controller_utils.go:1025] Waiting for caches to sync for resource quota controller
I0701 22:01:26.607709       1 controller_utils.go:1025] Waiting for caches to sync for garbage collector controller
I0701 22:01:26.629545       1 controller_utils.go:1032] Caches are synced for token_cleaner controller
W0701 22:01:26.720302       1 actual_state_of_world.go:491] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="node01" does not exist
I0701 22:01:26.733340       1 controller_utils.go:1032] Caches are synced for HPA controller
I0701 22:01:26.733469       1 controller_utils.go:1032] Caches are synced for node controller
I0701 22:01:26.739355       1 range_allocator.go:157] Starting range CIDR allocator
I0701 22:01:26.739527       1 controller_utils.go:1025] Waiting for caches to sync for cidrallocator controller
I0701 22:01:26.741541       1 controller_utils.go:1032] Caches are synced for ReplicationController controller
I0701 22:01:26.742992       1 controller_utils.go:1032] Caches are synced for GC controller
I0701 22:01:26.784247       1 controller_utils.go:1032] Caches are synced for service account controller
I0701 22:01:26.797619       1 controller_utils.go:1032] Caches are synced for ReplicaSet controller
I0701 22:01:26.809493       1 controller_utils.go:1032] Caches are synced for stateful set controller
I0701 22:01:26.809643       1 controller_utils.go:1032] Caches are synced for TTL controller
I0701 22:01:26.809493       1 controller_utils.go:1032] Caches are synced for PVC protection controller
I0701 22:01:26.828328       1 controller_utils.go:1032] Caches are synced for namespace controller
I0701 22:01:26.836768       1 controller_utils.go:1032] Caches are synced for endpoint controller
I0701 22:01:26.838895       1 controller_utils.go:1032] Caches are synced for deployment controller
I0701 22:01:26.839800       1 controller_utils.go:1032] Caches are synced for cidrallocator controller
I0701 22:01:26.841662       1 controller_utils.go:1032] Caches are synced for ClusterRoleAggregator controller
I0701 22:01:26.845050       1 controller_utils.go:1032] Caches are synced for taint controller
I0701 22:01:26.845182       1 taint_manager.go:205] Starting NoExecuteTaintManager
I0701 22:01:26.845380       1 node_lifecycle_controller.go:1095] Initializing eviction metric for zone:
panic: runtime error: index out of range

goroutine 1805 [running]:
k8s.io/kubernetes/pkg/controller/nodelifecycle/scheduler.(*NoExecuteTaintManager).Run.func1(0x155e8b90, 0x8, 0x1527c100)
	/workspace/anago-v1.11.0-rc.3.3+91e7b4fd31fcd3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/nodelifecycle/scheduler/taint_manager.go:229 +0x1f8
created by k8s.io/kubernetes/pkg/controller/nodelifecycle/scheduler.(*NoExecuteTaintManager).Run
	/workspace/anago-v1.11.0-rc.3.3+91e7b4fd31fcd3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/nodelifecycle/scheduler/taint_manager.go:217 +0x27c
```

I've included the full output of the commands above incase it's useful for folks:
```
HypriotOS/armv7: root@node01 in ~
# kubeadm init --pod-network-cidr 10.244.0.0/16
I0701 19:04:30.916028    2179 feature_gate.go:230] feature gates: &{map[]}
[init] using Kubernetes version: v1.11.0
[preflight] running pre-flight checks
I0701 19:04:31.053140    2179 kernel_validator.go:81] Validating kernel version
I0701 19:04:31.054345    2179 kernel_validator.go:96] Validating kernel config
	[WARNING SystemVerification]: docker version is greater than the most recently validated version. Docker version: 18.05.0-ce. Max validated version: 17.03
[preflight/images] Pulling images required for setting up a Kubernetes cluster
[preflight/images] This might take a minute or two, depending on the speed of your internet connection
[preflight/images] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[preflight] Activating the kubelet service
[certificates] Generated ca certificate and key.
[certificates] Generated apiserver certificate and key.
[certificates] apiserver serving cert is signed for DNS names [node01 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 172.16.1.50]
[certificates] Generated apiserver-kubelet-client certificate and key.
[certificates] Generated sa key and public key.
[certificates] Generated front-proxy-ca certificate and key.
[certificates] Generated front-proxy-client certificate and key.
[certificates] Generated etcd/ca certificate and key.
[certificates] Generated etcd/server certificate and key.
[certificates] etcd/server serving cert is signed for DNS names [node01 localhost] and IPs [127.0.0.1 ::1]
[certificates] Generated etcd/peer certificate and key.
[certificates] etcd/peer serving cert is signed for DNS names [node01 localhost] and IPs [172.16.1.50 127.0.0.1 ::1]
[certificates] Generated etcd/healthcheck-client certificate and key.
[certificates] Generated apiserver-etcd-client certificate and key.
[certificates] valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/scheduler.conf"
[controlplane] wrote Static Pod manifest for component kube-apiserver to "/etc/kubernetes/manifests/kube-apiserver.yaml"
[controlplane] wrote Static Pod manifest for component kube-controller-manager to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
[controlplane] wrote Static Pod manifest for component kube-scheduler to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/manifests/etcd.yaml"
[init] waiting for the kubelet to boot up the control plane as Static Pods from directory "/etc/kubernetes/manifests"
[init] this might take a minute or longer if the control plane images have to be pulled
[apiclient] All control plane components are healthy after 184.018533 seconds
[uploadconfig] storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[kubelet] Creating a ConfigMap "kubelet-config-1.11" in namespace kube-system with the configuration for the kubelets in the cluster
[markmaster] Marking the node node01 as master by adding the label "node-role.kubernetes.io/master=''"
[markmaster] Marking the node node01 as master by adding the taints [node-role.kubernetes.io/master:NoSchedule]
[patchnode] Uploading the CRI Socket information "/var/run/dockershim.sock" to the Node API object "node01" as an annotation
[bootstraptoken] using token: ak90k7.krztzu7fckmy3x96
[bootstraptoken] configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
[bootstraptoken] configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
[bootstraptoken] configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
[bootstraptoken] creating the "cluster-info" ConfigMap in the "kube-public" namespace
[addons] Applied essential addon: CoreDNS
[addons] Applied essential addon: kube-proxy

Your Kubernetes master has initialized successfully!

To start using your cluster, you need to run the following as a regular user:

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/

You can now join any number of machines by running the following on each node
as root:

  kubeadm join 172.16.1.50:6443 --token ak90k7.krztzu7fckmy3x96 --discovery-token-ca-cert-hash sha256:a8c2be99faea0ad52cd39320750f07d01e30d1dc8d27c581cea4a6dfc0110add
```

```
HypriotOS/armv7: pirate@node01 in ~
$ curl -sSL https://rawgit.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml | sed "s/amd64/arm/g" | kubectl create -f -
clusterrole.rbac.authorization.k8s.io/flannel created
clusterrolebinding.rbac.authorization.k8s.io/flannel created
serviceaccount/flannel created
configmap/kube-flannel-cfg created
daemonset.extensions/kube-flannel-ds created
```

**What you expected to happen**:

After a clean install, `kube-controller-manager` should not exit with a `panic: runtime error: index out of range` error. 

**How to reproduce it (as minimally and precisely as possible)**:
Perform a clean install of v1.11 on a Rasberry PI Model B, boostrap cluster with `kubeadm` and deploy `flannel`. `kube-controller-manager` will never stay up and panic. 

**Anything else we need to know?**:
My Go knowledge is very limited however, I think https://github.com/kubernetes/kubernetes/commit/620f7ab4ce2eb943ba238cf82f65d889907db1d1 might be related. 

The note itself appears Ready:
```
❯ kubectl get nodes
NAME      STATUS    ROLES     AGE       VERSION
node01    Ready     master    2h        v1.11.0
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T22:29:25Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/arm"}
```
- Cloud provider or hardware configuration: Raspberry Pi Model B
- OS (e.g. from /etc/os-release): `HypriotOS/armhf v1.9.0` 
- Kernel (e.g. `uname -a`): `Linux node01 4.14.34-hypriotos-v7+ #1 SMP Sun Apr 22 14:57:31 UTC 2018 armv7l GNU/Linux`
- Install tools: Officially `apt` repo's, used `kubeadm` to initialize node
- Others: 

As always, I'm more than happy to provide any details at all that might be helpful to debug here.

**Comment by jaredledvina** [comment]
I've had a hard time figuring out which SIG specifically might be owners for this but I _think_ scheduling might

@kubernetes/sig-scheduling-bugs

**Comment by wgliang** [comment]
#65603 maybe have fixed your issue. Or we can ensure if you give the last commit key.

**Comment by jaredledvina** [comment]
Hey @wgliang, thanks for the tip, I'm not sure how to properly give the last commit key I'm running. Is there a command or something I can use to get you that information? 

If it helps, here's the version of the packages I've installed from https://packages.cloud.google.com/apt/
```
# aptitude show kubelet
Package: kubelet
Version: 1.11.0-00
New: yes
State: installed
Automatically installed: no
Priority: optional
Section: misc
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Architecture: armhf
Uncompressed Size: 145 M
Depends: iptables (>= 1.4.21), kubernetes-cni (= 0.6.0), iproute2, socat, util-linux, mount, ebtables, ethtool, init-system-helpers (>= 1.18~)
Description: Kubernetes Node Agent
 The node agent of Kubernetes, the container cluster manager
Homepage: https://kubernetes.io
```
```
# aptitude show kubeadm
Package: kubeadm
Version: 1.11.0-00
New: yes
State: installed
Automatically installed: no
Priority: optional
Section: misc
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Architecture: armhf
Uncompressed Size: 51.2 M
Depends: kubelet (>= 1.6.0), kubectl (>= 1.6.0), kubernetes-cni (>= 0.6.0), cri-tools (>= 1.11.0)
Description: Kubernetes Cluster Bootstrapping Tool
 The Kubernetes command line tool for bootstrapping a Kubernetes cluster.
Homepage: https://kubernetes.io
```
```
# aptitude show kubectl
Package: kubectl
Version: 1.11.0-00
New: yes
State: installed
Automatically installed: no
Priority: optional
Section: misc
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Architecture: armhf
Uncompressed Size: 49.4 M
Description: Kubernetes Command Line Tool
 The Kubernetes command line tool for interacting with the Kubernetes API.
Homepage: https://kubernetes.io
```

**Comment by jaredledvina** [comment]
And from https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-armhf/Packages, I believe that version of `kubelet` is this `.deb.`: https://packages.cloud.google.com/apt/pool/kubelet_1.11.0-00_armhf_b7b98c3f9afda576a8778ae748ddbc0f449675380410d04c76a13b5947255ab8.deb

**Comment by liggitt** [comment]
This is fixed in master in https://github.com/kubernetes/kubernetes/pull/65596 and will be fixed in 1.11.1

**Comment by liggitt** [comment]
The issue was introduced in https://github.com/kubernetes/kubernetes/commit/f7cf33e218b93da90e8051c51131b64843ca9cfc#diff-ac6d86c4c48c967b3742e839bb016029 which assumed that casting a uint32 to an unsized int would always be positive. On a 32-bit platform, that is not the case

**Comment by d11wtq** [comment]
The last comment here was 11 hours ago. Is it correct the images are still unavailable?

```
$ docker pull k8s.gcr.io/kube-apiserver-arm:v1.11.1
Pulling repository k8s.gcr.io/kube-apiserver-arm
unauthorized: authentication required
```

**Comment by subodhp** [comment]
I am not able to pull as well. 

root@kubemaster:~# docker pull k8s.gcr.io/kube-controller-manager-amd64
Using default tag: latest
Pulling repository k8s.gcr.io/kube-controller-manager-amd64
unauthorized: authentication required

**Comment by neolit123** [comment]
@subodhp 
not sure which version your are targeting but you should use a version tag - e.g.:
```
docker pull k8s.gcr.io/kube-controller-manager-amd64:v1.11.2
```

or get the version with:
https://dl.k8s.io/release/stable-1.11.txt
