### ISSUE TITLE
Failing Test: [sig-scalability] Density [Feature:Performance]

### ISSUE THREAD

**Issue by mohammedzee1000** [kubernetes/kubernetes#66337]
# Failing Jobs
[sig-release-master-blocking#gce-scale-performance](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-scale-performance)

# Failing Tests
[should allow starting 30 pods per node using { ReplicationController} with 0 secrets, 0 configmaps and 0 daemons](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/180)

Tests Failing on sig-master-blocking

/kind bug
/sig scalability
/priority failing-test
/priority important-soon
/milestone v1.12
/cc @tpepper @AishSundar

**Comment by mborsz** [comment]
/cc @shyamjvs 

I was debugging this attempt today and the reason it fails is that pod 'load-medium-1113-25xkb' in RC 'load-medium-1113' cannot be stopped.

In kubelet's logs I see:
```
I0716 19:52:37.565795    1713 kubelet.go:1815] SyncLoop (DELETE, "api"): "load-medium-1113-25xkb_e2e-tests-load-30-nodepods-14-zx6kk(b3e8f551-88d6-11e8-ac58-42010a280002)"
I0716 19:52:37.566439    1713 kuberuntime_container.go:553] Killing container "docker://075b9e657986f5462fae46802e94c5188ca5cc80411f6e01f051ee4e16a1d430" with 1 second grace period
E0716 19:52:39.569515    1713 remote_runtime.go:229] StopContainer "075b9e657986f5462fae46802e94c5188ca5cc80411f6e01f051ee4e16a1d430" from runtime service failed: rpc error: code = Unknown desc = Error response from daemon: Cannot stop container 075b9e657986f5462fae46802e94c5188ca5cc80411f6e01f051ee4e16a1d430: Cannot kill container 075b9e657986f5462fae46802e94c5188ca5cc80411f6e01f051ee4e16a1d430: rpc error: code = 14 desc = grpc: the connection is unavailable
```

In docker's logs I see:
```
time="2018-07-16T19:52:37.568066954Z" level=debug msg="Calling POST /v1.27/containers/075b9e657986f5462fae46802e94c5188ca5cc80411f6e01f051ee4e16a1d430/stop?t=2"
time="2018-07-16T19:52:37.568098372Z" level=debug msg="Sending kill signal 15 to container 075b9e657986f5462fae46802e94c5188ca5cc80411f6e01f051ee4e16a1d430"
time="2018-07-16T19:52:39.568381981Z" level=error msg="Handler for POST /v1.27/containers/075b9e657986f5462fae46802e94c5188ca5cc80411f6e01f051ee4e16a1d430/stop returned error: Cannot stop container 075b9e657986f5462fae46802e94c5188ca5cc80411f6e01f051ee4e16a1d430: Cannot kill container 075b9e657986f5462fae46802e94c5188ca5cc80411f6e01f051ee4e16a1d430: rpc error: code = 14 desc = grpc: the connection is unavailable"
```

So it looks like containerd <-> dockerd grpc connection is broken.
I think the reason is that containerd has crashed - in dockerd's logs I see:
```
unexpected fault address 0x250a9c916548
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x250a9c916548 pc=0x250a9c916548]
goroutine 31 [running]:
runtime.throw(0x8dc28c, 0x5)
        /usr/lib64/go/src/runtime/panic.go:605 +0x95 fp=0xc4202659e8 sp=0xc4202659c8 pc=0x42d345
runtime.sigpanic()
        /usr/lib64/go/src/runtime/signal_unix.go:374 +0x227 fp=0xc420265a38 sp=0xc4202659e8 pc=0x4440a7
created by google.golang.org/grpc.(*Server).Serve
        /build/lakitu/tmp/portage/app-emulation/containerd-0.2.5_p20170308-r3/work/containerd-0.2.5_p20170308/src/github.com/docker/containerd/vendor/src/google.golang.org/grpc/server.go:357 +0x167
goroutine 1 [chan receive, 678 minutes]:
main.daemon(0xc4200c0500, 0xd, 0x0)
        /build/lakitu/tmp/portage/app-emulation/containerd-0.2.5_p20170308-r3/work/containerd-0.2.5_p20170308/src/github.com/docker/containerd/containerd/main.go:193 +0x639
main.main.func2(0xc4200c0500)
        /build/lakitu/tmp/portage/app-emulation/containerd-0.2.5_p20170308-r3/work/containerd-0.2.5_p20170308/src/github.com/docker/containerd/containerd/main.go:150 +0x2b
github.com/codegangsta/cli.(*App).Run(0xc4200c03c0, 0xc4200100d0, 0xd, 0xd, 0x0, 0x0)
        /build/lakitu/tmp/portage/app-emulation/containerd-0.2.5_p20170308-r3/work/containerd-0.2.5_p20170308/src/github.com/docker/containerd/vendor/src/github.com/codegangsta/cli/app.go:192 +0x90b
main.main()
        /build/lakitu/tmp/portage/app-emulation/containerd-0.2.5_p20170308-r3/work/containerd-0.2.5_p20170308/src/github.com/docker/containerd/containerd/main.go:154 +0x199
goroutine 5 [syscall, 678 minutes]:
os/signal.signal_recv(0x0)
        /usr/lib64/go/src/runtime/sigqueue.go:131 +0xa6
os/signal.loop()
        /usr/lib64/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /usr/lib64/go/src/os/signal/signal_unix.go:28 +0x41
goroutine 15 [syscall]:
syscall.Syscall6(0xe8, 0x5, 0xc42003d9b8, 0x80, 0xffffffffffffffff, 0x0, 0x0, 0xb45c80, 0xc42022ad00, 0x0)
        /usr/lib64/go/src/syscall/asm_linux_amd64.s:44 +0x5
syscall.EpollWait(0x5, 0xc42003d9b8, 0x80, 0x80, 0xffffffffffffffff, 0x1, 0x0, 0x0)
        /usr/lib64/go/src/syscall/zsyscall_linux_amd64.go:349 +0x77
github.com/docker/containerd/archutils.EpollWait(0x5, 0xc42003d9b8, 0x80, 0x80, 0xffffffffffffffff, 0x1, 0x0, 0x0)
        /build/lakitu/tmp/portage/app-emulation/containerd-0.2.5_p20170308-r3/work/containerd-0.2.5_p20170308/src/github.com/docker/containerd/archutils/epoll.go:21 +0x53
github.com/docker/containerd/supervisor.(*Monitor).start(0xc420125f80)
        /build/lakitu/tmp/portage/app-emulation/containerd-0.2.5_p20170308-r3/work/containerd-0.2.5_p20170308/src/github.com/docker/containerd/supervisor/monitor_linux.go:135 +0x7b
created by github.com/docker/containerd/supervisor.NewMonitor
        /build/lakitu/tmp/portage/app-emulation/containerd-0.2.5_p20170308-r3/work/containerd-0.2.5_p20170308/src/github.com/docker/containerd/supervisor/monitor_linux.go:24 +0x15f
goroutine 10 [chan receive]:
github.com/rcrowley/go-metrics.(*meterArbiter).tick(0xb71280)
        /build/lakitu/tmp/portage/app-emulation/containerd-0.2.5_p20170308-r3/work/containerd-0.2.5_p20170308/src/github.com/docker/containerd/vendor/src/github.com/rcrowley/go-metrics/meter.go:221 +0x31
created by github.com/rcrowley/go-metrics.NewMeter
        /build/lakitu/tmp/portage/app-emulation/containerd-0.2.5_p20170308-r3/work/containerd-0.2.5_p20170308/src/github.com/docker/containerd/vendor/src/github.com/rcrowley/go-metrics/meter.go:40 +0x127
goroutine 14 [IO wait, 678 minutes]:
internal/poll.runtime_pollWait(0x7f0b4442ff70, 0x72, 0xffffffffffffffff)
        /usr/lib64/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4200ab298, 0x72, 0xc42003cd00, 0x0, 0x0)
        /usr/lib64/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc4200ab298, 0xffffffffffffff00, 0x0, 0x0)
        /usr/lib64/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc4200ab280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib64/go/src/internal/poll/fd_unix.go:335 +0x1e2
net.(*netFD).accept(0xc4200ab280, 0xc42000e820, 0x0, 0x0)
        /usr/lib64/go/src/net/fd_unix.go:238 +0x42
net.(*UnixListener).accept(0xc420125d40, 0x7564c7, 0x45aaf0, 0xc42003cee0)
(...)
```

I'm going to check if this is a known issue.

**Comment by mborsz** [comment]
I think it also happened in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/183: all attempts to create a pending pod are failing there with a similar error "the connection is unavailable". Unfortunately docker.log is incomplete there, so I can't see if containerd has crashed on that machine.

**Comment by shyamjvs** [comment]
Thanks for digging @mborsz. So 180 and 183 indeed failed due to the reason you pointed above. I took a look into 181, and that one seems to fail in a different way (this may potentially be related to 180,183). A few pods that were already running/scheduled went down sometime later, e.g:

```
I0718 21:42:27.063] I0718 21:42:27.063066    7653 runners.go:177] Pod density150000-24-d1e41ecc-8ac7-11e8-a3f8-0a580a3c8141-5qjdd was deleted, had phase Running and host gce-scale-cluster-minion-group-1-lvq9
I0718 21:42:27.064] Jul 18 21:42:27.063: INFO: Unexpected error occurred: Number of reported pods for density150000-24-d1e41ecc-8ac7-11e8-a3f8-0a580a3c8141 changed: 2999 vs 3000
I0718 21:42:27.066] Jul 18 21:42:27.066: INFO: Pod density150000-29-d1e41ecc-8ac7-11e8-a3f8-0a580a3c8141-gj7bt was deleted, had phase Running and host gce-scale-cluster-minion-group-1-lvq9
I0718 21:42:27.066] 
I0718 21:42:27.067] I0718 21:42:27.066700    7653 runners.go:177] Pod density150000-29-d1e41ecc-8ac7-11e8-a3f8-0a580a3c8141-gj7bt was deleted, had phase Running and host gce-scale-cluster-minion-group-1-lvq9
I0718 21:42:27.067] Jul 18 21:42:27.066: INFO: Unexpected error occurred: Number of reported pods for density150000-29-d1e41ecc-8ac7-11e8-a3f8-0a580a3c8141 changed: 2999 vs 3000
I0718 21:42:27.067] Jul 18 21:42:27.067: INFO: Number of reported pods for density150000-30-d1e41ecc-8ac7-11e8-a3f8-0a580a3c8141 changed: 2999 vs 3000, pods that changed since the last iteration:
I0718 21:42:27.068] I0718 21:42:27.067726    7653 runners.go:177] Number of reported pods for density150000-30-d1e41ecc-8ac7-11e8-a3f8-0a580a3c8141 changed: 2999 vs 3000, pods that changed since the last iteration:
I0718 21:42:27.071] Jul 18 21:42:27.071: INFO: Pod density150000-30-d1e41ecc-8ac7-11e8-a3f8-0a580a3c8141-v9p98 was deleted, had phase Running and host gce-scale-cluster-minion-group-1-lvq9
```

All of them were pods running on the same node `gce-scale-cluster-minion-group-1-lvq9`. Looking at the [kubelet logs](http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/181/artifacts/gce-scale-cluster-minion-group-1-lvq9/), it seems to have gone down for 6 mins and then restarted when the above happened. So most likely the deletion of pods was a consequence of node-controller removing them because node was unhealthy for more than 5 mins (iirc). We need to understand, why kubelet was restarted (sadly docker logs are missing and I can't find anything useful in kernel logs).

**Comment by mborsz** [comment]
I debugged 181 as well, it's unrelated: the GCE VM gce-scale-cluster-minion-group-1-lvq9 was restarted due to host error (in activity logs of that VM I can see hostError and automaticRestart operations that happened exactly that time). I added information about this to the relevant issue:
https://github.com/kubernetes/kubernetes/issues/60097#issuecomment-407412794

**Comment by mborsz** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/179 is the same issue

docker's logs shows the same error:
```
time="2018-07-14T06:05:08.680177958Z" level=error msg="Handler for POST /v1.27/containers/a4803e38181d9471e43cecf0194a6934667ad873697a4a7d696fc79edb01a429/stop returned error: Cannot stop container a4803e38181d9471e43cecf0194a6934667ad873697a4a7d696fc79edb01a429: Cannot kill container a4803e38181d9471e43cecf0194a6934667ad873697a4a7d696fc79edb01a429: rpc error: code = 14 desc = grpc: the connection is unavailable"
```

**Comment by mborsz** [comment]
FTR We are using `cos-stable-65-10323-64-0` with docker in 17.03.2-ce version and containerd version `0.2.3 commit: 595e75c212d19a81d2b808a518fe1afc1391dad5`

**Comment by mborsz** [comment]
595e75c212d19a81d2b808a518fe1afc1391dad5 version of containerd uses rather old version of grpc library:
https://github.com/containerd/containerd/blob/595e75c212d19a81d2b808a518fe1afc1391dad5/vendor/src/google.golang.org/grpc/server.go#L357

I checked and even relatively fresh versions of cos (cos-stable-67-10575-62-0) are using the same version of docker (and containerd), so changing cos image won't help much here

**Comment by mborsz** [comment]
https://github.com/moby/moby/issues/34944 describes the same issue in that 17.03.2 version.

**Comment by mborsz** [comment]
docker implements health checking mechanism that restarts containerd when it doesn't respond to health check.
If this would work correctly in that case, it should be able to mitigate impact of this sigsegv.

https://github.com/moby/moby/blob/17.03.x/libcontainerd/remote_unix.go#L158

I think there is a bug in that logic:
In case of sigsegv, the error message is "transport is closing":
```
unexpected fault address 0x250a9c916548
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x250a9c916548 pc=0x250a9c916548]
goroutine 31 [running]:
runtime.throw(0x8dc28c, 0x5)
        /usr/lib64/go/src/runtime/panic.go:605 +0x95 fp=0xc4202659e8 sp=0xc4202659c8 pc=0x42d345
runtime.sigpanic()
        /usr/lib64/go/src/runtime/signal_unix.go:374 +0x227 fp=0xc420265a38 sp=0xc4202659e8 pc=0x4440a7
created by google.golang.org/grpc.(*Server).Serve
        /build/lakitu/tmp/portage/app-emulation/containerd-0.2.5_p20170308-r3/work/containerd-0.2.5_p20170308/src/github.com/docker/containerd/vendor/src/google.golang.org/grpc/server.go:357 +0x167
(...)
github.com/docker/containerd/runtime.(*container).createCmd.func1.1(0xc42022b520)
        /build/lakitu/tmp/portage/app-emulation/containerd-0.2.5_p20170308-r3/work/containerd-0.2.5_p20170308/src/github.com/docker/containerd/runtime/container.go:492 +0x47
created by github.com/docker/containerd/runtime.(*container).createCmd.func1
        /build/lakitu/tmp/portage/app-emulation/containerd-0.2.5_p20170308-r3/work/containerd-0.2.5_p20170308/src/github.com/docker/containerd/runtime/container.go:491 +0x3f
time="2018-07-16T19:46:33.439288738Z" level=error msg="libcontainerd: failed to receive event from containerd: rpc error: code = 13 desc = transport is closing"
time="2018-07-16T19:46:33.439391820Z" level=debug msg="libcontainerd: containerd health check returned error: rpc error: code = 13 desc = transport is closing"
```
The logic assumes that any error ending with "is closing" should stop the healthchecking logic.

So to sumarize:
* containerd in 0.2.3 has a bug that triggers sigsegv (0.2.x versions are no longer supported)
* docker 17.03.2 has a bug in containerd restarting logic (IIUC this version is no longer supported as well)
* all cos images are using 17.03.2 docker version for some reason.

I will reach out to to the COS team to understand reasons for using 17.03.2 and options we have.

**Comment by shyamjvs** [comment]
Great debugging @mborsz. One question I have here is what changed on our side that we started to see such failures recently? As our jobs were relatively green earlier and I don't remember such failures happening. I looked at the [cos version](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-test.sh#L78) we're using and that last changed 3 months ago.

**Comment by mborsz** [comment]
Instance from 1.11: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-beta/1082

**Comment by shyamjvs** [comment]
@mborsz Do you have a rough estimate around when we started seeing such failures?

**Comment by mborsz** [comment]
I think it started around ~2018-07-12.

Latest run is also affected by this issue: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/184

**Comment by shyamjvs** [comment]
Thanks.
So yesterday I took a look at test-infra changes and found following relevant ones:

- (July 12) https://github.com/kubernetes/test-infra/pull/8661 moved 5k-node scalability tests to us-east1-b (however, lower scale jobs (which were untouched) are also seeing the issue)
- (July 9) https://github.com/kubernetes/test-infra/pull/8604 enabled advanced audit log for scale-performance (but this was disabled again in https://github.com/kubernetes/test-infra/pull/8662 few days later)
- (July 5) https://github.com/kubernetes/test-infra/pull/8585 increased scheduler/c-m qps for smaller jobs (so this should've been a no-op for large-scale ones, where we're also seeing this issue)
- (July 4) https://github.com/kubernetes/test-infra/pull/8576 enabled kubelet profiling (but this one isn't too suspicious)
- (July 4) https://github.com/kubernetes/test-infra/pull/8575 changed 5k jobs to --v=2
- (July 3) https://github.com/kubernetes/test-infra/pull/8554 changed all scalability jobs except 5k ones to --v=2

None of the above look too suspicious. Moreover, assuming 2018-07-12 is the start time of regression, only the first one seems to have the chance (but that one too doesn't explain failures at lower scale).

**Comment by shyamjvs** [comment]
So @mborsz and me were discussing offline and I suggested looking at historical runs of our gce-100 job (where we seem to face the issue) to find the oldest suffering run as that job is running way more frequently than 5k one. Also, it maybe the case that some node's docker crashed even when the test was green (due to happening at a less critical time) - but this is sth to verify.

**Comment by mborsz** [comment]
Also https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable2/418

**Comment by guineveresaenger** [comment]
@wojtek-t @countspongebob there seems to be recent activity on this, and it's a 1.12 known issue. Should this be a 1.12 milestone? Please update.

**Comment by shyamjvs** [comment]
Yes, let's keep it in the milestone until we debug it or prove it's
unrelated to k8s.

**Comment by mohammedzee1000** [comment]
CI is green

**Comment by shyamjvs** [comment]
To update, @mborsz ran some manual tests last week trying to reproducing this and test failures weren't seen happening (both against head and commit from unhealthy period). The issue indeed doesn't seem related to k8s. Also, the CI job has had 4 continuous green runs now.

Maciek - Is there sth else you'd want to add and/or any pending actions under this issue? Thanks.

**Comment by mborsz** [comment]
Yes, there is a bug in containerd and docker causing the problems.
It's unclear to us why it started triggering so often at some point and then it stopped appearing without our action -- I wasn't able to reproduce this by manually running 5k scalability nodes in multiple k8s versions.

I think it's ok to close this bug for now. The effort of fixing underlying bug in docker used by cos image is tracked internally.
