### ISSUE TITLE
gce scalability tests stuck on gathering log sizes

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#66609]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable2/414 has failed with 
```
kubetest --timeout triggered
```

The last message before SIGABRT is:
```
I0725 03:33:19.146] STEP: Gathering log sizes data
W0725 05:01:09.225] 2018/07/25 05:01:09 process.go:199: Abort after 2h0m0s timeout during ./hack/ginkgo-e2e.sh --ginkgo.focus=\[Feature:Performance\] --gather-resource-usage=true --gather-metrics-at-teardown=true --gather-logs-sizes=true --minStartupPods=8 --logexporter-gcs-path=gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable2/414/artifacts --report-dir=/workspace/_artifacts --disable-log-dump=true --cluster-ip-range=10.64.0.0/14. Will terminate in another 15m
```

According to stacktrace, the framework is waiting for all goroutines to gather log sizes:
```
I0725 05:01:09.339] goroutine 100 [semacquire, 87 minutes]:
I0725 05:01:09.339] sync.runtime_Semacquire(0xc42186d964)
I0725 05:01:09.340]     /usr/local/go/src/runtime/sema.go:56 +0x39
I0725 05:01:09.340] sync.(*WaitGroup).Wait(0xc42186d958)
I0725 05:01:09.340]     /usr/local/go/src/sync/waitgroup.go:131 +0x72
I0725 05:01:09.340] k8s.io/kubernetes/test/e2e/framework.(*Framework).AfterEach(0xc42186d8c0)
I0725 05:01:09.340]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:333 +0x9e1
I0725 05:01:09.340] k8s.io/kubernetes/test/e2e/framework.(*Framework).AfterEach-fm()
I0725 05:01:09.340]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:135 +0x2a
(...)
I0725 05:01:16.069] goroutine 17205 [semacquire, 87 minutes]:
I0725 05:01:16.069] sync.runtime_Semacquire(0xc42708ffd4)
I0725 05:01:16.069]     /usr/local/go/src/runtime/sema.go:56 +0x39
I0725 05:01:16.069] sync.(*WaitGroup).Wait(0xc42708ffc8)
I0725 05:01:16.069]     /usr/local/go/src/sync/waitgroup.go:131 +0x72
I0725 05:01:16.069] k8s.io/kubernetes/test/e2e/framework.(*LogsSizeVerifier).Run(0xc42708ff80)
I0725 05:01:16.070]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/log_size_monitoring.go:217 +0x201
I0725 05:01:16.070] k8s.io/kubernetes/test/e2e/framework.(*Framework).BeforeEach.func1(0xc42186d8c0)
I0725 05:01:16.070]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:225 +0x32
I0725 05:01:16.070] created by k8s.io/kubernetes/test/e2e/framework.(*Framework).BeforeEach
I0725 05:01:16.070]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:224 +0x696
```

IIUC, a single goroutine is stuck on creating a SSH session:
```
I0725 05:01:17.235] goroutine 17383 [chan receive, 90 minutes]:
I0725 05:01:17.235] k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh.(*mux).openChannel(0xc42d56de30, 0x3dbd91d, 0x7, 0x0, 0x0, 0x0, 0x5fab0c0, 0xc42b8eccf0, 0xc42910baa0)
I0725 05:01:17.235]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh/mux.go:322 +0x1e6
I0725 05:01:17.235] k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh.(*mux).OpenChannel(0xc42d56de30, 0x3dbd91d, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
I0725 05:01:17.235]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh/mux.go:298 +0x64
I0725 05:01:17.236] k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh.(*Client).NewSession(0xc4234e0940, 0x3db79b0, 0x3, 0xc42778d140)
I0725 05:01:17.236]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/crypto/ssh/client.go:129 +0x67
I0725 05:01:17.236] k8s.io/kubernetes/pkg/ssh.runSSHCommand(0x5f6b6a0, 0x5f49de0, 0xc42b160480, 0x56, 0xc42001e025, 0x4, 0xc42778d140, 0x10, 0x5f7f5a0, 0xc423ebee20, ...)
I0725 05:01:17.236]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/ssh/ssh.go:229 +0x4bf
I0725 05:01:17.236] k8s.io/kubernetes/pkg/ssh.RunSSHCommand(0xc42b160480, 0x56, 0xc42001e025, 0x4, 0xc42778d140, 0x10, 0x5f7f5a0, 0xc423ebee20, 0xc42b160480, 0x7fbe9870ec50, ...)
I0725 05:01:17.236]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/ssh/ssh.go:202 +0xb8
I0725 05:01:17.236] k8s.io/kubernetes/test/e2e/framework.SSH(0xc42b160480, 0x56, 0xc42778d140, 0x10, 0x7ffeadc2ec69, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
I0725 05:01:17.236]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:3246 +0x316
I0725 05:01:17.236] k8s.io/kubernetes/test/e2e/framework.(*LogSizeGatherer).Work(0xc4294cf500, 0x1)
I0725 05:01:17.237]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/log_size_monitoring.go:245 +0x2d8
I0725 05:01:17.237] k8s.io/kubernetes/test/e2e/framework.(*LogSizeGatherer).Run(0xc4294cf500)
I0725 05:01:17.237]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/log_size_monitoring.go:221 +0x2b
I0725 05:01:17.237] created by k8s.io/kubernetes/test/e2e/framework.(*LogsSizeVerifier).Run
I0725 05:01:17.237]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/log_size_monitoring.go:214 +0x1b2
```

/sig scalability
/cc @shyamjvs

**Comment by mborsz** [comment]
Next instance of this issue: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable2/401

**Comment by mborsz** [comment]
And https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable2/394

**Comment by mborsz** [comment]
It happens also in 1.10 branch: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable1/1203

**Comment by mborsz** [comment]
Also https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable1/1187

**Comment by mborsz** [comment]
My understanding of this issue is that:
1. for some reason in e2e tests for 1.9 and 1.10 communication between nodes and test executor is broken which causes test to timeout. I'm trying to find what has happened there.
2. If this happens, I think that the correct behavior is to finish test without fetching logs from a broken node instead of failing the test. IIUC it's not possible right now in the crypto/ssh library we are using. I created an issue https://github.com/golang/go/issues/26643 to investigate this.

**Comment by mborsz** [comment]
I traced first failures due to this bug in each branch:
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable2/282/ -- 1.9 on 2018-06-22
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable1/1062/ -- 1.10 on 2018-06-14
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-beta/976/ -- 1.11 on 2018-06-28

**Comment by shyamjvs** [comment]
To update: I spoke with @mborsz offline and suggested that we simply turn off log-size-gathering in our release jobs to fix these flakes because:

- these are not seen on head job, but on the older release ones - so it's quite likely that it's coming from test-infra side
- since the issue is not easily reproducible and we'll eventually update these jobs to new releases, it's probably not worth investing too much time debugging it

**Comment by mborsz** [comment]
It's fixed now.
