### ISSUE TITLE
Serve_hostnames soak test gets unexpected errors

### ISSUE THREAD

**Issue by satnam6502** [kubernetes/kubernetes#6787]
Running the serve_hostnames soak test on a 100 node cluster with 10 pods per node (i.e. a total of 1,000 pods) with at most 500 queries in flight at a time and an average of 10 queries per node per iteration has started to give an unexpected error (see below).

The expected response is the name of the pod that responds e.g. `serve-hostname-34-9`. However, quite often, the response is like:

```
I0413 22:29:11.378919   27358 serve_hostnames.go:294] Got response from {
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "dial tcp 10.244.93.18:9376: no route to host",
  "code": 500
}
```

In the API server logs I notice:
```
I0413 22:31:46.938667    4456 handlers.go:138] GET /api/v1beta3/proxy/namespaces/serve-hostnames-9163/services/serv
e-hostnames: (33.195606ms) 0 [[serve_hostnames/v0.14.1 (linux/amd64) kubernetes/unknown] 127.0.0.1:49972]
        E0413 22:31:46.966566    4456 errors.go:66] apiserver received an error that is not an api.Status: dial tcp
 10.244.6.17:9376: no route to host
        I0413 22:31:46.966762    4456 handlers.go:138] GET /api/v1beta3/proxy/namespaces/serve-hostnames-9163/servi
ces/serve-hostnames: (3.036067672s) 500
        goroutine 3147427 [running]:
        github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc20e391860, 0x1f4)
                /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudP
latform/kubernetes/pkg/httplog/log.go:188 +0x9a
        github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.writeJSON(0x1f4, 0x7fb715f405f0, 0xc20801d5e0, 0x7f
b715f407b8, 0xc211327400, 0x7fb715d95880, 0xc20e391860)
                /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudP
latform/kubernetes/pkg/apiserver/apiserver.go:249 +0x232
        github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.(*ProxyHandler).tryUpgrade(0xc208584480, 0x7fb715d9
5880, 0xc20e391860, 0xc22116d1e0, 0xc210af00d0, 0xc21e9881c0, 0x0, 0x0, 0x0)
                /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudP
latform/kubernetes/pkg/apiserver/proxy.go:229 +0x18e
        github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.(*ProxyHandler).ServeHTTP(0xc208584480, 0x7fb715d95
880, 0xc20e391860, 0xc22116d1e0)
                /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudP
latform/kubernetes/pkg/apiserver/proxy.go:190 +0x1605
        github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·002(0xc213ad6630, 0xc2089b14a0)
                /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudP
latform/kubernetes/pkg/apiserver/api_installer.go:706 +0x60
        github.com/emicklei/go-restful.func·005(0xc213ad6630, 0xc2089b14a0)
                /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-rest
ful/container.go:214 +0x41
        github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc213ad6870, 0xc213ad6630, 0xc2089b14a0)
                /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-rest
ful/filter.go:21 +0xa2
        github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·003(0xc213ad6630, 0xc2089b14a0, 0xc213ad6870)
                /go/src/github.com/GoogleCloudPlatf [[serve_hostnames/v0.14.1 (linux/amd64) kubernetes/unknown] 127
.0.0.1:49786]
I0413 22:31:47.023973    4456 handlers.go:138] GET /api/v1beta3/services: (3.420608ms) 200 [[kube-proxy/v0.14.1 (li
nux/amd64) kubernetes/1be6847] 10.240.163.12:33033]
```

This is some of the log output of the soak test.

```
...
I0413 22:29:11.145102   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m38.200217826s
I0413 22:29:11.145141   27358 serve_hostnames.go:294] Got response from serve-hostname-34-9
I0413 22:29:11.378839   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m41.234674015s
I0413 22:29:11.378919   27358 serve_hostnames.go:294] Got response from {
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "dial tcp 10.244.93.18:9376: no route to host",
  "code": 500
}
I0413 22:29:11.548075   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m38.202100144s
I0413 22:29:11.548119   27358 serve_hostnames.go:294] Got response from serve-hostname-87-6
I0413 22:29:11.741882   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m41.398092402s
I0413 22:29:11.741929   27358 serve_hostnames.go:294] Got response from {
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "dial tcp 10.244.62.16:9376: no route to host",
  "code": 500
}
I0413 22:29:11.943367   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m38.201145191s
I0413 22:29:11.943428   27358 serve_hostnames.go:294] Got response from serve-hostname-67-5
I0413 22:29:12.345609   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m38.40038972s
I0413 22:29:12.345660   27358 serve_hostnames.go:294] Got response from serve-hostname-89-5
I0413 22:29:12.752724   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m41.603265662s
I0413 22:29:12.752771   27358 serve_hostnames.go:294] Got response from {
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "dial tcp 10.244.70.22:9376: no route to host",
  "code": 500
}
I0413 22:29:12.783879   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m38.238766373s
I0413 22:29:12.783919   27358 serve_hostnames.go:294] Got response from serve-hostname-58-6
I0413 22:29:13.143044   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m41.598008406s
I0413 22:29:13.143102   27358 serve_hostnames.go:294] Got response from {
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "dial tcp 10.244.78.21:9376: no route to host",
  "code": 500
}
I0413 22:29:13.145557   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m38.392609574s
I0413 22:29:13.145599   27358 serve_hostnames.go:294] Got response from serve-hostname-91-7
I0413 22:29:13.539806   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m41.396829148s
I0413 22:29:13.539872   27358 serve_hostnames.go:294] Got response from {
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "dial tcp 10.244.94.21:9376: no route to host",
  "code": 500
}
I0413 22:29:13.742147   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m41.396210773s
I0413 22:29:13.742187   27358 serve_hostnames.go:294] Got response from {
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "dial tcp 10.244.32.22:9376: no route to host",
  "code": 500
}
I0413 22:29:13.743846   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m38.200853638s
I0413 22:29:13.743886   27358 serve_hostnames.go:294] Got response from serve-hostname-9-8
I0413 22:29:13.940004   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m41.143346238s
I0413 22:29:13.940047   27358 serve_hostnames.go:294] Got response from {
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "dial tcp 10.244.55.17:9376: no route to host",
  "code": 500
}
I0413 22:29:13.944366   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m38.198924719s
I0413 22:29:13.944402   27358 serve_hostnames.go:294] Got response from serve-hostname-54-0
I0413 22:29:14.340538   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m41.182768701s
I0413 22:29:14.340606   27358 serve_hostnames.go:294] Got response from {
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "dial tcp 10.244.50.17:9376: no route to host",
  "code": 500
}
I0413 22:29:14.544639   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m37.400984389s
I0413 22:29:14.544724   27358 serve_hostnames.go:294] Got response from serve-hostname-6-9
I0413 22:29:14.738817   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m41.193959196s
I0413 22:29:14.738879   27358 serve_hostnames.go:294] Got response from {
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "dial tcp 10.244.41.14:9376: no route to host",
  "code": 500
}
I0413 22:29:14.947287   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m37.394815129s
I0413 22:29:14.947324   27358 serve_hostnames.go:294] Got response from serve-hostname-47-8
I0413 22:29:15.140596   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m41.396136063s
I0413 22:29:15.140659   27358 serve_hostnames.go:294] Got response from {
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "dial tcp 10.244.61.21:9376: no route to host",
  "code": 500
}
I0413 22:29:15.575149   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m41.234715445s
I0413 22:29:15.575220   27358 serve_hostnames.go:294] Got response from {
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "dial tcp 10.244.64.15:9376: no route to host",
  "code": 500
}
I0413 22:29:15.745343   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m37.404747185s
I0413 22:29:15.745400   27358 serve_hostnames.go:294] Got response from serve-hostname-98-1
I0413 22:29:15.939728   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m41.197106141s
I0413 22:29:15.939775   27358 serve_hostnames.go:294] Got response from {
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "dial tcp 10.244.44.15:9376: no route to host",
  "code": 500
}
I0413 22:29:15.945360   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m37.600336108s
I0413 22:29:15.945412   27358 serve_hostnames.go:294] Got response from serve-hostname-19-9
I0413 22:29:16.344389   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m41.399187951s
I0413 22:29:16.344440   27358 serve_hostnames.go:294] Got response from {
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "dial tcp 10.244.6.20:9376: no route to host",
  "code": 500
}
I0413 22:29:16.542738   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m41.399372698s
I0413 22:29:16.542793   27358 serve_hostnames.go:294] Got response from {
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "dial tcp 10.244.39.14:9376: no route to host",
  "code": 500
}
I0413 22:29:16.546302   27358 serve_hostnames.go:278] Proxy call in namespace serve-hostnames-9163 took 1m37.606040704s
I0413 22:29:16.546360   27358 serve_hostnames.go:294] Got response from serve-hostname-65-3

```

@lavalamp @smarterclayton @thockin

**Comment by lavalamp** [comment]
I'm still wondering if any of the /var/log/kube-proxy.log (on the nodes) say anything about too many open files...

**Comment by satnam6502** [comment]
Selected highlights from a kube-proxy file.

```
I0413 17:57:31.093767    5611 proxier.go:224] New UDP connection from 10.244.12.2:34387
E0413 17:57:31.101432    5611 proxier.go:252] Read failed: read udp 10.244.1.3:53: connection refused
I0413 17:57:31.109520    5611 proxier.go:224] New UDP connection from 10.244.12.2:34387
E0413 17:57:31.110242    5611 proxier.go:252] Read failed: read udp 10.244.1.3:53: connection refused
I0413 17:57:36.104871    5611 proxier.go:224] New UDP connection from 10.244.12.2:55952
I0413 17:57:36.107803    5611 proxier.go:224] New UDP connection from 10.244.12.2:47891
E0413 17:57:36.108641    5611 proxier.go:252] Read failed: read udp 10.244.1.3:53: connection refused
I0413 17:57:41.112728    5611 proxier.go:224] New UDP connection from 10.244.12.2:53457
I0413 17:57:41.116018    5611 proxier.go:224] New UDP connection from 10.244.12.2:55403
I0413 17:57:41.121214    5611 proxier.go:224] New UDP connection from 10.244.12.2:36016
E0413 17:57:41.122088    5611 proxier.go:252] Read failed: read udp 10.244.1.3:53: connection refused
I0413 17:57:46.127639    5611 proxier.go:224] New UDP connection from 10.244.12.2:40239
E0413 17:57:46.128907    5611 proxier.go:252] Read failed: read udp 10.244.1.3:53: connection refused
I0413 17:57:51.137371    5611 proxier.go:224] New UDP connection from 10.244.12.2:55421
I0413 17:57:51.141066    5611 proxier.go:224] New UDP connection from 10.244.12.2:59602
E0413 17:57:51.141995    5611 proxier.go:252] Read failed: read udp 10.244.1.3:53: connection refused
I0413 17:57:56.143601    5611 proxier.go:224] New UDP connection from 10.244.12.2:32890
I0413 17:57:56.156743    5611 proxier.go:224] New UDP connection from 10.244.12.2:57419
E0413 17:57:56.158036    5611 proxier.go:252] Read failed: read udp 10.244.1.3:53: connection refused
I0413 17:58:01.161317    5611 proxier.go:224] New UDP connection from 10.244.12.2:53080
...
W0413 18:14:27.289100    5611 api.go:153] Got error status on WatchServices channel: &{TypeMeta:{Kind: APIVersion:}
 ListMeta:{SelfLink: ResourceVersion:} Status:Failure Message:401: The event in requested index is outdated and cle
ared (the requested history has been cleared [16752/14370]) [17751] Reason: Details:<nil> Code:0}
...
I0413 18:29:57.875916    5611 iowatcher.go:102] Unexpected EOF during watch stream event decoding: unexpected EOF
...
```

**Comment by thockin** [comment]
This error comes up through a syscall, so it's not clear which one...
