### ISSUE TITLE
Failure of Priority function causes Scheduler Crash

### ISSUE THREAD

**Issue by DylanBLE** [kubernetes/kubernetes#68561]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
A failed Prioritize Map Function caused Scheduler break down.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x34396ec]

goroutine 574 [running]:
k8s.io/kubernetes/pkg/util/node.GetZoneKey(...)
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/node/node.go:117
k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/priorities.(*SelectorSpread).CalculateSpreadPriorityReduce(0xc420a20680, 0xc421401c20, 0x3cfe440, 0xc421b51180, 0xc421160060, 0xc420ec0280, 0x3, 0x3, 0xc421a65e90, 0x0)
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/priorities/selector_spreading.go:128 +0x15c
k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/priorities.(*SelectorSpread).CalculateSpreadPriorityReduce-fm(0xc421401c20, 0x3cfe440, 0xc421b51180, 0xc421160060, 0xc420ec0280, 0x3, 0x3, 0x0, 0xa)
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/priorities/selector_spreading.go:54 +0x7d
k8s.io/kubernetes/plugin/pkg/scheduler/core.PrioritizeNodes.func4(0xc42188dfc0, 0xc421401c20, 0x3cfe440, 0xc421b51180, 0xc421160060, 0xc4201a9380, 0x8, 0x8, 0xc421b4f1e0, 0x6, ...)
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/core/generic_scheduler.go:582 +0xf0
created by k8s.io/kubernetes/plugin/pkg/scheduler/core.PrioritizeNodes
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/core/generic_scheduler.go:580 +0x64f
```
**What you expected to happen**:
Pod remains Pending and describe pod will show errors of failed functions.

**How to reproduce it (as minimally and precisely as possible)**:
It happens when some prioritize's map functions return with error.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
 v1.9.6
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by DylanBLE** [comment]
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/core/generic_scheduler.go#L660
```
	processNode := func(index int) {
		nodeInfo := nodeNameToInfo[nodes[index].Name]
		var err error
		for i := range priorityConfigs {
			if priorityConfigs[i].Function != nil {
				continue
			}
			results[i][index], err = priorityConfigs[i].Map(pod, meta, nodeInfo)
			if err != nil {
				appendError(err)
				return
			}
		}
	}
	workqueue.Parallelize(16, len(nodes), processNode)
	for i, priorityConfig := range priorityConfigs {
		if priorityConfig.Reduce == nil {
			continue
		}
		wg.Add(1)
		go func(index int, config algorithm.PriorityConfig) {
			defer wg.Done()
			if err := config.Reduce(pod, meta, nodeNameToInfo, results[index]); err != nil {
				appendError(err)
			}
			if glog.V(10) {
				for _, hostPriority := range results[index] {
					glog.Infof("%v -> %v: %v, Score: (%d)", pod.Name, hostPriority.Host, config.Name, hostPriority.Score)
				}
			}
```
As shown above, if **priorityConfigs[i].Map(pod, meta, nodeInfo)** returns with error, there will be no chance for results[i + 1] to initialize its value, thus causing panic when calling 
**config.Reduce(pod, meta, nodeNameToInfo, results[i+1])**

**Comment by DylanBLE** [comment]
I opened a PR to initialize **results** with real host name instead of empty string.
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/core/generic_scheduler.go#L650
```
results[i] = make(schedulerapi.HostPriorityList, len(nodes))
```
