### ISSUE TITLE
kubeadm upgrade apply --feature-gates=CoreDNS=true crashes if kube-dns cm does not exist

### ISSUE THREAD

**Issue by jraby** [kubernetes/kubernetes#69112]
/kind bug
/sig cli

**What happened**:
running `kubeadm upgrade apply --dry-run --feature-gates=CoreDNS=true 1.10.8` crashes with the following error:

```
[dryrun] Would perform action GET on resource "configmaps" in API group "core/v1"
[dryrun] Resource name: "kube-dns"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x108 pc=0x2d7f24a]

goroutine 1 [running]:
k8s.io/kubernetes/cmd/kubeadm/app/phases/addons/dns.translateStubDomainOfKubeDNSToProxyCoreDNS(0x3be30e5, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0)
        /workspace/anago-v1.10.8-beta.0.41+7eab6a49736cc7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/addons/dns/dns.go:281 +0x3a
k8s.io/kubernetes/cmd/kubeadm/app/phases/addons/dns.coreDNSAddon(0xc42084d200, 0x5b1a7c0, 0xc420d2b9a0, 0xc420dc6200, 0xc4201c5668, 0x13)
        /workspace/anago-v1.10.8-beta.0.41+7eab6a49736cc7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/addons/dns/dns.go:156 +0x28a
k8s.io/kubernetes/cmd/kubeadm/app/phases/addons/dns.EnsureDNSAddon(0xc42084d200, 0x5b1a7c0, 0xc420d2b9a0, 0x1, 0x1)
        /workspace/anago-v1.10.8-beta.0.41+7eab6a49736cc7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/addons/dns/dns.go:58 +0x1b9
k8s.io/kubernetes/cmd/kubeadm/app/phases/upgrade.PerformPostUpgradeTasks(0x5b1a7c0, 0xc420d2b9a0, 0xc42084d200, 0xc4200a3d40, 0x5e06f01, 0xc42084d200, 0x0)
        /workspace/anago-v1.10.8-beta.0.41+7eab6a49736cc7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/upgrade/postupgrade.go:107 +0x432
k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade.RunApply(0xc420c1da70, 0x0, 0x0)
        /workspace/anago-v1.10.8-beta.0.41+7eab6a49736cc7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade/apply.go:188 +0x4a8
k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade.NewCmdApply.func1(0xc420d0c500, 0xc420d22750, 0x1, 0x3)
        /workspace/anago-v1.10.8-beta.0.41+7eab6a49736cc7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade/apply.go:109 +0x14a
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc420d0c500, 0xc420d226f0, 0x3, 0x3, 0xc420d0c500, 0xc420d226f0)
        /workspace/anago-v1.10.8-beta.0.41+7eab6a49736cc7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:757 +0x2c1
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420c23680, 0xc420ca6f00, 0xc420ca6c80, 0xc420ca6a00)
        /workspace/anago-v1.10.8-beta.0.41+7eab6a49736cc7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:843 +0x334
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420c23680, 0xc42000c010, 0x5adc1a0)
        /workspace/anago-v1.10.8-beta.0.41+7eab6a49736cc7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:791 +0x2b
k8s.io/kubernetes/cmd/kubeadm/app.Run(0xc420b5ff70, 0x4046f4)
        /workspace/anago-v1.10.8-beta.0.41+7eab6a49736cc7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:36 +0xe3
main.main()
        /workspace/anago-v1.10.8-beta.0.41+7eab6a49736cc7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:27 +0x26

```

**What you expected to happen**:

The upgrade should proceed as if the configmap was empty or exit with an error stating that the configmap is missing.

**How to reproduce it (as minimally and precisely as possible)**:

remove `kube-dns` cm and run the kudeadm upgrade command as explained above.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.6
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Install tools: cluster was originally installed with kubeadm on ~1.6 then upgraded to 1.8 then 1.10. Entirely possible that this configmap should have been created by an upgrade process that wasn't run properly.  However kubeadm shouldn't panic.

**Comment by neolit123** [comment]
> it seems fixed in 1.11.0

:+1: 

this cannot be backported to 1.10 as it's not a super critical fix and it's triggered by an edge case.
thanks for the report.

best to upgrade to 1.12 as soon as possible for a number of other fixes!
/close
