### ISSUE TITLE
jsonpath with -1 as index panics

### ISSUE THREAD

**Issue by surajssd** [kubernetes/kubernetes#69146]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When giving `jsonpath` to `kubectl get ...` and if you provide `-1` as index value to the list, `kubectl` panics. While index value of `-2` works fine.

**What you expected to happen**:

When an index of `-1` is given in jsonpath it should refer to the last item in the list.

**How to reproduce it (as minimally and precisely as possible)**:

I have started three pods to reproduce this:

```bash
$ kubectl run web --image nginx --replicas 3                                   
deployment.apps/web created
```

Here are they:

```bash
$ kubectl get pods
NAME                  READY     STATUS    RESTARTS   AGE
web-dcc695978-2gc97   1/1       Running   0          5m
web-dcc695978-dflt9   1/1       Running   0          5m
web-dcc695978-l442p   1/1       Running   0          5m
```

Now try to list the first pod `web-dcc695978-2gc97` using negative index values:

```bash
$ kubectl get pods -o jsonpath='{.items[-3].metadata.name}'
web-dcc695978-2gc97
```

Similarly listing second pod `web-dcc695978-dflt9` using negative index value:

```bash
$ kubectl get pods -o jsonpath='{.items[-2].metadata.name}'
web-dcc695978-dflt9
```

Now when you try to list the last one using `-1` then you can see panic:

```bash
$ kubectl get pods -o jsonpath='{.items[-1].metadata.name}'
panic: reflect.Value.Slice: slice index out of bounds

goroutine 1 [running]:
reflect.Value.Slice(0x1465b60, 0xc420876420, 0x97, 0x2, 0x0, 0x97, 0x241d900, 0x0)
        /usr/local/go/src/reflect/value.go:1597 +0x28d
k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).evalArray(0xc4203e1500, 0xc420876460, 0x1, 0x1, 0xc420434a00, 0xc420876460, 0x1, 0x1, 0x0, 0x0)
        /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:273 +0x43e
k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).walk(0xc4203e1500, 0xc420876460, 0x1, 0x1, 0x189e9e0, 0xc420434a00, 0xc420876460, 0x1, 0x1, 0x0, ...)
        /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:148 +0x79f
k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).evalList(0xc4203e1500, 0xc420876440, 0x1, 0x1, 0xc420a4bfc0, 0x40fc89, 0xc420876420, 0x20, 0x18, 0xc4208cd3f0)
        /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:202 +0xbb
k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).walk(0xc4203e1500, 0xc420876440, 0x1, 0x1, 0x189eba0, 0xc420a4bfc0, 0xc42088c768, 0xc2ca7d6c588e87d, 0x40dcf9, 0x20, ...)
        /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:142 +0x8ae
k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).FindResults(0xc4203e1500, 0x1541ee0, 0xc4209ff4d0, 0xc42088c6c0, 0xc42088c6c0, 0x0, 0x0, 0x0)
        /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:89 +0x1d4
k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).Execute(0xc4203e1500, 0x18940a0, 0xc42000c018, 0x1541ee0, 0xc4209ff4d0, 0x1, 0x0)
        /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:67 +0x49
k8s.io/kubernetes/pkg/kubectl/genericclioptions/printers.(*JSONPathPrinter).PrintObj(0xc420800060, 0x189db60, 0xc420801600, 0x18940a0, 0xc42000c018, 0xc4203cc380, 0x10)
        /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/printers/jsonpath.go:151 +0x2c4
k8s.io/kubernetes/pkg/printers.(ResourcePrinter).PrintObj-fm(0x189db60, 0xc420801600, 0x18940a0, 0xc42000c018, 0xc420801620, 0xc42088c6c0)
        /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:252 +0x57
k8s.io/kubernetes/pkg/printers.ResourcePrinterFunc.PrintObj(0xc420800080, 0x189db60, 0xc420801600, 0x18940a0, 0xc42000c018, 0xc420801620, 0x2)
        /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/printers/interface.go:38 +0x4e
k8s.io/kubernetes/pkg/kubectl/cmd/get.(*GetOptions).printGeneric(0xc4202f6380, 0xc420990900, 0x1, 0x1)
        /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:719 +0x7b1
k8s.io/kubernetes/pkg/kubectl/cmd/get.(*GetOptions).Run(0xc4202f6380, 0x18c7680, 0xc420597650, 0xc4205e2280, 0xc4201e85a0, 0x1, 0x3, 0x0, 0x0)
        /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:343 +0x13cd
k8s.io/kubernetes/pkg/kubectl/cmd/get.NewCmdGet.func1(0xc4205e2280, 0xc4201e85a0, 0x1, 0x3)
        /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:159 +0x115
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc4205e2280, 0xc4201e8510, 0x3, 0x3, 0xc4205e2280, 0xc4201e8510)
        /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760 +0x2c1
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42018bb80, 0xc420247680, 0x12a05f200, 0xc4208f1ee8)
        /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x30a
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42018bb80, 0x17eb070, 0x23ff060)
        /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
        /workspace/anago-v1.11.2-beta.0.50+bb9ffb1654d4a7/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:50 +0x196
```

**Environment**:
- Kubernetes version (use `kubectl version`):

```yaml
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-08-07T23:17:28Z
  compiler: gc
  gitCommit: bb9ffb1654d4a729bb4cec18ff088eacc153c239
  gitTreeState: clean
  gitVersion: v1.11.2
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: linux/amd64
serverVersion:
  buildDate: 2018-08-07T23:08:19Z
  compiler: gc
  gitCommit: bb9ffb1654d4a729bb4cec18ff088eacc153c239
  gitTreeState: clean
  gitVersion: v1.11.2
  goVersion: go1.10.3
  major: "1"
  minor: "11"
  platform: linux/amd64
```

**Comment by indradhanush** [comment]
I'm going to look into this over the next few days.

**Comment by nikhita** [comment]
@surajssd @indradhanush this looks like a dupe of https://github.com/kubernetes/kubernetes/issues/68578

**Comment by lavalamp** [comment]
@nikhita I don't think this can be related, #68578 is about "JSON Pointer" as interpreted by the server, not "JSON Path" as interpreted by the client.

**Comment by lavalamp** [comment]
(Or this description isn't right, I didn't dig further than reading the description)

**Comment by surajssd** [comment]
Closing since it seems to have been fixed now

```
$ kubectl get pods -o jsonpath='{.items[-1].metadata.name}'
web-546d98b79f-vfvzj
```
