### ISSUE TITLE
kube-apiserver restarted on boot, caused flake

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#70305]
For https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2572?log#log the cluster upgrade failed.

Looking at the failure, it seems to be an inopportune restart of apiserver.  The new master comes up, apiserver starts, but then it restarts.  The upgrade test hits it during the restart, it looks like.  Logs: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2572/artifacts/bootstrap-e2e-master/kube-apiserver.log-20181024-1540382414.gz

The reason for the apiserver restart was that kube-apiserver failed its liveness probe https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2572/artifacts/bootstrap-e2e-master/kubelet.log:
`I1024 05:18:39.900870    1569 kuberuntime_manager.go:565] Container "kube-apiserver" ({"docker" "2a1b78c8c811fe0939404eacf2eb815ff787ea636e1b6920fa9186c4b181eb1e"}) of pod kube-apiserver-bootstrap-e2e-master_kube-system(b13798debb0d0cb04a19e77831d7cf26): Container failed liveness probe.. Container will be killed and recreated.`

The liveness probe for api server is hitting :8080, and indeed it was failing its health check (apiserver log again):

```
I1024 05:18:28.000676       1 wrap.go:42] GET /healthz: (36.143742ms) 500
goroutine 5739 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc006619180, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:204 +0xd2
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc006619180, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:183 +0x35
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc0029ef840, 0x1f4)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:197 +0xaf
net/http.Error(0x7feed9dd2ce8, 0xc0070ebc98, 0xc00cea4000, 0x338, 0x1f4)
        /usr/local/go/src/net/http/server.go:1976 +0xda
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/healthz.handleRootHealthz.func1(0x7feed9dd2ce8, 0xc0070ebc98, 0xc00d23fc00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go:162 +0x3fe
net/http.HandlerFunc.ServeHTTP(0xc014103880, 0x7feed9dd2ce8, 0xc0070ebc98, 0xc00d23fc00)
        /usr/local/go/src/net/http/server.go:1964 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc006eb0d80, 0x7feed9dd2ce8, 0xc0070ebc98, 0xc00d23fc00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:241 +0x510
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc00a8cef50, 0x7feed9dd2ce8, 0xc0070ebc98, 0xc00d23fc00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x8a
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x3e7a8de, 0xf, 0xc008697170, 0xc00a8cef50, 0x7feed9dd2ce8, 0xc0070ebc98, 0xc00d23fc00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:154 +0x661
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7feed9dd2ce8, 0xc0070ebc98, 0xc00d23fc00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x4b4
net/http.HandlerFunc.ServeHTTP(0xc00a8d3240, 0x7feed9dd2ce8, 0xc0070ebc98, 0xc00d23fc00)
        /usr/local/go/src/net/http/server.go:1964 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7feed9dd2ce8, 0xc0070ebc98, 0xc00d23fc00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:160 +0x3ff
net/http.HandlerFunc.ServeHTTP(0xc0060e7a40, 0x7feed9dd2ce8, 0xc0070ebc98, 0xc00d23fc00)
        /usr/local/go/src/net/http/server.go:1964 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7feed9dd2ce8, 0xc0070ebc98, 0xc00d23fc00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x1ed9
net/http.HandlerFunc.ServeHTTP(0xc00a8d3280, 0x7feed9dd2ce8, 0xc0070ebc98, 0xc00d23fc00)
        /usr/local/go/src/net/http/server.go:1964 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAudit.func1(0x7feed9dd2ce8, 0xc0070ebc98, 0xc00d23fc00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/audit.go:54 +0x645
net/http.HandlerFunc.ServeHTTP(0xc00a8d32c0, 0x7feed9dd2ce8, 0xc0070ebc98, 0xc00d23fc00)
        /usr/local/go/src/net/http/server.go:1964 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7feed9dd2ce8, 0xc0070ebc98, 0xc00d23fb00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:81 +0x456
net/http.HandlerFunc.ServeHTTP(0xc0042099f0, 0x7feed9dd2ce8, 0xc0070ebc98, 0xc00d23fb00)
        /usr/local/go/src/net/http/server.go:1964 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc00f040540, 0xc00a91cbe0, 0x5cb0580, 0xc0070ebc98, 0xc00d23fb00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:100 +0xb3
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:96 +0x1b0

logging error output: "[+]ping ok\n[+]log ok\n[+]etcd ok\n[+]poststarthook/generic-apiserver-start-informers ok\n[+]poststarthook/start-apiextensions-informers ok\n[+]poststarthook/start-apiextensions-controllers ok\n[+]poststarthook/bootstrap-controller ok\n[-]poststarthook/rbac/bootstrap-roles failed: reason withheld\n[+]poststarthook/scheduling/bootstrap-system-priority-classes ok\n[+]poststarthook/ca-registration ok\n[+]poststarthook/start-kube-apiserver-informers ok\n[+]poststarthook/start-kube-apiserver-admission-initializer ok\n[+]poststarthook/start-kube-aggregator-informers ok\n[+]poststarthook/apiservice-registration-controller ok\n[+]poststarthook/apiservice-status-available-controller ok\n[+]poststarthook/apiservice-openapi-controller ok\n[+]poststarthook/kube-apiserver-autoregistration ok\n[+]autoregister-completion ok\nhealthz check failed\n"
 [curl/7.38.0 35.232.52.86:34956]
```

I'm guessing this is due to `poststarthook/rbac/bootstrap-roles failed: reason withheld`

Looking at the next run, I'm hypothesizing that RBAC updates just take too long, and so it's marginal as to whether the bootstrap roles complete in time.

/sig api-machinery
/kind failing-test

cc @jberkus

**Comment by hzxuzhonghu** [comment]
I see so many api calls getting clusterroles and clusterrolebingdings.
should we run `rbac/bootstrap-roles` in parallel to accelerate the bootstrap?

**Comment by hzxuzhonghu** [comment]
I open #70320 trying to fix it.

**Comment by justinsb** [comment]
That's great - thank you @hzxuzhonghu 

I do think we should also think about why each call is slow though - running in parallel or just boosting the timeout feels a little bit like cheating, at least until we have justified that this is an intrinsically slow operation.

cc @liggitt (as you know both apimachinery & auth)

**Comment by liggitt** [comment]
> I do think we should also think about why each call is slow though - running in parallel or just boosting the timeout feels a little bit like cheating, at least until we have justified that this is an intrinsically slow operation.
> 
> cc @liggitt (as you know both apimachinery & auth)

I'm seeing a total of 2 seconds to perform initialization on initial cluster bring-up, and a total of .25 seconds to verify initialization on cluster restart. There's nothing inherently slow about the operation.

If many many API calls are being made using the internal client on bring-up, it could exhaust the assigned QPS and artificially slow down all calls made using it.

The apiserver log of calls made during restart (as opposed to initial start) would be helpful in determining if there's a component that is making excessive numbers of API calls.

**Comment by justinsb** [comment]
Chatted with @liggitt directly, and found that while RBAC isn't fast (probably rate-limiting), the're a much bigger delay which is probably more significant:

```
I1029 15:54:52.394008       1 flags.go:33] FLAG: --version="false"
I1029 15:54:52.394018       1 flags.go:33] FLAG: --vmodule="httplog=3"
I1029 15:54:52.394028       1 flags.go:33] FLAG: --watch-cache="true"
I1029 15:54:52.394035       1 flags.go:33] FLAG: --watch-cache-sizes="[]"
I1029 15:54:52.394065       1 server.go:599] external host was not specified, using 35.184.199.144
I1029 15:54:52.394076       1 server.go:621] Initializing cache sizes based on 240MB limit
I1029 15:54:52.394183       1 server.go:147] Version: v1.13.0-alpha.2.146+eb1aa875b48778
W1029 15:54:54.088671       1 admission.go:76] PersistentVolumeLabel admission controller is deprecated. Please remove this controller from your configuration files and scripts.
I1029 15:54:54.092924       1 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,PodPreset,LimitRanger,ServiceAccount,NodeRestriction,PodSecurityPolicy,Priority,DefaultTolerationSeconds,PersistentVolumeLabel,DefaultStorageClass,StorageObjectInUseProtection,MutatingAdmissionWebhook.
I1029 15:54:54.092954       1 plugins.go:161] Loaded 6 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,PodSecurityPolicy,Priority,ValidatingAdmissionWebhook,ResourceQuota.
W1029 15:54:54.097623       1 admission.go:76] PersistentVolumeLabel admission controller is deprecated. Please remove this controller from your configuration files and scripts.
I1029 15:54:54.106355       1 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,PodPreset,LimitRanger,ServiceAccount,NodeRestriction,PodSecurityPolicy,Priority,DefaultTolerationSeconds,PersistentVolumeLabel,DefaultStorageClass,StorageObjectInUseProtection,MutatingAdmissionWebhook.
I1029 15:54:54.106386       1 plugins.go:161] Loaded 6 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,PodSecurityPolicy,Priority,ValidatingAdmissionWebhook,ResourceQuota.
I1029 15:55:09.544647       1 store.go:1414] Monitoring customresourcedefinitions.apiextensions.k8s.io count at <storage-prefix>//apiextensions.k8s.io/customresourcedefinitions
I1029 15:55:09.599653       1 master.go:244] Using reconciler: lease
I1029 15:55:09.610120       1 store.go:1414] Monitoring podtemplates count at <storage-prefix>//podtemplates
I1029 15:55:09.614739       1 store.go:1414] Monitoring events count at <storage-prefix>//events
```

Note the ~ 15 second gap.

And this was with other tests as well, e.g. the example above is actually from https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/31371/artifacts/bootstrap-e2e-master/kube-apiserver.log

Going to crank up the log level and see if I get any hints as to what is happening

**Comment by justinsb** [comment]
I dug into it - the reason for the long delay is that we're waiting for etcd to start.  We don't log anything, even at `--v=8`.

So maybe we do just increase the wait time :-(  An alternative would be to do an initializerPod that waits for etcd, which would be more correct.

**Comment by logicalhan** [comment]
I agree with @justinsb about increasing the wait time for our liveness check (especially considering the fact that we are apparently hitting our liveness failure threshold 75% of the time during out e2e tests).

**Comment by logicalhan** [comment]
@justinsb, how did you gather those metrics, by the way?

**Comment by justinsb** [comment]
@logicalhan I'm sure there's a better way, but I `gsutil cp`ed the logs down with some bash, and then grepped against them.  Specifically the kubelet.log file: `grep -l  kube-apiserver.message.Container.failed.liveness.probe */artifacts/bootstrap-e2e-master/kubelet.log` (`| wc -l` for a count) and `-L` to list files without matches

**Comment by jberkus** [comment]
Is this still broken?  Trying to figure out if it should be a blocker still, or not.  I'm not seeing these test failures.

**Comment by logicalhan** [comment]
I discussed this last week with @justinsb, we should increase the livenessProbe delay to avoid the premature kubelet restarts. 

/assign @logicalhan
