### ISSUE TITLE
multi attach error with Kubernetes resources from cinder

### ISSUE THREAD

**Issue by asishbose** [kubernetes/kubernetes#70349]
**What happened**:
There was issue with a node on openstack dnt he pods were shifting to another node where the resources were not able to attach with a prohibited multi attach error. 

K8S pod description::
f6d248bed48b path /dev/vds is attached to a different instance (f08443bf-6eae-4664-95f2-cd67f7d47287)
  Warning  FailedAttachVolume      7m               attachdetach-controller  Multi-Attach error for volume "pvc-a41e35bd-d1dc-11e8-9b2b-fa163ef89d28" Volume is already exclusively attached to one node and can't be attached to another
  Warning  FailedAttachVolume      2m (x2 over 3m)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-a41e35bd-d1dc-11e8-9b2b-fa163ef89d28" : error occurred getting volume by ID: f231dccb-1d87-4b4a-a0dc-f6d248bed48b, err: Get https://10.75.236.4:13776/v3/c1a647813afc4c6e9da2aea72d22493b/volumes/f231dccb-1d87-4b4a-a0dc-f6d248bed48b: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Normal   SuccessfulAttachVolume  2m               attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-a41e35bd-d1dc-11e8-9b2b-fa163ef89d28"
 Warning  FailedMount             2m (x3 over 6m)  kubelet, ci-01-g02-w-03  Unable to mount volumes for pod "kf-apaas-0_default(e2915bec-d69c-11e8-9b2b-fa163ef89d28)": timeout expired wait

Openstack error log ::
2018-10-19 15:19:34.435 159969 ERROR oslo_messaging.rpc.server [req-d22760bd-6991-43ae-afc4-53071e5760f2 0eb07d5594af436fbafe8d77521c1c6d 6d5fda63533440b7b21b11d25f24d61c - default default] Exception during message handling
2018-10-19 15:19:34.435 159969 ERROR oslo_messaging.rpc.server Traceback (most recent call last):
2018-10-19 15:19:34.435 159969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 133, in _process_incoming
2018-10-19 15:19:34.435 159969 ERROR oslo_messaging.rpc.server     res = self.dispatcher.dispatch(message)
2018-10-19 15:19:34.435 159969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 150, in dispatch
2018-10-19 15:19:34.435 159969 ERROR oslo_messaging.rpc.server     return self._do_dispatch(endpoint, method, ctxt, args)
2018-10-19 15:19:34.435 159969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 121, in _do_dispatch
2018-10-19 15:19:34.435 159969 ERROR oslo_messaging.rpc.server     result = func(ctxt, **new_args)
2018-10-19 15:19:34.435 159969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/volume/manager.py", line 4514, in initialize_connection
2018-10-19 15:19:34.435 159969 ERROR oslo_messaging.rpc.server     connector, volume=volume)
2018-10-19 15:19:34.435 159969 ERROR oslo_messaging.rpc.server   File "/usr/lib/python2.7/site-packages/cinder/volume/manager.py", line 1449, in initialize_connection
2018-10-19 15:19:34.435 159969 ERROR oslo_messaging.rpc.server     raise exception.VolumeBackendAPIException(data=err_msg)
2018-10-19 15:19:34.435 159969 ERROR oslo_messaging.rpc.server VolumeBackendAPIException: Bad or unexpected response from the storage volume backend API: Driver initialize connection failed (error: Conflict (HTTP 409) 16 - host exists).
2018-10-19 15:19:34.435 159969 ERROR oslo_messaging.rpc.server

**What you expected to happen**:
We need a wait on detach to ensure the detach has happened before the pod is shifted to another node. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10
- Cloud provider or hardware configuration: Openstack newton [https://releases.openstack.org/newton/]
- OS (e.g. from /etc/os-release): RHEL7
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug
/sig openstack

**Comment by zetaab** [comment]
multi-attach error means that controller starts detaching the volume as well. The problem is now that kubernetes assumes that openstack works correctly. If volume is attached to node x when pod tries to start in node y, the controller raises volume danglingerror https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack_volumes.go#L348 which means that it should detach the volume soon. It might take few minutes, but it will do it (if openstack works behind the scene).

imo this is not bug, this is not just openstack feature - it is how core controllers work in kubernetes.

**Comment by liurd** [comment]
Is it possible to enhance the function to let POD restart more times or wait more time? Otherwise the pod can't up due the PV can't mount. it's a common issue in all persistent storage case. 
Kubernetes move the pod, it can do more to improve pod robust.
