### ISSUE TITLE
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding

### ISSUE THREAD

**Issue by nicedudu** [kubernetes/kubernetes#71647]
**I don't know why this error occurred, I reloaded it many times but the problem still exists.**

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-27T01:14:37Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding
```

/kind bug

**Comment by zhouhaibing089** [comment]
`kubectl version --v=7` should give more information like which endpoint is 500-ing.

**Comment by nicedudu** [comment]
> @nicedudu：您还可以查看来自kube-apiserver的日志吗？


Which command do I need to execute? I just started learning kubernetes.

**Comment by Blunderchips** [comment]
Has this issue been resolved? @yue9944882 did not seem to help.

**Comment by PierreKelbert** [comment]
have the same issue after new install with kubeadm. Worked fine until reboot... Is there a way to get logs from apiserver to help ?

**Comment by BedivereZero** [comment]
The stress test reproduced the problem. kubelet cannot update node status after node has OOM.

```log
2020-08-31T11:59:05+0800 node-105-152 kubelet[47510]: E0831 11:59:05.877473   47510 kubelet_node_status.go:402] Error updating node status, will retry: error getting node "node-105-152": an error on the server ("") has prevented the request from succeeding (get nodes node-105-152)
2020-08-31T11:59:05+0800 node-105-152 kubelet[47510]: E0831 11:59:05.877580   47510 kubelet_node_status.go:389] Unable to update node status: update node status exceeds retry count
```

Restarting kubelet will fix this problem.

**Comment by LeoWenxiang** [comment]
@BedivereZero It's the Node OOM not the Pod OOM ？ and why kubelet cannot update node status after the OOM.

**Comment by BedivereZero** [comment]
> @BedivereZero It's the Node OOM not the Pod OOM ？ and why kubelet cannot update node status after the OOM.

Node OOM.

The kubernetes is deployed by kubeadm, contains 2 nodes: node-0 is master, node-1 is worker. I ran the memory stress test on node-1, next node had an OOM and kubelet couldn't access kube-apiserver until kubelet was restarted.

By the way, how to debug a running kubelet without restarting it.

**Comment by Gauravjaitly** [comment]
i am having the same issue
` kubectl apply -f aws-iam-authenticator.yaml`
` Error from server (InternalError): an error on the server ("") has prevented the request from succeeding`

**Comment by Prithvipal** [comment]
I am also getting the same error.
Even `kubectl version` command is not working.
`kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding`

**Comment by Med-All** [comment]
Same problem here on Mac OSX

**Comment by sarthak-sriw** [comment]
I tried to run  **kubectl create -f mysql-podpreset.yml**  
I am getting following error :Error from server (InternalError): an error on the server ("") has prevented the request from succeeding

**Comment by samtoi** [comment]
> Same problem here on Mac OSX

Had the same issue, found myself a solution from [https://github.com/docker/for-mac/issues/2990](https://github.com/docker/for-mac/issues/2990).
In short, deleting the following folders + restarting docker did the thing for me:
`rm -rf ~/Library/Group\ Containers/group.com.docker/pki/`
`rm -rf ~/.kube`
From what I understood, the pki folder holds the kubernetes cert/key info and removing them results in them getting regenerated with restart - apparently making the stack operational at least in my case.

**Comment by tangweihua163** [comment]
retry several times and then failed:
```
kubectl version --v=7
```

success:
```
http_proxy='' https_proxy='' kubectl version --v=7
```

```
[xxxxxxx@Mac-mini /Users/xxxxxxx ]$ kubectl version --v=7
I1029 00:24:48.805208   43758 loader.go:375] Config loaded from file:  /Users/xxxxxxx/.kube/config
I1029 00:24:48.805852   43758 cert_rotation.go:137] Starting client certificate rotation controller
I1029 00:24:48.805878   43758 round_trippers.go:420] GET https://192.168.64.3:8443/version?timeout=32s
I1029 00:24:48.805885   43758 round_trippers.go:427] Request Headers:
I1029 00:24:48.805888   43758 round_trippers.go:431]     Accept: application/json, */*
I1029 00:24:48.805892   43758 round_trippers.go:431]     User-Agent: kubectl/v1.18.8 (darwin/amd64) kubernetes/9f2892a
I1029 00:24:50.157245   43758 round_trippers.go:446] Response Status:  in 1351 milliseconds
I1029 00:24:50.157315   43758 request.go:907] Got a Retry-After 1s response for attempt 1 to https://192.168.64.3:8443/version?timeout=32s
I1029 00:24:51.158746   43758 round_trippers.go:420] GET https://192.168.64.3:8443/version?timeout=32s
I1029 00:24:51.158772   43758 round_trippers.go:427] Request Headers:
I1029 00:24:51.158780   43758 round_trippers.go:431]     Accept: application/json, */*
I1029 00:24:51.158786   43758 round_trippers.go:431]     User-Agent: kubectl/v1.18.8 (darwin/amd64) kubernetes/9f2892a
^C
[xxxxxxx@Mac-mini /Users/xxxxxxx ]$ http_proxy='' https_proxy='' kubectl version --v=7
I1029 00:25:11.782094   43766 loader.go:375] Config loaded from file:  /Users/xxxxxxx/.kube/config
I1029 00:25:11.782724   43766 cert_rotation.go:137] Starting client certificate rotation controller
I1029 00:25:11.782763   43766 round_trippers.go:420] GET https://192.168.64.3:8443/version?timeout=32s
I1029 00:25:11.782770   43766 round_trippers.go:427] Request Headers:
I1029 00:25:11.782773   43766 round_trippers.go:431]     Accept: application/json, */*
I1029 00:25:11.782777   43766 round_trippers.go:431]     User-Agent: kubectl/v1.18.8 (darwin/amd64) kubernetes/9f2892a
I1029 00:25:11.795078   43766 round_trippers.go:446] Response Status: 200 OK in 12 milliseconds
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
[xxxxxxx@Mac-mini /Users/xxxxxxx ]$
```

so, you may need to set your proxy to pass 192.168.0.0/16 directly

**Comment by imilano** [comment]
Don't forget to check the permission and owner of `kubectl` in `/usr/local/bin`, 

I encountered the same problem,`kubectl version` outputs `Error from server (InternalError): an error on the server ("") has prevented the request from succeeding`.  
- `rm .kube` does not work, neither `rm pki`.
- tried reinstall/reset, did not work.

However, I found `sudo kubectl version` get the right output. So I check the owner of `kubectl`, find there is problem with ownership: 
<img width="889" alt="kubectl" src="https://user-images.githubusercontent.com/26795680/98436994-0879d300-211a-11eb-9674-b86df971e0c9.png">

I run `sudo chown -h randy:admin kubectl` in directory `/usr/local/bin`, problem solved, now kubectl runs well.

Hope it work for you.

**Comment by Mr-YYM** [comment]
maybe you set a proxy
solution: unset https_proxy

**Comment by aidenhsy** [comment]
Can you double check that you have started kubernetes in the first place?

**Comment by Sebosek** [comment]
Just happened to me too.

![image](https://user-images.githubusercontent.com/372542/102024387-07c80280-3d92-11eb-85f9-7198b087694c.png)

**Comment by amritk** [comment]
This is happening to me now on github actions CI, wasn't before

**Comment by VladimirTambovtsev** [comment]
Any updates? Same on Ubuntu with kops.

**Comment by tomkcpr** [comment]
Same here.  Executing the following on a newly built node yields:

oc whoami
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding (get users.user.openshift.io ~)

**Comment by Corgi-Google** [comment]
> maybe you set a proxy
> solution: unset https_proxy

helpful for me, thx (*^▽^*)

**Comment by soudaburger** [comment]
I am attempting to run `kubectl` inside of a docker container.  Both the OSX host and the docker container have the same `kubectl` version installed, but the docker container instance doesn't connect to the kubernetes nodes.  Nodes are running in GKE.

From Docker Container:
```bash
kubectl version   
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding```

From OSX Host:
```bash
kubectl version                                                                                                                                                                                             ─╯
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-gke.2100", GitCommit:"36d0b0a39224fef7a40df3d2bc61dfd96c8c7f6a", GitTreeState:"clean", BuildDate:"2021-03-16T09:15:29Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by KentFujii** [comment]
I am attempting to run kubectl inside of a docker container too.

```
FROM python:3.6.6-stretch

# Setup
ENV LANG C.UTF-8
ENV EDITOR vim
ADD . /var/www/muramasa
WORKDIR /var/www/muramasa/ansible
RUN apt-get update && apt-get install -y curl git vim

# Install gcloud
RUN apt-get update && apt-get -y install apt-transport-https ca-certificates gnupg
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
RUN apt-get update && apt-get install -y google-cloud-sdk

# Install docker
ENV DOCKER_CLIENT_VERSION 1.13.0
RUN curl -fsSL https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_CLIENT_VERSION}.tgz | tar -xzC /usr/local/bin --strip=1 docker/docker

# Install kubectl
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.19.7/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/kubectl

# Install ansible
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install install -r requirements.txt
RUN ansible-galaxy collection install google.cloud:==1.0.0
RUN ansible-galaxy collection install community.kubernetes:==1.1.1
RUN ansible-galaxy collection install community.general:==1.2.0

```

and not work for me

```
root@12a1e67ef6eb:/var/www/muramasa/ansible# kubectl version --v=10
I0505 13:39:32.849948     281 loader.go:375] Config loaded from file:  /root/.kube/config
I0505 13:39:32.851008     281 round_trippers.go:424] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.19.7 (linux/amd64) kubernetes/1dd5338" 'https://34.85.25.72/version?timeout=32s'
I0505 13:39:32.853138     281 round_trippers.go:444] GET https://34.85.25.72/version?timeout=32s  in 1 milliseconds
I0505 13:39:32.853278     281 round_trippers.go:450] Response Headers:
I0505 13:39:32.853465     281 request.go:933] Got a Retry-After 1s response for attempt 1 to https://34.85.25.72/version?timeout=32s
I0505 13:39:33.858936     281 round_trippers.go:424] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.19.7 (linux/amd64) kubernetes/1dd5338" 'https://34.85.25.72/version?timeout=32s'
I0505 13:39:33.863128     281 round_trippers.go:444] GET https://34.85.25.72/version?timeout=32s  in 4 milliseconds
I0505 13:39:33.863228     281 round_trippers.go:450] Response Headers:
I0505 13:39:33.863309     281 request.go:933] Got a Retry-After 1s response for attempt 2 to https://34.85.25.72/version?timeout=32s
I0505 13:39:34.868561     281 round_trippers.go:424] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.19.7 (linux/amd64) kubernetes/1dd5338" 'https://34.85.25.72/version?timeout=32s'
I0505 13:39:34.873582     281 round_trippers.go:444] GET https://34.85.25.72/version?timeout=32s  in 4 milliseconds
I0505 13:39:34.873778     281 round_trippers.go:450] Response Headers:
I0505 13:39:34.873964     281 request.go:933] Got a Retry-After 1s response for attempt 3 to https://34.85.25.72/version?timeout=32s
I0505 13:39:35.874518     281 round_trippers.go:424] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.19.7 (linux/amd64) kubernetes/1dd5338" 'https://34.85.25.72/version?timeout=32s'
I0505 13:39:35.876677     281 round_trippers.go:444] GET https://34.85.25.72/version?timeout=32s  in 2 milliseconds
I0505 13:39:35.876784     281 round_trippers.go:450] Response Headers:
I0505 13:39:35.876905     281 request.go:933] Got a Retry-After 1s response for attempt 4 to https://34.85.25.72/version?timeout=32s
I0505 13:39:36.878999     281 round_trippers.go:424] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.19.7 (linux/amd64) kubernetes/1dd5338" 'https://34.85.25.72/version?timeout=32s'
I0505 13:39:36.882393     281 round_trippers.go:444] GET https://34.85.25.72/version?timeout=32s  in 3 milliseconds
I0505 13:39:36.882537     281 round_trippers.go:450] Response Headers:
I0505 13:39:36.882766     281 request.go:933] Got a Retry-After 1s response for attempt 5 to https://34.85.25.72/version?timeout=32s
I0505 13:39:37.883784     281 round_trippers.go:424] curl -k -v -XGET  -H "User-Agent: kubectl/v1.19.7 (linux/amd64) kubernetes/1dd5338" -H "Accept: application/json, */*" 'https://34.85.25.72/version?timeout=32s'
I0505 13:39:37.886504     281 round_trippers.go:444] GET https://34.85.25.72/version?timeout=32s  in 2 milliseconds
I0505 13:39:37.886647     281 round_trippers.go:450] Response Headers:
I0505 13:39:37.886729     281 request.go:933] Got a Retry-After 1s response for attempt 6 to https://34.85.25.72/version?timeout=32s
I0505 13:39:38.888308     281 round_trippers.go:424] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.19.7 (linux/amd64) kubernetes/1dd5338" 'https://34.85.25.72/version?timeout=32s'
I0505 13:39:38.892021     281 round_trippers.go:444] GET https://34.85.25.72/version?timeout=32s  in 3 milliseconds
I0505 13:39:38.892080     281 round_trippers.go:450] Response Headers:
I0505 13:39:38.892205     281 request.go:933] Got a Retry-After 1s response for attempt 7 to https://34.85.25.72/version?timeout=32s
I0505 13:39:39.892856     281 round_trippers.go:424] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.19.7 (linux/amd64) kubernetes/1dd5338" 'https://34.85.25.72/version?timeout=32s'
I0505 13:39:39.893906     281 round_trippers.go:444] GET https://34.85.25.72/version?timeout=32s  in 1 milliseconds
I0505 13:39:39.893945     281 round_trippers.go:450] Response Headers:
I0505 13:39:39.893993     281 request.go:933] Got a Retry-After 1s response for attempt 8 to https://34.85.25.72/version?timeout=32s
I0505 13:39:40.859362     281 round_trippers.go:424] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.19.7 (linux/amd64) kubernetes/1dd5338" 'https://34.85.25.72/version?timeout=32s'
I0505 13:39:40.860920     281 round_trippers.go:444] GET https://34.85.25.72/version?timeout=32s  in 1 milliseconds
I0505 13:39:40.860986     281 round_trippers.go:450] Response Headers:
I0505 13:39:40.861041     281 request.go:933] Got a Retry-After 1s response for attempt 9 to https://34.85.25.72/version?timeout=32s
I0505 13:39:41.862199     281 round_trippers.go:424] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.19.7 (linux/amd64) kubernetes/1dd5338" 'https://34.85.25.72/version?timeout=32s'
I0505 13:39:41.865347     281 round_trippers.go:444] GET https://34.85.25.72/version?timeout=32s  in 2 milliseconds
I0505 13:39:41.865506     281 round_trippers.go:450] Response Headers:
I0505 13:39:41.865727     281 request.go:933] Got a Retry-After 1s response for attempt 10 to https://34.85.25.72/version?timeout=32s
I0505 13:39:42.866616     281 round_trippers.go:424] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.19.7 (linux/amd64) kubernetes/1dd5338" 'https://34.85.25.72/version?timeout=32s'
I0505 13:39:42.869884     281 round_trippers.go:444] GET https://34.85.25.72/version?timeout=32s  in 3 milliseconds
I0505 13:39:42.869976     281 round_trippers.go:450] Response Headers:
I0505 13:39:42.870215     281 request.go:1097] Response Body:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
I0505 13:39:42.870813     281 helpers.go:216] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "an error on the server (\"\") has prevented the request from succeeding",
  "reason": "InternalError",
  "details": {
    "causes": [
      {
        "reason": "UnexpectedServerResponse"
      }
    ],
    "retryAfterSeconds": 1
  },
  "code": 500
}]
F0505 13:39:42.870886     281 helpers.go:115] Error from server (InternalError): an error on the server ("") has prevented the request from succeeding
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00013a001, 0xc000397770, 0x97, 0xe8)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x2d04b80, 0xc000000003, 0x0, 0x0, 0xc0006273b0, 0x2ae4041, 0xa, 0x73, 0x40b300)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:945 +0x191
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x2d04b80, 0x3, 0x0, 0x0, 0x2, 0xc000877af0, 0x1, 0x1)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:718 +0x165
k8s.io/kubernetes/vendor/k8s.io/klog/v2.FatalDepth(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1442
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.fatal(0xc0001acfc0, 0x68, 0x1)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:93 +0x1f0
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.checkErr(0x1e5b480, 0xc0006ad540, 0x1d06cf0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:188 +0x945
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:115
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/version.NewCmdVersion.func1(0xc0006af080, 0xc000197940, 0x0, 0x1)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/version/version.go:79 +0x117
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0006af080, 0xc000197910, 0x1, 0x1, 0xc0006af080, 0xc000197910)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000439600, 0xc00013c120, 0xc000118150, 0x3)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:950 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:887
main.main()
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x21d

goroutine 18 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2d04b80)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1131 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:416 +0xd8

goroutine 8 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1d06c28, 0x1e5b780, 0xc000476000, 0x1700000001, 0xc0001140c0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x149
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1d06c28, 0x12a05f200, 0x0, 0x1, 0xc0001140c0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x1d06c28, 0x12a05f200, 0xc0001140c0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs.InitLogs
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/util/logs/logs.go:51 +0x96

```

**Comment by alkanna** [comment]
Hitting the exact same issue here, I can't understand what is wrong. Can we reopen this ?

**Comment by alkanna** [comment]
I solved it by upgrading docker for mac to version 3.3.3
I believe they reverted some stuff about https in 3.3.2 which probably fixes the issue.

**Comment by KentFujii** [comment]
I solved it by upgrading docker for mac to version 3.3.3. Thanks, @alkanna.

**Comment by Morriz** [comment]
> I actually solved mine by modifying the way I was launching my docker container? What had been working for months now required that I specified `--network host`... Didn't try other non-host network types, but this actually resolved it. DNS and other networking was working regardless of the change, but _that_ allowed `kubectl` to start behaving again.

can you share your solution?

**Comment by nmante** [comment]
> I solved it by upgrading docker for mac to version 3.3.3
> I believe they reverted some stuff about https in 3.3.2 which probably fixes the issue.

This worked for my environment as well.

**Comment by kartikv11** [comment]
> I solved it by upgrading docker for mac to version 3.3.3
> I believe they reverted some stuff about https in 3.3.2 which probably fixes the issue.

This worked for me too. Thanks.

**Comment by echarles** [comment]
Worked for me.

```
From Docker version 20.10.5, build 55c4c88
To.  Docker version 20.10.6, build 370c289
```

**Comment by shashi47** [comment]
I faced the same issue with three manager cluster and I was accessing it through ucp client bundle. I figured out 2 out of 3 manager nodes were in not ready state. On debugging further I found space issue on those not ready boxes. After cleaning a little (mainly /var folder) and restart docker, those nodes came to ready state and I'm not getting this error.

**Comment by tomkcpr** [comment]
This was happening to me for some time until I learned that there is a certificate expiration time.  After installing the bootstrap nodes, the masters should be built out shortly after the bootstrap nodes are started up ( 24H or maybe 8H ).  After that, the masters will not be completed correctly I think.  I wrote up my own install for VMware and OpenShift w/ Kubernetes below and included a link to the secondary github link I used as well.  Hope this helps someone else.


Cert Expiration:

https://github.com/openshift/installer/issues/1792


Installation Writeup: My Experience
https://microdevsys.com/wp/openshift-w-kubernetes-setup-installing-using-the-upi-method/

Thanks,

**Comment by Leo069** [comment]
Maybe some errors happened when kubernets starting. you can use  `kubectl cluster-info dump` find the error, and fix it.
details can Refer to: [](https://blog.csdn.net/hjlzs/article/details/118408308)

**Comment by Leo069** [comment]
Maybe some errors happened when kubernets starting. you can use  `kubectl cluster-info dump` find the error, and fix it.
details can Refer to: [](https://blog.csdn.net/hjlzs/article/details/118408308)

**Comment by RorisangSitoboli** [comment]
Hi, all. Restart Docker to solve the error. On Windows use the GUI-it's easier. Right-click on the Docker 'badge' at the bottom right of screen. The one showing the whale-with-the-containers. Select 'Restart Docker'. Docker will restart and you can run 'kubectl cluster-info' to verify. All the kubectl ... command will now work on the command line/cmd/terminal. 

If you want to activate/initialize Kubernetes right-click the same icon and go to 'Settings'. Select 'Kubernetes' and you will be good. Good luck.

**Comment by Rtoax** [comment]
> Same here. Executing the following on a newly built 4.7.0 cluster yields:
> 
> oc whoami Error from server (InternalError): an error on the server ("") has prevented the request from succeeding (get users.user.openshift.io ~)

Totally same.

```
[rongtao@api ~]$ oc whoami
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding (get users.user.openshift.io ~)
```

**Comment by marcelloromani** [comment]
FWIW in my case I realised I had done a silly mistake: in Docker Desktop -> Kubernetes I had `docker-desktop` selected, _but_ I had disabled Kubernetes in Docker Desktop.

So the solution was simple: select the correct K8s cluster :)
