### ISSUE TITLE
APIServer crashes on killing timeout'd non-long-running requests

### ISSUE THREAD

**Issue by yue9944882** [kubernetes/kubernetes#72095]
/kind bug
/sig api-machinery

@kubernetes/sig-api-machinery-bugs 

/cc @sttts @liggitt 

**What happened**:

out of some reason, the apiserver failed to response a GET CR request within a timeout but when the server killed that request, its process crashed w/ following stacktraces:

```
E1216 20:50:23.729709       1 wrap.go:34] apiserver panic'd on GET /apis/admissionregistration.k8s.io/v1beta1/mutatingwebhookconfigurations/istio-sidecar-injector: killing connection/stream because servin
g request timed out and response had been started
goroutine 2732242 [running]:
runtime/debug.Stack(0xb482880, 0xc5a19b18f0, 0x4fa18d9)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1.1(0x440d700, 0xc420512340)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:34 +0x74
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc58b871cf0, 0x1, 0x1)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:54 +0xc8
panic(0x440d700, 0xc420512340)
        /usr/local/go/src/runtime/panic.go:491 +0x283
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc5a1f8ebc0, 0xc5a8a859e0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:217 +0x190
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc428466e00, 0xb482880, 0xc5a19b18f0, 0xc5a8e31c00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:101 +0x292
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0xb482880, 0xc5a19b18f0, 0xc5a8e31c00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:51 +0xeb
net/http.HandlerFunc.ServeHTTP(0xc424e0f940, 0xb482880, 0xc5a19b18f0, 0xc5a8e31c00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0xb482880, 0xc5a19b18f0, 0xc5a8e31c00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:45 +0x20f
net/http.HandlerFunc.ServeHTTP(0xc424e0f980, 0xb482880, 0xc5a19b18f0, 0xc5a8e31c00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0xb482880, 0xc5a19b18f0, 0xc5a8e31c00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:110 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc428466e20, 0xb482880, 0xc5a19b18f0, 0xc5a8e31c00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0xb482880, 0xc5a19b18f0, 0xc5a8e31c00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41 +0x108
net/http.HandlerFunc.ServeHTTP(0xc428466e40, 0xb4841c0, 0xc59f664170, 0xc5a8e31c00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc422ef45a0, 0xb4841c0, 0xc59f664170, 0xc5a8e31c00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:197 +0x51
net/http.serverHandler.ServeHTTP(0xc42350a820, 0xb4841c0, 0xc59f664170, 0xc5a8e31c00)
        /usr/local/go/src/net/http/server.go:2619 +0xb4
....


goroutine 2731618 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.RequestInfoFrom(0x0, 0x0, 0x0, 0x44f958)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestinfo.go:238 +0x22
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.ContextBasedNaming.Namespace(0xc591ad6b70, 0x7f3cdb6651e0, 0xb8362f0, 0x0, 0xc552222390, 0x28, 0x0, 0x0, 0xc5a82c1500, 0x55199a1a644, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/namer.go:70 +0x4f
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.(*ContextBasedNaming).Namespace(0xc584df4780, 0xc5a82c1500, 0xc584df4f80, 0xc5a5b3d4f0, 0x29, 0xc5522223c0)
        <autogenerated>:1 +0x60
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.ListResource.func1(0xb482800, 0xc599bc54a0, 0xc5a82c1500)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/get.go:170 +0x111
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentHandlerFunc.func1(0x7f3cd1f118e8, 0xc5a269cc98, 0xc5a82c1500)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:221 +0x1e0
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver.(*crdHandler).ServeHTTP(0xc420fac580, 0x7f3cd1f118e8, 0xc5a269cc98, 0xc5a82c1500)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go:239 +0x5cd
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc424e0f540, 0x7f3cd1f118e8, 0xc5a269cc98, 0xc5a82c1500)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x26d
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc420376150, 0x7f3cd1f118e8, 0xc5a269cc98, 0xc5a82c1500)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0xa1
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x4ea00eb, 0x17, 0xc420bf5c20, 0xc420376150, 0x7f3cd1f118e8, 0xc5a269cc98, 0xc5a82c1500)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:160 +0x6ad
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc420bf2d40, 0x7f3cd1f118e8, 0xc5a269cc98, 0xc5a82c1500)
        <autogenerated>:1 +0x75
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc4294def00, 0x7f3cd1f118e8, 0xc5a269cc98, 0xc5a82c1500)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:254 +0x407
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc4205c75e0, 0x7f3cd1f118e8, 0xc5a269cc98, 0xc5a82c1500)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0xa1
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x4e7605f, 0xe, 0xc420c14990, 0xc4205c75e0, 0x7f3cd1f118e8, 0xc5a269cc98, 0xc5a82c1500)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:160 +0x6ad
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc421168020, 0x7f3cd1f118e8, 0xc5a269cc98, 0xc5a82c1500)
        <autogenerated>:1 +0x75
k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc42cb7ec00, 0x7f3cd1f118e8, 0xc5a269cc98, 0xc5a82c1500)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:93 +0x18a
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc5a84aa180, 0x7f3cd1f118e8, 0xc5a269cc98, 0xc5a82c1500)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x26d
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc424b38070, 0x7f3cd1f118e8, 0xc5a269cc98, 0xc5a82c1500)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0xa1
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x4e79ee3, 0xf, 0xc427122fc0, 0xc424b38070, 0x7f3cd1f118e8, 0xc5a269cc98, 0xc5a82c1500)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:160 +0x6ad
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc428466d60, 0x7f3cd1f118e8, 0xc5a269cc98, 0xc5a82c1500)
        <autogenerated>:1 +0x75
```

the crux is that the context (which is provisioned by request) will be nil when the timeout filter kills the inactive requests:
[https://github.com/kubernetes/kubernetes/blob/c7ea1c7bef26561aaaabc56bb85ffc07685fa456/staging/src/k8s.io/apiserver/pkg/endpoints/request/requestinfo.go#L262](https://github.com/kubernetes/kubernetes/blob/c7ea1c7bef26561aaaabc56bb85ffc07685fa456/staging/src/k8s.io/apiserver/pkg/endpoints/request/requestinfo.go#L262)

happens on release-1.10

**Comment by liggitt** [comment]
#62810 likely resolved the issue in the 1.11 timeframe, and #71163 likely resolved the propagation of the nil panic [in 1.10.12](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.10.md#changelog-since-v11011)
