### ISSUE TITLE
Caused by: java.net.UnknownHostException

### ISSUE THREAD

**Issue by ankitam23** [kubernetes/kubernetes#72819]
Caused by: java.lang.RuntimeException: java.net.UnknownHostException: dm-authapi-986c54956-7sr4x
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:112)
	... 170 common frames omitted
Caused by: java.net.UnknownHostException: dm-authapi-986c54956-7sr4x
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at brave.httpclient.TracingMainExec.execute(TracingMainExec.java:50)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at brave.httpclient.TracingProtocolExec.execute(TracingProtocolExec.java:41)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.springframework.cloud.netflix.ribbon.apache.RibbonLoadBalancingHttpClient.execute(RibbonLoadBalancingHttpClient.java:81)
	at org.springframework.cloud.netflix.ribbon.apache.RibbonLoadBalancingHttpClient.execute(RibbonLoadBalancingHttpClient.java:44)
	at com.netflix.client.AbstractLoadBalancerAwareClient$1.call(AbstractLoadBalancerAwareClient.java:104)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:303)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:287)
	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:231)
	at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:228)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)

##################################################################################
**We are using eureka. So eureka is registering pod name instead of service name. 
Our pod name and service name are different.

for example my pod name is: my-service-abcdef-1234
and service name is: my-service
and port is 8888

so eureka is taking my-service-abcdef-1234:8888**
#################################################################################

**Comment by neolit123** [comment]
hi, this issue tracker is only about bugs in core kubernetes.
try using our support channels instead:
https://github.com/kubernetes/community/blob/master/contributors/guide/issue-triage.md#user-support-response-example

thank you.
/close
