### ISSUE TITLE
panic in kubectl get ... -o custom-columns

### ISSUE THREAD

**Issue by Sanjary** [kubernetes/kubernetes#72941]
**What happened**:
While using output format custom columns, I used array index -1 which caused the following panic:

```
panic: reflect.Value.Slice: slice index out of bounds

goroutine 1 [running]:
reflect.Value.Slice(0x1465900, 0xc4205b0da0, 0x97, 0x4, 0x0, 0x97, 0x240e900, 0x0)
	/usr/lib64/go/src/reflect/value.go:1597 +0x28d
k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).evalArray(0xc420492770, 0xc4205b1280, 0x1, 0x1, 0xc420964780, 0xc4205b1280, 0x1, 0x1, 0x0, 0x0)
	/builddir/build/BUILD/kubectl-1.11.1-1/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:273 +0x43e
k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).walk(0xc420492770, 0xc4205b1280, 0x1, 0x1, 0x189e120, 0xc420964780, 0xc4205b1280, 0x1, 0x1, 0x0, ...)
	/builddir/build/BUILD/kubectl-1.11.1-1/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:148 +0x79f
k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).evalList(0xc420492770, 0xc4205b1220, 0x1, 0x1, 0xc4205b1120, 0xc42085b300, 0x0, 0x0, 0x0, 0xc42085b318)
	/builddir/build/BUILD/kubectl-1.11.1-1/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:202 +0xbb
k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).walk(0xc420492770, 0xc4205b1220, 0x1, 0x1, 0x189e2e0, 0xc4205b1120, 0x0, 0x0, 0xc42085b408, 0x40fc89, ...)
	/builddir/build/BUILD/kubectl-1.11.1-1/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:142 +0x8ae
k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath.(*JSONPath).FindResults(0xc420492770, 0x1541ae0, 0xc4207ca150, 0x18b8420, 0xc420796010, 0x1, 0x10000000046b16c, 0xc42085b4b0)
	/builddir/build/BUILD/kubectl-1.11.1-1/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/jsonpath/jsonpath.go:89 +0x1d4
k8s.io/kubernetes/pkg/printers.(*CustomColumnsPrinter).printOneObject(0xc4200e5140, 0x189d220, 0xc420796010, 0xc420796038, 0x1, 0x1, 0x1893a00, 0xc42074e600, 0xc42085b708, 0x1269b7d)
	/builddir/build/BUILD/kubectl-1.11.1-1/_output/local/go/src/k8s.io/kubernetes/pkg/printers/customcolumn.go:221 +0x585
k8s.io/kubernetes/pkg/printers.(*CustomColumnsPrinter).PrintObj(0xc4200e5140, 0x189d220, 0xc420796010, 0x1893a00, 0xc42074e600, 0x0, 0x0)
	/builddir/build/BUILD/kubectl-1.11.1-1/_output/local/go/src/k8s.io/kubernetes/pkg/printers/customcolumn.go:196 +0x740
k8s.io/kubernetes/pkg/printers.(ResourcePrinter).PrintObj-fm(0x189d220, 0xc420796010, 0x18937e0, 0xc4200c0008, 0xc420796010, 0xc420016701)
	/builddir/build/BUILD/kubectl-1.11.1-1/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:252 +0x57
k8s.io/kubernetes/pkg/printers.ResourcePrinterFunc.PrintObj(0xc4205b10a0, 0x189d220, 0xc420796010, 0x18937e0, 0xc4200c0008, 0x0, 0xc4208a77e8)
	/builddir/build/BUILD/kubectl-1.11.1-1/_output/local/go/src/k8s.io/kubernetes/pkg/printers/interface.go:38 +0x4e
k8s.io/kubernetes/pkg/kubectl/cmd/get.(*GetOptions).printGeneric(0xc4208dc1c0, 0xc420621680, 0x1, 0x1)
	/builddir/build/BUILD/kubectl-1.11.1-1/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:725 +0xc26
k8s.io/kubernetes/pkg/kubectl/cmd/get.(*GetOptions).Run(0xc4208dc1c0, 0x18c6dc0, 0xc420547560, 0xc4208fb180, 0xc4203ef020, 0x2, 0x6, 0x0, 0x0)
	/builddir/build/BUILD/kubectl-1.11.1-1/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:343 +0x13cd
k8s.io/kubernetes/pkg/kubectl/cmd/get.NewCmdGet.func1(0xc4208fb180, 0xc4203ef020, 0x2, 0x6)
	/builddir/build/BUILD/kubectl-1.11.1-1/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:159 +0x115
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc4208fb180, 0xc4203eeae0, 0x6, 0x6, 0xc4208fb180, 0xc4203eeae0)
	/builddir/build/BUILD/kubectl-1.11.1-1/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760 +0x2c1
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200fef00, 0xc4205f4060, 0x12a05f200, 0xc4208a7ee8)
	/builddir/build/BUILD/kubectl-1.11.1-1/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x30a
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200fef00, 0x17ea8b0, 0x23f0060)
	/builddir/build/BUILD/kubectl-1.11.1-1/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
	/builddir/build/BUILD/kubectl-1.11.1-1/_output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:50 +0x196
```

**What you expected to happen**:
It should return the last element of the array, just like index -2 returns second to last element from the array.

**How to reproduce it (as minimally and precisely as possible)**:
`$ kubectl get pod <POD_NAME> -o custom-columns=CONTAINER:.spec.containers[-1].name`

**Environment**:
- Kubernetes version: v1.11.6
- Kubectl version: v1.11.1

**Comment by ashishranjan738** [comment]
I am a new contributor and I would like to work on this issue @Sanjary

**Comment by WanLinghao** [comment]
@ashishranjan738  oops, didn't see your assing..I have solved this one
