### ISSUE TITLE
apiserver 405 for POST event dumps stack in logs

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#7308]
I'm seeing 405s and traces like the following in my apiserver logs, haven't dug much deeper other than to say that it looks like we're also returning a 405 when previously a curl -X POST would return a 400? If this is expected maybe we should instead dump an error and avoid the confusing stacktrace? 

```
I0424 12:42:09.932085    3764 handlers.go:135] POST /api/v1beta3/events: (552.495µs) 405
goroutine 880 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0x4c208ea2e40, 0x195)
	/usr/local/google/home/beeps/goproj/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:188 +0x9a
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.writeJSON(0x195, 0x7f2f194f8830, 0x4c208fc0dc0, 0x7f2f194f8a48, 0x4c208562b00, 0x7f2f19361960, 0x4c208ea2e40)
	/usr/local/google/home/beeps/goproj/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:275 +0x232
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.errorJSON(0x7f2f194fa7d0, 0x4c208562900, 0x7f2f194f8830, 0x4c208fc0dc0, 0x7f2f19361960, 0x4c208ea2e40, 0x0)
	/usr/local/google/home/beeps/goproj/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:282 +0xa3
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.serviceErrorHandler(0x4c20874d760, 0x4c208727da0, 0x3, 0x3, 0x195, 0xe7ef10, 0x17, 0x4c208e1c240, 0x4c208c6d310)
	/usr/local/google/home/beeps/goproj/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:194 +0x38b
github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver.func·004(0x195, 0xe7ef10, 0x17, 0x4c208e1c240, 0x4c208c6d310)
	/usr/local/google/home/beeps/goproj/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/apiserver.go:176 +0x63
github.com/emicklei/go-restful.func·004(0x4c208e1c240, 0x4c208c6d310)
	/usr/local/google/home/beeps/goproj/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:198 +0xfb
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0x4c208e1c210, 0x4c208e1c240, 0x4c208c6d310)
	/usr/local/google/home/beeps/goproj/src/github.com/GoogleC [[curl/7.35.0] 127.0.0.1:35571]
```

@nikhiljindal , maybe related to some v1beta1vs3 changes?

**Comment by derekwaynecarr** [comment]
This is because Events are namespace-scoped and as a result, the apiinstaller does not support POST /api/v1beta3/events as a valid end-point.  You can only GET /api/v1beta3/events to list events across all namespaces.

I know that we have debates on where events go for non-namespaced objects, but I think at this point, we should just stick them in the default namespace at the moment.

**Comment by bprashanth** [comment]
We should probably prevent whatevers trying to post to events at apiserver bringup (was happening this morning), and say so in the error message

**Comment by nikhiljindal** [comment]
I believe https://github.com/GoogleCloudPlatform/kubernetes/pull/7170 should fix this.

cc @simon3z

**Comment by simon3z** [comment]
@nikhiljindal correct, #7170 will fix your issue.

**Comment by yujuhong** [comment]
@simon3z, FYI, #7408 is a similar fix, and there is some discussion over there as for whether nodes should be namespace-free.

**Comment by lavalamp** [comment]
Pretty sure this is fixed now. Events can be either namespaced or non-namespaced, since you can have events about both types of objects.
