### ISSUE TITLE
Custom controller Run loop hangs on a deferred Wait in client-go

### ISSUE THREAD

**Issue by mkobetic** [kubernetes/kubernetes#73089]
**What happened**:

We are observing a controller hang in its Run loop with one of our custom controllers for a custom resource. When we dump all goroutines once in that state (kill -SIGABRT) this is the one that seems relevant.

```
goroutine 86 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0xc000043e78)
	/tmp/cache/go1.11.4/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc000043e70)
	/tmp/cache/go1.11.4/go/src/sync/waitgroup.go:130 +0x64
github.com/Shopify/cloudbuddies/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Wait(0xc000043e70)
	/tmp/build/src/github.com/Shopify/cloudbuddies/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:47 +0x2d
panic(0x11f6ba0, 0x2013550)
	/tmp/cache/go1.11.4/go/src/runtime/panic.go:513 +0x1b9
github.com/Shopify/cloudbuddies/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/tmp/build/src/github.com/Shopify/cloudbuddies/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x11f6ba0, 0x2013550)
	/tmp/cache/go1.11.4/go/src/runtime/panic.go:513 +0x1b9
github.com/Shopify/cloudbuddies/bucketbuddy.syncIAMPolicies(0xc00039fb00, 0xc00075da38, 0xc00029ab60, 0x1, 0xc000129bd0)
	/tmp/build/src/github.com/Shopify/cloudbuddies/bucketbuddy/authorizations.go:33 +0x181
github.com/Shopify/cloudbuddies/bucketbuddy.syncResource(0xc00039fb00, 0xc00029ab60)
	/tmp/build/src/github.com/Shopify/cloudbuddies/bucketbuddy/bucketbuddy.go:228 +0x859
github.com/Shopify/cloudbuddies/bucketbuddy.(*BucketBuddy).GetHandlers.func1(0x134a1a0, 0xc00029ab60)
	/tmp/build/src/github.com/Shopify/cloudbuddies/bucketbuddy/bucketbuddy.go:91 +0x219
github.com/Shopify/cloudbuddies.BuddyEventHandlerFuncs.OnAdd(0xc000297040, 0xc000297050, 0xc000297060, 0x134a1a0, 0xc00029ab60)
	/tmp/build/src/github.com/Shopify/cloudbuddies/handlers.go:20 +0x70
github.com/Shopify/cloudbuddies/vendor/k8s.io/client-go/tools/cache.NewInformer.func1(0x120e9a0, 0xc00000cc60, 0x120e9a0, 0xc00000cc60)
	/tmp/build/src/github.com/Shopify/cloudbuddies/vendor/k8s.io/client-go/tools/cache/controller.go:314 +0x1b6
github.com/Shopify/cloudbuddies/vendor/k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0001f42c0, 0xc00044fe60, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/Shopify/cloudbuddies/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:444 +0x24a
github.com/Shopify/cloudbuddies/vendor/k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000422600)
	/tmp/build/src/github.com/Shopify/cloudbuddies/vendor/k8s.io/client-go/tools/cache/controller.go:150 +0x40
github.com/Shopify/cloudbuddies/vendor/k8s.io/client-go/tools/cache.(*controller).processLoop-fm()
	/tmp/build/src/github.com/Shopify/cloudbuddies/vendor/k8s.io/client-go/tools/cache/controller.go:124 +0x2a
github.com/Shopify/cloudbuddies/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000303f28)
	/tmp/build/src/github.com/Shopify/cloudbuddies/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/Shopify/cloudbuddies/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00075df28, 0x3b9aca00, 0x0, 0xc000043e01, 0xc0003b4900)
	/tmp/build/src/github.com/Shopify/cloudbuddies/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
github.com/Shopify/cloudbuddies/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000303f28, 0x3b9aca00, 0xc0003b4900)
	/tmp/build/src/github.com/Shopify/cloudbuddies/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
github.com/Shopify/cloudbuddies/vendor/k8s.io/client-go/tools/cache.(*controller).Run(0xc000422600, 0xc0003b4900)
	/tmp/build/src/github.com/Shopify/cloudbuddies/vendor/k8s.io/client-go/tools/cache/controller.go:124 +0x299
github.com/Shopify/cloudbuddies.Run.func1(0x1517880, 0xc00039fb00, 0xc000297070, 0x14f4080, 0xc000422600, 0xc0003b4900, 0xc0000c9440, 0xc00049e4a0)
	/tmp/build/src/github.com/Shopify/cloudbuddies/cloudbuddies.go:231 +0x85
created by github.com/Shopify/cloudbuddies.Run
	/tmp/build/src/github.com/Shopify/cloudbuddies/cloudbuddies.go:226 +0x47a
```

What seems to be going on is that we have a bug in our handler function (nil pointer dereference) that triggers a panic. That panic gets first recovered in a deferred `apimachinery/pkg/util/runtime.HandleCrash` which repanics and the deferred handler search continues. Eventually it hits the deferred wait group Wait from https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/controller.go#L120. At that point the controller loop is blocked forever.

**What you expected to happen**:

I would expect the panic triggered by our code to get all the way to the top of the goroutine and the controller to crash. As it is currently it gets stuck inside client-go and there's nothing we can do in our code to deal with that. I'm not sure what the entire rationale is behind that code, but it seems to me that deferring a wait group Wait like that is highly susceptible to this type of problem.

**How to reproduce it (as minimally and precisely as possible)**:

Looking at the stack I should be able to write a simple dummy controller that would reproduce this. I can do that if desired. Right now we can reproduce this reliably with our custom controller.

**Anything else we need to know?**:

Don't think so.

**Environment**:

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-gke.5", GitCommit:"9aba9c1237d9d2347bef28652b93b1cba3aca6d8", GitTreeState:"clean", BuildDate:"2018-12-11T02:36:50Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): Ubuntu 16.04.4 LTS
- Kernel (e.g. `uname -a`): Linux bucketbuddy-55cf998ffc-686sv 4.14.65+ #1 SMP Thu Oct 25 10:42:50 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
Here are the versions of relevant libraries from our custom controller (from Gopkg.toml):
```
[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-8.0"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "release-1.11"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.11"
```

**Comment by mkobetic** [comment]
CC @kubernetes/sig-api-machinery-bugs

**Comment by huangjiasingle** [comment]
@mkobetic  may be you can copy you controller code to the comment.

**Comment by mkobetic** [comment]
OK, here's a dummy controller that just panics that reproduces the problem for me.
```
package main

import (
	"os"

	v1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/fields"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/tools/cache"
	"k8s.io/client-go/tools/clientcmd"

	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
)

func main() {
	config, err := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(
		clientcmd.NewDefaultClientConfigLoadingRules(),
		&clientcmd.ConfigOverrides{CurrentContext: os.Getenv("KUBECONTEXT")},
	).ClientConfig()
	if err != nil {
		panic(err)
	}
	k8s := kubernetes.NewForConfigOrDie(config)
	typ := &v1.Event{}
	gv := typ.GetObjectKind().GroupVersionKind().GroupVersion()
	config.GroupVersion = &gv
	_, controller := cache.NewInformer(
		cache.NewListWatchFromClient(
			k8s.CoreV1().RESTClient(),
			"events",
			v1.NamespaceAll,
			fields.Everything(),
		),
		&v1.Event{},
		0,
		cache.ResourceEventHandlerFuncs{
			AddFunc: func(o interface{}) {
				panic("EVENT ADDED")
			},
		},
	)
	controller.Run(nil)
}
```
If you build it and then run the executable, it should print the panic (the default `HandleCrash` behavior) and then hang. If you `kill -ABRT` the process you should see goroutine like this in the dump
```
goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc000467da8)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc000467da0)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
k8s.io/apimachinery/pkg/util/wait.(*Group).Wait(0xc000467da0)
	/Users/martin/shopify/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181203235515-3d8ee2261517/pkg/util/wait/wait.go:47 +0x2d
panic(0x1b51e80, 0x1de1120)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/martin/shopify/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181203235515-3d8ee2261517/pkg/util/runtime/runtime.go:58 +0x108
panic(0x1b51e80, 0x1de1120)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
main.main.func1(0x1ca9760, 0xc000494000)
	/Users/martin/shopify/73089/main.go:38 +0x39
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(0x1d37390, 0x0, 0x0, 0x1ca9760, 0xc000494000)
	/Users/martin/shopify/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20181216231014-8a775d0346c8+incompatible/tools/cache/controller.go:195 +0x49
k8s.io/client-go/tools/cache.NewInformer.func1(0x1bb4fa0, 0xc0003f0000, 0x1bb4fa0, 0xc0003f0000)
	/Users/martin/shopify/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20181216231014-8a775d0346c8+incompatible/tools/cache/controller.go:314 +0x1b6
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc000106000, 0xc0002236e0, 0x0, 0x0, 0x0, 0x0)
	/Users/martin/shopify/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20181216231014-8a775d0346c8+incompatible/tools/cache/delta_fifo.go:444 +0x24a
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000388c00)
	/Users/martin/shopify/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20181216231014-8a775d0346c8+incompatible/tools/cache/controller.go:150 +0x40
k8s.io/client-go/tools/cache.(*controller).processLoop-fm()
	/Users/martin/shopify/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20181216231014-8a775d0346c8+incompatible/tools/cache/controller.go:124 +0x2a
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0000d1e40)
	/Users/martin/shopify/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181203235515-3d8ee2261517/pkg/util/wait/wait.go:133 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000509e40, 0x3b9aca00, 0x0, 0xc000467d01, 0x0)
	/Users/martin/shopify/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181203235515-3d8ee2261517/pkg/util/wait/wait.go:134 +0xbe
k8s.io/apimachinery/pkg/util/wait.Until(0xc0000d1e40, 0x3b9aca00, 0x0)
	/Users/martin/shopify/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181203235515-3d8ee2261517/pkg/util/wait/wait.go:88 +0x4d
k8s.io/client-go/tools/cache.(*controller).Run(0xc000388c00, 0x0)
	/Users/martin/shopify/go/pkg/mod/k8s.io/client-go@v2.0.0-alpha.0.0.20181216231014-8a775d0346c8+incompatible/tools/cache/controller.go:124 +0x299
main.main()
	/Users/martin/shopify/73089/main.go:42 +0x44f
```
Note that I got different behavior when I just `go run` the sample program. I had to `go build` it and execute the binary to reproduce the behavior we're seeing in our custom controller.

**Comment by huangjiasingle** [comment]
@mkobetic  usually, the ResourceEventHandlerFuncs you shouldn't to implement by your self. if you do that, when you add the up ,add,update,delete func produce the panic. the panic ofcuase process by the controller (the controller.Start and contoller.Run called, it's will be produce panic of controller). l think it's no problems.  if you want to use custom controller: you should do like this: (k8s all controller in kube-controller-manager was do like this): 

```
type XXXController struct {
	indexer  cache.Indexer
	queue    workqueue.RateLimitingInterface
	informer cache.Controller
}

func (c *Controller) processNextItem() bool {
	// get key from XXXController's queue and then get obj from XXXController's indexder by key 
}


func (c *Controller) Run(threadiness int, stopCh chan struct{}) {
	// start the XXXController's informer 
}

func (c *Controller) runWorker() {
	for c.processNextItem() {
	}
}

func main() {
	......
	......
	
	XXXController Run()

	for i:=0;i<workNum;i++{
		go runWorker()
	}
}
```

if you do like this. all the logic panic of you self, you can resovle it by youself code.

**Comment by mkobetic** [comment]
IIUC you're proposing to follow the structure outlined in https://github.com/kubernetes/sample-controller, which indeed bypasses the [`cache.Controller.Run()`] function altogether and implements its own, which would obviously avoid the problematic code.

That said I still think that deferring `WaitGroup.Wait()` [like that](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/controller.go#L120) is problematic and should be looked into.

**Comment by huangjiasingle** [comment]
@mkobetic  yes, may the controller can support one func allow custom to registry coustom's hand panic log func to HandleCrash() func.
