### ISSUE TITLE
kubectl exec: invalid memory address or nil pointer dereference v1.12.5

### ISSUE THREAD

**Issue by IpaliboWhyte** [kubernetes/kubernetes#73558]
**What happened**:
After upgrading my k8s cluster from **v1.12.4** to **v1.12.5** I'm currently having issues with `kubectl exec`

**e.g**
`kubectl -n kube-system exec -it <pod-name> sh` 
outputs:
```
error: error sending request: Post https://<host-ip>:6443/api/v1/namespaces/kube-system/pods/<pod-name>/exec?command=sh&container=<container>&container=<container>&stdin=true&stdout=true&tty=true: unexpected EOF
```

I noticed this error first on **kube-dashboard v1.10.1** anytime I try exec into any pod I get the following error on the screen:

```
error sending request: Post https://10.233.0.1:443/api/v1/namespaces/kube-system/pods/<pod-name>/exec?command=cmd&container=<container>&stderr=true&stdin=true&stdout=true&tty=true: unexpected EOF
```

Also tried the following curl request:
```
curl -k -X POST -d 'https://<api-host>:6443/api/v1/namespaces/kube-system/pods/<pod-name>/portforward' --header "Authorization: bearer <token>"
```
output:
```
Empty reply from server
```

**What you expected to happen**:
Successfully exec into the provided pod

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl -n kube-system exec -it <pod-name> sh`

**Anything else we need to know?**:
I'm currently using **kubespray v2.8.2** to bootstrap my cluster which uses **Kubernetes v1.12.5**
 
**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: **aws**
- OS (e.g. from /etc/os-release): 
```
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
`Linux hostname.ec2.internal 4.4.0-1074-aws #84-Ubuntu SMP Thu Dec 6 08:57:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**NOTE:**

I watched the api server logs using `docker logs <api-container>`, this errors pops up everytime I issue the `kubectl exec` command:

```
E0131 03:05:35.101235       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573
/usr/local/go/src/runtime/panic.go:502
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:388
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go:167
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go:177
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/core/pod/rest/subresources.go:195
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/core/pod/rest/subresources.go:191
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:143
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:188
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:142
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1100
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:225
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:277
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:199
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:146
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:90
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:154
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64
/usr/local/go/src/net/http/server.go:1947
/usr/local/go/src/net/http/server.go:1947
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:126
/usr/local/go/src/net/http/server.go:1947
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50
/usr/local/go/src/net/http/server.go:1947
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:75
/usr/local/go/src/net/http/server.go:1947
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:91
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:47
/usr/local/go/src/net/http/server.go:1947
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39
/usr/local/go/src/net/http/server.go:1947
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:46
/usr/local/go/src/net/http/server.go:1947
/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189
/usr/local/go/src/net/http/server.go:2697
/usr/local/go/src/net/http/server.go:1830
/usr/local/go/src/runtime/asm_amd64.s:2361
E0131 03:05:35.101415       1 wrap.go:32] apiserver panic'd on POST /api/v1/namespaces/kube-system/pods/<pod-name>/portforward
I0131 03:05:35.101525       1 log.go:172] http: panic serving <host-ip>:36814: runtime error: invalid memory address or nil pointer dereference
goroutine 767971 [running]:
net/http.(*conn).serve.func1(0xc436a98be0)
	/usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0x36141e0, 0x73a5a00)
	/usr/local/go/src/runtime/panic.go:502 +0x229
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc42ea29cc8, 0x1, 0x1)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x36141e0, 0x73a5a00)
	/usr/local/go/src/runtime/panic.go:502 +0x229
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/proxy.normalizeLocation(0xc433b4d180, 0xc42a546090)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go:167 +0x48
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/proxy.NewUpgradeAwareHandler(0xc433b4d180, 0x5459c40, 0xc42019f0e0, 0xc42a540100, 0x545c320, 0xc42a546090, 0x0)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go:177 +0x2f
k8s.io/kubernetes/pkg/registry/core/pod/rest.newThrottledUpgradeAwareProxyHandler(0xc433b4d180, 0x5459c40, 0xc42019f0e0, 0xc421010100, 0x546d420, 0xc42f7bfe40, 0xc4212b9c49)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/core/pod/rest/subresources.go:195 +0xe7
k8s.io/kubernetes/pkg/registry/core/pod/rest.(*PortForwardREST).Connect(0xc4215e2340, 0x54915a0, 0xc427ad8de0, 0xc4212b9c49, 0x1d, 0x5463fa0, 0xc4313a4840, 0x546d420, 0xc42f7bfe40, 0xc435a33f00, ...)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/registry/core/pod/rest/subresources.go:191 +0x1cf
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.ConnectResource.func1.1()
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:143 +0x1bd
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.RecordLongRunning(0xc42ccf1f00, 0xc42fa47ad0, 0xc435a344e0)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:188 +0x1c5
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.ConnectResource.func1(0x5486d60, 0xc430d60a10, 0xc42ccf1f00)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:142 +0x4c5
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints.restfulConnectResource.func1(0xc427ad8cc0, 0xc425b21620)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1100 +0xd6
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc427ad8cc0, 0xc425b21620)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:225 +0x208
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc4209c1a70, 0x5486de0, 0xc4314d0f50, 0xc42ccf1f00)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:277 +0x9b9
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(0xc4209c1a70, 0x5486de0, 0xc4314d0f50, 0xc42ccf1f00)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:199 +0x57
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x3e052ff, 0xe, 0xc4209c1a70, 0xc42057e9a0, 0x5486de0, 0xc4314d0f50, 0xc42ccf1f00)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:146 +0x4ec
k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc4252faf50, 0x5486de0, 0xc4314d0f50, 0xc42ccf1f00)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:90 +0x169
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc436861a40, 0x5486de0, 0xc4314d0f50, 0xc42ccf1f00)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x266
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc42566e150, 0x5486de0, 0xc4314d0f50, 0xc42ccf1f00)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x8a
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x3e082db, 0xf, 0xc427041050, 0xc42566e150, 0x5486de0, 0xc4314d0f50, 0xc42ccf1f00)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:154 +0x6a8
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x5486de0, 0xc4314d0f50, 0xc42ccf1f00)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x4b1
net/http.HandlerFunc.ServeHTTP(0xc424558640, 0x5486de0, 0xc4314d0f50, 0xc42ccf1f00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x5486de0, 0xc4314d0f50, 0xc42ccf1f00)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:126 +0x4e7
net/http.HandlerFunc.ServeHTTP(0xc4254060c0, 0x5486de0, 0xc4314d0f50, 0xc42ccf1f00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x5486de0, 0xc4314d0f50, 0xc42ccf1f00)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x1ce1
net/http.HandlerFunc.ServeHTTP(0xc424558680, 0x5486de0, 0xc4314d0f50, 0xc42ccf1f00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x5486de0, 0xc4314d0f50, 0xc42ccf1f00)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:75 +0x2b3
net/http.HandlerFunc.ServeHTTP(0xc4245586c0, 0x5486de0, 0xc4314d0f50, 0xc42ccf1300)
	/usr/local/go/src/net/http/server.go:1947 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc421a203a0, 0x5486de0, 0xc4314d0f50, 0xc42ccf1300)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:91 +0x3e4
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x5486de0, 0xc4314d0f50, 0xc42ccf1300)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:47 +0xd4
net/http.HandlerFunc.ServeHTTP(0xc4254060f0, 0x5486de0, 0xc4314d0f50, 0xc42ccf1300)
	/usr/local/go/src/net/http/server.go:1947 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x5486de0, 0xc4314d0f50, 0xc42ccf1000)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x181
net/http.HandlerFunc.ServeHTTP(0xc425406120, 0x5486de0, 0xc4314d0f50, 0xc42ccf1000)
	/usr/local/go/src/net/http/server.go:1947 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x5486de0, 0xc4314d0f50, 0xc42ccf1000)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:46 +0x11a
net/http.HandlerFunc.ServeHTTP(0xc421a203c0, 0x5487fe0, 0xc4264d5dc0, 0xc42ccf1000)
	/usr/local/go/src/net/http/server.go:1947 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc425406150, 0x5487fe0, 0xc4264d5dc0, 0xc42ccf1000)
	/workspace/anago-v1.12.5-beta.0.98+51dd616cdd25d6/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc4234d0dd0, 0x5487fe0, 0xc4264d5dc0, 0xc42ccf1000)
	/usr/local/go/src/net/http/server.go:2697 +0xbc
net/http.(*conn).serve(0xc436a98be0, 0x54914e0, 0xc4302a7ec0)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2798 +0x27b
```

According to the stack trace, the error comes from: https://github.com/kubernetes/kubernetes/blob/v1.12.5/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go#L167

Any ideas? 

Thanks in advance!

**Comment by yue9944882** [comment]
@IpaliboWhyte could you paste some more detail about your pod? like yaml definition, thx

**Comment by IpaliboWhyte** [comment]
@yue9944882 I was testing the exec for one the tiller pod:
```
{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "tiller-deploy",
    "namespace": "kube-system",
    "selfLink": "/apis/extensions/v1beta1/namespaces/kube-system/deployments/tiller-deploy",
    "uid": "59108a24-264f-11e9-ad7c-1244716f1236",
    "resourceVersion": "1254",
    "generation": 2,
    "creationTimestamp": "2019-02-01T18:29:45Z",
    "labels": {
      "app": "helm",
      "name": "tiller"
    },
    "annotations": {
      "deployment.kubernetes.io/revision": "1",
      "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"extensions/v1beta1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"creationTimestamp\":null,\"labels\":{\"app\":\"helm\",\"name\":\"tiller\"},\"name\":\"tiller-deploy\",\"namespace\":\"kube-system\"},\"spec\":{\"replicas\":1,\"strategy\":{},\"template\":{\"metadata\":{\"creationTimestamp\":null,\"labels\":{\"app\":\"helm\",\"name\":\"tiller\"}},\"spec\":{\"automountServiceAccountToken\":true,\"containers\":[{\"env\":[{\"name\":\"TILLER_NAMESPACE\",\"value\":\"kube-system\"},{\"name\":\"TILLER_HISTORY_MAX\",\"value\":\"0\"}],\"image\":\"gcr.io/kubernetes-helm/tiller:v2.11.0\",\"imagePullPolicy\":\"IfNotPresent\",\"livenessProbe\":{\"httpGet\":{\"path\":\"/liveness\",\"port\":44135},\"initialDelaySeconds\":1,\"timeoutSeconds\":1},\"name\":\"tiller\",\"ports\":[{\"containerPort\":44134,\"name\":\"tiller\"},{\"containerPort\":44135,\"name\":\"http\"}],\"readinessProbe\":{\"httpGet\":{\"path\":\"/readiness\",\"port\":44135},\"initialDelaySeconds\":1,\"timeoutSeconds\":1},\"resources\":{}}],\"priorityClassName\":\"system-cluster-critical\",\"serviceAccountName\":\"tiller\"}}},\"status\":{}}\n"
    }
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "app": "helm",
        "name": "tiller"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "app": "helm",
          "name": "tiller"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "tiller",
            "image": "gcr.io/kubernetes-helm/tiller:v2.11.0",
            "ports": [
              {
                "name": "tiller",
                "containerPort": 44134,
                "protocol": "TCP"
              },
              {
                "name": "http",
                "containerPort": 44135,
                "protocol": "TCP"
              }
            ],
            "env": [
              {
                "name": "TILLER_NAMESPACE",
                "value": "kube-system"
              },
              {
                "name": "TILLER_HISTORY_MAX",
                "value": "0"
              }
            ],
            "resources": {},
            "livenessProbe": {
              "httpGet": {
                "path": "/liveness",
                "port": 44135,
                "scheme": "HTTP"
              },
              "initialDelaySeconds": 1,
              "timeoutSeconds": 1,
              "periodSeconds": 10,
              "successThreshold": 1,
              "failureThreshold": 3
            },
            "readinessProbe": {
              "httpGet": {
                "path": "/readiness",
                "port": 44135,
                "scheme": "HTTP"
              },
              "initialDelaySeconds": 1,
              "timeoutSeconds": 1,
              "periodSeconds": 10,
              "successThreshold": 1,
              "failureThreshold": 3
            },
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "IfNotPresent"
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "serviceAccountName": "tiller",
        "serviceAccount": "tiller",
        "automountServiceAccountToken": true,
        "securityContext": {},
        "schedulerName": "default-scheduler",
        "priorityClassName": "system-cluster-critical"
      }
    },
    "strategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "maxUnavailable": 1,
        "maxSurge": 1
      }
    },
    "revisionHistoryLimit": 10,
    "progressDeadlineSeconds": 2147483647
  },
  "status": {
    "observedGeneration": 2,
    "replicas": 1,
    "updatedReplicas": 1,
    "readyReplicas": 1,
    "availableReplicas": 1,
    "conditions": [
      {
        "type": "Available",
        "status": "True",
        "lastUpdateTime": "2019-02-01T18:29:45Z",
        "lastTransitionTime": "2019-02-01T18:29:45Z",
        "reason": "MinimumReplicasAvailable",
        "message": "Deployment has minimum availability."
      }
    ]
  }
}
```

I also see this error message after the exec:
```
Get https://10.233.0.1:443/api/v1/namespaces/kube-system/pods/tiller-deploy-bf6884cdb-6xhkz/log?container=tiller&tailLines=5000&timestamps=true: stream error: stream ID 207; INTERNAL_ERROR
```

Thanks!

**Comment by IpaliboWhyte** [comment]
It turns out this had to do with my aws environment where I was using multi-domain in my dhcp setting. This was resolved after I changed from using multiple domain to using a single domain in my dhcp settings. I will go ahead and close this. 🙂Thanks!

**Comment by milesbxf** [comment]
We've just hit this in `v1.12.7` via `kubectl logs`. Unfortunately using a single domain in our DHCP options isn't really an option, so I'm going to raise a PR with a fix. Thanks for raising this @IpaliboWhyte, has saved us a lot of time 🙂
