### ISSUE TITLE
Internal Server Error 0-length response from extension API server for no obvious reason

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#73753]
**What happened**:
I have an extension API server based on the sample-apiserver, and today I updated it from release 1.10 to 1.12.  In testing, I got a lot of success but found one unexpected error in the log of an extension API server (and this was neither the first nor the last attempt to delete that Kind of object):

```
I0205 16:31:16.068883       1 wrap.go:47] DELETE /apis/network.example.com/v1alpha1/namespaces/0205-1130-1577/networkattachments/190004-010: (4.867691ms) 500
goroutine 25803 [running]:
k8s.io/examples/staging/kos/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc000986070, 0x1f4)
	/Users/mspreitzus.ibm.com/Documents/go2/src/k8s.io/examples/staging/kos/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:204 +0xd2
k8s.io/examples/staging/kos/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc000986070, 0x1f4)
	/Users/mspreitzus.ibm.com/Documents/go2/src/k8s.io/examples/staging/kos/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:183 +0x35
k8s.io/examples/staging/kos/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc0008a89c0, 0x1f4)
	/Users/mspreitzus.ibm.com/Documents/go2/src/k8s.io/examples/staging/kos/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:205 +0xaf
net/http.Error(0x7f77d6fae718, 0xc0001cfe40, 0xc0003bcb40, 0x86, 0x1f4)
	/usr/local/Cellar/go/1.11.1/libexec/src/net/http/server.go:1976 +0xda
k8s.io/examples/staging/kos/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.InternalError(0x7f77d6fae718, 0xc0001cfe40, 0xc001d24600, 0x7f77d6fc61b8, 0xc0008abba0)
	/Users/mspreitzus.ibm.com/Documents/go2/src/k8s.io/examples/staging/kos/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/errors.go:75 +0x126
k8s.io/examples/staging/kos/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7f77d6fae718, 0xc0001cfe40, 0xc001d24600)
	/Users/mspreitzus.ibm.com/Documents/go2/src/k8s.io/examples/staging/kos/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:69 +0x1ed
net/http.HandlerFunc.ServeHTTP(0xc000407540, 0x7f77d6fae718, 0xc0001cfe40, 0xc001d24600)
	/usr/local/Cellar/go/1.11.1/libexec/src/net/http/server.go:1964 +0x44
k8s.io/examples/staging/kos/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7f77d6fae718, 0xc0001cfe40, 0xc001d24600)
	/Users/mspreitzus.ibm.com/Documents/go2/src/k8s.io/examples/staging/kos/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:160 +0x434
net/http.HandlerFunc.ServeHTTP(0xc00075a180, 0x7f77d6fae718, 0xc0001cfe40, 0xc001d24600)
	/usr/local/Cellar/go/1.11.1/libexec/src/net/http/server.go:1964 +0x44
k8s.io/examples/staging/kos/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7f77d6fae718, 0xc0001cfe40, 0xc001d24600)
	/Users/mspreitzus.ibm.com/Documents/go2/src/k8s.io/examples/staging/kos/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x1ed9
net/http.HandlerFunc.ServeHTTP(0xc000407580, 0x7f77d6fae718, 0xc0001cfe40, 0xc001d24600)
	/usr/local/Cellar/go/1.11.1/libexec/src/net/http/server.go:1964 +0x44
k8s.io/examples/staging/kos/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7f77d6fae718, 0xc0001cfe40, 0xc001d24500)
	/Users/mspreitzus.ibm.com/Documents/go2/src/k8s.io/examples/staging/kos/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:75 +0x368
net/http.HandlerFunc.ServeHTTP(0xc0004075c0, 0x7f77d6fae718, 0xc0001cfe40, 0xc001d24500)
	/usr/local/Cellar/go/1.11.1/libexec/src/net/http/server.go:1964 +0x44
k8s.io/examples/staging/kos/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc000f31d40, 0xc000754ea0, 0x1b303a0, 0xc0001cfe40, 0xc001d24500)
	/Users/mspreitzus.ibm.com/Documents/go2/src/k8s.io/examples/staging/kos/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0xb3
created by k8s.io/examples/staging/kos/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/Users/mspreitzus.ibm.com/Documents/go2/src/k8s.io/examples/staging/kos/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:97 +0x1b0

logging error output: "Internal Server Error: \"/apis/network.example.com/v1alpha1/namespaces/0205-1130-1577/networkattachments/190004-010\": 0-length response\n"
 [attachment-tput-driver/v0.0.0 (darwin/amd64) kubernetes/$Format 172.30.19.2:38810]
```

The error message is being written from https://github.com/kubernetes/apiserver/blob/063b3905819b775547a6e9eb6072e89cd2875e7b/pkg/endpoints/filters/authorization.go#L69 and it looks like that `err` is coming from https://github.com/kubernetes/apiserver/blob/063b3905819b775547a6e9eb6072e89cd2875e7b/pkg/endpoints/filters/authorization.go#L59

**What you expected to happen**:
I expected no problems with authorization checks.  I monitored the rate of SubjectAccessReviews and TokenReviews on all apiservers (main and extension) with Prometheus and Grafana.  I used `rate(...[1m])` as my query.  The TokenReview rate peaked at 0.18 and the SubjectAccessReview rate peaked at 4.8.  I also monitored `apiserver_current_inflight_requests`, and that peaked at 4.

**How to reproduce it (as minimally and precisely as possible)**:
This was testing https://github.com/MikeSpreitzer/kube-examples/tree/59603fa695bbb6e7c077533b82dbbb4324302346/staging/kos

```
cd staging/kos
make build
make publish DOCKER_PREFIX=mspreitz
kubectl get Node | grep -vw NAME | while read nodename rest; do
	kubectl label --overwrite Node $nodename role.kos.example.com/control=true
	kubectl label --overwrite Node $nodename role.kos.example.com/workload=true
	kubectl annotate --overwrite Node $nodename prometheus.io/scrape=true
done
make deploy DOCKER_PREFIX=mspreitz
local-binaries/attachment-tput-driver --kubeconfig $KUBECONFIG
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
mjs11:kos mspreitzus.ibm.com$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:16:58Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4+IKS", GitCommit:"27c949c1ae36d3c99246bde7ef68ff8bd3bb4ad3", GitTreeState:"clean", BuildDate:"2019-01-09T10:08:47Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: IBM IKS
- OS (e.g. from /etc/os-release): the worker nodes had the following:
```
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

- Kernel (e.g. `uname -a`): the worker nodes said `Linux kube-wdc07-cra2309cb203544bbd820010982963df3a-w1.cloud.ibm 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

- Install tools:
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by rajathagasthya** [comment]
Looks like it's #71696. It was fixed just a few weeks ago in #72856

**Comment by dims** [comment]
yep that's the one @rajathagasthya

**Comment by MikeSpreitzer** [comment]
Thanks.  The next question is will that fix be back-ported to earlier releases.

**Comment by liggitt** [comment]
already done: https://github.com/kubernetes/kubernetes/pull/72858

**Comment by liggitt** [comment]
will be in the next 1.12.x release

/close

**Comment by MikeSpreitzer** [comment]
thanks!
