### ISSUE TITLE
Kube-dns: name resolution does not work (connection refused)

### ISSUE THREAD

**Issue by elmo3006** [kubernetes/kubernetes#74210]
**What happened**:
Pods cannot resolve other pods names. Pod2 cannot connect to pod1, in the logs we can find:

```
Caused by: java.net.UnknownHostException: pod1: Temporary failure in name resolution
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61)
```

```
NAME         READY    STATUS                RESTARTS  AGE
pod2-0       0/1      CrashLoopBackOff  1837         4d
pod1-0       1/1      Running                  0              4d
```
```
[root@host tmp]$ kubectl exec -it pod1-0 nslookup pod1
;; connection timed out; no servers could be reached
command terminated with exit code 1

[root@host tmp]$ kubectl exec -it pod1-0 nslookup google.com
;; connection timed out; no servers could be reached
command terminated with exit code 1

[root@host tmp]$ ping google.com
PING google.com (172.217.21.228) 56(84) bytes of data.

[root@host tmp]$ kubectl exec -it pod1r-0 -- cat /etc/resolv.conf
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local corp.fin
options ndots:5
```
Netstato kube-dns pod shows that port 53 is available:
```
udp        0      0 :::53                   :::*
```
```
[root@host tmp]$ kubectl get ep -n=kube-system
NAME                     ENDPOINTS                    AGE
default-http-backend     10.32.0.11:8080              17m
kube-controller-manager  <none>                       25m
kube-dns                 10.32.0.10:53,10.32.0.10:53  25m
kube-scheduler           <none>                       25m
```

**Log**
Kube-dns:
```I0131 11:13:13.666316       1 dns.go:48] version: 1.14.6-3-gc36cb11
I0131 11:13:13.667286       1 server.go:69] Using configuration read from directory: /kube-dns-config with period 10s
I0131 11:13:13.667341       1 server.go:112] FLAG: --alsologtostderr="false"
I0131 11:13:13.667358       1 server.go:112] FLAG: --config-dir="/kube-dns-config"
I0131 11:13:13.667366       1 server.go:112] FLAG: --config-map=""
I0131 11:13:13.667370       1 server.go:112] FLAG: --config-map-namespace="kube-system"
I0131 11:13:13.667378       1 server.go:112] FLAG: --config-period="10s"
I0131 11:13:13.667384       1 server.go:112] FLAG: --dns-bind-address="0.0.0.0"
I0131 11:13:13.667390       1 server.go:112] FLAG: --dns-port="10053"
I0131 11:13:13.667396       1 server.go:112] FLAG: --domain="cluster.local."
I0131 11:13:13.667404       1 server.go:112] FLAG: --federations=""
I0131 11:13:13.667410       1 server.go:112] FLAG: --healthz-port="8081"
I0131 11:13:13.667415       1 server.go:112] FLAG: --initial-sync-timeout="1m0s"
I0131 11:13:13.667420       1 server.go:112] FLAG: --kube-master-url=""
I0131 11:13:13.667425       1 server.go:112] FLAG: --kubecfg-file=""
I0131 11:13:13.667428       1 server.go:112] FLAG: --log-backtrace-at=":0"
I0131 11:13:13.667441       1 server.go:112] FLAG: --log-dir=""
I0131 11:13:13.667446       1 server.go:112] FLAG: --log-flush-frequency="5s"
I0131 11:13:13.667451       1 server.go:112] FLAG: --logtostderr="true"
I0131 11:13:13.667455       1 server.go:112] FLAG: --nameservers=""
I0131 11:13:13.667459       1 server.go:112] FLAG: --stderrthreshold="2"
I0131 11:13:13.667464       1 server.go:112] FLAG: --v="2"
I0131 11:13:13.667468       1 server.go:112] FLAG: --version="false"
I0131 11:13:13.667475       1 server.go:112] FLAG: --vmodule=""
I0131 11:13:13.667570       1 server.go:194] Starting SkyDNS server (0.0.0.0:10053)
I0131 11:13:13.668008       1 server.go:213] Skydns metrics enabled (/metrics:10055)
I0131 11:13:13.668025       1 dns.go:146] Starting endpointsController
I0131 11:13:13.668032       1 dns.go:149] Starting serviceController
I0131 11:13:13.668388       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I0131 11:13:13.668419       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I0131 11:13:14.168248       1 dns.go:170] Initialized services and endpoints from apiserver
I0131 11:13:14.168273       1 server.go:128] Setting up Healthz Handler (/readiness)
I0131 11:13:14.168287       1 server.go:133] Setting up cache handler (/cache)
I0131 11:13:14.168302       1 server.go:119] Status HTTP port 8081
I0131 11:22:20.279276       1 dns.go:555] Could not find endpoints for service "pod1" in namespace "default". DNS records will be created once endpoints show up.
I0131 11:22:43.352391       1 dns.go:555] Could not find endpoints for service "pod2" in namespace "default". DNS records will be created once endpoints show up.
```

dnsmasq:
```I0131 11:13:13.905971       1 main.go:76] opts: {{/usr/sbin/dnsmasq [-k --cache-size=1000 --no-negcache --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053] true} /etc/k8s/dns/dnsmasq-nanny 10000000000}
I0131 11:13:13.906459       1 nanny.go:94] Starting dnsmasq [-k --cache-size=1000 --no-negcache --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053]
I0131 11:13:14.303960       1 nanny.go:119]
W0131 11:13:14.303958       1 nanny.go:120] Got EOF from stdout
I0131 11:13:14.303993       1 nanny.go:116] dnsmasq[18]: started, version 2.78 cachesize 1000
I0131 11:13:14.304070       1 nanny.go:116] dnsmasq[18]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
I0131 11:13:14.304087       1 nanny.go:116] dnsmasq[18]: using nameserver 127.0.0.1#10053 for domain ip6.arpa
I0131 11:13:14.304095       1 nanny.go:116] dnsmasq[18]: using nameserver 127.0.0.1#10053 for domain in-addr.arpa
I0131 11:13:14.304103       1 nanny.go:116] dnsmasq[18]: using nameserver 127.0.0.1#10053 for domain cluster.local
I0131 11:13:14.304125       1 nanny.go:116] dnsmasq[18]: reading /etc/resolv.conf
I0131 11:13:14.304138       1 nanny.go:116] dnsmasq[18]: using nameserver 127.0.0.1#10053 for domain ip6.arpa
I0131 11:13:14.304145       1 nanny.go:116] dnsmasq[18]: using nameserver 127.0.0.1#10053 for domain in-addr.arpa
I0131 11:13:14.304167       1 nanny.go:116] dnsmasq[18]: using nameserver 127.0.0.1#10053 for domain cluster.local
I0131 11:13:14.304184       1 nanny.go:116] dnsmasq[18]: using nameserver 10.20.58.5#53
I0131 11:13:14.304206       1 nanny.go:116] dnsmasq[18]: using nameserver 10.20.58.7#53
I0131 11:13:14.304244       1 nanny.go:116] dnsmasq[18]: read /etc/hosts - 7 addresses
```

sidecar:
```I0131 11:13:14.166242       1 main.go:51] Version v1.14.6-3-gc36cb11
I0131 11:13:14.166326       1 server.go:45] Starting server (options {DnsMasqPort:53 DnsMasqAddr:127.0.0.1 DnsMasqPollIntervalMs:5000 Probes:[{Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33} {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33}] PrometheusAddr:0.0.0.0 PrometheusPort:10054 PrometheusPath:/metrics PrometheusNamespace:kubedns})
I0131 11:13:14.166361       1 dnsprobe.go:75] Starting dnsProbe {Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33}
I0131 11:13:14.166427       1 dnsprobe.go:75] Starting dnsProbe {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33}
W0131 11:13:14.166849       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:51277->127.0.0.1:53: read: connection refused
```

**Environment**:
* Kubernetes version (use `kubectl version`): v1.9.7
* Docker version: 1.12.6
* OS (e.g. from /etc/os-release): Red Hat Enterprise Linux Server release 7.6 (Maipo)
* Kernel (e.g. `uname -a`): Linux 3.10.0-957.1.3.el7.x86_64

**Comment by prameshj** [comment]
Pods do not get hostnames by default, so the error is expected.
Are service names being resolved? like - "nslookup kubernetes.default"
