### ISSUE TITLE
kubeadm fails with config file when using etcd key

### ISSUE THREAD

**Issue by nfrush** [kubernetes/kubernetes#74443]
**What happened**:

Attempted to run 'kubeadm init --config=/etc/kubernetes/cfg/config.yaml' where config.yaml was:

```
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
etcd:
  external:
    endpoints:
    - "10.0.0.50:2379"
    - "10.0.0.235:2379"
    caFile: "/etc/kubernetes/pki/etcd/ca.pem"
    certFile: "/etc/kubernetes/pki/etcd/client.pem"
    keyFile: "/etc/kubernetes/pki/etcd/client-key.pem"
networking:
  podSubnet: "172.0.0.0/16"
controlPlaneEndpoint: "10.0.0.255:6443"
apiServer:
  certSANs:
  - "10.0.0.255"
  extraArgs:
    advertise-address: "10.0.0.235:6443"
    anonymous-auth: "false"
    audit-log-path: "/var/log/audit.log"
```

Kubeadm fails to init with the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa7930c]

goroutine 1 [running]:
k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/validation.ValidateURLs(0x40000bafe0, 0x2, 0x2, 0x1, 0x40002967b0, 0x0, 0x40002967b0, 0xf302a0)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/validation/validation.go:324 +0xcc
k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/validation.ValidateEtcd(0x400000b490, 0x4000296720, 0x0, 0x0, 0x0)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/validation/validation.go:291 +0x1f0
k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/validation.ValidateClusterConfiguration(0x400000b460, 0x2049058, 0x0, 0x0)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/validation/validation.go:63 +0x3d8
k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/validation.ValidateInitConfiguration(0x400000b440, 0x0, 0x0, 0x400000b440)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/validation/validation.go:50 +0x194
k8s.io/kubernetes/cmd/kubeadm/app/util/config.ConfigFileAndDefaultsToInternalConfig(0x7fd857989b, 0x1f, 0x400057ce00, 0x0, 0x0, 0x0)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/util/config/initconfiguration.go:191 +0xe8
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newInitData(0x4000405400, 0x40003ad810, 0x1244ec0, 0x40000ac000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:304 +0x144
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdInit.func3(0x4000405400, 0x40000ce3c0, 0x40000b5770, 0x235c5c, 0xe5ac20)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:181 +0x48
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).InitData(0x40003df0e0, 0x7, 0x40000b5810, 0x1e, 0x1e)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:184 +0x54
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdInit.func1(0x4000405400, 0x400064cfc0, 0x0, 0x3)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:135 +0x3c
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0x4000405400, 0x400064cf00, 0x3, 0x3, 0x4000405400, 0x400064cf00)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760 +0x1e0
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x4000163b80, 0x40002bb680, 0x4000405400, 0x40003aa780)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x204
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0x4000163b80, 0x40000a6000, 0x1244ec0)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794 +0x20
k8s.io/kubernetes/cmd/kubeadm/app.Run(0x40000ae0c0, 0x14f24)
        /workspace/anago-v1.13.0-rc.2.1+ddf47ac13c1a94/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:48 +0x220
main.main()
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:29 +0x20
```

Which is unclear about why exactly it's failing. Removal of the etcd keys results in it being fine (and prevents usage of an external etcd cluster)

**What you expected to happen**:
I expected it to use the existing external etcd cluster (which is up and working beautifully). 

**How to reproduce it (as minimally and precisely as possible)**:
See above

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.3.0-00
- Cloud provider or hardware configuration: ARM64 boards
- OS (e.g: `cat /etc/os-release`): 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
- Kernel (e.g. `uname -a`):
Linux r001sv002 4.4.132-1075-rockchip-ayufan-ga83beded8524 #1 SMP Thu Jul 26 08:22:22 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux
- Install tools:
- Others:

**Comment by brentnk** [comment]
@nfrush Have you tried adding the scheme (http/https) to your etcd endpoints?

**Comment by neolit123** [comment]
moving to:
https://github.com/kubernetes/kubeadm/issues/1419
/close
