### ISSUE TITLE
Divide by zero panic in getContainerUsageNanocores

### ISSUE THREAD

**Issue by adelina-t** [kubernetes/kubernetes#74667]
Kubelet panic with the following error:

```
panic: runtime error: integer divide by zero

goroutine 248 [running]:
k8s.io/kubernetes/pkg/kubelet/stats.(*criStatsProvider).getContainerUsageNanoCores(0xc000235560, 0xc00130ebc0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/stats/cri_stats_provider.go:548 +0x1a5
k8s.io/kubernetes/pkg/kubelet/stats.(*criStatsProvider).makeContainerStats(0xc000235560, 0xc00130ebc0, 0xc000cf4a20, 0xc0000b9800, 0xc0016d0fd8, 0xc000d330e0, 0x24, 0x1)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/stats/cri_stats_provider.go:454 +0x259
k8s.io/kubernetes/pkg/kubelet/stats.(*criStatsProvider).ListPodStats(0xc000235560, 0x2e3628b, 0xc000235560, 0xc000ec0af0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/stats/cri_stats_provider.go:160 +0x85d
k8s.io/kubernetes/pkg/kubelet/server/stats.(*summaryProviderImpl).Get(0xc0002da8c0, 0xc000158d01, 0xc000ee4528, 0x1, 0x1)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/summary.go:86 +0x41f
k8s.io/kubernetes/pkg/kubelet/eviction.(*managerImpl).synchronize(0xc000371600, 0x413ee20, 0xc000902f00, 0xc000839ac0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go:241 +0x128
k8s.io/kubernetes/pkg/kubelet/eviction.(*managerImpl).Start.func2(0xc000371600, 0x413ee20, 0xc000902f00, 0xc000839ac0, 0xc000839ad0, 0x2540be400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go:186 +0x60
created by k8s.io/kubernetes/pkg/kubelet/eviction.(*managerImpl).Start
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go:184 +0x1f9
```

The relevant lines are this: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/stats/cri_stats_provider.go#L547-L548

Basically, this value:

`nanoSeconds := stats.Cpu.Timestamp - cached.Timestamp`

can, in some conditins, be 0

**Environment**:
- Build from master ( v1.15.0-alpha.0.327+139a13d312b1b1 ):
- Cloud provider or hardware configuration: Azure
- OS: Windows Server 2019
- Others: Issue was observed while running conformance tests on Windows Clusters.

**Comment by adelina-t** [comment]
@PatrickLang

**Comment by neolit123** [comment]
/sig node
/sig windows
(for tracking)
