### ISSUE TITLE
Intermittent DNS resolution failures in Pods, but only right after Pod creation

### ISSUE THREAD

**Issue by chrisghill** [kubernetes/kubernetes#76790]
**What happened**:
~10% of brand new pods are failing DNS resolution right after they are created.  I have a CronJob that runs once per minute and will perform `dig www.github.com` 5 times with a 1 second sleep between each try. ~90% of the time all 5 calls will succeed, but ~10% of the time the first call will fail with the message:
```
; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> www.github.com
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**What you expected to happen**:
DNS to reliable resolve addresses

**How to reproduce it (as minimally and precisely as possible)**:
I can't reproduce 100%, but like I mentioned earlier I created a CronJob which performs `dig www.github.com` and it periodically fails.

**Anything else we need to know?**:
Here are some extensive details on what I've done and the current state:

I've noticed this issue happening for a few months now as its causing multiple failures in jobs across the whole cluster. I've not seen it fail when resolving kubernetes internal names, I've only seen it fail when resolving external names (like www.github.com, or some of our own company-internal names like our.domain.company.local)

Originally we were running with kube-dns, but I migrated us to CoreDNS yesterday.  Unfortunately the issue exists with both.

I created a deployment that ran `dig www.github.com` every few seconds and I didn't see any failures with it. It seems once DNS is working, it stays working. Additionally, with the CronJobs, if the DNS fails I've only ever seen it fail on the **first** lookup.  The rest always appear to succeed.

I've heard about some EC2 QPS limits (and the fact that kube-dns doesn't cache misses by default) and I thought "maybe more kube-dns pods would spread the load across more EC2 instances".  So I bumped the number of kube-dns pods from 2 to 6 (using the kube-dns-autoscaler) and that actually seemed to reduce the error rate, but it didn't eliminate it. So that could be a red herring.

Since it was the first `dig` call in the Jobs that seems to fail I thought "maybe the network isn't stable right when a pod is created". So I tried adding a `sleep 5` to the start of the CronJob before I make the first dig call.  Again, it **might** have reduced the error rate, but this failure is intermittent enough that its hard to make any determination.  The end result is that failures are still happening.  Here are 2 pictures of the logs of the CronJobs.  The first one is without the sleep (the shorter bars are failures since 1/5 of the DNS lookups returned just a timeout message):
![DNS_failures](https://user-images.githubusercontent.com/15616541/56387723-4f277580-61e2-11e9-8c28-21ac36cd6566.png)
And failures with the 5 second sleep to start the job:
![DNS_failures_sleep](https://user-images.githubusercontent.com/15616541/56387748-5a7aa100-61e2-11e9-9d6f-f7970ce5cbad.png)

I also tried running the Kubernetes DNS perf-test: https://github.com/kubernetes/perf-tests/tree/master/dns
But it would always fail with:
```
...
INFO 04-18 11:51:31 runner.py:174] Create Service/test-svc19 ok
INFO 04-18 11:51:31 runner.py:174] Create Service/test-svc20 ok
INFO 04-18 11:51:31 runner.py:121] Creating server with new parameters
INFO 04-18 11:51:31 runner.py:343] Starting server teardown
/home/cghill/Temp/perf-tests/dns/py/runner.py:427: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  pods = yaml.load(out)
INFO 04-18 11:51:33 runner.py:431] Waiting for server to be deleted (0 pods active)
INFO 04-18 11:51:33 runner.py:351] Server teardown ok
INFO 04-18 11:51:39 runner.py:174] Create Deployment/dns-perf-server ok
ERROR 04-18 11:51:40 runner.py:172] Could not create dns: 1
stdout:

stderr:The Service "dns-perf-server" is invalid: spec.clusterIP: Invalid value: "10.0.0.20": provided IP is not in the valid range. The range of valid IPs is 100.64.0.0/13


INFO 04-18 11:51:40 runner.py:135] Exception caught during run, cleaning up. Traceback (most recent call last):
  File "/home/cghill/Temp/perf-tests/dns/py/runner.py", line 124, in go
    self._create(self.service_yaml)
  File "/home/cghill/Temp/perf-tests/dns/py/runner.py", line 173, in _create
    raise Exception('create failed')
Exception: create failed

INFO 04-18 11:51:40 runner.py:343] Starting server teardown
INFO 04-18 11:51:45 runner.py:431] Waiting for server to be deleted (0 pods active)
...
```
It seems the hardcoded spec.clusterIP value isn't compatible with our cluster. I didn't see any evidence of others experiencing this issue or how to resolve it.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
Running in AWS, cluster deployed with Kops Version 1.11.1 (git-0f2aa8d30)
Amazon AMI: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17

- OS (e.g: `cat /etc/os-release`):
My personal system:
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

- Kernel (e.g. `uname -a`):
`Linux kubuntu 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

- Install tools:
Kops Version 1.11.1 (git-0f2aa8d30)

- Others:
/sig network

**Comment by chrisghill** [comment]
@kubernetes/sig-network-bugs

**Comment by chrisghill** [comment]
Additonally, here is my cluster config from `kops get -o yaml`:
```
apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: <redacted>
spec:
  additionalPolicies:
    master: |
      [
        {
          "Effect": "Allow",
          "Action": ["route53:ChangeResourceRecordSets"],
          "Resource": ["arn:aws:route53:::hostedzone/*"]
        },
        {
          "Effect": "Allow",
          "Action": ["route53:ListHostedZones", "route53:ListResourceRecordSets"],
          "Resource": ["*"]
        },
        {
          "Effect": "Allow",
          "Action": ["sts:AssumeRole"],
          "Resource": "*"
        }
      ]
    node: |
      [
        {
          "Effect": "Allow",
          "Action": ["route53:ChangeResourceRecordSets"],
          "Resource": ["arn:aws:route53:::hostedzone/*"]
        },
        {
          "Effect": "Allow",
          "Action": ["route53:ListHostedZones", "route53:ListResourceRecordSets"],
          "Resource": ["*"]
        },
        {
          "Effect": "Allow",
          "Action": ["sts:AssumeRole"],
          "Resource": "*"
        }
      ]
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudLabels:
    cluster: <redacted>
  cloudProvider: aws
  configBase: s3://<redacted>
  encryptionConfig: true
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    - instanceGroup: master-us-west-2b
      name: b
    - instanceGroup: master-us-west-2c
      name: c
    name: events
  fileAssets:
  - content: "# This is the policy used by Google Cloud Engine\n# https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L739\napiVersion:
      audit.k8s.io/v1beta1\nkind: Policy\nrules:\n  # The following requests were
      manually identified as high-volume and low-risk,\n  # so drop them.\n  - level:
      None\n    users: [\"system:kube-proxy\"]\n    verbs: [\"watch\"]\n    resources:\n
      \     - group: \"\" # core\n        resources: [\"endpoints\", \"services\",
      \"services/status\"]\n  - level: None\n    # Ingress controller reads 'configmaps/ingress-uid'
      through the unsecured port.\n    # TODO(#46983): Change this to the ingress
      controller service account.\n    users: [\"system:unsecured\"]\n    namespaces:
      [\"kube-system\"]\n    verbs: [\"get\"]\n    resources:\n      - group: \"\"
      # core\n        resources: [\"configmaps\"]\n  - level: None\n    users: [\"kubelet\"]
      # legacy kubelet identity\n    verbs: [\"get\"]\n    resources:\n      - group:
      \"\" # core\n        resources: [\"nodes\", \"nodes/status\"]\n  - level: None\n
      \   userGroups: [\"system:nodes\"]\n    verbs: [\"get\"]\n    resources:\n      -
      group: \"\" # core\n        resources: [\"nodes\", \"nodes/status\"]\n  - level:
      None\n    users:\n      - system:kube-controller-manager\n      - system:kube-scheduler\n
      \     - system:serviceaccount:kube-system:endpoint-controller\n    verbs: [\"get\",
      \"update\"]\n    namespaces: [\"kube-system\"]\n    resources:\n      - group:
      \"\" # core\n        resources: [\"endpoints\"]\n  - level: None\n    users:
      [\"system:apiserver\"]\n    verbs: [\"get\"]\n    resources:\n      - group:
      \"\" # core\n        resources: [\"namespaces\", \"namespaces/status\", \"namespaces/finalize\"]\n
      \ # Don't log HPA fetching metrics.\n  - level: None\n    users:\n      - system:kube-controller-manager\n
      \   verbs: [\"get\", \"list\"]\n    resources:\n      - group: \"metrics.k8s.io\"\n
      \ # Don't log these read-only URLs.\n  - level: None\n    nonResourceURLs:\n
      \     - /healthz*\n      - /version\n      - /swagger*\n  # Don't log events
      requests.\n  - level: None\n    resources:\n      - group: \"\" # core\n        resources:
      [\"events\"]\n  # node and pod status calls from nodes are high-volume and can
      be large, don't log responses for expected updates from nodes\n  - level: Request\n
      \   users: [\"kubelet\", \"system:node-problem-detector\", \"system:serviceaccount:kube-system:node-problem-detector\"]\n
      \   verbs: [\"update\",\"patch\"]\n    resources:\n      - group: \"\" # core\n
      \       resources: [\"nodes/status\", \"pods/status\"]\n    omitStages:\n      -
      \"RequestReceived\"\n  - level: Request\n    userGroups: [\"system:nodes\"]\n
      \   verbs: [\"update\",\"patch\"]\n    resources:\n      - group: \"\" # core\n
      \       resources: [\"nodes/status\", \"pods/status\"]\n    omitStages:\n      -
      \"RequestReceived\"\n  # deletecollection calls can be large, don't log responses
      for expected namespace deletions\n  - level: Request\n    users: [\"system:serviceaccount:kube-system:namespace-controller\"]\n
      \   verbs: [\"deletecollection\"]\n    omitStages:\n      - \"RequestReceived\"\n
      \ # Secrets, ConfigMaps, and TokenReviews can contain sensitive & binary data,\n
      \ # so only log at the Metadata level.\n  - level: Metadata\n    resources:\n
      \     - group: \"\" # core\n        resources: [\"secrets\", \"configmaps\"]\n
      \     - group: authentication.k8s.io\n        resources: [\"tokenreviews\"]\n
      \   omitStages:\n      - \"RequestReceived\"\n  # Get repsonses can be large;
      skip them.\n  - level: Request\n    verbs: [\"get\", \"list\", \"watch\"]\n
      \   resources:\n    - group: \"\" # core\n    - group: \"admissionregistration.k8s.io\"\n
      \   - group: \"apiextensions.k8s.io\"\n    - group: \"apiregistration.k8s.io\"\n
      \   - group: \"apps\"\n    - group: \"authentication.k8s.io\"\n    - group:
      \"authorization.k8s.io\"\n    - group: \"autoscaling\"\n    - group: \"batch\"\n
      \   - group: \"certificates.k8s.io\"\n    - group: \"extensions\"\n    - group:
      \"metrics.k8s.io\"\n    - group: \"networking.k8s.io\"\n    - group: \"policy\"\n
      \   - group: \"rbac.authorization.k8s.io\"\n    - group: \"scheduling.k8s.io\"\n
      \   - group: \"settings.k8s.io\"\n    - group: \"storage.k8s.io\"\n    omitStages:\n
      \     - \"RequestReceived\"\n  # Default level for known APIs\n  - level: RequestResponse\n
      \   resources:\n    - group: \"\" # core\n    - group: \"admissionregistration.k8s.io\"\n
      \   - group: \"apiextensions.k8s.io\"\n    - group: \"apiregistration.k8s.io\"\n
      \   - group: \"apps\"\n    - group: \"authentication.k8s.io\"\n    - group:
      \"authorization.k8s.io\"\n    - group: \"autoscaling\"\n    - group: \"batch\"\n
      \   - group: \"certificates.k8s.io\"\n    - group: \"extensions\"\n    - group:
      \"metrics.k8s.io\"\n    - group: \"networking.k8s.io\"\n    - group: \"policy\"\n
      \   - group: \"rbac.authorization.k8s.io\"\n    - group: \"scheduling.k8s.io\"\n
      \   - group: \"settings.k8s.io\"\n    - group: \"storage.k8s.io\"      \n    omitStages:\n
      \     - \"RequestReceived\"\n  # Default level for all other requests.\n  -
      level: Metadata\n    omitStages:\n      - \"RequestReceived\"\n"
    name: audit-policy.yaml
    path: /srv/kubernetes/audit-policy.yaml
    roles:
    - Master
  hooks:
  - before:
    - kubelet.service
    manifest: |
      [Unit]
      Description=Download AWS Authenticator configs from S3
      [Service]
      Type=oneshot
      ExecStart=/bin/mkdir -p /srv/kubernetes/aws-iam-authenticator
      ExecStart=<redacted>
    name: kops-hook-authenticator-config.service
    roles:
    - Master
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeAPIServer:
    admissionControl:
    - Initializers
    - NamespaceLifecycle
    - LimitRanger
    - ServiceAccount
    - PersistentVolumeLabel
    - PersistentVolumeClaimResize
    - DefaultStorageClass
    - DefaultTolerationSeconds
    - MutatingAdmissionWebhook
    - ValidatingAdmissionWebhook
    - NodeRestriction
    - ResourceQuota
    - AlwaysPullImages
    - PodSecurityPolicy
    - DenyEscalatingExec
    auditLogMaxAge: 30
    auditLogMaxBackups: 10
    auditLogMaxSize: 100
    auditLogPath: /var/log/kube-apiserver-audit.log
    auditPolicyFile: /srv/kubernetes/audit-policy.yaml
    authenticationTokenWebhookConfigFile: /srv/kubernetes/aws-iam-authenticator/kubeconfig.yaml
    featureGates:
      ExpandPersistentVolumes: "true"
    runtimeConfig:
      admissionregistration.k8s.io/v1alpha1: "true"
      api/all: "true"
  kubeControllerManager:
    featureGates:
      ExpandPersistentVolumes: "true"
    horizontalPodAutoscalerUseRestClients: true
  kubeDNS:
    provider: CoreDNS
  kubelet:
    featureGates:
      ExpandPersistentVolumes: "true"
      ExperimentalCriticalPodAnnotation: "true"
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.9
  masterInternalName: api.internal.<redacted>
  masterPublicName: api.<redacted>
  networkCIDR: 172.20.0.0/16
  networking:
    weave:
      mtu: 8912
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-west-2a
    type: Private
    zone: us-west-2a
  - cidr: 172.20.64.0/19
    name: us-west-2b
    type: Private
    zone: us-west-2b
  - cidr: 172.20.96.0/19
    name: us-west-2c
    type: Private
    zone: us-west-2c
  - cidr: 172.20.0.0/22
    name: utility-us-west-2a
    type: Utility
    zone: us-west-2a
  - cidr: 172.20.4.0/22
    name: utility-us-west-2b
    type: Utility
    zone: us-west-2b
  - cidr: 172.20.8.0/22
    name: utility-us-west-2c
    type: Utility
    zone: us-west-2c
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
```

**Comment by huguesalary** [comment]
I am running into a similar issue where my cluster becomes unresponsive. 

I reported this bug to Google since I'm running on GKE, but it could be unrelated to GKE. Here's the original bug report (https://issuetracker.google.com/issues/131888720):

We started noticing lots of 522 timeouts being reported by cloudflare.

522 timeouts are explained here: https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522-Connection-timed-out

The gist of it is that a 522 can be triggered if upon establishing a connection from cloudflare to my server, if the SYN+ACK is not returned from the origin web server within 15 seconds, a 522 error will happen.

Upon investigation, it would appear as though everytime we get 522 errors, the kubernetes logs are litered with the following kubedns errors:

```
W  Liveness probe failed: rpc error: code = 13 desc = transport is closing
 
W  unable to get metrics for resource cpu: no metrics returned from resource metrics API 
W  failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API 
W  unable to get metrics for resource cpu: no metrics returned from resource metrics API 
W  failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server is currently unable to handle the request (get pods.metrics.k8s.io) 
W  unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server is currently unable to handle the request (get pods.metrics.k8s.io) 
W  Liveness probe failed: Get http://10.16.25.36:10054/healthcheck/kubedns: dial tcp 10.16.25.36:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.25.36:10054/healthcheck/dnsmasq: dial tcp 10.16.25.36:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.25.36:10054/healthcheck/kubedns: dial tcp 10.16.25.36:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.25.36:10054/healthcheck/dnsmasq: dial tcp 10.16.25.36:10054: connect: connection refused 
W  network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR] 
W  network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR] 
W  Unable to mount volumes for pod "fluentd-gcp-v3.2.0-9kctj_kube-system(e8fc5d1e-6dd6-11e9-afc3-4201ac120004)": timeout expired waiting for volumes to attach or mount for pod "kube-system"/"fluentd-gcp-v3.2.0-9kctj". list of unmounted volumes=[varlog varlibdockercontainers config-volume fluentd-gcp-token-wkjhb]. list of unattached volumes=[varlog varlibdockercontainers config-volume fluentd-gcp-token-wkjhb] 
W  network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR] 
W  Liveness probe failed: Get http://10.16.27.161:10054/healthcheck/kubedns: dial tcp 10.16.27.161:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.25.36:10054/healthcheck/kubedns: dial tcp 10.16.25.36:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.25.36:10054/healthcheck/dnsmasq: dial tcp 10.16.25.36:10054: connect: connection refused 
W  network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR] 
W  Liveness probe failed: Get http://10.16.27.161:10054/healthcheck/dnsmasq: dial tcp 10.16.27.161:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.27.161:10054/healthcheck/kubedns: dial tcp 10.16.27.161:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.27.161:10054/healthcheck/dnsmasq: dial tcp 10.16.27.161:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.23.146:10054/healthcheck/kubedns: dial tcp 10.16.23.146:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.23.146:10054/healthcheck/dnsmasq: dial tcp 10.16.23.146:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.27.161:10054/healthcheck/kubedns: dial tcp 10.16.27.161:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.27.161:10054/healthcheck/dnsmasq: dial tcp 10.16.27.161:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.23.146:10054/healthcheck/kubedns: dial tcp 10.16.23.146:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.23.146:10054/healthcheck/dnsmasq: dial tcp 10.16.23.146:10054: connect: connection refused 
gke-production-preemptible-9be27494-qfzl:{} gke-production-preemptible-9be27494-nj2l:{} gke-production-preemptible-9be27494-zw51:{}]: instance not found 
W  Liveness probe failed: Get http://10.16.26.62:10054/healthcheck/kubedns: dial tcp 10.16.26.62:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.26.62:10054/healthcheck/dnsmasq: dial tcp 10.16.26.62:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.4.85:10054/healthcheck/kubedns: dial tcp 10.16.4.85:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.4.85:10054/healthcheck/dnsmasq: dial tcp 10.16.4.85:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.26.62:10054/healthcheck/kubedns: dial tcp 10.16.26.62:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.26.62:10054/healthcheck/dnsmasq: dial tcp 10.16.26.62:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.4.85:10054/healthcheck/kubedns: dial tcp 10.16.4.85:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.4.85:10054/healthcheck/dnsmasq: dial tcp 10.16.4.85:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.26.62:10054/healthcheck/kubedns: dial tcp 10.16.26.62:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.26.62:10054/healthcheck/dnsmasq: dial tcp 10.16.26.62:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.25.37:10054/healthcheck/dnsmasq: dial tcp 10.16.25.37:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.25.37:10054/healthcheck/kubedns: dial tcp 10.16.25.37:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.4.85:10054/healthcheck/kubedns: dial tcp 10.16.4.85:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.4.85:10054/healthcheck/dnsmasq: dial tcp 10.16.4.85:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.25.37:10054/healthcheck/dnsmasq: dial tcp 10.16.25.37:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.25.37:10054/healthcheck/kubedns: dial tcp 10.16.25.37:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.25.37:10054/healthcheck/dnsmasq: dial tcp 10.16.25.37:10054: connect: connection refused 
W  Liveness probe failed: Get http://10.16.25.37:10054/healthcheck/kubedns: dial tcp 10.16.25.37:10054: connect: connection refused 
W  error determining status: rpc error: code = Unknown desc = Error: No such container: 5236a9cb7ab5cf7d9ce132363b815b40a3b87ccbd2a1862d8958979ab2980c4a 
W  network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR] 
```

Those errors seem to be happening at the same time the `kube-dns-autoscaler` scales down/up the kubedns pods of our cluster.

```
I0503 19:29:04.927387       1 k8sclient.go:215] Cluster status: SchedulableNodes[330], SchedulableCores[423]
I0503 19:29:04.927462       1 k8sclient.go:216] Replicas are not as expected : updating replicas from 22 to 21
I0503 19:29:24.928602       1 k8sclient.go:215] Cluster status: SchedulableNodes[313], SchedulableCores[406]
I0503 19:29:24.928655       1 k8sclient.go:216] Replicas are not as expected : updating replicas from 21 to 20
I0503 19:29:34.935662       1 k8sclient.go:215] Cluster status: SchedulableNodes[300], SchedulableCores[393]
I0503 19:29:34.935701       1 k8sclient.go:216] Replicas are not as expected : updating replicas from 20 to 19
I0503 19:29:54.935646       1 k8sclient.go:215] Cluster status: SchedulableNodes[286], SchedulableCores[379]
I0503 19:29:54.935691       1 k8sclient.go:216] Replicas are not as expected : updating replicas from 19 to 18
I0503 19:30:14.948235       1 k8sclient.go:215] Cluster status: SchedulableNodes[269], SchedulableCores[362]
I0503 19:30:14.948305       1 k8sclient.go:216] Replicas are not as expected : updating replicas from 18 to 17
I0503 19:30:34.946534       1 k8sclient.go:215] Cluster status: SchedulableNodes[251], SchedulableCores[344]
I0503 19:30:34.946643       1 k8sclient.go:216] Replicas are not as expected : updating replicas from 17 to 16
```

**Comment by omegarus** [comment]
@chrisghill I'am experiencing  same problem right now on 1.11.9. 
Further investigation showed that DNS resolution problems happens on specific nodes.
After reviewing syslog of this nodes i found this kernel message:
`kernel:unregister_netdevice: waiting for eth0 to become free. Usage count = 1`
Here is issues related to it #64743 
More info is here: https://pingcap.com/blog/try-to-fix-two-linux-kernel-bugs-while-testing-tidb-operator-in-k8s/

**Comment by chrisghill** [comment]
@omegarus Thanks for following up.  I had seen that issue before as well, and we've installed the NodeProblemDetector (https://github.com/kubernetes/node-problem-detector) and Draino (https://github.com/planetlabs/draino) to handle that case.

The other part of this issue seems related to the DNAT race condition outlined at length here: https://github.com/kubernetes/kubernetes/issues/56903

Since this is covered by other issues I'll close it here.

**Comment by aitescmgit** [comment]
**Set the value and output it to sysctl.conf file**

echo “net.bridge.bridge-nf-call-iptables=1” | sudo tee -a /etc/sysctl.conf

**Comment by therealak12** [comment]
The problem might be related to [this issue](https://github.com/alpinelinux/docker-alpine/issues/149#issuecomment-802902005). What base image do you use?

**Comment by lukos** [comment]
I am suffering from intermittent DNS and there don't seem to be any open issues currently. Did anyone ever put together the definitive guide to debugging and fixing this? We have a Rancher cluster running canal for networking and like another poster, it never seems to be a problem on nodes, but an intermittent problem in pods.

I have tried setting ndots to 1 and `single-request-reopen`, I also added a period on the end of the hostname (of a mail server) but it always failed with a DNS error. It works fine when I use an IP address. I haven't seen this before but I am not sure that I have called out from a microservice until today.

```bash
root@test-utils:/# nslookup mailhog.example.io
Server:         10.43.0.10
Address:        10.43.0.10#53

*** Can't find mailhog.example.io: No answer

root@test-utils:/# nslookup mailhog.example.io
Server:         10.43.0.10
Address:        10.43.0.10#53

Name:   mailhog.example.io
Address: 172.23.4.35

root@test-utils:/# nslookup mailhog.example.io
Server:         10.43.0.10
Address:        10.43.0.10#53

*** Can't find mailhog.example.io: No answer
```

**Comment by therealak12** [comment]
@lukos It could be due to alpine base image. If you using such an image as the base image, consider changing it to normal distribution images e.g. Ubuntu.

**Comment by lukos** [comment]
We are using Ubuntu so not that! Thanks.
