### ISSUE TITLE
components log to stderr *before* klog is initialized

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#77305]
To recreate the problem use this diff against `hack/local-up-cluster.sh`:
http://paste.openstack.org/raw/750145/

See the `*-stderr.log` files below, they contain output from the binaries before klog is properly initialized. We specify `--log-file` when we start the components and the `*-log-file.log` files contain the correct logs once klog is initialized properly.
```
dims@bigbox:/opt/stack/logs$ ls -altr *log-file.log *stderr.log
-rw-r--r-- 1 root root    4398 May  1 10:17 kube-apiserver-stderr.log
-rw-r--r-- 1 root root       0 May  1 10:18 kube-proxy-stderr.log
-rw-r--r-- 1 root root    2382 May  1 10:18 kube-controller-manager-stderr.log
-rw-r--r-- 1 root root    7701 May  1 10:18 kubelet-stderr.log
-rw-r--r-- 1 root root     456 May  1 10:18 kube-scheduler-stderr.log
-rw-r--r-- 1 root root  189950 May  1 10:18 kubelet-log-file.log
-rw-r--r-- 1 root root  146679 May  1 10:18 kube-scheduler-log-file.log
-rw-r--r-- 1 root root 9898330 May  1 10:19 kube-controller-manager-log-file.log
-rw-r--r-- 1 root root   54168 May  1 10:19 kube-proxy-log-file.log
-rw-r--r-- 1 root root 2593089 May  1 10:19 kube-apiserver-log-file.log
```

**Comment by dims** [comment]
cc @mtaufen @vincepri

**Comment by dims** [comment]
example output in *-stderr.log

```
dims@bigbox:/opt/stack/logs$ cat *stderr.log
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: kube-apiserver-stderr.log
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ Flag --insecure-bind-address has been deprecated, This flag will be removed in a future version.
   2   │ Flag --insecure-port has been deprecated, This flag will be removed in a future version.
   3   │ E0501 10:32:04.983775    6746 prometheus.go:55] failed to register depth metric admission_quota_controller: duplicate metrics collector registration attempted
   4   │ E0501 10:32:04.983962    6746 prometheus.go:68] failed to register adds metric admission_quota_controller: duplicate metrics collector registration attempted
   5   │ E0501 10:32:04.983989    6746 prometheus.go:82] failed to register latency metric admission_quota_controller: duplicate metrics collector registration attempted
   6   │ E0501 10:32:04.984010    6746 prometheus.go:96] failed to register workDuration metric admission_quota_controller: duplicate metrics collector registration attempted
   7   │ E0501 10:32:04.984041    6746 prometheus.go:112] failed to register unfinished metric admission_quota_controller: duplicate metrics collector registration attempted
   8   │ E0501 10:32:04.984062    6746 prometheus.go:126] failed to register unfinished metric admission_quota_controller: duplicate metrics collector registration attempted
   9   │ E0501 10:32:04.984080    6746 prometheus.go:152] failed to register depth metric admission_quota_controller: duplicate metrics collector registration attempted
  10   │ E0501 10:32:04.984097    6746 prometheus.go:164] failed to register adds metric admission_quota_controller: duplicate metrics collector registration attempted
  11   │ E0501 10:32:04.984137    6746 prometheus.go:176] failed to register latency metric admission_quota_controller: duplicate metrics collector registration attempted
  12   │ E0501 10:32:04.984180    6746 prometheus.go:188] failed to register work_duration metric admission_quota_controller: duplicate metrics collector registration attempted
  13   │ E0501 10:32:04.984207    6746 prometheus.go:203] failed to register unfinished_work_seconds metric admission_quota_controller: duplicate metrics collector registration attempted
  14   │ E0501 10:32:04.984227    6746 prometheus.go:216] failed to register longest_running_processor_microseconds metric admission_quota_controller: duplicate metrics collector registration attempted
  15   │ E0501 10:32:06.170806    6746 prometheus.go:55] failed to register depth metric admission_quota_controller: duplicate metrics collector registration attempted
  16   │ E0501 10:32:06.170856    6746 prometheus.go:68] failed to register adds metric admission_quota_controller: duplicate metrics collector registration attempted
  17   │ E0501 10:32:06.170888    6746 prometheus.go:82] failed to register latency metric admission_quota_controller: duplicate metrics collector registration attempted
  18   │ E0501 10:32:06.170913    6746 prometheus.go:96] failed to register workDuration metric admission_quota_controller: duplicate metrics collector registration attempted
  19   │ E0501 10:32:06.170937    6746 prometheus.go:112] failed to register unfinished metric admission_quota_controller: duplicate metrics collector registration attempted
  20   │ E0501 10:32:06.170958    6746 prometheus.go:126] failed to register unfinished metric admission_quota_controller: duplicate metrics collector registration attempted
  21   │ E0501 10:32:06.170977    6746 prometheus.go:152] failed to register depth metric admission_quota_controller: duplicate metrics collector registration attempted
  22   │ E0501 10:32:06.170995    6746 prometheus.go:164] failed to register adds metric admission_quota_controller: duplicate metrics collector registration attempted
  23   │ E0501 10:32:06.171057    6746 prometheus.go:176] failed to register latency metric admission_quota_controller: duplicate metrics collector registration attempted
  24   │ E0501 10:32:06.171146    6746 prometheus.go:188] failed to register work_duration metric admission_quota_controller: duplicate metrics collector registration attempted
  25   │ E0501 10:32:06.171171    6746 prometheus.go:203] failed to register unfinished_work_seconds metric admission_quota_controller: duplicate metrics collector registration attempted
  26   │ E0501 10:32:06.171191    6746 prometheus.go:216] failed to register longest_running_processor_microseconds metric admission_quota_controller: duplicate metrics collector registration attempted
  27   │ E0501 10:32:07.891035    6746 controller.go:148] Unable to remove old endpoints from kubernetes service: StorageError: key not found, Code: 1, Key: /registry/masterleases/172.17.0.1, ResourceVersion: 0, Additi
       │ onalErrorMsg:
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: kube-controller-manager-stderr.log
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ E0501 10:32:16.972387    7159 core.go:76] Failed to start service controller: WARNING: no cloud provider provided, services of type LoadBalancer will fail
   2   │ E0501 10:32:18.422363    7159 core.go:160] failed to start cloud node lifecycle controller: no cloud provider provided
   3   │ E0501 10:32:19.477718    7159 prometheus.go:55] failed to register depth metric certificate: duplicate metrics collector registration attempted
   4   │ E0501 10:32:19.477779    7159 prometheus.go:68] failed to register adds metric certificate: duplicate metrics collector registration attempted
   5   │ E0501 10:32:19.477819    7159 prometheus.go:82] failed to register latency metric certificate: duplicate metrics collector registration attempted
   6   │ E0501 10:32:19.477855    7159 prometheus.go:96] failed to register workDuration metric certificate: duplicate metrics collector registration attempted
   7   │ E0501 10:32:19.477900    7159 prometheus.go:112] failed to register unfinished metric certificate: duplicate metrics collector registration attempted
   8   │ E0501 10:32:19.477935    7159 prometheus.go:126] failed to register unfinished metric certificate: duplicate metrics collector registration attempted
   9   │ E0501 10:32:19.477966    7159 prometheus.go:152] failed to register depth metric certificate: duplicate metrics collector registration attempted
  10   │ E0501 10:32:19.477996    7159 prometheus.go:164] failed to register adds metric certificate: duplicate metrics collector registration attempted
  11   │ E0501 10:32:19.478072    7159 prometheus.go:176] failed to register latency metric certificate: duplicate metrics collector registration attempted
  12   │ E0501 10:32:19.478135    7159 prometheus.go:188] failed to register work_duration metric certificate: duplicate metrics collector registration attempted
  13   │ E0501 10:32:19.478175    7159 prometheus.go:203] failed to register unfinished_work_seconds metric certificate: duplicate metrics collector registration attempted
  14   │ E0501 10:32:19.478208    7159 prometheus.go:216] failed to register longest_running_processor_microseconds metric certificate: duplicate metrics collector registration attempted
  15   │ E0501 10:32:19.478257    7159 prometheus.go:139] failed to register retries metric certificate: duplicate metrics collector registration attempted
  16   │ E0501 10:32:19.478284    7159 prometheus.go:228] failed to register retries metric certificate: duplicate metrics collector registration attempted
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: kubelet-stderr.log
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ Flag --allow-privileged has been deprecated, will be removed in a future version
   2   │ Flag --address has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for m
       │ ore information.
   3   │ Flag --feature-gates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/
       │  for more information.
   4   │ Flag --cpu-cfs-quota has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/
       │  for more information.
   5   │ Flag --enable-controller-attach-detach has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/ku
       │ belet-config-file/ for more information.
   6   │ Flag --cgroups-per-qos has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-fil
       │ e/ for more information.
   7   │ Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/
       │  for more information.
   8   │ Flag --cgroup-root has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ f
       │ or more information.
   9   │ Flag --eviction-hard has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/
       │  for more information.
  10   │ Flag --eviction-soft has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/
       │  for more information.
  11   │ Flag --eviction-pressure-transition-period has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluste
       │ r/kubelet-config-file/ for more information.
  12   │ Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-f
       │ ile/ for more information.
  13   │ Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/
       │ for more information.
  14   │ Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-
       │ file/ for more information.
  15   │ Flag --authentication-token-webhook has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubel
       │ et-config-file/ for more information.
  16   │ Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file
       │ / for more information.
  17   │ Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ f
       │ or more information.
  18   │ Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file
       │ / for more information.
  19   │ Flag --runtime-request-timeout has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-co
       │ nfig-file/ for more information.
  20   │ Flag --port has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more
       │  information.
  21   │ E0501 10:32:21.388632    8051 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
  22   │     For verbose messaging see aws.Config.CredentialsChainVerboseErrors
  23   │ E0501 10:32:21.389039    8051 remote_runtime.go:81] Version from runtime service failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: de
       │ sc = "transport: Error while dialing dial unix /var/run/dockershim.sock: connect: connection refused"
  24   │ E0501 10:32:21.389178    8051 kuberuntime_manager.go:191] Get runtime version failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc
       │ = "transport: Error while dialing dial unix /var/run/dockershim.sock: connect: connection refused"
  25   │ F0501 10:32:21.389212    8051 server.go:268] failed to run Kubelet: failed to create kubelet: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection erro
       │ r: desc = "transport: Error while dialing dial unix /var/run/dockershim.sock: connect: connection refused"
  26   │ goroutine 1 [running]:
  27   │ k8s.io/kubernetes/vendor/k8s.io/klog.stacks(0xc0001d6a00, 0xc000a50000, 0x13c, 0x18e)
  28   │     /home/dims/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:840 +0xb1
  29   │ k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).output(0x77216c0, 0xc000000003, 0xc0007263f0, 0x73f5a53, 0x9, 0x10c, 0x0)
  30   │     /home/dims/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:791 +0x2d9
  31   │ k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).printDepth(0x77216c0, 0xc000000003, 0x1, 0xc000ac5c58, 0x1, 0x1)
  32   │     /home/dims/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:681 +0x12b
  33   │ k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).print(...)
  34   │     /home/dims/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:672
  35   │ k8s.io/kubernetes/vendor/k8s.io/klog.Fatal(...)
  36   │     /home/dims/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:1221
  37   │ k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0xc000736a00, 0xc00004e210, 0x1f, 0x1f)
  38   │     /home/dims/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:268 +0x619
  39   │ k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000736a00, 0xc00004e210, 0x1f, 0x1f, 0xc000736a00, 0xc00004e210)
  40   │     /home/dims/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760 +0x2ae
  41   │ k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000736a00, 0x42c0190, 0x7721200, 0x4142dc5)
  42   │     /home/dims/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x2ec
  43   │ k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
  44   │     /home/dims/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794
  45   │ main.main()
  46   │     _output/local/go/src/k8s.io/kubernetes/cmd/kubelet/kubelet.go:43 +0xd3
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: kube-scheduler-stderr.log
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ E0501 10:32:20.830215    7260 scheduler.go:481] error selecting node for pod: no nodes available to schedule pods
   2   │ E0501 10:32:20.871698    7260 scheduler.go:481] error selecting node for pod: no nodes available to schedule pods
   3   │ E0501 10:32:20.871936    7260 scheduler.go:481] error selecting node for pod: no nodes available to schedule pods
   4   │ E0501 10:32:20.872095    7260 scheduler.go:481] error selecting node for pod: no nodes available to schedule pods
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by dims** [comment]
cc @tallclair @yuwenma

**Comment by bgrant0607** [comment]
@dims Could you please remind me why klog is in SIG Architecture rather than SIG Instrumentation?

I added area/logging and sig/instrumentation.

**Comment by neolit123** [comment]
the sponsor SIG was sig-arch:
https://github.com/kubernetes/org/issues/195#issuecomment-435507351

but should be sig-instrumentation, indeed.

**Comment by dims** [comment]
@bgrant0607 @neolit123 +1 to moving it. I'll start the process

**Comment by dims** [comment]
cc @mtaufen
