### ISSUE TITLE
SAML auth with vSphere and zones API not working

### ISSUE THREAD

**Issue by rhockenbury** [kubernetes/kubernetes#77360]
**What happened**:

The vSphere cloud provider is unable to fetch the node failure domain labels when using VCP with SAML auth because of an authentication failure.  For context, the SAML token auth is described here - https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/saml-token-authentication.html.  SAML auth support for the zones api was introduced in this PR - https://github.com/kubernetes/kubernetes/pull/75515, which was cherry-picked to 1.14.1 here - https://github.com/kubernetes/kubernetes/pull/75742

I've tested the credentials I'm using with govc to ensure that I'm able to get a token:
```
$token = govc session.login -l -u vcdo -cert keys\public.crt -key keys\private.key -issue -debug
```
The credentials also work fine when using VCP without the node labels feature. 

Relevant kubelet logs: 
```
I0502 14:31:45.856013    5908 generic.go:189] GenericPLEG: Relisting
I0502 14:31:46.775592    5908 connection.go:142] SessionManager.LoginByToken with certificate
I0502 14:31:46.858589    5908 generic.go:189] GenericPLEG: Relisting
I0502 14:31:46.916706    5908 connection.go:209] New session ID for 'VSPHERE.LOCAL\k8s-vcp-dolap' = 52109852-8b67-9901-c095-6f21d8210c03
I0502 14:31:47.162687    5908 datacenter.go:99] VirtualMachine:vm-82 host is HostSystem:host-65
I0502 14:31:47.833807    5908 config.go:100] Looking for [api], have seen map[api:{}]
I0502 14:31:47.833807    5908 kubelet.go:1972] SyncLoop (housekeeping)
I0502 14:31:47.859584    5908 generic.go:189] GenericPLEG: Relisting
I0502 14:31:48.693024    5908 cni.go:182] Using CNI configuration file C:\k\cni\config\cni.conf
I0502 14:31:48.853838    5908 kubelet.go:2167] Container runtime status: Runtime Conditions: RuntimeReady=true reason: message:, NetworkReady=true reason: message:
I0502 14:31:48.860848    5908 generic.go:189] GenericPLEG: Relisting
I0502 14:31:49.833687    5908 config.go:100] Looking for [api], have seen map[api:{}]
I0502 14:31:49.833687    5908 kubelet.go:1972] SyncLoop (housekeeping)
I0502 14:31:49.863597    5908 generic.go:189] GenericPLEG: Relisting
E0502 14:31:49.992408    5908 vsphere.go:1538] Get zone for node ul-win-node-5k: POST https://vcdo.production.com:443/rest/com/vmware/cis/session: 401 Unauthorized
E0502 14:31:49.992408    5908 kubelet_node_status.go:68] Unable to construct v1.Node object for kubelet: failed to get zone from cloud provider: POST https://vcdo.production.com:443/rest/com/vmware/cis/session: 401 Unauthorized
I0502 14:31:50.194250    5908 kubelet_node_status.go:283] Setting node annotation to enable volume controller attach/detach
I0502 14:31:50.453104    5908 datacenter.go:99] VirtualMachine:vm-82 host is HostSystem:host-65
```

**What you expected to happen**:
VCP should add failure domain labels to the node object.

**How to reproduce it (as minimally and precisely as possible)**:
Setup SAML auth for VCP with zone labeling enabled. 

**Anything else we need to know?**:
There was a previous issue that was raised (https://github.com/kubernetes/kubernetes/issues/75511) but that was before SAML auth support for zones was implemented.  

This could potentially be an issue with govc handling of SAML tokens since even with the Administrator role assigned to the user, I'm still unable to list tags.
```
> $ENV:GOVC_LOGIN_TOKEN = govc session.login -l -u vcdo -cert keys\public.crt -key keys\private.key -issue
> govc tags.attached.ls -json -r /uunet
C:\Users\rhockenbury\Tools\govc.exe: POST https://vcdo/rest/com/vmware/cis/session: 401 Unauthorized
```

The role and keys were generated with the following:
```
 $manageK8sVms= @("Resource.AssignVMToPool","VirtualMachine.Config.AddExistingDisk","VirtualMachine.Config.AddNewDisk","VirtualMachine.Config.AddRemoveDevice","VirtualMachine.Config.RemoveDisk","VirtualMachine.Inventory.Create","VirtualMachine.Inventory.Delete","VirtualMachine.Config.Settings","DataStore.AllocateSpace","DataStore.FileManagement","StorageProfile.View","System.Read","System.Anonymous","System.view")
New-ViRole -name "manage-k8s-devops-lab" -privilege (Get-ViPrivilege -id $manageK8sVms)
set-ViRole -role "manage-k8s-devops-lab" -AddPrivilege (Get-VIPrivilege -id $manageK8sVms)

openssl req -newkey rsa:2048 -x509 -days 365 -nodes -keyout k8s-vcp-dolab.key -out k8s-vcp-dolab.crt -subj "/C=US/ST=CA/L=SF/O=VMware/OU=CNA/CN=www.vmware.com"

/usr/lib/vmware-vmafd/bin/dir-cli service create --name k8s-vcp-dolap --cert k8s-vcp-dolab.crt 
```

**Environment**:
- Kubernetes version (use `kubectl version`):
1.14.1
- Cloud provider or hardware configuration:
vSphere
- OS (e.g: `cat /etc/os-release`):
Linux & Windows

**Comment by rhockenbury** [comment]
@dougm Would you mind taking a look at this?  I can provide more info if needed.

**Comment by dougm** [comment]
govc's `session.login` command only works with the SOAP endpoint currently.  The REST endpoint has its own session manager and requires a separate login.  At the moment, govc's tags commands login/logout when each command is run and don't use a persisted session (which are saved to ~/.govmomi/sessions).

However, you can use a token returned by `session.login -issue` to test SAML auth with the tags commands.  For example:

```console
% token=$(govc session.login -u host -cert user.crt -key user.key -issue) # HoK token
GOVC_LOGIN_TOKEN="$token" govc tags.ls -u host -cert user.crt -key user.key)
```

Can you give that try?

There are some TODOs around this btw: https://github.com/vmware/govmomi/blob/fc3f0e9d2275df0e497a80917807a7c72d3c35bc/govc/flags/client.go#L575-L582

**Comment by rhockenbury** [comment]
Those commands work for me.

```
$ token=$(govc session.login -l -u vcdo.aptproduction.com -cert keys/public2.crt -key keys/private2.key -issue)
$ GOVC_LOGIN_TOKEN="$token" govc tags.ls -u vcdo.aptproduction.com -cert keys/public2.crt -key keys/private2.key -json | jq .
[
  {
    "id": "urn:vmomi:InventoryServiceTag:1f7e51fe-ebbc-4583-9374-67c0f69b921a:GLOBAL",
    "name": "uunet",
    "category_id": "urn:vmomi:InventoryServiceCategory:1496ee2c-1488-4063-94ff-a7f343d8b150:GLOBAL"
  },
  {
    "id": "urn:vmomi:InventoryServiceTag:87089ea6-2f35-456f-b18c-89bad5bbc9a3:GLOBAL",
    "name": "uunet-1c",
    "category_id": "urn:vmomi:InventoryServiceCategory:85c9b153-4f94-407e-9fd9-dbdc4b938e09:GLOBAL"
  },
  {
    "id": "urn:vmomi:InventoryServiceTag:4193c978-afd0-47c2-b42f-5cae666fce52:GLOBAL",
    "name": "uunet-1a",
    "category_id": "urn:vmomi:InventoryServiceCategory:85c9b153-4f94-407e-9fd9-dbdc4b938e09:GLOBAL"
  },
  {
    "id": "urn:vmomi:InventoryServiceTag:8357137f-666a-4dfb-91b0-ab358e11308f:GLOBAL",
    "name": "uunet-1b",
    "category_id": "urn:vmomi:InventoryServiceCategory:85c9b153-4f94-407e-9fd9-dbdc4b938e09:GLOBAL"
  }
]

$ GOVC_LOGIN_TOKEN="$token" govc tags.category.ls -u vcdo.aptproduction.com -cert keys/public2.crt -key keys/private2.key -jso
n | jq .
[
  {
    "id": "urn:vmomi:InventoryServiceCategory:1496ee2c-1488-4063-94ff-a7f343d8b150:GLOBAL",
    "name": "k8s-region",
    "cardinality": "MULTIPLE"
  },
  {
    "id": "urn:vmomi:InventoryServiceCategory:85c9b153-4f94-407e-9fd9-dbdc4b938e09:GLOBAL",
    "name": "k8s-zone",
    "cardinality": "MULTIPLE"
  }
]
```

So that would imply the solution user, role, and permissions are set up correctly? Would you expect the `tags.attached.ls` to also work?  I seem to be getting a 404 when using with the `-r` flag - https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#tagsattachedls

```
$ GOVC_LOGIN_TOKEN="$token" govc tags.attached.ls -u vcdo.aptproduction.com -cert keys/public2.crt -key keys/private2.key -r=true /uunet/host/devops
govc: GET https://vcdo.aptproduction.com/rest/com/vmware/cis/tagging/tag/id:k8s-region: 404 Not Found
```

Does seem to work when specifying  a tag name: 
```
$ GOVC_LOGIN_TOKEN="$token" govc tags.attached.ls -u vcdo.aptproduction.com -cert keys/public2.crt -key keys/private2.key uunet-1a
HostSystem:host-65
```

Are there any other govc commands I should check / verify?

**Comment by dougm** [comment]
@rhockenbury yes, the solution user setup looks right.  Not sure what the issue is with `-r`.  Can you share your vCenter build number (`govc about`)?  I'll try to reproduce the issue.

**Comment by rhockenbury** [comment]
$ govc about -u vcdo
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      6.7.0
Build:        13007421
OS type:      linux-x64
API type:     VirtualCenter
API version:  6.7.2
Product ID:   vpx
UUID:         f3a891ef-55ed-4737-9cc4-acf69a346b75

**Comment by dougm** [comment]
@rhockenbury I can reproduce this, but don't know what the issue is yet.  The version of Go and vSphere have changed since #75742 , but if it was one of those was the cause, I'd expect SAML auth to fail with the govc tags commands too.  All I have to go on for now is the vCenter log message below.  I'll update when I have more info.

```console
% tail /var/log/vmware/vapi/endpoint/endpoint.log
...
2019-05-13T19:43:20.835Z | INFO  | jetty-default-32          | SamlSecurityContextParser      | Could not build security context
com.vmware.vim.sso.http.AuthException: The message signature is not correct!
...
```

**Comment by dougm** [comment]
I have it working with the change below, but need to figure out a few things first:

* Why this is the case when run inside kubelet and not govc (note that the port change to 443 breaks govc)

* A good way to determine which port to use (depends on the answer to the above)

* If this is behavior is specific to 6.7U2 or something triggered by a change in K8s

I suppose a quick fix would change `SignRequest` to try port 443 if 80 fails, but would prefer to avoid that as the failure generates stack traces in the vapi/endpoint.log

```diff
modified   vendor/github.com/vmware/govmomi/sts/signer.go
@@ -266,7 +266,7 @@ func (s *Signer) SignRequest(req *http.Request) error {
 		bhash := sha256.New().Sum(body)
 
 		// Port in the signature must be that of the reverse proxy port, vCenter's default is port 80
-		port := "80" // TODO: get from lookup service
+		port := "443" // TODO: get from lookup service
 		var buf bytes.Buffer
 		msg := []string{
 			nonce,
```

**Comment by dougm** [comment]
This is obvious in retrospect, but the issue is the message signature needs to use the same port as the original request URL.  However, in the govc case there was no port set in the request URL.  The client defaults to port `443` when connecting (based on the scheme), but does not include any port with the `Host` header.  In the case, the default is `80` on the server side.  This can be reproduced with `govc tags.ls` if `GOVC_URL` includes the port `hostname:443`, rather than just `hostname` as we were using.
The VCP tests that use token auth for tags lookup just don't validate the signature, so this wasn't a change related to 6.7U2.  I'll open a K8s PR to pull in the fix: https://github.com/vmware/govmomi/pull/1461

**Comment by dougm** [comment]
Updating k/vendor to govmomi master adds almost 6K lines for a 3 line fix.  I may just create a govmomi branch off of v0.20 to reduce churn in the K8s release branches for this fix, may have to wait until tomorrow.

**Comment by rhockenbury** [comment]
Really appreciate the insight into this issue.  Can confirm that specifying the port (443) in the GOVC_URL reproduces the issue.  Thank you!

**Comment by rhockenbury** [comment]
Unfortunately, I'm seeing the same issue with v1.14.3:
```
E0606 15:37:44.878764    2808 vsphere.go:1538] Get zone for node ul-win-node-3zf: POST https://vcdo:443/rest/com/vmware/cis/session: 401 Unauthorized
E0606 15:37:44.879078    2808 kubelet_node_status.go:68] Unable to construct v1.Node object for kubelet: failed to get zone from cloud provider: POST https://vcdo:443/rest/com/vmware/cis/session: 401 Unauthorized
```

cloud_config
```
user = "<cert>"
password = "<key>"
port = 443
insecure-flag = 1

datacenters = "uunet"


[VirtualCenter "vcdo"]


[Workspace]
server = "vcdo"
datacenter = "uunet"
folder = "do-k8s-test"
default-datastore = "zonestorage1"
resourcepool-path = "devops/do-k8s-test"


[Disk]
scsicontrollertype = pvscsi

[Network]
public-network = do-k8s-portgroup

[Labels]
zone = k8s-zone
region = k8s-region
```

Works fine when I use the username and password of a vsphere admin, but using cert and key still has authentication issues.

**Comment by dougm** [comment]
@rhockenbury any related errors in vCenter's /var/log/vmware/vapi/endpoint/endpoint.log ?

**Comment by rhockenbury** [comment]
Seeing a lot of this exception:

```
2019-06-07T17:52:41.459Z | ERROR | sso5                      | SoapBindingImpl                | SOAP fault
com.sun.xml.internal.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: Cannot continue delegation chain Please see the server log to find more detail regarding exact cause of the failure.
	at com.sun.xml.internal.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:178)
	at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:116)
	at com.sun.xml.internal.ws.client.dispatch.DispatchImpl.doInvoke(DispatchImpl.java:259)
	at com.sun.xml.internal.ws.client.dispatch.DispatchImpl.invoke(DispatchImpl.java:289)
	at com.vmware.vim.sso.client.impl.SoapBindingImpl.sendMessage(SoapBindingImpl.java:161)
	at com.vmware.vim.sso.client.impl.SoapBindingImpl.sendMessage(SoapBindingImpl.java:114)
	at com.vmware.vim.sso.client.impl.SecurityTokenServiceImpl$RequestResponseProcessor.sendRequest(SecurityTokenServiceImpl.java:927)
	at com.vmware.vim.sso.client.impl.SecurityTokenServiceImpl$RequestResponseProcessor.executeRoundtrip(SecurityTokenServiceImpl.java:856)
	at com.vmware.vim.sso.client.impl.SecurityTokenServiceImpl.acquireTokenByCertificate(SecurityTokenServiceImpl.java:477)
	at com.vmware.vapi.endpoint.sso.context.StsFacadeImpl.acquireActAsToken(StsFacadeImpl.java:37)
	at com.vmware.vapi.endpoint.sso.context.SecurityContextUtil.acquireAndRenewActAsToken(SecurityContextUtil.java:303)
	at com.vmware.vapi.endpoint.sso.context.SecurityContextUtil.access$000(SecurityContextUtil.java:38)
	at com.vmware.vapi.endpoint.sso.context.SecurityContextUtil$2.run(SecurityContextUtil.java:170)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-06-07T17:52:41.459Z | WARN  | sso5                      | SecurityContextUtil            | Failed to acquire Act As token.
com.vmware.vapi.endpoint.sso.StsException: com.vmware.vim.sso.client.exception.InvalidTokenRequestException: Request is invalid: ns0:InvalidRequest: Cannot continue delegation chain
	at com.vmware.vapi.endpoint.sso.context.StsFacadeImpl.acquireActAsToken(StsFacadeImpl.java:73)
	at com.vmware.vapi.endpoint.sso.context.SecurityContextUtil.acquireAndRenewActAsToken(SecurityContextUtil.java:303)
	at com.vmware.vapi.endpoint.sso.context.SecurityContextUtil.access$000(SecurityContextUtil.java:38)
	at com.vmware.vapi.endpoint.sso.context.SecurityContextUtil$2.run(SecurityContextUtil.java:170)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.vmware.vim.sso.client.exception.InvalidTokenRequestException: Request is invalid: ns0:InvalidRequest: Cannot continue delegation chain
	at com.vmware.vim.sso.client.impl.SecurityTokenServiceImpl$RequestResponseProcessor.handleFaultCondition(SecurityTokenServiceImpl.java:1077)
	at com.vmware.vim.sso.client.impl.SecurityTokenServiceImpl$RequestResponseProcessor.sendRequest(SecurityTokenServiceImpl.java:932)
	at com.vmware.vim.sso.client.impl.SecurityTokenServiceImpl$RequestResponseProcessor.executeRoundtrip(SecurityTokenServiceImpl.java:856)
	at com.vmware.vim.sso.client.impl.SecurityTokenServiceImpl.acquireTokenByCertificate(SecurityTokenServiceImpl.java:477)
	at com.vmware.vapi.endpoint.sso.context.StsFacadeImpl.acquireActAsToken(StsFacadeImpl.java:37)
	... 6 more
2019-06-07T17:52:41.459Z | INFO  | sso5                      | BaseSessionImpl                | Cannot authenticate user login request com.vmware.vapi.cis.authn.SecurityContextFactory$1@1239e696 with error com.vmware.vapi.endpoint.sso.StsException: com.vmware.vim.sso.client.exception.InvalidTokenRequestException: Request is invalid: ns0:InvalidRequest: Cannot continue delegation chain.
```

**Comment by dims** [comment]
whoa! that stack trace is like punch in the gut (brings back memories!) @dougm :)

**Comment by dougm** [comment]
@dims indeed!!

@rhockenbury apologies, I must have had the change for PR #78876 locally, but failed to include it as I had focused on the signature issue and updating vendor/
