### ISSUE TITLE
Flacky full go build of k8s on Ubuntu 18.04

### ISSUE THREAD

**Issue by vkatsikaros** [kubernetes/kubernetes#77499]
**What happened**:

I was following the [main "To start developing Kubernetes" instructions](https://github.com/kubernetes/kubernetes#you-have-a-working-go-environment). I am a go noob so I apologize if I have done something stupid and cause noise.

Consecutive runs of `make` succeed only some times. I have examples of successful and unsuccessful builds. #74876 reports one of the unsuccessful build errors, but the machine I use already has 8G of memory.
```
root@k8t:~/go/src/k8s.io/kubernetes# make
+++ [0506 09:35:13] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/cloud-controller-manager
    cmd/kubelet
    cmd/kubeadm
    cmd/hyperkube
    cmd/kube-scheduler
    vendor/k8s.io/apiextensions-apiserver
    cluster/gce/gci/mounter
    cmd/kubectl
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genyaml
    cmd/genswaggertypedocs
    cmd/linkcheck
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
    cmd/kubemark
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e_node/e2e_node.test
root@k8t:~/go/src/k8s.io/kubernetes# echo $?
0
```

```
root@k8t:~/go/src/k8s.io/kubernetes# make                                                    
+++ [0506 09:04:07] Building go targets for linux/amd64:    
    cmd/kube-proxy                                                                                
    cmd/kube-apiserver                                                                        
    cmd/kube-controller-manager                                                                  
    cmd/cloud-controller-manager                             
    cmd/kubelet                                                                                   
    cmd/kubeadm                                                                                            
    cmd/hyperkube                                                                                               
    cmd/kube-scheduler                                       
    vendor/k8s.io/apiextensions-apiserver                                                                      
    cluster/gce/gci/mounter                                                                 
    cmd/kubectl                                                                                              
    cmd/gendocs                                                                                     
    cmd/genkubedocs                                                                                          
    cmd/genman                                      
    cmd/genyaml                                                                                              
    cmd/genswaggertypedocs                                                                                 
    cmd/linkcheck                                                                                            
    vendor/github.com/onsi/ginkgo/ginkgo                 
    test/e2e/e2e.test                                                                                               
    cmd/kubemark
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e_node/e2e_node.test
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
!!! [0506 09:06:40] Call tree:
!!! [0506 09:06:40]  1: /root/go/src/k8s.io/kubernetes/hack/lib/golang.sh:705 kube::golang::build_some_binaries(...)
!!! [0506 09:06:40]  2: /root/go/src/k8s.io/kubernetes/hack/lib/golang.sh:844 kube::golang::build_binaries_for_platform(...)
!!! [0506 09:06:40]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0506 09:06:40] Call tree:
!!! [0506 09:06:40]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0506 09:06:40] Call tree:
!!! [0506 09:06:40]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
Makefile:92: recipe for target 'all' failed
make: *** [all] Error 1
```

```
root@k8t:~/go/src/k8s.io/kubernetes# make                                                                                                                                            [197/685]
+++ [0506 09:16:39] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/cloud-controller-manager
    cmd/kubelet
    cmd/kubeadm
    cmd/hyperkube
    cmd/kube-scheduler
    vendor/k8s.io/apiextensions-apiserver
    cluster/gce/gci/mounter
    cmd/kubectl
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genyaml
    cmd/genswaggertypedocs
    cmd/linkcheck
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
    cmd/kubemark
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e_node/e2e_node.test
# k8s.io/kubernetes/cmd/hyperkube
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x6785eb, 0x16)
        /usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sysMap(0xc08c000000, 0x4000000, 0x85a7b8)
        /usr/local/go/src/runtime/mem_linux.go:170 +0xc7
runtime.(*mheap).sysAlloc(0x842d00, 0x2680000, 0x842d10, 0x1340)
        /usr/local/go/src/runtime/malloc.go:633 +0x1cd
runtime.(*mheap).grow(0x842d00, 0x1340, 0x0)
        /usr/local/go/src/runtime/mheap.go:1232 +0x42
runtime.(*mheap).allocSpanLocked(0x842d00, 0x1340, 0x85a7c8, 0x7f93579bb370)
        /usr/local/go/src/runtime/mheap.go:1150 +0x3a7
runtime.(*mheap).alloc_m(0x842d00, 0x1340, 0x7f9350650100, 0x7f935065bbc8)
        /usr/local/go/src/runtime/mheap.go:977 +0xc2
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:1048 +0x4c
runtime.(*mheap).alloc(0x842d00, 0x1340, 0xc000010100, 0x7f935065bb38)                                                                                                             [155/685]
        /usr/local/go/src/runtime/mheap.go:1047 +0x8a
runtime.largeAlloc(0x2680000, 0x450001, 0x7f935065bb38)
        /usr/local/go/src/runtime/malloc.go:1055 +0x99
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:950 +0x46
runtime.systemstack(0x0)
        /usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1153

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc000876eb8 sp=0xc000876eb0 pc=0x4553d0
runtime.mallocgc(0x2680000, 0x65cde0, 0x83f801, 0x4028748b0)
        /usr/local/go/src/runtime/malloc.go:949 +0x872 fp=0xc000876f58 sp=0xc000876eb8 pc=0x40bb92
runtime.growslice(0x65cde0, 0xc0898a2000, 0xa4400, 0xa4400, 0xa4401, 0x83f8ba, 0x0, 0x2874828)
        /usr/local/go/src/runtime/slice.go:181 +0x1e6 fp=0xc000876fc0 sp=0xc000876f58 pc=0x441076
cmd/link/internal/sym.(*Symbol).AddRel(...)
        /usr/local/go/src/cmd/link/internal/sym/symbol.go:273
cmd/link/internal/sym.(*Symbol).SetAddrPlus(0xc070715760, 0x82ed20, 0x1dae50, 0xc021c72b30, 0x0, 0x2874830)
        /usr/local/go/src/cmd/link/internal/sym/symbol.go:226 +0x196 fp=0xc000877010 sp=0xc000876fc0 pc=0x4ed7a6
cmd/link/internal/sym.(*Symbol).SetAddr(...)
        /usr/local/go/src/cmd/link/internal/sym/symbol.go:236
cmd/link/internal/ld.(*Link).pclntab(0xc000700000)
        /usr/local/go/src/cmd/link/internal/ld/pcln.go:286 +0x617 fp=0xc0008773a0 sp=0xc000877010 pc=0x59ce67
cmd/link/internal/ld.Main(0x82ed20, 0x10, 0x20, 0x1, 0x7, 0x10, 0x67a410, 0x1b, 0x676fe9, 0x14, ...)
        /usr/local/go/src/cmd/link/internal/ld/main.go:235 +0xc61 fp=0xc000877510 sp=0xc0008773a0 pc=0x59a6f1
main.main()
        /usr/local/go/src/cmd/link/main.go:65 +0x1d0 fp=0xc000877f98 sp=0xc000877510 pc=0x5fd6b0
runtime.main()
        /usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc000877fe0 sp=0xc000877f98 pc=0x42ce0c
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000877fe8 sp=0xc000877fe0 pc=0x457321
!!! [0506 09:18:50] Call tree:
!!! [0506 09:18:50]  1: /root/go/src/k8s.io/kubernetes/hack/lib/golang.sh:705 kube::golang::build_some_binaries(...)
!!! [0506 09:18:50]  2: /root/go/src/k8s.io/kubernetes/hack/lib/golang.sh:844 kube::golang::build_binaries_for_platform(...)
!!! [0506 09:18:50]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0506 09:18:50] Call tree:
!!! [0506 09:18:50]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0506 09:18:50] Call tree:
!!! [0506 09:18:50]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
Makefile:92: recipe for target 'all' failed
make: *** [all] Error 1
root@k8t:~/go/src/k8s.io/kubernetes# echo $?
2
```

```
root@k8t:~/go/src/k8s.io/kubernetes# make                                                                                                                                            [109/685]
+++ [0506 09:19:27] Building go targets for linux/amd64:                                                                                                                                      
    cmd/kube-proxy                                                                                                                                                                            
    cmd/kube-apiserver                                                                                                                                                                        
    cmd/kube-controller-manager                                                                                                                                                               
    cmd/cloud-controller-manager                                                                                                                                                              
    cmd/kubelet                                                                                                                                                                               
    cmd/kubeadm                                                                                                                                                                               
    cmd/hyperkube                                                                                                                                                                             
    cmd/kube-scheduler
    vendor/k8s.io/apiextensions-apiserver
    cluster/gce/gci/mounter
    cmd/kubectl
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genyaml
    cmd/genswaggertypedocs
    cmd/linkcheck
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
    cmd/kubemark
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e_node/e2e_node.test
# k8s.io/kubernetes/cmd/kubelet
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory

!!! [0506 09:21:33] Call tree:
!!! [0506 09:21:33]  1: /root/go/src/k8s.io/kubernetes/hack/lib/golang.sh:705 kube::golang::build_some_binaries(...)
!!! [0506 09:21:33]  2: /root/go/src/k8s.io/kubernetes/hack/lib/golang.sh:844 kube::golang::build_binaries_for_platform(...)
!!! [0506 09:21:33]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0506 09:21:33] Call tree:
!!! [0506 09:21:33]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0506 09:21:33] Call tree:
!!! [0506 09:21:33]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
Makefile:92: recipe for target 'all' failed
make: *** [all] Error 1
root@k8t:~/go/src/k8s.io/kubernetes# echo $?
2
```

**What you expected to happen**:
I'd expect to have only successful builds (`make`) 

**How to reproduce it (as minimally and precisely as possible)**:
```
curl -JO https://dl.google.com/go/go1.12.4.linux-amd64.tar.gz
sha256sum ~/go1.12.4.linux-amd64.tar.gz 
# d7d1f1f88ddfe55840712dc1747f37a790cbcaa448f6c9cf51bbe10aa65442f5  /root/go1.12.4.linux-amd64.tar.gz
tar -C /usr/local -xzf go1.12.4.linux-amd64.tar.gz 
echo 'export PATH=$PATH:/usr/local/go/bin' >> .profile 
apt-get update
apt-get install build-essential 
go get -d k8s.io/kubernetes
cd ~/go/src/k8s.io/kubernetes
make # some fail some succeed
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
commit df3e59fedc89da34ba9eb75e12d03a9bf4def2dd (HEAD -> master, origin/master, origin/HEAD)
Merge: 43ce2f17cf 5af6442cc5
Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
Date:   Sun May 5 21:09:36 2019 -0700

    Merge pull request #77356 from johnbelamaric/add-to-net-approvers
    
    Add johnbelamaric to sig-network-{reviewers,approvers}

root@k8t:~/go/src/k8s.io/kubernetes# git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```
- Cloud provider or hardware configuration:
Digitalocean, machine `8 GB Memory / 160 GB Disk` region `AMS3` Base image `Ubuntu 18.04 x64`
- OS (e.g: `cat /etc/os-release`):
```
cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```
Linux k8t 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
```
# dpkg --list | grep build-esse
ii  build-essential                 12.4ubuntu1                                 amd64        Informational list of build-essential packages

# gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
```

- Network plugin and version (if this is a network-related bug):
No
- Others:
No

**Comment by loqutus** [comment]
you probably need more memory, even on 16gb machine i have to add some swap:)

**Comment by vkatsikaros** [comment]
@loqutus thanks for the input. Indeed with 16G it works as expected.
