### ISSUE TITLE
Kubelet crashing with SIGSEGV under load

### ISSUE THREAD

**Issue by efilipov** [kubernetes/kubernetes#77655]
**What happened**:
Kubelet had crashed one one of the heavily loaded instances in AWS EC2 cluster (r4.8xlarge). 

Logs show the following traceback:
```
May  9 00:12:17 ip-10-117-0-156.eu-west-1.compute.internal kubelet: panic: runtime error: invalid memory address or nil pointer dereference
May  9 00:12:17 ip-10-117-0-156.eu-west-1.compute.internal kubelet: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x30de866]
May  9 00:12:17 ip-10-117-0-156.eu-west-1.compute.internal kubelet: goroutine 249849634 [running]:
May  9 00:12:17 ip-10-117-0-156.eu-west-1.compute.internal kubelet: k8s.io/kubernetes/pkg/kubelet/stats.cadvisorInfoToCPUandMemoryStats(0xc47b45ea00, 0xc44dd4b800, 0x0)
May  9 00:12:17 ip-10-117-0-156.eu-west-1.compute.internal kubelet: /workspace/anago-v1.12.7-beta.0.58+6f482974b76db3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/stats/helper.go:56 +0xa6
May  9 00:12:17 ip-10-117-0-156.eu-west-1.compute.internal kubelet: k8s.io/kubernetes/pkg/kubelet/stats.cadvisorInfoToContainerStats(0xc42b5ba0c0, 0x7, 0xc47b45ea00, 0xc4516d5c80, 0xc4516d5d80, 0xc44dd4b780)
May  9 00:12:17 ip-10-117-0-156.eu-west-1.compute.internal kubelet: /workspace/anago-v1.12.7-beta.0.58+6f482974b76db3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/stats/helper.go:87 +0x100
May  9 00:12:17 ip-10-117-0-156.eu-west-1.compute.internal kubelet: k8s.io/kubernetes/pkg/kubelet/stats.(*cadvisorStatsProvider).ListPodStats(0xc420f15f80, 0x0, 0x13b7169df9a3, 0x0, 0x0, 0xc454a62448)
May  9 00:12:17 ip-10-117-0-156.eu-west-1.compute.internal kubelet: /workspace/anago-v1.12.7-beta.0.58+6f482974b76db3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/stats/cadvisor_stats_provider.go:119 +0x810
May  9 00:12:17 ip-10-117-0-156.eu-west-1.compute.internal kubelet: k8s.io/kubernetes/pkg/kubelet/metrics/collectors.(*volumeStatsCollector).Collect(0xc421446600, 0xc45b299620)
May  9 00:12:17 ip-10-117-0-156.eu-west-1.compute.internal kubelet: /workspace/anago-v1.12.7-beta.0.58+6f482974b76db3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/metrics/collectors/volume_stats.go:82 +0x4b
May  9 00:12:17 ip-10-117-0-156.eu-west-1.compute.internal kubelet: k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc43f00e770, 0xc45b299620, 0x43e9980, 0xc421446600)
May  9 00:12:17 ip-10-117-0-156.eu-west-1.compute.internal kubelet: /workspace/anago-v1.12.7-beta.0.58+6f482974b76db3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus/registry.go:382 +0x61
May  9 00:12:17 ip-10-117-0-156.eu-west-1.compute.internal kubelet: created by k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
May  9 00:12:17 ip-10-117-0-156.eu-west-1.compute.internal kubelet: /workspace/anago-v1.12.7-beta.0.58+6f482974b76db3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus/registry.go:380 +0x302
```

**What you expected to happen**:
Kubelet not to crash.

**How to reproduce it (as minimally and precisely as possible)**:
Reproduction unknown at this point.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): Kubelet v.1.12.7; Control plane v.1.12.8
- Cloud provider or hardware configuration: AWS/EC2
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.6.1810 (Core)
- Kernel (e.g. `uname -a`): 5.0.4-1.el7.elrepo.x86_64 (non-standard kernel)
- Install tools: Custom-made

**Comment by yastij** [comment]
This seems like we don't check if Memory is not `nil` on latest stats

**Comment by mattjmcnaughton** [comment]
> This seems like we don't check if Memory is not `nil` on latest stats

Nice debugging :)
