### ISSUE TITLE
Running kubelet.exe v1.15.0-rc1 w/o parameters produces error invalid configuration CgroupsPerQOS

### ISSUE THREAD

**Issue by mbergal** [kubernetes/kubernetes#78925]
/sig windows

> kubelet.exe

```
.\kubelet : F0611 19:57:18.295485    5556 server.go:215] [invalid configuration: CgroupsPerQOS (--cgroups-per-qos) true is not supported on 
Windows, invalid configuration: EnforceNodeAllocatable (--enforce-node-allocatable) [pods] is not supported on Windows]
At line:1 char:1
+ .\kubelet >\\otterbank.eyediagnosis.local\ottershare\k8s\error 2>&1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (F0611 19:57:18....ted on Windows]:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog.stacks(0x72dcc01, 0x3, 0xc0000e29a0, 0xf8)
	/workspace/anago-v1.15.0-beta.2.65+02dc3d713dd7f9/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.g
o:900 +0xb8
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).output(0x72dcca0, 0xc000000003, 0xc0002c00e0, 0x719f086, 0x9, 0xd7, 0x0)
	/workspace/anago-v1.15.0-beta.2.65+02dc3d713dd7f9/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.g
o:815 +0xed
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).printDepth(0x72dcca0, 0x3, 0x1, 0xc000657cb8, 0x1, 0x1)
	/workspace/anago-v1.15.0-beta.2.65+02dc3d713dd7f9/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.g
o:718 +0x132
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).print(...)
	/workspace/anago-v1.15.0-beta.2.65+02dc3d713dd7f9/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.g
o:709
k8s.io/kubernetes/vendor/k8s.io/klog.Fatal(...)
	/workspace/anago-v1.15.0-beta.2.65+02dc3d713dd7f9/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.g
o:1289
k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0xc000429180, 0xc000078190, 0x0, 0x0)
	/workspace/anago-v1.15.0-beta.2.65+02dc3d713dd7f9/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go
:215 +0x2fe
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000429180, 0xc000078190, 0x0, 0x0, 0xc000429180, 0xc000078190)
	/workspace/anago-v1.15.0-beta.2.65+02dc3d713dd7f9/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/c
obra/command.go:760 +0x2b5
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000429180, 0x41a1d08, 0x72dc8e0, 0x402d29a)
	/workspace/anago-v1.15.0-beta.2.65+02dc3d713dd7f9/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/c
obra/command.go:846 +0x2f3
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/anago-v1.15.0-beta.2.65+02dc3d713dd7f9/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/c
obra/command.go:794
main.main()
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/kubelet.go:42 +0xd4

goroutine 19 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x72dcca0)
	/workspace/anago-v1.15.0-beta.2.65+02dc3d713dd7f9/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.g
o:1035 +0x92
created by k8s.io/kubernetes/vendor/k8s.io/klog.init.0
	/workspace/anago-v1.15.0-beta.2.65+02dc3d713dd7f9/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.g
o:404 +0x73

goroutine 53 [syscall]:
os/signal.signal_recv(0x45efe6)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa3
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x29
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x48

goroutine 66 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x41a1e00, 0x12a05f200, 0x0, 0xc00014e301, 0xc000076120)
	/workspace/anago-v1.15.0-beta.2.65+02dc3d713dd7f9/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachiner
y/pkg/util/wait/wait.go:164 +0x188
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/anago-v1.15.0-beta.2.65+02dc3d713dd7f9/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachiner
y/pkg/util/wait/wait.go:88
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x41a1e00, 0x12a05f200)
	/workspace/anago-v1.15.0-beta.2.65+02dc3d713dd7f9/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachiner
y/pkg/util/wait/wait.go:79 +0x57
created by k8s.io/kubernetes/vendor/k8s.io/component-base/logs.InitLogs
	/workspace/anago-v1.15.0-beta.2.65+02dc3d713dd7f9/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kube
rnetes/vendor/k8s.io/component-base/logs/logs.go:58 +0x91

```

**Comment by RakibFiha** [comment]
I am facing similar issues, kubelet will not start. I tried reinstalling kubernetes docker kubeadm kubelet
```bash
Nov 24 16:47:37 worker-d0-0b kubelet[8804]: main.main()
Nov 24 16:47:37 worker-d0-0b kubelet[8804]:         _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/kubelet.go:41 +0xcc
Nov 24 16:47:37 worker-d0-0b kubelet[8804]: goroutine 21 [chan receive]:
Nov 24 16:47:37 worker-d0-0b kubelet[8804]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x6509ac0)
Nov 24 16:47:37 worker-d0-0b kubelet[8804]:         /workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1131 +0x70
Nov 24 16:47:37 worker-d0-0b kubelet[8804]: created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
Nov 24 16:47:37 worker-d0-0b kubelet[8804]:         /workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:416 +0x118
Nov 24 16:47:37 worker-d0-0b kubelet[8804]: goroutine 83 [select]:
Nov 24 16:47:37 worker-d0-0b kubelet[8804]: k8s.io/kubernetes/vendor/go.opencensus.io/stats/view.(*worker).start(0x40001157c0)
Nov 24 16:47:37 worker-d0-0b kubelet[8804]:         /workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/go.opencensus.io/stats/view/worker.go:154 +0xb4
Nov 24 16:47:37 worker-d0-0b kubelet[8804]: created by k8s.io/kubernetes/vendor/go.opencensus.io/stats/view.init.0
Nov 24 16:47:37 worker-d0-0b kubelet[8804]:         /workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/go.opencensus.io/stats/view/worker.go:32 +0x5c
Nov 24 16:47:37 worker-d0-0b kubelet[8804]: goroutine 90 [select]:
Nov 24 16:47:37 worker-d0-0b kubelet[8804]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x3f87c48, 0x43dfb00, 0x4000386cc0, 0x842001, 0x40001160c0)
Nov 24 16:47:37 worker-d0-0b kubelet[8804]:         /workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0xec
Nov 24 16:47:37 worker-d0-0b kubelet[8804]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x3f87c48, 0x12a05f200, 0x0, 0x46a401, 0x40001160c0)
Nov 24 16:47:37 worker-d0-0b kubelet[8804]:         /workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x88
Nov 24 16:47:37 worker-d0-0b kubelet[8804]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
Nov 24 16:47:37 worker-d0-0b kubelet[8804]:         /workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
Nov 24 16:47:37 worker-d0-0b kubelet[8804]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x3f87c48, 0x12a05f200)
Nov 24 16:47:37 worker-d0-0b kubelet[8804]:         /workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81 +0x50
Nov 24 16:47:37 worker-d0-0b kubelet[8804]: created by k8s.io/kubernetes/vendor/k8s.io/component-base/logs.InitLogs
Nov 24 16:47:37 worker-d0-0b kubelet[8804]:         /workspace/anago-v1.19.4-rc.0.51+5f1e5cafd33a88/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/logs/logs.go:58 +0x8c
Nov 24 16:47:37 worker-d0-0b systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Nov 24 16:47:37 worker-d0-0b systemd[1]: kubelet.service: Failed with result 'exit-code'.
```
