### ISSUE TITLE
Fluentd ElasticSearch instance reporting 503 on health status

### ISSUE THREAD

**Issue by nabheet** [kubernetes/kubernetes#80549]
**What happened**:
fluentd-elasticsearch health status is reporting 503:
```
$ curl http://elasticsearch-logging.kube-system:9200/_cluster/health
{"error":{"root_cause":[{"type":"master_not_discovered_exception","reason":null}],"type":"master_not_discovered_exception","reason":null},"status":503}
```
```
[2019-07-25T00:22:57,242][WARN ][r.suppressed             ] [elasticsearch-logging-0] path: /_bulk, params: {}
org.elasticsearch.cluster.block.ClusterBlockException: blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];[SERVICE_UNAVAILABLE/2/no master];
        at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedException(ClusterBlocks.java:191) ~[elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.action.bulk.TransportBulkAction$BulkOperation.handleBlockExceptions(TransportBulkAction.java:472) [elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.action.bulk.TransportBulkAction$BulkOperation.doRun(TransportBulkAction.java:353) [elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.action.bulk.TransportBulkAction$BulkOperation$2.onTimeout(TransportBulkAction.java:506) [elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:322) [elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:249) [elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:555) [elasticsearch-7.1.1.jar:7.1.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [elasticsearch-7.1.1.jar:7.1.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:835) [?:?]
        Suppressed: org.elasticsearch.discovery.MasterNotDiscoveredException
                at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:259) ~[elasticsearch-7.1.1.jar:7.1.1]
                at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:322) [elasticsearch-7.1.1.jar:7.1.1]
                at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:249) [elasticsearch-7.1.1.jar:7.1.1]
                at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:555) [elasticsearch-7.1.1.jar:7.1.1]
                at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [elasticsearch-7.1.1.jar:7.1.1]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
                at java.lang.Thread.run(Thread.java:835) [?:?]
[2019-07-25T00:22:57,449][WARN ][o.e.c.c.ClusterFormationFailureHelper] [elasticsearch-logging-0] master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and [cluster.initial_master_nodes] is empty on this node: have discovered [{elasticsearch-logging-1}{p2vuutfzQXqJwB7iADo-kw}{vTbCWeyCQSSeBbNDJI59lA}{192.168.133.10}{192.168.133.10:9300}]; discovery will continue using [192.168.133.10:9300] from hosts providers and [{elasticsearch-logging-0}{ZDFC_MimRsu4svcRIzjhKA}{6FzCzWA1R36Jb77vOnAcZg}{192.168.134.14}{192.168.134.14:9300}] from last-known cluster state; node term 0, last-accepted version 0 in term 0
```
**What you expected to happen**:
It should report ES cluster health with a 200 status.

**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply -f https://raw.githubusercontent.com/kubernetes/kubernetes/master/cluster/addons/fluentd-elasticsearch/es-statefulset.yaml

**Anything else we need to know?**:
I think this error might be due to missing `cluster.initial_master_nodes` defintion in elasticsearch.yml. But I am not sure as it correctly discovers the second node in the cluster.
```
[2019-07-25T00:17:47,400][WARN ][o.e.c.c.ClusterFormationFailureHelper] [elasticsearch-logging-0] master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and [cluster.initial_master_nodes] is empty on this node: have discovered []; discovery will continue using [192.168.133.10:9300] from hosts providers and [{elasticsearch-logging-0}{ZDFC_MimRsu4svcRIzjhKA}{6FzCzWA1R36Jb77vOnAcZg}{192.168.134.14}{192.168.134.14:9300}] from last-known cluster state; node term 0, last-accepted version 0 in term 0
[2019-07-25T00:17:57,402][WARN ][o.e.c.c.ClusterFormationFailureHelper] [elasticsearch-logging-0] master not discovered yet, this node has not previously joined a bootstrapped (v7+) cluster, and [cluster.initial_master_nodes] is empty on this node: have discovered [{elasticsearch-logging-1}{p2vuutfzQXqJwB7iADo-kw}{vTbCWeyCQSSeBbNDJI59lA}{192.168.133.10}{192.168.133.10:9300}]; discovery will continue using [192.168.133.10:9300] from hosts providers and [{elasticsearch-logging-0}{ZDFC_MimRsu4svcRIzjhKA}{6FzCzWA1R36Jb77vOnAcZg}{192.168.134.14}{192.168.134.14:9300}] from last-known cluster state; node term 0, last-accepted version 0 in term 0
```
```
pod/elasticsearch-logging-0                  1/1     Running   0          10m   192.168.134.14   NODENAME1   <none>           <none>
pod/elasticsearch-logging-1                  1/1     Running   0          10m   192.168.133.10   NODENAME2   <none>           <none>
```
I think this might be related to [#80530](https://github.com/kubernetes/kubernetes/issues/80530). As the Kibana settings need to be changed too.

**Environment**:
- Kubernetes version (use `kubectl version`):
]# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: OpenStack
- OS (e.g: `cat /etc/os-release`): 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`): Linux INTERNAL-HOSTNAME 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by nabheet** [comment]
/sig cluster-lifecycle

I am assuming this is the correct sig based on #80530

**Comment by nabheet** [comment]
Looks like this is fixed now.
