### ISSUE TITLE
repo infra & depset iteration causing failures

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#80763]
without upgrading repo infra we get:
```
W0730 18:04:48.667] ERROR: /go/src/k8s.io/kubernetes/BUILD.bazel:39:1: in gcs_upload rule //:push-build: 
W0730 18:04:48.668] Traceback (most recent call last):
W0730 18:04:48.668]     File "/go/src/k8s.io/kubernetes/BUILD.bazel", line 39
W0730 18:04:48.668]         gcs_upload(name = 'push-build')
W0730 18:04:48.669]     File "/bazel-scratch/.cache/bazel/_bazel_prow/48d5366022b4e3197674c8d6e2bee219/external/io_k8s_repo_infra/defs/build.bzl", line 20, in _gcs_upload_impl
W0730 18:04:48.669]         for f in t.files: ...
W0730 18:04:48.669] type 'depset' is not iterable. Use the `to_list()` method to get a list. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.
```

upgrading it in https://github.com/kubernetes/kubernetes/pull/80755 to pick up using `to_list()` gives us:
```
W0730 19:40:08.800] INFO: Running command line: bazel-bin/push-build /go/src/k8s.io/kubernetes/_output/gcs-stage/v1.16.0-alpha.2.36+98993b68f56ea3 gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce/v1.16.0-alpha.2.36+98993b68f56ea3
W0730 19:40:08.808] INFO: Build completed successfully, 864 total actions
W0730 19:40:08.876] Traceback (most recent call last):
W0730 19:40:08.877]   File "../io_k8s_repo_infra/defs/gcs_uploader", line 340, in <module>
W0730 19:40:08.878]     Main()
W0730 19:40:08.878]   File "../io_k8s_repo_infra/defs/gcs_uploader", line 330, in Main
W0730 19:40:08.879]     os.execv(args[0], args)
W0730 19:40:08.879] OSError: [Errno 2] No such file or directory: '/bazel-scratch/.cache/bazel/_bazel_prow/48d5366022b4e3197674c8d6e2bee219/execroot/io_k8s_kubernetes/bazel-out/k8-fastbuild/bin/push-build.runfiles/bazel_tools/tools/python/py2wrapper.sh'
```

/cc @dims @cblecker @javier-b-perez

**Comment by BenTheElder** [comment]
and with the flags in https://github.com/kubernetes/kubernetes/pull/80762 lead to:

```
W0730 20:32:29.568] INFO: Build completed successfully, 864 total actions
W0730 20:32:29.693] Traceback (most recent call last):
W0730 20:32:29.693]   File "../io_k8s_repo_infra/defs/gcs_uploader", line 340, in <module>
W0730 20:32:29.694]     Main()
W0730 20:32:29.694]   File "../io_k8s_repo_infra/defs/gcs_uploader", line 330, in Main
W0730 20:32:29.694]     os.execv(args[0], args)
W0730 20:32:29.695] OSError: [Errno 2] No such file or directory: '/bazel-scratch/.cache/bazel/_bazel_prow/48d5366022b4e3197674c8d6e2bee219/execroot/io_k8s_kubernetes/bazel-out/k8-fastbuild/bin/push-build.runfiles/bazel_tools/tools/python/py3wrapper.sh'
```

**Comment by BenTheElder** [comment]
We've rolled back bazel to mitigate for now, but this is still something that needs solving long term.

**Comment by BenTheElder** [comment]
I don't understand where this breaks down exactly and am oversubscribed

somehow the new py2/3 stuff breaks down inside one of our rules implemented in python in repo-infra when we upgrade bazel (push-build is backed by this), otherwise I've already fixed the repo to support newer bazel, and upgraded it only to be surprised by this : |

/unassign
