### ISSUE TITLE
Kubelet stacktrace after upgrading to 1.15.1

### ISSUE THREAD

**Issue by rmb938** [kubernetes/kubernetes#80826]
**What happened**:

Upgraded Kubelet from 1.14.1 to 1.15.1 and it occasionally spits out the following stack trace

```
Jul 31 21:00:32 apslp kubelet[44765]: E0731 21:00:32.237698   44765 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Jul 31 21:00:32 apslp kubelet[44765]: goroutine 3625 [running]:
Jul 31 21:00:32 apslp kubelet[44765]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3992220, 0x775edd0)
Jul 31 21:00:32 apslp kubelet[44765]: /workspace/anago-v1.15.1-beta.0.48+4485c6f18cee9a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
Jul 31 21:00:32 apslp kubelet[44765]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Jul 31 21:00:32 apslp kubelet[44765]: /workspace/anago-v1.15.1-beta.0.48+4485c6f18cee9a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
Jul 31 21:00:32 apslp kubelet[44765]: panic(0x3992220, 0x775edd0)
Jul 31 21:00:32 apslp kubelet[44765]: /usr/local/go/src/runtime/panic.go:522 +0x1b5
Jul 31 21:00:32 apslp kubelet[44765]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).parsePodVolumeStats(0xc000ec0190, 0xc000e921dc, 0x4, 0xc0010fa840, 0x0, 0xc000e921dc, 0x4, 0x0, 0x0, 0x0, ...)
Jul 31 21:00:32 apslp kubelet[44765]: /workspace/anago-v1.15.1-beta.0.48+4485c6f18cee9a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:141 +0x73
Jul 31 21:00:32 apslp kubelet[44765]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).calcAndStoreStats(0xc000ec0190)
Jul 31 21:00:32 apslp kubelet[44765]: /workspace/anago-v1.15.1-beta.0.48+4485c6f18cee9a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:125 +0x753
Jul 31 21:00:32 apslp kubelet[44765]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).StartOnce.func1.1()
Jul 31 21:00:32 apslp kubelet[44765]: /workspace/anago-v1.15.1-beta.0.48+4485c6f18cee9a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:65 +0x2a
Jul 31 21:00:32 apslp kubelet[44765]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0017f7bf0)
Jul 31 21:00:32 apslp kubelet[44765]: /workspace/anago-v1.15.1-beta.0.48+4485c6f18cee9a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
Jul 31 21:00:32 apslp kubelet[44765]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0017f7bf0, 0xdf8475800, 0x3ff0000000000000, 0xc000c4bd01, 0xc000fb3aa0)
Jul 31 21:00:32 apslp kubelet[44765]: /workspace/anago-v1.15.1-beta.0.48+4485c6f18cee9a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
Jul 31 21:00:32 apslp kubelet[44765]: created by k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).StartOnce.func1
Jul 31 21:00:32 apslp kubelet[44765]: /workspace/anago-v1.15.1-beta.0.48+4485c6f18cee9a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:64 +0x9d
``` 

It also seems like the Ready condition on pods were never set to True even after passing health checks, a restart of the kubelet service seemed to fix that.

**What you expected to happen**:

No stack trace

**How to reproduce it (as minimally and precisely as possible)**:

Upgrade the K8s cluster from 1.14.1 to 1.15.1 using kubeadm then upgrade kubelets

**Anything else we need to know?**:

This seems to only happen on one of my nodes so far. I'm going to continue the upgrade and see if it happens on other nodes.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.1
- OS (e.g: `cat /etc/os-release`): Centos &
- Kernel (e.g. `uname -a`): `Linux apslp1360.uhc.com 5.2.5-1.el7.elrepo.x86_64`

**Comment by rmb938** [comment]
There always seems to be the same logs right before the stack trace, seems like it's related to the CSI?

```
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: I0731 21:12:14.699387   44765 clientconn.go:440] parsed scheme: ""
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: I0731 21:12:14.699413   44765 clientconn.go:440] scheme "" not registered, fallback to default scheme
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: I0731 21:12:14.699486   44765 asm_amd64.s:1337] ccResolverWrapper: sending new addresses to cc: [{/var/lib/kubelet/plugins/k8s-lvm-csi/csi.sock 0  <nil>}]
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: I0731 21:12:14.699501   44765 clientconn.go:796] ClientConn switching balancer to "pick_first"
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: I0731 21:12:14.699579   44765 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc002408780, CONNECTING
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: I0731 21:12:14.699604   44765 clientconn.go:1016] blockingPicker: the picked transport is not ready, loop back to repick
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: I0731 21:12:14.699832   44765 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc002408780, READY
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: E0731 21:12:14.738066   44765 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: goroutine 3620 [running]:
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3992220, 0x775edd0)
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: /workspace/anago-v1.15.1-beta.0.48+4485c6f18cee9a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: /workspace/anago-v1.15.1-beta.0.48+4485c6f18cee9a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: panic(0x3992220, 0x775edd0)
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: /usr/local/go/src/runtime/panic.go:522 +0x1b5
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).parsePodVolumeStats(0xc001d55900, 0xc000f778cc, 0x4, 0xc0013cc4c0, 0x0, 0xc000f778cc, 0x4, 0x0, 0x0, 0x0, ...)
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: /workspace/anago-v1.15.1-beta.0.48+4485c6f18cee9a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:141 +0x73
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).calcAndStoreStats(0xc001d55900)
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: /workspace/anago-v1.15.1-beta.0.48+4485c6f18cee9a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:125 +0x753
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).StartOnce.func1.1()
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: /workspace/anago-v1.15.1-beta.0.48+4485c6f18cee9a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:65 +0x2a
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0017f7ba0)
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: /workspace/anago-v1.15.1-beta.0.48+4485c6f18cee9a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0017f7ba0, 0xdf8475800, 0x3ff0000000000000, 0xc000c4bd01, 0xc000fb38c0)
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: /workspace/anago-v1.15.1-beta.0.48+4485c6f18cee9a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: created by k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).StartOnce.func1
Jul 31 21:12:14 apslp1360.uhc.com kubelet[44765]: /workspace/anago-v1.15.1-beta.0.48+4485c6f18cee9a/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:64 +0x9d
```

Did something change with how CSI plugins are handled in 1.15.1? This didn't happen in 1.14.1.

**Comment by rmb938** [comment]
I also see these logs every now and then.

```
Jul 31 21:16:26 apslp1360.uhc.com kubelet[44765]: I0731 21:16:26.060021   44765 operation_generator.go:193] parsed scheme: ""
Jul 31 21:16:26 apslp1360.uhc.com kubelet[44765]: I0731 21:16:26.060056   44765 operation_generator.go:193] scheme "" not registered, fallback to default scheme
Jul 31 21:16:26 apslp1360.uhc.com kubelet[44765]: I0731 21:16:26.060097   44765 asm_amd64.s:1337] ccResolverWrapper: sending new addresses to cc: [{/var/lib/kubelet/plugins/k8s-lvm-csi/csi.sock 0  <nil>}]
Jul 31 21:16:26 apslp1360.uhc.com kubelet[44765]: I0731 21:16:26.060109   44765 clientconn.go:796] ClientConn switching balancer to "pick_first"
Jul 31 21:16:26 apslp1360.uhc.com kubelet[44765]: I0731 21:16:26.060157   44765 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc001fcff30, CONNECTING
Jul 31 21:16:26 apslp1360.uhc.com kubelet[44765]: I0731 21:16:26.060331   44765 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc001fcff30, READY
Jul 31 21:16:26 apslp1360.uhc.com kubelet[44765]: E0731 21:16:26.137655   44765 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/k8s-lvm-csi/csi.sock" failed. No retries permitted until 2019-07-31 21:18:28.137634215 +0000 UTC m=+1748.282081509 (durationBeforeRetry 2m2s). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins/k8s-lvm-csi/csi.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
```

**Comment by tedyu** [comment]
Looks like this should have been fixed by commit cada0270fe195f1664bda43befc9547e454c7817:

Fix nil pointer dereference in metrics value calculator.

**Comment by rmb938** [comment]
Yup I saw that as well, it seems like it didn't make it into 1.15 though...

**Comment by rmb938** [comment]
Seems like #80642 will fix that.
