### ISSUE TITLE
fails to build with --incompatible_restrict_named_params

### ISSUE THREAD

**Issue by mariusgrigoriu** [kubernetes/kubernetes#81382]
**What happened**:
Running bazel 0.26.1 with `--incompatible_restrict_named_params` flag fails with
```
ERROR: /private/var/tmp/_bazel_marius/c39204db2cb7e0a79ba2096a64d88d76/external/io_k8s_kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/generated/openapi/BUILD:6:1: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_marius/c39204db2cb7e0a79ba2096a64d88d76/external/io_k8s_kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/generated/openapi/BUILD", line 6
		gen_openapi(outs = ["zz_generated.openapi.go...], ...")
	File "/private/var/tmp/_bazel_marius/c39204db2cb7e0a79ba2096a64d88d76/external/io_k8s_kubernetes/build/code_generation.bzl", line 59, in gen_openapi
		go_genrule(name = "zz_generated.openapi", src...")], <4 more arguments>)
	File "/private/var/tmp/_bazel_marius/c39204db2cb7e0a79ba2096a64d88d76/external/io_k8s_kubernetes/build/code_generation.bzl", line 66, in go_genrule
		" ".join([(("cd $$GOPATH/src/" + go_prefi..."])
	File "/private/var/tmp/_bazel_marius/c39204db2cb7e0a79ba2096a64d88d76/external/io_k8s_kubernetes/build/code_generation.bzl", line 75, in " ".join
		",".join([go_pkg(pkg) for pkg in tags_val..."]])
	File "/private/var/tmp/_bazel_marius/c39204db2cb7e0a79ba2096a64d88d76/external/io_k8s_kubernetes/build/code_generation.bzl", line 75, in ",".join
		go_pkg(pkg)
	File "/private/var/tmp/_bazel_marius/c39204db2cb7e0a79ba2096a64d88d76/external/io_k8s_kubernetes/build/code_generation.bzl", line 44, in go_pkg
		pkg.replace("staging/src/", "vendor/", maxsplit ...)
unexpected keyword 'maxsplit', for call to method replace(old, new, maxsplit = None) of 'string'
```

**What you expected to happen**:
The build conforms to https://github.com/bazelbuild/bazel/issues/8147

**Other info**: This was discovered when building an external project that imports Kubernetes for the purpose of building e2e tests. I expect the same error to occur when building Kubernetes itself with a future version of bazel or with the incompatible flag set.

Version: 1.15.2+

**Comment by mariusgrigoriu** [comment]
Should be fixed by #84664
