### ISSUE TITLE
[k8s][apiserver] goroutines increasing after upgrade

### ISSUE THREAD

**Issue by tw3rp** [kubernetes/kubernetes#81901]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tw3rp** [comment]
This is the goroutine that is getting created a lot!

```
goroutine 46696999 [chan send, 1109 minutes]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc114e65080)
	/workspace/anago-v1.13.10-beta.0.27+37d169313237cb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:106 +0x74
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc114e65080, 0xc00e292340, 0x5dcf940, 0xc105d340c8, 0xc0cf5c3300)
	/workspace/anago-v1.13.10-beta.0.27+37d169313237cb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:109 +0xb4
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/workspace/anago-v1.13.10-beta.0.27+37d169313237cb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:97 +0x1b0
```

**Comment by tw3rp** [comment]
and this is what I see most of the heap like 

```
0: 0 [517: 264704] @ 0x4f8bed 0x4f854c 0x4f86fa 0x574373 0x57445e 0x135d74f 0x136dafc 0x1385f21 0xff548d 0x7397f8 0x738de7 0x13ad2c1 0x13b2515 0x14a1aaa 0x1174be4 0x117480a 0x13ad471 0x13b2515 0x100b723 0x6aec44 0x116f43f 0x6aec44 0x100d68b 0x6aec44 0x1009fac 0x6aec44 0x100a7c6 0x6aec44 0x116fe23 0x45c151
#	0x4f8bec	bytes.makeSlice+0x6c											/usr/local/go/src/bytes/buffer.go:231
#	0x4f854b	bytes.(*Buffer).grow+0x16b										/usr/local/go/src/bytes/buffer.go:144
#	0x4f86f9	bytes.(*Buffer).Grow+0x39										/usr/local/go/src/bytes/buffer.go:163
#	0x574372	io/ioutil.readAll+0x92											/usr/local/go/src/io/ioutil/ioutil.go:34
#	0x57445d	io/ioutil.ReadAll+0x3d											/usr/local/go/src/io/ioutil/ioutil.go:45
#	0x135d74e	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.limitedReadBody+0xfe			/workspace/anago-v1.13.10-beta.0.27+37d169313237cb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:339
#	0x136dafb	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.UpdateResource.func1+0x22b		/workspace/anago-v1.13.10-beta.0.27+37d169313237cb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/update.go:67
#	0x1385f20	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints.restfulUpdateResource.func1+0xb0		/workspace/anago-v1.13.10-beta.0.27+37d169313237cb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1056
#	0xff548c	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1+0x20c		/workspace/anago-v1.13.10-beta.0.27+37d169313237cb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:225
#	0x7397f7	k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch+0x9b7			/workspace/anago-v1.13.10-beta.0.27+37d169313237cb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:277
#	0x738de6	k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).Dispatch+0x56			/workspace/anago-v1.13.10-beta.0.27+37d169313237cb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:199
#	0x13ad2c0	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP+0x4b0				/workspace/anago-v1.13.10-beta.0.27+37d169313237cb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:146
#	0x14a1aa9	k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP+0x169		/workspace/anago-v1.13.10-beta.0.27+37d169313237cb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:90
#	0x1174be3	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP+0x393			/workspace/anago-v1.13.10-beta.0.27+37d169313237cb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248
#	0x1174809	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP+0x89		/workspace/anago-v1.13.10-beta.0.27+37d169313237cb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234
#	0x13ad470	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP+0x660				/workspace/anago-v1.13.10-beta.0.27+37d169313237cb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:154
#	0x100b722	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1+0x4c2		/workspace/anago-v1.13.10-beta.0.27+37d169313237cb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64
#	0x6aec43	net/http.HandlerFunc.ServeHTTP+0x43									/usr/local/go/src/net/http/server.go:1964
#	0x116f43e	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1+0x3fe		/workspace/anago-v1.13.10-beta.0.27+37d169313237cb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:160
#	0x6aec43	net/http.HandlerFunc.ServeHTTP+0x43									/usr/local/go/src/net/http/server.go:1964
#	0x100d68a	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1+0x1eea		/workspace/anago-v1.13.10-beta.0.27+37d169313237cb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50
#	0x6aec43	net/http.HandlerFunc.ServeHTTP+0x43									/usr/local/go/src/net/http/server.go:1964
#	0x1009fab	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAudit.func1+0x4bb			/workspace/anago-v1.13.10-beta.0.27+37d169313237cb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/audit.go:110
#	0x6aec43	net/http.HandlerFunc.ServeHTTP+0x43									/usr/local/go/src/net/http/server.go:1964
#	0x100a7c5	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1+0x455		/workspace/anago-v1.13.10-beta.0.27+37d169313237cb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:81
#	0x6aec43	net/http.HandlerFunc.ServeHTTP+0x43									/usr/local/go/src/net/http/server.go:1964
#	0x116fe22	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1+0xb2	/workspace/anago-v1.13.10-beta.0.27+37d169313237cb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108
```

**Comment by tedyu** [comment]
Instead of spawning goroutine for every timeoutHandler#ServeHTTP, we can utilize worker pool where each worker performs what goroutine does starting at line 99 in vendor/k8s.io/apiserver/pkg/server/filters/timeout.go

**Comment by eytan-avisror** [comment]
Seeing similar behavior with 1.13.10, memory usage is spiking from apiserver until it gets evicted/rescheduled.

**Comment by CH-rahulprabhu** [comment]
Do you know if this is happening in >1.14 as well ?

**Comment by tw3rp** [comment]
@tedyu yea, putting it in a worker pool will solve this issue

@eytan-avisror do you happen to know if it is solved in >= v1.14  ?

**Comment by eytan-avisror** [comment]
@tw3rp Sorry, havent tried 1.14 yet, have just found this issue after rolling out 1.13.10 very recently

**Comment by tw3rp** [comment]
oh gotcha, the diff between 1.13.5 -> 1.13.10 does not look very suspicious tho. I upgraded the control plane first and it was fine for a day and this triggered when I converted the kubelets to 1.13.10.

**Comment by tw3rp** [comment]
Looking at the code, the goroutine is triggered by timeout.go in server/filters.go and chansend is called here https://github.com/kubernetes/apiserver/blob/b43e7957483c8057f5f25918b07a34b9be66da5a/pkg/server/filters/timeout.go#L106 but then it just sits in gopark and panic() is not called  here https://github.com/kubernetes/apiserver/blob/b43e7957483c8057f5f25918b07a34b9be66da5a/pkg/server/filters/timeout.go#L111-L114

**Comment by yue9944882** [comment]
not likely timeout handler to blame.. it hasnt changed for a period of time.. after upgrading your kubelets seems raising much more requests than before

**Comment by tw3rp** [comment]
How would I go about debugging why there are so many requests? or how can I find out the source for the rise in requests?

**Comment by tw3rp** [comment]
The apiserver sum by rate has not changed significantly over the period before we upgraded the kubelets 

<img width="1375" alt="Screen Shot 2019-08-25 at 9 46 51 PM" src="https://user-images.githubusercontent.com/9117091/63665849-fa909a00-c781-11e9-85b8-93d07bbe991a.png">
