### ISSUE TITLE
Failure to pull down container images with Bazel

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#82102]
**What happened**:
So I ran into this problem while trying to build a [kind node-image](https://kind.sigs.k8s.io/docs/user/quick-start/#building-images).
Running 
```
kind build node-image --type=bazel --kube-root="$(go env GOPATH)/src/k8s.io/kubernetes"
```

In order to reproduce it, the actual bazel command this runs is:
```
bazel build --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //cmd/kubeadm:kubeadm //cmd/kubectl:kubectl //cmd/kubelet:kubelet //build:docker-artifacts
```

Produced an error message that looked like this
```
ERROR: Analysis of target '//build:docker-artifacts' failed; build aborted: no such package '@debian-iptables-amd64//image': Pull command failed: Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/.cache/bazel/_bazel_user/340f471f8099bae3863e67364fd5f34d/external/puller/file/downloaded/__main__.py", line 30, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/user/.cache/bazel/_bazel_user/340f471f8099bae3863e67364fd5f34d/external/puller/file/downloaded/containerregistry/client/__init__.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/user/.cache/bazel/_bazel_user/340f471f8099bae3863e67364fd5f34d/external/puller/file/downloaded/containerregistry/client/docker_creds_.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 594, in spec_from_file_location
  File "/home/user/.cache/bazel/_bazel_user/340f471f8099bae3863e67364fd5f34d/external/puller/file/downloaded/httplib2/__init__.py", line 988
    raise socket.error, msg
```

Which seems to be the same issue as the one logged here https://github.com/tensorflow/tensorflow/issues/28824 "Error Loading Package @io_bazel_rules_docker when building Tensorflow".

The proposed solution is to update `rules_docker` from 0.7.0 to 0.8.1 

https://github.com/kubernetes/kubernetes/blob/master/build/root/WORKSPACE#L62
```
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "87fc6a2b128147a0a3039a2fd0b53cc1f2ed5adb8716f50756544a572999ae9a",
    strip_prefix = "rules_docker-0.8.1",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.8.1.tar.gz"],
)
```

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="19.04 (Disco Dingo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.04"
VERSION_ID="19.04"
````
- Kernel (e.g. `uname -a`): 
```
5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

/sig testing
/kind bug

**Comment by alejandrox1** [comment]
This is actually not an issue if one uses the same bazel version that is used in Kubernetes, o.23.x.
/close
