### ISSUE TITLE
panic encoding the same object from multiple goroutines concurrently

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#82497]
Seen in https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/69821/pull-kubernetes-integration/1170241808647589890

This happens to be triggered from a test, but other contexts that encoded the same object from multiple goroutines could hit the same issue

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x402f95]

goroutine 105737 [running]:
strings.Count(0x0, 0x2, 0x46fdf46, 0x1, 0x1)
	/usr/local/go/src/strings/strings.go:84 +0xf2
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/schema.ParseGroupVersion(0x0, 0x2, 0x8744b2, 0x3dfe500, 0xc000231410, 0xc01f8d4b38, 0xaf88cc0, 0x434c200)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/schema/group_version.go:222 +0x99
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/schema.FromAPIVersionAndKind(0x0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/schema/group_version.go:296 +0x5a
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1.(*TypeMeta).GroupVersionKind(0xc04cfdfc00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/meta.go:128 +0x5e
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime.WithVersionEncoder.Encode(0x7d611c0, 0xc04cf533c0, 0x7fc20274a3e8, 0xc00010fc00, 0x7d741a0, 0xc000214690, 0x7d71be0, 0xc04cfdfc00, 0x7d56f00, 0xc04cfba450, ...)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/helper.go:231 +0x177
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime.Encode(0x7d61120, 0xc04cf8b260, 0x7d71be0, 0xc04cfdfc00, 0xc04cfdfc00, 0x1, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/codec.go:46 +0x74
k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Request).Body(0xc04cfca600, 0x46ca1c0, 0xc04cfdfc00, 0xc04cfca600)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:400 +0x238
k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/core/v1.(*pods).Create(0xc04cfccd20, 0xc04cfdfc00, 0xc, 0x7e5d9a0, 0xc04cfccd20)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/kubernetes/typed/core/v1/pod.go:120 +0xd4
```

**Comment by smarterclayton** [comment]
We can probably fix this globally by slightly tweaking UnsafeConversion to copy the top most object (where kind is set) on its way down the conversion stack.

**Comment by kikisdeliveryservice** [comment]
Bug Triage Release Team checking in. Code freeze for the 1.17 release is on November 18. Will this a fix for this issue make it in? Thanks!

**Comment by tedyu** [comment]
From the crash report : addr=0x0
Prior to calling strings.Count, there is a check:
```
	if (len(gv) == 0) || (gv == "/") {
		return GroupVersion{}, nil
```
The check should have prevented the nil access.

**Comment by liggitt** [comment]
> The check should have prevented the nil access.

that doesn't hold in a race condition

**Comment by liggitt** [comment]
cc @smarterclayton @wojtek-t
