### ISSUE TITLE
[Failing Job] pull-kubernetes-node-e2e is failing

### ISSUE THREAD

**Issue by alejandrox1** [kubernetes/kubernetes#83086]
**Which jobs are failing**:
pull-kubernetes-node-e2e

**Which test(s) are failing**:
The overall stage is failing in this job.

**Since when has it been failing**:
Started failing today at 13 PDT.

**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-node-e2e

**Reason for failure**:
There isn't too much info in the logs.
From https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-node-e2e/1176596694691745792#0:build-log.txt%3A16079 :
```
I0924 20:58:27.412] Ginkgo ran 1 suite in 13m1.105374249s
I0924 20:58:27.412] Test Suite Passed
I0924 20:58:27.412] 
I0924 20:58:27.412] Success Finished Test Suite on Host tmp-node-e2e-8870c0d4-cos-stable-60-9592-84-0
I0924 20:58:27.412] <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
I0924 20:58:27.412] <                              FINISH TEST                               <
I0924 20:58:27.412] <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
I0924 20:58:27.413] 
I0924 20:58:27.413] Failure: 1 errors encountered.
W0924 20:58:27.513] exit status 1
W0924 20:58:27.514] 2019/09/24 20:58:27 process.go:155: Step 'go run /go/src/k8s.io/kubernetes/test/e2e_node/runner/remote/run_remote.go --cleanup --logtostderr --vmodule=*=4 --ssh-env=gce --results-dir=/workspace/_artifacts --project=k8s-jkns-pr-node-e2e --zone=us-west1-b --ssh-user=prow --ssh-key=/workspace/.ssh/google_compute_engine --ginkgo-flags=--nodes=8 --focus="\[NodeConformance\]" --skip="\[Flaky\]|\[Slow\]|\[Serial\]" --flakeAttempts=2 --test_args=--kubelet-flags="--cgroups-per-qos=true --cgroup-root=/" --test-timeout=1h5m0s --image-config-file=/workspace/test-infra/jobs/e2e_node/image-config.yaml' finished in 18m51.011388995s
W0924 20:58:27.514] 2019/09/24 20:58:27 node.go:42: Noop - Node DumpClusterLogs() - /workspace/_artifacts: 
W0924 20:58:27.514] 2019/09/24 20:58:27 node.go:52: Noop - Node Down()
W0924 20:58:27.515] 2019/09/24 20:58:27 process.go:96: Saved XML output to /workspace/_artifacts/junit_runner.xml.
W0924 20:58:27.515] 2019/09/24 20:58:27 process.go:153: Running: bash -c . hack/lib/version.sh && KUBE_ROOT=. kube::version::get_version_vars && echo "${KUBE_GIT_VERSION-}"
W0924 20:58:27.866] 2019/09/24 20:58:27 process.go:155: Step 'bash -c . hack/lib/version.sh && KUBE_ROOT=. kube::version::get_version_vars && echo "${KUBE_GIT_VERSION-}"' finished in 350.262074ms
W0924 20:58:27.866] 2019/09/24 20:58:27 main.go:319: Something went wrong: encountered 1 errors: [error during go run /go/src/k8s.io/kubernetes/test/e2e_node/runner/remote/run_remote.go --cleanup --logtostderr --vmodule=*=4 --ssh-env=gce --results-dir=/workspace/_artifacts --project=k8s-jkns-pr-node-e2e --zone=us-west1-b --ssh-user=prow --ssh-key=/workspace/.ssh/google_compute_engine --ginkgo-flags=--nodes=8 --focus="\[NodeConformance\]" --skip="\[Flaky\]|\[Slow\]|\[Serial\]" --flakeAttempts=2 --test_args=--kubelet-flags="--cgroups-per-qos=true --cgroup-root=/" --test-timeout=1h5m0s --image-config-file=/workspace/test-infra/jobs/e2e_node/image-config.yaml: exit status 1]
W0924 20:58:27.867] Traceback (most recent call last):
W0924 20:58:27.867]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 778, in <module>
W0924 20:58:27.867]     main(parse_args())
W0924 20:58:27.867]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 626, in main
W0924 20:58:27.868]     mode.start(runner_args)
W0924 20:58:27.868]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 262, in start
W0924 20:58:27.868]     check_env(env, self.command, *args)
W0924 20:58:27.868]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 111, in check_env
W0924 20:58:27.869]     subprocess.check_call(cmd, env=env)
W0924 20:58:27.869]   File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
W0924 20:58:27.869]     raise CalledProcessError(retcode, cmd)
W0924 20:58:27.870] subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--deployment=node', '--provider=gce', '--cluster=bootstrap-e2e', '--gcp-network=bootstrap-e2e', '--gcp-project=k8s-jkns-pr-node-e2e', '--gcp-zone=us-west1-b', '--node-test-args=--kubelet-flags="--cgroups-per-qos=true --cgroup-root=/"', '--node-tests=true', '--test_args=--nodes=8 --focus="\\[NodeConformance\\]" --skip="\\[Flaky\\]|\\[Slow\\]|\\[Serial\\]" --flakeAttempts=2', '--timeout=65m', '--node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/image-config.yaml')' returned non-zero exit status 1
E0924 20:58:27.876] Command failed
I0924 20:58:27.876] process 489 exited with code 1 after 18.9m
E0924 20:58:27.876] FAIL: pull-kubernetes-node-e2e
```

/cc @kubernetes/sig-node-test-failures 
/priority critical-urgent
/kind failing-test
/milestone v1.17
/cc @alenkacz

**Comment by zouyee** [comment]
related pr: https://github.com/kubernetes/test-infra/pull/14291
```
unable to create gce instance with running docker daemon for image coreos-beta-1911-2-0-v20181024.  could not create instance tmp-node-e2e-8870c0d4-coreos-beta-1911-2-0-v20181024: API error: googleapi: Error 400: Invalid value for field 'resource.disks[0].initializeParams.sourceImage': 'projects/coreos-cloud/global/images/coreos-beta-1911-2-0-v20181024'. The referenced image resource cannot be found., invalid
```

**Comment by alejandrox1** [comment]
coreos image issues being tracked in https://github.com/kubernetes/test-infra/issues/14465

**Comment by liggitt** [comment]
will by fixed by https://github.com/kubernetes/test-infra/pull/14466

**Comment by guineveresaenger** [comment]
Have we confirmed this issue has been addressed by ^^ merging?

**Comment by liggitt** [comment]
Yes, the merge queue has been unblocked
