### ISSUE TITLE
PDB controller doesn't handle tombstones

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#83948]
From integration tests:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/83709/pull-kubernetes-integration/1184076134967414784/

```
W1015 12:11:28.632] goroutine 1713 [running]:
W1015 12:11:28.632] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
W1015 12:11:28.632] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
W1015 12:11:28.632] panic(0x3a24020, 0xc00168e6f0)
W1015 12:11:28.632] 	/usr/local/go/src/runtime/panic.go:522 +0x1b5
W1015 12:11:28.632] k8s.io/kubernetes/pkg/controller/disruption.(*DisruptionController).removeDb(0xc00032d7a0, 0x3be4420, 0xc0015bae40)
W1015 12:11:28.633] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/disruption/disruption.go:366 +0x118
W1015 12:11:28.633] k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
W1015 12:11:28.633] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:212
W1015 12:11:28.633] k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0xc001355c80, 0xc000491270, 0xce)
W1015 12:11:28.633] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:660 +0x22b
W1015 12:11:28.634] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc0018a9e38, 0x42ccbf, 0xc0004912a0)
W1015 12:11:28.634] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
W1015 12:11:28.634] k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
W1015 12:11:28.634] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x79
W1015 12:11:28.634] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00136cf68)
W1015 12:11:28.634] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
W1015 12:11:28.634] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0018a9f68, 0xdf8475800, 0x0, 0x1, 0xc000370c60)
W1015 12:11:28.635] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
W1015 12:11:28.635] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
W1015 12:11:28.635] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
W1015 12:11:28.635] k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc000cb9e80)
W1015 12:11:28.635] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x9c
W1015 12:11:28.635] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0003eddb0, 0xc001950ce0)
W1015 12:11:28.636] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
W1015 12:11:28.636] created by k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
W1015 12:11:28.636] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
```

@kubernetes/sig-apps-bugs

**Comment by tedyu** [comment]
```
func (dc *DisruptionController) removeDb(obj interface{}) {
	if pdb, ok := obj.(*policy.PodDisruptionBudget); ok {
		klog.V(4).Infof("remove DB %q", pdb.Name)
		dc.enqueuePdb(pdb)
	}
```
How about adding a check for the cast ?

**Comment by wojtek-t** [comment]
On Tue, Oct 15, 2019 at 4:04 PM Ted Yu <notifications@github.com> wrote:

> func (dc *DisruptionController) removeDb(obj interface{}) {
> 	if pdb, ok := obj.(*policy.PodDisruptionBudget); ok {
> 		klog.V(4).Infof("remove DB %q", pdb.Name)
> 		dc.enqueuePdb(pdb)
> 	}
>
> How about adding a check for the cast ?
>

Nope - you need something like that:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replicaset/replica_set.go#L379

**Comment by tedyu** [comment]
I was looking at the GetPodFromDeleteAction when I noticed PR opened for this issue.
Hence I didn't update my snippet.
