### ISSUE TITLE
[Failing Test] ci-kubernetes-integration-master

### ISSUE THREAD

**Issue by hasheddan** [kubernetes/kubernetes#84022]
**Which jobs are failing**: ci-kubernetes-integration-master

**Which test(s) are failing**: `Overall`

**Since when has it been failing**: Last successful run at 12:30 PDT
infra commit: https://github.com/kubernetes/test-infra/commit/c1d6e4301e7eedd151c540dc0c466b512795593d
k/k commit: https://github.com/kubernetes/kubernetes/commit/01a6c27ee4130aadb88b188adcba59854e62804f

**Testgrid link**: https://k8s-testgrid.appspot.com/sig-release-master-blocking#integration-master

**Reason for failure**:
```
W1016 22:34:20.023] Run: ('docker', 'run', '--rm=true', '--privileged=true', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-v', '/etc/localtime:/etc/localtime:ro', '-v', '/workspace/k8s.io/kubernetes:/go/src/k8s.io/kubernetes', '-v', '/workspace/k8s.io/:/workspace/k8s.io/', '-v', '/workspace/_artifacts:/workspace/artifacts', '-e', 'KUBE_FORCE_VERIFY_CHECKS=y', '-e', 'KUBE_VERIFY_GIT_BRANCH=master', '-e', 'EXCLUDE_TYPECHECK=n', '-e', 'EXCLUDE_GODEP=n', '-e', 'REPO_DIR=/workspace/k8s.io/kubernetes', '--tmpfs', '/tmp:exec,mode=1777', 'gcr.io/k8s-testimages/kubekins-test:1.14-v20190817-cc05229', 'bash', '-c', 'cd kubernetes && ./hack/jenkins/test-dockerized.sh')
W1016 22:34:20.112] docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
W1016 22:34:20.113] See 'docker run --help'.
W1016 22:34:20.124] Traceback (most recent call last):
W1016 22:34:20.124]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 178, in <module>
W1016 22:34:20.124]     ARGS.exclude_typecheck, ARGS.exclude_godep)
W1016 22:34:20.125]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 140, in main
W1016 22:34:20.125]     check(*cmd)
W1016 22:34:20.125]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 48, in check
W1016 22:34:20.125]     subprocess.check_call(cmd)
W1016 22:34:20.125]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W1016 22:34:20.125]     raise CalledProcessError(retcode, cmd)
W1016 22:34:20.126] subprocess.CalledProcessError: Command '('docker', 'run', '--rm=true', '--privileged=true', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-v', '/etc/localtime:/etc/localtime:ro', '-v', '/workspace/k8s.io/kubernetes:/go/src/k8s.io/kubernetes', '-v', '/workspace/k8s.io/:/workspace/k8s.io/', '-v', '/workspace/_artifacts:/workspace/artifacts', '-e', 'KUBE_FORCE_VERIFY_CHECKS=y', '-e', 'KUBE_VERIFY_GIT_BRANCH=master', '-e', 'EXCLUDE_TYPECHECK=n', '-e', 'EXCLUDE_GODEP=n', '-e', 'REPO_DIR=/workspace/k8s.io/kubernetes', '--tmpfs', '/tmp:exec,mode=1777', 'gcr.io/k8s-testimages/kubekins-test:1.14-v20190817-cc05229', 'bash', '-c', 'cd kubernetes && ./hack/jenkins/test-dockerized.sh')' returned non-zero exit status 125
```

**Anything else we need to know**:

/priority important-soon
/milestone v1.17
/sig testing

/cc @alenkacz @droslean @Verolop @epk

**Comment by BenTheElder** [comment]
/assign
this should have been mitigated by https://github.com/kubernetes/test-infra/pull/14811

**Comment by BenTheElder** [comment]
roll forward fix is starting in https://github.com/kubernetes/test-infra/pull/14812 https://github.com/kubernetes/test-infra/pull/14813

similar to https://github.com/kubernetes/kubernetes/issues/71305

**Comment by BenTheElder** [comment]
roll forward in https://github.com/kubernetes/test-infra/pull/14814

also, while the most recent run did fail, it failed due to a test case rather than docker issues
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1184613331994939392

**Comment by BenTheElder** [comment]
Roll forward is in and docker is starting fine.

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1184643532015538176/
/close
