### ISSUE TITLE
Kubemark: fake fluentd broke tests

### ISSUE THREAD

**Issue by oxddr** [kubernetes/kubernetes#84855]
https://github.com/kubernetes/kubernetes/pull/83897 broken kubemark tests (e.g. https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-high-density-100-gce/1191791957987299332 or https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/1191801274085937152). Failure needs to be investigated before this option is enabled again.

**Comment by krzysied** [comment]
I look into hollow-node logs. There is a problem with nil pointer dereference:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1b26921]

goroutine 5587 [running]:
k8s.io/kubernetes/pkg/kubelet/dockershim.(*NativeExecHandler).ExecInContainer(0x785e428, 0x4ac61a0, 0xc00083a600, 0xc001dbb470, 0xc00288fa40, 0x3, 0x4, 0x0, 0x0, 0x49b1360, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/dockershim/exec.go:118 +0x581
k8s.io/kubernetes/pkg/kubelet/dockershim.(*streamingRuntime).exec(0xc000944060, 0xc0026a3120, 0x10, 0xc00288fa40, 0x3, 0x4, 0x0, 0x0, 0x49b1360, 0xc001d25f10, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_streaming.go:57 +0x165
k8s.io/kubernetes/pkg/kubelet/dockershim.(*dockerService).ExecSync(0xc000a52000, 0x4a11160, 0xc001d40e40, 0xc00288fa00, 0xc000a52000, 0xc001d40e40, 0xc000c69bd0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_streaming.go:81 +0x222
k8s.io/kubernetes/vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2._RuntimeService_ExecSync_Handler(0x4219120, 0xc000a52000, 0x4a11160, 0xc001d40e40, 0xc0014c3860, 0x0, 0x4a11160, 0xc001d40e40, 0xc000c18c80, 0x269)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go:7843 +0x23e
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000228000, 0x4a7b920, 0xc0008a0300, 0xc0010bb500, 0xc00072c120, 0x7787450, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:995 +0x466
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000228000, 0x4a7b920, 0xc0008a0300, 0xc0010bb500, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:1275 +0xda6
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000dc610, 0xc000228000, 0x4a7b920, 0xc0008a0300, 0xc0010bb500)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:710 +0x9f
created by k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:708 +0xa1
```

**Comment by krzysied** [comment]
The nil dereferencing is done in line: https://github.com/kubernetes/kubernetes/blob/76d04cf6025ce98c1d936bd9d075e8ddb8a64c7e/pkg/kubelet/dockershim/exec.go#L118.
This should be a result of https://github.com/kubernetes/kubernetes/blob/76d04cf6025ce98c1d936bd9d075e8ddb8a64c7e/pkg/kubelet/dockershim/exec.go#L114 returnin (nil, nil).

**Comment by krzysied** [comment]
Assuming that kubemark uses docker fake client, this problem is caused by:
https://github.com/kubernetes/kubernetes/blob/76d04cf6025ce98c1d936bd9d075e8ddb8a64c7e/pkg/kubelet/dockershim/libdocker/fake_client.go#L764-L766
which can return (nil, nil) - default for `NewFakeDockerClient`.
IMHO it should be return `f.ExecInspect` if it's not nil, else `&dockertypes.ContainerExecInspect{}`
