### ISSUE TITLE
panic in pkg/kubelet/server/stats when driver does not support volume stats

### ISSUE THREAD

**Issue by ggriffiths** [kubernetes/kubernetes#86106]
Found this on k8s Version: v1.15.3. Our CSI driver does not implement volume stats.

Similar issue to #79719. I noticed a fix for this was merged to release-1.15 on and is in 1.15.3: https://github.com/kubernetes/kubernetes/commit/78fdc0a129b5aeadcf1367c2142f57d8ff050ab6

```
Dec 07 09:10:21  kubelet[20530]: E1207 09:10:21.663369   20530 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Dec 07 09:10:21  kubelet[20530]: goroutine 90290 [running]:
Dec 07 09:10:21  kubelet[20530]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x4b61680, 0xc136b40)
Dec 07 09:10:21  kubelet[20530]: /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
Dec 07 09:10:21  kubelet[20530]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Dec 07 09:10:21  kubelet[20530]: /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
Dec 07 09:10:21  kubelet[20530]: panic(0x4b61680, 0xc136b40)
Dec 07 09:10:21  kubelet[20530]: /usr/local/go/src/runtime/panic.go:522 +0x1b5
Dec 07 09:10:21  kubelet[20530]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).parsePodVolumeStats(0xc002141f40, 0xc0018659e0, 0x18, 0xc000d98720, 0x0, 0xc0018659e0, 0x18, 0x0, 0x0, 0x0, ...)
Dec 07 09:10:21  kubelet[20530]: /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:143 +0xf5
Dec 07 09:10:21  kubelet[20530]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).calcAndStoreStats(0xc002141f40)
Dec 07 09:10:21  kubelet[20530]: /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:125 +0x753
Dec 07 09:10:21  kubelet[20530]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).StartOnce.func1.1()
Dec 07 09:10:21  kubelet[20530]: /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:65 +0x2a
Dec 07 09:10:21  kubelet[20530]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0019da310)
Dec 07 09:10:21  kubelet[20530]: /workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
Dec 07 09:10:21  kubelet[20530]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0019da310, 0xdf8475800, 0x3ff0000000000000, 0xc000940d01, 0xc0000b3260)
```

**Comment by ggriffiths** [comment]
@kubernetes/sig-storage-bugs
/sig storage

**Comment by haosdent** [comment]
wired, still have problem even you use latest version? and is this error caused by other volumes instead of csi?

**Comment by msau42** [comment]
Are you sure you're on 1.15.3?  I'm not sure if this string refers to the K8s version, but if so, it's a pre-1.15.3 version:
/workspace/anago-v1.15.3-beta.0.68+2d3c76f9091b6b

**Comment by ggriffiths** [comment]
Thanks, I'll double check the installation version. That's probably it

**Comment by ggriffiths** [comment]
Ah yeah, closing. Thanks!
