### ISSUE TITLE
[Failing Test] cip-postsubmit-push-to-staging (cip-postsubmit-push-to-staging)

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubernetes#86880]
**Which jobs are failing**:
cip-postsubmit-push-to-staging (cip-postsubmit-push-to-staging)

**Since when has it been failing**:
This is a postsubmit of `kubernetes-sigs/k8s-container-image-promoter` repository.

**Testgrid link**:
https://testgrid.k8s.io/sig-release-misc#cip-postsubmit-push-to-staging

**Reason for failure**:
```console
 Activating service account...
Activated service account credentials for: [deployer@k8s-prow.iam.gserviceaccount.com]
Running...
$ARTIFACTS is set, sending logs to /logs/artifacts
2019/12/31 00:48:10 Build directory: .
2019/12/31 00:48:10 Config directory: /home/prow/go/src/github.com/kubernetes-sigs/k8s-container-image-promoter
2019/12/31 00:48:10 cd-ing to build directory: .
2019/12/31 00:48:10 Creating source tarball at /tmp/118374550...
2019/12/31 00:48:10 Uploading /tmp/118374550 to gs://k8s-staging-artifact-promoter-gcb/source/56847387-8e0b-4df4-bde8-a4ad9f4f925f.tgz...
Copying file:///tmp/118374550 [Content-Type=application/octet-stream]...
/ [0 files][    0.0 B/ 99.1 KiB]                                                
-
- [1 files][ 99.1 KiB/ 99.1 KiB]                                                
Operation completed over 1 objects/99.1 KiB.                                     
2019/12/31 00:48:17 Running build jobs...
2019/12/31 00:48:17 No variants.yaml, starting single build job...
2019/12/31 00:55:44 Failed to run some build jobs: [error running [gcloud builds submit --verbosity info --config /home/prow/go/src/github.com/kubernetes-sigs/k8s-container-image-promoter/cloudbuild.yaml --substitutions _PULL_BASE_REF=master,_GIT_TAG=v20191231-v2.3.1-60-g3214f19 --project k8s-staging-artifact-promoter --gcs-log-dir gs://k8s-staging-artifact-promoter-gcb/logs --gcs-source-staging-dir gs://k8s-staging-artifact-promoter-gcb/source gs://k8s-staging-artifact-promoter-gcb/source/56847387-8e0b-4df4-bde8-a4ad9f4f925f.tgz]: exit status 1] 
```

**Anything else we need to know**:
/cc @kubernetes/ci-signal 
/priority critical-urgent
/milestone v1.18

**Comment by listx** [comment]
So this is the "create a staging image of the promoter upon a merge to its master branch" job so that I don't have to do it manually myself.

As for the failure, I am probably doing something wrong but from the logs it's hard to tell what I'm doing wrong.

I don't think this is critical as it is not blocking the official promoter or anything.

**Comment by listx** [comment]
I think the error could be that the service account for `deployer@...` doesn't have creds to push to the buckets. I'll post another update later.

**Comment by droslean** [comment]
@listx Thanks for the quick response. So, since this job is not critical, can we removed it from testgrid or is there a good reason to keep it there and just ignore the alerts?

**Comment by listx** [comment]
I should be able to fix it this week; if that deadline passes then we can move it to another testgrid dashboard.

**Comment by droslean** [comment]
/reopen

Let's observe the job first before closing.

**Comment by droslean** [comment]
@listx Do we have to rerun the job to make sure that it's fixed or wait for the next PR to be merge?

**Comment by listx** [comment]
The behavior I have observed is that the job will re-run for each PR merge.

I am now seeing that the latest build is failing due to a MemoryError when joining the heaviest Docker layer that contains gcloud:

```
[521 / 545] [Prepa] ImageConfig cip-docker-image-no-gcloud.0.config
ERROR: /workspace/BUILD.bazel:68:1: JoinLayers cip-docker-loadable.tar failed (Exit 1) join_layers failed: error executing command bazel-out/host/bin/external/io_bazel_rules_docker/container/join_layers '--output=bazel-out/k8-fastbuild/bin/cip-docker-loadable.tar' ... (remaining 30 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/sandbox/linux-sandbox/517/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/container/join_layers.runfiles/io_bazel_rules_docker/container/join_layers.py", line 304, in <module>
    main()
  File "/builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/sandbox/linux-sandbox/517/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/container/join_layers.runfiles/io_bazel_rules_docker/container/join_layers.py", line 300, in main
    blobsum_to_unzipped, blobsum_to_zipped, blobsum_to_legacy)
  File "/builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/sandbox/linux-sandbox/517/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/container/join_layers.runfiles/io_bazel_rules_docker/container/join_layers.py", line 197, in create_bundle
    v2_2_save.multi_image_tarball(tag_to_image, tar)
  File "/builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/sandbox/linux-sandbox/517/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/container/join_layers.runfiles/containerregistry/client/v2_2/save_.py", line 126, in multi_image_tarball
    v1_save.multi_image_tarball(tag_to_v1_image, tar)
  File "/builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/sandbox/linux-sandbox/517/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/container/join_layers.runfiles/containerregistry/client/v1/save_.py", line 73, in multi_image_tarball
    add_file(layer_id + '/layer.tar', content)
  File "/builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/sandbox/linux-sandbox/517/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/container/join_layers.runfiles/containerregistry/client/v1/save_.py", line 45, in add_file
    tar.addfile(tarinfo=info, fileobj=io.BytesIO(contents))
MemoryError
```

I am going to change the machine settings in another PR; stay tuned.

**Comment by listx** [comment]
Looks like the last couple PRs did the trick. It's green now! https://testgrid.k8s.io/sig-release-misc#cip-postsubmit-push-to-staging

**Comment by droslean** [comment]
Thanks @listx !

/close
