### ISSUE TITLE
Scheduler is failing in alpha presubmits

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#86908]
```
E0107 12:00:07.093533       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 298 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x186a0a0, 0x2bad8c0)
	staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x186a0a0, 0x2bad8c0)
	GOROOT/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/pkg/scheduler/framework/plugins/noderesources.(*ResourceLimits).Score(0xc000303530, 0x1d95e00, 0xc000798e00, 0xc0002cdc80, 0xc0006d87c0, 0xc0002f1ce0, 0x26, 0x0, 0x4700000000000000)
	pkg/scheduler/framework/plugins/noderesources/resource_limits.go:120 +0x338
k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1.(*framework).runScorePlugin(0xc0000e1080, 0x1d95e00, 0xc000798e00, 0x7f5278532320, 0xc000303530, 0xc0002cdc80, 0xc0006d87c0, 0xc0002f1ce0, 0x26, 0x0, ...)
	pkg/scheduler/framework/v1alpha1/framework.go:586 +0xa6
k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1.(*framework).RunScorePlugins.func2(0x0)
	pkg/scheduler/framework/v1alpha1/framework.go:521 +0x19a
k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.ParallelizeUntil.func1(0xc00061dc40, 0xc00008e300, 0xc00000f498, 0xc0002a38c0)
	staging/src/k8s.io/client-go/util/workqueue/parallelizer.go:57 +0xbf
created by k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.ParallelizeUntil
	staging/src/k8s.io/client-go/util/workqueue/parallelizer.go:49 +0x148
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1622508]
```

e.g. here:
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/86377/pull-kubernetes-e2e-gce-alpha-features/1214511677081391104/

@kubernetes/sig-scheduling-bugs

**Comment by wojtek-t** [comment]
@ahg-g
