### ISSUE TITLE
Test panic in "AfterEach" for skipped tests during "AllNodesReady"

### ISSUE THREAD

**Issue by davidz627** [kubernetes/kubernetes#87536]
**What happened**:
When running external CSI Driver tests with the Kubernetes E2E: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_gcp-compute-persistent-disk-csi-driver/458/pull-gcp-compute-persistent-disk-csi-driver-kubernetes-integration/1220789322400141312/

We seem to be getting the following error.

```
I0124 20:03:31.324] [BeforeEach] [Testpattern: Pre-provisioned PV (block volmode)] multiVolume [Slow]
I0124 20:03:31.324]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/base.go:95
I0124 20:03:31.324] Jan 24 20:03:31.150: INFO: Driver supports dynamic provisioning, skipping PreprovisionedPV pattern
I0124 20:03:31.329] [AfterEach] [Testpattern: Pre-provisioned PV (block volmode)] multiVolume [Slow]
I0124 20:03:31.329]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:175
I0124 20:03:31.329] Jan 24 20:03:31.151: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
I0124 20:03:31.329] E0124 20:03:31.152140   71880 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
I0124 20:03:31.329] goroutine 143 [running]:
I0124 20:03:31.330] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x41cc500, 0x7c969c0)
I0124 20:03:31.330] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
I0124 20:03:31.330] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
I0124 20:03:31.330] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
I0124 20:03:31.330] panic(0x41cc500, 0x7c969c0)
I0124 20:03:31.331] 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
I0124 20:03:31.331] k8s.io/kubernetes/test/e2e/framework.AllNodesReady.func1(0xc00243cc50, 0xc00056a000, 0x7f5987da1d98)
I0124 20:03:31.331] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:1351 +0x5e
I0124 20:03:31.331] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0xc00243cde0, 0xbedf00, 0x0, 0x0)
I0124 20:03:31.332] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:209 +0x6f
I0124 20:03:31.332] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.pollImmediateInternal(0xc000894b80, 0xc00243cde0, 0xc000894b80, 0x1)
I0124 20:03:31.332] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:344 +0x2f
I0124 20:03:31.342] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.PollImmediate(0x77359400, 0x29e8d60800, 0xc00243cde0, 0x33, 0xc00243cda0)
I0124 20:03:31.343] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:340 +0x4d
I0124 20:03:31.343] k8s.io/kubernetes/test/e2e/framework.AllNodesReady(0x0, 0x0, 0x29e8d60800, 0x4aca277, 0xb)
I0124 20:03:31.343] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:1348 +0x17f
I0124 20:03:31.343] k8s.io/kubernetes/test/e2e/framework.(*Framework).AfterEach(0xc00221dcc0)
I0124 20:03:31.344] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:457 +0x43c
I0124 20:03:31.344] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc001976f00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
I0124 20:03:31.345] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113 +0xb8
I0124 20:03:31.345] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc001976f00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
I0124 20:03:31.345] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:64 +0xcf
I0124 20:03:31.346] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*SetupNode).Run(0xc0022657d8, 0x53a8460, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
I0124 20:03:31.346] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/setup_nodes.go:15 +0x64
I0124 20:03:31.346] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample.func1(0xc00243d6e0, 0xc002f444b0, 0x53a8460, 0xc0001188c0)
I0124 20:03:31.346] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:180 +0x344
I0124 20:03:31.347] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc002f444b0, 0x0, 0x53a8460, 0xc0001188c0)
I0124 20:03:31.347] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:197 +0x2e6
I0124 20:03:31.347] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc002f444b0, 0x53a8460, 0xc0001188c0)
I0124 20:03:31.347] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:138 +0x101
I0124 20:03:31.348] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc002c103c0, 0xc002f444b0, 0x4)
I0124 20:03:31.348] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:200 +0x10f
I0124 20:03:31.348] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc002c103c0, 0x1)
I0124 20:03:31.349] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:170 +0x120
I0124 20:03:31.349] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc002c103c0, 0xc0020d70f8)
I0124 20:03:31.350] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:66 +0x117
I0124 20:03:31.350] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc0001022d0, 0x7f5984092e50, 0xc001e90f00, 0x4af08de, 0x14, 0xc0026ea750, 0x3, 0x3, 0x5473440, 0xc0001188c0, ...)
I0124 20:03:31.350] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:62 +0x42b
I0124 20:03:31.351] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0x53ac980, 0xc001e90f00, 0x4af08de, 0x14, 0xc002ce41c0, 0x3, 0x4, 0x4)
I0124 20:03:31.351] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:226 +0x217
I0124 20:03:31.351] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters(0x53ac980, 0xc001e90f00, 0x4af08de, 0x14, 0xc001fae860, 0x2, 0x2, 0x2)
I0124 20:03:31.351] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:214 +0xad
I0124 20:03:31.352] k8s.io/kubernetes/test/e2e.RunE2ETests(0xc001e90f00)
I0124 20:03:31.352] 	_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:110 +0x30a
I0124 20:03:31.352] k8s.io/kubernetes/test/e2e.TestE2E(0xc001e90f00)
I0124 20:03:31.352] 	_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:111 +0x2b
I0124 20:03:31.356] testing.tRunner(0xc001e90f00, 0x4c9fc68)
I0124 20:03:31.356] 	/usr/local/go/src/testing/testing.go:909 +0xc9
I0124 20:03:31.356] created by testing.(*T).Run
I0124 20:03:31.357] 	/usr/local/go/src/testing/testing.go:960 +0x350
I0124 20:03:31.357] 
I0124 20:03:31.357] 
I0124 20:03:31.358] S [SKIPPING] in Spec Setup (BeforeEach) [0.003 seconds]
I0124 20:03:31.358] External Storage [Driver: csi-gcepd]
I0124 20:03:31.358] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/external/external.go:165
I0124 20:03:31.358]   [Testpattern: Pre-provisioned PV (block volmode)] multiVolume [Slow]
I0124 20:03:31.358]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/base.go:94
I0124 20:03:31.359]     should access to two volumes with different volume mode and retain data across pod recreation on the same node [BeforeEach]
I0124 20:03:31.359]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/multivolume.go:211
I0124 20:03:31.359] 
I0124 20:03:31.359]     Driver supports dynamic provisioning, skipping PreprovisionedPV pattern
I0124 20:03:31.359] 
I0124 20:03:31.360]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/base.go:688
```

From initial investigation it looks like this happens in the `AfterEach` during `AllNodesReady` check but only when the test is being skipped. Hunch is that maybe since the test is skipped some resources are never created or they are cleaned up already and they are nil when the `AfterEach` is called and expecting them. Kind of low priority since it doesn't make any tests actually fail.

/cc @msau42 @misterikkit 
/sig storage

**Comment by neolit123** [comment]
see https://github.com/kubernetes/kubernetes/pull/87511

**Comment by msau42** [comment]
I think https://github.com/kubernetes/kubernetes/pull/87511 should address this
