### ISSUE TITLE
kubectl apply panic, slice out of bounds

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#87755]
**What happened**:
```
$ /tmp/foo.sh
serviceaccount/istio-pilot-service-account unchanged
clusterrole.rbac.authorization.k8s.io/istio-galley-istio-system unchanged
clusterrole.rbac.authorization.k8s.io/istio-pilot-istio-system unchanged
clusterrole.rbac.authorization.k8s.io/istiod-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/istio-pilot-istio-system unchanged
clusterrolebinding.rbac.authorization.k8s.io/istiod-pilot-istio-system unchanged
validatingwebhookconfiguration.admissionregistration.k8s.io/istio-galley configured
configmap/istio unchanged
configmap/istio-validation unchanged
configmap/pilot-envoy-config unchanged
mutatingwebhookconfiguration.admissionregistration.k8s.io/istio-sidecar-injector configured
deployment.apps/istiod configured
meshpolicy.authentication.istio.io/default unchanged
panic: runtime error: slice bounds out of range [:19206] with length 4096

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/yaml.(*YAMLOrJSONDecoder).Decode(0xc0004814c8, 0x1a13f60, 0xc003411530, 0x0, 0x0)
        /workspace/anago-v1.17.2-beta.0.2+59603c6e503c87/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/yaml/decoder.go:241 +0x606
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.(*StreamVisitor).Visit(0xc003122040, 0xc00311d8c0, 0x1000, 0xc000012000)
        /workspace/anago-v1.17.2-beta.0.2+59603c6e503c87/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:576 +0xd9
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.(*FileVisitor).Visit(0xc00311d6a0, 0xc00311d8c0, 0x0, 0x0)
        /workspace/anago-v1.17.2-beta.0.2+59603c6e503c87/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:528 +0x238
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.EagerVisitorList.Visit(0xc0033ccf50, 0x1, 0x1, 0xc003122340, 0xc003122301, 0xc003122340)
        /workspace/anago-v1.17.2-beta.0.2+59603c6e503c87/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:213 +0xc5
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.FlattenListVisitor.Visit(0x1d35760, 0xc00311d6c0, 0x1d43140, 0x2da5308, 0xc0031252c0, 0xc003122300, 0xc003125410, 0xc000595728)
        /workspace/anago-v1.17.2-beta.0.2+59603c6e503c87/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:391 +0x86
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.FilteredVisitor.Visit(0x1d357a0, 0xc0031252f0, 0xc0032fe330, 0x1, 0x1, 0xc0031222c0, 0xc0034515e0, 0xc0005957d8)
        /workspace/anago-v1.17.2-beta.0.2+59603c6e503c87/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:721 +0x86
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.FlattenListVisitor.Visit(0x1d35780, 0xc003125410, 0x1d43140, 0x2da5308, 0xc0031252c0, 0xc00311d880, 0x40c1d6, 0xc000595888)
        /workspace/anago-v1.17.2-beta.0.2+59603c6e503c87/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:391 +0x86
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.ContinueOnErrorVisitor.Visit(0x1d357a0, 0xc003125470, 0xc003122280, 0x203001, 0xc003122280)
        /workspace/anago-v1.17.2-beta.0.2+59603c6e503c87/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:354 +0x9c
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.DecoratedVisitor.Visit(0x1d35720, 0xc0033ccf90, 0xc00311d820, 0x3, 0x4, 0xc003443a40, 0xc003443a40, 0x0)
        /workspace/anago-v1.17.2-beta.0.2+59603c6e503c87/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:326 +0x86
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.(*Result).Visit(0xc00330bd80, 0xc003443a40, 0x0, 0x0)
        /workspace/anago-v1.17.2-beta.0.2+59603c6e503c87/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/result.go:99 +0x62
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/apply.(*ApplyOptions).Run(0xc0005bb080, 0x0, 0x1b81740)
        /workspace/anago-v1.17.2-beta.0.2+59603c6e503c87/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/apply/apply.go:377 +0x44b
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/apply.NewCmdApply.func1(0xc0005f2c80, 0xc0000d4ea0, 0x0, 0x6)
        /workspace/anago-v1.17.2-beta.0.2+59603c6e503c87/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/apply/apply.go:170 +0xff
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0005f2c80, 0xc0000d4de0, 0x6, 0x6, 0xc0005f2c80, 0xc0000d4de0)
        /workspace/anago-v1.17.2-beta.0.2+59603c6e503c87/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0006ed680, 0xc0000d4120, 0xc00003a080, 0x8)
        /workspace/anago-v1.17.2-beta.0.2+59603c6e503c87/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/anago-v1.17.2-beta.0.2+59603c6e503c87/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
main.main()
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x1f9

```

**What you expected to happen**:

No panic; if I did something wrong at least give a friendly error message

**How to reproduce it (as minimally and precisely as possible)**:

It seems reproducible just running this script:
[repro.txt](https://github.com/kubernetes/kubernetes/files/4145085/repro.txt)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17.2 client, 1.17.0 server
- OS (e.g: `cat /etc/os-release`): linux

**Comment by howardjohn** [comment]
Well I missed something. Line 85 of the repro is some junk that got mixed in that is not yaml/json. So its pretty clear the input was invalid, the issue here is just panic vs human friendly error.

/sig cli
