### ISSUE TITLE
leaderelection panic when failing to renew lease

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#87800]
**What happened**:

Using leaderelection with ConfigMapLock, I get a panic when I fail to renew the lease.

```
2020-02-04T03:50:27.372845Z     info    failed to renew lease istio-system/istio-leader: timed out waiting for the condition
2020-02-04T03:50:27.372888Z     info    leader election lock lost
panic: assignment to entry in nil map

goroutine 44 [running]:
k8s.io/client-go/tools/leaderelection/resourcelock.(*ConfigMapLock).Update(0xc000a4a280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        k8s.io/client-go@v0.17.2/tools/leaderelection/resourcelock/configmaplock.go:90 +0x129
k8s.io/client-go/tools/leaderelection.(*LeaderElector).release(0xc00012d7a0, 0x1bf08eb00)
        k8s.io/client-go@v0.17.2/tools/leaderelection/leaderelection.go:306 +0xc9
k8s.io/client-go/tools/leaderelection.(*LeaderElector).renew(0xc00012d7a0, 0x2a49ec0, 0xc00119c180)
        k8s.io/client-go@v0.17.2/tools/leaderelection/leaderelection.go:294 +0x166
k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc00012d7a0, 0x2a49ec0, 0xc00119c140)
        k8s.io/client-go@v0.17.2/tools/leaderelection/leaderelection.go:208 +0x15d
istio.io/istio/pilot/pkg/leaderelection.(*LeaderElection).Run.func1(0xc00012d7a0, 0x2a49ec0, 0xc000e1ba00, 0xc000ac6c50)
        istio.io/istio@/pilot/pkg/leaderelection/leaderelection.go:54 +0x3f
created by istio.io/istio/pilot/pkg/leaderelection.(*LeaderElection).Run
        istio.io/istio@/pilot/pkg/leaderelection/leaderelection.go:53 +0x124
```

**What you expected to happen**: 

No crash

**How to reproduce it (as minimally and precisely as possible)**:

* Create a leaderelection setup with ReleaseOnCancel=true
* Run the program, allow a lock to be acquired.
* Change RBAC permissions to block configmap `update` access
* Eventually we fail to acquire the lock and run into the panic above

**Comment by howardjohn** [comment]
@tedyu let me know if you need help getting more info, I am not sure if its easy to reproduce or not. I can add some extra debug logging, etc

**Comment by tedyu** [comment]
I will see if I can reproduce via unit test.

**Comment by tedyu** [comment]
@howardjohn 
Can you check the log around the time of crash to see if there was the following ?
```
		klog.Infof("failed to renew lease %v: %v", desc, err)
```
Checking the events around the time of crash would also help:
```
		le.config.Lock.RecordEvent("stopped leading")
```
thanks

**Comment by howardjohn** [comment]
@tedyu I have the log snippet at the top, there is a `2020-02-04T03:50:27.372845Z     info    failed to renew lease istio-system/istio-leader: timed out waiting for the condition`

**Comment by howardjohn** [comment]
I can also hit race conditions from a unit test. I can make this a new issue if preferred. 

```
==================
WARNING: DATA RACE
Read at 0x00c0001d7920 by goroutine 8:
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).maybeReportTransition()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/leaderelection/leaderelection.go:377 +0x47
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).renew.func1()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/leaderelection/leaderelection.go:280 +0x1d0
  k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152 +0x6f
  k8s.io/apimachinery/pkg/util/wait.JitterUntil()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153 +0x108
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).renew()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88 +0x16d
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/leaderelection/leaderelection.go:208 +0x188
  istio.io/istio/pilot/pkg/leaderelection.(*LeaderElection).Run()
      /usr/local/google/home/howardjohn/go/src/istio.io/istio/pilot/pkg/leaderelection/leaderelection.go:61 +0x293

Previous write at 0x00c0001d7920 by goroutine 24:
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).tryAcquireOrRenew()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/leaderelection/leaderelection.go:345 +0xd60
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).renew.func1.1.1()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/leaderelection/leaderelection.go:269 +0x6c

Goroutine 8 (running) created at:
  istio.io/istio/pilot/pkg/leaderelection.createElection()
      /usr/local/google/home/howardjohn/go/src/istio.io/istio/pilot/pkg/leaderelection/leaderelection_test.go:44 +0x555
  istio.io/istio/pilot/pkg/leaderelection.TestLeaderElectionNoPermission()
      /usr/local/google/home/howardjohn/go/src/istio.io/istio/pilot/pkg/leaderelection/leaderelection_test.go:104 +0x427
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Goroutine 24 (finished) created at:
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).renew.func1.1()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/leaderelection/leaderelection.go:267 +0xa9
  k8s.io/apimachinery/pkg/util/wait.PollImmediateUntil()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:393 +0x38
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).renew.func1()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/leaderelection/leaderelection.go:265 +0x1a8
  k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152 +0x6f
  k8s.io/apimachinery/pkg/util/wait.JitterUntil()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153 +0x108
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).renew()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88 +0x16d
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/leaderelection/leaderelection.go:208 +0x188
  istio.io/istio/pilot/pkg/leaderelection.(*LeaderElection).Run()
      /usr/local/google/home/howardjohn/go/src/istio.io/istio/pilot/pkg/leaderelection/leaderelection.go:61 +0x293
==================
```

and similar but slightly different:
```
==================
WARNING: DATA RACE
Read at 0x00c00037c060 by goroutine 8:
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).maybeReportTransition()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/leaderelection/leaderelection.go:377 +0x47
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).renew.func1()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/leaderelection/leaderelection.go:280 +0x1d0
  k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152 +0x6f
  k8s.io/apimachinery/pkg/util/wait.JitterUntil()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153 +0x108
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).renew()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88 +0x16d
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/leaderelection/leaderelection.go:208 +0x188
  istio.io/istio/pilot/pkg/leaderelection.(*LeaderElection).Run()
      /usr/local/google/home/howardjohn/go/src/istio.io/istio/pilot/pkg/leaderelection/leaderelection.go:61 +0x293

Previous write at 0x00c00037c060 by goroutine 27:
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).tryAcquireOrRenew()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/leaderelection/leaderelection.go:371 +0x8f8
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).renew.func1.1.1()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/leaderelection/leaderelection.go:269 +0x6c

Goroutine 8 (running) created at:
  istio.io/istio/pilot/pkg/leaderelection.createElection()
      /usr/local/google/home/howardjohn/go/src/istio.io/istio/pilot/pkg/leaderelection/leaderelection_test.go:44 +0x555
  istio.io/istio/pilot/pkg/leaderelection.TestLeaderElectionNoPermission()
      /usr/local/google/home/howardjohn/go/src/istio.io/istio/pilot/pkg/leaderelection/leaderelection_test.go:104 +0x427
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199

Goroutine 27 (finished) created at:
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).renew.func1.1()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/leaderelection/leaderelection.go:267 +0xa9
  k8s.io/apimachinery/pkg/util/wait.PollImmediateUntil()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:393 +0x38
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).renew.func1()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/leaderelection/leaderelection.go:265 +0x1a8
  k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152 +0x6f
  k8s.io/apimachinery/pkg/util/wait.JitterUntil()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153 +0x108
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).renew()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88 +0x16d
  k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run()
      /usr/local/google/home/howardjohn/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/leaderelection/leaderelection.go:208 +0x188
  istio.io/istio/pilot/pkg/leaderelection.(*LeaderElection).Run()
      /usr/local/google/home/howardjohn/go/src/istio.io/istio/pilot/pkg/leaderelection/leaderelection.go:61 +0x293
==================
```

**Comment by tedyu** [comment]
There is some race around accessing observedRecord.
We can use a Lock to protect the access.

Please log a new issue.

Thanks
