### ISSUE TITLE
Kubelet Panic if nodeId is empty and no error provided

### ISSUE THREAD

**Issue by tvoinarovskyi** [kubernetes/kubernetes#87806]
**What happened**:
Kubelet dies with a panic exception if CSI plugin returns NodeId == "" and nil error. 

Exception log see at the end of the message

**What you expected to happen**:
Kubelet should just raise an error to the plugin and ignore the registration.

**How to reproduce it (as minimally and precisely as possible)**:

* Create a CSI plugin with only Node that would implement GetNodeInfo as follows:
```go
func (d *GCSDriver) NodeGetInfo(ctx context.Context, req *csi.NodeGetInfoRequest) (*csi.NodeGetInfoResponse, error) {
	return &csi.NodeGetInfoResponse{NodeId: ""}, nil
}
```
* Register it as a DaemonSet and see kublet crush

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.10-gke.17
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`): Container-Optimized OS (cos)
- Kernel (e.g. `uname -a`): -
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

Related exception
```
Feb 04 10:44:17 xxx kubelet[42861]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 04 10:44:17 xxx kubelet[42861]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2510ff7]
Feb 04 10:44:17 xxx kubelet[42861]: goroutine 1640 [running]:
Feb 04 10:44:17 xxx kubelet[42861]: k8s.io/kubernetes/pkg/volume/csi.(*csiDriverClient).NodeGetInfo.func1(0x44282a0, 0x3c15101, 0xc0016f6280)
Feb 04 10:44:17 xxx kubelet[42861]:         /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_client.go:200 +0x77
Feb 04 10:44:17 xxx kubelet[42861]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x3b9aca00, 0x4000000000000000, 0x0, 0x5, 0x0, 0xc0016f6280, 0x2a
Feb 04 10:44:17 xxx kubelet[42861]:         /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:265 +0x51
Feb 04 10:44:17 xxx kubelet[42861]: k8s.io/kubernetes/pkg/volume/csi.(*csiDriverClient).NodeGetInfo(0xc0009d3620, 0x4fb5cc0, 0xc0013ac240, 0x4fb5cc0, 0xc0013ac240, 0xc001482ff0, 0
Feb 04 10:44:17 xxx kubelet[42861]:         /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_client.go:189 +0x1e3
Feb 04 10:44:17 xxx kubelet[42861]: k8s.io/kubernetes/pkg/volume/csi.(*RegistrationHandler).RegisterPlugin(0x81aa4c0, 0xc0015ea1d0, 0xe, 0xc000c30300, 0x30, 0xc001482f50, 0x1, 0x1
Feb 04 10:44:17 xxx kubelet[42861]:         /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_plugin.go:154 +0x2e9
Feb 04 10:44:17 xxx kubelet[42861]: k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher.(*Watcher).handlePluginRegistration(0xc0004a57a0, 0xc001153a40, 0x39, 0x0, 0x0)
Feb 04 10:44:17 xxx kubelet[42861]:         /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher.go:306 +0x798
Feb 04 10:44:17 xxx kubelet[42861]: k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher.(*Watcher).handleCreateEvent(0xc0004a57a0, 0xc001153a40, 0x39, 0xc000000001, 0xc0016226fa, 0xc
Feb 04 10:44:17 xxx kubelet[42861]:         /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher.go:256 +0x50b
Feb 04 10:44:17 xxx kubelet[42861]: k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher.(*Watcher).Start.func1.1(0xc0004a57a0, 0xc001153a40, 0x39, 0x1)
Feb 04 10:44:17 xxx kubelet[42861]:         /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher.go:118 +0x1da
Feb 04 10:44:17 xxx kubelet[42861]: k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher.(*Watcher).Start.func1(0xc0004a57a0, 0xc0010b0960)
Feb 04 10:44:17 xxx kubelet[42861]:         /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher.go:129 +0x26e
Feb 04 10:44:17 xxx kubelet[42861]: created by k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher.(*Watcher).Start
Feb 04 10:44:17 xxx kubelet[42861]:         /workspace/louhi_ws/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/util/pluginwatcher/plugin_watcher.go:106 +0x24b
Feb 04 10:44:17 xxx dockerd[1103]: time="2020-02-04T10:44:17.432143154Z" level=error msg="Handler for GET /v1.38/images/json returned error: write unix /var/run/docker.sock->@: wr
Feb 04 10:44:17 xxx dockerd[1103]: http: multiple response.WriteHeader calls
```
Related line of code:
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_client.go#L161 - no check whether error is not nil before calling Error() on it.

**Comment by neolit123** [comment]
/sig node

> Kubernetes version (use kubectl version): 1.14.10-gke.17

is this the version of the kubelet too?
1.14 is out of support. is the issue reproducible with a 1.15+ kubelet?

**Comment by tedyu** [comment]
I checked the code - same defect still exists in current codebase.

**Comment by neolit123** [comment]
thanks @tedyu 
/priority important-soon

**Comment by tvoinarovskyi** [comment]
@tedyu  Wow, that was fast. Thanks!
