### ISSUE TITLE
[Failing Test] gce-windows-2019-containerd-master (ci-kubernetes-e2e-windows-containerd-gce)

### ISSUE THREAD

**Issue by hrishin** [kubernetes/kubernetes#88478]
**Which jobs are failing**:
```
gce-windows-2019-containerd-master (ci-kubernetes-e2e-windows-containerd-gce)
```

**Which test(s) are failing**:

**Since when has it been failing**:
18th Feb

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-windows-2019-containerd-master

**Reason for failure**:
```
ERROR: gcloud crashed (MetadataServerException): HTTP Error 400: Bad Request

If you would like to report this issue, please run the following command:
  gcloud feedback

To check gcloud for common problems, please run the following command:
  gcloud info --run-diagnostics
Traceback (most recent call last):
  File "/google-cloud-sdk/lib/gcloud.py", line 95, in <module>
    main()
  File "/google-cloud-sdk/lib/gcloud.py", line 91, in main
    sys.exit(gcloud_main.main())
  File "/google-cloud-sdk/lib/googlecloudsdk/gcloud_main.py", line 186, in main
    gcloud_cli.Execute()
  File "/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 1007, in Execute
    self._HandleAllErrors(exc, command_path_string, specified_arg_names)
  File "/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 1040, in _HandleAllErrors
    exceptions.HandleError(exc, command_path_string, self.__known_error_handler)
  File "/google-cloud-sdk/lib/googlecloudsdk/calliope/exceptions.py", line 527, in HandleError
    core_exceptions.reraise(exc)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/exceptions.py", line 146, in reraise
    six.reraise(type(exc_value), exc_value, tb)
  File "/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 981, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 807, in Run
    resources = command_instance.Run(args)
  File "/google-cloud-sdk/lib/surface/config/set.py", line 148, in Run
    _WarnIfSettingProjectWithNoAccess(scope, prop.Get())
  File "/google-cloud-sdk/lib/surface/config/set.py", line 51, in _WarnIfSettingProjectWithNoAccess
    projects_api.Get(project_ref, disable_api_enablement_check=True)
  File "/google-cloud-sdk/lib/googlecloudsdk/api_lib/cloudresourcemanager/projects_api.py", line 67, in Get
    client = projects_util.GetClient(api_version)
  File "/google-cloud-sdk/lib/googlecloudsdk/api_lib/cloudresourcemanager/projects_util.py", line 56, in GetClient
    return apis.GetClientInstance(_API_NAME, version)
  File "/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis.py", line 325, in GetClientInstance
    use_google_auth)
  File "/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis_internal.py", line 164, in _GetClientInstance
    response_encoding=http_creds.ENCODING, use_google_auth=use_google_auth)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/http.py", line 93, in Http
    allow_account_impersonation=allow_account_impersonation)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 418, in LoadIfEnabled
    return Load(allow_account_impersonation=allow_account_impersonation)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 463, in Load
    cred = _Load(account, scopes, prevent_refresh)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 518, in _Load
    cred = STATIC_CREDENTIAL_PROVIDERS.GetCredentials(account)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 205, in GetCredentials
    cred = provider.GetCredentials(account)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 258, in GetCredentials
    return AcquireFromGCE(account)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 921, in AcquireFromGCE
    Refresh(credentials)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 636, in Refresh
    include_license=gce_include_license)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce.py", line 88, in Inner
    return f(self, *args, **kwargs)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce.py", line 278, in GetIdToken
    http_errors_to_ignore=(404,))
  File "/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 292, in DecoratedFunction
    exceptions.reraise(to_reraise[1], tb=to_reraise[2])
  File "/google-cloud-sdk/lib/googlecloudsdk/core/exceptions.py", line 146, in reraise
    six.reraise(type(exc_value), exc_value, tb)
  File "/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 162, in TryFunc
    return func(*args, **kwargs), None
  File "/google-cloud-sdk/lib/googlecloudsdk/core/credentials/gce.py", line 64, in _ReadNoProxyWithCleanFailures
    raise MetadataServerException(e)
googlecloudsdk.core.credentials.gce.MetadataServerException: HTTP Error 400: Bad Request
```

**Anything else we need to know**:
/sig windows
/sig release
/cc @kubernetes/ci-signal
/priority critical-urgent
/milestone v1.18

**Comment by hasheddan** [comment]
This is currently being tracked in #86788

/close

**Comment by hrishin** [comment]
Thank you @hasheddan :hugs:
