### ISSUE TITLE
[kubemark] kubemark hollow nodes panic on starts

### ISSUE THREAD

**Issue by jfbai** [kubernetes/kubernetes#88604]
**What happened**:

hollow nodes were running with no errors, but all nodes suddenly run into `CrashLoopBack` status for several minutes (maybe 10min+), and then recover. From the logs, I observed a panic

```
I0225 12:00:09.730501       6 eviction_manager.go:230] eviction manager: synchronize housekeeping
E0225 12:00:09.730565       6 eviction_manager.go:247] eviction manager: failed to get summary stats: failed to get root cgroup stats: failed to get cgroup stats for "/": unexpected number of containers: 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1a9bb55]

goroutine 927 [running]:
k8s.io/kubernetes/pkg/kubelet/dockershim.(*NativeExecHandler).ExecInContainer(0x72896c0, 0x4c3bac0, 0xc000794000, 0xc0012b1c20, 0xc000333dc0, 0x1, 0x1, 0x0, 0x0, 0x4b29b80, ...)
        /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/dockershim/exec.go:118 +0x555
k8s.io/kubernetes/pkg/kubelet/dockershim.(*streamingRuntime).exec(0xc0003daa80, 0xc00104a2e0, 0x10, 0xc000333dc0, 0x1, 0x1, 0x0, 0x0, 0x4b29b80, 0xc000333dd0, ...)
        /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_streaming.go:59 +0x165
k8s.io/kubernetes/pkg/kubelet/dockershim.(*dockerService).ExecSync(0xc00083c160, 0x4ba25c0, 0xc000c36bd0, 0xc000c36c00, 0xc00083c160, 0xc000c36bd0, 0xc000d6fa90)
        /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/dockershim/docker_streaming.go:83 +0x18d
k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2._RuntimeService_ExecSync_Handler(0x43ff040, 0xc00083c160, 0x4ba25c0, 0xc000c36bd0, 0xc0003cdf80, 0x0, 0x4ba25c0, 0xc000c36bd0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/api.pb.go:4417 +0x217
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc00068ae00, 0x4bfeae0, 0xc000772800, 0xc00079dc00, 0xc000865b60, 0x7160e50, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:1011 +0x4bd
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).handleStream(0xc00068ae00, 0x4bfeae0, 0xc000772800, 0xc00079dc00, 0x0)
        /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:1249 +0x12a4
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0004add00, 0xc00068ae00, 0x4bfeae0, 0xc000772800, 0xc00079dc00)
        /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:680 +0xbb
created by k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:678 +0xa1
```

Seems exec command was called, but I didn't find any exec call from the apiserver side.

**What you expected to happen**:

kubemark nodes run without panic

**How to reproduce it (as minimally and precisely as possible)**:

It occurs randomly, I have no idea about how to reproduce currently.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.8
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by gongguan** [comment]
It looks like actions such as `kubectl exec` triggered this panic, because fake docker client hasn't inject an `inspect_exec` error.

**Comment by gongguan** [comment]
I'm not sure it should be fixed, because kubemark doesn't use fake docker now.

**Comment by jfbai** [comment]
> It looks like actions such as `kubectl exec` triggered this panic, because fake docker client hasn't inject an `inspect_exec` error.

Thanks a lot, but I didn't find any logs about `exec` call and almost all the nodes are paniced.

**Comment by jfbai** [comment]
https://github.com/kubernetes/kubernetes/issues/84855

known issue, fixed in master branch.

cc @gongguan

/close
