### ISSUE TITLE
Panic in kubelet Run does not exit, creates multiple parallel Run goroutines

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#88779]
If the kubelet Run method panics (e.g. https://github.com/kubernetes/kubernetes/pull/88915)  Run gets called multiple times:

https://github.com/kubernetes/kubernetes/blob/cb3856042212fcc85ea12c95e5d17ab7f6c286c8/cmd/kubelet/app/server.go#L1131-L1134

That would start multiple goroutines calling relist() concurrently

https://github.com/kubernetes/kubernetes/blob/cb3856042212fcc85ea12c95e5d17ab7f6c286c8/pkg/kubelet/kubelet.go#L1450-L1451

https://github.com/kubernetes/kubernetes/blob/cb3856042212fcc85ea12c95e5d17ab7f6c286c8/pkg/kubelet/pleg/generic.go#L129-L132

From a PR that doesn't touch the PLEG (but might stress it?), panic in kubelet from pleg:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88440/pull-kubernetes-e2e-kind/1234952132935815168

```
Mar 03 19:21:03 kind-worker2 kubelet[88624]: fatal error: concurrent map read and map write
Mar 03 19:21:03 kind-worker2 kubelet[88624]: goroutine 1420 [running]:
Mar 03 19:21:03 kind-worker2 kubelet[88624]: runtime.throw(0x43641ed, 0x21)
Mar 03 19:21:03 kind-worker2 kubelet[88624]:         GOROOT/src/runtime/panic.go:774 +0x72 fp=0xc0011f57e8 sp=0xc0011f57b8 pc=0x432682
Mar 03 19:21:03 kind-worker2 kubelet[88624]: runtime.mapaccess2_faststr(0x3ddf9e0, 0xc000706690, 0xc00084f1a0, 0x24, 0xc0004b93c8, 0x1)
Mar 03 19:21:03 kind-worker2 kubelet[88624]:         GOROOT/src/runtime/map_faststr.go:116 +0x48f fp=0xc0011f5858 sp=0xc0011f57e8 pc=0x4160cf
Mar 03 19:21:03 kind-worker2 kubelet[88624]: k8s.io/kubernetes/pkg/kubelet/pleg.podRecords.setCurrent(0xc000706690, 0xc001e44600, 0x1d, 0x20)
Mar 03 19:21:03 kind-worker2 kubelet[88624]:         pkg/kubelet/pleg/generic.go:464 +0x149 fp=0xc0011f5910 sp=0xc0011f5858 pc=0x3318999
Mar 03 19:21:03 kind-worker2 kubelet[88624]: k8s.io/kubernetes/pkg/kubelet/pleg.(*GenericPLEG).relist(0xc000788960)
Mar 03 19:21:03 kind-worker2 kubelet[88624]:         pkg/kubelet/pleg/generic.go:214 +0x2c9 fp=0xc0011f5e20 sp=0xc0011f5910 pc=0x3316a89
Mar 03 19:21:03 kind-worker2 kubelet[88624]: k8s.io/kubernetes/pkg/kubelet/pleg.(*GenericPLEG).relist-fm()
Mar 03 19:21:03 kind-worker2 kubelet[88624]:         pkg/kubelet/pleg/generic.go:190 +0x2a fp=0xc0011f5e38 sp=0xc0011f5e20 pc=0x3318cca
Mar 03 19:21:03 kind-worker2 kubelet[88624]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00016fbc0
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/88440/pull-kubernetes-e2e-kind/1234916134344462336/artifacts/logs/kind-worker2/kubelet.log

**Comment by smarterclayton** [comment]
Could be related to #88440 but not seeing how yet

**Comment by smarterclayton** [comment]
I don't see how this map could have escaped the PLEG unless it was started twice.  I see no signs of that.  This appears to be code that should never fail this way if the go runtime is correct (I don't see the pod record object escaping this type, and I see no public interface that touches a field outside of an atomic accessor).

**Comment by smarterclayton** [comment]
Note nothing in this package has changed since last year in July (all the metrics stuff should already be thread safe)

**Comment by smarterclayton** [comment]
So far 88440 appears to be able to consistently reproduce it (because we improve the efficiency of some failure modes and change some loops), but I don't see many other kind jobs failing on it.  So this PR exacerbates (but does not cause?) the issue, potentially.

**Comment by smarterclayton** [comment]
88440 now no longer causes this after a rebase.  I am suspicious that this may have been something related to how the code was built in go (environment, optimizations, strange merge) but I don't have any evidence to support that.  Will keep watching.

**Comment by gongguan** [comment]
I think different relist period may trigger the race of  `GenericPLEG.podRecords`. 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/pleg/generic.go#L131
What do you think @smarterclayton ?

**Comment by sjenning** [comment]
Looking at the logs there are 3 fatal errors that occur: `concurrent map iteration and map write`, `concurrent map read and map write` (2x), and  `fatal error: concurrent map writes`.  All are caused by concurrent `relist()` calls.
```
$ grep -e "fatal error" -e "relist(" kubelet.log 
Mar 03 19:18:06 kind-worker2 kubelet[670]: fatal error: concurrent map read and map write
Mar 03 19:18:06 kind-worker2 kubelet[670]: k8s.io/kubernetes/pkg/kubelet/pleg.(*GenericPLEG).relist(0xc000c23aa0)
Mar 03 19:18:07 kind-worker2 kubelet[670]: k8s.io/kubernetes/pkg/kubelet/pleg.(*GenericPLEG).relist(0xc000c23aa0)
Mar 03 19:21:03 kind-worker2 kubelet[88624]: fatal error: concurrent map read and map write
Mar 03 19:21:03 kind-worker2 kubelet[88624]: k8s.io/kubernetes/pkg/kubelet/pleg.(*GenericPLEG).relist(0xc000788960)
Mar 03 19:21:03 kind-worker2 kubelet[88624]: k8s.io/kubernetes/pkg/kubelet/pleg.(*GenericPLEG).relist(0xc000788960)
Mar 03 19:21:55 kind-worker2 kubelet[107570]: fatal error: concurrent map writes
Mar 03 19:21:55 kind-worker2 kubelet[107570]: k8s.io/kubernetes/pkg/kubelet/pleg.(*GenericPLEG).relist(0xc0002a1e00)
Mar 03 19:21:55 kind-worker2 kubelet[107570]: k8s.io/kubernetes/pkg/kubelet/pleg.(*GenericPLEG).relist(0xc0002a1e00)
Mar 03 19:27:26 kind-worker2 kubelet[111302]: fatal error: concurrent map iteration and map write
Mar 03 19:27:26 kind-worker2 kubelet[111302]: k8s.io/kubernetes/pkg/kubelet/pleg.(*GenericPLEG).relist(0xc0005dd500)
Mar 03 19:27:26 kind-worker2 kubelet[111302]: k8s.io/kubernetes/pkg/kubelet/pleg.(*GenericPLEG).relist(0xc0005dd500)
```

**Comment by gongguan** [comment]
```
Mar 03 19:21:03 kind-worker2 kubelet[88624]: k8s.io/kubernetes/pkg/kubelet/pleg.podRecords.setCurrent(0xc000706690, 0xc001e44600, 0x1d, 0x20)
Mar 03 19:21:03 kind-worker2 kubelet[88624]:         pkg/kubelet/pleg/generic.go:464 +0x149 fp=0xc0011f5910 sp=0xc0011f5858 pc=0x3318999
Mar 03 19:21:03 kind-worker2 kubelet[88624]: k8s.io/kubernetes/pkg/kubelet/pleg.(*GenericPLEG).relist(0xc000788960)
Mar 03 19:21:03 kind-worker2 kubelet[88624]:         pkg/kubelet/pleg/generic.go:214 +0x2c9 fp=0xc0011f5e20 sp=0xc0011f5910 pc=0x3316a89
```
```
Mar 03 19:21:03 kind-worker2 kubelet[88624]: k8s.io/kubernetes/pkg/kubelet/pleg.getContainersFromPods(0xc000a8fae8, 0x2, 0x2, 0x24, 0xc0004b9568, 0xc001214401)
Mar 03 19:21:03 kind-worker2 kubelet[88624]:         pkg/kubelet/pleg/generic.go:322 +0x335
Mar 03 19:21:03 kind-worker2 kubelet[88624]: k8s.io/kubernetes/pkg/kubelet/pleg.(*GenericPLEG).relist(0xc000788960)
Mar 03 19:21:03 kind-worker2 kubelet[88624]:         pkg/kubelet/pleg/generic.go:222 +0x61d
```
these concurrent operations happens in different place, I wonder two goroutines use podRecords at the same time (after all 1 second relist period is too short).

**Comment by liggitt** [comment]
is it possible the kubelet is panicing (e.g. https://github.com/kubernetes/kubernetes/pull/88915) and Run is getting called multiple times?

https://github.com/kubernetes/kubernetes/blob/cb3856042212fcc85ea12c95e5d17ab7f6c286c8/cmd/kubelet/app/server.go#L1131-L1134

Would that start multiple goroutines calling relist() concurrently?

https://github.com/kubernetes/kubernetes/blob/cb3856042212fcc85ea12c95e5d17ab7f6c286c8/pkg/kubelet/kubelet.go#L1450-L1451

https://github.com/kubernetes/kubernetes/blob/cb3856042212fcc85ea12c95e5d17ab7f6c286c8/pkg/kubelet/pleg/generic.go#L129-L132

**Comment by liggitt** [comment]
it looks like the kubelet does not exit on panics:

https://github.com/kubernetes/kubernetes/blob/cb3856042212fcc85ea12c95e5d17ab7f6c286c8/cmd/kubelet/app/options/options.go#L61-L62

https://github.com/kubernetes/kubernetes/blob/cb3856042212fcc85ea12c95e5d17ab7f6c286c8/cmd/kubelet/app/server.go#L757

**Comment by liggitt** [comment]
The first panic seen in that kubelet log is:
```
Mar 03 19:17:52 kind-worker2 kubelet[670]: E0303 19:17:52.219064     670 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
Mar 03 19:17:52 kind-worker2 kubelet[670]: goroutine 261 [running]:
Mar 03 19:17:52 kind-worker2 kubelet[670]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3f93440, 0xc0017c6a80)
Mar 03 19:17:52 kind-worker2 kubelet[670]:         staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
Mar 03 19:17:52 kind-worker2 kubelet[670]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Mar 03 19:17:52 kind-worker2 kubelet[670]:         staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
Mar 03 19:17:52 kind-worker2 kubelet[670]: panic(0x3f93440, 0xc0017c6a80)
Mar 03 19:17:52 kind-worker2 kubelet[670]:         GOROOT/src/runtime/panic.go:679 +0x1b2
Mar 03 19:17:52 kind-worker2 kubelet[670]: k8s.io/kubernetes/pkg/kubelet/status.(*manager).TerminatePod(0xc00098d3e0, 0xc00230a400)
Mar 03 19:17:52 kind-worker2 kubelet[670]:         pkg/kubelet/status/status_manager.go:345 +0x58d
Mar 03 19:17:52 kind-worker2 kubelet[670]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).dispatchWork(0xc000618a80, 0xc00230a400, 0x1, 0x0, 0xbf8fc9380d0ce971, 0x6fedae26dc, 0x6f91000)
Mar 03 19:17:52 kind-worker2 kubelet[670]:         pkg/kubelet/kubelet.go:2010 +0x650
Mar 03 19:17:52 kind-worker2 kubelet[670]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).HandlePodUpdates(0xc000618a80, 0xc0009d8490, 0x1, 0x1)
Mar 03 19:17:52 kind-worker2 kubelet[670]:         pkg/kubelet/kubelet.go:2098 +0x1a9
Mar 03 19:17:52 kind-worker2 kubelet[670]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoopIteration(0xc000618a80, 0xc0009fee40, 0x4b42540, 0xc000618a80, 0xc000efe9c0, 0xc000efea20, 0xc000c23a40, 0xc000ba6e01)
Mar 03 19:17:52 kind-worker2 kubelet[670]:         pkg/kubelet/kubelet.go:1925 +0x3c7
Mar 03 19:17:52 kind-worker2 kubelet[670]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoop(0xc000618a80, 0xc0009fee40, 0x4b42540, 0xc000618a80)
Mar 03 19:17:52 kind-worker2 kubelet[670]:         pkg/kubelet/kubelet.go:1855 +0x371
Mar 03 19:17:52 kind-worker2 kubelet[670]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run(0xc000618a80, 0xc0009fee40)
Mar 03 19:17:52 kind-worker2 kubelet[670]:         pkg/kubelet/kubelet.go:1452 +0x27c
Mar 03 19:17:52 kind-worker2 kubelet[670]: k8s.io/kubernetes/cmd/kubelet/app.startKubelet.func1()
```

**Comment by sjenning** [comment]
@liggitt ah I see.  For the record, it does look like the kubelet crashes on the `fatal error`s.
```
Mar 03 19:18:07 kind-worker2 kubelet[670]: created by k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch
Mar 03 19:18:07 kind-worker2 kubelet[670]:         staging/src/k8s.io/client-go/tools/cache/reflector.go:322 +0x28f
Mar 03 19:18:08 kind-worker2 systemd[1]: kubelet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 03 19:18:08 kind-worker2 systemd[1]: kubelet.service: Failed with result 'exit-code'.
Mar 03 19:18:09 kind-worker2 systemd[1]: kubelet.service: Service RestartSec=1s expired, scheduling restart.
```
kubelet pid changes after each one.

But it makes sense if the kubelet isn't fully crashing on the first panic, leading to concurrent runs of the `GenericPLEG`, thus leading to the eventual fatal error.

**Comment by sjenning** [comment]
Yeah....
```
$ grep "Observed a panic" kubelet.log 
Mar 03 19:17:52 kind-worker2 kubelet[670]: E0303 19:17:52.219064     670 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
Mar 03 19:17:54 kind-worker2 kubelet[670]: E0303 19:17:54.693242     670 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
Mar 03 19:17:57 kind-worker2 kubelet[670]: E0303 19:17:57.967107     670 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
Mar 03 19:18:13 kind-worker2 kubelet[88624]: E0303 19:18:13.755935   88624 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
Mar 03 19:18:14 kind-worker2 kubelet[88624]: E0303 19:18:14.414551   88624 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
Mar 03 19:18:14 kind-worker2 kubelet[88624]: E0303 19:18:14.807793   88624 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
Mar 03 19:21:06 kind-worker2 kubelet[107570]: E0303 19:21:06.754161  107570 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
Mar 03 19:21:58 kind-worker2 kubelet[111302]: E0303 19:21:58.168598  111302 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
Mar 03 19:27:30 kind-worker2 kubelet[135453]: E0303 19:27:30.282614  135453 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
```
I think that is the real issue

**Comment by liggitt** [comment]
```
$ egrep 'Observed a panic|concurrent map' kubelet.log.txt 
Mar 03 19:17:52 kind-worker2 kubelet[670]: E0303 19:17:52.219064     670 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
Mar 03 19:17:54 kind-worker2 kubelet[670]: E0303 19:17:54.693242     670 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
Mar 03 19:17:57 kind-worker2 kubelet[670]: E0303 19:17:57.967107     670 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
Mar 03 19:18:06 kind-worker2 kubelet[670]: fatal error: concurrent map read and map write
Mar 03 19:18:13 kind-worker2 kubelet[88624]: E0303 19:18:13.755935   88624 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
Mar 03 19:18:14 kind-worker2 kubelet[88624]: E0303 19:18:14.414551   88624 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
Mar 03 19:18:14 kind-worker2 kubelet[88624]: E0303 19:18:14.807793   88624 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
Mar 03 19:21:03 kind-worker2 kubelet[88624]: fatal error: concurrent map read and map write
Mar 03 19:21:06 kind-worker2 kubelet[107570]: E0303 19:21:06.754161  107570 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
Mar 03 19:21:55 kind-worker2 kubelet[107570]: fatal error: concurrent map writes
Mar 03 19:21:58 kind-worker2 kubelet[111302]: E0303 19:21:58.168598  111302 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
Mar 03 19:27:26 kind-worker2 kubelet[111302]: fatal error: concurrent map iteration and map write
Mar 03 19:27:30 kind-worker2 kubelet[135453]: E0303 19:27:30.282614  135453 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
```

the panic makes another Run loop start, which sets up a concurrent map read/write, which actually causes the process exit :-)

**Comment by liggitt** [comment]
retitled and bumped priority

**Comment by sjenning** [comment]
We were _just_ talking about this in sig-node yesterday; changing the kubelet to crash on panic.  This is definitely evidence that we should do that.  I didn't realize this was possible with the panic recovery.
/cc @derekwaynecarr @dchen1107

**Comment by liggitt** [comment]
So there are two issues here:

1. Fix the [observed panic](https://github.com/kubernetes/kubernetes/issues/88779#issuecomment-597664682)
2. Fix the kubelet to exit on panic, not live on in zombie state

**Comment by liggitt** [comment]
looks like the particular panic was an actual bug in that PR: https://github.com/kubernetes/kubernetes/compare/782bf3341b7c9a60d151c237626d654b08976b91..5719d3138c3e3c27b3b511a8754343594fa95b46#diff-ea8c11a933d6d6c22c0c12b6a38c4b46R338

**Comment by tedyu** [comment]
Should we change the default for ReallyCrashForTesting to true ?

**Comment by liggitt** [comment]
Options:

1. [Remove the wait.Until wrapper around kubelet.Run](https://github.com/kubernetes/kubernetes/blob/cb3856042212fcc85ea12c95e5d17ab7f6c286c8/cmd/kubelet/app/server.go#L1131-L1134). Run() exiting is never expected, and calling it again is never correct.

2. Remove ReallyCrashForTesting completely and leave the panic handler at its default behavior of exiting. This would affect all uses of HandleCrash, which at first glance, looks like these for the kubelet:

```
$ grep -R '\.HandleCrash' cmd pkg staging | egrep -v 'test|apiserver|kubectl|controller|proxy|scheduler|ssh'
pkg/util/goroutinemap/goroutinemap.go:		defer k8sRuntime.HandleCrash()
pkg/kubelet/prober/worker.go:	defer runtime.HandleCrash(func(_ interface{}) { keepGoing = true })
pkg/kubelet/volumemanager/volume_manager.go:	defer runtime.HandleCrash()
pkg/kubelet/pod_workers.go:			defer runtime.HandleCrash()
pkg/kubelet/server/remotecommand/httpstream.go:	defer runtime.HandleCrash()
pkg/kubelet/kuberuntime/kuberuntime_container.go:		defer utilruntime.HandleCrash()
pkg/kubelet/kuberuntime/kuberuntime_container.go:			defer utilruntime.HandleCrash()
pkg/kubelet/oom/oom_watcher_linux.go:		defer runtime.HandleCrash()
pkg/kubelet/container/resize.go:		defer runtime.HandleCrash()
pkg/kubelet/pluginmanager/plugin_manager.go:	defer runtime.HandleCrash()
pkg/volume/csi/csi_plugin.go:		defer utilruntime.HandleCrash()
pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:		defer k8sRuntime.HandleCrash()
staging/src/k8s.io/client-go/tools/record/event.go:		defer utilruntime.HandleCrash()
staging/src/k8s.io/client-go/tools/record/event.go:		defer utilruntime.HandleCrash()
staging/src/k8s.io/client-go/tools/cache/shared_informer.go:	defer utilruntime.HandleCrash()
staging/src/k8s.io/client-go/tools/cache/shared_informer.go:	defer utilruntime.HandleCrash()
staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go:		runtime.HandleCrash()
staging/src/k8s.io/client-go/tools/events/event_recorder.go:		defer utilruntime.HandleCrash()
staging/src/k8s.io/client-go/tools/events/event_broadcaster.go:		defer utilruntime.HandleCrash()
staging/src/k8s.io/client-go/tools/pager/pager.go:		defer utilruntime.HandleCrash()
staging/src/k8s.io/client-go/tools/remotecommand/errorstream.go:		defer runtime.HandleCrash()
staging/src/k8s.io/client-go/tools/remotecommand/v3.go:		defer runtime.HandleCrash()
staging/src/k8s.io/client-go/tools/remotecommand/v2.go:			defer runtime.HandleCrash()
staging/src/k8s.io/client-go/tools/remotecommand/v2.go:			defer runtime.HandleCrash()
staging/src/k8s.io/client-go/tools/remotecommand/v2.go:		defer runtime.HandleCrash()
staging/src/k8s.io/client-go/tools/remotecommand/v2.go:		defer runtime.HandleCrash()
staging/src/k8s.io/client-go/transport/cert_rotation.go:	defer utilruntime.HandleCrash()
staging/src/k8s.io/client-go/util/workqueue/parallelizer.go:			defer utilruntime.HandleCrash()
staging/src/k8s.io/client-go/util/workqueue/delaying_queue.go:	defer utilruntime.HandleCrash()
staging/src/k8s.io/client-go/discovery/discovery_client.go:				defer utilruntime.HandleCrash()
staging/src/k8s.io/client-go/discovery/cached/memory/memcache.go:				defer utilruntime.HandleCrash()
staging/src/k8s.io/client-go/examples/workqueue/main.go:	defer runtime.HandleCrash()
staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:			defer runtime.HandleCrash()
staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:	defer runtime.HandleCrash()
staging/src/k8s.io/apimachinery/pkg/watch/streamwatcher.go:	defer utilruntime.HandleCrash()
```

**Comment by tedyu** [comment]
Working on a patch for option #1 now.

**Comment by roycaihw** [comment]
Yes we talked about making kubelet actually crash in the sig meeting yesterday. I think we had this consensus back in [2016](https://github.com/kubernetes/kubernetes/pull/28800#issuecomment-231911897), but kubelet wasn't changed because of the [flag](https://github.com/kubernetes/kubernetes/pull/3577). 

Yesterday I think we agreed it's good to make kubelet crash for debugging purpose. One concern was if there was a panic caused by plugin / container runtime, kubelet could end up in a crashlooping state. For that concern, we talked about every cluster setup should have some monitoring around how many times / how frequent kubelet restarted. systemd service has a restart counter. I haven't dig into whether it has the restart interval / frequency information
- https://github.com/systemd/systemd/pull/6495
- https://github.com/prometheus/node_exporter/blob/master/collector/systemd_linux.go#L103

I'm working on a PR to remove the ReallyCrashForTesting flag. I think we should do that in 1.19 and have release notes about the behavior change and monitoring suggestions.

**Comment by smarterclayton** [comment]
We should never wait.Until things that don't tolerate it.  So removing the wait.Until is appropriate.

**Comment by liggitt** [comment]
I would recommend removing the wait.Until around the Run() invocation in 1.15-1.18, since that is known to be wrong, and consider the removal of ReallyCrashForTesting in 1.19

**Comment by smarterclayton** [comment]
Agreed, that is the safest approach.
