### ISSUE TITLE
kube-apiserver v1.18.0-beta.1 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ProdanLabs** [kubernetes/kubernetes#88946]
```
Mar  8 15:11:48 k8s-master02 kube-apiserver: I0308 15:11:48.529082   16626 flags.go:33] FLAG: --v="2"
Mar  8 15:11:48 k8s-master02 kube-apiserver: I0308 15:11:48.529086   16626 flags.go:33] FLAG: --version="false"
Mar  8 15:11:48 k8s-master02 kube-apiserver: I0308 15:11:48.529092   16626 flags.go:33] FLAG: --vmodule=""
Mar  8 15:11:48 k8s-master02 kube-apiserver: I0308 15:11:48.529096   16626 flags.go:33] FLAG: --watch-cache="true"
Mar  8 15:11:48 k8s-master02 kube-apiserver: I0308 15:11:48.529100   16626 flags.go:33] FLAG: --watch-cache-sizes="[]"
Mar  8 15:11:48 k8s-master02 kube-apiserver: I0308 15:11:48.529116   16626 server.go:639] external host was not specified, using 172.19.0.13
Mar  8 15:11:48 k8s-master02 kube-apiserver: I0308 15:11:48.529122   16626 server.go:682] Initializing cache sizes based on 0MB limit
Mar  8 15:11:48 k8s-master02 kube-apiserver: I0308 15:11:48.529332   16626 server.go:153] Version: v1.18.0-beta.1
Mar  8 15:11:48 k8s-master02 kube-apiserver: panic: runtime error: invalid memory address or nil pointer dereference
Mar  8 15:11:48 k8s-master02 kube-apiserver: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1833ad5]
Mar  8 15:11:48 k8s-master02 kube-apiserver: goroutine 1 [running]:
Mar  8 15:11:48 k8s-master02 kube-apiserver: k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/audit/webhook.loadWebhook(0x7ffca5e07ac7, 0x28, 0x4516b30, 0xc, 0x4516b3d, 0x2, 0x2540be400, 0x4, 0x50ddd60, 0xc000205680)
Mar  8 15:11:48 k8s-master02 kube-apiserver: /workspace/anago-v1.18.0-beta.0.236+78ccbd44840fcd/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/audit/webhook/webhook.go:66 +0x185
Mar  8 15:11:48 k8s-master02 kube-apiserver: k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/audit/webhook.NewBackend(0x7ffca5e07ac7, 0x28, 0x4516b30, 0xc, 0x4516b3d, 0x2, 0x2540be400, 0x0, 0xc000511ce0, 0x2, ...)
Mar  8 15:11:48 k8s-master02 kube-apiserver: /workspace/anago-v1.18.0-beta.0.236+78ccbd44840fcd/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/plugin/pkg/audit/webhook/webhook.go:90 +0x77
Mar  8 15:11:48 k8s-master02 kube-apiserver: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/options.(*AuditWebhookOptions).newUntruncatedBackend(0xc0009c05b0, 0x5076780, 0xc000116ae0, 0x50ec720, 0xc000511ce0)
Mar  8 15:11:48 k8s-master02 kube-apiserver: /workspace/anago-v1.18.0-beta.0.236+78ccbd44840fcd/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/options/audit.go:595 +0x5f
Mar  8 15:11:48 k8s-master02 kube-apiserver: k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/options.(*AuditOptions).ApplyTo(0xc0009c0500, 0xc00037dd40, 0xc00055e400, 0x5180920, 0xc000575ea0, 0xc000cdd620, 0xc000d18f88, 0x0, 0x0)
Mar  8 15:11:48 k8s-master02 kube-apiserver: /workspace/anago-v1.18.0-beta.0.236+78ccbd44840fcd/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/options/audit.go:326 +0x18d
Mar  8 15:11:48 k8s-master02 kube-apiserver: k8s.io/kubernetes/cmd/kube-apiserver/app.buildGenericConfig(0xc0009b9080, 0xc0009c0640, 0x40502c0, 0x30, 0x30, 0x0, 0xd0, 0xc000a83110, 0x30, 0x30, ...)
Mar  8 15:11:48 k8s-master02 kube-apiserver: /workspace/anago-v1.18.0-beta.0.236+78ccbd44840fcd/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:525 +0xef4
Mar  8 15:11:48 k8s-master02 systemd: kube-apiserver.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Mar  8 15:11:48 k8s-master02 kube-apiserver: k8s.io/kubernetes/cmd/kube-apiserver/app.CreateKubeAPIServerConfig(0xc0009b9080, 0x0, 0x0, 0xc0009c0640, 0x0, 0x0, 0xc000a59500, 0x40bfe4, 0x7f893a0a07f0, 0x0, ...)
Mar  8 15:11:48 k8s-master02 kube-apiserver: /workspace/anago-v1.18.0-beta.0.236+78ccbd44840fcd/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:284 +0x50
Mar  8 15:11:48 k8s-master02 kube-apiserver: k8s.io/kubernetes/cmd/kube-apiserver/app.CreateServerChain(0xc0009b9080, 0xc0000a5620, 0x450da96, 0xc, 0xc000a59c48)
Mar  8 15:11:48 k8s-master02 kube-apiserver: /workspace/anago-v1.18.0-beta.0.236+78ccbd44840fcd/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:175 +0x74
Mar  8 15:11:48 k8s-master02 kube-apiserver: k8s.io/kubernetes/cmd/kube-apiserver/app.Run(0xc0009b9080, 0xc0000a5620, 0x0, 0x0)
Mar  8 15:11:48 k8s-master02 kube-apiserver: /workspace/anago-v1.18.0-beta.0.236+78ccbd44840fcd/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:155 +0x101
Mar  8 15:11:48 k8s-master02 kube-apiserver: k8s.io/kubernetes/cmd/kube-apiserver/app.NewAPIServerCommand.func1(0xc0007ff400, 0xc000784c00, 0x0, 0x3b, 0x0, 0x0)
Mar  8 15:11:48 k8s-master02 kube-apiserver: /workspace/anago-v1.18.0-beta.0.236+78ccbd44840fcd/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:122 +0x104
Mar  8 15:11:48 k8s-master02 kube-apiserver: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0007ff400, 0xc00004c410, 0x3b, 0x3f, 0xc0007ff400, 0xc00004c410)
Mar  8 15:11:48 k8s-master02 kube-apiserver: /workspace/anago-v1.18.0-beta.0.236+78ccbd44840fcd/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:826 +0x460
Mar  8 15:11:48 k8s-master02 kube-apiserver: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0007ff400, 0x15fa42a80dcc36ea, 0x768c960, 0xc000078750)
Mar  8 15:11:48 k8s-master02 kube-apiserver: /workspace/anago-v1.18.0-beta.0.236+78ccbd44840fcd/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
Mar  8 15:11:48 k8s-master02 kube-apiserver: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
Mar  8 15:11:48 k8s-master02 kube-apiserver: /workspace/anago-v1.18.0-beta.0.236+78ccbd44840fcd/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
Mar  8 15:11:48 k8s-master02 kube-apiserver: main.main()
Mar  8 15:11:48 k8s-master02 systemd: Failed to start Kubernetes API Service.
Mar  8 15:11:48 k8s-master02 kube-apiserver: _output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/apiserver.go:43 +0xcd
Mar  8 15:11:48 k8s-master02 systemd: Unit kube-apiserver.service entered failed state.
Mar  8 15:11:48 k8s-master02 systemd: kube-apiserver.service failed.
Mar  8 15:11:53 k8s-master02 systemd: Stopped Kubernetes API Service.
```

**Comment by ProdanLabs** [comment]
`audit-webhook-config-file` Parameter configuration is incorrect
