### ISSUE TITLE
kube-scheduler panic in NodesHaveSameTopologyKey

### ISSUE THREAD

**Issue by xtroncode** [kubernetes/kubernetes#89410]
**What happened**:
We are facing regular kube-scheduler panics
**What you expected to happen**:
kube-scheduler should not panic
**How to reproduce it (as minimally and precisely as possible)**:
Sorry. I haven't been able to reproduce it, it started happening after we upgraded to 1.16.6. 
**Anything else we need to know?**:
panic logs 
```sh
E0323 14:55:21.352508 1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)goroutine 369514 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1810be0, 0x2b37e00)
/workspace/anago-v1.16.6-beta.0.3+72c30166b2105c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
/usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
panic(0x1810be0, 0x2b37e00)
/workspace/anago-v1.16.6-beta.0.3+72c30166b2105c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
/workspace/anago-v1.16.6-beta.0.3+72c30166b2105c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/util/topologies.go:58
k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/util.NodesHaveSameTopologyKey(...)
k8s.io/kubernetes/pkg/scheduler/algorithm/priorities.(*podAffinityPriorityMap).processTerm(0xc0014cf620, 0xc000be8d08, 0xc00143b400, 0xc000ffbc00, 0x0, 0xffffffffffffff9c, 0xc00027a6a8, 0x0)
k8s.io/kubernetes/pkg/scheduler/algorithm/priorities.(*podAffinityPriorityMap).processTerms(0xc0014cf620, 0xc000be8d00, 0x1, 0x1, 0xc00143b400, 0xc000ffbc00, 0x0, 0xffffffffffffffff, 0x0, 0x0)
/workspace/anago-v1.16.6-beta.0.3+72c30166b2105c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity.go:76 +0x135
/workspace/anago-v1.16.6-beta.0.3+72c30166b2105c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity.go:87 +0xa0
k8s.io/kubernetes/pkg/scheduler/algorithm/priorities.(*InterPodAffinity).CalculateInterPodAffinityPriority.func1(0xc000ffbc00, 0x0, 0x0)
/workspace/anago-v1.16.6-beta.0.3+72c30166b2105c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity.go:141 +0x407
k8s.io/kubernetes/pkg/scheduler/algorithm/priorities.(*InterPodAffinity).CalculateInterPodAffinityPriority.func2(0xb)
/workspace/anago-v1.16.6-beta.0.3+72c30166b2105c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity.go:190 +0x113
k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.ParallelizeUntil.func1(0xc001387ae0, 0xc000a3e0d0, 0xc0000ad120, 0xc000dff540)
created by k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.ParallelizeUntil
/workspace/anago-v1.16.6-beta.0.3+72c30166b2105c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:57 +0xbf
/workspace/anago-v1.16.6-beta.0.3+72c30166b2105c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:49 +0x148
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x15ec535]
panic: runtime error: invalid memory address or nil pointer dereference
goroutine 369514 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/workspace/anago-v1.16.6-beta.0.3+72c30166b2105c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1810be0, 0x2b37e00)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/util.NodesHaveSameTopologyKey(...)
/workspace/anago-v1.16.6-beta.0.3+72c30166b2105c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/util/topologies.go:58
k8s.io/kubernetes/pkg/scheduler/algorithm/priorities.(*podAffinityPriorityMap).processTerm(0xc0014cf620, 0xc000be8d08, 0xc00143b400, 0xc000ffbc00, 0x0, 0xffffffffffffff9c, 0xc00027a6a8, 0x0)
k8s.io/kubernetes/pkg/scheduler/algorithm/priorities.(*podAffinityPriorityMap).processTerms(0xc0014cf620, 0xc000be8d00, 0x1, 0x1, 0xc00143b400, 0xc000ffbc00, 0x0, 0xffffffffffffffff, 0x0, 0x0)
/workspace/anago-v1.16.6-beta.0.3+72c30166b2105c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity.go:76 +0x135
k8s.io/kubernetes/pkg/scheduler/algorithm/priorities.(*InterPodAffinity).CalculateInterPodAffinityPriority.func1(0xc000ffbc00, 0x0, 0x0)
/workspace/anago-v1.16.6-beta.0.3+72c30166b2105c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity.go:141 +0x407
/workspace/anago-v1.16.6-beta.0.3+72c30166b2105c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity.go:87 +0xa0
/workspace/anago-v1.16.6-beta.0.3+72c30166b2105c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity.go:190 +0x113
k8s.io/kubernetes/pkg/scheduler/algorithm/priorities.(*InterPodAffinity).CalculateInterPodAffinityPriority.func2(0xb)
k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.ParallelizeUntil.func1(0xc001387ae0, 0xc000a3e0d0, 0xc0000ad120, 0xc000dff540)
/workspace/anago-v1.16.6-beta.0.3+72c30166b2105c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:57 +0xbf
created by k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.ParallelizeUntil
/workspace/anago-v1.16.6-beta.0.3+72c30166b2105c/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:49 +0x148
I0323 14:55:22.339423 1 serving.go:319] Generated self-signed cert in-memory
I0323 14:55:22.824664 1 server.go:148] Version: v1.16.6
I0323 14:55:22.825689 1 defaults.go:91] TaintNodesByCondition is enabled, PodToleratesNodeTaints predicate is mandatory
W0323 14:55:22.834286 1 authorization.go:47] Authorization is disabled
I0323 14:55:22.834347 1 deprecated_insecure_serving.go:51] Serving healthz insecurely on [::]:10251
W0323 14:55:22.834298 1 authentication.go:79] Authentication is disabled
I0323 14:55:22.834946 1 secure_serving.go:123] Serving securely on 127.0.0.1:10259
I0323 14:55:22.935620 1 leaderelection.go:241] attempting to acquire leader lease kube-system/kube-scheduler...
I0323 14:55:38.533050 1 leaderelection.go:251] successfully acquired lease kube-system/kube-scheduler
E0323 14:56:01.874600 1 factory.go:585] pod is already present in the activeQ
E0323 14:56:21.620005 1 factory.go:585] pod is already present in the activeQ
E0323 14:56:47.490600 1 factory.go:585] pod is already present in the activeQ
```
**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:31:31Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `AWS`
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):
```
Linux ip-X-X-X-X.X-X-X.compute.internal 4.4.0-1066-aws #76-Ubuntu SMP Thu Aug 16 16:21:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug): `weave-net:2.6.0`
- Others:

**Comment by angao** [comment]
can you show your pod info?

**Comment by xtroncode** [comment]
kubectl -n kube-system describe pod 

```
Name:                 kube-scheduler-ip-X-X-X-X.X-X-X.compute.internal
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 ip-X-X-X-X.X-X-X.compute.internal/X.X.X.X
Start Time:           Tue, 13 Aug 2019 12:57:10 +0530
Labels:               component=kube-scheduler
                      tier=control-plane
Annotations:          kubernetes.io/config.hash: bfae94a246f6566485186be86060a2c5
                      kubernetes.io/config.mirror: bfae94a246f6566485186be86060a2c5
                      kubernetes.io/config.seen: 2020-03-24T09:52:34.877039413+05:30
                      kubernetes.io/config.source: file
Status:               Running
IP:                   X.X.X.X
IPs:
  IP:  X.X.X.X
Containers:
  kube-scheduler:
    Container ID:  docker://7b4edc561f91bb17d2a852f404528364b9f017de4c3a825922d7595158a43355
    Image:         k8s.gcr.io/kube-scheduler:v1.16.6
    Image ID:      docker-pullable://k8s.gcr.io/kube-scheduler@sha256:5f2d8e9050a528db8deb40218d8d964bc513230a45567f5228a4b45d000f4549
    Port:          <none>
    Host Port:     <none>
    Command:
      kube-scheduler
      --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
      --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
      --bind-address=127.0.0.1
      --kubeconfig=/etc/kubernetes/scheduler.conf
      --leader-elect=true
    State:          Running
      Started:      Tue, 24 Mar 2020 09:52:35 +0530
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        100m
    Liveness:     http-get http://127.0.0.1:10251/healthz delay=15s timeout=15s period=10s #success=1 #failure=8
    Environment:  <none>
    Mounts:
      /etc/kubernetes/scheduler.conf from kubeconfig (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  kubeconfig:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/scheduler.conf
    HostPathType:  FileOrCreate
QoS Class:         Burstable
Node-Selectors:    <none>
Tolerations:       :NoExecute
Events:            <none>

```

**Comment by ahg-g** [comment]
It is possible the underlying issue is similar to https://github.com/kubernetes/kubernetes/issues/89006

/assign @alculquicondor

**Comment by ahg-g** [comment]
@xtroncode do you have a cluster where nodes are added/removed frequently?

**Comment by xtroncode** [comment]
@ahg-g yes, we use cluster-autoecaler , and scaling activity is frequent.

**Comment by ahg-g** [comment]
I think the problem is a consequence of changing listing the nodes from the informer cache to the scheduler cache (which in 1.17 changed again to list from the snapshot): 

In 1.15: https://github.com/kubernetes/kubernetes/blob/release-1.15/pkg/scheduler/factory/factory.go#L567

In 1.16: https://github.com/kubernetes/kubernetes/blob/release-1.16/pkg/scheduler/factory/factory.go#L505

**Comment by ahg-g** [comment]
[Here](https://github.com/kubernetes/kubernetes/blob/release-1.16/pkg/scheduler/algorithm/priorities/interpod_affinity.go#L186) we check that nodeinfo.Node is not nil, but by the time we get to [L115](https://github.com/kubernetes/kubernetes/blob/release-1.16/pkg/scheduler/algorithm/priorities/interpod_affinity.go#L186), the node inside nodeInfo gets deleted causing the panic.

in 1.15 this would have caused an error since looking up the node from the informer cache would have returned an error.

**Comment by ahg-g** [comment]
The same issue with the inter-pod affinity predicate: https://github.com/kubernetes/kubernetes/blob/release-1.16/pkg/scheduler/algorithm/predicates/predicates.go#L1307

**Comment by ahg-g** [comment]
looking at predicate and priority registry, it seems only interpod affinity uses the node lister, so I think the above two cases are the only ones, but we should double check.

**Comment by ahg-g** [comment]
Thanks @xtroncode  for reporting, a fix will soon be patched to 1.16.

Note that 1.17 and above doesn't have this problem because they operate on the snapshot which makes a deep copy of the node object.

**Comment by xtroncode** [comment]
Thanks @ahg-g for a quick response in such difficult times. Please let me know if I can help in any way.

**Comment by ahg-g** [comment]
/close

@xtroncode  pls let us know if this PR fixed the problem.
