### ISSUE TITLE
[Failing Test] pull-kubernetes-e2e-gce: failed to prepare test environment: --provider=gce boskos failed to acquire project: resources not found

### ISSUE THREAD

**Issue by oxddr** [kubernetes/kubernetes#89586]
**Which jobs are failing**:
pull-kubernetes-e2e-gce

**Which test(s) are failing**:
kubetest 

**Since when has it been failing**:
03/27 on https://github.com/kubernetes/kubernetes/pull/89571

**Testgrid link**:
https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce

**Reason for failure**:
```
W0327 16:36:47.894] 2020/03/27 16:36:47 main.go:316: Something went wrong: failed to prepare test environment: --provider=gce boskos failed to acquire project: resources not found
W0327 16:36:47.897] Traceback (most recent call last):
W0327 16:36:47.897]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 779, in <module>
W0327 16:36:47.897]     main(parse_args())
W0327 16:36:47.897]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 627, in main
W0327 16:36:47.897]     mode.start(runner_args)
W0327 16:36:47.898]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 262, in start
W0327 16:36:47.898]     check_env(env, self.command, *args)
W0327 16:36:47.898]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 111, in check_env
W0327 16:36:47.898]     subprocess.check_call(cmd, env=env)
W0327 16:36:47.898]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W0327 16:36:47.898]     raise CalledProcessError(retcode, cmd)
W0327 16:36:47.899] subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--build=bazel', '--stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce', '--up', '--down', '--test', '--provider=gce', '--cluster=e2e-8e35f81e07-674b9', '--gcp-network=e2e-8e35f81e07-674b9', '--extract=local', '--gcp-node-image=gci', '--gcp-zone=us-west1-b', '--ginkgo-parallel=30', '--runtime-config=batch/v2alpha1=true', '--test_args=--ginkgo.skip=\\[Slow\\]|\\[Serial\\]|\\[Disruptive\\]|\\[Flaky\\]|\\[Feature:.+\\] --minStartupPods=8', '--timeout=80m')' returned non-zero exit status 1
E0327 16:36:47.907] Command failed
```

**Anything else we need to know**:
I've tried to retest few times with no luck. I can't merge my PR because of those failures.

/priority critical-urgent

**Comment by spiffxp** [comment]
issue is being tracked in https://github.com/kubernetes/test-infra/issues/16987

**Comment by spiffxp** [comment]
/close
Seeing green runs in https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce
