### ISSUE TITLE
kube-apiserver exits with panic instead of error if not able to connect to etcd

### ISSUE THREAD

**Issue by lbogdan** [kubernetes/kubernetes#89812]
**What happened**:
When joining a new control plane node with stacked `etcd`, while the local `etcd` server starts and joins the `etcd` cluster, `kube-apiserver` can't connect to it and panics:

```
Flag --insecure-port has been deprecated, This flag will be removed in a future version.
I0403 08:27:40.218701       1 server.go:656] external host was not specified, using [redacted]
I0403 08:27:40.219327       1 server.go:153] Version: v1.18.0
I0403 08:27:41.143488       1 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the follo
wing order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTo
lerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,RuntimeClass,DefaultIngressClass,MutatingAdmissio
nWebhook.
I0403 08:27:41.143585       1 plugins.go:161] Loaded 10 validating admission controller(s) successfully in the fol
lowing order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,Cer
tificateSigning,CertificateSubjectRestriction,ValidatingAdmissionWebhook,ResourceQuota.
I0403 08:27:41.144636       1 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the follo
wing order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTo
lerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,RuntimeClass,DefaultIngressClass,MutatingAdmissio
nWebhook.
I0403 08:27:41.144703       1 plugins.go:161] Loaded 10 validating admission controller(s) successfully in the fol
lowing order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,Cer
tificateSigning,CertificateSubjectRestriction,ValidatingAdmissionWebhook,ResourceQuota.
I0403 08:27:41.149740       1 client.go:361] parsed scheme: "endpoint"
I0403 08:27:41.149836       1 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://127.0.0.1:
2379  <nil> 0 <nil>}]
W0403 08:27:41.150357       1 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {https://127
.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379
: connect: connection refused". Reconnecting...
I0403 08:27:42.141845       1 client.go:361] parsed scheme: "endpoint"
I0403 08:27:42.141909       1 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{https://127.0.0.1:
2379  <nil> 0 <nil>}]
W0403 08:27:42.142281       1 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {https://127
.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379
: connect: connection refused". Reconnecting...
W0403 08:27:42.150845       1 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {https://127
.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379
: connect: connection refused". Reconnecting...
[...repeated multiple times...]
panic: context deadline exceeded

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresourcedefinition.NewREST(0xc000126e70, 0x50df5c0, 0xc000379320, 0xc0001c0c48)
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresourcedefinition/etcd.go:56 +0x3e7
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver.completedConfig.New(0xc000d30fc0, 0xc00043eb88, 0x519de20, 0x773a7d8, 0x10, 0x0, 0x0)
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go:145 +0x14ef
k8s.io/kubernetes/cmd/kube-apiserver/app.createAPIExtensionsServer(0xc00043eb80, 0x519de20, 0x773a7d8, 0x0, 0x50df180, 0xc000c5fac0)
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/apiextensions.go:102 +0x59
k8s.io/kubernetes/cmd/kube-apiserver/app.CreateServerChain(0xc0009e78c0, 0xc0000a6720, 0x4558d31, 0xc, 0xc000b57c48)
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:186 +0x2b8
k8s.io/kubernetes/cmd/kube-apiserver/app.Run(0xc0009e78c0, 0xc0000a6720, 0x0, 0x0)
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:155 +0x101
k8s.io/kubernetes/cmd/kube-apiserver/app.NewAPIServerCommand.func1(0xc000303180, 0xc0001d28c0, 0x0, 0x1b, 0x0, 0x0)
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:122 +0x104
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000303180, 0xc0000ca010, 0x1b, 0x1b, 0xc000303180, 0xc0000ca010)
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:826 +0x460
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000303180, 0x160241e295ac89d4, 0x771c600, 0xc000066750)
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
main.main()
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/apiserver.go:43 +0xcd
```

**What you expected to happen**:
Not sure if this is a bug per se, because in the end the `kube-apiserver` static pod restarts and starts successfully after the `etcd` server joins the cluster, but that panic should probably be gracefully handled.

**How to reproduce it (as minimally and precisely as possible)**:
Join a new control plane node.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): **1.18.0**
- Cloud provider or hardware configuration: **Hetzner VPS**
- OS (e.g: `cat /etc/os-release`): **Ubuntu 18.04.4 LTS**
- Kernel (e.g. `uname -a`): **5.3.0-45-generic (Ubuntu's default HWE kernel)**
- Install tools: **kubeadm**
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
Yeah, the storage signature needs adjusting to propagate the error:

https://github.com/kubernetes/kubernetes/blob/d236162778960d99a9b051b91fd62f7ea156cdf8/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresourcedefinition/etcd.go#L58-L59

/remove-kind bug
/kind cleanup
/priority backlog
