### ISSUE TITLE
kube-scheduler invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#90004]
**What happened**:
kube-scheduler panics with `invalid memory address or nil pointer dereference`.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. I see the following logs from kube-scheduler

```
I0409 11:56:20.102929       1 node_tree.go:100] Removed node "ip-10-222-0-17.eu-west-1.compute.internal" in group "eu-west-1:\x00:eu-west-1a" from NodeTree
I0409 11:56:32.822610       1 node_tree.go:100] Removed node "ip-10-222-0-13.eu-west-1.compute.internal" in group "eu-west-1:\x00:eu-west-1a" from NodeTree
E0409 11:57:12.427582       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 228 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x18ebdc0, 0x2cdda90)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x18ebdc0, 0x2cdda90)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/pkg/scheduler/nodeinfo.(*NodeInfo).RemovePod(0xc000419860, 0xc000c31900, 0xc000645e60, 0x29)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/nodeinfo/node_info.go:555 +0x610
k8s.io/kubernetes/pkg/scheduler/internal/cache.(*schedulerCache).removePod(0xc0000c4ba0, 0xc000c31900, 0xc000e3bc48, 0xc00001e0d0)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/internal/cache/cache.go:447 +0x81
k8s.io/kubernetes/pkg/scheduler/internal/cache.(*schedulerCache).updatePod(0xc0000c4ba0, 0xc000c31900, 0xc0006ccc00, 0x1, 0x2d206a0)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/internal/cache/cache.go:431 +0x35
k8s.io/kubernetes/pkg/scheduler/internal/cache.(*schedulerCache).UpdatePod(0xc0000c4ba0, 0xc000c31900, 0xc0006ccc00, 0x0, 0x0)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/internal/cache/cache.go:509 +0x23c
k8s.io/kubernetes/pkg/scheduler.(*Scheduler).updatePodInCache(0xc0005721b0, 0x1b3d7a0, 0xc000c31900, 0x1b3d7a0, 0xc0006ccc00)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/eventhandlers.go:255 +0x91
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:225
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.FilteringResourceEventHandler.OnUpdate(0xc000708b40, 0x1e3a820, 0xc000767fe0, 0x1b3d7a0, 0xc000c31900, 0x1b3d7a0, 0xc0006ccc00)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:259 +0x120
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:742 +0x191
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00067e740)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5e
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000e3bf40, 0x1df3f00, 0xc000434ba0, 0xc00028c101, 0xc00036e9c0)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00067e740, 0x3b9aca00, 0x0, 0x42ed01, 0xc00036e9c0)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xe2
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc0001d5f80)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:738 +0x95
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000263090, 0xc00043ee20)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x59
created by k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x62
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1677af0]

goroutine 228 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x18ebdc0, 0x2cdda90)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/pkg/scheduler/nodeinfo.(*NodeInfo).RemovePod(0xc000419860, 0xc000c31900, 0xc000645e60, 0x29)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/nodeinfo/node_info.go:555 +0x610
k8s.io/kubernetes/pkg/scheduler/internal/cache.(*schedulerCache).removePod(0xc0000c4ba0, 0xc000c31900, 0xc000e3bc48, 0xc00001e0d0)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/internal/cache/cache.go:447 +0x81
k8s.io/kubernetes/pkg/scheduler/internal/cache.(*schedulerCache).updatePod(0xc0000c4ba0, 0xc000c31900, 0xc0006ccc00, 0x1, 0x2d206a0)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/internal/cache/cache.go:431 +0x35
k8s.io/kubernetes/pkg/scheduler/internal/cache.(*schedulerCache).UpdatePod(0xc0000c4ba0, 0xc000c31900, 0xc0006ccc00, 0x0, 0x0)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/internal/cache/cache.go:509 +0x23c
k8s.io/kubernetes/pkg/scheduler.(*Scheduler).updatePodInCache(0xc0005721b0, 0x1b3d7a0, 0xc000c31900, 0x1b3d7a0, 0xc0006ccc00)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/eventhandlers.go:255 +0x91
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:225
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.FilteringResourceEventHandler.OnUpdate(0xc000708b40, 0x1e3a820, 0xc000767fe0, 0x1b3d7a0, 0xc000c31900, 0x1b3d7a0, 0xc0006ccc00)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:259 +0x120
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:742 +0x191
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00067e740)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5e
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000e3bf40, 0x1df3f00, 0xc000434ba0, 0xc00028c101, 0xc00036e9c0)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00067e740, 0x3b9aca00, 0x0, 0x42ed01, 0xc00036e9c0)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xe2
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc0001d5f80)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:738 +0x95
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000263090, 0xc00043ee20)
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x59
created by k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/workspace/anago-v1.18.0-rc.1.21+8be33caaf953ac/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x62
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by gongguan** [comment]
duplicate as [#89552](https://github.com/kubernetes/kubernetes/issues/89552)

**Comment by ialidzhikov** [comment]
Thanks for the update @gongguan . I see that the fix is merged in the master and cherry-pick PR is open.

/close
