### ISSUE TITLE
Missing Azure credentials should return an error and not panic

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes/kubernetes#90382]
**What happened**: Was debugging something and forgot to export credentials before creating a cluster which resulted in missing Azure credentials in Azure.json:

``` 
{  "cloud": "AzurePublicCloud",
  "tenantId": "",
  "subscriptionId": "",
  "aadClientId": "",
  "aadClientSecret": "",
  "resourceGroup": "capz-vmss",
  "securityGroupName": "capz-vmss-node-nsg",
  "location": "southcentralus",
  "vmType": "standard",
  "vnetName": "capz-vmss-vnet",
  "vnetResourceGroup": "capz-vmss",
  "subnetName": "capz-vmss-node-subnet",
  "routeTableName": "capz-vmss-node-routetable",
  "userAssignedID": "capz-vmss",
  "loadBalancerSku": "standard",
  "maximumLoadBalancerRuleCount": 250,
  "useManagedIdentityExtension": false,
  "useInstanceMetadata": true
}
```

and it caused the cloud provider to panic(): 

```
E0422 23:09:24.866700       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1375 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x38bc340, 0x6b730a0)
    /workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    /workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x38bc340, 0x6b730a0)
    /usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).InstanceShutdownByProviderID(0xc0005de000, 0x47e34e0, 0xc000054030, 0xc000aa0820, 0x98, 0x40ae848, 0x5, 0x1)
    /workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_instances.go:208 +0x56
k8s.io/kubernetes/pkg/controller/cloud.shutdownInCloudProvider(0x47e34e0, 0xc000054030, 0x4833660, 0xc0005de000, 0xc0001e3500, 0x1, 0x0, 0x0)
    /workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/cloud/node_lifecycle_controller.go:206 +0x8b
k8s.io/kubernetes/pkg/controller/cloud.(*CloudNodeLifecycleController).MonitorNodes(0xc0000eb4f0)
    /workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/cloud/node_lifecycle_controller.go:152 +0x1ac
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00086cfb0)
    /workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000e18fb0, 0x12a05f200, 0x0, 0x1, 0xc000a4e9c0)
    /workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
    /workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/kubernetes/pkg/controller/cloud.(*CloudNodeLifecycleController).Run(0xc0000eb4f0, 0xc000a4e9c0)
    /workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/controller/cloud/node_lifecycle_controller.go:114 +0xb9
created by k8s.io/kubernetes/cmd/kube-controller-manager/app.startCloudNodeLifecycleController
    /workspace/anago-v1.17.4-beta.0.54+12bf0cb73007af/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/core.go:236 +0x1cd
```

**What you expected to happen**: The cloud provider should return an error and not panic.

**How to reproduce it (as minimally and precisely as possible)**: Create an Azure k8s cluster with empty client ID/ secret in azure.json as shown above.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/assign @aramase 
/sig cloud-provider
/area provider/azure

**Comment by andyzhangx** [comment]
user has already set `"--cloud-config=/etc/kubernetes/azure.json", "--cloud-provider=azure"`, and if does not have azure crendentials(sp or managed identity), we should panic directly. Otherwise user may be not aware of that.

**Comment by andyzhangx** [comment]
/close
@CecileRobertMichon let me know if you have any question.
