### ISSUE TITLE
e2e tests failing on Kubernetes 1.14 and below

### ISSUE THREAD

**Issue by munnerz** [kubernetes/kubernetes#90547]
This PR: https://github.com/jetstack/cert-manager/pull/2831 properly enabled the validating webhook during e2e tests.

Its merge corresponds with all our periodic e2e jobs on Kubernetes 1.14 and below failing due to:

```
    Unexpected error:
        <*errors.StatusError | 0xc0000c2640>: {
            ErrStatus: {
                TypeMeta: {Kind: "", APIVersion: ""},
                ListMeta: {
                    SelfLink: "",
                    ResourceVersion: "",
                    Continue: "",
                    RemainingItemCount: nil,
                },
                Status: "Failure",
                Message: "Internal error occurred: failed calling webhook \"webhook.cert-manager.io\": Post https://cert-manager-webhook.cert-manager.svc:443/validate?timeout=30s: EOF",
                Reason: "InternalError",
                Details: {
                    Name: "",
                    Group: "",
                    Kind: "",
                    UID: "",
                    Causes: [
                        {
                            Type: "",
                            Message: "failed calling webhook \"webhook.cert-manager.io\": Post https://cert-manager-webhook.cert-manager.svc:443/validate?timeout=30s: EOF",
                            Field: "",
                        },
                    ],
                    RetryAfterSeconds: 0,
                },
                Code: 500,
            },
        }
        Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/validate?timeout=30s: EOF
    occurred
```

Looking at the webhook logs I see:

```
2020-04-28T08:26:51.289036812Z stderr F 2020/04/28 08:26:51 http: panic serving 10.244.0.1:47296: runtime error: invalid memory address or nil pointer dereference
2020-04-28T08:26:51.289070665Z stderr F goroutine 407 [running]:
2020-04-28T08:26:51.289078539Z stderr F net/http.(*conn).serve.func1(0xc0002de000)
2020-04-28T08:26:51.289096636Z stderr F 	GOROOT/src/net/http/server.go:1772 +0x139
2020-04-28T08:26:51.28910386Z stderr F panic(0x1454500, 0x22b89a0)
2020-04-28T08:26:51.289111147Z stderr F 	GOROOT/src/runtime/panic.go:973 +0x3e3
2020-04-28T08:26:51.289117968Z stderr F github.com/jetstack/cert-manager/pkg/webhook/handlers.(*registryBackedValidator).Validate(0xc000382c90, 0xc0001a6340, 0xc000496050)
2020-04-28T08:26:51.289123475Z stderr F 	pkg/webhook/handlers/validation.go:78 +0x144
2020-04-28T08:26:51.289129788Z stderr F github.com/jetstack/cert-manager/pkg/webhook/server.(*Server).validate(...)
2020-04-28T08:26:51.289135833Z stderr F 	pkg/webhook/server/server.go:288
2020-04-28T08:26:51.289149699Z stderr F github.com/jetstack/cert-manager/pkg/webhook/server.(*Server).handle.func1(0x184b4a0, 0xc0000e6000, 0xc00040a000)
2020-04-28T08:26:51.28915613Z stderr F 	pkg/webhook/server/server.go:329 +0x2ab
2020-04-28T08:26:51.289161407Z stderr F net/http.HandlerFunc.ServeHTTP(0xc0001168a0, 0x184b4a0, 0xc0000e6000, 0xc00040a000)
2020-04-28T08:26:51.289166781Z stderr F 	GOROOT/src/net/http/server.go:2012 +0x44
2020-04-28T08:26:51.289172263Z stderr F net/http.(*ServeMux).ServeHTTP(0xc00012c1c0, 0x184b4a0, 0xc0000e6000, 0xc00040a000)
2020-04-28T08:26:51.289176882Z stderr F 	GOROOT/src/net/http/server.go:2387 +0x1a5
2020-04-28T08:26:51.289182001Z stderr F net/http.serverHandler.ServeHTTP(0xc000408000, 0x184b4a0, 0xc0000e6000, 0xc00040a000)
2020-04-28T08:26:51.289187073Z stderr F 	GOROOT/src/net/http/server.go:2807 +0xa3
2020-04-28T08:26:51.289192235Z stderr F net/http.(*conn).serve(0xc0002de000, 0x184d5e0, 0xc0002ee080)
2020-04-28T08:26:51.28919814Z stderr F 	GOROOT/src/net/http/server.go:1895 +0x86c
2020-04-28T08:26:51.289203277Z stderr F created by net/http.(*Server).Serve
2020-04-28T08:26:51.289208441Z stderr F 	GOROOT/src/net/http/server.go:2933 +0x35c
```

This seems like a legitimate failure and should be investigated ASAP ahead of v0.15.

/kind flake
/priority critical-urgent
/area webhook
/assign

**Comment by munnerz** [comment]
.... sorry, testgrid sent me to the wrong repo. Ignore this it's meant for jetstack/cert-manager 🤦
