### ISSUE TITLE
Kube API Server has been crash, cannot use kubectl

### ISSUE THREAD

**Issue by tanrobotix** [kubernetes/kubernetes#90585]
Hello,
Please help me, I fount this log in kube API server docker container.
Seem to be the api server has been crashed, I tried to reboot the server but it isn't work
```
E0429 05:26:32.479959       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 5323 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3ce83e0, 0xaa83850)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3ce83e0, 0xaa83850)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Structural).Unfold.func1(0xc0163f8120, 0xc0163e2ea0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/unfold.go:38 +0xa2
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).visitStructural(0xc00d0b0530, 0xc0163f8120, 0xc00d0b0028)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:41 +0x48e
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).visitStructural(0xc00d0b0530, 0xc0163d90e0, 0xc00d0b0100)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:48 +0x173
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).visitStructural(0xc00d0b0530, 0xc0163e77a0, 0xc00d0b0308)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:45 +0x478
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).visitStructural(0xc00d0b0530, 0xc0163e7560, 0xc00d0b0478)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:48 +0x173
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).visitStructural(0xc00d0b0530, 0xc0163d5cb0, 0xc0163d5cb0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:48 +0x173
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).Visit(...)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:35
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Structural).Unfold(0xc0163d5cb0, 0xc0163d5cb0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/unfold.go:60 +0x58
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder.BuildSwagger(0xc010ae3540, 0xc00b4a885c, 0x2, 0x1010100, 0x0, 0x0, 0xd0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder/builder.go:105 +0x1ade
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver.buildOpenAPIModelsForApply(0xc000d9a100, 0xc010ae3540, 0xc00b4a885c, 0x2, 0xc0141759b8, 0x0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go:1239 +0x177
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver.(*crdHandler).getOrCreateServingInfoFor(0xc00067aa50, 0xc01156ec90, 0x24, 0xc01156ec60, 0x21, 0x0, 0x0, 0x0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go:647 +0x3f7
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver.(*crdHandler).GetCustomResourceListerCollectionDeleter(0xc00067aa50, 0xc008a90840, 0x4475a40, 0xc000330348, 0xc0136fb790, 0x11bbefc)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go:573 +0x58
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).deleteInstances(0xc0016d2e10, 0xc008a90840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:190 +0x87
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).sync(0xc0016d2e10, 0xc0081db740, 0x21, 0x18, 0xc010f4bdf0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:149 +0x786
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).processNextWorkItem(0xc0016d2e10, 0xc004252600)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:301 +0xde
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).runWorker(0xc0016d2e10)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:289 +0x2b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00aaf76b0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00aaf76b0, 0x3b9aca00, 0x0, 0x1, 0xc010bb4120)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00aaf76b0, 0x3b9aca00, 0xc010bb4120)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).Run
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:282 +0x188
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0x310cce2]

goroutine 5323 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x3ce83e0, 0xaa83850)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Structural).Unfold.func1(0xc0163f8120, 0xc0163e2ea0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/unfold.go:38 +0xa2
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).visitStructural(0xc00d0b0530, 0xc0163f8120, 0xc00d0b0028)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:41 +0x48e
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).visitStructural(0xc00d0b0530, 0xc0163d90e0, 0xc00d0b0100)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:48 +0x173
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).visitStructural(0xc00d0b0530, 0xc0163e77a0, 0xc00d0b0308)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:45 +0x478
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).visitStructural(0xc00d0b0530, 0xc0163e7560, 0xc00d0b0478)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:48 +0x173
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).visitStructural(0xc00d0b0530, 0xc0163d5cb0, 0xc0163d5cb0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:48 +0x173
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Visitor).Visit(...)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/visitor.go:35
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema.(*Structural).Unfold(0xc0163d5cb0, 0xc0163d5cb0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/unfold.go:60 +0x58
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder.BuildSwagger(0xc010ae3540, 0xc00b4a885c, 0x2, 0x1010100, 0x0, 0x0, 0xd0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/openapi/builder/builder.go:105 +0x1ade
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver.buildOpenAPIModelsForApply(0xc000d9a100, 0xc010ae3540, 0xc00b4a885c, 0x2, 0xc0141759b8, 0x0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go:1239 +0x177
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver.(*crdHandler).getOrCreateServingInfoFor(0xc00067aa50, 0xc01156ec90, 0x24, 0xc01156ec60, 0x21, 0x0, 0x0, 0x0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go:647 +0x3f7
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver.(*crdHandler).GetCustomResourceListerCollectionDeleter(0xc00067aa50, 0xc008a90840, 0x4475a40, 0xc000330348, 0xc0136fb790, 0x11bbefc)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go:573 +0x58
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).deleteInstances(0xc0016d2e10, 0xc008a90840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:190 +0x87
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).sync(0xc0016d2e10, 0xc0081db740, 0x21, 0x18, 0xc010f4bdf0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:149 +0x786
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).processNextWorkItem(0xc0016d2e10, 0xc004252600)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:301 +0xde
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).runWorker(0xc0016d2e10)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:289 +0x2b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00aaf76b0)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00aaf76b0, 0x3b9aca00, 0x0, 0x1, 0xc010bb4120)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00aaf76b0, 0x3b9aca00, 0xc010bb4120)
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer.(*CRDFinalizer).Run
	/workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/controller/finalizer/crd_finalizer.go:282 +0x188
```

**What happened**:
KubeAPI Server has been crash, I can not use kubectl
**What you expected to happen**:
Restart KubeAPI Server
**How to reproduce it (as minimally and precisely as possible)**:
```
root@kubernetes-master-12:/tmp# kubectl delete crd podmonitors.monitoring.coreos.com
customresourcedefinition.apiextensions.k8s.io "podmonitors.monitoring.coreos.com" deleted
The connection to the server 10.109.3.12:6443 was refused - did you specify the right host or port?
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.0
- Cloud provider or hardware configuration: OnPremise
- OS (e.g: `cat /etc/os-release`): Ubuntu 16.04 LTS
- Install tools: Kubespray
- Network plugin and version (if this is a network-related bug): Flannel

**Comment by liggitt** [comment]
This was fixed in https://github.com/kubernetes/kubernetes/pull/83789 in 1.16.2+

**Comment by tanrobotix** [comment]
> This was fixed in #83789 in 1.16.2+

Thank you! I'll take a upgrade

**Comment by SuryaTeja369** [comment]
Hi,
@tanrobotix I found another way of resolving this issue without going for upgrade of the Kubernetes.

The issue lies in the fact that kube-apiserver is trying to fetch details with respect to CRDs from ETCD but the memory address of the CRDs are changed as soon as we run the delete statement.

To resolve this you can exec into the etcd pod(if running as a pod or directly via etcdctl command line if running as a service) and run the following commands to delete the entries from there permanently:

1. List all the CRDs in ETCD --> ETCDCTL_API=3 etcdctl get /registry/apiextensions.k8s.io/customresourcedefinitions --limit=10 --prefix --keys-only --cacert=<cacert> --cert=<tlscert> --key=<tlskey> --endpoints https://127.0.0.1:2379
2. Delete the individual CRDs with respect to prometheus --> ETCDCTL_API=3 etcdctl del /registry/apiextensions.k8s.io/customresourcedefinitions/podmonitors.monitoring.coreos.com --cacert=<cacert> --cert=<tlscert> --key=<tlskey> --endpoints https://127.0.0.1:2379

There will be several other CRDs of promtheus(5 as far as I remember), delete them in a similar manner and take a restart of your docker and kubelet services.

PS: This was the quickest and the only fix without upgrading or crashing the server and reinstalling kubernetes

@liggitt Can you please verify the same if possible? I have tried and tested this in my ENV and works like a charm :)

**Comment by liggitt** [comment]
upgrading the API server to the patched version is recommended over deleting data directly from etcd

**Comment by SuryaTeja369** [comment]
@liggitt Any idea how we can upgrade when the apiserver is down in this case(6443 is unreachable)?

**Comment by houzhx759** [comment]
@SuryaTeja369 I also encountered this problem, I implement this why is it so ETCDCTL_API=3 etcdctl get /registry/apiextensions.k8s.io/customresourcedefinitions --limit=10 --prefix --keys-only --cacert=cacertfile --cert=tlscertfile --key=tlskeyfile --endpoints https://127.0.0.1:2379
Error: open tlscertfile: no such file or directory
Please help to reply when you have time, thank you

**Comment by SuryaTeja369** [comment]
> @SuryaTeja369 I also encountered this problem, I implement this why is it so ETCDCTL_API=3 etcdctl get /registry/apiextensions.k8s.io/customresourcedefinitions --limit=10 --prefix --keys-only --cacert=cacertfile --cert=tlscertfile --key=tlskeyfile --endpoints https://127.0.0.1:2379
> Error: open tlscertfile: no such file or directory
> Please help to reply when you have time, thank you

Hi @houzhx759 you need to provide your tlscertfile, cacertfile & tlskeyfile paths in place of cacertfile, tlscertfile & tlskeyfile in the above command. In case your etcd service is not running on https endpoint then you can omit those options and use this:

**ETCDCTL_API=3 etcdctl get /registry/apiextensions.k8s.io/customresourcedefinitions --limit=10 --prefix --keys-only --endpoints http://127.0.0.1:2379**

**Comment by houzhx759** [comment]
@SuryaTeja369 Hi, thank you very much for your help. The problem has been solved. thank you

> > @SuryaTeja369我也遇到过这个问题，我实现了这个为什么会这样 ETCDCTL_API=3 etcdctl get /registry/apiextensions.k8s.io/customresourcedefinitions --limit=10 --prefix --keys-only --cacert=cacertfile -- cert=tlscertfile --key=tlskeyfile --endpoints https://127.0.0.1:2379 
> > Error: open tlscertfile: no such file or directory 有空
> > 请帮忙回复，谢谢
> 
> 嗨@houzhx759，您需要在上述命令中提供您的 tlscertfile、cacertfile 和 tlskeyfile 路径来代替 cacertfile、tlscertfile 和 tlskeyfile。如果您的 etcd 服务没有在 https 端点上运行，那么您可以省略这些选项并使用：
> 
> **ETCDCTL_API=3 etcdctl get /registry/apiextensions.k8s.io/customresourcedefinitions --limit=10 --prefix --keys-only --endpoints http://127.0.0.1:2379**

> @SuryaTeja369 Hi, thank you very much for your help. The problem has been solved. thank you
