### ISSUE TITLE
wait panic

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/kubernetes#90685]
**What happened**:
```
[root@master01 f]# kubectl wait --for=condition=ready  --local -f nginx-01.yaml 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x140118d]

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/wait.ConditionalWait.IsConditionMet(0x7ffed780280d, 0x5, 0x1ab6f21, 0x4, 0x1d7aca0, 0xc00000e028, 0xc0006a1570, 0xc0001f2c80, 0xc000683238, 0xa22a10, ...)
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/wait/wait.go:364 +0x15d
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/wait.(*WaitOptions).RunWait.func1(0xc0006a1570, 0x0, 0x0, 0x0, 0x0)
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/wait/wait.go:236 +0x56
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.DecoratedVisitor.Visit.func1(0xc0006a1570, 0x0, 0x0, 0x7f67e9, 0xc0006833a0)
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:335 +0xd9
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.ContinueOnErrorVisitor.Visit.func1(0xc0006a1570, 0x0, 0x0, 0x300, 0x0)
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:359 +0x114
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.FlattenListVisitor.Visit.func1(0xc0006a1570, 0x0, 0x0, 0xc0006a1570, 0xc00000f430)
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:399 +0x9ab
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.FlattenListVisitor.Visit.func1(0xc0006a1570, 0x0, 0x0, 0x4f9e61, 0xc00033a0d0)
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:399 +0x9ab
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.EagerVisitorList.Visit.func1(0xc0006a1570, 0x0, 0x0, 0xd0, 0xc000376c60)
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:218 +0x114
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.(*StreamVisitor).Visit(0xc000490d80, 0xc0001580a0, 0x1000, 0xc000226000)
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:597 +0x27a
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.(*FileVisitor).Visit(0xc0002d9ae0, 0xc0001580a0, 0x0, 0x0)
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:528 +0x204
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.EagerVisitorList.Visit(0xc000480050, 0x1, 0x1, 0xc0004910c0, 0xc000491001, 0xc0004910c0)
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:213 +0xc5
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.FlattenListVisitor.Visit(0x1d7bf00, 0xc00023dfc0, 0x1d896a0, 0x30afac0, 0xc00027a1e0, 0xc000491080, 0xc000683a40, 0xc000683a58)
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:391 +0x86
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.FlattenListVisitor.Visit(0x1d7bf40, 0xc00027b380, 0x1d896a0, 0x30afac0, 0xc00027a1e0, 0xc000158060, 0x10, 0xc000683b08)
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:391 +0x86
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.ContinueOnErrorVisitor.Visit(0x1d7bf40, 0xc00027b3e0, 0xc000491040, 0x203001, 0xc000491040)
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:354 +0xc3
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.DecoratedVisitor.Visit(0x1d7bec0, 0xc000480fb0, 0xc000158000, 0x3, 0x4, 0xc000158020, 0xc000158020, 0xc00027b3e0)
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:326 +0x86
k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource.(*Result).Visit(0xc0001f2d80, 0xc000158020, 0xc0001f2d80, 0x4)
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cli-runtime/pkg/resource/result.go:99 +0x62
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/wait.(*WaitOptions).RunWait(0xc0001f2c80, 0x0, 0x1b90640)
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/wait/wait.go:230 +0xbc
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/wait.NewCmdWait.func1(0xc000621900, 0xc0002bfa40, 0x0, 0x4)
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/wait/wait.go:119 +0x89
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000621900, 0xc0002bfa00, 0x4, 0x4, 0xc000621900, 0xc0002bfa00)
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:830 +0x2ae
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000536500, 0x1b90830, 0xc00003a1e0, 0x6)
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914 +0x2fc
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
main.main()
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x1e7
[root@master01 f]# 
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1step: get an yaml
```
[root@master01 f]# cat nginx-01.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80        
      hostPort: 80 
      protocol: TCP 
```
2step:run
 kubectl wait --for=condition=ready  --local -f nginx-01.yaml

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
[root@master01 f]# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
[root@master01 f]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tedyu** [comment]
The panic may have happened on the following line:
```
		gottenObjList, err := o.DynamicClient.Resource(info.Mapping.Resource).Namespace(info.Namespace).List(context.TODO(), metav1.ListOptions{FieldSelector: nameSelector})
```
Can you fill in 'How to reproduce it' section ?

**Comment by 13567436138** [comment]
I have filled

**Comment by zhouya0** [comment]
When setting `--local` to be `true`  cause `info.Mapping` is `nil` and nil pointer error happens:
https://github.com/kubernetes/kubernetes/blob/c30da3839c8e13fdff59ef5115e982362b2c90ed/staging/src/k8s.io/kubectl/pkg/cmd/wait/wait.go#L364
