### ISSUE TITLE
Intermittent restart of Kubelet on worker node

### ISSUE THREAD

**Issue by olakunleoladimeji** [kubernetes/kubernetes#91323]
Kubelet on a worker node keeps restarting due to various segfaults. The trace points to an issue between prometheus and cadvisor. Could someone more knowledgeable have a look? 

### Cluster information:

Kubernetes version: 1.15.12
Cloud being used: Bare-metal
Installation method: kubeadm
Host OS: Ubuntu 18.04
CNI and version: Flannel v0.11.0
CRI and version: Docker 18.09
Prometheus Version: 2.10.0v

Logs from journalctl:

```
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]: panic: runtime error: invalid memory address or nil pointer dereference
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1827bba]
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]: goroutine 464 [running]:
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]: k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*manager).getSubcontainers(0xc0008f0000, 0x41c37c6, 0x1, 0x0)
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]:         /workspace/anago-v1.15.12-beta.0.35+d69e6d58f41274/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/gi
thub.com/google/cadvisor/manager/manager.go:527 +0x21a
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]: k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*manager).getRequestedContainers(0xc0008f0000, 0x41c37c6, 0x1, 0x41c587a,
 0x4, 0x2, 0x1, 0x0, 0xc000d2a880, 0xc0009029c0, ...)
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]:         /workspace/anago-v1.15.12-beta.0.35+d69e6d58f41274/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/gi
thub.com/google/cadvisor/manager/manager.go:671 +0x9f
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]: k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*manager).GetContainerInfoV2(0xc0008f0000, 0x41c37c6, 0x1, 0x41c587a, 0x4
, 0x2, 0x1, 0x0, 0xc01286000, 0xa17190000, ...)
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]:         /workspace/anago-v1.15.12-beta.0.35+d69e6d58f41274/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/gi
thub.com/google/cadvisor/manager/manager.go:454 +0x84
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]: k8s.io/kubernetes/pkg/kubelet/cadvisor.(*cadvisorClient).ContainerInfoV2(0xc0009dc570, 0x41c37c6, 0x1, 0x41c587a, 0x4, 0x2, 0x1, 0x0, 
0xc00042c22b, 0x30, ...)
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]:         /workspace/anago-v1.15.12-beta.0.35+d69e6d58f41274/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubel
et/cadvisor/cadvisor_linux.go:135 +0x73
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]: k8s.io/kubernetes/pkg/kubelet/stats.getCadvisorContainerInfo(0x49e6900, 0xc0009dc570, 0x9587cb4595, 0x7645720, 0xc00042c22b)
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]:         /workspace/anago-v1.15.12-beta.0.35+d69e6d58f41274/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubel
et/stats/cadvisor_stats_provider.go:394 +0x82
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]: k8s.io/kubernetes/pkg/kubelet/stats.(*cadvisorStatsProvider).ListPodStats(0xc000abe3c0, 0xa17190000, 0x14c22a000, 0xc000902520, 0x2, 0
x2)
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]:         /workspace/anago-v1.15.12-beta.0.35+d69e6d58f41274/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubel
et/stats/cadvisor_stats_provider.go:84 +0x40f
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]: k8s.io/kubernetes/pkg/kubelet/stats.(*cadvisorStatsProvider).ListPodStatsAndUpdateCPUNanoCoreUsage(0xc000abe3c0, 0x3308754, 0xc000abe3
c0, 0xc00162e280, 0x0, 0x0)
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]:         /workspace/anago-v1.15.12-beta.0.35+d69e6d58f41274/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubel
et/stats/cadvisor_stats_provider.go:163 +0x2b
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]: k8s.io/kubernetes/pkg/kubelet/server/stats.(*summaryProviderImpl).Get(0xc0005ee080, 0xc0003b8001, 0xc000b5c6c0, 0x4, 0x4)
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]:         /workspace/anago-v1.15.12-beta.0.35+d69e6d58f41274/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubel
et/server/stats/summary.go:89 +0x59f
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]: k8s.io/kubernetes/pkg/kubelet/eviction.(*managerImpl).synchronize(0xc000acc9a0, 0x48f9d00, 0xc000af06e0, 0xc0008a28d0, 0x0, 0x0, 0x0)
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]:         /workspace/anago-v1.15.12-beta.0.35+d69e6d58f41274/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubel
et/eviction/eviction_manager.go:245 +0xf2
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]: k8s.io/kubernetes/pkg/kubelet/eviction.(*managerImpl).Start.func2(0xc000acc9a0, 0x48f9d00, 0xc000af06e0, 0xc0008a28d0, 0xc0008a28e0, 0
x2540be400)
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]:         /workspace/anago-v1.15.12-beta.0.35+d69e6d58f41274/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubel
et/eviction/eviction_manager.go:190 +0x53
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]: created by k8s.io/kubernetes/pkg/kubelet/eviction.(*managerImpl).Start
May 21 05:01:59 std1-viadesk-prod2-mon03 kubelet[94668]:         /workspace/anago-v1.15.12-beta.0.35+d69e6d58f41274/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubel
et/eviction/eviction_manager.go:188 +0x1ec
May 21 05:01:59 std1-viadesk-prod2-mon03 systemd[1]: kubelet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 21 05:01:59 std1-viadesk-prod2-mon03 systemd[1]: kubelet.service: Failed with result 'exit-code'.
May 21 05:02:09 std1-viadesk-prod2-mon03 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
```

and another:
```
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]: panic: runtime error: invalid memory address or nil pointer dereference
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1827bba]
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]: goroutine 3533 [running]:
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]: k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*manager).getSubcontainers(0xc000424e00, 0x41c37c6, 0x1, 0x0)
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]:         /workspace/anago-v1.15.12-beta.0.35+d69e6d58f41274/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager/manager.go:527 +0x21a
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]: k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*manager).SubcontainersInfo(0xc000424e00, 0x41c37c6, 0x1, 0xc001042ac0, 0x0, 0x19, 0x199, 0x0, 0x0)
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]:         /workspace/anago-v1.15.12-beta.0.35+d69e6d58f41274/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager/manager.go:536 +0x5a
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]: k8s.io/kubernetes/pkg/kubelet/cadvisor.(*cadvisorClient).SubcontainerInfo(0xc000946ab0, 0x41c37c6, 0x1, 0xc001042ac0, 0x47699a, 0x7585dc0, 0xc0012d6c00)
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]:         /workspace/anago-v1.15.12-beta.0.35+d69e6d58f41274/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/cadvisor/cadvisor_linux.go:143 +0x73
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]: k8s.io/kubernetes/pkg/kubelet/stats.(*StatsProvider).GetRawContainerInfo(0xc000a6f860, 0x41c37c6, 0x1, 0xc001042ac0, 0xc000b57801, 0x0, 0x0, 0x0)
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]:         /workspace/anago-v1.15.12-beta.0.35+d69e6d58f41274/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/stats/stats_provider.go:191 +0x159
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]: k8s.io/kubernetes/pkg/kubelet/server.prometheusHostAdapter.SubcontainersInfo(0x4a1eee0, 0xc0005f9600, 0x41c37c6, 0x1, 0xc001042ac0, 0x40fa18, 0x40, 0x3c92440, 0x430501, 0xc001042ac0)
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]:         /workspace/anago-v1.15.12-beta.0.35+d69e6d58f41274/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:938 +0x78
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]: k8s.io/kubernetes/vendor/github.com/google/cadvisor/metrics.(*PrometheusCollector).collectContainersInfo(0xc0000f7e50, 0xc000a876e0)
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]:         /workspace/anago-v1.15.12-beta.0.35+d69e6d58f41274/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/metrics/prometheus.go:1141 +0x81
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]: k8s.io/kubernetes/vendor/github.com/google/cadvisor/metrics.(*PrometheusCollector).Collect(0xc0000f7e50, 0xc000a876e0)
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]:         /workspace/anago-v1.15.12-beta.0.35+d69e6d58f41274/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/metrics/prometheus.go:1078 +0x89
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]: k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]:         /workspace/anago-v1.15.12-beta.0.35+d69e6d58f41274/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus/registry.go:434 +0x19d
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]: created by k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather
May 21 08:28:00 std1-viadesk-prod2-mon03 kubelet[123233]:         /workspace/anago-v1.15.12-beta.0.35+d69e6d58f41274/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/prometheus/client_golang/prometheus/registry.go:445 +0x571
May 21 08:28:00 std1-viadesk-prod2-mon03 systemd[1]: kubelet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 21 08:28:00 std1-viadesk-prod2-mon03 systemd[1]: kubelet.service: Failed with result 'exit-code'.
May 21 08:28:10 std1-viadesk-prod2-mon03 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
May 21 08:28:10 std1-viadesk-prod2-mon03 systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 22.
-- Subject: Automatic restarting of a unit has been scheduled
```

**Comment by BenTheElder** [comment]
Nil deref in cAdvisor?
cc @dashpole

**Comment by dashpole** [comment]
Huh, strange.  That function looks pretty simple: https://github.com/google/cadvisor/blame/master/manager/manager.go#L540

The only line that could be nil pointering that I can think of would be `name := m.containers[i].info.Name`

**Comment by dashpole** [comment]
I checked to make sure checking the length of a nil slice works: https://play.golang.org/p/GovBngRppk3

**Comment by olakunleoladimeji** [comment]
Thanks for the follow-up!

It is strange as we run Kubernetes on over 50 nodes and have never encountered this issue.

Please let me know any helpful information you need

**Comment by tedyu** [comment]
How about the following change ?
```
diff --git a/manager/manager.go b/manager/manager.go
index 7ea8a9c9..9ff1924b 100644
--- a/manager/manager.go
+++ b/manager/manager.go
@@ -545,6 +545,9 @@ func (m *manager) getSubcontainers(containerName string) map[string]*containerDa
        // Get all the unique subcontainers of the specified container
        matchedName := path.Join(containerName, "/")
        for i := range m.containers {
+               if m.containers[i] == nil {
+                       continue
+               }
                name := m.containers[i].info.Name
                if name == containerName || strings.HasPrefix(name, matchedName) {
                        containersMap[m.containers[i].info.Name] = m.containers[i]
```

**Comment by dashpole** [comment]
That could work.  I checked, and neither info nor Name can be nil, so unless i'm missing something, that should do the trick

**Comment by olakunleoladimeji** [comment]
I'll make a build with this modification on the affected node this weekend and revert. Thanks once again!

**Comment by olakunleoladimeji** [comment]
While trying to make a custom build, I  discovered a network issue on the VM which affected all SSL/TLS traffic.

Upon fixing this and rebooting, the issue was fixed.  

Thank you all very much
