### ISSUE TITLE
kubelet hugepages and benchmark tests panic

### ISSUE THREAD

**Issue by bart0sh** [kubernetes/kubernetes#91937]
**Which jobs are failing**:

- ci-kubernetes-node-kubelet-serial-hugepages
- ci-kubernetes-node-kubelet-benchmark

**Which test(s) are failing**:

Node tests

**Since when has it been failing**:

It happens occasionally and started quite long time ago.

**Testgrid link**:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-hugepages/1270133163225518083

**Reason for failure**:

panic in protobuf code:
```
panic: invalid Go type int for field k8s_io.kubernetes.vendor.go_etcd_io.etcd.etcdserver.etcdserverpb.loggablePutRequest.value_size

goroutine 228 [running]:
k8s.io/kubernetes/vendor/google.golang.org/protobuf/internal/impl.newSingularConverter(0x6155840, 0x4590640, 0x6155720, 0xc0070af5e0, 0x60c9601, 0xc006a09c20)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/protobuf/internal/impl/convert.go:143 +0xff5
k8s.io/kubernetes/vendor/google.golang.org/protobuf/internal/impl.NewConverter(0x6155840, 0x4590640, 0x6155720, 0xc0070af5e0, 0x203000, 0xc0087159e0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/protobuf/internal/impl/convert.go:60 +0xd9
k8s.io/kubernetes/vendor/google.golang.org/protobuf/internal/impl.fieldInfoForScalar(0x6155720, 0xc0070af5e0, 0x451e44b, 0x9, 0x0, 0x0, 0x6155840, 0x4590640, 0x451e456, 0x2e, ...)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/protobuf/internal/impl/message_reflect_field.go:234 +0x110
k8s.io/kubernetes/vendor/google.golang.org/protobuf/internal/impl.(*MessageInfo).makeKnownFieldsFunc(0xc00867d400, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xc0087158f0, 0xc008715920, 0xc008715950, 0xc008715980)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/protobuf/internal/impl/message_reflect.go:67 +0x938
k8s.io/kubernetes/vendor/google.golang.org/protobuf/internal/impl.(*MessageInfo).makeReflectFuncs(0xc00867d400, 0x6155840, 0x4eaf4c0, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xc0087158f0, 0xc008715920, 0xc008715950, ...)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/protobuf/internal/impl/message_reflect.go:36 +0x63
k8s.io/kubernetes/vendor/google.golang.org/protobuf/internal/impl.(*MessageInfo).initOnce(0xc00867d400)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/protobuf/internal/impl/message.go:90 +0x19c
k8s.io/kubernetes/vendor/google.golang.org/protobuf/internal/impl.(*MessageInfo).init(0xc00867d400)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/protobuf/internal/impl/message.go:72 +0x3c
k8s.io/kubernetes/vendor/google.golang.org/protobuf/internal/impl.(*messageReflectWrapper).Has(0xc00bc48090, 0x6155720, 0xc0070af500, 0xc0070af500)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/protobuf/internal/impl/message_reflect_gen.go:185 +0x33
k8s.io/kubernetes/vendor/github.com/golang/protobuf/proto.(*textWriter).writeMessage(0xc0087158c0, 0x6135260, 0xc00bc48090, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/protobuf/proto/text_encode.go:278 +0x925
k8s.io/kubernetes/vendor/github.com/golang/protobuf/proto.(*TextMarshaler).marshal(0x8cdfd92, 0x605b880, 0xc008715830, 0x0, 0x0, 0xc00bd3be80, 0x0, 0x1)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/protobuf/proto/text_encode.go:86 +0x18a
k8s.io/kubernetes/vendor/github.com/golang/protobuf/proto.(*TextMarshaler).Text(...)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/protobuf/proto/text_encode.go:44
k8s.io/kubernetes/vendor/github.com/golang/protobuf/proto.CompactTextString(...)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/protobuf/proto/text_encode.go:106
k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/etcdserverpb.(*loggablePutRequest).String(...)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/etcdserverpb/raft_internal_stringer.go:182
k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/etcdserverpb.(*requestOpStringer).String(0xc013744868, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/etcdserverpb/raft_internal_stringer.go:124 +0x180
k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/etcdserverpb.(*txnRequestStringer).String(0xc013744998, 0xc0032304c0, 0x17)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/etcdserverpb/raft_internal_stringer.go:98 +0x47e
k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/etcdserverpb.(*InternalRaftStringer).String(0xc00843d9e0, 0x57570aaac, 0x8e6bac0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/etcdserverpb/raft_internal_stringer.go:67 +0x123
k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver.warnOfExpensiveGenericRequest(0xc000264960, 0xbfaf5f956a16e3eb, 0x57570aaac, 0x8e6bac0, 0x5fe2560, 0xc00843d9e0, 0x0, 0x0, 0xc00732c430, 0x7, ...)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/util.go:149 +0x487
k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver.warnOfExpensiveRequest(0xc000264960, 0xbfaf5f956a16e3eb, 0x57570aaac, 0x8e6bac0, 0x5fe2560, 0xc00843d9e0, 0x605b640, 0xc008714570, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/util.go:111 +0xcc
k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver.(*applierV3backend).Apply.func1(0xc000c44440, 0xc0077787e0, 0xc0086699b0, 0xbfaf5f956a16e3eb, 0x57570aaac, 0x8e6bac0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/apply.go:118 +0x10d
k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver.(*applierV3backend).Apply(0xc000c44440, 0xc0077787e0, 0xc0086699b0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/apply.go:176 +0x2ba
k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver.(*authApplierV3).Apply(0xc0003fe050, 0xc0077787e0, 0x0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/apply_auth.go:60 +0xf5
k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver.(*EtcdServer).applyEntryNormal(0xc000c86100, 0xc013745498)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/server.go:2213 +0x1ea
k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver.(*EtcdServer).apply(0xc000c86100, 0xc00752fab8, 0x1, 0x1, 0xc0013c1ea0, 0x434dd0, 0x547f068, 0xc000080000)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/server.go:2127 +0x591
k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver.(*EtcdServer).applyEntries(0xc000c86100, 0xc0013c1ea0, 0xc0079e1100)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/server.go:1379 +0xd4
k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver.(*EtcdServer).applyAll(0xc000c86100, 0xc0013c1ea0, 0xc0079e1100)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/server.go:1103 +0x88
k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver.(*EtcdServer).run.func8(0x6081900, 0xc000e54700)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/server.go:1048 +0x3c
k8s.io/kubernetes/vendor/go.etcd.io/etcd/pkg/schedule.(*fifo).run(0xc000d1b2c0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/pkg/schedule/schedule.go:157 +0xf7
created by k8s.io/kubernetes/vendor/go.etcd.io/etcd/pkg/schedule.NewFIFOScheduler
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/pkg/schedule/schedule.go:70 +0x13b
```

log with the traceback: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-hugepages/1269647959063007233/artifacts/n1-standard-2-ubuntu-gke-1804-1-16-v20200330-9717e5df/services.log

**Anything else we need to know**:

Here is a workaround I did for ci-kubernetes-node-kubelet-benchmark job:
https://github.com/kubernetes/test-infra/pull/17743#issuecomment-638107187

**Comment by dims** [comment]
@bart0sh here's the follow up - https://github.com/etcd-io/etcd/issues/11992

**Comment by RainbowMango** [comment]
Same issue with https://github.com/kubernetes/kubernetes/issues/92070.

/assign

**Comment by alejandrox1** [comment]
Seeing the same in https://github.com/kubernetes/kubernetes/issues/91263 but only sometimes
