### ISSUE TITLE
k8s related processes Disk read speed Too high

### ISSUE THREAD

**Issue by DesistDaydream** [kubernetes/kubernetes#92072]
**What happened**:
k8s related processes Disk read speed Too high
![image](https://user-images.githubusercontent.com/39847025/84505961-338a0300-acf1-11ea-8917-cff055185f9e.png)
This situation will continue to occur until the pod is deleted

This is flanneld's exit log
```
I0525 02:17:56.806283       1 main.go:518] Determining IP address of default interface
I0525 02:17:56.901100       1 main.go:531] Using interface with name eth0 and address 10.0.9.218
I0525 02:17:56.901173       1 main.go:548] Defaulting external address to interface address (10.0.9.218)
W0525 02:17:56.901231       1 client_config.go:517] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0525 02:17:57.200298       1 kube.go:119] Waiting 10m0s for node controller to sync
I0525 02:17:57.200489       1 kube.go:306] Starting kube subnet manager
I0525 02:17:58.200675       1 kube.go:126] Node controller sync successful
I0525 02:17:58.200757       1 main.go:246] Created subnet manager: Kubernetes Subnet Manager - node-08.k8s.cloud.tjiptv.net
I0525 02:17:58.200775       1 main.go:249] Installing signal handlers
I0525 02:17:58.200912       1 main.go:390] Found network config - Backend type: host-gw
I0525 02:17:58.299841       1 main.go:355] Current network or subnet (10.252.128.0/17, 10.252.132.0/24) is not equal to previous one (0.0.0.0/0, 0.0.0.0/0), trying to recycle old iptables rules
I0525 02:17:58.700369       1 iptables.go:167] Deleting iptables rule: -s 0.0.0.0/0 -d 0.0.0.0/0 -j RETURN
I0525 02:17:58.705397       1 iptables.go:167] Deleting iptables rule: -s 0.0.0.0/0 ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
I0525 02:17:58.800242       1 iptables.go:167] Deleting iptables rule: ! -s 0.0.0.0/0 -d 0.0.0.0/0 -j RETURN
I0525 02:17:58.801554       1 iptables.go:167] Deleting iptables rule: ! -s 0.0.0.0/0 -d 0.0.0.0/0 -j MASQUERADE --random-fully
I0525 02:17:58.900309       1 main.go:305] Setting up masking rules
I0525 02:17:58.902343       1 main.go:313] Changing default FORWARD chain policy to ACCEPT
I0525 02:17:58.902568       1 main.go:321] Wrote subnet file to /run/flannel/subnet.env
I0525 02:17:58.902584       1 main.go:325] Running backend.
I0525 02:17:58.902606       1 main.go:343] Waiting for all goroutines to exit
I0525 02:17:58.902704       1 route_network.go:53] Watching for new subnet leases
I0525 02:17:58.999903       1 route_network.go:85] Subnet added: 10.252.128.0/24 via 10.0.9.201
I0525 02:17:59.000244       1 route_network.go:85] Subnet added: 10.252.140.0/24 via 10.0.9.214
I0525 02:17:59.002530       1 iptables.go:145] Some iptables rules are missing; deleting and recreating rules
I0525 02:17:59.002568       1 iptables.go:167] Deleting iptables rule: -s 10.252.128.0/17 -d 10.252.128.0/17 -j RETURN
I0525 02:17:59.099700       1 iptables.go:145] Some iptables rules are missing; deleting and recreating rules
I0525 02:17:59.099777       1 iptables.go:167] Deleting iptables rule: -s 10.252.128.0/17 -j ACCEPT
I0525 02:17:59.100054       1 route_network.go:85] Subnet added: 10.252.137.0/24 via 10.0.9.215
I0525 02:17:59.100383       1 route_network.go:85] Subnet added: 10.252.134.0/24 via 10.0.9.216
I0525 02:17:59.100653       1 route_network.go:85] Subnet added: 10.252.139.0/24 via 10.0.9.219
I0525 02:17:59.100849       1 route_network.go:85] Subnet added: 10.252.129.0/24 via 10.0.9.202
I0525 02:17:59.101030       1 route_network.go:85] Subnet added: 10.252.130.0/24 via 10.0.9.203
I0525 02:17:59.101230       1 route_network.go:85] Subnet added: 10.252.136.0/24 via 10.0.9.211
I0525 02:17:59.101464       1 route_network.go:85] Subnet added: 10.252.135.0/24 via 10.0.9.212
I0525 02:17:59.101675       1 route_network.go:85] Subnet added: 10.252.131.0/24 via 10.0.9.213
I0525 02:17:59.101876       1 route_network.go:85] Subnet added: 10.252.138.0/24 via 10.0.9.217
I0525 02:17:59.102074       1 route_network.go:85] Subnet added: 10.252.133.0/24 via 10.0.9.220
I0525 02:17:59.199745       1 iptables.go:167] Deleting iptables rule: -s 10.252.128.0/17 ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
I0525 02:17:59.202040       1 iptables.go:167] Deleting iptables rule: -d 10.252.128.0/17 -j ACCEPT
I0525 02:17:59.399983       1 iptables.go:167] Deleting iptables rule: ! -s 10.252.128.0/17 -d 10.252.132.0/24 -j RETURN
I0525 02:17:59.402090       1 iptables.go:155] Adding iptables rule: -s 10.252.128.0/17 -j ACCEPT
I0525 02:17:59.501915       1 iptables.go:167] Deleting iptables rule: ! -s 10.252.128.0/17 -d 10.252.128.0/17 -j MASQUERADE --random-fully
I0525 02:17:59.503969       1 iptables.go:155] Adding iptables rule: -s 10.252.128.0/17 -d 10.252.128.0/17 -j RETURN
I0525 02:17:59.600407       1 iptables.go:155] Adding iptables rule: -s 10.252.128.0/17 ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
I0525 02:17:59.701983       1 iptables.go:155] Adding iptables rule: -d 10.252.128.0/17 -j ACCEPT
I0525 02:17:59.902545       1 iptables.go:155] Adding iptables rule: ! -s 10.252.128.0/17 -d 10.252.132.0/24 -j RETURN
I0525 02:18:00.100892       1 iptables.go:155] Adding iptables rule: ! -s 10.252.128.0/17 -d 10.252.128.0/17 -j MASQUERADE --random-fully
E0528 23:59:22.738769       1 streamwatcher.go:109] Unable to decode an event from the watch stream: http2: server sent GOAWAY and closed the connection; LastStreamID=1519, ErrCode=NO_ERROR, debug=""
W0528 23:59:26.804303       1 reflector.go:323] github.com/coreos/flannel/subnet/kube/kube.go:307: watch of *v1.Node ended with: too old resource version: 1349122 (1349151)
SIGQUIT: quit
PC=0x458501 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x27a3fc8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffd7ab81cf8, 0x40fd7b, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:530 +0x21
runtime.futexsleep(0x27a3fc8, 0x7ffd00000000, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os_linux.go:45 +0x4b
runtime.notesleep(0x27a3fc8)
	/usr/local/go/src/runtime/lock_futex.go:151 +0x9b
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:1952 +0xe5
runtime.findrunnable(0xc420057400, 0x0)
	/usr/local/go/src/runtime/proc.go:2415 +0x50c
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2541 +0x13b
runtime.park_m(0xc420179200)
	/usr/local/go/src/runtime/proc.go:2604 +0xb6
runtime.mcall(0x2734018)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x5b

goroutine 1 [semacquire, 26522 minutes]:
sync.runtime_Semacquire(0xc4203a845c)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc4203a8450)
	/usr/local/go/src/sync/waitgroup.go:129 +0x72
main.main()
	/go/src/github.com/coreos/flannel/main.go:345 +0x9ec

goroutine 5 [syscall, 26522 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [chan receive]:
github.com/coreos/flannel/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x27a2f40)
	/go/src/github.com/coreos/flannel/vendor/github.com/golang/glog/glog.go:879 +0x8b
created by github.com/coreos/flannel/vendor/github.com/golang/glog.init.0
	/go/src/github.com/coreos/flannel/vendor/github.com/golang/glog/glog.go:410 +0x203

goroutine 400279 [IO wait]:
internal/poll.runtime_pollWait(0x7f3afa605f00, 0x72, 0xc4200ac858)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42052d398, 0x72, 0xffffffffffffff00, 0x1acff60, 0x2748378)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc42052d398, 0xc420b82000, 0x8000, 0x8000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42052d380, 0xc420b82000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc42052d380, 0xc420b82000, 0x8000, 0x8000, 0x8, 0x8, 0x7ff3)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4206f48c0, 0xc420b82000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6a
crypto/tls.(*block).readFromUntil(0xc42043a960, 0x7f3af83c21c8, 0xc4206f48c0, 0x5, 0xc4206f48c0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:493 +0x96
crypto/tls.(*Conn).readRecord(0xc4206f8700, 0x19f8017, 0xc4206f8820, 0xc4200acbc8)
	/usr/local/go/src/crypto/tls/conn.go:595 +0xe0
crypto/tls.(*Conn).Read(0xc4206f8700, 0xc420961000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1156 +0x100
bufio.(*Reader).Read(0xc420845620, 0xc420b36378, 0x9, 0x9, 0x28, 0xc4204b9c80, 0x0)
	/usr/local/go/src/bufio/bufio.go:216 +0x238
io.ReadAtLeast(0x1acb900, 0xc420845620, 0xc420b36378, 0x9, 0x9, 0x9, 0x43c021, 0xc420910600, 0x4)
	/usr/local/go/src/io/io.go:309 +0x86
io.ReadFull(0x1acb900, 0xc420845620, 0xc420b36378, 0x9, 0x9, 0xc4200acd10, 0x46a453, 0xc4200acd20)
	/usr/local/go/src/io/io.go:327 +0x58
github.com/coreos/flannel/vendor/golang.org/x/net/http2.readFrameHeader(0xc420b36378, 0x9, 0x9, 0x1acb900, 0xc420845620, 0x0, 0x0, 0xc420124668, 0xc420a94000)
	/go/src/github.com/coreos/flannel/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/coreos/flannel/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc420b36340, 0xc4204b9c80, 0x0, 0x0, 0x0)
	/go/src/github.com/coreos/flannel/vendor/golang.org/x/net/http2/frame.go:469 +0xa4
github.com/coreos/flannel/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc4200acfb0, 0x19f3d50, 0xc420a357b0)
	/go/src/github.com/coreos/flannel/vendor/golang.org/x/net/http2/transport.go:1343 +0x8e
github.com/coreos/flannel/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc4207c0000)
	/go/src/github.com/coreos/flannel/vendor/golang.org/x/net/http2/transport.go:1269 +0x76
created by github.com/coreos/flannel/vendor/golang.org/x/net/http2.(*Transport).newClientConn
	/go/src/github.com/coreos/flannel/vendor/golang.org/x/net/http2/transport.go:534 +0x651

goroutine 36 [semacquire]:
sync.runtime_notifyListWait(0xc42021a328, 0x11f21)
	/usr/local/go/src/runtime/sema.go:510 +0x10b
sync.(*Cond).Wait(0xc42021a318)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc42021a300, 0xc4204b8bd0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:438 +0x99
github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache.(*controller).processLoop(0xc420270b00)
	/go/src/github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:147 +0x40
github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache.(*controller).(github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache.processLoop)-fm()
	/go/src/github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:121 +0x2a
github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4200a6f70)
	/go/src/github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:96 +0x54
github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4200a6f70, 0x3b9aca00, 0x0, 0x1608201, 0x0)
	/go/src/github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97 +0xa1
github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4200a6f70, 0x3b9aca00, 0x0)
	/go/src/github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52 +0x4d
github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache.(*controller).Run(0xc420270b00, 0x0)
	/go/src/github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:121 +0x224
github.com/coreos/flannel/subnet/kube.(*kubeSubnetManager).Run(0xc420254460, 0x7f3af95d04b0, 0xc42003c018)
	/go/src/github.com/coreos/flannel/subnet/kube/kube.go:307 +0x78
created by github.com/coreos/flannel/subnet/kube.NewSubnetManager
	/go/src/github.com/coreos/flannel/subnet/kube/kube.go:117 +0x501

goroutine 39 [chan receive (nil chan), 26522 minutes]:
github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache.(*controller).Run.func1(0x0, 0xc420270b00)
	/go/src/github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:103 +0x34
created by github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache.(*controller).Run
	/go/src/github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache/controller.go:102 +0x92

goroutine 40 [select]:
github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache.(*Reflector).watchHandler(0xc4201da870, 0x1ad2de0, 0xc420bb22d0, 0xc420bedc80, 0xc42019c780, 0x0, 0x0, 0x0)
	/go/src/github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache/reflector.go:350 +0x200
github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc4201da870, 0x0, 0x0, 0x0)
	/go/src/github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache/reflector.go:321 +0xd49
github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache.(*Reflector).RunUntil.func1()
	/go/src/github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache/reflector.go:200 +0x33
github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc420155320)
	/go/src/github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:96 +0x54
github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420155320, 0x3b9aca00, 0x0, 0x1, 0x0)
	/go/src/github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97 +0xa1
github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc420155320, 0x3b9aca00, 0x0)
	/go/src/github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52 +0x4d
created by github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache.(*Reflector).RunUntil
	/go/src/github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache/reflector.go:199 +0x172

goroutine 400176 [select, 3 minutes]:
github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc420200690, 0x0, 0xc4207d9980, 0xc4201da870, 0xc42019c780, 0xc420200698)
	/go/src/github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache/reflector.go:268 +0xf3
created by github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch
	/go/src/github.com/coreos/flannel/vendor/k8s.io/client-go/tools/cache/reflector.go:266 +0x7fe

goroutine 84 [select, 26522 minutes, locked to thread]:
runtime.gopark(0x19f7fa0, 0x0, 0x197ba71, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc42050c750, 0xc42055e0c0)
	/usr/local/go/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:549 +0x1f4
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1

goroutine 85 [select, 26522 minutes]:
main.shutdownHandler(0x7f3af837d000, 0xc4206c2e80, 0xc42019c540, 0xc4203ea170)
	/go/src/github.com/coreos/flannel/main.go:368 +0xde
main.main.func1(0x7f3af837d000, 0xc4206c2e80, 0xc42019c540, 0xc4203ea170, 0xc4203a8450)
	/go/src/github.com/coreos/flannel/main.go:263 +0x49
created by main.main
	/go/src/github.com/coreos/flannel/main.go:262 +0x4e6

goroutine 86 [chan receive, 26522 minutes]:
github.com/coreos/flannel/backend.(*manager).GetBackend.func1(0xc4200e4230, 0xc420402fc8, 0x7)
	/go/src/github.com/coreos/flannel/backend/manager.go:75 +0x4e
created by github.com/coreos/flannel/backend.(*manager).GetBackend
	/go/src/github.com/coreos/flannel/backend/manager.go:74 +0x23b

goroutine 90 [sleep]:
time.Sleep(0x12a05f200)
	/usr/local/go/src/runtime/time.go:102 +0x166
github.com/coreos/flannel/network.SetupAndEnsureIPTables(0xc4205e4000, 0x4, 0x4, 0x5)
	/go/src/github.com/coreos/flannel/network/iptables.go:118 +0xa2
created by main.main
	/go/src/github.com/coreos/flannel/main.go:306 +0xd86

goroutine 91 [sleep]:
time.Sleep(0x12a05f200)
	/usr/local/go/src/runtime/time.go:102 +0x166
github.com/coreos/flannel/network.SetupAndEnsureIPTables(0xc4202273b0, 0x2, 0x2, 0x5)
	/go/src/github.com/coreos/flannel/network/iptables.go:118 +0xa2
created by main.main
	/go/src/github.com/coreos/flannel/main.go:314 +0xc00

goroutine 92 [select, 26522 minutes]:
github.com/coreos/flannel/backend.(*RouteNetwork).Run(0xc42019c600, 0x7f3af837d000, 0xc4206c2e80)
	/go/src/github.com/coreos/flannel/backend/route_network.go:71 +0x2f0
main.main.func2(0x1ad8120, 0xc42019c600, 0x7f3af837d000, 0xc4206c2e80, 0xc4203a8450)
	/go/src/github.com/coreos/flannel/main.go:328 +0x45
created by main.main
	/go/src/github.com/coreos/flannel/main.go:327 +0x962

goroutine 93 [select, 26522 minutes]:
github.com/coreos/flannel/subnet/kube.(*kubeSubnetManager).WatchLeases(0xc420254460, 0x7f3af837d000, 0xc4206c2e80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/coreos/flannel/subnet/kube/kube.go:295 +0x15d
github.com/coreos/flannel/subnet.WatchLeases(0x7f3af837d000, 0xc4206c2e80, 0x1ae59a0, 0xc420254460, 0xc420218ba0, 0xc4207d8060)
	/go/src/github.com/coreos/flannel/subnet/watch.go:37 +0xe9
github.com/coreos/flannel/backend.(*RouteNetwork).Run.func1(0x7f3af837d000, 0xc4206c2e80, 0xc42019c600, 0xc4207d8060, 0xc4204024a0)
	/go/src/github.com/coreos/flannel/backend/route_network.go:57 +0x5e
created by github.com/coreos/flannel/backend.(*RouteNetwork).Run
	/go/src/github.com/coreos/flannel/backend/route_network.go:56 +0x116

goroutine 94 [select]:
github.com/coreos/flannel/backend.(*RouteNetwork).routeCheck(0xc42019c600, 0x7f3af837d000, 0xc4206c2e80)
	/go/src/github.com/coreos/flannel/backend/route_network.go:161 +0x10b
github.com/coreos/flannel/backend.(*RouteNetwork).Run.func2(0xc42019c600, 0x7f3af837d000, 0xc4206c2e80, 0xc4204024a0)
	/go/src/github.com/coreos/flannel/backend/route_network.go:64 +0x3f
created by github.com/coreos/flannel/backend.(*RouteNetwork).Run
	/go/src/github.com/coreos/flannel/backend/route_network.go:63 +0x1cd

goroutine 1721153 [semacquire]:
sync.runtime_notifyListWait(0xc420124680, 0xc40000000d)
	/usr/local/go/src/runtime/sema.go:510 +0x10b
sync.(*Cond).Wait(0xc420124670)
	/usr/local/go/src/sync/cond.go:56 +0x80
github.com/coreos/flannel/vendor/golang.org/x/net/http2.(*pipe).Read(0xc420124668, 0xc420964001, 0x3dff, 0x3dff, 0x0, 0x0, 0x0)
	/go/src/github.com/coreos/flannel/vendor/golang.org/x/net/http2/pipe.go:60 +0x8c
github.com/coreos/flannel/vendor/golang.org/x/net/http2.transportResponseBody.Read(0xc420124640, 0xc420964001, 0x3dff, 0x3dff, 0x0, 0x0, 0x0)
	/go/src/github.com/coreos/flannel/vendor/golang.org/x/net/http2/transport.go:1589 +0xa1
encoding/json.(*Decoder).refill(0xc4203723c0, 0xa2900a, 0x9)
	/usr/local/go/src/encoding/json/stream.go:159 +0x132
encoding/json.(*Decoder).readValue(0xc4203723c0, 0x0, 0x0, 0x16e1140)
	/usr/local/go/src/encoding/json/stream.go:134 +0x23d
encoding/json.(*Decoder).Decode(0xc4203723c0, 0x1727220, 0xc420d29de0, 0x1acd0c0, 0xc4203b6580)
	/usr/local/go/src/encoding/json/stream.go:63 +0x78
github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/util/framer.(*jsonFrameReader).Read(0xc420bb22a0, 0xc420c4c000, 0x4000, 0x4a80, 0xc420361b40, 0x40, 0x38)
	/go/src/github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/util/framer/framer.go:150 +0x295
github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming.(*decoder).Decode(0xc4200e4be0, 0x0, 0x1acc600, 0xc420361b40, 0x2500, 0x1acd0c0, 0xc4202d0178, 0x4513d0, 0xc4202d0120)
	/go/src/github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go:77 +0x95
github.com/coreos/flannel/vendor/k8s.io/client-go/rest/watch.(*Decoder).Decode(0xc420a985c0, 0xc420be9fa8, 0x8, 0x1acd0c0, 0xc4203b6580, 0x0, 0x0)
	/go/src/github.com/coreos/flannel/vendor/k8s.io/client-go/rest/watch/decoder.go:49 +0x7c
github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc420bb22d0)
	/go/src/github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:93 +0x12e
created by github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/watch.NewStreamWatcher
	/go/src/github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/watch/streamwatcher.go:60 +0xa8

rax    0xca
rbx    0x27a3e80
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x27a3fc8
rsi    0x0
rbp    0x7ffd7ab81cc0
rsp    0x7ffd7ab81c78
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x8e0d3c
r13    0x0
r14    0x0
r15    0x0
rip    0x458501
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

**What you expected to happen**:
I hope the disk read speed can be normal

**How to reproduce it (as minimally and precisely as possible)**:
not know

**Anything else we need to know?**:
https://stackoverflow.com/questions/51040525/high-disk-usage-iops-and-bandwidth-by-kubernetes
There are similar questions here

**Environment**:
- Kubernetes version (use `kubectl version`):1.18.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):centos7
- Kernel (e.g. `uname -a`):3.10.0-1062.1.1.el7
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
is this happening only for flanneld?
if yes, log an issue in their issue tracker.

if k8s core processes do that too like kube-apiserver please reopen this ticket.

/close
/triage support

**Comment by DesistDaydream** [comment]
@neolit123
https://stackoverflow.com/questions/51040525/high-disk-usage-iops-and-bandwidth-by-kubernetes
In this problem, the k8s core process also has this phenomenon

**Comment by neolit123** [comment]
yes i saw that screenshot, but are you able to reproduce the kubelet high CPU usage in your setup?

**Comment by DesistDaydream** [comment]
Not high CPU usage, but disk read rate

**Comment by neolit123** [comment]
my mistake, are you able to reproduce the kubelet high diskusage in your setup?

**Comment by DesistDaydream** [comment]
I don’t know how to reproduce the problem for now...( ╯□╰ )

**Comment by neolit123** [comment]
i suggest you log an issue for flanneld here first:
https://github.com/coreos/flannel

this repo is for core k8s components only: kube-{apiserver, controller-manager, scheduler}, kubelet
