### ISSUE TITLE
[azure] kube-controller-manager panics because of the cloud-config init

### ISSUE THREAD

**Issue by JulienBalestra** [kubernetes/kubernetes#92504]
**What happened**:

While trying to setup a `kube-controller-manager` outside of the cluster, I had a panic as follow:

```text
I0625 11:36:46.285834    9145 serving.go:313] Generated self-signed cert in-memory
W0625 11:36:46.646110    9145 authentication.go:268] No authentication-kubeconfig provided in order to lookup client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication won't work.
W0625 11:36:46.646150    9145 authentication.go:292] No authentication-kubeconfig provided in order to lookup requestheader-client-ca-file in configmap/extension-apiserver-authentication in kube-system, so request-header client certificate authentication won't work.
W0625 11:36:46.646166    9145 authorization.go:146] No authorization-kubeconfig provided, so SubjectAccessReview of authorization tokens won't work.
I0625 11:36:46.646183    9145 controllermanager.go:161] Version: v0.0.0-master+$Format:%h$
I0625 11:36:46.647816    9145 secure_serving.go:178] Serving securely on 127.0.0.1:10257
I0625 11:36:46.647871    9145 tlsconfig.go:240] Starting DynamicServingCertificateController
I0625 11:36:46.648706    9145 deprecated_insecure_serving.go:53] Serving insecurely on [::]:10252
W0625 11:36:49.217880    9145 plugins.go:115] WARNING: azure built-in cloud provider is now deprecated. The Azure provider is deprecated and will be removed in a future release
I0625 11:41:37.407490    9145 azure.go:706] Setting up informers for Azure cloud provider
I0625 11:41:37.412573    9145 shared_informer.go:223] Waiting for caches to sync for tokens
I0625 11:41:38.515533    9145 shared_informer.go:230] Caches are synced for tokens 
I0625 11:41:39.015039    9145 core.go:239] Will not configure cloud provider routes for allocate-node-cidrs: false, configure-cloud-routes: false.
W0625 11:41:39.015427    9145 controllermanager.go:525] Skipping "route"
I0625 11:41:44.424855    9145 controllermanager.go:533] Started "garbagecollector"
I0625 11:41:44.425387    9145 garbagecollector.go:133] Starting garbage collector controller
I0625 11:41:44.425430    9145 shared_informer.go:223] Waiting for caches to sync for garbage collector
I0625 11:41:44.425671    9145 graph_builder.go:282] GraphBuilder running
I0625 11:41:45.219279    9145 controllermanager.go:533] Started "daemonset"
I0625 11:41:45.219555    9145 daemon_controller.go:257] Starting daemon sets controller
I0625 11:41:45.219653    9145 shared_informer.go:223] Waiting for caches to sync for daemon sets
I0625 11:41:45.973483    9145 controllermanager.go:533] Started "ttl"
I0625 11:41:45.973560    9145 ttl_controller.go:118] Starting TTL controller
I0625 11:41:45.974238    9145 shared_informer.go:223] Waiting for caches to sync for TTL
I0625 11:41:45.974290    9145 shared_informer.go:230] Caches are synced for TTL 
I0625 11:41:46.870297    9145 controllermanager.go:533] Started "attachdetach"
W0625 11:41:46.870434    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="parent1-cm-2-20200522111616000000" does not exist
W0625 11:41:46.870866    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="parent1-apiserver-20200522101925000002" does not exist
W0625 11:41:46.871991    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="mongo-mortar-1-20200615120249000003" does not exist
I0625 11:41:46.870347    9145 attach_detach_controller.go:338] Starting attach detach controller
I0625 11:41:46.872184    9145 shared_informer.go:223] Waiting for caches to sync for attach detach
W0625 11:41:46.872215    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="parent1-k8s-parent1-etcd-2" does not exist
W0625 11:41:46.872301    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="synthetics-browser-1-20200619123418000002" does not exist
W0625 11:41:46.872413    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="sre-default-3-20200522075651000001" does not exist
W0625 11:41:46.872505    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="mortar-cronjobs-2-20200615120849000003" does not exist
W0625 11:41:46.872631    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="control-plane-2-20200522094302000000" does not exist
W0625 11:41:46.872728    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="control-plane-3-20200522095201000003" does not exist
W0625 11:41:46.872826    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="cluster-controllers-2-20200523175113000002" does not exist
W0625 11:41:46.872920    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="cluster-controllers-3-20200523172117000009" does not exist
W0625 11:41:46.873013    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="parent1-apiserver-20200522101925000000" does not exist
W0625 11:41:46.873109    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="mortar-luigi-runner-1-20200615120849000002" does not exist
W0625 11:41:46.873205    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="mortar-luigi-runner-2-20200615120849000003" does not exist
W0625 11:41:46.873326    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="sre-default-2-20200522123443000001" does not exist
W0625 11:41:46.873420    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="parent1-scheduler-3-20200522114003000000" does not exist
W0625 11:41:46.873510    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="sre-default-1-20200522150839000001" does not exist
W0625 11:41:46.873602    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="cluster-dns-1-20200513195335000001" does not exist
W0625 11:41:46.873689    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="synthetics-api-1-20200619123418000002" does not exist
W0625 11:41:46.873761    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="parent1-scheduler-2-20200522114003000000" does not exist
W0625 11:41:46.873784    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="synthetics-browser-3-20200619123418000003" does not exist
W0625 11:41:46.873805    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="cluster-controllers-3-20200523172117000004" does not exist
W0625 11:41:46.873825    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="mortar-v2-1-20200615120849000002" does not exist
W0625 11:41:46.873843    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="sre-default-1-20200522150839000008" does not exist
W0625 11:41:46.873864    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="mortar-v2-3-20200615120849000006" does not exist
W0625 11:41:46.873882    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="synthetics-api-2-20200619123418000003" does not exist
W0625 11:41:46.873911    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="mongo-mortar-2-20200615120249000002" does not exist
W0625 11:41:46.873937    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="cluster-monitoring-2-20200513201833000000" does not exist
W0625 11:41:46.873957    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="manifest-generator-1-20200513201833000003" does not exist
W0625 11:41:46.873977    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="mortar-luigi-runner-3-20200615120849000002" does not exist
W0625 11:41:46.873997    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="cluster-dns-2-20200513200702000001" does not exist
W0625 11:41:46.874014    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="mongo-mortar-3-20200615120249000002" does not exist
W0625 11:41:46.874033    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="sre-default-3-2020052207565100000c" does not exist
W0625 11:41:46.874051    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="synthetics-browser-2-20200619123418000002" does not exist
W0625 11:41:46.874071    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="cluster-controllers-2-20200523175113000007" does not exist
W0625 11:41:46.874089    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="parent1-scheduler-1-20200522121655000000" does not exist
W0625 11:41:46.874107    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="sre-default-2-2020052212344300000v" does not exist
W0625 11:41:46.874127    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="control-plane-1-20200522092307000000" does not exist
W0625 11:41:46.874148    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="cluster-controllers-2-20200523175113000004" does not exist
W0625 11:41:46.874166    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="synthetics-api-3-20200619123418000002" does not exist
W0625 11:41:46.874188    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="mortar-cronjobs-1-20200615120849000004" does not exist
W0625 11:41:46.874207    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="mortar-cronjobs-3-20200615120849000002" does not exist
W0625 11:41:46.874227    9145 actual_state_of_world.go:506] Failed to update statusUpdateNeeded field in actual state of world: Failed to set statusUpdateNeeded to needed true, because nodeName="mortar-v2-2-20200615120849000003" does not exist
I0625 11:41:47.713374    9145 controllermanager.go:533] Started "cronjob"
W0625 11:41:47.713503    9145 controllermanager.go:525] Skipping "nodeipam"
I0625 11:41:47.713449    9145 cronjob_controller.go:97] Starting CronJob Manager
I0625 11:41:48.694440    9145 node_lifecycle_controller.go:78] Sending events to api server
I0625 11:41:48.694537    9145 controllermanager.go:533] Started "cloud-node-lifecycle"
E0625 11:41:54.243429    9145 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1417 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x47af340, 0x783ba40)
        /home/jb/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x131
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/jb/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0xd8
panic(0x47af340, 0x783ba40)
        /usr/local/src/go/src/runtime/panic.go:975 +0x41b
k8s.io/legacy-cloud-providers/azure.(*Cloud).InstanceShutdownByProviderID(0xc000618000, 0x58c9560, 0xc00005e110, 0xc000803080, 0xc0, 0x0, 0x0, 0x0)
        /home/jb/go/src/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_instances.go:209 +0x9c
k8s.io/kubernetes/pkg/controller/cloud.shutdownInCloudProvider(0x58c9560, 0xc00005e110, 0x590b600, 0xc000618000, 0xc0009db190, 0xc000d21900, 0x0, 0x0)
        /home/jb/go/src/k8s.io/kubernetes/pkg/controller/cloud/node_lifecycle_controller.go:207 +0x116
k8s.io/kubernetes/pkg/controller/cloud.(*CloudNodeLifecycleController).MonitorNodes(0xc0005f2820)
        /home/jb/go/src/k8s.io/kubernetes/pkg/controller/cloud/node_lifecycle_controller.go:153 +0x74f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000c2efb0)
        /home/jb/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x63
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000d21fb0, 0x585dd00, 0xc0010ebef0, 0x78a0a01, 0x0)
        /home/jb/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x92
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000c2efb0, 0x12a05f200, 0x0, 0x1, 0x0)
        /home/jb/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x9f
k8s.io/apimachinery/pkg/util/wait.Until(0xc000c2efb0, 0x12a05f200, 0x0)
        /home/jb/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
k8s.io/kubernetes/pkg/controller/cloud.(*CloudNodeLifecycleController).Run(0xc0005f2820, 0x0)
        /home/jb/go/src/k8s.io/kubernetes/pkg/controller/cloud/node_lifecycle_controller.go:115 +0xe0
created by k8s.io/kubernetes/cmd/kube-controller-manager/app.startCloudNodeLifecycleController
        /home/jb/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/core.go:233 +0x313
E0625 11:41:54.243602    9145 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1417 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x47af340, 0x783ba40)
        /home/jb/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x131
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/jb/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0xd8
panic(0x47af340, 0x783ba40)
        /usr/local/src/go/src/runtime/panic.go:975 +0x41b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/jb/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x1ae
panic(0x47af340, 0x783ba40)
        /usr/local/src/go/src/runtime/panic.go:975 +0x41b
k8s.io/legacy-cloud-providers/azure.(*Cloud).InstanceShutdownByProviderID(0xc000618000, 0x58c9560, 0xc00005e110, 0xc000803080, 0xc0, 0x0, 0x0, 0x0)
        /home/jb/go/src/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers/azure/azure_instances.go:209 +0x9c
k8s.io/kubernetes/pkg/controller/cloud.shutdownInCloudProvider(0x58c9560, 0xc00005e110, 0x590b600, 0xc000618000, 0xc0009db190, 0xc000d21900, 0x0, 0x0)
        /home/jb/go/src/k8s.io/kubernetes/pkg/controller/cloud/node_lifecycle_controller.go:207 +0x116
k8s.io/kubernetes/pkg/controller/cloud.(*CloudNodeLifecycleController).MonitorNodes(0xc0005f2820)
        /home/jb/go/src/k8s.io/kubernetes/pkg/controller/cloud/node_lifecycle_controller.go:153 +0x74f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000c2efb0)
        /home/jb/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x63
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000d21fb0, 0x585dd00, 0xc0010ebef0, 0x78a0a01, 0x0)
        /home/jb/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x92
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000c2efb0, 0x12a05f200, 0x0, 0x1, 0x0)
        /home/jb/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x9f
k8s.io/apimachinery/pkg/util/wait.Until(0xc000c2efb0, 0x12a05f200, 0x0)
        /home/jb/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
k8s.io/kubernetes/pkg/controller/cloud.(*CloudNodeLifecycleController).Run(0xc0005f2820, 0x0)
        /home/jb/go/src/k8s.io/kubernetes/pkg/controller/cloud/node_lifecycle_controller.go:115 +0xe0
created by k8s.io/kubernetes/cmd/kube-controller-manager/app.startCloudNodeLifecycleController
        /home/jb/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/core.go:233 +0x313
```

**What you expected to happen**:

Produce an error message as my configuration lacks some options.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.4
- Cloud provider or hardware configuration: Azure
- Others: 

--cloud-config=
```json
 {
   "subscriptionId": "***-***-***-***-***",
   "resourceGroup": "***",
   "location": "westus2",
   "vnetName": "***",
   "vnetResourceGroup": "***",
   "vmType": "vmss",
   "loadBalancerSku": "standard",
   "useManagedIdentityExtension": false,
   "excludeMasterFromStandardLB": true,
   "cloudConfigType": "file",
   "useInstanceMetadata": false
 }
```

The panics come from https://github.com/kubernetes/kubernetes/blob/934b4150ae526b53eb8a71832c69655d0026bebe/staging/src/k8s.io/legacy-cloud-providers/azure/azure_instances.go#L209  because we exit https://github.com/kubernetes/kubernetes/blob/934b4150ae526b53eb8a71832c69655d0026bebe/staging/src/k8s.io/legacy-cloud-providers/azure/azure.go#L460-L464 as we're not in this case https://github.com/kubernetes/kubernetes/blob/934b4150ae526b53eb8a71832c69655d0026bebe/staging/src/k8s.io/legacy-cloud-providers/azure/azure.go#L384-L389 as the `az.Config.CloudConfigType` is just defaulted-initialised by the caller to `""` here: https://github.com/kubernetes/kubernetes/blob/934b4150ae526b53eb8a71832c69655d0026bebe/staging/src/k8s.io/legacy-cloud-providers/azure/azure.go#L317-L327
and effectively assigned afterwards https://github.com/kubernetes/kubernetes/blob/934b4150ae526b53eb8a71832c69655d0026bebe/staging/src/k8s.io/legacy-cloud-providers/azure/azure.go#L452

**Comment by JulienBalestra** [comment]
cc @feiskyer

**Comment by feiskyer** [comment]
@JulienBalestra  thanks for reporting the issue and filing the PR to fix it
