### ISSUE TITLE
runtime error when running apiserver with HTTP Konnectivity egress

### ISSUE THREAD

**Issue by Avatat** [kubernetes/kubernetes#92690]
**What happened**:
apiserver crashes when I try to use it in connection with HTTP-mode Konnectivity egress:
```
I0630 16:48:03.703254       1 server.go:148] Version: v1.18.5
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x148514a]

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/egressselector.getTLSConfig(0x0, 0x0, 0xc00048c000, 0x7fda8179c6d0)
	/workspace/anago-v1.18.5-rc.1.1+d0eb837f519592/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/egressselector/egress_selector.go:244 +0x3a
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/egressselector.connectionToDialerCreator(0xc00077c300, 0xb, 0xc00055f560, 0x0, 0x0, 0x14813ac)
	/workspace/anago-v1.18.5-rc.1.1+d0eb837f519592/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/egressselector/egress_selector.go:294 +0x24e
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/egressselector.NewEgressSelector(0xc0005b45c0, 0x77427d8, 0x0, 0x0)
	/workspace/anago-v1.18.5-rc.1.1+d0eb837f519592/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/egressselector/egress_selector.go:351 +0x19b
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/options.(*EgressSelectorOptions).ApplyTo(0xc0004251a0, 0xc0005b8000, 0xc00055eeb0, 0x514d660)
	/workspace/anago-v1.18.5-rc.1.1+d0eb837f519592/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/options/egress_selector.go:71 +0x196
k8s.io/kubernetes/cmd/kube-apiserver/app.buildGenericConfig(0xc0009cc580, 0xc000a44000, 0x40993a0, 0x30, 0x30, 0xc00020c200, 0xd0, 0xc000a400d0, 0x30, 0x30, ...)
	/workspace/anago-v1.18.5-rc.1.1+d0eb837f519592/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:444 +0x2b8
k8s.io/kubernetes/cmd/kube-apiserver/app.CreateKubeAPIServerConfig(0xc0009cc580, 0x0, 0x0, 0xc000a44000, 0x0, 0x0, 0xc00075b4f8, 0x42ef01, 0x46f17d0, 0xc00075b508, ...)
	/workspace/anago-v1.18.5-rc.1.1+d0eb837f519592/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:279 +0x50
k8s.io/kubernetes/cmd/kube-apiserver/app.CreateServerChain(0xc0009cc580, 0xc0002e1320, 0x455ae51, 0xc, 0xc00075bc48)
	/workspace/anago-v1.18.5-rc.1.1+d0eb837f519592/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:170 +0x74
k8s.io/kubernetes/cmd/kube-apiserver/app.Run(0xc0009cc580, 0xc0002e1320, 0x0, 0x0)
	/workspace/anago-v1.18.5-rc.1.1+d0eb837f519592/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:150 +0x101
k8s.io/kubernetes/cmd/kube-apiserver/app.NewAPIServerCommand.func1(0xc0009d4000, 0xc00004ca00, 0x0, 0x1f, 0x0, 0x0)
	/workspace/anago-v1.18.5-rc.1.1+d0eb837f519592/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:117 +0x104
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0009d4000, 0xc0000ca210, 0x1f, 0x1f, 0xc0009d4000, 0xc0000ca210)
	/workspace/anago-v1.18.5-rc.1.1+d0eb837f519592/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:826 +0x460
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0009d4000, 0x161d6042ebe65c06, 0x7724600, 0xc00007a750)
	/workspace/anago-v1.18.5-rc.1.1+d0eb837f519592/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/anago-v1.18.5-rc.1.1+d0eb837f519592/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
main.main()
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-apiserver/apiserver.go:43 +0xcd
```

**What you expected to happen**:
Apiserver should start normally. Konnectivity in UDS mode works OK.

**How to reproduce it (as minimally and precisely as possible)**:
Set up Konnectivity services, and set below configuration as   :
```
apiVersion: apiserver.k8s.io/v1beta1
kind: EgressSelectorConfiguration
egressSelections:
- name: cluster
  connection:
    proxyProtocol: HTTPConnect
    transport:
      tcp:
        url: http://kubernetes:8131
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.5
- Cloud provider or hardware configuration: Selfhosted, VMware VMs
- OS (e.g: `cat /etc/os-release`): Debian 9
- Kernel (e.g. `uname -a`): 4.9.0-6-amd64
- Install tools: Docker image
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ialidzhikov** [comment]
@Avatat , I see that the referenced issue kubernetes-sigs/apiserver-network-proxy#123 is now fixed. Can we close this one?

**Comment by Avatat** [comment]
I think, that this issue is not relevant to the closed issue kubernetes-sigs/apiserver-network-proxy#123.
I can check this issue on the newest Kubernetes release.

**Comment by cheftako** [comment]
/assign @Jefftree 
Jeffrey mind taking a look at this?

**Comment by Jefftree** [comment]
I have a feeling this is related to https://github.com/kubernetes/kubernetes/pull/90223. 

@cheftako @caesarxuchao are we still looking to support a TCP socket between apiserver <-> konnectivity server or should we restrict to UDS only? GCE technically doesn't support TCP socket anymore.

**Comment by Avatat** [comment]
@cheftako, @caesarxuchao, ping :)
