### ISSUE TITLE
apiserver panic'd on GET /readyz

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#93599]
**What happened**:

```
curl -k https://localhost:8443/readyz
```

for extension API server panics with:

```
E0731 10:34:30.708313       1 wrap.go:39] apiserver panic'd on GET /readyz
I0731 10:34:30.708391       1 log.go:181] http2: panic serving 127.0.0.1:50412: assignment to entry in nil map
goroutine 262642 [running]:
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc0221c4720)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0x107
panic(0x1f49a20, 0x2660740)
	/usr/local/go/src/runtime/panic.go:969 +0x166
k8s.io/apiserver/pkg/server/healthz.(*informerSync).Check(0xc000d01e90, 0xc0221f8e00, 0x2227b52, 0xd)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go:108 +0x1cb
k8s.io/apiserver/pkg/server/healthz.handleRootHealthz.func1(0x7fcbc0171188, 0xc01ee49428, 0xc0221f8e00)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go:208 +0xa7b
net/http.HandlerFunc.ServeHTTP(0xc009314080, 0x7fcbc0171188, 0xc01ee49428, 0xc0221f8e00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc005d39c40, 0x7fcbc0171188, 0xc01ee49428, 0xc0221f8e00)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:241 +0x544
k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc0002cb6c0, 0x7fcbc0171188, 0xc01ee49428, 0xc0221f8e00)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x84
k8s.io/apiserver/pkg/server.director.ServeHTTP(0x222ff0a, 0x12, 0xc0005d0480, 0xc0002cb6c0, 0x7fcbc0171188, 0xc01ee49428, 0xc0221f8e00)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/server/handler.go:154 +0x69a
k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7fcbc0171188, 0xc01ee49428, 0xc0221f8e00)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x512
net/http.HandlerFunc.ServeHTTP(0xc00059e6c0, 0x7fcbc0171188, 0xc01ee49428, 0xc0221f8e00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7fcbc0171188, 0xc01ee49428, 0xc0221f8e00)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:160 +0x57e
net/http.HandlerFunc.ServeHTTP(0xc0009030b0, 0x7fcbc0171188, 0xc01ee49428, 0xc0221f8e00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7fcbc0171188, 0xc01ee49428, 0xc0221f8e00)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x1f9b
net/http.HandlerFunc.ServeHTTP(0xc00059e700, 0x7fcbc0171188, 0xc01ee49428, 0xc0221f8e00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithAudit.func1(0x7fcbc0171188, 0xc01ee49428, 0xc0221f8e00)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/endpoints/filters/audit.go:54 +0x751
net/http.HandlerFunc.ServeHTTP(0xc00059e740, 0x7fcbc0171188, 0xc01ee49428, 0xc0221f8e00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7fcbc0171188, 0xc01ee49428, 0xc0221f8d00)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:131 +0x9fb
net/http.HandlerFunc.ServeHTTP(0xc000d22640, 0x7fcbc0171188, 0xc01ee49428, 0xc0221f8d00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc0221c4720, 0xc000b269e0, 0x26df5c0, 0xc01ee49428, 0xc0221f8d00)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:113 +0xb8
created by k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:99 +0x1c0

goroutine 262641 [running]:
golang.org/x/net/http2.(*serverConn).runHandler.func1(0xc01ee49420, 0xc019641f8e, 0xc022200900)
	/go/src/github.com/gardener/gardener/vendor/golang.org/x/net/http2/server.go:2139 +0x16b
panic(0x1e9d2e0, 0xc021e8a350)
	/usr/local/go/src/runtime/panic.go:969 +0x166
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc019641c98, 0x1, 0x1)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1e9d2e0, 0xc021e8a350)
	/usr/local/go/src/runtime/panic.go:969 +0x166
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc000b269e0, 0x26d7f40, 0xc0221dacb0, 0xc0221f8d00)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:119 +0x433
k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x26d7f40, 0xc0221dacb0, 0xc0221f8c00)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:47 +0x113
net/http.HandlerFunc.ServeHTTP(0xc0009030e0, 0x26d7f40, 0xc0221dacb0, 0xc0221f8c00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x26d7f40, 0xc0221dacb0, 0xc0221f8b00)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x274
net/http.HandlerFunc.ServeHTTP(0xc000903110, 0x26d7f40, 0xc0221dacb0, 0xc0221f8b00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithCacheControl.func1(0x26d7f40, 0xc0221dacb0, 0xc0221f8b00)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/endpoints/filters/cachecontrol.go:31 +0xa8
net/http.HandlerFunc.ServeHTTP(0xc000b26a00, 0x26d7f40, 0xc0221dacb0, 0xc0221f8b00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x26cb1c0, 0xc01ee49420, 0xc0221f8a00)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:89 +0x2b6
net/http.HandlerFunc.ServeHTTP(0xc000b26a20, 0x26cb1c0, 0xc01ee49420, 0xc0221f8a00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x26cb1c0, 0xc01ee49420, 0xc0221f8a00)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:51 +0xe6
net/http.HandlerFunc.ServeHTTP(0xc000b26a40, 0x26cb1c0, 0xc01ee49420, 0xc0221f8a00)
	/usr/local/go/src/net/http/server.go:2041 +0x44
k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc000903140, 0x26cb1c0, 0xc01ee49420, 0xc0221f8a00)
	/go/src/github.com/gardener/gardener/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc009a1a620, 0x26cb1c0, 0xc01ee49420, 0xc0221f8a00)
	/usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.initALPNRequest.ServeHTTP(0x26df100, 0xc0221fc390, 0xc022077500, 0xc009a1a620, 0x26cb1c0, 0xc01ee49420, 0xc0221f8a00)
	/usr/local/go/src/net/http/server.go:3410 +0x8d
golang.org/x/net/http2.(*serverConn).runHandler(0xc022200900, 0xc01ee49420, 0xc0221f8a00, 0xc022063fc0)
	/go/src/github.com/gardener/gardener/vendor/golang.org/x/net/http2/server.go:2146 +0x8b
created by golang.org/x/net/http2.(*serverConn).processHeaders
	/go/src/github.com/gardener/gardener/vendor/golang.org/x/net/http2/server.go:1880 +0x4db
```

Apparently https://github.com/kubernetes/kubernetes/pull/92644 introduces this panic with `assignment to entry in nil map`.

**What you expected to happen**:
`/readyz` to do not panic.

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup extension API server with k8s.io/apiserver@v0.17.9 - for example k8s.io/sample-apiserver

2. curl the `/readyz` endpoint

3. Ensure that the apiserver panics with `assignment to entry in nil map`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `k8s.io/apiserver@v0.17.9` / `k8s.io/sample-apiserver@v0.17.9`
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by liggitt** [comment]
cc @wojtek-t

**Comment by wojtek-t** [comment]
Oops - sorry for that.
It seems it is basically this comment: https://github.com/kubernetes/kubernetes/pull/92644#discussion_r447850444 that I blindly applied without e2e retesting (the problem seem to be lack of tests, which is a bit surprising because bugs in my previous implementations were caught by tests).

@logicalhan ^^

BTW - this has been cherrypicked to previous releases:
1.16: https://github.com/kubernetes/kubernetes/pull/92695
1.17: https://github.com/kubernetes/kubernetes/pull/92694
1.18: https://github.com/kubernetes/kubernetes/pull/92693

so it's actually even more critical...

**Comment by ialidzhikov** [comment]
> BTW - this has been cherrypicked to previous releases:
> 1.16: #92695
> 1.17: #92694
> 1.18: #92693
> 
> so it's actually even more critical...

I can file the automated cherry-pick PRs once the PR against the master branch is merged. :)

**Comment by wojtek-t** [comment]
Reopening - since we need to cherrypick it still.

**Comment by ialidzhikov** [comment]
I now opened the cherry-picks:
1.16 - https://github.com/kubernetes/kubernetes/pull/93644
1.17 - https://github.com/kubernetes/kubernetes/pull/93643
1.18 - https://github.com/kubernetes/kubernetes/pull/93642

**Comment by liggitt** [comment]
Fix and picks are merged
