### ISSUE TITLE
Daemonset TestExpectationsOnRecreate fails consistently

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#93604]
**Which jobs are failing**:

TestExpectationsOnRecreate unit test, added in https://github.com/kubernetes/kubernetes/pull/91915 along with expectations bugfix during 1.19 and cherry-picked to 1.18/1.17

**Which test(s) are failing**:

`go test -race -count=10 ./pkg/controller/daemon -run TestExpectationsOnRecreate`

**Reason for failure**:

```
--- FAIL: TestExpectationsOnRecreate (0.21s)
    daemon_controller_test.go:548: Unexpected item in the queue
```

```
--- FAIL: TestExpectationsOnRecreate (0.22s)
    daemon_controller_test.go:569: There should be no expectations for DaemonSet "default/test" after it was deleted
    daemon_controller_test.go:620: No expectations found for DaemonSet "default/test"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x293b910]

goroutine 60 [running]:
testing.tRunner.func1.1(0x2c29a00, 0x3b02a50)
	/Users/liggitt/.gvm/gos/go1.15rc1/src/testing/testing.go:1057 +0x46a
testing.tRunner.func1(0xc000551c80)
	/Users/liggitt/.gvm/gos/go1.15rc1/src/testing/testing.go:1060 +0x636
panic(0x2c29a00, 0x3b02a50)
	/Users/liggitt/.gvm/gos/go1.15rc1/src/runtime/panic.go:975 +0x3e9
k8s.io/kubernetes/pkg/controller.(*ControlleeExpectations).Fulfilled(0x0, 0x2e22477)
	/Users/liggitt/go/src/k8s.io/kubernetes/pkg/controller/controller_utils.go:284 +0x30
k8s.io/kubernetes/pkg/controller/daemon.TestExpectationsOnRecreate(0xc000551c80)
	/Users/liggitt/go/src/k8s.io/kubernetes/pkg/controller/daemon/daemon_controller_test.go:622 +0x2379
testing.tRunner(0xc000551c80, 0x2ea96e0)
	/Users/liggitt/.gvm/gos/go1.15rc1/src/testing/testing.go:1108 +0x203
created by testing.(*T).Run
	/Users/liggitt/.gvm/gos/go1.15rc1/src/testing/testing.go:1159 +0x797
```

**Anything else we need to know**:

These failures are masked in CI because bazel test runs with flake retries (https://github.com/kubernetes/kubernetes/blob/master/build/root/.bazelrc#L32), so the test can fail 2/3 times and the job can still pass (cc @BenTheElder)

**Comment by liggitt** [comment]
adding to the milestone for triage, in case this is a real bug and not just a test issue

/milestone v1.19

**Comment by liggitt** [comment]
cc @kubernetes/sig-apps-test-failures

**Comment by liggitt** [comment]
looks like the panic is due to the test continuing in the !exists case (rather than exiting with a Fatal):

https://github.com/kubernetes/kubernetes/blob/6324c137ea26daa56faabed3d9c0d7bea1271bde/pkg/controller/daemon/daemon_controller_test.go#L615-L624

however, that still means the test is failing in two distinct places: 

```
daemon_controller_test.go:548: Unexpected item in the queue
```

```
daemon_controller_test.go:569: There should be no expectations for DaemonSet "default/test" after it was deleted
```
```
daemon_controller_test.go:620: No expectations found for DaemonSet "default/test"
```

**Comment by liggitt** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93605/pull-kubernetes-bazel-test/1289254188986929154

**Comment by liggitt** [comment]
it looks like the same failure existed in 1.18, so this probably isn't release blocking, but it does need to be resolved in order for us to stop ignoring unit test flakes in CI runs

**Comment by liggitt** [comment]
it actually looks like this test was added during the 1.19 dev cycle and cherry-picked back to 1.18/1.17, which is why release-1.18 is failing :-/

**Comment by liggitt** [comment]
figured it out... the controller sync is updating the DS, which is triggering an update event and adding an extra enqueue which the test did not account for

**Comment by liggitt** [comment]
possible test deflake in https://github.com/kubernetes/kubernetes/pull/93605
