### ISSUE TITLE
local-up-cluster.sh scheduler terminated unexpectedly

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes/kubernetes#93753]
**What happened**:
Attempting to run hack/local-up-cluster.sh deploys a cluster locally, but the scheduler terminated unexpectedly.  This results in pods not getting scheduled to the kubelet.

**What you expected to happen**:
Scheduler doesn't fail and pods are run as expected.

**How to reproduce it (as minimally and precisely as possible)**:
Followed instructions here: https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md

Checkout master, install docker, install etcd.
```sh
$ docker --version
Docker version 19.03.12, build 48a66213fe
$ etcd --version
etcd Version: 3.5.0-pre
Git SHA: Not provided (use ./build instead of go build)
Go Version: go1.12.6
Go OS/Arch: linux/amd64
```

Run hack/local-up-cluster.sh

Enter sudo password at prompt

**Anything else we need to know?**:
```sh
# cat /tmp/kube-scheduler.log
F0806 10:20:19.656222   39689 server.go:67] unable to initialize command options: converting (v1alpha1.LeaderElectionConfiguration) to (config.LeaderElectionConfiguration): unknown conversion
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00000e001, 0xc000442120, 0xc0, 0x113)
	/home/myuser/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:996 +0xb8
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x2ebe6a0, 0xc000000003, 0x0, 0x0, 0xc0003c71f0, 0x2ddd6b4, 0x9, 0x43, 0x0)
	/home/myuser/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:945 +0x19d
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printf(0x2ebe6a0, 0x3, 0x0, 0x0, 0x1c56580, 0x28, 0xc0004e3ea8, 0x1, 0x1)
	/home/myuser/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:733 +0x17b
k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatalf(...)
	/home/myuser/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1456
k8s.io/kubernetes/cmd/kube-scheduler/app.NewSchedulerCommand(0x0, 0x0, 0x0, 0x405c6f)
	/home/myuser/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:67 +0xd8
main.main()
	_output/local/go/src/k8s.io/kubernetes/cmd/kube-scheduler/scheduler.go:36 +0xc8

goroutine 6 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2ebe6a0)
	/home/myuser/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1131 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
	/home/myuser/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:416 +0xd6

goroutine 29 [sleep]:
time.Sleep(0x3b9aca00)
	/home/myuser/go_dists/go-1.14.6/src/runtime/time.go:188 +0xba
k8s.io/kubernetes/pkg/scheduler/framework/runtime.(*metricsRecorder).run(0xc000714840)
	/home/myuser/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/scheduler/framework/runtime/metrics_recorder.go:88 +0x3f
created by k8s.io/kubernetes/pkg/scheduler/framework/runtime.newMetricsRecorder
	/home/myuser/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/scheduler/framework/runtime/metrics_recorder.go:60 +0x104
```
**Environment**:
- Kubernetes version (use `kubectl version`):
```sh
./cluster/kubectl.sh version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-alpha.0.511+aa0632208ec0a2-dirty", GitCommit:"aa0632208ec0a2191e956d86f3406afbb497b881", GitTreeState:"dirty", BuildDate:"2020-08-06T14:18:41Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"}
error: You must be logged in to the server (the server has asked for the client to provide credentials)
```

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Fedora 31
- Kernel (e.g. `uname -a`): 5.7.11-100.fc31.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others: 

k/k commit: aa0632208ec0a2191e956d86f3406afbb497b881

**Comment by SataQiu** [comment]
/assign
Thanks @michaelgugino ! I'm going to check this again.

**Comment by SataQiu** [comment]
Hi @michaelgugino! I just cannot reproduce this issue based on the latest code.
I tried many times (on CentOS 7 system), but it seemed to work just fine! 
```sh
[root@dev kubernetes]# ./hack/local-up-cluster.sh
make: 进入目录“/root/kubernetes-master”
make[1]: 进入目录“/root/kubernetes-master”
make[1]: 离开目录“/root/kubernetes-master”
+++ [0807 20:53:14] Building go targets for linux/amd64:
    cmd/kubectl
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/cloud-controller-manager
    cmd/kubelet
    cmd/kube-proxy
    cmd/kube-scheduler
make: 离开目录“/root/kubernetes-master”
Kubelet cgroup driver defaulted to use: cgroupfs
API SERVER insecure port is free, proceeding...
API SERVER secure port is free, proceeding...
Unable to successfully run 'cfssl' from /opt/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin; downloading instead...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9.8M  100  9.8M    0     0   271k      0  0:00:37  0:00:37 --:--:--  207k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2224k  100 2224k    0     0   200k      0  0:00:11  0:00:11 --:--:--  343k
Detected host and ready to start services.  Doing some housekeeping first...
Using GO_OUT /root/kubernetes-master/_output/local/bin/linux/amd64
Starting services now!
Starting etcd
etcd --advertise-client-urls http://127.0.0.1:2379 --data-dir /tmp/tmp.rmPdMn0lb4 --listen-client-urls http://127.0.0.1:2379 --log-level=debug > "/tmp/etcd.log" 2>/dev/null
Waiting for etcd to come up.
+++ [0807 20:54:36] On try 2, etcd: : {"health":"true"}
{"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"2","raft_term":"2"}}Generating a 2048 bit RSA private key
............................+++
..................................+++
writing new private key to '/var/run/kubernetes/server-ca.key'
-----
Generating a 2048 bit RSA private key
...+++
.........................................................................+++
writing new private key to '/var/run/kubernetes/client-ca.key'
-----
Generating a 2048 bit RSA private key
..............................................+++
...................................................................................................+++
writing new private key to '/var/run/kubernetes/request-header-ca.key'
-----
2020/08/07 20:54:37 [INFO] generate received request
2020/08/07 20:54:37 [INFO] received CSR
2020/08/07 20:54:37 [INFO] generating key: rsa-2048
2020/08/07 20:54:37 [INFO] encoded CSR
2020/08/07 20:54:37 [INFO] signed certificate with serial number 121621560917450708010039650368934907179672536209
2020/08/07 20:54:37 [WARNING] This certificate lacks a "hosts" field. This makes it unsuitable for
websites. For more information see the Baseline Requirements for the Issuance and Management
of Publicly-Trusted Certificates, v.1.1.6, from the CA/Browser Forum (https://cabforum.org);
specifically, section 10.2.3 ("Information Requirements").
2020/08/07 20:54:37 [INFO] generate received request
2020/08/07 20:54:37 [INFO] received CSR
2020/08/07 20:54:37 [INFO] generating key: rsa-2048
2020/08/07 20:54:37 [INFO] encoded CSR
2020/08/07 20:54:37 [INFO] signed certificate with serial number 72490910634438577152962736160473491460630622035
2020/08/07 20:54:37 [WARNING] This certificate lacks a "hosts" field. This makes it unsuitable for
websites. For more information see the Baseline Requirements for the Issuance and Management
of Publicly-Trusted Certificates, v.1.1.6, from the CA/Browser Forum (https://cabforum.org);
specifically, section 10.2.3 ("Information Requirements").
2020/08/07 20:54:37 [INFO] generate received request
2020/08/07 20:54:37 [INFO] received CSR
2020/08/07 20:54:37 [INFO] generating key: rsa-2048
2020/08/07 20:54:38 [INFO] encoded CSR
2020/08/07 20:54:38 [INFO] signed certificate with serial number 188139266891910949315392422840414451909081993078
2020/08/07 20:54:38 [WARNING] This certificate lacks a "hosts" field. This makes it unsuitable for
websites. For more information see the Baseline Requirements for the Issuance and Management
of Publicly-Trusted Certificates, v.1.1.6, from the CA/Browser Forum (https://cabforum.org);
specifically, section 10.2.3 ("Information Requirements").
2020/08/07 20:54:38 [INFO] generate received request
2020/08/07 20:54:38 [INFO] received CSR
2020/08/07 20:54:38 [INFO] generating key: rsa-2048
2020/08/07 20:54:38 [INFO] encoded CSR
2020/08/07 20:54:38 [INFO] signed certificate with serial number 396064005597989639594457632448946023525573416081
2020/08/07 20:54:38 [WARNING] This certificate lacks a "hosts" field. This makes it unsuitable for
websites. For more information see the Baseline Requirements for the Issuance and Management
of Publicly-Trusted Certificates, v.1.1.6, from the CA/Browser Forum (https://cabforum.org);
specifically, section 10.2.3 ("Information Requirements").
2020/08/07 20:54:38 [INFO] generate received request
2020/08/07 20:54:38 [INFO] received CSR
2020/08/07 20:54:38 [INFO] generating key: rsa-2048
2020/08/07 20:54:39 [INFO] encoded CSR
2020/08/07 20:54:39 [INFO] signed certificate with serial number 350289135549891480563025248690687479249393981469
2020/08/07 20:54:39 [WARNING] This certificate lacks a "hosts" field. This makes it unsuitable for
websites. For more information see the Baseline Requirements for the Issuance and Management
of Publicly-Trusted Certificates, v.1.1.6, from the CA/Browser Forum (https://cabforum.org);
specifically, section 10.2.3 ("Information Requirements").
2020/08/07 20:54:39 [INFO] generate received request
2020/08/07 20:54:39 [INFO] received CSR
2020/08/07 20:54:39 [INFO] generating key: rsa-2048
2020/08/07 20:54:39 [INFO] encoded CSR
2020/08/07 20:54:39 [INFO] signed certificate with serial number 361353513807772412331138797316676145265912863298
2020/08/07 20:54:39 [WARNING] This certificate lacks a "hosts" field. This makes it unsuitable for
websites. For more information see the Baseline Requirements for the Issuance and Management
of Publicly-Trusted Certificates, v.1.1.6, from the CA/Browser Forum (https://cabforum.org);
specifically, section 10.2.3 ("Information Requirements").
2020/08/07 20:54:39 [INFO] generate received request
2020/08/07 20:54:39 [INFO] received CSR
2020/08/07 20:54:39 [INFO] generating key: rsa-2048
2020/08/07 20:54:40 [INFO] encoded CSR
2020/08/07 20:54:40 [INFO] signed certificate with serial number 325173361148627732912390615640913406937400845816
2020/08/07 20:54:40 [WARNING] This certificate lacks a "hosts" field. This makes it unsuitable for
websites. For more information see the Baseline Requirements for the Issuance and Management
of Publicly-Trusted Certificates, v.1.1.6, from the CA/Browser Forum (https://cabforum.org);
specifically, section 10.2.3 ("Information Requirements").
2020/08/07 20:54:40 [INFO] generate received request
2020/08/07 20:54:40 [INFO] received CSR
2020/08/07 20:54:40 [INFO] generating key: rsa-2048
2020/08/07 20:54:40 [INFO] encoded CSR
2020/08/07 20:54:40 [INFO] signed certificate with serial number 624972336675177560829914031488350144556569862255
2020/08/07 20:54:40 [WARNING] This certificate lacks a "hosts" field. This makes it unsuitable for
websites. For more information see the Baseline Requirements for the Issuance and Management
of Publicly-Trusted Certificates, v.1.1.6, from the CA/Browser Forum (https://cabforum.org);
specifically, section 10.2.3 ("Information Requirements").
Waiting for apiserver to come up
+++ [0807 20:54:46] On try 5, apiserver: : ok
clusterrolebinding.rbac.authorization.k8s.io/kube-apiserver-kubelet-admin created
clusterrolebinding.rbac.authorization.k8s.io/kubelet-csr created
Cluster "local-up-cluster" set.
use 'kubectl --kubeconfig=/var/run/kubernetes/admin-kube-aggregator.kubeconfig' to use the aggregated API server
service/kube-dns created
serviceaccount/kube-dns created
configmap/kube-dns created
deployment.apps/kube-dns created
Kube-dns addon successfully deployed.
WARNING : The kubelet is configured to not fail even if swap is enabled; production deployments should disable swap.
2020/08/07 20:54:47 [INFO] generate received request
2020/08/07 20:54:47 [INFO] received CSR
2020/08/07 20:54:47 [INFO] generating key: rsa-2048
2020/08/07 20:54:48 [INFO] encoded CSR
2020/08/07 20:54:48 [INFO] signed certificate with serial number 321630456951986789318368049954370274764894852858
2020/08/07 20:54:48 [WARNING] This certificate lacks a "hosts" field. This makes it unsuitable for
websites. For more information see the Baseline Requirements for the Issuance and Management
of Publicly-Trusted Certificates, v.1.1.6, from the CA/Browser Forum (https://cabforum.org);
specifically, section 10.2.3 ("Information Requirements").
kubelet ( 12006 ) is running.
wait kubelet ready
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
127.0.0.1   NotReady   <none>   2s    v0.0.0-master+97c5f1f7632f2
2020/08/07 20:55:04 [INFO] generate received request
2020/08/07 20:55:04 [INFO] received CSR
2020/08/07 20:55:04 [INFO] generating key: rsa-2048
2020/08/07 20:55:04 [INFO] encoded CSR
2020/08/07 20:55:04 [INFO] signed certificate with serial number 16041402685700807470924946424652246775390047025
2020/08/07 20:55:04 [WARNING] This certificate lacks a "hosts" field. This makes it unsuitable for
websites. For more information see the Baseline Requirements for the Issuance and Management
of Publicly-Trusted Certificates, v.1.1.6, from the CA/Browser Forum (https://cabforum.org);
specifically, section 10.2.3 ("Information Requirements").
Create default storage class for
storageclass.storage.k8s.io/standard created
Local Kubernetes cluster is running. Press Ctrl-C to shut it down.

Logs:
  /tmp/kube-apiserver.log
  /tmp/kube-controller-manager.log

  /tmp/kube-proxy.log
  /tmp/kube-scheduler.log
  /tmp/kubelet.log

To start using your cluster, you can open up another terminal/tab and run:

  export KUBECONFIG=/var/run/kubernetes/admin.kubeconfig
  cluster/kubectl.sh

Alternatively, you can write to the default kubeconfig:

  export KUBERNETES_PROVIDER=local

  cluster/kubectl.sh config set-cluster local --server=https://localhost:6443 --certificate-authority=/var/run/kubernetes/server-ca.crt
  cluster/kubectl.sh config set-credentials myself --client-key=/var/run/kubernetes/client-admin.key --client-certificate=/var/run/kubernetes/client-admin.crt
  cluster/kubectl.sh config set-context local --cluster=local --user=myself
  cluster/kubectl.sh config use-context local
  cluster/kubectl.sh
```

```sh
[root@dev kubernetes]#   export KUBECONFIG=/var/run/kubernetes/admin.kubeconfig
[root@dev kubernetes]#   cluster/kubectl.sh get node
NAME        STATUS   ROLES    AGE     VERSION
127.0.0.1   Ready    <none>   4m25s   v0.0.0-master+97c5f1f7632f2
```

**Comment by michaelgugino** [comment]
Updated to latest k8s master, things are working normally.  Did a diff between the current master tip (97c5f1f7632f2d349303515830be76f6c1084b19) and aa0632208ec0a2191e956d86f3406afbb497b881, nothing related found.

Checked out aa0632208ec0a2191e956d86f3406afbb497b881 to see if I still encountered the error, error is no longer present.

Based on the original error message 'converting (v1alpha1.LeaderElectionConfiguration) to (config.LeaderElectionConfiguration)' this seems like an error of some transient dependency.

Some web searching revealed this: https://github.com/kubernetes/kubernetes/issues/75188

Indeed, I had a locally modified deep copy as they did, but I did not make any modifications.  I had run the 'make verify' prior to running the cluster.

The make verify run had failed for some innocuous reason (install pyyaml), but left the mutated file.  I attempted this again and had the same results.  I'm going to try to get make verify to pass and record if the problem of the mutated deep copy file persists.

**Comment by ahg-g** [comment]
/close 

feel free to open again if this is still an issue

**Comment by phantooom** [comment]
i have the same issue

**Comment by michaelgugino** [comment]
I have been unable to run make verify successfully on Fedora using both golang 1.14 and 1.15.  I haven't had time to fully investigate.  Probably needs its own issue.
