### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by kvaps** [kubernetes/kubernetes#94361]
**What happened**:

During install v1.19 cluster can not finish coredns phase.
I guess https://github.com/kubernetes/kubernetes/issues/94286 is related, but for now it is not upgrade but clean install, also error is differet:

```
# kubeadm init phase addon coredns  --kubeconfig /etc/kubernetes/admin.conf
W0831 10:03:03.949390    1086 kubelet.go:200] cannot automatically set CgroupDriver when starting the Kubelet: cannot execute 'docker info -f {{.CgroupDriver}}': executable file not found in $PATH
W0831 10:03:03.949425    1086 kubelet.go:213] cannot determine if systemd-resolved is active: no supported init system detected, skipping checking for services
W0831 10:03:04.252273    1086 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
k8s.io/kubernetes/cmd/kubeadm/app/phases/addons/dns.isCoreDNSVersionSupported(0x1d5b6a0, 0xc0001d2000, 0xc000853400, 0xc0007449a0, 0x153)
	/workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/addons/dns/dns.go:413 +0x38f
k8s.io/kubernetes/cmd/kubeadm/app/phases/addons/dns.createCoreDNSAddon(0xc000b3e000, 0x7fb, 0xb5f, 0xc000904480, 0x309, 0x418, 0xc00092c400, 0x20a, 0x3dc, 0x1d5b6a0, ...)
	/workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/addons/dns/dns.go:271 +0x187
k8s.io/kubernetes/cmd/kubeadm/app/phases/addons/dns.coreDNSAddon(0xc0006ab6a0, 0x1d5b6a0, 0xc0001d2000, 0xc00014885c, 0x0, 0x0)
	/workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/addons/dns/dns.go:252 +0x505
k8s.io/kubernetes/cmd/kubeadm/app/phases/addons/dns.EnsureDNSAddon(0xc0006ab6a0, 0x1d5b6a0, 0xc0001d2000, 0x1d5b6a0, 0xc0001d2000)
	/workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/addons/dns/dns.go:109 +0x13e
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runCoreDNSAddon(0x1a58420, 0xc000207ce0, 0xc0006e0480, 0xd)
	/workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/addons.go:92 +0x85
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1(0xc00060e900, 0x0, 0x0)
	/workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234 +0x1e8
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll(0xc0005545a0, 0xc0005d5ce0, 0x0, 0x2)
	/workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:422 +0x6e
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run(0xc0005545a0, 0xc00052ab80, 0x0, 0x2, 0x726420, 0xc0004f9d48)
	/workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207 +0x153
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).BindToCommand.func1.1(0xc00077d340, 0xc00052ab80, 0x0, 0x2, 0x0, 0x0)
	/workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:348 +0xda
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc00077d340, 0xc00052ab60, 0x2, 0x2, 0xc00077d340, 0xc00052ab60)
	/workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:842 +0x47c
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0001d4000, 0xc000182000, 0x1cecec0, 0xc000182008)
	/workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:950 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:887
k8s.io/kubernetes/cmd/kubeadm/app.Run(0x0, 0x18249a0)
	/workspace/anago-v1.19.0-rc.4.197+594f888e19d8da/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50 +0x225
main.main()
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25 +0x25
```

**What you expected to happen**:

cordns succefully installed

**How to reproduce it (as minimally and precisely as possible)**

try to install coredns on cluster with no nodes
```
kubeadm init phase addon coredns
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.19.0
- Cloud provider or hardware configuration: kubefarm
- OS (e.g: `cat /etc/os-release`): ubuntu 20.04.1
- Kernel (e.g. `uname -a`): 5.4.0-42-generic
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:
  - [detailed_log.txt](https://github.com/kubernetes/kubernetes/files/5149706/detailed_log.txt)
  - [kubectl-pods.txt](https://github.com/kubernetes/kubernetes/files/5149707/kubectl-pods.txt)

**Comment by kvaps** [comment]
my bad, my etcd had some data previously, clean installation is working fine
