### ISSUE TITLE
[Flaky unit test] TestEventSeriesf timeout

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#94569]
**Which jobs are flaking**:

periodic-kubernetes-bazel-test-master (xref https://github.com/kubernetes/kubernetes/issues/94528#issuecomment-687208028)

**Which test(s) are flaking**:

k8s.io/client-go/tools/events TestEventSeriesf

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#bazel-test-master&width=20&sort-by-name=&include-filter-by-regex=k8s.io/client-go/tools/events/go

**Reason for failure**:

Timeout:

```
panic: test timed out:

goroutine 36 [running]:
testing.(*M).startAlarm.func1()
	/Users/liggitt/.gvm/gos/go1.15/src/testing/testing.go:1609 +0x11f
created by time.goFunc
	/Users/liggitt/.gvm/gos/go1.15/src/time/sleep.go:167 +0x52

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000370780, 0x27494fd, 0x10, 0x27de6e8, 0x0)
	/Users/liggitt/.gvm/gos/go1.15/src/testing/testing.go:1160 +0x7cf
testing.runTests.func1(0xc000370780)
	/Users/liggitt/.gvm/gos/go1.15/src/testing/testing.go:1430 +0xa7
testing.tRunner(0xc000370780, 0xc0000dfcc8)
	/Users/liggitt/.gvm/gos/go1.15/src/testing/testing.go:1108 +0x203
testing.runTests(0xc00036f2e0, 0x312d720, 0x3, 0x3, 0xbfcd324b557f0188, 0x12caa5938, 0x313ed80, 0x1)
	/Users/liggitt/.gvm/gos/go1.15/src/testing/testing.go:1428 +0x5ab
testing.(*M).Run(0xc0003a0000, 0x0)
	/Users/liggitt/.gvm/gos/go1.15/src/testing/testing.go:1338 +0x4ec
main.main()
	_testmain.go:47 +0x237

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x313f020)
	/Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1131 +0xb1
created by k8s.io/klog/v2.init.0
	/Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:416 +0x190

goroutine 7 [chan receive]:
k8s.io/client-go/tools/events.TestEventSeriesf(0xc000370900)
	/Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/events/eventseries_test.go:174 +0x170e
testing.tRunner(0xc000370900, 0x27de6e8)
	/Users/liggitt/.gvm/gos/go1.15/src/testing/testing.go:1108 +0x203
created by testing.(*T).Run
	/Users/liggitt/.gvm/gos/go1.15/src/testing/testing.go:1159 +0x797

goroutine 18 [chan receive]:
k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc000134000)
	/Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/mux.go:219 +0x8b
created by k8s.io/apimachinery/pkg/watch.NewBroadcaster
	/Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/mux.go:73 +0x1cb

goroutine 19 [chan send]:
k8s.io/client-go/tools/events.TestEventSeriesf.func3(0xc00012aa00, 0xc000049ae0, 0x
…
10407 runs so far, 1 failures
^C
[liggitt@liggitt-macbookpro2 kubernetes]$ more /var/folders/7f/9xt_73f12xlby0w362rgk0s400kjgb/T/go-stress-20200905T230234-934809070
panic: test timed out after 5s

goroutine 36 [running]:
testing.(*M).startAlarm.func1()
        /Users/liggitt/.gvm/gos/go1.15/src/testing/testing.go:1609 +0x11f
created by time.goFunc
        /Users/liggitt/.gvm/gos/go1.15/src/time/sleep.go:167 +0x52

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000370780, 0x27494fd, 0x10, 0x27de6e8, 0x0)
        /Users/liggitt/.gvm/gos/go1.15/src/testing/testing.go:1160 +0x7cf
testing.runTests.func1(0xc000370780)
        /Users/liggitt/.gvm/gos/go1.15/src/testing/testing.go:1430 +0xa7
testing.tRunner(0xc000370780, 0xc0000dfcc8)
        /Users/liggitt/.gvm/gos/go1.15/src/testing/testing.go:1108 +0x203
testing.runTests(0xc00036f2e0, 0x312d720, 0x3, 0x3, 0xbfcd324b557f0188, 0x12caa5938, 0x313ed80, 0x1)
        /Users/liggitt/.gvm/gos/go1.15/src/testing/testing.go:1428 +0x5ab
testing.(*M).Run(0xc0003a0000, 0x0)
        /Users/liggitt/.gvm/gos/go1.15/src/testing/testing.go:1338 +0x4ec
main.main()
        _testmain.go:47 +0x237

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x313f020)
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1131 +0xb1
created by k8s.io/klog/v2.init.0
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:416 +0x190

goroutine 7 [chan receive]:
k8s.io/client-go/tools/events.TestEventSeriesf(0xc000370900)
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/events/eventseries_test.go:174 +0x170e
testing.tRunner(0xc000370900, 0x27de6e8)
        /Users/liggitt/.gvm/gos/go1.15/src/testing/testing.go:1108 +0x203
created by testing.(*T).Run
        /Users/liggitt/.gvm/gos/go1.15/src/testing/testing.go:1159 +0x797

goroutine 18 [chan receive]:
k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc000134000)
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/mux.go:219 +0x8b
created by k8s.io/apimachinery/pkg/watch.NewBroadcaster
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/mux.go:73 +0x1cb

goroutine 19 [chan send]:
k8s.io/client-go/tools/events.TestEventSeriesf.func3(0xc00012aa00, 0xc000049ae0, 0x47, 0x50, 0x0, 0x0, 0x0)
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/events/eventseries_test.go:155 +0x56
k8s.io/client-go/tools/events.(*testEventSeriesSink).Patch(0xc000112040, 0xc00012aa00, 0xc000049ae0, 0x47, 0x50, 0x0, 0x0, 0xc00000e040)
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/events/eventseries_test.go:62 +0xa2
k8s.io/client-go/tools/events.recordEvent(0x2910820, 0xc000112040, 0xc00012aa00, 0x3170a84, 0xc00008db00)
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/events/event_broadcaster.go:231 +0x87b
k8s.io/client-go/tools/events.(*eventBroadcasterImpl).refreshExistingEventSeries(0xc000130060)
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/events/event_broadcaster.go:131 +0x226
k8s.io/client-go/tools/events.(*eventBroadcasterImpl).StartRecordingToSink.func1()
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/events/event_broadcaster.go:313 +0x45
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00012c050)
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x76
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00012c050, 0x28e4fc0, 0xc00036d020, 0x1, 0xc00012e000)
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xbb
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00012c050, 0x1a3185c5000, 0x0, 0x1, 0xc00012e000)
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x115
k8s.io/apimachinery/pkg/util/wait.Until(0xc00012c050, 0x1a3185c5000, 0xc00012e000)
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x5b
created by k8s.io/client-go/tools/events.(*eventBroadcasterImpl).StartRecordingToSink
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/events/event_broadcaster.go:312 +0xca

goroutine 20 [select]:
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00012c060, 0x28e4fc0, 0xc00040e000, 0x1, 0xc00012e000)
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x186
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00012c060, 0x53d1ac1000, 0x0, 0x1, 0xc00012e000)
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x115
k8s.io/apimachinery/pkg/util/wait.Until(0xc00012c060, 0x53d1ac1000, 0xc00012e000)
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x5b
created by k8s.io/client-go/tools/events.(*eventBroadcasterImpl).StartRecordingToSink
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/events/event_broadcaster.go:315 +0x15f

goroutine 21 [chan receive]:
k8s.io/client-go/tools/events.(*eventBroadcasterImpl).StartEventWatcher.func1(0x28edfa0, 0xc000130090, 0xc00012c070)
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/events/event_broadcaster.go:300 +0xf4
created by k8s.io/client-go/tools/events.(*eventBroadcasterImpl).StartEventWatcher
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/events/event_broadcaster.go:297 +0x90

goroutine 22 [chan receive]:
k8s.io/client-go/tools/events.(*eventBroadcasterImpl).StartRecordingToSink.func4(0xc00012e000, 0xc0001120a0)
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/events/event_broadcaster.go:328 +0x45
created by k8s.io/client-go/tools/events.(*eventBroadcasterImpl).StartRecordingToSink
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/events/event_broadcaster.go:327 +0x1f7

goroutine 26 [semacquire]:
sync.runtime_SemacquireMutex(0xc00013006c, 0x900000000, 0x1)
        /Users/liggitt/.gvm/gos/go1.15/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc000130068)
        /Users/liggitt/.gvm/gos/go1.15/src/sync/mutex.go:138 +0x1c5
sync.(*Mutex).Lock(0xc000130068)
        /Users/liggitt/.gvm/gos/go1.15/src/sync/mutex.go:81 +0x85
k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink.func1(0xc000130060, 0xc00012af00, 0x291a720, 0x31708c0)
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/events/event_broadcaster.go:196 +0x252
created by k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/events/event_broadcaster.go:171 +0x76

goroutine 35 [semacquire]:
sync.runtime_SemacquireMutex(0xc00013006c, 0x1100000000, 0x1)
        /Users/liggitt/.gvm/gos/go1.15/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc000130068)
        /Users/liggitt/.gvm/gos/go1.15/src/sync/mutex.go:138 +0x1c5
sync.(*Mutex).Lock(0xc000130068)
        /Users/liggitt/.gvm/gos/go1.15/src/sync/mutex.go:81 +0x85
k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink.func1.1(0xc000130060, 0xc0004a4280, 0x291a720, 0x31708c0, 0x0)
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/events/event_broadcaster.go:173 +0x70
k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink.func1(0xc000130060, 0xc0004a4280, 0x291a720, 0x31708c0)
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/events/event_broadcaster.go:191 +0x7d
created by k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink
        /Users/liggitt/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/events/event_broadcaster.go:171 +0x76
```

**Anything else we need to know**:
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=TestEventSeriesf

To reproduce with stress:
```
go test -race -c ./vendor/k8s.io/client-go/tools/events/
stress ./events.test -test.run TestEventSeriesf -test.timeout=10s
638 runs so far, 0 failures
1241 runs so far, 0 failures
1801 runs so far, 0 failures
2349 runs so far, 0 failures
2913 runs so far, 0 failures
3444 runs so far, 0 failures
3974 runs so far, 0 failures
4515 runs so far, 0 failures
5056 runs so far, 0 failures
5571 runs so far, 0 failures
5965 runs so far, 0 failures
6436 runs so far, 0 failures
6814 runs so far, 0 failures
7263 runs so far, 0 failures
7715 runs so far, 0 failures
8208 runs so far, 0 failures
8737 runs so far, 0 failures
9296 runs so far, 0 failures
9862 runs so far, 0 failures

/var/folders/7f/9xt_73f12xlby0w362rgk0s400kjgb/T/go-stress-20200905T230234-934809070
panic: test timed out after 10s
```

/cc @wojtek-t

**Comment by knight42** [comment]
filed #94570 to address this issue.

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/94570 contains the correct analysis of flakes (thanks a lot!), I commented on way of fixing it (which I'm not convinced about).
