### ISSUE TITLE
kubectl alpha debug fails with "panic: runtime error: index out of range"

### ISSUE THREAD

**Issue by kiyoshim55** [kubernetes/kubernetes#94579]
**What happened**:
When using `kubectl alpha debug` to create a debug container for a pod that has multiple init containers or ephemeral containers, `kubectl alpha debug` fails with `panic: runtime error: index out of range`.
```
# kubectl alpha debug myapp-pod --image=busybox
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/debug.containerNameToRef(0xc00010a400, 0x18)
        /home/kiyoshim/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/debug/debug.go:547 +0x299
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/debug.(*DebugOptions).computeDebugContainerName(0xc0000d8fc0, 0xc00010a400, 0x20, 0x19aa0a0)
        /home/kiyoshim/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/debug/debug.go:528 +0x4b
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/debug.(*DebugOptions).generateDebugContainer(0xc0000d8fc0, 0xc00010a400, 0x2)
        /home/kiyoshim/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/debug/debug.go:389 +0x39
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/debug.(*DebugOptions).debugByEphemeralContainer(0xc0000d8fc0, 0x1e93060, 0xc0000be010, 0xc00010a400, 0x1ed9a37800000000, 0xc000a079b8, 0xc00062a000, 0xc000650718, 0x4)
        /home/kiyoshim/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/debug/debug.go:359 +0x386
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/debug.(*DebugOptions).visitPod(0xc0000d8fc0, 0x1e93060, 0xc0000be010, 0xc00010a400, 0x0, 0x0, 0x0, 0x1000100, 0x0)
        /home/kiyoshim/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/debug/debug.go:343 +0xc5
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/debug.(*DebugOptions).Run.func1(0xc0007060e0, 0x0, 0x0, 0x0, 0x0)
        /home/kiyoshim/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/debug/debug.go:284 +0xd7
```

**What you expected to happen**:
`kubectl alpha debug` should create a debug container in pod `myapp-pod` successfully.

**How to reproduce it (as minimally and precisely as possible)**:
The EphemeralContainers feature gate must be enabled by using `--feature-gates=EphemeralContainers=true` flag in your cluster.
```
# cat myapp-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 1d']
  initContainers:
  - name: init-container-1
    image: busybox
    command: ['sh', '-c', 'sleep 1d']
  - name: init-container-2
    image: busybox
    command: ['sh', '-c', 'sleep 1d']

# kubectl apply -f myapp-pod.yaml
# kubectl alpha debug myapp-pod --image=busybox
panic: runtime error: index out of range [1] with length 1
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
# kubectl version 
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-alpha.0.996+74b04768b6d1a0", GitCommit:"74b04768b6d1a087c106828f45aeed2f84fa971e", GitTreeState:"clean", BuildDate:"2020-09-06T15:37:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-alpha.0.996+74b04768b6d1a0", GitCommit:"74b04768b6d1a087c106828f45aeed2f84fa971e", GitTreeState:"clean", BuildDate:"2020-09-06T15:37:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
- Kernel (e.g. `uname -a`):
Linux node-1 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig cli

**Comment by kiyoshim55** [comment]
I have investigated this issue and it looks like this issue happens in the following cases.
- When using `kubectl alpha debug` without `-c, --container=''` option
- When using `kubectl alpha debug` with `--copy-to=''` option

In those cases, the containerNameToRef function is called and each for-loop in the function refers to the same `&pod.Spec.Containers[i]` despite the range is `pod.Spec.Containers`, `pod.Spec.InitContainers` or `pod.Spec.EphemeralContainers`.

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/debug/debug.go#L540-L555

**Comment by kiyoshim55** [comment]
cc @seans3 @mengqiy If this issue needs to be fixed, I would like to work on this.

**Comment by verb** [comment]
Thanks @kiyoshim55 for the report and for fixing it!
