### ISSUE TITLE
KubeApiserver crash

### ISSUE THREAD

**Issue by bb3333bb** [kubernetes/kubernetes#94824]
**What happened**: 
We use Ambassador to as API gateway. When i delete all ambassador pods, APIserver crash and it take a about 5 minutes for cluster to get ready 
Log of API server:
```bash
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3c42aa0, 0xc0003dd340)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc02321db80, 0x1, 0x1)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3c42aa0, 0xc0003dd340)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc022770680, 0xc02c4605a0)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:257 +0x1cf
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc009434be0, 0x514e260, 0xc0204f45b0, 0xc02b643c00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:141 +0x310
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x514e260, 0xc0204f45b0, 0xc02b643b00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:59 +0x121
net/http.HandlerFunc.ServeHTTP(0xc0095273e0, 0x514e260, 0xc0204f45b0, 0xc02b643b00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x514e260, 0xc0204f45b0, 0xc02b643a00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x274
net/http.HandlerFunc.ServeHTTP(0xc009527410, 0x514e260, 0xc0204f45b0, 0xc02b643a00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithCacheControl.func1(0x514e260, 0xc0204f45b0, 0xc02b643a00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/cachecontrol.go:31 +0xa8
net/http.HandlerFunc.ServeHTTP(0xc009434c00, 0x514e260, 0xc0204f45b0, 0xc02b643a00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x514faa0, 0xc01cad6d20, 0xc01a0cdc00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:89 +0x2ca
net/http.HandlerFunc.ServeHTTP(0xc009434c20, 0x514faa0, 0xc01cad6d20, 0xc01a0cdc00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x514faa0, 0xc01cad6d20, 0xc01a0cdc00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:51 +0x13e
net/http.HandlerFunc.ServeHTTP(0xc009434c40, 0x514faa0, 0xc01cad6d20, 0xc01a0cdc00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc009527440, 0x514faa0, 0xc01cad6d20, 0xc01a0cdc00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc00c578c40, 0x514faa0, 0xc01cad6d20, 0xc01a0cdc00)
        /usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0109e21e0, 0x515b620, 0xc02b3898c0)
        /usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2928 +0x384
I0916 03:56:25.116445       1 log.go:172] http: superfluous response.WriteHeader call from k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1 (wrap.go:38)
E0916 03:56:25.116461       1 wrap.go:39] apiserver panic'd on GET /metrics
I0916 03:56:25.116589       1 log.go:172] http: panic serving 10.55.123.95:22274: killing connection/stream because serving request timed out and response had been started
goroutine 259885989 [running]:
net/http.(*conn).serve.func1(0xc0109e21e0)
        /usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x3c42aa0, 0xc0003dd340)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc02321db80, 0x1, 0x1)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x3c42aa0, 0xc0003dd340)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc022770680, 0xc02c4605a0)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:257 +0x1cf
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc009434be0, 0x514e260, 0xc0204f45b0, 0xc02b643c00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:141 +0x310
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x514e260, 0xc0204f45b0, 0xc02b643b00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:59 +0x121
net/http.HandlerFunc.ServeHTTP(0xc0095273e0, 0x514e260, 0xc0204f45b0, 0xc02b643b00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x514e260, 0xc0204f45b0, 0xc02b643a00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x274
net/http.HandlerFunc.ServeHTTP(0xc009527410, 0x514e260, 0xc0204f45b0, 0xc02b643a00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithCacheControl.func1(0x514e260, 0xc0204f45b0, 0xc02b643a00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/cachecontrol.go:31 +0xa8
net/http.HandlerFunc.ServeHTTP(0xc009434c00, 0x514e260, 0xc0204f45b0, 0xc02b643a00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x514faa0, 0xc01cad6d20, 0xc01a0cdc00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:89 +0x2ca
net/http.HandlerFunc.ServeHTTP(0xc009434c20, 0x514faa0, 0xc01cad6d20, 0xc01a0cdc00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x514faa0, 0xc01cad6d20, 0xc01a0cdc00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:51 +0x13e
net/http.HandlerFunc.ServeHTTP(0xc009434c40, 0x514faa0, 0xc01cad6d20, 0xc01a0cdc00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc009527440, 0x514faa0, 0xc01cad6d20, 0xc01a0cdc00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc00c578c40, 0x514faa0, 0xc01cad6d20, 0xc01a0cdc00)
        /usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0109e21e0, 0x515b620, 0xc02b3898c0)
        /usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2928 +0x384
E0916 03:56:31.260245       1 runtime.go:78] Observed a panic: &errors.errorString{s:"killing connection/stream because serving request timed out and response had been started"} (killing connection/stream because serving request timed out and response had been started)
goroutine 259886027 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3c42aa0, 0xc0003dd340)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc011561b80, 0x1, 0x1)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x3c42aa0, 0xc0003dd340)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc0291d6ea0, 0xc0248341e0)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:257 +0x1cf
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc009434be0, 0x514e260, 0xc013252af0, 0xc0163ed000)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:141 +0x310
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x514e260, 0xc013252af0, 0xc0163ecf00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:59 +0x121
net/http.HandlerFunc.ServeHTTP(0xc0095273e0, 0x514e260, 0xc013252af0, 0xc0163ecf00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x514e260, 0xc013252af0, 0xc0163ece00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x274
net/http.HandlerFunc.ServeHTTP(0xc009527410, 0x514e260, 0xc013252af0, 0xc0163ece00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithCacheControl.func1(0x514e260, 0xc013252af0, 0xc0163ece00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/cachecontrol.go:31 +0xa8
net/http.HandlerFunc.ServeHTTP(0xc009434c00, 0x514e260, 0xc013252af0, 0xc0163ece00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x514faa0, 0xc020deec40, 0xc01a2c7b00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:89 +0x2ca
net/http.HandlerFunc.ServeHTTP(0xc009434c20, 0x514faa0, 0xc020deec40, 0xc01a2c7b00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x514faa0, 0xc020deec40, 0xc01a2c7b00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:51 +0x13e
net/http.HandlerFunc.ServeHTTP(0xc009434c40, 0x514faa0, 0xc020deec40, 0xc01a2c7b00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc009527440, 0x514faa0, 0xc020deec40, 0xc01a2c7b00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc00c578c40, 0x514faa0, 0xc020deec40, 0xc01a2c7b00)
        /usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc03278d680, 0x515b620, 0xc019cc5280)
        /usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2928 +0x384
I0916 03:56:31.260318       1 log.go:172] http: superfluous response.WriteHeader call from k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1 (wrap.go:38)
E0916 03:56:31.260335       1 wrap.go:39] apiserver panic'd on GET /metrics
I0916 03:56:31.260391       1 log.go:172] http: panic serving 10.55.123.95:48818: killing connection/stream because serving request timed out and response had been started
goroutine 259886027 [running]:
net/http.(*conn).serve.func1(0xc03278d680)
        /usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x3c42aa0, 0xc0003dd340)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc011561b80, 0x1, 0x1)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x3c42aa0, 0xc0003dd340)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc0291d6ea0, 0xc0248341e0)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:257 +0x1cf
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc009434be0, 0x514e260, 0xc013252af0, 0xc0163ed000)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:141 +0x310
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x514e260, 0xc013252af0, 0xc0163ecf00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:59 +0x121
net/http.HandlerFunc.ServeHTTP(0xc0095273e0, 0x514e260, 0xc013252af0, 0xc0163ecf00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x514e260, 0xc013252af0, 0xc0163ece00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x274
net/http.HandlerFunc.ServeHTTP(0xc009527410, 0x514e260, 0xc013252af0, 0xc0163ece00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithCacheControl.func1(0x514e260, 0xc013252af0, 0xc0163ece00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/cachecontrol.go:31 +0xa8
net/http.HandlerFunc.ServeHTTP(0xc009434c00, 0x514e260, 0xc013252af0, 0xc0163ece00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x514faa0, 0xc020deec40, 0xc01a2c7b00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:89 +0x2ca
net/http.HandlerFunc.ServeHTTP(0xc009434c20, 0x514faa0, 0xc020deec40, 0xc01a2c7b00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x514faa0, 0xc020deec40, 0xc01a2c7b00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:51 +0x13e
net/http.HandlerFunc.ServeHTTP(0xc009434c40, 0x514faa0, 0xc020deec40, 0xc01a2c7b00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc009527440, 0x514faa0, 0xc020deec40, 0xc01a2c7b00)
        /workspace/anago-v1.18.4-rc.0.49+d809d9abe5c1e3/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc00c578c40, 0x514faa0, 0xc020deec40, 0xc01a2c7b00)
        /usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc03278d680, 0x515b620, 0xc019cc5280)
        /usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2928 +0x384
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.4
- Cloud provider or hardware configuration: BareMetal
- OS (e.g: `cat /etc/os-release`): Centos7.8
- Kernel (e.g. `uname -a`):
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): Flannel
- Others:
/sig api-machinery

**Comment by liggitt** [comment]
does the API server process actually exit, or is a timeout just being logged?

> killing connection/stream because serving request timed out and response had been started

that logs a stack trace but does not exit the server process.. a timeout panic is caught/logged and terminates serving of that request

**Comment by liggitt** [comment]
/close

due to lack of information
