### ISSUE TITLE
error: No such annotation key

### ISSUE THREAD

**Issue by TC-robV** [kubernetes/kubernetes#94957]
**What happened**:
seeing the following errors in the snapshot pod constantly:
`
2020-09-22T02:40:45.251921Z annotation.not-found           [k8s_snapshots.core] message=annotation.not-found: volume_claim.metadata.name='datadir-zk-a-2' resource=<PersistentVolumeClaim datadir-zk-a-2> severity=ERROR structured_error=[{'type': 'KeyError', 'message': "'backup.kubernetes.io/deltas'", 'readable': ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/rule.py", line 198, in get_deltas\n    deltas_str = annotations[deltas_annotation_key]\n', "KeyError: 'backup.kubernetes.io/deltas'\n"]}, {'type': 'AnnotationNotFound', 'message': 'No such annotation key', 'data': {'key': 'backup.kubernetes.io/deltas'}, 'readable': ['Traceback (most recent call last):\n', '  File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/core.py", line 269, in rule_from_persistent_volume_claim\n    volume_claim.annotations, ctx.config.get(\'deltas_annotation_key\'))\n', '  File "/usr/local/lib/python3.6/site-packages/k8s_snapshots-0.0.0-py3.6.egg/k8s_snapshots/rule.py", line 203, in get_deltas\n    ) from exc\n', "k8s_snapshots.errors.AnnotationNotFound: AnnotationNotFound: No such annotation key {'key': 'backup.kubernetes.io/deltas'}\n"]}] volume_claim={'kind': 'PersistentVolumeClaim', 'apiVersion': 'v1', 'metadata': {'name': 'datadir-zk-a-2', 'namespace': 'default', 'selfLink': '/api/v1/namespaces/default/persistentvolumeclaims/datadir-zk-a-2', 'uid': 'fe4e05ab-bf7a-4d07-9449-4fca2d242b38', 'resourceVersion': '37960876', 'creationTimestamp': '2020-04-15T17:05:47Z', 'labels': {'app': 'pulsar', 'cluster': 'pulsar_prod', 'component': 'zookeeper'}, 'annotations': {'pv.kubernetes.io/bind-completed': 'yes', 'pv.kubernetes.io/bound-by-controller': 'yes', 'volume.beta.kubernetes.io/storage-provisioner': 'kubernetes.io/aws-ebs', 'volume.kubernetes.io/selected-node': 'ip-10-0-7-180.ec2.internal'}, 'finalizers': ['kubernetes.io/pvc-protection']}, 'spec': {'accessModes': ['ReadWriteOnce'], 'resources': {'requests': {'storage': '100Gi'}}, 'volumeName': 'pvc-fe4e05ab-bf7a-4d07-9449-4fca2d242b38', 'storageClassName': 'ssd-retain', 'volumeMode': 'Filesystem'}, 'status': {'phase': 'Bound', 'accessModes': ['ReadWriteOnce'], 'capacity': {'storage': '100Gi'}}}`

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
happens on its own

**Anything else we need to know?**:
running latest.

**Environment**:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:05:26Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: aws
- OS (e.g: `cat /etc/os-release`): Ubuntu 16.04.6 LTS
- Kernel (e.g. `uname -a`):  4.4.0-1087-aws
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
is this snapshots functionality coming from https://github.com/miracle2k/k8s-snapshots ?

please re-open if this is a confirmed k8s core bug and not a bug in external tooling.
/close
