### ISSUE TITLE
node-kubelet-serial test failing

### ISSUE THREAD

**Issue by MHBauer** [kubernetes/kubernetes#95041]
**Which jobs are failing**:
ci-kubernetes-node-kubelet-serial node-kubelet-serial job https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L236

**Which test(s) are failing**:
Hard to tell, but everything at one point or another.

**Since when has it been failing**:
A month or two, by recollection.

http://storage.googleapis.com/k8s-metrics/failures-latest.json would indicate several years...
ci-kubernetes-node-kubelet-serial |  
failing_days | 992

**Testgrid link**:
https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial

**Reason for failure**:
Hard to tell, some is timeout, but I think timeouts due to test failures.

**Anything else we need to know**:
Nothing consistent about the failures that I can tell besides timeouts. This is the only place these serial tests are running.

**Comment by cynepco3hahue** [comment]
I will take a look at what happens with the serial lane.

**Comment by cynepco3hahue** [comment]
So the kubelet failed to restart because of
```
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: I1116 01:28:17.625646  262955 manager.go:888] Making allocation request for devices [Dev-1] for device plugin example.com/resource
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1e4a358]
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: goroutine 215 [running]:
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).allocateContainerResources(0xc000cd5520, 0xc00134a400, 0xc001632f20, 0xc00156b890, 0xc0012c23d0, 0x0)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/manager.go:908 +0xa18
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).Allocate(0xc000cd5520, 0xc00134a400, 0xc001632f20, 0xc001632dc0, 0x148)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/manager.go:385 +0x2ab
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.(*scope).allocateAlignedResources(0xc00048f0e0, 0xc00134a400, 0xc001632f20, 0xc001632dc0, 0x1)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/topologymanager/scope.go:122 +0x7a
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.(*scope).admitPolicyNone(0xc00048f0e0, 0xc00134a400, 0x0, 0x0, 0x0, 0x0, 0x0)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/topologymanager/scope.go:110 +0x1bc
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.(*containerScope).Admit(0xc00048f0e0, 0xc00134a400, 0x0, 0x0, 0x0, 0x0, 0x0)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/topologymanager/scope_container.go:48 +0xb25
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.(*manager).Admit(0xc000c59970, 0xc001631120, 0x0, 0x0, 0x0, 0x0, 0x0)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/topologymanager/topology_manager.go:190 +0xcc
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).canAdmitPod(0xc000b8c000, 0xc0011326c0, 0x1, 0x1, 0xc00134a400, 0x1, 0x1, 0xc000bfb810, 0x6f327f1, 0xa)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1771 +0xef
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).HandlePodAdditions(0xc000b8c000, 0xc0011326b0, 0x1, 0x1)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2048 +0x310
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoopIteration(0xc000b8c000, 0xc000bf7320, 0x4fb6420, 0xc000b8c000, 0xc000e22cc0, 0xc000e22d20, 0xc0003d4cc0, 0x1)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1890 +0x71d
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoop(0xc000b8c000, 0xc000bf7320, 0x4fb6420, 0xc000b8c000)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1833 +0x3f2
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run(0xc000b8c000, 0xc000bf7320)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1422 +0x2a5
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: created by k8s.io/kubernetes/cmd/kubelet/app.startKubelet
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:1183 +0x5f
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 systemd[1]: kubelet-20201116T004128.service: Main process exited, code=exited, status=2/INVALIDARGUMENTNov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: I1116 01:28:17.625646  262955 manager.go:888] Making allocation request for devices [Dev-1] for device plugin example.com/resource
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1e4a358]
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: goroutine 215 [running]:
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).allocateContainerResources(0xc000cd5520, 0xc00134a400, 0xc001632f20, 0xc00156b890, 0xc0012c23d0, 0x0)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/manager.go:908 +0xa18
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).Allocate(0xc000cd5520, 0xc00134a400, 0xc001632f20, 0xc001632dc0, 0x148)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/manager.go:385 +0x2ab
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.(*scope).allocateAlignedResources(0xc00048f0e0, 0xc00134a400, 0xc001632f20, 0xc001632dc0, 0x1)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/topologymanager/scope.go:122 +0x7a
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.(*scope).admitPolicyNone(0xc00048f0e0, 0xc00134a400, 0x0, 0x0, 0x0, 0x0, 0x0)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/topologymanager/scope.go:110 +0x1bc
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.(*containerScope).Admit(0xc00048f0e0, 0xc00134a400, 0x0, 0x0, 0x0, 0x0, 0x0)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/topologymanager/scope_container.go:48 +0xb25
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.(*manager).Admit(0xc000c59970, 0xc001631120, 0x0, 0x0, 0x0, 0x0, 0x0)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/topologymanager/topology_manager.go:190 +0xcc
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).canAdmitPod(0xc000b8c000, 0xc0011326c0, 0x1, 0x1, 0xc00134a400, 0x1, 0x1, 0xc000bfb810, 0x6f327f1, 0xa)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1771 +0xef
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).HandlePodAdditions(0xc000b8c000, 0xc0011326b0, 0x1, 0x1)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2048 +0x310
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoopIteration(0xc000b8c000, 0xc000bf7320, 0x4fb6420, 0xc000b8c000, 0xc000e22cc0, 0xc000e22d20, 0xc0003d4cc0, 0x1)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1890 +0x71d
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoop(0xc000b8c000, 0xc000bf7320, 0x4fb6420, 0xc000b8c000)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1833 +0x3f2
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run(0xc000b8c000, 0xc000bf7320)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1422 +0x2a5
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: created by k8s.io/kubernetes/cmd/kubelet/app.startKubelet
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:1183 +0x5f
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 systemd[1]: kubelet-20201116T004128.service: Main process exited, code=exited, status=2/INVALIDARGUMENTNov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: I1116 01:28:17.625646  262955 manager.go:888] Making allocation request for devices [Dev-1] for device plugin example.com/resource
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1e4a358]
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: goroutine 215 [running]:
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).allocateContainerResources(0xc000cd5520, 0xc00134a400, 0xc001632f20, 0xc00156b890, 0xc0012c23d0, 0x0)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/manager.go:908 +0xa18
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).Allocate(0xc000cd5520, 0xc00134a400, 0xc001632f20, 0xc001632dc0, 0x148)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/manager.go:385 +0x2ab
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.(*scope).allocateAlignedResources(0xc00048f0e0, 0xc00134a400, 0xc001632f20, 0xc001632dc0, 0x1)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/topologymanager/scope.go:122 +0x7a
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.(*scope).admitPolicyNone(0xc00048f0e0, 0xc00134a400, 0x0, 0x0, 0x0, 0x0, 0x0)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/topologymanager/scope.go:110 +0x1bc
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.(*containerScope).Admit(0xc00048f0e0, 0xc00134a400, 0x0, 0x0, 0x0, 0x0, 0x0)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/topologymanager/scope_container.go:48 +0xb25
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.(*manager).Admit(0xc000c59970, 0xc001631120, 0x0, 0x0, 0x0, 0x0, 0x0)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/topologymanager/topology_manager.go:190 +0xcc
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).canAdmitPod(0xc000b8c000, 0xc0011326c0, 0x1, 0x1, 0xc00134a400, 0x1, 0x1, 0xc000bfb810, 0x6f327f1, 0xa)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1771 +0xef
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).HandlePodAdditions(0xc000b8c000, 0xc0011326b0, 0x1, 0x1)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2048 +0x310
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoopIteration(0xc000b8c000, 0xc000bf7320, 0x4fb6420, 0xc000b8c000, 0xc000e22cc0, 0xc000e22d20, 0xc0003d4cc0, 0x1)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1890 +0x71d
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoop(0xc000b8c000, 0xc000bf7320, 0x4fb6420, 0xc000b8c000)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1833 +0x3f2
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run(0xc000b8c000, 0xc000bf7320)
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1422 +0x2a5
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: created by k8s.io/kubernetes/cmd/kubelet/app.startKubelet
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 kubelet[262955]: 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:1183 +0x5f
Nov 16 01:28:17 tmp-node-e2e-da054c92-cos-85-13310-1041-28 systemd[1]: kubelet-20201116T004128.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

I think it can be related to the topology manager scope PR, I will dig into the code tomorrow.
FYI @klueska @k-wiatrzyk @SergeyKanzhelev

**Comment by klueska** [comment]
It actually looks like it was introduced by: a8b8995ef241e93e9486d475126450f33f24ef4e

**Comment by cynepco3hahue** [comment]
@klueska Thanks for the update.

**Comment by ehashman** [comment]
Some of these failures are definitely due to #97288, which is causing tests to fail since pods aren't terminating in time.

**Comment by cynepco3hahue** [comment]
Under the latest run, I saw that the kubelet failed to restart because of
```
Jan 24 08:07:28 tmp-node-e2e-24ec7fb2-cos-85-13310-1041-161 kubelet[285886]: E0124 08:07:28.168269  285886 cpu_manager.go:203] [cpumanager] could not initialize checkpoint manager: could not restore state from checkpoint: configured policy "none" differs from state checkpoint policy "static", please drain this node and delete the CPU manager checkpoint file "/var/lib/kubelet/cpu_manager_state" before restarting Kubelet, please drain node and remove policy state file
Jan 24 08:07:28 tmp-node-e2e-24ec7fb2-cos-85-13310-1041-161 kubelet[285886]: F0124 08:07:28.168281  285886 kubelet.go:1371] Failed to start ContainerManager start cpu manager error: could not restore state from checkpoint: configured policy "none" differs from state checkpoint policy "static", please drain this node and delete the CPU manager checkpoint file "/var/lib/kubelet/cpu_manager_state" before restarting Kubelet
```
The problem that one of the topology manager tests failed in the middle and did not remove the state file, I can not guarantee that it a single problem, but let's start from it.
