### ISSUE TITLE
Kubernetes Pod’s cannot reach pods in serviceSubnet

### ISSUE THREAD

**Issue by jangel97** [kubernetes/kubernetes#95764]
Hello there,

I am new to Kubernetes and I am seeking help.

I just deployed a cluster of two nodes, one master and one worker. Apparenty, cluster is working fine, the problem is that pods cannot reach CoreDNS nor Kubernetes Api. 

In order to deploy networking I used **flannel** network driver.   https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

**Log error:**
```
[root@bastion test]# kubectl logs kubernetes-dashboard-74d688b6bc-xrz54 -n kubernetes-dashboard --kubeconfig admin.conf 
2020/10/21 13:43:11 Starting overwatch
2020/10/21 13:43:11 Using namespace: kubernetes-dashboard
2020/10/21 13:43:11 Using in-cluster config to connect to apiserver
2020/10/21 13:43:11 Using secret token for csrf signing
2020/10/21 13:43:11 Initializing csrf token from kubernetes-dashboard-csrf secret
panic: Get https://10.96.0.1:443/api/v1/namespaces/kubernetes-dashboard/secrets/kubernetes-dashboard-csrf: dial tcp 10.96.0.1:443: connect: no route to host

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/client/csrf.(*csrfTokenManager).init(0xc00000ccc0)
        /home/travis/build/kubernetes/dashboard/src/app/backend/client/csrf/manager.go:41 +0x446
github.com/kubernetes/dashboard/src/app/backend/client/csrf.NewCsrfTokenManager(...)
        /home/travis/build/kubernetes/dashboard/src/app/backend/client/csrf/manager.go:66
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initCSRFKey(0xc00017a080)
        /home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:501 +0xc6
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0xc00017a080)
        /home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:469 +0x47
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(...)
        /home/travis/build/kubernetes/dashboard/src/app/backend/client/manager.go:550
main.main()
        /home/travis/build/kubernetes/dashboard/src/app/backend/dashboard.go:105 +0x20d
```

**Opened ports:**
```
[root@bastion test]# ansible all -m shell -a 'firewall-cmd --list-ports' -i inv
**kubemaster** | CHANGED | rc=0 >>
6443/tcp 10250/tcp 2379-2380/tcp 10251/tcp 10252/tcp 10255/tcp 8285/tcp
**kubeworker** | CHANGED | rc=0 >>
10251/tcp 10255/tcp 10250/tcp 30495/tcp
```

**Network configuration:**
```
[root@bastion test]# kubectl -n kube-system get cm kubeadm-config -oyaml --kubeconfig admin.conf 
apiVersion: v1
data:
  ClusterConfiguration: |
    apiServer:
      extraArgs:
        authorization-mode: Node,RBAC
      timeoutForControlPlane: 4m0s
    apiVersion: kubeadm.k8s.io/v1beta2
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controllerManager: {}
    dns:
      type: CoreDNS
    etcd:
      local:
        dataDir: /var/lib/etcd
    imageRepository: k8s.gcr.io
    kind: ClusterConfiguration
    kubernetesVersion: v1.19.3
    networking:
      dnsDomain: cluster.local
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    scheduler: {}
  ClusterStatus: |
    apiEndpoints:
      kubemaster:
        advertiseAddress: 172.21.0.9
        bindPort: 6443
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterStatus
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-21T12:16:28Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ClusterConfiguration: {}
        f:ClusterStatus: {}
    manager: kubeadm
    operation: Update
    time: "2020-10-21T12:16:28Z"
  name: kubeadm-config
  namespace: kube-system
  resourceVersion: "161"
  selfLink: /api/v1/namespaces/kube-system/configmaps/kubeadm-config
  uid: 71782270-6f69-4ed4-9e75-3ff18799a61a

```
**Sysctl:**
```
[root@kubemaster ~]# cat /etc/sysctl.d/k8s.conf 
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
```

Is there anything I am missing? Please, if there is any additional information I can provide do not hesitate to contact me.

Kind regards,

**Comment by neolit123** [comment]
hi, this could be an issue in flannel. at least i think i've seen similar problems.
please try another CNI plugin like Calico / WeaveNet.

for further questions try the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close

**Comment by jangel97** [comment]
Nello @neolit123 , I will redeploy the cluster with calico this time, let's see what happens!

Thank you for the support channels information!

**Comment by jangel97** [comment]
Hello, I redeployed the cluster with calico network plugin and the issue still persists. 
```[root@bastion test]# kubectl get po --all-namespaces -o wide
NAMESPACE     NAME                                     READY   STATUS    RESTARTS   AGE   IP              NODE         NOMINATED NODE   READINESS GATES
kube-system   calico-kube-controllers-7d569d95-t2hqv   1/1     Running   0          34m   192.168.141.3   kubemaster   <none>           <none>
kube-system   calico-node-2vgsp                        1/1     Running   0          32m   172.21.0.13     kubeworker   <none>           <none>
kube-system   calico-node-cs52n                        1/1     Running   0          34m   172.21.0.11     kubemaster   <none>           <none>
kube-system   coredns-f9fd979d6-fzcc8                  1/1     Running   0          35m   192.168.141.1   kubemaster   <none>           <none>
kube-system   coredns-f9fd979d6-nd9nn                  1/1     Running   0          35m   192.168.141.2   kubemaster   <none>           <none>
kube-system   etcd-kubemaster                          1/1     Running   0          35m   172.21.0.11     kubemaster   <none>           <none>
kube-system   kube-apiserver-kubemaster                1/1     Running   0          35m   172.21.0.11     kubemaster   <none>           <none>
kube-system   kube-controller-manager-kubemaster       1/1     Running   0          35m   172.21.0.11     kubemaster   <none>           <none>
kube-system   kube-proxy-jkvxv                         1/1     Running   0          35m   172.21.0.11     kubemaster   <none>           <none>
kube-system   kube-proxy-snh2l                         1/1     Running   0          32m   172.21.0.13     kubeworker   <none>           <none>
kube-system   kube-scheduler-kubemaster                1/1     Running   0          35m   172.21.0.11     kubemaster   <none>           <none>
[root@bastion test]# kubectl get nodes
NAME         STATUS   ROLES    AGE   VERSION
kubemaster   Ready    master   35m   v1.19.3
kubeworker   Ready    worker   33m   v1.19.3
```
From master machine I can contact core-dns via Services SDN. But pods don't have connectivity with Service SDN.
