### ISSUE TITLE
Failing ci-npd-e2e-node: NodeProblemDetector [NodeFeature:NodeProblemDetector]

### ISSUE THREAD

**Issue by karan** [kubernetes/kubernetes#96272]
Similar to #95357

**Which jobs are failing**: ci-npd-e2e-node

**Which test(s) are failing**:

```
E2eNode Suite: [k8s.io] NodeProblemDetector [NodeFeature:NodeProblemDetector] [Serial] [k8s.io] SystemLogMonitor should generate node condition and events for corresponding errors
```

**Since when has it been failing**: 2020-10-23 11:08 PST

**Testgrid link**: https://k8s-testgrid.appspot.com/sig-node-node-problem-detector#

**Reason for failure**: Unclear at the moment

**Anything else we need to know**: It will block all PRs in https://github.com/kubernetes/node-problem-detector

**Comment by karan** [comment]
```
[1mSTEP[0m: Calculate Lookback duration
[1mSTEP[0m: Generate event list options
[1mSTEP[0m: Create config map for the node problem detector
[1mSTEP[0m: Create the service account for node problem detector
[1mSTEP[0m: Bind the cluster role system:node-problem-detector with the service account for node problem detector
[1mSTEP[0m: Create the node problem detector
[It] should generate node condition and events for corresponding errors
  _output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_problem_detector_linux.go:277
[1mSTEP[0m: should generate default node condition
[1mSTEP[0m: Wait for 0 temp events generated
[1mSTEP[0m: Wait for 0 total events generated
[1mSTEP[0m: Make sure only 0 total events generated
[1mSTEP[0m: Make sure node condition "TestCondition" is set
[AfterEach] [k8s.io] SystemLogMonitor
  _output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_problem_detector_linux.go:400
[1mSTEP[0m: Get node problem detector log
Nov  5 13:45:58.252: INFO: Node Problem Detector logs:
 Flag --system-log-monitors has been deprecated, replaced by --config.system-log-monitor. NPD will panic if both --system-log-monitors and --config.system-log-monitor are set.
I1105 13:45:35.120087       7 log_monitor.go:79] Finish parsing log monitor config file /config/testconfig.json: {WatcherConfig:{Plugin:filelog PluginConfig:map[message:kernel: \[.*\] (.*) timestamp:^.{15} timestampFormat:Jan _2 15:04:05] LogPath:/log/test.log Lookback:1h5m59.153805399s Delay:} BufferSize:10 Source:kernel-monitor-66783d58-d61e-419d-9015-f45d807e4f28 DefaultConditions:[{Type:TestCondition Status: Transition:0001-01-01 00:00:00 +0000 UTC Reason:Default Message:default message}] Rules:[{Type:temporary Condition: Reason:Temporary Pattern:temporary error} {Type:permanent Condition:TestCondition Reason:Permanent1 Pattern:permanent error 1.*} {Type:permanent Condition:TestCondition Reason:Permanent2 Pattern:permanent error 2.*}] EnableMetricsReporting:0x1f7781c}
I1105 13:45:35.120257       7 log_watchers.go:40] Use log watcher of plugin "filelog"
panic: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

goroutine 1 [running]:
k8s.io/node-problem-detector/pkg/exporters/k8sexporter/problemclient.NewClientOrDie(0xc0003e3860, 0xc0000b6d00, 0x0)
	/home/prow/go/src/k8s.io/node-problem-detector/pkg/exporters/k8sexporter/problemclient/problem_client.go:73 +0x3f7
k8s.io/node-problem-detector/pkg/exporters/k8sexporter.NewExporterOrDie(0xc0003e3860, 0xc000494370, 0x1)
	/home/prow/go/src/k8s.io/node-problem-detector/pkg/exporters/k8sexporter/k8s_exporter.go:52 +0x4f
main.main()
	/home/prow/go/src/k8s.io/node-problem-detector/cmd/nodeproblemdetector/node_problem_detector.go:60 +0x13a

[1mSTEP[0m: Delete the node problem detector
[1mSTEP[0m: Wait for the node problem detector to disappear

```

**Comment by karan** [comment]
Looks like a dupe of #96262
