### ISSUE TITLE
when kube-scheduler or kube-controller-manager lost leader,panic log too long

### ISSUE THREAD

**Issue by lojies** [kubernetes/kubernetes#96923]
**What happened**:
when kube-scheduler or kube-controller-manager lost leader, it panic and posts too much log.
**What you expected to happen**:
just write some nessary log.
**How to reproduce it (as minimally and precisely as possible)**:
make kube-scheduler or kube-controller-manager lost leader.
**Anything else we need to know?**:

**Comment by ahg-g** [comment]
can you post the panic logs so we understand why it panicked?

**Comment by lojies** [comment]
logs like below:
```
E1124 22:00:43.496137   54618 leaderelection.go:367] Failed to update lock: resource name may not be empty
I1124 22:00:46.103945   54618 leaderelection.go:288] failed to renew lease kube-system/kube-controller-manager: timed out waiting for the condition
F1124 22:00:46.104030   54618 controllermanager.go:279] leaderelection lost
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog.stacks(0xc00000e001, 0xc001fa2000, 0xc69, 0x2710)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:900 +0xb8
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).output(0x68ec260, 0xc000000003, 0xc000636000, 0x677dc5d, 0x14, 0x117, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:854 +0x13a
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).printf(0x68ec260, 0x3, 0x3f4a32a, 0x13, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:716 +0x14b
k8s.io/kubernetes/vendor/k8s.io/klog.Fatalf(...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:1350
k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func2()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:279 +0x5b
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run.func1(0xc0014505a0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:200 +0x40
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc0014505a0, 0x465bb40, 0xc0003d83c0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:209 +0x119
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection.RunOrDie(0x465bb80, 0xc00004e080, 0x4691660, 0xc000a5ec60, 0x37e11d600, 0x2540be400, 0x12a05f200, 0xc000a5ec40, 0x40a4c98, 0x0, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:221 +0x96
k8s.io/kubernetes/cmd/kube-controller-manager/app.Run(0xc00019b2d8, 0xc00011a0c0, 0xc000345bc0, 0xc00019a378)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:271 +0x940
k8s.io/kubernetes/cmd/kube-controller-manager/app.NewControllerManagerCommand.func1(0xc0002d1900, 0xc0002dd4a0, 0x0, 0x16)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:118 +0x27d
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0002d1900, 0xc000001390, 0x16, 0x17, 0xc0002d1900, 0xc000001390)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:830 +0x29d
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0002d1900, 0x164a7648390b0514, 0x68ebca0, 0x405d1f)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
main.main()
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/controller-manager.go:46 +0xe5

goroutine 6 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x68ec260)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:1084 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog.init.0
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:412 +0xd6
.......
```
it push about 13000 lines error logs, this make logs file difficult to read.

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/68f6b09e807917d73446e6ee6146b4029d1aae79/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go#L236-L257

check the annotation like `control-plane.alpha.kubernetes.io/leader`  in the configmap may help？ Not sure about it and cannot reproduce.

**Comment by inajob** [comment]
This trouble occured on my cluster.
I notice the panic occured random timing, but "leaderelecton lost" log always exists before the panic.
So I extended the lease time of controller and scheduler 4 times.

```
    - --leader-elect=true
    - --leader-elect-lease-duration=60s
    - --leader-elect-renew-deadline=40s
```

I don't know why panic occured only "leaderelection lost".

**Comment by aamsur-933** [comment]
> This trouble occured on my cluster. I notice the panic occured random timing, but "leaderelecton lost" log always exists before the panic. So I extended the lease time of controller and scheduler 4 times.
> 
> ```
>     - --leader-elect=true
>     - --leader-elect-lease-duration=60s
>     - --leader-elect-renew-deadline=40s
> ```
> 
> I don't know why panic occured only "leaderelection lost".

I'm new at k8s, and having a same issue. This params solved my problem.
Fyi, you can add those params at
```
/etc/kubernetes/manifests/kube-controller-manager.yaml
```
and
```
/etc/kubernetes/manifests/kube-scheduler.yaml
```
thx, good luck!
