### ISSUE TITLE
[Flaky unit test] pkg/kubelet/cri/remote TestVersion

### ISSUE THREAD

**Issue by ranand20** [kubernetes/kubernetes#96950]
**Which jobs are flaking**:
periodics-kubernetes-bazel-test

**Which test(s) are flaking**:
//pkg/kubelet/cri/remote   TestVersion
**Testgrid link**:

**Reason for failure**:
   Error:          Received unexpected error:
                                rpc error: code = Unavailable desc = transport is closing
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference

**Anything else we need to know**:
**To reproduce with stress:**
go test -race -c ./pkg/kubelet/cri/remote
stress ./remote.test -test.run TestVersion

Detailed logs
~~~
cloudusr@x86-arch-ra:~/kubernetes$ go test -race -c ./pkg/kubelet/cri/remote
cloudusr@x86-arch-ra:~/kubernetes$ stress ./remote.test -test.run TestVersion
/tmp/go-stress-20201130T052353-617378882
E1130 05:23:57.619773   11458 remote_runtime.go:86] Version from runtime service failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /tmp/kubelet_remote.sock: connect: no such file or directory"
--- FAIL: TestVersion (0.00s)
    remote_runtime_test.go:60:
                Error Trace:    remote_runtime_test.go:60
                Error:          Received unexpected error:
                                rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /tmp/kubelet_remote.sock: connect: no such file or directory"
                Test:           TestVersion
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd4c04d]

goroutine 7 [running]:
testing.tRunner.func1.1(0xdd2b80, 0x1365eb0)
        /usr/local/go/src/testing/testing.go:1072 +0x46a
testing.tRunner.func1(0xc0001ee000)
        /usr/local/go/src/testing/testing.go:1075 +0x636
panic(0xdd2b80, 0x1365eb0)
        /usr/local/go/src/runtime/panic.go:975 +0x47a
k8s.io/kubernetes/pkg/kubelet/cri/remote.TestVersion(0xc0001ee000)
        /home/cloudusr/kubernetes/pkg/kubelet/cri/remote/remote_runtime_test.go:61 +0x1ad
testing.tRunner(0xc0001ee000, 0xebcdc8)
        /usr/local/go/src/testing/testing.go:1123 +0x203
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1168 +0x5bc


ERROR: exit status 2
~~~

**Comment by JornShen** [comment]
I 'll give it a see and fix it :)

**Comment by BenTheElder** [comment]
/remove-sig testing
SIG node owns their unit tests. SIG testing owns the framework, infrastructure, etc.
