### ISSUE TITLE
Kubelet failed to start due to errors when invoked via kubeadm

### ISSUE THREAD

**Issue by mikecali** [kubernetes/kubernetes#97055]
**What happened**:
Trying to deploy kubernetes Cluster on my local machine using kubeadm following below

- install via yum - kubeadm, kubectl, kubelet
- install crio
- make sure selinux, all modules are enabled as per documentation
- start crio
- start kubelet
- swapoff -a
- kubeadm init --cri-socket /var/run/crio/crio.sock

**What you expected to happen**:

I expect to have a running cluster on my laptop - single node for after invoking the kubeadm init

**How to reproduce it (as minimally and precisely as possible)**:

As per above steps
The error I get is below:
```
Dec 04 08:03:59 homebase systemd[1]: Started kubelet: The Kubernetes Node Agent.
Dec 04 08:03:59 homebase kubelet[41875]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 04 08:03:59 homebase kubelet[41875]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 04 08:03:59 homebase kubelet[41875]: I1204 08:03:59.949417   41875 server.go:411] Version: v1.19.2
Dec 04 08:03:59 homebase kubelet[41875]: I1204 08:03:59.949977   41875 server.go:831] Client rotation is on, will bootstrap in background
Dec 04 08:03:59 homebase kubelet[41875]: I1204 08:03:59.954887   41875 certificate_store.go:130] Loading cert/key pair from "/var/lib/kubelet/pki/kubelet-client-current.pem".
Dec 04 08:03:59 homebase kubelet[41875]: I1204 08:03:59.958831   41875 dynamic_cafile_content.go:167] Starting client-ca-bundle::/etc/kubernetes/pki/ca.crt
Dec 04 08:03:59 homebase kubelet[41875]: W1204 08:03:59.968756   41875 manager.go:159] Cannot detect current cgroup on cgroup v2
Dec 04 08:04:04 homebase kubelet[41875]: W1204 08:04:04.973971   41875 nvidia.go:61] NVIDIA GPU metrics will not be available: no NVIDIA devices found
Dec 04 08:04:04 homebase kubelet[41875]: I1204 08:04:04.989341   41875 server.go:640] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
Dec 04 08:04:04 homebase kubelet[41875]: F1204 08:04:04.989544   41875 server.go:265] failed to run Kubelet: running with swap on is not supported, please disable swap! or set --fail-swap-on flag to false. /proc/swaps contained: [Filename                                Type                Size                Used                Priority /dev/zram0                              partition        4194300                0                100]
Dec 04 08:04:04 homebase kubelet[41875]: goroutine 1 [running]:
Dec 04 08:04:04 homebase kubelet[41875]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00012a001, 0xc000282500, 0x127, 0x25f)
Dec 04 08:04:04 homebase kubelet[41875]:         /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
Dec 04 08:04:04 homebase kubelet[41875]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x6cf6140, 0xc000000003, 0x0, 0x0, 0xc0005fe380, 0x6b49c19, 0x9, 0x109, 0x0)
Dec 04 08:04:04 homebase kubelet[41875]:         /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:945 +0x191
Dec 04 08:04:04 homebase kubelet[41875]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x6cf6140, 0xc000000003, 0x0, 0x0, 0x1, 0xc000dc7c80, 0x1, 0x1)
Dec 04 08:04:04 homebase kubelet[41875]:         /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:718 +0x165
Dec 04 08:04:04 homebase kubelet[41875]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).print(...)
Dec 04 08:04:04 homebase kubelet[41875]:         /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:703
Dec 04 08:04:04 homebase kubelet[41875]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatal(...)
Dec 04 08:04:04 homebase kubelet[41875]:         /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1436
Dec 04 08:04:04 homebase kubelet[41875]: k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0xc000163340, 0xc00012e010, 0x7, 0x7)
Dec 04 08:04:04 homebase kubelet[41875]:         /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:265 +0x63e
Dec 04 08:04:04 homebase kubelet[41875]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000163340, 0xc00012e010, 0x7, 0x7, 0xc000163340, 0xc00012e010)
Dec 04 08:04:04 homebase kubelet[41875]:         /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
Dec 04 08:04:04 homebase kubelet[41875]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000163340, 0x164d4a367d52eb0b, 0x6cf5c60, 0x409b05)
Dec 04 08:04:04 homebase kubelet[41875]:         /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:950 +0x375
Dec 04 08:04:04 homebase kubelet[41875]: k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
Dec 04 08:04:04 homebase kubelet[41875]:         /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:887
```
Here are the status of kubelet and crio

```[root@homebase mcalizo]# systemctl status crio
● crio.service - Container Runtime Interface for OCI (CRI-O)
     Loaded: loaded (/usr/lib/systemd/system/crio.service; disabled; vendor preset: disabled)
     Active: active (running) since Thu 2020-12-03 22:46:17 NZDT; 9h ago
       Docs: https://github.com/cri-o/cri-o
   Main PID: 3644 (crio)
      Tasks: 13
     Memory: 83.4M
        CPU: 7.301s
     CGroup: /system.slice/crio.service
             └─3644 /usr/bin/crio

Dec 04 07:50:57 homebase crio[3644]: time="2020-12-04 07:50:57.622897792+13:00" level=info msg="Checking image status: k8s.gcr.io/kube-scheduler:v1.19.4" id=33b16c25-2565-452d-aa0d-e53c56c12198 name=/runtime.v1alpha2.ImageS>
Dec 04 07:50:57 homebase crio[3644]: time="2020-12-04 07:50:57.624254145+13:00" level=info msg="Image status: &ImageStatusResponse{Image:&Image{Id:14cd22f7abe78e59b77c30819906920b3c5677596ef8967b649b87c13e8e65f4,RepoTags:[k>
Dec 04 07:50:57 homebase crio[3644]: time="2020-12-04 07:50:57.636568531+13:00" level=info msg="Checking image status: k8s.gcr.io/kube-proxy:v1.19.4" id=79a66df8-afe1-45d9-a517-dd6249e0b925 name=/runtime.v1alpha2.ImageServi>
Dec 04 07:50:57 homebase crio[3644]: time="2020-12-04 07:50:57.639338072+13:00" level=info msg="Image status: &ImageStatusResponse{Image:&Image{Id:635b36f4d89f0e74f1000ad953affb757e9d71b799c5a7e3f32ea145c553d9d6,RepoTags:[k>
Dec 04 07:50:57 homebase crio[3644]: time="2020-12-04 07:50:57.652174632+13:00" level=info msg="Checking image status: k8s.gcr.io/pause:3.2" id=80ee581e-b592-4e7a-bfb3-18d5fd960e45 name=/runtime.v1alpha2.ImageService/ImageS>
Dec 04 07:50:57 homebase crio[3644]: time="2020-12-04 07:50:57.653436662+13:00" level=info msg="Image status: &ImageStatusResponse{Image:&Image{Id:80d28bedfe5dec59da9ebf8e6260224ac9008ab5c11dbbe16ee3ba3e4439ac2c,RepoTags:[k>
Dec 04 07:50:57 homebase crio[3644]: time="2020-12-04 07:50:57.665154611+13:00" level=info msg="Checking image status: k8s.gcr.io/etcd:3.4.13-0" id=3d815441-0d08-4b2e-8f2d-496215bb63d2 name=/runtime.v1alpha2.ImageService/Im>
Dec 04 07:50:57 homebase crio[3644]: time="2020-12-04 07:50:57.667005817+13:00" level=info msg="Image status: &ImageStatusResponse{Image:&Image{Id:0369cf4303ffdb467dc219990960a9baa8512a54b0ad9283eaf55bd6c0adb934,RepoTags:[k>
Dec 04 07:50:57 homebase crio[3644]: time="2020-12-04 07:50:57.678809029+13:00" level=info msg="Checking image status: k8s.gcr.io/coredns:1.7.0" id=3e42677d-b57f-474e-bc30-26001618eea8 name=/runtime.v1alpha2.ImageService/Im>
Dec 04 07:50:57 homebase crio[3644]: time="2020-12-04 07:50:57.680804497+13:00" level=info msg="Image status: &ImageStatusResponse{Image:&Image{Id:bfe3a36ebd2528b454be6aebece806db5b40407b833e2af9617bf39afaff8c16,RepoTags:[k>
[root@homebase mcalizo]# systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
     Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/kubelet.service.d
             └─10-kubeadm.conf
     Active: activating (auto-restart) (Result: exit-code) since Fri 2020-12-04 08:07:08 NZDT; 6s ago
       Docs: https://kubernetes.io/docs/
    Process: 42185 ExecStart=/var/lib/minikube/binaries/v1.19.2/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime=docker --hostname-override=home>
   Main PID: 42185 (code=exited, status=255/EXCEPTION)
        CPU: 275ms

Dec 04 08:07:08 homebase kubelet[42185]: goroutine 138 [chan receive]:
Dec 04 08:07:08 homebase kubelet[42185]: k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1(0x4bfd7a0, 0xc000d43290, 0xc000d2f710)
Dec 04 08:07:08 homebase kubelet[42185]:         /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record/event.go:301 +0xaa
Dec 04 08:07:08 homebase kubelet[42185]: created by k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher
Dec 04 08:07:08 homebase kubelet[42185]:         /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record/event.go:299 +0x6e
Dec 04 08:07:08 homebase kubelet[42185]: goroutine 137 [chan receive]:
Dec 04 08:07:08 homebase kubelet[42185]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc00029c2c0)
Dec 04 08:07:08 homebase kubelet[42185]:         /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/mux.go:207 +0x66
Dec 04 08:07:08 homebase kubelet[42185]: created by k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch.NewBroadcaster
Dec 04 08:07:08 homebase kubelet[42185]:         /workspace/anago-v1.19.2-rc.0.12+19706d90d87784/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/mux.go:75 +0xce
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.4
- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`): Fedora 33
- Kernel (e.g. `uname -a`): 5.9.11-200.fc33.x86_64
- Install tools: kubeadm 1.19.4

**Comment by neolit123** [comment]
> Dec 04 08:04:04 homebase kubelet[41875]: F1204 08:04:04.989544   41875 server.go:265] failed to run Kubelet: running with swap on is not supported, please disable swap! or set --fail-swap-on

running with swap enabled your host is unsupported by k8s.
https://www.tecmint.com/disable-swap-partition-in-centos-ubuntu/

alternatively pass --fail-swap-on=false to the kubelet.

> ExecStart=/var/lib/minikube/binaries/

i don't know if minikube is passing the above flag, but the maintainers at #minikube on k8s slack should know.

/remove-kind bug
/kind support
/close

**Comment by neolit123** [comment]
for general support questions you could check with other users at the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
