### ISSUE TITLE
kube-apiserver restarts in ci-kubernetes-e2e-gce-scale-performance

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#97801]
**Which jobs are failing**:
ci-kubernetes-e2e-gce-scale-performance, .e.g

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1345777377413697536
**Which test(s) are failing**:

**Since when has it been failing**:

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-performance
**Reason for failure**:

kube-apiserver restarts, we are seeing errors like:
```
[namespace test-45dbpk-18 object small-job-0 creation error: Post "https://35.231.217.12/apis/batch/v1/namespaces/test-45dbpk-18/jobs": dial tcp 35.231.217.12:443: connect: connection refused
```

**Anything else we need to know**:
Potentially related: https://github.com/kubernetes/kubernetes/issues/97798

/assign
/sig scalability
/triage accepted

**Comment by mborsz** [comment]
In 1345777377413697536, clusterloader started at 17:17

At 18:15:35 we are seeing first "connection refused" errors in build-log

**Comment by mborsz** [comment]
I was trying to find prometheus snapshot for that run, but I failed:
* ci-kubernetes-e2e-gce-scale-performance-1345777377413697536 snapshot doesn't exist
* gce-scale-cluster-dyna-pvc-56f949c3-93d4-4998-8d92-884660a9769b disk is also removed

In CL2's logs I see:

```
W0103 20:45:45.386] I0103 20:45:45.386633   21206 experimental.go:71] Retrieving Prometheus' persistent disk metadata...
W0103 20:45:45.420] E0103 20:45:45.419961   21206 experimental.go:75] Listing PVs failed: Get "https://35.231.217.12/api/v1/persistentvolumes": dial tcp 35.231.217.12:443: connect: connection refused
W0103 20:45:55.386] I0103 20:45:55.386465   21206 experimental.go:71] Retrieving Prometheus' persistent disk metadata...
W0103 20:46:29.319] I0103 20:46:29.318833   21206 experimental.go:87] Found Prometheus' PV with name: pvc-56f949c3-93d4-4998-8d92-884660a9769b
W0103 20:46:29.319] I0103 20:46:29.319351   21206 experimental.go:90] PD name=gce-scale-cluster-dyna-pvc-56f949c3-93d4-4998-8d92-884660a9769b, zone=us-east1-b
W0103 20:46:29.319] I0103 20:46:29.319752   21206 prometheus.go:212] Tearing down prometheus stack
W0103 20:47:57.151] E0103 20:47:57.151101   21206 clusterloader.go:325] Error while tearing down prometheus stack: Delete "https://35.231.217.12/api/v1/namespaces/monitoring": unexpected EOF
W0103 20:47:57.151] F0103 20:47:57.151178   21206 clusterloader.go:334] 23 tests have failed!
```

**Comment by mborsz** [comment]
From kube-apiserver logs:
```
I0103 18:14:59.817877      11 trace.go:205] Trace[1071899073]: "Create" url:/api/v1/namespaces/test-45dbpk-11/configmaps,user-agent:clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format,client:35.224.156.164,accept:application/json,protocol:HTTP/2.0 (03-Jan-2021 18:14:49
.813) (total time: 10004ms):
Trace[1071899073]: [10.00458714s] [10.00458714s] END
I0103 18:14:59.818470      11 httplog.go:89] "HTTP" verb="POST" URI="/api/v1/namespaces/test-45dbpk-11/configmaps" latency="11.739276871s" userAgent="clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format" srcIP="35.224.156.164:52744" resp=500 statusStack="\ngoroutine 396873318 [running]:\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc0ec2272d0, 0x1f4)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:237 +0xcf\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc0ec2272d0, 0x1f4)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:216 +0x35\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc08b839ec0, 0x1f4)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:226 +0xb2\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.(*auditResponseWriter).WriteHeader(0xc5baf10690, 0x1f4)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/audit.go:223 +0x65\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.(*ResponseWriterDelegator).WriteHeader(0xc442314900, 0x1f4)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:571 +0x45\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.(*deferredResponseWriter).Write(0xc1068d9900, 0xc3edc28d80, 0xfb, 0x47e, 0x0, 0x0, 0x0)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:204 +0x1f7\nencoding/json.(*Encoder).Encode(0xc1cb7a4ac0, 0x49d6760, 0xc750fd5360, 0x0, 0x40f9fb)\n\t/usr/local/go/src/encoding/json/stream.go:231 +0x1cb\nk8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0xc000e02140, 0x52b72e0, 0xc750fd5360, 0x52a6540, 0xc1068d9900, 0x0, 0x0)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:327 +0x2e9\nk8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc000e02140, 0x52b72e0, 0xc750fd5360, 0x52a6540, 0xc1068d9900, 0x3bad339, 0x6)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:301 +0x169\nk8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode(0xc750fd5540, 0x52b72e0, 0xc750fd5360, 0x52a6540, 0xc1068d9900, 0x0, 0x0)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:228 +0x396\nk8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc750fd5540, 0x52b72e0, 0xc750fd5360, 0x52a6540, 0xc1068d9900, 0x530c420, 0xc000e02140)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:184 +0x170\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x4a991c8, 0x10, 0x7fc0c5d422d0, 0xc750fd5540, 0x530cce0, 0xc097251750, 0xc743056300, 0x1f4, 0x52b72e0, 0xc750fd5360)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:96 +0x12c\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x5310760, 0xc000f73380, 0x5310aa0, 0x74f3dd0, 0x0, 0x0, 0x4a7b8db, 0x2, 0x530cce0, 0xc097251750, ...)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:253 +0x572\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.ErrorNegotiated(0x52a5da0, 0xc750fd52c0, 0x5310760, 0xc000f73380, 0x0, 0x0, 0x4a7b8db, 0x2, 0x530cce0, 0xc097251750, ...)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:272 +0x16f\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.(*RequestScope).err(...)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernete
s/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:103\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.createHandler.func1(0x530cce0, 0xc097251750, 0xc743056300)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.i
o/apiserver/pkg/endpoints/handlers/create.go:187 +0x1ba5\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints.restfulCreateResource.func1(0xc442314840, 0xc45ae703f0)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/
endpoints/installer.go:1202 +0xe4\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc442314840, 0xc45ae703f0)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics
/metrics.go:449 +0x2d5\nk8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc000c26090, 0x530cc20, 0xc61cc5c408, 0xc743056300)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/conta
iner.go:288 +0xa84\nk8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(...)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:199\nk8s.io/kubernetes/vendor/k8s.io/apiserv
er/pkg/server.director.ServeHTTP(0x4a92b0f, 0xe, 0xc000c26090, 0xc00037a000, 0x530cc20, 0xc61cc5c408, 0xc743056300)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:146 +0x5de\nk8s.io/kubernetes/vendor
/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc005660c80, 0x530cc20, 0xc61cc5c408, 0xc743056300)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:121 +0x183\nk8s.io/k
ubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc183a95940, 0x530cc20, 0xc61cc5c408, 0xc743056300)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x47a\nk8s.
io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc00812e070, 0x530cc20, 0xc61cc5c408, 0xc743056300)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x8
c\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x4a96056, 0xf, 0xc00537b560, 0xc00812e070, 0x530cc20, 0xc61cc5c408, 0xc743056300)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handl
er.go:154 +0x87f\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1(0x530cc20, 0xc61cc5c408, 0xc743056300)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filterlatenc
y/filterlatency.go:95 +0x165\nnet/http.HandlerFunc.ServeHTTP(0xc0081248a0, 0x530cc20, 0xc61cc5c408, 0xc743056300)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x530cc20, 0xc61c
c5c408, 0xc743056300)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x59a\nnet/http.HandlerFunc.ServeHTTP(0xc0080e5600, 0x530cc20, 0xc61cc5c408, 0xc743056300)\n\t/usr/local/go/s
rc/net/http/server.go:2042 +0x44\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1(0x530cc20, 0xc61cc5c408, 0xc743056300)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoint
s/filterlatency/filterlatency.go:71 +0x186\nnet/http.HandlerFunc.ServeHTTP(0xc0080e5640, 0x530cc20, 0xc61cc5c408, 0xc743056300)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1(
0x530cc20, 0xc61cc5c408, 0xc743056300)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:95 +0x165\nnet/http.HandlerFunc.ServeHTTP(0xc0081248d0, 0x530cc20, 0xc61cc5c408, 0xc743056
300)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPriorityAndFairness.func1.4()\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/pri
ority-and-fairness.go:132 +0x3c6\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol.(*configController).Handle.func2()\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_filter.go:151 +0x
1aa\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol.immediateRequest.Finish(...)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go:647\nk8s.io/kubernetes/vendor/k8s.io/a
piserver/pkg/util/flowcontrol.(*configController).Handle(0xc00015fb80, 0x53130a0, 0xc4544d4390, 0xc1984bce70, 0x5313d60, 0xc17b0c9140, 0xc2c122d9d0, 0xc2c122d9e0, 0xc37d132cc0)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserv
er/pkg/util/flowcontrol/apf_filter.go:141 +0x86a\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPriorityAndFairness.func1(0x530cc20, 0xc61cc5c408, 0xc3ee029f00)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apis
erver/pkg/server/filters/priority-and-fairness.go:135 +0x5c3\nnet/http.HandlerFunc.ServeHTTP(0xc008124900, 0x530cc20, 0xc61cc5c408, 0xc3ee029f00)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency.tra
ckStarted.func1(0x530cc20, 0xc61cc5c408, 0xc3ee029f00)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:71 +0x186\nnet/http.HandlerFunc.ServeHTTP(0xc0080e5680, 0x530cc20, 0xc61cc
5c408, 0xc3ee029f00)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1(0x530cc20, 0xc61cc5c408, 0xc3ee029f00)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubern
etes/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:95 +0x165\nnet/http.HandlerFunc.ServeHTTP(0xc008124930, 0x530cc20, 0xc61cc5c408, 0xc3ee029f00)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endp
oints/filters.WithImpersonation.func1(0x530cc20, 0xc61cc5c408, 0xc3ee029f00)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x23dd\nnet/http.HandlerFunc.ServeHTTP(0xc0080e56c0, 0
x530cc20, 0xc61cc5c408, 0xc3ee029f00)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1(0x530cc20, 0xc61cc5c408, 0xc3ee029f00)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/sr
c/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:71 +0x186\nnet/http.HandlerFunc.ServeHTTP(0xc0080e5700, 0x530cc20, 0xc61cc5c408, 0xc3ee029f00)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/kubernetes/vendor/k8s.io/api
server/pkg/endpoints/filterlatency.trackCompleted.func1(0x530cc20, 0xc61cc5c408, 0xc3ee029f00)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:95 +0x165\nnet/http.HandlerFunc.Se
rveHTTP(0xc008124960, 0x530cc20, 0xc61cc5c408, 0xc3ee029f00)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAudit.func1(0x7fc0c5aec5f8, 0xc61cc5c400, 0xc3ee029d00)\n\t/go/src/k8s.io/kubernetes/_outp
ut/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/audit.go:110 +0x4bc\nnet/http.HandlerFunc.ServeHTTP(0xc0080e5740, 0x7fc0c5aec5f8, 0xc61cc5c400, 0xc3ee029d00)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/kubernetes/vendor
/k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1(0x7fc0c5aec5f8, 0xc61cc5c400, 0xc3ee029d00)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:71 +0x186\nnet/http.
HandlerFunc.ServeHTTP(0xc0080e5780, 0x7fc0c5aec5f8, 0xc61cc5c400, 0xc3ee029d00)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency.trackCompleted.func1(0x7fc0c5aec5f8, 0xc61cc5c400, 0xc3ee029d00)\n\t/
go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:95 +0x165\nnet/http.HandlerFunc.ServeHTTP(0xc0081249c0, 0x7fc0c5aec5f8, 0xc61cc5c400, 0xc3ee029d00)\n\t/usr/local/go/src/net/http/ser
ver.go:2042 +0x44\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7fc0c5aec5f8, 0xc61cc5c400, 0xc3ee029b00)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/
authentication.go:70 +0x6d2\nnet/http.HandlerFunc.ServeHTTP(0xc0080d4dc0, 0x7fc0c5aec5f8, 0xc61cc5c400, 0xc3ee029b00)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency.trackStarted.func1(0x7fc0c5aec5
f8, 0xc61cc5c400, 0xc3ee029900)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filterlatency/filterlatency.go:80 +0x38a\nnet/http.HandlerFunc.ServeHTTP(0xc0080e5800, 0x7fc0c5aec5f8, 0xc61cc5c400, 0xc3ee02990
0)\n\t/usr/local/go/src/net/http/server.go:2042 +0x44\nk8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc5a65a1380, 0xc00812c3e0, 0x5313e60, 0xc61cc5c400, 0xc3ee029900)\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src
/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:111 +0xb8\ncreated by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP\n\t/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/
apiserver/pkg/server/filters/timeout.go:97 +0x1cc\n" addedInfo="\nlogging error output: \"{\\\"kind\\\":\\\"Status\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"metadata\\\":{},\\\"status\\\":\\\"Failure\\\",\\\"message\\\":\\\"Internal error occurred: resource quota evaluation
timed out\\\",\\\"reason\\\":\\\"InternalError\\\",\\\"details\\\":{\\\"causes\\\":[{\\\"message\\\":\\\"resource quota evaluation timed out\\\"}]},\\\"code\\\":500}\\n\"\n"
```

Resource quota evaluation took ~10s for some reason. This repeats for many different configmaps and secrets.

**Comment by mborsz** [comment]
The kube-apiserver has been restarted by kubelet:

```
I0103 18:15:20.284940    2858 prober.go:117] Liveness probe for "kube-apiserver-gce-scale-cluster-master_kube-system(7358e0f81c70bb1ddefe5fc4ba6a8a62):kube-apiserver" failed (failure): Get "https://127.0.0.1:443/livez?exclude=etcd&exclude=kms-provider-0&exclude=kms-provider-1": context deadline exceeded
I0103 18:15:35.285431    2858 prober.go:117] Liveness probe for "kube-apiserver-gce-scale-cluster-master_kube-system(7358e0f81c70bb1ddefe5fc4ba6a8a62):kube-apiserver" failed (failure): Get "https://127.0.0.1:443/livez?exclude=etcd&exclude=kms-provider-0&exclude=kms-provider-1": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
I0103 18:15:35.287528    2858 kuberuntime_manager.go:656] Container "kube-apiserver" ({"containerd" "b2e53f30756f161ff4ee75bd8a703590806e2574b9f87c390b992154a1b61fe9"}) of pod kube-apiserver-gce-scale-cluster-master_kube-system(7358e0f81c70bb1ddefe5fc4ba6a8a62): Container kube-apiserver failed liveness probe, will be restarted
```

but issues with kube-apiserver started earlier, e.g.:

```
E0103 18:13:22.828234    2858 controller.go:187] failed to update lease, error: Put "https://35.231.217.12/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/gce-scale-cluster-master?timeout=10s": context deadline exceeded
```

**Comment by mborsz** [comment]
event-etcd seems to be overloaded that time:

```
I0103 18:13:04.871727      11 trace.go:205] Trace[261126121]: "Create" url:/api/v1/namespaces/test-45dbpk-12/events,user-agent:kubelet/v1.21.0 (linux/amd64) kubernetes/fdefde7,client:10.40.0.97,accept:application/vnd.kubernetes.protobuf,application/json,protocol:HTTP/2.0 (03-Jan-2021 18:12:58.460) (total time: 6411ms):
Trace[261126121]: ---"Object stored in database" 6410ms (18:13:00.871)
Trace[261126121]: [6.411013914s] [6.411013914s] END
I0103 18:13:04.872005      11 httplog.go:89] "HTTP" verb="POST" URI="/api/v1/namespaces/test-45dbpk-12/events" latency="9.897406605s" userAgent="kubelet/v1.21.0 (linux/amd64) kubernetes/fdefde7" srcIP="10.40.0.97:40980" resp=201
```
