### ISSUE TITLE
io.fabric8.kubernetes.client.KubernetesClientException: too old resource version

### ISSUE THREAD

**Issue by johnhec** [kubernetes/kubernetes#98564]
Experiencing repeated "too old resource version" onClose() exceptions in a Watcher object. The resource being watched, a Job, runs for several hours but (typically) after 80-100 minutes I always encounter a "too old resource version" exception. I re-create the Watch object, but after another period (35 minutes in one case) I encounter another "too old resource version" exception.

I keep re-creating the Watch object until the underlying Job completes.

The exception stack is as follows: -
2021-01-26 06:28:17 ERROR EngineWatcher:87 - too old resource version: 51780364 (52677017)
io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 51780364 (52677017)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:257)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
-----
What is the cause of this problem and how can I solve it

**Comment by neolit123** [comment]
please try the support channels or the repository of the Java client:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
https://github.com/kubernetes-client/java

/close
