### ISSUE TITLE
NPE in daemonset storage unit test in bbolt.(*Tx).Bucket(...)

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#98784]
**Which jobs are flaking**:

bazel-test

**Which test(s) are flaking**:

**Testgrid link**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/98781/pull-kubernetes-bazel-test/1357499406772867072

**Reason for failure**:

Panic in bbolt in a test framework (this could be a more significant underlying issue)

```
FAIL: //pkg/registry/apps/daemonset/storage:go_default_test (see /bazel-scratch/.cache/bazel/_bazel_root/7989b31489f31aee54f32688da2f0120/execroot/io_k8s_kubernetes/bazel-out/k8-fastbuild/testlogs/pkg/registry/apps/daemonset/storage/go_default_test/test.log)
INFO: From Testing //pkg/registry/apps/daemonset/storage:go_default_test:
==================== Test output for //pkg/registry/apps/daemonset/storage:go_default_test:
WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
	A future release of golang/protobuf will delete this package,
	which has long been excluded from the compatibility promise.
I0205 01:34:02.267412  135440 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{unix://localhost:5376030012499857450  <nil> 0 <nil>}]
I0205 01:34:02.272664  135440 client.go:360] parsed scheme: "endpoint"
I0205 01:34:02.272742  135440 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{unix://localhost:5376030012499857450  <nil> 0 <nil>}]
I0205 01:34:02.277673  135440 client.go:360] parsed scheme: "endpoint"
I0205 01:34:02.277751  135440 endpoint.go:68] ccResolverWrapper: sending new addresses to cc: [{unix://localhost:5376030012499857450  <nil> 0 <nil>}]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2584e06]
goroutine 1116 [running]:
k8s.io/kubernetes/vendor/go.etcd.io/bbolt.(*Tx).Bucket(...)
	vendor/go.etcd.io/bbolt/tx.go:101
k8s.io/kubernetes/vendor/go.etcd.io/etcd/mvcc/backend.(*concurrentReadTx).UnsafeRange(0xc0010ff4a0, 0x432041e, 0x3, 0x3, 0xc001292920, 0x11, 0x12, 0x0, 0x0, 0x0, ...)
	vendor/go.etcd.io/etcd/mvcc/backend/read_tx.go:195 +0x7a6
k8s.io/kubernetes/vendor/go.etcd.io/etcd/mvcc.(*storeTxnRead).rangeKeys(0xc0010ff4d0, 0xc000903c80, 0x1d, 0x20, 0x0, 0x0, 0x0, 0xd, 0x0, 0x2, ...)
	vendor/go.etcd.io/etcd/mvcc/kvstore_txn.go:147 +0x4f8
k8s.io/kubernetes/vendor/go.etcd.io/etcd/mvcc.(*storeTxnRead).Range(0xc0010ff4d0, 0xc000903c80, 0x1d, 0x20, 0x0, 0x0, 0x0, 0x0, 0x2, 0x441900, ...)
	vendor/go.etcd.io/etcd/mvcc/kvstore_txn.go:51 +0xea
k8s.io/kubernetes/vendor/go.etcd.io/etcd/mvcc.(*metricsTxnWrite).Range(0xc0010ff500, 0xc000903c80, 0x1d, 0x20, 0x0, 0x0, 0x0, 0x0, 0x2, 0x47ff00, ...)
	vendor/go.etcd.io/etcd/mvcc/metrics_txn.go:37 +0x132
k8s.io/kubernetes/vendor/go.etcd.io/etcd/mvcc.(*readView).Range(0xc00106ea80, 0xc000903c80, 0x1d, 0x20, 0x0, 0x0, 0x0, 0x0, 0x2, 0x7fbef3ec0000, ...)
	vendor/go.etcd.io/etcd/mvcc/kv_view.go:39 +0x1e2
k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/api/v3rpc.(*serverWatchStream).sendLoop(0xc0010e2240)
	vendor/go.etcd.io/etcd/etcdserver/api/v3rpc/watch.go:395 +0x322
k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/api/v3rpc.(*watchServer).Watch.func1(0xc0010e2240)
	vendor/go.etcd.io/etcd/etcdserver/api/v3rpc/watch.go:180 +0x39
created by k8s.io/kubernetes/vendor/go.etcd.io/etcd/etcdserver/api/v3rpc.(*watchServer).Watch
	vendor/go.etcd.io/etcd/etcdserver/api/v3rpc/watch.go:179 +0x379
================================================================================
```

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

**Comment by pacoxu** [comment]
etcd-io/etcd#12441 is opened for a similar trace for etcd 3.4.13.

**Comment by BenTheElder** [comment]
another occurrence on https://github.com/kubernetes/kubernetes/pull/99553
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99553/pull-kubernetes-bazel-test/1366080819080204288

**Comment by BenTheElder** [comment]
not sure if this was actually fixed but I'm not finding it in go.k8s.io/triage
it looks like it was not intentionally fixed in kubernetes or etcd, but we haven't encountered it recently
