### ISSUE TITLE
kubelet's volumemanager locked when upgrade k8s cluster

### ISSUE THREAD

**Issue by chenyw1990** [kubernetes/kubernetes#99188]
#### What happened:
kubelet's volumemanager locked when upgrade k8s cluster

Our Kubernetes cluster is installed on Bare Metal Server, and some pods on the nodes use CSI PVs,
Our k8s cluster upgrade processes is:

1. Upgrade Kubelet 
2. Stop etcd、haproxy、kube-apiserver、keepalived、kube-controller-manager、kube-scheduler by move the manifest files out of the monitoring directory of kubelet
3. Upgrade static pod of haproxy、keepalived and etcd 
4. Upgrade static pod of kube-apiserver、kube-controller and kube-scheduler

Problem: 
After the manifest file of kube-apiserver is placed in the monitoring directory of kubelet, the container of kube-apiserver is not created. 
kubelet will panic after a long time. I found that a deadlock occurred on kubelet in volumemanager.

The key logs are as follows:
volumemanager locked at WaitForCacheSync

```
E0128 09:49:52.614838  119469 csi_plugin.go:287] Failed to initialize CSINode: error updating CSINode annotation: timed out waiting for the condition; caused by: an error on the server ("") has prevented the request from succeeding (get csinodes.storage.k8s.io paas-192-168-2-2)
F0128 09:49:52.614847  119469 csi_plugin.go:301] Failed to initialize CSINode after retrying: timed out waiting for the condition
goroutine 820 [running]:

goroutine 962 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.WaitFor(0x4002a4d380, 0x400253aec8, 0x40020a3200, 0x0, 0x0)
	/usr1/workspace/CloudCore_PaaSLite_KUBERNETES_CSPEDGE_21_2_0_B060_ARM/src/k8s.io/kubernetes_build/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:539 +0xcc
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.PollUntil(0x5f5e100, 0x400253aec8, 0x40001160c0, 0x0, 0x0)
	/usr1/workspace/CloudCore_PaaSLite_KUBERNETES_CSPEDGE_21_2_0_B060_ARM/src/k8s.io/kubernetes_build/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:492 +0x9c
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.PollImmediateUntil(0x5f5e100, 0x400253aec8, 0x40001160c0, 0x45d3c8, 0x400253aec8)
	/usr1/workspace/CloudCore_PaaSLite_KUBERNETES_CSPEDGE_21_2_0_B060_ARM/src/k8s.io/kubernetes_build/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:511 +0x9c
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.WaitForCacheSync(0x40001160c0, 0x400253af40, 0x1, 0x1, 0x400253afd8)
	/usr1/workspace/CloudCore_PaaSLite_KUBERNETES_CSPEDGE_21_2_0_B060_ARM/src/k8s.io/kubernetes_build/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:255 +0x68
k8s.io/kubernetes/pkg/kubelet.(*kubeletVolumeHost).WaitForCacheSync(0x40013103c0, 0x4626e20, 0x40013103c0)
	/usr1/workspace/CloudCore_PaaSLite_KUBERNETES_CSPEDGE_21_2_0_B060_ARM/src/k8s.io/kubernetes_build/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volume_host.go:179 +0x5c
k8s.io/kubernetes/pkg/volume/csi.(*csiPlugin).skipAttach(0x4000d6e140, 0x4001d0d180, 0x11, 0x0, 0x0, 0x0)
	/usr1/workspace/CloudCore_PaaSLite_KUBERNETES_CSPEDGE_21_2_0_B060_ARM/src/k8s.io/kubernetes_build/_output/local/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_plugin.go:757 +0x190
k8s.io/kubernetes/pkg/volume/csi.(*csiPlugin).CanAttach(0x4000d6e140, 0x4003495840, 0x4000d6e140, 0xffff78639348, 0x4000d6e140)
	/usr1/workspace/CloudCore_PaaSLite_KUBERNETES_CSPEDGE_21_2_0_B060_ARM/src/k8s.io/kubernetes_build/_output/local/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_plugin.go:589 +0x98
k8s.io/kubernetes/pkg/volume.(*VolumePluginMgr).FindAttachablePluginBySpec(0x40013103c8, 0x4003495840, 0x0, 0x0, 0x40013103c8, 0x40bb710)
	/usr1/workspace/CloudCore_PaaSLite_KUBERNETES_CSPEDGE_21_2_0_B060_ARM/src/k8s.io/kubernetes_build/_output/local/go/src/k8s.io/kubernetes/pkg/volume/plugins.go:900 +0x9c
k8s.io/kubernetes/pkg/kubelet/volumemanager/cache.(*desiredStateOfWorld).isAttachableVolume(0x4000c0f1d0, 0x4003495840, 0x45f7e40)
	/usr1/workspace/CloudCore_PaaSLite_KUBERNETES_CSPEDGE_21_2_0_B060_ARM/src/k8s.io/kubernetes_build/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/cache/desired_state_of_world.go:456 +0x34
k8s.io/kubernetes/pkg/kubelet/volumemanager/cache.(*desiredStateOfWorld).AddPodToVolume(0x4000c0f1d0, 0x4000cbe090, 0x24, 0x4000ed8480, 0x4003495840, 0x400171d010, 0xe, 0x0, 0x0, 0x0, ...)
	/usr1/workspace/CloudCore_PaaSLite_KUBERNETES_CSPEDGE_21_2_0_B060_ARM/src/k8s.io/kubernetes_build/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/cache/desired_state_of_world.go:253 +0x1a4
k8s.io/kubernetes/pkg/kubelet/volumemanager/populator.(*desiredStateOfWorldPopulator).processPodVolumes(0x400136e360, 0x4000ed8480, 0x400253b9d8, 0x400253b9a8)
	/usr1/workspace/CloudCore_PaaSLite_KUBERNETES_CSPEDGE_21_2_0_B060_ARM/src/k8s.io/kubernetes_build/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go:343 +0x578
k8s.io/kubernetes/pkg/kubelet/volumemanager/populator.(*desiredStateOfWorldPopulator).findAndAddNewPods(0x400136e360)
	/usr1/workspace/CloudCore_PaaSLite_KUBERNETES_CSPEDGE_21_2_0_B060_ARM/src/k8s.io/kubernetes_build/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go:223 +0x17c
k8s.io/kubernetes/pkg/kubelet/volumemanager/populator.(*desiredStateOfWorldPopulator).populatorLoop(0x400136e360)
	/usr1/workspace/CloudCore_PaaSLite_KUBERNETES_CSPEDGE_21_2_0_B060_ARM/src/k8s.io/kubernetes_build/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go:174 +0x28
k8s.io/kubernetes/pkg/kubelet/volumemanager/populator.(*desiredStateOfWorldPopulator).Run.func1(0x40023bbe58, 0x0, 0x0)
	/usr1/workspace/CloudCore_PaaSLite_KUBERNETES_CSPEDGE_21_2_0_B060_ARM/src/k8s.io/kubernetes_build/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go:153 +0x4c
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0x4003137f88, 0x4003137e00, 0x0, 0x0)
	/usr1/workspace/CloudCore_PaaSLite_KUBERNETES_CSPEDGE_21_2_0_B060_ARM/src/k8s.io/kubernetes_build/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:211 +0x6c
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.WaitFor(0x4000ccf2a0, 0x400253bf88, 0x400073c600, 0x0, 0x0)
	/usr1/workspace/CloudCore_PaaSLite_KUBERNETES_CSPEDGE_21_2_0_B060_ARM/src/k8s.io/kubernetes_build/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:541 +0xe8
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.PollUntil(0x5f5e100, 0x4001504f88, 0x40001160c0, 0x0, 0x0)
	/usr1/workspace/CloudCore_PaaSLite_KUBERNETES_CSPEDGE_21_2_0_B060_ARM/src/k8s.io/kubernetes_build/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:492 +0x9c
k8s.io/kubernetes/pkg/kubelet/volumemanager/populator.(*desiredStateOfWorldPopulator).Run(0x400136e360, 0x45348e0, 0x4000de0150, 0x40001160c0)
	/usr1/workspace/CloudCore_PaaSLite_KUBERNETES_CSPEDGE_21_2_0_B060_ARM/src/k8s.io/kubernetes_build/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go:151 +0xd4
created by k8s.io/kubernetes/pkg/kubelet/volumemanager.(*volumeManager).Run
	/usr1/workspace/CloudCore_PaaSLite_KUBERNETES_CSPEDGE_21_2_0_B060_ARM/src/k8s.io/kubernetes_build/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/volume_manager.go:278 +0x98
```

#### What you expected to happen:
The static pod can be created.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.19.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ehashman** [comment]
/sig storage

This bug doesn't seem to have enough details to reproduce or further investigate. You must include full kubelet logs and relevant Kubernetes manifests along with clear steps to reproduce so we can help with your issue.

Please re-open this bug once you have provided more information.

/triage needs-information
/close
